### ISSUE TITLE
Refactor GenomeLocParser and GenomeLoc

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#100]
Currently, in order to create a GenomeLoc, you need to create a GenomeLocParser, which requires either a reference fasta or a sequence dictionary for validation. Sometimes, however, you don't want this level of validation (perhaps you have already checked that the interval is within bounds, making the extra validation wasteful -- this happens in a few places in the new engine). There should be a way to instantiate a GenomeLoc directly, without the need to pass around a GenomeLocParser.

**Comment by akiezun** [comment]
@droazen can you clarify what still needs to be done for this ticket? unassign when clarified.

**Comment by droazen** [comment]
Closing -- this was addressed via `SimpleInterval`
