### ISSUE TITLE
Migrate from GATKGCSOptions to AuthHolder

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/gatk#1002]
We use the GATKGCSOptions class to hold GCP authentication. It inherits from the Dataflow hierarchy and works well there, but since it doesn't implement Serializable it's cumbersome to work with in Spark.

We've created AuthHolder as a replacement. It can do all the things GATKGCSOptions can do, and more  (well, except for holding Dataflow debug options but we don't need that anymore).

Once #978 is merged in, we need to migrate the code from GATKGCSOptions to AuthHolder. One benefit is that this will allow the Spark code to support client-secrets.json (for access to private GCS files, unlike the API key which only grants access to world-readable GCS files).

**Comment by akiezun** [comment]
@lbergelson is the auth authority here

**Comment by droazen** [comment]
Closing this one -- we now want to move away from `AuthHolder`
