### ISSUE TITLE
how to use GATK to call Somatic Indels 

### ISSUE THREAD

**Issue by WinterLi1993** [broadinstitute/gatk#1003]
HI，Author，@jean-philippe-martin 
    I find gatk older verison 1.6 have SomaticIndelDetector tool to call Somatic Indel . Am i right ?
And can you give me some usage information to tell me how to use it ?
I have tumor-normal paired bam files, I wanna use your GATK to call somatic Indel.

thank you very much !

**Comment by akiezun** [comment]
The tool you refer to has indeed been canceled. A new tool is being developed; it is called MuTect 2 and will be released soon as part of the next version of GATK. When it is ready, there will be an announcement here: http://gatkforums.broadinstitute.org/

That is also a good place to ask any questions about how to use the tools. This place here is only for questions about the software code of the tools.
