### ISSUE TITLE
Determine whether AddContextDataToReadSparkSharded could use a spark custom partitioner

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1007]
Currently `AddContextDataToReadSparkOptimized` avoids shuffles by doing its own sharding. This introduces a lot of additional complexity, and doesn't leverage the built-in support for sharding in spark. During a discussion today it came up that this code could potentially be made more idiomatic/spark-friendly by using a custom partitioner. Let's investigate whether this is possible and how easy a change it would be to make (and if it's workable and a simple change, put together a quick implementation).

Making `AddContextDataToReadSparkOptimized` more spark-idiomatic would allow it to compare more favorably from a stylistic standpoint against the broadcast-based approach when we do https://github.com/broadinstitute/gatk/issues/995

**Comment by droazen** [comment]
@tomwhite or @laserson, would one of you have time to look into this?

**Comment by laserson** [comment]
I'll take a look at this next week.

**Comment by laserson** [comment]
I think the `Optimized` version deals with avoiding replicating reads in a more nuanced manner, but if I understand correctly, it doesn't seem to me to avoid the shuffle.  It looks like it essentially ignores the concept of data locality entirely, and potentially transfers a lot of data over the network.  (Equivalent to performing a shuffle on a sorted file in HDFS.)

IMO, the current "shuffle" implementation is already a "Spark-y" way to do it, but with multiple inefficiencies:
* Reads/variants are keyed to their corresponding shards, replicating reads if they cross over shard boundaries.  This necessitates an `aggregateByKey` operation that potentially reshuffles the entire data set at the end to deal with neighboring shards that could be hashed to different machines.
* The impl uses `cogroup` and `groupByKey`, which require materializing all values for a key in memory (which could be large).  Best to avoid these if possible.
* And related to the previous issue, the join strategy for reads and variants is basically a cross-product-and-filter, which is not very efficient, especially considering that the data can be ordered.

I think the best implementation here would steal JP's method of sharding the reads/variants, but make use of `repartitionAndSortWithinPartition`, which lets you specify what partition to use and also sorts all the values within a given partition.  This means that we could employ a sort-merge on each partition, and only scan through the datasets once after shuffling them.

Do you already have an impl for doing a sort-merge of `Locatable`s?  These can be a bit tricky.  I wrote one for the `ShuffleRegionJoin` impl in ADAM, but there are semantic differences that would make it less efficient to use. (Specifically, it would require the `aggregateByKey` operation and also creating `SimpleInterval`-style objects from a separate model.)

Finally, I would also add the ability to specify which join strategy to use separately for the reference bases and the variants.

**Comment by laserson** [comment]
Also note discussion in #987

**Comment by droazen** [comment]
Thanks for the analysis @laserson! Not sure I fully understand it yet, but will re-read it until I do :) By tomorrow I should have plots for https://github.com/broadinstitute/gatk/issues/995 comparing JP's existing code against the broadcast approach, and will link them here -- let's decide whether or not to devote more effort to refactoring JP's code after seeing those numbers.

In the meantime, recommend focusing on https://github.com/broadinstitute/gatk/issues/1015, which is probably the most urgent blocking issue for spark at the moment.

**Comment by laserson** [comment]
@droazen Could you also compare JP's code against the shuffle approach?

**Comment by droazen** [comment]
This is something to explore for beta

**Comment by droazen** [comment]
Closing as obsolete
