### ISSUE TITLE
CollectInsertSizeMetrics in Spark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1012]
the goal is to reproduce the results from Picard.

**Comment by akiezun** [comment]
@wbrockman feel free to grab this one if you're working on it

**Comment by akiezun** [comment]
@SHuang-Broad is this now done by your new code?

**Comment by SHuang-Broad** [comment]
@akiezun Yes, the tool is written and waiting for review. Please see #1566. It's not a complete rewrite (some filters not included yet, but adding them will be easy).

**Comment by akiezun** [comment]
this is closed
