### ISSUE TITLE
Design and implement a replacement for active region traversal

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#103]

**Comment by akiezun** [comment]
needs to be done whether we're dataflowing or not

**Comment by droazen** [comment]
alpha-1

**Comment by droazen** [comment]
Nominally assigned to me, but I'd like to work collaboratively with @lbergelson on this one, in consultation with HaplotypeCaller experts like @ldgauthier, as the design issues here definitely call for multiple points of view and careful requirements gathering.

**Comment by droazen** [comment]
Need to take into account issues like this: https://github.com/broadinstitute/gatk/issues/267

**Comment by droazen** [comment]
Done for alpha-1 purposes in https://github.com/broadinstitute/gatk/pull/1567 -- closing!
