### ISSUE TITLE
profile and optimize BaseRecalibrator

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1032]
the goal is to be at least same as gatk3.4 on single thread. This is for the walker version of the tool.
The ticket can be split into a) profile and b) optimize if needed

**Comment by droazen** [comment]
@lbergelson and I will take the BQSR profiling

**Comment by akiezun** [comment]
do you want to grab #1033 too?

**Comment by droazen** [comment]
Some initial results:

Using the following inputs:

    Reference: `/seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta`
    Bam: `/humgen/gsa-hpprojects/NA12878Collection/bams/CEUTrio.HiSeq.WGS.b37.NA12878.bam` (~350GB)
    Known Sites: `/humgen/gsa-hpprojects/dev/droazen/dbsnp_135.b37.excluding_sites_after_129.vcf` (~2 GB)

Running BQSR on the interval `1:10000000-20000000`, the GATK4 version appears to be ~5% faster:

    GATK 3.4-46-gbc02625: real 7m8.025s   user 10m47.397s   sys 1m47.758s
    Hellbender: real 6m45.652s  user 7m36.879s  sys 0m6.915s

However, running on the larger interval `1:1-20000000`, the GATK4 version is consistently ~10% slower:

    GATK 3.4-46-gbc02625: real 11m24.830s  user	 16m24.834s  sys 1m6.492s
                                            real 11m17.787s  user	 16m35.280s   sys 1m44.019s
    Hellbender: real 12m40.197s  user 13m54.710s  sys 0m9.322s
                        real 12m18.393s  user 13m31.382s  sys 0m8.499s

Will have to do some more digging in the profiler to figure out why this is the case.

**Comment by droazen** [comment]
The Feature caching does not appear to be the culprit, as with the Feature cache size increased from 1000 bases to 10000 bases, hellbender still took `12m29.527s` on the  `1:1-20000000` interval.

**Comment by droazen** [comment]
Next I set out to determine whether hellbender is slowing down on the larger interval simply because there is more data / a longer traversal, or because it's slower at processing the `1:1-10000000` interval than the `1:10000000-20000000` interval. And surprisingly, it appears that the latter is the case:

Time to process the `1:1-10000000` interval across two runs:

    GATK3: 5m25.983s  5m31.913s
    HB: 6m2.156s   5m59.804s

(Recall that HB was ~5% faster than GATK3 at processing the `1:10000000-20000000` interval)

Moreover, our newly-installed progress meter shows that the rate at which we process records is unusually low at the start of the `1:1-10000000` interval, but is consistent throughout the processing of the `1:10000000-20000000` interval:

HB processing rate over 1:1-10000000:

    14:22:19.520 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
    14:22:29.522 INFO  ProgressMeter -             1:769026              0.2                133000         797920.2
    14:22:39.531 INFO  ProgressMeter -            1:1066133              0.3                298000         893553.2
    14:22:49.544 INFO  ProgressMeter -            1:1389358              0.5                471000         941247.0
    14:22:59.572 INFO  ProgressMeter -            1:1695902              0.7                636000         952785.2
    14:23:09.601 INFO  ProgressMeter -            1:1961884              0.8                808000         968031.8
    14:23:19.636 INFO  ProgressMeter -            1:2264803              1.0                985000         983099.3
    14:23:29.637 INFO  ProgressMeter -            1:2583326              1.2               1162000         994352.2
    14:23:39.694 INFO  ProgressMeter -            1:2817177              1.3               1297000         970638.9
    14:23:49.705 INFO  ProgressMeter -            1:3095124              1.5               1467000         975993.8
    14:23:59.726 INFO  ProgressMeter -            1:3372416              1.7               1637000         980190.6
    14:24:09.734 INFO  ProgressMeter -            1:3678706              1.8               1810000         985355.8
    14:24:19.777 INFO  ProgressMeter -            1:4087198              2.0               1984000         989880.0
    14:24:29.813 INFO  ProgressMeter -            1:4341518              2.2               2165000         996983.7
    14:24:39.822 INFO  ProgressMeter -            1:4598153              2.3               2350000        1004975.0
    14:24:49.834 INFO  ProgressMeter -            1:4859664              2.5               2530000        1009892.7
    14:24:59.838 INFO  ProgressMeter -            1:5103960              2.7               2712000        1014982.7
    14:25:09.887 INFO  ProgressMeter -            1:5341742              2.8               2889000        1017450.6
    14:25:19.925 INFO  ProgressMeter -            1:5599552              3.0               3076000        1023037.2
    14:25:29.961 INFO  ProgressMeter -            1:5841197              3.2               3259000        1026774.7
    14:25:39.979 INFO  ProgressMeter -            1:6103914              3.3               3442000        1030235.6
    14:25:50.017 INFO  ProgressMeter -            1:6402855              3.5               3630000        1034694.1
    14:26:00.050 INFO  ProgressMeter -            1:6700345              3.7               3815000        1037954.0
    14:26:10.050 INFO  ProgressMeter -            1:6953845              3.8               4008000        1043161.4
    14:26:20.094 INFO  ProgressMeter -            1:7202715              4.0               4191000        1045250.1
    14:26:30.135 INFO  ProgressMeter -            1:7440529              4.2               4368000        1045747.5
    14:26:40.182 INFO  ProgressMeter -            1:7704929              4.3               4546000        1046412.6
    14:26:50.246 INFO  ProgressMeter -            1:7943120              4.5               4721000        1046297.7
    14:27:00.269 INFO  ProgressMeter -            1:8191836              4.7               4903000        1047839.9
    14:27:10.295 INFO  ProgressMeter -            1:8443081              4.8               5076000        1047407.8
    14:27:20.317 INFO  ProgressMeter -            1:8693600              5.0               5267000        1050608.9
    14:27:30.363 INFO  ProgressMeter -            1:8947934              5.2               5462000        1054294.3
    14:27:40.417 INFO  ProgressMeter -            1:9199287              5.3               5639000        1054360.3
    14:27:50.420 INFO  ProgressMeter -            1:9454308              5.5               5811000        1053671.8
    14:28:00.434 INFO  ProgressMeter -            1:9724703              5.7               5994000        1054928.8
    14:28:10.442 INFO  ProgressMeter -            1:9997608              5.8               6184000        1057329.0

Whereas for the `1:10000000-20000000` interval we reach our max records/minute rate from the beginning and sustain it throughout:

    11:59:25.779 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
    11:59:35.800 INFO  ProgressMeter -           1:10238878              0.2                179000        1071856.3
    11:59:45.815 INFO  ProgressMeter -           1:10479871              0.3                365000        1093032.5
    11:59:55.820 INFO  ProgressMeter -           1:10734140              0.5                543000        1084517.8
    12:00:05.862 INFO  ProgressMeter -           1:11009535              0.7                720000        1077763.6
    12:00:15.906 INFO  ProgressMeter -           1:11266264              0.8                906000        1084445.5
    12:00:25.975 INFO  ProgressMeter -           1:11519786              1.0               1088000        1084457.4
    12:00:36.005 INFO  ProgressMeter -           1:11779127              1.2               1264000        1079941.9
    12:00:46.045 INFO  ProgressMeter -           1:12038732              1.3               1440000        1076420.9
    12:00:56.072 INFO  ProgressMeter -           1:12294624              1.5               1617000        1074501.9
    12:01:06.118 INFO  ProgressMeter -           1:12547820              1.7               1818000        1087125.5
    12:01:16.130 INFO  ProgressMeter -           1:12796451              1.8               2002000        1088526.6
    12:01:26.168 INFO  ProgressMeter -           1:13176986              2.0               2170000        1081494.2
    ....
    etc.

I can only conclude that there's something about the start of chromosome 1 that is slowing HB down. Next step is to profile HB during traversal of that region.

**Comment by akiezun** [comment]
@droazen I'll grab this one. I'm doing the indel ripping out anyway and staring at the profiler for BaseRecalibrator. Grab back if you want it.

**Comment by droazen** [comment]
@akiezun It's all yours

**Comment by akiezun** [comment]
on the latest code on this region 1:1-20Mb we win but not by much, surprisingly:

```
GATK3 real	12m42.092s user	17m45.471s
GATK4 real	12m17.327s user	13m15.677s
```

closing this ticket though. mission accomplished.
