### ISSUE TITLE
profile and optimize ApplyBQSR

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1033]
the goal is to be at least same as gatk3.4 on single thread. This is for the walker version of the tool.
The ticket can be split into a) profile and b) optimize if needed

**Comment by akiezun** [comment]
Case1: 
chr10 of CEUTrio.HiSeq.WEx.b37.NA12892.bam from the gatk bundle, size 1.2Gb

running on Mac OS X 10.9.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17, local SSD

11.30 min GATK v3.4-46-gbc02625
9 min GATK4 .pre-alpha-51-ge098c21

time for GATK3
```
real	11m21.538s
user	17m24.320s
sys	0m8.073s
```

gatk4
```
real	9m7.691s
user	9m2.250s
sys	0m22.603s
```

**Comment by droazen** [comment]
Can you repeat this same test over an NFS filesystem from a Broad server?

**Comment by akiezun** [comment]
case 2, on NFS
ref `/humgen/1kg/reference/human_g1k_v37.fasta`
bam `/xchip/cga_home/akiezun/data/CEUTrio.HiSeq.WEx.b37.NA12892.chr10.bam --BQSR` (1.9Gb) 

Running on host dataflow01
Linux 2.6.32-573.3.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0-b132.

12.47 minutes GATK v3.4-46-gbc02625
11.8 minutes GATK 4.pre-alpha-45-g168cd60

gatk3 time
```
real	12m32.499s
user	18m58.643s
```

gatk4 time
```
real	11m49.027s
user	12m20.699s
```
