### ISSUE TITLE
implement per-target coverage collection in spark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1038]
It should be able to optionally split by read group or library or sample

**Comment by davidbenjamin** [comment]
@samuelklee is this issue still relevant?

**Comment by samuelklee** [comment]
@asmirnov239 will start working on unifying WES/WGS coverage collection in a Spark tool in the next couple of weeks.

**Comment by samuelklee** [comment]
Dupe of #3660.
