### ISSUE TITLE
Port native pairHMM on AVX from GATK3

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1040]
The requirements are:
- we need full source code in the repository and buildable from gradle and with unit tests
- all versions of the code, native or not, must produce exactly the same results every time and we much have tests that check that.

**Comment by akiezun** [comment]
@gspowley , should we close this given #1492  ?

**Comment by akiezun** [comment]
yes, let's

**Comment by droazen** [comment]
Re-opening -- the requirements for this ticket are not captured in the other ticket.

**Comment by droazen** [comment]
This one is done
