### ISSUE TITLE
Fix three remaining broken optical duplicate tests

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#1042]
The tests are:
- [x] `testOpticalDuplicateClusterSamePositionNoOpticalDuplicates`
- [x] `testOpticalDuplicateClusterSamePositionNoOpticalDuplicatesWithinPixelDistance`
- [x] `testStackOverFlowPairSetSwap`
in `MarkDuplicatesSparkIntegrationTest`

**Comment by lbergelson** [comment]
I suspect that many of the recently reactivated tests aren't so much fixed as they are temporarily avoided.  I think the ones that were disabled due to problems with unmapped reads will still have problems if we read from gcs since that still removes unmapped reads I think.

**Comment by droazen** [comment]
@davidadamsphd Is this still an issue? Will it be resolved as part of your validation efforts, or do we have to address it separately?

**Comment by droazen** [comment]
Since this is unassigned, assigning to @akiezun (who still needs more tickets) to evaluate whether this needs to be fixed for alpha.

**Comment by davidadamsphd** [comment]
It's unclear if this is still a practical issue. I compared our sample BAM using Picard and GATK4 with no difference in optical duplicates (up to ~1GB chunk of the BAM). I hadn't run into any issues yet, nor attempted to dig into this in more detail.

**Comment by akiezun** [comment]
I have a fix for `testStackOverFlowPairSetSwap` - see pull req #1156

**Comment by akiezun** [comment]
I have a fix for the other 2 in https://github.com/broadinstitute/gatk/pull/1161
