### ISSUE TITLE
Profile GATK4 walkers using inputs over NFS

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1046]
Profiling walkers using inputs from NFS filesystems could alter the profile of GATK4 vs. GATK3, as differences in the number of times we go to disk could be magnified by the slowness of NFS.

Task is to choose a representative set of walkers (one that takes reads, one that takes variants, and one that takes reads + a side input like -knownSites in BQSR that will trigger queries) and see if the profiles change at all when the inputs are in NFS. Do we still beat or match GATK3 in this case?

**Comment by droazen** [comment]
For @akiezun

**Comment by droazen** [comment]
I will take the BQSR part of this ticket

**Comment by droazen** [comment]
BQSR results over NFS are in a comment to https://github.com/broadinstitute/gatk/issues/1032

**Comment by akiezun** [comment]
I'm going to close this because it's a dup of the others. everyone should test on NFS i guess
