### ISSUE TITLE
restructure the Readme to make more useful for users

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1049]
the dev-oriented material such as coding conventions etc should be moved to a separate wiki page.
The main readme should have examples of how to install it, how to validate the installation and how run it locally, on spark cluster and on the cloud.

Candidate for alpha

**Comment by yegeniy** [comment]
Providing a reference to that wiki from the README would be helpful

**Comment by vdauwera** [comment]
FYI I'm planning a "GATK 4 Alpha" category for the forum + documentation guide to host the user-facing documentation, so feel free to keep the developer docs in the readme -- or we'll add a note in the readme pointing to the forum/guide pages.

**Comment by akiezun** [comment]
@vdauwera wouldn't it be simpler to have those docs on the github page?

**Comment by vdauwera** [comment]
I prefer to host the docs in the forum for the following reasons:

- We want people to use the GATK website and forum as a one-stop shop for all GATK needs, not have to go to Github for some things, both for convenience and as a matter of branding;
- Many end-users don't know/understand Github;
- In the forum we can easily host multiple documents in a way that's intuitive to navigate;
- We can easily render the docs as webpages within the GATK website, which many end-users prefer;
- Forum docs are easy for my team to update or tweak at a moment's notice;
- Users can comment directly on the documents, or create new discussion threads, and it's easier for us to answer them if all is in the same place. 
- If we need to open a github issue ticket (for bug report, feature request etc) we can do it directly from the forum discussion.

**Comment by lbergelson** [comment]
For what its worth, I know I always find it difficult to find things on the GATK forums.  A wiki is a much clearer way for me to navigate static information.  It's also easy for everyone to edit and has a clear history.

**Comment by vdauwera** [comment]
We have discussed this and I have shown @lbergelson the error of his ways ;)

Admittedly I'm still working on improving the presentation of content on the website -- but user feedback suggests they find the current site far superior to the old wiki. Also, I hate wikis.

Also also, Louis was mostly complaining about the dev zone and queue docs, which do suck.

**Comment by vdauwera** [comment]
But FYI, after discussion with Adam, I will add ability to respond to forum threads by email since it seems this is a must-have feature.

**Comment by droazen** [comment]
Closing -- we've refactored the README to make it more readable.
