### ISSUE TITLE
Add documentation about gsutil and gcloudto README

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1051]
Currently we have a dependency on having gcloud and gsutil installed and configured in a certain way, but we don't have any documentation about it.  

We're getting authentication partially from gcloud auth login, which is being propagated in a way I don't fully understand through the dataflow pipeline options.  

We need to understand exactly what's happening and then write an explanation of what a user needs to do to have it work.

**Comment by droazen** [comment]
beta

**Comment by droazen** [comment]
This is done.
