### ISSUE TITLE
ReadsSparkSource and ReadsSparkSink have different APIs

### ISSUE THREAD

**Issue by laserson** [broadinstitute/gatk#1062]
The `Source` version has a `JavaSparkContext` field, while the `Sink` version takes the `JavaSparkContext` as input into a static method.  Also, the `Sink` version has a `writeReads` that takes a `ReadsWriteFormat`, while the `Source` version doesn't have an overarching `get` method.  Also, what should the corresponding `enum` be called?  `ReadsReadFormat`?  `ReadsGetFormat`?

**Comment by laserson** [comment]
This is motivated by the fact that the `GATKSparkTool` doesn't have a good way to read ADAM data.

**Comment by droazen** [comment]
Hopefully this will be addressed as part of https://github.com/broadinstitute/gatk/issues/959

**Comment by laserson** [comment]
k, closing in favor of #959.
