### ISSUE TITLE
Expose mapred.max.split.size as a parameter to GATKSparkTool

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1064]
`mapred.max.split.size` is currently hardcoded to 10485760 in ReadsSparkSource.  It should be exposed as a parameter that can be set at the command line since different values are better for different tools.

It's a deprecated property, so it should probably be replaced with the new `mapreduce.input.fileinputformat.split.maxsize` instead.

**Comment by droazen** [comment]
So should we expose it, or should we replace it and expose the replacement? :)

**Comment by lbergelson** [comment]
I'm doing both!
