### ISSUE TITLE
Make all tools call into a common utility method to create SAMFileWriters

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1069]

**Comment by droazen** [comment]
Prerequisite for #121

**Comment by cmnbroad** [comment]
When this is integrated we should make sure that we require a reference for output CRAMs.

**Comment by droazen** [comment]
Please prioritize this ticket for this week, if possible, as it's related to some work I'm trying to get in before I leave for vacation.

**Comment by cmnbroad** [comment]
I've already started on it. Hopefully the CRAM PR will get merged in
quickly since these changes will conflict with the changes I made to all
the SamFileWriter creation code there.

**Comment by cmnbroad** [comment]
PR is https://github.com/broadinstitute/gatk/pull/1146

**Comment by droazen** [comment]
Thanks -- will review today

**Comment by droazen** [comment]
Done in https://github.com/broadinstitute/gatk/pull/1146 -- closing!
