### ISSUE TITLE
ReadThreadingAssemblerUnitTest contains identical tests with different names

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1081]
Intellij pointed out to me that these two tests were identical, but they sound like they're testing different things.  Are we missing an important test case?  

We should either fix whichever one isn't testing the thing it says it is, or delete one of them.

```
    @Test
    public void testStartInMiddleWithBubble() {
        final TestAssembler assembler = new TestAssembler(3);
        final String ref  = "CAAAATGGGG";
        final String read =   "AAATCGGG";
        assembler.addSequence(ref.getBytes(), true);
        assembler.addSequence(read.getBytes(), false);
        assertSingleBubble(assembler, ref, "CAAAATCGGG");
    }

    @Test
    public void testNoGoodStarts() {
        final TestAssembler assembler = new TestAssembler(3);
        final String ref  = "CAAAATGGGG";
        final String read =   "AAATCGGG";
        assembler.addSequence(ref.getBytes(), true);
        assembler.addSequence(read.getBytes(), false);
        assertSingleBubble(assembler, ref, "CAAAATCGGG");
    }
```

**Comment by akiezun** [comment]
@vruano can you advise here? is an important testcase missing? The code looks exactly the same in gatk3

**Comment by vruano** [comment]
git-blame says that this is quite old code by MdP 2013... and is difficult to recover the history since is before the maven refactoring. Here I would just apply amnesty and remove one of the tests; let's the lack of coverage do the talking. 

Of the two test method names ```testStartInMiddleWithBubble``` seems the most plausible one given the code but I'm not 100% sure about that.

**Comment by vruano** [comment]
@akiezun agreed?

**Comment by akiezun** [comment]
yes, will do
