### ISSUE TITLE
BaseRecalibratorSpark can't handle more than 1 knownSites file.

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1085]
BaseRecalibrator can take multiple feature files as known sites (the --knownSites argument). But BaseRecalibratorSpark can't and so BQSRPipelineSpark can't and ReadsPipelineSpark can't.

Once this is fixed, relevant tests should be reenabled

**Comment by akiezun** [comment]
this is a must fix - production uses multiple files

**Comment by droazen** [comment]
For alpha-1
