### ISSUE TITLE
Forward-port recent SelectVariants changes to GATK4

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1090]
https://github.com/broadinstitute/gsa-unstable/issues/1194
https://github.com/broadinstitute/gsa-unstable/issues/1060

(after https://github.com/broadinstitute/gatk/pull/792 is merged)

**Comment by cmnbroad** [comment]
The  VCF versioning part of this ticket (for broadinstitute/gsa-unstable#1060) will be dealt with in https://github.com/broadinstitute/gatk/issues/1116.

**Comment by akiezun** [comment]
@droazen @cmnbroad can you provide the pull request numbers (not issue numbers) here from gsa-unstable?

**Comment by cmnbroad** [comment]
Closing this ticket since the part referring to broadinstitute/gsa-unstable#1194 is fixed via #1115; the part referring to broadinstitute/gsa-unstable#1060 has been moved to a separate ticket #1116.
