### ISSUE TITLE
Profile SelectVariants against the GATK3 version

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1092]
After https://github.com/broadinstitute/gatk/pull/792 is merged, ensure that our version of `SelectVariants` is as fast or faster than the GATK3 version on typical inputs.

**Comment by droazen** [comment]
For @akiezun

**Comment by droazen** [comment]
Be sure to profile with a concordance/discordance track to make sure that querying auxiliary sources of variants in VariantWalkers is not more expensive in GATK4 than GATK3.

**Comment by droazen** [comment]
https://github.com/broadinstitute/gatk/pull/792 is merged, so this ticket is ready

**Comment by akiezun** [comment]
case1: local file CEUTrio.HiSeq.WGS.b37.bestPractices.b37.vcf 1.9G
commandline
```
-T SelectVariants -R /Users/akiezun/bin/reference/human_g1k_v37.fasta -V /Users/akiezun/bin/data/CEUTrio.HiSeq.WGS.b37.bestPractices.b37.vcf -select (vc.getGenotype("NA12878").getPhredScaledQual() >= 90 && vc.getGenotype("NA12891").getPhredScaledQual() >= 90 && vc.getGenotype("NA12892").getPhredScaledQual() >= 90) && ((vc.getGenotype("NA12878").isHomRef() && vc.getGenotype("NA12891").isHomRef() && vc.getGenotype("NA12892").isHomRef()) || (vc.getGenotype("NA12878").isHomVar() && vc.getGenotype("NA12891").isHomVar() && vc.getGenotype("NA12892").isHomVar()) || (vc.getGenotype("NA12878").isHet() && vc.getGenotype("NA12891").isHomRef() && vc.getGenotype("NA12892").isHomVar()) || (vc.getGenotype("NA12878").isHet() && vc.getGenotype("NA12891").isHomVar() && vc.getGenotype("NA12892").isHomRef())) --out selectVariants_phasingFilterTest_gatk3.vcf
```

**1m56.863s** on GATK 3.4-46-gbc02625
**1m24.934s** on GATK4.pre-alpha-100-g9200274

running on Mac OS X 10.9.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17.

time gatk3 
```
real	1m56.863s
user	1m58.199s
```

time gatk4
```
real	1m24.934s
user	1m33.709s
```

**Comment by akiezun** [comment]
case 2: file on NFS (same file as in case1)
CEUTrio.HiSeq.WGS.b37.bestPractices.b37.vcf 1.9G
(this is a 'long and skinny vcf - 3 samples, 6375842 variants)

Linux 2.6.32-573.3.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0-b132

```
-T SelectVariants -V /humgen/gsa-hpprojects/GATK/bundle/current/b37/CEUTrio.HiSeq.WGS.b37.bestPractices.b37.vcf -R /humgen/gsa-hpprojects/GATK/bundle/current/b37/human_g1k_v37.fasta -select (vc.getGenotype("NA12878").getPhredScaledQual() >= 90 && vc.getGenotype("NA12891").getPhredScaledQual() >= 90 && vc.getGenotype("NA12892").getPhredScaledQual() >= 90) && ((vc.getGenotype("NA12878").isHomRef() && vc.getGenotype("NA12891").isHomRef() && vc.getGenotype("NA12892").isHomRef()) || (vc.getGenotype("NA12878").isHomVar() && vc.getGenotype("NA12891").isHomVar() && vc.getGenotype("NA12892").isHomVar()) || (vc.getGenotype("NA12878").isHet() && vc.getGenotype("NA12891").isHomRef() && vc.getGenotype("NA12892").isHomVar()) || (vc.getGenotype("NA12878").isHet() && vc.getGenotype("NA12891").isHomVar() && vc.getGenotype("NA12892").isHomRef())) --out selectVariants_phasingFilterTest_gatk3.vcf
```

**2m58.899s** on GATK 3.4-46-gbc02625
**2m12.066s** GATK 4.pre-alpha-92-g9200274

time gat3
```
real	2m58.899s
user	3m44.438s
```

time gat4
```
real	2m12.066s
user	2m29.730s
```

**Comment by akiezun** [comment]
case3: different NFS file, 1.9 GB, different select expression (not using genotypes)

```
-T SelectVariants -R /humgen/gsa-hpprojects/GATK/bundle/current/b37/human_g1k_v37.fasta -V /humgen/1kg/processing/production_wgs_final/trio/CEU/CEU.wgs.HaplotypeCaller.20131118.snps_indels.high_coverage_pcr_free.genotypes.vcf -select vc.getGenotype("NA12878").getPhredScaledQual() <= 20 -sn NA12878 -selectType SNP -o lowQualSNPs_baseline_gatk3.vcf
```

dataflow01.broadinstitute.org on Linux 2.6.32-573.3.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0-b132.

**2m23.051s** GATK 3.4-46-gbc02625
**1m52.230s** GATK4 pre-alpha-92-g9200274
time gatk3
```
real	2m23.051s
user	3m8.037s
```

time gatk4
```
real	1m52.230s
user	2m14.190s
```

**Comment by akiezun** [comment]
closing this, we win

**Comment by droazen** [comment]
Nope -- you didn't test with a concordance/discordance track as requested above, which has major performance implications. Re-opening

**Comment by akiezun** [comment]
fine

**Comment by akiezun** [comment]
case 4: NFS drive, concordance track. 
input 1.9Gb, concordance track is the same file with permuted samples.

```
SelectVariants -R /humgen/gsa-hpprojects/GATK/bundle/current/b37/human_g1k_v37.fasta -V /humgen/1kg/processing/production_wgs_final/trio/CEU/CEU.wgs.HaplotypeCaller.20131118.snps_indels.high_coverage_pcr_free.genotypes.vcf --concordance /xchip/cga_home/akiezun/data/CEU.wgs.HaplotypeCaller.20131118.snps_indels.high_coverage_pcr_free.genotypes.permutedSamples.vcf -sn NA12878 -o concordance_gatk3.vcf
```

dataflow01.broadinstitute.org on Linux 2.6.32-573.3.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0-b132

**3m57.850s** on GATK 3.4-46-gbc02625
**5m14.169s** on GATK 4.pre-alpha-92-g9200274 :boom:

**Comment by akiezun** [comment]
case5: NFS drive, discordance track.  
input 1.9Gb, discordance track is the same file with permuted samples.

```
SelectVariants -R /humgen/gsa-hpprojects/GATK/bundle/current/b37/human_g1k_v37.fasta -V /humgen/1kg/processing/production_wgs_final/trio/CEU/CEU.wgs.HaplotypeCaller.20131118.snps_indels.high_coverage_pcr_free.genotypes.vcf --discordance /xchip/cga_home/akiezun/data/CEU.wgs.HaplotypeCaller.20131118.snps_indels.high_coverage_pcr_free.genotypes.permutedSamples.vcf -sn NA12878 -o discordance_gatk3.vcf
```
dataflow01.broadinstitute.org on Linux 2.6.32-573.3.1.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0-b132

**3m45.728s** on 3.4-46-gbc02625
**5m1.409s** on GATK 4.pre-alpha-92-g9200274 :boom:

**Comment by akiezun** [comment]
we lose on the concordance/discordance comparison - this issue now tracks profiling and optimizing that case. Bumped the time estimate to 3.

**Comment by akiezun** [comment]
case6: same as case5 but on increased cache size to 100000
**3m45.728s** on 3.4-46-gbc02625
**3m15.550s** on GATK4 :+1:

**Comment by droazen** [comment]
Woohoo, knew it would be a simple fix! :)

**Comment by droazen** [comment]
Can you try a few more cache sizes like 200000 and 500000? Also, when you do the PR, could you create `VariantWalker.FEATURE_CACHE_SIZE = 100000` (or whatever the final value is) and pass it into the `FeatureManager` in `initializeFeatures()`?

**Comment by droazen** [comment]
Also, have we profiled `VariantFiltration` yet against GATK3? It's unclear whether the existing caching will be sufficient for that tool (see https://github.com/broadinstitute/gatk/issues/670).

**Comment by akiezun** [comment]
re: `VariantFiltration`,  we did not profile the case of using an auxiliary data. The 100k cache will work for that one too, i'm sure.

**Comment by droazen** [comment]
@akiezun Can you double-check that assumption? I am concerned because caching is disabled on the second `FeatureDataSource` for the driving variants source (the one we add to the `FeatureManager` -- see `VariantWalker.initializeDrivingVariants()`), and I know that `VariantFiltration` does queries on that cacheless data source.
