### ISSUE TITLE
Spark options aren't being passed to master

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1096]
Spark parameters set in SparkCommandLineProgram aren't actually being propagated to the spark master.  @LeeTL1220 discovered that this was the case.   The solution is to move them into the SparkContextFactory and apply them to the `SparkConf` instead of the `SparkConfig`

**Comment by laserson** [comment]
Related to #1070?

**Comment by lbergelson** [comment]
@laserson Related to antagonistic too #1070.  This is setting this explicitly instead of using spark submit.  The solution to 1070 will probably revise the changes I'm making here.
