### ISSUE TITLE
Did the user give a value to the command argument.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#110]
Some times in the past I found that it would have been useful to be able to determine whether the user gave a value to an argument or not. I.e. the argument default value may be different based on the circumstances (by different tools if shared across tools or the same tool based on other argument values) and so it is important to make sure that we are not overriding the user request (or at least we can emit the appropriate warning or error message).

**Comment by lbergelson** [comment]
Closing because this is now tracked by https://github.com/broadinstitute/barclay/issues/23 in barclay.
