### ISSUE TITLE
Improve performance of MarkDuplicatesSpark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1100]
In the process of designing correctness tests for `MarkDuplicatesSpark`, @davidadamsphd has come up with a potential set of optimizations to `MarkDuplicatesSpark` that have the potential to improve performance by an order of magnitude. The task here is to meet with @davidadamsphd, get access to and understand his optimizations, and port them to the main `MarkDuplicatesSpark` tool (along with any other optimizations you feel are appropriate).

**Comment by droazen** [comment]
This one is for @laserson, as discussed in person (since he's conveniently slated to meet with @davidadamsphd in person this week).

**Comment by droazen** [comment]
@laserson When you get a chance, would you mind adding an update here with the status of this, and whether you think it's be possible to get any additional optimizations for `MarkDuplicatesSpark` in by alpha (Dec 4)? Thanks!

**Comment by akiezun** [comment]
@laserson so if I understand correctly, the investigation into using @davidadamsphd 's code for MD gave negative result? If that;s the case, let's close this ticket and open one that repsresents your current work benchmarking. what do you think?

**Comment by laserson** [comment]
Sorry, if I understand, David's tool is to check for correctness of of MarkDuplicates.  I'm just looking at the performance.

**Comment by akiezun** [comment]
the initial description here says there is some performance improvement for MD itself lurking in some of DA's branches. 
@davidadamsphd can you clarify what that is and what you think should be done in this ticket? I'm a bit confused here - the ticket mentions some mysterious code that is going to improve our lives etc but does not include a reference to it. Does the code exist, does it work, can we use it?

**Comment by lbergelson** [comment]
Closing this since it's sounds like Tom's changes have made major improvements.  @davidadamsphd Feel free to reopen if you have something else that can help.
