### ISSUE TITLE
Write a tool to gather one-end-anchored read pairs

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk#1105]
For now, just gather read pairs into a separate BAM file for evaluation.

**Comment by davidbenjamin** [comment]
@cwhelan are issues #1102 - #1106 resolved in gatk-protected?

**Comment by cwhelan** [comment]
We don't do any work in gatk-protected. Are you wanting to close these issues?

**Comment by cwhelan** [comment]
They are pretty out of date, I'll close the no-longer relevant ones.

**Comment by davidbenjamin** [comment]
> Are you wanting to close these issues?

Yeah, I was just going through issues to fix in my 20% time and came across these.
