### ISSUE TITLE
Fix intermittent gradle out-of-memory errors in travis

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1113]
Our travis builds are getting killed intermittently with out-of-memory errors -- it's unclear whether it's the test suite JVM or the JVM with gradle that is getting killed. This is happening more and more often...

**Comment by droazen** [comment]
Whatever fix we come up with for this should also be propagated to hellbender-protected, as requested by @LeeTL1220

**Comment by lbergelson** [comment]
I think the changes I've made in #1124 should probably resolve the situation for us.  Reopen if you see this again.
