### ISSUE TITLE
Remove fastutil dependency

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1117]
we use fastutil in 2 places - once in BQSR and once in ReadLikelihoods.

could they be replaced with code from guava?

**Comment by droazen** [comment]
`fastutil` is a huge library with 10,000+ classes -- we can't keep adding dependencies like this and then use them in only one or two classes - our jar size is becoming ridiculous. We should replace usages of `fastutil` with either guava or primitive arrays.

**Comment by akiezun** [comment]
haha, bogus eh?

**Comment by lbergelson** [comment]
We should add all the alternative collections frameworks just to be sure.

**Comment by akiezun** [comment]
I'm not planning to actively do anything here.  removing this direct dependency does make the jar file smaller, but only by 71301771-70815509 = 486262 bytes (0.68% smaller)
