### ISSUE TITLE
Stop tests from producing adam.log

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1123]
`ReadSparkSinkUnitTest.readsSinkADAMTest()` always writes an `adam.log` file to the hellbender root.  We should figure out how to prevent this, or at least clean it up after tests run.

**Comment by akiezun** [comment]
@laserson do you know how to not create that adam.log file?

**Comment by akiezun** [comment]
it was coming from the adam project - log4j was picking up that config file because it was the first log4j.properties file it could find. Fixed by providing our own
