### ISSUE TITLE
ApplyBQSR ignores useOriginalQualities

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1125]
in GATK3 useOriginalQualities is an engine level argument. In hellendender, it's only used in BaseRecalibrator and so you can't applyBQSR on originalBase qualities.

@eitanbanks is this an alpha requirement?

**Comment by eitanbanks** [comment]
It's used in the Genomes on the Cloud pipeline.  So if we really do want to push this to GotC - and you suggested we do this right after alpha - then it might need to be in...
