### ISSUE TITLE
display @Advanced arguments differently

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1128]
arguments marked as `@Advanced` should be displayed differently than others

**Comment by akiezun** [comment]
@vdauwera what does GATK3 do?

**Comment by droazen** [comment]
@cmnbroad Is this one done?

**Comment by magicDGS** [comment]
I added this feature to Barclay in https://github.com/broadinstitute/barclay/pull/19, so this can be closed (I think that the current SNAPSHOT has that PR included)
