### ISSUE TITLE
Make BROADCAST the default join strategy in BaseRecalibratorSpark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1131]
Since SHUFFLE is unusable.

**Comment by akiezun** [comment]
something is not right though. With this change, BaseRecalibratorSparkIntegrationTest are >20x slower. See this (look at times on the right hand side)

![image](https://cloud.githubusercontent.com/assets/1993519/11222166/e63a09bc-8d36-11e5-87f5-6fc69f368676.png)



Compare to shuffle times:
![image](https://cloud.githubusercontent.com/assets/1993519/11222123/a09101fe-8d36-11e5-97d2-709cddd875c4.png)

I'm assuming this is unexpected. Back to @droazen for resolution.

**Comment by droazen** [comment]
I think the problem is that you need to do https://github.com/broadinstitute/gatk/issues/1130 first, then refactor the tests to use a .2bit reference for the BROADCAST-based tests as part of this ticket (SHUFFLE should still have test coverage, though).

**Comment by droazen** [comment]
Note that we already have src/test/resources/large/human_g1k_v37.20.21.2bit

**Comment by droazen** [comment]
Answered, back to @akiezun

**Comment by droazen** [comment]
Note that an alternate (and faster) way of addressing this issue is to make the integration test cases that currently don't specify `--joinStrategy` run with `--joinStrategy SHUFFLE`. This way we can make BROADCAST the default without having to change any existing tests. It would be good, however, to have more of the BQSR spark tests run in BROADCAST mode if there's time to make the necessary changes.

**Comment by akiezun** [comment]
good idea. this is done in #1139

**Comment by droazen** [comment]
Fine, but I created https://github.com/broadinstitute/gatk/issues/1140 as well :)

**Comment by akiezun** [comment]
the rabbit hole never ends does it?

**Comment by droazen** [comment]
The rabbit hole ends when you tell me you have enough alpha tickets :)
