### ISSUE TITLE
BuildBamIndex doesn't support CRAM file indexing

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#1135]
It needs to be integrated with CRAMIndexer, and tests should be added for both BAM and CRAM.

**Comment by ldgauthier** [comment]
I'm going to close this because A) that tool is in the Picard codebase, not GATK, and B) in production we use `samtools index` to index crams anyway.

**Comment by lbergelson** [comment]
@ldgauthier With the changes to the cram code coming htsjdk we should would like to be able to index cram natively.  I think this actually might be newly relevant for the first time in a long time.  
@cmnbroad what's the new status of indexing cram in java?

**Comment by cmnbroad** [comment]
htsjdk can generate .crai (disq does so already, though the new code fixes a lot of bugs and has a lot more tests). On index read it still converts to bai though. Anyway I'll make a corresponding Picard ticket.
