### ISSUE TITLE
Add additional integration tests for BaseRecalibratorSpark that use --joinStrategy BROADCAST, now that it's going to be the default

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1140]

**Comment by droazen** [comment]
Since you are so fast @akiezun, here's another one for you.

**Comment by droazen** [comment]
Can probably copy existing tests, replacing the reference with a .2bit reference.

**Comment by akiezun** [comment]
what about tests that use Google cloud API for reference? Those will not use a 2bit one

**Comment by droazen** [comment]
Broadcast only works with a .2bit reference -- it cannot get the reference from the Google API.

**Comment by akiezun** [comment]
so should we blow us if you request broadcast and google API? https://github.com/broadinstitute/gatk/pull/1137 will make it blow up

**Comment by droazen** [comment]
I'll add: the tests that use a reference from the API are using a b37 reference -- so you can use src/test/resources/large/human_g1k_v37.20.21.2bit if they use chromosome 20/21.

**Comment by droazen** [comment]
Yes, blow up for now @akiezun. Unless you want to attempt a ticket to remove this restriction from the BROADCAST implementation, since you are so fast today (should not be hard to do...)

**Comment by droazen** [comment]
@akiezun Actually, looking at the code now I'm not entirely convinced BROADCAST won't work with the reference coming from the API (though we've never tried this combination before). New ticket incoming.

**Comment by akiezun** [comment]
@droazen is anything left to do here? We currently blow up on broadcast if reference is not a 2bit file. see  #1137

**Comment by droazen** [comment]
@akiezun Yes, the task is to add more integration tests that use `--joinStrategy BROADCAST`. Currently almost all of the tests use `SHUFFLE`, even though that's no longer the default.
