### ISSUE TITLE
Determine whether BaseRecalibratorSpark with --joinStrategy BROADCAST works with a reference from the Google API

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1142]

**Comment by droazen** [comment]
If it doesn't, should be pretty easy to allow it to support this.

**Comment by droazen** [comment]
Note: may require changes to https://github.com/broadinstitute/gatk/pull/1137

**Comment by akiezun** [comment]
we know it works but it's super slow (> 20x slower) so we'll disallow it for now. For numbers see the pictures in https://github.com/broadinstitute/gatk/issues/1131

Changes in https://github.com/broadinstitute/gatk/pull/1137 will make API+Broadcast a non-allowed combination so i'm closing this.
