### ISSUE TITLE
CLI usage page bogosities

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1150]
- [x] `Exome Analysis: Tools to analyze exome data. ` should be renamed to something about CNVs or removed altogether. Most of our tools can be used to analyze exome data and so this group designation is bogus
- [x] `ExampleIntervalWalker                        Print intervals with optional contextual data` I'd add something about 'it's a example'
- [x] top of the page says `USAGE: Main <program name> [-h]` - there's no Main
- [x] `Miscellaneous Tools:` has only 1 tool 'NormalizeFasta`. I'd fold this tool to another group and remove the misc
- [x] all mentions of `a SAM or BAM` should be changed to SAM/BAM/CRAM
- [x] all metrics that have names matching  `Collect*Metrics` should have the same form of a doc. Now it's all messy, eg `Produces from a SAM or BAM a file containing summary alignment metrics` vs `Writes insert size distribution metrics for a SAM or BAM file` vs `Produces jumping library metrics for the provided SAM/BAMs`
- [x] note, normally, we'd rename all metrics to have the same form of name but let's  wait until picard is sync'd up
- [x] note, normally we'd rename all commands that mention 'Sam` to something more accurate but we're waiting for picard sync up
- [x] ApplyBQSR can also work on SAM and CRAM but doc says `Applies the BQSR table to the input BAM`
- [x] some entries has periods at the end, some don't. Make them the same (no periods)
- [x] add works BQSR to doc of `BaseRecalibrator` and `AnalyzeCovariates`
- [x] CountBases should say more than `Count bases`
- [x] CountReads should say more than `Count reads`
- [x] PrintReads  should say more than `Print reads`
- [x] LeftAlignIndels should capitalize `bam` in doc
- [x] `Spark tests:                                     Programs to test out Apache Spark` should  be less about tests and more about 'spark-enabled implementation of tools'. Somethng like that
- [x] `ApplyBQSRSpark                               apply BQSR on spark` -> `ApplyBQSR on Spark`
- [x] `BQSRPipelineSpark                            Both steps of BQSR` - what steps?
- [x]  both BaseRecalibratorSpark and  BaseRecalibratorSparkOptimized say `Generates recalibration table`
- [x] I think all Spark tools can just have doc saying `TOOLNAMe on Spark` if it's all they are
- [x] `CountVariants                                Count variants` - counts them where?
- [x] ExampleReadWalkerWithVariants should be in the BAM/CRAM/SAM group'
- [x] ExampleVariantWalker add 'example' to its doc
- [x] IndexFeatureFile `Creates indices for Feature-containing files` is too cryptic
- [x] LiftoverVcf - all tools for liftover should use the same language. Now each one describes it differently
- [x] i think we should remove all mentions of BCF. We're not supporting BCF 2.1 and so it's kind of bogus to mention BCF until we do
- [x] it's very confusing to have VariantFiltration vs FilterVcf vs SelectVariants.

**Comment by droazen** [comment]
Anyone have bandwidth for this one?

**Comment by akiezun** [comment]
re: FilterVcf see https://github.com/broadinstitute/gatk/issues/1215

holding off on metrics

**Comment by akiezun** [comment]
for SAM or BAM issue - i went through all tools and checked that they do have a cram test (and added CRAM to usage), or have a ticket for cram tests
