### ISSUE TITLE
Several Picard command-line args are being ignored

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#1155]
In `PicardCommandLineProgram` there is an `instanceMain` that gets called when a subclass program is called. This "main" sets a number of static variables to values parsed from the arguments, then calls `super.instanceMain`.

The problem is that the values haven't been parsed before they are referenced in this function, so the default values are _always_ used. The ignored flags are:
- `VALIDATION_STRINGENCY`
- `COMPRESSION_LEVEL`
- `MAX_RECORDS_IN_RAM`
- `CREATE_INDEX`
- `CREATE_MD5_FILE`

These flags are ignored for _all_ Picard tools, of which we have dozens.

A rough sketch of the solution is here:
https://github.com/broadinstitute/gatk/compare/da_fix_picard
If this seems like a reasonable approach, I'll retake the bug and fix this.

**Comment by akiezun** [comment]
yes. This works nicely. Go ahead @davidadamsphd

**Comment by akiezun** [comment]
@davidadamsphd is this done? if yes, refer the pull req here

**Comment by droazen** [comment]
Reassigning to @akiezun to confirm that this is done.

**Comment by akiezun** [comment]
confirmed
