### ISSUE TITLE
Verify CRAM support works on Hadoop-BAM

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#1160]
@tomwhite just added support. We should try `SortBamSpark` on a large CRAM file to see if we have any reading or writing problem.

**Comment by akiezun** [comment]
do we need to upgrade to the latest hadoop-bam to have this @tomwhite ?

**Comment by tomwhite** [comment]
@akiezun yes, version 7.3.0.

The other thing I didn't mention is that AnySAMInputFormat will need to be changed to CRAMInputFormat for the test. (I opened https://github.com/HadoopGenomics/Hadoop-BAM/issues/35 to fix this properly.)

**Comment by tomwhite** [comment]
This is a duplicate of https://github.com/broadinstitute/gatk/issues/966, so one or other should be closed.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/966
