### ISSUE TITLE
Consider removing default mapred.max.split.size

### ISSUE THREAD

**Issue by laserson** [broadinstitute/gatk#1166]
Let HDFS/InputFormat deal with this as intended.  If a user wants to make it smaller, they should be able to pass it on the command line using a `--conf` setting.

Related to #1070, where Spark options should be given to Spark rather than GATK.

**Comment by lbergelson** [comment]
@laserson 
1.  How do you handle situations where you need different split sizes for different file types?  
2.  How do you handle setting reasonable defaults so it works right out of the box without people having to set their spark configs explicitly?

**Comment by laserson** [comment]
From a high level, users really shouldn't be worrying about this.  The Hadoop defaults are often adequate.  This is not a perfect analogy, but you generally don't think about block sizes for your usual Linux file system.

Also, the default 4 MB size that it's currently set to is very small.  The individual Spark tasks finish in just a few seconds, which means you're probably paying more overhead than you need.

>1. How do you handle situations where you need different split sizes for different file types?

You can manually specify the block sizes for individual files in HDFS.  It's possible that you could also specify the mapreduce split sizes in the `InputFormat`, but I'd need to ask @tomwhite.

>2. How do you handle setting reasonable defaults so it works right out of the box without people having to set their spark configs explicitly?

Have we already decided that the default Spark configs are bad?

**Comment by lbergelson** [comment]
I know we've had to tune this parameter to get things working, and different sizes are better for different tools.  If we increase it by much we start thrashing memory and spilling to disk, but the partition size range depends on the tool.  MD works more slowly if you increase this by several times, others you can increase it an order of magnitude and it's ok.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/1403
