### ISSUE TITLE
SAM/BAM writers should always call setHeader on added records

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#1175]
This will ensure that the reference indices are properly resolved against the current SD before writing.

**Comment by cmnbroad** [comment]
I made this change in htsjdk, but I don't think the consequences are quite what we want in all cases. Given the htsjdk policy that allows bad reference names but not reference indices to persist, this change will be silently destructive on persisted BAM records in the case where the writer's header doesn't contain the record's referenceName. The setHeader call doesn't throw, but leaves the current reference name as is and marks the reference index unresolved. But since the BAMRecordCodec doesn't encode the name, only the index, at that point the information is essentially lost.

**Comment by cmnbroad** [comment]
We might want to use a less forgiving version of setHeader for this. Back to @droazen for input.

**Comment by droazen** [comment]
I don't think "the writer's header doesn't contain all the reference names in the records" is a use case we want/need to support. Arguably we should throw an error in that case.

**Comment by cmnbroad** [comment]
Per discussion with @droazen we'll do this after alpha.

**Comment by cmnbroad** [comment]
We'll use a strict version of setHeader that throws if the record's reference names can't be resolved against the writer's header.

**Comment by cmnbroad** [comment]
htsjdk PR is https://github.com/samtools/htsjdk/pull/406

**Comment by cmnbroad** [comment]
Closed via #1469.
