### ISSUE TITLE
ReadsSparkSource/GATKSparkTool should propagate the reference to Hadoop-BAM cram reader

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1180]
For walkers we had to modify `GATKTool` to propagate the reference to our sam readers. It's likely we need to do something similar for Hadoop-BAM cram support. This probably involves changes to `GATKSparkTool`, `ReadsSparkSource`, or both.

**Comment by droazen** [comment]
With walkers it's done like this (in `GATKTool`):

        if (hasReference()){
            // pass in reference if available, because CRAM files need it
            factory = SamReaderFactory.makeDefault().validationStringency(ValidationStringency.SILENT).referenceSequence(referenceArguments.getReferenceFile());
        } else if (hasCramInput()) {
            throw new UserException.MissingReference("A reference file is required when using CRAM files.");
        }

Unsure how to do the same for Hadoop-BAM

**Comment by akiezun** [comment]
will be done as part of #966. closing this ticket
