### ISSUE TITLE
Require a reference in GATKSparkTool when there's a cram input 

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1181]
Similar to how `GATKTool` requires a reference when there's at least one cram input, we need to do the same thing in spark.

Right place to do this is probably in `GATKSparkTool.initializeReads()` or `GATKSparkTool.validateToolInputs()`

**Comment by akiezun** [comment]
this will be done in GATKSparkTool .getUnfilteredReads
ticcket #966 subsumes all this so i'm closing this one
