### ISSUE TITLE
Explicit codec for FeatureInputs

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#1184]
I would be useful to be able to explicitly indicate the Codec class for a FeatureInputs perhaps using an annotation. 

Currently the feature manager tries every possible codec hoping to find one and only one that answers yes to the canDecode(FileName) method call. If none does execution fails saying that there is no code available to deal with the input file; if more than one codec returns true then is supposed to throw another error indicating the ambiguity. The former is likely an user cased error whereas the later is rather a bug as Codec developers seems to be responsible to make sure that such a collision never happens...

This has a few draw backs:

* Seems to quasi-force to establish a 1-to-1 assignation of Codecs and file extension names; canDecode documentation encourages use the file name as the way to determine whether the codec can decode or not the file. What if the file is a simple tab separated value file (with some column count and format constrains) and general extensions such as .tab or .tsv seem acceptable names in practice?

* The error message when there is no supporting code does not tell what the problem is; whether the extension of the file (due to the the 1-to-1 name to type quasi-restriction above) or a more complex formatting issue in the file (e.g. required header missing, version not supported ... blah blah). 

* All codecs are tried out even when most won't ever apply. Even if the performance impact should in practice be minimal still may cause several file IO open operations as several Codec do actually peek into the file (e.g. BCF and VCF codecs). 

* Codec developers have to make sure their new codec does not collides with others; it would be better if codec development can be totally independent.

* General file extensions such as .tab , .tsv cannot be used by codecs due to possible collisions constraining users to name their files the way GATK needs them to; "I don't like people telling what file names a have to use... I'm already placing the correct argument name before the file name. What else you need!"

Proposal:

An annotation to tell what codes to try out, the first one that canDecode returns true is used otherwise a configurable error message saying what the problem could be:

<pre>
@Codecs(BEDCodec.class)
FeatureInput&lt;BEDFeature&gt; features;
</pre>

<pre>
@Codecs(value = BEDCodec.class, failureMessage = "The file provided must be a BED formatted file with extension .bed")
FeatureInput&lt;BEDFeature&gt; features;
</pre>  

<pre>
@Codecs(BCFCodec.class, VCFCodec.class)
FeatureInput&lt;VariantContext&gt; variants;
</pre>

<pre>
// force = true, means that canDecode won't be called and instead we try to read the content directly,
// the codec's code is responsible to throw an appropriate UserException.BadInput indicating formatting issues; this should be the case already anyway.
@Codecs(value = TargetCodec.class, force = true)
FeatureInput&lt;Target&gt; target;
</pre>

If the annotation is not present it can default to the current behavior.

**Comment by vruano** [comment]
Today I bumped into this issue where two codecs of mine collide.

**Comment by droazen** [comment]
Can you give us more details on how the codecs are colliding? Do their `canDecode()` methods claim the same extension(s)?

**Comment by vruano** [comment]
Yup, same extension... ".tab" or ".tsv" (or whatever the user pleases) as they are tab separate value files.

My canDecode look into the content of the file and don't care about extensions. Same as the VCF or BCF codecs.

**Comment by vruano** [comment]
Also it seems that one can access the type arguments of fields thru reflection, thus the default behavior could constrain to try the codecs whose declared feature type is compatible with the FeatureInput parameter type.

**Comment by droazen** [comment]
We can implement this, but first can you explain why your `canDecode()` methods can't unambiguously detect your file formats? The VCF/BCF codecs use a magic value at the start of the file to detect the format -- are your codecs guessing as to the intended format? Is there no way to be sure what the format is?

If we have multiple codecs able to decode a file, and only one produces `Features` that match the type parameter of the `FeatureInput`, would it solve your problem if we selected that codec rather than blow up? This would be a bit simpler/easier than a new annotation.

**Comment by vruano** [comment]
My files don't have magic numbers, I don't see the need for it; the user is telling me what the file are supposed to contain by choosing the argument name that comes in front. 

The only think the codecs check is that the single line header that contains the column names contain the mandatory columns for whatever type of feature they decode. For these two codecs the intersection of valid column names set for these to codecs is not empty.

**Comment by droazen** [comment]
Would selecting the codec that produces `Features` of type `X` for a `FeatureInput<X>` when there are multiple matches solve the problem?

**Comment by vruano** [comment]
That would work, yet I don't see why we simply can focus only in coders that return the right type.

**Comment by droazen** [comment]
A new annotation with features like `failureMessage` and `force=true` is a lot more complex and more work than just prioritizing type `X` for a `FeatureInput<X>`, if that will work just as well. See the chat room slogan "hellbender instinct shall be to simplify and rip stuff out" :)

**Comment by vruano** [comment]
I meant to forget about the annotations for now. Just try those codecs that return the right Feature type no even call canDecode on the other codecs.

I dont think this should be more lines of code.

**Comment by droazen** [comment]
So you're proposing that we just limit the set of codecs we consider as candidates to those that return the right `Feature` type? This seems like a good idea -- it shall be done!

**Comment by vruano** [comment]
yup i meant that, initially i thought the par types wernt available at runtime and so i thought the annotation was necesary
