### ISSUE TITLE
Measure the performance of the whole ReadsPipelineSpark vs string of Picard+GATK tools

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1196]
the main advantage of spark for processing is that we can do stuff in memory and so throughout **of the whole pipeline** should be higher than that of the string of Picard+GATK tools.

The thing to do here compare is:
1) take a bam file, run ReadsPipelineSpark on it, measure time (as function of # nodes, start with 1)
2) take same bam file, run MarkDuplicates, BaseRecalibrator, PrintReads in order, measure time

The bam file should be non-trivial, at least 30GB.

The goal for beta should be to beat non-spark on 1 node. It may already be true for alpha.

**Comment by droazen** [comment]
These profiling tickets do not absolutely need to be in for alpha -- moving to beta.

**Comment by akiezun** [comment]
putting this on hold until we add 1-shuffle MD

**Comment by akiezun** [comment]
closing as dup of #1559
