### ISSUE TITLE
GATKTool createSAMWriter should clone the reads header

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#1200]
Before we had common SAM writer creation, the tools were inconsistent about whether or not they cloned the SAMFileHeader from the input reads before using it as the output header. Now they consistently do not clone it, but I think defensive cloning should be the default behavior.

**Comment by cmnbroad** [comment]
Marking as alpha for now.

**Comment by droazen** [comment]
This one is done
