### ISSUE TITLE
delete SHUFFLE from BQSR spark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1203]
SHUFFLE is a loser, let's dump it after the broadcast/sharded decision

**Comment by droazen** [comment]
Remove `VariantShard` and `ReferenceShard` as well when we do this, if possible

**Comment by akiezun** [comment]
what is our story for the cloud though? Google references are not 2bit and we require 2bit for BROADCAST?

**Comment by droazen** [comment]
We should currently be able to broadcast .2bit references stored in GCS buckets in the cloud. Whether it makes sense to do this vs. accessing the reference directly via GCS or the Google reference API is a topic for a future comparison.

**Comment by droazen** [comment]
This is blocked until we can make reference broadcast work with cram inputs.

**Comment by droazen** [comment]
Specifically, it is blocked by https://github.com/broadinstitute/gatk/issues/1443

**Comment by akiezun** [comment]
Unmarking as alpha-2. I doubt this will rise enough priority. This is a cleanup task really because the default is BROADCAST already. @cmnbroad @droazen feel free to mark back as alpha-2 if #1443 is closed in time.

**Comment by droazen** [comment]
SHUFFLE is useful to keep around for profiling purposes -- closing.

**Comment by lbergelson** [comment]
Shouldn't we delete it anyway?  I'm not sure it's useful other than to say.  "Doing this badly is slow".

**Comment by droazen** [comment]
It useful to have a baseline during performance benchmarking to answer the question "are we better than a naive shuffle".
