### ISSUE TITLE
Determine fate of Picard tools

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1210]
Picard is still under (very) active development, while the ported versions of the picard tools in gatk4 are becoming more and more outdated. We need to either make gatk4 the official home of the picard tools and move all current picard development here, or give up on merging gatk and picard. Since having the picard tools and utilities as part of the codebase has been useful in many instances, and since hosting the official versions would also encourage more developers inside and outside the Broad to contribute to gatk4, I am hoping that we can make this marriage work!

**Comment by vdauwera** [comment]
Agreed! Users want this, we want this -- let's please do whatever we need to make it happen!

One barrier to getting this to work, as I understand it, is the need for a build system that allows production/Kathleen to generate new internal releases of the Picard portion independently of the rest of GATK. This is because they often need to update Picard tools but usually don't want to pull in changes to the GATK tools at that time. This was discussed some time ago but I don't know if any work has been done in that direction (apologies if I'm stepping on any toes).

@eitanbanks @yfarjoun @ktibbett @akiezun @geoffjentry

**Comment by droazen** [comment]
@vdauwera Does that really require a solution at the build system level? Couldn't we just have one hellbender jar that is used exclusively for running the Picard tools in production, and a second, separate hellbender jar that is used exclusively for running the GATK tools? Does it really matter if the "Picard" jar actually contains GATK tools, and vice versa, as long as we never run GATK tools from the "Picard" jar, or Picard tools from the "GATK" jar?

**Comment by vdauwera** [comment]
@droazen That actually sounds perfectly fine to me, I think it would satisfy @ktibbet's needs. Forest/trees <-- me not seeing past them.

**Comment by lbergelson** [comment]
It's also totally plausible to be able to build a separate picard jar from
the same project if that's a requirement.

**Comment by droazen** [comment]
@lbergelson Not if there are GATK tools/utilities calling into Picard tools/utilities and vice versa (which there certainly is at this point!).

**Comment by eitanbanks** [comment]
FYI @ktibbett is going to organize a meeting to discuss in person with interested parties

**Comment by lbergelson** [comment]
Should we try to get Tim and Nils involved in the meeting as well? They're
the most prolific committers at the moment.

**Comment by vdauwera** [comment]
Yes the plan is to involve them.

**Comment by lbergelson** [comment]
Good.  We need them on board if we want to avoid forking.

**Comment by droazen** [comment]
Let's try to make progress on this one for alpha-1, though we may not be able to resolve it completely within that time frame.

**Comment by droazen** [comment]
This thorny issue will not be resolved in alpha-1 -- we'll have to keep pushing on it in alpha-2 with the help of @vdauwera

**Comment by akiezun** [comment]
what's the action plan for this? How about the following subgoals for alpha-2:
- [ ] move picard to a specific tagged version of htsjdk from maven https://github.com/broadinstitute/picard/pull/542
- [ ] picard moves to using gradle
- [ ] picard release numbers and schedule get decoupled from htsjdk ones

**Comment by droazen** [comment]
All of the items above are being implemented as we speak by @jacarey (see https://github.com/broadinstitute/picard/issues/545) -- whether we can do more than this for alpha-2 remains to be seen.

**Comment by jacarey** [comment]
I will have a PR for moving picard to gradle shortly.

**Comment by jacarey** [comment]
https://github.com/broadinstitute/picard/pull/554

**Comment by akiezun** [comment]
@droazen if I see correctly, there's nothing more do to from the gatk side in this milestone, right?

**Comment by droazen** [comment]
This is resolved -- we are going to take in the Picard tools as a dependency, and refactor both projects to depend on a shared arg parsing/documentation system (https://github.com/broadinstitute/barclay).
