### ISSUE TITLE
retire FilterVcf in favor of VariantFiltration?

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1215]
FilterVcf seems to be a subset of VariantFiltration. Should we retire it?

**Comment by akiezun** [comment]
WDYT @yfarjoun @ldgauthier ?

**Comment by ldgauthier** [comment]
I've never used the Picard one.  I'm under the impression that the Picard version actually removes variants from the output, which I am against.

**Comment by yfarjoun** [comment]
OK. I looked at the code. They do the same thing. not removing variants,
but rather apply HARD filters to variants.

The Picard version was written since GATK was too slow....

**Comment by ldgauthier** [comment]
:+1: for fast.

**Comment by akiezun** [comment]
thanks for clarifying. I'll compare perf of GATK4 and report it here.

**Comment by akiezun** [comment]
It's true - FilterVCF is faster when filtering genotypes. Here I took 1 small vcf file with 2535 samples and 12632 lines (675M) 

I'm closing this then. Unclear if we want to invest in speeding up VariantFiltration given that we're moving away from vcf files at some point.

```
No filters: 
VariantFiltration Elapsed time: 0.20 minutes
FilterVCF Elapsed time: 1.11 minutes

MIN_DP - per-genotype filter
VariantFiltration: Elapsed time: 2.05 minutes.
FilterVCF: Elapsed time: 1.16 minutes.

MIN_GQ - per-genotype filter
VariantFiltration  Elapsed time: 2.06 minutes
FilterVCF: Elapsed time: 1.16 minutes.
```

**Comment by akiezun** [comment]
One clarification - FilterVCF is not a subset of VariantFiltration, it offers one new option - filter on allele balance computed on the fly. I added https://github.com/broadinstitute/gatk/issues/1726
