### ISSUE TITLE
Hadoop-bam 7.3.0 incompatible with htsjdk 2.0.0 (?) Breaks on CRAM

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1247]
I get this on my branch `ak_spark_cram` when trying to read a cram file on spark - see `ReadsSparkSourceUnitTest`

It seems that the constructor that Hadoop-bam was using is now gone and so it fails with `NoSuchMethodError`

```
java.lang.NoSuchMethodError: htsjdk.samtools.CRAMIterator.<init>(Lhtsjdk/samtools/seekablestream/SeekableStream;Lhtsjdk/samtools/cram/ref/ReferenceSource;[J)V
	at org.seqdoop.hadoop_bam.CRAMRecordReader.initialize(CRAMRecordReader.java:51)
	at org.seqdoop.hadoop_bam.CRAMInputFormat.createRecordReader(CRAMInputFormat.java:83)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:131)
	at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:104)

```

@cmnbroad can you help?

**Comment by akiezun** [comment]
or @tomwhite please

**Comment by akiezun** [comment]
I created this as a attempt to fix it https://github.com/HadoopGenomics/Hadoop-BAM/pull/40

**Comment by tomwhite** [comment]
Another option would be to add back the constructor that doesn't have ValidationStringency in CRAMIterator. (It looks like https://github.com/samtools/htsjdk/commit/efb11267ceea800d221a36d4cb9756dde4c7a984 introduced the incompatible change.) ValidationStringency can still be set using the setValidationStringency method. This would mean that no Hadoop-BAM JDK change or release is needed.

**Comment by cmnbroad** [comment]
I'm closing this because we're not going to do anything about compatibility with htsjdk 2.0.0. The remaining work we do need to track is in ticket https://github.com/broadinstitute/gatk/issues/1261.
