### ISSUE TITLE
Try using a larger split size for loading reads in spark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1248]
Using a larger split size for loading reads via Hadoop-BAM would improve performance -- @tomwhite has shown that the process of reading the input splits is expensive with a small split size like our current default of 10 MB (`ReadsSparkSource.DEFAULT_SPLIT_SIZE`). Let's see if we can use a larger split size for loading the reads, then re-partition back to a smaller split size that is a factor of the larger size before doing any work to avoid out-of-memory issues in map jobs. Ideally the re-partitioning step should NOT trigger a shuffle -- if it does, we may not want to make this change.

**Comment by tomwhite** [comment]
Spark's repartition method will always trigger a shuffle, whereas coalesce doesn't - but only if it's reducing the number of partitions. So I don't think we can re-partition back to a smaller split size in the way you describe.

What we can do though is take another look at why we need such a small split size and see if we can increase it (by better tuning etc). Even if we can't we know that some for some classes of jobs (e.g. metrics) we can use the default split size without an issue, so we could add logic to choose an appropriate split size based on the type of job.

**Comment by droazen** [comment]
Re-partitioning to a smaller size would increase the number of partitions, not reduce the number -- given this, are you sure that re-partitioning would definitely trigger a shuffle if the new size is a factor of the larger one? Wouldn't all the data already be exactly where it needs to be?

**Comment by droazen** [comment]
Or perhaps it triggers a shuffle, but the shuffle is in practice a "no-op" that costs nothing?

**Comment by tomwhite** [comment]
Re-partitioning to a smaller split size will increase the number of partitions, which requires a shuffle: http://spark.apache.org/docs/latest/api/java/org/apache/spark/api/java/JavaRDD.html#repartition(int)

If you have lots of small splits (large number of partitions) then it's easy to coalesce them without doing any shuffling. If you have a small number of large splits (small number of partitions) then you don't know how the data is distributed in them, so you have to shuffle them.

I don't think that the shuffle is "no-op" unfortunately - you still have to transfer the dataset over the network.

**Comment by droazen** [comment]
Do you agree that in theory the data is already where it needs to be in this scenario, and the problem is just that spark can't detect that this is the case?

**Comment by tomwhite** [comment]
Thinking about this a bit more, we're actually quite close to a solution. In the existing Spark Mark Duplicates implementation, for example, you can set the parallelism (with -P). By default it is the same as the number of input partitions, but if the partitions are too large then each reducer has too much data to deal with and the job fails. This is why we made the number of partitions large by reducing the split size to 10MB.

However, by increasing the number of reducers (by setting -P to be input data size/10MB), the input split size can be increased to its default of 128MB without causing a problem.

So I think the work here is to work out a good set of defaults and the smallest number of knobs to override them. For example, I think we could always use the default split size, have some heuristics to choose a good value for the parallelism, and allow it to be overridden with -P.

**Comment by tomwhite** [comment]
We should also decouple the parallelism and whether the output is a single file. For ReadsPipelineSpark we have `-shardedOutput`, but not for MarkDuplicatesSpark (where it's signalled by `-P 1`), so we should make this consistent.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/1403
