### ISSUE TITLE
Changes ExomeReadCounts tool name.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#1252]
Exome is too specific as we might use the same tools with other kind of data like arbitrary panels (not full exomes) or do target based analysis on WGS data. 

Also ReadCounts is not the only way we can measure coverage; we should be able to implement alternative coverage units in the same tool, so it is best to remove RC also from the name. 

ExomeReadCounts should be call instead CalculateTargetCoverage

Its "-exome" parameter should "-T" or "--targets" 

ExomeAnalysisProgramGroup should be TargetAnalysisProgramGroup

**Comment by vruano** [comment]
@LeeTL1220 I think you want to keep an eye on this one.

**Comment by droazen** [comment]
This is done! Closing
