### ISSUE TITLE
MarkDuplicatesSparkIntegrationTest.testMDOrder() passes locally, but fails intermittently in travis

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1258]
`MarkDuplicatesSparkIntegrationTest.testMDOrder()` *always* passes when run locally, but fails about 50% of the time when run in travis. As a result, it's currently disabled.

Some things I've tried to fix the test on travis, without success:
-Run MD with `--parallelism 1` instead of `--parallelism 0` (which doesn't guarantee ordering at all!) -- the original version of the test was running with `--parallelism 0`
-Converted test inputs from sam to bam
-Cleared all of travis's caches.

This may be purely a travis issue or a flaw in the test itself, or it may indicate that there remain issues with `MarkDuplicatesSpark` output and ordering despite the recent fixes. Note, however, that the original test from @davidadamsphd that first detected the ordering issue with MD on spark now passes, as do the new `ReadsSparkSink` ordering tests.

**Comment by droazen** [comment]
@akiezun Can you have a look at this one when you have time?

**Comment by akiezun** [comment]
@droazen do you have any logs of the failed runs?

**Comment by droazen** [comment]
@akiezun Sure! Here you go:

https://storage.googleapis.com/hellbender/test/build_reports/3776.2/tests/index.html
https://s3.amazonaws.com/archive.travis-ci.org/jobs/94993317/log.txt
https://travis-ci.org/broadinstitute/gatk/jobs/94993317

**Comment by akiezun** [comment]
Another error, probably related, is in ReadsSparkSinkUnitTest when run on NA12878_20_21_WGS_bam
```
Gradle suite > Gradle test > org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSinkUnitTest.readsSinkTest[3](/home/travis/build/broadinstitute/gatk/src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam, ReadsSparkSinkUnitTest4, .bam) FAILED
    java.lang.AssertionError: Reads are out of order (compare=121017): 20GAVAAXX100126:8:45:9150:97256	99	21	10121582	0	101M	=	10121932	437	TATGAGCTACCATGTCTCCTGTTTAACCTGAGTCTGAAGAGATTCAAAGTGCAGGTGCCATGAATGCCTCTTTAATAGCTCCATGTCGATTGATTTTCTGG	DDDBGFFEFEFFBFFFHFAHGFDGGHEFHDGGFF@DBDCE?GFGFHHEGFAFHG6FGFFFGGFHA>>@B>BDCDDFGGFHFFHGGFF>H=>>=D<GGBGGF	X0:i:5	X1:i:0	MD:Z:101	RG:Z:20GAV.8	XG:i:0	AM:i:0	NM:i:0	SM:i:0	XM:i:0	XO:i:0	BQ:Z:@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@A	MQ:i:0	OQ:Z:HHHHHHHGHHHGFHHHHHFHHHGHHHHHHGHHHHDGEGGGEHHHHHHGHHFHHH:HHHHGHHGHE??ADAEGGGGHHHHHHHHHHHHHHBBBBF?HHFHHH	XT:A:R
     and 20GAVAAXX100126:6:4:14681:182722	163	21	10000565	0	64M37S	=	10000875	410	TGTGATCCACCCGCCTTGGCCTCCCAAAGTGCTCGGATTACAGGCATGAGCCACCGTGAGTGACCTTGCGTTGTGATTTTTACGACAATTATCCCATATGT	BC;?897=><=120-E??-5D-CDDAH6:-;F9(03/65E5@F0%(65G6@B5=G&=;C?B7F######################################	X0:i:7	X1:i:2	XC:i:64	MD:Z:8G24G30	RG:Z:20GAV.6	XG:i:0	AM:i:0	NM:i:2	SM:i:0	XM:i:2	XO:i:0	BQ:Z:@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@	MQ:i:0	OQ:Z:B@6@859<<<;192-@;;15@+@@@=B35&<B5(97079B<?B6((:6B6=@4>A+<<B=>7A######################################	XT:A:R
     expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:496)
        at org.testng.Assert.assertTrue(Assert.java:42)
        at org.broadinstitute.hellbender.engine.spark.datasources.ReadsSparkSinkUnitTest.readsSinkTest(ReadsSparkSinkUnitTest.java:87)

```

**Comment by akiezun** [comment]
@droazen is on it
