### ISSUE TITLE
Fix reading queryname-sorted input crams with unmapped reads

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1259]
From @cmnbroad:

The write side for non-coordinate sorted CRAMs works now, but there is still a problem with reading queryname sorted input crams with unmapped reads. There is an existing test in GATK for this case that is already enabled and has been passing, but only because there is another bug in the test code that is masking the failure because it uses the value "outputExtension", which results in a BAM file being created. When I went to fix that as part of re-enabling the disabled CRAM tests, the verification of the queryname test output now fails. The test itself runs, but the samsEqualStringent verification fails reading the output. So the write-side issues with the presorted flag are fixed with samtools/htsjdk#368, but there is still a limitation in htsjdk for reading crams with unmapped reads that are not coordinate sorted that we need to fix/understand.

See also:
https://github.com/broadinstitute/gatk/issues/777
https://github.com/samtools/htsjdk/issues/404

**Comment by cmnbroad** [comment]
Also seen by @akiezun:  printreads test using print_reads.sorted.queryname.sam and printing to print_reads.sorted.queryname.cram

**Comment by cmnbroad** [comment]
vadim found the problem and is working on an htsjdk pr with a fix for this.

**Comment by cmnbroad** [comment]
The htsjdk fix for this is in https://github.com/samtools/htsjdk/pull/432.

**Comment by cmnbroad** [comment]
Closed via #1469.
