### ISSUE TITLE
Spark on CRAM complains about seq dictionary when non-spark does not 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1262]
spark complains but non-spark does not

```
CollectQualityYieldMetricsSpark  --output a.metrics --useOriginalQualities true --reference src/test/resources/Homo_sapiens_assembly19_chr1_1M.fasta --input src/test/resources/org/broadinstitute/hellbender/tools/picard/analysis/CollectQualityYieldMetrics/collect_quality_yield_metrics.cram  --disableSequenceDictionaryValidation false

org.broadinstitute.hellbender.exceptions.UserException$IncompatibleSequenceDictionaries: A USER ERROR has occurred: Input files reference and reads have incompatible contigs: Found contigs with the same name but different lengths:
  contig reference = 1 / 1000000
  contig reads = 1 / 249250621.
  reference contigs = [1]
  reads contigs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, X, Y, MT, GL000207.1, GL000226.1, GL000229.1, GL000231.1, GL000210.1, GL000239.1, GL000235.1, GL000201.1, GL000247.1, GL000245.1, GL000197.1, GL000203.1, GL000246.1, GL000249.1, GL000196.1, GL000248.1, GL000244.1, GL000238.1, GL000202.1, GL000234.1, GL000232.1, GL000206.1, GL000240.1, GL000236.1, GL000241.1, GL000243.1, GL000242.1, GL000230.1, GL000237.1, GL000233.1, GL000204.1, GL000198.1, GL000208.1, GL000191.1, GL000227.1, GL000228.1, GL000214.1, GL000221.1, GL000209.1, GL000218.1, GL000220.1, GL000213.1, GL000211.1, GL000199.1, GL000217.1, GL000216.1, GL000215.1, GL000205.1, GL000219.1, GL000224.1, GL000223.1, GL000195.1, GL000212.1, GL000222.1, GL000200.1, GL000193.1, GL000194.1, GL000225.1, GL000192.1, NC_007605]
```

Once fixed, reenable 2 tests in CollectQualityYieldMetricsSparkIntegrationTest

**Comment by droazen** [comment]
This ticket is invalid -- "non-spark" tools like `PrintReads` definitely complain about this combination of files:

    $ ./build/install/hellbender/bin/hellbender PrintReads -I src/test/resources/org/broadinstitute/hellbender/tools/picard/analysis/CollectQualityYieldMetrics/collect_quality_yield_metrics.cram -R src/test/resources/Homo_sapiens_assembly19_chr1_1M.fasta -O foo.bam
    [December 5, 2015 7:07:56 AM EST] org.broadinstitute.hellbender.tools.PrintReads  --output foo.bam --input src/test/resources/org/broadinstitute/hellbender/tools/picard/analysis/CollectQualityYieldMetrics/collect_quality_yield_metrics.cram --reference src/test/resources/Homo_sapiens_assembly19_chr1_1M.fasta  --disable_all_read_filters false --interval_set_rule UNION --interval_padding 0 --secondsBetweenProgressUpdates 10.0 --disableSequenceDictionaryValidation false --createOutputBamIndex true --help false --version false --VERBOSITY INFO --QUIET false
    [December 5, 2015 7:07:56 AM EST] Executing as droazen@wmce6-e31 on Mac OS X 10.9.5 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_25-b17; Version: Version:4.pre-alpha-210-gd7179f7-SNAPSHOT JdkDeflater
    07:07:56.668 INFO  PrintReads - Initializing engine
    07:07:56.815 INFO  PrintReads - Shutting down engine
    [December 5, 2015 7:07:56 AM EST] org.broadinstitute.hellbender.tools.PrintReads done. Elapsed time: 0.00 minutes.
    Runtime.totalMemory()=257425408
    ***********************************************************************
    
    A USER ERROR has occurred: Input files reference and reads have incompatible contigs: Found contigs with the same name but different lengths:  
      contig reference = 1 / 1000000
      contig reads = 1 / 249250621.
      reference contigs = [1]
      reads contigs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, X, Y, MT, GL000207.1, GL000226.1, GL000229.1, GL000231.1, GL000210.1, GL000239.1, GL000235.1, GL000201.1, GL000247.1, GL000245.1, GL000197.1, GL000203.1, GL000246.1, GL000249.1, GL000196.1, GL000248.1, GL000244.1, GL000238.1, GL000202.1, GL000234.1, GL000232.1, GL000206.1, GL000240.1, GL000236.1, GL000241.1, GL000243.1, GL000242.1, GL000230.1, GL000237.1, GL000233.1, GL000204.1, GL000198.1, GL000208.1, GL000191.1, GL000227.1, GL000228.1, GL000214.1, GL000221.1, GL000209.1, GL000218.1, GL000220.1, GL000213.1, GL000211.1, GL000199.1, GL000217.1, GL000216.1, GL000215.1, GL000205.1, GL000219.1, GL000224.1, GL000223.1, GL000195.1, GL000212.1, GL000222.1, GL000200.1, GL000193.1, GL000194.1, GL000225.1, GL000192.1, NC_007605]
    
    ***********************************************************************

I think you meant "the Picard version of this metric does not complain", which is expected given that Picard tools do not do the same automatic sequence dictionary validation as walkers and spark tools. If you think they should, you should create a different ticket "Multi-input Picard tools should perform sequence dictionary validation on their inputs". Closing

**Comment by akiezun** [comment]
created this: https://github.com/broadinstitute/gatk/issues/1272
