### ISSUE TITLE
ReadSparkSink adds a crc checksum file even for local files

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#1266]
The result of this bug is that if you produce a BAM with Spark, then produce a different BAM with the same name with the walker-framework, then try to read _that_ bam with Spark, it produces checksum (and other more misleading) errors.

**Comment by lbergelson** [comment]
Fixed by #1344

**Comment by lbergelson** [comment]
Reopened because we reverted #1344 in #1390

**Comment by droazen** [comment]
For alpha-1. Assigning to @tomwhite
