### ISSUE TITLE
ADAM ReadsSparkSinkUnitTest.loadReadsADAM test fails on NA12878.chr17_69k_70k.dictFix.bam

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1267]
see test in ReadsSparkSinkUnitTest.loadReadsADAM

**Comment by droazen** [comment]
Dupe of https://github.com/broadinstitute/gatk/issues/1254 -- closing

**Comment by akiezun** [comment]
not sure if they are related.
but fine

**Comment by droazen** [comment]
@akiezun Could you add a comment to the existing ticket (https://github.com/broadinstitute/gatk/issues/1254) 
with the additional failure?
