### ISSUE TITLE
implement writing cram files on spark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1270]
writing cram files on spark is not implemented yet and it'll throw when user attempts is (as per review of https://github.com/broadinstitute/gatk/pull/1268).

The task for this ticket is to implement/enable writing cram files on spark and add tests for it (do check that the results are in fact cram files - see https://github.com/broadinstitute/gatk/issues/1269)

**Comment by cmnbroad** [comment]
There are several parts to this that all exist, but need to be committed in this order:

-Minor refactoring of CRAM container writing code in htsjdk to allow separation of the writing of CRAM containers from the writing of the CRAM file header, SAM file header, and EOF container for part-merging.
-Hadoop-BAM needs to go to Java8 and upgrade to newer htsjdk.
-Add CRAMOutputFormat, CRAMRecordWriter, etc. to Hadoop-BAM (these depend on the htsjdk code mentioned above).
-Modify ReadSparkSink to be CRAM aware.

**Comment by cmnbroad** [comment]
The htsjdk and Hadoop-BAM parts of this are done (some refactoring will be needed for ReadSparkSink). The gating factor is getting Hadoop-BAM to move to Java 8 (this will be a topic for the call with Hadoop-BAM scheduled for 1/21) and upgrading to a newer htsjdk with ref-factored CRAM support. It would possible to implement this without that upgrade, but the it would require each partition to write a complete CRAM file, which would make the merging at the  end much less efficient.

**Comment by droazen** [comment]
This is done
