### ISSUE TITLE
gatk-launch usage output with no args is not clear

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#1286]
Its not clear what  the distinction is between "Tool" and "GATKTool", or "toolsArgs" vs "GATK arg 1".

**Comment by cmnbroad** [comment]
Note: this is based on the output from just running gatk-launch with no args. The output with --help is better.

**Comment by droazen** [comment]
I think the general format `gatk-launch Tool toolArgs -- sparkArgs` is pretty clear. Would this be solved by just making the terminology consistent (eg., change `Tool` to `GATKTool` etc.)?

**Comment by cmnbroad** [comment]
Changing "Tool" to "SparkTool" and using "toolArgs" for tool args and "sparkArgs" for spark args would help a lot.

**Comment by droazen** [comment]
alpha

**Comment by akiezun** [comment]
closed by #1345
