### ISSUE TITLE
gatk-launch should display a version #

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#1287]
which will be useful for field bug reporting.

**Comment by droazen** [comment]
alpha

**Comment by akiezun** [comment]
@cmnbroad can you clarify when you'd like to see the version number. When gatk runs it does print the version:
```
/gatk-launch FlagStat --input ./src/test/resources/org/broadinstitute/hellbender/tools/valid.bam
```

prints
```
... Version: Version:4.alpha.rc1-2-g29dfbf5-SNAPSHOT JdkDeflater
```

**Comment by cmnbroad** [comment]
I was expecting to see it with --version, or just running gatk-launch with no args. But as long as there is some way to get it - I missed it in the output.

**Comment by cmnbroad** [comment]
I see now that if you do "./gatk-launch PrintReads --version" you get the version, just not with just "./gatk-launch" with no tool.

**Comment by akiezun** [comment]
version without a tool is not very useful for debugging.
i'll close. reopen if I missed a useful usecase
