### ISSUE TITLE
The Spark/NonSpark tool distinction needs to be more obvious

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#1291]
Even if you know that only some tools are enabled for Spark, its not obvious how to find them. And the tool list has more than one Spark program group, which I didn't notice at first:

Spark Validation tools:                          Tools written in Spark to compare aspects of two different files
Spark pipelines:                                 Pipelines that combine tools and use Apache Spark for scaling out (experimental)
Spark tools:                                     Tools that use Apache Spark for scaling out (experimental)

**Comment by lbergelson** [comment]
@cmnbroad What's the suggestion here?  Move the spark tools so they're in the same groups as their non-spark counterparts?

**Comment by droazen** [comment]
The spark tools all end in `*Spark` and are in clearly marked groups that begin with `Spark*`, which seems pretty clear to me :)

**Comment by cmnbroad** [comment]
I think the program groups are a secondary issue; the primary one to me is that I don't think its obvious in general that some tools are Spark and some are not, unless you already know that. You have to read the whole tool list to see that some groups are spark and some are not.

**Comment by cmnbroad** [comment]
As for a suggestion, I'm not sure how to draw this out other than maybe in the gat-launch usage message.

**Comment by droazen** [comment]
This is the sort of thing that would be better described at the `README` / `Intro to the GATK` level rather than in the help output, I think.
