### ISSUE TITLE
spark tools should give a big warning that interval traversal is super slow

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1295]
using -L makes a huge different in speed for non-spark tools but much smaller for spark tools (due to https://github.com/HadoopGenomics/Hadoop-BAM/issues/34)

we should warn the users that this is the case

**Comment by droazen** [comment]
beta

**Comment by droazen** [comment]
Replaced by https://github.com/broadinstitute/gatk/issues/1399 -- closing
