### ISSUE TITLE
argument -V means different things in different tools

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1306]
in CountVariants -V means 'variant'

in IndexFeatureFile it seems to mean 'verbosity', see message below:

```
./gatk-launch IndexFeatureFile -V  /xchip/cga_home/akiezun/data/dbsnp_135.b37.excluding_sites_after_129.vcf
```

```
A USER ERROR has occurred: Invalid command line: Argument VERBOSITY has a bad value: /xchip/cga_home/akiezun/data/dbsnp_135.b37.excluding_sites_after_129.vcf. '/xchip/cga_home/akiezun/data/dbsnp_135.b37.excluding_sites_after_129.vcf' is not a valid value for LogLevel. Possible values: {ERROR, WARNING, INFO, DEBUG}```

**Comment by droazen** [comment]
This might be due to an unfortunate feature of our arg-parsing system that allows you to abbreviate argument names. Attempt a quick fix for alpha by adding an explicit `shortName` and `fullName` to the relevant arg.

**Comment by droazen** [comment]
Opened https://github.com/broadinstitute/gatk/issues/1347 for a definitive fix. As a quick fix I'll rename the `VERBOSITY` argument slightly.
