### ISSUE TITLE
weird message for CountVariants -L unmapped 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1309]
`A USER ERROR has occurred: Invalid command line: Argument -L/-XL has a bad value: unmapped. Currently the only way to view unmapped intervals is to perform a traversal of the entire file without specifying any intervals`

"unmapped intervals"?

**Comment by droazen** [comment]
beta

**Comment by droazen** [comment]
This one is no longer valid, since we've added `-L unmapped` support and the original error message has been removed.
