### ISSUE TITLE
SelectVariants should point to JEXL doc

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1313]
run `SelectVariants -select 'dbSNPBuildID=119'`

this blows up 
```
Invalid JEXL expression detected for select-0 with message ![0,18]: 'dbSNPBuildID = 119;' context is readonly
```

which is a suboptimal message - it should point to a doc to JEXL

(btw the fix seems to be to use `==` not `=`)

**Comment by droazen** [comment]
beta
