### ISSUE TITLE
should we have a generate_md5 option?

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1319]
picard tools have CREATE_MD5_FILE (even those in gatk)
gatk3 tools have generate_md5

but gatk4 walkers or spark tools don't offer this

**Comment by droazen** [comment]
Discussion for beta

**Comment by akiezun** [comment]
This may be a requirement for production. @eitanbanks, is it?

**Comment by eitanbanks** [comment]
Best person to ask is @ktibbett, but in general this is an extremely useful option.
