### ISSUE TITLE
CountReadsSpark does not print the result to stdout

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1325]
`./gatk-launch  CountReadsSpark --input hdfs:///user/akiezun/data/HCC1143_BL.bam -- --sparkRunner SUBMIT --sparkMaster yarn-client`

it runs for a while and prints no results

**Comment by droazen** [comment]
alpha

**Comment by akiezun** [comment]
i think this is just a limitation of running on the cluster - stdout gets lost somewhere. I'll close it
