### ISSUE TITLE
cram+spark+hdfs = hangs and blows up

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1326]
`/gatk-launch  CountReadsSpark --disableSequenceDictionaryValidation -R hdfs:///user/akiezun/data/human_g1k_v37.fasta --input hdfs:///user/akiezun/data/HCC1143_BL.cram -bps 1000000000 -- --sparkRunner SUBMIT --sparkMaster yarn-client --num-executors 36 --executor-cores 4 --executor-memory 16g`

hangs for a long time and then blows up (probably memory). The same exact command using bam file runs in 40seconds

**Comment by akiezun** [comment]
deep down in the guts of the logs i find this 

`Caused by: java.nio.file.NoSuchFileException: /local/dev/akiezun/bin/gatk/hdfs:/user/akiezun/data/human_g1k_v37.fasta`

this is super bizarre - it seems to want to treat the ref as a local file. (the same syntax works for ReadsPipelineSpark btw)

**Comment by droazen** [comment]
attempt to fix for alpha

**Comment by tomwhite** [comment]
@akiezun we still have the limitation that refs in CRAM are treated as a local file. We need a release of https://github.com/damiencarol/jsr203-hadoop so that HDFS works as a java.nio.file.Path implementation. Then we can include that JAR on the hellbender classpath and hdfs URIs will be loaded correctly.

**Comment by droazen** [comment]
Since this might require a patch to an external project to fix, moving to beta.

**Comment by droazen** [comment]
But adding `PRIORITY_HIGH` :)

**Comment by cmnbroad** [comment]
Another option is to invert the dependency by changing htsjdk.samtools.cram.ref.ReferenceSource to be an interface (which I've been lobbying the htsjdk CRAM developer to do independent of this issue) and change Hadoop-BAM to instantiate an implementation of that interface. I made the changes to all three layers locally to do this for non-HDFS references and the changes are pretty small. The interface itself is only one method:

**Comment by cmnbroad** [comment]
Its also worth pointing out that even though the ReferenceSource interface would probably be fairly narrow, the HDFS implementation would have to know how to find and process the corresponding index and dictionary, etc.

**Comment by tomwhite** [comment]
@cmnbroad +1 that sounds like a good solution to me.

BTW the maintainer of hadoop-jsr203 said he's trying to do a release soon: https://github.com/damiencarol/jsr203-hadoop/pull/13

**Comment by akiezun** [comment]
@tomwhite is this ticket related [Get Hadoop reference loading code into htsjdk](https://github.com/broadinstitute/gatk/issues/831) ?

**Comment by cmnbroad** [comment]
I tried using jsr-203 with Hadoop-BAM to create a cram reference source from HDFS, and it seems to work well (with the 2.0.1 version of htsjdk), so that does seem like the way to go. Its dependent on getting a release of jsr-203, and Hadoop-BAM needs to move to htsjdk 2.0.1+ and Java8. Then we can add the code to Hadoop-BAM to create the reference from a Path object from the hdfs URI.

**Comment by damiencarol** [comment]
I released a snapshot. A signed artifact will follow (1.0.0). Feel free to send me feedbacks BEFORE.
https://oss.sonatype.org/content/repositories/snapshots/com/github/jsr203hadoop/jsr203hadoop/0.0.1-SNAPSHOT/

**Comment by lbergelson** [comment]
@damiencarol Thanks for the release!  

I don't know if we'll be able to give you feedback about this until after the holidays.  I believe @tomwhite is on vacation and he's the one most involved with hadoop-bam.

**Comment by damiencarol** [comment]
no pb. But for me vacation means more time to finish the maven artifact release :D

**Comment by damiencarol** [comment]
Maven artifact for version 1.0.0 is deployed in a public repo:
https://github.com/damiencarol/jsr203-hadoop/issues/15

**Comment by droazen** [comment]
For alpha-1

**Comment by cmnbroad** [comment]
@tomwhite's PR to fix this in Hadoop-BAM is https://github.com/HadoopGenomics/Hadoop-BAM/pull/47. But it requires moving Hadoop-BAM up a Java version (I think it requires 7).

**Comment by cmnbroad** [comment]
Tom's PR bumps Java to 8, but IIRC I think this particular functionality only requires Java 7.

**Comment by tomwhite** [comment]
@cmnbroad Java 7 has the java.nio.file API that is required by hadoop-jsr203, but Java 8 is required because htsjdk needs Java 8 now.

**Comment by cmnbroad** [comment]
Closed via #1469.
