### ISSUE TITLE
Refactor gatk-launch to use argparse

### ISSUE THREAD

**Issue by laserson** [broadinstitute/gatk#1330]
And do a bit more cleanup

**Comment by droazen** [comment]
For beta

**Comment by lbergelson** [comment]
Shouldn't this be convert to argparse?  I think optparse is deprecated.

**Comment by droazen** [comment]
@lbergelson Is this still worth doing?

**Comment by droazen** [comment]
Not happening -- closing

**Comment by lbergelson** [comment]
Lets reconsider this because it's really dumb right now.

**Comment by laserson** [comment]
Dunno if it applies but I also really like http://click.pocoo.org/6/

But that would add a dependency...maybe not a problem for your build process though.

**Comment by jamesemery** [comment]
We are trying to get rid of the current incarnation of gatk-launch as it is. This is not a priority
