### ISSUE TITLE
gatk-launch -h doesn't always show the right info

### ISSUE THREAD

**Issue by laserson** [broadinstitute/gatk#1331]
If you haven't "built" the wrapper script, it complains.  Strictly speaking, if you're only ever going to use Spark, you don't need the wrapper.  The check should only happen if you choose the local walker impl.

```
[ec2-user@ip-10-1-1-71 gatk-4.alpha.rc1]$ ./gatk-launch -h
Missing GATK wrapper script: /home/ec2-user/gatk-4.alpha.rc1/build/install/gatk/bin/gatk
To generate the wrapper run:

    /home/ec2-user/gatk-4.alpha.rc1/gradlew installDist
```

**Comment by laserson** [comment]
Also, once you build the wrapper script, you get the main `gatk-launch -h` gives you the message with the big list of tools, rather than the launch script help, which requires `gatk-launch`

**Comment by lbergelson** [comment]
@laserson If you're running spark with the local[*] runner you need the wrapper script, since the spark jar doesn't include a copy of spark.

**Comment by lbergelson** [comment]
So we've had some debate over what the commands should be.  Definitely still subject to change.  

What's the right way to access the 
1.  help for gatk-launch itself
2.  tools list for gatk

currently `gatk-launch` displays it's own help, while `gatk-launch -help` passes through the help request to gatk which shows the tools list.

I don't think `gatk-launch --help` should ONLY display the help for gatk-launch, but we could change it to display the gatk-help followed by it's own help message.

**Comment by droazen** [comment]
How about having `gatk-launch` and `gatk-launch --help` both output the same `gatk-launch` help, PLUS a message stating `For a tool listing, run gatk-launch --list`?

**Comment by lbergelson** [comment]
That sounds fine.  What about run `gatk-launch --tools` instead?

**Comment by laserson** [comment]
Could we have all help messages display all the information?

**Comment by laserson** [comment]
But if not, I support having a separate option specifically for a tool listing.

**Comment by droazen** [comment]
I think if all the help options displayed everything the tool listing would dwarf the other info, so my preference would be for an explicit `gatk-launch --list` (or `--tools`), with prominent mention of that option in the output of both `gatk-launch` and `gatk-launch --help`

**Comment by laserson** [comment]
+1
