### ISSUE TITLE
gatk-launch should append a / as needed to GATK_GCS_STAGING

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1338]
Currently GATK_GCS_STAGING requires a full bucket path with a trailing /.

i.e. `GATK_GCS_STAGING=gs://hellbender/staging/`

it should be modified to detect the absence of the `gcs://` prefix and the trailing `/` and correctly function with options of the following form

`gs://hellbender/staging`
`hellbender/staging/`
`hellbender/staging`

**Comment by davidbenjamin** [comment]
Closed by #5452.
