### ISSUE TITLE
Have picard tools throw UserExceptions for file not found instead of SAMExceptions

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1340]
Picard tools throw a `SAMException` in cases where the input files are not found.  We should catch these and convert them to `UserExceptions`

Relates to #1290

**Comment by droazen** [comment]
Obsolete, closing

**Comment by lbergelson** [comment]
@droazen Are we going to port UserExceptions to picard?  It seems like a good idea...

**Comment by magicDGS** [comment]
For me it looks like a good idea to move the `UserExceptions` to Barclay, even if it is not handled there. It will be easier also for the development of toolkits using Barclay without dependence in GATK/HTSJDK.

**Comment by lbergelson** [comment]
Yeah, that seems like a good idea.  It's a really useful concept I think.
