### ISSUE TITLE
ReadsSparkSinkUnitTest.readsSinkTest[3] is to slow

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1342]
One unit test (`ReadsSparkSinkUnitTest.readsSinkTest[3]`) takes ~1/4 of our test time at around 4-5 minutes when running on travis.

It only takes ~20s on my local machine, so I suspect it may be running out of memory on travis and spending all of it's time thrashing, garbage collecting, and spilling to disk.   

We should either remove this tests or figure out how to fix it.

**Comment by droazen** [comment]
It's using one of the large files (`NA12878_20_21_WGS_bam`), so not surprising that it's slow. We might be able to just remove it, as the test case just before it (for `CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam`) proved sufficient on its own to detect the recent ordering bugs in `ReadsSparkSink`

**Comment by lbergelson** [comment]
@droazen It's just a bit strange that it goes from 20s on local machines to 5 minutes on travis.  Must be memory.  Or some critical spark performance bug we haven't seen before "_"
