### ISSUE TITLE
Disable argument abbreviation in joptsimple

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1347]
Argument abbreviation is causing confusing issues like https://github.com/broadinstitute/gatk/issues/1306, where `-V` means different things in different tools. Let's disable it in `joptsimple` (or, if there's no mechanism to disable it, ask the author to add one).

**Comment by lbergelson** [comment]
I patched this in joptSimple in https://github.com/pholser/jopt-simple/pull/89.  This can be enabled by upgrading to the 5.0.1-beta build or waiting for a stable release.  Unclear on the time lines for stable release.  I suspect if we really need it we can ask for a 4.10 release and the maintainer would likely be willing to create one.
