### ISSUE TITLE
Consider renaming --sparkRunner to --runner

### ISSUE THREAD

**Issue by laserson** [broadinstitute/gatk#1357]
Following up on #1329 and #1355.  This would make the most sense if `DIRECT` were limited to running only non-Spark walker impls.

**Comment by droazen** [comment]
Non-Spark walker implementations don't need a --runner argument at all (and shouldn't as we want them to be as easy to run as their GATK3 counterparts).

I vote no on the `--sparkRunner` -> `--runner` rename, as I think our users are mostly unfamiliar with Spark, and it's good to be clear about what is a Spark argument and what is a tool argument.

**Comment by laserson** [comment]
I'm +1 on @droazen if the default doesn't actually let you run Spark.  I would think that could lead to some confusion otherwise.

**Comment by droazen** [comment]
Closing, since the consensus seems to be against making this change.
