### ISSUE TITLE
port GatherBQSRReports

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1372]
port `GatherBQSRReports` from GATK3.

**Comment by akiezun** [comment]
high-prio because it's really an oversight for alpha

**Comment by vdauwera** [comment]
You mean this?

https://github.com/broadinstitute/gsa-unstable/blob/master/protected/gatk-tools-protected/src/main/java/org/broadinstitute/gatk/tools/GatherBqsrReports.java

**Comment by vdauwera** [comment]
(funny thing, I thought I was in gsa-unstable and you wanted to port this from GATK4 to GATK3 ... clearly I need some caffeine because in what universe does that make sense?)

**Comment by akiezun** [comment]
@lbergelson what's the status here?

**Comment by lbergelson** [comment]
I need to finish up the tests for this one.

**Comment by akiezun** [comment]
happy to review this when ready

**Comment by akiezun** [comment]
from @lbergelson 
```
./gatk-launch BaseRecalibrator -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -O gatk4.tbl --knownSites src/test/resources/large/dbsnp_138.b37.20.21.vcf -R src/test/resources/large/human_g1k_v37.20.21.fasta

./gatk-launch BaseRecalibrator -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -O gatk4_chr20.tbl --knownSites src/test/resources/large/dbsnp_138.b37.20.21.vcf -R src/test/resources/large/human_g1k_v37.20.21.fasta -L 20
./gatk-launch BaseRecalibrator -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -O gatk4_chr21.tbl --knownSites src/test/resources/large/dbsnp_138.b37.20.21.vcf -R src/test/resources/large/human_g1k_v37.20.21.fasta -L  21
./gatk-launch GatherBQSRReports -I gatk4_chr20.tbl -I gatk4_chr21.tbl -O gatk4_combined.tbl
```

the problem is that these tables (gatk4_combined.tbl and gatk4.tbl ) are different (and they are also different in gatk3)
