### ISSUE TITLE
Experiment with Graphite and Grafana for profiling Spark tools

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1377]
http://www.hammerlab.org/2015/02/27/monitoring-spark-with-graphite-and-grafana/

the task here to set this up and, if it's useful, update the readme on how to set it up and use

@laserson do you have experience with Graphite and Grafana

**Comment by akiezun** [comment]
the setup for this seems like a huge ordeal. I'll shelve it for now

**Comment by hammer** [comment]
In the future y'all can just email me if you're interested in our use of Spark for genomics hammer@cloudera.com

**Comment by akiezun** [comment]
thanks @hammer, let's follow up offline
