### ISSUE TITLE
PrintReads will silently fail to run BQSR if it is compiled as a public only GATK instance

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#1384]
_From @lbergelson on July 20, 2015 18:22_

`PrintReads` allows `--BQSR` to be specified even if it is compiled with out BQSR available.  This means that a public only compilation of gatk will look like it can perform BQSR, but silently fails to do so.  A check should be added so that `PrintReads` will throw a `UserException` if BQSR is requested but not available.

- [ ] When implemented (if not already fixed in G4), open an issue in gsa-unstable to have the fix backported to G3. 

_Copied from original issue: broadinstitute/gsa-unstable#1058_

**Comment by lbergelson** [comment]
@vdauwera This isn't relevant to gatk4.

**Comment by vdauwera** [comment]
Ah ok, thanks.
