### ISSUE TITLE
bug in BaseRecalibratorSpark

### ISSUE THREAD

**Issue by dnaase** [broadinstitute/gatk#1386]
Here is my command:
spark-submit --driver-memory 8G --master local[1] --conf spark.kryoserializer.buffer.max=512m --conf spark.driver.maxResultSize=0 --conf spark.driver.userClassPathFirst=true --conf spark.executor.userClassPathFirst=true --conf spark.io.compression.codec=lzf --conf spark.yarn.executor.memoryOverhead=600 gatk-4.alpha/build/libs/gatk-all-version-unknown-SNAPSHOT-spark.jar BaseRecalibratorSpark -knownSites test.vcf -R hg19_rCRSchrm.2bit -I test.bam -O test.txt

The error msg is:
java.lang.ClassCastException: org.broadinstitute.hellbender.utils.variant.MinimalVariant cannot be cast to htsjdk.samtools.util.Locatable
	at org.broadinstitute.hellbender.utils.collections.IntervalsSkipList.<init>(IntervalsSkipList.java:35)
	at org.broadinstitute.hellbender.engine.spark.BroadcastJoinReadsWithVariants.join(BroadcastJoinReadsWithVariants.java:22)
	at org.broadinstitute.hellbender.engine.spark.AddContextDataToReadSpark.add(AddContextDataToReadSpark.java:35)
	at org.broadinstitute.hellbender.tools.spark.BaseRecalibratorSpark.runTool(BaseRecalibratorSpark.java:91)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:257)

It seems like BroadCast strategy in BaseRecalibratorSpark has some bugs when trying to join variants with reads. 

i can see that Variant is implements from htsjdk.samtools.util.Locatable, but why it still have some problem there?

Is it because that somehow in some java environment, this clause will cause problem?
 final IntervalsSkipList<Variant> variantSkipList = new IntervalsSkipList<>(variants.collect());

And it should be this assertion:
final IntervalsSkipList<Variant> variantSkipList = new IntervalsSkipList<Variant>(variants.collect());

I use java 1.8.0_66

**Comment by lbergelson** [comment]
Hello,  we've seen similar problems using spark submit with the local master. Could you try running using gatk-launch with --sparkRunner DIRECT 

Or alternatively running the jar directly without using spark submit.

**Comment by lbergelson** [comment]
I believe this is the same issue as #1315. We need to either fix this or have gatk-launch detect and disallow local.

**Comment by dnaase** [comment]
Value: DIRECT is not a valid value for --sparkRunner.  Choose one of LOCAL, SPARK, GCS

in the released gatk-launch, there is no DIRECT option for --sparkRunner

**Comment by dnaase** [comment]
Ah, i see. DIRECT is the old version of LOCAL. But when i run in LOCAL, it is just run local walker, not the spark mode at all... I just want to test some sparkWalker...

**Comment by lbergelson** [comment]
Ah, I forgot we renamed it. If the tool is a spark tool running with LOCAL should run it using spark. It uses the included spark instead of the system spark.

**Comment by dnaase** [comment]
I found this online., this might be the reason why use include spark is different from system spark in this case.

In spark, when i try to cast the  variable to the same 'class' (with exact the same class name, in this case, you could try to cast any "Variant" to "Variant" in BroadcastJoinReadsWithVariants ), it always throw out the class exception error. It is because that "The equality of two classes in Java depends on the fully qualified name and the class loader that loaded it."
In system spark, it might split the JVM, which is means it may cause problem to identify if it is the same class?

This is what i test in spark:
List<Variant> vs = variants.take(10);
        MinimalVariant v = (MinimalVariant) vs.get(0);
        
this will throw ClassCastException error...

http://stackoverflow.com/questions/826319/classcastexception-when-casting-to-the-same-class
