### ISSUE TITLE
Promote ``ParamUtils.writeStringListToFile(...)`` to ``gatk`` repo from ``gatk-protected``

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#1387]
This method simply writes a list of strings (one per line) to a text file.  Does such a thing already exist in gatk?  If not, we can move ``ParamUtils.writeStringListToFile(...)`` to ``Utils.writeStringListToFile(...)`` (or similar).

**Comment by lbergelson** [comment]
This sounds like a very specific function, and I don't see it in ParamUtils...

`org.apache.commons.io.FileUtils.write(strings.join('\n'))` accomplish the same thing?

If you want to move it into hellbender, `IOUtils` is probably the right place for it.

**Comment by akiezun** [comment]
closing as part of https://github.com/broadinstitute/gatk/issues/1427
