### ISSUE TITLE
migrate dev wiki from gsa-unstable

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1388]
selected articles from https://github.com/broadinstitute/gsa-unstable/wiki are relevant to gatk4 and should be migrated

the task here is to review the wikis and select the relevant ones and migrate them here. I'm not sure if wiki is the right format though because it's not version controlled as files

**Comment by vdauwera** [comment]
Actually the github wikis are git repos themselves and the pages are stored as md files; you can clone them and do all the things you'd normally do with git, if that's how you choose to interact with them.

**Comment by droazen** [comment]
These all look obsolete to me -- closing in favor of https://github.com/broadinstitute/gatk/issues/1016
