### ISSUE TITLE
protect against regressions involving hdfs

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1391]
we need tests that will protect us from regressions like #1390 - we must test on hdfs, on travis or elsewhere

**Comment by akiezun** [comment]
@tomwhite can you recommend an approach to this?

**Comment by tomwhite** [comment]
@akiezun you can use a `MiniDFSCluster` to run an HDFS cluster in the local JVM. See MetricsUtilsTest and BucketUtilsTest for how to do this.

**Comment by droazen** [comment]
Closing as dupe of https://github.com/broadinstitute/gatk/issues/1402
