### ISSUE TITLE
create a "smoke test" for cluster upgrades

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1392]
we need a canonical set of tests that we run when we upgrade the cluster. We've been running terasort but it's not enough: 1) it does not run our code and 2) it does not even run java8 (recent config error when 2 nodes were running java7 was undetected).

The task here is to write, in readme or in scripts directory, a script or set of scripts that must be run after every change to the cluster.

**Comment by droazen** [comment]
Closing as obsolete
