### ISSUE TITLE
Spin up a public jenkins server for long-running validation tests (and other tests that can't or shouldn't run in travis), or switch from travis to a more flexible CI provider

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1400]
We want something like a hosted jenkins server to run parts of the test suite that can't or shouldn't be run in travis. This includes:

-Long-running validation tests, like those designed by @davidadamsphd for the `ReadsPipelineSpark`
-Tests involving reading data from HDFS.

**Comment by droazen** [comment]
For alpha-1.

**Comment by droazen** [comment]
Alternatively, we could switch from travis to another CI provider that allows us to do the things we can't currently do in travis.

**Comment by droazen** [comment]
Will this be happening for alpha-1?

**Comment by akiezun** [comment]
@lukwam what's your estimate for the jenkins instance?

**Comment by lukwam** [comment]
I have been out the last couple of days but the estimate at the strategy
board should have been this week.
On Thu, Mar 10, 2016 at 09:23 Adam Kiezun <notifications@github.com> wrote:

> @lukwam <https://github.com/lukwam> what's your estimate for the jenkins
> instance?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gatk/issues/1400#issuecomment-194869856>
> .
>
-- 
Lukas Karlsson, Lead Architect, DevOps
Broad Institute of MIT and Harvard
75 Ames Street, 11129, Cambridge, Massachusetts 02142
karlsson@broadinstitute.org, +1.6177147142

**Comment by lbergelson** [comment]
This is now up and running at [gatk-jenkins.broadinstitute.org](http://gatk-jenkins.broadinstitute.org) thanks to work by @mmonnar.

**Comment by akiezun** [comment]
@lbergelson the tests are not running on [gatk-jenkins.broadinstitute.org](url) so it's not usable yet. What remains to be done?
