### ISSUE TITLE
Run validation tests continuously in jenkins: ReadsPipelineSpark, BQSR etc

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1401]
The new validation tests for `ReadsPipelineSpark` should be easily runnable in either a push-button fashion or on a set automatic schedule (nightly or weekly) via a jenkins server.

Depends on https://github.com/broadinstitute/gatk/issues/1400

**Comment by akiezun** [comment]
It should include other tests too, eg BQSR

**Comment by droazen** [comment]
alpha-2

**Comment by akiezun** [comment]
is this done?

**Comment by akiezun** [comment]
i will send the rigght commandlines to @davidbernick

**Comment by akiezun** [comment]
this is blocked until https://github.com/broadinstitute/gatk/pull/1921 is in and https://github.com/broadinstitute/gatk/pull/1922 is fixed

**Comment by akiezun** [comment]
spilling over

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/2288
