### ISSUE TITLE
Run spark tests on HDFS via jenkins

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1402]
We've recently had some bugs that would have been caught if we had tests that ran on HDFS. Since these probably can't run in travis, let's run them via the public jenkins server we're going to set up for non-travis testing (https://github.com/broadinstitute/gatk/issues/1400).

**Comment by droazen** [comment]
From @tomwhite: "you can use a MiniDFSCluster to run an HDFS cluster in the local JVM. See MetricsUtilsTest and BucketUtilsTest for how to do this."

**Comment by akiezun** [comment]
needs @davidbernick to help

**Comment by akiezun** [comment]
This is redundant with https://github.com/broadinstitute/gatk/issues/1609 because https://github.com/broadinstitute/gatk/issues/1609 will run spark tools on hdfs for performance. Closing this one.
