### ISSUE TITLE
Tune the split size and number of reducers for spark tools (sensible defaults + ability to override)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1403]
From @tomwhite:

What we can do though is take another look at why we need such a small split size and see if we can increase it (by better tuning etc). Even if we can't we know that some for some classes of jobs (e.g. metrics) we can use the default split size without an issue, so we could add logic to choose an appropriate split size based on the type of job.

Thinking about this a bit more, we're actually quite close to a solution. In the existing Spark Mark Duplicates implementation, for example, you can set the parallelism (with -P). By default it is the same as the number of input partitions, but if the partitions are too large then each reducer has too much data to deal with and the job fails. This is why we made the number of partitions large by reducing the split size to 10MB.

However, by increasing the number of reducers (by setting -P to be input data size/10MB), the input split size can be increased to its default of 128MB without causing a problem.

So I think the work here is to work out a good set of defaults and the smallest number of knobs to override them. For example, I think we could always use the default split size, have some heuristics to choose a good value for the parallelism, and allow it to be overridden with -P.

We should also decouple the parallelism and whether the output is a single file. For ReadsPipelineSpark we have -shardedOutput, but not for MarkDuplicatesSpark (where it's signalled by -P 1), so we should make this consistent.

**Comment by droazen** [comment]
For alpha-1 and @tomwhite

**Comment by droazen** [comment]
Ideally this should be implemented in a shared way across tools for consistency (eg., in a base class if possible).

**Comment by tomwhite** [comment]
I posted a first attempt at this here: https://github.com/broadinstitute/gatk/pull/1432

**Comment by tomwhite** [comment]
Fixed in #1432.
