### ISSUE TITLE
SimpleInterval#getSpanningOverlap NPE

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#1405]
This public method will fail with an NPE if the input list is null or if contains any null.
It should throw a IAE instead.

**Comment by pasculorente** [comment]
Hi,
did you mean getSpanningInterval(locations)?
What about
```java
if (locations == null) {
  throw new IllegalArgumentException("locations cannot be null");
}
```
at the start of the function, and
```java
if (l == null){
  throw new IllegalArgumentException("a location cannot be null");
}
```
at the beginning of the loop?

**Comment by pasculorente** [comment]
Hi,
did you mean getSpanningInterval(locations)?
What about
```java
if (locations == null) {
  throw new IllegalArgumentException("locations cannot be null");
}
```
at the start of the function, and
```java
if (l == null){
  throw new IllegalArgumentException("a location cannot be null");
}
```
at the beginning of the loop?

**Comment by lbergelson** [comment]
@pasculorente Sorry no one replied before.  Thanks for the input.   You're always welcome to submit pull requests if you have solutions to an issue!  I think this is getting fixed already, but feel free to contribute if you feel like it.
