### ISSUE TITLE
Add ability to get queryname-sorted reads from Hadoop-BAM (for MarkDuplicates), and eliminate one shuffle from MarkDuplicatesSpark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1411]
We want the ability to get queryname-sorted reads from Hadoop-BAM, so that we can eliminate one of the shuffles in `MarkDuplicatesSpark`. This will probably involve implementing a custom partitioner that ensures that reads always end up in the same partition as their mates.

**Comment by droazen** [comment]
For @tomwhite

**Comment by tomwhite** [comment]
I've implemented the required change in Hadoop-BAM (https://github.com/HadoopGenomics/Hadoop-BAM/pull/49), but I'm not exactly sure what needs doing on the GATK side. @droazen, can you suggest a test I could write (and some suitable test data) to complete this? Thanks.

**Comment by droazen** [comment]
@tomwhite On the GATK side, I think the steps are:

1. Rev our Hadoop-BAM dependency once https://github.com/HadoopGenomics/Hadoop-BAM/pull/49 is in.

2. Take one of our existing test inputs and create a copy of it sorted by query name using the hellbender tool `SortSam`. I think a good file to use would be `src/test/resources/org/broadinstitute/hellbender/tools/BQSR/CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.noMD.noBQSR.bam`, as that file hasn't had either MD or BQSR run on it, and it's the primary input in the `ReadsPipelineSparkIntegrationTest`.

3. Before making any actual changes to MarkDuplicatesSpark, write a new integration test proving that MarkDuplicatesSpark can read in the queryname-sorted bam above, and produces the same result as when run on the coordinate-sorted version of the bam. The output in both cases when running with `--shardedOutput false` should be a coordinate-sorted bam.

4. Now the potentially tricky part: in `MarkDuplicatesSpark`, we want to detect queryname-sorted reads using the `SAMFileHeader` SO attribute (`SAMFileHeader.getSortOrder()`), and if we have them, avoid performing the first `groupByKey()` operation in `MarkDuplicatesSparkUtils.transformReads()`, instead relying on the natural ordering of the reads to create the `PairedEnds` objects.

5. Make sure that the test you wrote in step 3 doesn't break after doing step 4 :)

**Comment by droazen** [comment]
@laserson Adam mentioned that you might have insight into this ticket. Do you want to have a look at Tom's PR to Hadoop-BAM (https://github.com/HadoopGenomics/Hadoop-BAM/pull/49) and see if it looks sane? Do you have any thoughts on how `MarkDuplicatesSpark` could be modified once this change is in to take advantage of the queryname sorting and eliminate that first shuffle?

**Comment by tomwhite** [comment]
Thank you for the detailed steps @droazen! I have implemented this following your suggestions. See #1429.

Interestingly, it passes even without my changes from https://github.com/HadoopGenomics/Hadoop-BAM/pull/49, but that's because the BAM isn't split in such a way so as to have a pair in different splits. Achieving this is actually rather tricky for real BAMs, but it's tested in Hadoop-BAM by constructing an artificial BAM file with this property, so that should be sufficient.

**Comment by tomwhite** [comment]
Fixed in #1429.
