### ISSUE TITLE
Validate the walkers BaseRecalibrator/ApplyBQSR for production

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1413]

**Comment by droazen** [comment]
Depends on https://github.com/broadinstitute/gatk/issues/1414

**Comment by akiezun** [comment]
The plan is as follows
- [ ] copy 1 WGS file (NA12878) to local drive for speed:  /seq/picard_aggregation/G77386/NA12878/v1/NA12878.bam
- [ ] revert qualities to original using GATK4 RevertBaseQualityScores 
- [ ] run GATK3 BaseRecalibrator on the bam non-split (measure time too)
- [ ] run GATK4 BaseRecalibrator on the bam non-split (measure time too)
- [ ] compare tables. If different: loop fix and rerun until same
- [ ] run GATK3 PrintReads (measure time)
- [ ] run GATK4 ApplyBQSR (measure time)
- [ ] compare resulting bams using GATK4 CompareBaseQualities
- [ ] if different, loop fix and rerun until same

@eitanbanks that works?

**Comment by eitanbanks** [comment]
Yup, looks reasonable

**Comment by akiezun** [comment]
status: BQSR tables differ but just a tiny bit
differences in observations are on the order of 10^-9 (relative differences)

First table:
QuantizedScore correlation 0.9999333
QuantizedScore: summary of relative differences:
```
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
0.0000000 0.0000000 0.0000000 0.0006863 0.0000000 0.0322600
```

Second table:
all values the same

Third table:
Observations: summary of distro of relative diffs
```
Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
3.694e-10 3.472e-09 9.997e-09 3.990e-08 3.487e-08 2.045e-07
```

Errors: summary of distro of relative diffs
```
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
0.000e+00 0.000e+00 0.000e+00 3.172e-11 0.000e+00 5.352e-10
```

Fourth table:
Observations: summary of distro of relative diffs:
```
     Min.   1st Qu.    Median      Mean   3rd Qu.      Max.
0.000e+00 1.592e-10 4.776e-10 3.459e-09 2.229e-09 2.297e-07
```

Errors: no differences

Time (user time as reported by 'time -v') shows 20% difference:
GATK3 97670.95 seconds 
GATK4 78443.87

Percent of CPU this job got
GATK3 135%
GATK4 111%

Memory is very similar, this is before recent improvements. Maximum resident set size
GATK3 48.98 GB
GATK4 48.19 GB

**Comment by eitanbanks** [comment]
In other words: epsilon.  Looks good to me.

**Comment by akiezun** [comment]
ok, I bet it's due to some minute differences in filtering of reads. I'm not going to investigate unless someone objects

**Comment by eitanbanks** [comment]
No objections from me

**Comment by akiezun** [comment]
md5 may be a requirement #1319 because production uses the `generate_md5` flag in gatk3

**Comment by akiezun** [comment]
ApplyBQSR (aka PrintReads) is done. Performance stats look very good.

user time, gatk4 is 37% better
GATK3 57555.36 seconds
GATK4 35718.76 seconds  

and that's using less CPU: "Percent of CPU this job got"
GATK3 121%
GATK4 106%

Maximum resident set size (kbytes) - gatk4 uses 82% less memory
GATK3 84675872 kbytes
GATK4 14657904 kbytes

**Comment by droazen** [comment]
That's awesome, but are you sure those memory numbers are right? GATK3 uses 84675872 kbytes = 84 GB?

**Comment by akiezun** [comment]
Don't know - that's whatever `time -v` outputs. I'm not sure what exactly it means.

**Comment by akiezun** [comment]
Tie-out status: gatk4 filters out 319 reads (compared to 0 in gatk3 ) - out of 953543105 total. 
First read. I'm guessing it's the `61S90I` that triggers the filter. 

```
H22NGALXX141215:1:2116:28232:43888	1171	1	13984870	50	61S90I	=	13984520	-350	GGCCACCCCCCCCCCGGCCCCGCCGCGCCGTCCGGCAGGCGAGGCGCGCCTCTCCCCCCCCGCCCCTACTGGGAAGTGAGGAGCCCCTCCGCCCGGCCAGCCGCCCCATCCAGGAGGGAGGTGGGGGGGTCAGCCCCCCGCCCGGCCAGCC	###########################################################A<<KFA<7,,,AK<,F7,A,,F(<FFAF,<((KKA(F7(<AKFFKKKFAKKKKKKKKKKKKKKKKF<FFKKFAFFFKKFKKKKKKKKFFFAA	MC:Z:151M	OC:Z:61S90M	PG:Z:MarkDuplicates.4	RG:Z:H22NG.1	NM:i:90	MQ:i:60	OQ:Z:###########################################################A<<KFA<7,,,AK<,F7,A,,F(<FFAF,<((KKA(F7(<AKFFKKKFAKKKKKKKKKKKKKKKKF<FFKKFAFFFKKFKKKKKKKKFFFAA	UQ:i:0	AS:i:80
```

**Comment by eitanbanks** [comment]
This is great stuff.  Am curious about the memory too given David's question.  But very happy.

**Comment by akiezun** [comment]
I think it still needs to be run through an QA process independent from the dev team . There may be options, details etc that we don't do exactly how production does. Things coming to mind (there's surely much more):
- test splitting input in in many ways (the same exact way as production does)
- generation of md5 (we're not doing it yet)
- the PG tag in the header (we're not writing one yet)
- validate that the original qualities are preserved exactly (i;ve not done it as part of this validation)
- testing memory consumption and resource consumption - that's something that only someone close to production can measure/answer in the same environment in which production runs. I'm running on very different env.

etc.

**Comment by eitanbanks** [comment]
I think that you should test the first thing (you don't need to scatter exactly the same way as prod in order to test; just make sure it works for you) and then do the middle 3 things (which all should be fairly easy).  I do not think that we need to do the last bullet other than what you are seeing on your test data (really, just addressing David's point above is enough).

**Comment by akiezun** [comment]
Results are in: we have 0 differences out of 142779553658 recalibrated base qualities compared to GATK3

**Comment by akiezun** [comment]
todos:
md5: https://github.com/broadinstitute/gatk/issues/1319
pg: https://github.com/broadinstitute/gatk/issues/1527
gatherbqsrreports: https://github.com/broadinstitute/gatk/issues/1372

**Comment by akiezun** [comment]
boom, this is done

**Comment by lbergelson** [comment]
woo!

**Comment by eitanbanks** [comment]
Yay!
@akiezun @yfarjoun should we take this in now to GotC or wait until the BAQ stuff is purged?

**Comment by yfarjoun** [comment]
Since this is not a scientific question, I defer to others!

**Comment by eitanbanks** [comment]
This is a good point.  I made a note to discuss with Kathleen.
