### ISSUE TITLE
make BaseRecalibrator table sorting the same as Gatk3

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1416]
Gatk4 bqsr recalibration tables sort the `EventType` in the order `MID` instead of `MDI` as gatk3 does.  This could likely be changed by reordering the enum.

gatk4 bqsr also sorts the ReadGroup column differently.  Gatk3 appears to be lexicographically sorted while gatk4 does not appear to be sorted in any meaningful way.

These two differences make diffing tables produced by gatk3 and gatk4 more difficult.

**Comment by akiezun** [comment]
do you have an example input? for me it sorted the same way.

**Comment by lbergelson** [comment]
@akiezun using the same command lines from #1414 

I get different sorting with / without --sort_by_all_columns
```
./gatk-launch BaseRecalibrator -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -O gatk4.tbl --knownSites src/test/resources/large/dbsnp_138.b37.20.21.vcf -R src/test/resources/large/human_g1k_v37.20.21.fasta
```
```
java -jar ~/Workspace/GenomeAnalysisTK.jar -T BaseRecalibrator -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -o gatk3.tbl --knownSites src/test/resources/large/dbsnp_138.b37.20.21.vcf -R src/test/resources/large/human_g1k_v37.20.21.fasta --sort_by_all_columns

**Comment by akiezun** [comment]
is that not expected to get different sorting depending on `sort_by_all_columns`?
BTW, running without sort_by_all_columns seems silly - let's fix it to `true` and remove the option: see https://github.com/broadinstitute/gatk/issues/1418

**Comment by lbergelson** [comment]
I meant that if I neither gatk3 with `sort_by_all_columns` nor gatk3 without `sort_by_all_columns` matches the sorting i see from gatk4.

**Comment by lbergelson** [comment]
Ack.  I didn't realize that gatk4 needed sort_by_all_columns as well...  I thought that was some bogus thing from gatk3 only.  Sorting matches once I enable it on both gatk3 and gatk4.
