### ISSUE TITLE
Add support for java.nio.file.Path to SamReaderFactory in htsjdk

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1426]
We want to add an overload of `SamReaderFactory.open()` in htsjdk that accepts a `java.nio.file.Path`, and uses `Files.newInputStream(path)` or similar to get an `InputStream` from it and return a SAM/BAM/CRAM reader. This should enable us to transparently load reads from any input source for which there is a Java NIO file system provider available. Such a provider is already implemented for HDFS (https://github.com/damiencarol/jsr203-hadoop). There may be one for GCS as well (and if there isn't, it might be simple to implement one).

Note that this feature needs to handle the companion index as well, if present. Also note that we should not add any new dependencies to htsjdk as part of this change.

This change should be modeled on the equivalent change @tomwhite recently made for the reference classes in htsjdk (https://github.com/samtools/htsjdk/pull/308).

The unit tests in htsjdk for this feature can be very simple -- just take existing `File` arguments to test cases and call `toPath()` on them, and make sure the existing test cases pass. 

On the GATK side, we'd want tests to make sure that we can use the new `SamReaderFactory.open()` overload to open BAM/SAM/CRAM files locally, on HDFS, and on GCS. If it turns out that there isn't already a Java NIO provider for GCS and it's non-trivial to implement, that could become a separate ticket.

**Comment by droazen** [comment]
@davidadamsphd Have a look at this one and let me know whether you think it's doable as a 20% project. @tomwhite should be able to offer guidance on how to implement this, since he contributed the reference version of this in https://github.com/samtools/htsjdk/pull/308

**Comment by droazen** [comment]
Re-assigning this one to @tomwhite, since he's almost out of tickets, and this is related to work he's already started.

**Comment by tomwhite** [comment]
I submitted https://github.com/samtools/htsjdk/pull/458 for the htsjdk side.

**Comment by tomwhite** [comment]
Fixed in https://github.com/samtools/htsjdk/pull/458.
