### ISSUE TITLE
Move classes of general utility (new walker types, utilities for working with particular formats, etc.) from protected to public

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1427]
We want the public GATK framework to contain all the generic capabilities for loading and traversing data in various formats -- all new walker types, general-purpose utilities for working with different formats, etc. should ideally live in the framework rather than in protected. Moving these classes to public should also improve code quality by preventing general-purpose code from getting embedded within particular tools, and would encourage the development of clear APIs for using this code.

@akiezun since you love to rip code out, you get this one :) You should consult with @LeeTL1220 and @vruano to identify which classes should be moved. If the classes to be moved have already been adequately reviewed and are covered by tests, they shouldn't require a re-review (though we can do one if @LeeTL1220 requests it).

**Comment by droazen** [comment]
For @akiezun (in consultation with @LeeTL1220)

**Comment by akiezun** [comment]
this is probably best done by @vruano when moving germline CNV code to public.

**Comment by akiezun** [comment]
@droazen @vruano what's the plan there? Is the code stable enough to start moving pieces?
FeatureWalker and TargetWalker seem to be stable, as is the codecs package, SVD+PCA

**Comment by droazen** [comment]
@akiezun Let's do this after the HaplotypeCaller is merged/moved, and https://github.com/broadinstitute/gatk/issues/1676 is done.

**Comment by akiezun** [comment]
i'll grab this

**Comment by akiezun** [comment]
this will continue. moving to alpha-3

**Comment by akiezun** [comment]
closing this - i think PCA and TSV is enough for now
