### ISSUE TITLE
Write tests for Hadoop-BAM to build expertise in that codebase

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1440]
Test coverage on the Hadoop-BAM project is currently an abysmal 26% (https://github.com/HadoopGenomics/Hadoop-BAM/issues/51). Let's contribute some tests to both bring this number up and build our own expertise in that codebase.

**Comment by droazen** [comment]
After writing tests, should present to the rest of the team to spread the knowledge :)

**Comment by cmnbroad** [comment]
Update: @tomwhite and I have both added new tests recently, but we're still at about 38%.

**Comment by droazen** [comment]
This is an ongoing task that we'll want to continue in alpha-2

**Comment by droazen** [comment]
@tomwhite How's the test coverage in Hadoop-BAM these days?

**Comment by tomwhite** [comment]
@droazen it's at 60% (see badge on https://github.com/HadoopGenomics/Hadoop-BAM), which is pretty good, given that it started out <30%.

Also, @cmnbroad has contributed several patches to the project, and is now a committer.

For these reasons I'm going to close this issue.
