### ISSUE TITLE
Improve Hadoop-bam error message in createRecordReader

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1452]
Hadoop bam `AnySAMInputFormat.createRecordReader` throws `IllegalArgumentException` if it can't determine the format of a sam/bam file.  If this is caused by a nonexistant file it hides the `FileNotFoundException` which would be a more useful error message.  

This cropped up in a case where a file local to one machine was being specified as an input a spark cluster with multiple nodes.  The file existed for the master node, but the workers failed because it was unavailable to them.  

It would be helpful if the error message mentioned this possibility. 

see #1417 for the original issue

**Comment by droazen** [comment]
Should this be filed against Hadoop-BAM rather than us?

**Comment by lbergelson** [comment]
Yes.  I'll file one there too.

**Comment by akiezun** [comment]
let's close this - this is a dup of #1417.
