### ISSUE TITLE
Add methods to SparkCommandLineProgram that let you query the amount of memory available per executor / per core

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1456]

**Comment by droazen** [comment]
Requested by @tedsharpe as part of his SV work.

**Comment by droazen** [comment]
@tomwhite Do you know an easy way to do this? Assigning to you for alpha-1.

**Comment by tomwhite** [comment]
Do you want a way to retrieve the memory that has been set via `--executor-memory`? It would be good to understand the motivation behind this.

**Comment by droazen** [comment]
@tomwhite Yes, exactly, we want to retrieve the `--executor-memory` setting at runtime. I believe @tedsharpe wants to explore the possibility of having both a "low-memory" and a "high-memory" mode in his tool.

**Comment by tedsharpe** [comment]
When performing an action on an RDD, things will be fast and efficient if the output of each task fits in the available memory, and poky slow if we start spilling to disk.  I could easily set the number of partitions on my input RDD to make sure that the output would fit in available memory, if only I knew how much memory was available.  That's what I want to know.

**Comment by tomwhite** [comment]
Thanks for the explanation. You can query the available memory (in MB) with `ctx.sc().executorMemory()`, where `ctx` is the `JavaSparkContext` passed into the `runTool` method.

**Comment by tedsharpe** [comment]
Thanks, Tom.  But I'm afraid that that's only one piece of the puzzle.  For one thing, `ctx.sc().executorMemory()` doesn't give the right answer in local mode.  (Workaround:  `ctx.sc().getExecutorMemoryStatus()` does give a sensible answer in local mode, at the small cost of getting redundant info for each executor.)  However, to know how much is available for the execution of each task, one would have to divide by the number of cores per executor.  Seems like `ctx.getConf().get("spark.executor.cores")` might do the job, but, at least in local mode, it doesn't:  that key is not set.  Any further insights?

**Comment by tomwhite** [comment]
It's a bit messy, but the following will get the number of cores for the local runner, in case `spark.executor.cores` is not set:

```java
SchedulerBackend schedulerBackend = ctx.sc().schedulerBackend();
if (schedulerBackend instanceof LocalBackend) {
  int cores = ((LocalBackend) schedulerBackend).totalCores());
}
```

Could that work?

**Comment by droazen** [comment]
Seems like this is all sufficiently non-obvious as to justify adding `getExecutorCores()` and `getExecutorMemory()` methods at the `SparkCommandLineProgram` level that work reliably in all execution modes.

**Comment by droazen** [comment]
Re-assigning to @jamesemery

**Comment by droazen** [comment]
This one didn't work out -- closing.
