### ISSUE TITLE
Get walker BQSR tools in GATK4 to use less than 3.5Gb of RAM (request from production)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1460]
There's been a request from production (https://broadinstitute.atlassian.net/browse/DSDEEPB-2789) to try to ensure that the walker BQSR tools in hellbender can run with less than 3.5 GB of RAM to get costs down.

**Comment by akiezun** [comment]
Needs clarification on:

- what exact data (we need a bam file or many)
- what exact commandline (ie how many splits?)
- how will the memory usage be measured?

@eitanbanks can you clarify or point us to someone who can?

**Comment by eitanbanks** [comment]
1) Any data.  I assume that the worst case is a deeply covered whole genome, right?
2) I assume the worst case would be no splits, right?  So in that case, no splits.
3) If it goes over 3Gb the jobs will fail...

**Comment by akiezun** [comment]
1) which exact file
2) ok
3) how exactly is the mem measured?

**Comment by eitanbanks** [comment]
EVERY file.  Test on whichever files you like (you have permission to use any files under /seq/picard_aggregation/ and shouldn't need me to tell you how to test things), but the goal is for it to never need more than 3.5Gb.
I assume mem is measured by heap but we should ask @kcibul for sure.

**Comment by kcibul** [comment]
Assuming we're talking non-spark... I think a goal of running with -Xmx3g would do (so heap).  Since the machines have 3.75gb total, I'd push for 3gb instead of 3.5gb of heap

**Comment by akiezun** [comment]
@eitanbanks I can't verify that it will *never* take more than 3.5G. So I need to know the acceptance criteria. But I'm happy also to make up my own acceptance criteria though at least until we hand it off to production. I'll run some 300GB files I have.

I'll use -Xmx3g as the measurement of heap and run with --XX:OnOutOfMemoryError 

Note though that the Xmx option does NOT limit the actual amount of memory that the java VM can use.

**Comment by eitanbanks** [comment]
Why can't you know that it will never take more than 3.5G?
Let's put it this way: imagine you had a tool CountReads that reads in every read from a BAM and emits the total number.  Couldn't you say for sure that it would never take more than 3.5G?  Assuming you don't have any memory leaks, you know that you will only need to hold in memory 1 long (for the count), 1 read, plus some overhead for all of the data structures.  It shouldn't matter that some positions in the genome have 2M reads since you only need to traverse the BAM 1 read at a time.
Why isn't the same true for BQSR?  You know that you will need to reserve space for its internal data structures (and can determine the worst case space complexity for them) plus 1 read at a time.  Assuming the engine has no memory leaks and isn't accumulating reads, you should be able to set a cap on the memory, no?

**Comment by akiezun** [comment]
but the size of the data structures depends on the data - eg, on the number of read groups, on size of context covariates etc.

**Comment by eitanbanks** [comment]
Fair enough.  So could you then give guidance on how much it would require as a function of number of read groups?  Since we're scrapping indels, the context covariate is just previous base.

**Comment by akiezun** [comment]
My plan is as follows:
- [ ] copy 1 WGS file locally (133 GB) /seq/picard_aggregation/G77386/NA12878/v1/NA12878.bam
- [ ] revert qualities to original using GATK4 RevertBaseQualityScores
- [ ] run GATK3 BaseRecalibrator with -Xmx 10g no-split with time -v and check max memory
- [ ] run GATK4 BaseRecalibrator with -Xmx 10g no-split with time -v and check max memory
- [ ] run GATK3 BaseRecalibrator with -Xmx 3.5g no-split with time -v and check max memory and see that it finishes
- [ ] run GATK4 BaseRecalibrator with -Xmx 3.5g no-split with time -v and check max memory and see that it finishes

ok?

**Comment by eitanbanks** [comment]
Actually, Adam, I don't care about the GATK3 numbers.  I just want to know whether GATK4 can do it.  I'm ready to move towards the future!

How many read groups are in that particular file?

**Comment by akiezun** [comment]
2 readgroups in /seq/picard_aggregation/G77386/NA12878/v1/NA12878.bam
I do want to see if/that there are differences in mem - even just for the satisfaction of it (or horror if it goes up)

I also have a 332G file with 16 readgroups: /humgen/gsa-hpprojects/NA12878Collection/bams/CEUTrio.HiSeq.WGS.b37.NA12878.bam

**Comment by eitanbanks** [comment]
Okay, let's see the results on both files then.  Thanks!

**Comment by akiezun** [comment]
I peeked in the profiler - most of the memory is consumed by the BAQ tables

**Comment by eitanbanks** [comment]
Kill them

**Comment by akiezun** [comment]
as in: remove BAQ?
do we know how that impacts the results?

**Comment by pgrosu** [comment]
Hi Adam,

Thank you for this amazing work, and would like to suggest something small without disturbing the test-flow.  So unless I'm not mistaken, the class that is consuming the memory is [NestedIntegerArray.java](https://github.com/broadgsa/gatk/blob/master/public/gatk-utils/src/main/java/org/broadinstitute/gatk/utils/collections/NestedIntegerArray.java).  Why not try an experiment where you implement something similar to [Google's SSTable](https://www.igvita.com/2012/02/06/sstable-and-log-structured-storage-leveldb/) that got release as [leveldb](https://github.com/google/leveldb).  For instance the key-index lookup for you can be hash or a hash+offset.  Basically these structures borrow from the concept of a [Log-Structured Merge-Tree (LSM-Tree) - link is a PDF paper](http://paperhub.s3.amazonaws.com/18e91eb4db2114a06ea614f0384f2784.pdf). You can push most of these to disk instead of memory, and they can be compressed as well.  The indices can remain in memory for fast-lookup with the data staying on disk.  So for instance, you can generate an key-index digest of specific values via `hash_function(numReadGroups.id, qualDimension.index, eventDimension.type)`, whose result you then use to quickly lookup the value for that key - which would reside on disk.  That can be further improved with a priority queue cache for the most accessed values.

Hope it helps,
Paul

**Comment by akiezun** [comment]
thanks @pgrosu. Can you propose a PR? We'll be happy to review

**Comment by droazen** [comment]
@akiezun @pgrosu I'd be very hesitant to make such a radical change to the internals of the tool at the same instant we're trying to validate BQSR for production use (https://github.com/broadinstitute/gatk/issues/1413).

BAQ doesn't use `NestedIntegerArray`, anyway -- `NestedIntegerArray` is used for the recal tables themselves.

**Comment by akiezun** [comment]
proposing a PR is not the same as making the change.

**Comment by droazen** [comment]
@akiezun That's true, but the proposed change would not affect BAQ, which you said above was responsible for most of the memory usage. It would affect the covariates tables, which you said were not the problem. We shouldn't ask someone to spend time on something that doesn't solve our problem!

**Comment by pgrosu** [comment]
@droazen, @akiezun - Even though I looked at the code several times, I had a feeling I might have been off on something.  No worries, I can wait if you prefer.  But are you saying that the BAQ tables  are the following [line of code](https://github.com/broadinstitute/gatk/blob/63a31efa9c4c888144f701fc0ab0afbb36a6185c/src/main/java/org/broadinstitute/hellbender/utils/recalibration/BaseRecalibrationEngine.java#L118), or does the profiler suggests a specific structure within the [BAQ class](https://github.com/broadinstitute/gatk/blob/28019bdf63492affc6809487511437ee18c19114/src/main/java/org/broadinstitute/hellbender/utils/baq/BAQ.java), which is consuming the large amounts of memory:

```Java
final byte[] baqArray = nErrors == 0 ? flatBAQArray(read) : calculateBAQArray(read, refDS);
```

Thanks,
Paul

**Comment by eitanbanks** [comment]
@akiezun I believe that BAQ was only introduced into BQSR to handle indels... which we are dropping.

I think you should tie out to GATK3 with BAQ included, remove BAQ completely, and then it should be simple to show that the BAQ-less results are barely any different (esp. if we enable binning).

(@yfarjoun on cc)

**Comment by akiezun** [comment]
current investigations show that the memory is in fact dominated by the BAQ tables and most of the memory churn is from BAQ - in fact almost all comes from 3 allocation sites in BAQ.

Notably, only about ~200MB of total memory is non temporary, ie it's conceivable that we could fit BaseRecalibrator in 1GB.

**Comment by eitanbanks** [comment]
@akiezun, that's fantastic!
I'd like to propose the following steps:
1. tie out GATK3 and GATK4 with BAQ
2. get a baseline run of GATK4 with BAQ and with binning
3. remove BAQ
4. tie out GATK4 without BAQ but with binning to 2 above
5. move GATK4 into production
What do you think?  It would be strategically smart to get this done soonish so our BioIT announcement has some legs to it.

**Comment by eitanbanks** [comment]
But step 4 above, the results aren't expected to be identical.  We just want to show (which I'm sure we'll do easily) that any differences are insignificant.  @yfarjoun has done this recently with the cloud/on-prem workflow and can show you his scripts.

**Comment by akiezun** [comment]
thanks - my plan was to show the matrix of quals vs quals (for the 2 versions being compared)

**Comment by akiezun** [comment]
Help from Intel on memory profiling: "Java virtual machine (JVM) provides very good memory usage information through various utilities. We could start with getting a GC log file and take a look at it. Following command line options will make the JVM dump its memory usage information whenever a GC happens:
-XX:+PrintFlagsFinal -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintGCDetails -Xloggc:/<path>/<gc file name>
Once we have got the GC log file, we could visualize it using GCViewer (https://github.com/chewiebug/GCViewer) and get a basic idea about the memory usage."

**Comment by akiezun** [comment]
this is also nice for viewing those logs: http://gceasy.io/diamondGC

I'm running ApplyBQSR here on a file >100GB:

Here's the GATK4 plot: note that peak is 2.38GB
![image](https://cloud.githubusercontent.com/assets/1993519/13834462/ae6bffac-ebc5-11e5-80b3-7898022d1cea.png)

and same for GATK3 - peak was almost 18GB. 
![image](https://cloud.githubusercontent.com/assets/1993519/13834527/276910ca-ebc6-11e5-8061-9dda95e848be.png)

**Comment by pgrosu** [comment]
@akiezun That is awesome!

**Comment by yfarjoun** [comment]
massive :+1:

**Comment by akiezun** [comment]
previous runs were with -Xmx 32GB (which is default on my massive machine). Rerunning GATK4 with -Xmx3G now

**Comment by akiezun** [comment]
ok, so after setting -Xms and -Xmx to 3G, gatk4 can run applyBQSR of a 100GB file in peak head of 1.28GB

See heap after GC (check out the units on the y axis)
![image](https://cloud.githubusercontent.com/assets/1993519/13846713/7a3d4ace-ec1f-11e5-8ed0-5ef88f3f87a7.png)

Also, we're using IntelDeflater now and so this is 2x faster too even though we use less memory.

GATK3 with 32GB heap, unknown deflater, 55146.42 user time seconds (wall clock 13:24:10)
GATK4 with 32GB heap, JdkDeflater, 37011.46 user time seconds (wall clock 9:50:48)
**GATK4 with 3GB  heap, IntelDeflater, 27718.06 user time seconds** (wall clock 8:02:37)

I'm declaring victory on BaseRecalibrator front. Moving to BaseRecalibrator

**Comment by yfarjoun** [comment]
I have to ask, the resulting table is the same, right?

**Comment by akiezun** [comment]
last time i checked it was:
https://github.com/broadinstitute/gatk/issues/1413

**Comment by yfarjoun** [comment]
:+1:

**Comment by akiezun** [comment]
BaseRecalibrator with 3GB heap (file size 100GB). This is a snapshot after ~1 hour of runtime. Check out the differences in the y axis here. GATK3 is clearly struggling while Hellbender is doing fine:

GATK3 heap profile after GC (each red triangle is a full GC)
![image](https://cloud.githubusercontent.com/assets/1993519/13857812/dce2bcb8-ec51-11e5-9fb2-9745e86c8e24.png)


GATK4 heap profile after GC:
![image](https://cloud.githubusercontent.com/assets/1993519/13857765/b4525934-ec51-11e5-95aa-4135c05ef850.png)

**Comment by akiezun** [comment]
update on running ApplyBQSR GATK4 with async IO (only writing). We totally pwn gatk3 here.

GATK3 with 32GB heap, unknown deflater, 55146.42 user time seconds (wall clock 13:24:10)
GATK4 with 32GB heap, JdkDeflater, 37011.46 user time seconds (wall clock 9:50:48)
GATK4 with 3GB heap, IntelDeflater, 27718.06 user time seconds (wall clock 8:02:37)
**GATK4 with 3GB heap, IntelDeflater+asyncIO, 30190.24 user time seconds (wall clock 4:56:27)**

**Comment by akiezun** [comment]
death by garbage. Cambridge, MA. GATK3 ApplyBQSR (aka PrintReads) when run with 3GB heap died a violent death, after 71 minutes of life. In it's final minutes, it was drowning in garbage, trying to full-GC itself out of it.

![image](https://cloud.githubusercontent.com/assets/1993519/13862127/93f3c1e4-ec67-11e5-8238-c7fb50f2183a.png)

**Comment by lbergelson** [comment]
[image: Inline image 1]

**Comment by akiezun** [comment]
update on BaseRecalibrator. On a 111GB file, and 3GB heap, both GATK3 and GATK4 finish.

wall clock time:
GATK3: Elapsed (wall clock) time (h:mm:ss or m:ss): 19:23:58
GATK4: Elapsed (wall clock) time (h:mm:ss or m:ss): 18:01:54

user time:
GATK3: User time (seconds): 141297.53
GATK4: User time (seconds): 68317.42

on memory, GATK4 deals with ease and could easily fit with 1GB I think, maybe 0.5 GB (only 1 full GC during the whole run)
![image](https://cloud.githubusercontent.com/assets/1993519/13880255/d7abd360-ecf1-11e5-8517-370b347b35a1.png)

while GATK3 struggles and full-GCs all the time (thousands of times here):
![image](https://cloud.githubusercontent.com/assets/1993519/13880282/fdbf9758-ecf1-11e5-931a-409da92d0dfa.png)

I'm declaring victory on BaseRecalibrator too

**Comment by akiezun** [comment]
@kcibul FYI - ripe low-hanging fruit here

**Comment by droazen** [comment]
@akiezun Can you open a ticket to add a continuous test in jenkins to ensure that BQSR will continue to run in < 3.5 GB?

**Comment by akiezun** [comment]
is jenkins operational?

**Comment by droazen** [comment]
@akiezun https://gatk-jenkins.broadinstitute.org/

**Comment by akiezun** [comment]
clearly, it's not working properly. @lbergelson what's the status?

**Comment by droazen** [comment]
@akiezun That should not stop you from opening that ticket :)

**Comment by akiezun** [comment]
done https://github.com/broadinstitute/gatk/issues/1594

**Comment by lbergelson** [comment]
Jenkins itself is up and operational.  Tests on it are not yet functional.  I've been working with dev ops and people from the cromwell team to figure out the best way to dispatch jobs elastically.  I've set up a cromwell instance that we can send non-spark jobs to JES with right now.  That's one option, dev ops thinks we should try setting up a kubernetes swarm instead of using jes though.  There's a bunch of wiring to do in either case.
