### ISSUE TITLE
How could I iterate locus by locus using the new framework?

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#1463]
Hello, I'm trying to port some of tools that I was developing in GATK to the new framework, but I know that `LocusWalker` is not going to be implemented in the new framework.

Thus, I was thinking to use either the `ReadWalker` or the `IntervalWalker` to accomplish something similar to get a kind of a pileup for each position, but I do not know exactly how.

Could you help me in this issue?

**Comment by akiezun** [comment]
Can you describe more precisely what you want to accomplish? That is, can
you describe your tool and/or point us to the code?

**Comment by magicDGS** [comment]
@akiezun sorry, I apologize for didn't describe it properly.

Basically, I need to obtain the base/deletion counts (and insertions after the position) from the reads that overlaps each position in the reference genome. Previously I did that with a `LocusWalker` like this:

```java
public Integer map(RefMetaDataTracker refMetaDataTracker, ReferenceContext referenceContext, AlignmentContext alignmentContext) {
    ReadBackedPileup pileup = alignmentContext.getBasePileup();
    int[] baseCounts = pileup.getBaseCounts();
    int delCounts = pileup.getNumberOfDeletions();
    int insCounts = pileup.getNumberOfInsertionsAfterThisElement();
    // other operations ...
}
```
I don't know exactly how could be done this using the `ReadWalker` (my first idea is to accumulate the reads in a queue with positions, but it does not seem very efficient). On the other hand, with the `IntervalWalker` I imagine that could be done iterating over each position in the interval (in the apply implementation), but for an efficient position by position analysis will be interesting to pass them in a base per base basis.

What is the best approach? How are the GATK team planning to do it for their tools?

Thank you very much.

**Comment by droazen** [comment]
If there is sufficient demand, we could implement a `LocusWalker` class for GATK4, particularly as the key classes from GATK3 were recently ported as part of https://github.com/broadinstitute/gatk/pull/1442. Adding new walker types in GATK4 is much simpler than it was in GATK3, so this would actually be a fairly simple addition.

**Comment by akiezun** [comment]
I agree, +1. There are going to be a whole bunch of tools that are most easily expressed as locus walkers.

**Comment by droazen** [comment]
Alright, I'll create a ticket for this then.

**Comment by droazen** [comment]
https://github.com/broadinstitute/gatk/issues/1464

**Comment by akiezun** [comment]
closing this as a dup of #1464
