### ISSUE TITLE
Implement a LocusWalker traversal

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1464]
Since the key classes have now been ported, and since there is some demand for this (https://github.com/broadinstitute/gatk/issues/1463), let's implement a `LocusWalker` class like GATK3 had. This should actually be fairly easy to do now that `LocusIteratorByState` has been ported as part of https://github.com/broadinstitute/gatk/pull/1442

**Comment by droazen** [comment]
This is still in code review -- moving to alpha-2

**Comment by magicDGS** [comment]
I think that this could be closed.

**Comment by droazen** [comment]
Right you are -- closing
