### ISSUE TITLE
see if PerReadAlleleLikelihoodMap can be / should be refactored out

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1467]
see https://github.com/broadinstitute/gsa-unstable/issues/831

this came up in review of https://github.com/broadinstitute/gatk/pull/890

**Comment by davidbenjamin** [comment]
@droazen If this is in fact worth doing I would like to take it because `PerReadAlleleLikelihoodMap` pollutes a lot of Mutect2 code.

**Comment by droazen** [comment]
@davidbenjamin it's yours if you want it!
