### ISSUE TITLE
VariantAnnotation - enable overlapping with arbitrary feature source

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1485]
came up in review of https://github.com/broadinstitute/gatk/pull/890 - we dont support detection of overlap with arbitrary feature source, only DBSNP. This needs to be enabled and tested.

**Comment by droazen** [comment]
I actually think this does/should work in the current port -- can you try adding a test for it?

**Comment by akiezun** [comment]
well, the only place where `VariantOverlapAnnotator(final FeatureInput<VariantContext> dbSNP, final Map<FeatureInput<VariantContext>, String> overlaps)` is called with non-empty map is `initializeOverlapAnnotator` (used to be named `initializeDBs` and that only adds dbSNP AFAICT

**Comment by droazen** [comment]
@akiezun You need to allow a set of comparison `FeatureInputs` (what GATK3 calls "compBindings") to be passed in at construction, in addition to the DBSNP `FeatureInput`. Then you need to modify your `initializeOverlapAnnotator()` method slightly to add entries for the non-DBSNP "comp" `FeatureInputs` as well, and it should just work, I think. Could you please do this + add a test? This feature is needed/used by the HC, among other tools. Relevant code from GATK3:

        final Map<RodBinding<VariantContext>, String> overlapBindings = new LinkedHashMap<>();
        for ( final RodBinding<VariantContext> b : walker.getCompRodBindings())
            if ( b.isBound() ) overlapBindings.put(b, b.getName());
        if ( dbSNPBinding != null && ! overlapBindings.keySet().contains(VCFConstants.DBSNP_KEY) )
            overlapBindings.put(dbSNPBinding, VCFConstants.DBSNP_KEY); // add overlap detection with DBSNP by default

        variantOverlapAnnotator = new VariantOverlapAnnotator(dbSNPBinding, overlapBindings, engine.getGenomeLocParser());

**Comment by akiezun** [comment]
will do but let me merge in #890 first - i want to be done with it, it's been open since september

**Comment by droazen** [comment]
Would you mind doing it as part of https://github.com/broadinstitute/gatk/pull/890? It should be really easy (1 extra constructor arg + a few extra lines in `initializeOverlapAnnotator()`), and has implications for work I'm doing now.

**Comment by akiezun** [comment]
12 hours of hacking -> brain shutdown. Curing cancer has to wait for me to reboot it.
