### ISSUE TITLE
Load a VCF in parallel in Spark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1486]
We can use `SparkContext.textFile` "https://spark.apache.org/docs/1.5.0/api/java/org/apache/spark/SparkContext.html#textFile(java.lang.String,%20int)" and VCFCodec.decode to load the file (can be compressed) to an JavaRDD of VariantContexts. The codec needs to be set up with a header but that's easy - just read the first lines.

**Comment by pgrosu** [comment]
Hi Adam,

Maybe I'm thinking naively here - and I don't have access to a complete and proper Spark cluster for rigorous testing - but just as a simple test of loading a VCF via Spark, I took [PrintReadsSpark.java](https://github.com/broadinstitute/gatk/blob/030858bc08328200b9df287db2571b907189ec66/src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/PrintReadsSpark.java) and performed following updates:

* Copied `./src/test/resources/org/broadinstitute/hellbender/utils/SequenceDictionaryUtils/test.vcf` into the local directory.
* Renamed the copy of `PrintReadsSpark.java` as `PrintVCFSpark.java`
* Added `import org.broadinstitute.hellbender.utils.variant.Variant;`
* Added `import org.broadinstitute.hellbender.engine.spark.datasources.VariantsSparkSource;`
* As a test, I changed to the `runTool` method with the following to print the information in the first element in the RDD:

```Java
	 JavaRDD<Variant> rddParallelVariants =
                variantsSparkSource.getParallelVariants(output);

	 System.out.println( rddParallelVariants.first().toString() );
```

And after re-compiling GATK and running `PrintVCFSpark`, I got the following to print the first element of the RDD:

```Bash
$ ./gatk-launch PrintVCFSpark --input test.vcf --output test.vcf

Running:
    /home/pgrosu/me/hellbender_broad_institute/gatk/build/install/gatk/bin/gatk PrintVCFSpark --input test.vcf --output test.vcf
[February 14, 2016 7:04:16 PM EST] org.broadinstitute.hellbender.tools.spark.pipelines.PrintVCFSpark  --output test.vcf --input test.vcf  --readValidationStringency SILENT --interval_set_rule UNION --interval_padding 0 --bamPartitionSize 0 --disableSequenceDictionaryValidation false --shardedOutput false --numReducers 0 --sparkMaster local[*] --help false --version false --verbosity INFO --QUIET false
[February 14, 2016 7:04:16 PM EST] Executing as pgrosu on Linux 2.6.32-358.el6.x86_64 amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_05-b13; Version: Version:4.alpha-86-g154d0a8-SNAPSHOT JdkDeflater
19:04:16.098 INFO  PrintVCFSpark - Initializing engine
19:04:16.100 INFO  PrintVCFSpark - Done initializing engine
2016-02-14 19:04:17 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016-02-14 19:04:19 WARN  MetricsSystem:71 - Using default name DAGScheduler for source because spark.app.id is not set.
MinimalVariant -- interval(1:737406-737411), snp(false), indel(true)
19:04:24.266 INFO  PrintVCFSpark - Shutting down engine
[February 14, 2016 7:04:24 PM EST] org.broadinstitute.hellbender.tools.spark.pipelines.PrintVCFSpark done. Elapsed time: 0.14 minutes.
Runtime.totalMemory()=90177536
```

This seems to have the ability to load a VCF as a JavaRDD.  Let me know if this is what you were looking for, and sorry if I am assuming this solves the problem.

Thanks and hope you're keeping warm :)
Paul

**Comment by akiezun** [comment]
ha, interesting. let me take this on

**Comment by akiezun** [comment]
done in #1496 
thanks @pgrosu for pointing out that code!

**Comment by akiezun** [comment]
performance point: on our cluster this gives ~900MB/second (on 60 spinning disks).

**Comment by pgrosu** [comment]
@akiezun Gladly :)  Sorry to reply so late as I am slowly catching up on repository posts :)
