### ISSUE TITLE
port GenotypeGVCFs

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#15]
The requirement is to port the GenotypeGVCFs tool and tests. Test data should be made public whenever possible.

**Comment by akiezun** [comment]
closing in favor of https://github.com/broadinstitute/hellbender-protected/issues/42

**Comment by droazen** [comment]
alpha-2

**Comment by droazen** [comment]
Depends on https://github.com/broadinstitute/gatk/issues/1647 and https://github.com/broadinstitute/gatk/issues/692

**Comment by lbergelson** [comment]
Initial port of GenotypeGVCFs completed by https://github.com/broadinstitute/gatk-protected/pull/553/
