### ISSUE TITLE
add tests for LeftAlignIndels

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#150]
there were none in GATK, need to make some in hellbender. include cram tests

**Comment by davidbenjamin** [comment]
@droazen Do we still even need `LeftAlignIndels`?  It seems to duplicate behavior of `LeftAlignAndTrimVariants`, which does have an integration test.

**Comment by droazen** [comment]
@davidbenjamin Well, `LeftAlignIndels` is a pretty limited tool, as it has the restriction that "This tool will left-align reads with one and only one indel". Can `LeftAlignAndTrimVariants` correctly left align reads with multiple indels?

**Comment by davidbenjamin** [comment]
Not yet but it will in a week.
