### ISSUE TITLE
investigate using Isilon-as-HDFS for Spark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1508]
From @tomwhite 

"Isilon exposes a Hadoop filesystem interface which makes it possible
to use it as a source or sink for Spark. (There are some notes here:
http://www.cloudera.com/documentation/enterprise/latest/topics/cm_mc_isilon_service.html)

Note however that you lose the benefits of locality, so it won't be as
fast as HDFS. Definitely worth a try. Also, for a pipeline with
multiple steps, you could use HDFS to store intermediate data, only
reading from Isilon for the source files and writing to Isilon with
the final result."

**Comment by pfxuan** [comment]
In this case, it may make sense to insert an in-memory cache layer between Spark and Isilon for holding those intermediate datasets. For example, if Alluxio (Tachyon) is used, the benefits of locality could still be preserved and the I/O pressure to network as well as to Isilon storage will be largely released. GATK pipeline would achieve memory speed data sharing across different computational stages. The following is one of study cases:
[Making the Impossible Possible with Tachyon: Accelerate Spark Jobs from Hours to Seconds](
https://dzone.com/articles/Accelerate-In-Memory-Processing-with-Spark-from-Hours-to-Seconds-With-Tachyon)

**Comment by akiezun** [comment]
@pfxuan thanks for pointing this out - I'll investigate

**Comment by akiezun** [comment]
unclear if we needs this given the cloud

**Comment by pfxuan** [comment]
FYI
**Unified Namespace and Tiered storage in Alluxio, San Jose (Strata + Hadoop World):**
http://conferences.oreilly.com/strata/hadoop-big-data-ca/public/schedule/detail/47651

**Comment by pfxuan** [comment]
@akiezun  Here is a case study for your reference:
**Scalable Genomics Data Processing Pipeline with Alluxio, Mesos, and Minio**
https://alluxio.com/blog/scalable-genomics-data-processing-pipeline-with-alluxio-mesos-and-minio

**Comment by droazen** [comment]
With the move to the cloud we are much less interested in Isilon these days -- closing.
