### ISSUE TITLE
implement parallel copy from NFS (or IFS) to HDFS 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1509]
A lot of data we have lives on NFS (or underlying IFS - Isilon FS). Copying files in and out is a bottleneck and a pain. This ticket for an implementation of a parallel copy of a BAM/CRAM file to HDFS (sharded or unsharded)

**Comment by pfxuan** [comment]
Is NetApp-Hadoop-NFS-Connector useful for your problem? Also, the datasets pumped from NFS could be held at in-memory storage layer: 
https://github.com/NetApp/NetApp-Hadoop-NFS-Connector
http://www.alluxio.org/

**Comment by akiezun** [comment]
unclear if this is needed given the cloud.

**Comment by droazen** [comment]
This was resolved in https://github.com/broadinstitute/gatk/issues/2014
