### ISSUE TITLE
SVs should have their own program group

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1515]
SVs should have their own program group and we should us that rather than the Spark group (the Spark group will go away because tool should be group by what they do rather then by how thew do it)

**Comment by SHuang-Broad** [comment]
Should we close this, considering that there is one now? @cwhelan @tedsharpe

**Comment by cwhelan** [comment]
Sure, if it's done you can close this, just mention the pull request number
that contained the fix.

**Comment by akiezun** [comment]
done in #1514
