### ISSUE TITLE
Fix performance issues in interval subsetting in Spark and large interval lists

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#1532]
See notes in #1516.

**Comment by droazen** [comment]
Let's test with the exome interval list `ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/2.8/b37/Broad.human.exome.b37.interval_list.gz` (need to gunzip before using)

**Comment by droazen** [comment]
@cwhelan is seeing performance issues now with large interval lists + reads + spark. This might be a result of the way intervals are currently being sent to Hadoop-BAM in `ReadsSparkSource` (marshaled into a giant String, set as a Java system property, then re-parsed on the other end). @akiezun we might want to bump up the priority of this ticket.

**Comment by akiezun** [comment]
@cwhelan what;s the commandline you're working with?

**Comment by cwhelan** [comment]
@akiezun The goal is to use a genome mask, like for example Heng's low complexity sequence mask, which has many small intervals from the reference to be masked out. To that end I've tried using both the -XL exclude regions arg and -L with a 'complement' version of the mask.

I was running on custom 10X tools in one of my branches but the problem exists with simpler tools like PrintReadsSpark. 

For example running like this on a bam subset of 1MB of the reference is fine:

    time /humgen/gsa-scr1/cwhelan/GATK/gatk/gatk-launch PrintReadsSpark --input test_in.bam -O test_out.bam -- --sparkRunner LOCAL
    real    0m49.678s
    user    5m10.396s
    sys     0m14.556s

But add the complemented mask:

    $ time /humgen/gsa-scr1/cwhelan/GATK/gatk/gatk-launch PrintReadsSpark --input test_in.bam -O test_out.bam -L /humgen/gsa-hpprojects/dev/cwhelan/gatk-sv/hs37d5LCRs.complement.bed -- -- sparkRunner LOCAL

And it's still running 35+ minutes later. Similar results observed using the original mask and XL argument:

    $ time /humgen/gsa-scr1/cwhelan/GATK/gatk/gatk-launch PrintReadsSpark --input test_in.bam -O test_out.bam -XL /humgen/gsa-hpprojects/dev/cwhelan/gatk-sv/hs37d5LCRs.bed -- --sparkRunner LOCAL

Let me know if I can provide more details.

**Comment by akiezun** [comment]
perfect. this is enough to get me started. thanks!

**Comment by akiezun** [comment]
it's not the set, it's the actual intersect:
![image](https://cloud.githubusercontent.com/assets/1993519/14474312/601eccca-00ca-11e6-9d61-7b417d677433.png)

**Comment by akiezun** [comment]
Should we move IntervalsSkipList etc down to htsjdk so that everyone picks it up, including us and Hadoop-BAM? @droazen @jean-philippe-martin @tomwhite wdyt? 

The current code in Hadoop-bam does a linear scan over intervals: https://github.com/HadoopGenomics/Hadoop-BAM/blob/5f43540b49c8b9dd5b1d057bceada9f2980dde12/src/main/java/org/seqdoop/hadoop_bam/BAMRecordReader.java#L227

**Comment by akiezun** [comment]
I'm renaming the issue too

**Comment by jean-philippe-martin** [comment]
Sure, I'd love for IntervalsSkipList to be more broadly used! It looks like it would help there.

**Comment by tomwhite** [comment]
It would great to be able to use the skip list in BAMInputFormat. I agree that htsjdk sounds like the right home for it. I can do the Hadoop-BAM changes once it's in htsjdk.

**Comment by akiezun** [comment]
@tomwhite can you point us to how (in hadoop-bam) the index is used for querying? we're wondering how many reads the `BAMRecordReader.overlaps` iterates over?

**Comment by tomwhite** [comment]
It doesn't iterate over the overlapping intervals, it just checks whether any overlap at all. I've created a branch that uses `OverlapDetector` here: https://github.com/tomwhite/Hadoop-BAM/tree/intervals-optimization, which you can use to check if the changes address the performance issues you were seeing. 

It would be good if `OverlapDetector` could take a `Locatable` so we can pass in `SAMRecord` directly and not create a new `Interval` object. Having an `overlaps()` method that returns a boolean would be nice too.

I'm not sure how unmapped reads that have a coordinate set are handled. They may need a special case, as in https://github.com/HadoopGenomics/Hadoop-BAM/compare/master...tomwhite:intervals-optimization#diff-60ad8bad94dec0448bd32dcfebfdd6f4L234.

**Comment by droazen** [comment]
@tomwhite I believe that @akiezun is asking how the filtering done using the bam index in `BAMInputFormat` relates to the inefficient overlap check in `BAMRecordReader.overlaps(SAMRecord r, List<Locatable> intervals)`. Have we already subsetted down to the reads returned from the index query by the time we get to `overlaps()`?

**Comment by tomwhite** [comment]
Got it. The index is used to filter the input splits (by removing any that don't match, or trimming those that do match down to the minimum extent of the match). See https://github.com/HadoopGenomics/Hadoop-BAM/blob/master/src/main/java/org/seqdoop/hadoop_bam/BAMInputFormat.java#L288-L355

**Comment by akiezun** [comment]
I'm making improvements to the overlap detector api, suggestions welcome. I
should have a pr today

On Thursday, April 14, 2016, Tom White <notifications@github.com> wrote:

> Got it. The index is used to filter the input splits (by removing any that
> don't match, or trimming those that do match down to the minimum extent of
> the match). See
> https://github.com/HadoopGenomics/Hadoop-BAM/blob/master/src/main/java/org/seqdoop/hadoop_bam/BAMInputFormat.java#L288-L355
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gatk/issues/1532#issuecomment-209894805>
>


-- 
Sent from Gmail Mobile

**Comment by akiezun** [comment]
@tomwhite it's awesome. One test I did went from 1.10 minutes to 0.11 minutes (using 47726 intervals)! Thanks, let's put it in hadoop-bam

**Comment by tomwhite** [comment]
@akiezun great! Can you review the PR please? https://github.com/HadoopGenomics/Hadoop-BAM/pull/82

Also, any thoughts about unmapped reads - will `OverlapDetector` handle them?

**Comment by akiezun** [comment]
hmm, don't know about unmapped ones.

**Comment by akiezun** [comment]
this is done. I retested on latest master 4353d54fd2d64ea1b4c8429986f83eb873a4d687 and there's no performance problem when using intervals for subsetting.
