### ISSUE TITLE
change AFPriorProviderUnitTest to not compare doubles by equality

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1536]
AFPriorProviderUnitTest.java:37 compared doubles by strict equality which is not the right way. It should use the `TOLERANCE` (equal to `0.0001`) eg change 
```
Assert.assertEquals(priors[j], Math.log10(het) - Math.log10(j))
```

to
```
Assert.assertEquals(priors[j], Math.log10(het) - Math.log10(j),  TOLERANCE)
```

@frank-y-liu can you make this change and see it if fixed your problem? If yes, can you contribute a fix?

**Comment by frank-y-liu** [comment]
Sure I can. I am still trying to figure out what went wrong with other
tests. May have to wait till I can pass the other tests or I will have to
check in without passing all tests.

-Frank

**Comment by droazen** [comment]
This one is done
