### ISSUE TITLE
[feature request] When pulling INDELs, allow SelectVariants to pull indels from MIXED sites

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#1537]
This bug was posted for [gsa-unstable](https://github.com/broadinstitute/gsa-unstable/issues/1302) also, and is being posted here again at David R's request. 

In my opinion, this bug is a high priority. Also, it impedes me in my documentation work. So if there is a workaround that I can use in the meanwhile, please share with me so I can continue writing my tutorial for indel realignment.
#### How I found the bug

I loaded both the input and output VCFs into IGV and compared the variants in each. Using IGV's tooltip feature and hovering over each variant, I can see the variant type.
#### Bug description

It appears for those sites I checked, MIXED site INDELs are missing from the VCF with INDELs only. I created the INDELs only VCF using `SelectVariants` and `-selectType INDEL`. 
#### Command to recapitulate what I did

Here is the command I used, where $GATK refers to `../GATK/private_unstable_builds/GenomeAnalysisTK_latest_unstable.jar`:

```
java -jar $GATK -R $BUNDLE_B37 -T SelectVariants -V chr10_1Mb_b37_dbsnp_138.vcf -o INDEL_chr10_1Mb_b37_dbsnp_138.vcf -selectType INDEL
```

The input file, `/humgen/gsa-hpprojects/GATK/tutorial/solexa/indel_realignment/population_snippet/chr10_1Mb_b37_dbsnp_138.vcf` is subset for variants in the interval 10:96000000-97000000. Let me know if you want my output file. I won't provide it since I assume this bug will be recapitulated with the input and command above.

**Comment by vdauwera** [comment]
Not a bug -- as you say you're requesting "indels only", so that's what you're getting. If you want mixed records too you need to specify them.

**Comment by sooheelee** [comment]
Is there a way to pull the indels only from the MIXED records?

Soo Hee Lee, Ph.D.
Science Technical Writer

**Comment by vdauwera** [comment]
You mean keep the site and the info for the indel allele but get rid of the SNP allele? Not directly. This would be done automatically if you extracted a sample from a cohort and it only had the indel allele, *and* you specified you wanted to drop alleles that are not in your selected samples. But I can't think of a way to separate them agnostically of samples through GATK. What are you trying to achieve?

**Comment by sooheelee** [comment]
Creating an INDEL.vcf for RealignmentTargetCreator. My current solution is
just to include the MIXED sites. Found the mixed sites are only ~2% of
indels+mixed so I'm just going to include them even if they contain other
types of variants.

Soo Hee Lee, Ph.D.
Science Technical Writer

**Comment by sooheelee** [comment]
### Feature request 
I would like to be able to pull out the indel allele only from mixed records. I'm told this would take the form of a flag that would modify the -selectType behavior to additionally reach into mixed records and subset alleles. If this feature will be addressed, then it also needs to be backported to gsa-unstable.

Additionally, I would like to be able to pull out based on allele frequency cutoff, e.g. `-select  "AF> [#]"`. Currently this gives the following error:

    ##### ERROR MESSAGE: Invalid JEXL expression detected for select-0 with message ![0,10]: 'AF > 0.001;' > error

Laura says this error has do with multiallelic sites. Searching the forum for "JEXL, AF, multiallelic" I find two relevant discussions (links below) that tell me to do things well beyond my abilities. E.g. first I need to subset for biallelic sites etc.

<http://gatkforums.broadinstitute.org/gatk/discussion/6526/selectvariants-af-with-multiallelic-variants>
<http://gatkforums.broadinstitute.org/gatk/discussion/comment/21120#Comment_21120>

**Comment by sooheelee** [comment]
Have since learned external tools can separate out mixed-type records into biallelic records.

**Comment by smlee17** [comment]
> Have since learned external tools can separate out mixed-type records into biallelic records.

Hi, I am also facing the same issue, would you mind to share what type of external tools you used for the separation?
