### ISSUE TITLE
TargetCollection<T> should be renamed to LocatableCollection<L>

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#1538]
This class was created to provided for a need to keep a sorted (by location) set of targets. However there is nothing in it that could not really be applied to any locatable in general. 

As a matter of fact now I find myself in a situation in where I need the same functionality for a different subclass of Locatables, TargetCollection (and its implementations) have the functionality I need but using TargetCollection looks ugly due to its name and its methods names.

The task is the to rename TargetCollection<T> to LocatableCollection<L> and accordingly replace 'target' in methods names for something else (either locatable or a generic name such 'elements'). 

Also I recently noticed the existence of IntervalsSkipList which could be an additional implementation for TargetCollection (or rather the new LocatableCollection). So perhaps as part of this task we could unified the skip-list and the hash based solutions under a single common interface.

**Comment by davidbenjamin** [comment]
`TargetCollection` no longer exists.  I believe its uses were replaced by `OverlapDetector`.
