### ISSUE TITLE
MeanQualityByCycleSpark integration test fails on ADAM files with setHeaderStrict

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#1540]
ReadsSparkSource uses SAMHeaderReader.readSAMHeaderFrom to get the header from the input file, but it returns a bogus header object when called on an ADAM file (its actually htsjdk which is happily returning the header). Subsequent setHeaderStrict calls fail when using this header. The testADAM method should be re-enabled when there is a resolution for this.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/2483
