### ISSUE TITLE
Make Google NIO provider for GCS public and available via maven

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1547]
@jean-philippe-martin is working now to make the Google NIO provider for GCS that he found public.

**Comment by jean-philippe-martin** [comment]
GCS NIO provider is public already, accessible at:
https://github.com/GoogleCloudPlatform/gcloud-java/tree/gcs-nio

I'm working on getting the [integration tests](https://github.com/jean-philippe-martin/gcloud-java/blob/integration-tests/gcloud-java-contrib/gcloud-java-nio/src/test/java/com/google/gcloud/storage/contrib/nio/ITGcsNio.java) and examples ready, and later on getting the NIO provider onto the main branch so it's part of the default SDK download.

The integration tests pass, showing it's now possible to read/write GCS files via the NIO interface. So technically you could start using it now, though it's probably easier to wait until those tests and the examples have passed the pull request gauntlet.

**Comment by pgrosu** [comment]
Very cool @jean-philippe-martin!

**Comment by droazen** [comment]
Remaining task here is to get the new NIO code merged into the master branch of https://github.com/GoogleCloudPlatform/gcloud-java

**Comment by droazen** [comment]
This is done -- closing
