### ISSUE TITLE
Add new functionality in GATK4 to directly extract SamPairUtil.PairOrientation from GATKRead

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/gatk#1550]
Currently such information can only be extracted indirectly via a conversion to SamRecord, which incurs unnecessary performance penalty:

```
GATKRead read = ... // proper initialization
SAMFileHeader header = ...
SamPairUtil.PairOrientation readOrientation = SamPairUtil.getPairOrientation(read.convertToSAMRecord(header))
```

**Comment by droazen** [comment]
@SHuang-Broad Do you still want this feature?

**Comment by magicDGS** [comment]
I think that this is a good starting point for moving the read interface to htsjdk, to make possible different implementations of reads which work with the library...

**Comment by SHuang-Broad** [comment]
@droazen It could potentially speed up the SV pipeline as `wrong` pair orientation is a important type of evidence for SV.
