### ISSUE TITLE
remove BAQ from BQSR (and validate results)

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1557]
- [x] remove BAQ from code (provide a code path that skips BAQ)
- [x] run BaseRecalibrator skipping BAQ
- [x] run ApplyBQSR 
- [x] compare base quals to a BAQ-full run
- [x] compare base quals after binning

**Comment by akiezun** [comment]
BAQ skipping branch - https://github.com/broadinstitute/gatk/compare/ak_removeBAQ

**Comment by akiezun** [comment]
ongoing analysis in gsa6:/local/akiezun/gatk4_bqsr_tieout

**Comment by akiezun** [comment]
ongoing analyses in gsa6:/local/akiezun/gatk4_bqsr_deleteBAQ/gatk

**Comment by akiezun** [comment]
update, on small data (our file in git lfs), results with and without baq (respectively, QRead1, QRead2) are small differences (i'm updating the compare tool to do binning), though most bases gain 1 qual.

```
-----------CompareMatrix summary------------
diff	count
-2	4141872
-1	40845652
0	20910238
1	217848

---------CompareMatrix full matrix (non-zero entries) ----------
QRead1	QRead2	diff	count
1	1	0	1397
2	2	0	9335068
3	3	0	5060
4	4	0	18870
5	5	0	18478
7	8	-1	44
8	8	0	85
8	9	-1	132
9	9	0	1664
9	10	-1	875
10	10	0	7777
10	11	-1	3957
11	11	0	13073
11	12	-1	4741
12	12	0	14906
12	13	-1	6591
13	13	0	12765
13	14	-1	4113
14	14	0	12414
14	15	-1	1830
15	15	0	9595
15	16	-1	2225
16	16	0	7853
16	17	-1	5781
17	17	0	4089
17	18	-1	5891
18	17	1	294
18	18	0	6930
18	19	-1	8422
19	19	0	7357
19	20	-1	20324
20	20	0	8385
20	21	-1	24894
21	21	0	13942
21	22	-1	47819
21	23	-2	752
22	21	1	444
22	22	0	62260
22	23	-1	128662
22	24	-2	903
23	22	1	1466
23	23	0	110413
23	24	-1	271693
24	23	1	33597
24	24	0	534204
24	25	-1	1108115
24	26	-2	1352
25	24	1	33405
25	25	0	1291203
25	26	-1	2365657
25	27	-2	87558
26	26	0	856679
26	27	-1	5627145
26	28	-2	379332
27	26	1	13185
27	27	0	1763702
27	28	-1	14320550
27	29	-2	2152435
28	27	1	30820
28	28	0	4164178
28	29	-1	16198852
28	30	-2	1519540
29	28	1	104637
29	29	0	2489515
29	30	-1	687339
30	30	0	138376
```

**Comment by akiezun** [comment]
The same small test file binned, ~ 0.2% of total quals change by 10 after binning (this is on the very small file)

```
-----------CompareMatrix-binned summary------------
diff	count	%total
-10	136908	0.2071
-4	44	0.0001
0	65977192	99.7906
10	1466	0.0022

---------CompareMatrix-binned full matrix (non-zero entries) ----------
QRead1	QRead2	diff	count
1	1	0	1397
2	2	0	9335068
3	3	0	5060
4	4	0	18870
5	5	0	18478
6	10	-4	44
10	10	0	47210
10	20	-10	6591
20	20	0	267627
20	30	-10	130317
30	20	10	1466
30	30	0	56283482
```

**Comment by droazen** [comment]
@akiezun If you run `HaplotypeCaller` on the two outputs, do any of the calls change?

**Comment by akiezun** [comment]
If only I had a HaplotypeCaller in gatk4. 
(i doubt anything changed but this file it to trivial to matter. Am rerunning with 30GB exome)

**Comment by droazen** [comment]
@akiezun Oh, but you do! You do! https://github.com/broadinstitute/gatk-protected/pull/452

:)

**Comment by eitanbanks** [comment]
FWIW I don't even care if any of the calls change.  They would be marginal calls anyways.  These numbers are minuscule.
@yfarjoun what do you think?

**Comment by akiezun** [comment]
Let me at least run it on a 30GB file.

**Comment by akiezun** [comment]
Update on a 30GB exome file.

So, 11% of bases change quals by 11 or more (negative sign here means that quals "improved" when baq was off). Binned results follow, unbinned at the end

```
binned summary
diff    count	percent
-20	1505928	     0.00753545014704519
-10	2294198573	11.4798443048165
-4	3	         1.5011574551463e-08
0	17621174464	88.173858050224
1	16304311	 0.0815844600289127
2	753960	     0.00377270891627368
3	22026	     0.000110214980356841
4	1710832	     0.00856076070434285
10	48909067	 0.244734035171
```

```
binned (R1 and R2 are reads with and without BAQ, respectively)
R1     R2    diff       count           percent
1       1       0       11046302       0.0552741286636583
2       1       1       134293         0.000671983127079873
2       2       0       5439108879    27.2165294768776
3       1       2       273            1.36605328418313e-06
3       2       1       1650911        0.00826092451811011
3       3       0       5257473        0.0263076492972679
4       1       3       4151           2.0771015321041e-05
4       2       2       30057          0.000150400965431108
4       3       1       1721174        0.00861251060567992
4       4       0       14421926       0.0721652724415608
5       2       3       7355           3.68033769420034e-05
5       3       2       195142         0.000976462893707197
5       4       1       6194067        0.0309942328490856
5       5       0       7202415        0.0360398632410251
6       3       3       10520          5.26405880937969e-05
6       4       2       528488         0.00264447900385119
6       5       1       6603866        0.0330448089289572
6       6       0       12574438       0.0629207044932497
6       10      -4      3              1.5011574551463e-08
10      6       4       1710832        0.00856076070434285
10      10      0       97036068       0.485554722987611
20      10      10      1339792        0.0067041291638179
20      20      0       490579807      2.45479178207428
20      30      -10     1160138        0.00580516602566172
20      40      -20     1505928        0.00753545014704519
30      20      10      22329747       0.111734887268602
30      30      0       2943018882     14.7264491178354
30      40      -10     2293038435     11.4740391387908
40      30      10      25239528       0.126295018738579
40      40      0       8600928274     43.0378253323123
```

```
unbinned summary (negative numbers mean removing BAQ "improved" base quals)
diff    count
-15     386396
-14     1625384
-13     1550996
-12     4846154
-11     7714911
-10     11818590
-9      39209516
-8      66850047
-7      127996955
-6      299319054
-5      559321479
-4      981648925
-3      1706215870
-2      2799767852
-1      3603802916
0       9088821157
1       628927858
2       43909936
3       7743783
4       2677478
5       312790
6       111117
```

(skipping unbinned full results - too big to be useful here)

@eitanbanks @yfarjoun WDYT? running HC seems reasonable given 10% of bases changed by Q10 or more.

**Comment by droazen** [comment]
I think this qualifies as way more than a "minuscule" change, and we should definitely have a look at the effect on variant calling.

**Comment by akiezun** [comment]
this is becoming a more complex project - M2 variants may be impacted too.

BTW runtimes on the 30GB file
```
BaseRecalibrator            119.75 minutes (100%)
BaseRecalibrator no BAQ      69.3 minutes   (57%)
```

```
ApplyBQSR        48.52 minutes (100%)
ApplyBQSR no BAQ 46.20 minutes  (95%)
```

**Comment by yfarjoun** [comment]
yeah, this isn't miniscule...

**Comment by akiezun** [comment]
@eitanbanks @yfarjoun how do you want to proceed? The runtime gains are very real but both M2 and HC results need to be examined.

**Comment by yfarjoun** [comment]
Argh. This is the worst. I thought we don't use BAQ...so confused.

**Comment by akiezun** [comment]
we definitely do and it's eating a whole lot of CPU cycles

**Comment by eitanbanks** [comment]
BAQ was put in to make the indel calibration more accurate.
I'm fine holding off on this PR until a more thorough analysis is made; there isn't a rush.  @yfarjoun should we do this in Palantir?

**Comment by yfarjoun** [comment]
what BQSR and PrintReads commandline did you use? in particular, did you
put in indel qualities into the bam?

**Comment by akiezun** [comment]
no, indel qualities are not in the bam. I only compared non-indel qualities in the analyses above.

**Comment by akiezun** [comment]
@eitanbanks @yfarjoun what's the decision on how to proceed? Code is available and impact on speed measured. M2 and HC analyses are going to be another ticket I think.

**Comment by droazen** [comment]
Why was this closed? Did we decide not to remove BAQ?

**Comment by akiezun** [comment]
M2 and HC analyses will be tracked in Palantir I think. Dev work is done.

**Comment by akiezun** [comment]
this is now tracked here: https://github.com/broadinstitute/palantir/issues/324

**Comment by akiezun** [comment]
Some timings using a 30GB exome file on recent built from 20160718

User time of BaseRecalibrator in seconds and two different relative scalings:
```
11607.71 GATK 3.5            100%     279%
 7368.54 GATK 4 (with BAQ)    63%     177%
 4155.27 GATK 4 (no BAQ)      35%     100%
```

in other words GATK4 with no BAQ is 177% faster than GATK4 with BAQ and 279% faster than GATK3.5

**Comment by vdauwera** [comment]
@droazen Do I recall correctly that you guys removed BAQ altogether? Can I just use the no-BAQ number or would that be misleading?

**Comment by droazen** [comment]
@vdauwera We did end up turning off BAQ by default (after a painstaking evaluation to prove that doing so didn't harm quality of results).
