### ISSUE TITLE
Make pileups in parallel on Spark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1558]
We need a way to create pileups (alignment contexts) in parallel on Spark. Ie the input is a bam file and a vcf file. The engine should provide a way to create an RDD of `AlignmentContext`.

This functionality is important for tools that work on pileups (eg allelic copy number tools).

**Comment by droazen** [comment]
Turns out this may already have been done -- @samuelklee do you have a branch in protected that implements this?

**Comment by akiezun** [comment]
https://github.com/broadinstitute/gatk-protected/tree/sl_het_coverage_spark ?

**Comment by samuelklee** [comment]
Actually, I think this is it: https://github.com/broadinstitute/gatk/compare/sl_het_pulldown_spark

I did take a crack at Spark-ifying the het pulldown in this (ancient) branch, but I can't claim that I knew what I was doing---if I remember correctly, I just tried to adapt some code Adam had in https://github.com/broadinstitute/gatk/tree/ak_coverage_spark.  I don't think I ever implemented proper CIGAR-string parsing either.  Might be better to start from scratch?

**Comment by droazen** [comment]
Reassigning to @jamesemery

**Comment by droazen** [comment]
Blocked by https://github.com/broadinstitute/gatk/issues/1988

**Comment by droazen** [comment]
This ticket should be fairly simple once https://github.com/broadinstitute/gatk/issues/1988 is implemented.

**Comment by tomwhite** [comment]
Fixed by #2190
