### ISSUE TITLE
Benchmark ReadsPipelineSpark on queryname sorted BAMs

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1559]
https://github.com/broadinstitute/gatk/issues/1411

1 shuffle was removed from MarkDuplicates - we should measure performance impact of that
- [x] make a querynamesorted file and copy to cluster
    `hdfs:///user/akiezun/data/CEUTrio.HiSeq.WEx.b37.NA12892.readnamesort.bam`
- [x] run new code on it, measure time
- [x] run legacy code (picard + gatk3) on coordinate sorted bam, pinned to 1 CPU, 7GB ram

**Comment by akiezun** [comment]
blocked by #1560

**Comment by akiezun** [comment]
Legacy pipeline numbers and scripts are in gsa6 /dsde/working/akiezun/projects/readsPipelineBenchmarking

Full legacy pipeline, pinned to 1 CPU and 7GB, took 528 minutes

**Comment by akiezun** [comment]
this is done.

**Comment by tomwhite** [comment]
@akiezun what was the time for the new code?

**Comment by akiezun** [comment]
On our in house cluster, running cdh5.5.1 and using 60 executors, 1 core each and 7 GB per executor this took 19 minutes running master from a few days ago.
