### ISSUE TITLE
Test that providing a pre-created splitting index speeds up hadoop bam

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1568]
when https://github.com/broadinstitute/gatk/pull/1546 is merged we want to measure how much time is saved by pre-creating a splitting index

**Comment by akiezun** [comment]
meh, on a 100GB file, using the pre-created splitting index speeds things up by maybe a few seconds (out of 1:40 min needed for FlagStatSpark). Closing as 'investigated' but i'm not impressed by the time savings.

**Comment by tomwhite** [comment]
I think the idea behind having a splitting index is correctness (not having to use a heuristic approach to find record boundaries), rather than speed.

**Comment by akiezun** [comment]
I see, thank you for the clarification.

**Comment by droazen** [comment]
Yes, the whole motivation behind this effort was based on our belief that the split guessing in Hadoop BAM wasn't safe for production use, and so we wanted a more bulletproof mode of operation.
