### ISSUE TITLE
upgrade to gradle 2.12

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1578]
Gradle 2.12 just released which includes some improvements we've been waiting for.  It includes a "compileOnly" scope which should make some of our spark configuration unnecessary.  We should investigate if we can simplify the sparkJar setup using the new scope, and possible improve things for gatk-protected.

**Comment by akiezun** [comment]
closed by https://github.com/broadinstitute/gatk/pull/1586
