### ISSUE TITLE
investigate whether gzipped fasta is smaller than 2-bit

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1580]
It's possible that 2-bit isn't gaining us much efficiency.  If we could read gzip fasta we might be able to use that instead for less complexity. 

We might have to maintain it zipped in memory though, which could be complicated.

**Comment by droazen** [comment]
For alpha-2 and @akiezun

**Comment by akiezun** [comment]
Note: block gzipped fasta can be indexed by samtools

**Comment by akiezun** [comment]
Homo_sapiens_assembly19.fasta             - 3140756381 bytes
Homo_sapiens_assembly19.fasta.block.gz - 870590559 bytes

**Comment by akiezun** [comment]
closing this - the investigation is done. https://github.com/broadinstitute/gatk/issues/1718 will take over speed investivation
