### ISSUE TITLE
Port Pileup

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1581]
it's a nice simple example of a locus walker

blocked by #1464

**Comment by magicDGS** [comment]
I can implement it once #1526 is accepted, because I'll need it anyway.

**Comment by akiezun** [comment]
excellent, go for it Github won't let me assign to you but it's yours.

**Comment by droazen** [comment]
I'll review https://github.com/broadinstitute/gatk/pull/1526 later today.

**Comment by magicDGS** [comment]
Done!

**Comment by droazen** [comment]
Closing -- this is done
