### ISSUE TITLE
add a continuous test in jenkins to ensure that BQSR will continue to run in < 3.5 GB

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1594]

**Comment by lbergelson** [comment]
@akiezun Is our 30gb bam good enough for this?  Or do we need a full size one?

**Comment by akiezun** [comment]
it's fine. how long does it run?

**Comment by lbergelson** [comment]
2-3 hours.

**Comment by akiezun** [comment]
needs @davidbernick

**Comment by akiezun** [comment]
will be taken care of in https://github.com/broadinstitute/gatk/issues/1609 
closing this one
