### ISSUE TITLE
bad read performance when asyncIO is on (which is by default)

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1597]
write performance is good on asyncIO but read is bad and I'm not sure why. Need to investigate. The test I'm using is BaseRecalibrator - i see a 3x speed difference which is terrible

**Comment by akiezun** [comment]
this is a bigger project - tribble async reading is very broken. we need to rewrite that part and maybe expose sync/async via factory methods.

**Comment by akiezun** [comment]
here's a tracktrace of the main thread when it's hanging
![image](https://cloud.githubusercontent.com/assets/1993519/13889734/83a5c334-ed1e-11e5-8a0b-181d153e097d.png)

**Comment by droazen** [comment]
Do we really need asynchronous I/O in tribble? Is there a tool whose runtime is dominated by tribble-related (synchronous) I/O? If not, I say let's just find a way to turn asynch on for bam reading/writing only rather than trying to fix tribble.

**Comment by akiezun** [comment]
agreed @droazen !

**Comment by akiezun** [comment]
Technically. the doc in Default says 

```
    /** Should asynchronous I/O be used when writing out SAM and BAM files (one thread per file).  Default = false. */
    public static final boolean USE_ASYNC_IO;
```

so it's bogus that tribble even attempts multithreading

**Comment by droazen** [comment]
It's `LineReaderUtil` and `VariantContextWriterBuilder`. Looks like `Defaults.USE_ASYNC_IO ` has been hooked up to those since 2013/14. 

Splitting the setting into `USE_SAM_ASYNC_IO` and `USE_TRIBBLE_ASYNC_IO`, or making asynch I/O an option on the reader/writer factories, would be safer options than removal (unless you're convinced that tribble asynch I/O is so broken that no one should ever use it).

**Comment by akiezun** [comment]
I'm wrting tests for it right now - to see how broken it is

**Comment by akiezun** [comment]
I have a fix here https://github.com/samtools/htsjdk/pull/528 - just remove asynch from tribble readers because it was terrible. @droazen can you review the htsjdk PR?

**Comment by akiezun** [comment]
I want this for alpha 1. @droazen can you review the new async proposal at https://github.com/samtools/htsjdk/pull/529?

**Comment by droazen** [comment]
@akiezun Review complete

**Comment by akiezun** [comment]
@droazen @yfarjoun when is a htsjdk release expected?

**Comment by yfarjoun** [comment]
I think it would be goo to have a release soon...the main questio is should
it be before or after the new intelDeflator...

**Comment by akiezun** [comment]
what are the decision criteria about that? how about some sanity check for the bams created - eg print reads on a 30GB file and then 'samtools view' to a samfile and compare MD5s (results in SAM format should be identical, down to a MD5) ?

**Comment by droazen** [comment]
Resolved for now by https://github.com/broadinstitute/gatk/pull/1649.
