### ISSUE TITLE
Beat GATK3 performance (CPU and memory) of GenotypeGVCFs

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1608]
the goal is to beat GATK3 performance and memory usage of GenotypeGVCFs on realistic datasizes

**Comment by akiezun** [comment]
blocked on #15

**Comment by akiezun** [comment]
first measurement after code in master (file is a wide gvcf with 10k samples and 1k lines : 258M)
GATK3
real	0m31.092s
user	0m46.361s

GATK4
real	0m46.806s
user	0m55.150s

**Comment by akiezun** [comment]
after more aggressive caching of log10 values (a615f8d9c8)
GATK4
real	0m37.982s
user	0m46.861s

**Comment by droazen** [comment]
@lbergelson What input(s) were you using where you saw an order-of-magnitude speedup vs. GATK3?

**Comment by lbergelson** [comment]
I was using a long thin file.

**Comment by akiezun** [comment]
Running with the log10 cache on a non-bp file, 10k samples, 1k lines: 186M

GATK3.5
real	0m26.499s
user	0m42.367s

GATK4
real	0m33.999s
user	0m41.278s

**Comment by akiezun** [comment]
small loop code lifting

GATK4 bp file
real	0m35.082s
user	0m43.495s

GATK4 no-bp file
real	0m31.129s
user	0m40.782s

**Comment by droazen** [comment]
@akiezun Try playing with different values of `VariantWalker.FEATURE_CACHE_LOOKAHEAD` and see if that has an effect.

**Comment by akiezun** [comment]
sharing GenotypeLikelihoodCalculators
GATK4 bp file
real	0m31.917s
user	0m41.398s

GATK4 no-bp file
real	0m26.793s
user	0m36.451s

**Comment by akiezun** [comment]
@droazen i doubt it will help - most work is in the math + vcf decoding (we could move the latter to a different thread eventually i think)

**Comment by akiezun** [comment]
more code lifting out of loops
GATK4 bp file
real	0m32.947s
user	0m41.479s

GATK4 no-bp file
real	0m26.206s
user	0m35.763s

**Comment by akiezun** [comment]
(we're not beating the perf yet, only matching)

**Comment by akiezun** [comment]
@droazen what do you want to do here? We're matching the performance but not beating it at this point. We can either keep this open and continue to investigate or close as 'matching not beating'

**Comment by droazen** [comment]
@akiezun Keep it open as an alpha-3 ticket, but un-assign yourself. We'll continue to work on improving performance in the next quarter.

**Comment by akiezun** [comment]
ok. i'll copy the files that i'm using so that you can use them as well

**Comment by akiezun** [comment]
I copied my data files to `/dsde/working/akiezun/data/GenotypeGVCFs/`
they are short and wide (~9k samples)

**Comment by droazen** [comment]
This was done as part of the GenotypeGVCFs tie-out -- closing.
