### ISSUE TITLE
Establish a cloud dev environment

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1610]
The goal is to create a way to run, test and profile GATK tools in the cloud, the way that production runs them to optimize for production use

**Comment by akiezun** [comment]
1. For spark - cloud dataproc works well
2. For non-spark, the simplest setup seems to create a master-only dataproc cluster because it comes with a bunch of software already pre-installed. 

Maybe that's all we need.

**Comment by akiezun** [comment]
What's missing from the environment:
- samtools (massive pain to build, the install instructions are bogus and apt-get package is very old)

**Comment by lbergelson** [comment]
@akiezun Have you looked into spinning up a node and running one of the production dockers on it?  That way we'd have the exact production environment.  (although I assume there are different dockers for different tools)

**Comment by akiezun** [comment]
ok, this is almost done. The steps for setting up non-spark have been provided by @Davidbernick and checked by me here: https://broadinstitute.atlassian.net/wiki/display/DO/GATK+Dev+in+a+Docker+In+a+Cloud

For spark, dataproc is the preferred option for now (very easy setup). 

@lbergelson can you take over this issue and follow the docker steps as well as dataproc to confirm that it works for you. If/When it does, we'll make a public wiki page from the broad-internal wiki and call it a day.

**Comment by akiezun** [comment]
oh, @lbergelson , I did not realize we had `scripts/install_git_lfs.sh`. Does it make sense to update the Dockerfile to use that?

**Comment by lbergelson** [comment]
Probably not.  It might be named less explicitly than it should be.  It's really `install_git_lfs_assuming_youre_on_travis.sh

**Comment by akiezun** [comment]
i'll grab it back to turn into a wiki

**Comment by akiezun** [comment]
wiki is done https://github.com/broadinstitute/gatk/wiki/How-to-set-up-and-use-cloud-dev-environment
original page is here: https://broadinstitute.atlassian.net/wiki/display/DO/GATK+Dev+in+a+Docker+In+a+Cloud
