### ISSUE TITLE
BaseRecalibrator interpreting contig name to a file 

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/gatk#1626]
I was running BaseRecalibrator with an --interval of GL00207.1:1+ and received this error:

A USER ERROR has occurred: The file GL000207.1:1+ does not exist

It seems like if the contig name has a '.' in it, it thinks it should be looking for a file.  This worked for all other contigs that did not have a '.' in the name and it didn't complain about the Y or MT contigs that come before GL00207.1 in the full command:

org.broadinstitute.hellbender.tools.walkers.bqsr.BaseRecalibrator  --useOriginalQualities true --knownSites /cromwell_root/broad-gitc-reference/hg19/Homo_sapiens_assembly19.dbsnp138.vcf --knownSites /cromwell_root/broad-gitc-reference/hg19/Mills_and_1000G_gold_standard.indels.b37.sites.vcf --knownSites /cromwell_root/broad-gitc-reference/hg19/Homo_sapiens_assembly19.known_indels_20120518.vcf --output NA12878.recal_data.csv --intervals Y:1+ --intervals MT:1+ --intervals GL000207.1:1+ --intervals GL000226.1:1+ --intervals GL000229.1:1+ --intervals GL000231.1:1+ --intervals GL000210.1:1+ --intervals GL000239.1:1+ --intervals GL000235.1:1+ --intervals GL000201.1:1+ --intervals GL000247.1:1+ --intervals GL000245.1:1+ --intervals GL000197.1:1+ --intervals GL000203.1:1+ --intervals GL000246.1:1+ --intervals GL000249.1:1+ --intervals GL000196.1:1+ --intervals GL000248.1:1+ --intervals GL000244.1:1+ --intervals GL000238.1:1+ --intervals GL000202.1:1+ --intervals GL000234.1:1+ --intervals GL000232.1:1+ --intervals GL000206.1:1+ --intervals GL000240.1:1+ --intervals GL000236.1:1+ --intervals GL000241.1:1+ --intervals GL000243.1:1+ --intervals GL000242.1:1+ --intervals GL000230.1:1+ --intervals GL000237.1:1+ --intervals GL000233.1:1+ --intervals GL000204.1:1+ --intervals GL000198.1:1+ --intervals GL000208.1:1+ --intervals GL000191.1:1+ --intervals GL000227.1:1+ --intervals GL000228.1:1+ --intervals GL000214.1:1+ --intervals GL000221.1:1+ --intervals GL000209.1:1+ --intervals GL000218.1:1+ --intervals GL000220.1:1+ --intervals GL000213.1:1+ --intervals GL000211.1:1+ --intervals GL000199.1:1+ --intervals GL000217.1:1+ --intervals GL000216.1:1+ --intervals GL000215.1:1+ --intervals GL000205.1:1+ --intervals GL000219.1:1+ --intervals GL000224.1:1+ --intervals GL000223.1:1+ --intervals GL000195.1:1+ --intervals GL000212.1:1+ --intervals GL000222.1:1+ --intervals GL000200.1:1+ --intervals GL000193.1:1+ --intervals GL000194.1:1+ --intervals GL000225.1:1+ --intervals GL000192.1:1+ --intervals NC_007605:1+ --input broad-gotc-staging-storage/cromwell_execution/PairedEndSingleSampleWorkflow/124e075d-539f-47bd-b0ea-8e882a108cd6/call-AggregatedBamMarkDuplicates/NA12878.aligned.duplicates_marked.bam --reference broad-gitc-reference/hg19/Homo_sapiens_assembly19.fasta  --mismatches_context_size 2 --indels_context_size 3 --maximum_cycle_value 500 --mismatches_default_quality -1 --insertions_default_quality 45 --deletions_default_quality 45 --low_quality_tail 2 --quantizing_levels 16 --bqsrBAQGapOpenPenalty 40.0 --preserve_qscores_less_than 6 --defaultBaseQualities -1 --disable_all_read_filters false --interval_set_rule UNION --interval_padding 0 --readValidationStringency SILENT --secondsBetweenProgressUpdates 10.0 --disableSequenceDictionaryValidation false --createOutputBamIndex true --createOutputBamMD5 false --addOutputSAMProgramRecord false --help false --version false --verbosity INFO --QUIET false

This same command works with Gatk 3.5

**Comment by droazen** [comment]
I'll have a look at this

**Comment by droazen** [comment]
Replicated, working on a fix now

**Comment by droazen** [comment]
@jsotobroad This is fixed in the latest master -- can you please re-try and let us know if all is well?

**Comment by jsotobroad** [comment]
will do, thanks!
