### ISSUE TITLE
investigate performance improvements to SmithWaterman

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1629]
`SWPairwiseAlignment.calculateMatrix` comes up on profiles. We need to investigate performance improvements to it

**Comment by akiezun** [comment]
@paolonarvaez @gspowley FYI this is the ticket to track work on SW improvements.

**Comment by gspowley** [comment]
Oh, I didn't notice this issue and opened #1655 earlier today. We can close that one and track the work here.

**Comment by gspowley** [comment]
In the HaplotypeCaller test, about 80% of the Smith-Waterman calls result in a substring match to the reference without any indels. I'm working on adding a substring search to SWPairwiseAlignment to avoid running the full Smith-Waterman for these cases.

**Comment by akiezun** [comment]
FYI: I took care of one of the slow and common cases, when CIGAR was computed for equal strings by unleashing the whole SW n^2 machinery. It's now a quick linear check: https://github.com/broadinstitute/gatk/pull/1624 but it's outside of SW itself, in CigarUtils

**Comment by akiezun** [comment]
@gspowley is this issue done or is more work planned here?

**Comment by gspowley** [comment]
This issue can be closed. We do plan to add native Smith-Waterman to GKL, after compression and pairHMM are solid. We could track that work under #1812, or close both and reopen an issue when native Smith-Waterman is available in GKL.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/1812
