### ISSUE TITLE
Small naming issue with help docs for BaseRecalibrator and ApplyBQSR

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/gatk#1631]
The help docs for BaseRecalibrator and ApplyBQSR for some inputs have '(with -BQSR)' in the help text but the input for ApplyBQSR is actually -bqsr and will complain if you do -BQSR.  These should just be in lowercase as opposed to uppercase.

**Comment by lbergelson** [comment]
@jsotobroad Thanks for reporting this.
