### ISSUE TITLE
Spark version of HaplotypeCaller

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1639]
Should call into the existing `HaplotypeCallerEngine` and share as much code as possible with the walker version

**Comment by droazen** [comment]
For @lbergelson. The general plan for HaplotypeCaller work in Q2 is:

-I will work on validation/testing of the walker version
-Louis will take the Spark version
-Adam will work on further HC performance optimizations (potentially for both walker and spark)

**Comment by akiezun** [comment]
to clarify - there're no strict correctness requirement here. Just make it run on spark and produce some output.

**Comment by SHuang-Broad** [comment]
@droazen @akiezun How is the progress on this? I am working on a fix for GATK 3 in `HaplotypeCallerGenotypingEngine` [here](https://github.com/broadinstitute/gsa-unstable/pull/1395), and seems some related code has been ported but the HaplotypeCallerGenotypingEngine part hasn't been. So I need to report correctly in the [Google doc](https://docs.google.com/document/d/1DjEHw57k5h0i8MZRGYPlQA3InvURKwQ7pCoi_Eigc4M/edit).

**Comment by droazen** [comment]
@SHuang-Broad `HaplotypeCaller` is fully ported (as a walker), including `HaplotypeCallerGenotypingEngine` -- you are just looking in the wrong repository. Look in https://github.com/broadinstitute/gatk-protected

**Comment by SHuang-Broad** [comment]
Thanks @droazen.

**Comment by lbergelson** [comment]
I'm going to close this one, since we do in fact have a version of HaplotypeCallerSpark thats been merged since  294363819bcdb2d2021486525ca6eb648479df31.  It has a lot of issues, but it's definitely there.
