### ISSUE TITLE
Fully validate HaplotypeCaller walker for production (with help of palantir and/or short variants team)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1640]
Should be validated to the point where production would be willing to use it.

**Comment by droazen** [comment]
Depends on https://github.com/broadinstitute/gatk/issues/3233

**Comment by droazen** [comment]
We've handed the `4.beta.4` release off to palantir for evaluation (specifically, @skwalker and @meganshand will be doing the evaluation).

**Comment by skwalker** [comment]
For the most part, things look pretty good. There's 29 sites where the calls for GATK3 and GATK4 don't match (out of over 27k sites). I've attached some info about these sites and some screenshots from IGV. There's 3 really high qual sites that GATK3 has but GATK4 misses -- and I can't really tell why GATK4 HC doesn't call them.

[differentsites_gatk3_gatk4.xlsx](https://github.com/broadinstitute/gatk/files/1271586/differentsites_gatk3_gatk4.xlsx)

![1_40768483_deletion](https://user-images.githubusercontent.com/4933056/29988711-cc6bae96-8f3c-11e7-9b35-d7ddc7a81fc5.png)
![1_146215232](https://user-images.githubusercontent.com/4933056/29988713-cc6da93a-8f3c-11e7-89c7-8959761affdc.png)
![1_152188999](https://user-images.githubusercontent.com/4933056/29988710-cc6aafa0-8f3c-11e7-98a8-836d54566504.png)
![3_195510293_98insertion](https://user-images.githubusercontent.com/4933056/29988712-cc6d79ec-8f3c-11e7-995c-60f12d09f9eb.png)
![3_195511780](https://user-images.githubusercontent.com/4933056/29988714-cc72db44-8f3c-11e7-8f18-2ad71f549c74.png)
![3_195511814](https://user-images.githubusercontent.com/4933056/29988718-cc7b1304-8f3c-11e7-9ed2-af24c8668a06.png)
![3_195512107](https://user-images.githubusercontent.com/4933056/29988715-cc772956-8f3c-11e7-8ad4-23af181d81c1.png)
![3_195512549](https://user-images.githubusercontent.com/4933056/29988716-cc777f32-8f3c-11e7-980f-a64fd0036ea6.png)
![7_102147148](https://user-images.githubusercontent.com/4933056/29988717-cc7ad1d2-8f3c-11e7-8c9a-02622b791f3f.png)
![8_144522386_deletion](https://user-images.githubusercontent.com/4933056/29988719-cc83821e-8f3c-11e7-8c91-0e09c073d679.png)
![8_144940462_144940474](https://user-images.githubusercontent.com/4933056/29988731-ccd86fea-8f3c-11e7-8447-f68593b4ada6.png)
![11_1018116](https://user-images.githubusercontent.com/4933056/29988723-cca994b8-8f3c-11e7-947b-cf855d53b14a.png)
![11_1018144](https://user-images.githubusercontent.com/4933056/29988720-cc895950-8f3c-11e7-8183-cee6880fe573.png)
![11_48387668](https://user-images.githubusercontent.com/4933056/29988724-cca9b632-8f3c-11e7-990f-ac18a2ac82e2.png)
![11_48387757](https://user-images.githubusercontent.com/4933056/29988721-cc8d6324-8f3c-11e7-89a3-6e07864154e2.png)
![17_182928_deletion](https://user-images.githubusercontent.com/4933056/29988728-ccbb7a70-8f3c-11e7-8f33-d8a9df51cb0b.png)
![17_39240804_5_7_10_junk](https://user-images.githubusercontent.com/4933056/29988722-cc9c616c-8f3c-11e7-9c7f-7d91ee33d5b5.png)
![17_39240804](https://user-images.githubusercontent.com/4933056/29988725-ccaf4d2c-8f3c-11e7-9ee3-b5389a5717cf.png)
![17_39240816_deletion](https://user-images.githubusercontent.com/4933056/29988726-ccb57332-8f3c-11e7-8346-4fd9ea000b80.png)
![19_4511575_78_80_81](https://user-images.githubusercontent.com/4933056/29988727-ccb7828a-8f3c-11e7-8eb1-9607b5a6e1d7.png)
![20_29652196](https://user-images.githubusercontent.com/4933056/29988729-ccbbae82-8f3c-11e7-8e57-6540815b2141.png)
![22_23040462](https://user-images.githubusercontent.com/4933056/29988730-ccbf5a50-8f3c-11e7-9103-0efcd5518b61.png)

**Comment by ldgauthier** [comment]
The MUC* genes are slippery mofos (both figuratively and literally because they encode proteins for mucus!) with a lot of repetitive sequence that maps reasonably well to multiple places (see the self-chain track: https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr3%3A195511664-195511896&hgsid=606289117_FcbJ6YRk5hebRNiuQQLNK8ulx9ob)  Those chr3 discrepancies are likely due to the different active regions bounds, as you found by changing the interval.  Can you filter your list down to things that don't have hits on the self-chain or repeat-masker tracks?  You can download the tracks at https://genome.ucsc.edu/cgi-bin/hgTables?hgsid=606289117_FcbJ6YRk5hebRNiuQQLNK8ulx9ob but IGV will want you to sort and index them with bedtools.  Let me know if you need help.

Also, @droazen does GATK4 output the boundaries of the actual assembly data used, as for the active region bounds from GATK debug output?  Those could be good to compare.

**Comment by ldgauthier** [comment]
Also were the no-calls in GATK3 [0,0,0] PLs?  That's a symptom of funky assembly too.

**Comment by skwalker** [comment]
@ldgauthier when I do the same interval list minus the self-chain and repeat-master intervals I see only 3 sites where GATK3 and GATK4 differ, compared to 29 before. And the sites have pretty low QUALs so I'm guessing it's okay. Did we expect the way assembly was happening to change between GATK3 and GATK4?

Called in GATK4, missing from GATK3:
`11	48387668	.	C	G	78.77	.	CONC_ST=FP,TN	GT:AD:DP:GQ:PL	0/1:14,3:17:99:107,0,416	./.`
Called in GATK3, missing from GATK4:
`8	144522386	.	TGAG	T	38.73	.	CONC_ST=TN,FN	GT:AD:DP:GQ:PL	./.	0/1:31,4:35:76:76,0,1300`
`11	48387757	.	A	C	15.88	.	CONC_ST=TN,FN	GT:AD:DP:GQ:PL	./.	0/1:18,2:20:44:44,0,495`

**Comment by skwalker** [comment]
I ran it with:
```
bam=seq/picard_aggregation/D5227/NexPond-391382/current/NexPond-391382.bam
exomeTargets='/seq/references/HybSelOligos/whole_exome_illumina_coding_v1/whole_exome_illumina_coding_v1.Homo_sapiens_assembly19.targets.interval_list'
ref='/seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta'
dbsnp='/seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.dbsnp.vcf'
```

**Comment by skwalker** [comment]
memory / timing differences [gatk3_gatk4.xlsx](https://github.com/broadinstitute/gatk/files/1318287/Copy.of.gatk3_gatk4.xlsx)

**Comment by ldgauthier** [comment]
The gVCF with intervals cases are pretty horrific.  Is there anything different about intervals in the engine that might be responsible @lbergelson ?  Would that tool-dependent look-ahead have an effect here?

**Comment by droazen** [comment]
Looking into that issue now @ldgauthier...

**Comment by droazen** [comment]
This was done -- closing.
