### ISSUE TITLE
Port allele-specific annotations from GATK3

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1641]

**Comment by droazen** [comment]
Re-assigning to @akiezun, since he requested a few non-performance tickets to keep him from losing his sanity. This ticket should also encapsulate porting any other changes to the GATK3 annotation subsystem that have happened since the allele-specific support was added.

**Comment by akiezun** [comment]
done in https://github.com/broadinstitute/gatk/pull/1840 and https://github.com/broadinstitute/gatk-protected/pull/554
