### ISSUE TITLE
Port additional metrics to Spark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1643]
For this quarter, let's port some additional Picard metrics that are used by production.

**Comment by droazen** [comment]
(This ticket should spawn additional sub-tickets)

**Comment by droazen** [comment]
First task here is to examine the pipeline in https://github.com/broadinstitute/dsde-pipelines/blob/master/genomes_in_the_cloud/single_sample/PairedSingleSampleWf.wdl and determine which metrics used in production still need to be ported to Spark by us.

**Comment by cmnbroad** [comment]
WIP commit [here](https://github.com/broadinstitute/gatk/commit/45bac26ca158546afb3d36fd33195bce9f4f193d) with a proposed approach to factoring Spark metrics collectors so they work both as a standalone tool or on behalf of CollectMultipleMetricsSpark, which reuses a single RDD across multiple metrics tools.

**Comment by cmnbroad** [comment]
@droazen If you get a chance take a look at the branch linked in the comment above (not for code review, just discussion of the approach), and/or we can discuss when I'm in later this week.

**Comment by droazen** [comment]
Adding @jamesemery as a co-assignee along with @cmnbroad. @jamesemery feel free to port one or more metrics to spark once @cmnbroad's framework is fully merged, if you have the time/inclination or need a break from your other spark tickets.

**Comment by droazen** [comment]
This was done
