### ISSUE TITLE
Add ability to downsample reads in Spark at the Hadoop-BAM level.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1644]
We want to downsample pathological regions at the Hadoop-BAM level, before paying the cost of loading all the reads into an RDD. Probably we want something like a `ReservoirDownsampler` that downsamples on a per-alignment-start basis.

**Comment by tomwhite** [comment]
Could you use the built in [sample](http://spark.apache.org/docs/latest/api/java/org/apache/spark/api/java/JavaRDD.html#sample(boolean,%20double)) method?

**Comment by droazen** [comment]
@tomwhite Well, the idea is to downsample **before** we pay the cost of holding all the reads in memory -- with `sample` I think you'd be downsampling after we've paid that cost. The `ReservoirDownsampler` in GATK4 is able to perform a fair elimination on a stream of items as they come in, without having to store all the items in memory at once, and guaranteeing that every item has an equal probability of ending up in the final set.

Also, I think we might want to downsample on a per-alignment-start basis, rather than per-spark-partition. We want protection against the situation where mapping artifacts have caused an insane number of reads to be aligned to the same position, without eliminating coverage at positions that do not pose a problem for us.

**Comment by tomwhite** [comment]
Downsampling doesn’t have to be to an exact level of coverage, it's just to avoid very high areas, so you might be able to do this on a Spark partition basis. Use mapPartitions to iterate through the reads in a partition, downsampling as you go (a bit like LocusIteratorByState does). If reads for a given alignment start cross a partition, then this would just mean you get up to 2C coverage at that point, where C is the target downsample coverage. This would solve the problem you outlined, without having to push the downsampling logic into Hadoop-BAM. Could that work?

**Comment by droazen** [comment]
@tomwhite If there are a million reads mapped to the same position, my hope was that we could avoid loading them into an RDD at all, if possible (ie., eliminate as they are first read in), rather than load them into an RDD and then downsample. This is why I proposed doing this at the Hadoop-BAM layer. Do you think this is possible?

**Comment by tomwhite** [comment]
What I'm suggesting does not actually load the reads into the RDD. The RDD knows about input splits, and when you call mapPartitions it iterates through the reads in each split, which is the point at which the downsampling can be applied. So there's no point at which the million reads are held in memory. Does that make more sense?

**Comment by droazen** [comment]
Discussed in person -- @tomwhite convinced us that his approach would work, provided that the maximum coverage we expect to encounter would not be distributed over too many partitions (eg., hundreds rather than tens of thousands). As part of this ticket, we should determine how many partitions 1 million reads would get distributed over given our default settings in GATK4.

**Comment by droazen** [comment]
This one is not happening for alpha-2 -- removing milestone.

**Comment by droazen** [comment]
Re-assigning to @tomwhite as a possible future project, since he has a clear idea of how this could be implemented.
