### ISSUE TITLE
Build and package both .so and .dylib for native libraries

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1645]

**Comment by akiezun** [comment]
@lbergelson can this be closed or what else needs to be done here?

**Comment by droazen** [comment]
This is being handled in a different way, and will be closed shortly.

**Comment by lbergelson** [comment]
Yeah, this is being delegated to intel eventually, and until then david  has a plan to put them in a jar on artifactory.

**Comment by droazen** [comment]
Closing -- this should be fixed now
