### ISSUE TITLE
ReadsPipelineSpark expanded and benchmarked: from BWA -> HaplotypeCaller 

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1646]

**Comment by droazen** [comment]
Let's expand the existing `ReadsPipelineSpark` in both directions, so that it extends from `BWA` to the `HaplotypeCaller`

**Comment by droazen** [comment]
Requires https://github.com/broadinstitute/gatk/issues/1517 and https://github.com/broadinstitute/gatk/issues/1639

**Comment by akiezun** [comment]
this ticket itself is just to hook up and run

**Comment by akiezun** [comment]
closing - replaced  by #1904 and #1905
