### ISSUE TITLE
Better GATK-wide support for HDFS and GCS (via Java NIO Path and htsjdk-level patches)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1648]

**Comment by droazen** [comment]
Depends on https://github.com/broadinstitute/gatk/issues/958

**Comment by lbergelson** [comment]
Also depends on https://github.com/broadinstitute/gatk/issues/1547

**Comment by droazen** [comment]
Replaced by the more specific https://github.com/broadinstitute/gatk/issues/3709
