### ISSUE TITLE
Enable query-by-interval of VCFs (including blockgzipped VCFs) on Spark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1651]

**Comment by tomwhite** [comment]
This depends on https://github.com/HadoopGenomics/Hadoop-BAM/issues/71 (PR in https://github.com/HadoopGenomics/Hadoop-BAM/pull/81).

**Comment by akiezun** [comment]
@tomwhite do you have an update on this? The HadoopBAM PRs are resolved now

**Comment by tomwhite** [comment]
@akiezun I started looking at this, but I have a question about the sequence dictionary. I've added intervals tests to CountVariantsSparkIntegrationTest, but I get

```
We require at least one input source that has a sequence dictionary (reference or reads) when intervals are specified
```

Any thoughts about how to specify the sequence dictionary when the only input is a VCF (count_variants.vcf in this test)?

**Comment by tomwhite** [comment]
See https://github.com/broadinstitute/gatk/commit/6fe684622d5365861fe3655430b42c273f9ada2b

**Comment by akiezun** [comment]
this is related to https://github.com/broadinstitute/gatk/issues/1310

**Comment by akiezun** [comment]
@tomwhite does this work on non-indexed files? or do they need to be tribble or tabix indexed?

**Comment by tomwhite** [comment]
@akiezun the Hadoop-BAM part uses tabix files to filter which splits are needed, but it will still work (although potentially much slower) if no tabix files are provided.
