### ISSUE TITLE
Create official Spark GATK APIs for common traversal patterns for tool builders

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1652]
Currently we have `GATKSparkTool` as a catch-all for all Spark tools. We should have `ReadSparkTool`, `VariantSparkTool`, etc., interfaces with well-defined APIs.

**Comment by droazen** [comment]
This was done by @tomwhite

**Comment by tomwhite** [comment]
For the record, this was https://github.com/broadinstitute/gatk/pull/2256.
