### ISSUE TITLE
Investigate/prototype potential variant store implementations

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1659]

**Comment by droazen** [comment]
@tomwhite I'm told you've done some work in the past with variant stores. Since we're now moving into working on the variant part of the pipeline, we'd like to assess our options for storing/accessing variants efficiently. Perhaps you could present some of your past work, and/or prototype some technologies you think are promising? We're going to look at TileDB (https://github.com/broadinstitute/gatk/issues/1647), but we'd like to get your suggestions/thoughts on this.

**Comment by tomwhite** [comment]
@droazen sure. Probably best to talk about this in-person next week.

**Comment by droazen** [comment]
Moving to a future milestone, since for alpha-2 we're going to focus on TileDB (#1647)

**Comment by droazen** [comment]
Closing, as we're going to be using GenomicsDB as our variant store going forward
