### ISSUE TITLE
Tune the "recommendedNumReducers" for ReadsPipelineSpark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1660]
`ReadsPipelineSpark` should override `GATKSparkTool.getRecommendedNumReducers()` to provide an appropriate default value for the `numReducers` argument. The default gives us one partition per 10MB of input, which may be too small for this pipeline (it was kept small on purpose due to memory issues, but perhaps these have been resolved?)

**Comment by akiezun** [comment]
the number of reducers seems to be pretty irrelevant. I ran ReadsPipelineSpark on a 35GB file, with 60 executors, 1 CPU per exec, 7 GB per exec.

60    reducers -> 18 min first tree aggregate, > 12 mins on save, I killed it after that
270  reducers -> 13 mins first tree aggregate, 5.5 min save
1000 reducers  -> 11 min first tree aggregate, 5.0 min save
2000 reducers -> 11 min first tree aggregate, 5.1 min save
3539 reducers -> 11 min first treeAgg, 5.9 min save
