### ISSUE TITLE
Implement at least one good roundtrip test bam -> cram -> bam in htsjdk

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1661]
Despite much development work in the past year to iron the bugs out of htsjdk's cram implementation, there is still a need for much better, more robust tests, as we keep running into new issues. In particular, we need roundtrip bam -> cram -> bam tests on non-trivially-sized inputs.

**Comment by cmnbroad** [comment]
Test case list is kept at https://github.com/samtools/htsjdk/issues/592.

**Comment by droazen** [comment]
This is an ongoing effort

**Comment by cmnbroad** [comment]
There is an htsjdk PR for this here: https://github.com/samtools/htsjdk/pull/720.

**Comment by cmnbroad** [comment]
Closed via https://github.com/samtools/htsjdk/pull/720.
