### ISSUE TITLE
Inconsistent comments about low-weight chain pruning

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#1672]
Some comments on low-weight chain pruning in `LowWeightChainPruner`, `BaseGraph`, and `ReadThreadingAssembler` state that chains in which *any* edge has low weight are pruned.  Other comments say chains in which *all* edges have low weight are pruned.  The latter is what the code actually does.

**Comment by droazen** [comment]
@davidbenjamin Would you be able to contribute a patch to fix this?

**Comment by davidbenjamin** [comment]
Sure!

**Comment by davidbenjamin** [comment]
Closed in PR #1678.
