### ISSUE TITLE
Cram query using .crai returns incorrect results

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1673]

**Comment by cmnbroad** [comment]
There were quite a few other failing cases for cram queries; the fixes and a boatload of new tests are in https://github.com/samtools/htsjdk/pull/552.

**Comment by cmnbroad** [comment]
https://github.com/broadinstitute/gatk/pull/1962 reenabled the test; fix was pulled inf rom htsjdk in https://github.com/broadinstitute/gatk/pull/1958.
