### ISSUE TITLE
Audit ReadsDataSource for bugs related to header merging and contig indices

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1674]
ReadsDataSource uses the headers for individual bams when instantiating the individual iterators for each bam, but uses the merged header everywhere else when multiple bams are present. We need to verify that there are no issues/bugs related to contig indices changing in the merged header. There shouldn't be, since we use contig names everywhere except `SamReaderQueryingIterator` (where you definitely want the contig index to match the index from the bam file in question), but it doesn't hurt to spend a little time (no more than 1-2 days) double-checking and testing the case of reading multiple bams where the contig indices in the final merged header differ from the indices in the original files.

**Comment by droazen** [comment]
As part of this, should also look at the way `ReadWalker` uses the merged header to parse the intervals for traversal, and ensure that there are no possible issues in a multi-bam context.

`reads.setTraversalBounds(intervalArgumentCollection.getTraversalParameters(getHeaderForReads().getSequenceDictionary()))`

**Comment by droazen** [comment]
@cmnbroad Is this one satisfied by your merged PR https://github.com/broadinstitute/gatk/issues/2205 ?

**Comment by cmnbroad** [comment]
Closed via #2205.
