### ISSUE TITLE
Determine how much of the total runtime the broadcast step takes up in the Spark BQSR

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1675]
We need to prove that the broadcast of the reference and variants takes up a non-trivial fraction of the runtime of the Spark BQSR before it's worthwhile to consider optimizations/extra complexity like https://github.com/broadinstitute/gatk/issues/1407. We also need to understand:

-how the cost of the broadcasts scale as you add more nodes
-how the cost of the broadcasts scale as vcf file size increases

Should not be too difficult to determine this, and it seems like a necessary prerequisite to things like https://github.com/broadinstitute/gatk/issues/1407

**Comment by droazen** [comment]
For alpha-2 and @akiezun

**Comment by akiezun** [comment]
one knob to try is `spark.broadcast.blockSize`

**Comment by akiezun** [comment]
Here’s one example executor from a recent run

This the the variants broadcast (4 seconds using 100MB blocks)
```
16/04/11 20:55:24 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 3
...
16/04/11 20:55:28 INFO broadcast.TorrentBroadcast: Reading broadcast variable 3 took 3913 ms
...
16/04/11 20:55:35 INFO storage.MemoryStore: Block broadcast_3 stored as values in memory (estimated size 655.5 MB, free 2.9 GB)
```

This the the reference broadcast (130 seconds using 100MB blocks)
```
16/04/11 20:55:35 INFO broadcast.TorrentBroadcast: Started reading broadcast variable 4
...
16/04/11 20:57:46 INFO broadcast.TorrentBroadcast: Reading broadcast variable 4 took 130726 ms
...
16/04/11 20:57:47 INFO storage.MemoryStore: Block broadcast_4 stored as values in memory (estimated size 739.6 MB, free 1505.0 MB)
```

**Comment by akiezun** [comment]
another executor: 
```Reading broadcast variable 3 took 34917 ms```
```Reading broadcast variable 4 took 121334 ms```

and another one:
```Reading broadcast variable 3 took 35354 ms```
```Reading broadcast variable 4 took 76535 ms```

Changing `spark.broadcast.blockSize` to 400M may slow it down:
```Reading broadcast variable 3 took 16235 ms```
```Reading broadcast variable 4 took 140846 ms```

**Comment by akiezun** [comment]
conclusion - broadcast of the big data items (reference and reads) takes around 2-3 minutes per executor and it's not really influenced by broadcast block size. Also broadcast of reference takes longer than variants. 

To me this means we should look for better savings elsewhere for now.

**Comment by droazen** [comment]
Re-opening -- I don't think we've answered all of the important questions here -- in particular:

-what % of total wall-clock runtime does the broadcast step take up?
-how does this change (if at all) as you add/remove executors?
-how does this change if you increase the vcf file size?

These are critical questions that will have a huge influence on the decisions we make in Q2 with respect to Spark performance work.

**Comment by droazen** [comment]
In other words, saying that broadcast took X minutes is not meaningful unless it's framed as a fraction of total runtime, and we understand whether this is a fixed or variable cost.

**Comment by akiezun** [comment]
i shrunk the sites vcf to 3pct of its size (tossing mot variants) and the runtime did not change

**Comment by akiezun** [comment]
i rerun with empty cluster and tiny vcf file. absolutely no difference in runtime for readspipeline. I think we should close this - any objections, @droazen ?

**Comment by droazen** [comment]
@akiezun You've tried decreasing the vcf size, but what about increasing it by ~10x? Does broadcast fall apart then? Also trying increasing # of executors by ~10x and see if broadcast gets much worse. And you need some stats showing broadcast as a % of total wall-clock runtime, instead of just as an absolute time.

**Comment by akiezun** [comment]
what would increasing vcf size show that we dont already know? Of course it will fail because i only allocated 7GB per executor so if vcf is 30GB it will fail to broadcast. I'm still not sure how to measure % of wallclock time.

**Comment by droazen** [comment]
Increasing the vcf size would give us a sense of how the broadcast scales with input size -- I don't think you have enough data points to draw any conclusions there yet. Also, you could increase the memory per executor to allow the larger broadcasts to work -- point is to figure out whether the network/bittorrent protocol is a bottleneck.

**Comment by droazen** [comment]
As for % of wallclock time...you know the broadcast times (as reported above) -- don't you know the wallclock time of each run too?

**Comment by droazen** [comment]
Re-assigning to @jamesemery

**Comment by jamesemery** [comment]
[Broadcast data presentation.pdf](https://github.com/broadinstitute/gatk/files/369684/Broadcast.data.presentation.pdf)

Here is a link to the presentation I gave on the broadcasting profiling data that I collected. The big takeaways are:

- Broadcasting is relatively time efficient and appears to scale linearly with filesize
- Reference broadcasting takes longer and is much more variable compared to the variants which get broadcast immediately before
- There doesn't seem to be any memory shared between executors for broadcast variables, making it very memory inefficient when there are many executors 
- The brodcast block size is best kept small, (in the order of 4-10MB) as it can explode the broadcast time to be very slow
- Having files in HDFS is significantly faster than using the GCS adapter for large file sizes

**Comment by droazen** [comment]
Closing this as resolved
