### ISSUE TITLE
Port gatk-launch to protected

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1676]

**Comment by droazen** [comment]
For @lbergelson

**Comment by droazen** [comment]
Moving to alpha-1, as we really need to have this done before the release. We also need to update the protected README with usage instructions for `gatk-launch`

**Comment by droazen** [comment]
Still happening for alpha-1 @lbergelson ?

**Comment by lbergelson** [comment]
closed by https://github.com/broadinstitute/gatk-protected/pull/457 and #1772
