### ISSUE TITLE
intelDeflator.so isn't packaged in spark or shadow jars

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1680]
The intel deflator should be packaged as part of our spark and shadow jars.

**Comment by akiezun** [comment]
blocked by #1903

**Comment by akiezun** [comment]
assigning to @gspowley - this is part of transitioning to the use of Intel GKL

**Comment by droazen** [comment]
@akiezun Is this one fixed?

**Comment by lbergelson** [comment]
This should be magically included in the gkl.

**Comment by droazen** [comment]
Ok, closing then
