### ISSUE TITLE
Warn (and optionally blow up) when index on input file is out-of-date

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1683]
Can port the index-out-of-date detection code from GATK3. Unlike GATK3, however, we should not attempt to lock and/or re-generate out-of-date or missing indices on input files.

Requested by @eitanbanks

**Comment by droazen** [comment]
For @cmnbroad

**Comment by vdauwera** [comment]
Please be sure to make the blowing up optional (for super-strict stringency or something like that). When we move test files or tutorial data around the index often gets copied first (cause it's smaller) so we get out of date warnings. Would be really painful if that caused blowups systematically.

**Comment by akiezun** [comment]
I think this is done. @cmnbroad are you doing any work for it? I did some in #1425.

**Comment by droazen** [comment]
This is not done -- what's missing is the option to "optionally blow up", and hooking this check up to bam indices as well.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/5571
