### ISSUE TITLE
Code duplication in InfiniteRandomMatingPopulationModel

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#1684]
In `InfiniteRandomMatingPopulationModel` the methods `singleSampleLikelihoods`, `multiSampleHeterogeneousPloidyModelLikelihoods`, and `multiSampleHomogeneousPloidyModelLikelihoods` do almost exactly the same thing with almost identical code.  It does not appear that the assumptions of a single sample or homogeneous ploidy are used for any optimizations, unless you count not repeating the ploidy getter.  @lbergelson am I missing something?

**Comment by droazen** [comment]
@davidbenjamin I suspect you're looking at master -- please take a look at the branch `dr_runnable_haplotypecaller`, where this code is actually hooked up.

**Comment by davidbenjamin** [comment]
@droazen I'm already on `dr_runnable_haplotypecaller`.  It's not that the code doesn't make sense, just that I don't see what is gained by splitting the method into three separate cases.

**Comment by droazen** [comment]
@davidbenjamin Fair enough, feel free to submit a patch any time after `dr_runnable_haplotypecaller` hits master.
