### ISSUE TITLE
Incorrect class names and comments regarding HWE

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#1686]
`InfiniteRandomMatingPopulationModel` is simpler than its name suggests.  The *only* assumption it makes is that samples have independent genotypes -- after all, the only thing it really does is delegate the calculation, independently for each sample, to `GenotypeLikelihoodCalculator`.  Any further assumptions are built into `GenotypeLikelihoodCalculator`.  In particular, it is the latter class that assumes Hardy-Weinberg equilibrium (independent alleles).  Does anyone else like @vruano or @ldgauthier think that `InfiniteRandomMatingPopulationModel` should be renamed something like `IndependentSamplesModel` and the comment: `And genotypes should exhibit the ratios expected under HWE` moved to `GenotypeLikelihoodCalculator`?

**Comment by ldgauthier** [comment]
I agree that's a silly name and I'm in favor of renaming.  My seemingly arbitrary logic for that which I want to rename and that which I'd prefer remains the same is if I already know where things are.  ;)

I'm not sure I understand the way in which the GenotypeLikelihoodCalculator assumes Hardy-Weinberg equilibrium.  It does assume independent alleles, but that's also true in a lot of scenarios where HWE doesn't hold.

**Comment by davidbenjamin** [comment]
Good point.  So maybe the comment should be moved and rewritten in terms of independent alleles without making any grandiose claims about HWE?

**Comment by ldgauthier** [comment]
Sounds good.  With all due respect to @vruano I think the statements about the assumptions could be made a lot more general.  For example, we don't know that the samples all come from the same population, in which case HWE would not be expected.

**Comment by davidbenjamin** [comment]
Actually, `GenotypeLikelihoodCalculator` shouldn't get *any* new comment, because only posterior probabilities, not likelihoods, contain prior assumptions on allele independence, HWE, etc.

**Comment by davidbenjamin** [comment]
Closed by PR #1855.
