### ISSUE TITLE
Make sure we can process large numbers of contigs efficiently

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#1688]
GATK3 is very slow when processing references with large numbers of contigs, such as draft genomes. In the past this mostly affected microbial genomes so we didn't do anything about it, but now the Hg38 has a lot more contigs so we have to make sure that's not going to be a problem with GATK4. 

To be clear, efficient processing of reference genomes with thousands of contigs is a must-have. 

Efficient processing of e.g. microbial draft genomes with tens of thousands of contigs is a nice-to-have. More than that is just crazy talk.

**Comment by akiezun** [comment]
Can you describe more precisely what you mean by "processing" here?

On Wednesday, April 6, 2016, Geraldine Van der Auwera <
notifications@github.com> wrote:

> GATK3 is very slow when processing references with large numbers of
> contigs, such as draft genomes. In the past this mostly affected microbial
> genomes so we didn't do anything about it, but now the Hg38 has a lot more
> contigs so we have to make sure that's not going to be a problem with
> GATK4.
>
> To be clear, efficient processing of reference genomes with thousands of
> contigs is a must-have.
>
> Efficient processing of e.g. microbial draft genomes with tens of
> thousands of contigs is a nice-to-have. More than that is just crazy talk.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gatk/issues/1688>
>


-- 
Sent from Gmail Mobile

**Comment by vdauwera** [comment]
Reading in the contents and doing any sort of operation on them. I believe @droazen is aware of why this occurs in GATK3 -- he explained it to me a long time ago. At the time we put it down as a known limitation but after discussing some challenges associated with Hg38 with @ebanks it sounds like it's going to be important to avoid or mitigate the problem in GATK4.

**Comment by akiezun** [comment]
Do you have a dataset and a commandline that demonstrates the problem?

**Comment by vdauwera** [comment]
Not currently but we can get one if needed.

**Comment by akiezun** [comment]
definitely needed if this issue is to be addressed

**Comment by vdauwera** [comment]
OK, will try to put that together. Any chance you already have a sense of whether that could be an issue based on the system design?

**Comment by akiezun** [comment]
i prefer to measure, not guess

**Comment by vdauwera** [comment]
![image](https://cloud.githubusercontent.com/assets/2748435/14325169/0ece3db6-fbf6-11e5-87fb-07f947348238.png)

**Comment by akiezun** [comment]
let's not put a milestone until we have a testcase

**Comment by vdauwera** [comment]
Saw the recent https://github.com/samtools/htsjdk/pull/744 fix in htsjdk; I'm going to assume that it fixed whatever performance problems people have had previously linked to large genomes. If someone runs into new issues we'll create new ticket as appropriate.

**Comment by magicDGS** [comment]
The htsjdk fix is not directly apply to any downstream project, but should be implemented as in https://github.com/broadinstitute/picard/pull/687. Nevertheless, I opened an issue about this (#2284) so I guess that anyway is fine to close this one.
