### ISSUE TITLE
Investigate spark-submit --files as a broadcast replacement

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1689]
figure out how spark-submit --files works:
- [x] does it send files like it promises **yes**
- [x] where does it put them?
  **I believe it puts them in the working directory of the executor.**
- [ ] does cache them between runs?
- [ ] how do updates to the files work if it caches them?

**Comment by droazen** [comment]
Reassigning to @jamesemery

**Comment by droazen** [comment]
Would be good to know if there's an equivalent feature for `gcloud`

**Comment by lbergelson** [comment]
There is.  Gatk-launch should be handling --files for both yarn and dataproc.  I think James found some bug with gatk-launch and multiple files passed in, can't remember exactly what it was but it should be a simple fix.

**Comment by droazen** [comment]
This was done last summer
