### ISSUE TITLE
benchmark serial index creation on a bam file

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1690]
Find out how long it actually takes to index a bam file serially.  Do we need to do this in parallel?

**Comment by akiezun** [comment]
do you mean bai or splitting? Using samtools or gatk or something else?

**Comment by akiezun** [comment]
30 GB file on NFS
time samtools index CEUTrio.HiSeq.WEx.b37.NA12892.bam
real	5m18.298s
user	5m5.198s

**Comment by droazen** [comment]
@akiezun Does this mean that we can close https://github.com/broadinstitute/gatk/issues/1570?
