### ISSUE TITLE
Allow gatk-launch to be used with a fully-packaged jar, outside of the github source tree

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1693]

**Comment by droazen** [comment]
@lbergelson Please close if this already works and I just don't realize it :)

**Comment by droazen** [comment]
Although, if it **does** work, we should document in the `README` how to use it with a packaged jar in arbitrary locations.

**Comment by lbergelson** [comment]
No option for this yet. It has an option to specify the location of the spark jar, but it expects the non-spark installation to be the source directory.  We can add it in.  How do you envision people setting this up?

**Comment by droazen** [comment]
How about: first check an environment variable for the location of the GATK jar, and if it's not set check the script's working directory for a jar? Whatever we do should be consistent across the spark and non-spark jars.

**Comment by lbergelson** [comment]
That's what we do for the spark jar, easy to extend it to work for a non-spark jar too.  What I mean though, is when someone downloads a packaged gatk, what do they get/ how do they install it?

**Comment by droazen** [comment]
We'll need to distribute it alongside the packaged jar on our download page. Perhaps both could be distributed within a downloadable `tar.gz` (we've done this in the past to bundle example code with the pre-built jars).

**Comment by droazen** [comment]
Let's definitely try to get this working before our next release, so that we can have a sane binary distribution with 2 packaged jars (shadowJar and sparkJar), plus a launcher.

**Comment by lbergelson** [comment]
I don't think it's much different to have a zip file with 2 jars in it vs a zip file with a directory tree.  This will add an additional layer of complexity to testing.  I.e. do we test the packaged jars, now our unit tests run with a different configuration than the other tests, etc..  

What we probably really want is some sort of executable archive that wraps whatever we put in it into a single runnable file.  I'm not sure how to do that exactly, but if self extracting zip files are a thing there should be a way to do it.

**Comment by droazen** [comment]
The executable archive you're imagining would be a platform-dependent thing. A use case we care about is GATK users being able to freely copy a particular GATK jar across different machines and architectures and have it work transparently, as we recently discussed with @vdauwera. I still think we should plan on having a packaged jar + launcher unless you can come up with a more specific proposal for your executable archive idea.
