### ISSUE TITLE
Investigate whether htsjdk async I/O could be used in spark at the Hadoop-BAM layer

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1696]

**Comment by droazen** [comment]
Assigning to @tomwhite for an opinion. If it seems possible, should consult with @akiezun on implementation details.

**Comment by droazen** [comment]
Cf. performance results in https://github.com/broadinstitute/gatk/pull/1695

**Comment by tomwhite** [comment]
It doesn't look like we can easily take advantage of async IO at the moment (see https://github.com/HadoopGenomics/Hadoop-BAM/pull/94 and https://github.com/samtools/htsjdk/pull/576), so closing this.
