### ISSUE TITLE
Overhaul variant QUAL score calculation

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#1697]
Heng's paper _"A statistical framework for SNP calling. . ."_ presents two methods for calculating a variant QUAL score.  The first and simpler approach finds a maximum likelihood allele fraction.  The second, which is implemented in the GATK, enumerates the likelihoods of all possible partitions of allele counts among the total ploidy of all samples.

The latter approach becomes nightmarish (in terms of speed and code complexity) for non-diploid organisms _or_ multiple alt alleles and scales poorly (quadratically, I believe) with the number of samples.  Known bugs in the calculation -- and the difficulty of repairing them -- can be attributed to its complexity.  And its treatment of multiple alt alleles involves a major hack.

The task is to generalize the allele fraction (as opposed to allele count) equations to non-diploid samples with multiple alt alleles, figure out appropriate priors, and implement it as a new QUAL score calculator.

**Comment by vdauwera** [comment]
![image](https://cloud.githubusercontent.com/assets/2748435/14392742/ea36a19a-fd90-11e5-9cd6-0dc079f659c4.png)

**Comment by vruano** [comment]
There is some implementation for the MLE ratio test calculation in a branch of mine.

**Comment by vruano** [comment]
Not the ratio test but the MLE AF using EM. The ratio test is easy after you have that.

https://github.com/broadinstitute/gsa-unstable/tree/vrr_em_ml_af_and_qual_estimation

**Comment by vdauwera** [comment]
When this is done, please let me know so we can talk about back-porting to GATK3

**Comment by davidbenjamin** [comment]
@vruano That's great!  How close is it to a PR?  I can volunteer as code reviewer.

**Comment by davidbenjamin** [comment]
Note: issue #1891 is a prerequisite.

**Comment by ldgauthier** [comment]
In the course of investigating https://github.com/broadinstitute/gsa-unstable/issues/1409 a few things came up that I want to document for when it's time to test the new model:
- Throw away the spanning deletions alleles!  They shouldn't affect the QUAL anymore since we won't be using the independent alleles approximation, but I don't want them mucking with the site type and choice of prior (SNP vs INDEL)
- For the purposes of QD for VQSR, we should be using AS_QD very shortly, in which case the choice of prior for mixed sites will be clear because we're evaluating per-allele
- For the purposes of QUAL for emission, at mixed sites I'm in favor of continuing to apply the SNP prior in accordance with the doctrine of maximal sensitivity until VQSR

**Comment by davidbenjamin** [comment]
> the choice of prior for mixed sites will be clear because we're evaluating per-allele

@ldgauthier I don't recall whether we've discussed this but the new model does handle mixed sites very naturally by assigning separate indel/SNP pseudocountsto indel/SNP alleles in the Dirichlet prior on allele frequencies.

**Comment by davidbenjamin** [comment]
@vdauwera The new qual is now merged into GATK4.  The old one is still there for now and is used by default.  You can turn on the new one with the `-newQual` argument in `HaplotypeCaller` and `GenotypeGVCFs`.  I'll open the ticket to back-port and self-assign it now.

**Comment by vdauwera** [comment]
Wonderful, thanks @davidbenjamin !

**Comment by davidbenjamin** [comment]
Note: new AFCalculator added in PR #2098, but this issue can't be considered closed until the old model has been eradicated.

**Comment by ldgauthier** [comment]
:+1: to eliminating the confusion of the mixed sites prior.

Is the `-newQual` the only commandline change that's needed to run the new model?  I got a little distracted by the prnm comment in the PR review.

**Comment by davidbenjamin** [comment]
Yes, just `-newQual`, though `pnrm` would have been more elegant.

**Comment by davidbenjamin** [comment]
Status update: the new qual is finished, backported, and validated in both GATK4 and the backport.  In a validation of a subset of ExAC data (many samples) and 1kg data (low coverage) it finds all variants found with the old qual and saves many manifestly true multiallelics.

I'm going to close this and open a new issue to delete the old qual.

**Comment by ldgauthier** [comment]
Woohoo!
