### ISSUE TITLE
async BAM writing errors

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1699]
hmm, async bam writing causes this:

```
Gradle suite > Gradle test > org.broadinstitute.hellbender.utils.read.ArtificialBAMBuilderUnitTest.testBamProvider[4](ArtificialBAMBuilder{samples=[sample0], readLength=10, alignmentStart=1, skipNLoci=0, nLoci=100, nReadsPerLocus=10}, 10, 0, 1, 1, 10, 100) FAILED
    java.lang.RuntimeException: Queue should be empty but is size: 276
        at htsjdk.samtools.util.AbstractAsyncWriter.close(AbstractAsyncWriter.java:75)
        at org.broadinstitute.hellbender.utils.read.ArtificialBAMBuilder.makeBAMFile(ArtificialBAMBuilder.java:143)
        at org.broadinstitute.hellbender.utils.read.ArtificialBAMBuilder.makeTemporaryBAMFile(ArtificialBAMBuilder.java:130)
        at org.broadinstitute.hellbender.utils.read.ArtificialBAMBuilderUnitTest.testBamProvider(ArtificialBAMBuilderUnitTest.java:69)
```

**Comment by lbergelson** [comment]
Does it always cause that error or is it a non-deterministic failure?

**Comment by akiezun** [comment]
not always

**Comment by akiezun** [comment]
something i don't understand in `AbstractAsyncWriter` in htsjdk:
1. our main thread is writing records and then calls close():
2. let's say at this moment there are 276 records in the blocking queue.
3. now, when main thread calls `close()` the `isClosed` flag get turned off. But the queue is not empty so writer is not signalled and main thread calls `join()` to wait for the writer to die
4. meanwhile, writer keeps running and then sees that `isClosed.get()` so stops running. **But the queue is still not empty** when the writer stops writing. Who then writes the rest of the queue data? I need help understanding that. @tfenne can you help me understand the htsjdk code here please?

**Comment by akiezun** [comment]
nevermind. Somehow i misread the loop code - it will keep going while there's stuff in the queue

**Comment by akiezun** [comment]
there's a fix for it in https://github.com/samtools/htsjdk/pull/565/files that has Tim's approval. Waiting for any objections for 1 day and will merge then.

**Comment by akiezun** [comment]
this is fixed
