### ISSUE TITLE
Setup Jenkins job to run gatk and picard tests off of every htsjdk master build

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1705]
As discussed in our meeting we should have an automated job to build run picard and gatk against the most recent htsjdk master build.

- [x] picard
- [x] gatk4

**Comment by lbergelson** [comment]
picard tests are now running automatically

**Comment by lbergelson** [comment]
GATK tests are now running as well.  They may need additional work on robustness.  Initial versions were failing to checkout the correct htsjdk version and silently passing on master.  There should be a better way to verify this.

**Comment by akiezun** [comment]
can you include the URL here?

**Comment by lbergelson** [comment]
https://gatk-jenkins.broadinstitute.org/view/HTSJDK%20Release%20Tests/  has a display showing a pipeline view of 3 jobs, 1 builds htsjdk on its own, it then launches picard and gatk4 tests on that version of htsjdk

all 3 green means that they succeeded, but for now we should dig into the console output and verify that they look ok until we've run it enough times that we trust nothing new and funny is going on.

**Comment by lbergelson** [comment]
Closing this.  Seems to be working.

**Comment by droazen** [comment]
Can you add a badge to htsjdk for these tests @lbergelson? One of our promises was that non-Broadies would be able to see the status of them.

**Comment by lbergelson** [comment]
Hmn.  I'm not sure how to get a single badge for all the tests.  I might need a picard badge and a gatk badge.

**Comment by droazen** [comment]
Multiple badges should be fine, provided we include a clear label for each one.
