### ISSUE TITLE
Request: Easy access to FeatureInput<VariantContext> in GATKTool for walkers that traverse VariantContext

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#1710]
In my case, as an API user, my main usage of GATK is for traverse `GATKRead` and `VariantContext`, so I would like to have in `GATKTool` a simpler way of access to the `FeatureInput<VariantContext>` instead of getting them from `FeatureManager features`.

It will be useful in the `VariantWalker` as a step to issue #692, to get all the variants provided by the user in the same walker.

My idea is modify the `GATKTool` to include:
- A `public abstract boolean requiresVariant()`, which will be used to determine if we should detach or not all the variants inputs from the `FeatureManager features`.
- A `private void initializeVariants()`, which will implement a way to extract the `FeatureInput<VariantContext>` from `features` and initialize a `FeatureManager variants` or a extended class which includes only `VariantContext` inputs.

**Comment by akiezun** [comment]
assigning to @droazen for an opinion

**Comment by magicDGS** [comment]
This is ancient and I do not require it anymore. Closing.
