### ISSUE TITLE
print tool help by default - save user time

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1725]
help should be printed by default not only after asking with `--help`

That is, typing this
```
./gatk-launch FilterVcf
```
should be exactly the same as
```
./gatk-launch FilterVcf --help
```

**Comment by droazen** [comment]
Seems like a good idea -- @lbergelson do you agree?

**Comment by lbergelson** [comment]
Sure.  Seems fine.

**Comment by vdauwera** [comment]
I'm a little confused on this one. If the two are the same, what's the point of having `--help`?  What does "help" consist of? Basic usage or additional resources and detailed tool information like list of arguments?

**Comment by akiezun** [comment]
consists of nothing. it's just there for convention

**Comment by droazen** [comment]
Yeah, there are two kinds of people in the world: those who type "--help" first thing when running new software, and those who type nothing expecting help. We should help both kinds of people :)

**Comment by lbergelson** [comment]
What happens if someone wants to write a tool that takes no arguments?

**Comment by droazen** [comment]
We've never had a no-arg tool before, and I'm skeptical that we ever will...

**Comment by vdauwera** [comment]
Ah, fair enough. I also can't imagine a tool with zero inputs.

**Comment by akiezun** [comment]
@lbergelson i can take this one if you want. let me know

**Comment by akiezun** [comment]
Requirements (consistent with picard)
`./gatk-launch CountReads` <- prints error message, usage help, exit code 1
`./gatk-launch CountReads --help` <- no error message, usage help, exit code 1
`./gatk-launch CountReads fred` <- prints error message, usage help, exit code 1
`./gatk-launch CountReads -I src/test/resources/large/expected.NA12878.RNAseq.splitNcigarReads.bam` <- exit code 0

**Comment by lbergelson** [comment]
I think something with --help should exit code 0...

**Comment by akiezun** [comment]
what about no args and `--version`?

**Comment by akiezun** [comment]
just looked as samtools - no args gives 1, --help gives 0, and --version gives 0

**Comment by lbergelson** [comment]
That sounds right to me.  Anything that's explicitly asking for information and then exiting should be 0.  No args is usually an error state.

**Comment by akiezun** [comment]
I agree.

**Comment by akiezun** [comment]
New requirements then:
```
./gatk-launch CountReads <- prints error message, usage help, exit code 1
./gatk-launch CountReads --help <- no error message, usage help, exit code 0
./gatk-launch CountReads fred <- prints error message, usage help, exit code 1
./gatk-launch CountReads -I src/test/resources/large/expected.NA12878.RNAseq.splitNcigarReads.bam <- exit code 0
./gatk-launch CountReads --version <- prints only version number, exit code 0 
```
