### ISSUE TITLE
Concordance testing against GATK3 annotations for HaplotypeCaller (with a configurable tolerance before failure)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1732]
The current port of the `HaplotypeCaller` in `dr_runnable_haplotypecaller` has several "fuzzy" integration tests, in addition to traditional "exact match" integration tests, that test that we're above a certain % of concordance with a known good set (currently, GATK 3 output) using selected parts of the records (eg., alleles, genotypes, start/end positions). We should try to expand this strategy to include fuzzy testing for other parts of the output as well, such as annotations, with the ultimate goal of moving away from exact-match testing for the `HaplotypeCaller`. Will need to be done in consultation with methods people, particularly @ldgauthier

**Comment by ldgauthier** [comment]
I have a dream...

**Comment by droazen** [comment]
Depends on https://github.com/broadinstitute/gatk/issues/3275

**Comment by droazen** [comment]
Closing -- replaced by https://github.com/broadinstitute/gatk/issues/5532
