### ISSUE TITLE
change default argument behavior for collections so that default values are overridden when a new value is specified

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#175]
Picard style was to have arguments with default collection values be appended to rather than replaced if that argument is also specified on the command line

to remove the defaults you have to specifically pass in `null` and then the new options

this seems like totally bizarre behavior, I thought I had fixed it with my initial patch but it slipped through unchanged

`RevertSam` relies on this functionality, so its interface will need to change slightly.

**Comment by akiezun** [comment]
@lbergelson can you clarify what the requirements are for this ticket? Change the title accordingly. unassign when clarified.

**Comment by lbergelson** [comment]
Requirements are to change the handling of defaults in collection `@Argument`

Currently, if you specify a non-empty default collection, and then specify that argument on the command line, the value will be the combination of the default collection and any new arguments you specified.  There is a special `null` value you can pass in which lets you replace the defaults.  

This should be changed so that specifying a value replaces the defaults instead of appending to them.  

Current behavior:
```
@Argument
List<int> numbers = Lists.newArrayList(1,2,3,4);
```
on the command line
```
--numbers 5 --numbers 6
``` 
results in `numbers = [1,2,3,4,5,6]`

desired behavior would be `numbers = `[5,6]`

**Comment by lbergelson** [comment]
It's a simple change that I've implemented locally, I need to fix the picard programs that rely on the old behavior though.

**Comment by droazen** [comment]
This is long since done
