### ISSUE TITLE
LocusIteratorByState only keeps reads from one of the samples (and not always the same)

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#1752]
I was developing a `LocusWalker` (#1707)  when I found that if several BAM files are provided, the `LocusIteratorByState` (LIBS) returns only a `AlignmentContext` with associated `ReadPileup` with only one sample.

I realized that in the LIBS there is a commented exception thrown about that multi-sample is not supported. Because it is commented, the LIBS is providing an `AlignmentContext` for the next sample if the first of them does not have coverage. This is misleading for an API user (it took me some time to understand where the error comes from).

I was thinking to do a pull request (or include this in #1707) to solve the issue. There are two ways of doing this:

* As in GATK3, implement an internal `PerSampleReadPileup` that extends the `ReadPileup` and provides an efficient way of separate sample-specific pileups.
* If there is no plan to support multi-sample pileups (I'm worried about this, because I will need it), construct the `AlignmentContext` in the LIBS from all samples. Then, the method `makeFilteredPileup` could be used to extract (in a complicated way) a per-sample pileup by the user side.

Because the current implementation was done by @akiezun, could you please give me some feedback? I will need it for my stuff, and I will be very grateful if I can solve this as soon as possible...

**Comment by magicDGS** [comment]
In addition, I would like to have an option in LIBS where reads with Ns could be added to the pileup (switched off by default, of course), similar to the `includeReadsWithDeletionAtLoci` option.

**Comment by lbergelson** [comment]
I think this was originally not ported because it was more complex and unnecessary for the work we were doing at that moment, not any ideological opposition.  I think we'd be happy to have a multi-sample implementation if includes strong tests.

**Comment by droazen** [comment]
Correct, this functionality was not ported only because we didn't have a use case for it and because it introduced a fair amount of extra complexity. We'd be open to a PR to add back multi-sample support, provided the code is well-tested and not too convoluted.

**Comment by magicDGS** [comment]
Thanks @lbergelson and @droazen.

Could it be possible to add a simple patch to add all the reads to the returned `AlignmentContext`, instead of just add the `ReadPileup` from just one covered sample?

I just made some small changes in my fork: https://github.com/magicDGS/gatk/tree/dgs_multi_sample_libs

If you agree I will do a PR, if not it will take me some time due to the complexity...

**Comment by magicDGS** [comment]
I added a simple patch to fix this undocumented behaviour. Nevertheless, I'm working in an abstraction to include multi-sample support instead of include all the reads without differentiation in the pileup.

**Comment by magicDGS** [comment]
Closed by #1774.
