### ISSUE TITLE
Publish snapshot to artifactory whenever master changes

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1753]
We're going to need this now that we're splitting the `HaplotypeCaller` codebase across public and protected, otherwise it will be a huge pain to develop.

**Comment by droazen** [comment]
For @lbergelson

**Comment by akiezun** [comment]
@lbergelson this is done, correct?

**Comment by droazen** [comment]
Yes, this one is done

**Comment by lbergelson** [comment]
This is done.
