### ISSUE TITLE
HashedListTargetCollection has unnatural contig order

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#1754]
`HashedListTargetCollection` sorts targets by `IntervalUtils.LEXICOGRAPHICAL_ORDER_COMPARATOR` i.e. ASCII order.  Any tool that uses this class to store its targets outputs chromosomes in the order 1, 10, 11 . . . 19, 2, 20, 21, 22, 3 . . .

**Comment by droazen** [comment]
@vruano Care to comment on this?

**Comment by davidbenjamin** [comment]
Moot because @samuelklee replaced uses of `HashedListTargetCollection` with `OverlapDetector`.
