### ISSUE TITLE
Cap probabilities at 1.0 in ActivityProfile/BandPassActivityProfile, and enforce in ActivityProfileState

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1763]
The `BandPassActivityProfile` can sometimes generate probabilities that slightly exceed 1.0 when moving probability mass around. We should fix this by capping at 1.0, but first we must evaluate the effects of capping on the `HaplotypeCaller`.

**Comment by davidbenjamin** [comment]
This code needs to be thoroughly revised.
