### ISSUE TITLE
Need a way to override the KryoRegistrator in a GATKSparkTool.

### ISSUE THREAD

**Issue by tedsharpe** [broadinstitute/gatk#1767]
Various tools will be serializing different things and need to be able to register these classes with Kryo.  Currently the only way to vary what is registered is to specify a conf argument on the command line with the class name of the registrator.
Maybe a new property in SparkCommandLineProgram?  GATKSparkTool will default it to GATKRegistrator, but subclasses can override as they require.  This would be passed to the SparkContextFactory's getSparkContext method to set the value of the "spark.kryo.registrator" property.

**Comment by droazen** [comment]
@tedsharpe I thought you came up with a means of doing this involving static initializers?

**Comment by tedsharpe** [comment]
I did, but then I rethought it and decided that I think it's too fragile to do it that way:  You have to guarantee that all classes that might want to be registered are loaded and initialized before you instantiate the SparkConf.

The problem is that it varies among JVM implementations exactly when that (class loading and initialization) happens.  Some JVMs do the whole mess, chasing all references down from main recursively at the beginning, others are as lazy as possible and initialize only when actually traversing a reference for the first time.

We could use that technique to "inject" a set of registrations into the GATKRegistrator from each main class.  But since it's unreliable to do it in arbitrary classes, it seemed more straightforward to just let the normal object oriented method of overrides handle the problem, since it will need to be done only by direct subclasses, anyway.

But I'm certainly open to other solutions, so long as we provide the functionality.

**Comment by lbergelson** [comment]
@tedsharpe This sounds reasonable to me.

**Comment by droazen** [comment]
@tedsharpe Sure, open a PR with whatever approach you think is best, and we'll review. Using method overrides sounds like a pretty sane option.

**Comment by tedsharpe** [comment]
The method override idea works fine for getting the necessary registrations done for some given Spark executable, but doesn't address the problem of how to unit test, since we can have only one SparkContext for all unit tests, and can't customize the registrations.
Best practice might be to use a class annotation to designate a default serializer for each class that needs Kryo serialization, and then registration should all just happen magically at the minimal cost of recording the class name and ID in the stream when an object of that class is serialized the first time.
That's the road I'm going to try to go down, anyway.
