### ISSUE TITLE
Three very different names for similar tools

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1782]
For creating an "index" file corresponding to a data file, we have 3 tools, each with a completely different name form:
- BuildBamIndex  
- IndexFeatureFile  
- CreateHadoopBamSplittingIndex

we should pick "Build.." or "Create.." (using "index" as a verb is confusing)

@vdauwera thoughts?

**Comment by droazen** [comment]
I think we've always intended to have a unified `IndexFile` tool that can index anything.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/1545
