### ISSUE TITLE
extremely slow CRAM processing of intervals

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1787]
CountReads 

CRAM is 17x slower here! (in user time) 

using interval list from `ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/2.8/b37/Broad.human.exome.b37.interval_list.gz`

```
time ./gatk-launch CountReads -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.cram -L Broad.human.exome.b37.interval_list  -R src/test/resources/large/human_g1k_v37.20.21.fasta
real	1m12.498s
user	1m23.140s
```

```
time ./gatk-launch CountReads -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -L Broad.human.exome.b37.interval_list
real	0m2.178s
user	0m4.853s
```

**Comment by cmnbroad** [comment]
The current  multi-interval iterator in the CRAM reader is pretty inefficient (to put it mildly) - I actually would have predicted that with that many intervals it would be much worse. I recently rewrote much of the query implementation - if you're so inclined it would be interesting to know if the branch in https://github.com/samtools/htsjdk/pull/552 has better perf (and this would be a great test to check if the results are correct).

**Comment by droazen** [comment]
Even without any `-L` intervals, running `CountReads` on the cram is 3x slower than running it on the bam, so the performance problems are not confined to the interval-parsing code.

**Comment by cmnbroad** [comment]
Right; with my htsjdk branch, the example above goes from 17x to 2x, so the multi interval problem doesn't surprise me, and we have a fix in the pipeline. There is still something fundamentally slower about CRAM in the 2-3x range though that I need to look into.

**Comment by akiezun** [comment]
thanks for looking into it. how far is your fix from being ready?

**Comment by cmnbroad** [comment]
It just needs to be reviewed. https://github.com/samtools/htsjdk/pull/552.

**Comment by cmnbroad** [comment]
Just verified this. Adam's CountReads example above down in the 4 second range now with the new htsjdk.
