### ISSUE TITLE
Spin off new project(s) for native pairhmm

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1788]
started as discussion in https://github.com/broadinstitute/gatk/pull/1748 - see the thread there

**Comment by droazen** [comment]
As per the linked discussion, we are going to try to get access to a hosted PPC service that we can run automated tests on. If we're successful in setting up PPC automated tests, then the two native PairHmm implementations could live in the same repo -- if not, then we might prefer two separate repos.

**Comment by akiezun** [comment]
To summarize current state of discussions - we're going to have 3 repos, as originally planned (1 for the interfaces and 2 for Intel and IBM implementations, respectively). There will be a bit code duplication but many other aspects (some technical, some organizational) are massively simplified by such architecture. 

@droazen @lbergelson @gspowley @paolonarvaez @frank-y-liu @t-ogasawara  - please use this ticket to comment.

**Comment by akiezun** [comment]
ok, native repo is done https://github.com/broadinstitute/gatk-native-bindings
we're still hashing out the interfaces and it will be a bit before we have created the artifacts at maven central.

**Comment by akiezun** [comment]
My understanding is that the Intel implementation will be hosted at https://github.com/Intel-HLS/ and uploaded to maven central (from where GATK will pick it up) - @paolonarvaez @gspowley is that correct?

@frank-y-liu @t-ogasawara do you prefer to host your code at your own github organization or elsewhere?

**Comment by t-ogasawara** [comment]
I suppose that you are going to try to set up the automated tests on PPC. If the test environment is set up, the native libraries can live in the same repo.
@droazen @akiezun Did you not get access a PPC service?

It is useful to keep the source files under a single tree (with the common and cpu-specific parts as I explained) from the view point of maintenance and another porting.

**Comment by akiezun** [comment]
source trees for the C code will live in 2 separate repositories - one for AVX/Intel and one for PPC/IBM codes. We should indeed be able to set up automated tests on PPC, with @frank-y-liu 's help probably

**Comment by t-ogasawara** [comment]
It is not clear for me what 2 separate repos can improve. Could you elaborate on that?

**Comment by akiezun** [comment]
Separate repos for each native implementation will allow the native-code providers to be much more nimble and will free the Broad from maintenance of native code - this is much better placed with experts on AVX and Power etc. We are experts on genomics but others are experts on native-code optimizations. With separate repos, IBM and Intel (and others else in the future) can keep on innovating and improving native code without having to test on multiple platforms and GATK takes advantage of those platform-specific libraries and integrates them into the genome toolkit. I think the small amount of initial code duplication is well worth it. Happy to discuss more - feel free to reach out directly.

**Comment by t-ogasawara** [comment]
@akiezun Thank you for your explanation. I understand the benefits (and priorities). I agree.

**Comment by droazen** [comment]
@akiezun Who is going to physically move the code? Can we re-assign this ticket, or should it stay assigned to you?

**Comment by akiezun** [comment]
@gspowley can you help with this?

**Comment by droazen** [comment]
Marking as `PRIORITY_HIGH` so that we do this sooner rather than later, and don't have to temporarily make the GATK build system into more of a Frankenstein monster than it already is.

**Comment by gspowley** [comment]
@akiezun @droazen Yes, I can own the ticket for moving the code to the Intel native library. This effort has been accelerated so we can provide the Intel deflator in the native library. PairHMM will follow soon after.

**Comment by akiezun** [comment]
this ticket is done. https://github.com/broadinstitute/gatk-native-bindings is the set of interfaces and IntelGKL is the library that contains the Intel native code. Our build scripts are updated. GKL will move to maven central but that's not a gatk work item.
