### ISSUE TITLE
Beat GATK3 performance (CPU and memory) of HaplotypeCaller (VCF mode)

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1799]
The GATK3 v3.5-0-g36282e4 commandlines and numbers:

running on gsa5 (has AVX)

VCF mode on 32GB of ram

```
time java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T HaplotypeCaller -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -R src/test/resources/large/human_g1k_v37.20.21.fasta --out a.gatk3.vcf
...
real    1m52.247s
user    2m32.789s
```

Note:The VCF mode is not what production is running so it's lower priority than GVCF

**Comment by akiezun** [comment]
Update 20160502 
GATK4 Version:09f6b60-SNAPSHOT
commit 09f6b602a175a729e07d710d112e878332876390ESC

running on gsa5


VCF mode
```
time ./gatk-launch HaplotypeCaller -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -R src/test/resources/large/human_g1k_v37.20.21.fasta -O a.vcf
...
real	1m48.297s
user	3m7.960s
```

**Comment by droazen** [comment]
Let's revisit this later this week after HC downsampling is in.

**Comment by akiezun** [comment]
update with OpenMP code from @gspowley (#1813)

running on gsa5 

You can get a wallclock speedup but it costs in total time (fine if you have idle CPUs anyway)
```
real	0m58.288s (1.93x speedup)
user	5m52.283s
```

**Comment by akiezun** [comment]
Similar to VCF (#1800) the new OpenMP code scales nicely to 12 cores and does not suffer when run on 1 CPU. Beyond 12 cores we hit Amdahl's law limit and/or interference from other jobs on the node - that does not bother me much. 

From this, I conclude that OpenMP is good for the VCF mode too.

All runs were on gsa5 (48 CPUs)

limited to 1 OMP thread, 32GB
```
real	1m38.331s
user	2m56.949s
Total compute time in PairHMM computeLogLikelihoods() : 43.676249759
```

limited to 2 OMP threads, 32GB
```
real	1m7.480s
user	2m42.873s
Total compute time in PairHMM computeLogLikelihoods() : 19.320970122000002
```

limited to 4 OMP threads, 32GB
```
real	0m57.341s
user	2m44.878s
Total compute time in PairHMM computeLogLikelihoods() : 9.383934680000001
```

limited to 6 OMP threads, 32GB
```
real	0m59.096s
user	2m54.211s
Total compute time in PairHMM computeLogLikelihoods() : 6.815784246000001
```

limited to 12 OMP threads, 32GB
```
real	0m56.027s
user	2m57.085s
Total compute time in PairHMM computeLogLikelihoods() : 3.8520847110000003
```

limited to 24 OMP threads, 32GB
```
real	0m57.237s
user	3m32.483s
Total compute time in PairHMM computeLogLikelihoods() : 3.0299127660000003
```

limited to 48 OMP threads, 32GB
```
real	1m1.604s
user	5m49.551s
Total compute time in PairHMM computeLogLikelihoods() : 3.834293344
```

**Comment by droazen** [comment]
This was done -- next step is https://github.com/broadinstitute/gatk/issues/5264
