### ISSUE TITLE
port HaplotypeCaller 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#18]
@rpoplin should this wait for window traversal issue #10 or port as is (i guess the former)?

**Comment by droazen** [comment]
alpha-1

**Comment by droazen** [comment]
This ticket does not include the design and implementation of the active region traversal replacement, which is https://github.com/broadinstitute/gatk/issues/103

**Comment by droazen** [comment]
Done for alpha-1 purposes in https://github.com/broadinstitute/gatk/pull/1567 -- closing!
