### ISSUE TITLE
Beat GATK3 performance (CPU and memory) of HaplotypeCaller (GVCF mode)

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1800]
The GATK3 v3.5-0-g36282e4 commandlines and numbers:

running on gsa5 (has AVX)

GVCF mode on 32GB of ram

```
time java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T HaplotypeCaller -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -R src/test/resources/large/human_g1k_v37.20.21.fasta -ERC GVCF --out a.gatk3.g.vcf
...
real    3m48.076s
user    8m45.049s
```

GVCF mode on 10GB of ram

```
 time java -Xmx10g -Xms10g -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T HaplotypeCaller -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -R src/test/resources/large/human_g1k_v37.20.21.fasta -ERC GVCF --out a.gatk3.g.vcf
...
real    3m39.496s
user    10m16.387s
```

**Comment by akiezun** [comment]
Update 20160502 
GATK4 Version:09f6b60-SNAPSHOT
commit 09f6b602a175a729e07d710d112e878332876390ESC

running on gsa5
GVCF mode 32GB ram

```
time ./gatk-launch HaplotypeCaller -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -R src/test/resources/large/human_g1k_v37.20.21.fasta -O a.g.vcf -ERC GVCF
...
real	2m12.702s
user	4m0.566s
```

GVCF mode 10GB of ram
```
time JAVA_OPTS="-Xmx10g -Xms10g" ./gatk-launch HaplotypeCaller -I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -R src/test/resources/large/human_g1k_v37.20.21.fasta -O a.g.vcf -ERC GVCF
...
real	2m7.780s
user	3m31.849s
```

OK, i'm declaring victory on GVCF

**Comment by droazen** [comment]
Should we try to make it even better than 2x? Also, we need to test on a larger scale once downsampling is hooked up to make sure these results hold up.

**Comment by akiezun** [comment]
agreed. but i'll close this as the goal has been achieved. we'll retest once downsampling is in (and I'll keep updating the ticket when I have improvements)

**Comment by akiezun** [comment]
update with @gspowley code from https://github.com/broadinstitute/gatk/pull/1813)
on gsa5 (has 48 CPUs and 126GB of RAM total) - not sure how many cores this run took though

Wallclock time is better but (understandably) total time is higher. If we have spare CPUs in production, this is fine.

using 32GB of RAM 
```
real	1m11.403s   (3.25x speedup)
user	6m28.748s
```

using 10GB of RAM
```
real	1m10.963s
user	6m3.221s
```

**Comment by akiezun** [comment]
I did a quick scalability ministudy - this seems to scale well up to 12 cores and then diminishes due to Amdahl's law I think that's fine. There is no diminished runtime due to OMP overhead when on 1 core. Note that our cluster on which I wan these was not empty (a few of the 48 cores were in use) and do this is just a ballpark estimate of scalability, in particular 24 was worse than 12 probably due to interference. Based on this I think OMP is a good idea and it's going to work on 1 CPU too.

limited to 1 OMP thread, using 10GB of RAM
```
real	2m15.621s
user	3m17.269s
Total compute time in PairHMM computeLogLikelihoods() : 50.964700625000006
```


------------------------------------------
limited to 1 OMP thread, using 32GB of RAM 
```
real	1m46.597s
user	3m17.363s
Total compute time in PairHMM computeLogLikelihoods() : 45.797104454
```

limited to 2 OMP threads, using 32GB of RAM
```
real	1m26.310s
user	3m24.636s
Total compute time in PairHMM computeLogLikelihoods() : 23.790980359000002
```

limited to 4 OMP threads, using 32GB of RAM
```
real	1m15.298s
user	3m29.834s
Total compute time in PairHMM computeLogLikelihoods() : 11.332445694
```

limited to 6 OMP threads, using 32GB of RAM
```
real	1m14.015s
user	3m20.876s
Total compute time in PairHMM computeLogLikelihoods() : 7.862075811
```

limited to 12 OMP threads, using 32GB of RAM
```
real	1m6.370s   
user	3m42.340s
Total compute time in PairHMM computeLogLikelihoods() : 4.585800097
```

limited to 24 OMP threads, using 32GB of RAM (clearly, OMP hits the limit here)
```
real	1m8.779s
user	4m15.489s
Total compute time in PairHMM computeLogLikelihoods() : 3.047581173
```

limited to 48 OMP threads, using 32GB of RAM (worse than 12 threads)
```
real	1m11.535s
user	6m26.100s
Total compute time in PairHMM computeLogLikelihoods() : 4.112299148
```

**Comment by droazen** [comment]
Re-opening for alpha-3, since we will attempt to make additional performance improvements this quarter.

**Comment by droazen** [comment]
This was done -- next step is https://github.com/broadinstitute/gatk/issues/5264
