### ISSUE TITLE
Create a gatk-native-bindings github repository with JNI interfaces for native code

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1801]
Initial version should consist of:

* A superinterface called `NativeLibrary` that has `getLibraryPath()` and `isSupported()` methods.

* A `PairHmmBinding` interface (name open to negotiation!) that extends `NativeLibrary` and has signatures for `jniComputeLikelihoods()` and other PairHmm JNI methods.

Once created, we need to publish a jar on maven for this repository.

**Comment by droazen** [comment]
@akiezun Could you take this one?

**Comment by akiezun** [comment]
I'll close this as a dup of #1788 - it's all aiming to do the same thing so let's use that ticket.

**Comment by droazen** [comment]
Re-opening -- it's good to have this spun out as a separate subtask with a specification for the interface, since this can be done quickly, while the rest of https://github.com/broadinstitute/gatk/issues/1788 will potentially take weeks.

**Comment by akiezun** [comment]
whetever, man. To me it's the same work item. Will keep both if you like it that way

**Comment by droazen** [comment]
My philosophy is it will encourage us to do this piece ASAP, instead of waiting on the creation of the IBM/Intel repos. This ticket also has the interface specification which might be forgotten if this is closed.

**Comment by akiezun** [comment]
repo exists now  https://github.com/broadinstitute/gatk-native-bindings 
will be made public shortly - i requested broad IT to switch to public

Pull req is here: https://github.com/broadinstitute/gatk-native-bindings/pull/1

**Comment by akiezun** [comment]
done
