### ISSUE TITLE
Test filtering in gradle stopped working

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1802]
this used to work (just 2 weeks ago when https://github.com/broadinstitute/gatk/pull/1719 was merged)
```
./gradlew test --tests *VariantFiltrationIntegrationTest*
```

now i get:
```
> No tests found for given includes: [*VariantFiltrationIntegrationTest*]
```

very annoying

**Comment by lbergelson** [comment]
@akiezun You probably need `'` around them.  Differences in shells on different machines.

**Comment by lbergelson** [comment]
Hmn, or maybe not.  I'm having trouble with it too

**Comment by akiezun** [comment]
it works now. Louis thinks it was cause by the same bug as https://github.com/broadinstitute/gatk/pull/1804
