### ISSUE TITLE
create automated test environment on Power systems at http://osuosl.org/ 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1808]
To test GATK on IBM's power systems we need to run an automated test suite off-travis (they do not have power support). We have an account at http://osuosl.org/ - @droazen has an account.

Ideally, this would run on all pushes to all branches (+ add a badge to our repo) but we can start with a nightly build of master

**Comment by droazen** [comment]
Correction: we do not have an account -- we WILL have one within a week if our application is accepted :)

**Comment by droazen** [comment]
Not doing this -- delegating to IBM.
