### ISSUE TITLE
experiment with RDD caching in MarkDuplicatesSpark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1811]
as it is now, we read the data twice in MarkDuplicatesSpark because we filter it using predicate `p` and `!p`. We could cache the RDD but it's not clear if it's faster than just re-reading.

**Comment by akiezun** [comment]
note: Lucy is looking at this

**Comment by SHuang-Broad** [comment]
The local assembly step currently in SV pipeline also uses RDD cacheing (`validateAndSaveResults` of `RunSGAViaProcessBuilderOnSpark.java`), so this would help.
Thanks, @akiezun and Lucy

**Comment by SHuang-Broad** [comment]
One note that might be useful (or known already to the team): simply calling `cache()` doesn't cause any action. It seems that one might need to force the computation to be done on the RDD (e.g. `count()`), for caching to work, if the predicate depends on the results of computation. (ref last comment in #1877)

**Comment by akiezun** [comment]
assigning to @gspowley as our Intel contact and proxy for Lucy and Eric's work

**Comment by gspowley** [comment]
Closing since Lucy and Eric are no longer looking at this issue.
