### ISSUE TITLE
Native SmithWaterman

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1812]
https://github.com/mengyao/complete-striped-smith-waterman-library
I've successfully built and run it on linux and mac. Need to investigate performance and usability for us

see also #1629

**Comment by akiezun** [comment]
ugh, made some progress but got stuck because that code requires that penalties are less than 256 and match/mismatch are below 128. Or default values are match 200, mismatch -150, open -260, extend -11

work in progress is in branch ak_native_smithwaterman_sse 

@gspowley FYI

**Comment by akiezun** [comment]
removing milestone - may not happen

**Comment by akiezun** [comment]
this is on hold until we figure out if/how to make progress

**Comment by akiezun** [comment]
I wonder if there's a way to rescale the parameters to get the same results. We don't care about the actual score at all only about the cigar really.

**Comment by droazen** [comment]
Is this library in maven?

**Comment by akiezun** [comment]
no

**Comment by droazen** [comment]
And has Intel looked at it and declared it sane?

**Comment by akiezun** [comment]
yes

**Comment by gspowley** [comment]
I tried using this library too, and tried scaling the parameters. It didn't give exactly the same results. 

Another difference I noticed, the `SWPairwiseAlignment.OverhangStrategy.INDEL` and `SWPairwiseAlignment.OverhangStrategy.LEADING_INDEL` overhang strategies in GATK Smith-Waterman produce different results than the SSW library.

**Comment by akiezun** [comment]
@gspowley can I assign this to you to investigate and follow up? Even if not all OverhangStrategies are supported this is still valuable if it speeds up haplotype caller. I'm removing the point estimate for now too - it may require a reimplementation, though it would be preferable of course if we could use that existing code (it's MIT licensed so it's all good).

**Comment by gspowley** [comment]
@akiezun Yes, you can assign to me and we'll investigate and follow up. I agree the OverhangStrategy support is not a big deal, just wanted to point out the difference.

**Comment by droazen** [comment]
It's likely there will eventually be a native SW implementation in intel-gkl. From @gspowley: "We do plan to add native Smith-Waterman to GKL, after compression and pairHMM are solid."

**Comment by droazen** [comment]
@gspowley Do you guys have a timeline for when this might be implemented? The SV developers have a need for an efficient SmithWaterman implementation, so this would benefit more than just the `HaplotypeCaller`

**Comment by gspowley** [comment]
We have a few things in GKL in flight right now. Let's meet and discuss priorities so we can set a timeline that meets your needs.

**Comment by droazen** [comment]
Ok, we can discuss at the next Monday meeting.

**Comment by magicDGS** [comment]
Probably useful for this: https://github.com/ekg/ssw

**Comment by droazen** [comment]
This is currently in development at Intel.

**Comment by magicDGS** [comment]
Just a question about this @droazen: it is going to be supported in any kind of computers? If not, it will be nice if there is a general native implementation for fallback in case that the native code is not available...

**Comment by lbergelson** [comment]
There will always be a java implementation to fallback to if your computer isn't supported.  The accelerated native code will just be faster on supported hardware.

**Comment by droazen** [comment]
Right, our policy with native code is always to have a Java fallback implementaiton.

**Comment by lbergelson** [comment]
*always*\*
