### ISSUE TITLE
update all usage examples

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#182]
there are comments like:
" \* java -Xmx4g -jar GenomeAnalysisTK.jar \
-   -T BaseRecalibrator \
-   -I my_reads.bam \
-   -R resources/Homo_sapiens_assembly18.fasta \
-   -knownSites bundle/hg18/dbsnp_132.hg18.vcf \
-   -knownSites another/optional/setOfSitesToMask.vcf \
-   -o recal_data.table"

which are wrong. There needs to be a pass over all usage examples to update them once we settle on the usage.

**Comment by droazen** [comment]
Tagging as needed for the 4.0 release

**Comment by droazen** [comment]
From @lbergelson :

```
As well as fixing errors, it would be good to change the javadoc so it references parameters by the constant values instead of hardcoding them. (use {@value StandardArgumentDefinitions#SOME_NAME} )
```

**Comment by droazen** [comment]
This was done
