### ISSUE TITLE
Turn off sputnik

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1830]
I know attempts have been made, but it still appears to be on, and spamming us with millions of warnings about default encodings.

**Comment by droazen** [comment]
For @akiezun

**Comment by akiezun** [comment]
Millions? You must be writing a lot more code than others.

On Tuesday, May 17, 2016, droazen <notifications@github.com> wrote:

> Assigned #1830 <https://github.com/broadinstitute/gatk/issues/1830> to
> @akiezun <https://github.com/akiezun>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gatk/issues/1830#event-663692417>
>


-- 
Sent from Gmail Mobile

**Comment by akiezun** [comment]
fixed by #1831

**Comment by akiezun** [comment]
btw we may be able to try this again sometime: https://github.com/TouK/sputnik-ci/issues/11
