### ISSUE TITLE
rename packages from hellbender to gatk

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1832]
has to be done at some point, probably better sooner than later.

@droazen any thoughts on preferred timing?

**Comment by droazen** [comment]
@akiezun Let's do it towards the end of alpha-2, after all of the heavy-duty branches are in.

**Comment by droazen** [comment]
Closing -- we've decided it would be too disruptive to do this package rename.

**Comment by magicDGS** [comment]
That's a pity, but understandable. Long live for "hellbender" package with lots of `GATK*` named classes!
