### ISSUE TITLE
unmappable character for encoding ASCII in @magicDGS name

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1841]
```
error: unmappable character for encoding ASCII
 * @author Daniel G??mez-S??nchez (magicDGS)
```

affected files: IntervalOverlappingIterator.java:17, LocusWalker.java:27, ExampleLocusWalker.java:22

@magicDGS can you fix this?

**Comment by magicDGS** [comment]
Sure, I've just push the PR.

**Comment by magicDGS** [comment]
Should this be closed now?

**Comment by akiezun** [comment]
Yes

On Friday, May 20, 2016, Daniel Gómez-Sánchez <notifications@github.com>
wrote:

> Should this be closed now?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/gatk/issues/1841#issuecomment-220519412>
>


-- 
Sent from Gmail Mobile

**Comment by akiezun** [comment]
hmm, @magicDGS there are some more files (in tests, which is why we missed them before):
ExampleLocusWalkerIntegrationTest.java
IntervalOverlappingIteratorUnitTest.java

can you fix those and verify by running 
```
find src -name "*.java" -exec grep -H "magicDGS" {} \;
```

(right now it finds 5 hits and 2 are not fixed)
```
src/main/java/org/broadinstitute/hellbender/engine/LocusWalker.java: * @author Daniel Gomez-Sanchez (magicDGS)
src/main/java/org/broadinstitute/hellbender/tools/examples/ExampleLocusWalker.java: * @author Daniel Gomez-Sanchez (magicDGS)
src/main/java/org/broadinstitute/hellbender/utils/iterators/IntervalOverlappingIterator.java: * @author Daniel Gomez-Sanchez (magicDGS)
src/test/java/org/broadinstitute/hellbender/tools/examples/ExampleLocusWalkerIntegrationTest.java: * @author Daniel Gómez-Sánchez (magicDGS)
src/test/java/org/broadinstitute/hellbender/utils/iterators/IntervalOverlappingIteratorUnitTest.java: * @author Daniel Gómez-Sánchez (magicDGS)
```

**Comment by magicDGS** [comment]
Sorry for the inconvenience. I've just done a PR for the tests (#1850).
