### ISSUE TITLE
Improve performance of JBWA native code

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1857]
(added here for easier tracking)

In bwajni.c
- [ ] lift `(*env)->GetArrayLength(env,baseArray)` out of loops
- [ ] pass pointers directly not wrapped in classes, eg. BwaIndex could be passed as a pointer
- [ ] cache all fieldIDs, methodIDs and classes
- [ ] pass in data directly without the ShortRead
- [ ] batch multiple calls to align (1 read) 
- [ ] pass in a struct for the native code to fill rather then allocate a new AlnRgn everytime

**Comment by SHuang-Broad** [comment]
@akiezun , the first item in the list, is it assuming that the input sequences are all the same length?
For contigs assembled in the SV pipeline, this is not the case (just to be sure).

**Comment by akiezun** [comment]
good point @SHuang-Broad

**Comment by SHuang-Broad** [comment]
It would be great if the jbwa also exposes a `bwa index` option, as we might need to map reads back to the assembled contigs (there will be many of them) for the genotyping step in SV pipeline, which in turn requires the contigs themselves to be indexed.

**Comment by droazen** [comment]
Closing, since we have new BWA bindings now courtesy of @tedsharpe
