### ISSUE TITLE
Fix sum(AD) > DP

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#1858]
Issue spotted in GATK3 and fixed by pull-request https://github.com/broadinstitute/gsa-unstable/pull/1377. Original issue: https://github.com/broadinstitute/gsa-unstable/issues/1340

Needs to be ported to GATK4 as part of a larger fix involving the refactoring of AFCalculators (Issue TBA).

**Comment by vruano** [comment]
@davidbenjamin I think that this issue will be addressed by the AFCalculator refactoring one way or another (e.g. by lifting up the max-alt-allele restrictions or simply avoid adding the NON-REF allele before calling the AFCalculator).

**Comment by vruano** [comment]
I have assigned it to you as you going to do start work on the AFCalculator but feel free to unassign yourself.

**Comment by davidbenjamin** [comment]
@vruano That makes sense.

**Comment by davidbenjamin** [comment]
@vruano I think GATK 4 fixes this by extracting allele subsetting from genotyping and the qual score.  Is there a  particular bam and variant I can test on before closing this issue?

**Comment by vruano** [comment]
You mean that subsetting does not look back into the ReadLikelihoods object but only the VariantContext correct?, In that case this should not be a problem any more.

**Comment by vruano** [comment]
mmm... second thought... I think the problem is when we combine samples allele lists from different samples and the non-observed alleles get the counts from the NON-REF allele correct? how is the separation between subsetting and genotyping would fix that?

**Comment by vruano** [comment]
... looking at the associated commit I don't see changes that directly affect GenotypeGVCFs and CombineGVCFs so I guess that that was actually a no issue or was fixed somewhere else. If you are confident GATK4 don't have the issue reported then just close it.

**Comment by davidbenjamin** [comment]
I *think* it's fixed but I'm not confident enough to close the issue without actually running on a test case that used to have the problem in GATK 3.

**Comment by skwalker** [comment]
@davidbenjamin I didn't come across this issue but I also did not test for it specifically.

**Comment by davidbenjamin** [comment]
That's good enough for me.  If it's still an issue we'll find out soon enough.
