### ISSUE TITLE
SplitNCigarReads should be able to take -L as an argument

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/gatk#1864]

**Comment by droazen** [comment]
It doesn't take `-L` currently because it's implemented as a raw Picard-style `CommandLineProgram` instead of as a `GATKTool`

**Comment by meganshand** [comment]
So it probably should be implemented as a GATKTool, right?

**Comment by droazen** [comment]
I would say so, yes :)

**Comment by meganshand** [comment]
Actually, should it use the ReadWalker?

**Comment by droazen** [comment]
It should probably be a `ReadWalker`, yes -- but if it can't be one for some reason, it is possible to extend `GATKTool` directly.

**Comment by vdauwera** [comment]
Btw the GATK3 version of SNCR doesn't generate a valid bam file according to ValidateSAMFile. Would be lovely to fix that here (and backport the fix if possible).

v4 issue is here: https://github.com/broadinstitute/gatk/issues/1394

**Comment by meganshand** [comment]
That's exactly what I came here to do! I checked if Picard's FixMateInformation would fix it but it doesn't look that simple.

**Comment by vdauwera** [comment]
Ah, wonderful :) 

Yeah I think we had tested FixMate at the time but no joy.
