### ISSUE TITLE
Need to use template size evidence in FindBreakpointEvidenceSpark

### ISSUE THREAD

**Issue by tedsharpe** [broadinstitute/gatk#1866]
It's currently turned off (see TODO in ReadClassifier) because evidence of this type is so copious that it swamps everything else.  We'll need to figure out a means of de-weighting it or something.

**Comment by tedsharpe** [comment]
Per Chris W.:  We might want to consider a) ignoring small zish scores, and b) weighting pieces of evidence more highly if they agree with other pieces of evidence w/r/t their mate mapping position for discordant pairs or their SA tag locations for split reads.

**Comment by SHuang-Broad** [comment]
@tedsharpe @cwhelan pinning to see if this is done already, especially by #3138

**Comment by SHuang-Broad** [comment]
ping again....

**Comment by tedsharpe** [comment]
this is a) done, and b) superfluous now that we have Ted B.'s classifier
