### ISSUE TITLE
Reconsider subsetting haplotypes before genotyping

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#1868]
While working on a GATK-3 bug, broadinstitute/gsa-unstable#855, @SHuang-Broad noticed that the natural place to avoid an explosion of genotypes (i.e. the size of the GLs vector) for a large number of alleles is right after computing haplotype likelihoods.  In GATK-4 this is in `HaplotypeCallerEngine::callRegion` after the line `final ReadLikelihoods<Haplotype> readLikelihoods =
likelihoodCalculationEngine.computeReadLikelihoods(assemblyResult, samplesList, reads)`.  

However, at this point there is the following comment:

``` java
// Note: we used to subset down at this point to only the "best" haplotypes in all samples for genotyping, but there
        //  was a bad interaction between that selection and the marginalization that happens over each event when computing
        //  GLs.  In particular, for samples that are heterozygous non-reference (B/C) the marginalization for B treats the
        //  haplotype containing C as reference (and vice versa).  Now this is fine if all possible haplotypes are included
        //  in the genotyping, but we lose information if we select down to a few haplotypes.  [EB]
```

If I understand EB's (@eitanbanks?) point right, subsetting here is dangerous only because of our downstream hack to turn multiallelic genotyping into a biallelic problem.  The new AF/QUAL model will perform honest multiallelic genotyping, hence it makes sense to revisit whether to subset haplotypes at this point.

**Comment by davidbenjamin** [comment]
It's also worth clarifying just how must subsetting we're talking about -- the bug @SHuang-Broad is dealing with involves culling a really big number of alleles to something more moderate and I think the comment in the code might be talking about more draconian subsetting.

**Comment by SHuang-Broad** [comment]
To be fair, @vruano suggested the solution and I am simply writing code to try to make the allele-trimming work.

**Comment by davidbenjamin** [comment]
@jamesemery's work reduces the number of haplotypes dramatically.
