### ISSUE TITLE
Invent a spiffier Pair-HMM that can handle LCRs

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#1869]
While @ldgauthier was presenting LobSTR, an STR indel caller, @fleharty and I were discussing how their probabilistic model was in some sense trying to convey a gap opening penalty and a gap continuation penalty for PCR slippage and related errors.  This sort of suggests that one could go whole hog and build this into an enhanced pair-HMM that is aware of multiple error modes.

**Comment by ldgauthier** [comment]
FWIW Yossi got more detailed slides from Melissa here: http://www.broadinstitute.org/~gymrek/GSAStutterNoise_mgymrek.pdf

**Comment by davidbenjamin** [comment]
Modeling PCR stutter is better done with Valentin's approach, or in BQSR, or with deep learning.  Making pairHMM fancier is not the answer.
