### ISSUE TITLE
build gatk4 failed 

### ISSUE THREAD

**Issue by yuruoxin** [broadinstitute/gatk#1870]
git clone https://github.com/lindenb/jbwa

and make, error message is:

ksw.c:29:23: fatal error: emmintrin.h: No such file or directory
#include <emmintrin.h>
^
compilation terminated.
make[1]: *** [ksw.o] Error 1
make[1]: Leaving directory `/home/dlspark/gatk/lib/jbwa/bwa-8e2da1e407972170d1a660286f07a3a3a71ee6fb'
make: *** [bwa-8e2da1e407972170d1a660286f07a3a3a71ee6fb/libbwa.a] Error 2

**Comment by droazen** [comment]
@yuruoxin The latest master branch version of GATK4 does not clone and build `jbwa` from source -- instead, it pulls down a pre-compiled version from maven. Can you update your GATK4 clone to the latest master and try again?

**Comment by akiezun** [comment]
closing this. @yuruoxin please reopen if you still see it on master
