### ISSUE TITLE
IllegalArgumentException problem when running some programs 

### ISSUE THREAD

**Issue by chutianwen** [broadinstitute/gatk#1876]
I have tested several program functions by GATK4, some of them work pretty well. GATK4 does a great job to organize all steps by different tools like BWA, samtools, picard. Besides, it seems that there is also some optimization inside. Like "cleanSam" step, GATK4 cuts the time half compared to the one using Picard. (From 8 mins to 4 mins on same data)  

However, the problem about GATK4 is that some programs fail due to java related problem (Maybe some reasons else).  So far, the functions I failed are "FastqToSam" and "ReadsPipelineSpark ". 

Note that, I am using spark locally not scale-out cluster. So the command I am running ReadsPipelineSpark is as below(with oracle java8). Then it gives me java error. 

./bin/gatk/gatk­launch \
ReadsPipelineSpark \
-O hdfs:<PATH>CEUTrio.HiSeq.WEx.b37.NA12892.readnamesort.bam.md.bqsr \
-I hdfs:<PATH>/CEUTrio.HiSeq.WEx.b37.NA12892.readnamesort.bam \
-R hdfs:<PATH>human_g1k_v37.2bit \
--knownSites hdfs:<PATH>dbsnp_138.b37.excluding_sites_after_129.vcf \
--shardedOutput true \
--emit_original_quals \
--duplicates_scoring_strategy SUM_OF_BASE_QUALITIES

All the failure seems to do with the java.lang.IllegalArgumentException with different error causes:
1. readpipeline: java.lang.IllegalArgumentException: Null object is not allowed here
2. fastqtosam: java.lang.IllegalArgumentException: Self-suppression not permitted

**Comment by lbergelson** [comment]
@chutianwen Thanks for reporting this.  I'm pretty sure the issue is with your hdfs paths.  You say that you're not running on a cluster, which makes me suspect you also don't have hdfs configured.  Let me know if that isn't the case and your files are on hdfs.

Try using file paths instead of the hdfs ones you're using.

If you checked out the git-lfs files then the following command should work if you're in the gatk directory

```
/bin/gatk/gatk­launch  \
ReadsPipelineSpark \
-O CEUTrio.HiSeq.WEx.b37.NA12892.readnamesort.bam.md.bqsr \
-I src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam \
-R src/test/resources/large/human_g1k_v37.20.21.2bit \
--knownSites src/test/resources/large/dbsnp_138.b37.20.21.vcf \
--shardedOutput true \
--emit_original_quals \
--duplicates_scoring_strategy SUM_OF_BASE_QUALITIES
```

**Comment by lbergelson** [comment]
@chutianwen I haven't heard any response for a while so I'm going to close this.  Please reopen if you still are having trouble.
