### ISSUE TITLE
Arguments for ReadFilters in tools which require reads

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#1885]
Tools which require reads usually have a `makeReadFilter` method (like `ReadWalker` or `LocusWalker`), and the optional `@Argument(fullName = "disable_all_read_filters")`. It could be interesting to have an argument collection for this to maintain consistency.

In addition, I think that it will be useful to provide a way to allow the user of the tool to set concrete `ReadFilter`s on demand.

**Comment by cmnbroad** [comment]
This work is underway (https://github.com/broadinstitute/gatk/issues/589) and a PR will be available soon.

**Comment by cmnbroad** [comment]
Closing as dup of #589.

**Comment by magicDGS** [comment]
Sorry @cmnbroad, I didn't realize.
