### ISSUE TITLE
Add integration test using -maxNumPLValues for GenotypeGVCFs 

### ISSUE THREAD

**Issue by ronlevine** [broadinstitute/gatk#1895]
Port https://github.com/broadinstitute/gsa-unstable/pull/1403.

**Comment by ronlevine** [comment]
@droazen Should this be a gatk-protected ticket instead?

**Comment by droazen** [comment]
@ronlevine Yes, it should.

**Comment by ronlevine** [comment]
Issue moved to [broadinstitute/gatk-protected #724](https://github.com/broadinstitute/gatk-protected/issues/724) via [**ZenHub**](https://www.zenhub.com/)
