### ISSUE TITLE
make a flexible coverage tool (DepthOfCoverage, DiagnoseTargets, ...)

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#19]
DepthOfCoverage 
DiagnoseTargets  

From @vdauwera 
It would probably make sense to write one really good tool for coverage analysis to replace these two. DoC is great at providing per-locus coverage counts, and the main output table is straightforward and easy for downstream scripts to consume. The summary results table is also ok. But the functionality for aggregating results over intervals and refseq gene lists is super confusing; intervals and genelists interact in an counterintuitive way, and the refseq format requirements are a little vague. In contrast, DT is great at providing per-interval results that give you a go/no-go for callability (+ a culprit metric e.g. MAPQ0, DP etc. in case of a no-go call), but the output is terrible (a pseudo-VCF, which users dont like) and it does not give any per-site counts. There are related tools that users find somewhat useful like CallableLoci, CompareCallableLoci, QualifyMissingIntervals, FindCoveredIntervals, CoveredByNSamplesSites etc. which have overlapping functionality with the coverage tools, and whose functionalities could perhaps be folded into a pan-coverage tool.

**Comment by akiezun** [comment]
@vruano can you comment on what is implemented in your recent tool and what is missing to satisfy the requirements of this issue?

**Comment by akiezun** [comment]
assign to @vruano to expand the description of missing functionality (not necessarily fix this).

**Comment by sooheelee** [comment]
A researcher is asking about the status of the ports for FindCoveredIntervals, DiagnoseTargets, and DepthOfCoverage at https://gatkforums.broadinstitute.org/gatk/discussion/12950/. In addition, they have some suggestions for features for DiagnoseTargets. I've recapitulated below:

---

This is a GATK3 issue, but I hope that GATK4 will  incorporate the following suggestion. And while we are on the subject, what is the roadmap for FindCoveredIntervals, DiagnoseTargets, and DepthOfCoverage (or something even more awesome) in GATK4?

A common pattern is to use `FindCoveredIntervals --uncovered` to create an interval list that serves as input to `DiagnoseTargets`. On a good day, FindCoveredIntervals --uncovered might create an interval list file that is empty, i.e., all the tested intervals were covered well enough by the given criteria. In this case DiagnoseTargets will first emit a warning like
```
#WARN  18:11:43,557 IntervalUtils - The interval file /gpfs/share/cmoco_sys_dev/nfs/storage/cromwell/cromwell-executions/somatic_workflow/6a32b126-f616-42c5-9ec6-2994a4e4bd81/call-BamQCGatk/shard-4/bam_qc/2a4033e0-ea75-4d33-91ff-7ba7656536fe/call-FindUncoveredIntervals/shard-1/execution/VAL18-248-NT-D@VAL18-248-NT-D.08302018JH.Lymphoma.uncovered_intervals.interval_list contains no intervals that could be parsed.
```
and then it raises an error like
```
###### ERROR MESSAGE: This tool only works if you provide one or more intervals (use the -L argument). If you want to run whole genome, use -T DepthOfCoverage instead.
```
and exit with a non-zero return code.

It is certainly possible to trap the empty interval list and skip DiagnoseTargets, but it I think it would be better if DiagnoseTargets emitted the warning but then quit with empty output and a zero rc. This would avoid the problem of a workflow that was developed with test data that always had some uncovered intervals suddenly failing when there is excellent coverage.

**Comment by samuelklee** [comment]
Could some combination of `CollectReadCounts` and the `FilterIntervals` tool I am working on in my latest branch suffice to replicate the functionality of `FindCoveredIntervals`?  Here is the current doc for `FilterIntervals`

```
/**
 * Given annotated intervals output by {@link AnnotateIntervals} and/or counts collected on those intervals output
 * by {@link CollectReadCounts}, outputs a filtered Picard interval list.  Parameters for filtering based on the
 * annotations and counts can be adjusted.  Annotation-based filters will be applied first, followed by count-based
 * filters.
 *
 * <h3>Inputs</h3>
 *
 * <ul>
 *     <li>
           Intervals to be filtered.
 *         The argument {@code interval-merging-rule} must be set to {@link IntervalMergingRule#OVERLAPPING_ONLY}
 *         and all other common arguments for interval padding or merging must be set to their defaults.
 *         A blacklist of regions in which intervals should always be filtered (regardless of other annotation-based
 *         or count-based filters) may also be provided via -XL; this can be used to filter pseudoautosomal regions
 *         (PARs), for example.
 *     </li>
 *     <li>
 *         (Optional) Annotated-intervals file from {@link AnnotateIntervals}.
 *         Must contain the intervals to be filtered as a subset.  Must be provided if no counts files are provided.
 *     </li>
 *     <li>
 *         (Optional) Counts files (TSV or HDF5 output of {@link CollectReadCounts}).
 *         Must contain the intervals to be filtered as a subset.  Must be provided if no annotated-intervals file
 *         is provided.
 *     </li>
 * </ul>
 *
 * <h3>Output</h3>
 *
 * <ul>
 *     <li>
 *         Filtered Picard interval-list file.
 *     </li>
 * </ul>
 *
 * <h3>Usage examples</h3>
 *
 * <pre>
 *     gatk FilterIntervals \
 *          -L intervals.interval_list \
 *          -XL blacklist_intervals.interval_list \
 *          -I sample_1.counts.hdf5 \
 *          -I sample_2.counts.hdf5 \
 *          ... \
 *          --annotated-intervals annotated_intervals.tsv \
 *          -O filtered_intervals.interval_list
 * </pre>
 *
 * <pre>
 *     gatk FilterIntervals \
 *          -L intervals.interval_list \
 *          --annotated-intervals annotated_intervals.tsv \
 *          -O filtered_intervals.interval_list
 * </pre>
 *
 * <pre>
 *     gatk FilterIntervals \
 *          -L intervals.interval_list \
 *          -I sample_1.counts.hdf5 \
 *          -I sample_2.counts.hdf5 \
 *          ... \
 *          -O filtered_intervals.interval_list
 * </pre>
 */
```

Optional parameters not shown can filter based on count threshold.  However, note that coverage would be defined the same was as in `CollectReadCounts` (a read contributes a count towards the interval in which its start lies, assuming it passes all filters; see also #5233).  I haven't looked to see how `FindCoveredIntervals` defines coverage, but perhaps we could write an analogous `CollectBaseCounts` tool (we've had similar tools in the repo in the recent past) if necessary.

On the other hand, `DiagnoseTargets` might warrant a faithful port, as it seems to be a little less straightforward.

**Comment by droazen** [comment]
Requirements gathering for this is complete. @jamesemery will handle the implementation.
