### ISSUE TITLE
Load inteldeflater from intel-gkl, hook up to new htsjdk interface

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1903]

**Comment by akiezun** [comment]
blocked by htsjdk release

**Comment by akiezun** [comment]
@gspowley is already on it - see pull #1935

**Comment by akiezun** [comment]
@gspowley do you have a timeline on this? We need it in alpha-2 (tomorrow).

**Comment by akiezun** [comment]
I'll grab this - I have a solution in branch ak_use_intelDeflaterFactory
