### ISSUE TITLE
hook up BWA to ReadsPipelineSpark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1904]

**Comment by akiezun** [comment]
hmm, BQSR on spark wants 2bit reference and bwa wants a fasta reference.

**Comment by droazen** [comment]
Oh dear -- can provide both for now in the interests of getting it running, but we need to fix this...

**Comment by akiezun** [comment]
another issue concerns readgroups - we need to make sure that the input unmapped bam file has read group info. Also, current BwaSpark drops read group info

**Comment by akiezun** [comment]
we need to keep track of what `GATKReads` correspond to which `ShortReads` and the `Strings` returned from jbwa.  One way may be to extend `ShortRead` with a data slot to keep the back pointer to the original `GATKRead` (the jni layer would ignore it and copying 64 bits per read is not a big deal) and then copy the auxiliary data (like read groups etc) back from the `GATKRead` to the newly created `SAMRecord`

**Comment by tomwhite** [comment]
This is being done in #3666

**Comment by droazen** [comment]
This is done -- closing.
