### ISSUE TITLE
User exception for Pileup output PrintStream

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#1909]
If an invalid path is given to `Pileup`, the exception is not informative for the final user: `A USER ERROR has occurred: Invalid command line: Argument output has a bad value: /some/invalid/path. Problem constructing PrintStream from the string '/some/invalid/path'.`.

Although #121 should correct this issue, in the meanwhile it could be better to use `File` in the argument and generate the stream in `onTraversalStart` to throw a more informative `CouldNotCreateOutputFile`.

Thanks to @lbergelson for pointing it out when reviewing #1862.

**Comment by droazen** [comment]
Done in https://github.com/broadinstitute/gatk/pull/1917 -- closing
