### ISSUE TITLE
Put expected outputs for benchmark data online somewhere

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1913]
Gatk performance work, do we have output files included in our data bucket?  We need to add those so people can compare.

**Comment by ldgauthier** [comment]
There are clonable, reproducible workflows and expected outputs in the featured workspace: https://app.terra.bio/#workspaces/help-gatk/GATK4-Germline-Preprocessing-VariantCalling-JointCalling/data Admittedly the data is downsampled, but I think this is enough to compare results.  @lbergelson you can reopen if you disagree.
