### ISSUE TITLE
BwaSpark serializes the whole GATKSparkTool

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#1926]
It looks like the mapPartitions call in BwaSpark results in a larger serialized object graph than the other Spark tools. I discovered this by accident when I added a non-serializeable read filter object to the ReadInput argument collection in GATK Spark tool, which caused the BwaSparkIntegrationTest to fail. All other tests passed.

It can be reproduced it by just adding an instance of anything that's not serializeable to BwaSpark or GATKSparkTool and running the test BwaSparkIntegrationTest. At the moment the following line will do it since ReadGroupBlackListReadFilter  is currently not serializeable (though anything containing a MapEntry will do):

ReadGroupBlackListReadFilter prf = new ReadGroupBlackListReadFilter(Collections.singletonList("RG:test"), getHeaderForReads());

**Comment by droazen** [comment]
For @jamesemery -- this would be a good one for learning about Spark serialization

**Comment by jamesemery** [comment]
@cmnbroad So I checked the out this issue after the recent refactor and it appears that it might have already been fixed. When I add a non-serializable object to the BwaSpark class it still seems to pass the BwaSparkIntegrationTest. Let me know if this still seems to be an issue.

**Comment by cmnbroad** [comment]
@jamesemery I'm not surprised - I thought the refactoring might solve this when I saw the changes.
