### ISSUE TITLE
CLI: specifying list based arguments should replace, not add to, the defaults

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1928]
when an argument has a List type and a default eg

```
@Argument
List<String> foos = Arrays.asList("foo", "bar");
```

then specifying that argument on the commandline should just use the provided values and not add the provided values to the defaults (as it does currently) 

came up in review of https://github.com/broadinstitute/gatk-protected/pull/554

**Comment by lbergelson** [comment]
duplicate (but probably clearer wording) of #175

**Comment by akiezun** [comment]
feel free to close one of them

**Comment by droazen** [comment]
This is done
