### ISSUE TITLE
Add the ability to change BWA parameters in the BWA native API

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk#1942]
For the SV project, we would like to be able to change BWA's alignment parameters to tune them for the problem of aligning assembled contigs to the reference. In particular, we'd like to be able to set these parameters:

`-B9 -O16 -E1`

This will require adding some way to pass parameters to BWA instance creation to jBWA.

**Comment by SHuang-Broad** [comment]
Did an update, see [this](https://github.com/SHuang-Broad/jbwa/tree/sh_update_mem_opt)

**Comment by SHuang-Broad** [comment]
To test if it gives the same output:
1. clone bwa
2. append `bwamem-lite` to Makefile on line 13
3. use the attached hacking for `example.c` (original code doesn't take parameters)
[example.c.zip](https://github.com/broadinstitute/gatk/files/332338/example.c.zip)
4. make bwa
5. run `./bwamem-lite -B9 -O16 -E1 <path_to_indexed_ref> <path_to_SE_reads>`; capture stdout if desired
6. go to the branch in jbwa, make
7. in the `test` sub-directory, find a file named `ExampleSEChangeMemOptTestOutput.txt`, this is the output by running `ExampleSEChangeMemOpt`
8. compare the `bwamem-lite` output to the java output.

**Comment by SHuang-Broad** [comment]
Now the PR is in the original repo. 
@droazen , should we build/publish another "artifactory" based on this?
Not an emergency but just an FYI.

**Comment by SHuang-Broad** [comment]
Should we close this now, or wait until an "artifactory" is ready?

**Comment by SHuang-Broad** [comment]
Closed by #2001
