### ISSUE TITLE
Documentation and parameter name for AFCalculatorProvider disagree

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/gatk#1945]
For abstract method

```
/**
 * Returns a AF calculator given the required homogeneous ploidy and allele count (including the reference).
 * @param ploidy the required ploidy.
 * @param maximumAltAlleles the allele count.
 * @return never {@code null}
 */
 public abstract AFCalculator getInstance(final int ploidy, final int maximumAltAlleles);
```

which is the intended? should the parameter name be changed or the other way?

**Comment by akiezun** [comment]
What's the discrepancy?

On Saturday, June 25, 2016, Steve Huang <notifications@github.com> wrote:

> For abstract method
>
> /**
>  * Returns a AF calculator given the required homogeneous ploidy and allele count (including the reference).
>  * @param ploidy the required ploidy.
>  * @param maximumAltAlleles the allele count.
>  * @return never {@code null}
>  */
>  public abstract AFCalculator getInstance(final int ploidy, final int maximumAltAlleles);
>
> which is the intended? should the parameter name be changed or the other
> way?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/broadinstitute/gatk/issues/1945>, or mute the thread
> <https://github.com/notifications/unsubscribe/AB5rLzQR25GpzvicBJu2nvGBLsbUBJCOks5qPczwgaJpZM4I-deM>
> .
>


-- 
Sent from Gmail Mobile

**Comment by SHuang-Broad** [comment]
The documentation says "including the reference", but name of the parameter reads "maximumAltAlleles" . This is confusing to me.

**Comment by droazen** [comment]
Assigning to @davidbenjamin to either update the docs or close this issue if the existing docs are fine.

**Comment by davidbenjamin** [comment]
It's alt alleles.  I'll submit a PR to change the javadoc.

**Comment by droazen** [comment]
Ok thanks -- please make sure this issue gets closed once your PR is merged.
