### ISSUE TITLE
Connect HaplotypeCaller args to PairHMM

### ISSUE THREAD

**Issue by gspowley** [broadinstitute/gatk#1946]
- Create `PairHMMNativeArguments` in HaplotypeCaller and pass to `VectorLoglessPairHMM` in `PairHMM.java`.
- Supply GATK temp directory in `VectorLoglessPairHMM.java`. Currently passing `null`, which uses the system temp directory.

```
final boolean isSupported = new IntelPairHmm().load(null);
```

**Comment by gspowley** [comment]
@droazen @lbergelson 
We have a new version of GKL that resolves this issue and #1819 . I need to pass `PairHMMNativeArguments` from the HaplotypeCaller/MuTect2 command line to the GKL implementation.

I found the `pair_hmm_implementation` option in `UnifiedArgumentCollection` in gatk, but it looks like `HaplotypeCaller` uses `pair_hmm_implementation` in `LikelihoodEngineArgumentCollection` in gatk-protected. Is that right?

Can you provide some help/advice on how to hook up these new command line args?

**Comment by droazen** [comment]
@gspowley This is still a TODO, correct?

**Comment by gspowley** [comment]
Yes, @lbergelson and I worked on this a while ago. We need to revive the code.

**Comment by gspowley** [comment]
@erniebrau please look at #2259 for the code changes required.

**Comment by erniebrau** [comment]
I have made the changes to connect the PairHMM parameters [here](https://github.com/erniebrau/gatk-protected); it is based on [this branch](https://github.com/broadinstitute/gatk/tree/lb_connect_pairhmmargs), which @gspowley pointed me to. I am submitting a PR now...

**Comment by gspowley** [comment]
Closed with https://github.com/broadinstitute/gatk/pull/2574 and https://github.com/broadinstitute/gatk-protected/pull/998.
