### ISSUE TITLE
Develop strategies for profiling spark tools, and write up a wiki with findings

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1948]

**Comment by droazen** [comment]
One thing to look at is https://github.com/intel-hadoop/PAT/tree/master/PAT

**Comment by droazen** [comment]
Goal is by the end of summer to present to the rest of the team and share whatever knowledge you've gained on Spark profiling.

**Comment by lbergelson** [comment]
This wiki article is an outcome of this ticket:  https://github.com/broadinstitute/gatk/wiki/Running-Intel-PAT-on-Dataproc

**Comment by lbergelson** [comment]
James figured out how to use PAT which seems like a good solution to our profiling problems.  See #1986 and the wiki.
