### ISSUE TITLE
Figure out a way to share BwaIndex between tasks on the same executor

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk#1966]
In AlignContigsAndCallBreakpointsSpark, we were able to take care of localizing the reference once per executor, but I'm hesitant to put a BwaIndex in a static initializer for fear that it won't ever get freed. The JNI memory should be reclaimed when the executor JVM exits but it's possible that the executor could be reused for other tasks in the same application ahead of time. This issue is to see if this is something we need to worry about and find a solution.

**Comment by SHuang-Broad** [comment]
@cwhelan still valid, with the new binding, image and singleton solution?

**Comment by cwhelan** [comment]
I think the new architecture fixed this.
