### ISSUE TITLE
use getExecutorCores to guide parallelism in AlignContigsAndCallBreakpointsSpark

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk#1967]
We currently repartition the data into a fixed number of assemblies per partition. Once getExecutorCores is implemented in https://github.com/broadinstitute/gatk/pull/1947, we could make sure that we don't reduce the number of partitions to less than the number of cores.

**Comment by tedsharpe** [comment]
You can use `defaultParallelism()` in the JavaSparkContext for this.  In my experimentation, this is always equal to the total number of executor threads.  (Except for a brief race condition where it gives the wrong answer for the first few seconds of the lifetime of the JavaSparkContext.  Nice, eh?)

**Comment by cwhelan** [comment]
Ah, nice. Closing this then.
