### ISSUE TITLE
BwaSpark - need to account for multiple alignments returned by bwa

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#1980]
a call to jbwa `BwaMem.align2` may return a String that corresponds to multiple SAMRecords (as per comment in bwamem.h (https://github.com/lh3/bwa/blob/5961611c358e480110793bbf241523a3cfac049b/bwamem.h)

```
Note that $seqs[i].sam may consist of several SAM lines if the corresponding sequence has multiple primary hits.
```

currently, the code assumes that the string will result in 1 `SAMRecord` because it calls SAMLineParser.parseLine

The task here is to create a test case that exhibits this problem and then code up a solution to it

**Comment by droazen** [comment]
Closing -- we no longer use jbwa.
