### ISSUE TITLE
Using GATK as a dependency blows up after gkl is included

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#1985]
Using the latest `master` version of GATK4 as dependency in gradle (using [jitpack](https://jitpack.io/)) to build a shadow jar generetes the following error when a custom walker run using `java -jar shadowJar.jar CustomTool`, but also with public tools. Only if `--use_jdk_deflater true` is provided, it works. 

The log is the following (there is no other log):

```
14:57:19.102 INFO  IntelGKLUtils - Trying to load Intel GKL library from:
	jar:file:/Users/daniel/workspaces/gatk4test/build/libs/shadowJar-0.0.1-SNAPSHOT-all.jar!/com/intel/gkl/native/libIntelGKL.dylib
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000000128c014d0, pid=31197, tid=5891
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libIntelGKL8818190486223479934.dylib+0xe4d0]  _ZN7ContextIfEC2Ev+0x30
#
# Core dump written. Default location: /cores/core or core.31197
#
# An error report file with more information is saved as:
# /Users/daniel/workspaces/gatk4test/hs_err_pid31197.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6 (core dumped)
```

To fix it, I tried by excluding `com.intel.gkl` from GATK and add it as a dependency to my program, but it blows up anyway. In addition, I tried a sample program to load the PairHMM fastest implementation by `PairHMM.Implementation.FASTEST_AVAILABLE.makeNewHMM()`, and it also blows up. If I remove completely the dependency in my shadow jar, the command line blows up because the gkl `IntelDeflaterFactory` is not found.

I guess that the error in the library is GKL-related, but in the case of the GATK framework I would like to have a way of using the library without assuming that the final user will have support for the native code or not. Could this be done? I prefer not to remove the faster code by intel because I know that some users will benefit from it.

Just in case it is needed, my system is a Mac OS X (10.11.5) with Darwin Kernel Version 15.5.0 (root:xnu-3248.50.21~8/RELEASE_X86_64 x86_64).

Thank you very much in advance.

**Comment by akiezun** [comment]
@gspowley can you have a look at this?

**Comment by droazen** [comment]
If the GKL can't be loaded on a particular platform/architecture, it should fall back to the Java implementations transparently and without error. If it's not doing so, that's a bug.

**Comment by gspowley** [comment]
@magicDGS can you please attach /Users/daniel/workspaces/gatk4test/hs_err_pid31197.log to this issue?

**Comment by magicDGS** [comment]
I removed that one, but this is from another run (with the whole dependency): [hs_err_pid32046.log](https://github.com/broadinstitute/gatk/files/354563/hs_err_pid32046.txt)

**Comment by lbergelson** [comment]
@magicDGS This is probably unrelated to the error, but we publish builds to our [artifactory](https://artifactory.broadinstitute.org/artifactory/webapp/browserepo.html?2) on every commit to master.  It might be easier to use those than to use jitpack.

**Comment by gspowley** [comment]
Thanks @magicDGS. I see the segfault is happening during PairHMM initialization when GKL is loaded. We have a Mac with the exact same OS version, but haven't been able to reproduce the error yet.

Let's rule out any HW differences. Can you please post the results of this command?
```
> sysctl -a | grep machdep.cpu.*features
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 BMI2 INVPCID FPU_CSDS
machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT RDTSCP TSCI
```

**Comment by magicDGS** [comment]
@gspowley, it also blows up without initialize PairHMM... I can do another test without that to send you the log.

And here it's the result from `sysctl -a | grep machdep.cpu.*features`:

```
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 POPCNT
machdep.cpu.extfeatures: SYSCALL XD EM64T LAHF RDTSCP TSCI
```

**Comment by magicDGS** [comment]
@lbergelson, is there  the `master` branch of GATK in the artifactory?

**Comment by gspowley** [comment]
Thanks @magicDGS. It looks like the issue is your CPU doesn't support AVX. We decided not to support CPUs without AVX, but we should fallback to Java if AVX is not supported. We'll make a new release of GKL to resolve this issue.

**Comment by magicDGS** [comment]
Thank you very much, @gspowley. If it could not be used without AVX, I'm fine. The only problem is that I would like to be able to use the GATK framework for my program, and I need it to run in any computer.

I will appreciate if you let me know when it is solved. Thank you in advance.

**Comment by lbergelson** [comment]
@magicDGS There isn't a specific master branch, but each push to master gets it's own artifact with a name like 4.alpha.1-208-g702c9e3-SNAPSHOT.   You can search for the short commit hash of the build you want and use that artifact. 

you'll need to add the artifactory repository to your build file

```
repositories {
    maven {
        url "https://artifactory.broadinstitute.org/artifactory/libs-snapshot/" 
    }
```

There seems to be some bug right now where it hasn't uploaded the last 2 commits to master, I'm not sure what's causing that, but in general there should always be the most recent commits to master available.  (As well as a snapshot of every pull request branch).

It wouldn't be a bad idea for us to have master-SNAPSHOT as well, maybe we should do that.

**Comment by droazen** [comment]
:+1: on `master-SNAPSHOT` (in addition to versioned snapshots, not as a replacement for them)

**Comment by magicDGS** [comment]
Thanks @lbergelson, I will have a look to include the artifactory in my reporitories instead of jitpack. And I also like the idea of a master-SNAPSHOT.

**Comment by magicDGS** [comment]
@droazen, @lbergelson, should I open a ticket regarding this?

**Comment by droazen** [comment]
@magicDGS Sure, go ahead

**Comment by gspowley** [comment]
This issue is resolved in GKL 0.1.2.
@droazen do you want a new PR that only changes the GKL version?

**Comment by droazen** [comment]
@gspowley Yes, let's bump our GKL version to get the fix.

**Comment by magicDGS** [comment]
Closing because #1991 solves the issue
