### ISSUE TITLE
Create VariantsSparkSink that works similarly to ReadsSparkSink

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1989]
We need a way to write sharded vcf/variant data on Spark, with the option of assembling the shards into a single output file, like we have for reads. This implies a need for a `VariantsSparkSink` that works like `ReadsSparkSink`

**Comment by droazen** [comment]
Needed for https://github.com/broadinstitute/gatk/issues/1639, among other things.

**Comment by tomwhite** [comment]
Fixed in #2103
