### ISSUE TITLE
Package precompiled HDF5 as hdf5-java-bindings, and pull it down via maven

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#1990]
This will greatly simplify setup for gatk-protected.

**Comment by droazen** [comment]
Should contain versions for both Mac and Linux, and implement the `NativeLibrary` interface from `gatk-native-bindings`

**Comment by droazen** [comment]
For @akiezun and alpha-3

**Comment by akiezun** [comment]
https://github.com/broadinstitute/hdf5-java-bindings/pull/3

**Comment by akiezun** [comment]
packaging it done. I dont know how to do maven. Assigning to @droazen

**Comment by droazen** [comment]
Done -- `1.0.0-hdf5_2.11.0` released to central. Back to @akiezun to finish up this ticket.

**Comment by akiezun** [comment]
done!
