### ISSUE TITLE
Continuous snapshots failing

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#1993]
For an unknown reason master snapshots are failing.  They're trying to upload with the version "unspecified-SNAPSHOT".

I don't know why they're not setting the version properly.  

The last good build was 
f3cd74 [travis-log](https://travis-ci.org/broadinstitute/gatk/jobs/143069453)
the next build has nothing suspicious in it as far as I can tell
69a0f89 [travis-log](https://travis-ci.org/broadinstitute/gatk/jobs/143174237)

I suspect it may have something to do with the shallow clone that travis does.  I suspect that with the clone being shallow, the last tag was lost and git describe is unable to describe.  I'm not sure why it occurred on 203 though, since the clone is 50 deep.  In any case, using the clone command from github results in a clone that reports an undefined version.  

`git clone --depth=50 --branch=master https://github.com/broadinstitute/gatk.git broadinstitute/gatk`

Not sure what the best solution is, but the easiest is to just set the version manually.

**Comment by droazen** [comment]
@lbergelson Let's just have travis run `git fetch --unshallow` after doing its clone -- this should fix it.
