### ISSUE TITLE
Snapshot for master

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#1995]
It will be nice to have in the Broad Institute artifactory a `master-SNAPSHOT` in addition to the commit-specific SNAPSHOT to use in developmental projects which use the latest commit.

**Comment by lbergelson** [comment]
This may not be working correctly yet.  It seems like it might be publishing snapshots from other pull requests as master.  Don't use this snapshot yet.

**Comment by droazen** [comment]
Let's be sure to delete the mis-labelled snapshots once we've resolved this.

**Comment by lbergelson** [comment]
It looks like the errant snapshot was one that I uploaded manually last week and forgot about.  This should be good.

**Comment by lbergelson** [comment]
@magicDGS You should be able to use master-SNAPSHOT as a dependency from artifactory now.

**Comment by magicDGS** [comment]
Thanks @lbergelson.

There are some issues with the current implementation of the filter plugin and barclay that is preventing me to use the latest master, but once they are solved I will try it out and if I find any problem I will report it.

For me, as a solo developer, this is going to be amazing for keeping everything up-to-date without breaking compatibility before releases of my own software.
