### ISSUE TITLE
Update `AlignContigsAndCallBreakpointsSpark` with jBWA's para changing capacity

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/gatk#2001]
The updated jBWA code allows changing scoring parameters for `bwa mem`. 
Specifically, the `BwaMem` class now has a method `updateScoringParameters()`.

This ticket is to remind the SV group to update, accordingly, the class `AlignContigsAndCallBreakpointsSpark` and `ContigAligner.java`.

Closes #1942 .

**Comment by droazen** [comment]
Closing -- we no longer use jbwa.
