### ISSUE TITLE
Migrate from the v1beta2 Google Genomics API to the v1 API

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2009]
Request from Google. Migration instructions are here: http://googlegenomics.readthedocs.io/en/latest/migrating_v1beta2_to_v1.html

**Comment by melissachang** [comment]
Hi, we (Google) are still seeing v1beta2 requests from Broad.

genomics.referencesets.search
genomics.references.search
genomics.references.bases.list

https://github.com/broadinstitute/gatk/search?utf8=%E2%9C%93&q=v1beta2

Can this issue be reopened?

**Comment by jean-philippe-martin** [comment]
ReferenceAPISource talks to Genomics API v1beta2, and if nothing else ReferenceAPISourceUnitTest will exercise this code.

https://github.com/broadinstitute/gatk/search?utf8=%E2%9C%93&q=ReferenceAPISource&type=Code

**Comment by droazen** [comment]
@jean-philippe-martin A (hopefully) quick one for you when you have some spare time.

**Comment by droazen** [comment]
Closing -- we've removed support for the legacy Google Genomics API.
