### ISSUE TITLE
create wiki page with spark performance information

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2012]
Many people are doing performance work on spark, but we're not collecting that data in a single place so people are reinventing the wheel.

We should try to collect at least some spark best practice information in a single place.

**Comment by droazen** [comment]
Assigning to @akiezun to gather his past performance results into one place.

**Comment by akiezun** [comment]
why don't people just search the tickets and look for 'performance' ? I guess we can make a wiki with 'best practices' but the code already incorporates the best practices as we know them

**Comment by lbergelson** [comment]
I don't think we're doing this.
