### ISSUE TITLE
Genotype likelihoods ignore combinatorial factor

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#2019]
`HaplotypeCaller` works with unphased genotypes.  The unphased genotype A/B represent the phased genotpyes A/B _and_ B/A, for a combinatorial factor of 2, in contrast to A/A, which has a combinatorial factor of 1.  It does not appear that the genotype likelihoods emitted by `GenotypeLikelihoodCalculator` account for this.  That is, the genotype likelihoods for heterozygous diploid genotypes are too small by a factor of 2.  The relevant code in `GenotypeLikelihoodCalculator` is

``` java
private double[] genotypeLikelihoods( [arguments])  {
  ...
  for (int g = 0; g < genotypeCount; g++) {
    result[g] = MathUtils.sum(readLikelihoodsByGenotypeIndex[g], 0, readCount) - denominator;
    [ we need result += (GenotypeAlleleCounts of genotype g).log10CombinationCount() ]
        }
  ...
```

@ldgauthier @vruano do you agree?

**Comment by ldgauthier** [comment]
I've gone around in circles for a while on this issue and I'm need more convincing.

First off, SOAPsnp has the same equations we do, lacking the 2x factor on het genotypes: http://genome.cshlp.org/content/19/6/1124.full#sec-14

Secondly, to think about comparing likelihoods (which I get in trouble with sometimes because I was raised frequentist, so I may be going off in the wrong direction), as the calculations are now, you are twice as likely to observe a read from the reference haplotype given that the genotype is homRef than you are to observe a read from the reference haplodype given that the genotype is heterozygous reference.  That seems right to me, but I may be thinking about it backwards.  If you add the binomial coefficient, then the two likelihoods will be equal.

**Comment by lh3** [comment]
I guess these are two separate issues: a factor of 2 and binomial coefficient. I am not sure I understand the argument for the factor of 2. In the derivation, where does this 2 come in? Binomial coefficient is the more tricky part. You can derive the formula in two ways, one with binorm coef and the other not. You will end up with the same result as the binorm coef is canceled out.

**Comment by davidbenjamin** [comment]
To put it another way, what we call `genotypeLikelihoods[n]` is the quantity Prob(reads | genotype n), where n is calculated as if it were a phased genotype (as far as I can tell).  Since we call *unphased* genotypes, we really need Prob(reads | unphased genotype) = Sum_{phased genotypes consistent with this unphased genotype} P(read | phased genotype) = combinatorial factor * P(reads | phased genotype).

**Comment by davidbenjamin** [comment]
> First off, SOAPsnp has the same equations we do, lacking the 2x factor on het genotypes: http://genome.cshlp.org/content/19/6/1124.full#sec-14

True, but because they consider only calling of single-sample diploid SNPs they can absorb the combinatorial factor in their very simple prior.  I'm not saying they *do* this (they don't really justify their priors), but I'm saying that in principle they could.  And for all I know maybe we do the same in the exact model.  In the new AF model, however, the most natural place for this factor is in the genotype likelihoods, not in the prior.

**Comment by lh3** [comment]
In derivation, we always use unphased genotypes. If you derive the equation using phased genotypes to start with, I believe the factor of 2 will appear at the beginning but will be canceled out in the end. You will get the same equation.

As to soapsnp, you can move a factor of 2 between likelihood and prior. For SNP calling, the result will be the same. However, if you do that, the likelihood you get will not be the (unphased) genotype likelihood.

**Comment by pgrosu** [comment]
Maybe I'm simplifying things too much, but can't the equation in the paper be just rewritten as follows and thus the 2 will get eliminated?

![haploid](https://cloud.githubusercontent.com/assets/6555937/17074490/c72614e0-5049-11e6-856c-243901521a41.png)

**Comment by davidbenjamin** [comment]
@pgrosu Yes, that's correct.  My point is that *in the code* the factor of 2 in the numerator of your expression appears to be missing.  If I have read the code of `GenotypeLikelihoodsCalculator::genotypeLikelihoods` correctly it behaves as follows (calculations are in log space but I have translated to real space; also it divides by ploidy at the end of the calculation instead of per read, but the effect is the same).

Suppose (for pedagogical purposes) we have a triploid genotype AAB.  Then the likelihood P(R | G = AAB) of read R given the genotype is (2/3) P (R | A) + (1/3) P (R | B).  The overall likelihood of genotype AAB is the product of P(R | G) over all reads.  This is the likelihood of the *phased* genotype AAB, and it is the same GL that is used downstream in HaplotypeCaller.  I don't see anywhere in the code where the (equal) contribution of a different permutation (eg ABA, BAA) is added, as in the numerator of your expression.

Furthermore, it's hard to see where the correct combinatorial factor is hiding, because until you multiply the read likelihoods (add in log space) of all reads, which is a pretty transparent step, you *have to* work with phased genotypes (since all reads must share the same phased genotype, you have to have a hierarchical model with unphased genotype -> phased genotype -> { all reads }).  Thus, if a permutation factor needs to be there, it could only be put in right after all the read likelihoods are multiplied and nowhere else.

**Comment by vruano** [comment]
I think @davidbenjamin is correct, that class does not produce unphased likelihoods but phased one. That is per se not a problem if they are handled appropriatelly down stream. 

For example i think the Exact AF calculator does handle them as phased likelihoods. However many if not most of other usages may be wrong, for example the VCF output itself. The spec doesnt say whether the PL are phased or unphased or whether it would depend on whether the GT is phased or unphased itself. 

It seems that we have been rather careless all this time as to how we were using those likelihood and we shall revise that. 

In practice it only makes a difference low signal/noise ratio data... perhaps this is the source or a source of bias against het calls if that has been observed in the past.

My suggestion is to rename the likelihood emitting methods adding Phased to them and a new  Unphased method set delegate on those applying the corresponding coefficient.

**Comment by ldgauthier** [comment]
Oops, I did not read the initial issue carefully enough -- sorry.

I thought I'd checked some easy SNP PLs by hand a long time ago, but maybe not.  Anyway, I agree with Valentin that most of the time the differences in haplotype likelihoods are drastic enough that the 2X factor won't make a big difference.  :+1: to the rename and new method.

**Comment by pgrosu** [comment]
@davidbenjamin, et al.  I have two recommendations:

1) Though I prefer to work symbolically and through proofs, it might be nice to first expand on the validation by proof in the JavaDoc - including for the specific function's header - and anywhere else where necessary across the GATK code, just for sanity's sake, and for tying things together neatly and properly.  This process of always going through the mathematical steps alerts me when I code that I have not missed anything. 

2) When dealing with multiple levels of transformations, it probably would be good to formulate a collection of complete set of simple tests.  Since like you mentioned {phased} is a subset (⊂) of {unphased}, then the paths of phased genotypes one works with would also be ideal to test on.  Does this function have any validation tests against the likelihoods can be confirmed for both phased and unphased genotypes?  These can be generated tests, if original files do not exists.

Hope it helps,
Paul

**Comment by lh3** [comment]
@pgrosu I think your derivation is wrong. The correct one is the following. Let
```
P(r|h) = P(r|read r was sequenced from haplotype h)
```
The genotype likelihood is (in math `<h1,h2>=<h2,h1>` typically denotes an unordered pair):
```
P(r|<h1,h2>) = 1/2*P(r|r from h1)+1/2*P(r|r from h2) = [P(r|h1)+P(r|h2)]/2
```
If `h1==h2`, we get the GL of a hom: `P(r|<h1,h1>)=P(r|h1)`. If `h1!=h2`, we get the GL of a het: `P(r|<h1,h2>)=[P(r|h1)+P(r|h2)]/2`, which in my understanding is what the source code is doing according to @davidbenjamin. Note that in most cases, `r` is one of `h1` and `h2`. `P(r|<h1,h2>)` is often very close to 1/2. Actually when Mark explains the model, he just uses 1/2 for het genotype likelihood.

Biologically speaking, there are actually no "phased genotypes" – when we talk about genotypes, we always ignore phasing. Mathematically, however, you can still define a "phased genotype" as `(h1,h2)` – here `(h1,h2)` is an ordered pair. The (phased) genotype likelihood is the same:
```
P(r|(h1,h2)) = 1/2*P(r|r from h1)+1/2*P(r|r from h2) = [P(r|h1)+P(r|h2)]/2
```
However, the prior is different from the unphased case: at a het where `h1!=h2`:
```
P((h1,h2)) = P((h2,h1)) = P(<h1,h2>)/2
```
Therefore, the posterior of a het is `P((h1,h2)|data)=P(<h1,h2>|data)/2`.

In all, I still think the current GATK implementation is correct. Also note that all the equations in my samtools paper are based on the so-called "unphased genotypes" `<h1,h2>`. Unless you substantially modify those equations, adding a factor of 2 will make everything wrong in math.

**Comment by ldgauthier** [comment]
@davidbenjamin after letting this percolate for a few years, are you convinced by Heng's argument?

**Comment by davidbenjamin** [comment]
I wish I were.  The `AlleleFrequencyCalculator` accounts for this when it computes posteriors and multiplies by the combinatorial factor.  Nonetheless, I don't agree that the likelihoods of phased and unphased genotypes are the same and only the priors are different.  As I see it, the unphased genotype likelihood is
P(reads | unphased h1,h2) = P (reads | either maternal h1, paternal h2 OR maternal h2, paternal h1)
= P (reads | either maternal h1, paternal h2) + P(reads | maternal h2, paternal h1)
= 2 x phased genotype likelihood

I see Heng's point that the combinatorial factor is really part of the prior, not the likelihood, but I don't agree.  But above all, it would be nice to close this issue.

**Comment by lh3** [comment]
The following equation is wrong:

> P (reads | either maternal h1, paternal h2 OR maternal h2, paternal h1)
= P (reads | either maternal h1, paternal h2) + P(reads | maternal h2, paternal h1)

You can't apply plus to replace "OR" in conditions. The following is mathematically correct: "P (either maternal h1, paternal h2 OR maternal h2, paternal h1 | reads)
= P (either maternal h1, paternal h2 | reads) + P(maternal h2, paternal h1 | reads)"

**Comment by davidbenjamin** [comment]
Okay, I see my error now:

It is fine to marginalize over all phased genotypes consistent with het by saying:

 P(reads | unphased genotype g) = sum(phased genotype g' consistent with unphased genotype g) P(g' | g) P (reads | g')

_However_, I have been implicitly setting P(g' | g) = 1, which is obviously incorrect.  So it looks like 1) the GATK has both the correct likelihood in the PLs and the correct posterior in the qual model; 2) we can close this issue.  Sorry for being dense, Heng!

**Comment by lh3** [comment]
Just for future readers, my derivation in your style looks something like:
```txt
  P (reads | unphased h1,h2)
= P (reads | either maternal h1, paternal h2 OR maternal h2, paternal h1)
=  P(reads, maternal h1, paternal h2 | either maternal h1, paternal h2 OR maternal h2, paternal h1)
 + P(reads, paternal h1, maternal h2 | either maternal h1, paternal h2 OR maternal h2, paternal h1)
=  P(reads | maternal h1, paternal h2) * P(maternal h1, paternal h2 | either maternal h1, paternal h2 OR maternal h2, paternal h1)
 + P(reads | paternal h1, maternal h2) * P(paternal h1, maternal h1 | either maternal h1, paternal h2 OR maternal h2, paternal h1)
= [P(reads | maternal h1, paternal h2) + P(read | paternal h1, maternal h2)] / 2
```
where
```
1/2 = P(maternal h1, paternal h2 | either maternal h1, paternal h2 OR maternal h2, paternal h1)
    = P(paternal h1, maternal h1 | either maternal h1, paternal h2 OR maternal h2, paternal h1)
```
