### ISSUE TITLE
make bigger correct input for bwaspark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#2027]
for bwaspark reads must be paired or you get `[mem_sam_pe] paired reads have different names`. Our only paired data is tiny "CEUTrio.HiSeq.WGS.b37.NA12878.20.21.tiny.queryname.noMD.bam"

this ticket is about creating a bigger dataset of correctly paired reads

**Comment by lbergelson** [comment]
is gs://hellbender/test/resources/benchmark/CEUTrio.HiSeq.WEx.b37.NA12892.readnamesort.bam not paired properly?

**Comment by akiezun** [comment]
@lbergelson that may work but it requires an indexed fasta that we have not provided (bwa index is the command one needs to run - it creates I think 9 files, some as big as 3GB).

I'll close this for now. I sent a bigger file to our Intel collaborators.
