### ISSUE TITLE
Try skipping/ignoring contigs that are below a given length

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk#2031]
The assembly output sometimes includes a bunch of small contigs, including unassembled reads (ie contigs of length 151). We should investigate ignoring these small contigs since they probably are not much help in identifying breakpoints.

**Comment by SHuang-Broad** [comment]
Would this be useful: In the graph, if the these extremely short contigs are orphans/islands (not overlapping with any other contigs), we can probably safely ignore them, as these would suggest, even if they generate a chimera, the signal could be poorly-supported.

In this regard, I think fermi-lite has a very-nice feature that's desirable: for the final graph it outputs, the number of reads used to generate the contig is given, plus the coverage for each base .

**Comment by SHuang-Broad** [comment]
Still valid as of date 2017/07/06.

**Comment by cwhelan** [comment]
This is outdated; closing.
