### ISSUE TITLE
SAMSequenceDictionary for 2bit references is not in a good order

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk#2037]
When using a 2bit reference, the sequence dictionary appears to be in an arbitrary order. When used to sort VCF files, this produces very strangely sorted variants. It would be nice if there was some way to associate reference index files (ie .fasta.fai) with a 2bit reference, or some other solution for getting a useable sequence dictionary when using 2bit references.

**Comment by droazen** [comment]
This is fixed in https://github.com/bigdatagenomics/adam/pull/1508, but that project needs to do a release in order for us to get the fix.

**Comment by droazen** [comment]
According to the ADAM people, a release is imminent within the next few weeks.

**Comment by droazen** [comment]
I believe this was fixed by https://github.com/broadinstitute/gatk/pull/4044 -- @cwhelan or @tedsharpe can you please confirm?

**Comment by tedsharpe** [comment]
@droazen @cwhelan Yes, it appears to be fixed.  (Don't have a failing test that I can run on the old behavior, but a quick test of the latest code in master appears to have repaired the flaw.)
