### ISSUE TITLE
BwaSpark fails silently to align any reads

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#2038]
checkout the ak_bwa_nothing branch
run `./gatk-launch BwaSpark -I src/test/resources/org/broadinstitute/hellbender/tools/spark/bwa/BwaSpark/testBWA.bam -R src/test/resources/large/human_g1k_v37.20.21.fasta -O foo.bam`

see foo.bam - it only has a header. I expected 10 reads

**Comment by SHuang-Broad** [comment]
unaligned bam `testBWA.bam` isn't there?

**Comment by akiezun** [comment]
it's fixed now

**Comment by akiezun** [comment]
I'll look into this

**Comment by akiezun** [comment]
OK, I know what this is - all reads get filtered out but Spark tools currently do not report any filtering statistics. I'm going to unassign myself because i won't be able to work on it now

**Comment by akiezun** [comment]
@droazen FYI

**Comment by huangk3** [comment]
Hi @akiezun How did you get the unaligned bam from fastq? I tried FastqToSam, but got the error:
"In paired mode, read name 1 (HWI-D00377:30:H8EJDADXX:1:2209:8491:93586) does not match read name 2 (HWI-D00377:30:H8EJDADXX:1:2104:20024:30303)". Do you know how to get rid of that error?

**Comment by droazen** [comment]
@tedsharpe Can you have a quick look to see if this is still an issue with the current version of `BwaSpark`?

**Comment by lbergelson** [comment]
closing in favor of #2120
