### ISSUE TITLE
GenotypeGVCFs bug when calculating the QUAL column in multi-allelics.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#2040]
Port changes in https://github.com/broadinstitute/gsa-unstable/pull/1442 once it has been merged into gsa-unstable/master.

**Comment by vruano** [comment]
Has been merged into gatk3 master.

**Comment by davidbenjamin** [comment]
@droazen This would be easy for me to do in Louis's absence.

**Comment by droazen** [comment]
Thanks @davidbenjamin -- re-assigning to you!

**Comment by davidbenjamin** [comment]
Closed by PR #2184.
