### ISSUE TITLE
Argument to include Supplementary Alignments in HaplotypeCaller

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/gatk#2043]
Once #2021 is merged the resulting bam files will have supplementary alignments that we want HaplotypeCaller to include. We'll also need to run HaplotypeCaller with --dontUseSoftClippedBases since the soft clipped bases are now being represented in the supplementary alignments. 

Until this argument is made the new version of SplitNCigarReads is not recommended.

**Comment by vdauwera** [comment]
Are they not already? Or is this different between GATK3 and GATK4? Bit of relevant discussion happening right now over here: https://github.com/broadinstitute/dsde-docs/issues/1092#issuecomment-234985659

**Comment by meganshand** [comment]
Hmm, I don't have access to dsde-docs. I thought by default haplotypeCaller doesn't use supplementary reads in GATK3? If I'm wrong about that assumption, then I don't see any reason why it would be different in GATK4.

**Comment by vdauwera** [comment]
I just added you so you should have access now.

**Comment by meganshand** [comment]
@vdauwera Thanks, this is great for RNA! We won't have to change anything and this ticket is done.
