### ISSUE TITLE
dependency conflict with gcloud-java-nio

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/gatk#2044]
### Background: jar dependency hell

Getting GATK to compile with the gcloud-java-nio dependency is already a little bit of a struggle because of conflicting versions of the com.google.protobuf class (see #2013). Running it on Dataproc results in a version conflict somewhere else, probably linked to the jars that are automatically included on Dataproc.

Getting gcloud-java-nio to work on vanilla Spark runs into the exact same category of problems (dependency conflicts), see eg. [this question on StackOverflow](http://stackoverflow.com/questions/38536004/spark-java-noclassdeffounderror-when-adding-dependency/38575957#38575957).

The root of the problem is that both Hadoop and GCloud-Java rely on the same core Google libraries (Guava, Protobuf), but they use different versions that are incompatible. Java is not currently able to have two different versions of the same library at once, so instead you end up forcing one version of the other. Neither version appears to work for all of our dependencies, so we have a problem.

### Workaround

Barring improvements in Java, our only way forward may be to use a shaded "fat jar" version of gcloud-java-nio that (i) includes all of its dependencies in a single jar and (ii) renames the shared dependencies so they won't conflict with what eg. Hadoop brings in.

Luckily, gcloud-java-nio already builds such a jar by default. However that jar is not published on Maven Central.

So the solution is to download the gcloud-java-nio source code, compile it ourselves (without any modification), and use the resulting jar (target/gcloud-java-nio-0.2.7-SNAPSHOT-shaded.jar). 

This solution works for both vanilla Spark and GATK.

I suspect it would be acceptable for us to directly include that jar in our source tree so that our own users wouldn't have to take any special steps to use GATK: just compile and run, as usual.

Let's discuss.

CC: @droazen @lbergelson

**Comment by pgrosu** [comment]
@jean-philippe-martin I can see the shaded Jar in the following repository:

https://oss.sonatype.org/#nexus-search;quick~gcloud-java-nio

You can even download it from the following link:

https://oss.sonatype.org/service/local/repositories/snapshots/content/com/google/cloud/gcloud-java-nio/0.2.7-SNAPSHOT/gcloud-java-nio-0.2.7-20160722.195539-2-shaded.jar

Hope it helps,
~p

**Comment by jean-philippe-martin** [comment]
Indeed, I stand corrected! So we can do what I was describing but directly using Maven (or Gradle), no need to compile anything custom. I tried it and it seems work. Great!

**Comment by pgrosu** [comment]
Super duper - glad it helped :)  No problemo, Bioinformatics/CS is always most fun as a team - feel free to ping the list anytime on anything :)  

Cheers,
~p
