### ISSUE TITLE
GATKRead - investigate caching of query values

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#2058]
some queries like `isPaired` or `isUnmapped` are called over and over on GATKReads and definitely have impact on performance, eg see #2032. It may make sense to cache those values - the risk is that reads are mutable and so caches need to be invalidated and that cached valued (even booleans) add overhead to memory footprint and shuffle footprint. 

This ticket is to implement caching of those frequently called queries and measure performance impact.

**Comment by jamesemery** [comment]
We already cache these values
