### ISSUE TITLE
Turn off BAQ by default in BQSR

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2060]
A recent palantir investigation showed that disabling BAQ has only a very miniscule effect on variant calls, while providing a 77% performance boost. We should disable it by default in GATK4 (unless @vdauwera objects).

**Comment by eitanbanks** [comment]
Do it!

**Comment by akiezun** [comment]
do you want to flip the default value of the `skipBAQ` flag or flip the flag itself, rename to `useBAQ`?

**Comment by akiezun** [comment]
flipping the default for `skipBAQ` will be

**Comment by akiezun** [comment]
keeping the old flag and flipping the default will make sure that old scripts still work. But having a flag that defaults to true is non conventional.

**Comment by droazen** [comment]
I say flip it to `enableBAQ`

**Comment by vdauwera** [comment]
+1 to enableBAQ
