### ISSUE TITLE
VQSR alpha-3 Epic

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2062]
This epic is to track work on porting and validating VQSR for alpha-3. Feel free to add related tickets to the epic.

**Comment by samuelklee** [comment]
Not sure if this is outside the scope of a simple port, but I think it would be great if the fitting of a `GaussianMixtureModel` was made a little bit more generic and extracted.  Right now the method `maximizeGaussian` takes in `List<VariantDatum>`, but it should be trivial to refactor it to take in a `double[]` or `List<Double>`.  Fitting a GMM could be more generally useful for other methods, after all.  It might even be useful to extract the k-means clustering code used to initialize the model, if this is retained in the port.

Perhaps also outside the scope, but it'd also be nice if variable names were changed to match the notation in Bishop Ch. 10 (on which the variational-Bayes algorithm is based).  I think this would make the code much easier to parse from a mathematical standpoint.

**Comment by akiezun** [comment]
I'd definitely advise against combining the port with improvements to the code or the algorithm - I tried it and it was a very bumpy ride. The code is a mix of vqsr-specific and non-specific general-math parts and does not follow any particular notation or textbook. If you want to improve it after the port, that's fine but I think it needs to be separated.

**Comment by samuelklee** [comment]
OK---I'll volunteer if no one else is champing at the bit!  It's possible that we might want to do some GMM stuff for tumor heterogeneity.

**Comment by droazen** [comment]
The task here is to simply move the code while changing as little as possible, and then validate that. Once that's done, we can do whatever refactoring/changes we want to VQSR, or replace it completely.

**Comment by droazen** [comment]
This is done
