### ISSUE TITLE
Port VQSR tests, slimming down as necessary to achieve reasonable runtime

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2063]

**Comment by droazen** [comment]
Alternatively, if we can't slim down the test data without harming the legitimacy of the tests, we can explore running the VQSR tests in parallel in travis (as a separate test group).

**Comment by droazen** [comment]
We also have to audit the data to identify private data, and replace or sanitize.

**Comment by cmnbroad** [comment]
Closing via #2164.
