### ISSUE TITLE
Create JNI (experimental) for fermi-lite as the assembler in SV pipeline

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/gatk#2072]
Limited manual eyeballing seem to suggest it's worth a try, and go large scale for more testing.

**Comment by lh3** [comment]
Let me know if you want more methods exposed, or need any help in general.

**Comment by SHuang-Broad** [comment]
Yep. Thanks @lh3 !

**Comment by SHuang-Broad** [comment]
Updated with [this](https://github.com/SHuang-Broad/JNIFermiLite).

@cwhelan would you mind taking a brief look and see what improvements can be made to the interface?
@lbergelson I also added you as a contributor so later if we decide to make use of fermi-lite in the SV pipeline, you'll be in control.

Thanks!

**Comment by droazen** [comment]
@tedsharpe This can be closed too, right?

**Comment by tedsharpe** [comment]
Yes.  Done.  Closing.
