### ISSUE TITLE
Invalid Genomic Location for VariantWalker with indexed files without dictionary when providing other sources

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#2081]
If a `VariantWalker` driving variant is indexed with tribble but does not have an sequence dictionary in the header, the dictionary is loaded from the index. Nevertheless, this is a truncated dictionary because the end coordinate for each chromosome is the last variant in that contig.

Thus, even if a proper interval for the genome is provided (regarding the reference sequence), the program throw an user error exception. This could be reproduced with the following test in `ExampleVariantWalkerIntegrationTest`:

```java
    @Test
    public void testExampleVariantWalkerInvalidDictionary() throws IOException {
        final IntegrationTestSpec testSpec = new IntegrationTestSpec(
                " -L 1:200-1125" +
                        " -R " + hg19MiniReference +
                        " -I " + TEST_DATA_DIRECTORY + "reads_data_source_test1.bam" +
                        " -V " + TEST_DATA_DIRECTORY + "example_variants.vcf" +
                        " -auxiliaryVariants " + TEST_DATA_DIRECTORY + "feature_data_source_test.vcf" +
                        " -O %s", Arrays.asList(TEST_OUTPUT_DIRECTORY + "expected_ExampleVariantWalkerIntegrationTest_output.txt"));
        testSpec.executeTest("testExampleVariantWalker_UndefinedContigLengthsInDictionary", this);
    }
```

The thrown exceptions is the following:
```java
java.lang.RuntimeException: org.broadinstitute.hellbender.exceptions.UserException$MalformedGenomeLoc: A USER ERROR has occurred: Badly formed genome loc: Failed to parse Genome Location string: 1:200-1125
```

This comes from the overrided method `VariantWalker.getBestAvailableSequenceDictionary()`, which prefers the one from the driving variant (in this case, the one which comes from the index), not using the one from the reference/reads if available.

**Comment by cmnbroad** [comment]
Closing as a dup of https://github.com/broadinstitute/gatk/issues/1999.

**Comment by magicDGS** [comment]
Sorry, I haven't seen it.
