### ISSUE TITLE
Integrate GenomicsDB load VCFs java interface

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2087]
An initial very basic java interface to allow loading vcfs into GenomicsDB from GATK.
This is expected as a first step towards greater write support for genomics db.

Could possibly require json files, but ideally could create them itself.

one possible example interface:

```
GenomicsDBLoader.loadSingleSampleGVCFs(URI workspace, String arrayname, File vidJson, List<File> vcfs)
```

**Comment by droazen** [comment]
Adding to TileDB epic

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/2590
