### ISSUE TITLE
Remove -1 length once a corrected version of the exome interval list is released.

### ISSUE THREAD

**Issue by ronlevine** [broadinstitute/gatk#2089]
Follow up to https://github.com/broadinstitute/gatk/pull/2010.
Remove the following code from `IntervalUtils. intervalFileToList()` when a new exome, correctly converted interval list (with no -1 length intervals) is released :

```
if (interval.getStart() - interval.getEnd() == 1 ) { 
   logger.warn("Possible incorrectly converted length 1 interval : " + interval);
}
```

Remove corresponding test `IntervalUtilsUnitTest.testIntervalFileToListNegativeOneLength`.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/2520
