### ISSUE TITLE
Add createGVCFWriter method(s) similar to the createVCFWriter ones, and hook up to HaplotypeCaller

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2102]
and change HaplotypeCallerEngine.makeVCFWriter() (in gatk-protected) to use these instead of creating the writers manually. From @droazen: GATK3 uses the semi-unofficial file extension .g.vcf for GVCFs. There should also probably be a way to explicitly request GVCF output even when the file extension is .vcf

**Comment by ldgauthier** [comment]
This seems to have already been refactored at some point.
