### ISSUE TITLE
Abandon SamFileTester in favor of ArtificialSAMUtils for unit tests

### ISSUE THREAD

**Issue by mattsooknah** [broadinstitute/gatk#211]
Creating test files by hand is tedious, error-prone, and bloats the repo. When writing new tests, we should try to generate test data in-memory where possible.

Picard has SamFileTester, which is a wrapper around HTSJDK's SAMRecordSetBuilder. GATK has ArtificialSAMUtils. SamFileTester/SAMRecordSetBuilder is only used in a few places (e.g. MarkDuplicates), whereas ArtificialSAMUtils is heavily used, so I would say stick with the latter.

**Comment by droazen** [comment]
Closing as obsolete
