### ISSUE TITLE
Implement MultiVariantWalker for VQSR

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2114]
We need to support multiple variant inputs in VQSR for the sake of scatter-gather parallelism. In practice these inputs will be strictly non-overlapping, but we should implement a general `MultiVariantWalker` traversal in the engine rather than a VQSR-specific solution.

**Comment by cmnbroad** [comment]
When the MultiVariantWalker is integrated with VQSR, we need to make sure to update the code that populates the output header to match the way GATK3 did it with multiple inputs (mostly affects ApplyVQSR).

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/2182.
