### ISSUE TITLE
BwaSpark filters reads incorrectly

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2120]
BwaSpark is using WELLFORMED as it's read filter.  This includes a number of checks that the reads validate against the header.  However, most unaligned sam files are likely to have no or incomplete headers.  This causes many reads to be unexpectedly filtered.

We should define a better filter criteria BwaSpark.

**Comment by droazen** [comment]
@tedsharpe Would you have time to have a quick look at this to see if it's still an issue for the current version of `BwaSpark`?

**Comment by lbergelson** [comment]
this is the cause of #2038

**Comment by lbergelson** [comment]
I have a fix for this in lb_fixing_read_filter_for_bwa but I still need to write a test.

**Comment by tedsharpe** [comment]
Sure.  I can take a look.  Seems like partly a matter of taste, however.  The only real requirement for a read that is to be aligned is that it have some sequence.  Shall we back the filter off to that bare minimum?

**Comment by droazen** [comment]
Closing -- this is fixed.
