### ISSUE TITLE
Remove duplicate AdvancedOption/HiddenOption annotation implementations

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2130]
The package org.broadinstitute.hellbender.utils.commandline contains annotation classes called AdvancedOption and HiddenOption that are duplicates of Advanced and Hidden in org.broadinstitute.hellbender.commandline. All usages of these should be updated and this entire package should be removed.

Also, it looks like Hidden is not integrated with the command line parser.

**Comment by lbergelson** [comment]
advanced isn't integrated either

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/2293.
