### ISSUE TITLE
Don't call on non-chromosomal contigs in hg19

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk#2135]
We currently are processing 207 intervals on GL contigs and one on NC_007605. I don't have a lot of confidence in calling events on those contigs, and think we should probably exclude them from breakpoint evidence searches (but I think it's still a good idea to pull reads from them for assemblies).

**Comment by tedsharpe** [comment]
This is easily accomplished by adding these intervals to the kill list.  I will do so.

**Comment by tedsharpe** [comment]
Done.
