### ISSUE TITLE
Request: Allow API user to include packages for codecs

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#2139]
`FeatureManager.CODEC_PACKAGES` contains only htsjdk and hellbender codecs, but other users could develop their own codecs, and an static method for add a codec package will be interesing from the API user point of view.

**Comment by magicDGS** [comment]
This requires also a finer control for the codecs, once the configuration-code is implemented, to ignore default packages, and include/exclude single classes.

**Comment by droazen** [comment]
Should be resolved by https://github.com/broadinstitute/gatk/pull/3447

**Comment by magicDGS** [comment]
@droazen - That won't be solved by the current #3447, because there is no way of fine-tune the codecs: I require to being able to add/remove concrete classes, and exclude codecs from a concrete package. An example is a custom codec implementation for some feature, to provide extra-validation for the downstream toolkit. This would be even more useful if HTSJDK is moving to an interface-based library...

**Comment by droazen** [comment]
This ticket is just to make the codec packages configurable, which would be resolved by https://github.com/broadinstitute/gatk/pull/3447. If you need more fine-grained control than this, we could discuss as part of a separate ticket.

**Comment by droazen** [comment]
This is now configurable via Owner -- closing.
