### ISSUE TITLE
Add a --getDefaultReadFilters command line arg

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2143]
that prints the default read filters that are used for a tool.

**Comment by cmnbroad** [comment]
Ideally, this should also show the default values of the default read filter's arguments.

**Comment by magicDGS** [comment]
I will also would like to have a way to know which filters could be applied, with a similar option as this one. I guess that this will be nice for all kind of plugging. And a definition not only contained in the class name.

**Comment by cmnbroad** [comment]
Closing this in favor of https://github.com/broadinstitute/gatk/issues/2143.
