### ISSUE TITLE
FeatureInput always treats the first token as a name even when it specifies a k/v pair

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2144]
If you mistakenly leave out the name for a FeatureInput, but specify k/v pairs, the first key is never defined, i.e.:

  --resource known=true,prior=10.0:....

winds up having the name "known=true", and the known key isn't defined.

**Comment by cmnbroad** [comment]
This will be fixed in Barclay (https://github.com/broadinstitute/barclay/issues/29).

**Comment by droazen** [comment]
Closing -- will be addressed by https://github.com/broadinstitute/gatk/issues/2473 instead.
