### ISSUE TITLE
getDefaultReadFilters should be overridden in SplitNCigarReads not TwoPassReadWalker

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2148]
`getDefaultReadFilters` is overridden in `TwoPassReadWalker` but that override should be moved to `SplitNCigarReads` since it's really specific to SplitNCigarReads.

**Comment by cmnbroad** [comment]
Also at the same time the override of makeReadFilter in SplitNCigarReads should be removed (unless it doesn't want the default treatment), since its the base class implementation of makeReadFilter that does the enabling/disabling/merging of user specified read filters.

**Comment by cmnbroad** [comment]
@lbergelson I took this since I was making a PR that had changes here anyway.
