### ISSUE TITLE
Add ReadFilter support to FeatureWalker

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2152]
FeatureWalker doesn't have support for command line driven read filters, but CalculateTargetBaseCallCoverage makes use of read filters.  

It might be worth moving all of the read filter machinery into GatkTool.  There's a lot of repeated code, and if we add it to FeatureWalker than I think VariantWalker is the only walker type that's missing read filter support.

**Comment by droazen** [comment]
This is done thanks to @cmnbroad ! Closing.
