### ISSUE TITLE
Add tests for AlleleSubsettingUtils

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2158]
There is no `AlleleSubsettingUtilsUnitTest`.  Tests for `subsetAlleles` live `GATKVariantContextUtilsUnitTest` and there are no tests for `calculateMostLikelyAlleles`.

**Comment by fleharty** [comment]
@lbergelson Is this issue done, I was looking for things to contribute to, and was going to add these tests, but it looks like they are already there.

**Comment by droazen** [comment]
This one is done! Closing.
