### ISSUE TITLE
PrimaryAlignmentReadFilter doesn't filter supplementary reads

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2165]
PrimaryAlignmentReadFilter filters out secondary alignments, but not supplementary alignments (this is what GATK3 does as well). This doesn't match the SAM spec (though it does match the language used by htsjdk); is redundant given that in GATK4 we have a NotSecondaryAlignmentReadFilter for use with InsertSizeMetricsCollector; and is likely confusing.

Proposed change is to visit the usages of the PrimaryAlignmentReadFilter (BaseRecalibrator, Pileup, CalculateTargetBaseCallCoverage and HaplotypCaller) and for any that don't want supplementary alignments filtered, replace the filter with NotSecondary, and for those that do, change Primary to also reject supplementary reads.

**Comment by cmnbroad** [comment]
Related to GATK3 discussion https://github.com/broadinstitute/gsa-unstable/issues/1472.

**Comment by magicDGS** [comment]
I know the usage in the `Pileup`, because I added it when I ported it: I've just tried to mimic the samtools mpileup default filter flags. In samtools, the help of mpileup said regarding the filters: 
```
--ff, --excl-flags STR|INT  filter flags: skip reads with mask bits set
                                            [UNMAP,SECONDARY,QCFAIL,DUP]
```
Thus I guess that in the `Pileup` the usage is correct.

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/3195.
