### ISSUE TITLE
Move read filter plugin initialization to GATKTool

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2175]
There's lots of duplicate code for initializing read filters in different walker types.  (and at least one bug so far #2173)).  It seems like almost every walker type including feature and variant walkers may want to be able to filter their reads.  We should consolidate the read filter code in GATKTool and add support to FeatureWalker and VariantWalker for filtering their side inputs.

**Comment by droazen** [comment]
Assigning to @cmnbroad to make this happen for this quarter.

**Comment by droazen** [comment]
Should also include an update to gatk-protected to make the tools there use the new API in a more consistent way.

**Comment by droazen** [comment]
As part of this, should hook up to the `ReadsContext` in variant tools using a `ReadFilteringIterator`

**Comment by cmnbroad** [comment]
Closed via #2218.
