### ISSUE TITLE
Request: improvements in CreateSequenceDictionary

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#2177]
`CreateSequenceDictionary` have several things that could be improved:
- The ouptut is necessary, but a default value could be created within the tool. Because the framework reads the sequence dictionary from the same path and a default extension (**.dict**), it would be nice to allow the creation without specifying the output file and create it according to the convention.
- An option to create the **.fai** index could be included. The `samtools faidx` indexing is well [documented](http://www.htslib.org/doc/faidx.html) and it looks simple to implement. I don't know if this should be implemented here or in htsjdk.

I can contribute with both if the GATK developers think that this will improve the tool. I think that the first point is good because is fairly simple and consistent with the framework. The second could be an improvement to be able to create the two required indexes using the same bundled tool.

**Comment by droazen** [comment]
Closing as obsolete

**Comment by magicDGS** [comment]
It is not really obsolete, but I will port the issue to Picard/HTSJDK. Create all indexes needed for GATK with a single tool will be nice, including the `.fai` index and the imageIndexFile for bwa (with the same approach as in #2452, or even better if https://github.com/broadinstitute/gatk-bwamem-jni/issues/4 is implemented).

**Comment by magicDGS** [comment]
Issue opened in HTSJD: https://github.com/samtools/htsjdk/issues/830

**Comment by droazen** [comment]
We've removed all issues related to Picard tools from our issue tracker -- this is what is meant by "obsolete". Of course, you're free to port any of these issues to the Picard/htsjdk issue tracker.

**Comment by magicDGS** [comment]
Thanks for the feedback, @droazen!
