### ISSUE TITLE
create unit test AlelleSubsettingUtils.calculateLikelihoodSums

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2178]
We don't have any test that check the correctness of `AlelleSubsettingUtils.calculateLikelihoodSums` and we probably should.  (it's tested indirectly in protected, but that's not really ideal.)

**Comment by droazen** [comment]
@davidbenjamin Would you be able to add the requested test when you have time, since you created this class?

**Comment by davidbenjamin** [comment]
Sure, but "when I have the time" might be two weeks from now because M2 is intense right now.
