### ISSUE TITLE
Investigate partitioning the reference as an alternative to broadcast

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#2192]
The idea is to partition the reference in the same way as reads, then do a `zipPartitions` to join them together. Then only the relevant part of the reference is sent to each executor, which should reduce memory usage.

**Comment by jean-philippe-martin** [comment]
It'll be interesting to compare this to the Genomics Reference API approach, which can also send only the relevant part of the reference but does it on request instead of up front (unless we add prefetching).

**Comment by tomwhite** [comment]
Closing this, as its roughly what we now have in `LocusWalkerSpark`. Reference bases are retrieved once for each shard (by the worker), rather than the whole reference being broadcast to each worker, or being retrieved for each read.
