### ISSUE TITLE
Error when running VariantRecalibrator

### ISSUE THREAD

**Issue by huangk3** [broadinstitute/gatk#2199]
Hi,

I ran into this issue when running VariantRecalibrator in GATK4. I used the same command as recommended in the GATK3 best practice, but seems the command can't recognize the track information of the resources:

**java -jar ~/Softwares/gatk/build/libs/gatk-package-4.alpha.2-49-g491f7f2-SNAPSHOT-local.jar VariantRecalibrator \
    -R ~/Resources/genome_b38/genome.fa \
    -V ${op}/DUKE_6954540_200400624.vcf.gz \
    -resource hapmap,known=false,training=true,truth=true,prior=15.0 ~/Resources/genome_b38/hapmap_3.3.b38.vcf.gz \
    -resource omni,known=false,training=true,truth=true,prior=12.0 \
~/Resources/genome_b38/1000G_omni2.5.b38.vcf.gz \
    -resource 1000G,known=false,training=true,truth=false,prior=10.0 \
~/Resources/genome_b38/tmp/1000G_phase3.snps.high_confidence.b38.rh.vcf.gz \
    -resource dbsnp,known=true,training=false,truth=false,prior=2.0 \
~/Resources/genome_b38/dbsnp_142.b38.vcf.gz \
    -an DP \
    -an QD \
    -an FS \
    -an MQRankSum \
    -an ReadPosRankSum \
    -mode SNP \
    -tranche 100.0 -tranche 99.9 -tranche 99.0 -tranche 90.0 \
    -O DUKE_6954540_200400624.snp.output.recal \
    -tranchesFile DUKE_6954540_200400624.snp.output.tranches** 

The error I got is:

**"A USER ERROR has occurred: Invalid command line: Invalid argument '~/Resources/genome_b38/hapmap_3.3.b38.vcf.gz'".** 

It seems the command treat **hapmap,known=false,training=true,truth=true,prior=15.0** and **~/Resources/genome_b38/hapmap_3.3.b38.vcf.gz** as different arguments. And if I only provided "**~/Resources/genome_b38/hapmap_3.3.b38.vcf.gz**" to '**-resource**', the job shut down immediately. Is this a bug? Thanks.

**Comment by cmnbroad** [comment]
@huangk3 The syntax is slightly different for GATK4. Try this (note the ":"):

--resource hapmap,known=false,training=true,truth=true,prior=15.0:~/Resources/genome_b38/hapmap_3.3.b38.vcf.gz \

**Comment by huangk3** [comment]
Hi @cmnbroad Thanks for the quick response. I tried your suggestion, but still get the error :

**A USER ERROR has occurred: Couldn't read file ~/data/Illumina/GATK4/TEST/~/Resources/genome_b38/hapmap_3.3.b38.vcf.gz. Error was: It doesn't exist.**

Seems the ":" was converted to my current working directory.

**Comment by cmnbroad** [comment]
I think you're not getting shell expansion of the "~" because its embedded now. Try expanding that manually it the command.

**Comment by huangk3** [comment]
Hi @cmnbroad That works, thanks a lot and have a nice weekend!

**Comment by imneuro** [comment]
I had similar problem using GATK4.1.0.0.  I try to specify --resource with absolute path, yet it still give me error on path like following:

> A USER ERROR has occurred: Couldn't read file file:///dsgmnt/seq4_llfs/work/xhong/refinement/VQSR/script/hapmap,known=false,training=true,truth=true,prior
> =15:/dsgmnt/db/region/ftpGATK/resources_broad_hg38_v0_hapmap_3.3.hg38.vcf.gz. Error was: It doesn't exist.
> 

The command I used is with absolute path as following:
```
java1.8 -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compres
sion_level=2 -Xmx4g -jar /dsg_cent/packages/GATK/gatk-4.1.0.0/gatk-package-4.1.0.0-local.jar VariantRecalibrator \
-R /dsgmnt/llfs2/masterdata/geno/hg38/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta \
-V /dsguser/xhong/llfs_workdir/refinement/VQSR/gatk4100v2/c1joint_c1.filtered.SiteOnly.vcf \
--resource hapmap,known=false,training=true,truth=true,prior=15:/dsgmnt/db/region/ftpGATK/resources_broad_hg38_v0_hapmap_3.3.hg38.vcf.gz \
--resource omni,known=false,training=true,truth=false,prior=12:/dsgmnt/db/region/ftpGATK/resources_broad_hg38_v0_1000G_omni2.5.hg38.vcf.gz \
--resource 1000G,known=false,training=true,truth=false,prior=10:/dsgmnt/db/region/ftpGATK/resources_broad_hg38_v0_1000G_phase1.snps.high_confidence.hg38.vcf.gz \
--resource dbsnp,known=true,training=false,truth=false,prior=2:/dsgmnt/db/region/ftpGATK/resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf \
-an QD -an MQ -an MQRankSum -an ReadPosRankSum -an FS -an SOR -an DP \
-tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.8 -tranche 99.6 -tranche 99.5 -tranche 99.4 -tranche 99.3 -tranche 99.0 -tranche 98.0 -tranche 97.0 -tranche 90.0 \
-mode SNP --max-gaussians 6 \
-O /dsguser/xhong/llfs_workdir/refinement/VQSR/gatk4100v2/c1joint_c1.snp.recal \
--output-model /dsguser/xhong/llfs_workdir/refinement/VQSR/gatk4100v2/c1joint_c1.snp.model \
--tranches-file /dsguser/xhong/llfs_workdir/refinement/VQSR/gatk4100v2/c1joint_c1.snp.tranches \
--rscript-file /dsguser/xhong/llfs_workdir/refinement/VQSR/gatk4100v2/c1joint_c1.snp.plots.R
```

Somehow the  current path **/dsgmnt/seq4_llfs/work/xhong/refinement/VQSR/script/** was added in front of **hapmap**, which should not be there.
It would be very helpful if anyone can instruct me how to avoid this problem in GATK4.1.0.0 

Best,
Xin

**Comment by droazen** [comment]
@imneuro The syntax for tagged arguments has changed in GATK 4.1. Instead of this:

```
--resource 
hapmap,known=false,training=true,truth=true,prior=15:/dsgmnt/db/region/ftpGATK/resources_broad_hg38_v0_hapmap_3.3.hg38.vcf.gz
```

You need to write this:

```
--resource:hapmap,known=false,training=true,truth=true,prior=15 
 /dsgmnt/db/region/ftpGATK/resources_broad_hg38_v0_hapmap_3.3.hg38.vcf.gz
```

**Comment by imneuro** [comment]
Wonderful! It run through as you instructed. And then I run into R script error as following:

>13:10:07.074 INFO  VariantRecalibratorEngine - Evaluating full set of 3600 variants...
> 13:10:07.367 INFO  VariantRecalibrator - Executing: Rscript /dsguser/xhong/llfs_workdir/refinement/VQSR/gatk4100v2/c1joint_c1.snp.plots.R
> 13:10:10.758 INFO  VariantRecalibrator - Shutting down engine
> [April 17, 2019 1:10:10 PM CDT] org.broadinstitute.hellbender.tools.walkers.vqsr.VariantRecalibrator done. Elapsed time: 5.48 minutes.
> Runtime.totalMemory()=2298478592
> org.broadinstitute.hellbender.utils.R.RScriptExecutorException:
> Rscript exited with 1
> Command Line: Rscript -e tempLibDir = '/tmp/Rlib.4429476854635893449';source('/llfs_workdir/refinement/VQSR/gatk4100v2/c1joint_c1.snp.plots.
> R');
> Stdout:
> Stderr: Error in library(ggplot2) : there is no package called ‘ggplot2’
> Calls: source -> withVisible -> eval -> eval -> library
> Execution halted
>

Besides ggplot2, grid, and tools, any other R package I need? And also any instruction about R version and installation specified for GATK 4100 that I can follow?

**Comment by cmnbroad** [comment]
@imneuro The easiest thing to do is to use the GATK docker image, however, if you like you can install R and then run the R script found [here](https://github.com/broadinstitute/gatk/blob/master/scripts/docker/gatkbase/install_R_packages.R) to get the required R dependencies.

Also, these kinds of questions can be best handled by posting on the GATK forum - github issues are for bugs/feature requests.

**Comment by imneuro** [comment]
will do. Thank you

**Comment by marionamujal** [comment]
I have a similar issue with BaseRecalibator; i get the error message below; when I run the script below.
A USER ERROR has occurred: Invalid argument 'UGTB015-pe.sorted.marked_duplicates.bam'.
***********************************************************************
org.broadinstitute.barclay.argparser.CommandLineException: Invalid argument 'UGTB015-pe.sorted.marked_duplicates.bam'.
        at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.setPositionalArgument(CommandLineArgumentParser.java:600)
        at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.parseArguments(CommandLineArgumentParser.java:432)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:232)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:206)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)

`for sample in $(ls *-pe.sorted.marked_duplicates.bam | sed 's/-pe.sorted.marked_duplicates.bam//g' | sort | uniq);
do
echo $sample
gatk --java-options "-DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Xmx4g -Djava.io.tmpdir=`pwd`/tmpdir" BaseRecalibrator \
          -R $REF \
          -I ${sample}-pe.sorted.marked_duplicates.bam \
          --known-sites ${ref_dbsnp} \
          --known-sites ${ref_Mills_and_1000G} \
          --known-sites ${ref_1000G_phase1_snps} \
          -O ${sample}_recal_data.table

done
`

**Comment by cmnbroad** [comment]
I just noticed that this email was sent directly to me, rather than being
posted to the github ticket.

Anyway, this looks like a completely different issue than what was reported
in the original ticket - in this case, the parser thinks that
'UGTB015-pe.sorted.marked_duplicates.bam' is a positional argument, which
indicates that the command line being executed is not properly formed. I
suspect the shell code isn't working as you expect.
-Chris

**Comment by smeeta** [comment]
Please need help : 

I ran the script for VQSR 


gatk-4.2.0.0/gatk VariantRecalibrator\
    -V variants_sitesonly.vcf.gz\
  	-trust-all-polymorphic\
    -tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.5 -tranche 99.0 -tranche 97.0 -tranche 96.0 -tranche 95.0 -tranche 94.0 -tranche 93.5 -tranche 93.0 -tranche 92.0 -tranche 91.0 -tranche 90.0\
    -an FS -an ReadPosRankSum -an MQRankSum -an QD -an SOR -an DP\ 
    -mode INDEL\
    -max-gaussians 4\
    -resource:mills,known=false,training=true,truth=true,prior=12:Mills_and_1000G_gold_standard.indels.hg38.vcf.gz\
    -resource:axiomPoly,known=false,training=true,truth=false,prior=Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz\
    -resource:dbsnp,known=true,training=false,truth=false,prior=2:Homo_sapiens_assembly38.dbsnp138.vcf\
    -O cohort_indels.recal\
    --tranches-file cohort_indels.tranches

ERROR - >


A USER ERROR has occurred: Argument resource was missing: Argument 'resource' is required


Any help would be really great !

thank you
Smeeta

**Comment by cmnbroad** [comment]
@smeeta The command line syntax you're using is incorrect. Instead of this:

`-resource:mills,known=false,training=true,truth=true,prior=12:Mills_and_1000G_gold_standard.indels.hg38.vcf.gz`

use

`-resource:mills,known=false,training=true,truth=true,prior=12 Mills_and_1000G_gold_standard.indels.hg38.vcf.gz`

Note that I changed the last ":" to a space, right before the file name.

This repo is for bug reports and feature requests. In the future, please post this kind of question on the [GATK support forum](https://gatk.broadinstitute.org/hc/en-us/community/topics).
