### ISSUE TITLE
FeatureInputs with logical names thwart shell expansion of ~

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2200]
Because the filename doesn't occur at the beginning of a word when you use a logical name:

--arg aname:~/dir1/...

the ~ doesn't get expanded by the shell, so the command fails, and the resulting error message is confusing because we call file.getAbsolutePath() on the file object to create the exception, which prepends the current directory onto the (unexpanded, nonexistent) filename (see https://github.com/broadinstitute/gatk/issues/2199). If we can't fix the underlying problem we should try to improve the error message.

**Comment by droazen** [comment]
Closing this one -- this will be fixed by https://github.com/broadinstitute/gatk/issues/2473
