### ISSUE TITLE
MuTect2 should fail on BAMs with multiple samples

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#2203]
### Affected tool(s)

MuTect2
### Affected version(s)

version 3.6
### Description

A user reported that when he input a BAM file that has multiple sample names to MuTect2, the tool mseems to run fine but outputs an empty VCF. Because MuTect2 cannot run on multiple samples, there should be an error message that lets the user know he/she cannot have multiple samples in the BAM file.
#### Expected behavior

There should be an error message telling the user to input only single sample BAM files, and the run should fail.
#### Actual behavior

The tool runs to completion but outputs an empty VCF.

[Original Forum Post](http://gatkforums.broadinstitute.org/gatk/discussion/comment/33336#Comment_33336)
---

**Comment by davidbenjamin** [comment]
@chandrans Could you move this issue to gatk-protected and give it the Mutect2 label?

**Comment by chandrans** [comment]
Issue moved to [broadinstitute/gatk-protected #761](https://github.com/broadinstitute/gatk-protected/issues/761) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chandrans** [comment]
Simple to do! There is a move function that let me move the issue right over and close this :)
