### ISSUE TITLE
Pick a name for the arg parser + docs github project

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2207]
May not want "gatk" in the name, given that this project will be shared across GATK and Picard.

**Comment by droazen** [comment]
@vdauwera Suggestions?

**Comment by vdauwera** [comment]
Hm... `gammadoc` as a stand-in for `gatkdoc`? I know it's not just docs though... `commutils` for common/communication utilities? `paradoc` for parser and docs? But what if we expend to include other things...

**Comment by cmnbroad** [comment]
gammautils
userutils
uiutils
spockdoc

**Comment by vdauwera** [comment]
I grok spockdoc. Why is there no vulcan salute emoji on github? Sad!

Hmm, user/ui utils is a good connection to make. I was thinking from there, youtils but there are already github projects with that name. 

Utilosaur or utilosaurus? Everyone loves dinosaurs. 

multatuli -- An obscure dutch literary reference.

**Comment by cmnbroad** [comment]
The name with the most votes is "barclay".

**Comment by droazen** [comment]
(after the great http://memory-alpha.wikia.com/wiki/Reginald_Barclay, of course :)

Closing as resolved!

**Comment by vdauwera** [comment]
Wait there was a vote?

**Comment by droazen** [comment]
Yes, at our group meeting today

**Comment by lbergelson** [comment]
Sadly, Picargs was defeated in honorable democratic combat.

**Comment by vdauwera** [comment]
(sad that I didn't get invited to vote...)

Glad to hear that Picargs didn't survive.

**Comment by lbergelson** [comment]
HoloDoc didn't make it either :(

**Comment by vdauwera** [comment]
Whaaat I would have voted for holodoc
