### ISSUE TITLE
Copy Picard arg parser to arg parser repo as-is, and create mechanism to select it

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2212]
We likely want the mechanism to be a properties file loaded from the classpath, so that we can build jars that use the Picard arg parser by default.

**Comment by droazen** [comment]
The only change I hope we have to make in the copied version of the Picard arg parser is to rename `Option` to `Argument`

**Comment by droazen** [comment]
@cmnbroad Can this be closed?

**Comment by cmnbroad** [comment]
@droazen The PR isn't merged yet. We might want to remove the beta label though.

**Comment by droazen** [comment]
@cmnbroad But the Picard arg parser has been copied as-is to barclay, and there is a mechanism to select it, so isn't this ticket done?

**Comment by cmnbroad** [comment]
@droazen Maybe a technicality, but the "mechanism to select it" part is in the Picard PR, and that isn't merged yet.

**Comment by droazen** [comment]
@cmnbroad The part of this ticket that's not merged is already covered by https://github.com/broadinstitute/gatk/issues/2213, so I think we can close this one.
