### ISSUE TITLE
Make Picard depend on arg parser repo via maven, and create non-default build target to build jar that uses the old arg parsing system

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2213]

**Comment by droazen** [comment]
Will need to do the `Option` -> `Argument` migration in the Picard codebase as part of this.

**Comment by cmnbroad** [comment]
Closing via https://github.com/broadinstitute/picard/pull/897 (formerly known as https://github.com/broadinstitute/picard/pull/817).

**Comment by droazen** [comment]
Woohoo!
