### ISSUE TITLE
Walker-Spark Convergence

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#2217]
One of the benefits of the work in #1988 and #1558 is that the APIs for Walker and Spark tools are getting closer. For example, this branch shows how to create a Spark equivalents for each Walker class: https://github.com/broadinstitute/gatk/compare/tw_spark_walkers.

It is worth investigating whether the Spark and Walker code could be made to converge even more.

**Comment by tomwhite** [comment]
Here's a prototype showing one way of doing this: https://github.com/broadinstitute/gatk/commit/3cf7f9078b6aedcb87a4ca77c2aa8e84e7e5fe99.

The idea is that `GATKTool` has a `-spark` flag, so you can run a tool in Spark mode. The parallel `GATKSparkTool` hierarchy would disappear, and tool writers would optionally be able to support Spark as an alternative to the regular walker, by providing the relevant code in the same tool class. As an example, the `FlagStat` implementation looks like this:

```java
@Override
public void traverse() {
    if (sparkArgs.useSpark) {
        sum = getReadsRdd().aggregate(new FlagStatus(), FlagStatus::add, FlagStatus::merge);
    } else {
        sum = getReadsStream().collect(FlagStatus::new, FlagStatus::add, FlagStatus::merge);
    }
}
```

Note that the walker version uses the Java 8 Streams API, while the Spark version uses the RDD API. While these are different APIs, many of the concepts are similar, so it should be possible to share the underlying logic by encapsulating it in classes, in much the same way as is done by the `FlagStatus` class for `FlagStat`.

It would also be possible to keep the existing `apply` method for walker versions of tools that simply iterate over each record.

Removing the parallel `GATKSparkTool` hierarchy has a number of benefits, such as reducing duplication, making it easier for tool writers to add Spark support, and making it easier to share tests.

Thoughts? /cc @DR, @lbergelson, @cmnbroad

**Comment by cmnbroad** [comment]
I definitely like the idea of moving in this direction, and it will become more compelling as we extend the GATKSparkTool hierarchy, which is currently pretty flat and doesn't mirror the GATKTool hierarchy.

I think we should also consider using some of the concepts from the metrics refactoring, which introduces a layer that separates the implementation of the processing logic from the containing tool/driver, and allows a single implementation (i.e. metrics collector, but could be FlagStats, CuntReads, SelectVariants, whatever) to be independent of the source and/or destination of the data. It adds more moving parts, but has the advantage of allowing a single implementation to be used from any of Spark tool, standalone tool, Spark pipeline, standalone pipeline, etc.

**Comment by cmnbroad** [comment]
The existing Spark interface for metrics collectors is described [here](https://github.com/broadinstitute/gatk/blob/fc66240a1a382ad803b7f83ead612f65957a644e/src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/MetricsCollectorSpark.java). [Here](https://github.com/broadinstitute/gatk/blob/414cedf60d2041636f772658a6d04f470affb0f4/src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/metrics/QualityYieldMetricsCollectorSpark.java) is one implementation of that interface, which in turn just delegates to the actual "tool" logic component that is reused for all variations of the tool (Spark, standalone, CollectMultiple, etc).

**Comment by droazen** [comment]
@tomwhite I think the general goal of unifying the Spark/non-Spark tool hierarchies is worthwhile, but I don't like the idea of all tools having `if (sparkArgs.useSpark) {} else {}` boilerplate. If we do this, we should have separate abstract methods that get called automatically in the Spark/non-Spark cases.

I also think we should wait to perform this refactoring until later in the quarter, after the Spark evaluation, and after we've standardized more on `Path` for inputs/outputs, as it will break a lot of downstream code in gatk-protected -- and we don't want to break all the tools more than once if we can help it.

**Comment by tomwhite** [comment]
@droazen the `if (sparkArgs.useSpark) {} else {}` could definitely be improved - probably by using the technique @cmnbroad described for metrics.
