### ISSUE TITLE
PrintReadsSpark throws error "Invalid splitting BAM index" on writing BAM

### ISSUE THREAD

**Issue by mwalker174** [broadinstitute/gatk#2219]
I've run into an error using a certain BAM file I created for testing. Possibly relevant: I also tried running it through PrintReads - all reads were filtered out by the WellFormedReadFilter because they do not have read groups or base qualities.

[test_pathseq_unmapped.bam.zip](https://github.com/broadinstitute/gatk/files/537153/test_pathseq_unmapped.bam.zip)

> > ./gatk-launch PrintReadsSpark -I ~/Work/gatk/tests/test_pathseq_unmapped.bam -O ~/Work/gatk/tests/test_pathseq_unmapped.output.bam
> > Using GATK wrapper script /Users/markw/IdeaProjects/gatk/build/install/gatk/bin/gatk
> > Running:
> >     /Users/markw/IdeaProjects/gatk/build/install/gatk/bin/gatk PrintReadsSpark -I /Users/markw/Work/gatk/tests/test_pathseq_unmapped.bam -O /Users/markw/Work/gatk/tests/test_pathseq_unmapped.output.bam
> > 15:10:22.765 INFO  IntelGKLUtils - Trying to load Intel GKL library from:
> >     jar:file:/Users/markw/IdeaProjects/gatk/build/install/gatk/lib/gkl-0.1.2.jar!/com/intel/gkl/native/libIntelGKL.dylib
> > 15:10:22.790 INFO  IntelGKLUtils - Intel GKL library loaded from classpath.
> > [October 18, 2016 3:10:22 PM EDT] org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark  --output /Users/markw/Work/gatk/tests/test_pathseq_unmapped.output.bam --input /Users/markw/Work/gatk/tests/test_pathseq_unmapped.bam  --readValidationStringency SILENT --interval_set_rule UNION --interval_padding 0 --interval_exclusion_padding 0 --bamPartitionSize 0 --disableSequenceDictionaryValidation false --shardedOutput false --numReducers 0 --sparkMaster local[*] --help false --version false --verbosity INFO --QUIET false --use_jdk_deflater false --disableAllReadFilters false
> > [October 18, 2016 3:10:22 PM EDT] Executing as markw@WMC9F-819 on Mac OS X 10.11.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_91-b14; Version: Version:4.alpha.1-318-gcdc484c-SNAPSHOT
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.BUFFER_SIZE : 131072
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.COMPRESSION_LEVEL : 1
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.CREATE_INDEX : false
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.CREATE_MD5 : false
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.CUSTOM_READER_FACTORY :
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.EBI_REFERENCE_SERVICE_URL_MASK : http://www.ebi.ac.uk/ena/cram/md5/%s
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.NON_ZERO_BUFFER_SIZE : 131072
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.REFERENCE_FASTA : null
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.SAM_FLAG_FIELD_FORMAT : DECIMAL
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
> > 15:10:22.793 INFO  PrintReadsSpark - Defaults.USE_CRAM_REF_DOWNLOAD : false
> > 15:10:22.794 INFO  PrintReadsSpark - Deflater IntelDeflater
> > 15:10:22.794 INFO  PrintReadsSpark - Initializing engine
> > 15:10:22.794 INFO  PrintReadsSpark - Done initializing engine
> > 15:10:23.180 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> > 15:10:25.800 INFO  PrintReadsSpark - Shutting down engine
> > [October 18, 2016 3:10:25 PM EDT] org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark done. Elapsed time: 0.05 minutes.
> > Runtime.totalMemory()=467140608
> > org.broadinstitute.hellbender.exceptions.GATKException: unable to write bam: java.io.IOException: Invalid splitting BAM index: should contain at least 1 offset and the file size
> >     at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.writeReads(GATKSparkTool.java:252)
> >     at org.broadinstitute.hellbender.tools.spark.pipelines.PrintReadsSpark.runTool(PrintReadsSpark.java:35)
> >     at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:348)
> >     at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
> >     at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:109)
> >     at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:167)
> >     at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:186)
> >     at org.broadinstitute.hellbender.Main.instanceMain(Main.java:76)
> >     at org.broadinstitute.hellbender.Main.main(Main.java:92)

**Comment by droazen** [comment]
@mwalker174 If the reads in your bam are failing `WellFormedReadFilter`, then the GATK (generally speaking) can't handle them. Reads must pass at least that filter in order to be usable by GATK. Are you able to modify the bam to add read groups, etc., to allow the bam to pass the filter? If not, it is theoretically possible to disable `WellFormedReadFilter`, but I don't recommend it...

**Comment by droazen** [comment]
@tomwhite Can you comment on the "Invalid splitting BAM index: should contain at least 1 offset" error? Is this what we get when trying to write an empty bam (because all the reads have been filtered)? If so, we should probably fix this.

**Comment by mwalker174** [comment]
@droazen Yes I will just modify the BAM so it will pass the filter.

**Comment by droazen** [comment]
Assigning to @tomwhite to determine if this is still an issue.

**Comment by mwalker174** [comment]
This also happens when there are more reducers than reads such that at least one reducer writes an empty split bam.

**Comment by tomwhite** [comment]
@droazen @mwalker174 I've verified that this is due to writing an empty split BAM. I've opened https://github.com/HadoopGenomics/Hadoop-BAM/issues/138 and https://github.com/HadoopGenomics/Hadoop-BAM/pull/139 to fix the problem.

**Comment by droazen** [comment]
This should be fixed in Hadoop-BAM 7.9.0, which we're currently on ( @tomwhite correct me if I'm wrong). Closing.
