### ISSUE TITLE
VariantRecalibrator should throw an error when an annotation is specified twice

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#2221]
### Tool(s) involved

VariantRecalibrator
### Description

A user reported he gets an `##### ERROR MESSAGE: No data found.` from VariantRecalibrator when running with -an MQ twice. There should be a check for this and an error message letting the user know he/she has specified the same annotation twice. 

[Original Forum Post](http://gatkforums.broadinstitute.org/gatk/discussion/comment/33592#Comment_33592)

---

**Comment by droazen** [comment]
Has this bug been replicated in GATK4?

**Comment by chandrans** [comment]
No. Can I use /humgen/gsa-hpprojects/GATK/gatk4/gatk4-latest/gatk-protected.jar to test it?

**Comment by droazen** [comment]
As discussed in person, you should build the latest master rather than using that jar.

**Comment by ldgauthier** [comment]
This was, in fact, a problem, even in the latest version.  If dupes are specified, I'm just going to clean 'em up.
