### ISSUE TITLE
Write a tool to add a sequence dictionary to a VCF

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2222]
The tool should take a VCF plus a source of a sequence dictionary (eg., a fasta reference, a bam, a `.dict` file, or another VCF that already has a dictionary), and add the sequence dictionary to the VCF.

**Comment by droazen** [comment]
For @cmnbroad and alpha-4.

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/2234.
