### ISSUE TITLE
Implement a --minimal_header option

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#2233]
### Tool(s) involved

Engine
### Description

An ENUM with several levels of minimalism. Main use case: keeping down the lines of SQ.

As put by @eitanbanks  

> One thing that option would do would be to _not_ print out all of the reference contigs.  While it's not terrible in b37, you should know that hg38 has thousands upon thousands of contigs and it's such a pain to have them all in the header.

Simplest way to do this imho (and I would advocate making it the default GATK behavior): write to VCF header SQ lines representing only the contigs for which we have calls.

More discussion needed to define exactly what options should distinguished.

**Comment by fleharty** [comment]
@vdauwera Would this option only output SQ lines that are represented, or are there other things that could be removed?

**Comment by vdauwera** [comment]
Good question, there might have to be degrees of removal. There could be an EXTREME option that removes everything not required by the spec (technically annotation definitions are not required) and a REASONABLE option that just removes the SQ and anything else that we don't care much about (to be defined through discussion). Option names are negotiable of course.

**Comment by fleharty** [comment]
@vdauwera Would it be reasonable to implement --minimal_header REASONABLE that removes SQ that we don't use, and leave other options like EXTREME for later?

**Comment by vdauwera** [comment]
Absolutely, if you can write it in a way that makes it extensible, that seems perfectly... REASONABLE ;)

**Comment by lbergelson** [comment]
What's the plan to implement this?  We typically write the header before we know what the calls are going to be.

**Comment by vdauwera** [comment]
I think for SQ you could limit the lines you write out to the contigs that are covered in your intervals list, ignore the rest. So you can access that info as soon as you've parsed the command line. Or if you're running without an intervals list you could supply a seq dict file through a separate arg. But the former seems safer. 

For other modes: EXTREME would hardcode what we consider required. Then you could potentially do ARBITRARY to allow passing strings for specific attributes that you want to drop. 

None of these would have to depend on what's in the calls, I think.

**Comment by fleharty** [comment]
@lbergelson Since we write the header before we know the calls, I imagine this will be fairly difficult to implement, yes?  I certainly wouldn't want to make the calls, and then go back to the header and delete things that had already been written to disk.

**Comment by vdauwera** [comment]
*I don't think we need to rely on the calls to decide what should be in the header...*

**Comment by fleharty** [comment]
@vdauwera We may not have to rely on the calls, but we would definitely need to figure out the intervals (which I assume is done) before writing out the header.

**Comment by vdauwera** [comment]
Oh sure, that we do. I do think taking them from an intervals file is the right way to do it.

**Comment by ldgauthier** [comment]
I've done a bunch of cleanup to get rid of extraneous annotation header lines and GVCF block definitions, but I don't want to mess with the sequence dictionary.  The contig lines should be a small percentage of the total data. This is only an issue if you're running `less` on VCFs, which you really shouldn't be doing.  Either `grep ^[^#]` or use a real tool.
