### ISSUE TITLE
Improve how pairs of overlapping mates are handled by ReadUtils

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#2238]
Stems from https://github.com/broadinstitute/gsa-unstable/issues/1406. Unless something changed in the port from GATK3 to GATK4, this is how pairs of overlapping mates are handled by ReadUtils when a tool seeks to determine adaptor boundaries:

<img src="http://cd8ba0b44a15c10065fd-24461f391e20b7336331d5789078af53.r23.cf1.rackcdn.com/gatk.vanillaforums.com/FileUpload/41/48ae8ddb4ba74d5a02310b75135347.png" align="right" height="45"/> When inserts are small such that mapped mates overlap, we clip off the non-overlapping regions based on the assumption that they are adapter sequence. 

@ldgauthier suggests that this is a dumb way to handle them because "there will be cases where the reads overlap, but don't yet read into the adapter and we're throwing away data".

The task here is to propose and implement a better way to do this. If this code is no longer used in GATK4, please point out by what it has been replaced.

**Comment by ronlevine** [comment]
Close since #1406 is merged.
