### ISSUE TITLE
Remove VQSR gatk3Compatibility argument when VQSR qualification is complete

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2240]
A temporary gatk3Compatibility argument was introduced in [this branch](https://github.com/broadinstitute/gatk/pull/2182) branch to help with https://github.com/broadinstitute/gatk/issues/2065. When #2065 is closed, this argument should be removed.

**Comment by droazen** [comment]
@cmnbroad Since https://github.com/broadinstitute/gatk/issues/2065 is now closed, we should be able to do this one.

**Comment by droazen** [comment]
@cmnbroad Could you remove this argument for beta?
