### ISSUE TITLE
SparkSharder: ensure robustness in the face of areas of high coverage

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2251]
We need to make sure the `SparkSharder` can handle coverage spikes. We should profile to see how it performs in regions of high coverage, and potentially come up with a partition-level downsampling strategy that could discard partitions with extraneous coverage.

**Comment by droazen** [comment]
For @tomwhite

**Comment by tomwhite** [comment]
This is being addressed by the downsampling code in #3106

**Comment by tomwhite** [comment]
Fixed in #3106
