### ISSUE TITLE
Eliminate the old ExactAFCalculator QUAL score

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#2255]
First, question: what must we do to convince ourselves to pull the plug on the old QUAL?  In every test so far, the new model performs equally well on biallelics and better on multiallelics.  We will eliminate about 6000 lines of code, many future bugs, and GATK workshop slides that nobody wants to present.

Assuming that we are soon convinced, the ticket is pretty simple: delete every implementation of `AFCalculator` and replace anything that calls for an abstract `AFCalculator` with the concrete class `AlleleFrequencyCalculator`.  Then clean up hacky parts of `AlleleFrequencyCalculator` that were put in to implement `AFCalculator`.  Finally, delete all the ancillary classes like `StateTracker` that comprised the `AFCalculator`'s military-industrial complex.

**Comment by vdauwera** [comment]
I support ripping out every old crappy thing that we're sure we're not going to want to use in GATK4.  I would however suggest that this one NOT get back ported to 3.x -- just leave things there as a museum of horrors.

**Comment by davidbenjamin** [comment]
For various reasons that backport would be too awful to contemplate even if we wanted to backport.  The question remains for GATK4 whether we want to preserve the old qual in case there's some edge case where it performs better.  I consider this highly unlikely but others might disagree.

**Comment by vdauwera** [comment]
Ah, I thought that might be the case, to be honest. 

My vote is for ripping out the old. If for whatever reason you find an edge case where the new doesn't perform as well, then in my view that just means the new can be improved. 

Ultimately it seems to me that @ldgauthier is the one with the most experience in this space and should make the call.

**Comment by davidbenjamin** [comment]
@droazen Should this wait for the `HaplotypeCaller` port's completion?  What about `VQSR`?

**Comment by ldgauthier** [comment]
@davidbenjamin Just to confirm, you mean not backporting the removal/cleanup right?

**Comment by davidbenjamin** [comment]
Correct, I don't expect to backport any *more* code to GATK3 unless we find a bug in the new qual.  However, the new qual, including the recent numerical stability patch is fully backported.

**Comment by lh3** [comment]
I would say the proof is that we can do low-cov joint calling well with the new model. Although we are not doing such sequencing any more at Broad, some GATK users might do. Killing features should be taken with great caution.

**Comment by vdauwera** [comment]
We're going to release the new model in 3.7 and have users test-drive that for quite a bit before we move to release 4.0, so we should be able to get some feedback on performance in the wild before we need to make any final decisions.

**Comment by davidbenjamin** [comment]
@lh3 We agree about the low-cov joint calling and have already tested it on 191 low-coverage (roughly 3-4x) samples from 1kg.  The calls were identical except for one site with qual just above 30 that used to be just below, but this difference is basically arbitrary.  If we simply add 15 to the qual threshold (as we should, because the new qual is systematically more permissive due to learning a minor allele fraction that may be greater than the average genome-wide heterozygosity), results are completely identical.

**Comment by lh3** [comment]
Thanks. This sounds good to me!

**Comment by vruano** [comment]
I vote for remove and move on.

**Comment by droazen** [comment]
@davidbenjamin I think we should wait to rip out the old code until the GATK4 port of `HaplotypeCaller` has been tied-out against GATK3 by Palantir. This is scheduled to happen this month, so I would say early December would be a good time to kill the old code.

**Comment by davidbenjamin** [comment]
@vdauwera any feedback from GATK 3.7 users? @droazen how's the Palantir tie-out doing?

**Comment by vdauwera** [comment]
Users have commented on speed increases (with happiness) but not yet on the new QUAL. Note that Dec-to-Jan tends to be a dead zone, so probably not many people have had the opportunity to look at it closely.
