### ISSUE TITLE
New truth assessment walker

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#2267]
We want a new, more general truth assessment walker to replace AssessNA12878 and also be able to be run on the synthetic diploid truth data.

The walker should take in two VCFs, one of which is the truth (true positives only?) and one of which is the eval, and an optional confidence region describing territory where any eval calls not in truth are assumed to be false positives. Output could be a table giving the number of true positives called, false negatives called, false positives called (if confidence region is provided) and total bases evaluated.  Should be stratified by SNPs and indels.  Filters should be taken into account and there should be a way to specify a sample of interest and ignore its monomorphic sites.  Alleles must be matched.  Some users might be interested in a "lenient mode" similar to Heng's distEval script where alleles don't need to be matched and a call within +/- Xbp of a truth event is considered a true positive.  I have no interest in allowing BAM input or having the tool apply "reasonable filters", as for AssessNA12878.

This should work with the NIST GiaB data (truth VCF + confidence BED) and the synthetic diploid data (also truth VCF + confidence BED).  A mode to take in a snapshot VCF of the NA12878KB would be desirable for backward compatibility.

**Comment by davidbenjamin** [comment]
@ldgauthier A very similar issue, broadinstitute/gatk-protected#795, is currently assigned to me as part of our quarterly goals and I'm doing it this week.  The Mutect version ought to be very similar to the HaplotypeCaller version.  I can't promise that it will be the Cadillac of concordance tools but it will be a good start.  Do you mind if I take this one?

**Comment by ldgauthier** [comment]
Great!  I can't remember if I wrote up the design requirements somewhere, but they're simple.  The only non-obvious thing is to take a "high-confidence" interval list where we assume anything not in the truth is a false positive (as in NIST GiaB).  Might also be useful for DREAM, but I don't remember the details of how that truth data is represented.

**Comment by takutosato** [comment]
I inherited broadinstitute/gatk-protected#795 from @davidbenjamin.

**Comment by davidbenjamin** [comment]
Closed by @takutosato in broadinstitute:gatk-protected#922
