### ISSUE TITLE
Ensure full GATK command lines are added to BAM/VCF headers

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2269]
GATK3 had a feature that automatically added the full command line to BAM/VCF headers. We're going to need to port this code and hook up to our tools via the standardized output writer creation methods.

The VCF header lines look like this:

```
##GATKCommandLine.SelectVariants=<ID=SelectVariants,Version=3.4-46-gbc02625,Date="Wed Aug 19 10:29:53 EDT 2015",Epoch=1439994593766,CommandLineOptions="analysis_type=SelectVariants input_file=[] showFullBamList=false read_buffer_size=null phone_home=AWS gatk_key=null tag=NA read_filter=[] disable_read_filter=[] intervals=[20:10000000-10250000, 21:10000000-10250000] excludeIntervals=null interval_set_rule=UNION interval_merging=ALL interval_padding=0 reference_sequence=human_g1k_v37.fasta nonDeterministicRandomSeed=false disableDithering=false maxRuntime=-1 maxRuntimeUnits=MINUTES downsampling_type=BY_SAMPLE downsample_to_fraction=null downsample_to_coverage=1000 baq=OFF baqGapOpenPenalty=40.0 refactor_NDN_cigar_string=false fix_misencoded_quality_scores=false allow_potentially_misencoded_quality_scores=false useOriginalQualities=false defaultBaseQualities=-1 performanceLog=null BQSR=null quantize_quals=0 disable_indel_quals=false emit_original_quals=false preserve_qscores_less_than=6 globalQScorePrior=-1.0 validation_strictness=SILENT remove_program_records=false keep_program_records=false sample_rename_mapping_file=null unsafe=null disable_auto_index_creation_and_locking_when_reading_rods=false no_cmdline_in_header=false sites_only=false never_trim_vcf_format_field=false bcf=false bam_compression=null simplifyBAM=false disable_bam_indexing=false generate_md5=false num_threads=1 num_cpu_threads_per_data_thread=1 num_io_threads=0 monitorThreadEfficiency=false num_bam_file_handles=null read_group_black_list=null pedigree=[] pedigreeString=[] pedigreeValidationType=STRICT allow_intervals_with_unindexed_bam=false generateShadowBCF=false variant_index_type=DYNAMIC_SEEK variant_index_parameter=-1 logging_level=INFO log_to_file=null help=false version=false variant=(RodBinding name=variant source=dbsnp_138.b37.vcf) discordance=(RodBinding name= source=UNBOUND) concordance=(RodBinding name= source=UNBOUND) out=/home/unix/droazen/bundle_snippets/dbsnp_138.b37.20.21.vcf sample_name=[] sample_expressions=null sample_file=null exclude_sample_name=[] exclude_sample_file=[] exclude_sample_expressions=[] selectexpressions=[] invertselect=false excludeNonVariants=false excludeFiltered=false preserveAlleles=false removeUnusedAlternates=false restrictAllelesTo=ALL keepOriginalAC=false keepOriginalDP=false mendelianViolation=false invertMendelianViolation=false mendelianViolationQualThreshold=0.0 select_random_fraction=0.0 remove_fraction_genotypes=0.0 selectTypeToInclude=[] selectTypeToExclude=[] keepIDs=null excludeIDs=null fullyDecode=false justRead=false maxIndelSize=2147483647 minIndelSize=0 maxFilteredGenotypes=2147483647 minFilteredGenotypes=0 maxFractionFilteredGenotypes=1.0 minFractionFilteredGenotypes=0.0 setFilteredGtToNocall=false ALLOW_NONOVERLAPPING_COMMAND_LINE_SAMPLES=false filter_reads_with_N_cigar=false filter_mismatching_base_and_quals=false filter_bases_not_stored=false">
```

The BAM header lines look something like this (may have changed slightly in more recent versions):

```
@PG	ID:GATK IndelRealigner	VN:1.2-573-g821421d	CL:knownAlleles=[(RodBinding name=knownAlleles source=/humgen/gsa-hpprojects/GATK/data/Comparisons/Validated/dbSNP/dbsnp_132_b37.leftAligned.vcf), (RodBinding name=knownAlleles2 source=/humgen/1kg/processing/official_release/phase1/projectConsensus/ALL.wgs.projectConsensus_v2b.20101123.snps.sites.vcf), (RodBinding name=knownAlleles3 source=/humgen/gsa-hpprojects/GATK/data/Comparisons/Unvalidated/AFR+EUR+ASN+1KG.dindel_august_release_merged_pilot1.20110126.sites.vcf)] LODThresholdForCleaning=5.0 consensusDeterminationModel=USE_READS entropyThreshold=0.15 maxReadsInMemory=150000 maxIsizeForMovement=3000 maxPositionalMoveAllowed=200 maxConsensuses=30 maxReadsForConsensuses=120 maxReadsForRealignment=20000 noOriginalAlignmentTags=false nWayOut=null generate_nWayOut_md5s=false check_early=false noPGTag=false keepPGTags=false indelsFileForDebugging=null statisticsFileForDebugging=null SNPsFileForDebugging=null
```

We don't need to replicate the formatting of these -- we can just have the raw command line as a String for both headers, along with tool name and version number.

**Comment by droazen** [comment]
For @cmnbroad

**Comment by droazen** [comment]
@cmnbroad This is another one we should do sooner rather than later. I think all we need is a method in barclay to give you the full command line as a String (if there isn't such a method already), and a method in GATK4 to add the command line String to a BAM or VCF header along with tool + version number. Once we have that, we can determine how and where this method should be invoked.

**Comment by cmnbroad** [comment]
Ok. There is a method on the CLP called getCommandLine, but it reconstructs the command line from the actual values, so it includes all argument values, even defaults that were not specified.

**Comment by droazen** [comment]
@cmnbroad I think that might actually be better than just capturing the user's command line, so that the tool defaults not explicitly specified by the user can be recorded (in case they change over time).

**Comment by magicDGS** [comment]
`CommandLineProgram` stores the information of the command line that @cmnbroad mention in the `defaultHeaders`. This may be useful.

Nevertheless, I found a problem regarding this String and I don't know if this is going to be an issue here or in Barclay. The String returned can't be reused to re-run the analysis, because it includes also mutex arguments that are not allowed. I try to copy the command line [reported in the System.err](https://github.com/broadinstitute/gatk/blob/9d82097641f160e00fa1ef4236d9bcdccbfa38b0/src/main/java/org/broadinstitute/hellbender/cmdline/CommandLineProgram.java#L146-L147) to re-run a test in the command line and it blows up if there are some mutex arguments.

**Comment by cmnbroad** [comment]
There is an existing method in GATKTool called getHeaderForSAMWriter that creates and populates the PG record, and it's called by GATKTool.createSAMWriter, so we already do this for BAMs that are created that way (which excludes the Picard tools). We should probably fix MarkDuplicates though.

HaplotypeCaller and Mutect2 use HaplotypBAMWriter/SAMFileDestination/HaplotypeBAMDestination, all of which live in gatk, but create their own writers directly, so they need to be updated (and could probably be simplified a bit).

We need a similar method for vcf header lines.

**Comment by droazen** [comment]
@cmnbroad Is this done? Can we close this?

**Comment by cmnbroad** [comment]
The only remaining (non-Picard) tool output that doesn't have this is the HC bamout and my understanding is its not required for that. Closing via https://github.com/broadinstitute/gatk/pull/2716 and https://github.com/broadinstitute/gatk-protected/pull/1115.
