### ISSUE TITLE
VQSR sometimes outputs repeats of tranches

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2276]
GATK4 in some cases outputs the first and last tranches twice in its tranche file and this leads to an extra line in the output file as well. This was reported as part of the tieout, i.e. for this test case:

gatk-launch VariantRecalibrator \
 --variant /seq/dax/ExAc2/Exome/v2/sites_only_combined/chr1.sites_only.unfiltered.vcf.gz \
 --resource mills,known=false,training=true,truth=true,prior=12:/seq/references/Homo_sapiens_assembly19/
 --resource axiom,known=false,training=true,truth=false,prior=10:/seq/references/Homo_sapiens_assembly19
 --resource dbsnp138,known=true,training=false,truth=false,prior=2:/seq/references/Homo_sapiens_assembly
 -an QD -an MQRankSum -an ReadPosRankSum -an FS -an SOR \
 -tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.8 -tranche 99.6 -tranche 99.5 -tranche 99.4 -tr
 -trustAllPolymorphic \
 --output results/recal4_indel_exome.vcf \
 -mode INDEL \
 -tranchesFile results/recal4_indel_exome.txt \
 --gatk3Compatibility

**Comment by lucidtronix** [comment]
I think the tranches arguments got truncated in the command line above.  Here is one that causes the issue:

gatk-launch VariantRecalibrator \
--variant /seq/dax/ExAc2/Exome/v2/sites_only_combined/chr1.sites_only.unfiltered.vcf.gz \
--resource mills,known=false,training=true,truth=true,prior=12:/seq/references/Homo_sapiens_assembly19/v1/variant_calling/vqsr_resources/WGS/v2/Mills_and_1000G_gold_standard.indels.b37.vcf.gz \
--resource axiom,known=false,training=true,truth=false,prior=10:/seq/references/Homo_sapiens_assembly19/v1/variant_calling/vqsr_resources/WGS/v2/Axiom_Exome_Plus.genotypes.all_populations.poly.vcf.gz \
--resource dbsnp138,known=true,training=false,truth=false,prior=2:/seq/references/Homo_sapiens_assembly19/v1/variant_calling/vqsr_resources/WGS/v2/dbsnp_138.b37.vcf.gz \
-an QD -an MQRankSum -an ReadPosRankSum -an FS -an SOR \
-tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.8 -tranche 99.6 -tranche 99.5 -tranche 99.4 -tranche 99.3 -tranche 99.0 -tranche 98.0 -tranche 97.0 -tranche 90.0 \
-trustAllPolymorphic \
--output results/recal4_indel_exome.vcf \
-mode INDEL \
-tranchesFile results/recal4_indel_exome.txt \
--gatk3Compatibility

**Comment by cmnbroad** [comment]
@lucidtronix The duplicate tranches are caused by a command line parser bug that appends the user-specified tranches with the default ones; any tranche that overlaps is output twice (and thats fixed in the build as of yesterday). However, you mentioned that you saw an extra line in the output file. I don't see any reason that the tranches should affect that, and I don't see it happening in my (smaller) test cases, so I just want confirm that what you were seeing was an extra line in the actual output vcf ?

**Comment by lucidtronix** [comment]
I noticed an extra line in the final output vcf, the one produced by ApplyVQSR.  For example a command line like:

gatk-launch ApplyVQSR --variant /seq/dax/ExAc2/Exome/v2/sites_only_combined/chr1.sites_only.unfiltered.vcf.gz --ts_filter_level 99.0 -tranchesFile results/recal4_indel_exome.txt -recalFile results/recal4_indel_exome.vcf -mode INDEL -O results/exome_recalibrated4_indel.vcf


The output file results/exome_recalibrated4_indel.vcf had extra lines. I did not see extra lines in the recal vcf that is output by VQSR.  My guess is that if it is fixed in the generation of the tranches file then ApplyVQSR output would be fine as well.

**Comment by cmnbroad** [comment]
I see whats going on now - I had been assuming that the extra lines were variant records, but they're just extra filter metadata lines resulting from the bogus tranches. So, the actual fix for this was https://github.com/broadinstitute/gatk/pull/2275. I'm closing this ticket out and will add a separate PR with an integration test that uses multiple tranches so we don't regress.
