### ISSUE TITLE
Change default value of STANDARD_CONFIDENCE_FOR_CALLING to 10

### ISSUE THREAD

**Issue by ronlevine** [broadinstitute/gatk#2278]
Port https://github.com/broadinstitute/gsa-unstable/pull/1511.

**Comment by droazen** [comment]
I'll take this one, since it's needed for @lbergelson 's current work, and since the HC tests will likely be affected.

**Comment by droazen** [comment]
@lbergelson will do the public PR, and I'll take the protected half after it's merged.

**Comment by lbergelson** [comment]
Closed by #2521
