### ISSUE TITLE
MuTect2 VCF should have sample names instead of "Tumor" and "Normal"

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#2291]
### Tool(s) involved

MuTect2

### Description

User would like MuTect2 VCF to have the sample names in the header instead of TUMOR and NORMAL. For example, if the normal sample name is Sample1 and the tumor sample name is Sample2, the VCF header should show those names.  

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/gatk/discussion/comment/34612#Comment_34612

**Comment by vdauwera** [comment]
We need to put some more thought into what form this should take. How exactly do we want to encode this information? 

Right now we have (a)

    #CHROM POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  TUMOR   NORMAL

So would we want to change that to this? (b)

    #CHROM POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  sample1   sample2

Or would we want to make it look like e.g. this for maximal clarity? (c)

    #CHROM POS ID  REF ALT QUAL    FILTER  INFO    FORMAT  T-sample1   N-sample2

Or just add an informational note line elsewhere in the VCF header, like this? (d)

    ##samples=<TUMOR="sample1",NORMAL="sample2">

Or a combination of d + a, b or c?

**Comment by vdauwera** [comment]
@davidbenjamin

**Comment by davidbenjamin** [comment]
@vdauwera Going with b + d.  PR submitted:  broadinstitute/gatk-protected#858.

**Comment by vdauwera** [comment]
Great, that is the form I find most pleasing functionally and aesthetically!

**Comment by vdauwera** [comment]
I've notified the user, btw.

**Comment by davidbenjamin** [comment]
@vdauwera -- just to be clear, this is only in GATK 4 M2, which is pre-release (but we're working as fast as we can).

**Comment by vdauwera** [comment]
Yep, that's great, thank you!

**Comment by davidbenjamin** [comment]
closed in broadinstitute/gatk-protected#858
