### ISSUE TITLE
Fisher Exact Test Edge Case

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/gatk#2292]
Fisher's Exact Test fails for the following two unit tests (that should be added to the data provider in `FisherExactTestUnitTest.java`):

```
tests.add(new Object[]{0, 0, 0, 3,                     1.0});
tests.add(new Object[]{9, 0, 0, 0,                     1.0});
```

R's implementation results in 1.0 for both of these tables, but the current GATK implementation results in 0.0 for both of them. They are examples of an edge case when the observed table is the only possibility given the marginal distributions (so the p-value should be 1).

**Comment by lbergelson** [comment]
@meganshand Would you be willing to patch this one?

**Comment by meganshand** [comment]
Yeah, I'll try to look at it on Friday.

**Comment by lbergelson** [comment]
No rush!  Just wondering if you could take a look.
