### ISSUE TITLE
MuTect2 Outputs Odd Allele Frequencies

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#2295]
### Affected tool(s)
Mutect2

### Affected version(s)
3.6

### Description 
The AF field of MuTect2 is unpredictable depending on the input interval. For example, if I run with `-L chr7:140452736-140453536`, I get this at one site:
`chr7	140453136	.	A	T	.	PASS	ECNT=1;HCNT=27;MAX_ED=.;MIN_ED=.;NLOD=239.30;TLOD=243.81	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/1:1489,145:0.049:69:76:0.524:45565,4764:771:718	0/0:1094,0:0.00:0:0:.:34322,0:549:545`
But, if I run with `-L chr7:140452836-140453436`, I get this at the same site:
`chr7	140453136	.	A	T	.	PASS	ECNT=1;HCNT=15;MAX_ED=.;MIN_ED=.;NLOD=239.98;TLOD=245.96	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/1:1489,144:0.092:69:75:0.521:45567,4730:770:719	0/0:1097,0:0.00:0:0:.:34389,0:551:546`
Notice the major difference in AF between the two runs. Side  note, the AF does not equal the alt count / (alt count + ref count)?

#### Steps to reproduce
Test files here:
`/humgen/gsa-scr1/schandra/micknudsen_MuTect2AF/bugreport_AF`

Command for interval size of 600:
`java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T MuTect2 -R /humgen/gsa-hpprojects/GATK/bundle/2.8/hg19/ucsc.hg19.fasta -I:normal /humgen/gsa-scr1/schandra/micknudsen_MuTect2AF/bugreport_AF/normal_chr7.12.bam -I:tumor /humgen/gsa-scr1/schandra/micknudsen_MuTect2AF/bugreport_AF/tumor_chr7.12.bam -o Sheila.MuTect2.vcf -L chr7:140452836-140453436

Command for interval size of 800:
`java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T MuTect2 -R /humgen/gsa-hpprojects/GATK/bundle/2.8/hg19/ucsc.hg19.fasta -I:normal /humgen/gsa-scr1/schandra/micknudsen_MuTect2AF/bugreport_AF/normal_chr7.12.bam -I:tumor /humgen/gsa-scr1/schandra/micknudsen_MuTect2AF/bugreport_AF/tumor_chr7.12.bam -o Sheila.MuTect2.400.vcf -L chr7:140452736-140453536`

----

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/gatk/discussion/comment/33762#Comment_33762

**Comment by vdauwera** [comment]
@chandrans MuTect2 is in the gatk-protected repo, so I believe issues should go there rather than here.

**Comment by chandrans** [comment]
Issue moved to [broadinstitute/gatk-protected #812](https://github.com/broadinstitute/gatk-protected/issues/812) via [**ZenHub**](https://www.zenhub.com/)
