### ISSUE TITLE
bwaspark fails at the chunk boundary

### ISSUE THREAD

**Issue by zhipan** [broadinstitute/gatk#2296]
Running GATK4 BwaSpark encounter the following fatal error message:
`[M::mem_sam_pe] Paired reads have different names: "206B4ABXX100825:7:66:2632:21260", "206B4ABXX100825:7:66:2632:31752"`

Script: 
`$GATK_LAUNCH BwaSpark -I $unsorted_bam_hdfs -O $sorted_bam_hdfs -t 10 --disableSequenceDictionaryValidation true -R $ref_hdfs -K 10000000 -- --sparkRunner SPARK --sparkMaster yarn --num-executors 1 --executor-cores 10 --executor-memory 40g`

$unsorted_bam_hdfs is a file generated by FastqToBam, and copied to HDFS. 
spark 2.0 is used. 

The original Fastq files are perfectly fine, and we have been using it for all our tests using previous versions, including 3.6. I also manually checked the generated name-sorted BAM file generated by FastToBam, and the neighboring lines are perfectly paired as well. 

What I suspect is that chunk is cut inside a pair, and thus not just this one, all subsequent lines are all error'ed out. To confirm this, I ran the job with different  -K and -bps options, and the error will occur at different locations.

**Comment by zhipan** [comment]
Anyone?? I think this is a very serious bug... Thanks...

**Comment by vdauwera** [comment]
We will discuss this in the forum, thank you. If we need a work ticket for the dev team we will create one ourselves.
