### ISSUE TITLE
Add test covering --missingValuesInExpressionsShouldEvaluateAsFailing in VariantFiltration

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2303]
GATK3 has such a test, we should either port it or write a new one.

**Comment by droazen** [comment]
For @ronlevine

**Comment by vdauwera** [comment]
@SHuang-Broad should be involved in this

**Comment by droazen** [comment]
Added @SHuang-Broad as co-assignee.

**Comment by ronlevine** [comment]
I created a test on the `rhl_test_vf_missing_expression_values` branch.

**Comment by ronlevine** [comment]
Closing since #2323 is merged.
