### ISSUE TITLE
Port VariantFiltration/JEXL fix from GATK3

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#2308]
See https://github.com/broadinstitute/gsa-unstable/pull/1533

Partial fix related to buggy htsjdk implementation of JEXL matching

**Comment by droazen** [comment]
Assigning to @vdauwera to ensure that this gets ported before 4.0

**Comment by ronlevine** [comment]
@vdauwera Should I implement this?

**Comment by vdauwera** [comment]
Ah no we should just give them direct access to our dev repo. Will do now. Thanks though @ronlevine

**Comment by vdauwera** [comment]
Aaaaand just ignore what I said, wrong thread. Yes please do.
