### ISSUE TITLE
Possible bug in ReadLikelihoods.bestAlleles methods?

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#2311]
I'm using the `ReadLikelihoods` in a test and I'm setting the likelihoods to negative values. Nevertheless, when I'm trying to get the best alleles for each read using the `bestAlleles()` method, it turns out to return the allele where I haven't set any likelihood (by default, 0).

I think that the bug is in the private method [`searchBestAllele`](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/utils/genotyper/ReadLikelihoods.java#L438), were if the candidate likelihood is __bigger than__ the best likelihood, the best allele is updated.

I apologize in advance if this is not a bug, but I would like to know if I should use negative likelihoods as in the removed `PerReadAlleleLikelihoodMap`, or positive ones, as suggest the current implementation for getting the best alleles.

Thank you in advance.

**Comment by magicDGS** [comment]
As you did the removal of PRALM (https://github.com/broadinstitute/gatk/pull/2185), could you help me with this, @davidbenjamin? Thank you very much!

**Comment by davidbenjamin** [comment]
@magicDGS I'm on it.

**Comment by davidbenjamin** [comment]
@magicDGS I believe `searchBestAllele`'s behavior is correct.  A larger (i.e. more positive or less negative) likelihood (or rather, log-likelihood) is a better allele.  If you want to initialize some alleles to be better than the default, use a positive value.  If you want them to be worse than the default, use a negative value.  I'm not surprised that `PerReadAlleleLikelihoodMap` did something contradictory and backward.  It was a remarkably silly class.  There's no need to apologize for being confused by its misdirection.

**Comment by magicDGS** [comment]
Ok, now I got it! Thanks @davidbenjamin! Just two short questions before closing:

* Could this fact be added to the javadoc (`ReadLikelihood`or `LikelihoodMatrix`)?
* If the more negative values are the less likely, why the construction without information sets everything to 0? I would like to have a way to set on construction the default value and/or this to be `Double.NEGATIVE_INFINITY`. My feeling told me that if a likelihood is set for an allele, it should be more likely than the ones where the likelihood was not computed; but I'm usually wrong, so that's why I'm asking.

Thank you very much for your time. Now I can progress in the change to the new likelihood class.

**Comment by davidbenjamin** [comment]
@magicDGS I forgot about your question and apologize for the delay.  The thing to understand is that in GATK 4 the only use for this class (except for the artificial case of unit tests) is to be filled immediately after construction with likelihoods from `PairHMM`.  Therefore, the initialization is irrelevant to our purposes.

I am loathe to add anything to the javadoc because confusion only arises relative to the deprecated `PerReadAlleleLikelihoodMap`, which will be forgotten in GATK 4.

**Comment by magicDGS** [comment]
Thanks for your answer @davidbenjamin. I still think that a javadoc update may be useful. If GATK is used as a framework and the user does not know that they should fill in all the likelihoods for all the alleles and reads, even without knowing about `PerReadAlleleLikelihoodMap`, this may drive to errors in the code that may be solved with a implementation note in the documentation.

Thanks a lot again for the information, it was very useful!
