### ISSUE TITLE
Custom Spark configuration in tests

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk#2337]
At the moment, all tests share a global Spark context. Once the test context is created, subsequent calls to `getTestSparkContext(Map<String, String> overridingProperties)` or `getSparkContext(...)` return the existing context and `overridingProperties` is ignored. This results in failure of integration tests of tools that need to override certain Spark configs (e.g. to register custom serializers).

To make life a bit easier for gatk-protected devs, it is (at least) desirable to take a global set of overriding Spark config key-value pairs from within the gradle build script, and considering them when instantiating the global test Spark context. In particular, I would like to add a few comma-separated extra registrators to `spark.kryo.registrator`.

Perhaps this feature is already present?

**Comment by droazen** [comment]
@tomwhite Thoughts on this?

**Comment by lbergelson** [comment]
@mbabadi You can directly register more classes by adding them in GATKRegistrator.  It doesn't fix the problem of needing custom configuration, but that's how we've been  dealing with custom serializers, just put them all in all the time.

**Comment by mbabadi** [comment]
@lbergelson but GATKRegistrator is in gatk repo (and not in gatk-protected) and gatk is imported as a maven artifact into gatk-protected. What is the easiest way to do this?

**Comment by davidbenjamin** [comment]
gatk-protected and gatk public merged several years ago.
