### ISSUE TITLE
Hook up cloud prefetching to tribble and FeatureDataSource

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2375]
1. Wrap `SeekablePathStream` in the tribble feature readers with a `Function<SeekableByteChannel, SeekableByteChannel>`

2. Mirror what was done in https://github.com/broadinstitute/gatk/pull/2331 for `FeatureDataSource`: propagate cloud prefetching buffer sizes from `GATKTool` down to `FeatureDataSource`, create wrapper functions within `FeatureDataSource`, and pass down to htsjdk.

**Comment by droazen** [comment]
For @lbergelson, since @jean-philippe-martin is out this week.

**Comment by lbergelson** [comment]
This was done in https://github.com/samtools/htsjdk/pull/796 and https://github.com/broadinstitute/gatk/pull/2393
