### ISSUE TITLE
SelectVariants fails when sample_file is used with a .list file

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2390]
The collection list file feature implemented in broadinstitute/barclay#28 can break tools that already have a `Collection<Files>` argument that is used to manually from populate another collection, if the argument value supplied is a ".list" file.

The CLP feature checks to see if an argument value for a collection has a ".list" extension, and if so, populates the argument field with the contents of the file, rather than with the filename. SelectVariants has two such arguments ("sample_file" and "exclude_sample_file") that are typed as `Set<File>`, and are each intended to contain a list of file names, each of which in turn contains a list of sample names. SelectVariants manually loads all of the samples from all of the files in the set, and creates a list of unique sample names.

With the broadinstitute/barclay#28, the CLP populates the file set directly with the contents of the file if the argument value ends in the extension ".list". SelectVariants will fail when this happens, because it then tries to treat the sample names in the collection as file names.

One possible solution would be to change the CLP to not implement this functionality if the type parameter of the Collection is File.

**Comment by lbergelson** [comment]
@cmnbroad I'm not sure I understand what's wrong here.  It seems like if someone was specifying a .list file for `--sample_file`, then they should understand that it has to point to a file full of filenames, not sample names.  Maybe select variants should change to take a list of sample names instead of files, and people can choose to provide a file with .list if they want to.

It seems better than making .list inconsistent based on argument type.  The major use of .list is to specify collections of filenames, so it would sort of the defeat the point if it wasn't allowed to be used for files.

**Comment by cmnbroad** [comment]
Yes, the CLP change suggestion wasn't a great one of several reasons, type erasure for one. SV can be changed with a small amount of code to take advantage of the new CLP feature and still retain  compatibility with it's previous command line syntax.

**Comment by cmnbroad** [comment]
@lbergelson @droazen Ah,  SV has two arguments for samples: "sample_name" takes sample names, and "sample_files" takes file containing samples, but it will take *any *file, regardless of extension. The whole thing is repeated with "exclude_samples".

We could eliminate the file-based arguments, but the result would only work with ".list" files. If we can break backward command line compatibility, we can simplify SV,  remove two arguments, and remove the SampleUtils and SampleUtilsUnitTest file-reading code. We just need to decide which.

**Comment by lbergelson** [comment]
My vote is just to remove the "sample_files" argument and let people use the `.list` file with "sample_names".
