### ISSUE TITLE
disabling a non-existent read filter gives a warning instead of an exception

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2397]
`--disableReadFilter` should throw if a value that is not a valid ReadFilter is given

**Comment by lbergelson** [comment]
this is a counter proposal to #2358

**Comment by mbabadi** [comment]
I second this: we had a wrong filter name in our WDL scripts which wouldn't get disabled, leading to wrong results and apparently successful runs: https://github.com/broadinstitute/gatk-protected/issues/893

**Comment by magicDGS** [comment]
In #2358 I'm referring to the help. Actually, I also agree on this.

**Comment by magicDGS** [comment]
By the way, I can take this one. I'm planning to do a big PR with a workaround with some of the problems of the plugin that I found to discuss them there.

**Comment by cmnbroad** [comment]
@magigDGS Yes, please include the fix for this in the PR with the other related changes.
