### ISSUE TITLE
default read filters are excluded from the help output for --disableReadFilters

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2398]
Tool default ReadFilters are not included in the help output as possible values for either `--readFilter` or `--disableReadFilter`.

It makes some sense to not include default read filters in the list of read filters to enable, but we definitely need them in the list to disable.

**Comment by magicDGS** [comment]
I think that https://github.com/broadinstitute/gatk/pull/2360 fix it.

**Comment by magicDGS** [comment]
This is kind of a duplicate of #2358

**Comment by cmnbroad** [comment]
Closed via #2401.
