### ISSUE TITLE
htsjdk should parse multiallelic AF/AC

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#241]
It would be wonderful to be able to use SelectVariants with a query like -select "AF > 0.1" on a VCF containing multiallelics and have it filter multiallelics by the allele with the highest AF. (Possibly conversely for "AF < X"queries. Right now it crashes unless you use a crazy JEXL or pull out the multiallelics. Maybe we could make a maxAF/minAF in htsjdk/JEXLmap.java which equals AF for biallelics?

Internally, it might be nice to have a Map<Allele, Double> with the AF (or AC) for each allele for the SelectVariants issue and to simplify some of the crazy logic already in VariantAnnotator to deal with different allele ordering.

As part of this task, we should also make 100% sure that allele ordering is preserved so that AF/AC array ordering is preserved during VC reading/writing/manipulation.

**Comment by akiezun** [comment]
@ldgauthier @droazen why is this issue here and not in htsjdk? Am i missing something?

**Comment by droazen** [comment]
To improve the chances of it actually getting implemented :)

**Comment by akiezun** [comment]
this is troublesome. let's discuss offline

**Comment by akiezun** [comment]
@droazen given htsjdk gatekeeping changes, should we now move this to that repo? assigning to you to decide

**Comment by droazen** [comment]
Moved to htsjdk as https://github.com/samtools/htsjdk/issues/423 -- closing
