### ISSUE TITLE
How to generate  bwamemIndexImage

### ISSUE THREAD

**Issue by tushu1232** [broadinstitute/gatk#2414]
Bwa Spark needs a required argument  bwamemIndexImage.How to generate it.
Are there any defined steps

**Comment by lbergelson** [comment]
Hi @tushu1232.  The index image is a new feature that's not fully exposed in a friendly.  It's the 5 indexes that bwa requires baked into a single file for easy distribution. ( .amb, .ann, .bwt, .pac, .sa )  We're going to add an official tool to generate it in the near future, but at present the only way to do so is to write a tool yourself that calls into org.broadinstitute.hellbender.utils.bwa.BwaMemIndex.createIndexImage();

**Comment by rtemanni** [comment]
Hi @lbergelson, would it be possible to have the indeximage for hs37d5 and hs38DH available for download ?
Thanks in advance.

**Comment by lbergelson** [comment]
@rtemanni That sounds like a good idea to host them.  Maybe we could include them in the GATKBundle in the future.  They're pretty large files though, and can be generated from the reference directly, so I'm not sure if it makes sense to download them or just create the index yourself from your own reference.  We will definitely consider it though.

**Comment by SHuang-Broad** [comment]
Did something [here](https://github.com/SHuang-Broad/bwamem-index-image) with a "shameless" copy of Ted's original code. It takes a very short time to create the image, so downloading the big image file (~5GB) might not worth it.

**Comment by lbergelson** [comment]
@SHuang-Broad Why not just add that as a gatktool?

**Comment by SHuang-Broad** [comment]
Laziness... I just did that project today for fun & practice. It shouldn't be difficult to do it in Java. I'll do it later.
