### ISSUE TITLE
Support secondary and supplementary alignments when handling paired reads for queryname-sorted BAMs

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#2418]
From @droazen on https://github.com/broadinstitute/gatk/pull/2350

> Would be good to add test cases with: 1. secondary alignments in addition to primary alignments 2. supplementary alignments in addition to primary alignments, and possibly 3. the case of more than two reads in a fragment (in which case both "first of pair" and "second of pair" can be set).

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/2442, which is a bit more specific and detailed about what needs to be done.
