### ISSUE TITLE
Allow Intel Inflater to be used with block-gzipped VCFs as well

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2420]
Requires some additional hook-up work in htsjdk, on top of the work we've already done for bams.

**Comment by droazen** [comment]
For @gspowley

**Comment by gspowley** [comment]
@droazen  We have some questions about this. Example GATK commands that use block-gzipped VCFs will help. Let's discuss on Monday (2/27).

**Comment by gspowley** [comment]
@droazen Actually, `IntelInflater` is already being used with block-gzipped VCFs.

On this [line in htsjdk](https://github.com/samtools/htsjdk/blob/912c28bec415c430b43515652ccaf13222b07e7b/src/main/java/htsjdk/variant/vcf/AbstractVCFCodec.java#L629), the `AbstractVCFCodec` creates a `BlockCompressedInputStream` using the default `BlockGunzipper`, which is `IntelInflater` by default in GATK.

I verified `IntelInflater` is used by running this GATK command with a debug version of GKL (to display usage info):
```
./gatk-launch CountVariants -V src/test/resources/large/dbsnp_138.b37.20.21.vcf.blockgz.gz
```

We could add an issue to htsjdk to support different `Inflater` implementations for each block-gzipped VCF codec instance, but I don't think it's a high priority.

I propose we close this issue.

**Comment by gspowley** [comment]
Added https://github.com/samtools/htsjdk/issues/859 to request HTSJDK feature to support non-default `InflaterFactory` for block compressed VCF files.

Closing this issue.
