### ISSUE TITLE
Determine whether spark.local.dir is automatically set to use the SSD on Google dataproc when one is available

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2426]

**Comment by droazen** [comment]
It turns out that using an SSD for spark.local.dir results in a massive speedup over using a conventional HDD for our tools. We should find out whether Google dataproc is smart enough to set spark.local.dir to an SSD when one is available

**Comment by droazen** [comment]
@jean-philippe-martin Could you look into this when you have time?

**Comment by jean-philippe-martin** [comment]
OK!

**Comment by jean-philippe-martin** [comment]
It *looks like* it doesn't. I ran a job and looked at the "environment" tab in the Spark page for the job and didn't see "spark.local.dir" mentioned in the list of properties or the command line. Based on [the documentation](http://spark.apache.org/docs/latest/configuration.html), the setting must thus still be at its default value of "/tmp". 

/tmp is on the HDD, the SSD one would have to be on /mnt/1/.

**Comment by jean-philippe-martin** [comment]
Confirmed via a custom program: spark.local.dir is unset.

**Comment by lbergelson** [comment]
Interesting, that's somewhat disturbing news, I wonder if we're paying for ssd's without actually being able to use them...   It's also possible there's a different setting that's configuring the ssd's to be used for shuffle output.  

We should investigate this further and 1) see if setting spark.local.dir makes a performance difference 2) ask the dataproc team about this.

**Comment by jean-philippe-martin** [comment]
Well we know they're not *completely* unused since I see a `spark` and `hadoop` folder on the SSD (complete with tmp subfolder).

**Comment by lbergelson** [comment]
Running a particular bam sort takes ~20minutes with hdd and 16 minutes with ssd.  So it's definitely being used somehow.  It looks like spark.local.dir is over ridden by the environment variable LOCAL_DIRS, and I don't see that set, but it's possible it's being set but not recorded correctly in the UI or something like that.  Someone will need to poke at a bit more to be more clear about what's happening.

**Comment by jean-philippe-martin** [comment]
Ah, excellent point! LOCAL_DIRS is set! I see it's pointing to
`/mnt/1/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1488408043187_0001`
which is on the SSD, so the answer is that in fact Dataproc uses the SSD automatically. That's a relief!

**Comment by lbergelson** [comment]
👍 Thanks for investigating.
