### ISSUE TITLE
Enable PrintReads to exclude reads above a certain MQ threshold

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#2432]
@chandrans commented on [Wed Sep 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1476)

### Tool(s) involved

PrintReads
### Description

Right now, we have a flag that outputs reads with a MQ greater than the set threshold. Users may want to only output reads that have a MQ below a certain threshold. There should be a flag (something like -maximumMappingQuality) that only emits reads that have less than the set Mapping Quality. 

For example, a user needs this to compare low mapQ reads from different samples, blast search and/or perform de novo assembly.

---

This Issue was generated from your [forums](http://gatkforums.broadinstitute.org/gatk/discussion/comment/32943#Comment_32943) 

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1476#issuecomment-260498511)

Might end up being a feature request for bidirectional read filtering functionality in GATK4. 

---

@chandrans commented on [Tue Feb 28 2017](https://github.com/broadinstitute/gsa-unstable/issues/1476#issuecomment-283141618)

Okay. Should I keep this open or close it/move to GATK4?

---

@vdauwera commented on [Tue Feb 28 2017](https://github.com/broadinstitute/gsa-unstable/issues/1476#issuecomment-283150007)

Yeah move to 4 please

**Comment by magicDGS** [comment]
This could be easily implemented in the `MappingQualityReadFilter` as a new parameter, and the syntax will be something like:

```bash
java -jar $GATK_JAR_FILE PrintReads -I $bam -O $output -RF MappingQualityReadFilter --minimumMappingQuality $min_qual --maximumMappingQuality $max_qual
```

I can take this one.

**Comment by chandrans** [comment]
Thanks @magicDGS and @droazen. I will let the user know it is in GATK4
