### ISSUE TITLE
Feature request for Picard and GATK tools to rationalize GRCh37 versus hg19 nomenclature

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#2434]
The benefit of this is that analysts would not have to convert back and forth between GRCh37 and hg19 format data, e.g. 1000 Genomes Project VCF resource file.

Components our tools would rationalize:

1. plus or minus chr at the beginning of contigs
2. MT == M
3. 2bp shift somewhere in the mitochondrial contig

See my March 1 comment at http://gatkforums.broadinstitute.org/gatk/discussion/comment/36692#Comment_36692 for some background.

This feature would require we allow for two different coordinate sort orders for tools that require matching coordinate sort orders in input data. I illustrate here with primary assembly contigs only:

    A. chromosomes 1 through 22, then X, Y and MT (GRCh37)
    B. chrM, 1-22, X, Y (hg19)

It would be useful to have the choice to sort on either one of these schemes irregardless of whether contigs start with `chr`. Or better yet, to unify what is a coordinate sort by choosing one of these and forcing all data (irregardless of whether GRCh37 or hg19) to comply with one.

I know we are moving to GRCh38 where all of these issues are resolved. However, from the vantage point of answering forum questions, having these features would save us (and users) a lot of headache currently and (I am certain) for the next couple of years.

**Comment by vdauwera** [comment]
I understand where you're coming from but this is not the right thing to do, not least because it would introduce brittle special-casing. We enforce strict reference matching for good reasons -- I don't want to allow people to do the wrong thing just because it would be easier.

**Comment by sooheelee** [comment]
I am doing this all the time--going back and forth between these references
with resource files. = (
