### ISSUE TITLE
Update google-cloud-java dependency to a snapshot containing newly added NIO API methods

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2441]
This will allow us to verify that the issues with NIO on Spark have been resolved, and hopefully allow us to finally close https://github.com/broadinstitute/gatk/issues/2287

**Comment by droazen** [comment]
For @jean-philippe-martin

**Comment by droazen** [comment]
@jean-philippe-martin pinging you on this one

**Comment by jean-philippe-martin** [comment]
I see not all our NIO pull requests have made it in:
- https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1715
- https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1630
- https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1463

Would you like to proceed now anyways, or should we wait for one or more of those?

**Comment by droazen** [comment]
How much longer do you think they'll be in review? If more than a few days, then perhaps we could move to a snapshot of a branch containing all of the unmerged changes? I think we likely need at least https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1630 for the Spark use case.

**Comment by jean-philippe-martin** [comment]
I've put a note on that PR, let's check back later today.

**Comment by jean-philippe-martin** [comment]
That PR is in so we're good. I see there were [four alpha releases](https://mvnrepository.com/artifact/com.google.cloud/google-cloud) in February so the code may be soon available officially.

**Comment by jean-philippe-martin** [comment]
The good news that that gcloud does offer snapshot versions. We can look at
https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/pom.xml#L7
to see what it's called, and import that.

The bad news is that it looks like the AuthCredentials class isn't in gcloud anymore yet we still reference it, so we don't compile when using that version.

**Comment by droazen** [comment]
Was the class just renamed or something, or is there some replacement class we should be using?

**Comment by lbergelson** [comment]
From the release notes it looks like it's an easy substitution.  In a surprise twist though, it looks like the shading produced invalid package names, so we can't actually refer to the shaded auth class, shaded.cloud-nio.com.google.auth.Credentials.

**Comment by lbergelson** [comment]
I opened a pr to fix that problem here: https://github.com/GoogleCloudPlatform/google-cloud-java/pull/1743

**Comment by jean-philippe-martin** [comment]
Good news: there's been a release since so we don't even need to rely on snapshot.
Pull Request #2488 does the update.

However I'm going to have to merge in @lbergelson's fix as well.

**Comment by jean-philippe-martin** [comment]
Merged, closing this bug. Next step: #2496
