### ISSUE TITLE
fix invalid certificate for gatk-jenkins

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2446]
https://gatk-jenkins.broadinstitute.org/ is currently giving a warning when you try to visit it.  We need to fix it's certificate so that it doesn't give a scary warning.  It says it expired several days ago.

@davidbernick Could you look into this?

**Comment by davidbernick** [comment]
We started tracking it two days ago as DSPTO-166 -- one of my people will get on it.

**Comment by davidbernick** [comment]
Done

**Comment by lbergelson** [comment]
@davidbernick Thank you!
