### ISSUE TITLE
port the ContEst tool

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#246]
contest is a tool for estimation of contamination levels. there exists an old implementation here: https://github.com/broadinstitute/contest
This ticket is about porting contest to hellbender

**Comment by akiezun** [comment]
removing 'help wanted' because code is not visible outside and integration tests use internal data.

**Comment by akiezun** [comment]
the requirement is that both the code and the tests are migrated to the hellbender repository and the tests use data that can be shared publicly.

**Comment by akiezun** [comment]
@ldgauthier is this going to come from GATK3 together with M2?

**Comment by ldgauthier** [comment]
Eventually.  I have the code building and running nicely in a branch, but @kcibul needs to find where the server test data was moved to.

**Comment by droazen** [comment]
For @akiezun and alpha-3

**Comment by akiezun** [comment]
The tool is ported - see the `ak_contest_v2` branch (note that it will not compile if rebased because it depends on a reverted PR that introduced symbolic names for read inputs). 

What remains to be done is tests. I'm not going to be able to work on this so I'll un-assign.

**Comment by droazen** [comment]
This is done thanks to @davidbenjamin !
