### ISSUE TITLE
Change in GATK3 allele subsetting routine may have mistakenly not been ported to GATK4

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2466]
In GATK3 `GATKVariantContextUtils` line 852 we have:

```
                if ( newLikelihoods == null || (originalVC.getAttributeAsInt(VCFConstants.DEPTH_KEY, 0) == 0 && likelihoodsAreUninformative(newLikelihoods) )) {
                    gb.noPL();
                } else {
                    gb.PL(newLikelihoods);
                }
```

The equivalent block of code in GATK4 is in `AlleleSubsettingUtils` line 71 (since `GATKVariantContextUtils.createGenotypesWithSubsettedLikelihoods()` was extracted to a separate class in GATK4 along with all allele subsetting routines).

```
            final boolean useNewLikelihoods = newLikelihoods != null && GATKVariantContextUtils.isInformative(newLikelihoods);
            final GenotypeBuilder gb = useNewLikelihoods ? new GenotypeBuilder(g).PL(newLikelihoods) : new GenotypeBuilder(g).noPL();
```

Note that the GATK4 version of this line lacks the `(originalVC.getAttributeAsInt(VCFConstants.DEPTH_KEY, 0) == 0` check present in GATK3. This check was added to GATK3 by @davidbenjamin  as part of his "Genotype GVCF emits QUAL for ref sites" PR  (https://github.com/broadinstitute/gsa-unstable/pull/1346), but appears to have never made it to GATK4.

**Comment by droazen** [comment]
Assigning to @davidbenjamin to determine whether the change in question should be ported, and if it should, to make the change and add a unit test that fails without it.

**Comment by droazen** [comment]
@lbergelson take note

**Comment by lbergelson** [comment]
I have a test case that fails without it :)

**Comment by droazen** [comment]
Then feel free to submit the PR for this fix @lbergelson -- but I'd still like to get @davidbenjamin 's explicit thumbs up on it, since he made the change in GATK3.

**Comment by davidbenjamin** [comment]
Thumbs-up given.

**Comment by droazen** [comment]
Thanks @davidbenjamin -- @lbergelson You should have a look at https://github.com/broadinstitute/gsa-unstable/pull/1346 to see if other GenotypeGVCFs-related changes were made there that didn't make it to GATK4.
