### ISSUE TITLE
make 100% sure that allele ordering is preserved in htsjdk

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#247]
Thoroughly test htsjdk code to make sure the alternate allele ordering in the input VCF (for multiallelic variants) is preserved during VC reading/writing/manipulation.

As part of this task, while whoever is doing is it making changes, it would be wonderful to take out the allele alphabetizing in the VariantContext::toString method because that makes debugging this issue less straight forward.

**Comment by akiezun** [comment]
@ldgauthier i'm not sure what this issue is. Is it about testing in htsjdk? If yes, maybe it belongs to htsjdk. Or is it a bug? If the latter, what is the test case?

**Comment by droazen** [comment]
It's definitely a testing issue in htsjdk, but I asked Laura to open the ticket here to remind us to address this eventually (especially as we port more variant tools). If we opened the ticket directly in the htsjdk tracker it would probably just rot.

**Comment by akiezun** [comment]
now that @droazen is a htsjdk gatekeeper, chances are greater for making this happen. Assigning to @droazen to decide what to do

**Comment by droazen** [comment]
Moved to htsjdk as https://github.com/samtools/htsjdk/issues/424. Closing
