### ISSUE TITLE
Hook up new barclay universal argument tagging

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2473]
This feature is needed in particular by Mutect (and related tools in protected)

**Comment by lbergelson** [comment]
I still think that separate --normal and --tumor arguments are probably better than -b:tumor.

**Comment by droazen** [comment]
This feature is needed by many tools, not just somatic tools, so it makes sense to rely on the generalized tagging support we implemented in barclay.

**Comment by droazen** [comment]
@cmnbroad is this done?

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/5526.
