### ISSUE TITLE
Ingest Picard as a dependency, add mechanism to Main.java to execute both GATK and Picard CommandLinePrograms

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2478]

**Comment by magicDGS** [comment]
The mechanism for include picard CLPs (or other custom ones) is already implemented, `Main.getPackageList()` should return the package where the picard tools live, once #2477 is implemented.

**Comment by droazen** [comment]
There are a few other pieces needed here besides that, like code to actually do the search using a `ClassFinder`, resolve the situation where both a GATK and a Picard tool have the same name, and code to actually execute a Picard `CommandLineProgram` in GATK.

**Comment by magicDGS** [comment]
This is solved already, no?

**Comment by cmnbroad** [comment]
Yeah - closed via #3620.
