### ISSUE TITLE
Possible memory leak in GATK4

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2484]
@cmnbroad reports that he's seeing out-of-memory errors when running the test suite locally. He says it could be a recently-introduced regression -- we should narrow it down to a single commit.

**Comment by lbergelson** [comment]
@tedsharpe This sounds related to the test hangs you were telling me about.

**Comment by cmnbroad** [comment]
Closing in favor if https://github.com/broadinstitute/gatk/issues/2490.

**Comment by droazen** [comment]
Likely duplicate of https://github.com/broadinstitute/gatk/issues/2490
