### ISSUE TITLE
figure out why some annotations don't implement Annotation and decide if they should

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2493]
Some annotation base classes don't implement the `Annotation` marker interface.  (i.e. `VariantAnnotation`) This was the case in gatk3 as well, but it's unclear why.  It may be a historical artifact rather than a design decision, in which case it should be corrected.  If it's important to have the marker interface then all the annotations should implement them.  If it isn't, then we should probably remove it or move abstract functions into the interface.

**Comment by droazen** [comment]
Adding to annotation epic #3274

**Comment by jamesemery** [comment]
This has been handled by other annotation pull requests like https://github.com/broadinstitute/gatk/pull/3851
