### ISSUE TITLE
SV called variants.vcf ASSEMBLY_IDS and CONTIG_IDS uses % rather than , to separate elements.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#2502]
VCF's standard is to use , to separate elements in INFO and FORMAT annotations. 

The output of the SV variant caller instead of , uses % to separate elements.

**Comment by cwhelan** [comment]
@SHuang-Broad was there a reason you used '%'?

**Comment by vruano** [comment]
This seems to come from this constant in GATKSVVCFHeaderLines.java line 15.

    GATKSVVCFHeaderLines.FORMAT_FIELD_SEPARATOR= "%"

**Comment by vruano** [comment]
The constant name is rather deceptive as it would be strictly speaking ':' I guess it should be called something like FIELD_ELEMENT_SEPARATOR and I guess there is VCF Consants class constant for that anyway.

**Comment by SHuang-Broad** [comment]
Nope, simply an ignorance of that part of the VCF spec, and the fact that `INSERTED_SEQUENCE_MAPPINGS` is using `,` for separating fields of a single mapping.

**Comment by SHuang-Broad** [comment]
ping @vruano for reviewing #2512 that fixes this issue

**Comment by SHuang-Broad** [comment]
closed by #2512
