### ISSUE TITLE
Tool to create a reduced input bam file with those reads that constitute the evidence of a set of given variants.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#2504]
This or these tool would be use to use piece meal bam files that we can use for local (laptop/desktop) development and integration tests.

The input would be SV called variant VCF with and two intervals lists. The first one would indicate for what variants in input we want to gather the evidence reads and the second the supported reference interval in the output (anything outside that interval will be changed to unmapped). The second interval list must include the first interval list since otherwise it would not make any sense.

**Comment by vruano** [comment]
This or these tool would be use to use piece meal bam files that we can use for local (laptop/desktop) development and integration tests.

The input would be SV called variant VCF with and two intervals lists. The first one would indicate for what variants in input we want to gather the evidence reads and the second the supported reference interval in the output (anything outside that interval will be changed to unmapped). The second interval list must include the first interval list since otherwise it would not make any sense.


@SHuang-Broad, tagging you here since you seem to have done some work on this.

**Comment by SHuang-Broad** [comment]
Yep. I'll find time this week, but most likely after the Methods meeting.

**Comment by vruano** [comment]
Actually I'm doing some work on this regards. I have unassigned you, at lease for now.

**Comment by SHuang-Broad** [comment]
@vruano ping to see if still valid.

**Comment by vruano** [comment]
ja, it never got merged and now is sort of invalid due to changes in the assembly fastq, so still pending.

**Comment by vruano** [comment]
I remember that got it to work at some point but probably buried very deep in some lost branch at this point. So lets close this.
