### ISSUE TITLE
Maintaining Headers and Callset Mapping (to internal TileDB row indexes) in GenomicsDB

### ISSUE THREAD

**Issue by kdatta** [broadinstitute/gatk#2505]
The key issue here is how to best maintain the mapping data structures for GenomicsDB. During the import, we create two mapping structures – a) merged header created from the INFO, FORMAT and FILTER fields of all the input gVCFs and b) a callset map containing the mapping between callset/sample ids to unique TileDB row indexes.
 
If we decide that GenomicsDB will internally maintain both a) and b), then question is how do we handle simultaneous readers and writers. If there are more than one writers, then we need to “build” a mechanism to lock the metadata. This is important to maintain consistency of the header fields across all writers. In addition, each callset must be mapped to one and only one row index. Hence, the order in which row indexes are assigned to the callsets must be same across all writers.
 
In GenomicsDB v0.4.0, we punt this and provide output paths for both mappings to the user. This works today because we assume no simultaneous writes and probably readers are collocated with the writers. Hence, the user just passes the output file paths used during import to the readers. Internally, the writers always use the same order of callsets. If not, then data in GenomicsDB will be corrupted as we discussed before.

@droazen @lbergelson  @kgururaj

**Comment by droazen** [comment]
@lbergelson Since you were the one who raised this issue at our weekly meeting, could you add your opinion on this topic here for the record? Thanks!

**Comment by kgururaj** [comment]
Closing since we generate JSON files during import that are used during queries
