### ISSUE TITLE
Integrate Picard and GATK report formats

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/gatk#251]
Picard and GATK have different (incompatible) mechanisms for report generation.

I woudl strongly advocate finding out what the requirements are and merging the two systems.

**Comment by akiezun** [comment]
@yfarjoun what are the requirements?

**Comment by yfarjoun** [comment]
- human/java/R readable
- for picard, need to beable to repopulate metrics class from file
- for gatk need to be able to read into r list of dataframes
- javadoc generation of metrics description from comments in class (as in
picard)
- for picard: need to allow one table and one histogram
- for GATK need to allow multiple different tables

**Comment by droazen** [comment]
Not happening -- closing
