### ISSUE TITLE
NIO error: "position should be non-negative"

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/gatk#2516]
It looks like when reading from cloud we sometimes hit a bug that crashes GATK with the following message:

```
Caused by: com.google.cloud.storage.StorageException: java.lang.IllegalArgumentException: Position should be non-negative, is %d [-385875968]
        at com.google.cloud.storage.StorageException.translateAndThrow(StorageException.java:78)
        at com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:140)
        at com.google.cloud.storage.contrib.nio.CloudStorageReadChannel.read(CloudStorageReadChannel.java:109)
        at org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher$WorkUnit.call(SeekableByteChannelPrefetcher.java:121)
```

This doesn't happen every time, but clearly it should never happen at all.

**Comment by jean-philippe-martin** [comment]
Trying to reproduce, but still haven't been able to. This crash looks like a rare occurence.

**Comment by lbergelson** [comment]
Another transient internet thing then.

**Comment by jean-philippe-martin** [comment]
It happened again, on Friday. This was running updated code that [checks the position before calling](https://github.com/broadinstitute/gatk/blob/jp_retry_more_2/src/main/java/org/broadinstitute/hellbender/utils/nio/SeekableByteChannelPrefetcher.java#L119) - so we know that we set the position to a non-negative value before doing the read.

The error says that the position was -218103808 -- this is 0xD000000 in hex, a suspiciously round number. The previous times we've seen this, we got:

value seen in error | hex | on 40MB boundary?
------------ | ------------- | ---
 -218103808 | -0xD000000 | no
-285212672 | -0x11000000 | no
-1577058304 | -0x5E000000 | no
-385875968 | -0x17000000 | no

Our prefetch buffer size is 40 MB (0x2800000) so we might think that explains the many leading zeroes (are we just on a negative number of buffer boundaries?) but the error number is not a multiple of this constant, so that's not it.

**Comment by jean-philippe-martin** [comment]
A good news is that my [intense reading tests](https://github.com/broadinstitute/gatk/blob/jp_gcloud_17_snapshot/src/test/java/org/broadinstitute/hellbender/utils/nio/ExtremeReadsTest.java#L64) related to fixing #2685 did not trigger this bug. Possibly we were lucky, and possibly upgrading the gcloud version as that PR does brought in a fix for this issue.

**Comment by droazen** [comment]
We are suddenly seeing this error again at scale: https://github.com/broadinstitute/gatk/issues/3316

**Comment by droazen** [comment]
Resolved by https://github.com/broadinstitute/gatk/pull/3373 and https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2283
