### ISSUE TITLE
Improve indel calls on repeats (review the current PCR error model).

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#2519]
@vruano commented on [Tue Jun 28 2016](https://github.com/broadinstitute/gsa-unstable/issues/1425)

### Tool(s) involved

_HaplotypeCaller_
### Description

Review the current approach to handle indel in short repeats. Fix and change to improve accuracy.

---

@vruano commented on [Tue Jul 12 2016](https://github.com/broadinstitute/gsa-unstable/issues/1425#issuecomment-232150240)

Comparison using KB NA12878 on PCR+ PCR- data across 20:10M-25M:

<img width="550" alt="screen shot 2016-07-12 at 3 15 45 pm" src="https://cloud.githubusercontent.com/assets/791104/16780183/9042fcda-4843-11e6-99e5-cb9b39e5dfdc.png">

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1425#issuecomment-260494000)

@vruano Are you currently working on this? Or can this be moved into the GATK4 repo for future work? 

---

@vruano commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1425#issuecomment-260503444)

Working on it on GATK3 but I could merge it into GATK4 whenever is ready if you prefer.

---

@vdauwera commented on [Mon Nov 14 2016](https://github.com/broadinstitute/gsa-unstable/issues/1425#issuecomment-260509332)

Ok great, totally fine to do in 3 but please do port to 4 when it's ready. Do you have an order of magnitude sense of when it might be ready? Meaning days/weeks/months (for release scheduling purposes)

---

@vruano commented on [Fri Mar 10 2017](https://github.com/broadinstitute/gsa-unstable/issues/1425#issuecomment-285721454)

In the last methods meeting I presented the results of our first effort to improve accuracy calling in STR. As far as unfiltered single and trio calls are concerned the recommendation is to apply the new model with PCR+ data.

However, for PCR- dataset one either can choose not apply any correction or to apply the new model train on PCR- data... the latter seems to have slightly F1 values however for the sake of simplicity it might just make sense no to apply any correct; either way is good.

The presentation I gave can be found [here](https://drive.google.com/open?id=0Bzt9p0vCNxlHWlZVUHZfdXR5MTg)

---

@vruano commented on [Fri Mar 10 2017](https://github.com/broadinstitute/gsa-unstable/issues/1425#issuecomment-285722791)

It seems that at some point Planatir will take a look and see whether it improves calls once filtered with VQSR.

---

@vdauwera commented on [Mon Mar 20 2017](https://github.com/broadinstitute/gsa-unstable/issues/1425#issuecomment-287822174)

Is there a PR associated with this issue? Will there be a new feature to release? Need to know for release scheduling purposes.

**Comment by ldgauthier** [comment]
@droazen @vruano can we say DragSTR closes this?

**Comment by droazen** [comment]
@ldgauthier Yes, I would say so. Do you agree @vruano ?

**Comment by vruano** [comment]
Ok... let's close it, if any thing happen beyond DRAGstr will be a different issue.
