### ISSUE TITLE
Request: package the testing framework into a module

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#2533]
It will be nice to have the GATK testing framework in a different module and maven artifact to add it as a dependency only for testing, and do not include it in the uber-jar the TestNG dependecy (or the Mini-Cluster from Hadoop).

**Comment by droazen** [comment]
Closing as duplicate of https://github.com/broadinstitute/gatk/issues/1481 -- please do a textual search of our issues for possible duplicates before opening a new one.

**Comment by magicDGS** [comment]
Sorry, I use to search but this time I forgot. My fault...

**Comment by lbergelson** [comment]
I blame github's lack of autosearch when creating a new ticket.  Every other issue tracker has it...
