### ISSUE TITLE
Protect against TileDB writes that would corrupt an existing instance

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2536]
Should throw an error if the client tries to write to TileDB in such a way as would corrupt an instance.

**Comment by droazen** [comment]
For @kgururaj and @kdatta

**Comment by kdatta** [comment]
@droazen, we have a failIfUpdating flag in GenomicsDB which throws an IOException if one tries to update an existing instance. Once issue #2613 gets merged, I can add this functionality

**Comment by droazen** [comment]
I think we addressed this by throwing if the GenomicsDB target directory already exists -- closing.
