### ISSUE TITLE
InbreedingCoefficient isn't hooked up to pedigree files

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2542]
Currently there's no way to pass in pedigree files to `InbreedingCoefficient`  We should ask if this is an important feature for genotype gvcfs in production.

**Comment by magicDGS** [comment]
I think that this is related with https://github.com/broadinstitute/gatk/issues/1880, and I've already develop a rough system in a small project to have a plugin for variant annotation. I would love to contribute to this, and I kind of started with https://github.com/broadinstitute/gatk/pull/2534

**Comment by droazen** [comment]
Would probably be solved by https://github.com/broadinstitute/gatk/issues/3287
