### ISSUE TITLE
How Can I Recalibrate Indel Quality?

### ISSUE THREAD

**Issue by ShawnWilliams** [broadinstitute/gatk#2549]
Hi,
It seems that gatk4.0 has removed indel quality recalibration function. 
I need indel quality to use Mutect2. Is there any tool I can use to recalibrate indel quality?

**Comment by lbergelson** [comment]
Hi @ShawnWilliams, our analysis showed us that indel quality recalibration wasn't giving us very much of a benefit and it was quite expensive computationally, so we disabled it by default.  

There's a hidden argument `-indelBQSR` which will re-enable that functionality, but we don't think it's necessary for most recent sequencing data.  I think it was a mistake that that argument was made hidden, I'm going to label it `Advanced` instead...

**Comment by ShawnWilliams** [comment]
Hi @lbergelson 
Thanks so much for your help!
And thanks @droazen for add "question" label to my question!

I find that I can run BaseRecalibrator with -indelBQSR to generate a .grp file contains insertion type and deletion type, and with -enableBAQ to turn on BAQ function.
But I can't run ApplyBQSR with -indelBQSR, and the error information is:
***********************************************************************

A USER ERROR has occurred: i is not a recognized option

***********************************************************************

And if I run ApplyBQSR with no optional arguments, the output .bam file doesn't contain inserntion quality and deletion quality. How can I get a output bam file with indel quality?

**Comment by lbergelson** [comment]
@ShawnWilliams I'm sorry, I think I steered you wrong.  It looks like the ability to *apply* the indel recalibration was removed at some point.  Which is probably why the argument was hidden in the first place...  

We did analysis and found that it didn't made a significant difference in the final variant calls if you don't do it, so we dropped support for it.  I thought we'd just turned it off by default, but it looks like it's actually been removed from the apply functions. 

Could you tell me a bit about your data?  Unless there is something very strange about it I wouldn't  expect it to gain much benefit from indel recalibration.  (Base recalibration is more important  if you have low quality or older data, but even in those cases the indel recalibration doesn't make that much difference.)   

If your really need to run it it looks like your only option is going to be to use gatk3 for now.  Sorry to have mislead you.

**Comment by ShawnWilliams** [comment]
@lbergelson Thanks for your explanation, it really eliminates my confusion!
I used to think that Mutect2 can't run with a bam file which doesn't contain indel quality, it's my fault. The fact is that I can run Mutect2 with default Indel Quality(45). Now I'll put my data(without indel quality) into Mutect2 and see whether it make a significant difference or not.

**Comment by vdauwera** [comment]
MuTect2 shouldn't require indel qualities to be present -- if you find that it does let us know, because it's not intentional.
