### ISSUE TITLE
Explore whether the native PairHMM could be custom-tuned or modified to benefit Mutect2

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2562]
@davidbenjamin has requested that we look into whether there are `PairHMM` optimizations we could do that would benefit Mutect2 specifically -- the performance profile may be different than for the `HaplotypeCaller`. 

Intel has agreed to have a look, but they'll need a Mutect2 test case that they can run. @davidbenjamin would you be able to provide one?

**Comment by droazen** [comment]
For @gspowley and the 4.0 milestone.

**Comment by davidbenjamin** [comment]
@droazen Sure.  Does that mean paths on the Broad server to all inputs, presumably ones we have permission to share, and a Mutect command line?

**Comment by droazen** [comment]
It just means working with @gspowley / Intel to give them whatever "tech support" they need to get up and running with Mutect2 on a profile-able use case.

**Comment by davidbenjamin** [comment]
Of course, whatever @gspowley wants!

**Comment by gspowley** [comment]
Thanks @davidbenjamin! To start with, I'll need a Mutect2 command line and some shareable data that will give meaningful profiling results. We plan to run the experiments at Intel, so we'll have to figure out how to get the data there (download or copy to a disk).

**Comment by davidbenjamin** [comment]
@gspowley I have neglected this for a while, to say the least.  Here is a command line using publicly available data with paths on the Broad servers.  Everyone at the Broad has read access to these files, FWIW.  What should I do with the data?

```bash
wgs_intervals=/seq/references/Homo_sapiens_assembly19/v1/variant_calling/wgs_calling_regions.v1.interval_list
hg19=/seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta
tumor_bam=/dsde/working/davidben/dream/synthetic/original_bams_symlinks/tumor_4.bam
tumor_sample=synthetic.challenge.set4.tumour
normal_bam=/dsde/working/davidben/dream/synthetic/original_bams_symlinks/normal_4.bam
normal_sample=synthetic.challenge.set4.normal
java -jar $gatk Mutect2 \
  -R $hg19 \
  -L $wgs_intervals \
  -I $tumor_bam -tumor $tumor_sample \
  -I $normal_bam -normal $normal_sample \
  -O output.vcf
```

**Comment by gspowley** [comment]
Thanks @davidbenjamin for the feedback and sorry for the slow response. We have been working on improving PairHMM by adding AVX-512 (#3615) and FPGA (#2725) implementations. 

We are also adding AVX2 (#3701) and AVX-512 (future PR) Smith-Waterman, which will improve the performance of Mutect2.

We have the data above and will provide benchmarking results of your Mutect2 command with these improvements.
