### ISSUE TITLE
ReadsSparkSource should support "-L unmapped", like walkers do

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2571]
We have a request from @vruano to implement support in `ReadsSparkSource` for "-L unmapped" -- that is, the ability to specify a special "unmapped" interval in one's interval list to request the unmapped reads that have no mapped mates that are stored at the end of a bam file. 

`ReadWalker` and `LocusWalker` already have support for this feature -- it's implemented by calling `getTraversalParameters()` on an `IntervalArgumentCollection` and then `setTraversalBounds( final TraversalParameters traversalParameters )` on a `ReadsDataSource`, which causes `traverseUnmapped` to get set, and the underlying `SamReaderQueryingIterator` to call `queryUnmapped()` in addition to `queryOverlapping()` on its `SamReader`. We should be able to do the equivalent in Hadoop-BAM.

**Comment by droazen** [comment]
@tomwhite Could you take this one? Shouldn't be too difficult, I hope.

**Comment by tomwhite** [comment]
This will need implementing in Hadoop-BAM, as you point out. It's a little tricky as it will need new input splits for the unmapped reads, but I think it's doable.

**Comment by droazen** [comment]
Re-targeting for the 4.0 milestone due to difficulty
