### ISSUE TITLE
How to get a RDD<GATKRead> of the unmapped pairs of bam efficiently.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#2572]
There seems to be no obvious way to read thru the unmapped read pairs in a bam file in Spark.

Looking at the code in ```ReadSparkSource#getParallelReads(String, String, List, long)``` it seems that 
perhaps it is possible by setting the appropriate property in Configuration returned by ```ctx.hadoopConfiguration()``` however there is no documentation as to what property that could be. 

@droazen I assign it to you initially so that you route it to whoever might be most suited to address this issue.

**Comment by droazen** [comment]
@vruano Can you tell me whether https://github.com/broadinstitute/gatk/issues/2571 covers this request, or is that only one piece of what you want here?

**Comment by vruano** [comment]
I guess it would cover it as long as 'unmapped' support means efficient processing of the unmapped pairs (i.e. it would just go thru the whole bam file and ignore the mapped pairs).
