### ISSUE TITLE
Write up a Google doc with known/expected differences in GATK3 vs. GATK4 GenotypeGVCFs for palantir, along with suggested command-line test cases

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2575]

**Comment by droazen** [comment]
Should also mention the version of GATK3 that the palantir evaluation should be done with, and provide a link to both a gatk-protected jar and docker image to be used for testing.

**Comment by droazen** [comment]
For @lbergelson before he leaves on vacation. @yfarjoun take note.

**Comment by lbergelson** [comment]
closing this since it's done https://docs.google.com/document/d/1i2ldNfYp7ZX1lqpti7vjO9W0joqt1jTSqHTUxRl_TYM/edit
