### ISSUE TITLE
Enable fast log10/exp of an array of doubles

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/gatk#2577]
Many tools in our world require going from log-space to linear-space and back using log10 and exp.

These are slow functions and are usually used on an array (typically of length 3) of doubles.

It would be great to have a 
```
log10OfArray(double[] array)  
```
and
```
expOfArray(double[] array, base)
```
functions to enable fast computation of logs.

**Comment by droazen** [comment]
@gspowley Can you comment on whether this would be appropriate for a possible vectorized implementation in the GKL?

@davidbenjamin @vruano Can you comment on some of the existing approaches GATK takes to try to avoid expensive calls to `Math.log10()`, etc.? I think we rely (or used to rely) extensively on caching, correct?

**Comment by davidbenjamin** [comment]
@droazen Off the top of my head, we

* cache `log10(n)` and `log10(n!)` up to some large value.
* have a fast version of `log10SumLog10(double a, double a)` that works as follows: we want to compute `log10(10^a + 10^b)`.  WLOG `a < b`, so this comes out to `a + log10(1 + 10^(a - b))`.  I believe we cache the values of `log10(1 + 10^(x)` over a finely-spaced grid and round `a-b` to the nearest cached `x`. 

There might not be anything else.  There's a lot of stuff to keep calculations in log space for numerical stability but those don't avoid `log10()` and `Math.pow()`.

**Comment by mbabadi** [comment]
@yfarjoun for small arrays, `FastMath.log` is pretty much as fast as it gets. It is highly optimized. If you are dealing with giant arrays, however, an alternative is to cast the Java arrays into [NDArray](www.nd4j.org) and execute Nd4j native ops. Here's how the timings look:
```N = 1, Apache = 0.001625 ms, Nd4j = 0.113038 ms
N = 10, Apache = 0.002112 ms, Nd4j = 0.029833 ms
N = 100, Apache = 0.011660 ms, Nd4j = 0.028464 ms
N = 1000, Apache = 0.049915 ms, Nd4j = 0.052455 ms
N = 10000, Apache = 0.348786 ms, Nd4j = 0.430606 ms
N = 100000, Apache = 3.572483 ms, Nd4j = 1.810641 ms
N = 10000000, Apache = 323.021844 ms, Nd4j = 175.421305 ms
```
The nd4j times include the overhead of creating NDArrays and pulling back the results to JVM heap. The break even point is around N ~ 1000.

If accuracy is not a concern, perhaps a native implementation of log using half-precision floats can help. Also -- if many of these N = 3 arrays can be combined together, a vectorized native call is certainly helpful.

**Comment by mbabadi** [comment]
(I just updated my previous reply)

**Comment by gspowley** [comment]
[MKL](https://software.intel.com/en-us/intel-mkl) has highly optimized versions of `log10()` and `pow()`, which are much faster than standard native implementations.

@mbabadi would you mind sharing your profiling code? I'd like to make an apples-to-apples comparison of MKL to Apache and Nd4j.

**Comment by yfarjoun** [comment]
I don't think that we could merge those triples into bigger vectors easily....

**Comment by gspowley** [comment]
If the vector size is usually 3, then native code probably won't help due to the JNI transfer overhead. If there are uses cases with bigger vectors, we can investigate more.

**Comment by mbabadi** [comment]
I second @gspowley -- JNI transfer overhead is certainly more than ~ 10 ns it takes to calculate 3 logs (see below).

Here's the benchmarking code just in case:
```
        final int[] sizes = new int[]{1, 10, 100, 1000, 10000, 100000, 10000000};
        final int numTrials = 500;
        final RandomGenerator rng = new MersenneTwister();
        final List<DescriptiveStatistics> apacheStats = new ArrayList<>(sizes.length);
        final List<DescriptiveStatistics> nd4jStats = new ArrayList<>(sizes.length);
        final List<DescriptiveStatistics> nd4jCreationStats = new ArrayList<>(sizes.length);

        for (int idx = 0; idx < sizes.length; idx++) {
            final DescriptiveStatistics currentApacheStats = new DescriptiveStatistics();
            final DescriptiveStatistics currentNd4jStats = new DescriptiveStatistics();
            final DescriptiveStatistics currentNd4jCreationStats = new DescriptiveStatistics();
            apacheStats.add(currentApacheStats);
            nd4jStats.add(currentNd4jStats);
            nd4jCreationStats.add(currentNd4jCreationStats);

            for (int n = 0; n < numTrials; n++) {
                final double[] vals = IntStream.range(0, sizes[idx])
                        .mapToDouble(i -> 100 * FastMath.abs(rng.nextDouble())).toArray();

                final long t0 = System.nanoTime();
                apacheLog(vals);
                final long t1 = System.nanoTime();
                ndLog(vals);
                final long t2 = System.nanoTime();
                ndJustCreate(vals);
                final long t3 = System.nanoTime();

                currentApacheStats.addValue((t1 - t0) / 1000000.0);
                currentNd4jStats.addValue((t2 - t1) / 1000000.0);
                currentNd4jCreationStats.addValue((t3 - t2) / 1000000.0);
            }
        }

        for (int idx = 0; idx < sizes.length; idx++) {
            System.out.println(String.format("N = %d, ApacheFastMath = %f +/- %f ms, Nd4jLog = %f +/- %f ms, Nd4jOverhead = %f +/- %f ms",
                    sizes[idx],
                    apacheStats.get(idx).getMean(), apacheStats.get(idx).getStandardDeviation(),
                    nd4jStats.get(idx).getMean(), nd4jStats.get(idx).getStandardDeviation(),
                    nd4jCreationStats.get(idx).getMean(), nd4jCreationStats.get(idx).getStandardDeviation()));
        }

    }

    private double[] apacheLog(final double[] vals) {
        return Arrays.stream(vals).parallel().map(FastMath::log).toArray();
    }

    private double[] ndLog(final double[] vals) {
        return Transforms.log(Nd4j.create(vals), false).data().asDouble();
    }

    private double[] ndJustCreate(final double[] vals) {
        return Nd4j.create(vals).data().asDouble();
    }
```

Nd4j is on maven (add `compile 'org.nd4j:nd4j-native-platform:0.5.0'` to the gradle build script). Here's another run [nd4j:0.5.0, 2.8 GHz Core i7]:
```N = 1, ApacheFastMath = 0.021837 +/- 0.164358 ms, Nd4jLog = 0.029076 +/- 0.083403 ms, Nd4jOverhead = 0.012227 +/- 0.011450 ms
N = 10, ApacheFastMath = 0.230046 +/- 1.897271 ms, Nd4jLog = 0.042676 +/- 0.020724 ms, Nd4jOverhead = 0.016770 +/- 0.009369 ms
N = 100, ApacheFastMath = 0.052309 +/- 0.065039 ms, Nd4jLog = 0.037651 +/- 0.011225 ms, Nd4jOverhead = 0.017572 +/- 0.006995 ms
N = 1000, ApacheFastMath = 0.165869 +/- 1.852535 ms, Nd4jLog = 0.067076 +/- 0.017515 ms, Nd4jOverhead = 0.027893 +/- 0.009753 ms
N = 10000, ApacheFastMath = 0.164083 +/- 0.393109 ms, Nd4jLog = 0.331356 +/- 0.089105 ms, Nd4jOverhead = 0.152498 +/- 0.054611 ms
N = 100000, ApacheFastMath = 0.828509 +/- 0.259002 ms, Nd4jLog = 1.863066 +/- 0.348823 ms, Nd4jOverhead = 1.359101 +/- 0.336344 ms
N = 10000000, ApacheFastMath = 65.555431 +/- 15.020319 ms, Nd4jLog = 144.962199 +/- 15.107102 ms, Nd4jOverhead = 116.420955 +/- 11.090896 ms
```

For Nd4j and N = 10_000_000, the _actual_  log computation time is only ~ 30 ms (3 ns per log), though, there's a giant JNI overhead of ~ 116 ms (12 ns per log, 4x the execution time!).

**Comment by gspowley** [comment]
Closing this issue. Based on the discussion above, the most common vector size of 3 would not benefit from a native implementation.
