### ISSUE TITLE
Exclude htsjdk from GenomicsDB dependency in build.gradle?

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2578]
@cmnbroad and I were looking yesterday at the process for building GATK4 protected with a custom htsjdk snapshot, and we found that we couldn't get the htsjdk snapshot to propagate all the way through to protected unless we excluded htsjdk from our GenomicsDB dependency:

```
-    compile 'com.intel:genomicsdb:0.3.0'
+    compile ('com.intel:genomicsdb:0.3.0') {
+        exclude module: 'htsjdk'
+    }
```

Without this, htsjdk gets pulled in transitively via GenomicsDB. @lbergelson @kgururaj @kdatta Can you think of any reason why we shouldn't make this change?

**Comment by lbergelson** [comment]
Weird, I would have that that forcing the htsjdk version like we already do would have done it...    I don't see anything wrong with adding that exclusion, but I'm confused why we need it.

`    force 'com.github.samtools:htsjdk:' + htsjdkVersion`

**Comment by kdatta** [comment]
htsjdk is included in the GenomcisDB fat jar, maybe that's why getting pulled in from there. GenomicsDB class paths should be okay as long as htsjdk is in the path.

@droazen , is it okay to make this change in the latest GenomicsDB import PR? The version dependency has changed anyway.

**Comment by lbergelson** [comment]
Are we pulling in the fat jar?  Very minor issue, but it seems it would be better to pull in a slim jar that only has GenomicsDB + native code, and get its java dependencies separately.

**Comment by cmnbroad** [comment]
I think we need to exclude the htsjdk module from ADAM/bdgenomics as well. Without that I still get htsjdk 2.5 pulled in.

**Comment by droazen** [comment]
That's very strange @cmnbroad -- in the test I did in front of you yesterday, I added only the exclusion above and it worked fine for me. Are you building with `gradle` or `gradlew`?

Recommend we add whatever exclusions are necessary in a separate, simple PR, independent from the GenomicsDB PR.

**Comment by kdatta** [comment]
[PR-2588](https://github.com/broadinstitute/gatk/pull/2588) created

**Comment by cmnbroad** [comment]
The reason I was getting different behavior was because my local htsjdk was built from a fork, and it had stale tags. That doesn't matter for GATK, since the GATK build.gradle uses a resolution strategy of "force" for htsjdk, forcing it to use the version I specified (even though it looks old due to the old tags). But the gatk-protected build.gradle doesn't have an explicit resolution strategy declared, so gradle resolve by "pick the newest one". Since there are versions available via other transitive dependencies, it was choosing those over my local one.

**Comment by droazen** [comment]
This is done as a side effect of the repo merger -- closing
