### ISSUE TITLE
Could not find org.broadinstitute:barclay:1.0.0-24-g87c3fa2-SNAPSHOT

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/gatk#2579]
I just pulled to the latest version and was surprised to see `gradlew clean` not work!
```
$ ./gradlew clean
(...)
Could not find org.broadinstitute:barclay:1.0.0-24-g87c3fa2-SNAPSHOT
```

Reverting to 1.0.0-17-g30db73c-SNAPSHOT didn't work (same error).
Reverting to 1.0.0 made it fail somewhere else, with:
Could not resolve org.broadinstitute:gatk-bwamem-jni:1.0.0-rc1-SNAPSHOT

What's going on? Is there something wrong with my configuration?

**Comment by lbergelson** [comment]
I tried clearing my caches and rebuilding, but I resolve everything.  I noticed that our artifactory website looks much different today than it did yesterday.  I wonder if it was down temporarily for an update.  Maybe try again now? Unless they put it behind the firewall which would be a disaster... can you access https://artifactory.broadinstitute.org/?

**Comment by jean-philippe-martin** [comment]
I can access the artefactory web site.

I tried again, and the build worked! Must have been a transient issue. Thanks for checking!
