### ISSUE TITLE
fix negative RankSumTest annotation emission

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2587]
RankSumTest annotations with small negative values are sometimes emitted during GenotypeGVCFs where no annotation is emitted by gatk3.

**Comment by fleharty** [comment]
@lbergelson Do you have any input that reproduces these negative annotations?

**Comment by meganshand** [comment]
I have some input. If I give you a gvcf and a site location would that be enough?

**Comment by meganshand** [comment]
I put the input gVCF here: `/humgen/gsa-hpprojects/dev/mshand/palantir/Analysis/535_GenotypeGVCFs/inputVCF/shard-314.vcf.gz` (NOTE: this gVCF is hg38)

It seems that this happens for a bunch of different rank sums, but they happen at different sites. Here are some examples:

CHROM | POS | Type of RankSum
---|---|---
5 | 43293574 | BaseQRankSum
5 | 43299622 | ClippingRankSum
5 | 43515428 | MQRankSum
5 | 43197296 | ReadPosRankSum

**Comment by lbergelson** [comment]
Also important to note that that gvcf is not shareable publicly, so variants from it can't be directly added as test examples.

**Comment by meganshand** [comment]
This appears to be a bug in GATK3. The only cases where this happens is when the RankSum happens to be a negative round number (no decimal point) such as -2. 

The code in GATK3 is in ReferenceConfidenceVariantContextMerger::parseRemainingAnnotations:

```java
for (ReducibleAnnotationData value : currentData.getValue()) {
               try {
                    final String stringValue = value.getRawData();
                    if (stringValue.contains(".")) {
                        annotationValues.add(Double.parseDouble(stringValue));
                    } else if (Character.isDigit(stringValue.charAt(0))){
                        annotationValues.add(Integer.parseInt(stringValue));
                    //TODO: uncomment this to parse dbSNP membership annotation once allele-specific merging for that attribute is added
                    /*} else if (Character.isLetter(stringValue.charAt(0))) {
                        if (stringValue.equalsIgnoreCase("true"))
                            annotationValues.add(true);
                        else if (stringValue.equalsIgnoreCase("false"))
                            annotationValues.add(false);*/
                    }
                } catch (final NumberFormatException e) {
                    logger.warn("WARNING: remaining (non-reducible) annotations are assumed to be ints or doubles or booleans, but " + value.getRawData() + " doesn't parse and will not be annotated in the final VC.");
                }
}
```

Here it adds the value if it contains a decimal point or if the first character of the string is a digit. Since "-" isn't a digit it returns false without hitting that warning but doesn't add the annotation to the output.
