### ISSUE TITLE
Standardize long argument names to follow the "lowercase-with-dashes-as-separators" convention, with enforcement check in barclay

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2596]
As discussed in https://github.com/broadinstitute/picard/issues/786#issuecomment-293999711 and approved by @vdauwera , for the 4.0 release of GATK4 we are going to standardize all of our long argument names to follow the `--lowercase-with-dashes-as-separators` style, as opposed to the current inconsistent mix of camel case, underscores, and dashes.

As part of this, we should have an opt-in enforcement check in barclay to ensure that this convention is obeyed.

This change will be made more palatable for our users via https://github.com/broadinstitute/gatk/issues/1454, which is now targeted for 4.0

**Comment by droazen** [comment]
Assigning to @vdauwera for the 4.0 milestone

**Comment by davidbenjamin** [comment]
If this is up for voting, camel case makes more sense to me because this will involve command lines with a lot of dashes.

**Comment by magicDGS** [comment]
I'm with @davidbenjamin that a camel-case looks clearer, because there are very long names in the GATK-framework that may involve a lot of dashes.

Even if the bash-completion will help on this, for downstream projects it can be a nightmare to change this. For instance, I'm not planning to add the bash-completion generation to my toolkit, and I personally find difficult to read long arguments with tons of dashes...

**Comment by vdauwera** [comment]
My worry about camel case is that it trips up people a lot, especially those whose native language doesn't have a concept of case (like Chinese). 

Maybe long arguments with lots of dashes need to be refactored to have fewer... can you give some examples?

**Comment by lbergelson** [comment]
@magicDGS I'm curious, why not add the bash completion to your toolkit?

**Comment by magicDGS** [comment]
@vdauwera, I don't have a concrete example at this moment, but generally self-explanatory arguments are used in GATK. That's something that I personally like, but with dashes will become longer and, from my point of view,  less readable.

@lbergelson, my toolkit still uses the syntax of `java - jar Toolkit.jar` instead of a master-script... so completion code won't work. That's the main reason of not adding support yet.

**Comment by lbergelson** [comment]
Oh, that's a good point.  I wonder if there's a way we can get it to work for java -jar ToolkitName.

**Comment by magicDGS** [comment]
@vdauwera, examples of long arguments from the `StandardArgumentDefinitions`:

* `--disable-tool-default-read-filters`
* `--disable-sequence-dictionary-validation`
* `--add-output-sam-program-record`
* `--add-output-vcf-command-line`

This arguments are long anyway, but from my point of view it is more readable in the camel-case format; in addition, for the two last I have a question: is the upper-case format extension (SAM/VCF) going to be in lower-case? If not, there is still a mixture of upper/lower-case that may be confusing (and difficult to enforce).

**Comment by davidbenjamin** [comment]
@vdauwera For those of us on the m2 team our preference for camel case is less important than having the go-ahead for *something*.  Is `--lowercase-with-dashes-as-separators` definitely going to be our standard?  If so, we'll conform ASAP.

**Comment by vdauwera** [comment]
Thanks @magicDGS for the examples and sorry for the response lag. I find those are quite readable and would consider the camelcase version worse. 

Let's move ahead with `--lowercase-with-dashes-as-separators` as planned, as it's ultimately the least worst option. Formats should all be lowercased as well, so `sam`, `vcf` and so on.

**Comment by davidbenjamin** [comment]
@vdauwera Thanks for the guidance.  We'll get to work.  @takutosato, you were also wondering about this.  Here's our answer.

**Comment by magicDGS** [comment]
@vdauwera, thank you for taking into consideration my comments. One last comment is that the ReadFilter/tool names will be in camel case anyway, because their names come from a class. A mixture of lower/upper case in the command line will be unavoidable anyway.

Finally, I would like to ask for including a way in `Main` to remove the forcing behavior of the syntax, to be sure that downstream projects could set their standards in different ways. Thanks in advance!

**Comment by sooheelee** [comment]
@vdauwera Will this happen? If so, Sheila and I will need to know the new arguments for the GATK4 documentation that we are planning to work on for the next three weeks.

**Comment by droazen** [comment]
@magicDGS raises a good point that things like read filter names are necessarily going to be camel-cased. Does this change anyone's opinion on this topic?

**Comment by vdauwera** [comment]
Not mine -- toolnames are also still going to be camel-case

**Comment by magicDGS** [comment]
I would like to point out that my opinion is still the same: I prefer camel-case instead of kebab-case; anyway, the only requirement for me is to be able to turn off the requirement in downstream projects...

**Comment by sooheelee** [comment]
If we are to meet the documentation deadline you set for us @vdauwera (Jan 9), then we need to get to updating documents soon. We are waiting for the changes this issue ticket will bring about before getting started. Can you let us know when this will be implemented (if at all) so we can plan accordingly? Or can we push back the documentation deadline? Thanks.

**Comment by davidbenjamin** [comment]
@sooheelee It's already implemented in Mutect (code, documentation, and wdl).

**Comment by vdauwera** [comment]
I’d like to get the dev team involved — but will start a push over the weekend. Maybe you can make a list of the tools that we should tackle in priority?

**Comment by sooheelee** [comment]
Sheila and I have agreed the germline SNP and indel calling tools and supporting tools are the top priority @vdauwera. Then Mutect (thank you @davidbenjamin). Then anything that is in production-worthy status.

**Comment by sooheelee** [comment]
Based on @davidbenjamin's changes, I gather you all have agreed that this is kebab-case conversion is going to happen. If so, then our users also need fair warning so they too can plan time to adjust their scripts, etc. Also, I know we are in the habit of first warning parameters will be deprecated in the documentation before removing it. So, may I suggest a transition time where both conventions are recognized? 

We have exactly two months to the Jan 9 release as today is November 9. What is an appropriate amount of warning and an appropriate amount of transition time?

This will also give the Comms team time to update all our materials (workshop slides, hands-on tutorials, etc).

**Comment by vdauwera** [comment]
Doing a transition period is not practical — and anyway this is beta software, one of the caveats is that everything can change. We can post in the blog about it but that’s all the warning they get.

**Comment by vdauwera** [comment]
After the current workshop, there are no events until mid December, at which point it should be done or we’re in bad shape. 

So let’s just buckle down and do it. I’ll do a first pass over the weekend.

**Comment by sooheelee** [comment]
<https://github.com/broadinstitute/gatk/issues/3853> is dependent on this issue.

**Comment by sooheelee** [comment]
Actually, have used <https://github.com/broadinstitute/gatk/issues/3853> to enlist developer's hands with changing camel to snake case. So #3853 will resolve this issue (#2596).

**Comment by sooheelee** [comment]
@vdauwera Developers are asking for specifics on the KEBAB convention. Is there a document that outlines the rules, e.g. POSIX conventions?

**Comment by droazen** [comment]
We did this -- closing
