### ISSUE TITLE
Fix grossly inconsistent short vs. long argument names

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2597]
Some of our argument names have grossly inconsistent short vs. long names, like `-writeFullFormat,--never_trim_vcf_format_field`. For the 4.0 release we should do a pass to ensure that all short and long names are consistent with each other.

**Comment by droazen** [comment]
For @vdauwera and the 4.0 milestone.

**Comment by sooheelee** [comment]
@vdauwera We this happen? If so, Sheila and I will need to know the new arguments for the GATK4 documentation that we are planning to work on for the next three weeks.

**Comment by droazen** [comment]
This is not the ticket I was talking about @sooheelee -- the ticket you want is https://github.com/broadinstitute/gatk/issues/2596

**Comment by sooheelee** [comment]
Ok thanks!

**Comment by droazen** [comment]
Done
