### ISSUE TITLE
ReferenceUtils.loadFastaDictionary should throw a UserException if given an invalid .dict file.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#2609]

**Comment by droazen** [comment]
Re-assigning to @jonn-smith

**Comment by droazen** [comment]
For this ticket, we need to modify `ReferenceUtils.loadFastaDictionary()` to throw a `UserException` if the header returned from its `SAMTextHeaderCodec` contains no sequence dictionary
