### ISSUE TITLE
Add --batchSize argument to GenomicsDBImport

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2613]
For @kgururaj / @kdatta and the beta milestone.

**Comment by kdatta** [comment]
thanks

**Comment by droazen** [comment]
@kdatta Note that a requirement of this feature is that the batch size should limit the number of simultaneous `FeatureReaders` open at any given time. Each `FeatureReader` has an NIO buffer around its byte stream to make queries over GCS performant, and maintaining too many of such buffers at once would likely exceed any reasonable memory limits.

**Comment by droazen** [comment]
@kgururaj @kdatta Is a PR for this coming soon? We're going to need this argument to be able to run the tool with more than just a handful of samples.

**Comment by kdatta** [comment]
@droazen, I thought you guys are going to give it a shot first. I'm on it. I'll create the PR.

**Comment by droazen** [comment]
Unfortunately we have not had the free time this week to do it ourselves, so we'd be grateful if you could take it on -- thanks!

**Comment by droazen** [comment]
@kdatta How's this ticket going? Run into any problems we can help with?

**Comment by kdatta** [comment]
@droazen, things are going good. I will push code today.

**Comment by droazen** [comment]
@kdatta Ok, thanks!
