### ISSUE TITLE
Implement marker annotation for experimental tools, and hook up to barclay

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2623]
We should be able to annotate a tool as, eg., `@Experimental`, at the class level, and have that information show up in barclay-generated docs.

For beta, as discussed with @vdauwera

**Comment by cmnbroad** [comment]
Dup of https://github.com/broadinstitute/gatk/issues/2560

**Comment by droazen** [comment]
Whoops, thanks @cmnbroad !
