### ISSUE TITLE
Remove reference requirement from GenomicsDBFeatureReader constructor, if possible

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2624]
Currently we have to pass a reference file into the `GenomicsDBFeatureReader` constructor that takes a vidmap and callset JSON, like this:

```
            return new GenomicsDBFeatureReader<>(vidmapJson.getAbsolutePath(),
                                                 callsetJson.getAbsolutePath(),
                                                 workspace.getAbsolutePath(),
                                                 GenomicsDBImport.DEFAULT_ARRAY,
                                                 reference.getAbsolutePath(),
                                                 null,
                                                 new BCF2Codec());
```

We should try to remove the requirement to pass in a reference here, if possible, as it creates a lot of awkwardness for the engine.

@kgururaj @kdatta Can you comment on what the reference is currently being used for in `GenomicsDBFeatureReader`, and whether it might be possible to pass in a substitute (like a sequence dictionary, for example)?

**Comment by kgururaj** [comment]
The reference is used to obtain the reference base when a REF block gets split in the middle.
For example, if there are 2 samples:
S0: REF block interval chr1: [1, 100]
S1: REF block interval chr1: [1, 50]
The feature reader will create 2 reference block intervals chr1:[1-50], chr1:[51-100]. The reference base at chr1:51 can be obtained only from the reference genome.
This functionality is identical to the GATK-3 CombineGVCFS tool - it requires a reference genome also.

**Comment by droazen** [comment]
Alright, I guess this is not doable then -- closing!

**Comment by lbergelson** [comment]
I'm not sure this isn't doable..  It might make sense to bake the reference file into the gendb so that they're kept together.

**Comment by kgururaj** [comment]
The other option is to insert "N" for the REF in the VC objects when a reference genome isn't passed. Some other downstream tool must figure out the right base.

**Comment by lbergelson** [comment]
I think it's probably better to require it be passed in than give N's.  I think N's will potentially cause a lot of chaos in downstream tools
