### ISSUE TITLE
Remove wasteful List -> array conversion in MannWhitneyU client code

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2625]
Currently we have to convert from `List` to array in `RankSumTest` when calling into `MannWhitneyU`:

```
final MannWhitneyU.Result result = mannWhitneyU.test(Doubles.toArray(altQuals), Doubles.toArray(refQuals), MannWhitneyU.TestType.FIRST_DOMINATES);
```

Ideally we should avoid this wasteful conversion.

**Comment by droazen** [comment]
First step on this one is to run a profiler to determine if this even matters.

**Comment by jonn-smith** [comment]
Checked in JProfiler and this conversion isn't registering as taking any time.  Doesn't seem to be a problem.
