### ISSUE TITLE
class cast exception in GenotypeGVCFs

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2632]
tracking https://github.com/broadinstitute/gatk-protected/issues/1014

**Comment by droazen** [comment]
@kgururaj @kdatta Could you guys give us your thoughts on this error?

**Comment by lbergelson** [comment]
@droazen It's another bug of the type "the variant reader gives you back whatever the hell type of object it wants and you need to explicitely handle every case.  GenomicsDB is doing the right thing and handing over `int`, but we were expecting `String` because usually it does the wrong thing.  

I opened a ticket in htsjdk to talk about getters that are agnostic to the underlying type, https://github.com/samtools/htsjdk/issues/866, since they exist and look correct but are deprecated.

**Comment by kgururaj** [comment]
I'm guessing if you pass the VCFCodec to the GenomicsDBFeatureReader the error will go away. The BCF2Codec gives the correct types if I remember.

**Comment by droazen** [comment]
@kgururaj Right, but we want the extra performance provided by using the BCF2Codec, if at all possible..

**Comment by droazen** [comment]
This is now fixed in protected/master -- closing
