### ISSUE TITLE
GenotypeGVCFs doesn't index outputs on the fly

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2635]
It needs to call `GATKTool.createVCFWriter()` instead of `GATKVariantContextUtils.createVCFWriter()` in order to obey the engine argument `--createOutputVariantIndex`, which defaults to true.

**Comment by droazen** [comment]
@lbergelson Would you be able to do a quick PR today to fix this? If you don't have time, I can take it.

**Comment by lbergelson** [comment]
@droazen Pr is open here https://github.com/broadinstitute/gatk-protected/pull/1017
