### ISSUE TITLE
GenomicsDBImport seems to be dropping rsIDs

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2636]
@kdatta @kgururaj It seems like we're losing rsID's in the input gvcf when we load them into genomics db.  Is this deliberate to save space?  Is it a bug? Is it a configuration option that isn't exposed by `GenomicsDBImport`?  

I don't think it's important for production because they pass in a dbSNP at genotyping time so that can be recomputed, but it's causing issues in some of my tests.

**Comment by droazen** [comment]
@kdatta @kgururaj Can you comment on this?

**Comment by kgururaj** [comment]
In general, a field should be imported in TileDB/GenomicsDB iff the value is specific to the sample and the genomic position. The ID field value(s) is/are independent of the sample. Hence, we tended to ignore importing it.

Having said that, there is an option for importing the ID field in the PR. The Java VCF based importer will add an ID field by default.

**Comment by lbergelson** [comment]
closed by #2733

**Comment by droazen** [comment]
@lbergelson @kgururaj Do we have a test that proves this is resolved? Not sure we should close this if the answer is no...

**Comment by kgururaj** [comment]
CI tests in GenomicsDB - https://github.com/Intel-HLS/GenomicsDB/pull/116/files#diff-4d1bd3fdfc67d35993565f52590bd28f
