### ISSUE TITLE
Ported from Classic-GATK: Assembly not robust to changes in active region boundaries

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#267]
Originally from @vruano 

Depending of what ploidy we use AR may return different active region boundaries. This differences cause the haploid assembly to fail with the larger region hightlight the lack of robustness of the current approach. More concretely the problem seem to be the presence of cycle in the larger region

Files are located in 

```
/humgen/gsa-hpprojects/dev/valentin/bug-reports/non-rubsassembly-with-ploidy4

cd $THAT_DIR
sh ./run.sh
```

in CEUTrio*ploidy4.vcf the variant 20:22064431 is missing (as some other in the same region) which is a TP in knowledge base. 

If you look into the debug output ploidy2.err and ploidy4.err, the latter attempts to assemble a larger region failing due to a cycle. 

AR traversal comes out with different active region boundaries because the engine used takes as a parameter the ploidy. That is not by itself a bug and a bad think is just that the assembly fails for the extended region. 

The task here is to improve the assembly algorithm to cope with this situations better (perhaps handle cycles appropriately).

**Comment by davidbenjamin** [comment]
Dupe.
