### ISSUE TITLE
Add emitting of uncovered/"empty" to LocusWalkerSpark.

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#2679]
For more details, see...
https://github.com/broadinstitute/gatk/pull/2661

Also, see #2678 for an easier solution.

**Comment by droazen** [comment]
@LeeTL1220 Can this one be closed?

**Comment by LeeTL1220** [comment]
No.  PR not merged.

**Comment by droazen** [comment]
This was done -- closing
