### ISSUE TITLE
Ported from Classic-GATK: BQSR + PairHMM issue where Prob(insQual) + Prob(delQual) > 1

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#268]
It seems that insQual and delQual score may produce by BQSR or modified by the Indel error model may sum more than 1.  Eg. IQ = 1, DQ = 1 so 0.9 prob of an insertion and 0.9 prob of a deletion.

This would result Prob > 1 in PairHMM (a different bug from the previously reported to this regard). 

The question is how to fix this… must be controlled by BQSR/ index error model… should result in a warning and the qual adjusted to a maximum error probability.

**Comment by akiezun** [comment]
@vdauwera need a test case

**Comment by akiezun** [comment]
closing. @vdauwera please reopen if you have a test case
