### ISSUE TITLE
GenomicsDBImport is not hooked up to its progress meter

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2683]
This tool always emits "Processed 0 total records" at traversal end. We just need to hook it up to the standard progress meter.

**Comment by lbergelson** [comment]
I think we'll need to generalize the progress meter slightly to allow for different wording in the output message.  (and the position column will make no sense for this tool).

**Comment by droazen** [comment]
Yeah, I'm making that change in a branch right now.
