### ISSUE TITLE
GenomicsDB: max # of alleles should be configurable

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2687]
We're seeing messages like the following when running `GenomicsDBImport`:

```
Column 948660 has too many alleles in the combined VCF record : 61 : current limit : 50. Fields, such as  PL, with length equal to the number of genotypes will NOT be added for this location.
Column 948710 has too many alleles in the combined VCF record : 83 : current limit : 50. Fields, such as  PL, with length equal to the number of genotypes will NOT be added for this location.
```

Is this limit of 50 configurable, if we wanted to raise it, and if not, could it be made configurable?

**Comment by droazen** [comment]
Assigning to @kgururaj and @kdatta for an answer.

**Comment by droazen** [comment]
@lbergelson and @ldgauthier have confirmed that GATK CombineGVCFs (the predecessor to GenomicsDB) also had this same limit, so GenomicsDB is not doing anything radically new here. This ticket is just to ensure that the limit is configurable if it already isn't

**Comment by kgururaj** [comment]
Will add a variable to our Protobuf configuration object - the JSON already an option to set this.

**Comment by droazen** [comment]
Implemented in https://github.com/broadinstitute/gatk/pull/4645
