### ISSUE TITLE
how does the BwaSpark in GATK4 control the number of threads?

### ISSUE THREAD

**Issue by cattlepotato** [broadinstitute/gatk#2705]
I tried to ERR000589 process data with BwaSpark. The bam file size is 1.3G. The average time spent is about 25 min (5 nodes).
However it would only cost 5 min in processing same data if I tried to use original C bwa with 32 threads.
Base on this observation, I have several questions list as follow:
1. If there is anything wrong with my params?
2. For each Partition, is BwaSpark running in multi-thread mode?
3. How to control the number of the bwa threads inside BwaSpark?

P.S. 
The running command is:
./gatk-launch BwaSpark -I hdfs:///user/XX/ERR000589/ERR000589.bam -O hdfs:///user/XX/ERR000589/ERR000589_bwa.bam -R hdfs:///user/xx/refs/ucsc.hg19.fasta --bwamemIndexImage ~/data/ref/ucsc.hg19.img -disableSequenceDictionaryValidation true -- --sparkRunner SPARK --sparkMaster <master_url> --executor-cores 1 --total-executor-cores 16 --executor-memory 4G

I tried to further adjust the following parameters,
--executor-cores  --total-executor-cores  --executor-memory   --driver-memory
but none of these took less time than 16 min

Besides, I alsow tried to run it in local mode, while it won't end successfully. It seems that CPU was in endless waiting. I guess it occupied so much memory that the swap space is in use? Pic 1 shows the memory consumed while running 
This time, the command is:
./gatk-launch BwaSpark -I hdfs:///user/XX/ERR000589/ERR000589.bam -O hdfs:///user/xx/ERR000589/ERR000589.bwa.bam -R /software/home/xx/data/ref/ucsc.hg19.fasta \ --bwamemIndexImage ~/data/ref/ucsc.hg19.img -disableSequenceDictionaryValidation true -- --sparkRunner SPARK --sparkMaster local[*] --total-executor-cores 8 --executor-memory 20G --driver-memory 30G

BTW, the testing environment is:
CPU 2 X 8 physical core
node: 5    
network: GBE
memory: 64G
![memory](https://cloud.githubusercontent.com/assets/22440517/25929003/19a38210-3632-11e7-8dfc-c18f75604de6.png)
![cpu](https://cloud.githubusercontent.com/assets/22440517/25929008/205497ac-3632-11e7-8aa9-9c459d99371d.png)

**Comment by mwalker174** [comment]
BwaSpark uses 1 thread per task and there is no way to change that currently. I believe the default partition size is 64MB, so you have 1.3GB / 64MB = 21 partitions, which would give you enough parallelism if Spark decided to use 16 total tasks. 

Have you looked at the Spark UI? How many executors it is using? You may want to try using --num-executors 5 and --executor-cores 16 and then explicitly disabling Spark's dynamic resource allocation with --conf spark.dynamicAllocation.enabled=false. This is enabled by default on some servers (such as Google DataProc) and tends to override the settings you provide. 

Also note that --num-executors and --executor-cores specify the MAXIMUM it will use. Spark may decide not to use all those resources. If it doesn't, another idea is to try increasing the number of partitions by setting --bamPartitionSize <num_bytes> to something smaller than 64M.

**Comment by lbergelson** [comment]
@cattlepotato Since we haven't heard anything back in a while I'm hoping that Mark's suggestions helped.  I'm going to close this.  Feel free to reopen if you have more information or the suggestions did not help.
