### ISSUE TITLE
PSUtilsTest should be rewritten so it succeeds when it runs as root

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2708]
PSUtilsTest should be rewritten so it succeeds when it runs as root.  It could possibly make use of  `BaseTest.getSafeNonExistentFile()`.

**Comment by droazen** [comment]
Lee has already done this :)

**Comment by lbergelson** [comment]
Oh good!

**Comment by LeeTL1220** [comment]
@lbergelson @droazen This fix will appear in the PR that addresses issue #2457

**Comment by LeeTL1220** [comment]
@mwalker174 This is just FYI... you do not need to do anything.  You cannot assume that the user running the test doesn't have root access.  Also, I cleaned up the test a bit to use standard TestNG conventions (note the ``@ Test``):
```
    @Test(expectedExceptions = UserException.CouldNotCreateOutputFile.class)
    @SuppressWarnings("unchecked")
    public void testWriteTwoKryo() throws Exception {
        final File tempFile = createTempFile("test", ".dat");
        final Integer int_in = 29382;
        final String str_in = "test string";
        PSUtils.writeKryoTwo(tempFile.getPath(), int_in, str_in);

        final Kryo kryo = new Kryo();
        kryo.setReferences(false);
        final Input input = new Input(BucketUtils.openFile(tempFile.getPath(), null));
        final Integer int_out = (Integer) kryo.readClassAndObject(input);
        final String str_out = (String) kryo.readClassAndObject(input);
        input.close();

        Assert.assertEquals(int_in, int_out);
        Assert.assertEquals(str_in, str_out);

        // Point to a subdir that does not exist, so that we get a FNF exception
        PSUtils.writeKryoTwo(tempFile.getAbsolutePath() + "/bad_dir/bad_subdir/", int_out, str_out);
    }
```

Please note that this is not in ``master`` at the time of this writing.

**Comment by mwalker174** [comment]
@LeeTL1220 Thanks! Are the first and last lines the only thing you changed? The rest of it looks identical to the original. 

Will use the TestNG annotations in the future.

**Comment by droazen** [comment]
Should "Two" be "To"? :)
