### ISSUE TITLE
GenomicsDBImporter constructor calls generateSortedCallSetMap() to download headers to get sample names it already has

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2714]
I noticed, while looking at https://github.com/broadinstitute/gatk/issues/2713, that the main `GenomicsDBImporter` constructor calls `GenomicsDBImporter.generateSortedCallSetMap()` to download all VCF headers to get the sample names, but it already has the sample names passed in to it (as `variants.keySet()`). This sort of defeats the purpose of the `--sampleNameMap` argument in the `GenomicsDBImport` tool...

**Comment by droazen** [comment]
@kgururaj @kdatta could we get a fix for this?

**Comment by droazen** [comment]
Re-worded the title and description to make it clear that the call in question is happening in the constructor for `GenomicsDBImporter` (`GenomicsDBImporter` line 464)

**Comment by lbergelson** [comment]
@kdatta @kgururaj Do you have any update or ETA on this?  Can we help with this somehow?

**Comment by kdatta** [comment]
@lbergelson, was in back to back meetings today. I will release the code by tomorrow.

**Comment by lbergelson** [comment]
@kdatta Thank you, I see a PR for it in GenomicsDB :)

**Comment by lbergelson** [comment]
@kdatta It seems like the PR in genomicsDb addresses 2713 but not 2714.  Is there a fix coming for the much more important 2714?

**Comment by lbergelson** [comment]
close by #2733
