### ISSUE TITLE
GenomicsDBImporter constructor allows NPE to occur when sample name not found in sampleToVCMap

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2715]
It should instead notice that `sampleToVCMap.get()` has returned null, and throw a descriptive error message (including, crucially, the sample name in question) instead of allowing a `NullPointerException` to occur.

**Comment by droazen** [comment]
For @kgururaj / @kdatta . Relates to https://github.com/broadinstitute/gatk/issues/2713 and https://github.com/broadinstitute/gatk/issues/2714

**Comment by kdatta** [comment]
@droazen @lbergelson, in the new changes, I throw an illegal arugment exception if FeatureReader is null in the sampleToReaderMap. Also, if the sample name in the sampleToReaderMap does not match with the one in the header, I print a warning message. Let me know if these two changes fixes this issue.

**Comment by lbergelson** [comment]
close by #2733
