### ISSUE TITLE
spark-submit --master argument overridden in SparkContextFactory.java

### ISSUE THREAD

**Issue by david-wb** [broadinstitute/gatk#2718]
While testing BwaSpark on a yarn cluster, I noticed that only a single executor (the driver) was being created and running only on the master node. The worker nodes were idle. This happened when running the following command 

```
spark-submit \
--deploy-mode client \
--class org.broadinstitute.hellbender.Main \
--master yarn \
/home/hadoop/gatk-package-4.alpha.2-269-gdce8abc-SNAPSHOT-spark.jar BwaSpark \
--bwamemIndexImage /var/tmp/hs38DH-V.fasta.img \
-I hdfs:///unaligned.bam \
-O hdfs:///aligned.bam \
-R hdfs:///hg38/hs38DH-V.fasta \
--disableSequenceDictionaryValidation true
```

I checked the spark environment settings in the spark web UI and found that `spark.master` was set to `local` despite the `--master yarn` cmd-line argument. Next I checked the gatk source and found a suspicious call to `SparkConf.setMaster()` at line 138 in 
`src/main/java/org/broadinstitute/hellbender/engine/spark/SparkContextFactory.java`. I commented out this call, recompiled, and tried again, and the issue went away. I suspect that `setMaster()` was overriding the `--master yarn` cmd-line argument. I believe this is a bug and propose somehow avoiding `setMaster()` when the app is run with `spark-submit`.

Thanks,
David

**Comment by lbergelson** [comment]
@david-wb Interesting... what version of spark / spark submit are you using?  I was pretty sure that at the point where setMaster() was called by gatk the spark context was already created by yarn and setup with the appropriate master.  I wonder if it changed from a previous version of spark...

Alternatively, I may be misremembering and relying on the fact that our wrapper  script  supplies `--sparkMaster yarn` as a gatk argument which would probably override what's being set.  Could you try:
```
spark-submit \
--deploy-mode client \
--class org.broadinstitute.hellbender.Main \
--master yarn \
/home/hadoop/gatk-package-4.alpha.2-269-gdce8abc-SNAPSHOT-spark.jar BwaSpark \
--bwamemIndexImage /var/tmp/hs38DH-V.fasta.img \
-I hdfs:///unaligned.bam \
-O hdfs:///aligned.bam \
-R hdfs:///hg38/hs38DH-V.fasta \
--disableSequenceDictionaryValidation true
--sparkMaster yarn
```

or with the wrapper: 
```
GATK_SPARK_JAR_ENV_VARIABLE=/home/hadoop/gatk-package-4.alpha.2-269-gdce8abc-SNAPSHOT-spark.jar

./gatk-launch \
--bwamemIndexImage /var/tmp/hs38DH-V.fasta.img \
-I hdfs:///unaligned.bam \
-O hdfs:///aligned.bam \
-R hdfs:///hg38/hs38DH-V.fasta \
--disableSequenceDictionaryValidation true
-- \
--sparkRunner SPARK
--sparkMaster yarn
```

Our wrapper script sets a number of properties which we think are important for running our spark tools.  If running directly on spark you might want to set them explicitly.  Things like `-Dsamjdk.compression_level=1` have MAJOR performance implications.  

Also, be aware the BwaSpark is not in the best health at the moment may have issues. If you're running it you may want to run the version that's in this branch which is currently under review https://github.com/broadinstitute/gatk/pull/2494.

**Comment by david-wb** [comment]
I can confirm it works with the command 
```
spark-submit \
--deploy-mode client \
--class org.broadinstitute.hellbender.Main \
--master yarn \
/home/hadoop/gatk-package-4.alpha.2-269-gdce8abc-SNAPSHOT-spark.jar BwaSpark \
--bwamemIndexImage /var/tmp/hs38DH-V.fasta.img \
-I hdfs:///unaligned.bam \
-O hdfs:///aligned.bam \
-R hdfs:///hg38/hs38DH-V.fasta \
--disableSequenceDictionaryValidation true \
--sparkMaster yarn
```
so I guess it's really a minor issue. I can see it confusing other spark users though, who might expect spark configuration arguments to go through `spark-submit` rather than the application args, especially since the --sparkMaster app arg is optional. Just my two cents.

**Comment by lbergelson** [comment]
Yeah, it's definitely confusing, we should look into changing it for the future.  We definitely do recommend using our launcher script though, which handles it for you. 

It was tricky to enable both spark-submit and standalone running spark through the jar without having a way to inject the spark master as a command line argument, but there's probably a better way of handling it then the way we do.  

I'm keeping this issue open, but since it's a pretty easy workaround I don't know when we'll be able to fix it.
