### ISSUE TITLE
Invalid GZIP header when using -L -jdk_inflater=true

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2722]
Bug report recieved via email:  

I am testing GATK4 walker version. I tried the following command

./gatk-launch BaseRecalibrator -R human_g1k_v37_decoy.fasta -I NA12878.md.bam -O NA12878.br.table --knownSites 1000G_phase1.indels.b37.vcf **-L Broad.human.exome.b37.interval_list -jdk_inflater=true**

It will fail with the following error message `htsjdk.samtools.SAMFormatException: Invalid GZIP header`

If I run 
./gatk-launch BaseRecalibrator -R human_g1k_v37_decoy.fasta -I NA12878.md.bam -O NA12878.br.table --knownSites 1000G_phase1.indels.b37.vcf **-L Broad.human.exome.b37.interval_list**

or 

./gatk-launch BaseRecalibrator -R human_g1k_v37_decoy.fasta -I NA12878.md.bam -O NA12878.br.table --knownSites 1000G_phase1.indels.b37.vcf **-jdk_inflater=true**

or 

./gatk-launch BaseRecalibrator -R human_g1k_v37_decoy.fasta -I NA12878.md.bam -O NA12878.br.table --knownSites 1000G_phase1.indels.b37.vcf

all three will run with no problem. However when combined **-L and -jdk_inflater=true** it will fail with error. This problem is on both Intel system and Power system. It feels like an easy fix. Would you please look into that? Thanks!

**Comment by droazen** [comment]
First step is to see if we can replicate this using our own files, since we don't have the user's files.

**Comment by lbergelson** [comment]
I haven't been able to replicate this myself, but I emailed the original reporter to ask her for a proper stack trace.

**Comment by jonn-smith** [comment]
I was unable to reproduce this with some of our data sets.
