### ISSUE TITLE
Upgrade Barclay and integrate ExperimentalFeature annotation

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#2744]
Barclay defines the ExperimentalFeature annotation; displays it in command line program usage output, and also propagates an "experimental" property to the freemarker template used for doc. To fully manifest these in GATK we need to:

- update the custom doc templates used by GATK to recognize the "experimental" property
- update the command line output from --list/--help, which is generated directly by GATK, to look for the ExperimentalFeature annotation and display accordingly

**Comment by droazen** [comment]
Let's be sure to do this one this week :)
