### ISSUE TITLE
make GatherVCFs with NIO into a GATK tool

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2745]
We've patched GatherVCFs to allow it to read from NIO, but since it's a picard tool it's going to be reverted when we switch to depending on the real picard. We need to either port the changes to picard or make a gatk-tool version

**Comment by droazen** [comment]
Done

**Comment by cmnbroad** [comment]
@droazen - Seems like we should still make this (GatherVcfsCloud) a GATKTool at some point - right now its a CommandLineProgram.

**Comment by droazen** [comment]
Right, but this was was to make it a "GATK tool" (as opposed to a Picard tool), not necessarily a "`GATKTool`" (the class).
