### ISSUE TITLE
SVFastqUtils.FastqRead getName() returns the whole read descriptor.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#2754]
For a read with the following id line in the fastq:
    `@HJYFJCCXX160204:4:1124:22424:1133/1 mapping=20:61724009;151M`
This method would return pretty much the whole descriptor except for the starting '@':
  ` HJYFJCCXX160204:4:1124:22424:1133/1 mapping=20:61724009;151M`
Intuitively it should be only the first part, what an equivalent SAMRecord object getName() would return:
  `HJYFJCCXX160204:4:1124:22424:1133`

**Comment by SHuang-Broad** [comment]
Given that there will be a code freeze, I'll probably do this after the public-protected merge.

**Comment by SHuang-Broad** [comment]
Should this be closed now, after #3133 ?

**Comment by vruano** [comment]
Yes
