### ISSUE TITLE
Differences in QUAL in GenotypeGVCFs between GATK3 and GATK4

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/gatk#2756]
There are some insignificant differences between the QUAL score in GATK3 and GATK4 that we haven't been able to explain. This also means that QD is also different at those sites. Here are some examples (note that this data is private and cannot be used in public tests):

Input Combined gvcf: `/humgen/gsa-hpprojects/dev/mshand/palantir/Analysis/535_GenotypeGVCFs/inputVCF/shard-314.vcf.gz`

Chr | Site | QUAL in GATK3 | QUAL in GATK4 | QD in GATK3 | QD in GATK4
---|---|---|---|---|---
chr5 | 43191532 | 3233.06 | 3234.67 | 11.93 | 11.94
chr5 | 43298363 |  3233.06 | 3232.12 | 14.9 | 14.89

While these sites are clearly not significantly different, it would still be nice to know why these differences are occurring.

**Comment by sooheelee** [comment]
Looks like a rounding difference?

**Comment by meganshand** [comment]
Yup, most likely, but I haven't found the code that does the rounding.

**Comment by ronlevine** [comment]
It might be significant digits since it's showing for the larger values. One version might be using a double while the other is using a float.

**Comment by sooheelee** [comment]
Does GATK prefer the double or float? I see a lot of gatk-protected tools are expecting doubles. This has to do with the number of significant digits in the number, yes?

**Comment by ronlevine** [comment]
@sooheelee It's a mix of float and double, depending on the algorithm. This will determine the number of significant digits. A good explanation of single and double precision is [here](https://en.wikipedia.org/wiki/Floating-point_arithmetic#IEEE_754:_floating_point_in_modern_computers).

**Comment by sooheelee** [comment]
Are the HaplotypeCaller inputs identical? Are there default parameters that may have changed for GenotypeGVCFs between GATK3 and GATK4?

**Comment by sooheelee** [comment]
Did this get tied out? I see https://github.com/broadinstitute/palantir/pull/552

**Comment by droazen** [comment]
Yes, this was resolved -- closing
