### ISSUE TITLE
Differences in InbreedingCoeff in GenotypeGVCFs between GATK3 and GATK4

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/gatk#2757]
There are insignificant differences between InbreedingCoeff when calculated in GATK3 and GATK4. I've tried to recreate these differences and haven't been able to find them when I run with -L over a single site. There is nothing random in the Inbreeding Coefficient calculation as far as I can tell, so I'm not sure why I haven't been able to recreate the difference. When I run on a single site I get the same value that is output by GATK4 in both GATK3 and GATK4.

Here are some examples (note that this data is private and cannot be used in public tests):

Input Combined gvcf: `/humgen/gsa-hpprojects/dev/mshand/palantir/Analysis/535_GenotypeGVCFs/inputVCF/shard-314.vcf.gz`

Chr | Site | InbreedingCoeff in GATK3 | InbreedingCoeff in GATK4
---|---|---|---
chr5 | 43645663 | 0.2240 | 0.2253 
chr5 | 43645685 | 0.1697 | 0.1684

**Comment by davidbenjamin** [comment]
Insignificant differences no longer matter.
