### ISSUE TITLE
Gatk-Gatk-protected merger

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2768]
Merge the two repos into a single code base.

There are a number of goals, some somewhat contradictory:
 * maintain history of both repos
 * minimize repo size by removing large files that were accidentally committed to gatk-protected
 * merge git-lfs files
 * migrate issues from gatk-protected to gatk
 * merge travis builds
 * maintain reasonable test runtimes

**Comment by cmnbroad** [comment]
Maybe as a separate ticket/PR, but at some point we should consolidate files that mirror things in public, like GATKProtectedMathUtils and GATKProtectedVariantContextUtils.

**Comment by lbergelson** [comment]
I'll make this an epic and make tickets for each thing...

**Comment by droazen** [comment]
Closing this epic as 100% complete.
