### ISSUE TITLE
add documentation stylesheet to gatk repo

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2769]
Currently the html doc we build looks pretty ugly in the browser.  We don't have the appropriate style sheets available locally.  We should check those into the repo so that it can build a nice looking copy of the documentation.

**Comment by droazen** [comment]
@vdauwera Could you make this happen?

**Comment by vdauwera** [comment]
Sure. But we'll probably need to use some simpler stylesheets than what the website uses.

**Comment by vdauwera** [comment]
addressed in #3165
