### ISSUE TITLE
migrate issues from gatk-protected to gatk

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2774]
Migrate the issues and boards from gatk-protected to gatk.  We should try to do this in the least intrusive way possible that maintains the comment history as well as possible.

**Comment by lbergelson** [comment]
@vdauwera I'm assigning you here since you have experience with this.  Maybe we can talk about it on tuesday/wednesday and figure out what tool you used before.

**Comment by droazen** [comment]
Migration of issues from protected -> here is complete -- closing!

**Comment by lbergelson** [comment]
Ack, so much tedium!
