### ISSUE TITLE
Mutect2 and HaplotypeCaller lack the option to output active regions

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#2796]
This is a feature in GATK3 HaplotypeCaller that is yet to be ported to GATK4 HaplotypeCaller (which is in beta currently).

Given Mutect2 is ~~no longer~~ `still` in beta ~~(in production)~~, might consider adding this option.

The exact parameter name is `-ARO` or `--activeRegionOut`.

**Comment by davidbenjamin** [comment]
@sooheelee What does this output look like?  Could you paste a sample vcf line?

**Comment by vdauwera** [comment]
IIRC it's just an intervals file. It's a debugging option so not a priority for the beta release.

**Comment by sooheelee** [comment]
Had an internal user come around asking HaplotypeCaller questions the answer to which is to output an ARO. I was working on M2 documentation at the time and noticed then that this is not a current option. Since we have new parameters that allow users to tweak active region determination (min_variants_in_pileup, minNormalVariantFraction, and tumorStandardDeviationsThreshold), it would then follow that we should have an easy (non-compute-heavy) way to check the effects of changing these parameter values.

**Comment by vdauwera** [comment]
I agree that it's useful, just not urgent

**Comment by sooheelee** [comment]
Yes, I leave prioritization to you all.

**Comment by droazen** [comment]
It's been added to the 4.0 milestone.

**Comment by vdauwera** [comment]
Woohoo thanks for this

**Comment by sooheelee** [comment]
Thank you.
