### ISSUE TITLE
IndexFeatureFile produces an incorrect tabix index on .vcf.gz files with a large header

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2801]
@kcibul and @cmnbroad report that the `IndexFeatureFile` tool produces an incorrect tabix index on `.vcf.gz` files with a large header, such as hg38 vcfs. The symptoms of this appear to be that queries on the file return no records. Running tabix directly produces a correct index.

**Comment by magicDGS** [comment]
Something similar happens with BED files, and it is a known issue in HTSJDK: https://github.com/samtools/htsjdk/issues/393

I also implemented a failing test with BED file in a [PR](https://github.com/samtools/htsjdk/pull/820), but I don't dare to touch the tabix indexing code because I'm not familiar with the specifications.

**Comment by droazen** [comment]
@magicDGS Do you know if the index corruption is triggered only by files with large headers?

**Comment by magicDGS** [comment]
The BED problem is not about a large header, but about some problem with the first bins. I think that this will be similar here, because the header may affect the first bin... But it's just a guess...

**Comment by cmnbroad** [comment]
This problem happens with the IndexFactory [methods](https://github.com/samtools/htsjdk/blob/912c28bec415c430b43515652ccaf13222b07e7b/src/main/java/htsjdk/tribble/index/IndexFactory.java#L285) that take a file. When an index is created this way, the first feature that gets returned by the [FeatureIterator](https://github.com/samtools/htsjdk/blob/912c28bec415c430b43515652ccaf13222b07e7b/src/main/java/htsjdk/tribble/index/IndexFactory.java#L401) and handed to the [indexer](https://github.com/samtools/htsjdk/blob/912c28bec415c430b43515652ccaf13222b07e7b/src/main/java/htsjdk/tribble/index/IndexFactory.java#L352) always has it's file offset as 0, even if its actually offset by a header. Whether or not the bogus index that gets generated actually works is dependent on the size of the header.

When the index is created on the fly (while writing the file), the offsets are correct. The BED file issue is a slightly different problem (its first feature actually IS at offset 0), but the first feature is never returned.

**Comment by droazen** [comment]
Thanks for looking into this @cmnbroad !

* Does this issue only affect tabix indices, or all indices? 

* Does it only affect `IndexFeatureFile`, or other GATK4 tools as well? 

* Will an htsjdk patch be required?

* You say that the offsets are correct when indexing on the fly -- does this mean that a tabix index produced by `ApplyVQSR` on an hg38 `.vcf.gz` on-the-fly will be correct? Can you comment on https://github.com/broadinstitute/gatk/issues/2821 to confirm?

If this is the case, can you craft an integration test proving that `ApplyVQSR` creates a correct tabix index for an hg38 `.vcf.gz`? We should also probably disable tabix index creation in `IndexFeatureFile` temporarily until we can patch htsjdk.

**Comment by cmnbroad** [comment]
@droazen I have more work to do on this, but the short answers based on what I know so far:

- It affects anything that uses IndexFactory.FeatureIterator, so probably all index types.
- AFAICT it only affects IndexFeatureFile in GATK, but its possible there are other code paths.
- An htsjdk patch will definitely be required, though so far the only solution is see is pretty stateful and hacky. I don't think we should hold up beta for this if at all possible. I do think we should disable/beta IFF.
- I'll update #2821 with more info.

**Comment by cmnbroad** [comment]
Finally got to the bottom of these issues. Updated details are in https://github.com/samtools/htsjdk/issues/393.
