### ISSUE TITLE
Docker integration tests intermittently hit hard travis limit of 50 minutes

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2808]
After the merger with gatk-protected, the docker integration tests are intermittently (but frequently) hitting the hard travis time limit of 50 minutes. We need to fix this ASAP!

**Comment by droazen** [comment]
For @LeeTL1220

**Comment by LeeTL1220** [comment]
Not entirely sure on best approach to solve this.  We'll discuss Monday?

**Comment by lbergelson** [comment]
I talked to travis support and I believe this is now fixed:

From travis support:
> I've happily increased the timeout to 70 minutes on your broadinstitute/gatk repository. Please let me know if you need to increase it further.
