### ISSUE TITLE
Identify issues that were accidentally closed during import of protected

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#2814]
We've accidentally closed a lot of issues by merging gatk protected.  All of the commits from protected that included a "closed #X" now closed gatk public tickets by accident.  This is an unfortunate unforseen side effect.

**Comment by lbergelson** [comment]
@droazen :man_facepalming:   I wish we had thought of this ahead of time so we could have done the appropriate commit message rewrites...

**Comment by droazen** [comment]
It can't be very many issues -- we have 435 open issues in public, which is about what we had before...

**Comment by droazen** [comment]
Also the issue numbers would have to be <= 1116 (max issue number in protected). We are on issue 2814 here, which means only very ancient issues could have been closed.

**Comment by droazen** [comment]
I found them and re-opened them. There were three such accidentally closed issues: https://github.com/broadinstitute/gatk/issues/964, https://github.com/broadinstitute/gatk/issues/873, and https://github.com/broadinstitute/gatk/issues/302

**Comment by droazen** [comment]
Closing as resolved
