### ISSUE TITLE
Docker tests should upload TestNG report to bucket

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2817]
The standard integration/unit tests upload their test report -- the docker tests should as well.

**Comment by droazen** [comment]
Re-assigning to @jamesemery

**Comment by lbergelson** [comment]
I think the easiest way to do this is to mount a host directory into the docker where it will write it's output.

ex: ``` docker -v $( pwd )/build/reports:/build/reports ...```

**Comment by jamesemery** [comment]
Closed by this pull request https://github.com/broadinstitute/gatk/pull/3353.
