### ISSUE TITLE
Split integration tests into two roughly equal targets

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2818]
The current test report suggests that if we split off the tests in the `exome` package into a separate target, we would be close to a balanced 2-way split.

Possibly the right way to do this is to have two new values for `TEST_TYPE` in `build.gradle`: `cnvIntegration` and `nonCNVIntegration`. Specifying just `integration` would run all the integration tests, as before. Specifying `cnvIntegration` would run everything in the `exome`, `copynumber`, and `coveragemodel` packages. Specifying `nonCNVIntegration` would run everything outside of those packages.

**Comment by jamesemery** [comment]
We have already split off VariantCallingIntegration tests a while ago
