### ISSUE TITLE
Confirm that ApplyRecalibration indexes its output, and generates a correct tabix index for hg38 vcfs

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2821]
Let's double-check that `ApplyRecalibration` now indexes its outputs, and find out whether it generates correct tabix indices, or is affected by the possible htsjdk bug in https://github.com/broadinstitute/gatk/issues/2801

**Comment by cmnbroad** [comment]
I'll try to see if I can create a test to verify index creation. It will probably involve manually integrating an hg38 header with a clone of one of the existing tests, though, since I need something that matches a real recal file.

**Comment by droazen** [comment]
This is done!
