### ISSUE TITLE
Update to new gcloud release when it's out

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2822]
I'm told there will be a new gcloud release any day now (https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2110) with @jean-philippe-martin 's NIO retry fixes. We should update as soon as it's out, and confirm that it resolves https://github.com/broadinstitute/gatk/issues/2749, https://github.com/broadinstitute/gatk/issues/2685, and (possibly) https://github.com/broadinstitute/gatk/issues/2686

**Comment by jean-philippe-martin** [comment]
Note to self: the gcloud API changes a bit with the new release, apply the changes in [jp_gcloud_17_snapshot](https://github.com/broadinstitute/gatk/tree/jp_gcloud_17_snapshot) to adapt.

**Comment by droazen** [comment]
@jean-philippe-martin Looks like it's out!

**Comment by jean-philippe-martin** [comment]
Has it? I don't [see](https://mvnrepository.com/artifact/com.google.cloud/google-cloud-nio) any June release listed yet (?) The latest as of this writing is 0.18.0-alpha.

**Comment by droazen** [comment]
@jean-philippe-martin `https://github.com/GoogleCloudPlatform/google-cloud-java/releases/tag/v0.19.0` (released 4 hours ago)

**Comment by jean-philippe-martin** [comment]
Great! Let me update my pull request then.

**Comment by droazen** [comment]
This is done
