### ISSUE TITLE
Add support R needs X11/Cairo to be built for plotting

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2828]
@achevali commented on [Thu Nov 12 2015](https://github.com/broadinstitute/gatk-protected/issues/185)

---

@LeeTL1220 commented on [Wed Dec 02 2015](https://github.com/broadinstitute/gatk-protected/issues/185#issuecomment-161477822)

@achevali Is this just a simple doc change to make sure cairo and png are supported in a `capabilities()` call?

---

@samuelklee commented on [Wed Aug 17 2016](https://github.com/broadinstitute/gatk-protected/issues/185#issuecomment-240517725)

@achevali can we close this issue?

**Comment by samuelklee** [comment]
Ancient.
