### ISSUE TITLE
Review Valentin's notes on HC efficiency TODOs

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2829]
@vdauwera commented on [Fri Dec 18 2015](https://github.com/broadinstitute/gatk-protected/issues/259)

Back in July 2015, @vruano made a laundry list of issues suggesting possible improvements to HaplotypeCaller and related internals. They won't be done in GATK3 so  I tagged them as "HC-refactor" when I closed them. Whoever ports HC should review those suggestions so that @vruano's wisdom is not wasted. 

https://github.com/broadinstitute/gsa-unstable/issues?q=label%3AHC-refactor+is%3Aclosed

**Comment by davidbenjamin** [comment]
We have addressed these things.
