### ISSUE TITLE
Find a better way for determining the number of partitions/slices to use for Spark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2831]
@LeeTL1220 commented on [Mon Jan 04 2016](https://github.com/broadinstitute/gatk-protected/issues/276)

Particularly in the SVD spark calculations.  This is hardcoded to 50, which could cause issues later.

What is the best general strategy?

**Comment by samuelklee** [comment]
Don't think the hardcoded value really causes any issues, closing.
