### ISSUE TITLE
Support blacklisting regions for WGS

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2832]
@achevali commented on [Mon Jan 11 2016](https://github.com/broadinstitute/gatk-protected/issues/287)

Such as common germline cnv

---

@LeeTL1220 commented on [Tue Jan 26 2016](https://github.com/broadinstitute/gatk-protected/issues/287#issuecomment-175140271)

Given that we have a flag for pruning X, Y, and M/MT, I am putting the arbitrary blacklist for WGS to a later milestone.

**Comment by samuelklee** [comment]
This can be done trivially via `-L / -XL`.  What the blacklist should actually be is another issue...
