### ISSUE TITLE
Make sure that ``CreatePanelOfNormals`` can be run on spark cluster

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2834]
@LeeTL1220 commented on [Thu Jan 21 2016](https://github.com/broadinstitute/gatk-protected/issues/316)

How does the performance look?
This may also include having to troubleshoot adding a `sparkJar` artifact to `build.gradle`.

---

@LeeTL1220 commented on [Fri Jan 22 2016](https://github.com/broadinstitute/gatk-protected/issues/316#issuecomment-173938780)

Dependent on issue https://github.com/broadinstitute/gatk-protected/issues/317

**Comment by samuelklee** [comment]
Obviated by #2858.
