### ISSUE TITLE
Anonymize CNV PoNs

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2835]
@LeeTL1220 commented on [Mon Feb 01 2016](https://github.com/broadinstitute/gatk-protected/issues/343)

In `CreatePanelOfNormals` make anonymize a flag that defaults to `false`.  (i.e. `--anonymize`)  In other words, by default, we do _not_ produce an anonymized PoN.

We could also use a separate tool that takes a pre-existing PoN and anonymizes it.  

To anonymize a PoN:
- [ ] Determine which fields are private.  At the very least:  `fnt_control_matrix`, `log_normals`, and `log_normals_pinv`.  _There may be others -- please investigate as part of this issue_
- [ ] Have `CreatePanelOfNormals` delete the fields as the last step.
- [ ] Make sure that `HDF5PoN` produces reasonable error messages if one of these fields is accessed in an anonymized PoN.
- [ ] Create CLI that can take existing PoN and delete the fields.

---

@LeeTL1220 commented on [Mon Feb 01 2016](https://github.com/broadinstitute/gatk-protected/issues/343#issuecomment-178022285)

This is necessary since we may want to share PoNs and the PoN files cannot have any private data.

---

@LeeTL1220 commented on [Wed Mar 02 2016](https://github.com/broadinstitute/gatk-protected/issues/343#issuecomment-191420153)

Moving this to later milestone, unless it becomes more urgent.

**Comment by samuelklee** [comment]
We may still want to allow this for both gCNV and ModelSegments PoNs.

**Comment by mwalker174** [comment]
Closing this issue, as there doesn't seem to be an impetus for this feature.
