### ISSUE TITLE
Refactor segment classes.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2836]
@samuelklee commented on [Mon Feb 01 2016](https://github.com/broadinstitute/gatk-protected/issues/344)

Segment class that was reintroduced in the germline code requires reference to collection of Targets in constructor and also stores a call, segment mean, and number of targets.  ModeledSegment (used in CNV) now extends this and adds methods to transform CR/log2CR, and in turn ACNVModeledSegment (used in ACNV) extends ModeledSegment in https://github.com/broadinstitute/gatk-protected/pull/329.  However, this is awkward because ACNVModeledSegment does not store a call, segment mean, or number of targets.

I think we decided in https://github.com/broadinstitute/gatk-protected/issues/57, https://github.com/broadinstitute/gatk-protected/issues/61, https://github.com/broadinstitute/gatk-protected/issues/70, https://github.com/broadinstitute/gatk-protected/issues/71, etc. that Segments should simply query the relevant collection of Targets, especially for things like number of targets (which, correct me if I'm wrong, is only needed upon output to file), and that we should use SimpleInterval to represent a segment whenever possible.  This obviates the need to update internally held fields when merging segments, etc.

@LeeTL1220 @vruano @davidbenjamin we should probably get together and decide how these classes should be structured before moving them over into public.  I expect that some of this will also resolve once CNV's output is more along the lines of ACNV's (i.e., when it outputs posterior summaries).

**Comment by samuelklee** [comment]
Addressed in #2858.

**Comment by samuelklee** [comment]
Addressed by #3716.
