### ISSUE TITLE
Understand performance, profiling & how to optimize

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#284]
How do we profile and identify bottlenecks?

**Comment by akiezun** [comment]
assigning to @wbrockman to point us to resources (people or articles/materials) that will help

**Comment by jean-philippe-martin** [comment]
See this document for logging:
https://docs.google.com/document/d/1KlHklzpmnGfvWDyBfgVEjlDsAtlH81TvMEWjRuGQkWw/edit#heading=h.24wjirjf21g8

**Comment by wbrockman** [comment]
https://spark.apache.org/docs/1.2.0/monitoring.html is the basic overview of monitoring Spark applications.

**Comment by laserson** [comment]
Are you using Spark 1.2?  Just make sure you're using the right version of the docs, as this is a common pitfall.

**Comment by laserson** [comment]
Also check out some of the work by Jeff Hammerbacher's lab, like:
http://www.hammerlab.org/2015/02/27/monitoring-spark-with-graphite-and-grafana/
and
http://www.hammerlab.org/2015/07/25/spree-58-a-live-updating-web-ui-for-spark/

**Comment by akiezun** [comment]
we have spark 1.3 on prem (cdh 5.4.5 )

**Comment by wbrockman** [comment]
Thanks, good catch on the incorrect version of docs!  Still getting up to speed in the Spark world.

**Comment by akiezun** [comment]
@jean-philippe-martin should we turn this ticket into a section in the readme or wiki? What;s the plan here?

**Comment by jean-philippe-martin** [comment]
@akiezun understanding how to optimize a Spark job can apply to multiple projects, so it doesn't seem right to put this in the readme or wiki of this project. Ideally we'd write an article for a blog or a technical presentation.

**Comment by akiezun** [comment]
closing this in favor of #https://github.com/broadinstitute/gatk/issues/1377 and https://github.com/broadinstitute/gatk/issues/1376
