### ISSUE TITLE
ACNV on WGS workflow evaluation

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2840]
@LeeTL1220 commented on [Wed Mar 02 2016](https://github.com/broadinstitute/gatk-protected/issues/396)

We would like performance for WGS.  
Metrics could be: 
- sensitivity and precision
- concordance between multiple WGS replicates
- RMSE against HAPSEG results

Feel free to finalize this list...

**Comment by samuelklee** [comment]
This is addressed by #2858, closing.
