### ISSUE TITLE
Put generative coverage model into somatic code (part 1)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2842]
@davidbenjamin commented on [Thu Mar 31 2016](https://github.com/broadinstitute/gatk-protected/issues/432)

Before integrating this with probabilistic segmentation, which is more complicated for somatic than for germline, we can simply replace the current tangent normalization step with the mode of the likelihood (as a function of copy ratio) resulting from the generative coverage model.  This requires issues https://github.com/broadinstitute/gatk-protected/issues/429 and https://github.com/broadinstitute/gatk-protected/issues/430 to be completed.

---

@davidbenjamin commented on [Thu Mar 31 2016](https://github.com/broadinstitute/gatk-protected/issues/432#issuecomment-204015562)

Also, this should only be attempted if we get good results from doing the equivalent in the germline code, issue https://github.com/broadinstitute/gatk-protected/issues/431.  After it is done somatic and germline will share a PoN and all associated code, including tangent normalization.

---

@LeeTL1220 commented on [Mon Jun 06 2016](https://github.com/broadinstitute/gatk-protected/issues/432#issuecomment-223992660)

This only needs to be done if we stick with CBS for segmentation.  

At the very least, we need to implement this for checking performance against HMM.

**Comment by samuelklee** [comment]
Replaced by #4121.
