### ISSUE TITLE
Model FFPE

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2847]
@achevali commented on [Wed Apr 27 2016](https://github.com/broadinstitute/gatk-protected/issues/461)

Explicitly model FFPE which will vary across targets as a function of the time the sample has been in FFPE and probably the type as well.

**Comment by mwalker174** [comment]
@droazen Close this one as well? Unlikely to see FFPE-specific tools but I will note that this is of interest for future CNV modeling efforts.

**Comment by samuelklee** [comment]
Note that David R. is only on these issues because he's the one that ported them over from gatk-protected. I think it's safe to close this---I'd hope future denoising models would be more generalizable and able to handle FFPE (even if this might require e.g. FFPE-specific resource tracks).
