### ISSUE TITLE
HaplotypeCaller - bamOut does not respect --createOutputBamIndex true

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2849]
@akiezun commented on [Wed Apr 27 2016](https://github.com/broadinstitute/gatk-protected/issues/466)

tag 39c988c2dc7f669306d246a2191d16af50496640
```./gatk-launch HaplotypeCaller -I ~/IdeaProjects/gatk/src/test/resources/large/CEUTrio.HiSeq.WGS.b37.NA12878.20.21.bam -L 20:1-11000000 -R ~/IdeaProjects/gatk/src/test/resources/large/human_g1k_v37.20.21.fasta  -O testa.g.vcf -ERC GVCF --bamOutput testa.outHC.bam

```

the created bam file does not have an index created
```

**Comment by chandrans** [comment]
Thanks Chris! This will help us in our Mutect2 tutorial :)
