### ISSUE TITLE
Merge consecutive events in the truth en Germline Evaluation tool.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2852]
@vruano commented on [Wed May 04 2016](https://github.com/broadinstitute/gatk-protected/issues/492)

Currently if the truth (GenomeSTRiP vcf variants) are contiguous in target space we do not merge them thus they would count as several independent truth events when there is no way that an exome based tool would ever see them that way.

This issue is about adding an option so that these event can be merged.

This cannot be iniciated until the evaluation code has been merged into master.

**Comment by samuelklee** [comment]
We completely rewrote evaluation scripts for 4.0, so this is no longer relevant.
