### ISSUE TITLE
Give ReadCountCollection some features of TargetCollection

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2859]
@davidbenjamin commented on [Tue May 31 2016](https://github.com/broadinstitute/gatk-protected/issues/531)

`ReadCountCollection` should be able to query all targets / records in a given interval.  This will eliminate some unnatural-looking code, in particular anything involving `ReadCountRecord.SingleSampleRecord`.

**Comment by samuelklee** [comment]
In #2858 I give each `LocatableCollection` a method to create an `OverlapDetector` when necessary, which does the trick.  The new pipeline has no dependence on either `ReadCountCollection` or `TargetCollection`.
