### ISSUE TITLE
GenomeLoc special constants WHOLE_GENOME and UNMAPPED aren't well supported.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#286]
For example  operations like overlapP with WHOLE_GENOME should always return true for an mapped genome-loc (or WHOLE_GENOME itself). Seems that some if not many of this genome-loc operations do not observed these two constants...

**Comment by akiezun** [comment]
@vruano is this a bug?

**Comment by vruano** [comment]
I think it is a bug, but since is supposed to disappear I guess it might well not be worth the work.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/166
