### ISSUE TITLE
Spark-ify ``GetBayesianHetPulldown``

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2861]
@LeeTL1220 commented on [Fri Jun 17 2016](https://github.com/broadinstitute/gatk-protected/issues/567)

Waiting on improvements in the GATK engine that will be in place for HaplotypeCaller.

The issue is that partitions cannot share reads, which is problematic for intervals (SNP sites) near the edge of a partition.

**Comment by samuelklee** [comment]
I think this was basically addressed by #2968.
