### ISSUE TITLE
R code does not have access to changes in column names/file formats

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2862]
@achevali commented on [Fri Jun 17 2016](https://github.com/broadinstitute/gatk-protected/issues/572)

We have issues that may arise due to future changes in file formats which make it difficult to both:
1. Ensure that files are being used correctly
2. Run files that have different sample names

Currently we have hardcoded file formats separately for R. If these change, R code needs to be changed or it will fail. 

ACNV plotting takes in a segment file, a tangent file, and a snp file.

Segment file and tangent file both have sample names within them. We take sample name from segment file and use that. Currently we use the sample name from the segment file as canonical.

**Comment by samuelklee** [comment]
Better sample name validation is done on the java side of plotting in #2858, but otherwise I don't really see a way around hardcoding column names in the R code that isn't more trouble than it's worth.
