### ISSUE TITLE
enable --includeNonVariantSites GenotypeGVCFS option

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2865]
@lbergelson commented on [Tue Jun 21 2016](https://github.com/broadinstitute/gatk-protected/issues/580)

Update genotype gvcfs so includeNonVariantSites can be enabled.  This may be easiest by implementing a different walker type to match the old LocusWalker behavoir but could also be done by accumulating sites as it goes.

---

@lbergelson commented on [Fri Apr 07 2017](https://github.com/broadinstitute/gatk-protected/issues/580#issuecomment-292661735)

this is blocked by  broadinstitute/gatk#2429

**Comment by chandrans** [comment]
We have at least 4 users who are excited for this to go in.

**Comment by jleinenbach** [comment]
Whatshap needs this option.

**Comment by melisakman** [comment]
It would be great to have this option. +1 here!

**Comment by nealplatt** [comment]
I'd love to see this option implemented.

**Comment by citscisean** [comment]
I would love to see this as well.

**Comment by jiyongkun** [comment]
I need this option as well!

**Comment by danilovkiri** [comment]
Me too!

**Comment by jjfarrell** [comment]
I also need this option.

**Comment by marchoeppner** [comment]
Same...

**Comment by janrehker** [comment]
This feature would help me obliterate a horrible, horrible hack in my pipeline, thus replacing it with a solution of delight and beauty.
+1

**Comment by droazen** [comment]
May be able to use the existing `MultiVariantWalkerGroupedOnStart` traversal

**Comment by droazen** [comment]
Re-assigning to @cmnbroad

**Comment by 13am** [comment]
+1

**Comment by sooheelee** [comment]
Opened to connect to the relevant PR at https://github.com/broadinstitute/gatk/pull/5219.
