### ISSUE TITLE
delete files that were moved to gatk

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2869]
@lbergelson commented on [Fri Jul 01 2016](https://github.com/broadinstitute/gatk-protected/issues/598)

We currently have files that were moved from gatk-protected to gatk but never deleted in gatk-protected.   See https://github.com/broadinstitute/gatk/pull/1888.  Since these moved without changing packages we have duplicate files with the same exact identifiers.  We should figure out how to prevent this in the future, possibly by giving gatk-protected its own package.  

We should check the affected files before deleting because I think there may have diverged from the versions in public.

**Comment by davidbenjamin** [comment]
@lbergelson I think this was automatically moved from gatk-protected via ZenHub, but does it make any sense in this repo?

**Comment by lbergelson** [comment]
Nope
