### ISSUE TITLE
Port bug fix for GVCF block merging.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2870]
@samuelklee commented on [Wed Jul 06 2016](https://github.com/broadinstitute/gatk-protected/issues/602)

See https://github.com/broadinstitute/gsa-unstable/pull/1431.

---

@samuelklee commented on [Tue Jul 26 2016](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-235368315)

Also see broadinstitute/gsa-unstable#1440.

---

@samuelklee commented on [Wed Apr 19 2017](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-295471040)

@lbergelson were these fixes ported?

---

@lbergelson commented on [Thu Apr 20 2017](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-295807498)

@samuelklee I don't think so, not by me at least. 

---

@ronlevine commented on [Mon Apr 24 2017](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-296712948)

@samuelklee Would you like me to do the port? It will require both gatk and gatk-protected changes.

---

@samuelklee commented on [Mon Apr 24 2017](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-296749077)

If you don't mind, @ronlevine, please go ahead---I probably won't get around to it for a bit.  Not high priority though, I was just going through and cleaning up issues.

---

@ronlevine commented on [Mon Apr 24 2017](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-296750806)

Will do.

---

@ronlevine commented on [Wed Apr 26 2017](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-297488855)

Closing since https://github.com/broadinstitute/gatk/pull/2619 is merged.

---

@ronlevine commented on [Wed Apr 26 2017](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-297566792)

Reopening since need to do the protected part.

---

@samuelklee commented on [Mon May 08 2017](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-300044005)

Also note that https://github.com/broadinstitute/gsa-unstable/pull/1451 should be included in this port.

---

@ronlevine commented on [Mon May 08 2017](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-300047651)

The HaplotypeCaller tests that compare the output GVCFs between the current code and GATK 3.5 will not pass. This is due the block merging fix. So, I generated output files with with a version of GATK 3 that has this fix, 3.7-42-gbe6a37c. If it's premature for these tests, they can be disabled.

---

@droazen commented on [Mon May 08 2017](https://github.com/broadinstitute/gatk-protected/issues/602#issuecomment-300049046)

Please don't either disable these tests or move them to GATK 3.7 outputs just yet -- this would be disruptive to my current efforts to figure out what's behind some annotation differences in the GATK4 HaplotypeCaller. I do plan to migrate the tests to 3.7 outputs soon, but I need to study the diffs a bit first.

**Comment by ronlevine** [comment]
Closing, already merged:
https://github.com/broadinstitute/gatk/commit/93dea7d151dcc15f60b63b444922ad2b5cbfc4c0
https://github.com/broadinstitute/gatk/commit/dc08fad3cf58efd711985126f1c4999adbf4b63a
