### ISSUE TITLE
ClusteringGenomicHMMSegmenter can fail if random memory length exceeds maximum allowed.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2877]
@samuelklee commented on [Tue Aug 09 2016](https://github.com/broadinstitute/gatk-protected/issues/640)

This combined with an unset random seed was causing `AlleleFractionSegmenter.testChromosomesOnDifferentSegments` to fail intermittently in #633.  @davidbenjamin could you take a look when you get back?  This could be fixed easily by a `Math.min` in the right place, but I don't know if the fact that the memory length seems to blow up is something generic that happens when we collapse to a single state that needs to be addressed more carefully.

---

@samuelklee commented on [Wed Aug 17 2016](https://github.com/broadinstitute/gatk-protected/issues/640#issuecomment-240523360)

@davidbenjamin can you take a quick look?  I think it's probably a quick fix.

---

@davidbenjamin commented on [Wed Aug 17 2016](https://github.com/broadinstitute/gatk-protected/issues/640#issuecomment-240530369)

Sure.

**Comment by samuelklee** [comment]
Obviated by #2858.
