### ISSUE TITLE
Determine and document best practices for CNV..

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2881]
@samuelklee commented on [Thu Aug 11 2016](https://github.com/broadinstitute/gatk-protected/issues/644)

We currently have some recommendations for coverage collection that were based on recapseg, but it would be good to revisit them with GATK CNV and the new coverage model/HMM segmentation.  In addition, GC bias correction has been implemented in the workflow, but it is not yet evaluated.

Documentation and and scripts to generate evaluations and plots showing the effects on GATK CNV, the new coverage model, and downstream tools (e.g., ACNV) are needed.
- [ ] target padding
- [ ] keeping duplicates
- [ ] GC bias correction
- [ ] sequence repeat correction
- [ ] target filtering

---

@samuelklee commented on [Wed Apr 19 2017](https://github.com/broadinstitute/gatk-protected/issues/644#issuecomment-295360224)

I am planning on removing sequence repeat correction to close #645.  We can reimplement and reevaluate in the future.

**Comment by samuelklee** [comment]
We can also investigate the impact of using the common-sites list generated in #4069 vs. the one we are running now.

**Comment by nyl2002** [comment]
For germline CNV:
It would be interesting to know which details (e.g. read group tags such as platform, model or also average insert size) are important for choosing additional Fastq/BAM files for creating a Panel of Normals (PON), when one does not have access to a batch.

Which results from the GATK quality metrics would be most useful for choosing such datasets?

I'm thinking especially about e.g. choosing other Fastq/BAM files from the Personal Genomes Project.


It would also be interesting to know if something like a "Panel of Unnormals" could be created, e.g. by choosing datasets from similar patients according to participant survey results from the Personal Genomes Project (https://my.pgp-hms.org/google_surveys).

If a Panel of Normals can be used to reject spurious read counts, then a Panel of Unnormals could help to not reject rare read counts.

Taking Ehlers-Danlos-Syndrome as an unsolved and probably multi-gene example, there are 115 hits grepping the above surveys and at least a few of these might offer full fastq/bam files.

**Comment by samuelklee** [comment]
Thanks for your input, @nyl2002!  We do have some plans to investigate clustering on metrics to determine cohorts for PoN building.  @ldgauthier @yfarjoun I'll open a new issue.

**Comment by samuelklee** [comment]
We can revisit once #4122 and #4123 are in place.
