### ISSUE TITLE
NaN in GC annotations of Y contig

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2882]
@mbabadi commented on [Fri Aug 26 2016](https://github.com/broadinstitute/gatk-protected/issues/651)

I get NaNs in GC annotated targets:

Ref: /seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta 
target: /xchip/cga/reference/capseg/targets/hg19/whole_exome_agilent_1.1_refseq_plus_3_boosters.Homo_sapiens_assembly19.targets.bed

Here's the complete list of NaN annotations:
Y       1447301 1447907 target_189424_CRLF2     NaN
Y       1449665 1450247 target_189425_CRLF2     NaN
Y       1451033 1451608 target_189426_CRLF2     NaN
Y       1455244 1455902 target_189427_CRLF2     NaN
Y       1455921 1456562 target_189428_CRLF2     NaN
Y       1457883 1458870 target_189429_CRLF2     NaN
Y       1460541 1461152 target_189430_CRLF2     NaN
Y       1471911 1472632 target_189431_CRLF2     NaN
Y       1481374 1481997 target_189432_CRLF2     NaN
Y       1486615 1487259 target_189433_CRLF2     NaN
Y       1487624 1488257 target_189434_CRLF2     NaN
Y       1490300 1490985 target_189435_CRLF2     NaN
Y       1494167 1494830 target_189436_CRLF2     NaN
Y       1496376 1497264 target_189437_CRLF2     NaN
Y       1500911 1501520 target_189438_CRLF2     NaN
Y       1503664 1504226 target_189439_CRLF2     NaN
Y       1504336 1504901 target_189440_CRLF2     NaN
Y       1507739 1508287 target_189441_CRLF2     NaN
Y       1510828 1511460 target_189442_CRLF2     NaN
Y       1521390 1521983 target_189443_CRLF2     NaN
Y       1534121 1535701 target_189444_CRLF2     NaN
Y       1662105 1663367 target_189445_AKAP17A   NaN
Y       1664026 1664675 target_189446_AKAP17A   NaN
Y       1667834 1668575 target_189447_AKAP17A   NaN
Y       1669301 1670737 target_189448_AKAP17A   NaN
Y       1683842 1684411 target_189449_ASMT      NaN
Y       1691781 1692456 target_189450_ASMT      NaN
Y       1692911 1693541 target_189451_ASMT      NaN
Y       1696345 1696914 target_189452_ASMT      NaN
Y       1698463 1699082 target_189453_ASMT      NaN
Y       1701792 1702433 target_189454_ASMT      NaN
Y       1705080 1705703 target_189455_ASMT      NaN
Y       1711445 1712157 target_189456_ASMT      NaN
Y       2088831 2089520 target_189457_DHRSX     NaN
Y       2110813 2111521 target_189458_DHRSX     NaN
Y       2134530 2135238 target_189459_DHRSX     NaN
Y       2159292 2159894 target_189460_DHRSX     NaN
Y       2276535 2277104 target_189461_DHRSX     NaN
Y       2292987 2293595 target_189462_DHRSX     NaN
Y       2356425 2359010 target_189463_DHRSX     NaN
Y       2368607 2369216 target_189464_DHRSX     NaN
Y       2559151 2559718 target_189465_CD99      NaN
Y       2582212 2582745 target_189466_CD99      NaN
Y       2585395 2585943 target_189467_CD99      NaN
Y       2587451 2587996 target_189468_CD99      NaN
Y       2588146 2588715 target_189469_CD99      NaN
Y       2590417 2590965 target_189470_CD99      NaN
Y       2591104 2591655 target_189471_CD99      NaN
Y       2594050 2594664 target_189472_CD99      NaN
Y       2605990 2606547 target_189473_CD99      NaN
Y       2608569 2609095 target_189474_CD99      NaN
Y       59106289        59107656        target_189877_SPRY3     NaN
Y       59221885        59222531        target_189878_VAMP7     NaN
Y       59228041        59228599        target_189879_VAMP7     NaN
Y       59230531        59231169        target_189880_VAMP7     NaN
Y       59232916        59233507        target_189881_VAMP7     NaN
Y       59252232        59252800        target_189882_VAMP7     NaN
Y       59272120        59272713        target_189883_VAMP7     NaN
Y       59274302        59274871        target_189884_VAMP7     NaN
Y       59330180        59330708        target_189885_IL9R      NaN
Y       59333828        59334429        target_189886_IL9R      NaN
Y       59335302        59335904        target_189887_IL9R      NaN
Y       59335905        59336289        target_189888_IL9R      NaN
Y       59336290        59336776        target_189889_IL9R      NaN
Y       59336840        59337486        target_189890_IL9R      NaN
Y       59337698        59338400        target_189891_IL9R      NaN
Y       59338503        59339109        target_189892_IL9R      NaN
Y       59339943        59340528        target_189893_IL9R      NaN
Y       59342236        59343330        target_189894_IL9R      NaN

---

@mbabadi commented on [Fri Aug 26 2016](https://github.com/broadinstitute/gatk-protected/issues/651#issuecomment-242767764)

@davidbenjamin could you please take a look? it sounds like it could be a problem with the reference missing these regions.

---

@mbabadi commented on [Fri Aug 26 2016](https://github.com/broadinstitute/gatk-protected/issues/651#issuecomment-242774747)

OK it turns out that the reference is hard masked and has "N" in that region. Nevertheless, we shouldn't get NaNs. In my opinion, the correct behavior is to drop targets on which GC percentage can not be defined + emit informative error messages.

---

@davidbenjamin commented on [Sun Sep 11 2016](https://github.com/broadinstitute/gatk-protected/issues/651#issuecomment-246177779)

I will address this.

---

@mbabadi commented on [Tue Sep 27 2016](https://github.com/broadinstitute/gatk-protected/issues/651#issuecomment-250018497)

@davidbenjamin also, CorrectGCBias produces NaNs when a sample has very low coverage. I think the correct behavior is this:

(1) when annotating targets, it is OK to produce NaNs on targets whose GC bias can not be determined. When correcting for GC bias, those targets must be removed altogether.

(2) if the bias curve can not be determined (let's say because of low coverage), the tool should remove that sample from the collection and emit appropriate warning messages. If all samples are removed, the tool should produce a bad input error.

---

@mbabadi commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/651#issuecomment-302466279)

@asmirnov239 can you review and if the issue is resolved, close?

**Comment by samuelklee** [comment]
We drop regions containing all Ns in the pipelines before they get to GC-bias correction.
