### ISSUE TITLE
Optimize allele-fraction model

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2884]
@samuelklee commented on [Thu Sep 01 2016](https://github.com/broadinstitute/gatk-protected/issues/662)

See comments in #660.  Runtime is now about 30-40 minutes for an exome with default parameters, which is a little high.

I think we could explore implementing a version of the AF model where the reference bias is not integrated out.  This might require more iterations to converge, but on the other hand conditional likelihoods might be cheaper to calculate.

**Comment by samuelklee** [comment]
Closing this, see comments in #2858.
