### ISSUE TITLE
Use only log_2 or real space for copy ratios.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2886]
@samuelklee commented on [Thu Sep 01 2016](https://github.com/broadinstitute/gatk-protected/issues/665)

Documentation is spotty and it's hard to tell which is being used where.  Along with #615 I think this will make things a lot easier for us.

**Comment by samuelklee** [comment]
Addressed in #2858.

**Comment by samuelklee** [comment]
Closed in #3729.
