### ISSUE TITLE
Remove NON_REF from allSites VCF output

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2889]
@ronlevine commented on [Thu Sep 08 2016](https://github.com/broadinstitute/gatk-protected/issues/692)

Port https://github.com/broadinstitute/gsa-unstable/pull/1470.

---

@ronlevine commented on [Thu Dec 15 2016](https://github.com/broadinstitute/gatk-protected/issues/692#issuecomment-267362572)

This will have to wait since -allSites is not yet supported.

**Comment by davidbenjamin** [comment]
Closed by #6406.
