### ISSUE TITLE
New Mutect PoN

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2891]
@davidbenjamin commented on [Fri Sep 09 2016](https://github.com/broadinstitute/gatk-protected/issues/700)

Currently, `Mutect2` hard filters a candidate somatic variant if any event occurs at the same locus in the panel of normal samples.  The idea is to avoid false positive calls at inherently noisy sites.  This approach is reasonable but perhaps we can improve it.  Some thoughts:
- Asymptotically, as the size of the PoN goes to infinity eventually every site will have some event and we will filter out every variant.  Obviously this is an unrealistic limit, but a model should always perform better with more data.
- It might be good to use the PoN to learn a probabilistic model of error at each site, similar to the tool EBCall which has been noted to perform quite well on indels.
- regardless of our model, we should consider alternatives to hard filtering, such as perhaps using the PoN to penalize a somatic quality score.

**Comment by davidbenjamin** [comment]
Subdividing this issue.
