### ISSUE TITLE
Better implementation of CNV-avoidance regularizer for unevenly spaced targets

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2892]
@mbabadi commented on [Fri Sep 09 2016](https://github.com/broadinstitute/gatk-protected/issues/701)

The present implementation of the CNV-avoidance regularizer in the new coverage model assumes evenly spaced targets on a single contig. It does not take into account the fact that targets on different chromosomes are "infinitely" separated. Agilent/Ice targets are very unevenly spaced and the distribution of target spacing has a heavy tail, making the matter worse.

The regularizer could still be used with certain modifications. Let us define the "target coverage noise" for sample s as:

u_{st} = \sum_{\mu} W_{t \mu} z_{s \mu} + m_t

(1) [implementation] First of all, the target coverage noise must be regularized on each contig separately. It doesn't make sense to stack up all targets and take once giant FFT of u_{st}. This can be fixed in the current implementation with little effort.

(2) [formal development + implementation] Within each contig, u_{st} must be mapped from target space to genomic position space e.g. via kernel density estimation. It is crucial to take into account the uncertainty in density estimation in the penalty function. For example, if the pre-image of a genomic position $x$ lies at the middle of a certain target $t$, the estimated value is much more reliable than the case where it lies between two largely separated targets. The penalty must be weighted according to the certainty of estimation.

(3) [formal development + implementation] once step 1 and 2 are done, the iterative solver code must be updated accordingly.

---

@mbabadi commented on [Fri Sep 09 2016](https://github.com/broadinstitute/gatk-protected/issues/701#issuecomment-246015485)

@samuelklee @davidbenjamin @asmirnov239 Let's have a joint meeting at some point to discuss the problem. It is (probably) not too hard to figure out, and it will make our model really shine!

---

@mbabadi commented on [Tue Sep 13 2016](https://github.com/broadinstitute/gatk-protected/issues/701#issuecomment-246822768)

I have some notes written on this which I can discuss tomorrow in the CNV meeting.

---

@mbabadi commented on [Tue Sep 27 2016](https://github.com/broadinstitute/gatk-protected/issues/701#issuecomment-249735634)

Here's a nice demonstration @asmirnov239 @samuelklee @davidbenjamin. The first sample is denoised with D=2 principal components, the second with D=8 principal components. The obvious deletion events are gone. All common events will be absorbed in the PoN once one spends "enough" principal components. According to Genome STRiP, the disappeared deletions are indeed common in the samples used to make the PoN.

ps> apparently, several points in the lower "better" plot (with D=8) look noisier compared to the "worse" D=2 plot. This is an illusion -- those points are way out in D=2 and do not appear in the upper plot. 
![chr_3_events](https://cloud.githubusercontent.com/assets/15305869/18863954/f0b620ec-8461-11e6-83eb-c7d8d23a9e6b.png)
![chr_3_no_events](https://cloud.githubusercontent.com/assets/15305869/18863957/f3aee996-8461-11e6-9a62-50b7614bce7b.png)

---

@mbabadi commented on [Tue Sep 27 2016](https://github.com/broadinstitute/gatk-protected/issues/701#issuecomment-249760868)

@asmirnov239 this looks very much like your simulated data -- there will be a significant penalty associated to picking up those deletions as noise.

**Comment by samuelklee** [comment]
We're taking a different approach for common CNVs, closing.
