### ISSUE TITLE
Port fix 1475 from GATK3

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2893]
@SHuang-Broad commented on [Tue Sep 13 2016](https://github.com/broadinstitute/gatk-protected/issues/706)

[Here](https://github.com/broadinstitute/gsa-unstable/pull/1475), but the alt allele removal functions must be ported to protected first, preferably by the original author @vruano.

**Comment by davidbenjamin** [comment]
GATK4 currently does not have this issue.
