### ISSUE TITLE
Detect anomalous samples during/after coverage PoN creation

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2895]
@mbabadi commented on [Tue Sep 20 2016](https://github.com/broadinstitute/gatk-protected/issues/710)

It happens often that the users attempt to make a coverage PoN from samples that come from different sequencing platforms, for example, let say platforms A and B. In this situation, some principal components will have strong projections onto A, and some onto B. We need to be able to identify such anomalies, either during PoN creations or in a post-processing step.

**Comment by samuelklee** [comment]
Dupe of #4060.
