### ISSUE TITLE
Improve the performance of forward-backward algorithm by caching emission likelihoods

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2896]
@mbabadi commented on [Tue Sep 20 2016](https://github.com/broadinstitute/gatk-protected/issues/711)

The title says it all. Emission probability calculation is quite expensive in the new coverage model and we need many such calls (in particular for random sampling).

**Comment by samuelklee** [comment]
@mbabadi Is this still relevant?

**Comment by samuelklee** [comment]
Closing this.  Future implementations will probably use stochastic inference rather than caching.
