### ISSUE TITLE
If PoN QC removes all samples and the number of input samples is small, should we automatically disable the QC?

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2899]
@LeeTL1220 commented on [Fri Sep 30 2016](https://github.com/broadinstitute/gatk-protected/issues/729)

On a small corpus of samples, it seems the that the PoN QC is quite aggressive and will remove all samples.  Can we have it automatically bypass the QC step?

**Comment by samuelklee** [comment]
No QC in #2858, better QC in gCNV.  Closing.
