### ISSUE TITLE
``CombineReadCounts`` should allow duplicate sample names

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2900]
@LeeTL1220 commented on [Thu Oct 06 2016](https://github.com/broadinstitute/gatk-protected/issues/732)

Rename the columns to *_1, *_2, etc.

The allowing of renaming should be a flag that goes into `CombineReadCounts` and default duplicate sample names should be disallowed.
I.e....
`--allow-multiple-replicates` default to false...

**Comment by samuelklee** [comment]
Duplicates are still disallowed in #2858.  Unless there is a strong argument for allowing them, closing this.
