### ISSUE TITLE
When upgrading Firehose to the next version of GATK for CNV toolchain, make sure to change the CNLoH task to call the correct CLI

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2903]
@LeeTL1220 commented on [Tue Oct 18 2016](https://github.com/broadinstitute/gatk-protected/issues/742)

Should now be `CallAllelicSplits`

Rename the task configuration as well.

**Comment by samuelklee** [comment]
I do not think we are continuing Firehose support at this point.
