### ISSUE TITLE
Update forum posts for the name change in CNLoH caller

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2904]
@LeeTL1220 commented on [Tue Oct 18 2016](https://github.com/broadinstitute/gatk-protected/issues/743)

Now called `CallAllelicSplits` 

This should happen after (or right before) the next release.
- [ ] Update forum posts
- [ ] Add forum post explaining the output of the cnb_called files

See issue #585

**Comment by sooheelee** [comment]
This is moot given the Somatic CNV workflow has completely changed.
