### ISSUE TITLE
Standardize gCNV PoN output

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2905]
@mbabadi commented on [Wed Oct 19 2016](https://github.com/broadinstitute/gatk-protected/issues/745)

The PoN must:

- [x] Contain as much non-trivial information as possible:
    \* Model parameters (W, \Psi, m; also, ordered norms of W)
    \* Sample names used to make the PoN
    \* Posterior expectations (\gamma, z, d, total remove variance, total unexplained variance)
    \* Useful distributions (bootstrapped distribution of log likelihoods and sample-specific variances)
    \* Command-line used to make the PoN (add a log file to the HDF5 bundle in the end)

- [x] Be human-readable ideally. Binary dumps are fast but are difficult to work with in debugging.
- [ ] Encapsulated and easily shared, perhaps via HDF5 bundles

---

@mbabadi commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/745#issuecomment-302465665)

This is partially addressed in PR https://github.com/broadinstitute/gatk-protected/pull/857. We must, however, decide whether or not we want to bundle models into HDF5 blobs.

**Comment by samuelklee** [comment]
We handle this relatively reasonably in the new gCNV.  The WDL outputs an array of compressed model directories; each directory corresponds to a scattered interval block and contains model posterior summaries in a human readable format.
