### ISSUE TITLE
Understand what causes subpar coverage denoising in certain WES samples

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2906]
@mbabadi commented on [Wed Oct 19 2016](https://github.com/broadinstitute/gatk-protected/issues/746)

Here are some possible culprits:

1) Low base call quality
2) Low mapping quality
3) Significantly different noise covariates (i.e. sample coming from a different platform, or a bizarre library preparation/sequencing issue resulting in a different bias modality)

(1) and (2) can be investigated by taking a few good and bad BAMs and studying the distribution of their base/mapping qualities.

(3) can be studied in various ways.

One approach is as follows:

Make PoNs with different numbers of principal components D and plot the total denoising power (TDP), defined as ||W z_s||^2, for each sample as a function D. For "good" samples, we expect a steady increase of TDP vs. D. For "bad" samples, we expect a lag; why? for small D, most benefit comes from choosing principal components that describe the bias covariates of "good" samples (majority). Eventually, they will be depleted and further data likelihood gains will require dedicating the next principal components to "bad" samples (minority).

Another (complementary) approach is as follows:

Fix D to a reasonable value such that a differentiation between good and bad samples is still noticeable (remember: if D = #samples, no signal is left after denoising, so D should be still). Next, obtain the empirical distribution of z_s^\mu, i.e. the projection of each sample s over each principal component \mu. If bad samples do not regress, it shows the incompatibility of their bias covariates with the rest of the samples.

---

@mbabadi commented on [Wed Oct 19 2016](https://github.com/broadinstitute/gatk-protected/issues/746#issuecomment-254800421)

@davidbenjamin @samuelklee anything to add?

**Comment by samuelklee** [comment]
I think preclustering as in #4170 and related work handles this satisfactorily.  We can add QC post-gCNV via #4060.
