### ISSUE TITLE
Evaluate gCNV for rare germline CNV events

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2907]
@mbabadi commented on [Wed Oct 19 2016](https://github.com/broadinstitute/gatk-protected/issues/747)

We use Genome STRiP TCGA/GPC2 call sets as ground truth.

It is desirable to evaluate:

(1) XHMM and CODEX vs. GATK (almost done @asmirnov239)
(2) GATK ROC curves as a function of bias latent space dimension D
(3) GATK ROC curves for a fixed D, and for different unexplained variance models: (isotropic, target-resolved, adaptive), w/ and wo/ sample-specific unexplained variance calling during PoN creations, and calling. That is, 3 x 2 x 2 = 12 cases.

---

@mbabadi commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/747#issuecomment-302465336)

This was done a while ago. Keeping open for upcoming evaluations.

**Comment by kuanlinhuang** [comment]
Related to this when would the best practices for this analysis be released:
https://software.broadinstitute.org/gatk/best-practices/

**Comment by samuelklee** [comment]
Opening a new issue for evaluating the new version of gCNV.  @kuanlinhuang We will release Best Practices recommendations for this workflow, including suggested parameter values for various data types typically generated at the Broad, when this new round of evaluations is complete.
