### ISSUE TITLE
A probabilistic extension of coverage collection

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2908]
@mbabadi commented on [Wed Oct 19 2016](https://github.com/broadinstitute/gatk-protected/issues/748)

At the moment, CalculateTargetCoverage simply counts the number of overlapping reads with each target. Optionally, low quality calls are hard filtered.

Here, we propose a probabilistic approach that avoids the usage of hard filters and fits well with the new probabilistic target coverage modeler.

By definition, mapping quality MAPQ = -10 \log_10{mapping position is wrong} (see http://samtools.github.io/hts-specs/SAMv1.pdf, pg 5, item 5). It is defined in the range [0, 2^8-1]. The specific value 255 is reserved for when MAPQ is not available. Most MAPQs are well below 255.

We consider the following process for assigning reads to each target. Pick a read "k" aligned to target "t" with a given MAPQ_k. By definition, it maps to the genomic position "x" with p_x = 1 - 10^{-MAPQ_k/10}, and to some other position with probability 1 - p_x. We refer to the alignment genomic position of read k as x_k, and the exome target(s) it overlaps with T_k.

Let's assume we have T exome targets, and let z_{kt} be a 1-of-#T indicator variable for a read where t is a target and #T is the number of all exome targets.

\pi_{kq} = P(z_{kq} = 1) =

   p_k x O_{kq}     if q \in T_k
   (1 - p_k) / (#T - #T_k)    if q \notin T_k

Here, O_{kq} is the fractional overlap of the read to an exome target q. Note that since we don't have the information about the next best alignment position, we take a flat prior.

Finally, the number of reads belonging to target t, n_t, reads as:

n_t = \sum_k z_{kt}

Since there are many reads, n_t will be approximately Gaussian. It is an elementary calculation to calculate coverage mean E[n_t] and coverage variance var[n_t] in terms of \pi_{kq}. In the probabilistic target coverage model, var[n_t] will be added to the statistical noise.

So, the read count collection will have two entries for each target: coverage mean, and coverage variance.

---

@mbabadi commented on [Wed Oct 19 2016](https://github.com/broadinstitute/gatk-protected/issues/748#issuecomment-254812286)

@samuelklee @asmirnov239 
The outcome of https://github.com/broadinstitute/gatk-protected/issues/746 will indicate whether or not we'll need this. Andrey already has a preliminary indication that a fair fraction (50%!) of reads have mapping quality < 20. This implies a very significant coverage variance. Feeding this information into the probabilistic target coverage modeler is guaranteed to significantly reduce FDR.

**Comment by samuelklee** [comment]
I think we are probably OK with hard filters on counts for the foreseeable future.
