### ISSUE TITLE
Purity-ploidy inference tool.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2909]
@samuelklee commented on [Wed Oct 19 2016](https://github.com/broadinstitute/gatk-protected/issues/750)

Tool for inferring mixture of CNV subclones from ACNV output.
- [x] Develop resources for simulating tumor phylogenies/mixtures
- Wrote python code for simulating phylogenies and generating corresponding truth tables for CN profiles, ACNV segment files (with varying noise---i.e., CR and MAF credible-interval sizes---and purity levels), and plots.
- [x] Design basic algorithm
- Gibbs sampling MCMC of Dirichlet mixture of CNV subclones, to start.  Graphical model is written down.
- [x] Implement basic algorithm
- CLI roughly implemented in sl_purity_ploidy_mcmc branch.  Could stand some refactoring and code cleanup before it is PR ready and needs tests.
- [x] Algorithm improvements
- Currently, the model is initialized assuming a 50-50 normal-tumor split and only a clonal population.  This is run for ~100 MCMC iterations, and the result is used to initialize a second run that expands the number of populations.  This tends to work reasonably well, but there are situations where the model can get stuck in incorrect, degenerate solutions.  Going to try adding some MH steps that will swap populations to see if these can help get the model unstuck.
- Need to add outlier absorption to the model, which appears to be critical for inference of subclonal populations from real data (i.e., ACNV output), which may have spurious segments, oversegmentation, etc.  Simple clonal models appear to work reasonably well without this, though.
- [x] Evaluate algorithm on simulated data.
- Implemented simple Queue pipeline for running CLI on simulated ACNV segment files.  Takes <2 minutes for ~1000 iterations for each sample, can run 100s of samples in parallel on the gsa clusters.
- Need to write up some scripts to automatically calculate and plot metrics.
- [x] Evaluate algorithm on real data
- Some initial runs on HCC1143 purity series show reasonable results for the clonal model, i.e., purity is recovered within credible intervals (question: what are the error bars on the purities of the samples?).  Subclonal performance is a little less clear due to 1) no real ground truth, 2) events in the normal, and 3) lack of outlier absorption.
- Can we get a hold of some cleaner purity series?
- [ ] Document algorithm in technical whitepaper

---

@samuelklee commented on [Thu Dec 08 2016](https://github.com/broadinstitute/gatk-protected/issues/750#issuecomment-265798051)

The first release of this tool will most likely include the following:

- Some refactoring to MCMC package and addition of an EnsembleSampler, which implements affine-invariant ensemble sampling from Goodman & Weare 2010 (this is the same method used by the emcee python package).  This method is critical for sampling our highly multimodal posterior well.

- Output of 1) all population fraction / ploidy MCMC samples, and 2) average variant profile and 3) posterior summaries at the posterior mode (determined by naive binning of samples).

- No plotting.

Early next quarter:

- [ ] Unit tests for EnsembleSampler.

- [ ] Allowing for >1 tumor population.  The model already allows for this, but some performance optimization of the variant-profile sampling step will probably be required.

- [ ] Evaluation on BAMs prepared with mixing scripts.

- [ ] Writeup of model in technical white paper.

- [ ] Tool to produce interactive plots.  I think this is necessary to represent the uncertainty in "solutions" produced by the tool.

**Comment by samuelklee** [comment]
#4116 can build on the previous work done here.
