### ISSUE TITLE
Limit haplotypes in M2

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2921]
@davidbenjamin commented on [Wed Nov 30 2016](https://github.com/broadinstitute/gatk-protected/issues/805)

Since Mutect2 runs on a single human's worth of samples i.e. a tumor and an optional normal, we should never see more than a few haplotypes at any location.  We might therefore be able to increase speed dramatically by setting the 'maxNumHaplotypesInPopulation' argument to a smaller value than its default of 128.  The question is whether we can do this without hurting sensitivity.

**Comment by davidbenjamin** [comment]
Junction trees.
