### ISSUE TITLE
SparkGenomeReadCounts emits "null" message 

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2922]
@eddiebroad commented on [Thu Dec 01 2016](https://github.com/broadinstitute/gatk-protected/issues/806)

An issue encountered with gatk-protected "SparkGenomeReadCounts" tool is a non-helpful "null" error message.  A non-helpful error "null" message was printed by gatk-protected with the command-line below
during the course of trying to use it on/in FireCloud:

```
+ java -Xmx48g -jar fc-7ac504fc-7fe4-4bc1-89d3-7f16317b8ff4/eddie.jar SparkGenomeReadCounts --outputFile this.entity_id.coverage.tsv --reference fc-e2421839-93d5-4ed5-8861-593f00364e54/Homo_sapiens_assembly19.fasta --input firecloud-tcga-open-access/tutorial/bams/C835.HCC1143_BL.4.bam --binsize 5000
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/cromwell_root/tmp
 .....
......
......
proceeding with flushing remote transports.
***********************************************************************

null

***********************************************************************
```

To try to make a more helpful error message appear I added a "catch" block after a call to runTool in instanceMainPostParseArgs  in file CommandLineProgram.java and got a more helpful message about a missing dictionary file: 

        try {
        return runTool();
        } 
        catch(Exception e) {
            e.getStackTrace();
            }

java.lang.RuntimeException: org.broadinstitute.hellbender.exceptions.UserException$MissingReferenceDictFile
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:204)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:95)
	at org.broadinstitute.hellbender.Main.instanceMain(Main.java:103)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:115)
	at org.broadinstitute.hellbender.Main.main(Main.java:152)
Caused by: org.broadinstitute.hellbender.exceptions.UserException$MissingReferenceDictFile
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeReference(GATKSparkTool.java:409)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeToolInputs(GATKSparkTool.java:355)
	at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:346)
	at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:111)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	... 5 more

To bring about success I added 4 lines of code : 

```
    ln -vs ${ref_fasta} ; 
    ln -vs ${ref_fasta_fai} ;
    ln -vs ${ref_fasta_dict} ;
    FASTA_NAME=`basename ${ref_fasta} `;  

```

Then, instead of --reference ${ref_fasta} in calling gatk-protected, I put --reference  $FASTA_NAME and the "null" exception went away and the program run successfully.

---

@eddiebroad commented on [Thu Dec 01 2016](https://github.com/broadinstitute/gatk-protected/issues/806#issuecomment-264264203)

per @droazen :  @achevali @LeeTL1220 

---

@LeeTL1220 commented on [Tue Dec 06 2016](https://github.com/broadinstitute/gatk-protected/issues/806#issuecomment-265342816)

@eddiebroad Before this gets assigned, what version of gatk-protected are you using?
Assuming that this is a version we built (despite the name "eddie.jar"): @achevali , can you figure out how you are reporting the error.  @droazen are you sure this is not in the engine?

---

@eddiebroad commented on [Wed Dec 07 2016](https://github.com/broadinstitute/gatk-protected/issues/806#issuecomment-265464665)

@LeeTL1220 

The original JAVA JAR where I first observed the "null" message I presume was based off commit 3a2bb0d.  At the time the project was initiated I think it was the latest commit.     The original JAR where the "null" message was observed was gatk-protected-all-3a2bb0d-SNAPSHOT-spark_standalone.jar  .   Because of the "3a2bb0d" in the JAR file name is why I presume that it's based off commit 3a2bb0d.   

From the gatk-protected repo code (and also "gatk" repo)  I added some debug/print statements and saved to a differently named JAR "eddie.jar" to help me distinguish my hacking from the original JAR.  

The JAVA file where I added the most helpful statements was in CommandLineProgram.java which is actually in "gatk" repo (not "gatk-protected" repo)

If I look at a LOG, I can see "EAS" my initials and see c40e75b which appears to be a more recent commit compared to 3a2bb0d

```
EAS in main!!!!
EAS to call instanceMain second....
EAS to call instanceMain first....
17:28:40.295 INFO  SparkGenomeReadCounts - EAS ABOUT TO CALL instanceMainPostParseArgs in  instanceMain  in clp.java 
17:28:40.396 INFO  IntelGKLUtils - Trying to load Intel GKL library from:
	jar:file:/cromwell_root/fc-7ac504fc-7fe4-4bc1-89d3-7f16317b8ff4/eddie.jar!/com/intel/gkl/native/libIntelGKL.so
17:28:40.498 INFO  IntelGKLUtils - Intel GKL library loaded from classpath.
[December 1, 2016 5:28:40 PM UTC] org.broadinstitute.hellbender.tools.genome.SparkGenomeReadCounts  --binsize 5000 --outputFile this.entity_id.coverage.tsv --reference Homo_sapiens_assembly19.fasta --input firecloud-tcga-open-access/tutorial/bams/C835.HCC1143_BL.4.bam  --keepXYMT false --readValidationStringency SILENT --interval_set_rule UNION --interval_padding 0 --interval_exclusion_padding 0 --bamPartitionSize 0 --disableSequenceDictionaryValidation false --shardedOutput false --numReducers 0 --sparkMaster local[*] --help false --version false --verbosity INFO --QUIET false --use_jdk_deflater false --disableAllReadFilters false
[December 1, 2016 5:28:40 PM UTC] Executing as root@71bfa07f6996 on Linux 3.16.0-0.bpo.4-amd64 amd64; OpenJDK 64-Bit Server VM 1.8.0_111-8u111-b14-2~bpo8+1-b14; Version: Version:c40e75b-SNAPSHOT
17:28:40.501 INFO  SparkGenomeReadCounts - Defaults.BUFFER_SIZE : 131072
```

---

@eddiebroad commented on [Wed Dec 07 2016](https://github.com/broadinstitute/gatk-protected/issues/806#issuecomment-265470147)

I want to mention in my case, all the reference files were present (fasta, fai, dict) BUT the dict was in a different directory and NOT in the same directory as the other two files (which were in the same directory) and that's why the dict was not found and that's why the soft link creation fixed the issue.

---

@droazen commented on [Wed Dec 07 2016](https://github.com/broadinstitute/gatk-protected/issues/806#issuecomment-265491329)

@LeeTL1220 It's very possibly in the engine -- if the tool itself gets cleared of blame, feel free to bounce this one back to gatk public.

**Comment by samuelklee** [comment]
Fixed in #3524.
