### ISSUE TITLE
using set -x

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2923]
@eddiebroad commented on [Thu Dec 08 2016](https://github.com/broadinstitute/gatk-protected/issues/817)

As a standard practice, whenever I write WDL, I have as my first command "set -x".
The command causes bash to print the commands it actually runs to stderr.
See Table 2-1 here
http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_02_03.html

@LeeTL1220 mentioned that this practice be good in the WDLs of gatk-protected so, per him, I write this issue.

**Comment by samuelklee** [comment]
I think this should be contained in the WDL style guide.
