### ISSUE TITLE
Sample-specific OB Filter

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2926]
@LeeTL1220 commented on [Tue Dec 20 2016](https://github.com/broadinstitute/gatk-protected/issues/830)

Currently, it will apply the one preAdapterQ file to all samples in a single VCF.  There should be a way to specify different files for each sample in the VCF.

This also means that the summary output file will list the same preAdapterQ value for all samples, which is incorrect for the NORMAL in a tumor-normal VCF file.

Supported:
- Tumor-normal pair (but the normal must have 0/0 GT in all genotypes)
- Tumor-only

The solution to this issue is to also support (within one VCF):
- Trios
- Multiple tumor samples

**Comment by davidbenjamin** [comment]
The new orientation bias model is sample-specific.
