### ISSUE TITLE
gCNV miscellaneous optimizations and code improvements left from PR review

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2931]
@mbabadi commented on [Thu Jan 12 2017](https://github.com/broadinstitute/gatk-protected/issues/853)

- [ ] thread capping in `SynchronizedUnivariateSolver`
- [ ] faster calculation of prior copy number contribution to log likelihood in `IntegerCopyNumberExpectationsCalculator`
- [ ] optimize `CoverageModelEMWorkspace.replaceMaskedEntries` using Nd4j native ops

**Comment by mbabadi** [comment]
Deprecated by the new gCNV. Closing.
