### ISSUE TITLE
GetBayesianHetCoverage hangs indefinitely.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2933]
@samuelklee commented on [Thu Jan 19 2017](https://github.com/broadinstitute/gatk-protected/issues/863)

We've had a few reports of this---let's look into it.

---

@mbabadi commented on [Thu Jan 19 2017](https://github.com/broadinstitute/gatk-protected/issues/863#issuecomment-273861786)

The only thing that comes to my mind is that GetBayesianHetCoverage enables indexing in samtools/htsjdk by default and GetHetCoverage disables it in most cases. Can you gather a few problematic samples?

---

@samuelklee commented on [Thu Jan 19 2017](https://github.com/broadinstitute/gatk-protected/issues/863#issuecomment-273871723)

Yup, got a user on the forum that I'm trying to get more information from.  @dlivitz have you run into any samples that you could pass along?

---

@LeeTL1220 commented on [Fri Jan 20 2017](https://github.com/broadinstitute/gatk-protected/issues/863#issuecomment-274081867)

I've had this issue.

---

@LeeTL1220 commented on [Wed Jan 25 2017](https://github.com/broadinstitute/gatk-protected/issues/863#issuecomment-275125293)

This may be related to #865 , since I am having an issue like this as well...

I believe it relates to the number of intervals (i.e. size of the SNP list).

A ton of time is being spent during initialization on ``DiskBasedBAMFileIndex.getSpanOverlapping`` and ``AbstractBamFileIndex.query`` when you have a long interval list.  I am not 100% sure that this is the same issue as here, but symptoms look the same.  I saw 50k intervals taking about 50 sec to init, but when I ran 500k intervals I just killed it after half an hour.

**Comment by samuelklee** [comment]
Deleted in #3903.
