### ISSUE TITLE
Mutect2 should report Loss of heterozygosity at germline variant sites

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2934]
@lbergelson commented on [Mon Jan 23 2017](https://github.com/broadinstitute/gatk-protected/issues/864)

If I remember correctly, Mutect-Classic filtered out sites that had germline calls at them.  This meant it didn't report somatic mutations that involved loss of heterozygosity or new alleles at variant germline sites.  Mutect 2 should report these sites as variant.  

@davidangb Not sure if this already happens, but it seems like a good thing to fix if it doesn't.

---

@vdauwera commented on [Mon Jan 23 2017](https://github.com/broadinstitute/gatk-protected/issues/864#issuecomment-274585906)

I support this feature request.

---

@davidbenjamin commented on [Wed Jan 25 2017](https://github.com/broadinstitute/gatk-protected/issues/864#issuecomment-275116409)

@lbergelson LoH is a great idea that we don't do already; we *do* handle new alleles at germline variant sites now.

---

@davidbenjamin commented on [Wed Apr 19 2017](https://github.com/broadinstitute/gatk-protected/issues/864#issuecomment-294329953)

Actually, I'm having second thoughts.  LoH is a copy-number event that occurs in chunks, so we could end up emitting (and spending CPU time on) a huge number of additional sites.  Also, @samuelklee is there any reason not to leave the LoH-finding to aCNV?

---

@davidbenjamin commented on [Wed Apr 19 2017](https://github.com/broadinstitute/gatk-protected/issues/864#issuecomment-295324137)

Yeah, LoH is aCNV's job.  Mutect would do the same thing at much greater expense and with less power.

---

@lbergelson commented on [Wed Apr 19 2017](https://github.com/broadinstitute/gatk-protected/issues/864#issuecomment-295335240)

@davidbenjamin, aCNV won't detect point mutations leading to LOH at specific sites.  It's an admittedly rare case, and maybe not clinically relevant since reversion to the reference is probably not disease causing, but it means missing real somatic variants.  

---

@davidbenjamin commented on [Wed Apr 19 2017](https://github.com/broadinstitute/gatk-protected/issues/864#issuecomment-295336177)

@lbergelson Ah, I see your point.  Then it becomes an interesting trade-off of time vs sensitivity.  I suppose we could make it optional.  I'll re-open.

**Comment by davidbenjamin** [comment]
Actually, it would be so hard to distinguish from germline homozygosity with sufficient likelihood to counterbalance the tiny prior probability of somatic variation that I'm closing again.
