### ISSUE TITLE
GC Correction does not do much of a fitting when target sizes are too large

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2935]
@LeeTL1220 commented on [Wed Jan 25 2017](https://github.com/broadinstitute/gatk-protected/issues/870)

There are many possible solutions.  One would be to break the GC adjustment into smaller bins and weight the read count on those bins rather than making an adjustment per target.

In theory, this could happen when we have large exome targets as well, though this is probably seen most in WGS.

**Comment by samuelklee** [comment]
Obviated by #2858 (and the real issue was always poor segmentation from CBS, not insufficient GC-bias correction).
