### ISSUE TITLE
Pre-training clustering for HMM segmentation

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2936]
@davidbenjamin commented on [Mon Jan 30 2017](https://github.com/broadinstitute/gatk-protected/issues/886)

My original infinite HMM joint segmentation was nifty on paper but is 1) horribly slow and 2) falls into spurious local minima.  One way to improve upon both of these is to learn an initial set of hidden states via Chinese Restaurant Process clustering of the raw allelic count and coverage data, without regard to segmentation and the HMM structure.  Because this doesn't constrain neighboring sites to (usually) have the same state, it will yield a liberal set of initial states, which is fine because they can always be pruned.

Probably, we can run a single pass of the HMM to prune most states.  This will reduce the number of iterations enormously and obviate expensive max-likelihoods learning learning of the hidden state values.

**Comment by samuelklee** [comment]
Obviated by #2858.
