### ISSUE TITLE
Simpler and faster allele fraction likelihoods for HMM segmentation

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2937]
@davidbenjamin commented on [Mon Jan 30 2017](https://github.com/broadinstitute/gatk-protected/issues/887)

The initial implementation of joint segmentation is prohibitively slow, in part because the allele likelihoods model is expensive.  For segmentation we can very likely get away with a much faster binomial + outlier, or maybe beta-binomial + outlier model.

**Comment by samuelklee** [comment]
We still need an improved allele-fraction model, but with #3590 we don't need it for segmentation.  Closing.
