### ISSUE TITLE
Allow -L as an argument for CNV plot zooming.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2939]
@samuelklee commented on [Mon Feb 06 2017](https://github.com/broadinstitute/gatk-protected/issues/892)

---

@droazen commented on [Tue Feb 14 2017](https://github.com/broadinstitute/gatk-protected/issues/892#issuecomment-279793685)

Extend `GATKTool` to get the standard `-L`/`-XL` functionality for free.

**Comment by samuelklee** [comment]
I think interactive plots are the way to go, if we ever get around to this.
