### ISSUE TITLE
Use conditionals to reduce the coverage collection to one task call in case and pon GATK ACNV wdl

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2940]
@LeeTL1220 commented on [Tue Feb 14 2017](https://github.com/broadinstitute/gatk-protected/issues/899)

---

@LeeTL1220 commented on [Tue Feb 14 2017](https://github.com/broadinstitute/gatk-protected/issues/899#issuecomment-279799900)

``CalculateTargetCoverage`` and ``WholeGenomeCoverage`` can be called using a conditional.  The current WDL was a workaround, since it pre-dates cromwell conditionals.

**Comment by samuelklee** [comment]
Obviated by ModelSegments pipeline.
