### ISSUE TITLE
Basic testing of mutect2-replicate-validation.wdl still incomplete

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2948]
@LeeTL1220 commented on [Tue Feb 21 2017](https://github.com/broadinstitute/gatk-protected/issues/915)

This will be obviated by #884 anyway, but in case that takes a while to deliver.

The testing was slowed by https://github.com/broadinstitute/cromwell/issues/2011

**Comment by davidbenjamin** [comment]
This is now an unsupported wdl and it's in good enough shape for our purposes.
