### ISSUE TITLE
Use linkage disequilibrium for tumor-only mode

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2950]
@davidbenjamin commented on [Fri Mar 03 2017](https://github.com/broadinstitute/gatk-protected/issues/927)

In tumor-only mode we can use correlations among variants to impute germline variants.

---

@mbabadi commented on [Fri Mar 03 2017](https://github.com/broadinstitute/gatk-protected/issues/927#issuecomment-284086199)

I thought about doing this a while ago for germline Het SNP calling from tumor-only data, but I kept hearing that LD is lost in tumor samples, though I'm not quite convinced... I'd like to brainstorm on this.

---

@davidbenjamin commented on [Mon Mar 06 2017](https://github.com/broadinstitute/gatk-protected/issues/927#issuecomment-284473367)

I'm not quite convinced either.

**Comment by davidbenjamin** [comment]
I doubt we will ever do this.
