### ISSUE TITLE
Make ordering of contigs in ReadCountCollection and AllelicCountCollection consistent.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2951]
@samuelklee commented on [Thu Mar 09 2017](https://github.com/broadinstitute/gatk-protected/issues/933)

This inconsistency gave rise to a bug in joint segmentation.  I think it ultimately stems from the fact that the common SNP list used to generate pulldowns is not sorted in lexicographical order.

---

@davidbenjamin commented on [Thu Mar 09 2017](https://github.com/broadinstitute/gatk-protected/issues/933#issuecomment-285448744)

Note: see broadinstitute/gatk#1754.

**Comment by samuelklee** [comment]
Addressed in #3716 and #3775 for classes in the copynumber package.
