### ISSUE TITLE
The M2 WDL task for ProcessOptionalArguments can use a smaller docker image.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2952]
@LeeTL1220 commented on [Tue Mar 14 2017](https://github.com/broadinstitute/gatk-protected/issues/937)

By grabbing the gatk-protected docker image (or whichever is being used for M2), this task commits to a ~2GB download.  However, the task does basic bash commands, which could easily be performed using one of the ``ubuntu:14.04`` images or maybe even one smaller.

**Comment by davidbenjamin** [comment]
Closed by #3326.
