### ISSUE TITLE
HaplotypeCaller missing a potentially good variant

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2954]
@vdauwera commented on [Mon Mar 20 2017](https://github.com/broadinstitute/gatk-protected/issues/941)

@chandrans commented on [Mon Dec 05 2016](https://github.com/broadinstitute/gsa-unstable/issues/1530)

### Affected tool(s)
HaplotypeCaller

### Affected version(s)
3.6

### Description 
A user has reported HaplotypeCaller is making a variant call in their case sample, but not in their control sample. When I look at the sites in the GVCF, the case has this:
`chr6	57398201	.	T	C,<NON_REF>	1539.77	.	BaseQRankSum=1.170;ClippingRankSum=0.000;DP=134;ExcessHet=3.0103;MLEAC=1,0;MLEAF=0.500,0.00;MQRankSum=1.964;RAW_MQ=485000.00;ReadPosRankSum=-0.547	GT:AD:DP:GQ:PL:SB	0/1:87,46,0:133:99:1568,0,3286,1837,3433,5269:49,38,27,19`
but, the control has this:
`chr6	57398201	.	T	<NON_REF>	.	.	END=57398201	GT:DP:GQ:MIN_DP:PL	0/0:313:0:313:0,0,0`
Notice the PLs for the control are all 0. However, the bamout file has many reads that have high quality alternate alleles. I don't know why the tool is not making the call. 

Bamout files (top is control and bottom is case):
<img width="1440" alt="screen shot 2016-12-05 at 3 16 18 pm" src="https://cloud.githubusercontent.com/assets/6998669/20900849/d8bdf974-bafd-11e6-967f-e589373c3f97.png">

#### Steps to reproduce
Files and commands in thread below.

----

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/gatk/discussion/comment/34280#Comment_34280

---

@chandrans commented on [Mon Dec 05 2016](https://github.com/broadinstitute/gsa-unstable/issues/1530#issuecomment-264964927)

Test files here:
`/humgen/gsa-scr1/schandra/trevorconley_HaplotypeCallerNotCallingVariant/PersImmune_GATK/`

Command for control (GVCF):
`java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T HaplotypeCaller -R /humgen/gsa-hpprojects/GATK/bundle/2.8/hg19/ucsc.hg19.fasta -I /humgen/gsa-scr1/schandra/trevorconley_HaplotypeCallerNotCallingVariant/PersImmune_GATK/control/01-MDS-03A_aCD3_interval.bam -L chr6:57397901-57398501 -o Sheila.HaplotypeCaller.control.g.vcf -ERC GVCF  -bamout Sheila.HaplotypeCaller.control.bam`

Command for case (GVCF):
`java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T HaplotypeCaller -R /humgen/gsa-hpprojects/GATK/bundle/2.8/hg19/ucsc.hg19.fasta -I /humgen/gsa-scr1/schandra/trevorconley_HaplotypeCallerNotCallingVariant/PersImmune_GATK/case/01-MDS-03A_CD14_interval.bam -o Sheila.HaplotypeCaller.g.vcf -bamout SheilaHaplotypeCaller.bam -L chr6:57397901-57398501 -ERC GVCF`

---

@vruano commented on [Wed Dec 07 2016](https://github.com/broadinstitute/gsa-unstable/issues/1530#issuecomment-265534394)

It seems that this missed variant is a assembly problem. The region has quite a few events resulting in very complex graphs with may possible haplotypes. 

If one adds the -debug -l DEBUG options you can see in the logs that the number of haplotypes for kmer size 10  hits the default maximum of 128. If one increases the limit to 512 ```(-maxNumHaplotypesInPopulation 512)``` then the variant comes up in the output. 

When such a limit is hit, we reduce the number of haplotypes for further analysis using an algorithm that  calculates a pseudo likelihood based on the reads that support different paths in the graph. 

One would hope that this algorithm would pick up at least one of the haplotypes that contain that variant amongst the top 128 haplotypes for any kmer size, however in this instance this is not the case.

So we need to verify  that that algorithm is doing what is supposed to do and if so, whether we can change the way such a pseudo likelihood is calculated in order to make a better selection for this case and in general.

---

@vruano commented on [Wed Dec 07 2016](https://github.com/broadinstitute/gsa-unstable/issues/1530#issuecomment-265535122)

Also increase the kmer size to 35 does the job (-kmerSize 35) I guess that that prevents non-ref paths merge back into the reference between events thus resulting in less complex graphs.

---

@vruano commented on [Wed Dec 07 2016](https://github.com/broadinstitute/gsa-unstable/issues/1530#issuecomment-265535498)

The user can be inform of using these work arounds (change the max number of haplotypes or kmersize) but those are not good solutions in general as he would pay a CPU and sensitivity penalty in other places. 

---

@vruano commented on [Wed Dec 07 2016](https://github.com/broadinstitute/gsa-unstable/issues/1530#issuecomment-265551340)

I can see how the current best-path selection algorithm may fail to produce a good coverage of events across the active region depending on the weights on edges .... for some configurations the algorithm may dedicate too much time in exploring alternatives in one section of the graph because these are nearly equaly likely disregarding other possibilities other section just because they can only result in a relatively larger drop in the likelihood of the path. 

I quick but elegant solution would be to simulate passes across the graph... first iterations would produce a quickly growing set of haplotypes but eventually repeated sampling would not produce new haplotypes. if after 100 subsequent simulations there is no new discovery or we have reached a limit (128?) we would stop there.

This simulation approach could be implemented only in situations the graphs are too complex for an analytical solution. We can determine the maximum number of paths in a graph with a quick deep first traversal to decide whether to use the analytical-exact or the simulation-proximate approach. 

---

@vdauwera commented on [Mon Mar 20 2017](https://github.com/broadinstitute/gsa-unstable/issues/1530#issuecomment-287813366)

To be done in GATK4.

**Comment by davidbenjamin** [comment]
Junction trees will fix this.  @jamesemery
