### ISSUE TITLE
More M2 normal-normals

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2961]
@davidbenjamin commented on [Mon Mar 27 2017](https://github.com/broadinstitute/gatk-protected/issues/958)

We currently have an ICE exome normal-normal analysis set up i.e. you can `cd` into `/dsde/working/davidben/mutect/validations/normalNormal` and `/Users/home/davidben/cromwell/run_sge.sh normal_normal.wdl normal_normal.json` is all you need to get the analysis.

Let's set this up for a few other replicate sets, which we can grab from the Palantir wiki.

**Comment by davidbenjamin** [comment]
Done.
