### ISSUE TITLE
GATK CNV/ACNV automated WDL tests should use docker

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2963]
@LeeTL1220 commented on [Wed Mar 29 2017](https://github.com/broadinstitute/gatk-protected/issues/961)

---

@LeeTL1220 commented on [Wed Mar 29 2017](https://github.com/broadinstitute/gatk-protected/issues/961#issuecomment-290092153)

Currently, the tests do not use docker.  The M2 WDL does use docker.

**Comment by samuelklee** [comment]
Closed in #3408.
