### ISSUE TITLE
Refactor WGS and WES coverage collection to be more analogous.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2964]
@samuelklee commented on [Wed Apr 05 2017](https://github.com/broadinstitute/gatk-protected/issues/975)

Should be an equivalent of PadTargets for WGS that outputs a file specifying the bins.  Alternatively, the WES coverage collection CLI should calculate padded targets on the fly.  This will simplify the WDL and reduce the number of tasks.

**Comment by samuelklee** [comment]
Closed by #3775 and #3597.
