### ISSUE TITLE
Spanning reads annotation

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2966]
@davidbenjamin commented on [Sun Apr 09 2017](https://github.com/broadinstitute/gatk-protected/issues/980)

One familiar source of false positives in HaplotypeCaller and Mutect are deletion calls coming from reads that do not span an STR.  For example, let's say the reference is (STR italicized)

. . . TGCCA*GCTGCTGCTGCTGCT*AATCGG . . .

Then a read ending with . . . TGCCA*GCTGCT* is consistent with the reference, but *also* with deletions of 1, 2, or 3 GCT repeat units.

The most principled way to deal with this is probably an empirical Bayes approach similar to the new `AFCalculator` model or to the proposed new somatic likelihoods model, but another useful and complementary approach would be to annotate the call with the count of variant reads that span the entire STR.

This  shouldn't be hard because the `TandemRepeat` annotation already calculates the length of the STR run, so we just need to compare reads' end positions to the end of the STR.

**Comment by davidbenjamin** [comment]
Somatic likelihoods model has cleaned this up.
