### ISSUE TITLE
CollectAllelicCounts should extend LocusWalker

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2968]
@asmirnov239 commented on [Tue Apr 18 2017](https://github.com/broadinstitute/gatk-protected/issues/987)

Replace the `AllelicCountCollector` with the implementation using LocusWalker

---

@LeeTL1220 commented on [Wed Apr 19 2017](https://github.com/broadinstitute/gatk-protected/issues/987#issuecomment-295366237)

Actually, I have to replace ``CollectAllelicCounts`` and ``AllelicCountCollector``

---

@LeeTL1220 commented on [Fri May 12 2017](https://github.com/broadinstitute/gatk-protected/issues/987#issuecomment-301082304)

Dependent on: 

https://github.com/broadinstitute/gatk/pull/2661

**Comment by samuelklee** [comment]
Closed in #3203.
