### ISSUE TITLE
Make RobustBrentSolver more flexible

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2971]
@mbabadi commented on [Wed Apr 19 2017](https://github.com/broadinstitute/gatk-protected/issues/990)

`RobustBrentSolver` is a univariate solver developed as a part of GATK coverage model. It has a Brent solver at the core but tries to avoid spurious non-bracketing conditions by creating a collection of refined sub-brackets.

The implementation needs to be made more flexible:
- Allow the user to specify how sub-brackets are generated. The default grid is a logarithmic grid concentrated about the leftmost endpoint followed by uniform refinement of each grid element.

**Comment by samuelklee** [comment]
Going to go ahead and close this.  Note that I didn't delete RobustBrentSolver in #3935, as it might come in handy, but it's currently only used in unit tests.
