### ISSUE TITLE
learn something from kmer-based M2 PoN

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2973]
@davidbenjamin commented on [Thu Apr 20 2017](https://github.com/broadinstitute/gatk-protected/issues/994)

The simplest idea is to take kmers (k = 5, 7, 10?) centered at variant positions and fit a distribution (beta distribution?) of artifact allele fractions for each kmer.  

Back of the envelope: with k = 10 we have 4^10 ~ 1 million different kmers, so each kmer appears ~ 3000 times per genome or about 1 million times in our panel of normals.  This is easily enough to fit the distribution of artifact fractions very precisely.

In addition to beta distributions, we may wish to fit different distributions for artifact allele fractions, such as a mixture of no artifacts (other than base errors as expected from the base quals) and a beta.

**Comment by davidbenjamin** [comment]
This task is to take the training data generated in issue #3092 and learn something from it, for example a regression model that predicts a distribution of artifactual read fractions.  Using the learned model in filtering is a separate issue.

**Comment by davidbenjamin** [comment]
Done by @thebkaufman1995, now moving on to a deeper architecture.
