### ISSUE TITLE
CalculateTargetCoverage should throw an exception if MAPPED filter is disabled

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2976]
@asmirnov239 commented on [Fri Apr 21 2017](https://github.com/broadinstitute/gatk-protected/issues/1000)

Right now if a user disables MAPPED filter, which is a default filter for CalculateTargetCoverage tool, it will fail with the following uninformative exception (unless somehow all reads are mapped):
```
java.lang.IllegalArgumentException: the input location cannot be null
	at org.broadinstitute.hellbender.utils.Utils.nonNull(Utils.java:549)
	at org.broadinstitute.hellbender.tools.exome.HashedListTargetCollection.indexRange(HashedListTargetCollection.java:152)
	at org.broadinstitute.hellbender.tools.exome.CalculateTargetCoverage.apply(CalculateTargetCoverage.java:298)
```
We should guard against it and throw an exception before the traversal starts if MAPPED filter is disabled

---

@asmirnov239 commented on [Fri Apr 21 2017](https://github.com/broadinstitute/gatk-protected/issues/1000#issuecomment-296295294)

Since there is no direct API call to access the list of resolved filters(after command line parsing) this bug fix will have to wait until [broadinstitute/barclay#38](https://github.com/broadinstitute/barclay/pull/38) is merged

**Comment by samuelklee** [comment]
Deleted in #3935.
