### ISSUE TITLE
GetBayesianHetCoverage with multiple matched tumor samples

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2977]
@dpmccabe commented on [Mon Apr 24 2017](https://github.com/broadinstitute/gatk-protected/issues/1008)

(Very low-priority enhancement request)

Allow GetBayesianHetCoverage's matched tumor-normal mode to run on multiple tumor samples matched to a single normal. The normal coverage pulldown and likelihood calculations really only need to be calculated and written to a file once. Alternatively, allow the user to specify a `normalHets` file instead of a BAM if one has already been generated. Thanks!

---

@samuelklee commented on [Thu Apr 27 2017](https://github.com/broadinstitute/gatk-protected/issues/1008#issuecomment-297704915)

We're slowly rebuilding the entire somatic pipeline.  One change on the allelic side will be to simply collect allelic counts at all specified sites, rather than performing genotyping on all sites in matched normals and then collecting the corresponding tumor counts at het sites.  

The CLI tool to do this (CollectAllelicCounts) is already merged, if you'd like to start using it.  You'd only have to run this once on each BAM.  The ultimate idea is that resulting allelic count files, along with the corresponding coverage files, could then be passed to a SomaticCNVCaller tool, along with the necessary annotations denoting whether they are tumor or normal.  For now, you could probably insert a simple script that performs the genotyping step if you still want to use the rest of the old pipeline but avoid pulling down the normal multiple times.

**Comment by samuelklee** [comment]
Deprecated.
