### ISSUE TITLE
Expand Git LFS instructions in README

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2978]
@ronlevine commented on [Mon May 01 2017](https://github.com/broadinstitute/gatk-protected/issues/1019)

Clarify the instructions for using Git LFS.

**Comment by droazen** [comment]
Mention that git lfs commands must be run from the repository root.

**Comment by ronlevine** [comment]
Closing since https://github.com/broadinstitute/gatk/pull/3041 is closed.
