### ISSUE TITLE
gCNV refactoring and code improvement

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2979]
@mbabadi commented on [Tue May 02 2017](https://github.com/broadinstitute/gatk-protected/issues/1021)

- [ ] factor I/O methods out of `CoverageModelEMWorkspace` and to a new class
- [ ] shrink the exposed API
- [ ] rename/refactor `CopyRatioCallingMetadata` appropriately
- [ ] rename/move `MathObjectAsserts` to test

**Comment by samuelklee** [comment]
Replaced by #4058.
