### ISSUE TITLE
Port gsa-unstable bug fix to increase maximum GQB to 100.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2981]
@samuelklee commented on [Mon May 08 2017](https://github.com/broadinstitute/gatk-protected/issues/1029)

Port https://github.com/broadinstitute/gatk-protected/pull/1027.

---

@ronlevine commented on [Mon May 08 2017](https://github.com/broadinstitute/gatk-protected/issues/1029#issuecomment-300053921)

@samuelklee Do you mean https://github.com/broadinstitute/gsa-unstable/pull/1451?

---

@samuelklee commented on [Tue May 09 2017](https://github.com/broadinstitute/gatk-protected/issues/1029#issuecomment-300056771)

Oops, yup---thanks.  Too much copying/pasting of cross-repo PRs and issues...

---

@ronlevine commented on [Tue May 09 2017](https://github.com/broadinstitute/gatk-protected/issues/1029#issuecomment-300229785)

Created the branch `rhl_max_qdb_value_1451` with the HaplotypeCaller documentation change. Need to wait for https://github.com/broadinstitute/gatk/pull/2682 to be merged in order to grab the gatk public snapshot from artifactory.

**Comment by ronlevine** [comment]
Closing since #2682 is merged.

**Comment by samuelklee** [comment]
Were the documentation changes to GVCFGQBands from https://github.com/broadinstitute/gsa-unstable/pull/1451 ported?

**Comment by ronlevine** [comment]
@samuelklee I missed that. The functional changes have but the documentation changes need to be ported to `HaplotypeCallerArgumentCollection`.

**Comment by ronlevine** [comment]
Closing since https://github.com/broadinstitute/gatk/pull/3155 is merged.
