### ISSUE TITLE
Mutect filter for barcode-swapping duplicates

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2982]
@davidbenjamin commented on [Tue May 09 2017](https://github.com/broadinstitute/gatk-protected/issues/1031)

@fleharty has found a common artifact in his UMI work in which barcode swapping causes duplicate reads not to be correctly flagged as such, thereby overestimating the evidence in favor of a false positive variant.  In his examples, several reads usually have the variant at *exactly* the same position.  Less frequently but still often enough that we must deal with it, there will be two sets of artifacts and two distinct positions.

Reasonable approaches to an annotation and corresponding filter include but are not limited to 1) a p-value for this degree of clustering, 2) a simple generative model, and 3) just counting the number of unique positions within the read.

**Comment by fleharty** [comment]
@droazen Is this supposed to be closed?  I haven't finished reviewing @takutosato 's implementation.

**Comment by droazen** [comment]
@fleharty It's not closed -- it's just been moved from gatk-protected (the gatk-protected copy of the issue was closed). See my email to dsde-methods.

**Comment by takutosato** [comment]
#3134
