### ISSUE TITLE
Prototype ADVI implementation of coverage model.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2984]
@samuelklee commented on [Fri May 12 2017](https://github.com/broadinstitute/gatk-protected/issues/1038)

- [x] PyMC3 (theano) implementation
- [x] PyStan implementation
- [x] investigate GPU performance
- [x] investigate batch/minibatch performance

See https://github.com/broadinstitute/dsde-methods-prototyping/tree/sl_advi for notebook on Bayesian GMM and instructions to set up the appropriate python environment with conda.

---

@samuelklee commented on [Sun May 14 2017](https://github.com/broadinstitute/gatk-protected/issues/1038#issuecomment-301189833)

Coverage model with ARD and full batch now in https://github.com/broadinstitute/dsde-methods-prototyping/blob/sl_advi/cnv-th/advi-prototypes/coverage.ipynb in the sl_advi branch.  Toy number of targets (100) and samples (50) seems to work well and converge quickly with random initialization.

---

@samuelklee commented on [Sun May 14 2017](https://github.com/broadinstitute/gatk-protected/issues/1038#issuecomment-301321417)

T = 10^5 and N = 100 took 15 minutes running on one core of an i5-3570K with 32GB memory, which includes theano graph compilation.  This includes 350 iterations of ADVI, but note that convergence to 1% was achieved after about 250 iterations.  I also did not initialize with PCA.

However, upping to T = 10^6 causes out of memory.  Not sure if this could be naively alleviated by setting theano flags appropriately, but I think we will probably want to minibatch in T instead.

Note also that this model uses the exact Poisson likelihood.  Composing with an HMM segmentation step, perhaps alternating for a few iterations, would give the gCNV PoN without the Gaussian approximation we use.

---

@samuelklee commented on [Wed May 17 2017](https://github.com/broadinstitute/gatk-protected/issues/1038#issuecomment-302234920)

The same run of T = 10^5 and N = 100 took <4 minutes on the gsa5 Tesla K40c GPU---about a 3x speedup over my home CPU.  A slightly larger run of T = 1.5 * 10^5 and N = 200 took 10 minutes and 6GB of the GPU's 12GB memory.  (I did start running into some weird theano/pymc3 errors when I tried to go bigger, unfortunately.)  Moving to the GPU does require a bit of extra configuration but is relatively trivial.

The real business goes down in exactly 11 lines of code, which cleanly specify the gCNV probabilistic model for read counts:

```
with pm.Model() as model:
    alpha_u = Uniform(name='alpha_u', lower=alpha_min, upper=alpha_max, shape=D)
    m_t = Uniform(name='m_t', lower=m_min, upper=m_max, shape=T)
    psi_t = Uniform(name='psi_t', lower=psi_min, upper=psi_max, shape=T)
    depth_s = Uniform(name='depth_s', lower=depth_min, upper=depth_max, shape=N)
    
    z_su = Normal(name='z_us', mu=0., sd=1., shape=(N, D))
    W_tu = Normal(name='W_tu', mu=0., sd=1. / sqrt(alpha_u), shape=(T, D))
    mu_st = Deterministic(name='mu_st', var=z_su.dot(W_tu.T) + m_t)
    b_st = Normal(name='b_st', mu=mu_st, sd=sqrt(psi_t), shape=(N, T))
    n_ts = Poisson(name='n_ts', mu=depth_s * exp(b_st).T, observed=n_ts_data)
    
fit_pm = pm.variational.advi(model=model, n=num_iterations, learning_rate=learning_rate, random_seed=random_seed, eval_elbo=eval_elbo_iterations)
```

@eitanbanks @droazen @lbergelson @LeeTL1220 @ldgauthier @yfarjoun This is just one example of how using recently developed ML frameworks could make our lives orders of magnitude easier.  The sooner we can develop a strategy to leverage these in Java land, the better!

I'd expect that roughly the same amount of code would be needed to specify this model using Stan.  Interfaces for Stan exist for many other languages, so it might be relatively easy to come up with some Java bindings.  However, one downside is that Stan is not built on top of a computational graph (e.g., theano/tensorflow), so we don't get GPU/distributed computing for free.  I don't think this is a deal breaker, but it's something we should consider.

---

@samuelklee commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/1038#issuecomment-302429919)

It should be said that I consider this a major blocker for the CNV team.  I don't think it makes sense to rebuild the somatic pipeline to include the new coverage model until we move to this ADVI framework or something like it.  I do think @mbabadi should continue adding features (such as common CNV calling) to his non-ADVI germline implementation, so that we can be in a position to start calling on gnomAD or other large cohorts, but that we should eventually move the germline tool over to this framework as well.

**Comment by samuelklee** [comment]
PyMC3 coverage-model implementation: https://github.com/broadinstitute/dsde-methods-prototyping/blob/sl_advi/cnv-th/advi-prototypes/coverage-pymc3.ipynb

PyStan coverage-model implementation: https://github.com/broadinstitute/dsde-methods-prototyping/blob/sl_advi/cnv-th/advi-prototypes/coverage-pystan.ipynb

@lbergelson We can discuss in person the implications for possible Java bindings.

**Comment by samuelklee** [comment]
Some Stan developments to be aware of:

http://andrewgelman.com/2017/06/16/stan-weekly-roundup-16-june-2017/
http://andrewgelman.com/2017/06/16/speed-parallelizing-stan-using-message-passing-interface-mpi/

**Comment by samuelklee** [comment]
Likewise, some PyMC3 developments to be aware of:

http://twiecki.github.io/blog/2017/07/05/new-in-pymc3-31/

SVGD may be a good option for the TH model, which exhibits highly multimodal posteriors.  It would be ideal if our Stan interface allows us to implement it.

In general, it appears that PyMC3 is more feature rich than Stan at the moment.  GPU support in particular is much farther along.

**Comment by samuelklee** [comment]
@LeeTL1220 asked me to summarize some PyMC3 and PyStan benchmarks.  Let T = number of targets, N = number of samples, and M = number of ADVI iterations.  From the notebooks posted above:

PyMC3, T = 500, N = 100, M = 2000: 45 seconds on my laptop single-core CPU (including Theano graph compilation)
PyStan, T = 500, N = 100, M = 2000: 45 seconds compilation + 4.5 minutes on my laptop single-core CPU

PyMC3, T = 10^5, N = 100, M = 350: 15 minutes on my desktop single-core CPU
PyMC3, T = 10^5, N = 100, M = 350: 4 minutes on the gsa5 Tesla K40c GPU

PyMC3, T = 1.5 *10^5, N = 200, M = 350:  10 minutes on the gsa5 Tesla K40c GPU

I didn't run these last few benchmarks on PyStan because I figured they would take too long.
