### ISSUE TITLE
Prototype siHMM.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2985]
@samuelklee commented on [Fri May 12 2017](https://github.com/broadinstitute/gatk-protected/issues/1039)

Hooking up a siHMM (or some variation) to the coverage model from https://github.com/broadinstitute/gatk-protected/issues/1038 will be our first cut at GATK CNV 2.0.  Performance and convergence on WGS-size data should be a priority.  The end goal will be a joint siHMM once we also have the 2.0 allele-fraction model prototyped.

**Comment by samuelklee** [comment]
I think this is obviated by kernel segmentation.  We may use some sort of HMM for the tumor heterogeneity tool, but we can open new, more relevant issues then.
