### ISSUE TITLE
Prototype ADVI coverage model + germline HMM.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2986]
@samuelklee commented on [Fri May 12 2017](https://github.com/broadinstitute/gatk-protected/issues/1040)

Following https://github.com/broadinstitute/gatk-protected/issues/1038 and in conjunction with https://github.com/broadinstitute/gatk-protected/issues/1039.  @asmirnov239, to start, could you make sure you can get the conda environment in https://github.com/broadinstitute/dsde-methods-prototyping/tree/sl_advi up and running?

**Comment by samuelklee** [comment]
New gCNV is built.
