### ISSUE TITLE
Applying GATK to microbiome data

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2987]
@sooheelee commented on [Wed May 17 2017](https://github.com/broadinstitute/gatk-protected/issues/1045)

For MuTect2 developers, a feature to keep in mind -- allowing moving-variable-ploidy calling on highly diverse pooled microbiome samples.

---
Hi, I am interested in knowing how to apply gatk tools to microbiome data. Specifically, I would like to override the assumption of ploidy in the HaplotypeCaller and making it flexible, in that one sample could have a unknown number of haplotypes at the same time, I know somatic mutation caller Mutect2 does not share the assumption but then it's designed to specifically deal with normal - tumor sample pair which is not really applicable in the microbiome studies. Thanks

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/gatk/discussion/9594/applying-gatk-to-microbiome-data/p1

---

@davidbenjamin commented on [Mon May 22 2017](https://github.com/broadinstitute/gatk-protected/issues/1045#issuecomment-303273671)

@sooheelee Tumor-only calling is fully supported in GATK 4 M2, but I will need to understand more about microbiome variant calling to know if M2 could be used.

---

@vdauwera commented on [Tue May 23 2017](https://github.com/broadinstitute/gatk-protected/issues/1045#issuecomment-303284834)

We've had users trying to use MuTect this way for a long time; we just tell them it's unsupported. Actually putting effort into figuring this out and potentially supporting it would probably be a quarterly-goals level decision. Given everything on everyone's plate I wouldn't expect this to get on the QGs in a long while, unless there's a high-profile project that demands it.

Don't get me wrong, I'd love to see this done, and I will bring it up, but realistically I'm not going to hold my breath... 

---

@davidbenjamin commented on [Tue May 23 2017](https://github.com/broadinstitute/gatk-protected/issues/1045#issuecomment-303413211)

This could be the sort of thing like mitochondrial calling that requires very little work to make people pretty happy, so I would be interested in talking about it with someone from the comms team at any time.  Even if it turns out to be a significant project I like planning ahead.  Also, we might be covering the microbiome in journal club soon.

---

@vdauwera commented on [Tue May 23 2017](https://github.com/broadinstitute/gatk-protected/issues/1045#issuecomment-303419699)

Oh I would definitely support some feasibility exploration. I nominate Soo Hee to be your Comms point of contact since she started this ;)

---

@sooheelee commented on [Tue May 23 2017](https://github.com/broadinstitute/gatk-protected/issues/1045#issuecomment-303432970)

What have I gotten myself into? I am a big proponent of mitochondrial research.

**Comment by davidbenjamin** [comment]
@sooheelee After our good experience using Mutect2 for mitochondria I bet that it works decently off the shelf for microbiomes.  So how about we tell the next person who asks that it's untested but there's a good chance it works, and if it doesn't the M2 team promises to work really hard to satisfy early adopters?
