### ISSUE TITLE
Docker image to use openjdk8

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2990]
@LeeTL1220 commented on [Wed May 17 2017](https://github.com/broadinstitute/gatk-protected/issues/1053)

And upgrade ubuntu to 16.04

And leverage the ``broadinstitute/gatk:gatkbase-1.0`` image.  Actually, this will handle the move to OpenJDK8 and ubuntu 16.04.

**Comment by lbergelson** [comment]
This is done already.
