### ISSUE TITLE
Viterbi vs. local posteriors

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2993]
@mbabadi commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/1056)

Here's a relevant conversation we had:

**David**: At some point we should consider ditching Viterbi altogether, since you can segment using the forward-backward result eg setting the call at each target to be the max posterior value. If it works equally well or better it would simplify stuff.

**Mehrtash**: Sam and I had a lengthy discussion about this. The Viterbi result on one hand, and what you get from stacking MAP on each target one the other hand, can be (very) different. One can think of the former as the ground state of the entire system and the latter as the most favorable local state after tracing out the rest of the system.

What we thought would be interesting to do is to:
(1) segment based on Viterbi,
(2) segment based on stacking local CR MAP, and
(3) generate a swarm of hidden state samples from the HMM, segment each sample, and create a 1D density plot for state transition "hotspots".

The hope is that (1) gives us the best overall hidden chain (which may sacrifice local calls), (2) gives us target-resolved genotypes, and (3) gives us some insight about "excitations" about the Viterbi state, i.e. (3) is something between (1) and (2).

**Samuel**: I think breakpoint probabilities based on sequences drawn from the joint posterior (3) would be most useful, but let's see how these look in real data.

**Comment by ldgauthier** [comment]
@samuelklee do you want to keep this issue open?

**Comment by samuelklee** [comment]
Some discussion worth archiving, but we can probably close.
