### ISSUE TITLE
gCNV default parameters

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2995]
@mbabadi commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/1058)

- [ ] good choice of default parameters
- [ ] double-check assertion coverage in `CoverageModelArgumentCollection.validate()`
- [ ] if a model is provided, ARD and number of PCs must be overridden (currently, an exception is thrown if there is a discrepancy between model parameters and arguments)

Relevant discussion:
**Mehrtash**: We may be able to get rid of a number of these parameters. Though, generally speaking, I'd rather expose more than less, with good default values and bold advanced disclaimers w/ proper documentation as you suggested. This is the case with sophisticated tools like HaplotypeCaller, StarAligner, etc. Soon enough, we will get strange errors from various users many of which can be resolved by changing a certain advanced parameter. Without exposing them, we will have to create patches for them and/or build custom jars.

**Comment by mbabadi** [comment]
Deprecated by the new gCNV. Closing.
