### ISSUE TITLE
Evaluate the necessity for external GC correction vs. depending on the coverage model for ab initio discovery of GC bias

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2997]
@mbabadi commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/1061)

If external GC bias correction was found beneficial, we must do it in the way suggested in the notes, i.e. not directly on the read count table, but as a _hard coded_ bias covariates. This will ensure that the Poisson noise is not under/over-estimated as a result of GC bias correction.

**Comment by samuelklee** [comment]
This is done in gCNV and will be done in future models as well.
