### ISSUE TITLE
More flexible integer copy number transition priors in gCNV

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#2998]
@mbabadi commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/1062)

- [ ] the ability to _override_ global transition priors in polymorphic regions, etc.
- [ ] the ability to ingest XHMM-like priors (i.e. parametrized models)
- [ ] (bonus) different max copy number states for different genomic loci

**Comment by samuelklee** [comment]
I think we can say this is addressed by #3925.
