### ISSUE TITLE
Replace or remove Nd4jUtils.getNDArrayByIndices() method

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3000]
@asmirnov239 commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/1063)

Due to a bug in Nd4j library, INDArray.get() method does not work correctly for row or column vectors (that we work with when number of samples is 1). In these cases a call to `getNDArrayByIndices(array, indX, indY, int)` is made.
Note that this bug was fixed in later version of Nd4j (currently used version is 0.5.0), so the method can be removed when the dependency is updated

**Comment by samuelklee** [comment]
Closed in #1076.
