### ISSUE TITLE
Limit the number of copy number states and designate a special state to capture all higher copy number states

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3001]
@mbabadi commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/1064)

At the moment, the maximum copy number in gCNV is set by the dimension provided transition matrices. One needs to work with copy number states up to 10 ~ 20 in order to capture high copy number states seen in certain regions.

It is desirable to limit the number of states, however, to designate a special state that represents _all copy number states at and above CN_max_. This can be achieved by adjusting the emission probability to integrate over all higher copy number states. There are other challenges too (e.g. calculating copy number posteriors from such states).

**Comment by mwalker174** [comment]
This is certainly of interest for capturing multi-allelic sites that can have very high copy states. We won't add this to the current gCNV tool, but I am noting this as a desired property for future models.
