### ISSUE TITLE
Migrate to Nd4j BLAS

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3003]
@mbabadi commented on [Thu May 18 2017](https://github.com/broadinstitute/gatk-protected/issues/1066)

At the time of initial development of gCNV, Nd4j did not provide native implementation of BLAS level-3 functions. Now that we have them (as of nd4j 0.6.0), it is desirable to migrate all BLAS level-3 ops to native Nd4j (as opposed to converting NDArrays to Apache matrices back and forth). This includes LU decomposition and matrix inversion ops.

**Comment by samuelklee** [comment]
@mbabadi Gonna go ahead and close this.  Again, let's reevaulate the need for nd4j.
