### ISSUE TITLE
Instrumentation and ICG function evaluation counts in gCNV

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3007]
@mbabadi commented on [Fri May 19 2017](https://github.com/broadinstitute/gatk-protected/issues/1071)

It is desirable to perform an explicit bookkeeping of ICG function evaluation to ensure that gCNV is not performing unnecessary EM evaluation in each cycle.

**Comment by samuelklee** [comment]
Obviated by new gCNV.
