### ISSUE TITLE
DetermineGermlineContigPloidy and PAR regions

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3008]
@mbabadi commented on [Mon May 22 2017](https://github.com/broadinstitute/gatk-protected/issues/1085)

- [ ] Add the ability to blacklist PAR regions with an argument, e.g. `--blacklistRegion contig1:start1-end1 --blacklistRegion contig2:start2-end2 --blacklistRegion contig3:start3-end3 ...`

**Comment by samuelklee** [comment]
See model update in #4371 that should obviate this.  Should also handle this via -XL anyway.
