### ISSUE TITLE
Count different kinds of alt reads in M2 isActive

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3012]
@davidbenjamin commented on [Mon May 22 2017](https://github.com/broadinstitute/gatk-protected/issues/1090)

Currently we lump together all variant reads and add up the total alt evidence.  This classifies too many regions as active.  We should tally reads supporting SNVs (of each possible substitution), deletions, and insertions separately.

**Comment by davidbenjamin** [comment]
Actually, this turns out to be an edge case.  Not closing, but removing from the epic.

**Comment by davidbenjamin** [comment]
This is now a priority for the mitochondrial calling project, and probably for any high-depth calling because, as @meganshand has found, we lose *sensitivity* due to inactive regions.

**Comment by davidbenjamin** [comment]
Just kidding!  We lose sensitivity from `isActive()` when the depth is high but we found the true reason.
