### ISSUE TITLE
NormalizeSomaticReadCounts has ``targets`` parameter as optional, but it is required.

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3017]
@LeeTL1220 commented on [Fri May 26 2017](https://github.com/broadinstitute/gatk-protected/issues/1106)

The code will actually run, but fail right before doing the normalization.

**Comment by samuelklee** [comment]
Actually, I think this is intended behavior, according to the current tests.  If there is no targets file, the tool will attempt to get target names from the read-count file and then fail if they are missing.
