### ISSUE TITLE
IntervalWalkers should be able to request that intervals not be modified in any way

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#302]
Currently the engine always merges overlapping intervals (and, optionally, adjacent intervals). Should there be a "don't touch my intervals in any way" mode for IntervalWalkers?

IntervalWalker traversal with overlapping intervals would be very inefficient in the current framework, but could probably be made to work reasonably on dataflow.

**Comment by droazen** [comment]
Re-opening -- this was closed by accident.

**Comment by ldgauthier** [comment]
Closing because we now have a `OVERLAPPING_ONLY`(#3254) and because we haven't found a use case for this in almost five years.
