### ISSUE TITLE
Filter reads more aggressively in Mutect

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3020]
@davidbenjamin commented on [Sat May 27 2017](https://github.com/broadinstitute/gatk-protected/issues/1110)

The traditional approach in Mutect and HaplotypeCaller is to filter reads based on simple properties, such as low mapping quality, lack of mate, etc.  This still leaves a lot of fairly bad reads.  These probably don't affect calls because they don't support any allele well according to `PairHMM`.  Still, they probably waste a lot of time by generating unnecessary paths in the assembly graph.

Some possible filters include an excessive number of different CIGAR elements, and too many low-quality bases.

**Comment by davidbenjamin** [comment]
Pileup-based error correction achieves this goal.
