### ISSUE TITLE
Use bigger kmers in assembly

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3024]
@davidbenjamin commented on [Sun May 28 2017](https://github.com/broadinstitute/gatk-protected/issues/1114)

HaplotypeCaller and Mutect by default assemble reads with kmer sizes of 10 and 25.  10 seems extremely small given the low error rates of Illumina sequencing.  It's worth investigating how the Mutect validations are affected by increasing these values.

---

@ldgauthier commented on [Tue May 30 2017](https://github.com/broadinstitute/gatk-protected/issues/1114#issuecomment-305032024)

Investigate away, but keep in mind bigger kmers introduce more "dangling tails", which may end up dropping evidence at the ends of reads.

If you end up diving into the assembly graphs, I'm happy to consult. It's a deep, dark rabbit hole, but I've been there before and I know the way.  ;)

**Comment by davidbenjamin** [comment]
Note to self: the code for rescuing dangling tails seems pretty good.  If it's not, the decrease in number of haplotypes to be gained from larger kmers might offset the necessary increase in haplotype padding.  We'll have to investigate.

**Comment by ldgauthier** [comment]
There's no code for branched tails though. For somatic data maybe that's
rare enough it doesn't matter.

**Comment by davidbenjamin** [comment]
James is working on this.
