### ISSUE TITLE
Provide mutect equations in pdf format, not just .tex laTex format

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3025]
@sooheelee commented on [Tue May 30 2017](https://github.com/broadinstitute/gatk-protected/issues/1116)

I'm looking at <https://github.com/broadinstitute/gatk-protected/tree/master/docs/mutect>. Can we please provide these in PDF format, much like in the CNV branch of the docs?

**Comment by davidbenjamin** [comment]
Closed in #3037.
