### ISSUE TITLE
CollectSequencingArtifactMetrics (GATK) has errors and requires workaround in downstream tools

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3030]
Currently, FilterByOrientation requires replacing a required input's contents with a sed command: 

```
sed -r "s/picard\.analysis\.artifacts\.SequencingArtifactMetrics\\\$PreAdapterDetailMetrics/org\.broadinstitute\.
 hellbender\.tools\.picard\.analysis\.artifacts\.SequencingArtifactMetrics\$PreAdapterDetailMetrics/g" \
 "metrics.pre_adapter_detail_metrics" > "gatk.pre_adapter_detail_metrics"
```

The required input is the detailed pre-adapter summary metrics from Picard's CollectSequencingArtifactMetrics. The sed command replaces
```
## METRICS CLASS	picard.analysis.artifacts.SequencingArtifactMetrics$PreAdapterDetailMetrics
```
with 
```
## METRICS CLASS	org.broadinstitute.hellbender.tools.picard.analysis.artifacts.SequencingArtifactMetrics$PreAdapterDetailMetrics
```

If this class is not replaced, then the tool errors with: 
```
htsjdk.samtools.SAMException: Could not locate class with name gatk.analysis.artifacts.SequencingArtifactMetrics$PreAdapterDetailMetrics
	at htsjdk.samtools.metrics.MetricsFile.read(MetricsFile.java:356)
	at org.broadinstitute.hellbender.tools.exome.FilterByOrientationBias.onTraversalStart(FilterByOrientationBias.java:102)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:777)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:115)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:122)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:143)
	at org.broadinstitute.hellbender.Main.main(Main.java:221)
Caused by: java.lang.ClassNotFoundException: gatk.analysis.artifacts.SequencingArtifactMetrics$PreAdapterDetailMetrics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at htsjdk.samtools.metrics.MetricsFile.loadClass(MetricsFile.java:471)
	at htsjdk.samtools.metrics.MetricsFile.read(MetricsFile.java:353)
	... 8 more
```

If it is replaced, the tool still errors but with a different error:
```
java.lang.IllegalArgumentException: Features added out of order: previous (TabixFeature{referenceIndex=0, start=118314029, end=118314036, featureStartFilePosition=1403632633, featureEndFilePosition=-1}) > next (TabixFeature{referenceIndex=0, start=33414233, end=33414234, featureStartFilePosition=1403632876, featureEndFilePosition=-1})
	at htsjdk.tribble.index.tabix.TabixIndexCreator.addFeature(TabixIndexCreator.java:89)
	at htsjdk.variant.variantcontext.writer.IndexingVariantContextWriter.add(IndexingVariantContextWriter.java:170)
	at htsjdk.variant.variantcontext.writer.VCFWriter.add(VCFWriter.java:219)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.broadinstitute.hellbender.tools.exome.FilterByOrientationBias.onTraversalSuccess(FilterByOrientationBias.java:171)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:781)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:115)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:170)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:189)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:122)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:143)
	at org.broadinstitute.hellbender.Main.main(Main.java:221)
```

It does not matter if I produce the pre-adapter metrics with the latest Picard jar v2.9.2. I get the same error. 

I'm using a M2 callset from GATK3. Even so, I don't think I should get the above error?

**Comment by sooheelee** [comment]
@davidbenjamin Is that some solution that I've overlooked?

**Comment by davidbenjamin** [comment]
@sooheelee That error message occurs after the tool has done all the hard work and ju isst has to emit the `VariantContext`s to a file.  It seems like the inputs are out of order.  Could you check two things: 1) is the input vcf ordered? and 2) are you outputting a vcf or a vcf.gz?  I'm curious if the error occurs for both.

**Comment by davidbenjamin** [comment]
@sooheelee Also, @LeeTL1220 is the expert on this tool.

**Comment by sooheelee** [comment]
I was outputting to .vcf.gz.  

I reran the command to output to just. vcf and it runs without error:
```
/gatk-launch FilterByOrientationBias --artifactModes 'G/T' -V /Users/shlee/Documents/workshop_materials/mutect2_tutorial/mutect2_handson/8_mutect2.vcf.gz -P ~/Documents/workshop_materials/mutect2_tutorial/mutect2_handson/gatk_6_T_artifact.pre_adapter_detail_metrics -O test_filterbyorientationbias.vcf
Using GATK wrapper script /Users/shlee/Documents/branches/hellbender/build/install/gatk/bin/gatk
Running:
    /Users/shlee/Documents/branches/hellbender/build/install/gatk/bin/gatk FilterByOrientationBias --artifactModes G/T -V /Users/shlee/Documents/workshop_materials/mutect2_tutorial/mutect2_handson/8_mutect2.vcf.gz -P /Users/shlee/Documents/workshop_materials/mutect2_tutorial/mutect2_handson/gatk_6_T_artifact.pre_adapter_detail_metrics -O test_filterbyorientationbias.vcf
01:16:16.916 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/shlee/Documents/branches/hellbender/build/install/gatk/lib/gkl-0.4.3.jar!/com/intel/gkl/native/libgkl_compression.dylib
[June 6, 2017 1:16:16 AM EDT] FilterByOrientationBias  --output test_filterbyorientationbias.vcf --preAdapterDetailFile /Users/shlee/Documents/workshop_materials/mutect2_tutorial/mutect2_handson/gatk_6_T_artifact.pre_adapter_detail_metrics --artifactModes G/T --variant /Users/shlee/Documents/workshop_materials/mutect2_tutorial/mutect2_handson/8_mutect2.vcf.gz  --interval_set_rule UNION --interval_padding 0 --interval_exclusion_padding 0 --readValidationStringency SILENT --secondsBetweenProgressUpdates 10.0 --disableSequenceDictionaryValidation false --createOutputBamIndex true --createOutputBamMD5 false --createOutputVariantIndex true --createOutputVariantMD5 false --lenient false --addOutputSAMProgramRecord true --addOutputVCFCommandLine true --cloudPrefetchBuffer 40 --cloudIndexPrefetchBuffer -1 --disableBamIndexCaching false --help false --version false --showHidden false --verbosity INFO --QUIET false --use_jdk_deflater false --use_jdk_inflater false --disableToolDefaultReadFilters false
[June 6, 2017 1:16:16 AM EDT] Executing as shlee@WMCF9-CB5 on Mac OS X 10.11.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_111-b14; Version: 4.alpha.2-1102-g6e91a5d-SNAPSHOT
01:16:16.954 INFO  FilterByOrientationBias - HTSJDK Defaults.COMPRESSION_LEVEL : 1
01:16:16.955 INFO  FilterByOrientationBias - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
01:16:16.955 INFO  FilterByOrientationBias - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
01:16:16.955 INFO  FilterByOrientationBias - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
01:16:16.955 INFO  FilterByOrientationBias - Deflater: IntelDeflater
01:16:16.955 INFO  FilterByOrientationBias - Inflater: IntelInflater
01:16:16.955 INFO  FilterByOrientationBias - Initializing engine
01:16:17.042 INFO  FeatureManager - Using codec VCFCodec to read file file:///Users/shlee/Documents/workshop_materials/mutect2_tutorial/mutect2_handson/8_mutect2.vcf.gz
01:16:17.259 INFO  FeatureManager - Using codec VCFCodec to read file file:///Users/shlee/Documents/workshop_materials/mutect2_tutorial/mutect2_handson/8_mutect2.vcf.gz
01:16:17.363 INFO  FilterByOrientationBias - Done initializing engine
01:16:17.385 INFO  FilterByOrientationBias - preAdapter scores:
01:16:17.385 INFO  FilterByOrientationBias - A>G: 50.69292989984913
01:16:17.385 INFO  FilterByOrientationBias - C>G: 100.0
01:16:17.385 INFO  FilterByOrientationBias - C>T: 47.69489057653316
01:16:17.385 INFO  FilterByOrientationBias - C>A: 100.0
01:16:17.386 INFO  FilterByOrientationBias - G>T: 35.96142674042852
01:16:17.386 INFO  FilterByOrientationBias - A>T: 100.0
01:16:17.386 INFO  FilterByOrientationBias - G>C: 65.54621245392002
01:16:17.386 INFO  FilterByOrientationBias - A>C: 100.0
01:16:17.386 INFO  FilterByOrientationBias - T>C: 100.0
01:16:17.386 INFO  FilterByOrientationBias - T>A: 46.63506199398367
01:16:17.386 INFO  FilterByOrientationBias - T>G: 62.081336058792466
01:16:17.386 INFO  FilterByOrientationBias - G>A: 100.0
01:16:17.470 INFO  ProgressMeter - Starting traversal
01:16:17.470 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
01:16:17.493 INFO  ProgressMeter -             unmapped              0.0                     4          10434.8
01:16:17.493 INFO  ProgressMeter - Traversal complete. Processed 4 total variants in 0.0 minutes.
01:16:17.493 INFO  FilterByOrientationBias - Tagging whether genotypes are in one of the artifact modes.
01:16:17.496 INFO  ProgressMeter - Starting traversal
01:16:17.496 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
01:16:17.497 INFO  ProgressMeter -             unmapped              0.0                     8         480000.0
01:16:17.498 INFO  ProgressMeter - Traversal complete. Processed 8 total records in 0.0 minutes.
01:16:17.500 INFO  OrientationBiasFilterer - NORMAL: Nothing to filter.
01:16:17.500 INFO  OrientationBiasFilterer - TUMOR: Nothing to filter.
01:16:17.500 INFO  OrientationBiasFilterer - Updating genotypes and creating final list of variants...
01:16:17.500 INFO  ProgressMeter - Starting traversal
01:16:17.501 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Records Processed   Records/Minute
01:16:17.501 INFO  ProgressMeter -             unmapped              0.0                     4         Infinity
01:16:17.501 INFO  ProgressMeter - Traversal complete. Processed 4 total records in 0.0 minutes.
01:16:17.501 INFO  FilterByOrientationBias - Writing variants to VCF...
01:16:17.512 INFO  FilterByOrientationBias - Writing a simple summary table...
01:16:17.576 INFO  FilterByOrientationBias - Shutting down engine
[June 6, 2017 1:16:17 AM EDT] org.broadinstitute.hellbender.tools.exome.FilterByOrientationBias done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=232259584
WMCF9-CB5:hellbender shlee$ 
```

This is the case for the file that I augmented with what the sed command was meant to do. Otherwise, the command errors. I think the tool should be able to take CollectSequencingArtifactMetrics whether run using Picard or GATK. I say this since folks may have these metrics from old runs before the as-of-yet-available Picard tools in the GATK jar.

**Comment by davidbenjamin** [comment]
I'm going to assign to @LeeTL1220. He'll have a better idea what to do.

**Comment by LeeTL1220** [comment]
GATK version of collect sequencing artifact metrics has bugs.  You have to use Picard version as workaround, but the output of Picard must be changed.

@sooheelee your input file is also busted.  The errors you are getting are in dependencies of FilterByOrientationBias.  Also, I don't think you can just cut and paste the sed command from the WDL (Don't ask.... Subtleties of WDL parsing).  Vcf vs tar.gz is in the engine.  @lbergelson might know

**Comment by LeeTL1220** [comment]
Not sure who to assign this to.

**Comment by LeeTL1220** [comment]
https://github.com/broadinstitute/gatk/issues/2351

**Comment by sooheelee** [comment]
@LeeTL1220 I am not using the sed command but instituting the effects of it with a text-editor. I am also using an output from Picard that I ran a while ago when I was developing the M2 hands-on tutorial.

Again, this:
```
picard.analysis.artifacts.SequencingArtifactMetrics$PreAdapterDetailMetrics
```
effectively becomes:
```
org.broadinstitute.hellbender.tools.picard.analysis.artifacts.SequencingArtifactMetrics$PreAdapterDetailMetrics
```

Users should NOT have to do this. The tool should accept outputs directly from Picard.

**Comment by sooheelee** [comment]
As for my input files being busted. Which file do you mean? I'm not sure why @LeeTL1220 changed the title of this issue ticket. Can you please explain? Because CollectSequencingArtifactMetrics works just fine. It is FilterByOrientationBias that errors.

**Comment by sooheelee** [comment]
### Until these bugs in FilterByOrientationBias are resolved, I will add the BETA label to the tool.

**Comment by LeeTL1220** [comment]
There is a lot going on here...  Let me see if I can explain...  

First things first, there are two versions of ``CollectSequencingArtifactMetrics`` ... a GATK port and the Picard version.  The GATK port has show-stopping issues, so the picard version is used in the meantime, which necessitates that ``sed`` stuff...

> As for my input files being busted. Which file do you mean? As you can see from my late-night post, I do get the tool to run using the odd workarounds.

``java.lang.IllegalArgumentException: Features added out of order: previous (TabixFeature{referenceIndex=0, start=118314029, end=118314036, featureStartFilePosition=1403632633, featureEndFilePosition=-1}) > next (TabixFeature{referenceIndex=0, start=33414233, end=33414234, featureStartFilePosition=1403632876, featureEndFilePosition=-1})``

This is has something to do with your input file.  If I am wrong and this is truly a code error, then the fix is not in ``FilterByOrientationBias``.  @lbergelson Can you confirm?  


> Also, why @LeeTL1220 have you changed the title of this issue ticket? Can you please explain? Again, I reiterate that CollectSequencingArtifactMetrics works just fine. It is FilterByOrientationBias that errors without these workarounds.

``CollectSequencingArtifactMetrics`` (GATK version) definitely does not work just fine.  I've cited the issue above.  I do not think that any of the code fixes would actually go into FilterByOrientationBias.  If the GATK version worked just fine, we would ditch the ``sed`` command and use that.

``CollectSequencingArtifactMetrics`` (Picard version) works just fine BUT it introduces that string which requires the ``sed`` statement.  If you do not use ``sed``, a (general-use/engine) dependency of ``FilterByOrientationBias`` will try to instantiate a class that does not exist.  The ``sed`` was supposed to be temporary until picard was wrapped properly in GATK.  But until then, it does mean that all GATK-based downstream dependencies of ``CollectSequencingArtifactMetrics``  will fail without the sed.  Again, the fix is not in ``FilterByOrientationBias``.

> Also, FilterByOrientationBias does not output bgzipped VCFs. So this is not in line with how GATK tools should work.  

``FilterByOrientationBias`` just farms it out to a VCF Writer.  That dependency (VCF Writer) should handle that.  Can you confirm, @lbergelson ?  Is there an additional step to make this work that I did not know about?

> Again, FilterByOrientationBias is not production worthy and I think at this point it should get an experimental or BETA label.

Only because of the ``sed`` nonsense, as near as I can tell.  Definitely, BETA -- not experimental.  All I'm saying is that I don't believe any code change needs to go into ``FilterByOrientationBias`` (with the possible exception of the bgzip VCF).  These issues are all in its dependencies, which are part of the engine/picard-ports.

**Comment by LeeTL1220** [comment]
``FilterByOrientationBias`` should already be BETA, anyway, since it is part of the M2 workflow.

**Comment by LeeTL1220** [comment]
@sooheelee I do agree.  USers cannot be expected to do this.  @lbergelson @droazen Any ideas how best to address this?  Tell me if you need more details.  This ties into Picard integration.

**Comment by sooheelee** [comment]
I have never used the GATK version CollectSequencingArtifactMetrics. So all of my errors stem from using the results of Picard's CollectSequencingArtifactMetrics, which we can expect our users to do for the foreseeable future, given the merging of the toolsets is not something in the works as far as I know. 

@LeeTL1220 It seems peculiar to me that we should have to fix Picard's CollectSequencingArtifactMetrics for compatibility with this new tool FilterByOrientationBias. Rather, shouldn't you fix FilterByOrientationBias to accept either string?

**Comment by sooheelee** [comment]
Are you saying @LeeTL1220 that all of GATK4's tools cannot write bgzipped VCFs?

**Comment by LeeTL1220** [comment]
@sooheelee Was not my call to implement the parser that way.  Hence, to support both would require a big hack that we would throw away later, anyway.  

Possible that FBOB is using the dependency wrong for writing out bgz VCF.  But it seems to be doing it in a pretty standard way.  I'm just going to have to ask @droazen and @lbergelson on that one.

**Comment by lbergelson** [comment]
I'm honestly not sure what's going on here.  The picard/gatk differences will be resolved soon and then the sed command can go away.  I don't think it's worth doing anything until then.

We should be able to write vcf.gz so if there's an issue there we want to know about it.  There could either be an issue in the TabixIndex writer (which we know for sure has issues, one is a blocker on the 11k project at the moment. )  Alternatively the input file could just be invalid, in which case our vcf writer should be detecting the error and is not.

**Comment by cmnbroad** [comment]
@sooheelee Is the input "8_mutect2.vcf.gz" file that you used above the same one that David sent me today ? If so, the second error above (the "Features added out of order...") that happens when the output is a .gz, is a legitimate error. That input file was not sorted (even though it had a companion .tbi index file, which I suspect is not it's actual companion), so the output tabix index can't be created.

You can try adding `--createOutputVariantIndex false` to the command line and see if that eliminates the error message.

**Comment by sooheelee** [comment]
FilterByOrientation now takes in the Picard metrics (tested with GATK4.beta.6) and my original question has been addressed.
