### ISSUE TITLE
jenkins builds failing with out of of space errors

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3067]
It looks like jenkins builds are failing with what seem to be lack of disk space.  

This looks like the culprit:
<img width="1069" alt="screen shot 2017-06-08 at 11 09 38 am" src="https://user-images.githubusercontent.com/4700332/26935854-0b9f907c-4c3b-11e7-9054-a8af6df479e6.png">

We need to clean up space on the disk.

**Comment by davidbernick** [comment]
Yup doing it now.

**Comment by davidbernick** [comment]
Can we destroy old builds? That's the issue. There's 50G of old builds.

**Comment by davidbernick** [comment]
I think you're good here. Things are building and node is online.

**Comment by lbergelson** [comment]
Thank you!
