### ISSUE TITLE
fix artifactory setup

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3068]
The broad artifactory moved to https://broadinstitute.jfrog.io/broadinstitute/.

There is a redirect in place which as been working for downloads, but uploads are failing with `401 Unauthorized`.  It seems like updating the url fixes the problem.

As a second issue, our builds try to upload archives for every integration test build, which worked when we only had 1 integration test build, but now that we have multiples we are uploading duplicates which isn't good.  We should fix that, probably by adding either a new environment variable to the travis build, or a final build stage to perform the upload.

**Comment by droazen** [comment]
@davidbernick Could you help out with this one? Thanks!

**Comment by lbergelson** [comment]
We know the solution, I'll try to get a pr in today.

**Comment by magicDGS** [comment]
I want to update my dependencies, but the last commits are not in the new artifactory. Which one is the latest?

**Comment by lbergelson** [comment]
@magicDGS I just merged the fix, so a new master snapshot **should** be uploaded in about 45 minutes.

**Comment by magicDGS** [comment]
Thanks @lbergelson!
