### ISSUE TITLE
GKL is outputting a warning that should probably be handled by java

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3069]
The pair hmm is emitting this warning which doesn't respect the log settings.  
It would be nice if it respected our logging settings.  

Maybe we should add a "setLogLevel" hook to GatkNativeBindings?

I'm not sure why this is being triggered on travis, since I would have thought travis supports OpenMP, so either travis isn't testing what we think it is, or the warning is being emitted for a slightly different reason than it claims.
`[WARNING] Ignoring request for 4 threads; not using OpenMP implementation`

**Comment by droazen** [comment]
For @kgururaj /@kdatta

**Comment by lbergelson** [comment]
@droazen @kgururaj @kdatta This isn't a genomics db issue, it's a pair hmm gkl issue.

**Comment by droazen** [comment]
Whoops, so it is -- re-assigning to the GKL folks :)

**Comment by gspowley** [comment]
@erniebrau was this issue resolved?

**Comment by erniebrau** [comment]
@gspowley Yes. The warnings are now handled by Java. This was resolved in #3513.

**Comment by gspowley** [comment]
Thanks @erniebrau, closing this issue.
