### ISSUE TITLE
jenkins spark tests are failing but say they're succesful.

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3077]
Our jenkins nightly tests are failing, but they're reporting success.  This shouldn't be happening.  

Some of the failures are due to #3067, but the spark failures look like something else is causing them

Notice the very short runtimes because nothing is actually happening.
<img width="958" alt="screen shot 2017-06-09 at 2 04 31 pm" src="https://user-images.githubusercontent.com/4700332/26988271-a61ab3fc-4d1c-11e7-9110-9941888b66ce.png">

This ticket is to fix the fact that the tests report success even when they fail, not to fix the tests themselves.

**Comment by lbergelson** [comment]
@davidbernick Could you take a look at this and at #3067 when you have a chance?

**Comment by davidbernick** [comment]
This one is actually different than 3067 -- it's resolved too. But I'm letting it run now just to be 100%.

**Comment by davidbernick** [comment]
This is good, too.
