### ISSUE TITLE
Design GATK configuration mechanism

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3079]
Once we choose the library to use for GATK configuration, let's have a design meeting to make sure we come up with something that works for Spark, downstream projects, our users, etc.

**Comment by droazen** [comment]
As part of this, we should determine exactly which settings should live in the new config file.

**Comment by jonn-smith** [comment]
Some info on Spark configurations:

https://stackoverflow.com/questions/29441316/specifying-an-external-configuration-file-for-apache-spark

**Comment by jonn-smith** [comment]
Here's another one with our exact problem (solved largely by putting the config onto HDFS).

http://progexc.blogspot.com/2014/12/spark-configuration-mess-solved.html

**Comment by droazen** [comment]
Closing -- we are past the design phase on this one.
