### ISSUE TITLE
logger message in SortReadFileSpark

### ISSUE THREAD

**Issue by hliang** [broadinstitute/gatk#3095]
`SortReadFileSpark` gives a log message like this:
```
17:31:00.062 INFO  SortReadFileSpark - Using %s reducers2744
```
It's trivial, but I think the [logger](https://github.com/broadinstitute/gatk/blob/c18e7800ed85c55f81387cf02fdcbf6cb3aaaf5e/src/main/java/org/broadinstitute/hellbender/tools/spark/pipelines/SortReadFileSpark.java#L41)  needs a small fix.

**Comment by magicDGS** [comment]
PR open: #3096

**Comment by lbergelson** [comment]
@hliang Thanks for reporting the problem.
@magicDGS Thanks for fixing the problem.
