### ISSUE TITLE
GermlineCNVCaller setting Nd4j could be more user-friendly

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3098]
Hey @mbabadi, I've answered this user question but I think my answer needs your review. Also, DR mentioned perhaps this option could be set automatically for users? Thanks.

---
Thanks @shlee for the update,
I used the latest jar from the gatk4 repo as recommended. And managed to derive the read count input file and sex genotype table. I just wanted to confirm whether Nd4j also needed to be installed if not using Spark.

#script run
./gatk-launch GermlineCNVCaller  --contigAnnotationsTable ../gatk4_Hellbender/grch37_contig_annotations.tsv --copyNumberTransitionPriorTable ../gatk4_Hellbender/grch37_germline_CN_priors.tsv --jobType LEARN_AND_CALL --outputPath ./TS1 --input ../gatk4_Hellbender/target_cov.tsv  --targets ../gatk4_Hellbender/targets.txt --disableSpark true --sexGenotypeTable ../gatk4_Hellbender/TS1_genotype --rddCheckpointing false --biasCovariateSolverType LOCAL

#I am getting the following error which seems to be linked with Nd4j:

Using GATK jar ~/localwork/playground/programs/gatk-protected/build/libs/gatk-protected-package-b4390fb-SNAPSHOT-local.jar
102-b14; Version: 4.alpha.2-1136-gc18e780-SNAPSHOT
16:55:21.931 INFO  GermlineCNVCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 1
16:55:21.932 INFO  GermlineCNVCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
16:55:21.932 INFO  GermlineCNVCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
16:55:21.932 INFO  GermlineCNVCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
16:55:21.932 INFO  GermlineCNVCaller - Deflater: IntelDeflater
16:55:21.932 INFO  GermlineCNVCaller - Inflater: IntelInflater
16:55:21.932 INFO  GermlineCNVCaller - Initializing engine
16:55:21.932 INFO  GermlineCNVCaller - Done initializing engine
16:55:21.933 INFO  GermlineCNVCaller - Spark disabled.  sparkMaster option (local[*]) ignored.
16:55:23.448 INFO  GermlineCNVCaller - Parsing the read counts table...
16:55:24.876 INFO  GermlineCNVCaller - Parsing the sample sex genotypes table...
16:55:24.896 INFO  GermlineCNVCaller - Parsing the germline contig ploidy annotation table...
16:55:24.906 INFO  ContigGermlinePloidyAnnotationTableReader - Ploidy tags: SEX_XX, SEX_XY
16:55:25.056 INFO  GermlineCNVCaller - Parsing the copy number transition prior table and initializing the caches...
16:55:28.634 INFO  GermlineCNVCaller - Initializing the EM algorithm workspace...
16:55:32.861 INFO  GermlineCNVCaller - Shutting down engine
[June 12, 2017 4:55:32 PM ACST] org.broadinstitute.hellbender.tools.coveragemodel.germline.GermlineCNVCaller done. Elapsed time: 0.18 minutes.
Runtime.totalMemory()=1364721664
org.broadinstitute.hellbender.exceptions.GATKException: Nd4j data type must be set to double for coverage modeller routines to function properly. This can be done by setting JVM system property "dtype" to "double". Can not continue.

Thanks

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/gatk/discussion/comment/39376#Comment_39376

**Comment by sooheelee** [comment]
I refreshed my page and now see your answer! Thanks for that.

**Comment by samuelklee** [comment]
Deleted in #3935.
