### ISSUE TITLE
update com.google.guava version

### ISSUE THREAD

**Issue by david-wb** [broadinstitute/gatk#3102]
Hi, 

I am trying to run GATK with against a Java NIO library that depends on `com.google.guave:22:0`.
In the GATK `build.gradle` there is a `force 'com.google.guava:guava:18.0'` at line 71. This version is 3 years old. Can you consider updating it to a newer version? 22.0 is the latest.

Thanks,
David

**Comment by lbergelson** [comment]
@david-wb Upgrading guava seems reasonable.  I suspect it should work with newer versions without major problems.  Did you find a workaround?  Also, I'm curious what NIO library you're using?  Is it one for S3?

**Comment by david-wb** [comment]
Yeah, the workaround was simply to add the library jar to the classpath and not try to compile them together. I created the issue to soon, Sorry. 

As for the NIO library, it is for AWS S3. We are adapting this one https://github.com/Upplication/Amazon-S3-FileSystem-NIO2 to meet our needs. We didn't like the way it handles s3 endpoints because AWS EMR Spark clusters don't support s3 uri's with that particular syntax. Our version modifies it to support normal s3 uri's without endpoints, instead setting allow the endpoint to be set with a configuration parameter.

**Comment by lbergelson** [comment]
I tried a quick upgrade of our guava dependency from 18 -> 22, but it ends in test failures.  It looks like at least one of our hadoop dependencies  requires guava <= 18.  I'm not totally clear if it's an issue for hadoop-core or only in hadoop-minicluster which is a library we use for running tests.  If you're not using hdfs I think you won't have any problems including 22, but I'm afraid we can't upgrade our default version without some work.  

Hopefully hadoop 3.x will solve the problem in general by shading their internal version of guava. 
 https://issues.apache.org/jira/browse/HADOOP-14284, https://issues.apache.org/jira/browse/HADOOP-10101.

It sounds like you have a reasonable workaround, let us know if you have further issues with it.

**Comment by david-wb** [comment]
No worries, I think compiling my library with guava 22 and adding the jar to the gatk classpath will do the trick. Thanks very much for taking a look at this.

**Comment by lbergelson** [comment]
@david-wb Is your s3 plugin available as an open source plugin that others could use?  We had another question about s3 support in gatk and I thought you might have some insight about it.

**Comment by david-wb** [comment]
Hi Louis,


Our simple s3 nio library is not currently open source, but we would be willing to make it so after testing it properly. We found that to get the s3 nio library work with GATK, a few minor changes need to be made the in the GATK source. This is especially true for the spark tools because, on AWS EMR Spark clusters, s3 uris can be treated exactly as if they are HDFS uris. Therefore, it was not quite as simple for us to just add the s3 nio library to the classpath and have everything work as expected. For that reason would put the project on hold until GATK is closer to release.


Thanks,

David

________________________________

**Comment by lbergelson** [comment]
Hi David, 

Thanks for the reply.  I'm sorry to hear that you had to put things on hold.  A lot of the spark tools are not refined to the point they need to be for productive use.  We hope to fix a lot of the spark issues towards the end of the summer or beginning of fall, so maybe we can revisit this then.  

I'm curious what changes you ended up making to gatk.  We've had to do quite a lot of work to get gcs NIO support working well so it's not surprising that there would be similar changes needed for s3.  

We'd definitely be interested in hearing about your work on this though, maybe we could schedule a chat at some point once we're nearing the end of beta.  It would be really valuable to have native support for s3 in gatk, and I think you've gotten the closest to making it happen.

**Comment by david-wb** [comment]
Sure thing. I can find out which changes I needed to make in gatk  to get certain tools to work, like `PrintReads` and `MarkDuplicates`, though they were certainly not exhaustive. We will also see about open sourcing our s3 nio library which is basically a rewrite of https://github.com/Upplication/Amazon-S3-FileSystem-NIO2 with changes for handling s3 endpoints.
