### ISSUE TITLE
Is there a spark version of GenotypeGVCFs?

### ISSUE THREAD

**Issue by hliang** [broadinstitute/gatk#3103]
In GATK3, we usually do joint genotyping by calling HaplotypeCaller (bam -> gvcf), then GenotypeGVCFs (gvcf -> vcf).
Looks like HaplotypeCallerSpark can produce gvcf files, but there is no "GenotypeGVCFsSpark" in GATK4. So is there a spark version of GenotypeGVCFs, or equivalent tool, to do the job?

**Comment by lbergelson** [comment]
@hliang We currently don't have a spark version of GenotypeGVCFs.  We would like to implement one in the future but we don't have a timeline for it.

**Comment by hliang** [comment]
What's the recommended way, if there is one, for joint genotyping hundreds of samples on Spark?
There are spark tools for fastq -> bwa/bam -> BQSR/bam -> haplotypecaller/gvcf, but I'm not sure what's next.

**Comment by lbergelson** [comment]
At the moment there's no way to do joint genotyping in spark.  The pipeline we use for our production data is to take the gvcfs from haplotype caller -> GenomicsDBImport -> GenotypeGVCFs -> VariantRecalibration.  We're still fine-tuning the non-spark version of the pipeline.  Once that's finished we would like to implement a version in spark, but there are other things that have higher priority for us so I'm not sure when we will get to it.

**Comment by droazen** [comment]
Closing as answered
