### ISSUE TITLE
Do VCF indices have proper dictionaries?

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#3119]
Somehow Kris managed to generate a VCF with an index that doesn't have a properly sorted sequence dictionary: gs://broad-dsde-methods/kcibul/bug_for_louis  I think it was with GATK4 SelectVariants (with a version prior to the commandline being put in the header), but I'm not 100% sure.

Generating the index on the fly with GATK3 works fine.  I'm not sure if the original tabix index from the GotC pipeline is okay: gs://broad-jg-dev-storage/temp/09C99383.91c5a812-70c5-4526-a3a2-3e99b9cf08fb.g.vcf.gz.tbi

I found this because GATK3 complained about the contig order.

**Comment by droazen** [comment]
@ldgauthier Can this be reproduced with the latest gatk/master? There was a fix for a similar issue in htsjdk recently that I believe has now propagated to GATK.

**Comment by ldgauthier** [comment]
I'm going to close this until someone sees it again.  Test data is gone.
