### ISSUE TITLE
Allow retry settings to be set globally in google-cloud-java, rather than per-Path

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3120]
Currently we set NIO retry settings on a per-Path basis in `BucketUtils.getPathOnGcs()`. This is a bit brittle, since there are places in other libraries like htsjdk that create their own `Path` objects on-the-fly, and these new Path objects don't respect our retry settings (see https://github.com/broadinstitute/gatk/issues/2749).

Ideally we'd be able to set these retry settings globally on startup, and all `Path` objects created anywhere would inherit these settings.

**Comment by droazen** [comment]
For @jean-philippe-martin and the 4.0 milestone.

**Comment by droazen** [comment]
@jean-philippe-martin Mind prioritizing this one? We are building a custom snapshot of `google-cloud-java` with `maxChannelReopens` hardcoded to the value we want, which should resolve https://github.com/broadinstitute/gatk/issues/2685 for now, but it would be great to have a permanent solution in master. Requiring GATK to construct Path objects a certain way and pass them down into libraries like htsjdk is just too brittle, as those libraries often need to create Path objects on-the-fly and we lose our settings. Ideally we'd just be able to call a static method (or similar) at GATK startup to force all instances of `CloudStorageReadChannel` to use our desired settings.

**Comment by jean-philippe-martin** [comment]
You got it.

**Comment by droazen** [comment]
Thanks!

**Comment by jean-philippe-martin** [comment]
Pull request is up: https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2159

**Comment by jean-philippe-martin** [comment]
(for what it's worth, an "ideal library" could get the filesystem object from the provided path and then use that to create the new paths it needs and maintain all the options. Granted, I haven't seen anyone do this yet)
