### ISSUE TITLE
SVFastqRead with reversed strand mapped reads.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#3131]
Fastq files writen using this ulitity contains reads with bases and qualities as they appear in the original aligned bam file. 

Reads that map to reverse strand have their based changed to the reverse complement with respect with the original sequenced bases. This results in a lost of information where we do not know whether the read in the .fastq file generated contains either the original base calls or their reverse complement. 

We need to fix that.

**Comment by SHuang-Broad** [comment]
Should this be closed now, after #3133 ?

**Comment by vruano** [comment]
yes.
