### ISSUE TITLE
Ensure that the -Xmx values in the example tool commands in GATKDocs are accurate

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3137]

**Comment by droazen** [comment]
We should make sure these values are appropriate for each tool.

**Comment by droazen** [comment]
For @sooheelee @vdauwera @chandrans and the 4.0 milestone.

**Comment by sooheelee** [comment]
I use 4G as the default except for one tool where I show 16G (if I remember correctly). How do we determine what is the correct amount?

**Comment by chandrans** [comment]
That is a good question Soo Hee. I myself don't set the argument unless I get an error. If I do get an error, I just set is to 100G which is outrageous, but I don't know how much is appropriate. If anyone else has suggestions, I would be interested in the answer too.

**Comment by vdauwera** [comment]
I'm not crazy about the idea of specifying this in the example commands in general. It will depend a lot on what data and use case a user is going through at any given time. I would much prefer leaving specific recommendations to our pipeline scripts, where we can use whatever the prod pipeline uses, and say "given this use case and example data, this is what works, ymmv".

So I would actually advocate for removing all -Xmx values in the tool docs.

**Comment by droazen** [comment]
@vdauwera There are some tools that have very specific requirements with regards to `-Xmx`, however. For example, `GenomicsDBImport` requires that you size your `-Xmx` value significantly **smaller** than the total amount of free memory on the machine, in order to leave enough room for the native heap. If you don't do this, you will get truly horrific and cryptic messages when the native code crashes with out-of-memory. This is really something that needs to be documented prominently!

I'd advocate for selective inclusion of recommended `-Xmx` values in the docs, for cases like the above where it really matters.

**Comment by vdauwera** [comment]
Ah well, that definitely sounds like something that needs to be documented, indeed! 

I just don't want to end up having to do it systematically and making up numbers that don't really mean anything.

**Comment by sooheelee** [comment]
Do the WDL scripts in the repo reflect some rough proportionate setting for `-Xmx`?

**Comment by droazen** [comment]
@vdauwera Agreed, it should be selective -- only for tools that have unusual memory requirements.

**Comment by sooheelee** [comment]
@droazen, can you help us out and list the tools that have this unusual memory requirement? I'm back from ASHG and visiting family and am just now turning my attention to GATK4 documentation.

**Comment by sooheelee** [comment]
This is left to the developers who will update the tool docs.

**Comment by sooheelee** [comment]
So far, there is a mix of adding or not adding the -Xmx params and I have been leaving this up to the developers. Going forward I should remind the developers to only specify this if needed.

**Comment by sooheelee** [comment]
We've taken a stab at this with the tooldoc updates. There may be things to change going forward, but we can deal with them as they come.
