### ISSUE TITLE
Does GATK 4 support multiple bam files as input?

### ISSUE THREAD

**Issue by Blaok** [broadinstitute/gatk#3142]
In the command line help message, it says 

```--input,-I:String             BAM/SAM/CRAM file containing reads  This argument must be specified at least once.```

However, if we actually give multiple input files, it says

```org.broadinstitute.hellbender.exceptions.UserException: Sorry, we only support a single reads input for spark tools for now.```

 On the other hand, if we specify the input parameter as the folder containing all partial bam files, it actually works. Could you explain how this feature works now?

**Comment by vdauwera** [comment]
Hi @Blaok, please post usage questions (ie not related to development) in our support forum at http://gatkforums.broadinstitute.org/gatk.
