### ISSUE TITLE
Refactor WGS coverage collection and GC annotation.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#3153]
This should be more parallel to the WES workflow and should take an interval list of precomputed bins as input.  Consider using ReadWalkerSpark.

**Comment by mbabadi** [comment]
Also, a necessary functionality is fragment-based counts. Perhaps a good starting point is bringing back Valentin's GATKReadPair which was removed as a part of XHMM-related code cleanup.

Eventually, it is also useful to have the option of collecting various summary statistics and empirical distribution for features such as insert length, mapping quality, the position with respect to bins. Other things to consider are summary of orphan reads, reads with mates on other contigs, and reads with multiple alternate alignments. This requires a bit of good software engineering but it's a necessary one-time investment.

This is a relatively high-priority refactoring given the growing interest in running gCNV on large datasets (gnomAD, gen psy cohort, TCGA).
