### ISSUE TITLE
Determine whether we need to support zero-length intervals

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#317]
Some factors to consider in making this decision:

-Operations on zero-length intervals are error-prone due to lack of understanding/consensus about expected results (eg., should a query on a zero-length interval return records that abut it on either side?)

-We need to determine how a query involving a zero-length interval is supposed to behave in the GA4GH API, as this does not seem to be clearly defined in the API documentation (eg., http://ga4gh.org/documentation/api/v0.5.1/ga4gh_api.html#/schema/%2FUsers%2Fkeenan%2FDropbox%2Fgit-checkouts%2Fschemas%2Fsrc%2Fmain%2Fresources%2Favro%2Ftarget%2Fall.avpr/org.ga4gh.GASearchReadsRequest). The representation is 0-based closed-open (like BED), which means zero-length intervals are possible, but their behavior appears undefined.

-None of our current query interfaces (tribble/samtools) support computing overlap with zero-length intervals (although they don't throw an error when given such an interval -- they just never return any records for such queries).

-It seems unlikely that we'll be moving anytime soon to representing insertions using zero-length intervals, given that the VCF spec requires insertions to be represented in terms of the preceding reference base.

**Comment by akiezun** [comment]
@droazen can you clarify how this is going to get resolved? Is it our decision or are we waiting for someone? Assigning to you to clarify

**Comment by droazen** [comment]
I vote against supporting zero-length intervals and closing this issue, unless there is a very compelling use case. Objections?

**Comment by vdauwera** [comment]
Can we clarify what it means to not support zero-length intervals? I.e. if we encounter them, what happens? Do we throw an error, or silently ignore them, or something else?

**Comment by droazen** [comment]
@vdauwera We currently throw an exception if we encounter a zero-length interval.

**Comment by vdauwera** [comment]
Maybe it would be good to have a flag that allows silent skipping so users
can proceed without having to modify their intervals file.

**Comment by sooheelee** [comment]
Here is a [Biostars post](https://www.biostars.org/p/84686/) of users discussing their preferences. 

Ensembl uses 1-based coordinate system
UCSC uses 0-based coordinate system

**Comment by vdauwera** [comment]
@sooheelee We do support both 1-based and 0-based systems; the question here is what do we do with intervals that have a length of zero, which can arise in 0-based systems.

**Comment by sooheelee** [comment]
@vdauwera My newbie question is--What are the operations we can do on intervals? For example, a reference interval of given length, do we have an operation that returns all variant sequences (or sequence lengths) within that interval? In this case, we'd want to be able to return a variant that is an insertion in that interval (ignores all other variants including deletions spanning the coordinates). This is what comes to mind for someone who has never analyzed a VCF.

**Comment by vdauwera** [comment]
@sooheelee Let's take this discussion offline to avoid introducing noise into this dev issue.

**Comment by akiezun** [comment]
let's close this. it's easy to reopen of this is ever an actual problem

**Comment by droazen** [comment]
Re-opening -- it is a problem, and we need to make a decision on it.

**Comment by akiezun** [comment]
How is it a problem? What errors does it cause?

**Comment by droazen** [comment]
It's a problem because we have to work with formats that support zero-length intervals (eg., BED). We need to talk this issue through and come to a clear decision.

**Comment by droazen** [comment]
Closing -- we are not going to support zero-length intervals in GATK4.
