### ISSUE TITLE
Request: adding Altivec based pairhmm library libVectorLoglessPairHMM.so support for GATK4

### ISSUE THREAD

**Issue by yhcheng** [broadinstitute/gatk#3180]
Currently GATK4 walker mode won't recognize altivec-based libVectorLoglessPairHMM.so only AVX based library. On POWER it will Falling back to the MUCH slower LOGLESS_CACHING implementation.

To avoid performance degradation on POWER for Haplotyecaller, please include support for Altivec based pairhmm library libVectorLoglessPairHMM.so
Two possible ways to do it:
1. integrate support by using "grep -i altivec /proc/cpuinfo" to identify availability of Altivec support and then integrate the library
2. We can setup Java path or other options that will look for any libVectorLoglessPairHMM.so available and test compatibility.

We would do all necessary works to get this done, but would appreciate your direction on which way to peruse. Thanks!

**Comment by davidbenjamin** [comment]
@droazen Doing my occasional issue-pruning -- does this issue need to stay up?

**Comment by droazen** [comment]
Yes, we can close this one.
