### ISSUE TITLE
Make a GC bias annotator for Megan and Sam

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/gatk#3205]
Write a simple annotator that annotates a vcf with a GC context in the reference near a variant as an INFO field. Ideally it would take a k-mer size as an argument, but I'm not sure if VariantAnnotator supports that.

**Comment by takutosato** [comment]
@meganshand, @lucidtronix

**Comment by droazen** [comment]
Arguments within annotation classes are an engine ticket that we hope to complete this quarter: https://github.com/broadinstitute/gatk/issues/1880

**Comment by davidbenjamin** [comment]
@takutosato Do Megan and Sam still want this, or can we close?

**Comment by takutosato** [comment]
I doubt it. Closing.
