### ISSUE TITLE
cosmic is not a recognized option in GATK4 Mutect2

### ISSUE THREAD

**Issue by ycl6** [broadinstitute/gatk#3207]
I am trying the latest version of GATK4 (gatk-4.beta.1), and it seems Mutect2 does not accept cosmic file as the variant whitelist any more. It is an oversight or have this been removed in GATK4?

**Comment by sooheelee** [comment]
Hi @ycl6, please post your questions to the GATK forum at <http://gatkforums.broadinstitute.org/gatk>. 

It has been removed in GATK4.

GATK4 Mutect2 now takes a known population variants resource, e.g. gnomAD, with allele-specific frequencies. I've put such an example resource in the GATK bundle at <https://software.broadinstitute.org/gatk/download/bundle>, in the folder labeled `beta`.

**Comment by ycl6** [comment]
Thanks @sooheelee

**Comment by lbergelson** [comment]
Closing since it seems like this is resolved.
