### ISSUE TITLE
--gatherType BLOCK in GatherVcfs fails with IllegalStateException on empty VCFs

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/gatk#3218]
If one of the block compressed VCFs in the list is empty (i.e. it does have proper header lines but there are no variant records, which is perfectly valid) then the tool fails with an IllegalStateException:

java.lang.IllegalStateException: Could not read available bytes from BlockCompressedInputStream.
at org.broadinstitute.hellbender.utils.Utils.validate(Utils.java:697)
at org.broadinstitute.hellbender.tools.GatherVcfs.gatherWithBlockCopying(GatherVcfs.java:354)

**Comment by droazen** [comment]
@lbergelson Can you have a look?

**Comment by lbergelson** [comment]
Will fix today.
