### ISSUE TITLE
Turn off assemblies of non-primary contigs

### ISSUE THREAD

**Issue by cwhelan** [broadinstitute/gatk#3225]
These seem to be generating contigs that spuriously map back to primary chromosomes and generating spurious SV calls.

**Comment by SHuang-Broad** [comment]
@cwhelan Can you please provide some of these calls? I am considering filtering the mapping/alignments and want to evaluate the filter's performance. Thanks!

**Comment by cwhelan** [comment]
@TedBrookings and I noticed a few but didn't record them. If someone wants to evaluate them, I suggest doing it systematically: you could find all the IDs of intervals that were identified on non-primary contigs, and search the VCFs for variants where the contigs assembled came from those intervals.

I think at least until we can handle them better we'll probably want to just turn off interval finding on the non-primary contigs.

**Comment by SHuang-Broad** [comment]
@cwhelan 
while I'm going over our tickets, is this done already? Or someone is handling this?

**Comment by cwhelan** [comment]
We turned off gathering evidence from non-primary contigs back in #4438 . Closing this.
