### ISSUE TITLE
Write an example VariantWalker

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#323]
VariantWalker needs an example implementation, as the other Walker types already have.

**Comment by akiezun** [comment]
does CountVariants count? if not, can you specify the requirements for the example?

**Comment by droazen** [comment]
It should be similar to `ExampleIntervalWalker` -- a basic reference implementation for authors to use as a starting point.

**Comment by akiezun** [comment]
i can grab this one

**Comment by droazen** [comment]
And make sure we have examples for all kinds of walkers.
