### ISSUE TITLE
Eliminate Targets from new/legacy CNV tools.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#3246]
The use of Targets to refer to genomic intervals is unnecessary and confusing.  It obfuscates the fact that most of the tools and code can be applied to not only counts from WES targets, but also counts from WES baits, WGS bins, etc.  Requiring that Targets be named also adds unnecessary storage and memory burden.  We should just use SimpleIntervals everywhere.  We should also get rid of the target file format.

In terms of external visibility, we can just rename tools and edit javadoc.  Internally, there will be many classes that need to be both renamed and refactored.  I instead suggest that we rebuild new versions of the classes and tools as necessary in the tools/copynumber package.

- [ ] Rename tools: AnnotateTargets -> AnnotateIntervals, TargetCoverageSexGenotyper -> ReadCountSexGenotyper.  
- [ ] Deprecate tools: CalculateTargetCoverage, ConvertBedToTargetFile, and PadTargets will be replaced by @asmirnov239's new CollectReadCounts tool and on-the-fly padding specified by --interval_padding parameters.
- [ ] Deprecate target file format and change all other affected file formats.
- [ ] Refactor/rename/rebuild classes.

**Comment by sooheelee** [comment]
Hey remember the GATK engine's `-L` parameter for specifying intervals.

**Comment by samuelklee** [comment]
Definitely!  This would allow us to take intervals as input in more standard ways throughout.

**Comment by samuelklee** [comment]
Actually, one thing we will have to consider is that `-L` will take the union or the intersection of input intervals.  We will want to keep adjacent intervals separate.  Optional checks for overlaps would also be nice.  @droazen @lbergelson let me know what you think?

**Comment by droazen** [comment]
@samuelklee We can easily expose the `IntervalMergingRule` in `IntervalArgumentCollection` (which is where `-L` is defined) as an argument to prevent the merging of adjacent intervals. We could also add a way for individual tools to set a default value for `IntervalMergingRule` themselves.

**Comment by samuelklee** [comment]
Sounds good to me!
