### ISSUE TITLE
Tagged files aren't echoed back correctly as args

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#3247]
I tried to run VariantRecalibrator using the args echoed from an integration test and found that the resource files weren't listed properly.  The command in the test was ` " --resource known,known=true,prior=10.0:" + getLargeVQSRTestDataDir() + "dbsnp_132_b37.leftAligned.20.1M-10M.vcf"` and what came out of the engine was `--resource known:/Users/gauthier/workspaces/gatk/src/test/resources/large/VQSR/dbsnp_132_b37.leftAligned.20.1M-10M.vcf`, so it lost the known=true and the prior which makes the command line unrunnable. Probably affects #2269 too.

This behavior can be replicated by running any of the VariantRecalibration integration tests and checking the console output.

**Comment by cmnbroad** [comment]
This happens because the current FeatureInput toString implementation doesn't round-trip the key-value pairs, only the name and path. We could fix it in the short term, or we could wait until we switch to using Barclay tagged arguments, which preserves these.

**Comment by ldgauthier** [comment]
This isn't urgent. We can wait til the Barclay switch.

**Comment by ldgauthier** [comment]
This still isn't perfect, but it will suffice.  In the current master the arguments come out like:
```
--resource:known,known=true,prior=10.0 known:/Users/gauthier/workspaces/gatk/src/test/resources/large/VQSR/dbsnp_132_b       37.leftAligned.20.1M-10M.vcf
--resource:truth_training1,truth=true,training=true,prior=15.0 truth_training1:/Users/gauthier/workspaces/gatk/src/test/resources/large/VQSR/sites_r27_nr.b37_fwd.20.1M-10M.vcf
--resource:truth_training2,training=true,truth=true,prior=12.0 truth_training2:/Users/gauthier/workspaces/gatk/src/test/resources/large/VQSR/Omni25_sites_1525_samples.b37.20.1M-10M.vcf
```
which don't parse perfectly if you try to run them as a command, but at least all the information is there.  (false attributes are dropped, but will be interpreted correctly if omitted)

This isn't causing me any problems, so I'm going to close it.
