### ISSUE TITLE
Add multi-interval support to GenomicsDBImport

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3269]
`GenomicsDBImport` is currently designed for scattering on a cluster, and so accepts only a single interval per invocation. To make it easier to run the tool locally as a replacement for `CombineGVCFs`, we should add the ability to pass in multiple intervals at once.

**Comment by droazen** [comment]
For @kgururaj and @kdatta

**Comment by ptranvan** [comment]
Multi intervals working now ?

**Comment by droazen** [comment]
Not yet @ptranvan. @kgururaj and his team have a patch coming soon to add multi-interval support to this tool, so there's a good chance it will make it into a GATK release this month.

**Comment by ajshultz** [comment]
Hello,
Any update to the timeline here? It looks like there is only some lasts tests to be run? I am eagerly awaiting multi-interval support for a project I am working on. Thank you for all of your hard work!

**Comment by droazen** [comment]
Should not be much longer @ajshultz -- https://github.com/broadinstitute/gatk/pull/4645 just needs a final review pass, so it's likely to make the next GATK release.

**Comment by droazen** [comment]
Implemented in https://github.com/broadinstitute/gatk/pull/4645
