### ISSUE TITLE
Add tribble codec (read support) for GENCODE files to htsjdk

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3277]
We'll need to support both hg38 and hg19 inputs.

**Comment by jonn-smith** [comment]
@lbergelson suggested looking at the IGV Tribble codec for Gencode:
https://github.com/igvteam/igv/blob/8b4fa74fc51d20f91c467f123f6e8b8bf23698e5/src/org/broad/igv/feature/tribble/GFFCodec.java 

I'll start by checking this out.

**Comment by lbergelson** [comment]
It looks like there's an hg37 lift over of the hg38 data that uses the same format so that should suffice hopefully.
