### ISSUE TITLE
Bundle annotation-related arguments into an ArgumentCollection

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3292]
Currently tools using the annotation engine are manually defining arguments to control which annotations should be enabled/disabled. See `HaplotypeCallerArgumentCollection` `annotationsToUse`/`annotationGroupsToUse` for an example. We should bundle these into a reusable argument collection, like we did for read filters, as part of the task of making annotations a barclay plugin.

**Comment by magicDGS** [comment]
It will be very useful to have an abstract class for the plugin arguments (as I did for the read filters plugin in #2355) to be able for downstream projects to change default values or hide arguments to the final user.
