### ISSUE TITLE
Disable non-docker unit/integration tests

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3294]
Once we do https://github.com/broadinstitute/gatk/issues/2817, we can disable the non-docker unit and integration tests in travis, saving a huge amount of time and resources. (We should keep the instance of the tests that run on the Oracle JDK, however).

**Comment by droazen** [comment]
Must be done after https://github.com/broadinstitute/gatk/issues/2817

**Comment by jamesemery** [comment]
Closed by this pull request https://github.com/broadinstitute/gatk/pull/3353.
