### ISSUE TITLE
Decimals in periods vs commas possibly erring tools for international users

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3297]
User has reported default settings in other countries cause tools to error because of the switch between commas and periods.  The tools themselves generate the data with the commas that then error downstream tools. User reports a workaround solution of adding `-Duser.language=en -Duser.country=US` to commands but this is cumbersome. 

Should our tools should be internationally compatible?

---
Hi @shlee, @slee,

yes it is working when I replace the commas with points, but since I am using the wdl-pipeline which was provided by slee on gitHub, this is not a sufficient workaround. Due to my expectation that the problem (commas instead of points) arise from my language settings I try different thing to change my actual language on the system. To make the long story short the solution was to start CalculateTargetCoverage with the flags (I added them in the cnv_somatic_tasks.wdl):
```
java -Duser.language=en -Duser.country=US -Xmx${default=4 mem}g -jar ${gatk_jar} CalculateTargetCoverage
```
And now the cnv_somatic_panel_workflow.wdl runs smoothly to the end, with points instead of commas :)

An other solution would be to running the pipeline in a DockerContainer wich have an english java-version installed, like the one which is provide by the gatk-team.

I hope this helps other user too which are working with non-englisch java versions.

Greetings EADG

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/40481#Comment_40481

**Comment by sooheelee** [comment]
Not sure who this type of issue would go to. Assigning to @droazen for further dispatching.

**Comment by vdauwera** [comment]
Language should probably be set to English by gatk launch

**Comment by cmnbroad** [comment]
We recently made a change that should prevent this from happening (we set the locale to English/US before we run the tool), so I wouldn't expect to see this in recent builds. I think that change was in for beta 1; I think the first thing we should do is verify which GATK build/version this occurs in (I can't tell from the forum post).

**Comment by chandrans** [comment]
Thanks Chris. Just asked user to clarify. Must be using an alpha build I suspect.

**Comment by sooheelee** [comment]
Seems this is addressed.
