### ISSUE TITLE
PlotSegmentedCopyRatios says run is successful without actually generating plots

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3301]
User is @wleeidt and they outline their case in <https://gatkforums.broadinstitute.org/gatk/discussion/comment/40530#Comment_40530>.

**I can generate plots** with their data and so presumably they are missing some component for the tool to generate plots. Whatever these dependencies, the tool should not emit a `SUCCESS` for the run when plots are absent. User instead gets a `plotting_dump.rda` file.

Data is at `/humgen/gsa-scr1/pub/incoming/bugReport_by_wleeidt.updated.zip`.
User's system is
```
Mac OS X
10.11.4 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_101-b13; 
```
GATK Version:
```
4.beta.1
```
Command
```
gatk-launch PlotSegmentedCopyRatio -TN S4_tumor.pn.tsv -PTN S4_tumor.ptn.tsv -S S4_tumor.seg -O sandbox -SD hg19.dict -pre S4_gatk4_cnv_segment -LOG
```

Tool could use better error messaging. I will hand this to @LeeTL1220 for appropriate assignment.

**Comment by sooheelee** [comment]
User replies the missing element was the Rscript packages and once this was installed they were able to plot.

So the error message needs to point to the repo's Rscript and the dependent R packages it installs.

As of this writing, here is what the error message should say:

> Install R package dependencies using `Rscript install_R_packages.R` with the script from https://github.com/broadinstitute/gatk/blob/master/scripts/docker/gatkbase/install_R_packages.R. The script lists the packages.

**Comment by LeeTL1220** [comment]
@samuelklee should delegate it.

**Comment by samuelklee** [comment]
Deleted in #3935, but I tried to replicate with the new versions of the CNV plotting tools.  I get a sensible warning if a package is missing, e.g.:

`Stderr: Error in library(data.table) : there is no package called ‘data.table’`
