### ISSUE TITLE
(How to) Call somatic copy number variants using GATK4 CNV

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3313]
I'm not familiar with ACNV nor GetBayesianHetCoverage, so I need to consult a dev on this question.

---

@shlee. I have a question about the PoN. You mentioned previously that it's recommended to have at least 10 normal samples to generate the PoN. What if I only have 2 normal samples? Is that going to affect the accuracy of the whole CNV analysis? I plotted the minor allele frequency using `PlotACNVResults` using `GetBayesianHetCoverage` to get the het SNPs with one normal bam and one tumor bam. And in the end, the minor allele frequency all hovering around 0.3, which looks strange. 

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/40588#Comment_40588

**Comment by sooheelee** [comment]
Could either @LeeTL1220 or @samuelklee look into this or delegate onwards?

**Comment by samuelklee** [comment]
User was not using matched tumor/normal for GetBayesianHetCoverage.

**Comment by sooheelee** [comment]
Thanks for following up with the user Sam.
