### ISSUE TITLE
Implement 1D and 2D adaptive quadrature

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#3318]
Integrals are part of life and Apache Commons' methods are lacking.

**Comment by mbabadi** [comment]
I suggest making composite quadratures by stacking multiple copies of low-order quadratures. Also, note that high-order Gaussian quadratures only provide reliable error guarantees for smooth integrands. Composite quadratures with the same number of grid points often give better estimates than a high-order quadrature with the same number of points.
