### ISSUE TITLE
Make Mutect command line arguments consistent with rest of GATK

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#3325]
Some are camel case already, some are python-style underscored arguments, and none are in the new standard format of #2596.  Note that this requires carefully changing our wdls!!!  @LeeTL1220 and @vdauwera this is easy enough to do, but any considerations on timing relative to releases or other logistical thoughts?

I notice that this inconsistency is shared with HaplotypeCaller. . .

**Comment by droazen** [comment]
@davidbenjamin This proposal conflicts with https://github.com/broadinstitute/gatk/issues/2596

**Comment by davidbenjamin** [comment]
@droazen Thanks for pointing that out.  I'll convert the issue to "make sure M2 is not a renegade of command line arguments."

**Comment by davidbenjamin** [comment]
We'll wait to see what style HaplotypeCaller switches to.

**Comment by droazen** [comment]
@davidbenjamin If you have an opinion on what style GATK should standardize on, please comment on https://github.com/broadinstitute/gatk/issues/2596!

**Comment by davidbenjamin** [comment]
Geraldine has confirmed that the GATK is moving to the style of #2596.  This ticket is ready to proceed.

**Comment by davidbenjamin** [comment]
Closed by #3584.
