### ISSUE TITLE
M2 WDL (as all analysis WDLs really) should use gatk-launch instead of calling the jar directly

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#3334]
Currently the M2 WDL needs to be given the path to a GATK4 jar and calls the jar directly in the commands. This should be amended to use gatk-launch instead (per @droazen). 

@davidbenjamin @LeeTL1220

**Comment by droazen** [comment]
Yes, bypassing `gatk-launch` causes a number of important system properties (such as htsjdk settings) to not get set. This should be easy to fix, as `gatk-launch` is in the standard docker image in `/gatk`

**Comment by vdauwera** [comment]
So at the risk of sounding thick, what exact path do I use in my command when I'm calling the docker? Imagine I'm a six year old who doesn't understand what is the internal structure of the GATK docker image or what "gatk-launch is in the standard docker image in /gatk" means. Note that right now to call the jar I use /root/gatk.jar

**Comment by droazen** [comment]
@vdauwera Within the docker image, just `cd /gatk`, then run `./gatk-launch ToolName etc.`

**Comment by droazen** [comment]
You can also invoke the `gatk-launch` script by absolute pathname: `/gatk/gatk-launch ToolName etc.`

**Comment by davidbenjamin** [comment]
Requested guidance (in a different ticket) on how this works when running locally.

**Comment by davidbenjamin** [comment]
This is about to be closed by #4071.
