### ISSUE TITLE
Document Pair-HMM alignment in Mutect 2

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#3338]

**Comment by ronlevine** [comment]
@davidbenjamin I am doing something similar for HaplotypeCaller. When do you expect to have a pull request? I can add my notes.

**Comment by davidbenjamin** [comment]
@ronlevine I haven't started, but start to PR would be a few days to a week.  However, if you're doing the same thing my efforts might be totally extraneous.  It depends what exactly you're doing but Pair-HMM is the same for HC and M2.

**Comment by ronlevine** [comment]
@davidbenjamin It's more developer centric and would complement your document. I plan to explain the Pair HMM from a HIGH level and point to places in the code that pertain to the algorithm.

**Comment by davidbenjamin** [comment]
Okay, then I'll proceed and probably have a PR in a week.

**Comment by davidbenjamin** [comment]
Closed by #3433.
