### ISSUE TITLE
Mutect 2 documentation

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#3340]
We have been responsible about documenting new features.  We should now document everything else.  @vdauwera @chandrans @sooheelee

**Comment by chandrans** [comment]
@davidbenjamin Hi David. Happy to help as soon as I get caught up on the forum and a few other things. However, I think we are waiting for Mutect2 to be out of beta status to focus our full efforts on documenting it.

**Comment by davidbenjamin** [comment]
@chandrans Don't worry, this ticket is not meant to imply any responsibility for the comms team.  I was looping you in because the docs we produce will hopefully be useful to you.

**Comment by davidbenjamin** [comment]
We did it!
