### ISSUE TITLE
Have SparkGenomeReadCounts produce a HDF5 for coverage in addition to the tsv and make it readable during PoN creation.

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#3349]
This would probably yield a non-trivial increase in speed, since much of the time spent is I/O.

**Comment by LeeTL1220** [comment]
Keep default to be current behavior.  Add a flag to produce a HDF5 equivalent file.

@samuelklee

**Comment by samuelklee** [comment]
Thanks for taking care of this.  Be sure to take a look at the HDF5RandomizedSVDReadCountPanelOfNormals.IntervalHelper class in my sl_create_pon branch.  I changed the way intervals are written to HDF5 to be faster and more space efficient by using a double matrix.  Still a little hacky IMO, but since we can't write integer matrices it'll do for now.

**Comment by lbergelson** [comment]
@samuelklee Why can't we right integer matrices?  Is that a missing feature in the hdf5 wrapper we built or is it fundamental to hdf5?

**Comment by samuelklee** [comment]
I believe it's missing in the wrapper, although I'm not sure why?

If we revisit the wrapper code, there is some chunking functionality I've introduced in my branch for #2858 that we should perhaps also add.  The writing of string matrices is also a bit awkward and could be improved.

**Comment by samuelklee** [comment]
@LeeTL1220 reminds me that there is also some code for reading/writing intervals that I introduced that probably belongs in the wrapper as well.

**Comment by lbergelson** [comment]
@samuelklee Should we make some tickets to update the wrapper?

**Comment by samuelklee** [comment]
Yes, let me know if they should go in this repo or the wrapper repo.

**Comment by samuelklee** [comment]
I've noticed that HDFUtils.writeIntervals seems a bit more memory intensive than it should be.  I'm getting OOM errors for bin sizes of 250bp with -Xmx12G, which seems like it should be more than enough.  Let's remember to investigate before merging.
