### ISSUE TITLE
Pileup needed for AllelicCapseg

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#335]
AllelicCapseg needs base counts from pileup. This does not exist in gatk4 yet. Assigning to @LeeTL1220 to connect with @droazen to flesh out what needs to be implemented.

**Comment by akiezun** [comment]
@LeeTL1220 can we schedule this for the next milestone (~6 weeks)

**Comment by akiezun** [comment]
@LeeTL1220 @samuelklee Can you clarify if we still needs this given the current work in ACS?

**Comment by samuelklee** [comment]
Based on the code above, I implemented a public static method getPileupBaseCounts to get base counts from pileups in the class HetPulldownCalculator in hellbender-protected.  However, if this method will be needed by anything else, it could probably be moved out of this class.

**Comment by samuelklee** [comment]
After getting feedback from @vruano on Issue 45 in hellbender-protected and speaking with @droazen and @lbergelson, it seems that LocusWalker should be implemented instead.

For the time being we will move forward with SamLocusIterator, but I'll file a separate issue in hellbender-protected to remind us to switch over to LocusWalker once it is implemented.

**Comment by droazen** [comment]
Closing, since there are no plans to implement `LocusWalker`
