### ISSUE TITLE
SparkGenomeReadCounts - NumberFormatException

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3357]
CNV workflows are unable to handle GRCh38 alternate and decoy contig names. This acts as an unintended safeguard against users including these contigs in a CNV analysis, which _they should not do for somatic analyses_. 

However, in principle, this inability to process data for a contig, albeit an alternate contig, is a bug that should be fixed. This may be relevant to someone's research as I explain to the forum user who brought this bug to our attention. My reply is shown below.

---
Hey @ameynert,

Use three ticks on an independent line to surround your code block. I see from:
```
/exports/igmm/eddie/bioinfsvice/ameynert/software/gatk-4.beta.2/gatk-launch SparkGenomeReadCounts \
    -I ../../bcbio/final/WW00247b/WW00247b-ready.bam \
    -o WW00247b.prop_cov \
    --reference /exports/igmm/eddie/bioinfsvice/ameynert/bcbio/data/genomes/Hsapiens/hg38/seq/hg38.fa 
```
that you are using GRCh38. So I think the `A*01` from the error message refers to any of the eleven HLA-A contigs:
```
WMCF9-CB5:~ shlee$ cat ~/Documents/ref/hg38/Homo_sapiens_assembly38.dict | grep 'A\*01'
@SQ	SN:HLA-A*01:01:01:01	LN:3503	M5:01cd0df602495b044b2c214d69a60aa2	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
@SQ	SN:HLA-A*01:01:01:02N	LN:3291	M5:743d9f66c77fc21b964a681e0c6de2ad	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
@SQ	SN:HLA-A*01:01:38L	LN:3374	M5:dd27b7fe617e92bb77eea00fede6fd15	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
@SQ	SN:HLA-A*01:02	LN:3374	M5:3ba47a11a8a5b47ccb855308e26a2f4a	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
@SQ	SN:HLA-A*01:03	LN:3503	M5:554d43de8f2a97cae068169fe3d8462e	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
@SQ	SN:HLA-A*01:04N	LN:3136	M5:072ea3e53c79f3d00e1f1a7b492b0a8f	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
@SQ	SN:HLA-A*01:09	LN:3105	M5:68176666a98582ea361a9181d69679af	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
@SQ	SN:HLA-A*01:11N	LN:3374	M5:b9ad3338cc73e2a99888a36e04c29f75	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
@SQ	SN:HLA-A*01:14	LN:3095	M5:0385be87eb49df4c59d7487495e3b1b4	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
@SQ	SN:HLA-A*01:16N	LN:2985	M5:10150ad21301a29f92e1521530fdd3f5	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
@SQ	SN:HLA-A*01:20	LN:3105	M5:05dc0384da2f751afe549a9bfdbc3037	AS:38	UR:/seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta	SP:Homo sapiens
```

If the contig name is the issue, then this is a bug of sorts that, depending on your project, may or may not be an issue.

If you expect all of your samples (PoN normals and tumor samples) to have coverage for specific alternate contigs and need to include such contigs in your analysis, then we can request a fix for this parsing error. I think this case would be unusual.

If alternate contigs are not needed for your research, or you expect sporadic coverage for the contigs across samples, then you can move ahead by limiting your analysis to the [primary assembly](https://gatkforums.broadinstitute.org/gatk/discussion/7857/reference-genome-components). For a typical somatic CNV analysis, because of the way the PoN is pruned, when working with GRCh38 alignments, you want to be sure to limit your counting to the primary assembly. You want to use the `-L` argument with an intervals file that only lists the primary assembly and excludes alternate and decoy contigs. This is really important. Any apparent arm/contig level event with variable coverage across your samples will cause CreatePanelOfNormals to raise a _red flag_ for the sample. The tool considers the sample suspect, in that it interprets the arm/contig level event as somatic and in that it expects some amount of coverage for each contig for each normal sample. Suspect samples get tossed from the PoN. Because the workflow uses proportional counts, this means that for your tumor sample you must count over the same genomic intervals as the PoN normal samples.

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/40740#Comment_40740

**Comment by samuelklee** [comment]
SparkGenomeReadCounts has some code to get rid of some of the non-autosomal chromosomes:

    private static final Set<String> NONAUTOSOMALCONTIGS = new HashSet<>(Arrays.asList("X", "Y", "MT", "M", "x", "y",
            "m", "chrX", "chrY", "chrMT", "chrM", "chrm"));

    protected static final String DROP_NON_AUTOSOMES_SHORT_NAME = "keepxy";
    protected static final String DROP_NON_AUTOSOMES_LONG_NAME = "keepXYMT";

    @Argument(doc = "Keep X, Y, GL*, NC_*, and MT regions.  If this option is not specified, these regions will be dropped, regardless of intervals specified.  Use -L (or -XL) and enable this option for exact specification of intervals.  This option may be removed in the future.",
            fullName = DROP_NON_AUTOSOMES_LONG_NAME,
            shortName = DROP_NON_AUTOSOMES_SHORT_NAME,
            optional = true
    )
    protected boolean keepNonAutosomes = false;

This is a bit hacky.  (Also note that the choice of the short name for the parameter is not great...we should fix that.)  @asmirnov239 the final version of your new tool should be able to handle this.

**Comment by vruano** [comment]
Looking at the stack trace, the error takes place in a low-level BAM input reading component in a dependency library.... It seems that is trying to read as a number portions of the contig name for a read record in the input... which makes very little sense.... 

My guess is that either it is a bug entirely contained in that library (is the name seqdoop?), say it does not tolerate those contig names, or that the user managed to input a bam file that isn't formatted correctly on those records.

**Comment by vruano** [comment]
@samuelklee, that is very hackish indeed, and very reference version/species dependent.

Tools should not discard hard-wired contig names or intervals like that but rather the user must provide the appropriate -L or -XL list.

A half-way possibility here is to provide a default set of excluded chromosomes depending on what reference is being used which must be verified on run-time as supposed to make the assumption is the one/ones the developer cared about at the time of writing the code. Lack of reference version/species mismatch, lack of explicity -L or -XL lists and lack of non-autosome exclusing flag in the argument list  should result in a warning message or perhaps even an error.

**Comment by vruano** [comment]
In contrast, I think excluded chromosomes should be announced in INFO messages (perhaps WARN messages).

**Comment by lbergelson** [comment]
Ah, yes, the garbage contig names strike again! It looks like hadoop-bam hasn't been patched to know about the horrors of hg38 contig names.  #3360

**Comment by samuelklee** [comment]
SparkGenomeReadCounts is now deprecated.
