### ISSUE TITLE
IntelliJ/gradle not respecting user's PATH when building hellbender

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#337]
Following our recommended IntelliJ setup instructions in our README leads to an IntelliJ project that does not respect the user's PATH environment variable when, eg., building via gradle. We instead end up with a default PATH that includes only a few directories such as `/usr/bin/`. 

We need to find a way to get IntelliJ to respect the user's PATH when building, and update our README accordingly.

**Comment by lbergelson** [comment]
This is definitely platform specific.  Seems like it changes between various OSX versions too.

**Comment by lbergelson** [comment]
@droazen I think this one is irrelevant now that we are recommending using the gradle wrapper
