### ISSUE TITLE
Make Mutect2 multi-sample wdl work in Firecloud

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#3387]
Instead of a single tsv with columns for the bam, bam index, and sample name, we need to input separate lists for the bams and bam indices and then zip the lists in the wdl.  This willr equire changing a lot of things that use this as a subworkflow.  Note that due to recent changes in the wdl the sample names no longer need to be input.

**Comment by davidbenjamin** [comment]
Idea: perhaps we could obviate the bam index file input by creating a wdl task that creates a list of indices from a list of bams by looking for neighboring bai files.

**Comment by vdauwera** [comment]
If I understand your idea correctly, I don't think that's going to work well in the FireCloud context. 

There are plans to get Cromwell to handle secondary files like bam index automatically next quarter, so I would recommend not putting a lot of effort into working around current limitations.

**Comment by vdauwera** [comment]
By the way, why do you need to make the multisample WDL work in FC? There we can just apply the single-pair WDL to a set of pairs. Unless I misunderstand what the multi sample WDL does.

**Comment by davidbenjamin** [comment]
> There are plans to get Cromwell to handle secondary files like bam index automatically next quarter, so I would recommend not putting a lot of effort into working around current limitations.

Nice.

> By the way, why do you need to make the multisample WDL work in FC?

We weren't going to, but the pon creation wdl calls the multi sample wdl and we want *that* to run in FC (I think).

**Comment by vdauwera** [comment]
Ah yes we do need to have a PON creation WDL in FireCloud.

**Comment by davidbenjamin** [comment]
Closed by #4048.
