### ISSUE TITLE
GKL v0.5.2 is known to hang / fail to load on CentOS - should upgrade to 0.5.3

### ISSUE THREAD

**Issue by danxmoran** [broadinstitute/gatk#3389]
We got a bug report (broadinstitute/picard#886) in Picard about the Intel inflater / deflater causing CLPs to hang on CentOS. I wasn't able to replicate the hang on our on-prem CentOS server, but I did see the GKL consistently failing to load there. The problem was a known bug in GKL v0.5.2, fixed in v0.5.3: Intel-HLS/GKL#33. Bumping the version got the library to load for me on CentOS.

**Comment by droazen** [comment]
Thanks @danxmoran -- we've opened a PR to move to the newer GKL.

**Comment by droazen** [comment]
Resolved by https://github.com/broadinstitute/gatk/pull/3392
