### ISSUE TITLE
add new contributor byoo to AUTHORS file

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3391]
@byoo You recently made your first contribution to gatk (thank you!) and so we'd like to add you to our authors file.  I don't know how to refer to you though.  
We typically list people as   `Full Name <email>` but I don't know either of those for you.

Would you like to be added, and if so, how should we refer to you.

**Comment by byoo** [comment]
Louis, thank you very much for the acknowledgement!
You may list me as Byunggil Yoo <byunggil.yoo@gmail.com>
