### ISSUE TITLE
Document that GGA mode is not supported 

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#3426]
Following https://gatkforums.broadinstitute.org/gatk/discussion/10049/genotype-given-alleles-mode-not-work-in-gatk4-beta

Since GGA mode (`--genotyping_mode GENOTYPE_GIVEN_ALLELES `) is definitely not supported at the present time, we should either put a note in the corresponding argument's doc string, make it `@Hidden`, or possibly both.

**Comment by chandrans** [comment]
I don't think this is still an issue? https://github.com/broadinstitute/gatk/pull/4038

**Comment by davidbenjamin** [comment]
@chandrans is correct.
