### ISSUE TITLE
GATK4 Spark with cromwell Spark backend

### ISSUE THREAD

**Issue by blueskypie** [broadinstitute/gatk#3428]
Hi, 
I have a question on how to use GATK4 Spark with cromwell Spark backend. I posted [here](https://gatkforums.broadinstitute.org/wdl/discussion/10124/gatk4-spark-with-wdl#latest) on the Broad WDL forum. Could someone help?

Appreciated!

**Comment by vdauwera** [comment]
We'll get you an answer in the forum, please don't cross-post to github as that just generates noise that slows us down.

**Comment by blueskypie** [comment]
sorry and thanks!
