### ISSUE TITLE
SvCigarUtils should be merged into CigarUtils.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#3446]
IMO there is no need to have two helper classes... it seems that SvCigarUtils methods could be useful for anyone.

**Comment by SHuang-Broad** [comment]
Those utilities are relatively more specific for the SV group (in particular for discovery step given aligned locally-assembled contigs or other types of long reads), IMO we should wait until there's need from other groups/domains.

**Comment by vruano** [comment]
I'm afraid that they might just get duplicated eventually... people won't into SvBlah for exiting helping methods unless you work in SV and even so, it would not occur to me to look for SvBlah... is just happen to pop up while I was solving a conflict in a rebase of a branch of mine.

**Comment by vruano** [comment]
If I'm looking to do something with cigar I look into Cigar* or CigarUtil* classes; I think that is what the average GATK developer would tend to do.

**Comment by magicDGS** [comment]
I agree with @vruano, because the `SvCigarUtils` contains generic methods to work with cigars and not specifically with SVs; for developers using GATK as a library, these methods may be useful for other cases and it is more difficult to find them with the SV prefix...

**Comment by SHuang-Broad** [comment]
There are assumptions in the code that is restrictive (e.g. most of them would fail in face of `N` or `P` right now). So if anyone decides to move (or use) `SvCigarUtils`, be careful.

**Comment by SHuang-Broad** [comment]
I'm reviving this discussion, since we have seen more data now compared to only CHM and NA12878.

What do you guys think? Should we still do it?
