### ISSUE TITLE
Patch O(n^2) algorithm in VCFHeader.addMetadataLineLookupEntry()

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3448]
`VCFHeader.addMetadataLineLookupEntry()` is showing up in profiles of, eg., the 20k gnomAD run as around ~15% of total runtime of 16-hour jobs. This is due to a O(n^2) algorithm that @cmnbroad identified. We should prioritize a fix for this in htsjdk.

**Comment by droazen** [comment]
@cmnbroad Could you please make this your highest priority when you get back? Thanks!

**Comment by cmnbroad** [comment]
Tests passed, PR is reviewed and merged into htsjdk.

**Comment by cmnbroad** [comment]
Closing via https://github.com/samtools/htsjdk/pull/968/ and https://github.com/broadinstitute/gatk/pull/3504.
