### ISSUE TITLE
Set locale to US in Main is not applied to downstream projects Main classes

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#3483]
Because in `Main`the call to `Utils.forceJVMLocaleToUSEnglish()` is done in an static block, this is not applied to downstream projects. I wonder if this call can be moved to `Main.mainEntry`, to assess extending classes apply the same locale.

**Comment by lbergelson** [comment]
@magicDGS Doesn't the static block run when a subclass of Main is loaded as well?

**Comment by magicDGS** [comment]
I haven't test it by myself (all my computers have the default locale to US-En), but regarding  https://github.com/broadinstitute/gatk/pull/3447#discussion_r134548399, it looks like it won't work.

**Comment by cmnbroad** [comment]
@magicDGS I'm still missing why this wouldn't work for downstream projects (as long as they load Main or some Main-derived class). I think the owner config issue is different; for locale, we need to always force US. Can you verify this, or maybe provide more details about what case doesn't work ?

**Comment by magicDGS** [comment]
I'm always confused with static-block initializers, and I just wondered in the config PR if the static block in `Main` it is correctly setting everything in sub-classes. I understood that this won't work in Main-derived classes; if that's not the case, feel free to close this PR...

**Comment by magicDGS** [comment]
Closing as I think that this is wrong.
