### ISSUE TITLE
Prototype a PythonScriptExecutor, and assess maintainability of an example tool that calls into a Python machine-learning library

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3501]
Implement a `PythonScriptExecutor` that is similar to the existing `RScriptExecutor` (invokes Python with a given set of arguments). Then ask the CNV team to prototype an example tool or two that use `PythonScriptExecutor` to call into a Python machine-learning library, and do an assessment of maintainability, etc.

`PythonScriptExecutor` will come with an attached set of conditions for its use, intended to address the most serious issues raised by the engine and support teams with having Python code in the GATK. We should document these conditions in the docs for `PythonScriptExecutor` when it's implemented:

1. All tools that use `PythonScriptExecutor` must have a Java-based front-end, with standard GATK (barclay-based) arguments. We put a lot of development effort into our arg parser and into striving for user-interface consistency across tools, and cannot afford to duplicate this effort in Python. Geraldine (CC'd) and the rest of the support team can back me up on this one!

2. An honest effort should be made to minimize the amount of code written in Python -- as much of each tool's work as possible should be done in Java. In particular, reading/writing final inputs and outputs should happen in Java. This is important for a number of reasons, including the engine team's goal of ensuring universal GCS support, consistent Google authentication handling, etc. Again, we really don't want to have to duplicate that work in Python, or for the tools that call into Python to be inconsistent with the rest of the toolkit.

3. All dependencies (Python and native) of Python libraries used will be clearly documented, and included in the default GATK docker image. I don't think I need to explain why this one is important :)   

4. Before we go any further down this path, we prototype one or two tools using `PythonScriptExecutor`, and do a fair assessment of maintainability and other concerns of the engine/support teams, such as whether it will even be possible to package all dependencies without conflicts.

5. Engine team will continue to search for Java-based solutions while this evaluation is ongoing, but this proposal at least unblocks the CNV team for now.

**Comment by droazen** [comment]
@cmnbroad has volunteered to implement `PythonScriptExecutor` (should be quick), plus an example tool. Then he'll turn things over to @samuelklee and the CNV team to implement a prototype ML tool, after which we'll do the evaluation outlined above and decide whether this is the right path to go down.

**Comment by mbabadi** [comment]
@droazen ideally, the executor must be able to fire up one (or more) python kernels and keep it (them) alive as long as the user decides to keep it (or the GATK session terminates). Here's an example why this is desirable: the compilation of a complicated theano computational graph can take a significant portion of the total computation time. The compiled graph is a function of data dimensions, which in my use case, varies from loci to loci. My current solution to this is to pre-compile and cache a number of theano computational graphs with different sizes, pad the data to fit it to the closest matching computational graph, and re-use the same compiled graph(s) as required. To this end, one needs to keep the python kernel w/ the compiled graphs alive.

**Comment by mbabadi** [comment]
@cmnbroad @droazen if we ended up doing it the "ambitious" way, these projects might be useful:
http://jyni.org/
https://github.com/bcdev/jpy

**Comment by cmnbroad** [comment]
@samuelklee @mbabadi @lucidtronix This is merged in and should get you started. Please give it a try and let me know if we need to do anything more in terms of staging of scripts, or other functionality.

**Comment by samuelklee** [comment]
Awesome, thanks!  We'll give it a try and let you guys know.

**Comment by cmnbroad** [comment]
Reopening since only step 1 is done.

**Comment by samuelklee** [comment]
I think we can close this. :100:
