### ISSUE TITLE
modify build.gradle to give a reasonable error if R isn't found

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#351]
Basically the same issue as #336.  It stems from the same misunderstanding of how gradle exec works.

**Comment by akiezun** [comment]
@lbergelson can you clarify the expected behavior? Why should it not fail - the build (tests) cannot complete without RScript

**Comment by lbergelson** [comment]
It crashes with an exception instead of doing a partial build with failing
tests.

**Comment by akiezun** [comment]
is this a bug? sounds like a feature

**Comment by lbergelson** [comment]
It needs to be addressed to at least give a proper error message.  Right now it will confuse people.

**Comment by akiezun** [comment]
not a bug then

**Comment by akiezun** [comment]
@lbergelson please rename the issue to reflect what needs to be done

**Comment by akiezun** [comment]
alpha candidate?

**Comment by droazen** [comment]
@lbergelson Can we close this?

**Comment by droazen** [comment]
This is done -- closing
