### ISSUE TITLE
HaplotypeCaller misses indel at end of amplicon reads

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#3528]
### Affected tool(s)
HaplotypeCaller

### Affected version(s)
latest GATK4 

### Description 
HaplotypeCaller misses calls at the ends of reads that UnifedGenotyper picks up in amplicon data. For example, UnifiedGenotyper calls the indel at the ends of the reads, but HaplotypeCaller does not.
<img width="1440" alt="screen shot 2017-08-28 at 4 11 27 pm" src="https://user-images.githubusercontent.com/6998669/29791713-ea62d6f6-8c0b-11e7-9ff4-efa428d5981f.png">
The top is the original BAM file and the bottom is the bamout file. 

#### Steps to reproduce
The files are here: `/humgen/gsa-scr1/schandra/ulitskyi_MissedCall`

Command for UnifiedGenotyper:
`java -jar /humgen/gsa-hpprojects/GATK/bin/current/GenomeAnalysisTK.jar -T UnifiedGenotyper -R hg19.unmasked.fa -I snippet4.bam -o Sheila.UnifiedGenotyper.vcf -glm BOTH`

Command for HaplotypeCaller:
`/humgen/gsa-scr1/public/gatk-4.beta.3-SNAPSHOT/gatk-launch HaplotypeCaller -R hg19.unmasked.fa -I snippet4.bam -O Sheila.HaplotypeCaller.vcf -dontTrimActiveRegions --disableOptimizations`

#### Expected behavior
The indel should be called.

#### Actual behavior
Indel is not called, but is called by UnifiedGenotyper.

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/41504#Comment_41504

**Comment by cmnbroad** [comment]
Assigning to @lbergelson for further triage.

**Comment by chandrans** [comment]
@lbergelson Hey Louis. The user just asked about this. Is this something you guys are willing to look into? I guess it would be nice to let the user know if this is something that will be fixed in the general release or the next beta release or never.

**Comment by lbergelson** [comment]
@chandrans Does gatk3 haplotype caller call this?

**Comment by chandrans** [comment]
I am pretty sure GATK3 HC did not call this. But, I am checking now. I put this in GATK4 because I know it will not be fixed in GATK3. I can let the user know this is not high priority for now? We will get to bugs after the main release?

**Comment by lbergelson** [comment]
Yeah, we'd obviously like to fix any bugs, and having the test case will be really useful.  We might be able to get to it before the release, but it won't be for a little bit.

**Comment by chandrans** [comment]
Thanks Louis. Will let user know.

**Comment by chandrans** [comment]
The user is really eager for this fix to go in, so I told him it will be in the next release (4.1). I hope this is alright.

**Comment by ldgauthier** [comment]
There are only 19 reads out of 116 with the 1bp insertion here, which is not representative of a good diploid call.  But the real problem is that the indel is _very_ close to the end of the reads and there's not enough data to be sure that the rest of the read supports the reference.  There's a slim possibility it might get called if you add a smaller kmer size (`--kmer-size 5`), but otherwise there's nothing to be done.
