### ISSUE TITLE
Output vcf index not generated in HaplotypeCaller

### ISSUE THREAD

**Issue by skwalker** [broadinstitute/gatk#3534]
GATK4 Hapltotype Caller does not generate a vcf.idx, even though the default for createOutputVariantIndex is true. Explicitly setting it to true still does not generate a VCF index.

**Comment by cmnbroad** [comment]
We need to fix this at the same time as part of https://github.com/broadinstitute/gatk/issues/2102.

**Comment by chandrans** [comment]
But the good news is IndexFeatureFile works now ? We have not had any users report this, but I just tried it, and got no errors :)

**Comment by cmnbroad** [comment]
@chandrans Yes, IndexFeatureFile should work now.
