### ISSUE TITLE
Would be better that IntervalsSkipList.getOverlapping would accept a Locatable rather than a SimpleInterval.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#3541]
I can see the reassurance of knowing that the input Locatable is constant and with a non-null contig... yet as a result we are often creating redundant simpleIntervals instances when our objects of interest are some other type of Locatable.

**Comment by lbergelson** [comment]
I think we discovered at some point that IntervalSkipList has worse performance than htsjdk `OverlapDetector`.  We should probably be deprecating and removing it.
