### ISSUE TITLE
AllelicCountCollector infers the wrong alternate allele from the pileups

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#3548]
If you run this on position 20:10022820 in `src/test/resources/large/mutect/dream_synthetic_bams/tumor.bam` you will get the wrong alt (you get C, but should be T).  

Proposed solution:  Use findLast() (or reverse b1 and b2 in the compare statement to get this to sort in descending order).

```
    private static Nucleotide inferAltFromPileupBaseCounts(final Nucleotide.Counter baseCounts,
                                                           final Nucleotide refNucleotide) {
        return BASES.stream()
                .filter(b -> b != refNucleotide)
                .sorted((b1, b2) -> Long.compare(baseCounts.get(b1), baseCounts.get(b2)))
                .findFirst().get();
    }
```

**Comment by samuelklee** [comment]
Whoops, I think this one is on me.  Thanks for catching it.  Will issue a bugfix shortly.
