### ISSUE TITLE
FeatureInput cannot be used to define the intervals

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#3549]
For example, I have a tool that takes in a VCF as a FeatureInput.  I would like to run on the intervals defined by the VCF.  Currently, I would have to use -L and specify the VCF (effectively specifying it twice), which is ugly.

@lbergelson

**Comment by lbergelson** [comment]
We might be able to do something clever here with an IntervalArgumentCollection that contains a FeatureInput.  It would require some changes to gatktool I think, but this is a pretty reasonable request so maybe it's worth it.

**Comment by davidbenjamin** [comment]
Not sufficiently worth it for anyone to care in the last 2+ years.
