### ISSUE TITLE
GermlineCNVCaller and tests only work when run from gradle.

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#3552]
The code is dependent on the nd4j dtype system property being set to "double" by gradle. Otherwise the tests (and the tool itself) fail when run from intellij or from the command line. The nd4j unit tests have the same issue.

Its easy enough to set the dtype programmatically, though I'm not sure where the best place to do that is.

**Comment by cmnbroad** [comment]
@mbabadi Can you take a look - I know the tool is beta but as it stands its a bit painful to figure out whats happening when the tests fail.

**Comment by lbergelson** [comment]
seems like a good candidate to be moved into the config files...

**Comment by mbabadi** [comment]
deprecated by the new gCNV implementation. Closing.
