### ISSUE TITLE
Why is pair_hmm_implementation hidden?

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3553]
I noticed that the PairHMM implementation argument is hidden in `LikelihoodEngineArgumentCollection` for some reason.  Shouldn't it be exposed as an advanced argument people can choose what pair hmm they want?

It's also present in the `UnifiedArgumentCollection`, but it's never used from there.

```
    /**
     * The PairHMM implementation to use for genotype likelihood calculations. The various implementations balance a tradeoff of accuracy and runtime.
     */
    @Hidden
    @Argument(fullName = "pair_hmm_implementation", shortName = "pairHMM", doc = "The PairHMM implementation to use for genotype likelihood calculations", optional = true)
    public PairHMM.Implementation pairHMM = PairHMM.Implementation.FASTEST_AVAILABLE;
```

It seems like we should remove it from the `UnifiedArgumentCollection` and make it either a normal argument or an advanced argument in the `LikelihoodEngineArgumentCollection`.

**Comment by davidbenjamin** [comment]
It's hidden because the only implementations are the regular pair HMM and the random likelihoods one.  We don't actually use the latter of use (maybe we did in GATK 3?) and #6354 gets rid of it entirely.
