### ISSUE TITLE
Picard interval list files with .list extension can't be used with -L

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#3555]
This Barclay [feature](https://github.com/broadinstitute/barclay/issues/25) automatically expands the contents of a file ending in ".list" whenever the target argument is a collection. This precludes the use of Picard interval list files ending in ".list" with -L in GATK, since they contain a sam header. The raw sam header lines wind up getting added as interval strings, which then fails parsing: A USER ERROR has occurred: Badly formed genome unclippedLoc: Failed to parse Genome Location string: @HD	VN:1.5: Problem parsing start/end value in interval string. Value was: 1.5

A short term GATK workaround is to use a file ending in one of the other known Picard interval list extensions (.interval_list, .intervals, or .picard) instead, but we should find a better fix for this since .list seems to be commonly used.

Tools such as GetHetCoverage, which take an interval list in an argument typed as a File (--snpIntervals), are able to consume the interval file because the target argument is not a collection, so the auto-expansion is not triggered.

I expect this issue could cause more problems in Picard as well once Barclay is the default parser there.

**Comment by cmnbroad** [comment]
@sooheelee This is what I mentioned in slack.

**Comment by magicDGS** [comment]
I've already suggested in https://github.com/broadinstitute/barclay/pull/28#discussion_r98629000), when the feature was implemented, that this can be an issue in downstream projects. Maybe it is still not late to change the extension to ".arg_list" to be sure that it is what the user requested.

**Comment by cmnbroad** [comment]
After some discussion, we're planning to change the built-in extension used by Barclay for automatic expansion from ".list" to  ".args".

**Comment by sooheelee** [comment]
Thanks for letting me know Chris. I'm on vacay and just viewing the email thread that starts with mention of my name and not the whole github thread. If I can help out with something specific, do let me know.

**Comment by magicDGS** [comment]
I added a PR to Barclay (https://github.com/broadinstitute/barclay/pull/95) to both change the extension and to switch off the behaviour if need it. That may solve other errors in the future too, if other downstream project want to use the extension for other purposes.

**Comment by cmnbroad** [comment]
This is fixed by the Barclay upgrade in https://github.com/broadinstitute/gatk/pull/3804, but we really should add an explicit integration test that uses a Picard interval list with a .list extension that includes a header (i.e., src/test/resources/small_unmerged_picard_intervals.list, but this is only used in a unit test).

**Comment by droazen** [comment]
We fixed this.
