### ISSUE TITLE
CNV OncotateSegments does not expose bootDiskInGb runtime parameter

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#3566]
This is often needed since the docker image is big.

Expose this parameter with a 20GB value

**Comment by samuelklee** [comment]
@LeeTL1220 We'll need to add Oncotator back to the ModelSegments at some point, correct?

**Comment by LeeTL1220** [comment]
@samuelklee Yes, ASAP, we cannot support our internal TAG use cases without it.

**Comment by samuelklee** [comment]
OK.  The only issue I see is converting from ModelSegments output back to the old column headers.  I'd rather not have Java code for this if we can take care of it on the Oncotator side.  Or perhaps even just a bash one-liner in the WDL.

**Comment by LeeTL1220** [comment]
@samuelklee Fine by me
