### ISSUE TITLE
Polish M2 wdl using new cromwell

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#3568]
There are a few changes possible since Cromwell 27.  For example, there must be a way to get rid of the `ProcessOptionalArguments` task.  Also, explicit input of the tumor and normal sample names is no longer necessary.

**Comment by LeeTL1220** [comment]
@jsotobroad @meganshand Note this....

**Comment by davidbenjamin** [comment]
Closed by #3584.
