### ISSUE TITLE
No space left on device M2 WDL Travis failure.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#3572]
Seems to be intermittent: https://travis-ci.org/broadinstitute/gatk/jobs/274887535

**Comment by cmnbroad** [comment]
@samuelklee Your branch is pretty far behind master, and is using the new travis image introduced last week, which has less space than the previous one (see https://github.com/broadinstitute/gatk/issues/3559). You need rebase onto current master to pick up https://github.com/broadinstitute/gatk/pull/3557.

**Comment by samuelklee** [comment]
Was wondering if that might have something to do with it.  Thanks!
