### ISSUE TITLE
Create Jenkins job to run ReadsPipelineSpark on exome data

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#3573]
Set up a recurring (nightly) job that runs ReadsPipelineSpark using the settings in https://github.com/broadinstitute/gatk/blob/tw_spark_end_to_end/scripts/spark_eval/exome_reads-pipeline_gcs.sh

This takes about 30 mins on a 10 node cluster.

**Comment by tomwhite** [comment]
@davidbernick I was going to tackle this by cloning https://gatk-jenkins.broadinstitute.org/job/gatk-perf-test-spark-readpipeline and adjusting some of the parameters. Are there any issues or gotchas I should know about? /cc @lbergelson

**Comment by davidbernick** [comment]
That's fine -- just make sure it launches with : 
Build after other projects are built - to gatk-perf test. That's the one that sets up the environment and builds latests dockers. So that needs to happen first then all the other tests downstream after. A clone should capture that but just double check.

**Comment by tomwhite** [comment]
@davidbernick thanks!

I noticed that the existing jobs are now failing with a GCS error (see https://gatk-jenkins.broadinstitute.org/job/gatk-perf-test-spark-markeddupe/436/console):

```
Error code 404 trying to get security access token from Compute Engine metadata for the default service account. This may be because the virtual machine instance does not have permission scopes specified.
```

There has been a change to the GCS library (https://github.com/broadinstitute/gatk/commit/b47838c9a5fa172ed6669ed4872b04d91c962a85), but when I ran a GCS pipeline manually on my machine it worked fine, even with this change.

Any thoughts?

**Comment by davidbernick** [comment]
This is related to a known issue with GCS. #3591 When that's fixed, the spark tests will work again.

**Comment by tomwhite** [comment]
Thanks @davidbernick. When the tests are working again I'll create a new job for this issue.

**Comment by tomwhite** [comment]
See https://gatk-jenkins.broadinstitute.org/job/gatk-perf-test-spark-readpipeline-exome/
