### ISSUE TITLE
make our travis test results stored in gcs expire after some amount of time

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3578]
They currently pile up forever and are fairly large.  It seems like we can set them to disappear automatically after some number of days if we use lifecycle rules on the bucket https://cloud.google.com/storage/docs/lifecycle.

**Comment by jamesemery** [comment]
It looks like it shouldn't be to difficult but it would necessitate either moving the bucket they are located in or asking people to clear out the hellbender bucket of other things because it appears the lifecycle features can only be applied on a per-bucket basis.

**Comment by lbergelson** [comment]
definitely easiest to move the logs I think, the hellbender bucket unfortunately has become hardcoded into a bunch of tests and might be a pain to move

**Comment by jamesemery** [comment]
Resolved by this commit: https://github.com/broadinstitute/gatk/commit/c063348274cce3da724a06d789cd1b8edcd9f893
See gs://hellbender-test-logs/ for the new source of test logs.

**Comment by lbergelson** [comment]
@jamesemery 👍
