### ISSUE TITLE
Rename onTraversalDone() to onTraversalSuccess() and clarify the docs

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#358]
Currently, the engine-level shutdown routine `onShutdown()` is always invoked, even when an exception occurs during traversal, but the tool-level shutdown routine `onTraversalDone()` is not wrapped within a `finally` block and so not invoked when an exception occurs. Do we want it to always be invoked? Some tools might be designed on the assumption that `onTraversalDone()` will only be reached if the traversal completed start to finish without error (and so it's appropriate to generate certain final output, etc.), while other tools might prefer it to always be invoked so that resources can be closed. Thoughts?

**Comment by akiezun** [comment]
agreed. onTraversalDone should be renamed to onTraversalSuccess and doc clarified to reflect the semantics.

**Comment by droazen** [comment]
Depends on https://github.com/broadinstitute/hellbender/issues/121

**Comment by akiezun** [comment]
alpha candidate?
