### ISSUE TITLE
Seems that the scripts/sv/manage_sv_cluster.sh might is broken:

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#3593]
Go the following:

```
Current git hash does not match GATK git hash. Run anyway?yes
error: malformed object name 1
usage: git branch [<options>] [-r | -a] [--merged | --no-merged]
   or: git branch [<options>] [-l] [-f] <branch-name> [<start-point>]
   or: git branch [<options>] [-r] (-d | -D) <branch-name>...
   or: git branch [<options>] (-m | -M) [<old-branch>] <new-branch>
   or: git branch [<options>] [-r | -a] [--points-at]
...
```
Not sure the first error message about the "hashes" means perhaps that is the cause though.

Assigned to @TedBrookings because I think this is you beast.

**Comment by TedBrookings** [comment]
The git hash refers to the commit of GATK you have checked out in your branch as opposed to the commit of GATK that has been built in Java (and will be run on the cluster). I will clarify the error message: it means that you need to rebuild GATK to match your changes to the repository.

The malformed object name is a different story, and seems like a bug. I will try to figure that out.
