### ISSUE TITLE
Allele-to-Allele determination of variant type

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#3603]
The variant context functions such as `isSNP()` are not very useful in the context of a genotype or determination of one allele to another.

Therefore, we should add a function that can determine the variant type (using the same constants as used in VariantContext) from Allele-to-allele transformations.

**Comment by lbergelson** [comment]
@LeeTL1220 Is this not necessary anymore or did you add a function somewhere?

**Comment by LeeTL1220** [comment]
I built it and forgot to close the issue

On Nov 8, 2017 11:41, "Louis Bergelson" <notifications@github.com> wrote:

@LeeTL1220 <https://github.com/leetl1220> Is this not necessary anymore or
did you add a function somewhere?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/broadinstitute/gatk/issues/3603#issuecomment-342876663>,
or mute the thread
