### ISSUE TITLE
Implement tests for new GenomicsDB support for non-diploid genotypes and phasing information

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3609]
https://github.com/broadinstitute/gatk/pull/3575 added GenomicsDB support for non-diploid genotypes and also for preserving phasing information in genotypes. We still need to craft tests to prove that this functionality works as intended, however.

**Comment by droazen** [comment]
For @jamesemery

**Comment by jamesemery** [comment]
In implementing these tests, I have run into https://github.com/samtools/htsjdk/issues/1044, which is waiting on to unblock https://github.com/samtools/htsjdk/pull/1048.

**Comment by jamesemery** [comment]
Closed by https://github.com/broadinstitute/gatk/pull/4000
