### ISSUE TITLE
Add the ability for downstream projects to customize which packages to search for Annotation classes

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#3610]
Currently when a `VariantAnnotatorEngine` object is instantiated it searches in the package `org.broadinstitute.hellbender.tools.walkers.annotator` and creates an object for every Annotation object it finds. This should be generalized using OWNER so that other projects are able to specify other packages to search in.

**Comment by droazen** [comment]
Co-assigning to @jonn-smith, since it's likely to be implemented using the new OWNER configuration facility.

**Comment by magicDGS** [comment]
Dup of https://github.com/broadinstitute/gatk/issues/2155?

**Comment by lbergelson** [comment]
@magicDGS Yes, thank you, closing this as a duplicate.
