### ISSUE TITLE
can we remove the SGA code?

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3612]
@SHuang-Broad We still have these SGA tests that always skip.  Has the need for that been replaced by Fermilite and BWA?  Can we delete that code / remove those tests?

**Comment by SHuang-Broad** [comment]
I am OK with removing it, since our pipeline seems to have been stabilized without it for almost 6 months now. What do you think @cwhelan @tedsharpe ?

**Comment by tedsharpe** [comment]
I'm fine with it.
If the skipped tests are the primary irritant let's just delete them.

**Comment by cwhelan** [comment]
Yes I think we can get rid of these.

**Comment by SHuang-Broad** [comment]
closed by #3613
