### ISSUE TITLE
Mutect2 should have a standard argument group

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#3618]
I noticed that in the `M2ArgumentCollection` there is a hardcoded list of annotations to include, namely `"Coverage", "DepthPerAlleleBySample", "TandemRepeat", "OxoGReadCounts", "ReadPosition", "BaseQuality", "MappingQuality", "FragmentLength", "StrandArtifact"` and no annotation groups specified. This means that currently if the user specifies any new annotations with the -A argument all of the above specified annotations will be blown away unless the user specifies each one individually. I propose that these annotations should be bundled into a group `StandardM2Annotations` on by default keeping with the pattern set by the Haplotype caller.

**Comment by jamesemery** [comment]
@davidbenjamin

**Comment by davidbenjamin** [comment]
@jamesemery @droazen this is a good idea.
