### ISSUE TITLE
Remove download of picard.jar from .travis.yml and update Mutect2 WDL

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#3625]
Once https://github.com/broadinstitute/gatk/pull/3620/ is in, we should be able to remove the download of picard.jar from .travis.yml, and change the M2 WDL to no longer depend having access to it. Workflow calls to picard tools can be replaced with calls to the same tools in GATK, although the argument syntax will have to change from picard style to Barclay style ("I=..." to "-I ...").

**Comment by droazen** [comment]
@davidbenjamin Would you be able to do this one, since it mainly affects the M2 WDL?

**Comment by davidbenjamin** [comment]
@droazen Yes, with pleasure.
