### ISSUE TITLE
Consolidate the Picard and GATK Program groups

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#3626]
Picard and GATK have separate program groups, some of which overlap, i.e., both have a SAM/BAM group, a VCF group, etc. Also, Picard has an "Alpha" program group. Once https://github.com/broadinstitute/gatk/pull/3620/ goes in, these all show up on the command line as different groups.

We need to decide how we want these organized in GATK (the Picard tools don't follow all of the same conventions as GATK, so it might be worthwhile to distinguish them somehow).

While we're at it, we should unify the use of Beta/Experimental/Alpha in tool summary text.

**Comment by droazen** [comment]
This is done.
