### ISSUE TITLE
Generate unified GATK/Picard doc and tab completion script

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#3627]
Once https://github.com/broadinstitute/gatk/pull/3620/ is in, we should add/update the gradle tasks for gatkDoc and gatkTabComplete to generate unified (GATK and Picard) doc and tab completion script.

**Comment by droazen** [comment]
@cmnbroad This one is done, right?

**Comment by cmnbroad** [comment]
Closed via #3683.
