### ISSUE TITLE
Migrate remaining Picard class duplicates to the corresponding Picard classes

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#3632]
- utils.artifacts.Transition can be removed and replaced with picard.analysis.artifacts.transition class (once the Picard one is made public)
- utils.read.SamComparison can be removed and replaced with picard.sam.util.SamComparison once https://github.com/broadinstitute/picard/pull/913 is merged

**Comment by magicDGS** [comment]
https://github.com/broadinstitute/gatk/pull/3620 is already merged, which makes `Transition` public. So only `SamComparison` is left...

**Comment by cmnbroad** [comment]
https://github.com/broadinstitute/picard/pull/913 is finally merged, so we can make this swap the next time we upgrade picard.
