### ISSUE TITLE
GATK Docker should include non-root user account

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3644]
To allow for those without root privileges, e.g. working off a hosted server, to use the container. This came up during the Helsinki workshop and also at <https://gatkforums.broadinstitute.org/gatk/discussion/comment/42547>.

**Comment by lbergelson** [comment]
@sooheelee I'm not sure I understand this issue.  Is someone running the gatk docker image and then having people use that as a shared server?  If they are, then it seems like it's their responsibility to control ssh access to the server, set up permissions, etc.  That's outside of the scope of what we can do.  If someone is running docker and starting up their own instance of the gatk container, then they have root access to that container by definition. 

Could you explain the exact use case you want to support?  I read the thread you pointed at but I also didn't really follow EADG's reasoning.

**Comment by sooheelee** [comment]
At the Helsinki workshop someone explained to me they couldn't use Dockers on their servers because folks don't typically have root access. I cannot say I understand the details, but I can get you in touch with someone who does if this is something you want to follow up on.

**Comment by sooheelee** [comment]
I am told Docker now allows nonroot usage.

**Comment by sooheelee** [comment]
Fyi, here's info on Singularity: http://singularity.lbl.gov/
Which [Nextflow](https://www.nextflow.io/) can use. Nextflow also uses Docker.

**Comment by PeteClapham** [comment]
Hi, 
for those looking to run containers within a multi-user HPC environment, running a container with default root privileges presents a potential data security risk.

Adding something like :

RUN useradd -ms /bin/bash gatk
WORKDIR /home/gatk
USER gatk

to the Docker file would greatly reduce the risk and bring the current containers in line with general best practice, e.g https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b

There should be no downsides to running in this manner. Singularity could help but the current configuration will be picked up and prevented from running by any site using a container security scanner, e.g. Aqua.
