### ISSUE TITLE
GATK Docker should provide versioning info with "cat Dockerfile"

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3645]
So users don't have to root around for program versions. Instead, they can have these listed. See `@Tiffany_at_Broad`'s comments at <https://gatkforums.broadinstitute.org/gatk/discussion/comment/42547> for details for how this works for the GOTC Docker.

**Comment by LeeTL1220** [comment]
@droazen @lbergelson I'm not really sure how to do this.  It's easy in SVN, but not in git.  We would need to insert the version info in the labels of the dockerfile when we cut a release -- the release version (e.g. 4.beta.4) not the git hash.  How is GotC doing it?

**Comment by LeeTL1220** [comment]
@sooheelee I am not sure that modifying the Dockerfile is the way to go.  Especially since our list is a lot shorter than GotC.  For most users, the GATK version is all that is important.  Everything else is derived from that.  We've removed our WDL usage of `samtools` and soon GATK will wrap `picard` and again the version of picard being wrapped will be 1:1 to the version of GATK.

**Comment by sooheelee** [comment]
At the least we should allow easy identification of the GATK, Picard and Java program versions listable from the image OR in the Docker repo for each release.

**Comment by droazen** [comment]
@sooheelee The GATK version and the docker image version are identical. The Picard version is printed when any GATK tool is run.

**Comment by sooheelee** [comment]
The annoyance is having to run a command on data, with proper syntax, to find out the Picard version. It should b something we can pull up via `docker inspect`, `gatk --version` or other simple command that does not involve some tool. I just assume this will not be addressed so I closed it.

**Comment by droazen** [comment]
Well, we'd be potentially open to the idea of including additional info in the `gatk --version` output. Feel free to open a separate ticket to discuss.
