### ISSUE TITLE
Indexing output files on the fly

### ISSUE THREAD

**Issue by nh13** [broadinstitute/gatk#365]
As a bioinformatician, I would like any hellbender tool to output an index along with the primary output file, for any output file format that can be indexed (ex. BAM/VCF/BCF/FASTA), so that I do not need to re-read the output file to create an index (looking at you GenotypeVCFs, tabix, and CombineVCFs).

**Comment by droazen** [comment]
Depends on https://github.com/broadinstitute/hellbender/issues/121

**Comment by akiezun** [comment]
needs a way to prevent data races. Otherwise, multiple concurrent tools write the same index file and bad things happen.

**Comment by nh13** [comment]
How about an indexingoutputstream?

**Comment by lbergelson** [comment]
Are data races actually an issue here?  If you have 2 tools creating the same **output** file, that's a problem on it's own.  I think the data race issue was a problem with tools that auto indexed their **input** files.

**Comment by nh13** [comment]
Basically Picard's ```CREATE_INDEX``` command line option should have an analogous option in hellbender.

**Comment by akiezun** [comment]
@lbergelson yes, i meant 2 concurrent tools making indices for the same **input** file. They will both try to write the same index file, with bad consequences.

**Comment by droazen** [comment]
This ticket only deals with on-the-fly indexing of output files. We already know from our experiences with the old GATK that on-the-fly indexing of input files is a bad idea, so I don't think anyone is advocating for that.

**Comment by akiezun** [comment]
renamed the ticker

**Comment by droazen** [comment]
Let's do this one for alpha-1

**Comment by cmnbroad** [comment]
Walkers:
-ReadWalkers These is already done through the GATKTool createSAMWriter for any BAM outputs that are coordinate sorted.
-VariantWalkers We need something in GATKTool similar to createSAMWriter for creating VCFs that honors the index arg.
-IntervalWalkers Not sure what these will need.
-PicardCommandLineTool These already use a common method for creating BAM writers that honors CREATE_INDEX. We need similar thing for VCFs.
-GATKSparkTools should these default to auto indexing as well ? 

Questions:
Right now we have a --createOutputBAMIndex arg for GATK tools - should this be moved down to ReadWalker ?
PicardCommandLineProgram currently has a --CREATE_INDEX arg, documented as being for BAMs.

Should we unify the name of the indexing argument across all of these, or possibly unify down to two, one for alignment output files and one for variant output files ? Some GATK tools (ie., HaplotypeCaller) create both BAM and VCF outs.

**Comment by cmnbroad** [comment]
This is done for non-Spark tools (Spark tools are covered by #1480). But per discussion with @droazen its on hold until we resolve the various different ways of getting a sequence dictionary. Code is in https://github.com/broadinstitute/gatk/commit/2fb990dfeb7f5be20d6d09e184327d3872094f26.

**Comment by akiezun** [comment]
When can this be merged? is there a PR? It's not in master

**Comment by cmnbroad** [comment]
Its dependent on https://github.com/broadinstitute/gatk/pull/1424 and https://github.com/broadinstitute/gatk/pull/1425 getting resolved. When those are merged in, I'll rebase and resolve the branch against those, then make a PR.

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/2046.
