### ISSUE TITLE
Conditional logic in CNV workflows should use explicit arguments

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#3657]
The conditional logic (wgs vs exome, T/N vs T-only) should not be based on the presence or absence of file inputs. This should instead be done using an explicit switch, eg a “mode” argument. Otherwise people are going to run into all sorts of trouble.

**Comment by samuelklee** [comment]
Just to make sure I understand the issue---will this cause technical problems in the Firecloud environment, or is it more of a style issue?

If the latter, one reason I prefer the use of optional file inputs to trigger tool-level "modes" when possible is that it propagates more naturally from the tool level.  For example, let's consider a tool that can operate in either tumor-only or matched-pair mode.  It is natural at the tool level to make the tumor a required input and the normal optional.  The other options are quite awkward: 1) make both inputs required and switch between using the normal or not with a flag (in which case it is very easy for the user to shoot themselves in the foot if they forget to set the flag right, and we'd have to pass a dummy normal every time we want to run tumor only if we don't actually have a pair), 2) leave the normal as optional but add a flag anyway, which would be redundant and require an additional validation (i.e., if the flag is set to matched mode but we don't have a normal, we should fail early), or 3) write separate tools for each mode with the corresponding required inputs.

If we accept that optional file input is the way to handle such a scenario at the tool level but not at the workflow level, then we will simply run into the same problems at the workflow level.

I'm sure there are more complex scenarios when triggering on file presence/absence doesn't uniquely specify a workflow, in which case flags are a must.  But for simple scenarios, I'm not sure why we shouldn't take advantage of the ability to specify optional file inputs in WDL (actually, I'm not sure how else we are supposed to use them?)

However, if this is a problem for Firecloud, then I'd like to understand why---and what possible solutions there might be.

**Comment by vdauwera** [comment]
It's not a technical problem but it's more than a question of style. It's a user experience problem. Happy to go into detail at some point (just not now). I hear you on the internal wiring rationale; but I think we should explore whether it's possible to fix that, potentially through changes to WDL itself. Clearly the language isn't allowing you to do what you need as an author and what I need as a user -- which I would characterize as "conditional optionality", ie things are made optional or not depending on a condition. Would be good to get redteam involved to see what they can suggest.

**Comment by samuelklee** [comment]
Would definitely be good to make changes to WDL if needed---let's discuss more in person?

**Comment by vdauwera** [comment]
Scheduling that might be tricky on my end -- I'm working from home until next week then heading out to Europe & South Africa until the end of the month. I'll be onsite tomorrow morning (giving the MPG primer at 8:30) but I won't stick around very long. If you're available then we can definitely chat; otherwise I might recommend you get the conversation going with redteam and I'll provide air support over slack/email where I can.

**Comment by samuelklee** [comment]
Closing this for now.  We can reopen if it turns out to be an issue.
