### ISSUE TITLE
Tools in CNV workflows should accept standard interval list formats

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#3658]
Encountered this problem in CNV tools but it may occur elsewhere. All GATK tools should use engine capabilities to accept the major standard interval list formats (including "GATK style" and "Picard style" as documented [here](https://software.broadinstitute.org/gatk/documentation/article?id=1319)). Requiring a specific interval format is a huge and unnecessary pain in the neck for end users...

**Comment by samuelklee** [comment]
Already on our radar, see #3246.  This is already being partly addressed by #3597 (which should be merged shortly) and hopefully @asmirnov239's tool will be under review shortly.  It then remains to port over the GC annotation code.

**Comment by vdauwera** [comment]
Ah, fantastic, that's good to hear. Thanks!
