### ISSUE TITLE
Speed up CombineGVCFs

### ISSUE THREAD

**Issue by nh13** [broadinstitute/gatk#366]
As a bioinformatician, I would like to combine gvcfs quickly for large sets of genomes, and intelligently use indexes (we do not need them persistent in memory through execution), so that combining hundreds of whole genome gvcfs is as fast as reading the file.

**Comment by eitanbanks** [comment]
I would like to submit that we should connect this issue to the development of the Likelihood Store.  Once the LS is live no one (including external users) will ever need CombineGVCFs again.

**Comment by nh13** [comment]
Agreed, take out the index part and my story could use the likelihood store!

**Comment by akiezun** [comment]
@nh13 can you specify acceptance criteria for this?
depends on https://github.com/broadinstitute/hellbender/issues/16

**Comment by nh13** [comment]
I will work with @eitanbanks to get this.

**Comment by nh13** [comment]
```CombineGVCFs``` scales exponentially (claim made by @eitanbanks), and we would like to see the solution scale an order of magnitude faster (up to 100K gvcfs).  Another acceptable use case is to achieve the same results by removing ```CombineGVCFs``` from the gvcf creation to genotype gvcfs process, reducing the run time of that process by the same amount as if you had scaled ```CombineGVCFs```.

**Comment by akiezun** [comment]
Low prio because likelihood store replaces this code

**Comment by akiezun** [comment]
i'm closoing this. the code is not ported. we'll profile it then
