### ISSUE TITLE
SamAssertionUtils silently failing

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#3664]
Since the Picard changes in #3620, SamAssertionUtils has been failing silently. See e.g. the Standard error tab for https://storage.googleapis.com/hellbender-test-logs/build_reports/13120.7/tests/test/classes/org.broadinstitute.hellbender.tools.spark.pipelines.ReadsPipelineSparkIntegrationTest.html:

```
USAGE: SortSam [arguments]
...
input is not a recognized option
```

**Comment by tomwhite** [comment]
@cmnbroad any thoughts about what is happening here - something to do with case (input vs INPUT)?

**Comment by cmnbroad** [comment]
@tomwhite Yeah - I know what it is. PR coming.
