### ISSUE TITLE
GenomicsDB should handle all VCFHeaderLine types

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3677]
Currently GenomicsDB's `GenomicsDBImporter.generateVidMapFromMergedHeader` only includes specific subclasses of `VCFHeaderLine`.  It's missing support for `VCFHeaderLine` and `SimpleVCFHeaderLine`.  These header lines should be handled and propagated to the output.

**Comment by lbergelson** [comment]
@kgururaj Feature request for you here.

**Comment by sooheelee** [comment]
Hi @lbergelson @kgururaj. I have a user with a headerline error from GenomicsDB that may or may not be related. Would it be possible for one of you to take a glance and let me know if I should post a new bug report or if this PR will fix the issue? Thanks so much.

```
htsjdk.tribble.TribbleException: Could not decode field AS_RAW_ReadPosRankSum with value |5 of declared type Float
```

User error is described at  https://gatkforums.broadinstitute.org/gatk/discussion/11107/gatk4beta6-annotation-incompatibility-between-haplotypecaller-and-genomicsdbimport#latest.
