### ISSUE TITLE
"sites-only" query for GenomicsDB

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#3688]
In order for the variant calling pipeline to be able to scale to process the 68K genomes in the next version of gnomAD and beyond, we need to limit the amount of genotype data we localize.  For the filtering portion of the pipeline we could greatly improve performance using a "sites-only" query from GenomicsDB.  The result could be in BCF format (as I believe it is now) and should include the first 8 fields of the VCF line (CHROM, POS, ID, REF, ALT, QUAL, FILTER, INFO) but should not return format-level/genotype data.

**Comment by ldgauthier** [comment]
@kgururaj Hopefully this will be relatively easy.  We're going to need this for 68K callset we promised in the next quarter.

**Comment by cmnbroad** [comment]
Per discussion with @kgururaj, this will probably take the form of a flag that suppresses materializing the genotype data. Also see the protobuf-based enhancements described [here](https://github.com/broadinstitute/gatk/issues/3689).

**Comment by ldgauthier** [comment]
I did a really rough benchmarking of the new mode on my local machine.  There were ~80,000 samples and ~40,000 variants.  Master finished in 139.6 minutes and the new branch finished in 44.74.  Significant speedup!  At a glance the variants and INFO field attributes look like they match, but I'm running a more thorough comparison now.

There's something weird about the logging though.  Master output a progress update every 1000 variants, but the new branch only had an update at 1000 and then the total stats when it finished:
```
 16:19:16.342 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
 Chromosome chr20 position 1279618 (TileDB column 2714308521) has too many alleles in the combined VCF record : 61 : current limit : 50. Fields, such as  PL, with length equal to the number of genotypes will NOT be added for this location.
 17:03:54.604 INFO  ProgressMeter -        chr20:1269692             44.6                  1000             22.4
 GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),0.36128615400000264,Cpu time(s),0.3515559999999785
 17:03:56.445 INFO  ProgressMeter -        chr20:1308850             44.7                 40156            899.0
 17:03:56.445 INFO  ProgressMeter - Traversal complete. Processed 40156 total variants in 44.7 minutes.
```

**Comment by ldgauthier** [comment]
@kgururaj There does seem to be a significant discrepancy in the INFO field depth (DP) for about a quarter of the sites.  Example below (left is original, right is new sites-only mode):
```
chr20   1270174 .       TA      T,<NON_REF>     .       .       DP=1680211;MQRankSum=0.387;MQ_DP=158;QUALapprox=1557; | chr20   1270174 .       TA      T,<NON_REF>     .       .       DP=2528691;MQRankSum=0.387;MQ_DP=158;QUALapprox=1557;
chr20   1270175 .       A       *,<NON_REF>     .       .       DP=1680371                                            | chr20   1270175 .       A       *,<NON_REF>     .       .       DP=2528811
chr20   1270176 .       A       <NON_REF>       .       .       .                                                       chr20   1270176 .       A       <NON_REF>       .       .       .
chr20   1270177 .       A       <NON_REF>       .       .       .                                                       chr20   1270177 .       A       <NON_REF>       .       .       .
chr20   1270178 .       C       <NON_REF>       .       .       .                                                       chr20   1270178 .       C       <NON_REF>       .       .       .
chr20   1270179 .       A       G,<NON_REF>     .       .       DP=1681456;MQ=60.00;MQRankSum=-1.330e-01;MQ_DP=3998;Q | chr20   1270179 .       A       G,<NON_REF>     .       .       DP=2529148;MQ=60.00;MQRankSum=-1.330e-01;MQ_DP=3998;Q
chr20   1270180 .       T       <NON_REF>       .       .       .                                                       chr20   1270180 .       T       <NON_REF>       .       .       .
chr20   1270181 .       T       G,<NON_REF>     .       .       DP=1680135;MQRankSum=-5.980e-01;MQ_DP=122;QUALapprox= | chr20   1270181 .       T       G,<NON_REF>     .       .       DP=2528796;MQRankSum=-5.980e-01;MQ_DP=122;QUALapprox=
chr20   1270182 .       G       <NON_REF>       .       .       .                                                       chr20   1270182 .       G       <NON_REF>       .       .       .
chr20   1270183 .       A       <NON_REF>       .       .       .                                                       chr20   1270183 .       A       <NON_REF>       .       .       .
chr20   1270184 .       C       <NON_REF>       .       .       .                                                       chr20   1270184 .       C       <NON_REF>       .       .       .
chr20   1270185 .       C       A,<NON_REF>     .       .       DP=1679938;MQRankSum=0.401;MQ_DP=276;QUALapprox=3525; | chr20   1270185 .       C       A,<NON_REF>     .       .       DP=2528310;MQRankSum=0.401;MQ_DP=276;QUALapprox=3525;
chr20   1270186 .       A       <NON_REF>       .       .       .                                                       chr20   1270186 .       A       <NON_REF>       .       .       .
chr20   1270187 .       G       T,<NON_REF>     .       .       DP=1680013;MQRankSum=1.52;MQ_DP=16;QUALapprox=210;RAW | chr20   1270187 .       G       T,<NON_REF>     .       .       DP=2528560;MQRankSum=1.52;MQ_DP=16;QUALapprox=210;RAW
chr20   1270188 .       C       G,<NON_REF>     .       .       DP=1680051;MQRankSum=-1.480e+00;MQ_DP=13;QUALapprox=1 | chr20   1270188 .       C       G,<NON_REF>     .       .       DP=2528536;MQRankSum=-1.480e+00;MQ_DP=13;QUALapprox=1
```
GenotypeGVCFs from the original jar agrees with the version on the left from the same jar, which isn't a big surprise.  My intuition leads me to believe that this could be something like excluding no-call sites from the DP sum, but in the new version those sites don't become no-call without genotyping.  Can you see if you can reproduce the problem with a more manageable number of samples?

**Comment by ldgauthier** [comment]
Darn, I forgot about that.  I was hoping to not have to touch the genotypes at all, as you implemented it.  Let me look at some more data and see if there's anything we can do. There are a couple different flavors of depth and maybe the sum over the INFO field does make more sense.

**Comment by droazen** [comment]
Sounds like the fix here might kill some/all of our performance gains from implementing this feature... :(

**Comment by kgururaj** [comment]
* The performance should be fine - TileDB/GenomicsDB stores each field in a separate file (columnar storage) and so adding MIN_DP file to the list of queried fields (~5-10 INFO fields) should be fine.
* One possible source of performance improvement - I was querying the PL field in the sites only query (not producing it in the output VariantContext objects). I think it can be dropped from the query. I was assuming that the PL field would be needed to correctly handle spanning deletions (spanning deletion corresponds to deletion allele with min PL). However, for spanning deletions, all INFO fields are dropped. Hence, any INFO fields that depend on the allele order (allele specific annotations) would be dropped for the spanning deletion. Hence, the exact deletion allele corresponding to the spanning deletion is irrelevant making it possible to drop the PL field from the query as well. Is that correct?

**Comment by ldgauthier** [comment]
I reran the data with the new branch, but forgot to enable the sites-only mode.  :-(  I'm going to do it right this time and I'll get you results (and possibly an associated thumbs up or thumbs down) soon @kgururaj .

**Comment by ldgauthier** [comment]
BTW, we could actually get a more accurate DP estimate by using the INFO field instead of the FORMAT DP (so we wouldn't have to touch the genotypes at all), but I'm still thinking through the implementation details.  It would introduce batch effects, but it would be an improvement in results and rescue your performance optimization.

**Comment by ldgauthier** [comment]
New version looks good!  My results show identical data in the first 8 columns (sites-only) of the VCF from master and from the latest gatk-3688 branch commit.  The log says the new version ran in 39.61 minutes, which is much, much better than the 139.75 minutes for master.  I give it a :+1: for meeting the requirements in this issue.

I'm still getting very coarse logging, though:
```
14:52:36.401 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
15:32:05.185 INFO  ProgressMeter -        chr20:1269692             39.5                  1000             25.3
GENOMICSDB_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),0.3190466489999985,Cpu time(s),0.3105320000000207
15:32:06.573 INFO  ProgressMeter -        chr20:1308850             39.5                 40156           1016.5
15:32:06.573 INFO  ProgressMeter - Traversal complete. Processed 40156 total variants in 39.5 minutes.
```
@droazen and I talked about this and he has some ideas, but that can be another ticket.

**Comment by droazen** [comment]
Implemented in https://github.com/broadinstitute/gatk/pull/4645
