### ISSUE TITLE
Provide a way of streaming data in/out of PythonScriptExecutor

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3698]
We want tasks such as parsing VCF files to be done in Java, rather than in Python, so that we can leverage all the work we do in htsjdk even in tools that call into a `PythonScriptExecutor`. This implies that we need an easy/efficient means of streaming data in and out of the child Python process. Perhaps a "popen()"-like approach would be good here (or a named FIFO, or protocol buffers...lots of options).

**Comment by droazen** [comment]
For @cmnbroad. It shouldn't be too hard to implement some simple mechanism here. 

Needed for @lucidtronix 's work on the next-generation VQSR.

**Comment by mbabadi** [comment]
Our current mode of communication in gCNV is disk I/O. In my estimate, I/O is _not_ going to take a significant amount of time relatively. The overall structure is as follows: (java) pre-processing and filtering counts and writing processed counts to disk, (python) reading the processed counts, making CNV calls, writing model parameters and CNV posteriors to disk, (back to java) loading python results from disk and post-processing, i.e. creating .vcf files, .seg files, etc.

**Comment by droazen** [comment]
@mbabadi Ah, well file-based I/O would be the simplest option of all, of course, and should definitely be considered as a candidate solution to this ticket, particularly if you've already tried it and found the performance penalty to be minimal for your use case (@cmnbroad take note).

The division of labor you describe between Java and Python sounds great, by the way -- exactly the sort of approach I was hoping you'd implement.

**Comment by lucidtronix** [comment]
@TedBrookings FYI

**Comment by droazen** [comment]
This was done -- we implemented `StreamingPythonScriptExecutor`
