### ISSUE TITLE
Full support for allele-specific annotations in GenomicsDB

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3707]

**Comment by sooheelee** [comment]
We have a user keen on seeing this done, either in the official release or in a nightly, whichever is sooner. Please can whoever is working on this either post to tell the user at https://gatkforums.broadinstitute.org/gatk/discussion/11107/gatk4beta6-annotation-incompatibility-between-haplotypecaller-and-genomicsdbimport#latest or ping me please? Thanks.

**Comment by droazen** [comment]
Done in https://github.com/broadinstitute/gatk/pull/4261! We have tests, but it would be good for someone like @ldgauthier to try out the new support.

**Comment by ldgauthier** [comment]
I have a giant pile of exomes (1230, on prem) with AS annotations at /humgen/gsa-hpprojects/dev/gauthier/AS_GDBtest/lotsOfExomes.list.  If someone could run Import and Genotype against those I'd be happy to QC.
