### ISSUE TITLE
Add GCS support for fasta and interval files via NIO

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3709]

**Comment by jean-philippe-martin** [comment]
This issue could use a description. Support for reading? Writing? In Spark or outside of Spark?

**Comment by droazen** [comment]
Let's make it easy: read support only, and in walkers only.

**Comment by droazen** [comment]
Basically the walker arguments -I and -V already support GCS, but the arguments -R and -L don't, so this ticket is to enable GCS support for the -R and -L arguments in walkers.
