### ISSUE TITLE
Nightly Cron job failing because of excessive log output

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3710]
Travis is terminating our cron job because there is too much log output.  
It seems to be thousands of repetitions of:

```
21:44:23.077 WARN  DefaultDocWorkUnitHandler - Could not access the field definition for backtrace while searching for SHOW_HIDDEN, presumably because the field is inaccessible
```

Possibly related to our recent inclusion of picard in our doc output?

See: https://travis-ci.org/broadinstitute/gatk/jobs/289240692

**Comment by lbergelson** [comment]
@cmnbroad @jamesemery I'm not sure if this should be addressed in travis or in barclay, maybe you can rocks paper scissors for it?

**Comment by cmnbroad** [comment]
I'll take it. The tab completion task is printing out too many warnings for all of the new instance of unresolvable backtrace variables due to Picard. I'll do....something with it.

**Comment by cmnbroad** [comment]
The number of backtrace messages emitted definitely went up with the addition of the Picard sources, but the number I see when I run the gatkTabComplete task locally is dramatically lower than the number emitted when the cron job runs it. The main difference I can see is the cron job is using openjdk, whereas I'm not; the number of times the message is emitted is definitely sensitive to the order in which the sources are processed and ClassDoc and FieldDoc objects are traversed.

**Comment by cmnbroad** [comment]
Reopening since even though this change fixed the immediate problem and the last cron job appears to have succeeded, its still generating 22497 "backtrace" messages, which is about 22400 more than I see when running the task standalone. Minimally we need to change Barclay to suppress the "backtrace" message that is specific to Throwable.
