### ISSUE TITLE
Possible issue with symbolic link in Dockerfile.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#3730]
Paraphrasing an email from Chunyang Bao:

> In the Dockerfile Line 18, the source code is “RUN ln -s /testdata src/test/resources”. And, I just want to know whether it should be “RUN ln -s src/test/resources /testdata”. Does it make sense? If I change this link, I can get more results from the test script (/root/run_unit_tests.sh)

Will double check this when I get a chance, but perhaps it will be immediately obvious to @lbergelson.

**Comment by lbergelson** [comment]
@samuelklee  I think it's right for what we're doing.  We mount the test data as `/testdata` and then create a symlink from src/test/resources to /testdata to provide it to the test files.  It seems to work.
 
I'm not clear what they get more of the other way around.  More tests?  Are they using our create docker script? Or our travis file? Or something else?  I think we might just be able to just directly mount test data to src/test/resources and avoid the symlink, but I probably had a reason when I set it up that way...

I think this is a non-issue unless they can provide more information.

**Comment by samuelklee** [comment]
OK, thanks for taking a look---I haven't had a chance to yet.  I've sent him a link to this issue in case he wants to provide more detail, otherwise we can close for now.
