### ISSUE TITLE
GenomicsDBImport segfaults during batch import

### ISSUE THREAD

**Issue by chapmanb** [broadinstitute/gatk#3736]
Hi all;
I'm running to a segfault issue with GATK4 beta6 when running GenomicsDBImport on some batches. This is a small self contained test case that demonstrates the problem:

https://s3.amazonaws.com/chapmanb/testcases/gatk/gatk4_genomicsdb_segfault.tar.gz

When running:
```
gatk-launch --javaOptions '-Xms1g -Xmx2g' GenomicsDBImport --genomicsDBWorkspace fails_genomicsdb -L chr6:130365070-146544250 --variant NA12878.vcf.gz --variant NA24631.vcf.gz --variant NA24385.vcf.gz
```
It appears to segfault in jniImportBatch:
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.intel.genomicsdb.GenomicsDBImporter.jniImportBatch(J[J)Z+0
j  com.intel.genomicsdb.GenomicsDBImporter.importBatch()Z+160
j  org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.traverse()V+301
j  org.broadinstitute.hellbender.engine.GATKTool.doWork()Ljava/lang/Object;+12
j  org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool()Ljava/lang/Object;+27
j  org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs()Ljava/lang/Object;+431
j  org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain([Ljava/lang/String;)Ljava/lang/Object;+14
j  org.broadinstitute.hellbender.Main.runCommandLineProgram(Lorg/broadinstitute/hellbender/cmdline/CommandLineProgram;[Ljava/lang/String;)Ljava/lang/Object;+20
j  org.broadinstitute.hellbender.Main.mainEntry([Ljava/lang/String;)V+19
j  org.broadinstitute.hellbender.Main.main([Ljava/lang/String;)V+8
v  ~StubRoutines::call_stub
```
The same command works without the NA24385.vcf.gz sample but it wasn't clear what caused the issue from this input. I'm also seeing similar behavior over a few other regions and guess they're all caused by the same underlying issue.

Thanks much for any pointers or ideas and please let me know if any other information would be useful.

**Comment by droazen** [comment]
@kgururaj Could you look into this one?

**Comment by chapmanb** [comment]
Thanks so much for looking at this. I was digging into it a bit more after submitting the issue and noticed one difference between the NA24385 sample and the others was the presence of dbSNP membership and the `DB` INFO flag. We used HaplotypeCallerSpark to generate the NA24385 VCF, which does not support dbSNP, but the others used standard HaplotypeCaller, which does. I'm not sure if this is a trigger for the actual problem but just an FYI in case it helps.

**Comment by droazen** [comment]
@chapmanb Is this still a problem for you in the 4.0 release?

**Comment by chapmanb** [comment]
Thanks for checking in on this. 4.0 still has the same segfault issue with the real samples and this test case. The test case just needs a little light editing to swap over to your new command line parameters but otherwise should reproduce the issue. Let me know if I can provide anything else that would be helpful and thanks again for looking at it.

**Comment by droazen** [comment]
@kgururaj Can you have a look at this one as well?

**Comment by kgururaj** [comment]
The NA24385.vcf.gz is missing the DB field in the header - this INFO field is of type Flag.  This hit an unhandled corner case in GenomicsDB. Fixed in the code now. Thanks.

For now, you can fix your use case by adding the DB field in the header.

**Comment by droazen** [comment]
Resolved by https://github.com/broadinstitute/gatk/pull/4261
