### ISSUE TITLE
SimpleAnnotatedGenomicRegion refactoring to use Tribble

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#3738]
- Additionally, we should create a LocatableCollection class rather than using List<SimpleAnnotatedGenomicRegion>

We can probably reuse the SimpleAnnotatedGenomicRegion static parsing methods, but these should be moved to a new class.

**Comment by LeeTL1220** [comment]
The ultimate goal is to be able to do concordance analyses across VCF TSV (SEG, MAF) etc.  

To do this, we will need to have a Tribble codec for segment files.

**Comment by samuelklee** [comment]
Encapsulated by #4717.
