### ISSUE TITLE
Uninformative warning from GenomicsDB when PLs are dropped

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#3745]
When running a prototype tool similar to GenotypeGVCFs on gs://broad-jg-dev-11k-call-set/ImportVcfs/b617fc44-4d01-4f0c-ab1c-21df9943f6ec/call-ImportGVCFs/shard-0/attempt-3/genomicsdb.tar I saw the following warning:
`Column 2713622024 has too many alleles in the combined VCF record : 72 : current limit : 50. Fields, such as  PL, with length equal to the number of genotypes will NOT be added for this location.`

A more informative warning would contain the chromosome and position corresponding to that column.

**Comment by droazen** [comment]
Resolved by https://github.com/broadinstitute/gatk/pull/4261

**Comment by ldgauthier** [comment]
Just saw one of these in the log that I'm going to go investigate.  The new error message is very helpful, thanks @kgururaj !

**Comment by droazen** [comment]
You mean you saw an **informative** error message rather than an **uninformative** one, I assume? :)

**Comment by ldgauthier** [comment]
Oops, yes, I saw the new one!  Very informative.
