### ISSUE TITLE
SamAssertionUtils.assertSamsEqual should return a more useful message

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#375]
Currently `SamAssertionUtils.assertSamsEqual` fails with `"SAM file output differs from expected output"`.  It uses `SamComparison`, which prints a lot of helpful information about how the files differ to stdout.  This output is often hidden when running it in a test suite though.  It's also a bit strange to print error messages to stdout.  `SamComparison` should capture this information and provide an accessor to retrieve it instead of dumping it to stdout.

**Comment by droazen** [comment]
This is a dupe of https://github.com/broadinstitute/hellbender/issues/190

**Comment by lbergelson** [comment]
I don't think it's quite a dupe of it.  It's more a subset :)

**Comment by droazen** [comment]
This one is done! Closing
