### ISSUE TITLE
Check if gatk4 thinks hg19 sequence dictionary is compatible with hg38

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3754]
I have a suspicion that we might determine hg19 and hg38 are compatible because of the change in `chr` naming and a shared contig `M`.  We should check this...

**Comment by droazen** [comment]
@lbergelson Since we were just talking about this issue, I'm resurrecting this old ticket for you

**Comment by lbergelson** [comment]
My suspicion was wrong.  We also include a safety check which cause us to correctly reject most accidental matches.  If we detect 2 chromosomes with the same name but different lengths we fail even if we detect otherwise matching chromosomes.

I've run all the dictionaries I could find in the gatk bundle against each and only b37 and b37_decoy are compatible with each other which is the desired behavior I believe.


|           |  hg18 | hg19 | b37 | b37_decoy | hg38 |
| --      |------|-----|------|-----------|-------|
| hg18  | ✅      |         |         |                   |            |
| hg19  |         | ✅         |         |                   |            |
| b37 |         |         |     ✅    |       ✅            |            |
| b37_decoy  |         |         |    ✅     |         ✅          |            |
| hg38 |         |         |         |                   |        ✅    |

```
    @DataProvider
    public Iterator<Object[]> getComparisons(){
        final ArrayList<Object[]> comparisons = new ArrayList<>();
        final List<String> dicts = Arrays.asList("Homo_sapiens_assembly18.dict",
                                                   "ucsc.hg19.dict",
                                                   "human_b36_both.dict",
                                                   "human_g1k_v37.dict",
                                                   "human_g1k_v37_decoy.dict",
                                                   "Homo_sapiens_assembly38.dict");
        for( String left : dicts) {
            for (String right: dicts){
                Path leftDict =Paths.get("/Users/louisb/Downloads/dicts", left);
                Path rightDict = Paths.get("/Users/louisb/Downloads/dicts", right);

                comparisons.add( new Object[] {leftDict, rightDict});
            }
        }
        return comparisons.iterator();
    }

    @Test(dataProvider = "getComparisons")
    public void testSequenceDictionariesAgainstEachother(Path left, Path right){
        String leftName = left.getFileName().toString();
        String rightName = right.getFileName().toString();
            SequenceDictionaryUtils.validateDictionaries(leftName,
                                                         SAMSequenceDictionaryExtractor.extractDictionary(left),
                                                         rightName,
                                                         SAMSequenceDictionaryExtractor.extractDictionary(right));
    }
```

**Comment by ldgauthier** [comment]
I'm not sure how I feel about b37 and b37_decoy being compatible.  On the one hand, if you provide one reference for a VCF derived from the other in order to SelectVariants, it's not a big deal, but a bam aligned to b37 and the same bam aligned to b37_decoy will have some definite differences in the autosomes.  I suspect @yfarjoun would prefer that they are not considered compatible.

**Comment by lbergelson** [comment]
@ldgauthier Yes, there's definitely a disagreement about what the criteria should be.  We can argue about changing it but that's outside of the scope of this issue...  I was just testing if it actually behaved the way people think it does to or if we were accidentally letting in extra stuff that we definitely shouldn't be.

**Comment by droazen** [comment]
@ldgauthier Feel free to open a ticket describing your dream sequence dictionary compatibility check -- we can make the existing check stricter if you think the existing check is too permissive, since users are always free to run with `--disable-sequence-dictionary-validation`
