### ISSUE TITLE
Create a path-based line reader

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#3756]
We need a file reader that is based on the `java.nio.path` interface that can read lines from a `Path` object.  This should wrap `files.lines` and return an `Iterator<String>`.

**Comment by magicDGS** [comment]
I think that this does not require a line reader. It could be done by simply use `Files.lines(path).iterator()` for the `Path`. Maybe it could be included directly in the utils class (e.g., Utils.lineIterator(Path)`).
