### ISSUE TITLE
Need simple parser for non-locatable files

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#3757]
We need a parser that can read in non-Locatable files.

These files will be *sv formatted (e.g. tsv / csv / etc.).

This should be based off of the simple `Path` reader in #3756

**Comment by magicDGS** [comment]
Cannot this use directly `TableReader`? Maybe it should include a `Path` constructor and being refactored a bit...

Another option could be the picard `BasicInputParser`, `TabbedInputParser` or `TabbedTextFileWithHeaderParser`...

**Comment by droazen** [comment]
This particular reader will be specialized for the needs of the funcotator tool, so it will likely be its own thing (but built on top of a more primitive reader).
