### ISSUE TITLE
CommandLineProgram TMP_DIR should support java.nio.Path

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#3765]
Currently, it is constraint to be a `File`. With the change in https://github.com/samtools/htsjdk/pull/910, it can be a list of `String`: the method body can use `IOUtils` to convert to a `java.nio.Path` and set the java property.

**Comment by droazen** [comment]
Closing -- this was done in https://github.com/broadinstitute/gatk/pull/4469
