### ISSUE TITLE
Huge -L seems to take longer than it should

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#3788]
I'm running SelectVariants with an interval list L of 600,000 loci and an excluded interval list XL of 160 loci.  Based on restricting L and XL it seems that the runtime scales as |L|x|XL|, which comes out to over an hour.  The runtime does not depend at all on the size of the vcf in the -V argument.  That is, once traversal begins it's basically instantaneous, but processing the intervals takes forever.

Naively, one could make this scale as |L| + |XL| by querying each variant in the input vcf against L and then against XL.  For reasons @cmnbroad points out this is not a great solution, but it seems like because (i) L and XL are ordered and (ii) each L overlaps with only a sparse subset of XL and vice versa that this quadratic scaling is not necessary.

For my case I can get around this easily by preprocessing V with -XL, then running SelectVariants with -L.

@lbergelson was also in this conversation.

**Comment by droazen** [comment]
To make sure I understand, are you saying that it took over an hour for traversal to even start in this case?

**Comment by lbergelson** [comment]
@davidbenjamin Could you upload your interval files somewhere so we can reproduce this.

**Comment by davidbenjamin** [comment]
@droazen That's right -- the whole thing is over an hour but traversal itself is a few seconds.

**Comment by davidbenjamin** [comment]
@lbergelson @cmnbroad @droazen I investigated further and to my surprise the excluded intervals are a red herring.  The time is linear in |L| and I just assumed it was linear in |XL| as well, but the command took an hour *without* any `-XL` at all.  So the issue is just that processing a large interval list seems to take longer than it ought to.  Here's the full command, with paths:

```bash
input_vcf=/dsde/working/davidben/mutect/speed/realign/subsetted_truth.vcf
intervals=/dsde/working/davidben/mutect/speed/realign/inactiveRegions.list

#same behavior for master builds on 5-16, 7-10, and 9-6
gatk=/dsde/working/davidben/gatk_builds/master-11-1.jar
java -jar $gatk SelectVariants -V $input_vcf -L $intervals -selectType SNP -O out.vcf
```

The output is
```bash
16:04:11.274 INFO  SelectVariants - HTSJDK Defaults.COMPRESSION_LEVEL : 5
16:04:11.275 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
16:04:11.275 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : false
16:04:11.275 INFO  SelectVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
16:04:11.275 INFO  SelectVariants - Deflater: IntelDeflater
16:04:11.275 INFO  SelectVariants - Inflater: IntelInflater
16:04:11.275 INFO  SelectVariants - GCS max retries/reopens: 20
16:04:11.275 INFO  SelectVariants - Using google-cloud-java patch c035098b5e62cb4fe9155eff07ce88449a361f5d from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
16:04:11.275 INFO  SelectVariants - Initializing engine
16:04:12.848 INFO  FeatureManager - Using codec VCFCodec to read file file:///dsde/working/davidben/mutect/speed/realign/subsetted_truth.vcf
17:06:21.155 INFO  IntervalArgumentCollection - Processing 173964752 bp from intervals
17:06:21.203 INFO  SelectVariants - Done initializing engine
17:06:25.808 INFO  ProgressMeter - Starting traversal
17:06:25.808 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
17:06:29.757 INFO  ProgressMeter -             unmapped              0.1                    86           1307.0
17:06:29.757 INFO  ProgressMeter - Traversal complete. Processed 86 total variants in 0.1 minutes.
17:06:30.049 INFO  SelectVariants - Shutting down engine
[November 2, 2017 5:06:30 PM EDT] org.broadinstitute.hellbender.tools.walkers.variantutils.SelectVariants done. Elapsed time: 62.33 minutes.
Runtime.totalMemory()=10042212352
```
and the line it hangs on is `FeatureManager - Using codec VCFCodec to read file`.

**Comment by cmnbroad** [comment]
The problem appears to be [here](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/utils/IntervalUtils.java#L403-L410). This is called once for each input interval, with setTwo growing by 1 each time.  Lots of time spent in the addAll(setTwo) on line 408.

**Comment by davidbenjamin** [comment]
If I understand correctly, are you saying that if the input intervals are A, B, C, D, the pseudocode for `loadIntervals` in case of `IntervalSetRule.UNION` is:

```
initialize cumulative interval list to empty list
for (intervalString in intervals) {
  parse the next interval
  *recalculate* cumulative intervals = union(next interval, cumulative intervals)
  // as opposed to cumulative intervals.add(next interval)
}
```
  which scales quadratically.

**Comment by droazen** [comment]
@davidbenjamin Could you run JProfiler on your test case and post the CPU profile here? Profiling beats manual code inspection any day of the week ;)

**Comment by cmnbroad** [comment]
I have a local test case using a modified version of @davidbenjamin 's interval list (cut down to 175000 intervals) and can see thats where the time is going. I'll run it and save the profile - it just takes forever to run.

**Comment by cmnbroad** [comment]
<img width="1225" alt="screen shot 2017-11-03 at 11 53 14 am" src="https://user-images.githubusercontent.com/10062863/32383235-d2670822-c08d-11e7-9b0e-b3a4ebbeb90f.png">
<img width="1228" alt="screen shot 2017-11-03 at 11 53 55 am" src="https://user-images.githubusercontent.com/10062863/32383247-dd9f2152-c08d-11e7-85ab-d8d18bc41f3f.png">

**Comment by droazen** [comment]
@cmnbroad Ok, great -- would you have time to submit a quick patch against `IntervalUtils`?

**Comment by cmnbroad** [comment]
Sure.

**Comment by cmnbroad** [comment]
The fix here is to stop Barclay from auto-expanding files with a ".list" extension (the extension will be changed to ".args"). With this change, for the common case of a .list file, the interval merging code will see a single (file) value, which it will load directly, rather than the already expanded list of interval strings. Loading the file directly results in a single call to mergeListsBySetOperator (which re-copies the entire aggregate interval list on each call), rather one call per interval. Note that this doesn't actually change the underlying order of growth of mergeListsBySetOperator; it just minimizes the magnitude of the input size.

**Comment by droazen** [comment]
This was fixed
