### ISSUE TITLE
Patch build_docker.sh -p option to push to GCR in addition to dockerhub

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3793]
As discussed internally, we should publish our docker image to GCR in addition to dockerhub, so that dockerhub won't get clobbered by our production users.

The GCR repo to use will be provided by @hjfbynara. Once we have it, we should patch `build_docker.sh -p` to push there as well, and update our "How to release GATK" wiki article appropriately.

**Comment by hjfbynara** [comment]
created the google group (gatk-release@broadinstitute.org), populated it and transferred ownership to the team.  Created the google project: broad-gatk enabled container registry. Made Geraldine and David Owners.   Added gatk-release google group as Editors

Could someone test out pushing to GCR:

docker pull broadinstitute/gatk:<someTAG>

gcloud docker -- push us.gcr.io/broad-gatk/gatk:<someTAG>

Then you should browse to the Google project: https://console.cloud.google.com/gcr/images/broad-gatk?project=broad-gatk&organizationId=548622027621
and see the image

**Comment by droazen** [comment]
@hjfbynara I'll try this out now and let you know how it goes

**Comment by droazen** [comment]
@hjfbynara I was able to push a copy of the latest GATK4 docker image (4.beta.6) into the new GCR repo. 

I assume that this is sufficient to alleviate the current crisis for now. I'll update our release script early next week so that future releases will also get published to the GCR repo.
