### ISSUE TITLE
Command lines contain fully-expanded lists when displayed, no matter how long

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#3797]
If you specify an input argument that is a file that is auto-expanded by Barclay, the entire contents of the expanded list is included wherever command lines are displayed, such as on the command line and in output files (PG records, etc.).

**Comment by droazen** [comment]
Uh-oh...we should definitely fix this :)

**Comment by magicDGS** [comment]
I think that this is a nice feature (at least for me) and not a bug. For example, if in GATK someone runs a tool with `-RF read_filters.args`, then the pipeline cannot be reproduced in a different dataset unless the file is accessible.

I can understand that it could be also nice to preserve the `-RF read_filters.args` to be able to modify the file an re-run the tool with different parameters, but for me the purpose of storing the command line in the header or other places is keep track of the exact params that I used: if a file is modified, then it is impossible to trace the params. For input files, this is expected (if the input has changed, it is expected that the result change), but for arguments it shouldn't be the case (independently of the file changing, the tool was running with exactly that parameters).

I vote for solve this in Barclay in a configurable way, to allow users to decide which kind of verbosity of the command line they want (I definitely prefer to expand as currently).

**Comment by cmnbroad** [comment]
We need to put some hard upper limit on the number of entries included in the output. The issue that brought this to my attention was an intervals list with 600,000+ entries.

**Comment by droazen** [comment]
Done in https://github.com/broadinstitute/gatk/pull/4270
