### ISSUE TITLE
If CG tag is present in SAM record, use as CIGAR string

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3799]
For compatibility with long reads, if we will become interested in supporting their features down the road. Otherwise, please take this ticket as informational.

New aligner by Heng Li, Minimap2, has option to emit `CG` tag containing full CIGAR string for long reads that would have >65535 CIGAR operations. This is for BAM compatibility. My understanding is that in such cases, the CIGAR field would then contain only clipping information.

Minimap2 will also have the option to emit a `CS` tag, encoding bases at mismatches and INDELs.

This mapper is originally intended for long read mapping, e.g. at the scale of PacBio and Oxford Nanopore (ONT), where it is ~ten times faster than BWA-MEM and other conventional mappers for ~10kb noisy reads. **The mapper is also currently compatible with >100 base reads, either genomic (DNA) or spliced nucleotide (RNA) and for these, is three times faster than BWA-MEM and Bowtie2.** 

See <https://github.com/lh3/minimap2> for details and <https://arxiv.org/pdf/1708.01492.pdf> for the preprint.

**Comment by droazen** [comment]
@sooheelee This should be handled automatically by the htsjdk API rather than the GATK. Eg., `getCigar()` on a `SAMRecord` should automatically check `CG` as necessary.

**Comment by sooheelee** [comment]
@droazen you are saying this is already something htsjdk handles correctly? 

Apologies for posting to the incorrect repo. You are entirely correct and I jumped the gun. Can I leave this up for sometime for others to be informed?

**Comment by sooheelee** [comment]
Heng says he has pull requests in htsjdk that are pending. Also mentions that @droazen and @lbergelson may want to reimplement it.

**Comment by sooheelee** [comment]
Will close this as it's been up a month and parties should be informed.
