### ISSUE TITLE
Reversion of compatibility with GRCh38 HLA contigs?

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3807]
I came across some notes I made 20170901, while developing the Helsinki Mutect2 tutorial, to report a particular bug, that I am just now getting around to. Here is the command I ended up using to solve the problem:
```
gatk-launch PrintReads -I hcc1143_N_clean.bam -O hcc1143_N_chr17.bam -L chr17 -L chr11:915890-1133890 -L chr6:29941013-29946495 -L chr11_KI270927v1_alt -L HLA-A*24:03:01:1+
```

Notice the protection tag `:1+` that I add to the last interval. If I do not add this, I get the following error:
```
***********************************************************************

A USER ERROR has occurred: Badly formed genome unclippedLoc: Contig 'HLA-A*24:03' does not match any contig in the GATK sequence dictionary derived from the reference; are you sure you are using the correct reference fasta file?

***********************************************************************
```
This error persists even if I provide a dictionary/ref to the command. 

The solution comes from the pipelines team, in their [PESS workflow that I documented](https://gatkforums.broadinstitute.org/gatk/discussion/7899/reference-implementation-pairedendsinglesamplewf-pipeline), so credit goes to them. Perhaps our code can do this internally for HLA contigs.

Sorry for the late notice. I've been extremely busy. I will assign @droazen since we touched upon this briefly last week.

**Comment by cmnbroad** [comment]
This was fixed in https://github.com/broadinstitute/gatk/pull/4093. The ":+1" is no longer necessary.
