### ISSUE TITLE
Add documentedfeature tag to annotation modules and make content consistent

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#3809]
E.g. SOR annotation does not show up in GATK4 versioned docs currently. Code at
 <https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandOddsRatio.java> needs `@DocumentedFeature` tag at top.

**Comment by magicDGS** [comment]
I think that no `VariantAnnotation` is documented yet, because there is no even a plugin. It will be nice to have them anyway...

**Comment by sooheelee** [comment]
Hey @magicDGS, since I'm on the forum documentation side of things, I'm not familiar with a plugin. Is this something @cmnbroad typically takes care of?

**Comment by cmnbroad** [comment]
@magicDGS is correct that no annotations are tagged as `@DocumentedFeature` yet, but thats just because nobody has done it. The plugin (which I think @jamesemery is planning to implement soon), is a completely separate issue - the `@DocumentedFeature` annotations can be added either way.

**Comment by magicDGS** [comment]
I think that the annotation plugin is assigned to @jamesemery here: https://github.com/broadinstitute/gatk/issues/3287

But of course it can be documented before it is a plugin. I just wanted to point out that all of them should be annotated properly...

**Comment by sooheelee** [comment]
I'll ask @jamesemery to explain to me what he is doing fits in with what we need to do on the documntation side.

Is there anything else besides the `@DocumentedFeature` that I should be adding to each annotation document to annotate properly?

**Comment by sooheelee** [comment]
Also, I'll remove the annotation epic label.

**Comment by cmnbroad** [comment]
@sooheelee You'll need to add new string constants for the group name and group summary for annotations to HelpConstants.java, and then use them in each `@DocumentedFeature`, along with a summary specific to each annotation. Take a look at how [read filters](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/engine/filters/ReadFilterLibrary.java#L32) are done as a model. Let me know if you need help with that part.

**Comment by sooheelee** [comment]
## SOP 

[1] Add feature tag and define elements to all annotation modules in <https://github.com/broadinstitute/gatk/tree/master/src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator>. E.g. the tag looks thus:
```
@DocumentedFeature(groupName=HelpConstants.DOC_CAT_READFILTERS, groupSummary=HelpConstants.DOC_CAT_READFILTERS_SUMMARY, summary = "Keep only reads that are first of pair")
```
- group name variable
- group summary variable
- summary 

[2] Add variables to HelpConstants.java at <https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/utils/help/HelpConstants.java>. These need to be under _group definitions_ as well as under _supercategory_.

- group name variable and descriptor
- group summary variable and descriptor
- super category

**Comment by sooheelee** [comment]
- 43 annotation modules under gatk/src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ 
- and 14 additional allele-specific modules under gatk/src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/allelespecific/
- gives 57 pieces of code to tag.

**Comment by cmnbroad** [comment]
@sooheelee Not everything listed above should get a DocumentedFeature tag. For example, Annotation is a base interface; AnnotationUtils are utilities; RankSumTest is a base class for other rank sum-based annotations (none of these should be tagged). There may be others. In general, things that are interfaces, abstract classes, or utility classes should probably be skipped. If in doubt, feel free to ask...

**Comment by sooheelee** [comment]
Thanks for this clarification. I'll check off the ones that obviously need the tag as I tag them and we'll be left with those that are in doubt.

**Comment by sooheelee** [comment]
Unlike the read filters, the annotation modules appear to have more information at top in our forum docs:

![screenshot 2017-11-14 17 29 27](https://user-images.githubusercontent.com/11543866/32808537-592c0bba-c961-11e7-8381-9a4cc57eea6f.png)
![screenshot 2017-11-14 17 29 14](https://user-images.githubusercontent.com/11543866/32808539-5c26da52-c961-11e7-98af-1d2a1b68d947.png)

Do I need to add the `VCF Field`, `Type` and `Header definition line` fields?

**Comment by sooheelee** [comment]
It seems to me the `Header definition line` encompasses the information given by the `VCF Field` so this latter is redundant. 

It would definitely be useful to categorize INFO (cohort) versus FORMAT (SAMPLE) level annotations. I'm not clear on the significance of the `Type` nor `Category` fields.

**Comment by sooheelee** [comment]
CN confirms these elements were pulled out with code in gatk3 but this code was not ported to gatk4. Discussion would be great on what we actually want and should involve @vdauwera.

**Comment by sooheelee** [comment]
Since Geraldine is away till the end of the week, and we are under the Nov 23 deadline for review, I will proceed with changes. I think it useful for me to go through the motions and see what other discussion items turn up.

**Comment by sooheelee** [comment]
Alright, I think I've tagged the documents that need tagging. I've touched 39 documents in total according to the commit history for the pull request.

**Comment by sooheelee** [comment]
This will go through travis checks then review by @cmnbroad.

**Comment by sooheelee** [comment]
Checks failed because missing `import org.broadinstitute.barclay.help.DocumentedFeature;` at top.

**Comment by sooheelee** [comment]
Just set up IntelliJ for a clean master branch and fetched my branch with changes. Going through now and importing both the above and the HelpConstants.

**Comment by sooheelee** [comment]
Had to 
```
WMCF9-CB5:gatk shlee$ git remote remove origin
WMCF9-CB5:gatk shlee$ git remote add origin git@github.com:broadinstitute/gatk.git
```
Before being able to push my branch. Changes are now in and I will go through them to make sure they appear consistent.

**Comment by sooheelee** [comment]
- [ ] Not sure if UniqueAltReadCount.java's acronym is actually UNIQ_ALT_READ_COUNT.
- [ ] Not clear what VariantOverlapAnnotator.java does and whether it actually should be tagged.

**Comment by sooheelee** [comment]
Build with `./gradlew clean gatkDoc` gives the annotations modules in the doc:
<img width="1056" alt="screenshot 2017-11-15 14 46 03" src="https://user-images.githubusercontent.com/11543866/32856838-fe302274-ca13-11e7-8d5e-e3036c466583.png">

This needs review for content. @vdauwera is this something Sheila reviews for me or something you can review given some discussion items should involve you?

**Comment by sooheelee** [comment]
Clicking through these now tagged docs, I see that their detailed descriptors range in detail and some have authors listed. E.g.:

<img width="1050" alt="screenshot 2017-11-15 14 51 41" src="https://user-images.githubusercontent.com/11543866/32857034-952c9810-ca14-11e7-828d-17daa9526837.png">

**Comment by sooheelee** [comment]
- I changed some capitalization depending on what a google search brought up for terms. But I only did so for the summary and did not touch the rest of the doc.

**Comment by vdauwera** [comment]
Based on the screenshot above, it looks like we're missing "VCF Field" (whether it's INFO/site or FORMAT/genotype level), "Type" (eg ActiveRegionBasedAnnotation) and "Header definition line" ie how the annotation is represented and defined in the header. Those need to be extracted programmatically by the doc system. Everything below that is just plain text content that we can add "manually". 

The utility of "Type" is debatable but the other two are really important. We should definitely add those. 

Wrt plain text content it would be good to define a template based on the annotations that are most fully documented in v3.

**Comment by vdauwera** [comment]
Would also be good to annotate which annotator (curr M2, HC and VA) has access to each annotation module.

**Comment by sooheelee** [comment]
Having tagged annotation modules to show up in the tool docs, I'm noticing other missing elements.

### In v3 docs, but in v4 docs:
- ABSENT: Engine Parameters, aka CommandLineGATK (this needs addition)
- seemingly TRUNCATED: Diagnostics and QC Tools section currently only has 3 tools; looks like other tools have been dispersed
- ABSENT: Resource File Codecs (likely intentional)
- ABSENT: Reference Utilities (I think also likely intentional)

### In HelpConstants (and in `--list`), but in v4 docs:
- ABSENT: `DOC_CAT_SPARK_SV = "Spark Structural Variation Analysis Tools";`
- ABSENT: `DOC_CAT_SPARK_PATHSEQ = "PathSeq Tools";`
- ABSENT: `DOC_CAT_SPARK_VALIDATION = "Spark Test Tools";` (likely intentional)
- ABSENT: ` public final static String DOC_CAT_TEST = "Test Tools";` (likely intentional)
- ABSENT: `DOC_CAT_BWA_MEM_UTILS = "Bwa Mem JNI binding Tools";` 
- ABSENT supercategories (not used by `--list` either):
    ```
    public final static String DOC_CAT_VARDISC = "Variant Discovery Tools";
    public final static String DOC_CAT_VAREVAL = "Variant Evaluation Tools";
    public final static String DOC_CAT_VARMANIP = "Variant Manipulation Tools";
    ```

### In `--list`, but in v4 doc:
- Picard tools and categories

### Absent altogether everywhere:
- distinction between GATK and Picard tools
- Picard standard arguments

**Comment by sooheelee** [comment]
SamPileupCodec and TableCodec are in gatk4 though. So do we mean to document these? Looks like @magicDGS is the author on the former. Do we want these to show up in the documentation?

**Comment by vdauwera** [comment]
No we don’t need to document codecs.

**Comment by sooheelee** [comment]
This issue is resolved excepting the "make content consistent" bit. This latter aim will be addressed in <https://github.com/broadinstitute/gatk/issues/3853>.
