### ISSUE TITLE
Bug in GenomicsDB import with renamed duplicate samples in the same batch

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/gatk#3814]
It looks like we've found a bug in GenomicsDB.

We had a project with 26 replicates (same sample in there twice) among another ~1000 samples.  Therefore we uniquified the names in the sample map that’s input to TileDB for those 26 samples (i.e. converted them to project.sample instead of just sample) -- but obviously the names in the gvcfs remained unaltered.

When we look at the output VCF from GenomicsDB, there's definitely a problem.  These 52 samples are the first ones in the list and here's what we see:

The first 26 samples (the first occurrence of the replicates) are fine.
Then the next 24 samples (the second occurrence of the replicates) are all “.:0,0” (i.e. empty) for all columns in the VCF.
Then the next 2 samples (also second occurrences of replicates) are fine.

Given that our batch size was 50 when importing into GenomicsDB, this looks suspiciously like an error with the batching.  So within a batch it looks like it’s not respecting the renaming somehow?

@kgururaj

**Comment by droazen** [comment]
@kgururaj Could you & your team please make this and https://github.com/broadinstitute/gatk/issues/3815 your highest priorities? We'll add more information here as we discover it.

**Comment by droazen** [comment]
@lbergelson has been able to replicate the bug using a simple test case, so this is confirmed.

**Comment by droazen** [comment]
Looking at the code in both GATK's `GenomicsDBImport` and the GenomicsDB library itself, I don't think the sample name map was ever intended as a mechanism to rename samples. It was just added as a way to avoid the up-front download of all the VCF headers.

However, using it to rename samples is a pretty natural thing for clients to do. At a minimum, we need to throw if a rename is attempted until sample renaming via the map file is officially supported and tested.

**Comment by kgururaj** [comment]
A few points:
1. When we wrote the Java interface, the 'agreement' was that the sample names would be unique and consistent within the VCF headers. Hence, the assert statement in the Java code. We pretty much expected this issue to crop up.
1. Having said that, the sample name in the VCF header is ignored completely if checks are disabled (which are disabled by default). This includes the assert statement and a couple of other checks in the importer code. The sample name is taken from the name to reader map provided in the constructor call. This map is created from the tab delimited file.
1. Would it be possible to provide a simple test case to replicate the bug? I couldn't replicate it. Here is what I did.
    1. Three VCF files - t0.vcf.gz, t1.vcf.gz, t0_dup.vcf.gz. t0 and t0_dup are identical except for the GT field in one location. So, these 2 files have the same header (same sample name in the header).
    1. Tab file (unique sample names)

           HG00141 test_inputs/vcf_test_inputs/t0.vcf.gz
           HG0155  test_inputs/vcf_test_inputs/t0_dup.vcf.gz
           HG00192 test_inputs/vcf_test_inputs/t1.vcf.gz

    1. ./gatk-launch GenomicsDBImport --genomicsDBWorkspace /tmp/ws -L 1:1-1000000 --sampleNameMap test_inputs/gatk4_dup_test_list --batchSize 2
    1. Query prints the output correctly

           ./bin/gt_mpi_gather -j test_inputs/query/gatk4-generated.json  --produce-Broad-GVCF

           #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HG00141 HG00192 HG0155
           1       12144   .       G       <NON_REF>       .       .       .       GT      0/0     .       0/0
           1       12191   .       T       <NON_REF>       .       .       .       GT      0/0     0/0     0/0
           1       17385   .       G       A,T,<NON_REF>   .       .       .       GT      0/1     2/2     1/1

    1. Works with batch size 1

**Comment by droazen** [comment]
@lbergelson Can you provide @kgururaj with your simple test case that replicates this issue?

**Comment by droazen** [comment]
We fixed this
