### ISSUE TITLE
LocusWalkerSpark not determining the correct number of RDDs to process

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#3823]
On branch `ll_CollectAllelicCountsSpark`, I have created a CLI called:  `CollectAllelicCountsSpark` ...  This tool will have the exact same functionality as `CollectAllelicCounts`, to the point where I can re-use the integration tests.

However, the integration tests fail.  When I dig deeper in `CollectAllelicCountsSpark`, I see that only 8 RDDs (correct amount: 11) are being passed to processAlignments...  Consider the following code:

```
 @Override
    protected void processAlignments(JavaRDD<LocusWalkerContext> rdd, JavaSparkContext ctx) {
        final String sampleName = SampleNameUtils.readSampleName(getHeaderForReads());
        final SampleMetadata sampleMetadata = new SimpleSampleMetadata(sampleName);
        final Broadcast<SampleMetadata> sampleMetadataBroadcast = ctx.broadcast(sampleMetadata);

        final AllelicCountCollector finalAllelicCountCollector =
                rdd.mapPartitions(distributedCount(sampleMetadataBroadcast.getValue(), minimumBaseQuality))
                .reduce((a1, a2) -> combineAllelicCountCollectors(a1, a2, sampleMetadataBroadcast.getValue()));
        final List<LocusWalkerContext> tmp = rdd.collect();
 ....snip....
```

In this case `tmp` will have a size of 8.  However, the integration test would indicate a size of 11 is correct, since 11 intervals are being passed in.  Note that `emitEmptyLoci()` returns `true`, so 11 is the correct number as seen in `CollectAllelicCountsSparkIntegrationTest` .  

Additionally, in (at least) one result, the counts are wrong.

`CollectAllelicCounts` (non-spark) passes the integration test.

I have tried a couple of tests to gather more information:

- Is `emitEmptyLoci()` causing an issue?  
Does not appear to be causing the issue.  I say this because when set to `false`, I get (essentially) the same error.
- The code uses `mapPartition` and not `map`, does this cause the issue?  Why are you doing this?
This does not cause the issue.  I refactored the code to use `map` and got the exact same issue.  I use `mapPartition` in order to instantiate only one instance of `AllelicCountCollector` per partition, instead of per locus.

Assigning to @tomwhite by request of @droazen ...

**Comment by tomwhite** [comment]
@LeeTL1220 sorry for the long delay, but I think I've found the problem and got a fix, see #5222. Please let me know what you think.
