### ISSUE TITLE
GenomicsDB outputs AD header line that doesn't match HTSJDK

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#3839]
GenomicsDB appears to be adding a headerline:
`##FORMAT=<ID=AD,Number=R,Type=Integer,Description="AD">`
while the htsjdk version used by GATK is:
`##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">`

The consequence is that the final callset has two AD header lines.  This has caused some confusion as Cotton refines the Hail VDS format.  He would like a one to one correspondence of FORMAT headers and emitted annotations.

**Comment by cmnbroad** [comment]
Some things consider: htsjdk has code that [normalizes/standardizes](https://github.com/samtools/htsjdk/blob/fbba5364e1809de071bc479f30e4e2c8b17f5bbe/src/main/java/htsjdk/variant/vcf/VCFStandardHeaderLines.java#L150-L203) select known header lines. One of these is AD. So in this particular case, when it reads in a header containing this:

    `##FORMAT=<ID=AD,Number=R,Type=Integer,Description="AD">`

it will turn it in to the standardized version:

    `##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">`

But not all header mutation code paths do this, and not all header lines are repaired. Its quite possible to read/create a header with two lines of a given type (FORMAT/INFO) with the same ID, but different attributes, and htsjdk will retain both (though the spec precludes this). The header query APIs (say, getFormatHeaderLines()) would only return one, but both will be serialized on write.

We have a large htsjdk [PR](https://github.com/samtools/htsjdk/pull/835) to fix a bunch of VCF header bugs, including the duplicate header line issue, though its pretty old and stale at this point. This might be additional incentive to revive that.

**Comment by ldgauthier** [comment]
I'm all in favor of htsjdk fixes.  I can help review the PR if that will speed things along.

While I gave AD as an example (and it does have its own unusual behavior), the real issue is that GenomicsDB is modifying all the FORMAT and INFO annotations in the input header. I would like GenomicsDB to be able to pass the annotation definitions in the header without modification.
