### ISSUE TITLE
Ensure VQSR QC plotting is robust to dbsnp version

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#385]
In GATK3, the VQSR tools have specific expectations for novel Ti/Tv that are based on what was known at the time before the 1000 Genomes project results were added to dbsnp. If you use the corresponding "old" dbsnp version, the expectations are fulfilled and your QC plots come out looking shiny. If you use a more recent version, key assumptions break down and it screws up the VQSR's QC routines (which produce the plots).

Would be good to be able to handle whatever version of dbsnp users use. 

This Issue was generated from your [forums](http://gatkforums.broadinstitute.org/discussion/comment/20493#Comment_20493)

**Comment by akiezun** [comment]
@vdauwera please enter a specific test case that fails on GATK3 and you want to work on GATK4. ok to include links to broad-only files for now.

**Comment by ldgauthier** [comment]
I'm closing this, but we can reopen if there's a test case.
