### ISSUE TITLE
SVIntervalTree.isUpstreamOf seems to do the opposite to what the name implies.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#3852]
As it is now 

```x.isUpstreamOf(y)```

is true iff ```y``` has a larger contig index or it comes later in the same contig (```y.start >= x.end``` {open end interval}).

It seems that the name of this method seems to be misleading as the natural interpretation of the line of code above is that ```x``` is in upstream of/from ```y```.

In the end this is a matter of opinion though, what do you think?

**Comment by tedsharpe** [comment]
I'm probably being dense, but I don't understand the issue.  I'm thinking of the genome as a stream.  The headwaters are at the 5' end of chromosome 1, and the stream's outlet is at the 3' end of the last chromosome.  So, in this analogy, x *is* upstream of y if y has a larger contig index or starts later than x ends.  Is there some other metaphor that I'm overlooking that leads to confusion?
https://en.wikipedia.org/wiki/Upstream_and_downstream_(DNA)

**Comment by vruano** [comment]
Oops I guess I was the dense here... my under-diagnosed dyslexia :P
