### ISSUE TITLE
Funcotator - Benchmark it and compare to Oncotator

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#3857]

**Comment by jonn-smith** [comment]
Ran some comparisons between funcotator and oncotator using the following data sources against a set of 46 variants (see attached):
- achilles
- cancer_gene_census
- clinvar
- cosmic
- cosmic_fusion
- cosmic_tissue
- dna_repair_genes
- familial
- gencode
- gencode_xhgnc (Only Funcotator had this data source)
- gencode_xrefseq
- hgnc
- oreganno
- simple_uniprot

While the details of the results were not compared between the two tools (unit tests are designed to do this comparison), the tools runtimes were captured (using the BSD `time` utility) over 10 iterations of annotating this data set (VCF->VCF).




Full results set is attached, but the long and short of it is that depending on which timing you count by (real/user/system/user+system) **Funcotator is faster than Oncotator by anywhere from 8 to 57 percent**.

I have attached the timing measurements, as well as a gzip containing the inputs and the script I used to collect the timing information.
[benchmarking_funcotator_oncotator.tar.gz](https://github.com/broadinstitute/gatk/files/1601085/benchmarking_funcotator_oncotator.tar.gz)


[BENCHMARK_funcotator_oncotator.xlsx](https://github.com/broadinstitute/gatk/files/1601079/BENCHMARK_funcotator_oncotator.xlsx)

**Comment by LeeTL1220** [comment]
@jonn-smith Excellent!  Thanks so much for doing this.  This is great.

**Comment by LeeTL1220** [comment]
@droazen @jonn-smith I'm leaving it to one/both of you to close this issue.

**Comment by jonn-smith** [comment]
Closing issue.  This is primarily here to keep a record of how things stack up.
