### ISSUE TITLE
gatk jenkins is inaccessible

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3862]
If I try to navigate to https://gatk-jenkins.broadinstitute.org/ I get:

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server

Apache Server at gatk-jenkins.broadinstitute.org Port 443
```

**Comment by lbergelson** [comment]
@davidbernick gatk-jenkins seems to be inaccessible right now.  Any chance you could take a look at it?

**Comment by davidbernick** [comment]
It's up now. Looks like it might have been down for a month! I'll set up an alert on it (we are not actively monitoring non-Prod machines).

**Comment by davidbernick** [comment]
I think it's okay now.
