### ISSUE TITLE
get read depth per base using source code

### ISSUE THREAD

**Issue by jiadong324** [broadinstitute/gatk#3881]
I am trying to use GATK source code to get read depth at a base, what should I do? 

As far as I know, there is a simpleInterval class I can use to pass the genome region I want to inspect. But I don't know where should I pass the simpleInterval and get the read depth.

Thanks!

**Comment by lbergelson** [comment]
It's not exactly clear what you're trying to do here.  Are you trying to write a new tool that just gets the per base read depth?  If that's what you want to do you would start by implementing a new `LocusWalker`.  In the `apply` method you implement you can check `alignmentContext.size()` to get the pileup depth at each locus.

**Comment by jiadong324** [comment]
@lbergelson Thanks for your answer. I am implementing some algorithm for research purpose. And per base read depth is a value I want to use. I've already figure out a way to calculate.

**Comment by lbergelson** [comment]
@jiadong324 👍
