### ISSUE TITLE
Delete old CNV tools.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#3887]
These can almost definitely go:
CalculatePulldownPhasePosteriors
PerformAlleleFractionSegmentation
PerformCopyRatioSegmentation
PerformJointSegmentation
XHMMSegmentCaller
XHMMSegmentGenotyper

@mbabadi will touch base with Monkol, but we think these can go:
TargetCoverageSexGenotyper
GermlineCNVCaller

Not sure about these germline validation tools, let me know:
ConvertGSVariantsToSegments
EvaluateCopyNumberTriStateCalls

**Comment by samuelklee** [comment]
@mbabadi @MartonKN @asmirnov239 Here's the list of tools for deletion.  Go ahead and assign yourselves to others for docs duty, starting with our own.

**Comment by samuelklee** [comment]
@mbabadi Can you let me know about the validation tools today?

**Comment by mbabadi** [comment]
@samuelklee just wrote to Monkol.
