### ISSUE TITLE
Rename FASTA test files?

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#3904]
Are some of the FASTA test files misnamed?  For example, src/test/resources/large/human_g1k_v37.20.21.fasta seems to only include chr20, but the associated dict and fai include chr21 as well.  Is this intentional?

**Comment by lbergelson** [comment]
seriously?  that seems really wrong. we have a ton of tests that rely on that file too...

**Comment by lbergelson** [comment]
My copy has 20 and 21.  They're just `20` and `21`, not `chr20` and `chr21`, maybe that messed up your search?

**Comment by samuelklee** [comment]
I’m an idiot.  You’re correct.
