### ISSUE TITLE
Shrink the docker image

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3929]
Our docker image is too big.  Make it smaller.

![image](https://user-images.githubusercontent.com/4700332/33681285-15ff286c-da92-11e7-8389-da2171a3a862.png)

relates too #2720

**Comment by droazen** [comment]
In particular, we should not package the full clone of our repo in the docker image (and instead mount it externally during tests).

**Comment by droazen** [comment]
Closing -- dupe of https://github.com/broadinstitute/gatk/issues/3930
