### ISSUE TITLE
Spark and deploy-mode

### ISSUE THREAD

**Issue by AxVE** [broadinstitute/gatk#3933]
Hi,
Currently, using spark tools, we can set the runner and master using --sparkRunner and sparkMaster.
However, there is not similar parameter to set the deploy-mode so we have to manually set it using --conf.
For example , the following parameters are currently used in the command-line to run on a yarn+cluster spark environment : 
`--sparkRunner SPARK --sparkMaster yarn --conf 'spark.submit.deployMode=cluster'`
It's not very user-friendly, a sparkDeployMode parameter could be usefull :
`--sparkRunner SPARK --sparkMaster yarn --sparkDeployMode cluster`

**Comment by lbergelson** [comment]
@AxVE Have you tried using `--deploy-mode client`?  That's the standard spark-submit option to set deploy-mode, we should passing any unknown spark options directly on to spark submit when using `--sparkRunner SPARK`. 

It looks like it won't work when using `--sparkRunner GCS` because it's not in our table of things we translate for GCS, so we should that.

**Comment by AxVE** [comment]
@lbergelson In fact, `--deploy-mode cluster` is the first things I tried. It does not matter where I put it nor if I set either to cluster or client, I always got the following error : 

> ***********************************************************************
> 
> A USER ERROR has occurred: deploy-mode is not a recognized option
> 
> ***********************************************************************
> org.broadinstitute.barclay.argparser.CommandLineException: deploy-mode is not a recognized option
> 	at org.broadinstitute.barclay.argparser.CommandLineArgumentParser.parseArguments(CommandLineArgumentParser.java:384)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.parseArgs(CommandLineProgram.java:217)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:191)
> 	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:137)
> 	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:158)
> 	at org.broadinstitute.hellbender.Main.main(Main.java:239)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:733)
> 	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:177)
> 	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:202)
> 	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:116)
> 	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Actually, I just re-checked and i'm not sure my solution `--conf 'spark.submit.deployMode=cluster'` works well. I'm currently testing it.

My current command is:
> /home/axverdier/Tools/GATK4/gatk-4.beta.6/gatk-launch CountReadsSpark --programName gatk4-testing --input hdfs://spark01:7222/user/axverdier/data/710-PE-G1.bam --output hdfs://spark01:7222/user/axverdier/testOutGATK_CountReadsSpark --sparkRunner SPARK --sparkMaster yarn --conf 'spark.submit.deployMode=cluster' --javaOptions -Dmapr.library.flatclass

I need the `-Dmapr.library.flatclass` because our spark is using a mapr filesystem and I was getting error about JNI library linkage.
However, the paths of files are given with `hdfs://spark01:7222` because I get a protocol error when I set `maprfs://` instead. Don't bother with it right now, I'm going to open another issue about it :)

**Comment by lbergelson** [comment]
I think the issue might be that you need a ` -- ` between the gatk options on the left, and the spark specific options on the right.  This is a confusing artifact of hour our arg parsing works and the fact thatthe gatk-launch script needs a way of finding the spark options but doesn't have access to our java parser.  (we're planning on fixing that in the near future, but no good time line)  

Could you try:
```
/home/axverdier/Tools/GATK4/gatk-4.beta.6/gatk-launch CountReadsSpark --programName gatk4-testing --input hdfs://spark01:7222/user/axverdier/data/710-PE-G1.bam --output hdfs://spark01:7222/user/axverdier/testOutGATK_CountReadsSpark  --javaOptions -Dmapr.library.flatclass -- --sparkRunner SPARK --sparkMaster yarn --deploy-mode cluster
```

**Comment by AxVE** [comment]
Hi,
I tried your commands (and many adaptions / changements) but I always get the same problem:
If the command line includes `--`, I get the JNI linkage error as if the spark related parameters were not parsed.
I tried many things, as:
> /home/axverdier/Tools/GATK4/gatk-4.beta.6/gatk-launch CountReadsSpark --programName gatk4-testing --input hdfs://spark01:7222/user/axverdier/data/710-PE-G1.bam --output hdfs://spark01:7222/user/axverdier/testOutGATK_CountReadsSpark  --javaOptions -Dmapr.library.flatclass -- --sparkRunner SPARK --sparkMaster yarn --deploy-mode cluster
> /home/axverdier/Tools/GATK4/gatk-4.beta.6/gatk-launch CountReadsSpark --programName gatk4-testing --input hdfs://spark01:7222/user/axverdier/data/710-PE-G1.bam --output hdfs://spark01:7222/user/axverdier/testOutGATK_CountReadsSpark  --javaOptions -Dmapr.library.flatclass --sparkRunner SPARK --sparkMaster yarn  -- --master yarn --deploy-mode cluster
> /home/axverdier/Tools/GATK4/gatk-4.beta.6/gatk-launch CountReadsSpark --programName gatk4-testing --input hdfs://spark01:7222/user/axverdier/data/710-PE-G1.bam --output hdfs://spark01:7222/user/axverdier/testOutGATK_CountReadsSpark  --javaOptions -Dmapr.library.flatclass --sparkRunner SPARK --sparkMaster yarn  -- --master yarn --deploy-mode cluster --conf spark.driver.extraJavaOptions='-Dmapr.library.flatclass' --conf spark.executor.extraJavaOptions='-Dmapr.library.flatclass'
> /home/axverdier/Tools/GATK4/gatk-4.beta.6/gatk-launch CountReadsSpark --programName gatk4-testing --input hdfs://spark01:7222/user/axverdier/data/710-PE-G1.bam --output hdfs://spark01:7222/user/axverdier/testOutGATK_CountReadsSpark  --javaOptions -Dmapr.library.flatclass --sparkRunner SPARK --sparkMaster yarn  -- --master yarn --deploy-mode cluster --driver-java-options '-Dmapr.library.flatclass'
It's a non-exhaustive list, I tried a lot of configurations similar to these ones.

**Comment by lbergelson** [comment]
Interesting.  Sorry this is causing so much trouble.  From one of your above comments I wasn't clear if the solution using `--conf 'spark.submit.deployMode=cluster'` work correctly or not.  

Is it possible that it's correct behavior for it to fail with the linkage error?  According to the [mapr doc](https://maprdocs.mapr.com/52/DevelopmentGuide/c-loading-mapr-native-library.html) that command causes it to expect the application to load the library itself, but GATK by default doesn't have a copy of MAPR and won't load it on it's own.  Have you included the mapr library somehow into the gatk jar?  Or is it provided to spark some other way?  I don't really know how maprfs works and how it interacts with hadoop paths.

**Comment by AxVE** [comment]
In fact, setting the deploy-mode works with manual jobs as we get logs in our Hadoop monitor ( the tool to monitor the jobs on the spark cluster ) and directly on our console if deploy-mode is not set / set to client. Both `--deploy-mode` and `--conf 'spark.submit.deployMode=cluster'`.

But with GATK, logs appear directly on my console and not in the Hadoop monitor even if we set with   `--conf 'spark.submit.deployMode=cluster`. The other methods `--deploy-mode` and `-- --deploy-mode` having the said problems.
About the `-- --deploy-mode` and the JNI linkage error, I'm currently checking this.
All our Spark nodes have access to the mapr libraries from `/opt/mapr/...`.

**Comment by AxVE** [comment]
Hi,
Copying and running the `spark-submit` command run by gatk-launch, I found out the parameter `spark.driver.userClassPathFirst` is set to true, and if I set to false it runs well (well, my job has an error but because of my data ^^).
Here, my command which works:
> spark-submit --master yarn \
> --conf 'spark.driver.userClassPathFirst=false' --conf 'spark.io.compression.codec=lzf' --conf 'spark.driver.maxResultSize=0' --conf 'spark.executor.extraJavaOptions="-DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=false -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1"' \
> --conf 'spark.driver.extraJavaOptions="-DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=false -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1"' \
> --conf 'spark.kryoserializer.buffer.max=512m' --conf 'spark.yarn.executor.memoryOverhead=600' \
> --conf 'spark.submit.deployMode=cluster' \
> /home/axverdier/Tools/GATK4/gatk-4.beta.6/gatk-package-4.beta.6-spark.jar BwaSpark --programName gatk4-bwa-test --input hdfs://spark01:7222/user/axverdier/data/phalstedii/PLHAL710.710.unmappedReads.bam --output hdfs://spark01:7222/user/axverdier/testOutGATK_BWA_BwaSpark.bam --reference hdfs://spark01:7222/user/axverdier/data/phalstedii/Plhal710r1.1.fa

I didn't find out how to override `spark.driver.userClassPathFirst` to false in the gatk-launch command, it seems to be ignored or replaced by true.
