### ISSUE TITLE
CollectFragmentCount requires a new feature: different fragment assignment policies

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk#3938]
The midpoint policy is most useful for WGS data where the coverage is _a priori_ uniform, save for biases. For targetted seq data (WES, gene panels), this policy leads to loss of fragments that are captured by baits at their left and right endpoints: the midpoint of such fragments can lie outside of the capture region. In the absence a better model, the most consistent policy is to find the set of overlapping targets, and associate the fragment to the target with highest overlap. In case of a tie, a deterministic coin flip should break the tie.

Note: this is pretty much a 30m ~1hr feature branch on the top of `CollectFragmentCounts` tool. The infrastructure is already there. One just needs to add `getFragmentInterval` to `ReadOrientation` (in addition to `getFragmentCenter`) + an extra CLI argument to set the fragment counting policy.

**Comment by samuelklee** [comment]
See #4551.
