### ISSUE TITLE
ReferenceBases assumes that the ReferenceContext has its Window set to 10

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#3944]
The Annotation ReferenceBases currently crashes with an `ArrayIndexOutOfBoundsException` unless the ReferenceContext has had its window set to 10, `Line 44 final String localBases = allBases.substring(basesToDiscardInFront, basesToDiscardInFront + 2 * NUM_BASES_ON_EITHER_SIDE);` appears to be the culprit, as basesToDiscardInFront doesn't account for bases in the back. Unfortunately it is dangerous to edit the ReferenceContext here so we should decide what the proper behavior should be if the reference context is small.

**Comment by davidbenjamin** [comment]
@takutosato did you fix this in #5151?

**Comment by takutosato** [comment]
@davidbenjamin I think so, but I didn't test beyond the cases at the ends of chromosomes so it's possible that I didn't fix it completely. 

I can come back to this after I review your adaptive pruning PR

**Comment by davidbenjamin** [comment]
@takutosato To be clear, this issue is from a year ago, and I'm just confirming that we can close it.  This is not new bug behavior.  No action required on your part besides what you just said.
