### ISSUE TITLE
Cannot access pull request for Owner configuration

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#3945]
I would like to have a look to #3447 and review it because it is quite important for downstream projects. But GitHub just show a fancy unicorn saying that "This page is taking way too long to load". 

I wonder if this is a problem only for me, and if something can be done to be able to review before accepting it. Do you have any idea of why this is happening? @droazen or @jonn-smith, could you help me here? I would like to review before it gets in, for have minimal effects in downstream projects like mine...

**Comment by lbergelson** [comment]
It's a problem for all of us.  We broke github with to many reviews.

**Comment by magicDGS** [comment]
Thanks @lbergelson - so what's the plan there?

**Comment by droazen** [comment]
We've filed a ticket with github support -- however, the branch has been cleared to merge in its current state, as it's had more than enough reviews. We can file tickets to improve/refactor once it's in master.

**Comment by lbergelson** [comment]
closing this since it's no longer relevant
