### ISSUE TITLE
GetPileupSummaries silently fails if AF isn't present in the VCF?

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/gatk#3955]
After banging my head on GetPileupSummaries for a bit, I think I've figured out a problem with the tool: it assumes that the AF INFO annotation is always present in an input VCF.  There are several ways that it could proceed with a record/VCF that doesn't have AF, but the way it currently does (silently skip all of those records) is not a good one.  I had zero indication as to why the output was empty.
FWIW, I would suggest doing the following:
1. Warn the user the first time it encounters a record with no AF that such a record will be ignored.
2. If no records contain AF then throw a User error at the end of the traversal.
3. Provide an option to the tool that tells it to assume that the AF is less than 0.2 if not present.

We should probably fix this before the release.

**Comment by davidbenjamin** [comment]
I can also check the vcf header for the AF field before traversal.  I realize that the header could have AF without it being present in any record, but it seems like a useful check.

**Comment by davidbenjamin** [comment]
> Provide an option to the tool that tells it to assume that the AF is less than 0.2 if not present.

Are you using this tool for something other than `CalculateContamination`?  If not, there's no use for a record without an AF.

**Comment by eitanbanks** [comment]
Yes, I needed it for CalculateContamination.  And there are definitely cases in which you have a record without an AF, since I hit one just this morning...  :)

**Comment by davidbenjamin** [comment]
I meant that `CalculateContamination` needs the allele frequency, so if we don't have AF for a site I wouldn't want `GetPileupSummaries` to emit it with a made-up value.

**Comment by davidbenjamin** [comment]
For example, if you say that a missing AF is 0.2 when it's actually 0.01, your contamination will be off by about 20%.

**Comment by eitanbanks** [comment]
Then definitely have this tool fail with a clear explanation if there's no AF.

**Comment by davidbenjamin** [comment]
I can do that.

**Comment by davidbenjamin** [comment]
Closed by #3966.
