### ISSUE TITLE
Funcotator - Add in an abstraction above GencodeFuncotation

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#3958]
In order to support ENSEMBL, we need to create an abstraction above `GencodeFuncotation` that can hold both `EnsemblFuncotations` and `GencodeFuncotations`

This will become important when want to support other organisms (these use regular ENSEMBL, not GENCODE). 

Possible name: `TranscriptFuncotation`.

**Comment by droazen** [comment]
This is done!
