### ISSUE TITLE
VariantRecalibrator should use argument collections

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#3963]
VariantRecalibrator currently uses annotations but is not related with the annotations framework despite having annotations relatated arguments, namely the "-an" arguments. These should probably be changed to "-A" for consistency sake.  Furthermore, an argument collection for arguments related to "tranches-file" should probably be extracted as well as they are used in several places.

**Comment by ldgauthier** [comment]
VariantRecalibrator applies an annotation (VQSLOD and possibly also AS_VQSLOD), but the `-an` are annotations it reads.  Note sure that I agree that those should go to `-A`, since that's what we currently use for writing annotations.

**Comment by davidbenjamin** [comment]
@ldgauthier Think we can close this one?

**Comment by ldgauthier** [comment]
There are still over 900 open issues and I'm not going to get to this anytime soon.  I'm in favor of closing it.
