### ISSUE TITLE
Mutect2 WDLs don't use gatk launcher script

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3967]
The M2 WDLs don't use the standard gatk launcher script, which results in important system properties not being set.  Assigning to @davidbenjamin and @LeeTL1220 to fix in time for the 4.0 release.

Note that `gatk-launch` is being renamed to `gatk` in https://github.com/broadinstitute/gatk/pull/3961, so you'll want to wait until that PR is merged (should be merged today).

**Comment by droazen** [comment]
The change that needs to happen is trivial: 

* Ensure that the `gatk` script is in the same directory as the GATK jar
* Ensure that the GATK jar has its original name as created during the gradle build (ending in `local.jar` or `spark.jar`)
* Change all instances of `java -Xmx4g -jar ${gatk_jar} ToolName` to `./gatk --javaOptions "-Xmx4g" ToolName` (or `/path/to/gatk` instead of `./gatk`)

**Comment by davidbenjamin** [comment]
@droazen Does this mean that the `gatk` script needs to be a wdl `File` input in order to localize it?

**Comment by droazen** [comment]
@davidbenjamin No, it should be in the docker image (and it is in the standard docker images we publish).

**Comment by droazen** [comment]
See https://github.com/broadinstitute/dsde-pipelines/blob/develop/genomes_in_the_cloud/joint_genotyping_workflow/JointGenotypingWf.wdl for an example, and also the comments to https://github.com/broadinstitute/gatk/issues/3968
