### ISSUE TITLE
CNV WDLs don't use the gatk launcher script

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#3968]
The CNV WDLs don't use the standard gatk launcher script, which results in important system properties not being set.  Assigning to @samuelklee  and @LeeTL1220 to fix in time for the 4.0 release.

Note that `gatk-launch` is being renamed to `gatk` in https://github.com/broadinstitute/gatk/pull/3961, so you'll want to wait until that PR is merged (should be merged today).

**Comment by droazen** [comment]
The change that needs to happen is trivial: 

* Ensure that the `gatk` script is in the same directory as the GATK jar
* Ensure that the GATK jar has its original name as created during the gradle build (ending in `local.jar` or `spark.jar`)
* Change all instances of `java -Xmx4g -jar ${gatk_jar} ToolName` to `./gatk --javaOptions "-Xmx4g" ToolName` (or `/path/to/gatk` instead of `./gatk`)

**Comment by samuelklee** [comment]
@LeeTL1220 @davidbenjamin Can we coordinate one person to do this across CNV and M2 WDLs?

@droazen I think it might be slightly more complicated than that, given that we have a `gatk4_jar_override` parameter.  Can we do the same thing by setting `GATK_LOCAL_JAR_ENV_VARIABLE`?

**Comment by droazen** [comment]
@samuelklee Yes, setting the `GATK_LOCAL_JAR` and/or `GATK_SPARK_JAR` environment variables will cause the gatk script to use that jar, instead of looking in its directory for a jar. The naming of the jar itself also doesn't matter if you use the environment variable method.

**Comment by samuelklee** [comment]
OK, great.  @LeeTL1220 @davidbenjamin Let's coordinate.  Might make sense to hold off until Cromwell 30 changes are in, but I'll let you guys decide.

**Comment by davidbenjamin** [comment]
> Yes, setting the GATK_LOCAL_JAR and/or GATK_SPARK_JAR environment variables will cause the gatk script to use that jar, instead of looking in its directory for a jar. The naming of the jar itself also doesn't matter if you use the environment variable method.

@droazen I think this leaves one more question: what about running locally?  Since cromwell doesn't take in the docker image in that case (right?) wouldn't we need to pass in a pass to the gatk script?

**Comment by samuelklee** [comment]
@LeeTL1220 @davidbenjamin When should we make these changes?  I think the gCNV branch (#3925), which also contains WDL, needs to get merged first.  We're aiming to get this done by Friday, will that leave enough time?

**Comment by samuelklee** [comment]
@droazen I think there is still the open question of running the WDL locally.  In my opinion, it's OK to assume that gatk is in the PATH.

**Comment by droazen** [comment]
@samuelklee I think assuming that `gatk` in the PATH is the right thing to do for local runs.

**Comment by droazen** [comment]
And obviously you guys are going to want to wait for the merge of https://github.com/broadinstitute/gatk/pull/3961 later today.

**Comment by samuelklee** [comment]
OK, great.  And yup, that's what reminded me!
