### ISSUE TITLE
RecalibrationArgumentColleciton arguments need to be refactored to new standard

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#3974]
Most of the arguments in RecalibrationArgumentCollection are in the form "mismatches_context_size". This probably needs to be updated but it will have the consequence of invalidating existing BaseRecalibrator report tables and require the arguments get changed in all of the report tables checked in as test files.

**Comment by davidbenjamin** [comment]
@jamesemery Looks like this has been done.  Re-open if I'm wrong.
