### ISSUE TITLE
Expose or hide all task-level parameters in CNV WDLs consistently.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#3980]
Somatic WDLs have them hidden, gCNV WDLs (in sl_gcnv_ploidy_cli) have them exposed.  (EDIT: Actually, gCNV WDLs only have them exposed for gCNV-specific tasks.  Common tasks such as PreprocessIntervals are also not exposed.)

The former makes for cleaner `wdltool inputs` JSONs that contain only the bare minimum inputs, but it is unclear whether FC will allow for task-level parameters to be set.  However, this can still be done via JSON, as long as the task is at the main workflow level (although this may change with a C30 hotfix?)

The latter makes for messier JSONs and requires more upkeep to make sure everything stays exposed, but should work in FC (unless the workflow is used as a subworkflow?)

**Comment by samuelklee** [comment]
@LeeTL1220 @katevoss @ruchim I started exposing all optional task-level parameters in the somatic workflows so that they could be specified via json when the workflows are used as subworkflows.  E.g., `CNVSomaticPanelWorkflow.PreprocessIntervals.bin_length` is an optional task-level parameter that can be specified properly via json when `CNVSomaticPanelWorkflow` is the top-level workflow, but not when `CNVSomaticPanelWorkflow` is used as a subworkflow.  This is because `MetaWorkflow.CNVSomaticPanelWorkflow.PreprocessIntervals.bin_length` cannot be set, correct?

However, things quickly became very messy.  For example, alongside parameters like `bin_length` which are unique to the PreprocessIntervals task, we also have a lot of optional runtime parameters that are named generic things like `mem` which are not.  So to expose these, we'd have to have workflow-level parameters with names like `preprocess_intervals_mem`, etc.  It seems like this is exactly the problem the expected functionality would solve, if only it worked past the subworkflow level and the namespace is propagated as one would expect.  Requiring that these be exposed also partially obviates the reason for having optional task-level arguments in the first place---what's the point of having them be optional if I have to add lines of code to expose all of them at the workflow level?

So again, I'm strongly against exposing all inputs for a particular workflow on the off-chance that that workflow might be used as a subworkflow.  This adds a lot of unnecessary boilerplate that quickly gets very messy.  I think that this problem should instead be solved by properly bubbling up all inputs, optional or required, at all levels.

Anyway, I'm not going to try to tackle this before release, which I think was OK with @LeeTL1220.  However, after release, I'd be happy to sit down and discuss how we want to do this sort of thing going forward.

**Comment by LeeTL1220** [comment]
@samuelklee Can we just expose `bin_length` since it determines what is WGS vs. Exome?  Punt the rest?

**Comment by samuelklee** [comment]
I thought we agreed to leave it unless Intel needed to wrap the current workflows as subworkflows?  Remember that things like `CNVSomaticPanelWorkflow.PreprocessIntervals.bin_length` can still be set.  Not sure how this is looks on FireCloud at the moment, but unless it doesn't show up there even when the workflow is top level (in which case, I really don't understand the point of optional parameters), then let's leave it.

**Comment by LeeTL1220** [comment]
@samuelklee My apologies, yes we did.  Ignore previous comment.
