### ISSUE TITLE
Restore PadTargets padding/merging behavior to PreprocessIntervals.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#3981]
Currently in master, intervals from the IAC that have been modified by the engine are further padded, overlapping intervals are merged, and bins are created.  WES should be run by specifying bin_length = 0, and the total number of intervals (targets, in this case) should remain fixed.  However, current behavior does not prevent intervals that overlap after padding from being merged.

Note also that in sl_gcnv_ploidy_cli, bins that contain only Ns are also dropped.

We should add validation of the IAC to check for minimal modification by the engine (as is done by other CNV CLIs), and then pad without introducing overlaps or merging if bin_length = 0.  If bin length != 0, then the current behavior is fine (since it is conceivable that one might want to bin when running WES).

**Comment by samuelklee** [comment]
@LeeTL1220 Not sure if you will absolutely need this for HCC1143 WES validation, but just be aware that this change is coming soon.

**Comment by LeeTL1220** [comment]
Sure.  Sounds good that it will be fixed.  I doubt that it will affect results too much.
