### ISSUE TITLE
Somatic CNV WDL needs to support tumor-only mode where no matched normal is available.

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#3983]

**Comment by LeeTL1220** [comment]
Maybe rename the WDL to case workflow instead of pair? 

Does this now require a separate WDL file?  Or can we use optional parameters as we had previously?

**Comment by samuelklee** [comment]
What does FC need?  And what naming convention makes most sense in the FC context, i.e., is a tumor-only sample represented as a `case` or as a `pair` with no normal?

**Comment by LeeTL1220** [comment]
FC was fine with previous model of having normal input bams/bais be optional parameters.

I don't think FC would let you do a pair missing a sample.  Typically, in FC, you would create two method configurations, one for tumor-only and one for pair.  Then the former would be run on samples and the latter run on pairs.

**Comment by LeeTL1220** [comment]
Isn't this a dupe of #3940 ?

**Comment by samuelklee** [comment]
Yup.  Adding the note here to fill in some cost optimizations for some of the common tasks.

**Comment by samuelklee** [comment]
@LeeTL1220 Can we clarify what is needed for FC?  If this is as simple as making the normal optional in the pair WDL, let's just do that.  @sooheelee take note.

**Comment by samuelklee** [comment]
A reminder: we can also make the PoN optional.

One thought: if users want to run ModelSegments for germline, what should they do?  Presumably they could run the pair WDL in "tumor-only" mode and just use the normal as input.  So maybe we should change all instances of "tumor" to "case" and "normal" to "matched_normal"?  Or is this still too confusing?  I'd like to avoid having separate case and pair WDLs if possible.

**Comment by samuelklee** [comment]
By the way, I thought @vdauwera was opposed to using optional inputs in this way at some point (see #3657).  Was that question ever decided?  (I'm still of the opinion that they *should* be used in this way, but this is one of the reasons I didn't for this iteration of the WDL.)

To be clear, the pair WDL right now does not allow all of the workflow paths (tumor-only, no PoN, etc.) that the new tools make possible.  It only allows the one that we will most likely run in production (matched-normal + PoN).

**Comment by LeeTL1220** [comment]
Originally,  we just had the normal be optional.   You also had automated tests in the WDL Travis. 

In FC, for tumor only,  you would probably want a separate method configuration that ran on sample entity type.   I'm open to other suggestions,  but I can't think of another way.   This could in theory be used for germline calling, too.

**Comment by LeeTL1220** [comment]
Note separate method configuration, but uses the same WDL.
