### ISSUE TITLE
investigate use of spark-bam to improve spark bam reading

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#3993]
There's a new [small library for bam reading](https://github.com/hammerlab/spark-bam) from hammer lab that is designed to fix problems in the bam splitting.  It sounds promising from they've posted.  We've been patching these problems in a very ad-hoc way as we discover them, but they've done a systematic survey to identify them.  They also claim it's substantially faster.  It's currently missing some important features, like selecting by interval.  
We should investigate if they're performance gains bear out in pratice, and if so if:
1.  We want to use the new library for bam reading
2.  We want to back port their changes to hadoop-bam

**Comment by tomwhite** [comment]
We have Disq now, see #5138.
