### ISSUE TITLE
Generate new resources for CNV WDL tests.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#4007]
It's a little confusing that we use downsampled tumor BAMs for the gCNV WDL tests, for example.  Can wait until after release.

**Comment by samuelklee** [comment]
@LeeTL1220 We'll keep you updated here.  Should be quick, but I want @asmirnov239 to finish up #4113 first.

I think if we can point @asmirnov239 to a few public germline BAMs to use for building both gCNV and ModelSegments PoNs, and we can continue using HCC1143 for the tumor.

**Comment by LeeTL1220** [comment]
FYI.... @ruchim is going to use full size bams for the examples in FC.  If she changes her mind and wants to go back to the downsampled chr20 versions, she can comment here.

**Comment by samuelklee** [comment]
OK.  I think that probably makes more sense.  I don't think we should use Travis test data as FC example data in general, as I'd want the latter to be able to showcase the workflows more realistically.

**Comment by asmirnov239** [comment]
To generate PostprocessGermlineCNVCallsIntegrationTest test data - run gCNV on coverage files located in `gatk/src/test/resources/org/broadinstitute/hellbender/tools/copynumber/gcnv-sim-data/`
and ploidy calls in `
gatk/src/test/resources/org/broadinstitute/hellbender/tools/copynumber/gcnv-sim-data/contig-ploidy-calls/`

**Comment by samuelklee** [comment]
Just noting here that I saw a lot of intermittent 60-minute Travis timeouts for the gCNV case mode WDL tests in #7411. I'm pretty sure that at some point we were running cohort + case together, so not sure why case alone is now hitting the limit. So might be worth investigating and tightening up the tests/data. Also note @ldgauthier's concerns about using a fake dictionary in the simulated data in #6957.
