### ISSUE TITLE
Mapping quality threshold in GetPileupSummaries needs to be modifiable 

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/gatk#4011]
The MAPPING_QUALITY_THRESHOLD for GetPileupSummaries is hard coded at 50, but that's not documented anywhere -- and really is only good for BWA aligned reads.  There are other mappers that are more spread in their mapping qualities and we lose so many reads.

Instead, please change this tool so that MAPPING_QUALITY_THRESHOLD is a command-line argument (and it's fine to have it set to 50 by default).

Thanks!

**Comment by eitanbanks** [comment]
@davidbenjamin are you the right person for this?

**Comment by samuelklee** [comment]
@davidbenjamin Note that this is not exposed in CollectAllelicCounts either and is set to 30 by default.  Our default set of read filters is also less stringent.  However, we do expose a threshold on minimum base quality.  Just a few more things to consider when we unify the two tools!

**Comment by davidbenjamin** [comment]
@eitanbanks Yes, I will fix this.

**Comment by davidbenjamin** [comment]
@eitanbanks Fixed in #4466.
