### ISSUE TITLE
Mutect2.wdl workflow question 

### ISSUE THREAD

**Issue by dannykwells** [broadinstitute/gatk#4017]
We are in the process of trying to get [The Mutect2 WDL worfkow](https://github.com/broadinstitute/gatk/tree/master/scripts/mutect2_wdl) working. When we run it on an input tsv file, we get the following error on transitioning from Mutect2 to MergeVCFs:

`Unable to evaluate parameters: parameter \"m2_multi.m2.MergeVCFs.input_vcfs-9\" has invalid value:`

This error I think is due to a confusion between a string output and a file output in the Mutect2 call. And in fact, there I see that `File output_vcf = read_string("vcf_name.txt")` - `read_string` is not terribly well documented, but I would guess that it in fact outputs a string, rather than a file. 

I am by no means an expert on WDL, but it does appear that this output might need a fix. Thoughts? (This issue has been seen before btw, [here](https://gatkforums.broadinstitute.org/wdl/discussion/10046/string-vs-file-mistake-caused-cromwell-26-workflow-to-hang), and I just found [this old forum post](https://gatkforums.broadinstitute.org/wdl/discussion/8683/what-is-the-best-way-to-specify-a-file-output-when-the-file-name-is-not-known-ahead-of-the-run) which seems to ask the question too)

**Comment by dannykwells** [comment]
I should clarify, if it matters, that I am running this work flow with a GCP backend.

**Comment by LeeTL1220** [comment]
@dannykwells Fix is in `master`.

The error only occurs in GCP backend.

**Comment by davidbenjamin** [comment]
Closed by #4048, after which all output file names are known before their task starts.

**Comment by dannykwells** [comment]
Great, thanks!
