### ISSUE TITLE
Update doc templates to reflect "Experimental" tag.

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#4033]
The GATK Freemarker templates need to change reflect the new `@Experimental` tag when the [Barclay PR](https://github.com/broadinstitute/barclay/pull/116) is merged and assimilated into GATK.

**Comment by droazen** [comment]
@cmnbroad This one is done, right?

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/4070.
