### ISSUE TITLE
ReadUtils.createCommonSAMWriterFromFactory should accept a reference Path

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4039]
ReadUtils.createCommonSAMWriterFromFactory currently requires a File instead of a path.  Requires a change in htsjdk to have SAMFileWriterFactory.makeWriter() accept the reference as a path.

**Comment by magicDGS** [comment]
There is a PR in that solves the HTSJDK part: https://github.com/samtools/htsjdk/pull/1005 - we just need to reach a consensus about the overloads...
