### ISSUE TITLE
Specifying shortName but not fullName for argument leads to unexpected documentation/behavior?

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#4049]
@cmnbroad @droazen Didn't realize that I accidentally omitted the `fullName` when specifying the sequence-dictionary argument for PlotModeledSegments:

    @Argument(
            doc = PlottingUtils.SEQUENCE_DICTIONARY_DOC_STRING,
            shortName = StandardArgumentDefinitions.SEQUENCE_DICTIONARY_NAME
    )
    private File inputSequenceDictionaryFile;

This works when called in WDL tests using the fullName `--sequenceDictionary` (which is why it slipped by me--I would've thought this should fail):

    java -Xmx${command_mem}m -jar $GATK_JAR PlotModeledSegments \
            --denoised-copy-ratios ${denoised_copy_ratios} \
            --allelic-counts ${het_allelic_counts} \
            --segments ${modeled_segments} \
            --sequence-dictionary ${ref_fasta_dict} \
            --minimum-contig-length ${default="1000000" minimum_contig_length} \
            --output ${output_dir_} \
            --output-prefix ${entity_id}

However, the argument names appear in the documentation as:

    --inputSequenceDictionaryFile,-sequence-dictionary:File

And if the argument is not specified, this gives the error message:

    A USER ERROR has occurred: Argument inputSequenceDictionaryFile was missing: Argument 'inputSequenceDictionaryFile' is required.

Is this intended behavior?  If so, please close, but it seems a little unexpected to me.

**Comment by cmnbroad** [comment]
Yeah, its expected, but admittedly a little weird. The fallback to using field name for longname if one isn't explicitly specified is somewhat rational (Picard heritage), but the parser allows the use of `-` and `--` interchangeably, which results in it accepting `--sequence-dictionary ${ref_fasta_dict}` but complaining about `inputSequenceDictionaryFile`.

**Comment by samuelklee** [comment]
Ah, OK, that makes sense.  Good to know!
