### ISSUE TITLE
Warn about low genotyping quality during contig ploidy determination

### ISSUE THREAD

**Issue by mbabadi** [broadinstitute/gatk#4055]
As mentioned in the tool documentation, `DetermineGermlineContigPloidy` assumes integer contig ploidy states. The presence of mosaic aneuploidy and/or germline partial chromosome loss will result in unreliable results.

- [ ] In the COHORT mode, it is desirable to emit warning messages for (sample, contig) with outlyingly low genotyping quality (GQ) in the population. As it stands, GQs are only written to output contig ploidy tables.

- [ ] In the COHORT mode, it is also desirable to store the distribution of GQs in the ploidy model (see below).

- [ ] In the CASE mode, it is desirable to emit informative warning messages  for (sample, contig) with outlyingly low genotyping quality (GQ) in the population used to generate the ploidy-model parameters.

**Comment by mwalker174** [comment]
Closing this issue for now, but I think this is an important point.

For CNV and SV tools in general, we need to improve QC functionality. Capabilities for visualizing model output, particularly contig ploidy calling where sample quality and mosaicisms could negatively affect CNV calling, are critical. Warnings would be a bare minimum, but in practice I don't think this go far enough, as most of the time these pipelines are run at scale as WDLs, and users don't tend to check log output carefully. It'd be better to have up-front QC to filter out problematic samples before running the model.
