### ISSUE TITLE
new Germline CNV wdl test are too slow, causing travis failures

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4064]
The newly enabled GermlineCNV wdl tests seem to take ~1 hour 8 minutes.  The maximum timeout for our travis jobs is 1 hour 10 minutes.  This is causing random failures.  It's also the slowest of our matrix entry by a large margin which makes our tests even slower than they are.  Can these be speed up?

Alternatively we may need to talk to the travis people and get a special dispensation to increase our job timeouts even farther.

**Comment by samuelklee** [comment]
Yeah I trimmed then down even further in #4061.  Looks like they run about ~40 minutes now.  This is just running a single iteration of gCNV in each of cohort (3 samples) and case mode, which is already kind of the bare minimum (2 tests---in comparison we run 8 such tests on the somatic side).  We might be able to trim down the test data even further (to decrease the number of intervals), but I'm not sure why the tests are so slow on Travis in the first place.  They run much faster locally.

**Comment by samuelklee** [comment]
Note that we can't merge #4061 until we make a decision about how to handle a missing osx64 python dependency.

**Comment by samuelklee** [comment]
Also, I wouldn't worry about talking to the Travis people---this will give us more incentive to keep our tests short, which I think is a good thing...

**Comment by cmnbroad** [comment]
@samuelklee I'm not sure we need to hold up #4061 for the osx issue - those dependencies were introduced in #3925 and are already in master. I don't think #4061 makes them any worse.
