### ISSUE TITLE
gCNV python env fails on mac

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#4074]
#3925 introduced a conda dependency on libgcc-ng=7.2.0, which works in Travis since its available or Ubuntu, but fails to resolve for osx.

Its not clear to me what the options are, but we need to resolve this one way or another.

**Comment by mbabadi** [comment]
@samuelklee @cmnbroad I wonder whether we could get rid of libgcc-ng altogether? it automatically appeared after I installed the main dependencies. For what it's worth, I have a fully working mkl-enabled gcnv python env on my mac!

**Comment by samuelklee** [comment]
@mbabadi Can you try removing libgcc-ng, installing the resulting environment (`./gradlew createPythonPackageArchive; conda env create -n gatk -f scripts/gatkcondaenv.yml`), and then verifying that gcnv runs as intended?  If so, mind creating the PR?

**Comment by ldgauthier** [comment]
@cmnbroad is this still a problem?  Aside from the tensorflow issue (#6325), I had no GCNV Python issues on my mac.

**Comment by cmnbroad** [comment]
If you were able to create the conda env on mac then I assume this is no longer an issue. Closing until/unless someone knows its still an issue.
