### ISSUE TITLE
Consider adding osx to the travis matrix

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#4075]
This would catch things like https://github.com/broadinstitute/gatk/issues/4074, but multiplies the test matrix. https://docs.travis-ci.com/user/multi-os/

**Comment by lbergelson** [comment]
It would have caught #4062 as well... 

This is a duplicate of https://github.com/broadinstitute/gatk/issues/1816

**Comment by cmnbroad** [comment]
Dup of https://github.com/broadinstitute/gatk/issues/1816.
