### ISSUE TITLE
Arebwa function in GATK4

### ISSUE THREAD

**Issue by Sun-shan** [broadinstitute/gatk#4081]
Can GATK4 starts from the fastq file in Spark，not from the bam file ?

**Comment by lbergelson** [comment]
@Sun-shan Currently it has to start with a bam file.  You can use an unmapped bam file and then align it with bwa as part of the spark pipeline, but we can't currently read FASTQ directly.  That's a feature we'd like to consider in the future.

**Comment by lbergelson** [comment]
I opened a new ticket to keep this on our radar #4086

**Comment by magicDGS** [comment]
@Sun-shan - I recently published a simple toolkit, ReadTools, for standardizing formats into an unmapped BAM that follow the specifications, starting from different FASTQ inputs (and others): single-end, pair-end, Illumina-legacy names, Casava read names, etc. Check it out in the [ReadTools documentation page](http://magicdgs.github.io/ReadTools/).
