### ISSUE TITLE
Implement a mechanism to automatically label GCS/NIO enabled arguments as such

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4105]
We need a way to label GCS-enabled arguments as such (ideally an automated/foolproof way).

**Comment by cmnbroad** [comment]
@droazen Is this the same thing as https://github.com/broadinstitute/gatk/issues/3773 ?

**Comment by droazen** [comment]
You're right @cmnbroad -- closing as dupe of https://github.com/broadinstitute/gatk/issues/3773
