### ISSUE TITLE
Multiple GenomicsDBImport commands can't be run concurrently in the same directory?

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#4106]
There was an unverified bug report from a user on the forum:
"I did also run in to a problem with running all of these imports from the same directory.  It creates a .tmp_loader.json file in the directory you kick the imports off from, which is problematic when you kick off 24 imports, one for each chromosome.  This json file seems to specify the location of the GenomicsDB which that job is to write to.  With that file being overwritten each time I kicked off a new import, I got core dumps and jobs writing to the wrong db.  I had specified a unique db for each, but with jobs reading from the same json file, what I had specified on the command line and what the jobs actually did didn't line up.  I ended up creating a separate dir for each chromosome, and kicked each job off from those dirs, which solved the problem."

I haven't tried to reproduce it yet.  I've created multiple GDBs by running commands in the same directory, though only one at a time.  I can't find any .tmp_loader.json files, but they may be deleted on completion.

**Comment by lbergelson** [comment]
This is very believable. I've certainly never tried running multiple in the same directory...

**Comment by kgururaj** [comment]
That sounds like a bad implementation from our side - apologies.

We are working on fully fixing the Protobuf implementation. As part of that task, the temp loader/query JSON files will no longer be created (the vid and callset JSONs will still be needed).

**Comment by droazen** [comment]
Assigning to @kgururaj for a fix.

**Comment by droazen** [comment]
Resolved by https://github.com/broadinstitute/gatk/pull/4261
