### ISSUE TITLE
Error in line 84 cohort_determine_ploidy_and_depth.py

### ISSUE THREAD

**Issue by stefandiederich** [broadinstitute/gatk#4125]
Hi,

I tried to use your new released GATK4 package to do CNV analysis. I know it's a beta tool... I followed the tools documentation and did "CollectFragmentCounts" first to get hdf5 files. After that I tried to run "DetermineGermlineContigPloidy" in cohort mode with these files. I created a ploidy_priors.tsv file like described in the documentation and used 8 hdf5-files. A few seconds after starting the tool I get the following error:

```
[11. Januar 2018 16:42:24 MEZ]
org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy done. Elapsed time: 0.05 minutes.
Runtime.totalMemory()=2294808576
org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException:
python exited with 1
Command Line: python /tmp/die9s/cohort_determine_ploidy_and_depth.9149389425697869853.py --sample_coverage_metadata=/tmp/die9s/samples-by-coverage-per-contig814612566493224652.tsv --output_calls_path=/media/Berechnungen/CNV_analysis/GATK4/normal_cohort-calls --mapping_error_rate=1.000000e-02 --psi_s_scale=1.000000e-04 --mean_bias_sd=1.000000e-02 --psi_j_scale=1.000000e-03 --learning_rate=5.000000e-02 --adamax_beta1=9.000000e-01 --adamax_beta2=9.990000e-01 --log_emission_samples_per_round=2000 --log_emission_sampling_rounds=100 --log_emission_sampling_median_rel_error=5.000000e-04 --max_advi_iter_first_epoch=1000 --max_advi_iter_subsequent_epochs=1000 --min_training_epochs=20 --max_training_epochs=100 --initial_temperature=2.000000e+00 --num_thermal_epochs=20 --convergence_snr_averaging_window=5000 --convergence_snr_trigger_threshold=1.000000e-01 --convergence_snr_countdown_window=10 --max_calling_iters=1 --caller_update_convergence_threshold=1.000000e-03 --caller_admixing_rate=7.500000e-01 --disable_caller=false --disable_sampler=false --disable_annealing=false --interval_list=/tmp/die9s/intervals671187352630642175.tsv --contig_ploidy_prior_table=/media/Berechnungen/CNV_analysis/GATK4/ploidy_priors.tsv --output_model_path=/media/Berechnungen/CNV_analysis/GATK4/normal_cohort-model
Stdout:
Stderr:   File "/tmp/die9s/cohort_determine_ploidy_and_depth.9149389425697869853.py", line 84
    sample_metadata_collection: gcnvkernel.SampleMetadataCollection = gcnvkernel.SampleMetadataCollection()
                              ^
SyntaxError: invalid syntax

        at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)
        at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:151)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:121)
        at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.executeDeterminePloidyAndDepthPythonScript(DetermineGermlineContigPloidy.java:316)
        at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.doWork(DetermineGermlineContigPloidy.java:215)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:275)
```

Have you seen an error like this before? Do you have an idea where it is coming from?

Thanks a lot in advance
Stefan

**Comment by lbergelson** [comment]
@stefandiederich What version of python are you running?  That looks like it's erroring out when it hit's a type annotation, which is a python 3+ feature.  I believe the CNV tools require python 3.6.2+.

**Comment by droazen** [comment]
@mbabadi @samuelklee @cmnbroad It would be good if the Python executor could accept a per-tool required Python version, and throw a nice user exception if the Python version requirements aren't met.

**Comment by cmnbroad** [comment]
@stefandiederich There is a conda environment .yml file called gatkcondaenv.yml that is included with the distribution. It will establish the correct version of Python and other dependencies that are required for the CNV tools. You can find more detail about how to set this up [here](https://github.com/broadinstitute/gatk#requirements).

**Comment by samuelklee** [comment]
@droazen @cmnbroad @mbabadi I generally agree with the sentiments expressed in #4127, except that I think it's OK to require a conda environment (or even use of the Docker) for these particular tools.  How we should validate this requirement is another question.  We can discuss more with @vdauwera.

@stefandiederich Hopefully once you get the conda environment set up you will be able to run the tools.  We would definitely appreciate any feedback you might be able to provide.  Note that the gCNV model is relatively sophisticated, so there may be some parameters (which control the priors for the model as well as how inference is performed) that you will need to adjust for your data.  Depending on the number of intervals/bins you are using and your memory constraints, you may also need to scatter across multiple GermlineCNVCaller runs; see how things are done in the WDLs here: https://github.com/broadinstitute/gatk/tree/master/scripts/cnv_wdl/germline

As you noted, this pipeline is still in beta.  We are currently running several evaluations and hope to soon release some Best Practices recommendations for the aforementioned parameter values that should work well for various data types generated at the Broad.  We will also have some blog or forum posts that explain the new CNV pipelines in more detail coming soon---stay tuned!

**Comment by stefandiederich** [comment]
@cmnbroad Thanks for pointing to the conda environment file. I tried to install load it but the first error it gave me was 
´´´
NoPackagesFoundError: Package missing in current linux-64 channels:
  - intel-openmp 2018.0.0*
´´´´
so I installed this package by hand with ´conda install -c anaconda intel-openmp´ and afterwards tried to install the gatkcondaenv.yml again with ´conda env create -n gatk -f gatkcondaenv.yml´ . Unfortunately  I run into the next error which says:

´´´
root@k-hg-srv1:/BioinfSoftware# conda env create -n gatk -f gatkcondaenv.yml
Using Anaconda API: https://api.anaconda.org
Solving environment: done

Downloading and Extracting Packages
mkl-service 1.1.2: ################################################################################################################################################################################################################## | 100%
libgcc-ng 7.2.0: #################################################################################################################################################################################################################### | 100%
mkl 2018.0.1: ####################################################################################################################################################################################################################### | 100%
intel-openmp 2018.0.0: ############################################################################################################################################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Requirement 'build/gatkPythonPackageArchive.zip' looks like a filename, but the file does not exist
Processing ./build/gatkPythonPackageArchive.zip
Exception:
Traceback (most recent call last):
  File "/BioinfSoftware/Anaconda/envs/gatk/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/BioinfSoftware/Anaconda/envs/gatk/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/BioinfSoftware/Anaconda/envs/gatk/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/BioinfSoftware/Anaconda/envs/gatk/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/BioinfSoftware/Anaconda/envs/gatk/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/BioinfSoftware/Anaconda/envs/gatk/lib/python3.6/site-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/BioinfSoftware/Anaconda/envs/gatk/lib/python3.6/site-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/BioinfSoftware/Anaconda/envs/gatk/lib/python3.6/site-packages/pip/utils/__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/BioinfSoftware/Anaconda/envs/gatk/lib/python3.6/site-packages/pip/utils/__init__.py", line 482, in unzip_file
    zipfp = open(filename, 'rb')
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/BioinfSoftware/build/gatkPythonPackageArchive.zip'

CondaValueError: pip returned an error
´´´

Thanks also to all the other ones for their good hints for using germlineCNV caller.

**Comment by samuelklee** [comment]
@stefandiederich I think we forgot to mention that you need to create the GATK python package using “./gradlew createPythonPackageArchive” before creating the conda environment.  I don’t think you should run into any further issues.

The error with the intel-openmp package was most likely due to your Anaconda/Miniconda installation not being as up to date as the one our Docker image uses.  (Note that using that image to run everything might be another option to consider.)

**Comment by stefandiederich** [comment]
@samuelklee Thanks for yor help. I created the ython package and could set up the conda environment. I activated it and run the command for DetermineGermlineContigPloidy again. Now it`s running :-)

Thanks again for you very quick respons and high quality help! I am realy looking forward to the BestPractice guide for GermlineCNV calling. Thanks to all. 
I will close this issue now.
Stefan

**Comment by sooheelee** [comment]
Do I need to run this Python package in the GATK4.0.4.0 Docker? I am getting a similar error with DetermineGermlineContigPloidy while running within the Docker on a Linux Compute Engine VM.
```
...
19:06:35.948 INFO  DetermineGermlineContigPloidy - Aggregating read-count file /gatk/snail/gcnv_180517/coverage_1k/A19625.hc.soohee1k.hdf5 (24 / 24)
19:06:54.675 INFO  DetermineGermlineContigPloidy - Shutting down engine
[May 18, 2018 7:06:54 PM UTC] org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy done. Elapsed time: 1.83 minutes.
Runtime.totalMemory()=2822242304
org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException: 
python exited with 1
Command Line: python /tmp/root/cohort_determine_ploidy_and_depth.8539868448285133842.py --sample_coverage_metadata=/tmp/root/samples-by-coverage-per-contig3023244219495833390.tsv --output_calls_path=/gatk/snail/gcnv_180517/ploidy/hc24_soohee1k_ploidy-calls --mapping_error_rate=1.000000e-02 --psi_s_scale=1.000000e-04 --mean_bias_sd=1.000000e-02 --psi_j_scale=1.000000e-03 --learning_rate=5.000000e-02 --adamax_beta1=9.000000e-01 --adamax_beta2=9.990000e-01 --log_emission_samples_per_round=2000 --log_emission_sampling_rounds=100 --log_emission_sampling_median_rel_error=5.000000e-04 --max_advi_iter_first_epoch=1000 --max_advi_iter_subsequent_epochs=1000 --min_training_epochs=20 --max_training_epochs=100 --initial_temperature=2.000000e+00 --num_thermal_epochs=20 --convergence_snr_averaging_window=5000 --convergence_snr_trigger_threshold=1.000000e-01 --convergence_snr_countdown_window=10 --max_calling_iters=1 --caller_update_convergence_threshold=1.000000e-03 --caller_admixing_rate=7.500000e-01 --disable_caller=false --disable_sampler=false --disable_annealing=false --interval_list=/tmp/root/intervals3258684972117897378.tsv --contig_ploidy_prior_table=/gatk/snail/gcnv/grch38_germline_CN_priors.tsv --output_model_path=/gatk/snail/gcnv_180517/ploidy/hc24_soohee1k_ploidy-model
Stdout: 
Stderr: Traceback (most recent call last):
  File "/tmp/root/cohort_determine_ploidy_and_depth.8539868448285133842.py", line 78, in <module>
    args.contig_ploidy_prior_table)
  File "/opt/miniconda/envs/gatk/lib/python3.6/site-packages/gcnvkernel/io/io_ploidy.py", line 183, in get_contig_ploidy_prior_map_from_tsv_file
    assert columns[0] == io_consts.ploidy_prior_contig_name_column
AssertionError

	at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)
	at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170)
	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:151)
	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:121)
	at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.executeDeterminePloidyAndDepthPythonScript(DetermineGermlineContigPloidy.java:365)
	at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.doWork(DetermineGermlineContigPloidy.java:263)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
(gatk) root@d345bbc30072:/gatk/snail/gcnv_180517/ploidy# 
```

**Comment by cmnbroad** [comment]
@sooheelee The GATK Docker is preconfigured with the conda environment already established; I think what you're seeing is some other issue.

**Comment by sooheelee** [comment]
I'm able to install Conda, run the yml and activate it locally. I don't know what's up with the Docker either.

**Comment by JiguangPeng** [comment]
> Do I need to run this Python package in the GATK4.0.4.0 Docker? I am getting a similar error with DetermineGermlineContigPloidy while running within the Docker on a Linux Compute Engine VM.
> 
> ```
> ...
> 19:06:35.948 INFO  DetermineGermlineContigPloidy - Aggregating read-count file /gatk/snail/gcnv_180517/coverage_1k/A19625.hc.soohee1k.hdf5 (24 / 24)
> 19:06:54.675 INFO  DetermineGermlineContigPloidy - Shutting down engine
> [May 18, 2018 7:06:54 PM UTC] org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy done. Elapsed time: 1.83 minutes.
> Runtime.totalMemory()=2822242304
> org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException: 
> python exited with 1
> Command Line: python /tmp/root/cohort_determine_ploidy_and_depth.8539868448285133842.py --sample_coverage_metadata=/tmp/root/samples-by-coverage-per-contig3023244219495833390.tsv --output_calls_path=/gatk/snail/gcnv_180517/ploidy/hc24_soohee1k_ploidy-calls --mapping_error_rate=1.000000e-02 --psi_s_scale=1.000000e-04 --mean_bias_sd=1.000000e-02 --psi_j_scale=1.000000e-03 --learning_rate=5.000000e-02 --adamax_beta1=9.000000e-01 --adamax_beta2=9.990000e-01 --log_emission_samples_per_round=2000 --log_emission_sampling_rounds=100 --log_emission_sampling_median_rel_error=5.000000e-04 --max_advi_iter_first_epoch=1000 --max_advi_iter_subsequent_epochs=1000 --min_training_epochs=20 --max_training_epochs=100 --initial_temperature=2.000000e+00 --num_thermal_epochs=20 --convergence_snr_averaging_window=5000 --convergence_snr_trigger_threshold=1.000000e-01 --convergence_snr_countdown_window=10 --max_calling_iters=1 --caller_update_convergence_threshold=1.000000e-03 --caller_admixing_rate=7.500000e-01 --disable_caller=false --disable_sampler=false --disable_annealing=false --interval_list=/tmp/root/intervals3258684972117897378.tsv --contig_ploidy_prior_table=/gatk/snail/gcnv/grch38_germline_CN_priors.tsv --output_model_path=/gatk/snail/gcnv_180517/ploidy/hc24_soohee1k_ploidy-model
> Stdout: 
> Stderr: Traceback (most recent call last):
>   File "/tmp/root/cohort_determine_ploidy_and_depth.8539868448285133842.py", line 78, in <module>
>     args.contig_ploidy_prior_table)
>   File "/opt/miniconda/envs/gatk/lib/python3.6/site-packages/gcnvkernel/io/io_ploidy.py", line 183, in get_contig_ploidy_prior_map_from_tsv_file
>     assert columns[0] == io_consts.ploidy_prior_contig_name_column
> AssertionError
> 
> 	at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)
> 	at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
> 	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170)
> 	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:151)
> 	at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:121)
> 	at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.executeDeterminePloidyAndDepthPythonScript(DetermineGermlineContigPloidy.java:365)
> 	at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.doWork(DetermineGermlineContigPloidy.java:263)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
> 	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
> 	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
> 	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
> 	at org.broadinstitute.hellbender.Main.main(Main.java:289)
> (gatk) root@d345bbc30072:/gatk/snail/gcnv_180517/ploidy# 
> ```
> My Docker's gatk directory shows the following:
> 
> ```
> ~/gatk-4.0.4.0$ ls
> gatk  gatk-completion.sh  gatkcondaenv.yml  GATKConfig.EXAMPLE.properties  gatkdoc  gatk-package-4.0.4.0-local.jar  gatk-package-4.0.4.0-spark.jar  gatkPythonPackageArchive.zip  README.md
> ```
@sooheelee ,I met the same problem, but not in the docker. have you fixed this?

**Comment by cmnbroad** [comment]
@JiguangPeng You shouldn't need to run this in the Docker, but if you don't, you need to manually activate the GATK conda environment as described earlier in this thread. Based on your command prompt, it looks like you may not have done that (the command prompt usually reflects the current conda environment). Directions for how to do it are [here](https://github.com/broadinstitute/gatk#python).
