### ISSUE TITLE
Increase verbosity of Travis logging for WDL tests.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#4130]
This will make debugging easier.  Currently the only way to debug failing tests is to rerun them locally, which typically requires editing the JSONs and WDLs.  Logging the stdout/stderr for all tasks would probably suffice.

**Comment by cmnbroad** [comment]
One thing to try is to configure cromwell to retain the log directory via a workflow option when we run the tests. Then at the end of the build we can copy them somewhere, either always, or via the travis after_failure entry in the build matrix. Then we'd be able to see exactly what failed in the travis environment.

**Comment by lbergelson** [comment]
I think uploading the logs to a bucket like we do with the test outputs is a good idea.  There's an example of how to do it in the after_script block of the .travis.yml.

**Comment by samuelklee** [comment]
Not sure if this has been address, but comfortable calling it a dupe of #5098.
