### ISSUE TITLE
picard 2.10.7 fails pipelining SortSam and SetNmAndUqTags

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4133]
Bug on 4.0.0.0 reported on forum -- please advise how to proceed @droazen @lbergelson.

---

Ok now things are getting more interesting. Disabling intelflaters seems to solve the problem. But why?

Same flaters work with standalone picard as well and they don't have any issues. Compression level does not change anything. Is this a memory allocation error? I don't think so because it does not segfault. The error message says filename not found. 

I am wondering if this has anything to do with meltdown patches. Both of my systems (Ubuntu and macOS) are patched against meltdown bug. And Intel flaters are causing this issue. But this won't explain why standalone picard is still working fine with them. The only explanation that I have is the difference between HTSJDK and GKL versions between standalone picard 2.17.2 and embedded picard 2.17.2 in gatk. The latest HTSJDK update for standalone picard mentions 2.13.1 version but the one in gatk 4.0 is 2.13.2 I believe. I don't have the info about GKL version used in them. 

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/44985#Comment_44985

**Comment by sooheelee** [comment]
For @droazen to delegate.

**Comment by lbergelson** [comment]
I commented on the message itself.  The problem seems to be that we output some log messages to STDOUT that break piping.  Picard puts them on STDERR.
