### ISSUE TITLE
Optimize overlap detection in ReadsSparkSource

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#4153]
In `ReadsSparkSource` there are two places, lines 118 and 169, where for every read in an `RDD` we check for overlap with some `TraversalParameters`.  The `samRecordOverlaps` method that does this is done from scratch for every read.  It would be much more efficient to create an `OverlapDetector` from the `TraversalParameters` *once* and then repeatedly query it.

**Comment by davidbenjamin** [comment]
BTW, this is low-priority because the logic is only invoked for *SAM* files, not *BAM*s.

**Comment by davidbenjamin** [comment]
@tomwhite I'm confused by the following code in `samRecordOverlaps`:

```java
for (SimpleInterval interval : intervals) {
    if (record.getReadUnmappedFlag() && record.getAlignmentStart() != SAMRecord.NO_ALIGNMENT_START) {
        int start = record.getAlignmentStart();
        return interval.getStart() <= start && interval.getEnd() >= start;
    } else  if (interval.overlaps(record)) {
        return true;
    }
}
```
If a record is unmapped (which necessarily implies that `getContig()` returns `null`), it checks whether its assigned start lies between the start and end of any interval in `traversalParameters` *regardless of that interval's contig*.

**Comment by tomwhite** [comment]
@davidbenjamin thanks for the report. (And sorry for the slow reply, I was out at the time you reported it.) I agree with the optimisation you suggest for checking overlaps for SAMs.

For the `samRecordOverlaps`, I think that check predates the use of `TraversalParameters`. The correct fix is probably to remove the `if` clause since unmapped records are handled earlier in the method.

**Comment by davidbenjamin** [comment]
@tomwhite Thanks for the answer, and don't worry because David Roazen let me know you would be away for a while!

**Comment by davidbenjamin** [comment]
I don't see this problem in the code any more.
