### ISSUE TITLE
How can I debug the gatk4.0 code in intellij IDEA？

### ISSUE THREAD

**Issue by Sun-shan** [broadinstitute/gatk#4156]
How can I debug the gatk4.0 code in intellij IDEA？
Can I build the source code in intellij IDEA？

**Comment by cmnbroad** [comment]
@Sun-shan You can clone this repo, and then follow [these](https://github.com/broadinstitute/gatk#creating-a-gatk-project-in-the-intellij-ide-last-tested-with-version-201624) instructions in the README.md to set up an IntelliJ project.
