### ISSUE TITLE
How to interpret results from GermlineCNVCaller

### ISSUE THREAD

**Issue by stefandiederich** [broadinstitute/gatk#4157]
Hi, 
I now managed to process my data with the following steps:
1. CollectFragmentCounts
2. DetermineGermlineContigPloidy
3. GermlineCNVCaller

From the GermlineCNVCaller tool I get a lot of files per sample. Unfortunately I can't find any description what the content of these files tells me and how I can interpret the data to see at which genomic coordinates my CNVs are. Do I need an other tool to somehow extract these informations out of the given files?

Thanks again
Stefan

**Comment by samuelklee** [comment]
Hi @stefandiederich,

Great that you were able to successfully run GermlineCNVCaller!  @asmirnov239 is currently working on a postprocessing tool that will convert the raw generated results into VCFs.  @mbabadi is also working on writing some more in-depth documentation on the tool and its probabilistic model.

For now, you may be able to parse the raw results on your own.  You are probably most interested in the contents of the "*-calls" directory.  The root of this directory contains the interval list common to all samples; furthermore, each sample has its own subdirectory that contains text files that describe the sample-specific model-parameter posteriors.  In particular, the "log_q_c_tc.tsv" file contains the log posteriors per copy-number state, with rows corresponding to the intervals in the aforementioned interval list.
