### ISSUE TITLE
GenomicsDBImport segfault on `std::string::compare` with paths longer than 105 characters

### ISSUE THREAD

**Issue by chapmanb** [broadinstitute/gatk#4160]
Hi all;
When validation runs on the GATK 4.0.0 release (congrats!) we're running into segfault issues on some `GenomicsDBImport` runs which look to be due to the length of the database path:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f99a7642c5b, pid=7446, tid=0x00007f99fbfa0700
#
# JRE version: OpenJDK Runtime Environment (8.0_121-b15) (build 1.8.0_121-b15)
# Java VM: OpenJDK 64-Bit Server VM (25.121-b15 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtiledbgenomicsdb8843204539247232071.so+0x4fdc5b]  std::string::compare(char const*) const+0x1b
```
Here is a self-contained test case that reproduces the issue:

https://s3.amazonaws.com/chapmanb/testcases/gatk/gatk4_genomicsdb_length.tar.gz

A standard small name and longer name of 105 characters work fine:
```
gatk-launch --java-options '-Xms1g -Xmx2g' GenomicsDBImport --reader-threads 1 --genomicsdb-workspace-path short_genomicsdb -L chr22:15069-15500 --variant Test1.vcf.gz --variant Test2.vcf.gz
gatk-launch --java-options '-Xms1g -Xmx2g' GenomicsDBImport --reader-threads 1 --genomicsdb-workspace-path long_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_genomicsdb/works_aaaaaaaaaaaaaaaaaaaaaaaaaa -L chr22:15069-15500 --variant Test1.vcf.gz --variant Test2.vcf.gz
```
But when you add an additional character, you trigger the segfault:
```
gatk-launch --java-options '-Xms1g -Xmx2g' GenomicsDBImport --reader-threads 1 --genomicsdb-workspace-path long_aaaaaa
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa_genomicsdb/fails_aaaaaaaaaaaaaaaaaaaaaaaaaaa -L chr22:15069-15500 -
-variant Test1.vcf.gz --variant Test2.vcf.gz
```
Thank you for looking at this and please let me know if I can provide any other information to help debug.

**Comment by droazen** [comment]
@kgururaj Can you please have a look at this one?

**Comment by kgururaj** [comment]
Thanks for exercising this corner case - looks like TileDB internally used 256 chars for paths. Have increased that to 4096 (max for most filesystems). The next release will fix this.

**Comment by droazen** [comment]
Resolved by https://github.com/broadinstitute/gatk/pull/4261
