### ISSUE TITLE
GenotypeGVCF struggling at high sample size

### ISSUE THREAD

**Issue by owensgl** [broadinstitute/gatk#4161]
I'm trying to genotype 2388 whole genome samples of a wild species. This species has a large genome and lots of diversity. I've created my genomicsDB for my combined set and genotypeGVCF gets stuck when trying to make the VCF. 
I've been giving it 120G of ram, 32 cores and 30 minutes and it only prints out the first variable 12 sites (corresponding to about 800bp of the genome) to the VCF . I understand that is certainly going to be slow, and I'm prepared to heavily parallelize it, but this is currently unusable to me. Is there any way to speed it up?

Here's my command:

```
/gatk/gatk-launch --java-options "-Xmx120G" GenotypeGVCFs \
        -R /home/user/bin/ref/reference.fa \
        --intervals $contig \
        -V gendb://${chr}_$pos \
        -O /scratch/wild_gwas/$genomicsdb/${chr}_$pos.tmp.vcf.gz \
        --seconds-between-progress-updates 5 --verbosity DEBUG
```
Here's standard out:

> 21:13:04.092 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/build/install/gatk/lib/gkl-0.8.2.jar!/com/intel/gkl/native/libgkl_compression.so
> 21:13:04.108 DEBUG NativeLibraryLoader - Extracting libgkl_compression.so to /tmp/gowens/libgkl_compression3380966567685792416.so
> 21:13:04.218 INFO  GenotypeGVCFs - ------------------------------------------------------------
> 21:13:04.219 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.0.0.0
> 21:13:04.219 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
> 21:13:04.219 INFO  GenotypeGVCFs - Executing as user@cdr806.int.cedar.computecanada.ca on Linux v3.10.0-693.5.2.el7.x86_64 amd64
> 21:13:04.219 INFO  GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11
> 21:13:04.219 INFO  GenotypeGVCFs - Start Date/Time: January 15, 2018 9:13:04 PM UTC
> 21:13:04.219 INFO  GenotypeGVCFs - ------------------------------------------------------------
> 21:13:04.220 INFO  GenotypeGVCFs - ------------------------------------------------------------
> 21:13:04.220 INFO  GenotypeGVCFs - HTSJDK Version: 2.13.2
> 21:13:04.220 INFO  GenotypeGVCFs - Picard Version: 2.17.2
> 21:13:04.222 INFO  GenotypeGVCFs - HTSJDK Defaults.BUFFER_SIZE : 131072
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 1
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.CREATE_INDEX : false
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.CREATE_MD5 : false
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.CUSTOM_READER_FACTORY :
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.DISABLE_SNAPPY_COMPRESSOR : false
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.EBI_REFERENCE_SERVICE_URL_MASK : https://www.ebi.ac.uk/ena/cram/md5/%s
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.NON_ZERO_BUFFER_SIZE : 131072
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.REFERENCE_FASTA : null
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.SAM_FLAG_FIELD_FORMAT : DECIMAL
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
> 21:13:04.223 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_CRAM_REF_DOWNLOAD : false
> 21:13:04.224 DEBUG ConfigFactory - Configuration file values:
> 21:13:04.230 DEBUG ConfigFactory -      gcsMaxRetries = 20
> 21:13:04.230 DEBUG ConfigFactory -      gatk_stacktrace_on_user_exception = false
> 21:13:04.230 DEBUG ConfigFactory -      samjdk.use_async_io_read_samtools = false
> 21:13:04.230 DEBUG ConfigFactory -      samjdk.use_async_io_write_samtools = true
> 21:13:04.230 DEBUG ConfigFactory -      samjdk.use_async_io_write_tribble = false
> 21:13:04.230 DEBUG ConfigFactory -      samjdk.compression_level = 1
> 21:13:04.230 DEBUG ConfigFactory -      spark.kryoserializer.buffer.max = 512m
> 21:13:04.230 DEBUG ConfigFactory -      spark.driver.maxResultSize = 0
> 21:13:04.230 DEBUG ConfigFactory -      spark.driver.userClassPathFirst = true
> 21:13:04.230 DEBUG ConfigFactory -      spark.io.compression.codec = lzf
> 21:13:04.230 DEBUG ConfigFactory -      spark.yarn.executor.memoryOverhead = 600
> 21:13:04.230 DEBUG ConfigFactory -      spark.driver.extraJavaOptions =
> 21:13:04.230 DEBUG ConfigFactory -      spark.executor.extraJavaOptions =
> 21:13:04.230 DEBUG ConfigFactory -      codec_packages = [htsjdk.variant, htsjdk.tribble, org.broadinstitute.hellbender.utils.codecs]
> 21:13:04.230 DEBUG ConfigFactory -      cloudPrefetchBuffer = 40
> 21:13:04.231 DEBUG ConfigFactory -      cloudIndexPrefetchBuffer = -1
> 21:13:04.231 DEBUG ConfigFactory -      createOutputBamIndex = true
> 21:13:04.231 INFO  GenotypeGVCFs - Deflater: IntelDeflater
> 21:13:04.231 INFO  GenotypeGVCFs - Inflater: IntelInflater
> 21:13:04.231 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
> 21:13:04.231 INFO  GenotypeGVCFs - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
> 21:13:04.231 INFO  GenotypeGVCFs - Initializing engine
> 21:13:11.834 INFO  GenotypeGVCFs - Done initializing engine
> 21:13:11.950 DEBUG MathUtils$Log10Cache - cache miss 2 > 0 expanding to 12
> 21:13:11.992 INFO  ProgressMeter - Starting traversal
> 21:13:11.992 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
> 21:14:17.635 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:1->2
> 21:14:17.858 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:2->3
> 21:14:17.872 DEBUG MathUtils$Log10Cache - cache miss 13 > 12 expanding to 26
> 21:14:17.872 DEBUG MathUtils$Log10Cache - cache miss 27 > 26 expanding to 54
> 21:14:17.872 DEBUG MathUtils$Log10Cache - cache miss 55 > 54 expanding to 110
> 21:14:17.872 DEBUG MathUtils$Log10Cache - cache miss 111 > 110 expanding to 222
> 21:14:17.873 DEBUG MathUtils$Log10Cache - cache miss 223 > 222 expanding to 446
> 21:14:17.873 DEBUG MathUtils$Log10Cache - cache miss 447 > 446 expanding to 894
> 21:14:17.873 DEBUG MathUtils$Log10Cache - cache miss 895 > 894 expanding to 1790
> 21:14:17.874 DEBUG MathUtils$Log10Cache - cache miss 1791 > 1790 expanding to 3582
> 21:14:17.894 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:1->2
> 21:14:17.930 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:1->2
> 21:14:17.937 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:1->2
> 21:14:18.507 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:3->4
> 21:14:18.510 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:2->3
> 21:27:38.720 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:2->3
> 21:28:26.332 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:2->3
> 21:30:24.296 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:4->5
> 21:30:24.299 DEBUG GenotypeLikelihoodCalculators - Expanding capacity ploidy:2->2 allele:3->4
> 

Here's standard error:

> WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
> WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
> WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
> WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
> WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
> WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
> WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
> WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
> DEBUG   2018-01-15 21:13:11     BlockCompressedOutputStream     Using deflater: IntelDeflater
> WARNING: No valid combination operation found for INFO field DS - the field will NOT be part of INFO fields in the generated VCF records
> WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
> WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
> WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records

**Comment by owensgl** [comment]
I think I've fixed my own problem by turning on the new qual calculator (--use-new-qual-calculator). It now outputs variants at a reasonable, if slow, speed.

**Comment by lbergelson** [comment]
@owensgl Sorry you're running into problems.  We typically speed up the process by running multiple GenotypeGVCF processes in parallel, subsetting by genomic intervals.  GenotypeGVCFs isn't really multicore, you'll probably be best off giving each process 1 or 2 cores. (You'll see better performance with 2 since java has parallel garbage collection, but it might be more cost effective to run twice as many slower processes...)  If you do that you'll want to run with `--only-output-calls-starting-in-intervals`  enabled in order to avoid problems on the edges of intervals.   

Things tend to bog down with many highly multi-allelic sites.  If you have a population with very high diversity you may be hitting lots of sites like that.  I'm not sure why it's as slow as you say it is though.  It should be faster than 800bp / 30 minutes even with old qual. If you could provide a subset of your data we might be able to profile and see if there's some pathological case we're not handling well.  I believe new-qual handles multi-allelic sites more efficiently which I suspect is why it's going faster.

**Comment by owensgl** [comment]
Thanks for the advice. With this dataset, we see variants at about every second basepair on average and around 10-20% of the sites are multi-allelic. There aren't very many sites with >3 alleles, although there are a few. I'll look into seeing if I can upload a subset of the data. Is it possible to send a tarballed genomicsDB directory?

**Comment by lbergelson** [comment]
It should be possible if it was created with the version of GenomicsDB that's packaged with the 4.0 version of gatk. If it was created with an earlier version, you'll need to include the exact full path that the genomicsDB was stored in and I'll need to recreate that exactly on my system, which is obviously a gross.
