### ISSUE TITLE
Cloud tests are failing due to "Error while looking up reference set EOSsjdnTicvzwAE".

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#4163]
Seems to be non-intermittent.

**Comment by lbergelson** [comment]
As far as I can tell, they've just turned off the entire genomics api.  I'm going to disable these tests immediately and then wait until I hear back from google to decide what to do in the future.  

There's a support ticket [here](https://enterprise.google.com/supportcenter/managecases#Case/0016000000MNGDy/U-14725661).

**Comment by lbergelson** [comment]
opening #4166 to track the resolution of this

**Comment by lbergelson** [comment]
Google claims this should be re-enabled for our broad-dsde-dev project specifically now.  I'm unable to confirm because travis seems to be having trouble.

**Comment by lbergelson** [comment]
The tests are still failing on my machine.

**Comment by droazen** [comment]
Let's just disable them for now.
