### ISSUE TITLE
Allow barclay list auto-expansion to be disabled using an @Argument attribute, disable it for -L in GATK , and add back .list as an acceptable extension for list files

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4165]
* Allow barclay list auto-expansion to be disabled using an @Argument attribute
* Disable it for -L in GATK
* Add back `.list` as an acceptable extension for list files (but keep the current extension `.args` as well)

**Comment by lbergelson** [comment]
I'm not a fan of the additional `@Argument` parameter.  If we have to have one can it modify the accepted extensions instead of being a boolean?

**Comment by droazen** [comment]
@lbergelson As discussed earlier today, that would be more awkward than the simple boolean toggle  in the case of `-L`, since you really don't want to specify an alternate extension in that case, you just want to turn the expansion off completely.

**Comment by lbergelson** [comment]
You could specify no extension.  Or `.args`, in the case you wanted to provide a file of files or something like that.

**Comment by droazen** [comment]
@lbergelson Allowing the actual extension to vary per-argument seems WAY more confusing than just allowing certain arguments to not support list expansion.

**Comment by lbergelson** [comment]
If you're going to have a crazy hack you should go all in on the crazy!

**Comment by cmnbroad** [comment]
I think I'm inclined towards just the simple toggle.

**Comment by droazen** [comment]
Simple toggle wins the day, by a vote of 2-1  :)

**Comment by magicDGS** [comment]
I am sorry to change to a draw (2-2), but I'm in favor of even more flexibility in Barclay to allow users to change the extension(s) in a per-argument basis.

**Comment by cmnbroad** [comment]
I suggest we start with just the toggle, since we have an immediate need for that, and leave finer-grained control to the more general customization/delegation mechanism we've started in other PRs, and so clearly need.

**Comment by droazen** [comment]
Done in https://github.com/broadinstitute/gatk/pull/4270
