### ISSUE TITLE
remove code supporting google Read and Reference API

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4166]
Google is deprecating and removing their implementation of the old style GA4GH read and reference API's. 

> 
> Reads API functionality is now replaced by the htsget protocol 
> 
> This year, the GA4GH team introduced the htsget protocol to allow users to download read data for subsections of the genome in which they are interested. This is a richer and more flexible approach to working with reads data. It allows you to keep your genomics data in a common BAM file format on Google Cloud Storage and work with it efficiently from your computation pipelines, using standard bioinformatics tools. We have already launched our own open source implementation of this protocol, which you can use to access your reads data. Many popular tools such as samtools and htslib have been updated by the community to support htsget. Documentation is provided here. The Reads API is now deprecated, and will be decommissioned after one year, or after there has been no API activity for one month by those receiving this notice, whichever comes first. 
> 
> Variants API is now replaced by htsget and Variant Transforms 
> 
> The GA4GH team also plans to extend the htsget protocol to cover variant data, and we will extend our implementation of htsget to cover this use case. 
> 
> After analyzing usage of the Variants API, we found that users primarily used it to import variant data and then export it to BigQuery. To save time and effort, we created Variant Transforms, an open source tool for directly importing VCF data into BigQuery. Variant Transforms and its documentation are published here. Variant Transforms is more scalable than the legacy Variants API, and it has a robust roadmap with a dedicated team. We also welcome collaborators on this project as it advances. 
> 
> The Variants API is now deprecated, and will be decommissioned after one year, or after there has been no API activity for one month, whichever comes first. 
> 
> We are excited to move in step with the global genomics community and provide you with the latest technology for managing your genomic data. We have lots of other projects on the way, and look forward to supporting you. 

Accordingly, we should remove our code that uses them.  Unfortunately, this means we'll only have a single implementation of `GATKRead` which is unfortunate.

**Comment by magicDGS** [comment]
@lbergelson - regarding the single implementation of `GATKRead`, I would like to maintain the interface because I have some custom implementations. Although if it is true that HTSJDK will move to a version 3 based on interfaces, I can change my code to use the HTSJDK interfaces instead.

**Comment by droazen** [comment]
@magicDGS We will definitely be keeping the `GATKRead` interface around for the foreseeable future. When the HTSJDK 3.0 interfaces materialize we'll re-evaluate, but it's possible that we would continue to code against `GATKRead` even then, as our `SAMRecord` -> `GATKRead` adapter layer does some useful caching, and having our own interface has certain advantages (as well as disadvantages).

**Comment by lbergelson** [comment]
This was done in #4266
