### ISSUE TITLE
One user reports HaplotypeCaller 4.0 performance is slower than beta 2

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#4169]
User says beta 2 is much faster than release. 

----
User Report
----
Hi @Geraldine_VdAuwera , thanks for the quick response!

We used CCLE WES FASTQs for the purpose of testing (6GB per paired end). We scattered the tool using a custom BED file with 86 intervals.

4.0.0.0 failed due to memory with 2GB per job. It completed with 4GB per job. Each job lasted approximately 1h 10 min. 4.beta.2 completed with 2GB per job and each job lasted approximately 5m.

This is in gVCF mode, with the same settings as described above. All input files, settings and hardware are the same between versions.

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/44970#Comment_44970

**Comment by droazen** [comment]
This user is going to have to give us a runnable test case to reproduce this, as our own profiling shows that the 4.0 version of `HaplotypeCaller` is much faster than the betas. You should also ask the user to try running with GATK3 and report the timing.

**Comment by droazen** [comment]
@chandrans I'd also mention to the user that the `4.beta.2` version of `HaplotypeCaller` does NOT give correct output at all, while the `4.0` version gives output that is almost identical to GATK3. So the right question to ask is whether `4.0` is faster than `3.x`, not whether it's faster than the early beta `4.beta.2`, which was not even a complete version of the tool.

**Comment by chandrans** [comment]
Okay, will do. Thanks David.

**Comment by chandrans** [comment]
Good news. User says this is no longer an issue:

`We found the reason why HaplotypeCaller 4.0.0.0 performed worse than 4.beta.2. We are scattering tools using intervals from a custom BED file. Before, each instance of HaplotypeCaller received a BAM file from ApplyBQSR that was produced using a specific interval, but not the interval itself. This worked for 4.beta.2, but was causing poor performance for 4.0.0.0. We now pass both the BAM and the interval to HaplotypeCaller 4.0.0.0 and it performs just as well as 4.beta.2 with the same amount of memory.`

**Comment by droazen** [comment]
Great, glad this mystery is solved!

It makes sense that running HC 4.0.0.0 without any intervals on a bam snippet would be slower than running without intervals in HC 4.beta.2, since HC 4.beta.2 lacked some logic that was present in GATK3 to handle uncovered loci.
