### ISSUE TITLE
add AxVE to AUTHORS list

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4177]
@AxVE Since you've just had your first pull request merged, we'd like to add you to the [AUTHORS](https://github.com/broadinstitute/gatk/blob/master/AUTHORS) file.  How would you like to be listed?

We typically list individuals as 

Your Name <Your.email>

**Comment by AxVE** [comment]
@lbergelson Thank you.

`Axel Verdier axel.verdier@inra.fr`  should be fine ^^
