### ISSUE TITLE
IndexFeatureFile can't index .vcf.gz using ProgressReportingDelegatingCodec

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#4184]
When trying to index a gzipped VCF at `/humgen/gsa-hpprojects/dev/gauthier/reblockGVCF/hybrid.m38.vcf.gz`I get the error `A USER ERROR has occurred: This tool does not supports indexing of block-compressed files for ProgressReportingDelegatingCodec`

Indexing this file with tabix is speedy and successful.

**Comment by droazen** [comment]
Running `gatk IndexFeatureFile` with `--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true'` reveals that the underlying error is:

```
htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 483650: unparsable vcf record with allele M
```

Can you check whether the VCF is malformed at this location, as the error claims?

**Comment by droazen** [comment]
More specifically, the locus in question is chr1:248752514 with ref == M and alt == C

**Comment by droazen** [comment]
Since the VCF in question is malformed, the task here becomes "make IndexFeatureFile throw a more informative error message when the file being indexed is malformed"
