### ISSUE TITLE
get rid of ADAMSparkRegistrator spam

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4186]
```
18/01/17 08:24:55 INFO org.bdgenomics.adam.serialization.ADAMKryoRegistrator: Did not find Spark internal class. This is expected for Spark 1.
``` 

Appears hundreds of times in the log output since we upgraded ADAM.  This is despite the fact that we're not using spark 1.  Maybe there's a way to silence a specific logger?

**Comment by lbergelson** [comment]
I've been told that this is solvable by bumping the dataproc version from 1.1 -> 1.2.  We need to update this on jenkins assuming it works fine with spark 2.2.

**Comment by lbergelson** [comment]
It might still be worth silencing this for people who are running spark 2.0.0 which is what we are doing on jenkins.  (and what we officially support in our build.gradle).  Ultimately we need to upgrade to spark 2.2.x  #2555

**Comment by cwhelan** [comment]
This is still an issue when running with `--spark-runner LOCAL`, ie not in dataproc.

**Comment by lbergelson** [comment]
That makes sense because it uses the bundled spark 2.0.2
