### ISSUE TITLE
M2 WDL script wishlist

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4188]
For @davidbenjamin. I've been asked to take the user-perspective and report things I'd want to make our WDL scripts more extensible. So here goes.

<img width="824" alt="screenshot 2018-01-17 13 22 27" src="https://user-images.githubusercontent.com/11543866/35060379-501cb8c8-fb8c-11e7-845e-a146fc2ced94.png">

## Major wants
- The is_bamout Boolian appears to be hardcoded to `false` in the script. Users need to be able to understand that this option can be changed without ambiguity. So this should become a proper  optional variable. @LeeTL1220 tells me this can be overwritten. However, why leave this as misinterpretable to newbie WDL-scriptors? Especially since `wdltools inputs` doesn't include it as a variable at all in the generated inputs list. Please can we make this a proper optional argument that `wdltools inputs` will generate a variable for.
- [ "${variants_for_contamination}" == *.vcf ] does not allow *.vcf.gz files. It should accept either.
- Outputs should allow either .vcf or .vcf.gz compression by user-specification. Alternatively, if we want to keep it simple and hardcode, then the preference is for compressed files. Some of us prefer to save on storage.
- Need to be able to specify optional string args for SplitIntervals. I would like to be able to use the BALANCING_WITHOUT_INTERVAL_SUBDIVISION mode. Furthermore, I'd like for the tool to automatically interpret this mode, when not given an -L intervals list, to not split reference contigs. I.e. a contig is an interval. (Perhaps already the tool behavior?)
- The version of Oncotator is not compatible with GRCh38. Please, can we have an option to switch this out with Funcotator? 

## Minor wants
- The JSON template in the repo should show the optional variables.
- Script calls for a Picard jar. I don't mind specifying this because I like controlling for the Picard version I use. However, users may want to call the Picard version within the GATK jar. I cannot fathom a simple way to allow switching this out in the script, but perhaps something like the gatk_override option could work. The goal would be to call the Picard tool from a Docker. This better enables provenance.

**Comment by samuelklee** [comment]
Would appreciate similar insights on the CNV WDLs when you get a chance, @sooheelee!  Just one minor comment for @davidbenjamin: I think we agreed to remove the CNV JSON templates from the repo at some point, any reason why we can't do the same for the M2 template?  These templates don't buy you anything over just using `wdltools inputs`, but have the drawback of having to be kept up to date.

**Comment by sooheelee** [comment]
Sure thing @samuelklee. 

As for the JSON template, it helps me understand what the script requires, without going through the script itself. 

One more thing to add to the general list of wants in any WDL script. This comes from @knoblett. Every GATK/Picard tool run should allow for optional string type args.

**Comment by samuelklee** [comment]
Right @sooheelee, the template is certainly useful for that, but can just as easily be generated using `wdltool inputs`.  Whatever you and @davidbenjamin decide, let me know if I should add the CNV templates back to be consistent.  (But again, my vote is for removing the M2 template!)

@LeeTL1220 can add whatever we decide about optional string type args to the style guide, but I'd prefer for this sort of thing to be automatically generated (#2480).

**Comment by sooheelee** [comment]
I just noticed the script doesn't run CollectSequencingArtifactMetrics nor GetPileupSummaries on the matched normal. Just curious if you have plans to incorporate these additions given a matched normal.

**Comment by davidbenjamin** [comment]
> [ "${variants_for_contamination}" == *.vcf ] does not allow *.vcf.gz files. It should accept either

I'm about to fix this in a PR.

> Script calls for a Picard jar. I don't mind specifying this because I like controlling for the Picard version I use. However, users may want to call the Picard version within the GATK jar. I cannot fathom a simple way to allow switching this out in the script, but perhaps something like the gatk_override option could work. The goal would be to call the Picard tool from a Docker. This better enables provenance.

The same PR is also going to call Picard from the gatk.
> (But again, my vote is for removing the M2 template!)
 
I agree with @samuelklee about the template.

> I just noticed the script doesn't run CollectSequencingArtifactMetrics nor GetPileupSummaries on the matched normal. 

I should definitely use the normal for contamination.  @sooheelee What's the case for CollectSequencingArtifactMetrics on the normal?

**Comment by vdauwera** [comment]
My $0.02:

1. In general it's ok with me to not provide a template for WDLs in the GATK repo as long as you guys help us (ie @bshifaw) produce appropriate templates to include in the gatk-workflows repo and in FireCloud. 

2. Re: Picard tools, going forward they should be invoked from the GATK jar by default. Among other benefits, that will reduce support entropy wrt possible combination of versions of tools people might be using.

3. I like the idea of focusing on the auto-generated wrappers for improvements like the string variable for adding arbitrary extra args.

**Comment by sooheelee** [comment]
@davidbenjamin, the case for CollectSequencingArtifactMetrics on the normal is not strong and I agree it doesn't have to be a part of the M2 workflow. 

I just like to have a control and I can do this separately for the tutorial. Presumably, the normal and tumor samples were prepped together. Given this, my expectation is that the tumor and normal show similar sequencing artifacts. Any deviations from this expectation should have a rational explanation, e.g. the samples were prepped separately. Otherwise, I'd be suspicious of the artifacts in the tumor.

**Comment by byoo** [comment]
If docker is needed to run M2 wdl, I wish it can run without docker.
I need to run M2 wdl using grid engine backend and an old version needed some modifications to run without docker installed.

**Comment by davidbenjamin** [comment]
@byoo We run the M2 wdl without modification on a Broad SGE cluster for our internal evaluations all the time.  A cromwell config file for SGE is required, but that's the case for every backend.  You *do* need to supply a gatk docker image string as an input, but it is ignored.

Please feel free to share your input json and config file if it doesn't work for you.  I can't say I'm skilled enough to catch anything subtle, but I can check for obvious differences.

**Comment by davidbenjamin** [comment]
> The version of Oncotator is not compatible with GRCh38. Please, can we have an option to switch this out with Funcotator?

@jonn-smith Is Funcotator ready to go in the wdl?  Should it even *replace* Oncotator?  Does it need its own docker or does one just invoke it like the rest of the GTK tools?  Do we need to do anything special to toggle between references?

**Comment by sooheelee** [comment]
Another option @davidbenjamin and @jonn-smith is to put in a comment line that Oncotator is not compatible with GRCh38 and to point users to a separate Funcotator WDL script.

**Comment by sooheelee** [comment]
@byoo You may find https://software.broadinstitute.org/gatk/documentation/article?id=11090 helpful in setting up docker.

**Comment by jonn-smith** [comment]
@davidbenjamin Funcotator is not quite ready to outright replace Oncotator, but there is a test WDL for it in the M2/unsupported folder.  

It can run off the same docker image, but you need to download the data sources (or provide your own - the provided tar.gz is about 300MB and extracts to about 3GB).  There is a short set of instructions in the tool doc for how to run it (I'm still working on the tutorial for the forum).  

One current limitation is that it only consumes and produces VCF files, which may be an issue for some users.  

I should add that while I have done _some_ testing with GRCh38, I have not extensively tested with that reference.

**Comment by davidbenjamin** [comment]
> Furthermore, I'd like for the tool to automatically interpret this mode, when not given an -L intervals list, to not split reference contigs. I.e. a contig is an interval. (Perhaps already the tool behavior?)

@sooheelee I just tested this and the `BALANCING_WITHOUT_INTERVAL_SUBDIVISION` already works the way you want it to.

**Comment by davidbenjamin** [comment]
Status as of PR #4238:

## Remaining wants
- Outputs should allow either .vcf or .vcf.gz compression by user-specification. Alternatively, if we want to keep it simple and hardcode, then the preference is for compressed files. Some of us prefer to save on storage.
- The version of Oncotator is not compatible with GRCh38. Please, can we have an option to switch this out with Funcotator?

**Comment by sooheelee** [comment]
Just seeing this. Sorry, I asked again elsewhere a question you already answered here!

**Comment by davidbenjamin** [comment]
That's okay! It actually seemed to me like you saw it already and wanted more explicit clarification.

**Comment by byoo** [comment]
@davidbenjamin mutect2_pon.wdl and mutect2.wdl worked great without docker installed. Thanks!

@samuelklee @sooheelee As a user, I found a json template useful for two reasons, though it may be up to how a wdl is written.
1) womtool generates inputs from all the dependent wdls including unnecessary ones for the workflow. (e.g. mutect2_pon.wdl)
2) womtool didn't provide default values. Looking at mutect_resources.wdl, I wondered what the good value for minimum_allele_frequency is (or what GATK team used for creating the resource bundle).

In addition, I thought a test to validate every wdl would be helpful. (womtool validate [a wdl])

**Comment by davidbenjamin** [comment]
@byoo Wonderful, we really appreciate your feedback!
