### ISSUE TITLE
Correct type for GenomicsDBImport intervals parameter in the documentation

### ISSUE THREAD

**Issue by ThomasHickman** [broadinstitute/gatk#4196]
The current documentation states that the type of the intervals parameter in the GenomicsDBImport 
 tool is `List[String]` whereas this tool can only take one interval (as explained in the Caveats section) at https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.0.0/org_broadinstitute_hellbender_tools_genomicsdb_GenomicsDBImport.php#--intervals. The type should be updated to be just a `string` and maybe a note should be included in the actual argument documentation to say that, in opposition to other tools, only one interval can be provided.

**Comment by droazen** [comment]
This is something we can't easily fix, unfortunately. The interval argument is a shared argument across the entire toolkit, and most tools accept multiple intervals. It's just this one particular tool that only accepts one interval (for now).

The ultimate solution to this issue will be https://github.com/broadinstitute/gatk/issues/3269
