### ISSUE TITLE
HaplotypeCallerSpark outputs plain text instead of bgzipped VCFs when no variants present

### ISSUE THREAD

**Issue by chapmanb** [broadinstitute/gatk#4197]
@tomwhite and @lbergelson 
I've been testing the 4.0.0.0 release with the bgzip output fix for HaplotypeCallerSpark (#3725). Thanks again for the work on that bug. I'm now hitting a similar issue with empty output VCFs. It will correctly output bgzipped VCFs when there are variants in the region, but if we call in a region with no variants we end up with plain text output.

Here is a self contained test case that demonstrates the issue:

https://s3.amazonaws.com/chapmanb/testcases/gatk/gatk4_haplotypecallerspark_plain.tar.gz

The first example command line produces plain text because it includes no variants, while the second is correct:
```
gatk-launch --java-options '-Xms1g -Xmx2g' HaplotypeCallerSpark --reference hg19.2bit -I Test1-sort-recal.bam -L chrM:1-70 --spark-master local[1] --output plain_text.vcf.gz
gatk-launch --java-options '-Xms1g -Xmx2g' HaplotypeCallerSpark --reference hg19.2bit -I Test1-sort-recal.bam -L chrM:1-75 --spark-master local[1] --output correct_gzip.vcf.gz
```
Thank you again for all the help.

**Comment by davidbenjamin** [comment]
This doesn't seem to occur in GATK 4.1.4.1.
