### ISSUE TITLE
 BUG: a bug the https://github.com/broadinstitute/gatk/blob/master/gatk

### ISSUE THREAD

**Issue by ruoshuiwyl** [broadinstitute/gatk#4230]
```bash
gatk-4.0.0.0/gatk HaplotypeCallerSpark \
        -R file://data/all_data/reference/ucsc.hg19/ucsc.hg19.fasta\
        -I file://data/all_data/large_test/NA12178/wgs_30x1/bam/mem_pe_T20_trios_NA12878_dedup.0810.bam\
        -O trios_NA12878_.vcf\
        --max-alternate-alleles 2\
        --native-pair-hmm-threads 20\
        -- --spark-runner SPARK -**-spark-master local[20]**
```
cammand 

  `  spark-submit --master local[20] --conf spark.driver.userClassPathFirst=true --conf spark.io.compression.codec=lzf --conf spark.driver.maxResultSize=0 --conf spark.executor.extraJavaOptions=-DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=false -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1  --conf spark.driver.extraJavaOptions=-DGATK_STACKTRACE_ON_USER_EXCEPTION=true -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=false -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1  --conf spark.kryoserializer.buffer.max=512m --conf spark.yarn.executor.memoryOverhead=600 /data/chenxi/tools/gatk-4.0.0.0/gatk-package-4.0.0.0-spark.jar HaplotypeCallerSpark -R file://data/all_data/reference/ucsc.hg19/ucsc.hg19.fasta -I file://data/all_data/large_test/NA12178/wgs_30x1/bam/mem_pe_T20_trios_NA12878_dedup.0810.bam -O file:/trios_NA12878_.vcf --max-alternate-alleles 2 --native-pair-hmm-threads 20 **--spark-master local[20]**

**Comment by lbergelson** [comment]
Somehow the bottom of this submission was cut off, the email from github included the following additional useful information.

> I found bug https://github.com/broadinstitute/gatk/blob/master/gatk line:146-150
> 146. if sparkMaster is not None:
> 147. i = sparkArgs.index("--spark-master")
> 148. del sparkArgs[i] #remove spark target
> 149. del sparkArgs[i] #and its parameter
> 150. gatkArgs += ["--spark-master", sparkMaster]
> 
> I think change gatkArgs to sparkArgs

**Comment by lbergelson** [comment]
@ruoshuiwyl Typically the way we've been running if you want to run with the local master is to use 
`--spark-master LOCAL`  Does that work for you?

**Comment by ruoshuiwyl** [comment]
It does not work
gatk HaplotypeCallerSpark -R /data/all_data/reference/ucsc.hg19/ucsc.hg19.2bit -I /data/all_data/large_test/NA12178/wgs_30x1/bam/mem_pe_T20_trios_NA12878_dedup.0810.bam        -O mem_pe_T20_trios_NA12878_raw_variants_gatk4_40_2.vcf        --max-alternate-alleles 2        --native-pair-hmm-threads 20        -- --spark-runner LOCAL --spark-master local[20] --spark
Using GATK jar /data/chenxi/tools/gatk-4.0.0.0/gatk-package-4.0.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar /data/chenxi/tools/gatk-4.0.0.0/gatk-package-4.0.0.0-local.jar HaplotypeCallerSpark -R /data/all_data/reference/ucsc.hg19/ucsc.hg19.2bit -I /data/all_data/large_test/NA12178/wgs_30x1/bam/mem_pe_T20_trios_NA12878_dedup.0810.bam -O /home/wangyanlong/Gatk4/mem_pe_T20_trios_NA12878_raw_variants_gatk4_40_2.vcf --max-alternate-alleles 2 --native-pair-hmm-threads 20 --spark-master local[20] --spark

**Comment by ruoshuiwyl** [comment]
OK, Thank.

**Comment by lbergelson** [comment]
Did that fix the problem?  Depending on your shell you may have to escape the local bit.

```
--spark-master `local[20]`
```

**Comment by lbergelson** [comment]
@ruoshuiwyl I'm closing this one because I haven't heard anything back.  Hopefully it fixed the problem.  If not, feel free to reopen.
