### ISSUE TITLE
Provide assortment of BAM files for compression profiling

### ISSUE THREAD

**Issue by gspowley** [broadinstitute/gatk#4249]
Related to #3413. We have improvements for BAM compression in GKL and need an assortment of various types of BAM files to test the performance and compression ratio.

**Comment by droazen** [comment]
This is done -- I've provided the GKL team with a representative assortment of bams via email, including whole genomes and exomes, binned and unbinned qual scores, and a super-deep panel bam.

**Comment by lbergelson** [comment]
Should we link to them here?  It would be nice to be able to find them again.
