### ISSUE TITLE
CNV ReadCount PoN WDL will not work on cram files...

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#4253]
A reference is required, but the task WDL does not ingest the reference given to the workflow.

Proposed solution is to simply add:

```
File ref_fasta
File ref_fasta_fai
File ref_fasta_dict
```
to the input block of `task CollectFragmentCounts`

and add 
```
ref_fasta_dict = ref_fasta_dict,
ref_fasta_fai = ref_fasta_fai,
ref_fasta = ref_fasta
```

to the `call CollectFragmentCounts`

and lastly, add `-R ${ref_fasta}` to the end of the `gatk` command in  `task CollectFragmentCounts`

**Comment by LeeTL1220** [comment]
Ditto with `CollectFragmentCounts`

**Comment by samuelklee** [comment]
Oops, did not realize that CRAM support required special treatment of the reference.  This only needs to be added as an input to the CollectFragmentCounts task, then, correct?  Why are the changes to the CreateReadCountPanelOfNormals task needed?

More generally, if we are aiming to support all CRAMs passed via -I in all relevant GATK walkers, then this is probably something that should be added to the WDL style guide.  I guess it’d be overkill to make the reference required for these walkers on the Java side.

**Comment by samuelklee** [comment]
Also, perhaps we could add CRAMs to the mix of BAMs used in the WDL tests.  Should be addressed at the same time as #4007.  However, I wouldn't want to just expand the test matrix, since those tests already run long enough.

**Comment by samuelklee** [comment]
@davidbenjamin Do you need to worry about this for M2, e.g. GetPileupSummaries?

**Comment by davidbenjamin** [comment]
I guess so.  There are a few other places where that wdl looks specifically for a .bam extension that would have to be generalized.

**Comment by samuelklee** [comment]
Also, I'm guessing any additional overhead from always requiring the reference (even for BAMs) is probably acceptable in the current pipelines, but it won't hurt to double check.

**Comment by LeeTL1220** [comment]
I modified my initial comments.  The CreatePanel task is fine as is.
