### ISSUE TITLE
BaseRecalibratorSpark: creating KnownSiteCache takes a long time on HDFS

### ISSUE THREAD

**Issue by frank-y-liu** [broadinstitute/gatk#4264]
At the beginning of BaseRecalibratorSpark, each JVM reads the given KnownSite in vcf format and create the `KnownSiteCache`.  Below is the `stdout` of this process:

```text
12:29:30.680 INFO  FeatureManager - Using codec VCFCodec to read file hdfs://n001:54310/GATK4TEST/genome/dbsnp_138.b37.vcf
12:29:31.037 INFO  KnownSitesCache - Number of variants read: 1
12:29:33.039 INFO  KnownSitesCache - Number of variants read: 100001
12:29:34.733 INFO  KnownSitesCache - Number of variants read: 200001
12:29:35.938 INFO  KnownSitesCache - Number of variants read: 300001
12:29:37.378 INFO  KnownSitesCache - Number of variants read: 400001
12:29:38.651 INFO  KnownSitesCache - Number of variants read: 500001

... ... lots of similar entries deleted ...... 

12:38:08.377 INFO  KnownSitesCache - Number of variants read: 60200001
12:38:09.341 INFO  KnownSitesCache - Number of variants read: 60300001
12:38:10.131 INFO  KnownSitesCache - Number of variants read: 60400001
12:38:10.940 INFO  KnownSitesCache - Number of variants read: 60500001
12:38:11.719 INFO  KnownSitesCache - Number of variants read: 60600001
12:38:12.568 INFO  KnownSitesCache - Number of variants read: 60700001
12:38:13.432 INFO  KnownSitesCache - Number of variants read: 60800001
12:38:14.137 INFO  KnownSitesCache - Number of variants read: 60900001
12:38:14.833 INFO  KnownSitesCache - Number of variants read: 61000001
12:39:23.200 INFO  BaseRecalibrationEngine - The covariates being used here: 
12:39:23.200 INFO  BaseRecalibrationEngine - 	ReadGroupCovariate
```
Based on the time stamps, the observation is that it took 10 min to read the KnowSites.vcf file (about 10GB), for the code which is a filtering and copy operation:

```java
private static List<GATKVariant> wrapQueryResults(final Iterator<VariantContext> queryResults ) {
     final List<GATKVariant> wrappedResults = new ArrayList<>();
     long count = 0;
     while ( queryResults.hasNext() ) {
          if (count++ % 100000 == 0) {
              log.info("Number of variants read: " + count);
          }
          wrappedResults.add(VariantContextVariantAdapter.sparkVariantAdapter(queryResults.next()));
      }
      return wrappedResults;
}

```
Seems to me this is awfully slow.  The vcf file resides on HDFS (with a 100Gbps switch and backed up by a NVMe storage with over 1GBps bandwidth). Assuming we can achieve a persistent 100MBps bandwidth (which IMO is quite modest), it would take 100 sec to fetch the file. Added the overhead, it should take only 2 to 3 minutes to finish this process.

If it turns out that IO performance cannot be improved, I have the impression that knownSites file is relatively stable. Would it make sense to convert the KnownSites into an intermediate format which can be read much faster? Or smaller than the 2GB threshold?

**Comment by lbergelson** [comment]
Yeah, this doesn't really make sense.  I think the right thing for us to do is change it to do a just in time lookup for each shard rather than try to suck the whole thing into memory.

**Comment by tomwhite** [comment]
`KnownSiteCache` is no longer used; Spark `--files` is the replacement (handled automatically).
