### ISSUE TITLE
WDL for somatic CNV PoN creation looks broken 

### ISSUE THREAD

**Issue by eitanbanks** [broadinstitute/gatk#4281]
The workflow in cnv_somatic_panel_workflow.wdl defines:
" Int? mem_gb_for_create_read_count_pon"

But when it's used in the call to CreateReadCountPanelOfNormals, the variable is referred to as "mem_for_create_read_count_pon" (i.e. no "_gb").

This causes the workflow to fail...

**Comment by samuelklee** [comment]
Yup, sorry about this---caught and fixed in #4280.  I'd maybe count this as a `womtool validate` bug...?

**Comment by samuelklee** [comment]
@eitanbanks Is the PoN WDL working for you now?

**Comment by eitanbanks** [comment]
Yes!  Thanks
