### ISSUE TITLE
PathSeqBuildReferenceTaxonomy usage example shows usage of the tool PathSeqBuildKmers

### ISSUE THREAD

**Issue by ThomasHickman** [broadinstitute/gatk#4284]
In the docs of [PathSeqBuildReferenceTaxonomy](https://software.broadinstitute.org/gatk/documentation/tooldocs/4.0.0.0/org_broadinstitute_hellbender_tools_spark_pathseq_PathSeqBuildReferenceTaxonomy), the usage example uses the command `PathSeqBuildKmers` instead of `PathSeqBuildReferenceTaxonomy`

**Comment by davidbenjamin** [comment]
@mwalker174 I stumbled on this by accident.

**Comment by mwalker174** [comment]
Thank you @ThomasHickman and @davidbenjamin. Fixed via #4911
