### ISSUE TITLE
HaplotypeCallerSpark shouldn't resort reads if they're already coordinate sorted

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4296]
currently HaplotypeCallerSpark is sorting the reads even if the header says they're coordinate sorted.  This is very expensive and should be avoided.

**Comment by droazen** [comment]
@tomwhite This seems like an easy way to get a big performance boost in `HaplotypeCallerSpark` -- what do you think?

**Comment by tomwhite** [comment]
Since #5127 HaplotypeCallerSpark only accepts coordinate-sorted reads. Closing this one.
