### ISSUE TITLE
GATK - 4.0.0.0 [BaseRecalibratorSpark low performance]

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#4300]
@chandrans commented on [Mon Jan 29 2018](https://github.com/broadinstitute/dsde-docs/issues/2881)

User reports BaseRecalibratorSpark in gatk-4.beta.6-17 took 3.79 minutes vs 40 minutes in official release.

----
User Report
----

Dear GATK_team, I'd like to run Spark-enabled GATK tools on a Spark cluster. Precisely I am launching a Spark cluster in the standalone mode submitting the `BaseRecalibratorSpark` application via Slurm. Before the official release, I was running the `gatk-4.beta.6-17` version, with the following allocated resources, and the following command line for the Spark arguments: `./gatk-launch BaseRecalibratorSpark \ --sparkRunner SPARK --sparkMaster spark://${MASTER} --driver-memory 80g --num-executors 16 --executor-memory 8g`. The speed-up achieved was 3.79 min. However, with the official release GATK-4.0.0.0, with the same datafiles and the same Spark arguments I don't see the same nice speed-up anymore (~ 40 min). Am I missing something with the new version? Or with the invoking command line? Thanks in advance for your time and kind answer. Best, Giuseppe

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/11260/gatk-4-0-0-0-baserecalibratorspark-low-performance/p1

---

@chandrans commented on [Mon Jan 29 2018](https://github.com/broadinstitute/dsde-docs/issues/2881#issuecomment-361324925)

@droazen @lbergelson Hi David and Louis. Do you have any comments? I was supposed to put this in gatk but put it in dsde-docs. Thanks

---

@droazen commented on [Mon Jan 29 2018](https://github.com/broadinstitute/dsde-docs/issues/2881#issuecomment-361342262)

@chandrans Could you move this ticket to the gatk repo so that we can remember to have a look at the tool? Someone will have to re-profile.

**Comment by chandrans** [comment]
Done here @droazen Thanks

**Comment by lbeltrame** [comment]
I can add that my (rather empirical) tests on 3.8 vs 4.0 show a noticeable increase in runtime (currently around 4-5 hours for an Agilent OneSeq enrichment on a non-AVX capable CPU). I can explain it in part with the lack of downsampling (as mentioned in the last comments of the above GH ticket), but it's still far more than what I used to see with 3.8.

Unlike the original reporter, however, I did not test the betas. Is there a standardized way to profile these results, so I can give out more concrete data?

**Comment by droazen** [comment]
There was a confirmed performance regression in `BaseRecalibratorSpark` just before the 4.0 release: https://github.com/broadinstitute/gatk/issues/4376. I suspect that's what's responsible for the results reported above.

Until this is patched (most likely in the next GATK release), I'd recommend running the regular `BaseRecalibrator` instead of the spark version.

**Comment by chandrans** [comment]
I think this can be closed. Fixed by 4.0.2.0
