### ISSUE TITLE
Feature request: joint/time-series calling for Mutect2?

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4327]
This request comes from the forum: 

Mutect2 accepts multiple _different_ tumor samples (from the same individual) and calls on each sample at the same time, much like in a time-course experiment.

Relatedly, if it's not too much to ask, I'd like to be able to provide multiple `--germline-resource` VCFs.

---
@Sheila and @shlee,
Thank you so much for referring me to the informative article and discussion!
I can't say I fully understand the technical difficulties. But I understood it is nontrivial to implement and joint somatic variant calling should be different from the joint calling of haplotypecaller. I still think it might be worthwhile for Mutect2 to be able to call somatic variants jointly on multiple tumor samples from **an** individual. It would help track somatic variants of a person over time.

By the way, the article mentioned that Mutect2 would run without a matched normal. I wonder if Mutect2 now supports the tumor only mode. I remember no variant passed filters in tumor only mode for an older version. (One the other hand, I now think tumor only calling with high false positives would be a privacy threat..)

![](https://public.media.smithsonianmag.com/legacy_blog/snowflake-growth-2.gif "")
Image credit: [Libbrecht lab](https://smithsonianmag.com/science-nature/the-art-and-science-of-growing-snowflakes-in-a-lab-180949243/)

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/45571#Comment_45571

**Comment by sooheelee** [comment]
@davidbenjamin and @takutosato straight from the forum to you.

**Comment by sooheelee** [comment]
I should mention this is likely to be challenging. As far as I'm aware, CuffDiff _attempts_ to analyze time-course experiments for RNA transcript isoforms, and has been met with criticism.

**Comment by davidbenjamin** [comment]
@sooheelee As an initial attempt to address this without too much refactoring, what about a two-step process where the user runs M2 with all samples eg `-I normal.bam -I tumor1.bam -I tumor2.bam -tumor sample1 -tumor sample2` (this would require a small code change to specify `-tumor` more than once) and then uses the common set of variants in GGA mode (PR #4601) on each sample individually?

**Comment by sooheelee** [comment]
What will the results looks like @davidbenjamin? A multi-sample VCF? For a variety of contexts outside a time course, being able to analyze multiple samples at once against the same normal control would be super useful.

**Comment by davidbenjamin** [comment]
This proposal would yield several single-sample vcfs.  But I think a less-clunky single-pass version that emits a multi-sample vcf would be doable.  Which do you prefer?

**Comment by davidbenjamin** [comment]
We're going to do this, and have opened issue #4887.
