### ISSUE TITLE
GATK should preserve Picard tool exit codes 

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#4329]
When running a Picard tool within GATK, the exit code of that Picard tool is not preserved when GATK exits.

For example, running `ExtractSequences` with no arguments produces an error and the Picard return code of `1`, but GATK returns a 0.

This seems to be around `Main.java:196` (`mainEntry`).

**Comment by magicDGS** [comment]
Maybe the way is to check the returned value inside `PicardCommandLineProgramExecutor` and throw a `PicardCommandNonZeroExit` exception containing a field with the exit code, that can be handled in `Main` with a special function (as user exception, etc.).

Tests for checking the exit code returned by `mainEntry` can be found in https://github.com/broadinstitute/gatk/pull/4283.

**Comment by droazen** [comment]
That sounds like a good way to do it @magicDGS
