### ISSUE TITLE
Evaluate GCS-enabled fork of GenomicsDB

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4331]
With @ldgauthier

**Comment by droazen** [comment]
Need to recruit a member of the engine team to assist.

**Comment by ldgauthier** [comment]
Any volunteers?  Anyone forced to volunteer?

**Comment by droazen** [comment]
@ldgauthier Sorry, it may be a week or two before we'll have bandwidth to assign someone on our side to this. Let me know if that's a problem for you.

**Comment by ldgauthier** [comment]
Nalini pinged me about this again.  Any idea when someone will have the time?

**Comment by droazen** [comment]
We're a little short on time right now with the end of the quarter coming up, unfortunately. I wonder if @kgururaj or a member of his team would have time to set up a GATK branch built against the fork that you would then be able to evaluate.

**Comment by droazen** [comment]
I'll ask @kgururaj next week about this @ldgauthier. If his team doesn't have time, we'll assign someone from the engine team to spend a day this month getting a branch set up for evaluation purposes.

**Comment by ldgauthier** [comment]
Great, thanks!

**Comment by droazen** [comment]
Update on this: @kgururaj will try to provide us with a GATK branch that uses the GenomicsDB fork this week, and ask Gans's team for help if he's not able to build it himself.

**Comment by droazen** [comment]
We did this -- closing.
