### ISSUE TITLE
Optionally copy FASTQ's in `scripts/sv/copy_sv_results.sh`

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/gatk#4332]
And in `scripts/sv/manage_sv_pipeline.sh`.

As suggested by @cwhelan when reviewing PR #4328 

> One suggested feature enhancement if you feel like it while you're working on these scripts: most of the time I don't want to write out and copy all of the fastq files for the assemblies (mostly because it takes a long time to copy them out of the cluster), but occasionally I do. It would be nice if the scripts by default didn't move the fastqs (this could be accomplished either by not writing them or by excluding them from the copy -- @TedBrookings didn't you have code that did the latter before?), but had an optional flag to enable them.

@TedBrookings assigning to you for now, but it may not be a priority.

**Comment by TedBrookings** [comment]
I used to have it in there, but once I got copy performance up I assumed it was just clutter. I need to make a minor update to the scripts anyway (option to run the debug program instead of the full pipeline) so I can put back the option to not copy fastq files as well.

**Comment by SHuang-Broad** [comment]
closed by #4385
