### ISSUE TITLE
Duplicate records in VCF produced by CalculateGenotypePosteriors

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#4346]
### Affected tool(s)
CalculateGenotypePosteriors

### Affected version(s)
4.0.1.1

### Description 
The input VCF only contains 1 record for the position, but after running CalculateGenotypePosteriors, the output VCF contains 2 records for the position.

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/11278/duplicate-records-after-calculategenotypeposteriors/p1

**Comment by chandrans** [comment]
@lbergelson Thanks a lot for being so fast with this :)

**Comment by ameynert** [comment]
Just to report I have observed this behaviour with version 4.0.1.2 as well.

**Comment by lbergelson** [comment]
the fix still isn't merged

**Comment by lbergelson** [comment]
@ameynert The fix just went in. It will be in the next release.
