### ISSUE TITLE
Funcotator - Need to have a funcotation output list

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#4359]
Must allow support for an output funcotation list that, if specified, will cause Funcotator only output funcotations from the given list and suppress all other funcotations.

**Comment by jonn-smith** [comment]
This is related to #4583 - that issue must be done before this one is worked on.

**Comment by LeeTL1220** [comment]
Make sure that this is supported in #4581 

- Add a CLI flag `--exclude-field-name` which can be specified multiple times.
For example `... --exclude-field-name Clinvar_bar --exclude-field-name Clinvar_foo ...`

We will specify the column names with the full field name:  `<datasourcename>_<fieldname>`

For now, we specify via an `exclude`.  If nothing is specified, then show everything.

- Make sure that this new parameter is integrated into the config file framework as implemented by #4581

**Comment by jonn-smith** [comment]
Put exclusion list into OutputRenderer at construction time, then check on `write`.
