### ISSUE TITLE
GATK 3.7 and GATK 4 HaplotypeCaller runtime 

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#4361]
User has tested GATK3.7 HaplotypeCaller and GATK4 HaplotypeCaller. GATK4 takes ~35 hours while GATK3.7 takes about 18 hours. Original report is here: https://github.com/broadinstitute/gatk/issues/3631 David, I assigned you just so you could take a look. User seems satisfied that GATK4 is faster, but I am just making sure this is expected. I asked for more details on what type of data they are using and whether Spark version is faster (assuming this is from non-Spark version). 

----
User Report
----

@Sheila,

Hi Sheila,

I repeated the experiment with GATK4.0.0 version. The performance is much better than GATK4beta5 version. Here are the logs: 

$ tail -400 NA12892.HaplotypeCaller.err
Using GATK jar /gpfs/software/genomics/GATK/4.0.0/gatk-package-4.0.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar /gpfs/software/genomics/GATK/4.0.0/gatk-package-4.0.0.0-local.jar HaplotypeCaller --reference /gpfs/data_jrnas1/ref_data/Hsapiens/hs37d5/hs37d5.fa --input /gpfs/projects/NAGA/naga/NGS/pipeline/GATK_Best_Practices/GATK4.0.0/NA12892/bam/NA12892.recal.bam --dbsnp /gpfs/data_jrnas1/ref_data/Hsapiens/GRCh37/variation/dbsnp_138.vcf.gz --emit-ref-confidence GVCF --read-validation-stringency LENIENT --native-pair-hmm-threads 32 --output /gpfs/projects/NAGA/naga/NGS/pipeline/GATK_Best_Practices/GATK4.0.0/NA12892/vcf/NA12892.raw.snps.indels.g.vcf
[January 26, 2018 1:09:58 AM AST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: **2,133.48 minutes**.
Runtime.totalMemory()=2183659520
real 128010.56
user 436969.62
sys 3030.18

Thanks and Regards,
Naga

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/45634#Comment_45634

**Comment by droazen** [comment]
@chandrans Please ask the user to repeat the test, with the following adjustments:

* Run both GATK 3.7 and GATK 4.0.1.1 (latest release) on the same machine, one right after another, on chromosome 20 only (using `-L` in both cases), and ensure that there are no other expensive processes running on this machine during the tests. Run each version 3 times, and take the average of the results.
* Add `-pairHMM AVX_LOGLESS_CACHING` to both the GATK3 and GATK4 command lines, to guarantee that the native PairHMM will be used in both cases.
* Get rid of the `--native-pair-hmm-threads 32` in the GATK 4 command line. Too many threads can sometimes make performance worse by introducing too much contention.
* Check both the GATK3 and GATK4 output to ensure that the Intel inflater and deflater were used in both cases.
* Check both the GATK3 and GATK4 command lines to be sure they are equivalent (eg., if one is running with -ERC GVCF, the other one should as well).
* Compute wall-clock time by running the Unix `time` command, if the user is not already doing so (eg., `time ./gatk HaplotypeCaller....`

**Comment by chandrans** [comment]
Thanks David. Will let you know when they get back.

**Comment by yuntwang** [comment]
Can I know the result?

I compare  the version GATK(4.0.2.1)  with the version GATK(3.8) in the HaplotypeCaller.

And found the GATK4 is slower than GATK3.8.

**Comment by davidbenjamin** [comment]
The wall-clock time of waiting for the user has exceeded 17,000 hours.
