### ISSUE TITLE
Mutect 2 B38 germline resource

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4366]
Quick forum question for @davidbenjamin @takutosato. How to set `--af-of-alleles-not-in-resource` for WGS data when coverage in gnomAD resource is combination of WES and WGS?

---
Thanks a lot @shlee for the information. Can you point me towards where the README is? I suspected the liftover might be more involved than it appears (it explains why one isn't already floating around) and it would be good to understand how you've done it.  Can I ask why you don't recommend cross-map? 

Looking at your tutorial you suggest altering --af-of-alleles-not-in-resource for exome data. What would you recommend for whole genomes - which would include non-coding regions only covered by the 16k and coding regions covered by the ~200,000?

Thanks again

Dan

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/45767#Comment_45767

**Comment by davidbenjamin** [comment]
@sooheelee That's a pitfall we haven't solved yet.  I think we'll eventually infer the value locally from the AC of nearby variants in the germline resource.  Until then, I would use the smaller value i.e. the one for coding regions.  The only possible harm would be a very few rare germline events that aren't in gnomAD, whereas if you set it too high you risk filtering true somatic events.

**Comment by sooheelee** [comment]
I've passed the word along. Thank you.
