### ISSUE TITLE
Tools marked as @BetaFeature/@ExperimentalFeature should output a warning when run

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4367]
The warning should state that the tool is in a beta/experimental state, and should not be used for production work.

**Comment by droazen** [comment]
@cmnbroad Could you get a PR in for this by Friday, if possible? I'd like to include it in the next point release.

**Comment by cmnbroad** [comment]
I'll have something shortly.

**Comment by cmnbroad** [comment]
Reopening as a placeholder since we really need t do this in Picard as well.

**Comment by droazen** [comment]
Closing -- this was done.
