### ISSUE TITLE
Default read filters are not included in tool doc

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#4387]
This worked until we kebabified. The Freemarker template looks for the hardcoded string "readFilter", but the doc system populates the Freemarker map using the display name self-reported by the (ReadFilter) plugin, which is in turn derived from the standard argument name for read filters. These matched when the arg was "readFilter". But after kebabification, its now "read-filter". We should probably change the plugins to use a fixed display.

**Comment by cmnbroad** [comment]
We should fix this - the current behavior is misleading and causing (understandable) confusion https://gatkforums.broadinstitute.org/gatk/discussion/12285/about-read-filters.

**Comment by bhanugandham** [comment]
Hi Chris,

We have a user enquiring about  an update on this issue. Do we have a timeline for this?

**Comment by cmnbroad** [comment]
I have a fix so it should be able to go into 4.1.

**Comment by bhanugandham** [comment]
Thanks Chris.
