### ISSUE TITLE
gcnvkernel/tasks/inference_task_base.py

### ISSUE THREAD

**Issue by wujh2017** [broadinstitute/gatk#4389]
Hi
      I wanna call germline CNVs using GATK4,but now have a problem when i was runing newest DetermineGermlineContigPloidy.here is err info.

**>>> import gcnvkernel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/NfsDir/UserDir/wujh/Biosoft/Anaconda3/lib/python3.5/site-packages/gcnvkernel/__init__.py", line 5, in <module>
    from .tasks.inference_task_base import HybridInferenceParameters
  File "/opt/NfsDir/UserDir/wujh/Biosoft/Anaconda3/lib/python3.5/site-packages/gcnvkernel/tasks/inference_task_base.py", line 244
    self.temperature: types.TensorSharedVariable = th.shared(
                    ^
SyntaxError: invalid syntax**

here is the code 
**240         _logger.info("Setting up DA-ADVI...")
241         with self.continuous_model:
242             if not hasattr(self, 'temperature'):
243                 initial_temperature = self.hybrid_inference_params.initial_temperature
244                 self.temperature: types.TensorSharedVariable = th.shared(
245                     np.asarray([initial_temperature], dtype=types.floatX))
246             initial_temperature = self.temperature.get_value()[0]
247             if (np.abs(initial_temperature - 1.0) < self.temperature_tolerance or
248                     hybrid_inference_params.disable_annealing):**

anyone can give me some suggestion ????

**Comment by samuelklee** [comment]
@wujh2017 Did you set up the appropriate conda environment as described in the README?

> Python 3.6.2, along with a set of additional Python packages, are required to run some tools and workflows. GATK uses the Conda package manager to establish and manage the environment and dependencies required by these tools. The GATK Docker image comes with this environment pre-configured. In order to establish an environment suitable to run these tools outside of the Docker image, the conda gatkcondaenv.yml file is provided. To establish the conda environment locally, Conda must first be installed. Then, create the gatk environment by running the command conda env create -n gatk -f gatkcondaenv.yml (developers should run ./gradlew createPythonPackageArchive, followed by conda env create -n gatk -f scripts/gatkcondaenv.yml from within the root of the repository clone). To activate the environment once it has been created, run the command source activate gatk. See the Conda documentation for additional information about using and managing Conda environments.

**Comment by mbabadi** [comment]
@wujh2017 thank you for trying out this beta tool! As @samuelklee mentioned above, your issue is most likely due to not having the proper python conda env (most likely, you have a python 2.x in your system environment). 

Also, I would like to add that the default parameters for running the Germline CNV calling pipeline are currently being fine-tuned separately for WES and WGS data. The default parameters shipped with GATK 4.0.0.0 are preliminary and are not expected to yield optimal results.

**Comment by wujh2017** [comment]
@samuelklee 
        Thanks for your reply. I have solved the problem by setting up  gatk environment(running the command conda env create -n gatk -f gatkcondaenv.yml ).
        But now i have another problem  like this :
**python exited with 1
Command Line: python /tmp/wujh/cohort_denoising_calling.2811237809986304051.py --ploidy_calls_path=DetermineGermlineContigPloidy/test-calls/ --output_calls_path=GermlineCNVCaller/S30_cohort_run-calls --modeling_interval_list=/tmp/wujh/intervals8089007129860424044.tsv --output_model_path=GermlineCNVCaller/S30_cohort_run-model --enable_explicit_gc_bias_modeling=False --read_count_tsv_files /tmp/wujh/sample-08626640858001005110.tsv /tmp/wujh/sample-1339552300304625236.tsv /tmp/wujh/sample-28118361671858104996.tsv /tmp/wujh/sample-35451430264553463139.tsv --psi_s_scale=1.000000e-04 --mapping_error_rate=1.000000e-02 --depth_correction_tau=1.000000e+04 --q_c_expectation_mode=hybrid --max_bias_factors=5 --psi_t_scale=1.000000e-03 --log_mean_bias_std=1.000000e-01 --init_ard_rel_unexplained_variance=1.000000e-01 --num_gc_bins=20 --gc_curve_sd=1.000000e+00 --active_class_padding_hybrid_mode=50000 --enable_bias_factors=True --disable_bias_factors_in_active_class=False --p_alt=1.000000e-06 --cnv_coherence_length=1.000000e+04 --max_copy_number=5 --p_active=0.010000 --class_coherence_length=10000.000000 --learning_rate=5.000000e-02 --adamax_beta1=9.000000e-01 --adamax_beta2=9.900000e-01 --log_emission_samples_per_round=50 --log_emission_sampling_rounds=10 --log_emission_sampling_median_rel_error=5.000000e-03 --max_advi_iter_first_epoch=100 --max_advi_iter_subsequent_epochs=100 --min_training_epochs=10 --max_training_epochs=50 --initial_temperature=2.000000e+00 --num_thermal_epochs=20 --convergence_snr_averaging_window=500 --convergence_snr_trigger_threshold=1.000000e-01 --convergence_snr_countdown_window=10 --max_calling_iters=10 --caller_update_convergence_threshold=1.000000e-03 --caller_admixing_rate=7.500000e-01 --disable_caller=false --disable_sampler=false --disable_annealing=false
Stdout: 16:08:22.897 INFO cohort_denoising_calling - Loading 4 read counts file(s)...
16:08:25.950 INFO gcnvkernel.io.io_metadata - Loading germline contig ploidy and global read depth metadata...

Stderr: Traceback (most recent call last):
  File "/tmp/wujh/cohort_denoising_calling.2811237809986304051.py", line 114, in <module>
    n_st, sample_names, sample_metadata_collection)
  File "/opt/NfsDir/BioDir/Anaconda3/lib/python3.6/site-packages/gcnvkernel/models/model_denoising_calling.py", line 377, in __init__
    sample_metadata_collection, sample_names, self.contig_list)
  File "/opt/NfsDir/BioDir/Anaconda3/lib/python3.6/site-packages/gcnvkernel/models/model_denoising_calling.py", line 584, in _get_baseline_copy_number_and_read_depth
    **"Some samples do not have read depth metadata"**
AssertionError: Some samples do not have read depth metadata

        at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)
        at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:151)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:121)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.executeGermlineCNVCallerPythonScript(GermlineCNVCaller.java:448)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.doWork(GermlineCNVCaller.java:286)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:275)
Using GATK jar /opt/NfsDir/BioDir/GATK4/gatk420180130/gatk-master/build/libs/gatk-package-unspecified-SNAPSHOT-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar /opt/NfsDir/BioDir/GATK4/gatk420180130/gatk-master/build/libs/gatk-package-unspecified-SNAPSHOT-local.jar GermlineCNVCaller --run-mode COHORT -L 20130108.exome.interval_list --contig-ploidy-calls DetermineGermlineContigPloidy/test-calls/ --input Sample/NIST7035_1_fragmentcounts.hdf5 --input Sample/NIST7035_2_fragmentcounts.hdf5 --input Sample/NIST7086_1_fragmentcounts.hdf5 --input Sample/NIST7086_2_fragmentcounts.hdf5 -imr OVERLAPPING_ONLY --output GermlineCNVCaller --output-prefix S30_cohort_run**
        In my test, I added 30 samples to build sample pool. But it seems only 24 samples are used as follows, I wonder whether this might be the problem. If not, what can be the reason you think? 
Details are as follows,
**drwxr-xr-x 32 groupdcits 4096 Feb 23 10:25 change30-calls
drwxr-xr-x  2 groupdcits 4096 Feb 23 10:25 change30-model
[tele-6 DetermineGermlineContigPloidy30]$ ll change30-calls/
total 0
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_0
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_1
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_10
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_11
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_12
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_13
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_14
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_15
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_16
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_17
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_18
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_19
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_2
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_20
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_21
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_22
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_23
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_24
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_25
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_26
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_27
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_28
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_29
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_3
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_4
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_5
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_6
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_7
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_8
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_9
** 
**
less -S change30-model/mu_mean_bias_j_lowerbound__.tsv
## @shape=(24,)
@dtype=float64
0.019458835809044867
0.031170431276168496
0.031063834325466548
-0.053430597788607564
0.028991976776819313
0.03188641042191654
0.025744730251853483
-0.044683440580166059
-0.038202707908613423
0.039446858245067919
0.027734188731645144
-0.037494123601623915
-0.031763923523433074
0.031717803459495424
0.029446966097923417
-0.042422887245494631
0.024412305218945277
-0.031389153909177715
-0.025703579689687561
-0.024220041223810457
-0.031458386250220551
-0.02899769747610664
0.014783173073955026
-0.004379005066713005
**
PS:The reads number of samples in the pool have a big difference
