### ISSUE TITLE
M2 WDL defaults to nonsensical oncotator docker image

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#4391]
This used to work fine.  The default oncotator docker image should be:

"broadinstitute/oncotator:1.9.6.1"

No optional WDL parameters should be specified in such a way as to make it fail automatically.  Then it is not actually optional.

@davidbenjamin

**Comment by LeeTL1220** [comment]
@davidbenjamin Can this issue be closed?

**Comment by davidbenjamin** [comment]
Closed by #4394.
