### ISSUE TITLE
Trobule with best practices 

### ISSUE THREAD

**Issue by erarroji** [broadinstitute/gatk#4392]
Hi

I'am new with all NGS tools, I tried to follow best practices workflow for my exome reads from tumor samples: I align with bwa mem, sort with samtools, mark duplicates and recalibrated bases with GATK 4 and finally call variants with Mutect 2. Although the software run successfully I noticed that the mark duplicates metrics only have a 0.3% of duplicates, which I double check with samtools flagstat. So I marked duplicates with samtools, from the same bam, which give a 30% of duplicates. 
Later when I did the variant calling the output from the bam mark with samtools was of 297061 mutations againts 50370 from the bam mark with GATK.
I am not sure which file is the right one. What could I be doing wrong? How can I make sure which file is worked correctly?.

Thank you.
Ernesto Rojas

**Comment by droazen** [comment]
@erarroji Can you give us more information about exactly which GATK4 tools you are running in your pipeline? Some GATK4 tools (such as `MarkDuplicatesSpark` and `HaplotypeCallerSpark`) are still marked as `beta` and may not always give correct output. You should use the non-beta versions of these tools instead (eg., `MarkDuplicates` and `HaplotypeCaller`). 

You can see which tools are marked as `beta` by running: `./gatk --list`

**Comment by sooheelee** [comment]
@erarroji, please post your GATK/Picard questions to the GATK forum at https://gatkforums.broadinstitute.org/gatk/discussions.

To answer your question, see:
https://software.broadinstitute.org/gatk/blog?id=7264

**Comment by erarroji** [comment]
Hi 

I already post the question on GATK forum, also my fraction of duplicates is 0.000384 which I double check with samtools flagstat calculating from the output values.
