### ISSUE TITLE
New germline CNV and SV methods for new Ehlers-Danlos research announced today

### ISSUE THREAD

**Issue by nyl2002** [broadinstitute/gatk#4398]
I would like to make recommendations for how to best use GATK4's new CNV, SV and maybe CNN capabilities to the research project about Hypermobile Ehlers-Danlos Syndrome, that was announced today.
https://www.ehlers-danlos.com/ehlers-danlos-society-receives-transformational-gift-accelerate-genomic-research-hypermobile-eds/

I think that hEDS could an interesting applications for the new tools. It is usually not deadly and also highly complex and has interestingly many comorbidities.

Does anyone have any ideas?

It would be interesting to look at RCCX/TNXB (one of the known genes for Ehlers-Danlos variants) alt contigs with the new SV methods. I have posted in the bwa github to ask about how to best add RCCX/TNXB alt contigs to bwa.

There is also known dosage sensitive pathogenicity for related genes, so that could be interesting for the germline CNV tools.
Example:
https://www.ncbi.nlm.nih.gov/projects/dbvar/clingen/clingen_gene.cgi?sym=COL1A1&subject=

Hypermobility (the core symptom of Ehlers-Danlos) is multi-genic trait for which dosage sensitive effects could be easily observable and measurable.

**Comment by samuelklee** [comment]
Thanks, @nyl2002---perhaps discussion could continue in the GATK forum?
