### ISSUE TITLE
Docker build script should not run "gradle installAll"

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4409]
The current docker build script runs `gradle installAll` in addition to running `localJar`. This causes the `gatk` script in our docker image to prefer running with the unpackaged set of jars, instead of the fully packaged jar. This, in turn, can cause us to run out of file handles in certain tools, since we need to open all of the jars for our dependencies individually at once.

We should just run something like `gradle clean localJar sparkJar createPythonPackageArchive` in our `Dockerfile`, and avoid `installAll`

**Comment by lbergelson** [comment]
Is this a problem in docker? We control the image so it should have plenty of file handles available.

**Comment by droazen** [comment]
There's no reason to even risk it becoming a problem in the future -- let's just include the fully-packaged jars in the docker image (since that is our standard binary distribution format anyway).

**Comment by droazen** [comment]
This was fixed
