### ISSUE TITLE
GATK4 FeatureInput vs. GATK3 RodBinding default names

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#4426]
In GATK3, when a tool required a VCF/ROD file as an argument, it typically used RodBinding.  For example, VariantEval.evals.  When arguments are parsed, if no name is provided in the path (such as 'foo' in foo:/path/to/myVCF.vcf), then the argument name gets used as the RodBinding name.  This happens in ArgumentTypeDescriptor ~line 328.

In GATK, FeatureInput handles the analogous situation ~line 190, which defers to ParsedArgument.of().  If no name is provided in the argument (i.e. 'foo:/path'), then it uses the full path of the VCF/ROD as the name.  I'm not sure if either is strictly right or wrong, but is this a deliberate change, and if so, why?

This is relevant b/c I'm working to port VariantEval to GATK4 and VariantEval relied on this behavior for the evals, dbsnp and comps arguments.

**Comment by droazen** [comment]
@bbimber Yes, this was a deliberate change, as it seemed better to provide each `FeatureInput` with a unique default name in the case of an argument of type `List<FeatureInput>`. However, I don't think that any code in GATK4 actually relies on the fact that the default name is equal to the path, so we might possibly be persuaded to change the default back if you can make a strong case for it and it's causing major problems for your port of `VariantEval`.

Do you currently have a viable workaround for this issue? `VariantEval` has its `FeatureInputs` already separated by argument, so it should be possible to work around this for now, I would think.

I should also mention that there are plans to eventually migrate from the current argument tagging scheme in `FeatureInput` to the more generic argument tagging supported by our arg-parsing library barclay (see https://github.com/broadinstitute/gatk/issues/2473). When this migration happens, the tags will once again be part of the argument name, as they were in GATK3, rather than the argument value (eg., `--arg:tag value` instead of `--arg tag:value`)

**Comment by bbimber** [comment]
I can see why you'd change this; however, it breaks this particular legacy tool.  VariantEval uses those labels to populate columns in the reports is creates.  In GATK3, if there is no user-supplied label on in the argument, it will simply use the argument name, which ends up being either eval, comp or dbsnp.  Those strings end up in most reports that are created.  Switching these to the filepath doesnt strictly break function, but it's a lot less friendly to look at and doesnt add much value in most cases.

Generally speaking, I agree there isnt much of a reason for a tool to reply on those user-supplied names as much of anything beyond a label.  However, if this is essentially just a label, is there a situation where non-unique names is actually a problem?  A tool probably shouldnt rely on this user-supplied value as a way to uniquely find an input.  If this value if generally being used for things like populating user-facing values in a reports, having this extremely long filepath as the name isnt exactly user friendly.  If a given tool accepts a list of FeatureInputs, it would seem like it's the responsibility of that developer to make sure that tools deals with the potential of overlapping labels appropriately.

Perhaps a solution is to delegate some of this behavior back to the argument definition?  A few thoughts/comments:

1) Is there any reason name can't just be NULL (instead of file URI) if nothing was supplied, instead of filepath?  

2) Similar to 1, if FeatureInputs somehow tracked whether there was actually a user-supplied name or if name was NULL (defaulting to filename), then upstream code could potentially use this information to change behavior.

3) While this if more involved, perhaps ParsedArgument.of() could take another nullable "defaultName" argument, and if there is no user-supplied name in the argument value and if defaultName is non-null then it is used as the FeatureInput name instead of filepath?  Then perhaps through either a flag in the tool, or better yet some flag in the @Argument annotation, the developer could specify that argument name should be passed in as the defaultValue?  This doesnt seem like it would be a huge task, but it would require changes in barclay to implement and touches a number of low-level classes.  

Again, I dont personally feel all that strongly about what's right here and i have generally barely made use of the labeling feature.  This just is a backwards compatibility question for at minimum VariantEval and maybe other GATK3 tools.

**Comment by bbimber** [comment]
Also - you asked about workarounds.  The attached is not pretty, but it is a minimal way to let tools like VariantEval provide their old behavior.  It essentially adds a method in FeatureInput to check whether the name matches the default value it would use.  Upstream code can call FeautreInput.isUserSuppliedName() and act accordingly.  Rather than use the scheme I do here with string matching, we could make it more explicit in ParsedArgument and actually pass a boolean it we detected one in the parsed argument value.  Not necessarily advocating this as a production solution, just as one way to make it work
[FeatureInputWorkaround.patch.txt](https://github.com/broadinstitute/gatk/files/1745946/FeatureInputWorkaround.patch.txt)
.

**Comment by bbimber** [comment]
One other related bit of information:

From what i can see, there's two different patterns in GATK4.  For example, VariantWalker has the user provide a String drivingVariantFile, which is later initialized as:

drivingVariantsFeatureInput = new FeatureInput<>(drivingVariantFile, "drivingVariantFile");

The only reason I can see not to declare this as a FeatureInput in the arugment is so the custom name can get added.  A more direct path from Argument definition to named feature might have general value beyond our VariantEval legacy case.

**Comment by cmnbroad** [comment]
Closing as obsolete (partly resolved via https://github.com/broadinstitute/gatk/pull/4495 and partly replaced by https://github.com/broadinstitute/gatk/issues/5439)
