### ISSUE TITLE
Picard tools report 0 for exit code even if they fail

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#4433]
I think this user report sums it up nicely.

----
User Report
----

In my BASH scripts I often use "$?" to monitor the exit status of a process and normally stop if there is an error. However, I am using the latest version of GATK (4.0.0.0) and some tools return 0 exit status even if they fail. Instead, they display the following message to STDOUT:
    
    Tool returned:
    1

Though inconvenient for error handling in BASH scripts, this might be an intended behaviour, but not all tools exhibit it. To mention a few, MarkDuplicates, CollectMultipleMetrics, CollectGcBiasMetrics always have a 0 exit status, whereas VariantsToTable or CountVariants do return 1 if they encounter an error. 

A similar issue had been reported in the past for previous versions of GATK (https://gatkforums.broadinstitute.org/gatk/discussion/8618/error-handling-end-exit-codes-in-gatk).

Best regards,

Roger

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/11414/exit-codes-in-gatk-4-0/p1

**Comment by cmnbroad** [comment]
Yes, the return value for Picard tools are not propagated properly when run through GATK. We'll try to get the fix in for the next release. Closing as a dup of https://github.com/broadinstitute/gatk/issues/4329.

**Comment by chandrans** [comment]
Thanks Chris. Did not realize this was a duplicate.
