### ISSUE TITLE
Creating a dummy FeatureInput in GATK4?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#4440]
VariantEval compares input VCF(s) to comparison tracks(s).  One can execute the tool without providing comparison tracks.  In GATK3, when no comps are provided, the tool creates a dummy RODBinding, not backed by a file.  This is passed through the downstream code in the tool.  In GATK4, RODBinding has become FeatureInput.  Is there a way to replicate this dummy FeatureInput behavior in GATK4?  I dont see a way to do this in GATK4, since FeatureInput needs a valid filepath.

I think I can rework VariantEval to come up w/ a different solution than this dummy binding; however, thought I'd ask here first.

**Comment by cmnbroad** [comment]
Closing as obsolete.
