### ISSUE TITLE
StreamingPythonScriptExecutor: explore use of a 2nd FIFO for synchronization (instead of relying on the Python prompt)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4444]
Use of the second FIFO should be encapsulated behind an easy-to-use API on the Python side, perhaps with methods such as "writeBatchOutput" that would both write a batch's worth of output and signal to Java that the batch is done using the second FIFO.

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/4757.
