### ISSUE TITLE
GATK3 RodWalker vs. GATK4 LocusWalker/VariantWalker

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#4447]
I am looking into porting VariantEval to GATK4.  In GATK3, this used RodWalker, which basically iterated all covered sites, driven by a ROD file.  A VCF is typically a pretty sparse file, so you end up with large stretches of non-covered positions of the genome.  In GATK3, RodWalker / AlignmentContext explicitly tracked getSkippedBases(), which seems designed to allow tools to track stretches of REF sites.  VariantEval in GATK3 relied on AlignmentContext.getSkippedBases() to count the number of loci it processed, for example.  In GATK4, VariantWalker simply iterates over the sites in the VCF.  Am I missing an analog, and/or is there a design reason why GATK4 does not track something akin to GATK3's getSkippedBases()?

I dont fully know the implications for parallelization, but if VariantWalker tracked something like lastProcessedSite, then this would effectively provide the same information as GATK3's AlignmentContext.

**Comment by bbimber** [comment]
In the way VariantEval uses this, another way to think about this problem is to determine the difference between the theoretically requested intervals (either the size of the reference genome, or limited by -L), and the # of sites actually iterated.  Can code in a Walker easily figure that out?  It seems like TraversalParameters.getIntervalsForTraversal(), which is a list of intervals, would provide this?

**Comment by lbergelson** [comment]
@bbimber There's no principled reason why it doesn't have a getSkippedBases() call.  It just wasn't implemented because we didn't know if there was demand for it.  You're the second person who wants it though, so we should probably add it.  In the meantime it's very easy to do it yourself by saving the last variant you saw in a field.

**Comment by bbimber** [comment]
Alright.  Are there parallelization implications if I try to stash this in a field?

**Comment by lbergelson** [comment]
No problems. The walkers have no built in parallelism so there's no problem with using state.  It makes it harder to adapt to spark, but that's probably not a big deal.

**Comment by bbimber** [comment]
alright.  in this situation, I am pretty sure that even though GATK3 VariantEval tracked this value using getSkippedBases(), I'm pretty sure it can be inferred using the total size of intervals requested (either user-supplied or the size of genome).  At least so far I can find a situation where this isnt accurate.  This saves needing to stash the value, should it ever get some kind of parallelization.
