### ISSUE TITLE
VariantWalker doesnt respect -L?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#4449]
Unless I'm misreading the code, doesnt VariantWalker ignore any restrictions the user supplies using -L?  In VariantWalkerBase.traverse(), it doesnt seem to factor in intervalsForTraversal.  

Would creating/adding some kind of VariantIntervalFilter that is constructed with intervalsForTraversal and added to the stream/forEach be the right solution?

**Comment by droazen** [comment]
@bbimber `VariantWalker` definitely respects `-L`. Only variant records that overlaps the `-L` intervals get passed to `apply()`. The `intervalsForTraversal` get set on the driving variants input in `VariantWalker.onStartup()`

**Comment by bbimber** [comment]
yes, you're right.  i was misinterpreting something in the VariantEval output.
