### ISSUE TITLE
VariantAnnotator, RankSumAnnotation for pileup data should not compute the stratified pileup over Indels

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#4452]
In keeping concordance with gatk3, when computing the RankSumAnnotation for pileups when the likelihoods map is not available we attempt to match the bases of the reads to the allele in the variant context. This is problematic if the variant is not a snp. For most other annotations we explicitly only compute the annotation for SNPs in this case, but in order to mimic gatk3 behavior it will still attempt to compute the rank sum over indels. This should be evaluated and changed. 

Related to #4450, #3803

**Comment by davidbenjamin** [comment]
Closed by #6172.
