### ISSUE TITLE
GermlineCNVCaller

### ISSUE THREAD

**Issue by wujh2017** [broadinstitute/gatk#4457]
Hi
## I have a problem when i was runing GermlineCNVCaller of GATK4 beta.The detail as followed.
**
Command Line: python /tmp/wujh/cohort_denoising_calling.7794651839449939395.py --ploidy_calls_path=DetermineGermlineContigPloidy30/change30-calls/ --output_calls_path=GermlineCNVCaller30/S30_cohort_run-calls --modeling_interval_list=/tmp/wujh/intervals7463528925479894950.tsv --output_model_path=GermlineCNVCaller30/S30_cohort_run-model --enable_explicit_gc_bias_modeling=False --read_count_tsv_files /tmp/wujh/sample-01816723514568532186.tsv /tmp/wujh/sample-13107068168629701107.tsv /tmp/wujh/sample-27833035991451357507.tsv /tmp/wujh/sample-34834664875327254000.tsv --psi_s_scale=1.000000e-04 --mapping_error_rate=1.000000e-02 --depth_correction_tau=1.000000e+04 --q_c_expectation_mode=hybrid --max_bias_factors=5 --psi_t_scale=1.000000e-03 --log_mean_bias_std=1.000000e-01 --init_ard_rel_unexplained_variance=1.000000e-01 --num_gc_bins=20 --gc_curve_sd=1.000000e+00 --active_class_padding_hybrid_mode=50000 --enable_bias_factors=True --disable_bias_factors_in_active_class=False --p_alt=1.000000e-06 --cnv_coherence_length=1.000000e+04 --max_copy_number=5 --p_active=0.010000 --class_coherence_length=10000.000000 --learning_rate=5.000000e-02 --adamax_beta1=9.000000e-01 --adamax_beta2=9.900000e-01 --log_emission_samples_per_round=50 --log_emission_sampling_rounds=10 --log_emission_sampling_median_rel_error=5.000000e-03 --max_advi_iter_first_epoch=100 --max_advi_iter_subsequent_epochs=100 --min_training_epochs=10 --max_training_epochs=50 --initial_temperature=2.000000e+00 --num_thermal_epochs=20 --convergence_snr_averaging_window=500 --convergence_snr_trigger_threshold=1.000000e-01 --convergence_snr_countdown_window=10 --max_calling_iters=10 --caller_update_convergence_threshold=1.000000e-03 --caller_admixing_rate=7.500000e-01 --disable_caller=false --disable_sampler=false --disable_annealing=false
Stdout: 10:35:09.182 INFO cohort_denoising_calling - Loading 4 read counts file(s)...
10:35:12.176 INFO gcnvkernel.io.io_metadata - Loading germline contig ploidy and global read depth metadata...
sample_names

Stderr: Traceback (most recent call last):
  File "/tmp/wujh/cohort_denoising_calling.7794651839449939395.py", line 114, in <module>
    n_st, sample_names, sample_metadata_collection)
  File "/opt/NfsDir/BioDir/Anaconda3/lib/python3.6/site-packages/gcnvkernel/models/model_denoising_calling.py", line 379, in __init__
    sample_metadata_collection, sample_names, self.contig_list)
  File "/opt/NfsDir/BioDir/Anaconda3/lib/python3.6/site-packages/gcnvkernel/models/model_denoising_calling.py", line 586, in _get_baseline_copy_number_and_read_depth
    "Some samples do not have read depth metadata"
AssertionError: Some samples do not have read depth metadata

        at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)
        at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:151)
        at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:121)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.executeGermlineCNVCallerPythonScript(GermlineCNVCaller.java:416)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.doWork(GermlineCNVCaller.java:255)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:136)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
        at org.broadinstitute.hellbender.Main.main(Main.java:275)
Using GATK jar /opt/NfsDir/BioDir/GATK4/gatk4/gatk-package-4.0.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar /opt/NfsDir/BioDir/GATK4/gatk4/gatk-package-4.0.0.0-local.jar GermlineCNVCaller --run-mode COHORT -L 20130108.exome.interval_list --contig-ploidy-calls DetermineGermlineContigPloidy30/change30-calls/ --input Sample/NIST7035_1_fragmentcounts.hdf5 --input Sample/NIST7035_2_fragmentcounts.hdf5 --input Sample/NIST7086_1_fragmentcounts.hdf5 --input Sample/NIST7086_2_fragmentcounts.hdf5 -imr OVERLAPPING_ONLY --output GermlineCNVCaller30 --output-prefix S30_cohort_run
**
## I have added 30 samples to build sample pool and those samples have a big difference of reads num. But it seems just 24 samples are used.i'm not sure what happend .So can you give me some suggestion ?Detail followed.
**
drwxr-xr-x 32 wujh groupdcits 4096 Feb 23 10:25 change30-calls
drwxr-xr-x  2 wujh groupdcits 4096 Feb 23 10:25 change30-model
[wujh@tele-4 DetermineGermlineContigPloidy30]$ ll change30-calls
total 0
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_0
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_1
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_10
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_11
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_12
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_13
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_14
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_15
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_16
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_17
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_18
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_19
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_2
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_20
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_21
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_22
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_23
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_24
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_25
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_26
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_27
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_28
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_29
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_3
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_4
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_5
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_6
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_7
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_8
drwxr-xr-x 2 wujh groupdcits 155 Feb 23 10:25 SAMPLE_9

less -S change30-model/mu_mean_bias_j_lowerbound__.tsv
@shape=(24,)
@dtype=float64
0.019458835809044867
0.031170431276168496
0.031063834325466548
-0.053430597788607564
0.028991976776819313
0.03188641042191654
0.025744730251853483
-0.044683440580166059
-0.038202707908613423
0.039446858245067919
0.027734188731645144
-0.037494123601623915
-0.031763923523433074
0.031717803459495424
0.029446966097923417
-0.042422887245494631
0.024412305218945277
-0.031389153909177715
-0.025703579689687561
-0.024220041223810457
-0.031458386250220551
-0.02899769747610664
0.014783173073955026
-0.004379005066713005
**

**Comment by samuelklee** [comment]
Hi @wujh2017,

Note that the numbers in change30-model/mu_mean_bias_j_lowerbound__.tsv indicate the mean bias per *contig*, not per *sample*.

It looks like you are providing only 4 samples to GermlineCNVCaller, even though you provided 30 samples to DetermineGermlineContigPloidy.  Are these 4 samples included in those 30?  Typically, you would just provide all 30 samples (along with their ploidy calls) to GermlineCNVCaller.

Also, you mentioned that the read depth varies dramatically between samples.  Remember that we are trying to model systematic sequencing bias using the samples in the cohort, so ideally they should have all been sequenced with a similar protocol.

**Comment by wujh2017** [comment]
@samuelklee 
I have realised my mistake and changed it .everything is ok now,thank you.

**Comment by samuelklee** [comment]
@wujh2017 Great!  Let us know if you have any more feedback.  Please be aware that both DetermineGermlineContigPloidy and GermlineCNVCaller are still in beta.  There are some parameters that may need to be tuned appropriately for your data.
