### ISSUE TITLE
VariantAnnotator, extract a common interface between readsLikelihoods and UnfilledReadsLikelihoods.

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#4462]
As part of the implementation of VariantAnnotator, to avoid significant changes to the annotation interfaces a subclass of ReadLikelihoods was made to support partial data that was backed up by read pileups. Unfortunately since functionality is entangled with its superclass, this subclass is going to be subject to issues as more likelihoods functionality is added. A common interface between the two objects along the lines of a "ReadEvidence" object would help alleviate these problems.
Related to #4450, #3803

**Comment by davidbenjamin** [comment]
Closed by #6172.
