### ISSUE TITLE
Include non-variant sites in output of genotypeGVCFs for GATK 4?

### ISSUE THREAD

**Issue by davidecarlson** [broadinstitute/gatk#4470]
Hi GATK devs,

In version 3.X of GATK, it was possible to include non-variant positions in the output vcf file produced from genotypeGVCFs using the "--includeNonVariantSites " flag.  This flag appears to have been removed with the switch to GATK 4.  

After examining the tool documentation, I don't see any equivalent option for genotypeGVCFs that would output non-variant positions in the vcf file.

Is there some way to do this that I'm just not seeing?
Thanks,
Dave

**Comment by chandrans** [comment]
Hi Dave. There are plans to do this in https://github.com/broadinstitute/gatk/issues/2865

**Comment by davidecarlson** [comment]
Thanks!  I'll close this ticket and follow #2865.
Cheers,
Dave
