### ISSUE TITLE
Cannot find '.git' directory

### ISSUE THREAD

**Issue by alrafaykhan** [broadinstitute/gatk#4475]
Issue while Building GATK4

sudo   ./gradlew bundle
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Build file '/home/rafay/gatk-4.0.2.0/build.gradle' line: 289

* What went wrong:
A problem occurred evaluating root project 'gatk'.
> Cannot find '.git' directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.349 secs

**Comment by cmnbroad** [comment]
@alrafaykhan Did you clone (this) repository with git, and if so, is the root of that clone the location from which you're running ./gradlew ? I'm not sure how that happened, but it seems like you have  build.gradle, but not the rest of the repo. You also can download a [zip file with GATK already built](https://github.com/broadinstitute/gatk/releases) if you just want to run it.

**Comment by droazen** [comment]
@alrafaykhan I'm guessing that you downloaded the source code zip instead of actually cloning our git repository. You need to clone the repository to build GATK.

**Comment by alrafaykhan** [comment]
Yes i have downloaded source code (zip) from https://github.com/broadinstitute/gatk/archive/4.0.2.0.zip
