### ISSUE TITLE
Does GCS NIO support appending to existing files?

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4478]
A question for @jean-philippe-martin from @kcibul and @geoffjentry

**Comment by jean-philippe-martin** [comment]
GCS NIO doesn't currently support appending to existing files. If you try, you will see this error:

```
java.lang.UnsupportedOperationException: APPEND
```

As you can see in [CloudStorageFileSystemProvider.java](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageFileSystemProvider.java#L351), the list of supported open options currently includes
- CREATE
- CREATE_NEW
- TRUNCATE_EXISTING
- WRITE
- SPARSE (ignored)

Conceptually, GCS is designed to hold rarely-modified objects so append isn't a great fit, though it's not impossible.
