### ISSUE TITLE
Fix FeatureManager feature discovery

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#4480]
FeatureManager dynamically discovers all `FeatureInput` arguments in a tool by accepting a (pre-populated) CommandLineProgram object, which it then passes to static methods in Barclay. Those methods perform the same `@Argument`/`@ArgumentCollection` discovery already implemented by the parser, but using separate, out-of-date code paths that currently don't discover `@PositionalArguments` or plugin descriptor arguments.

Rather than fixing the redundant code paths and static methods in Barclay, they can be eliminated and replaced with an instance method on the parser. Since FeatureManager already requires that the parser have been run on the tool, the parser already has the state necessary to just collect the results. However, this means that FeatureManager would require a CommandLineParser object instead of the tool itself. (Alternatively, we could  extract the results from the parser and pass them in directly to FeatureManager instead of the parser). @droazen do you have any opinion on this before I refactor this part of the parser ?

**Comment by droazen** [comment]
This ties into the URI class design meeting we're having next week -- I'd say wait until then before starting any refactor of this part of the code.

**Comment by cmnbroad** [comment]
This will be fixed when https://github.com/broadinstitute/gatk/pull/4523 is merged.

**Comment by cmnbroad** [comment]
Fixed in https://github.com/broadinstitute/gatk/pull/4523.
