### ISSUE TITLE
Minor: Consider more conventional metadata header formatting of CNV outputs

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4481]
Just some thoughts for @samuelklee.

For example, CollectFragmentCounts produces the following hybrid-type `@RG` line:

![screenshot 2018-02-22 15 05 48](https://user-images.githubusercontent.com/11543866/36908820-66b90938-1e0a-11e8-8830-793ff3f71e96.png)

```
@RG    ID:GATKCopyNumber    SM:HCC1143_tumor
```
Official format specifications are at https://samtools.github.io/hts-specs/. Let me briefly describe the  #choices.

---
If we are to follow conventions used in the alignment world (SAM specs), then...

We note data transformations using `@PG` program groups. These can be added successively to the same data file, given unique `@PG ID` fields, and collectively these lines showcase the history of data transformations for a dataset.

The `@RG` group is reserved for lane level data and yes, does unify based on the sample or library.

---
If we examine VCFs, the convention is to use `#` hashtags to denote header rows (VCF specs). Double hashtags `##` denote all metadata lines and a single hashtag `#` denotes the line with the column labels. Here are some select rows from an M2 VCF header:
```
##fileformat=VCFv4.2
##FILTER=<ID=artifact_in_normal,Description="artifact_in_normal">
...
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Allelic depths for the ref and alt alleles in the order listed">
...
##GATKCommandLine=<ID=FilterMutectCalls,CommandLine="FilterMutectCalls...
...
##GATKCommandLine=<ID=Mutect2,CommandLine="Mutect2  --tumor-sample HCC1143_tumor ...
...
##INFO=<ID=TLOD,Number=A,Type=Float,Description="Tumor LOD score">
##Mutect Version=2.1-beta
##command=FilterByOrientationBias  --output hcc1143_T_clean-filtered.vcf...
...
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr2,length=242193529>
...
##contig=<ID=HLA-DRB1*16:02:01,length=11005>
##filtering_status=These calls have been filtered by FilterMutectCalls to label false positives with a list of failed filters and true positives with PASS.
##normal_sample=HCC1143_normal
##orientation_bias_artifact_modes=<ID=C/T|G/T,Description="The artifact modes that were used for orientation bias artifact filtering for this VCF">
##source=FilterMutectCalls
##source=Mutect2
##tumor_sample=HCC1143_tumor
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HCC1143_normal  HCC1143_tumor
```
You can see that `grep -v '##' ` allows exclusion of all but the column label, while `grep -v '#'` allows exclusion of all header lines. The latter makes it easy to count the number of data rows using `wc -l`.

**Comment by samuelklee** [comment]
Thanks for these suggestions, @sooheelee.  Note that there's already an issue filed to add `@PG` tags here: https://github.com/broadinstitute/gatk/issues/4117  As for the `@RG` tag, I was following the example of the SV team, which I saw introduced a custom RG ID (although this may only be used for tagging intermediate files---not sure?)  Although not ideal, I think passing the sequence dictionary and sample name in this way allows us to reuse the relevant SAM header code and also prevents the possibility of users mixing up samples.  (Recall that the old pipeline required the sample name to be passed in as a separate input to each tool and that no validation that each input came from the same sample was performed.)

As for VCF output, we are also planning to add this to the ModelSegments pipeline (it is already in the gCNV pipeline).  See https://github.com/broadinstitute/gatk/issues/4114.  However, I think it makes sense for this to wait until the improved caller is in.

I'll close this as a dupe for now, but we'll be able to reference your comments here from those issues in the future.

**Comment by sooheelee** [comment]
I should have checked to see if a related issue ticket existed. Glad these descriptions can be of use.
