### ISSUE TITLE
Clearer exception messages for ploidy priors in DetermineGermlineContigPloidy

### ISSUE THREAD

**Issue by b-kaufman** [broadinstitute/gatk#4486]
Currently if the number of headers do not match the number of rows it manifests as:`AssertionError: Some contigs do not have ploidy priors`. It would be good if the error message could more explicitly state how the ploidy prior file is malformed. In the event where it's actually the case it might also be worth explicitly stating which contig was found not to have a ploidy prior.

**Comment by samuelklee** [comment]
Might be more trouble than it's worth to add a detailed exception.  The original exception might be vague, but it is correct.  Closing for now.
