### ISSUE TITLE
HaplotypeCallerSpark   lose a lot of variable sites and the result jitter 

### ISSUE THREAD

**Issue by lelqz** [broadinstitute/gatk#4488]
version: gatk 4.0.2.1
I use the pipeline :BwaAndMarkDuplicatesPipelineSpark-》BQSRPipelineSpark-》HaplotypeCallerSpark，and I get the bad result。by testing，HaplotypeCallerSpark lose a lot of variable sites and HaplotypeCallerSpark 'result jitter to the same input bam。

**Comment by droazen** [comment]
@lelqz Thanks for the report. `HaplotypeCallerSpark` is still in beta status, and has many known issues with its output. It should be used for evaluation purposes only. For now you should use the regular `HaplotypeCaller` in all cases where you care about the quality of the results.

**Comment by lelqz** [comment]
@droazen Thanks. I use HaplotypeCaller and get the good results. my pipeline is :BwaAndMarkDuplicatesPipelineSpark-》BQSRPipelineSpark-》HaplotypeCaller.

**Comment by lelqz** [comment]
@droazen . I have fixed the issue according Mr wangdy12 ' ways, I tested  and the results is good .  please reference A GATK4.0 Spark bug about HaplotypeCallerSpark and How to fix #4231 .

**Comment by ggittu** [comment]
@lelqz Is the fixed version in GATK 4.0.9.0?

**Comment by droazen** [comment]
@ggittu No, but we have plans to assign someone to work on `HaplotypeCallerSpark` this quarter. As part of this work, we'll consider the patch proposed by @lelqz

**Comment by ggittu** [comment]
@droazen That would be great, we are looking forward to it. And meanwhile, If I need to include the patch proposed by @lelqz what can I do? Is there any build that include that patch ?

**Comment by droazen** [comment]
@ggittu We don't have such a build -- you could ask @lelqz if he has a fork/branch with his patch applied.

**Comment by ggittu** [comment]
@droazen Thank you , and I appreciate your attention! Can we expect something by end of this month? Meanwhile, I will wait for @lelqz for a branch with the applied patch.

**Comment by droazen** [comment]
@ggittu Most likely not this month -- the effort to get `HaplotypeCallerSpark` out of beta will be starting up in November, and will be led by @jonn-smith, @jamesemery, and @tomwhite. It would be a good idea to remind one of them about this proposed patch via a github mention around November 1.

**Comment by tomwhite** [comment]
See https://github.com/broadinstitute/gatk/issues/4231#issuecomment-464754012
