### ISSUE TITLE
CollectAllelicCounts - Badly formed genome unclippedLoc: Parameters to GenomeLocParser

### ISSUE THREAD

**Issue by stefandiederich** [broadinstitute/gatk#4504]
Hi 

I used CollectAllelicCounts with a bed file for the `-I` parameter and got the following error message:

`A USER ERROR has occurred: Badly formed genome unclippedLoc: Parameters to GenomeLocParser are incorrect:The stop position 29430911 is less than start 29430912 in contig chr2`

The only entry in my bed file dealing with this position is the following:

`chr2	 29430911	29430911	ENSE00001695104	3	ENST00000431873	ENSG00000171094	ALK`

There seems to be a problem, that CollectAllelicCounts add 1 base to the start of each interval. I tried it with a padding of 10 (`-ip 10`) but did not get it to work.

Am I on the wrong way? Isn't it a problem with the bed file?`
Thanks in advance
Stefan

**Comment by sooheelee** [comment]
@stefandiederich, I think this is a problem with how your BED file is being interpreted. In general, with GATK, it's best to use 1-based coordinates intervals, e.g. that of a [Picard-style interval_list](https://gatkforums.broadinstitute.org/gatk/discussion/1319/collected-faqs-about-interval-lists). BED is 0-based. See https://www.biostars.org/p/84686/ for a clear illustration of the differences. 

If provided a BED file, i.e. an intervals list with `.bed` extension, GATK will convert it to the expected 1-based format. So, if `chr2 29430911 29430911` is 0-based BED, then conversion to 1-based would yield `chr2 29430912 29430911`, making the stop less than the start as the error message says. 

It seems though that your intervals are actually already 1-based, not 0-based (which the BED format implies). Make sure your coordinates are expected and try changing the file extension.

**Comment by sooheelee** [comment]
Going forward, be sure to post your GATK/Picard questions to the GATK forum at https://gatkforums.broadinstitute.org/gatk.

**Comment by stefandiederich** [comment]
@sooheelee Thanks for your quick response. Changing the file extension or using a picard-style interval list solves the problem. Have not thought about the 0 based bed file and will post the issues in GATK forum next time, I' m sorry.

**Comment by sooheelee** [comment]
No worries. Glad your issue is solved.
