### ISSUE TITLE
CreateHadoopBamSplittingIndex on cram?

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gatk#4506]
Should the CreateHadoopBamSplittingIndex tool also work on a cram?  I am getting this error below which suggests not. What are the benefits of a SplittingIndex for a spark job? On average-how long should it take a spark job to get the splits for a 30x bam or cram? 

```
gatk CreateHadoopBamSplittingIndex -I adni/cram/ADNI_002_S_0413.hg38.realign.bqsr.cram
Using GATK jar /share/pkg/gatk/4.0.1.1/install/bin/gatk-package-4.0.1.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=1 -jar /share/pkg/gatk/4.0.1.1/install/bin/gatk-package-4.0.1.1-local.jar CreateHadoopBamSplittingIndex -I adni/cram/ADNI_002_S_0413.hg38.realign.bqsr.cram
11:47:53.243 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/pkg/gatk/4.0.1.1/install/bin/gatk-package-4.0.1.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
11:47:53.455 INFO  CreateHadoopBamSplittingIndex - ------------------------------------------------------------
11:47:53.455 INFO  CreateHadoopBamSplittingIndex - The Genome Analysis Toolkit (GATK) v4.0.1.1
11:47:53.455 INFO  CreateHadoopBamSplittingIndex - For support and documentation go to https://software.broadinstitute.org/gatk/
11:47:53.455 INFO  CreateHadoopBamSplittingIndex - Executing as farrell@scc-hadoop.bu.edu on Linux v2.6.32-696.10.3.el6.x86_64 amd64
11:47:53.456 INFO  CreateHadoopBamSplittingIndex - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_151-b12
11:47:53.456 INFO  CreateHadoopBamSplittingIndex - Start Date/Time: March 7, 2018 11:47:52 AM EST
11:47:53.456 INFO  CreateHadoopBamSplittingIndex - ------------------------------------------------------------
11:47:53.456 INFO  CreateHadoopBamSplittingIndex - ------------------------------------------------------------
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - HTSJDK Version: 2.14.1
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - Picard Version: 2.17.2
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - HTSJDK Defaults.COMPRESSION_LEVEL : 1
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - Deflater: IntelDeflater
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - Inflater: IntelInflater
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - GCS max retries/reopens: 20
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
11:47:53.457 INFO  CreateHadoopBamSplittingIndex - Initializing engine
11:47:53.458 INFO  CreateHadoopBamSplittingIndex - Done initializing engine
11:47:53.463 INFO  CreateHadoopBamSplittingIndex - Shutting down engine
[March 7, 2018 11:47:53 AM EST] org.broadinstitute.hellbender.tools.spark.CreateHadoopBamSplittingIndex done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=1115160576
***********************************************************************

A USER ERROR has occurred: Bad input: A splitting index is only relevant for a bam file, but a file with extension cram was specified.

***********************************************************************
Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
```

**Comment by lbergelson** [comment]
@jjfarrell  You don't need splitting index for cram.  The index works around a bam specific problem which makes it hard to find good split points in the file.  Cram is designed in a way that makes it easier to find the split points so the index is unnecessary. 

I don't have good numbers for how long it takes to find the split points for bam.  It depends on your filesystem.  If you have a low latency file system like a local disk or hdfs setup than finding split points takes very little time (~seconds),  but if you have a high latency file system like something backed by google object store then finding split points may take a long time (on the order of minutes to tens of minutes depending on latency and file size).

**Comment by jjfarrell** [comment]
Thanks for the explanation!

**Comment by lbergelson** [comment]
We're working on speeding up the splitting on cloud filesystems, but it's going to take a while before we have a good solution other than the splitting index.

**Comment by jjfarrell** [comment]
On my system

```
18/03/07 13:24:26 INFO storage.BlockManagerMasterEndpoint: Registering block manager scc-q14.scc.bu.edu:42456 with 25.4 GB RAM, BlockManagerId(2, scc-q14.scc.bu.edu, 42456, None)
18/03/07 13:24:27 INFO memory.MemoryStore: Block broadcast_0 stored as values in memory (estimated size 247.0 KB, free 8.4 GB)
18/03/07 13:24:28 INFO memory.MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 25.5 KB, free 8.4 GB)
18/03/07 13:24:28 INFO storage.BlockManagerInfo: Added broadcast_0_piece0 in memory on 10.48.225.55:32895 (size: 25.5 KB, free: 8.4 GB)
18/03/07 13:24:28 INFO spark.SparkContext: Created broadcast 0 from newAPIHadoopFile at ReadsSparkSource.java:112
18/03/07 13:24:28 INFO hdfs.DFSClient: Created HDFS_DELEGATION_TOKEN token 7164 for farrell on ha-hdfs:scc
18/03/07 13:24:28 INFO security.TokenCache: Got dt for hdfs://scc; Kind: HDFS_DELEGATION_TOKEN, Service: ha-hdfs:scc, Ident: (HDFS_DELEGATION_TOKEN token 7164 for farrell)
18/03/07 13:24:28 INFO input.FileInputFormat: Total input paths to process : 1
18/03/07 13:59:26 INFO spark.SparkContext: Starting job: aggregate at FlagStatSpark.java:73
18/03/07 13:59:26 INFO scheduler.DAGScheduler: Got job 0 (aggregate at FlagStatSpark.java:73) with 252 output partitions
18/03/07 13:59:26 INFO scheduler.DAGScheduler: Final stage: ResultStage 0 (aggregate at FlagStatSpark.java:73)
18/03/07 13:59:26 INFO scheduler.DAGScheduler: Parents of final stage: List()
18/03/07 13:59:26 INFO scheduler.DAGScheduler: Missing parents: List()
18/03/07 13:59:26 INFO scheduler.DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[3] at filter at GATKSparkTool.java:220), which has no missing parents
18/03/07 13:59:26 INFO memory.MemoryStore: Block broadcast_1 stored as values in memory (estimated size 1148.4 KB, free 8.4 GB)
18/03/07 13:59:26 INFO memory.MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 345.8 KB, free 8.4 GB)
18/03/07 13:59:26 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on 10.48.225.55:32895 (size: 345.8 KB, free: 8.4 GB)
18/03/07 13:59:26 INFO spark.SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:996
18/03/07 13:59:26 INFO scheduler.DAGScheduler: Submitting 252 missing tasks from ResultStage 0 (MapPartitionsRDD[3] at filter at GATKSparkTool.java:220)
18/03/07 13:59:26 INFO cluster.YarnScheduler: Adding task set 0.0 with 252 tasks
18/03/07 13:59:26 INFO scheduler.TaskSetManager: Starting task 2.0 in stage 0.0 (TID 0, scc-q05.scc.bu.edu, executor 4, partition 2, NODE_LOCAL, 6147 bytes)
18/03/07 13:59:26 INFO scheduler.TaskSetManager: Starting task 25.0 in stage 0.0 (TID 1, scc-q10.scc.bu.edu, executor 3, partition 25, NODE_LOCAL, 6147 bytes)
18/03/07 13:59:26 INFO scheduler.TaskSetManager: Starting task 15.0 in stage 0.0 (TID 2, scc-q07.scc.bu.edu, executor 1, partition 15, NODE_LOCAL, 6147 bytes)
18/03/07 13:59:26 INFO scheduler.TaskSetManager: Starting task 4.0 in stage 0.0 (TID 3, scc-q16.scc.bu.edu, executor 8, partition 4, NODE_LOCAL, 6147 bytes)
18/03/07 13:59:26 INFO scheduler.TaskSetManager: Starting task 3.0 in stage 0.0 (TID 4, scc-q14.scc.bu.edu, executor 2, partition 3, NODE_LOCAL, 6147 bytes)

```

**Comment by lbergelson** [comment]
@jjfarrell Huh.  I expected that sort of annoying delay from splitting on a cloud system but not on a hadoop one.  Does running with splitting index avoid the delay?

**Comment by jjfarrell** [comment]
FlagStatSpark was also run on the bam file without the splitting index. There was no delay just a slightly longer run of 2.5 min.  Both had the same results.  The 30-40 minute delay is only found when reading crams.  @lbergelson Is there a  fix for this long delay for processing a cram?

**Comment by cmnbroad** [comment]
@lbergelson @jjfarrell I'm not sure how much of the difference this accounts for, but the cram splitter iterates through all of the cram containers using htsjdk's CramContainerIterator, which decodes and materializes all SAMRecords in each container it sees. The bam (probabilistic) splitter only materializes a few records around each putative split boundary. And decoding cram is inherently slower than bam to start with.

**Comment by jjfarrell** [comment]
@cmnbroad @lbergelson  For Spark tools, shouldn't the cram-splitter be using Hadoop-Bam and not  htsjdk's CramContainerIterator?  That would probably explain the 30-40 minute extra time for cram splits  versus bam splits.

**Comment by cmnbroad** [comment]
@jjfarrell Yes, but Hadoop-Bam in turn uses htsjdk.

**Comment by jjfarrell** [comment]
@cmnbroad @lbergelson   The cram index looks like it has all the info required to generate the splits without using the CramContainerIterator to look at the cram file directly.  

Could using the crai index for splits be a potential solution to the glacially slow cram split generation?  
 
CRAM index

A CRAM index is a gzipped tab delimited file containing the following columns:
1. Sequence id
2. Alignment start
3. Alignment span
4. **Container start byte offset in the file**
5. Slice start byte offset in the container data (‘blocks’)
6. Slice bytes
Each line represents a slice in the CRAM file. Please note that all slices must be listed in index file.

**Comment by tomwhite** [comment]
@jjfarrell I agree that it would make a lot more sense to use the .crai file. That's something we could certainly do in Hadoop-BAM or the new code.

@cmnbroad does CramContainerIterator materialize each record? I was under the impression that it was just finding boundaries - but the slow runtime suggests it may not.

**Comment by fnothaft** [comment]
> @jjfarrell I agree that it would make a lot more sense to use the .crai file. That's something we could certainly do in Hadoop-BAM or the new code.

We've already got code that does this for BAM indices; even if CRAIs have a different API, they should be able to reuse the split calculation code.

**Comment by cmnbroad** [comment]
@tomwhite I just took a look and I did overstate the case when I said CramContainerIterator materializes SAMRecords. It stops short of doing that, but it does crack each container open and iterate through and decompress each data block in each slice in each container as it goes along. Its not clear to me how much this affects the difference in split calc time vs. bam.

**Comment by jjfarrell** [comment]
There is a initial release of the faster and more accurate replacement for Hadoop-Bam at:

https://github.com/disq-bio/disq

It would be great to see faster reading of crams in spark GATK with this.  Any plans for testing this release?

**Comment by lbergelson** [comment]
@jjfarrell Yes, we're working on migrating to disq.  See https://github.com/broadinstitute/gatk/pull/5138

**Comment by jjfarrell** [comment]
4.1.0.0 version with disq is reading crams much faster!
