### ISSUE TITLE
Keras model for variant calling?

### ISSUE THREAD

**Issue by daquang** [broadinstitute/gatk#4511]
Hi, I'm interested in your keras model for variant calling. Is there anyway I can download it to study it?

**Comment by jjfarrell** [comment]
Here is a blog regarding the Deep CNN model used for variant filtering....

https://gatkforums.broadinstitute.org/gatk/discussion/10996/deep-learning-in-gatk4

**Comment by daquang** [comment]
Thanks for the response. I actually already read the blog (you can see my comment at the bottom of the blog). But I felt the blog didn’t really give me a lot of info that I wanted. I really would like the keras model’s raw .h5 file weights, and the source code of the training process.

**Comment by ldgauthier** [comment]
@daquang -- Sam (@lucidtronix ) has already merged the code to run the model inference for his simpler 1D model architecture.  I think src/main/resources/org/broadinstitute/hellbender/tools/walkers/vqsr/cnn_1d_annotations.hd5 is what you're looking for.  He currently has a PR in review (https://github.com/broadinstitute/gatk/pull/4245) to add the more sophisticated 2D model and a GATK walker to do the training (CNNVariantTrain).  That PR should get finalized and merged any day now.

**Comment by daquang** [comment]
Thanks, I found the weights and loaded the 1D model. Would it also be possible to get the original training script that generated this model?

**Comment by ldgauthier** [comment]
We've been having some problems with the test server,
 but the PR should get merged soon: (https://github.com/broadinstitute/gatk/pull/4245/).

**Comment by ldgauthier** [comment]
@daquang The Java model training tool was just merged in.  We'll probably cut a release soon, but you can build from master if you just can't wait.
