### ISSUE TITLE
CombineGVCFs java.lang.IllegalArgumentException: Unexpected base in allele bases '*AACC'

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#4525]
### Affected tool(s)
CombineGVCFs

### Affected version(s)
4.0.2.0

### Description 
CombineGVCFs fails with an IllegalArgumentException when trying to combine GVCFs. However, when trying to combine a different subset of the GVCFs, it fails with a ClassCastException. The GVCFs all validate with ValidateVariants and were produced with GATK4 HaplotypeCaller.

#### Steps to reproduce
Details in https://github.com/broadinstitute/dsde-docs/issues/2990

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/11503/combinegvcfs-java-lang-illegalargumentexception-unexpected-base-in-allele-bases-aacc/p1

**Comment by chandrans** [comment]
A second user has reported it as well. https://gatkforums.broadinstitute.org/gatk/discussion/11693/combine-gvcfs-error

**Comment by droazen** [comment]
@cmnbroad Could you please have a look at this one when you get a chance, since you're already in this tool at the moment for https://github.com/broadinstitute/gatk/issues/4572? We've been asked to prioritize this ticket. Thanks!

**Comment by cmnbroad** [comment]
@chandrans I don't have access to dsde-docs so I can't see the ticket/test files (we asked @vdauwera to give me access last week for a different issue, but I don't have it yet).

**Comment by chandrans** [comment]
Oh. I will slack you Chris.

**Comment by cmnbroad** [comment]
Fixed via https://github.com/broadinstitute/gatk/pull/4680.
