### ISSUE TITLE
StructuralVariationDiscoveryPipelineSpark is generating too much logging info

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gatk#4531]
When running StructuralVariationDiscoveryPipelineSpark,  we found the local storage on our Hadoop Datanodes filling up. The pipeline was generating 2 GB of output and filling up the /var storage on the datanodes. The job would then fail.

Is there a way to turnoff this extensive logging info for this pipeline and make less extensive logging the default? 

Here is an example of one of the files.....
container_e2417_1520821377253_0060_01_000052/stdout

writing; 10000139 2/2 76b aligned read.
writing; 1000014 1/2 76b aligned read.
writing; 1000014 2/2 76b aligned read.
writing; 10000140 2/2 76b aligned read.
writing; 10000140 1/2 76b aligned read.
writing; 10000141 1/2 76b aligned read.
writing; 10000141 2/2 76b aligned read.
writing; 10000142 1/2 76b aligned read.
writing; 10000142 2/2 76b aligned read.
writing; 10000143 1/2 76b aligned read.
writing; 10000143 2/2 76b aligned read.
writing; 10000144 2/2 76b aligned read.
writing; 10000144 1/2 76b aligned read.
writing; 10000145 2/2 76b aligned read.
writing; 10000145 1/2 76b aligned read.
writing; 10000146 2/2 76b aligned read.
writing; 10000146 1/2 76b aligned read.
writing; 10000147 1/2 76b aligned read.
writing; 10000147 2/2 76b aligned read.
writing; 10000148 2/2 76b aligned read.
writing; 10000148 1/2 76b aligned read.
writing; 10000149 2/2 76b aligned read.
writing; 10000149 1/2 76b aligned read.

**Comment by cwhelan** [comment]
Hi @jjfarrell 

We took a look through our code and libraries we're depending on and the only place we could find any logging message that would produce those lines in any related repo we could find is in the `TestBAM` example tool from the Hadoop-BAM library. Is there any chance you ran that tool on one of your files (one with 76bp reads), perhaps after installing Hadoop-BAM and following the examples README, and that's what filled up the log?

**Comment by SHuang-Broad** [comment]
Also, could you provide at what level is the logging configured @jjfarrell ?

**Comment by jjfarrell** [comment]
Yes, I did run that Hadoop-Bam test in the midst of runs of the StructuralVariationDiscoveryPipelineSpark. When I was notified of the issue, I assumed it was those jobs and not the TestBAM runs.

There was a 30-40 minute delay of GATK Spark jobs reading crams relative to bams that I was looking into (https://github.com/broadinstitute/gatk/issues/4506).
