### ISSUE TITLE
FilterVariantTranches should be written entirely in Java

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#4535]
FilterVariantTranches currently has a thin Java layer that is a pass-through to Python, but can be written entirely in Java.

**Comment by droazen** [comment]
@lucidtronix Is this on your radar for this quarter? Engine team is happy to help with the conversion (we think it should be pretty easy) -- feel free to book some time on our calendar if you like.

**Comment by lucidtronix** [comment]
The PR is in: https://github.com/broadinstitute/gatk/pull/4800

**Comment by droazen** [comment]
@lucidtronix Sorry, saw that PR just after I posted the comment above :)  Thanks for doing it!

**Comment by lbergelson** [comment]
closed by https://github.com/broadinstitute/gatk/pull/4800
