### ISSUE TITLE
Implement a way to specify combine operations per-field in GenomicsDB

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4541]

**Comment by droazen** [comment]
@kgururaj Is this one still on your radar? It's mentioned in https://github.com/broadinstitute/gatk/pull/4645 as being targeted for the "next version" of the protobuf API, and @ldgauthier mentioned it to me as a feature she'd really love to have.

**Comment by kgururaj** [comment]
Yep, next version

**Comment by droazen** [comment]
This is done -- closing.
