### ISSUE TITLE
Check in an installer script (ideally with Java frontend) for funcotator datasources

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4549]
We should have an installer script checked in to the repo for downloading the Funcotator datasources. Ideally the script would have a trivial Java frontend in the form of a simple GATK tool, to make it more discoverable by users.

**Comment by jonn-smith** [comment]
Look at the lanterna library for an interactive curses menu: 

https://github.com/mabe02/lanterna

**Comment by jonn-smith** [comment]
For initial 1.0 release, just have a tool that will download the zipped data source package specified by the user from the bucket/ftp site.
