### ISSUE TITLE
ArgumentsBuilder needs to be refactored.

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#4550]
As discovered in one of the recent `Funcotator` PRs, `ArgumentsBuilder` needs to be refactored.

**Comment by droazen** [comment]
@jonn-smith Can you be more specific? If we come back to this ticket in 3 months, we won't remember exactly how it needs to be refactored.

**Comment by lbergelson** [comment]
Sorry, I asked for this ticket.  We should remove the old functionality to convert picard style arguments -> gatk style.  We should also add more convenience overloads for things like Path, String, enum values, and numbers.  There's currently some weirdness with having differently named methods for different input values as well which should just be handled with overloads.
