### ISSUE TITLE
Does GATK4 Mutect2 support Force Calling?

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4555]
Question from Broadie on Mutect2 to follow up on for @davidbenjamin and @takutosato.

---
Hi,
Does GATK4 Mutect2 support Force Calling? If yes, could you let me know how to do it? Thanks a lot!

Thanks,
Chunyang

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/11658/does-gatk4-mutect2-support-force-calling/p1

**Comment by sooheelee** [comment]
I have tentatively followed up.

**Comment by sooheelee** [comment]
@davidbenjamin gave an answer on SLACK which I have recapitulated on the forum. Waiting to hear why researcher needs this mode.

**Comment by cbao-bi** [comment]
Thanks @sooheelee!
I posted the reason in the GATK forum. Please feel free to let me know if you have any questions.

"Say that we have some known variants (e.g. VCF file from GATK4 mutect2) in sample A and want to force them to call mutations in sample B. The key is to determine the genotype of sample B by the intervals of these variants. In the research of cancer evolution, it is important to figure out whether the mutations in late grade samples are 'true negative' or just filtered out in early grade samples. That is the main reason why I want to run force calling."

**Comment by davidbenjamin** [comment]
@sooheelee [Commenting on the forum discussion] `--alleles`, `--genotyping-mode`, and `--consensus` are inherited from a common parent class of Mutect2 and HaplotypeCaller and are inactive in GATK 4 Mutect2.  I should fix this misleading situation.

@cbao-bi's use case is important and the work-around that I gave on the forum is not satisfactory.  I'm convinced that it's worth doing it right.  Let me tentatively guess that I can put in a good force-calling mode within two months.

**Comment by cbao-bi** [comment]
Thanks @davidbenjamin and @sooheelee ! Please keep me updated.

**Comment by davidbenjamin** [comment]
@cbao-bi It's in code review: PR #4601.

**Comment by cbao-bi** [comment]
@davidbenjamin Thank you! I would like to follow up.

**Comment by cbao-bi** [comment]
Cool! Thanks @davidbenjamin. I like the wdl because I can use the vcf from M2 and do not need to generate interval list (Interval list is required in M1 pipeline). Hope to get the docker soon.

**Comment by sooheelee** [comment]
Great to hear this is already under review. Amazing @davidbenjamin.
