### ISSUE TITLE
Blacklist the Picard NIO dependency in build.gradle

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4556]
The latest Picard release introduces a dependency on the Google Cloud NIO library that conflicts with GATK's dependency. We are going to have to blacklist the Picard NIO dependency for now. 

Longer term, we might want to consider having both projects depend upon a build of htsjdk that comes with the NIO plugin.

**Comment by lbergelson** [comment]
The problem seems to be fixed in picard with @cmnbroad's change to the cloud configuration.  Thew pom for 2.18.1+ looks like it won't include nio.

**Comment by lbergelson** [comment]
It's a good idea to force our version anyway though.
