### ISSUE TITLE
Is the NeuralNetInference usable?

### ISSUE THREAD

**Issue by aderzelle** [broadinstitute/gatk#4559]
Hello,
I wish to try the deep learning search but what are we supposed to feed the program with the option "a" ?
`--architecture,-a:String      Neural Net architecture and weights hd5 file  Required`

By hd5 file, do you mean hdf5 file? 

Thanks a lot. 

Alessandro

**Comment by cmnbroad** [comment]
Hi @aderzelle. Thanks for your interest in NeuralNetInference. The tool currently has pre-beta`Experimental` status, so for now it should be used for evaluation purposes only. We expect to be releasing another version of GATK, probably within the next week, that will include an updated version of the tool that will include a default architecture file, along with some additional tools for things like training. The tools will still be `Experimental`, but should be a bit easier to use. Also note that in the next release, the name of the tool will have changed to CNNScoreVariants. @lucidtronix may want to chime in of there is anything else to add.

**Comment by lucidtronix** [comment]
There is an hd5 (hdf5) file [here](https://github.com/broadinstitute/gatk/blob/master/src/main/resources/org/broadinstitute/hellbender/tools/walkers/vqsr/cnn_1d_annotations.hd5) that you can give to the -a argument. As @cmnbroad mentioned the tool name and the argument structure will change in the upcoming PR.

**Comment by aderzelle** [comment]
Thanks for your replies, I will give it a try.

**Comment by lbergelson** [comment]
Closing this since it seems like it's been resolved.  Feel free to reopen if you have additional questions.
