### ISSUE TITLE
jfrog repository does not have any snapshot artifact

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#4565]
I have a project that depends on `4.alpha.2-183-ge1e71d7-SNAPSHOT` (I am planning to update it, that's why I look at it), and I discovered that the jfrog repository the folder is empty: https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot/org/broadinstitute/gatk/4.alpha.2-183-ge1e71d7-SNAPSHOT/

When looking at the jfrog repository, it looks like no SNAPSHOT jar file is present. As an example, one after-release SNAPSHOT: https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot/org/broadinstitute/gatk/4.0.0.0-1-g9423d25-SNAPSHOT/

Is this in purpose or should it be present? It looks like the current commit https://github.com/broadinstitute/gatk/commit/8463525cc9b523cd00daf2810bcf1c13b69ce0a1 does contain a proper artifact, but I am wondering how long the snapshots are going to be maintained.

Thank you!

**Comment by cmnbroad** [comment]
@magicDGS We talked with our ops people and it looks like we periodically purge anything older than 60 days, so this snapshot is gone. We're going to try to streamline what we upload, which will then allow us to extend the retention time for these things. Hopefully you can rebuild what you need.

**Comment by magicDGS** [comment]
It is ok, @cmnbroad - I think that for snapshots, I will use https://jitpack.io/, which builds on demand the commits that are needed. Thanks for looking into this!
