### ISSUE TITLE
Mutect2 - emit germline sites

### ISSUE THREAD

**Issue by lima1** [broadinstitute/gatk#4573]
This has been asked a few times (e.g. https://gatkforums.broadinstitute.org/gatk/discussion/10251/is-it-possible-for-gatk4-beta3-mutect2-to-output-germline-variants-also), but would it be possible to add a flag to M2 so that it keeps germline sites? Currently there are filters hardcoded in M2 when matched normals are provided. 

Thanks for all the awesome work in GATK4. @davidbenjamin

**Comment by davidbenjamin** [comment]
Based on community interest we did this in PR #4522.  Although it has been merged into master we haven't put out a new tagged release since then, so it's not yet in the gatk4 docker.

**Comment by lima1** [comment]
Fantastic, thanks a lot!
