### ISSUE TITLE
Mutect2 alway output "." to VCF QUAL when tumor only mode

### ISSUE THREAD

**Issue by wangyugui** [broadinstitute/gatk#4574]
Hi.

Mutect2 alway output "." to VCF QUAL when tumor only mode

Should we assign a qual value for it?

```
gatk4 version:gatk-package-4.0.2.1-local.jar

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HiSeqX-Nextera-NA12891
MT      195     .       T       C       .       .       DP=5708;ECNT=5;POP_AF=1.000e-03;P_GERMLINE=-2.169e-04;TLOD=23981.58     GT:AD:AF:F1R
2:F2R1:MBQ:MFRL:MMQ:MPOS:PGT:PID:SA_MAP_AF:SA_POST_PROB     0/1:3,5583:0.988:1,2625:2,2958:41:174,354:60:35:0|1:195_T_C:0.990,0.990,0.999:0.
025,0.029,0.946
```

**Comment by wangyugui** [comment]
`--use-new-qual-calculator true` does NOT work too.

**Comment by wangyugui** [comment]
Can we change some param of HaplotypeCaller to make it more sensitive , so the vcf result of HaplotypeCaller will be more close to that of Mutect2 tumor-only mode?

**Comment by ldgauthier** [comment]
This is expected behavior.  Github issues are for bug reports.  Please post questions to the GATK forum: https://gatkforums.broadinstitute.org/gatk/
