### ISSUE TITLE
multiple samples support or GVCF support for mutect2 tumor-only mode

### ISSUE THREAD

**Issue by wangyugui** [broadinstitute/gatk#4575]
Hi.

We need multiple samples support or GVCF support for mutect2 tumor-only mode.

so we can diff the ./. and 0/0 in multiple normal samples.

There is neither multiple samples support nor GVCF support in version 4.0.2.1.

Best Regards

**Comment by davidbenjamin** [comment]
@wangyugui Could you explain your use case a bit further?

**Comment by wangyugui** [comment]
for example, 
the var of sample Normal_A:
chr1   100   T    A  1/1 
chr1   110    T   T   0/0(not ouputted in vcf)

the var of samlpe Normal_B:
chr1   100   T    T  ./. (not coveraged, not outputed in vcf too)
chr1   110   T    A   1/1

**Comment by davidbenjamin** [comment]
@wangyugui We have decided to do this -- see #4887.
