### ISSUE TITLE
which option to tuning sensitivity of HaplotypeCaller/GATK 4.0.2.1

### ISSUE THREAD

**Issue by wangyugui** [broadinstitute/gatk#4576]
Hi.

GATK HaplotypeCaller -stand-call-conf 0 report 21 var on chrM, but Mutect2 tumor-only mode report 57 var on chrM.
and GATK HaplotypeCaller -stand-call-conf 10 report 21 var on chrM too.

Which option can be used to tuning sensitivity of HaplotypeCaller/GATK 4.0.2.1?

The sample is NA12891 of BaseSpace HiSeqX Nextera data.

Best Regards

**Comment by wangyugui** [comment]
In the above example,most of var found in HaplotypeCaller's result are also found in Mutect2 tumor-only mode.  but there is one exception .

rs2001031(chrM:8860) is found in HaplotypeCaller's result, but not found in the result of Mutect2 tumor-only mode. and there is no complex var near chrM:8860 in the result of Mutect2 tumor-only mode too.

**Comment by ldgauthier** [comment]
HaplotypeCaller run using the default ploidy of 2 is not suited to mitochondrial variant calling.  Variants at or below 10% allele fraction may not trigger assembly of the active region.

Some users have reported improved HaplotypeCaller MT calling results by using higher ploidies (up to 100).

**Comment by wangyugui** [comment]
@ldgauthier 

Is there a param to tuning this 'Variants at or below 10% allele fraction may not trigger assembly of the active region.'?

**Comment by wangyugui** [comment]
In other region, -stand-call-conf 0/10  works well in my test.

**Comment by ldgauthier** [comment]
No.  You can try calling at higher ploidy, but we do not support mitochondrial variant calling with HaplotypeCaller.
