### ISSUE TITLE
Funcotator - VCFOutputRenderer needs to be reviewed with new changes from MAF

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#4583]
The `MafOutputRenderer` changed how some funcotation fields are accessed.  

Need to make VCF output consistent with the code in MAF output, and need to make sure it's consistent to the VCF format.

Specifically, `VCFOutputRenderer` should use the funcotation map that is now created internally to go through and render the annotations.

Specifically use `Funcotation::getFieldNames` and `Funcotation::getField`.

**Comment by LeeTL1220** [comment]
I think this is already done as part of #4872 ... @jonn-smith Can you confirm?

**Comment by jonn-smith** [comment]
@LeeTL1220 actually I think this was actually addressed in #4838.

Either way, I think we can close this one.
