### ISSUE TITLE
Funcotator - Need Performance Upgrades

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#4586]
Funcotator can be slow.

Need to profile it and make it fast all the time.

**Comment by droazen** [comment]
A large speedup has already been achieved in https://github.com/broadinstitute/gatk/pull/4740. According to @lbergelson:

```
Original (46a8661): 31.1 minutes, 1658 variants / minute
Changes (#4740): 1.26 minutes, 40933 variants / minute

~24.6x speedup
```

**Comment by jonn-smith** [comment]
We should investigate tuning the caching parameter to increase speed further.

We still need to profile, increase speed further, and compare to Oncotator.

**Comment by jonn-smith** [comment]
We also need to profile on multiple machines and verify that `Funcotator` will run at the same speed on all of them.

**Comment by jonn-smith** [comment]
Turns out the caching fix is only a partial fix because of the discrepancies between b37 contig names, hg19 contig names, and the fact that the datasources are inconsistent between them.
