### ISSUE TITLE
Need an escape character in the Filter task in the M2 WDL

### ISSUE THREAD

**Issue by jnktsj** [broadinstitute/gatk#4596]
Hi, I found a tiny bug in the `Filter` task that runs `FilterMutectCalls`. It appears that the line 713 of the M2 WDL needs an `\` at the end.

https://github.com/broadinstitute/gatk/blob/b5720472fe025270e410379885cd58fed7b20b77/scripts/mutect2_wdl/mutect2.wdl#L713-L714

**Comment by davidbenjamin** [comment]
Thanks @jnktsj.  I will fix this today.

**Comment by jnktsj** [comment]
@davidbenjamin I also found there are two `preemptible_attempts = preemptible_attempts` lines in line 181 and 187. Having these lines wouldn't cause an error, but I just wanted to let you know.
https://github.com/broadinstitute/gatk/blob/b5720472fe025270e410379885cd58fed7b20b77/scripts/mutect2_wdl/mutect2.wdl#L181-L187

**Comment by davidbenjamin** [comment]
Thanks @jnktsj, I will fix that, too.
