### ISSUE TITLE
Provide a WDL that can efficiently run SortSamSpark on a ~100 GB genome

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4598]
Provide @eitanbanks with a WDL that can efficiently run `SortSamSpark` on a normal-size (~100GB genome) on a single large compute instance. It should make whatever resource requests are necessary, including multiple local SSDs stitched together into a RAID or virtual filesystem, sufficient memory, and use an appropriate number of cores to balance memory usage against performance.

For @jamesemery and @lbergelson

**Comment by jamesemery** [comment]
This task has been subsumed by MarkDuplicatesSpark work
