### ISSUE TITLE
Funcotator should support segment annotations.

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#4609]
Funcotator currently does not support annotating `.seg` files.

This functionality should be added and should be mutually exclusive to `VCF` annotations.

The segment annotation process should create a `gene_list` file and a new `.seg` file.

**Comment by LeeTL1220** [comment]
What to do about the FeatureInputs?  The list will be quite long for some datasources and we are likely going to discard the data anyway. Note that the feature lookup is in the engine, not part of the datasources.
