### ISSUE TITLE
Push gatkbase tags to GCR

### ISSUE THREAD

**Issue by kshakir** [broadinstitute/gatk#4610]
For the various GATK docker images, the larger `4.x.y.z` tags are available in GCR but the smaller `gatkbase-a.b.c` tags are only available in [docker hub](https://hub.docker.com/r/broadinstitute/gatk/tags/).

```shell
$ gcloud container images list-tags us.gcr.io/broad-gatk/gatk
DIGEST        TAGS            TIMESTAMP
1c870d8bea16  4.0.3.0,latest  2018-03-28T05:12:42
fd8e7a9e65e6  4.0.2.1         2018-03-03T03:52:42
899b5d55c45b  4.0.2.0         2018-02-27T11:57:49
14b4dd387cf6  4.0.1.2         2018-02-10T03:48:55
98b2f223dce4  4.0.1.1         2018-02-02T05:45:05
634e2aaa5565  4.0.1.0         2018-02-01T00:13:47
277658fad225  4.0.0.0         2018-01-10T03:16:45
460c6b71b019  4.beta.6        2017-10-17T05:14:55
98ed56704964  4.beta.5        2017-09-07T02:47:16
12b65b9fe0bf  4.beta.4        2017-08-26T11:03:39
fa4d2b05e376  4.beta.3        2017-07-26T23:55:37
$ 
```

The smaller "base" images are 1/5th of the size of the larger images while still containing a number of useful utilities for GATK based workflows.

**Comment by droazen** [comment]
This was an oversight on our part that we'll fix. You should also note, however, that we have a branch coming soon that will *significantly* reduce the size of the main GATK docker image (by several GB).

**Comment by droazen** [comment]
Done -- the latest base image is up at `us.gcr.io/broad-gatk/gatk:gatkbase-1.2.3`
