### ISSUE TITLE
Error when using IntervalListTools in gatk4

### ISSUE THREAD

**Issue by bshifaw** [broadinstitute/gatk#4619]
### Affected tool(s)
IntervalListTools

### Affected version(s)
GATK 4.0.3.0

### Description
I’ve been getting the following error when executing IntervalListTools in gatk4 

`SECOND_LIST must be null when ACTION is CONCAT, found []. Please put all the inputs in INPUT for this ACTION.`

I can replicate the error when manually executing the command on gatk4 docker but the same command works fine on gitc using picard

COMMANDS
latest gatk4 docker
`/gatk/gatk IntervalListTools --SCATTER_COUNT 6 --SUBDIVISION_MODE BALANCING_WITHOUT_INTERVAL_SUBDIVISION_WITH_OVERFLOW --UNIQUE true --SORT true --INPUT /gatk/interval/Homo_sapiens_assembly19_1000genomes_decoy.whole_genome.interval_list`
gitc 2.3.3-1513176735
`java -Xms1g -jar /usr/gitc/picard.jar IntervalListTools SCATTER_COUNT=6 SUBDIVISION_MODE=BALANCING_WITHOUT_INTERVAL_SUBDIVISION_WITH_OVERFLOW UNIQUE=true SORT=true INPUT=/gatk/interval/Homo_sapiens_assembly19_1000genomes_decoy.whole_genome.interval_list`

INPUT:
gs://broad-references/Homo_sapiens_assembly19_1000genomes_decoy/Homo_sapiens_assembly19_1000genomes_decoy.whole_genome.interval_list

**Comment by cmnbroad** [comment]
It looks like this was an issue in Picard that was fixed in https://github.com/broadinstitute/picard/pull/972. It should be fixed in GATK the next time we pull in a new version of Picard.
