### ISSUE TITLE
FilterMutectCalls difference between 4.0.2.1 and 4.0.3.0

### ISSUE THREAD

**Issue by igordot** [broadinstitute/gatk#4625]
I tried running `FilterMutectCalls` on a VCF generated with `Mutect2` for matched tumor-normal samples. With 4.0.2.1, I get some variants that are labeled `PASS` as would be expected, but with 4.0.3.0, I get 0. That does not seem right.

**Comment by davidbenjamin** [comment]
@igordot When you get no PASS variants are you filtering `Mutect2` calls from 4.0.3.0?  What is your command line?  Could you paste a few vcf lines of variants that were PASS in 4.0.2.1 but filtered in 4.0.3.0?  Which filter(s) tends to be most responsible for PASSes getting filtered?

**Comment by igordot** [comment]
I actually cross-posted this issue on GATK forums (the actual commands and variants are there also): https://gatkforums.broadinstitute.org/gatk/discussion/11752/filtermutectcalls-change-between-4-0-2-1-and-4-0-3-0

In the meantime, I noticed something else. The variants that were `PASS` with 4.0.2.1 are not labeled as `PASS` with 4.0.3.0, but also not tagged with any failed filters. If I filter for "." in the `FILTER` field (column 7), I only get those variants that were `PASS` with 4.0.2.1. It seems like they should have been labeled `PASS`, but were not for some reason.

**Comment by chandrans** [comment]
@igordot Alright, it seems this is a case of PASS turning into . in 4.0.3.0. David @davidbenjamin if you could confirm, that would be great. Also, it would be nice to get PASS back into the FILTER column instead of .

**Comment by davidbenjamin** [comment]
@igordot @chandrans The fix is almost in.

**Comment by chandrans** [comment]
Thanks David. I think we can close this.
