### ISSUE TITLE
suggest to merge MosaicHunter into GATK

### ISSUE THREAD

**Issue by Yyx2626** [broadinstitute/gatk#4632]
Hello. I am Adam Yongxin Ye, a PhD candidate in Peking University, supervised by Prof Liping Wei.

We have developed MosaicHunter, a bioinformatic tool that can identify postzygotic single-nucleotide mosaicisms (with allele fraction deviated from homozygous 0, 1 and heterozygous 0.5) in bulk sequencing data of a single sample without matched control. After I had the recent lectures on GATK4 tutorial in Beijing, I thought it might be great to merge MosaicHunter into GATK framework, especially for the local assembly function in HaplotypeCaller and Mutect2, to increase the sensitivity & specificity and even extend for mosaic indels, as well as to make MosaicHunter easy for more users to use.

MosaicHunter utilized GATK preprocessing, distinguished mosaicisms from germline homozygous and heterozygous sites by a Bayesian genotyper, and applied several stringent hard filters.  MosaicHunter has been published (https://academic.oup.com/nar/article/45/10/e76/2962179 and http://www.nature.com/articles/cr2014131) and is publicly available (http://mosaichunter.cbi.pku.edu.cn/ and https://github.com/zzhang526/MosaicHunter (with source code in java)).

So I wonder if GATK team is interested in this suggestion. Could someone or may we contribute it into GATK?

**Comment by sooheelee** [comment]
Hi, @Yyx2626. 

I am Soo Hee and I work with the GATK Communications team. I think our developers will be keen to check out your tool, MosaicHunter. Thank you for offering to contribute your algorithm to GATK. 

We will be in touch. 

@davidbenjamin @ldgauthier, please take note.

**Comment by davidbenjamin** [comment]
@Yyx2626 This is an intriguing proposal.  We're fairly familiar with the paper by now but we still need to think more about how best to fit MosaicHunter into the GATK.  By the way, this is David Benjamin, current lead developer of Mutect2 (the original author is Kristian Cibulskis).  I occasionally hear from people using Mutect2 for mosaicism and it's definitely not a perfect fit.

**Comment by vdauwera** [comment]
Hi @Yyx2626, I'm Geraldine, you may remember me from the Beijing training. It was great visiting your team! I'm sorry it took me so long to follow up on this discussion, and I want to thank you again for reaching out to us about integrating the tool that you developed into GATK. We are certainly very interested in providing this enhancement to the research community, and we are now ready to talk about the next steps. 

After examining your paper and the source code in Github, we think that the most efficient way to integrate the functionality you developed would be to adapt the filtering parts of your tool to run on the output of Mutect2. So this would be a standalone tool that you would run after Mutect2, much like the current FilterMutectCalls tool. 

If the results are comparable to your current tool, then we would take that into the official distribution of GATK. If somehow that integration does not yield satisfactory results, then we would look at integrating the entire tool, though we're hoping it won't be necessary, so we can avoid maintaining duplicate functionality for some of the boilerplate data transformations. 

David @davidbenjamin can provide some advice on how to implement this in GATK4; in brief you would need to write some code that applies the filters you developed to a variant context. Let us know if this is an option you'd like to explore; we'd be happy to help.

**Comment by Yyx2626** [comment]
Dear Geraldine and David,


Sorry for my delayed reply. I am busy with graduation in recent days, and will work on visa application for the further postdoc position at Harvard Medical School.


Thank you for the interests in our tool, MosaicHunter. The option you suggest looks great. Do you mean that I should establish the GATK 4 developing environment and develop the MosaicHunterFilter tool? I may do that when I have some time. I found the document of GATK 4 at https://github.com/broadinstitute/gatk. Do you have any further advices?


Best regards,
Adam Yongxin Ye
Center for Bioinformatics
Peking University



At 2018-07-07 01:43:05, "Geraldine Van der Auwera" <notifications@github.com> wrote:


Hi @Yyx2626, I'm Geraldine, you may remember me from the Beijing training. It was great visiting your team! I'm sorry it took me so long to follow up on this discussion, and I want to thank you again for reaching out to us about integrating the tool that you developed into GATK. We are certainly very interested in providing this enhancement to the research community, and we are now ready to talk about the next steps.

After examining your paper and the source code in Github, we think that the most efficient way to integrate the functionality you developed would be to adapt the filtering parts of your tool to run on the output of Mutect2. So this would be a standalone tool that you would run after Mutect2, much like the current FilterMutectCalls tool.

If the results are comparable to your current tool, then we would take that into the official distribution of GATK. If somehow that integration does not yield satisfactory results, then we would look at integrating the entire tool, though we're hoping it won't be necessary, so we can avoid maintaining duplicate functionality for some of the boilerplate data transformations.

David @davidbenjamin can provide some advice on how to implement this in GATK4; in brief you would need to write some code that applies the filters you developed to a variant context. Let us know if this is an option you'd like to explore; we'd be happy to help.

**Comment by vdauwera** [comment]
Congratulations on your graduation! And good luck with your application, I know from personal experience it is a hassle, but it’s worth it!

Yes, that is what we are proposing. @davidbenjamin can give you some more guidance to get you started. 

Thank you!

**Comment by davidbenjamin** [comment]
Closing for now but I will be very happy to re-open if @Yyx2626 isn't too busy at HMS.
