### ISSUE TITLE
VariantFiltration - log4j:WARN

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#4637]
User is running VariantFiltration and gets

`log4j:WARN No appenders could be found for logger (org.apache.commons.jexl2.JexlEngine).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Tagging Chris, as he already helped a bit.

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/47736#Comment_47736

**Comment by bhanugandham** [comment]
Hi @cmnbroad 

We have another user facing this same issue. 
https://gatkforums.broadinstitute.org/gatk/discussion/15514/i-got-some-warn-when-i-run-variantfiltration/p1
Whats the solution for this? Does this effect effect results?

Regards
Bhanu

**Comment by cmnbroad** [comment]
@bhanugandham This message itself is harmless and won't affect results, but I wouldn't expect a user to see it when running from a normal installation, and I'm not sure why it seems to be intermittent. I'll need to do some debugging.

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/5422.
