### ISSUE TITLE
Emit MNPs as single event in Mutect2

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#4647]
In order to make Funcotator's life easier, among other reasons, M2 should emit MNPs as eg `AT -> CG` and not as two separate SNVs.  That is, of course, if the two substitutions are in fact in phase.

This probably involves going into `EventMapper`.

@LeeTL1220 @jonn-smith I expect this not to take very long.

@ldgauthier Is this relevant to HaplotypeCaller?

**Comment by ldgauthier** [comment]
The MacArthur lab has dealt with this by using our PID/PGT tags and post processing.  If we did it for them it would probably be appreciated.

Full disclosure: we don't have 100% sensitivity to adjacent phased SNPs with PID/PGT because the phasing heuristic requires cis-phase variants to be on ALL the same haplotypes, which breaks down occasionally in messy regions and some other scenarios.

**Comment by jonn-smith** [comment]
Works for me.  It will be completely transparent to Funcotator - it already handles MNPs.

**Comment by davidbenjamin** [comment]
Here's my proposed solution.  We break haplotypes into variant alleles in `EventMapper`, which loops over all the CIGAR elements of the haplotype versus the reference.  The code for SNPs and MNPs is lines 125 - 144 of EventMap.java, which I translate into pseudocode below:
```java
if (cigar element is M, X, or EQ) {
   for( each base in this cigar element) {
      if (haplotype base != ref base) {
         create a SNP here
      }
   }
}
```
I propose adding an optional parameter `treat-mnps-as-single-event`, to be hooked up to any `AssemblyRegionWalker`, that if true instead looks for maximal consecutive non-reference bases and builds a single MNP out of them.

**Comment by sooheelee** [comment]
Will this feature allow for a cutoff to discount potential low-level sequencing artifacts that generate haplotypes that don't make sense?

**Comment by davidbenjamin** [comment]
@sooheelee I don't see, at least not immediately, how artifacts would be more of a risk than they are already.  If anything I could see this making it a bit harder for false positives to get by.
