### ISSUE TITLE
Proposal: update gradle to 4.6

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#4659]
This can improve some build configurations for GATK (ony noted the ones in 4.6, but not previos ones):

* `failFast` property for test tasks. This would be useful for PRs
* Declare reasons for dependency resolution rules and constraint dependencies. This could be useful for explaining why some dependencies are not the latest (e.g., protobuf).
* Allow options in the command line. This could be nice for the doc generation.
* Default jacoco is 0.8.0, which improves the coverage report by filtering out some empty constructors

**Comment by lbergelson** [comment]
Any reason not to go straight 4.6?

**Comment by lbergelson** [comment]
Heh, no problem, it's easy to make a mistake like that.  I have [a branch](https://github.com/broadinstitute/gatk/tree/lb_update_to_gradle_4.6) that I've working to get 4.6 on.  Gradle 4+ changes the log output and it interacts badly with travis.  I've been trying to figure out the solution, but I keep running into different dumb typos and things so it's going slowly.  I think it's pretty close now though.
