### ISSUE TITLE
Mutect2 gatk-4.0.2.1 results are not same with gatk 3

### ISSUE THREAD

**Issue by bluesea2017** [broadinstitute/gatk#4662]
Hi,
  We used mutect2 gatk-4.0.2.1 and compared results the older results, theare are 16 samples then the filter  results are different with older more than 90%.

 where are differences between with the two versions?

Thank you !

**Comment by droazen** [comment]
@davidbenjamin Care to take this one?

**Comment by davidbenjamin** [comment]
@bluesea2017 How are you running M2 in GATK 3 and GATK 4 ie what are your command lines?

**Comment by davidbenjamin** [comment]
We can re-open this if we hear back from @bluesea2017.
