### ISSUE TITLE
Execution of "git lfs pull --include src/main/resources/large" failed with exit code: 1

### ISSUE THREAD

**Issue by Leornardzhou** [broadinstitute/gatk#4669]
""""
 gatk]# ./gradlew
Downloading https://services.gradle.org/distributions/gradle-3.1-bin.zip
............................................
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
Executing: git lfs pull --include src/main/resources/large

FAILURE: Build failed with an exception.

* Where:
Build file '/data/md1/zhouyajun/biotools/gatk/gatk/build.gradle' line: 102

* What went wrong:
A problem occurred evaluating root project 'gatk'.
> Execution of "git lfs pull --include src/main/resources/large" failed with exit code: 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
"""
what should I do ?
How can I install GATK4 successful?

**Comment by magicDGS** [comment]
Do you have the [build requirements](https://github.com/broadinstitute/gatk#requirements) installed? Concretely, [git lfs](https://git-lfs.github.com/) might not be there and thus the command is failing. This is just a guess...

**Comment by cmnbroad** [comment]
> How can I install GATK4 successful?

If you just want to install (as opposed to build), you can download a [release .zip or .tar](https://github.com/broadinstitute/gatk/releases) directly.

If you want to build, then as @magicDGS suggested, you need to have git-lfs installed. If you already have that, I would try manually running the command `git lfs pull --include src/main/resources/large` from the root of the repo clone and see if you get a more detailed failure  message.

**Comment by Leornardzhou** [comment]
THX all!
The problem is that I did not install "git lfs"  @magicDGS

**Comment by magicDGS** [comment]
Nice that it worked out, @Leornardzhou!

**Comment by lbergelson** [comment]
I believe this has been resolved.  Closing.
