### ISSUE TITLE
[GenotypeGVCFs]FORMAT/AD is outputed as '0,0' when FORMAT/GT is 0/1 or 1/1

### ISSUE THREAD

**Issue by wangyugui** [broadinstitute/gatk#4691]
Hi,

FORMAT/AD is outputed as '0,0' when FORMAT/GT is 0/1 or 1/1 in the output VCF file of GenotypeGVCFs.

FORMAT/AD is OK when FORMAT/GT is 0/0;

GATK version:4.0.3.0

VCF samples
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  HiSeqX-Nextera-NA12891  HiSeqX-Nextera-NA12892  NovaSeq.TruSeq.Nano.
550.NA12878.30x.chr6

6       63629   .       CAGCAGTGT       C       111.64  .       DP=30;MLEAC=1;MLEAF=0.167       GT:AD:DP:GQ:PL  0/0:13,0:13:39:0,39,519 0/0:17,0:17:5:0,5,670   0/1:0,0:.:99:120,0,122

6       93932   .       T       C       32.26   .       DP=28;MLEAC=1;MLEAF=0.167       GT:AD:DP:GQ:PL  0/0:15,0:15:30:0,30,450 0/0:13,0:13:27:0,27,405 0/1:0,0:.:41:41,0,72

6       73928   rs11242695      G       A       346.30  .       DB;DP=24;MLEAC=3;MLEAF=1.00     GT:AD:DP:GQ:PL  ./.:23,0:23:.:0,0,0     ./.:1,0:1:.:0,0,0       1/1:0,0:.:36:357,36,0

```

**Comment by wangyugui** [comment]
command line:
```
java -jar /usr/hpc-bio/gatk/gatk-package-4.0.3.0-local.jar GenotypeGVCFs -V /biowrk/BaseSpace/vcf.NA12878.GRCh38.p12/vcf.gatk-4.0.3.0.novoalign-3.08.02.NovaSeq.TruSeq.Nano.550.NA12878.30x.chr6.set/gatk.g.vcf -L 6 -O /biowrk/BaseSpace/vcf.NA12878.GRCh38.p12/vcf.gatk-4.0.3.0.novoalign-3.08.02.NovaSeq.TruSeq.Nano.550.NA12878.30x.chr6.set/tmp_dir/gatk.6.vcf --verbosity WARNING --reference /usr/bio-ref/GRCh38.p12.dnaref/dnaref.fa --dbsnp /usr/bio-ref/GRCh38.p12.dnaref/dbsnp.vcf --use-new-qual-calculator true -G AS_StandardAnnotation
```

**Comment by ldgauthier** [comment]
This is behavior that GATK3 would exhibit because the Standard annotation group gets dropped when another group is specified. Is that also the case in GATK4 @jamesemery ?

Also note that allele-specific annotations won't be output by GenotypeGVCFs if there are no allele-specific annotations in the input GVCFs.  (https://gatkforums.broadinstitute.org/gatk/discussion/9622/allele-specific-annotation-and-filtering  )

**Comment by wangyugui** [comment]
This problem is yet not fixed in gatk 4.0.4.0

**Comment by ldgauthier** [comment]
@wangyugui can you please rerun at least a portion of your GVCFs using the HaplotypeCaller arguments in the document above?  The AD annotation is part of the HCStandardAnnotation group, which I believe is being dropped if it's not explicitly specified.

**Comment by wangyugui** [comment]
It works well if we add '-A DepthPerAlleleBySample -A DepthPerSampleHC'.

**Comment by ldgauthier** [comment]
Does the command `java -jar $GATKjar -T HaplotypeCaller -R $reference \
    -I mySample.bam \
    -o mySample.AS.g.vcf \
    -ERC GVCF \
    -G StandardAnnotation -G AS_StandardAnnotation -G StandardHCAnnotation` from the article also fix the issue?  Can this be closed?

**Comment by wangyugui** [comment]
'-G StandardAnnotation -G AS_StandardAnnotation -G StandardHCAnnotation' works too.

**Comment by jakevc** [comment]
This issue still occurs for me with both of the above solutions: 

```
"gatk HaplotypeCaller \
                -R {input.ref} \
                -I {params.sample} \
                -ERC GVCF \
                -O {output.gvcf} \
                -stand-call-conf 30 \
                -A DepthPerAlleleBySample \
                -A DepthPerSampleHC"
```

and with 
```
"gatk HaplotypeCaller \
                -R {input.ref} \
                -I {params.sample} \
                -ERC GVCF \
                -O {output.gvcf} \
                -stand-call-conf 30 \
                -G StandardAnnotation \
                -G AS_StandardAnnotation \
                -G StandardHCAnnotation"
```

**Comment by ldgauthier** [comment]
@jakevc I don't think this is a software bug. If you post on the forum (https://gatkforums.broadinstitute.org/gatk/) someone can help you figure out your unexpected output.

**Comment by cheche0717** [comment]
> In this case, allele-specific annotations are outputted to GVCFs files by 'HaplotypeCaller -ERC GVCF -G AS_StandardAnnotation' command.
> 
> Although some warning message of 'HaplotypeCaller -ERC GVCF -G AS_StandardAnnotation' command.
> 
> ```
> WARN:StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
> ```
> 
> This warning message does not happen in all of my cases, but the FORMAT/AD error happen in all of my cases.

hello , i met the warning message:
`DepthPerSampleHC - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null`
 `WARN:StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null`

could you help me ? i just am a fresh . So i don't know what should i do next step and why it reported some warning messages. 
Thank you very much !

**Comment by ldgauthier** [comment]
@cheche0717 If you post on the forum (https://gatkforums.broadinstitute.org/gatk/) someone can help explain the warnings.
