### ISSUE TITLE
Straightforward port of ApplyRecalibration

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#47]

**Comment by akiezun** [comment]
this is not on the critical path now. will keep working on it but removing the milestone

**Comment by droazen** [comment]
alpha-2

**Comment by droazen** [comment]
Most straightforward port possible. Should probably rename this tool to `ApplyVQSR` for consistency with `ApplyBQSR`

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/2094.
