### ISSUE TITLE
SelectVariants: s is not a recognized option

### ISSUE THREAD

**Issue by thedam** [broadinstitute/gatk#4705]
Hi,
I'm running a command:
```
java -jar gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar SelectVariants \
  -R ref/human_g1k_b37_20.fasta \
  -V dupa.raw.indels.snps.vcf \
  -selectType INDEL \
  -O dupa_raw.INDEL.vcf

```
and I get error:
```
***********************************************************************

A USER ERROR has occurred: s is not a recognized option

***********************************************************************
```
Tested on various input files.

```
java -version
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (Zulu 8.25.0.1-linux64) (build 1.8.0_152-b16)
OpenJDK 64-Bit Server VM (Zulu 8.25.0.1-linux64) (build 25.152-b16, mixed mode)
```

Looks like it's a bug?

**Comment by magicDGS** [comment]
The `-selectType` argument now is `--select-type`, and that's what is failing. It is true that the error message is not that useful.

@cmnbroad - is this related with https://github.com/broadinstitute/barclay/issues/119, no?

**Comment by cmnbroad** [comment]
@magicDGS Yes, because of clustering, in this case `-selectType` falls back to being treated as a cluster, which then fails on the first arg in the cluster, which is "s".

**Comment by droazen** [comment]
@cmnbroad Can we turn off clustering in barclay?

**Comment by cmnbroad** [comment]
There doesn't appear to be a supported way to do this. There is a [PR](https://github.com/broadinstitute/barclay/pull/136) here that works though.
