### ISSUE TITLE
UserException.BadTmpDir has an out of date error message

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4709]
`UserException.BadTmpDir` has the error message: 
 `"Failure working with the tmp directory %s. Override with -Djava.io.tmpdir=X on the command line to a bigger/better file system."`

This should be changed refer to either the  `--java-options` command or `--TMP_DIR`.

Also, it doesn't attach the casual exception.

**Comment by magicDGS** [comment]
I prefer to keep out of this user exceptions the arguments from the wrapper script due to downstream projects including tools from GATK (and using the `UserException` classes). Thus, I vote for refere to the `--TMP_DIR`
