### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid interval. 

### ISSUE THREAD

**Issue by chatchawit** [broadinstitute/gatk#4712]
I've got this error.

java.lang.IllegalArgumentException: Invalid interval. Contig:ENST00000342066.7|ENSG00000187634.11|OTTHUMG00000040719.10|OTTHUMT00000276866.2|SAMD11-202|SAMD11|2551|protein_coding| start:0 end:0

I'm working on hg38. The VCF input file was produced from Mutect2.

First, I've the error "java.lang.NullPointerException". So I put only "gencode" folder in the data-source folder. Then, I've got the error message above.

**Comment by lbergelson** [comment]
Hi @chatchawit,

It's hard to tell what's going on from the information you provided.  Could you include the exact commandline that you're trying to run.  Also, the complete stack trace from both the original error and the new error message would be very helpful.

**Comment by jonn-smith** [comment]
@chatchawit Like Louis said, there have been quite a few updates.

The issue you're seeing is a data sources problem relating to HG38.  This has been fixed in the latest release of funcotator and the data sources.

If you grab the latest software and the latest data sources release this problem should go away.

Sorry for the inconvenience.

**Comment by chatchawit** [comment]
I've tried the latest GATK today. The error message changed. Please help. Thanks.

Using GATK jar /omics/chatchawit/gatk2/gatk-package-4.0.4.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /omics/chatchawit/gatk2/gatk-package-4.0.4.0-local.jar Funcotator -R /omics/chatchawit/bundle/hsa38.fasta -V /omics/chatchawit/sm/out/sample21.vcf -O /omics/chatchawit/sm/anno/sample21.vcf --output-file-format VCF --data-sources-path /omics/chatchawit/bundle/dsrc/ --ref-version hg38
10:24:13.971 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/omics/chatchawit/gatk2/gatk-package-4.0.4.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
10:24:14.182 INFO  Funcotator - ------------------------------------------------------------
10:24:14.183 INFO  Funcotator - The Genome Analysis Toolkit (GATK) v4.0.4.0-0.0.2
10:24:14.183 INFO  Funcotator - For support and documentation go to https://software.broadinstitute.org/gatk/
10:24:14.183 INFO  Funcotator - Executing as chatchawit@omics on Linux v3.13.0-133-generic amd64
10:24:14.184 INFO  Funcotator - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_161-b12
10:24:14.184 INFO  Funcotator - Start Date/Time: April 28, 2018 10:24:13 AM ICT
10:24:14.184 INFO  Funcotator - ------------------------------------------------------------
10:24:14.184 INFO  Funcotator - ------------------------------------------------------------
10:24:14.185 INFO  Funcotator - HTSJDK Version: 2.14.3
10:24:14.185 INFO  Funcotator - Picard Version: 2.18.2
10:24:14.186 INFO  Funcotator - HTSJDK Defaults.COMPRESSION_LEVEL : 2
10:24:14.186 INFO  Funcotator - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
10:24:14.186 INFO  Funcotator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
10:24:14.186 INFO  Funcotator - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
10:24:14.186 INFO  Funcotator - Deflater: IntelDeflater
10:24:14.186 INFO  Funcotator - Inflater: IntelInflater
10:24:14.186 INFO  Funcotator - GCS max retries/reopens: 20
10:24:14.186 INFO  Funcotator - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
10:24:14.187 WARN  Funcotator -

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

   Warning: Funcotator is a BETA tool and is not yet ready for use in production

   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


10:24:14.187 INFO  Funcotator - Initializing engine
10:24:15.574 INFO  FeatureManager - Using codec VCFCodec to read file file:///omics/chatchawit/sm/out/sample21.vcf
10:24:15.701 INFO  Funcotator - Done initializing engine
log4j:WARN No appenders could be found for logger (org.broadinstitute.hellbender.tools.funcotator.dataSources.DataSourceUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
10:24:15.728 INFO  FeatureManager - Using codec VCFCodec to read file file:///omics/chatchawit/bundle/dsrc/dbsnp/hg38/hg38_All_20170710.vcf.gz
10:24:15.884 INFO  FeatureManager - Using codec XsvLocatableTableCodec to read file file:///omics/chatchawit/bundle/dsrc/oreganno/hg38/oreganno.tsv
10:24:15.945 INFO  FeatureManager - Using codec GencodeGtfCodec to read file file:///omics/chatchawit/bundle/dsrc/gencode/hg38/gencode.v27.chr_patch_hapl_scaff.annotation.REORDERED.gtf
WARNING 2018-04-28 10:24:17     AsciiLineReader Creating an indexable source for an AsciiFeatureCodec using a stream that is neither a PositionalBufferedStream nor a BlockCompressedInputStream
10:24:29.369 INFO  ProgressMeter - Starting traversal
10:24:29.370 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
10:24:36.192 INFO  Funcotator - Shutting down engine
[April 28, 2018 10:24:36 AM ICT] org.broadinstitute.hellbender.tools.funcotator.Funcotator done. Elapsed time: 0.37 minutes.
Runtime.totalMemory()=5195694080
java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.lang.String.substring(String.java:1967)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createUtrFuncotation(GencodeFuncotationFactory.java:1088)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createGencodeFuncotationOnTranscript(GencodeFuncotationFactory.java:601)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createFuncotationsHelper(GencodeFuncotationFactory.java:529)
        at org.broadinstitute.hellbender.tools.funcotator.dataSources.gencode.GencodeFuncotationFactory.createFuncotationsOnVariant(GencodeFuncotationFactory.java:276)
        at org.broadinstitute.hellbender.tools.funcotator.DataSourceFuncotationFactory.createFuncotations(DataSourceFuncotationFactory.java:137)
        at org.broadinstitute.hellbender.tools.funcotator.DataSourceFuncotationFactory.createFuncotations(DataSourceFuncotationFactory.java:113)
        at org.broadinstitute.hellbender.tools.funcotator.Funcotator.enqueueAndHandleVariant(Funcotator.java:496)
        at org.broadinstitute.hellbender.tools.funcotator.Funcotator.apply(Funcotator.java:387)
        at org.broadinstitute.hellbender.engine.VariantWalkerBase.lambda$traverse$0(VariantWalkerBase.java:110)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.broadinstitute.hellbender.engine.VariantWalkerBase.traverse(VariantWalkerBase.java:108)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:892)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by chatchawit** [comment]
I've checked the README file (see below). I think it's the latest one because I cannot see the newer version in the ftp site.

Funcotator was able to produce some output. So I tried Funcotator with the same VCF input but with only first 5 loci. The program terminated safely.

I hypothesized that the bug happened with only some records in the VCF file which was produced from Mutect2.

Please help.

+---------------------------------------------+
| Data Source Version Information             |
+---------------------------------------------+

Version:          1.2.20180329
Source:           ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/funcotator/funcotator_dataSources.v1.2.20180
329.tar.gz
Alternate Source: gs://broad-public-datasets/funcotator/funcotator_dataSources.v1.2.20180329.tar.gz

**Comment by jonn-smith** [comment]
@chatchawit You're correct - you have the latest version.  I just wanted to double-check.

I think your intuition is correct about it only happening for certain variants.  Are you able to share your file somehow?  I can see where it's happening but having some variants that cause the issue would be helpful to debug.

**Comment by chatchawit** [comment]
I gave two lines that cause the error. By removing these lines,  the program was able to proceed to the next.

chr1  959248  .       A       AAGAT   .       .       DP=111;ECNT=4;POP_AF=0.016;P_GERMLINE=-8.838e-03;TLOD=3.19      GT:AD:AF:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:SA_MAP_AF:SA_POST_PROB     0/1:107,2:0.027:31,2:76,0:16:186,156:40:1:0.00,0.020,0.018:0.073,1.660e-03,0.925

chr1  1273803 .       G       GCGC    .       .       DP=12;ECNT=1;IN_PON;POP_AF=0.016;P_GERMLINE=-1.931e-05;RPA=5,6;RU=CGC;STR;TLOD=6.39     GT:AD:AF:F1R2:F2R1:MBQ:MFRL:MMQ:MPOS:SA_MAP_AF:SA_POST_PROB     0/1:7,2:0.291:4,2:3,0:37:188,211:42:44:0.192,0.192,0.222:0.023,0.021,0.956

**Comment by jonn-smith** [comment]
OK, great.  I'll run these and try to get to the bottom of this.

**Comment by chatchawit** [comment]
Should I wait for a bug fix ? Can I do something to avoid the error? Thanks.

**Comment by jonn-smith** [comment]
Unfortunately this is going to need a code fix.  I should be able to get to it by early next week.

**Comment by jonn-smith** [comment]
Quick update  - this bug occurs when handling alternate alleles (I believe of size > 1 base) in 5' UTRs.

I'm working on a fix now.

**Comment by chatchawit** [comment]
![image](https://user-images.githubusercontent.com/38786115/40131493-50819d2a-5964-11e8-9e95-3c834521f7b7.png)

I guess you've done something. How can I know that the bug has been fixed? How to download and install the new version? Please help. Thank you.

**Comment by jonn-smith** [comment]
@chatchawit I just merged the code into master, so it should be live now.

If you build the GATK from source you will get the latest update - do you need help doing this?

**Comment by chatchawit** [comment]
@jonn-smith  I have sucessfully built GATK by these commands.

git clone https://github.com/broadinstitute/gatk
gradlew bundle

I've got this zip file in folder "build".
gatk-4.0.4.0-34-g2cc7abd-SNAPSHOT.zip

So I unzipped and used this to replace GATK-4.0.4.0 that I downloaded from https://github.com/broadinstitute/gatk/releases/download/4.0.4.0/gatk-4.0.4.0.zip.

I still found errors.

21:09:33.811 INFO  ProgressMeter - Starting traversal
21:09:33.811 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
21:09:46.267 INFO  ProgressMeter -        chr1:24929636              0.2                  3000          14453.2
21:09:59.072 INFO  ProgressMeter -        chr1:64681324              0.4                  6000          14251.2
21:10:09.456 INFO  ProgressMeter -       chr1:156245393              0.6                  9000          15149.8
21:10:21.510 INFO  ProgressMeter -       chr1:206965947              0.8                 12000          15094.7
21:10:26.132 INFO  Funcotator - Shutting down engine
[May 23, 2018 9:10:26 PM ICT] org.broadinstitute.hellbender.tools.funcotator.Funcotator done. Elapsed time: 1.36 minutes.
Runtime.totalMemory()=11500781568
java.lang.IllegalArgumentException: Genomic positions must be > 0.
        at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:722)

What should I do? Can you send me one that is ready-to-use? Thanks.

**Comment by jonn-smith** [comment]
@chatchawit Thanks.  From the stack trace it looks like another issue that I'm actually currently working on.  I'm not sure when it will be done, but I'm going through it as part of fixing #4739 (it's an aggravating bug that will require some refactoring).

**Comment by jonn-smith** [comment]
@chatchawit If you haven't already, try again with the latest release.  It should help.  There are also updated Data Sources in the usual place.

**Comment by jonn-smith** [comment]
@chatchawit Is this still an issue?

**Comment by chatchawit** [comment]
Hi John,


The last time (a couple months ago) I were not able to run the Funcotator with my data. I've already switched to Oncotator and almost finish the project.


Best,

Chatchawit A.


________________________________
