### ISSUE TITLE
Long file names prevent cloning GATK on system with encrypted /home

### ISSUE THREAD

**Issue by TedBrookings** [broadinstitute/gatk#4718]
@droazen  Two .vcf files used for testing prevented cloning the GATK on my home laptop. Supposedly ecryptfs is okay up to 143 characters, but I think that might be _typical_ behavior rather than guaranteed safe. It seems like knocking 10-20 characters off the names should make them totally safe. I don't know how important it is for the files to have metadata in their names.

**length 142:**
src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.CEUTrio.HiSeq.WGS.b37.NA12878.CONTAMINATED.WITH.HCC1143.NORMALS.AT.15PERCENT.calls.20.10100000-10150000.gatk3.8-1-1-gdde23f56a6.g.vcf
**length 140:**
src/test/resources/org/broadinstitute/hellbender/tools/haplotypecaller/expected.CEUTrio.HiSeq.WGS.b37.NA12878.CONTAMINATED.WITH.HCC1143.NORMALS.AT.15PERCENT.calls.20.10100000-10150000.gatk3.8-1-1-gdde23f56a6.vcf

**Comment by droazen** [comment]
If you change PERCENT to PCT, get rid of `.calls`, and get rid of `.AT`, that should hopefully bring you under the limit without removing any useful information from the names :)

**Comment by lbergelson** [comment]
It's a feature, we're so committed to open source that we don't allow it to be made private through encryption.

**Comment by TedBrookings** [comment]
Minor mystery solved. I somehow overlooked the corresponding .vcf.idx files, which were over or at the 144 byte limit, so the errors are less surprising. PR made.
