### ISSUE TITLE
Sparkified Mutect2

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4726]
At some point in the next several quarters @davidbenjamin I'd recommend a collaboration between your team and the engine team on a `Mutect2Spark` tool. Most of the prerequisite infrastructure has already been implemented for `HaplotypeCallerSpark`, so it may be a much simpler task than you'd imagine!

**Comment by droazen** [comment]
@davidbenjamin Probably not this quarter, but I'll be sure to propose it as a project for next quarter.

**Comment by chandrans** [comment]
Thanks for pursuing this D and D :)

**Comment by davidbenjamin** [comment]
I can't envision doing this.  We can re-open in case of a change of heart.
