### ISSUE TITLE
Scatter by contig in somatic CNV WDLs.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#4728]

**Comment by samuelklee** [comment]
Also, plotting can be subset by contig by passing the appropriate sequence dictionary.

**Comment by samuelklee** [comment]
@LeeTL1220 do you have any opinions on making the somatic CNV workflow scatter by contig?  This could allow WGS to complete even faster and could allow us to avoid issues such as #4734.  A few issues:

1) Do we want a single WDL that can optionally scatter, depending on WES vs. WGS?  It would be nicer to have just one workflow, but I haven't thought about how an optional scatter might look in WDL.

2) For data collection, denoising/PoN creation, segmentation, and modeling, scattering should have little impact on the final result (although there are a few global-level quantities in the models that would be reduced to contig-level quantities, which might slightly affect the quality of their inference).  However, we'd want to concatenate all per-contig results for both plotting and segment calling.  It'd be relatively easy to either have a separate tool to concatenate AbstractLocatableCollections (there is already a method to do this that is used for the gCNV pipeline), or to make the plotting and calling tools take in parallel inputs and combine them.  I'd tend towards the former, just so we don't have to deliver per-contig files.

**Comment by samuelklee** [comment]
To add, just in case it wasn't clear, note that this is almost certainly overkill for most somatic applications.  However, if this is going to double as a more lightweight germline pipeline (as it is for the time being, as we are using some of the results to prototype SV integration), it might be worthwhile.

**Comment by sooheelee** [comment]
> Also, plotting can be subset by contig by passing the appropriate sequence dictionary.

Not for the v4.0.1.1 WDL. The sequence dictionary is fixed to that used by PreprocessIntervals.
Manually visualizing with custom sequence dictionaries outside the context of the WDL is possible I guess. Let me fix that phrase in the tutorial draft.

**Comment by samuelklee** [comment]
That's correct.  We could easily add an optional sequence-dictionary input for plotting in the WDL, if desired, but I decided to keep it simple for now.

**Comment by samuelklee** [comment]
Eh, closing this one.  Workflow is fast enough, so this would be more trouble than it's worth for typical numbers of samples.
