### ISSUE TITLE
.so files not deleted from tmp dir on shutdown

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4754]
We have a report on the forum that libgkl.so and libgenomicsdb.so are not deleting themselves on shutdown.  We should fix that.

https://gatkforums.broadinstitute.org/gatk/discussion/comment/48537#Comment_48537

**Comment by erniebrau** [comment]
For GKL, it looks like we're cleaning up properly (see: [code here](https://github.com/Intel-HLS/GKL/blob/master/src/main/java/com/intel/gkl/NativeLibraryLoader.java#L65)). Might this be an issue of improper shutting down of GATK?

**Comment by lbergelson** [comment]
@erniebrau Thanks for checking.  Must be incorrect shutdown then.

**Comment by kgururaj** [comment]
[Fixed now](https://github.com/Intel-HLS/GenomicsDB/blob/master/src/main/java/com/intel/genomicsdb/GenomicsDBLibLoader.java#L96)

**Comment by lbergelson** [comment]
I believe this has been fixed by https://github.com/broadinstitute/gatk/pull/4645
