### ISSUE TITLE
query.json files not deleted after query finishes

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4755]
According to a [forum report](https://gatkforums.broadinstitute.org/gatk/discussion/comment/48537#Comment_48537) the genomicsdb query.json files are not deleted from tmp.  These should be cleaned up when the query is finished and on shutdown in case of exceptions.

**Comment by kgururaj** [comment]
If the JVM crashes, no matter what we do with respect to the query JSON files, there is a chance that the file will not be deleted. If the JVM exits cleanly, then the tmp file will be deleted. I don't think I can improve this any further.

**Comment by lbergelson** [comment]
@kgururaj Yeah, that's fair.  If it doesn't shut down cleanly there's not much that can be done.  Thanks for looking into it.  One thing we could consider is deleting the generated query.json file when we close the reader the created it, as well as marking it for deletion on exit.
