### ISSUE TITLE
Create class to wrap URI and handle URIs to local files automatically

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#477]
We don't want users to have to prepend "file://" to their input/output files. Let's create a class that wraps URI, and prepends "file://" by default when there's no explicit prefix. It should have a constructor that takes a single String to integrate with our argument parsing system.

**Comment by jean-philippe-martin** [comment]
And let's also have something like gg://reference/FOOBAR as a shortcut for using the reference id FOOBAR with the Google Genomics API (what the API calls a "reference set"). And gg://readset/BUZ to use readset BUZ.

**Comment by droazen** [comment]
Closing -- dupe of https://github.com/broadinstitute/gatk/issues/958
