### ISSUE TITLE
GenomicsDB: add support for incremental updates

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4773]
According to @vdauwera, the most-requested GenomicsDB feature from GATK users is the ability to do incremental updates to an existing GenomicsDB.

**Comment by vang42** [comment]
Any updates on this issue? One year old today and still very much needed :)

**Comment by ldgauthier** [comment]
There is a workaround, which is to add the new samples to a new GenomicsDB and then run CombineGVCFs using the two GenomicsDBs as two different inputs.  I've tested this on a small number of samples and it works.  Then you run GenotypeGVCFs on the combined GVCF and continue as usual. The caveat is that you'll need more non-heap memory to support two GDB readers. If you're running on a VM, you will want to increase the memory while keeping the java Xmx/Xms the same.
