### ISSUE TITLE
HaplotypeCaller giving zero byte vcf output file with errorMessage: WARN  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM

### ISSUE THREAD

**Issue by ttamho** [broadinstitute/gatk#4788]
Here is my command:
`gatk --java-options "-Xmx32g" HaplotypeCaller  \
  -R ucsc.hg19.fasta \
  -I ${result}/${outf}_recal_reads.bam \
  -O ${result}/${outf}.g.vcf.gz \
  -G StandardAnnotation \
  -G StandardHCAnnotation \
  -genotyping-mode DISCOVERY \
  -ERC GVCF \
  -bamout ${result}/${outf}_HCbamout.bam`

I suspect there could be issue of memory. Is there any other alternative causes?
The last few lines of the log seems like HaplotypeCaller got cut short and VariantCalibrator jumped in.
Here is VariantRecalibrator command:
java -Xmx6g -jar GenomeAnalysisTK.jar \
    -T VariantRecalibrator \
    -R ${refgen} \
    -input ${result}/${outf}.g.vcf.gz \
    -resource:hapmap,known=false,training=true,truth=true,prior=15.0 ${hapmap} \
    -resource:omni,known=false,training=true,truth=false,prior=12.0 ${omni} \
    -resource:1000G,known=false,training=true,truth=false,prior=10.0 ${phaseonesnp} \
    -resource:dbsnp,known=true,training=false,truth=false,prior=2.0 ${dbsnp} \
    -an DP \
    -an QD \
    -an FS \
    -an MQRankSum \
    -an ReadPosRankSum \
    -mode SNP \
    -tranche 100.0 \
    -tranche 99.9 \
    -tranche 99.0 \
    -tranche 90.0 \
    -recalFile ${result}/${outf}_recalibrate_SNP.recal \
    -tranchesFile ${result}/${outf}_recalibrate_SNP.tranches \
    -rscriptFile ${result}/${outf}_recalibrate_SNP_plots.R

Here is the log:
`package-4.0.1.2-local.jar!/com/intel/gkl/native/libgkl_compression.so

18:58:01.493 INFO  HaplotypeCaller - ------------------------------------------------------------

18:58:01.493 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.0.1.2

18:58:01.493 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/

18:58:01.493 INFO  HaplotypeCaller - Executing as tranahg@i23 on Linux v3.10.0-693.11.6.el7.x86_64 amd64

18:58:01.493 INFO  HaplotypeCaller - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_45-b14

18:58:01.493 INFO  HaplotypeCaller - Start Date/Time: May 17, 2018 6:58:01 PM PDT

18:58:01.493 INFO  HaplotypeCaller - ------------------------------------------------------------

18:58:01.493 INFO  HaplotypeCaller - ------------------------------------------------------------

18:58:01.494 INFO  HaplotypeCaller - HTSJDK Version: 2.14.1

18:58:01.494 INFO  HaplotypeCaller - Picard Version: 2.17.2

18:58:01.494 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 1

18:58:01.494 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false

18:58:01.494 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true

18:58:01.494 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false

18:58:01.494 INFO  HaplotypeCaller - Deflater: IntelDeflater

18:58:01.494 INFO  HaplotypeCaller - Inflater: IntelInflater

18:58:01.494 INFO  HaplotypeCaller - GCS max retries/reopens: 20

18:58:01.494 INFO  HaplotypeCaller - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes

18:58:01.494 INFO  HaplotypeCaller - Initializing engine

18:58:02.043 INFO  HaplotypeCaller - Done initializing engine

18:58:02.053 INFO  HaplotypeCallerEngine - Standard Emitting and Calling confidence set to 0.0 for reference-model confidence output

18:58:02.053 INFO  HaplotypeCallerEngine - All sites annotated with PLs forced to true for reference-model confidence output

18:58:02.886 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/gatk/4.0.1.2/gatk-package-4.0.1.2-local.jar!/com/intel/gkl/native/libgkl_utils.so

18:58:02.888 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/bigdata/operations/pkgadmin/opt/linux/centos/7.x/x86_64/pkgs/gatk/4.0.1.2/gatk-package-4.0.1.2-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so

18:58:02.932 WARN  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM

18:58:02.933 INFO  IntelPairHmm - Available threads: 8

18:58:02.933 INFO  IntelPairHmm - Requested threads: 4

18:58:02.933 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation

18:58:02.986 INFO  ProgressMeter - Starting traversal

18:58:02.987 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute

18:58:12.992 INFO  ProgressMeter -         chr1:6969901              0.2                 23290         139712.1

18:58:22.989 INFO  ProgressMeter -        chr1:13470130              0.3                 44960         134866.5

18:58:32.991 INFO  ProgressMeter -        chr1:21393130              0.5                 71370         142721.0

INFO  18:58:37,986 HelpFormatter - ---------------------------------------------------------------------------------- 

INFO  18:58:37,989 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.8-0-ge9d806836, Compiled 2017/07/28 21:26:50 

INFO  18:58:37,989 HelpFormatter - Copyright (c) 2010-2016 The Broad Institute 

INFO  18:58:37,989 HelpFormatter - For support and documentation go to https://software.broadinstitute.org/gatk 

INFO  18:58:37,989 HelpFormatter - [Thu May 17 18:58:37 PDT 2018] Executing on Linux 3.10.0-693.11.6.el7.x86_64 amd64 

INFO  18:58:37,989 HelpFormatter - Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 

INFO  18:58:37,992 HelpFormatter - Program Args: -T VariantRecalibrator -R ucsc.hg19.fasta -input /rhome/`

#IntelPairHMM #HaplotypeCaller

**Comment by davidbenjamin** [comment]
@droazen Should we triage this?

**Comment by droazen** [comment]
@davidbenjamin The message "Flush-to-zero (FTZ) is enabled when running PairHMM" is completely normal and not a sign of any problem. The ticket does not have enough detail for us to determine why the output file was empty.

**Comment by davidbenjamin** [comment]
In that case, let's close it.  It's almost two years old.
