### ISSUE TITLE
germline CNV

### ISSUE THREAD

**Issue by wujh2017** [broadinstitute/gatk#4790]
I have got my result using 32 samples.but there is a problem that too many variants in the "sample_x_genotyped_segments.vcf" which i don't expect,it has 24987 vairants.So what happend and what should i do ?
it's my samples' problem or i just need to filter the vcf file ? 
##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Segment most-likely copy-number call">
##FORMAT=<ID=GT,Number=1,Type=Integer,Description="Segment genotype">
##FORMAT=<ID=NP,Number=1,Type=Integer,Description="Number of points (i.e. targets or bins) in the segment">
##FORMAT=<ID=QA,Number=1,Type=Integer,Description="Complementary Phred-scaled probability that all points (i.e. targets or bins) in the segment agree with the segment copy-number call">
##FORMAT=<ID=QS,Number=1,Type=Integer,Description="Complementary Phred-scaled probability that at least one point (i.e. target or bin) in the segment agrees with the segment copy-number call, divid
##FORMAT=<ID=QSE,Number=1,Type=Integer,Description="Complementary Phred-scaled probability that the segment end position is a genuine copy-number changepoint">
##FORMAT=<ID=QSS,Number=1,Type=Integer,Description="Complementary Phred-scaled probability that the segment start position is a genuine copy-number changepoint">
##GATKCommandLine=<ID=PostprocessGermlineCNVCalls,CommandLine="PostprocessGermlineCNVCalls  --calls-shard-path ../GermlineCNVCaller/COHORT_test-calls --model-shard-path ../GermlineCNVCaller/COHORT_
##INFO=<ID=END,Number=1,Type=Integer,Description="End coordinate of the variant">
##source=PostprocessGermlineCNVCalls
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  R32
chr1    14363   CNV_chr1_14363_16765    N       <DEL>,<DUP>     .       .       END=16765       GT:CN:NP:QA:QS:QSE:QSS  1:1:4:35:23:25:64
chr1    16858   CNV_chr1_16858_17055    N       <DEL>,<DUP>     .       .       END=17055       GT:CN:NP:QA:QS:QSE:QSS  1:0:1:25:25:25:25
chr1    17233   CNV_chr1_17233_17742    N       <DEL>,<DUP>     .       .       END=17742       GT:CN:NP:QA:QS:QSE:QSS  1:1:2:49:38:49:25
chr1    69091   CNV_chr1_69091_70008    N       <DEL>,<DUP>     .       .       END=70008       GT:CN:NP:QA:QS:QSE:QSS  1:0:1:272:272:272:272
chr1    661140  CNV_chr1_661140_665184  N       <DEL>,<DUP>     .       .       END=665184      GT:CN:NP:QA:QS:QSE:QSS  2:4:1:3:3:3:3
chr1    761587  CNV_chr1_761587_763155  N       <DEL>,<DUP>     .       .       END=763155      GT:CN:NP:QA:QS:QSE:QSS  0:2:2:18:35:16:70
chr1    783034  CNV_chr1_783034_789740  N       <DEL>,<DUP>     .       .       END=789740      GT:CN:NP:QA:QS:QSE:QSS  2:3:5:12:6:30:11
chr1    803453  CNV_chr1_803453_812182  N       <DEL>,<DUP>     .       .       END=812182      GT:CN:NP:QA:QS:QSE:QSS  2:5:3:14:7:28:19
chr1    852953  CNV_chr1_852953_861393  N       <DEL>,<DUP>     .       .       END=861393      GT:CN:NP:QA:QS:QSE:QSS  0:2:6:50:17:50:49
chr1    865535  CNV_chr1_865535_871276  N       <DEL>,<DUP>     .       .       END=871276      GT:CN:NP:QA:QS:QSE:QSS  2:4:3:13:5:28:14
chr1    874420  CNV_chr1_874420_892653  N       <DEL>,<DUP>     .       .       END=892653      GT:CN:NP:QA:QS:QSE:QSS  0:2:25:45:12:72:44
chr1    894309  CNV_chr1_894309_896180  N       <DEL>,<DUP>     .       .       END=896180      GT:CN:NP:QA:QS:QSE:QSS  2:4:3:12:5:34:13
chr1    896673  CNV_chr1_896673_1182102 N       <DEL>,<DUP>     .       .       END=1182102     GT:CN:NP:QA:QS:QSE:QSS  0:2:130:10:12:22:39
chr1    1189294 CNV_chr1_1189294_1209234        N       <DEL>,<DUP>     .       .       END=1209234     GT:CN:NP:QA:QS:QSE:QSS  2:4:8:3:3:8:16
chr1    1219358 CNV_chr1_1219358_1278138        N       <DEL>,<DUP>     .       .       END=1278138     GT:CN:NP:QA:QS:QSE:QSS  0:2:85:20:12:31:10
chr1    1284276 CNV_chr1_1284276_1293915        N       <DEL>,<DUP>     .       .       END=1293915     GT:CN:NP:QA:QS:QSE:QSS  2:3:11:7:6:7:14
chr1    1309110 CNV_chr1_1309110_1356650        N       <DEL>,<DUP>     .       .       END=1356650     GT:CN:NP:QA:QS:QSE:QSS  0:2:25:22:13:48:7
chr1    1361508 CNV_chr1_1361508_1376145        N       <DEL>,<DUP>     .       .       END=1376145     GT:CN:NP:QA:QS:QSE:QSS  2:4:5:10:5:24:12
chr1    1385069 CNV_chr1_1385069_1412730        N       <DEL>,<DUP>     .       .       END=1412730     GT:CN:NP:QA:QS:QSE:QSS  0:2:13:7:13:24:50
chr1    1414024 CNV_chr1_1414024_1414488        N       <DEL>,<DUP>     .       .       END=1414488     GT:CN:NP:QA:QS:QSE:QSS  1:1:2:23:14:35:28
chr1    1416247 CNV_chr1_1416247_1417994        N       <DEL>,<DUP>     .       .       END=1417994     GT:CN:NP:QA:QS:QSE:QSS  2:4:3:10:4:29:10
chr1    1420396 CNV_chr1_1420396_1452792        N       <DEL>,<DUP>     .       .       END=1452792     GT:CN:NP:QA:QS:QSE:QSS  0:2:11:28:15:30:40
chr1    1453096 CNV_chr1_1453096_1453155        N       <DEL>,<DUP>     .       .       END=1453155     GT:CN:NP:QA:QS:QSE:QSS  1:0:1:37:37:37:37
chr1    1454301 CNV_chr1_1454301_1480382        N       <DEL>,<DUP>     .       .       END=1480382     GT:CN:NP:QA:QS:QSE:QSS  0:2:18:29:15:8:44
chr1    1500153 CNV_chr1_1500153_1510262        N       <DEL>,<DUP>     .       .       END=1510262     GT:CN:NP:QA:QS:QSE:QSS  2:4:2:2:2:13:2
chr1    1550884 CNV_chr1_1550884_1564102        N       <DEL>,<DUP>     .       .       END=1564102     GT:CN:NP:QA:QS:QSE:QSS  0:2:16:21:10:15:22
chr1    1564513 CNV_chr1_1564513_1567753        N       <DEL>,<DUP>     .       .       END=1567753     GT:CN:NP:QA:QS:QSE:QSS  2:3:5:7:5:7:15
chr1    1571695 CNV_chr1_1571695_1576474        N       <DEL>,<DUP>     .       .       END=1576474     GT:CN:NP:QA:QS:QSE:QSS  0:2:9:16:7:21:7
chr1    1577267 CNV_chr1_1577267_1577362        N       <DEL>,<DUP>     .       .       END=1577362     GT:CN:NP:QA:QS:QSE:QSS  1:0:1:238:238:238:238
chr1    1592940 CNV_chr1_1592940_1608285        N       <DEL>,<DUP>     .       .       END=1608285     GT:CN:NP:QA:QS:QSE:QSS  2:3:8:10:4:11:15
chr1    1623888 CNV_chr1_1623888_1624243        N       <DEL>,<DUP>     .       .       END=1624243     GT:CN:NP:QA:QS:QSE:QSS  2:5:1:4:4:4:4
chr1    1632800 CNV_chr1_1632800_1639684        N       <DEL>,<DUP>     .       .       END=1639684     GT:CN:NP:QA:QS:QSE:QSS  0:2:10:13:12:17:14
chr1    1640477 CNV_chr1_1640477_1640572        N       <DEL>,<DUP>     .       .       END=1640572     GT:CN:NP:QA:QS:QSE:QSS  1:0:1:266:266:266:266
chr1    1650798 CNV_chr1_1650798_1655705        N       <DEL>,<DUP>     .       .       END=1655705     GT:CN:NP:QA:QS:QSE:QSS  2:4:3:3:2:13:4
chr1    1663681 CNV_chr1_1663681_1756938        N       <DEL>,<DUP>     .       .       END=1756938     GT:CN:NP:QA:QS:QSE:QSS  0:2:27:8:15:6:12
chr1    1770629 CNV_chr1_1770629_1770677        N       <DEL>,<DUP>     .       .       END=1770677     GT:CN:NP:QA:QS:QSE:QSS  2:4:1:1:1:1:1
chr1    1846266 CNV_chr1_1846266_1850527        N       <DEL>,<DUP>     .       .       END=1850527     GT:CN:NP:QA:QS:QSE:QSS  0:2:10:24:16:29:6
chr1    1884752 CNV_chr1_1884752_1888223        N       <DEL>,<DUP>     .       .       END=1888223     GT:CN:NP:QA:QS:QSE:QSS  2:4:2:8:5:2:9
chr1    1890559 CNV_chr1_1890559_1935276        N       <DEL>,<DUP>     .       .       END=1935276     GT:CN:NP:QA:QS:QSE:QSS  2:3:16:1:4:21:2
chr1    1956381 CNV_chr1_1956381_1962192        N       <DEL>,<DUP>     .       .       END=1962192     GT:CN:NP:QA:QS:QSE:QSS  0:2:8:23:11:27:23

>

**Comment by samuelklee** [comment]
Hi @wujh2017,

You should filter your variants using the various quality scores described in the VCF header.  We find that simply filtering on QS is typically a good strategy.

Also, you might find it more helpful to post this sort of question in the GATK forums---other users might benefit from seeing the answer there.
