### ISSUE TITLE
Funcotator requires all GENCODE datasources (in the config) to be named "Gencode"

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#4791]
This is because the GencodeFuncotationFactory will force the datasource name (`getName()`) to return "Gencode".  However, some areas of the code (e.g. `Funcotator.java`) will query the name from the config file.  If these do not match, confusion ensues.  You will get IGRs for everything, since all queries into the datasource will yield no found features/transcripts.

**Comment by droazen** [comment]
beta blocker?

**Comment by LeeTL1220** [comment]
@jonn-smith Didn't you already fix this?

**Comment by jonn-smith** [comment]
Yes - this was fixed in #3956
