### ISSUE TITLE
Funcotator can't handle variants that start outside an exon and end within an exon

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#4804]
Funcotator must be able to handle indels that span exon start boundaries.

For example, in `hg19` the following variant is not handled properly:

chr5:71622537-71622538 CA->C

The current workaround is to throw a `FuncotatorUtils.TranscriptCodingSequenceException` for the transcript causing this problem in Gencode.

**Comment by jonn-smith** [comment]
This is related to #4307

**Comment by droazen** [comment]
@jonn-smith I think you should close this issue in favor of https://github.com/broadinstitute/gatk/issues/4307, since https://github.com/broadinstitute/gatk/issues/4307 is a strict superset of this issue.

**Comment by jonn-smith** [comment]
OK - will do.
