### ISSUE TITLE
Mutect isActive loses sensitivity when allele fraction is comparable to base error rate

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#4816]
If you look at the approximation going from equation 34 to 35 in https://github.com/broadinstitute/gatk/blob/master/docs/mutect/mutect.pdf you will find that we replace f(1 - e) + (1 - f)e by just f(1 - e), where f is the allele fraction and e is the error rate.  When f is much bigger than e this is okay but when they are comparable (consider mitochondrial or cfDNA calling with f = 1% and base qualities of 25) the approximation breaks down and we significantly underestimate the log odds, thereby failing to consider a region active.

This must be fixed!

@meganshand

**Comment by meganshand** [comment]
@fleharty This might be of interest.

**Comment by davidbenjamin** [comment]
Closed by #4832.
