### ISSUE TITLE
Add jitpack.yml to build snapshots

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#4819]
Using https://jitpack.io/#broadinstitute/gatk for building SNAPSHOTS (independent on your jfrog repository, which has a expired date for snapshots - https://github.com/broadinstitute/gatk/issues/4565) is not working any longer due to the requirement of git-lfs (e.g., https://jitpack.io/com/github/broadinstitute/gatk/4.0.4.0/build.log)

It will be nice to add a `jitpack.yml` file (see https://jitpack.io/docs/BUILDING/#custom-commands) to install dependencies - this will be useful for downstream project depending on SNAPSHOTS.

**Comment by lbergelson** [comment]
@magicDGS We should do this, it seems useful.  I haven't had any bandwidth to take a look at it yet though.
