### ISSUE TITLE
Creating Conda gatk env error

### ISSUE THREAD

**Issue by jjfarrell** [broadinstitute/gatk#4822]
I am getting the following error when creating the gatk environment with conda env create -n gatk -f scripts/gatkcondaenv.yml

NoPackagesFoundError: Package missing in current linux-64 channels:
  - intel-openmp 2018.0.0*

Below is the complete listing. Any suggestions?

.```
/gradlew createPythonPackageArchive
:createPythonPackageArchive UP-TO-DATE

BUILD SUCCESSFUL

Total time: 13.183 secs

 conda env create -n gatk -f scripts/gatkcondaenv.yml
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............

NoPackagesFoundError: Package missing in current linux-64 channels:
  - intel-openmp 2018.0.0*
```

**Comment by lucidtronix** [comment]
I've had this issue on MacOS X and was able to install the environment successfully by removing the open-mp and mkl lines from the yaml:
```
- intel-openmp=2018.0.0
- mkl=2018.0.1
- mkl-service=1.1.2
``` 
Then you may need to remove the partially installed environment with:
```
conda remove --name gatk --all
```
Then hopefully you can run:
```
conda create -n gatk -f ./scripts/gatkcondaenv.yml
```
Hopefully, the tools will run without openmp and mkl, but I'm sure we are taking a performance hit so we should figure out what is the right channel to point to for these packages.  @erniebrau have you ever had these isssues?

**Comment by yeroslaviz** [comment]
This is not working. Is there another way to install the python pacakges for `CNNScoreVariants`?

I get this error:

```
 conda create -n gatk -f ./scripts/gatkcondaenv.yml
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - ./scripts/gatkcondaenv.yml

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/r/linux-64
  - https://conda.anaconda.org/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by cmnbroad** [comment]
@yeroslaviz Are you trying to create the environment from a cloned github repo, or from a zip installation of GATK ? It looks like its from a repo, in which case you need to follow the instructions [here](https://github.com/broadinstitute/gatk#python). (gatkcondaenv.yml is generated from sources by a gradle task, so running gradle is required unless you're creating the env from an install).
