### ISSUE TITLE
Bamout aligns non-spanning reads to false deletions in STRs

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#4829]
The following screenshot of a bamout is common in HaplotypeCaller and Mutect2:

![screen shot 2018-05-30 at 2 36 58 pm](https://user-images.githubusercontent.com/8438890/40759148-b860a5da-645e-11e8-8f94-21534ed9ab48.png)

Notice how all of the reads that appear to support a single-base deletion actually do not because they do not span the poly-T homopolymer.  This makes the bamout harder to interpret.  In this particular case (of a false positive M2 insertion) it is a red herring because it suggests that the multiallelicness of the site is relevant to the false positive deletion.

One could ask what in the GATK engine is responsible.

* The assembly engine, perhaps?  No, it is the assembly engine's job to propose possible haplotypes, not to call them.  In any case, there *is* one spanning read with the deletion above the reads shown, so it is a valid path in the graph.
* Pair-HMM?  This one confused me for a while, but no.  The engine is *not* saying that these reads' best alignment to the reference has a deletion, which would be false because there is a gap opening penalty.  Rather, it says that they align equally well (with no deletions) to the ref haplotype and to the deletion haplotype.  The deletion shown in IGV is the deletion of the alt haplotype relative to the reference, not of the reads relative to their best haplotype.
* The bamout writer?  Nope, that code is really straightforward and does the right thing.

So what's the issue?  Well, the bamout writer gets its read alignments from the `readLikelihoods` after the reads have been realigned to their best haplotype.  In these cases, it turns out that the alignment of the reads to their best haplotype, the deletion has a log likelihood better than the alignment to the ref haplotype by about 0.00001.  The simplest solution would be to give an extremely modest prior in favor of the reference and break these near-ties in favor of the reference.  @droazen @ldgauthier @yfarjoun if you think this is a good idea I can fix it for both HC and M2.  Otherwise I'll do an M2-only fix.

**Comment by yfarjoun** [comment]
I don't understand the reason for the 0.00001 preference for the alt
haplotype...the alignments are identical: all bases match. so why is there
a preference? is there a preference for a shorter haplotype somehow?

**Comment by ldgauthier** [comment]
I found the data from yet another example of this behavior (see poorly aligned reads in the bamout -- somehow the big fat deletion is preferred over the reference):
![dlbcl-c_d_pair13 nkap x_119059262 frame_shift_del ctctcttcttggttaaaggatgcaaggg_-](https://user-images.githubusercontent.com/6578548/40785072-7fdff344-64b5-11e8-8539-78267b9a2950.png)

tumor exome:  /seq/picard_aggregation/C1637/c_D_pair13_Dx/v3/c_D_pair13_Dx.bam
normal exome:  /seq/picard_aggregation/C1637/RICOVER_134_N/v2/RICOVER_134_N.bam
M2 tumor bam:  /xchip/cga_home/stewart/Cancer/DLBCL/M2/test/c_D_pair13_Dx.bam
M2 normal bam:  /xchip/cga_home/stewart/Cancer/DLBCL/M2/test/RICOVER_134_N.bam
M2 combined bam:  /xchip/cga_home/stewart/Cancer/DLBCL/M2/test/DLBCL-c_D_pair13.M2_validation_bam.bam
I can't guarantee the data is still around and I don't have the exact intervals, but if it doesn't reproduce in the latest GATK4 M2 then we can forget about it.  If it does reproduce then it would put my mind at ease if the prior fixes this case too (and you could let Chip know that it got fixed 2.5 years later :-P)

**Comment by davidbenjamin** [comment]
The marginalization over all paths, not the the likeliest one, would make a small difference, but I'm not sure in which direction.  In fact, I would even guess it would tend to favor the reference over a deletion because there are more contributions from things like TTTTT -> TT(DELETE A T)TT(INSERT A T)T that don't actually change the bases but do contribute to the sum.  That is, if the reference has a longer poly-T, there are more places to put the cancelling deletion(s) and insertion(s).  However, all this stuff incurs gap opening penalties and I would be surprised if it could make a difference as big as 0.07.

I think I know what can, however.  If you take a look at the top of page 3 of our pair-HMM docs https://github.com/broadinstitute/gatk/blob/master/docs/pair_hmm.pdf, you will see, as @yfarjoun guessed, that there is a preference for shorter haplotypes in the form of a 1/haplotype length factor.  And in fact, this amount seems to be in the right ballpark.  For example, @ldgauthier's case is a 28-base deletion.  If you calculate the log_10 ratio of the 1/length factors assuming a 100-base deletion haplotype, you get log_10(128/100) = 0.107.

This, by the way, would explain why we don't see this sort of thing with insertions.

We could simply say that any uninformative read (a log likelihood difference of 0.2) should go to the reference if that is the second best.  That's basically the prior I was talking about.

The M2-only solution would be to use the somatic likelihoods model on the haplotypes and remove unsupported haplotypes from the likelihoods matrix.  Similarly, I could use it to align reads to the haplotype with the greatest posterior probability.

**Comment by yfarjoun** [comment]
is there a haplotype-based prior that uses the alignment of the haplotype
to the reference? A prior that depends on the alignment might be better
than a flat pro-reference prior

**Comment by davidbenjamin** [comment]
We could concoct one, but it might introduce more reference bias than a flat but modest epsilon nudge.

**Comment by davidbenjamin** [comment]
@ldgauthier I made a branch that gives the nod to reference haplotype when the likelihood is uninformative (more precisely, when the reference likelihood is within the uninformative threshold -- it doesn't choose the reference in case of a tie between two non-ref haplotypes!) and ran it on a NA12878 exome and compared with master.  There are a few thousand differences in the whole exome, mainly `DP -> DP +/- 1` and tiny changes in `BaseQualityRankSum`.  I looked at a bunch of the bamouts for these sites and in *every* case the new bamout made more sense.  Here are some examples; they get boring after a while.  Top is old, bottom is new.
<img width="670" alt="screen shot 2018-06-06 at 9 21 31 pm" src="https://user-images.githubusercontent.com/8438890/41073508-9fe5c382-69d1-11e8-920a-5838b649e669.png">
<img width="833" alt="screen shot 2018-06-06 at 9 22 29 pm" src="https://user-images.githubusercontent.com/8438890/41073510-9ff44ce0-69d1-11e8-8800-ef28ab0c9e9f.png">
<img width="834" alt="screen shot 2018-06-06 at 9 24 01 pm" src="https://user-images.githubusercontent.com/8438890/41073511-a0034fb0-69d1-11e8-967a-a20e85578d57.png">
<img width="778" alt="screen shot 2018-06-06 at 9 24 38 pm" src="https://user-images.githubusercontent.com/8438890/41073512-a010cf82-69d1-11e8-8e16-0f6789a8bf47.png">
<img width="743" alt="screen shot 2018-06-06 at 9 24 57 pm" src="https://user-images.githubusercontent.com/8438890/41073513-a01dbae4-69d1-11e8-828a-af634ac3caea.png">
<img width="899" alt="screen shot 2018-06-06 at 9 26 48 pm" src="https://user-images.githubusercontent.com/8438890/41073514-a02a075e-69d1-11e8-9a4c-f969000bb09e.png">
<img width="844" alt="screen shot 2018-06-06 at 9 27 16 pm" src="https://user-images.githubusercontent.com/8438890/41073515-a0412af6-69d1-11e8-98e8-c8c10d6be1c6.png">
<img width="792" alt="screen shot 2018-06-06 at 9 28 17 pm" src="https://user-images.githubusercontent.com/8438890/41073516-a04e6be4-69d1-11e8-9db7-8da8eaf978f5.png">

**Comment by ldgauthier** [comment]
I love it!  Especially that second one where the 5bp deletion goes to no deletion with a low qual G at the read end.  (I'm assuming something similar happens in the last example, but I don't see a read in the bottom that looks like it could match the 6bp deletion in the top.) Submit a PR and I can review.
