### ISSUE TITLE
Funcotator support for MT protein change

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#4863]
### Tool(s) or class(es) involved
Funcotator

### Description
- Funcotator needs to have an option to annotate protein change in mitochondria
- Important:  Note that mitochondria uses different codons.
https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi#SG2
- Gencode v28 (at least) has transcripts.
- First version of this solution can be for mitochondria-only VCFs (most-likely from M2).
While this is not high priority now, it may become high priority around September 2018.

**Comment by jonn-smith** [comment]
Codon table is here:

https://en.wikipedia.org/wiki/Vertebrate_mitochondrial_code

Note: there are implied changes / requirements for specific species, humans included.

**Comment by jonn-smith** [comment]
This should be straight-forward once the discussion above is resolved.

Just detect if the variant is on a known Mitochondrial contig.  If so, use the MT codon table, otherwise use the regular codon table.

**Comment by jonn-smith** [comment]
From Sarah Calvo:

```

AGA | Ter * | Arg R
-- | -- | --
AGG | Ter * | Arg R
AUA | Met M | Ile I
UGA | Trp W | Ter *

```

**Comment by jonn-smith** [comment]
I actually will implement special case testing for each different genus that is listed on the wiki page for now.

**Comment by jonn-smith** [comment]
Must rebase on master after merging #5302
