### ISSUE TITLE
Port FastaAlternateReferenceMaker to GATK4

### ISSUE THREAD

**Issue by chandrans** [broadinstitute/gatk#4891]
@chandrans commented on [Wed Jan 17 2018](https://github.com/broadinstitute/dsde-docs/issues/2852)

Is FastaAlternateReferenceMaker going to be in GATK4?  I did not see any mention of it. I hope other users will request it if there is demand.

----
User Report
----

Where is the fastaalternatereferencemaker in GATK4.0?
I want to build a reference with mutation by fastaalternatereferencemaker, but I can not find the  commond
of fastaalternatereferencemaker , please tell me where ? 
Thank you !

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/11210/about-fastaalternatereferencemaker-in-gatk-4-0/p1

**Comment by chandrans** [comment]
6 people have requested this. I realize this is still low priority, but any chance someone would be willing to take this on?

**Comment by Genetics2-tokyo** [comment]
Hi
Where is the fastaalternatereferencemaker in GATK4.0?

**Comment by AidanQuinn** [comment]
It's a very useful tool, would be great to have included in GATK4!

**Comment by ryfa5051** [comment]
Would love to have this in GATK4, hopefully with an option for keeping the fasta headers to the name after the whitespace and not the default 1, 2, 3, etc. This would make it ideal for moving that data to Sequencher or any other assembly by name program.

**Comment by AgaricX** [comment]
This is an essential tool for people examining regions with both variant and invariant sites - basically anyone studying evolution.  Please add this to 4.0.

**Comment by davidecarlson** [comment]
I would love to have this in GATK4 as well!

**Comment by TepoltC** [comment]
I'd also love to see this feature in v4 - as has been stated above, it's a great tool for a lot of evolutionary work.

**Comment by lecook** [comment]
This would be amazing to have in GATK 4. Super useful!

**Comment by lbi-usp** [comment]
Count me as another who would like to have it on GATK 4

**Comment by avneeshbt** [comment]
Please count me also. It is very useful tool. My whole pipeline is with GATK4, so it would be best to have this tool too.

**Comment by rvosa** [comment]
I would also like to have this, thanks.

**Comment by kescull** [comment]
I'd also like to see this tool in GATK4. I'm just starting out in the area, but I think it will be useful for our proteogenomics-based work.

**Comment by leoqiang** [comment]
I would also like to have it in GATK4.

**Comment by ryfa5051** [comment]
How soon is the near future?

**Comment by droazen** [comment]
@ryfa5051 It's scheduled to be ported this quarter (so, either this month or next month).
