### ISSUE TITLE
Retire the MarkDuplicatesGATK tool (for now)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#4896]
@jamesemery has found that he's been able to make `MarkDuplicatesSpark` call directly into Picard code for much core functionality. As a result, `MarkDuplicatesGATK` has gotten out-of-date relative to both the Spark version and the Picard version.

I think that we should remove `MarkDuplicatesGATK` for now, as it's likely just confusing users. Longer term, we should still discuss migrating development of the Picard `MarkDuplicates` tool to GATK in order to avoid constant divergence between that version and the Spark version, but if we end up doing this we'd likely want to re-port from scratch anyway rather than use `MarkDuplicatesGATK` as a starting point.

**Comment by lbergelson** [comment]
That seems like the right choice, we should also remove the corresponding EstimateLibraryComplexityGATK
