### ISSUE TITLE
add kohlk to the AUTHORS file

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#4908]
@kohlk just had their first PR merged.  We should add them to the AUTHORS file.  

Typically we list people as

```
First and Last Name <email@address>
```

@kohlk You don't have any contact information listed on your github, would you like to be added and if so how should list you?

**Comment by kohlk** [comment]
I would love to be added and intend on contributing however I can!

Kohl Kinning kohlkinning@gmail.com

**Comment by kohlk** [comment]
I am logged in to an old account, that's why I've got no info! I'll henceforth be contribution from @kohlkopf. The contact information is the same. I need to deactivate this ratty old account.

**Comment by lbergelson** [comment]
This was closed by https://github.com/broadinstitute/gatk/pull/4910
