### ISSUE TITLE
Implement CollectInsertSizeMetrics in dataflow

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#491]
Implement a version of CollectInsertSizeMetrics that runs on dataflow and produces the same output as the current picard version.  

It seems like a pretty simple and fairly representative metric.  

Should deal with #468 as part of this.

**Comment by lbergelson** [comment]
I am not going to attempt to run the RScripts this calls in dataflow.

**Comment by akiezun** [comment]
equirement: existing integration tests (CollectInsertSizeMetricsTest) need to produce identical results

**Comment by akiezun** [comment]
closing this dataflow ticket. spark ticket is #1012
