### ISSUE TITLE
Transcript list (userRequestedTranscripts) is acting as a filter, when it should be for prioritizing transcripts during selection.

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#4918]
### Affected tool(s) or class(es)
Funcotator

### Affected version(s)
- [ ] Latest master branch as of [June 19, 2018]

#### Expected behavior
The transcript list should define transcript priority.  In other words, among transcripts that overlap a variant, any that appear on the transcript list should be given highest priority (above the EFFECT or CANONICAL selection)

#### Actual behavior
Currently, the transcript list is a filter -- i.e. if a transcript is not in the list, it will never be used.

**Comment by LeeTL1220** [comment]
And need to add tests?

**Comment by jonn-smith** [comment]
Yeah - I just looked.  You're correct.
