### ISSUE TITLE
Inaccurate javadoc in FragmentUtils method

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#4932]
The javadoc above `FragmentUtils.adjustQualsOfOverlappingPairedFragments` says that it may return a merged strandless read.  This is false -- in fact it is a `void` method that modifies the paired reads in-place.

**Comment by davidbenjamin** [comment]
Perhaps this was closed by mistake.

**Comment by lbergelson** [comment]
@davidbenjamin It was closed by #5104.

**Comment by kvinter1** [comment]
Fixed by https://github.com/broadinstitute/gatk/pull/5104#pullrequestreview-146111705

**Comment by lbergelson** [comment]
It's useful to put something like  `fixes #5104` in the commit message.  That way it automatically closes the issue and shows a link from the PR to the Issue.

**Comment by kvinter1** [comment]
Yep, sorry. Just learned that as you were closing it.

**Comment by davidbenjamin** [comment]
Ah, got it.  By the way, @kvinter1 thanks for being the first person to take on a "learn GATK" issue!
