### ISSUE TITLE
Mutect2 and haplotypecaller require UCSC chromosome names

### ISSUE THREAD

**Issue by evcon131** [broadinstitute/gatk#4939]
### Affected tool(s) or class(es)
HaplotypeCaller Mutect2

### Affected version(s)
GATK 4.0.4.0
6/20/18
### Description 
When running either mutect2 or haplotypecaller on a custom genome, the returned VCFs will be empty if the chromosome names are in the ensembl format. 
#### Steps to reproduce
 For example if the reference fasta looks like this
```
head ../../cf3genome.fa
>1 dna:chromosome chromosome:CanFam3.1:1:1:122678785:1 REF
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTATGTGAGAAGATAGCTGAA
CGCCTTGTCCACATCATCTTACTGCTGAGAGTTGAGCTCACCCTCAGTCCCTCACAGTTC
CACACTGCCTGCAGAGTGAGTTTCCCATGTCTTCACCAGAGACTTTTGCCAGAGGCTTCT
GAGACGCAAGTTAACAATGCAGACCTGGAGGGTATCTCCAGGTGCAGTAGAGTGGTAATC
TCGGAACCTCCTGACTCAGAATACTGCTACCTTCACACTGTCATAAGAATGCAGCGAGTT
GAGAGCTGGCTTCTAGGCATGCTTCCTTTTGAGAGCTGAGGACAGGACAGAACCCTCCCG
CATCCTGCCTGACTGTAGACGTACCTGCTAACCTCCTCATGTTAGTGGCTGGGATAGATT
GTGGGAAAAGCATGTGTAAGCATTGGGCCTGAACTCCCGTGTATCTGAGTTGAATACAGC
```
and the mutect2 call looks like this:
```
gatk Mutect2 \
-R ../../cf3genome.fa \
-I in.bam \
--tumor-sample in \
-O vcfs/out.vcf
```
The resultant vcf is empty. There is a header just no variants. 
However, if the reference fasta has UCSC style names it will work. If the reference fasta looks like this
```
 head ../../canFam3.fa
>chr1
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
TATGTGAGAAGATAGCTGAACGCCTTGTCCACATCATCTTACTGCTGAGA
GTTGAGCTCACCCTCAGTCCCTCACAGTTCCACACTGCCTGCAGAGTGAG
TTTCCCATGTCTTCACCAGAGACTTTTGCCAGAGGCTTCTGAGACGCAAG
TTAACAATGCAGACCTGGAGGGTATCTCCAGGTGCAGTAGAGTGGTAATC
TCGGAACCTCCTGACTCAGAATACTGCTACCTTCACACTGTCATAAGAAT
GCAGCGAGTTGAGAGCTGGCTTCTAGGCATGCTTCCTTTTGAGAGCTGAG
GACAGGACAGAACCCTCCCGCATCCTGCCTGACTGTAGACGTACCTGCTA
```
#### Expected behavior
I would expect either to work if your bams are consistent in style
#### Actual behavior
The tools require UCSC style chromosome names regardless.

**Comment by lbergelson** [comment]
@evcon131 Just to clarify, what does the header in the bam say?  When you say "consistent in style" I assume you mean the bam header matches the reference?  I.e. if your bam is using contigs `1, 2, 3, etc` then your reference should match and if it's `chr1, chr2, chr3, etc` then the reference should match that.   

If the bam is `1, 2, 3` and the reference is `chr1, chr2, chr3` we should really be throwing an exception.

**Comment by evcon131** [comment]
So I mean the bam header is contig 1 2 3 like this:@SQ SN:1 LN:122678785

@SQ SN:10 LN:69331447
@SQ SN:11 LN:74389097
@SQ SN:12 LN:72498081
and the reference is 10 11 12, heres the first line of the reference:

>1 dna:chromosome chromosome:CanFam3.1:1:1:122678785:1 REF
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

When I used these files it didn't work

**Comment by davidbenjamin** [comment]
Most of our integration tests use the non-UCSC convention.  I would be shocked if that were the issue.  If anyone reading this has the issue, feel free to re-open or post on the GATK forum.
