### ISSUE TITLE
Debug state is not properly passed to the EventMap in HaplotypeCaller

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#4943]
~The AssemblyResultSet in AssemblyBasedCallerUtils.assembleReads is sup posed to output some stats about the active region (debugDump), but it never appears in the log.~

Also debug state is not properly passed to the EventMap.

**Comment by ldgauthier** [comment]
Ohhh, I need to lower the logger output level from the command line.  I thought I remembered that there were two args for effective HC debugging and that's the second one.

But the EventMap thing is still true.

**Comment by davidbenjamin** [comment]
Closed by #5455.
