### ISSUE TITLE
Cromwell v33 released.  Supports intelligent file localization, so we should merge forked WDLs

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#4948]
### Tool(s) or class(es) involved
M2, at least

### Description
With Cromwell v33, we should be able to merge the mutect2.wdl and mutect_nio.wdl into one WDL.  There will need to be WDL modifications, for sure.

https://github.com/broadinstitute/cromwell/releases

**Comment by davidbenjamin** [comment]
@LeeTL1220 When will Firecloud support Cromwell v33?  We can't release an unforked M2 WDL until then.

**Comment by davidbenjamin** [comment]
Closed by #6108.
