### ISSUE TITLE
Annotate strand artifact before throwing out overlapping reads

### ISSUE THREAD

**Issue by takutosato** [broadinstitute/gatk#4959]
Mutect throws away one read in an overlapping read pair before annotating variants. As @madduran found out, when we have only a few alt reads the strand counts may appear more biased than it really is. In other words strand-related annotations (StrandBySample and StrandArtifact) should be read-based, not fragment-based.

The solution is to annotate these two annotations before Mutect throws away overlapping reads

**Comment by davidbenjamin** [comment]
Assigning myself as a reminder for the upcoming PR in which overlapping mates are not discarded.
