### ISSUE TITLE
Fix failing gatk-nightly builds

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#4965]
Apparently there have been some issues lately with the gatk-nighly builds failing to upload. This appears to have been the case for the past month as the dockerhub repo doesn't show any images newer than 3 months ago.

**Comment by jamesemery** [comment]
So update: the builds have been broken as a result of the new mechanism for constructing smaller docker images. Namely no longer is the gatk clone and dockerfile sufficient to construct the docker image which has resulted in dockerhubs automated builds feature failing to construct the image successfully. Since there are a number of dependencies that our build has (notably things like java) and the vm dockers build runs is out of our control, a better approach would appear to be constructing the image with a cron job and pushing it to dockerhub manually.

**Comment by droazen** [comment]
@jamesemery We've been asked to re-prioritize fixing the nightly builds -- adding to this quarter's goals.
