### ISSUE TITLE
Please upgrade NIO to a version that has prefetching baked-in.

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/gatk#4986]
This will enable other project (read: picard) to also have prefetching, which will unblock https://github.com/broadinstitute/picard/issues/1175.

**Comment by droazen** [comment]
Upgrading directly to the latest `google-cloud-java` is blocked by https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2453, but we could update our fork to include the built-in prefetching.
