### ISSUE TITLE
GATK4 VariantAnnotator does not handle PED file that GATK3 can

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#4987]
Researcher reports that GATK4 VariantAnnotator errors with a PED file that works fine with CalculateGenotypePosteriors. The same VariantAnnotator command and PED file work fine in GATK3.

---
Hi @shlee ,

We have ped files. And it worked fine for CalculateGenotypePosteriors too. But not with VariantAnnotator.

So we downraded to GATK3 with same files on same parameters in order to finish that part - we hope calculations are same.

Thank You!
Sergey

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/50327#Comment_50327

**Comment by sooheelee** [comment]
I see that this tool is actively being ported. Assigning @droazen. On a side note, VariantAnnotator does not show up in the forum tool docs but lists fine with `gatk X --help`. Let me know if this latter is something I can fix.

**Comment by cmnbroad** [comment]
It looks like this is happening because the `GATKAnnotationPluginDescriptor` only propagates pedigree arguments to annotations that derive from the `PedigreeAnnotation` class. In the forum post comments, the one report that includes an input command line specifies the `PossibleDeNovo` annotation, which isn't part of the`PedigreeAnnotation` hierarchy.  So it doesn't get properly populated. I assume the other case is similar. This fix is change the hierarchy (or better yet, find a more type-safe way to identify pedigree annotations).

Also, the tool doesn't appear in the docs because it doesn't have a `@DocumentedFeature` annotation.

**Comment by jamesemery** [comment]
Furthermore, upon looking it appears that PossibleDeNovo isn't actually currently being used anywhere, not even in `CalculateGenotypePosteriors` so perhaps we should remove the class instead, or mark it as deprecated?

**Comment by ldgauthier** [comment]
In the (proposed) pipeline it was run separately with VariantAnnotator.  It could probably be rolled into CalculateGenotypePosteriors. Admittedly even four years later we still don't use it in production.

**Comment by zhangjianruwang** [comment]
so how to produce denovo mutations with GATK4.0  ?

**Comment by sooheelee** [comment]
We have another researcher asking about this feature at <https://gatkforums.broadinstitute.org/gatk/discussion/14299/gatk4-variantannotator-de-novo-ped-workshop-1809#latest>. If annotating de novos will not be a feature, then please can we remove the option and/or update the error message to be more informative? Would appreciate it. Thank you.

**Comment by Arhodes-Broad** [comment]
Hello, we have another researcher asking about this error here: https://gatkforums.broadinstitute.org/gatk/discussion/comment/54993#Comment_54993

**Comment by sooheelee** [comment]
@jamesemery requests test files that show what a possible de novo looks like and I have agreed to prep some data towards this.

Here is the data bundle that includes a GATK3.7 result.
[VariantAnnotator_PossibleDeNovo_sooheelee.zip](https://github.com/broadinstitute/gatk/files/2852379/VariantAnnotator_PossibleDeNovo_sooheelee.zip)

The command I used with GATK3.7:
```
java -jar $GATK -T VariantAnnotator \
-R ref/ref.fasta \
-V precomputed/trioGGVCF.vcf.gz \
-o trioVA.denovo.vcf.gz \
-A PossibleDeNovo 
-ped trio.ped
```

Here are the three records that then show either `loConfDeNovo` or `hiConfDeNovo` annotations as a result:
![screenshot 2019-02-11 13 10 16](https://user-images.githubusercontent.com/11543866/52583757-64f17680-2dfe-11e9-8c8e-11a9751f881c.png)

For all of the records that change, see https://gatkforums.broadinstitute.org/gatk/discussion/comment/56268#Comment_56268.

**Comment by albertRichael** [comment]
@sooheelee  Thanks for your reply, I thought all sites would have hiConfDenovo/loConfDenovo annotation, if I used grep command, there would be no question(what a fool mistake -_-).

**Comment by sooheelee** [comment]
No problem @albertRichael. Glad you sorted that out.

**Comment by jamesemery** [comment]
#5663 Hooks up the `PossibleDeNovo` to the annotation engine and should hopefully resolve this issue when it gets in by the next release.
