### ISSUE TITLE
Move BaseTest static initialization to BeforeSuite method

### ISSUE THREAD

**Issue by magicDGS** [broadinstitute/gatk#5013]
Could it be possible to set all these properties and configurations in a method annotated with `@BeforeSuite`?

https://github.com/broadinstitute/gatk/blob/3c960c9d7174785a82d272fe9cd33076ae7ed271/src/main/java/org/broadinstitute/hellbender/utils/test/BaseTest.java#L35-L42

Downstream toolkits using the testing framework provided by GATK (and thus, extending `BaseTest`) might benefit for that change - currently they are kept unset if not explicitly defined by the implementation.

If it is not possible because it is not correctly handled by TestNG, feel free to close the issue.

**Comment by magicDGS** [comment]
This is also related with #5012 (where the locale should be set)

**Comment by magicDGS** [comment]
Although I was again wrong by static-blocks and inheritance (see https://github.com/broadinstitute/gatk/issues/3483), I think that in the case of the tests is better to make overridable this config - thus, I keep it open.

**Comment by davidbenjamin** [comment]
@lbergelson Is it worth keeping this open?

**Comment by lbergelson** [comment]
Fine to close this, I think the only person who cared is unlikely to run into it again.
