### ISSUE TITLE
Memory usage spike GenotypeGVCF 4.0.4.0 vs 4.0.6.0

### ISSUE THREAD

**Issue by EvanTheB** [broadinstitute/gatk#5024]
I updated from 4.0.4.0 to 4.0.6.0 and noticed either a memory bug or spike in GenotypeGVCF. 

Based on https://github.com/EvanTheB/gatk4-germline-snps-indels/blob/master/joint-discovery-gatk4.simple.wdl:

```
"/share/ClusterShare/software/contrib/evaben/gatk/prebuilt/4.0.4.0/bin/gatk" --java-options "-Xmx8g -Xms8g" \
GenomicsDBImport \
--genomicsdb-workspace-path "$genomicsdb" \
--batch-size "50" \
-L "chr18:1-80373285" \
--sample-name-map "/share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/e64f393e-2ac6-43e6-9b20-cbfa905e7c33/call-GenotypeGVCFs/shard-17/inputs/-321562876/sample_map" \
--reader-threads 5 \
-ip 500

tmp_vcf="$TMPDIR"/tmp.vcf.gz

"/share/ClusterShare/software/contrib/evaben/gatk/prebuilt/4.0.4.0/bin/gatk" --java-options "-Xmx8g -Xms8g" \
 GenotypeGVCFs \
 -R "/share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/e64f393e-2ac6-43e6-9b20-cbfa905e7c33/call-GenotypeGVCFs/shard-17/inputs/1017648146/Homo_sapiens_assembly38.fasta" \
 -O "$tmp_vcf" \
 -D "/share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/e64f393e-2ac6-43e6-9b20-cbfa905e7c33/call-GenotypeGVCFs/shard-17/inputs/1017648146/Homo_sapiens_assembly38.dbsnp138.vcf" \
 -G StandardAnnotation \
 --only-output-calls-starting-in-intervals \
 --use-new-qual-calculator \
 -V gendb://"$genomicsdb" \
 -L "chr18:1-80373285"

"/share/ClusterShare/software/contrib/evaben/gatk/prebuilt/4.0.4.0/bin/gatk" --java-options "-Xmx8g -Xms8g" \
  VariantFiltration \
  --filter-expression "ExcessHet > 54.69" \
  --filter-name ExcessHet \
  -O "output.vcf.gz" \
  -V "$tmp_vcf"
```

And a SGE hard memory limit of 40G (GenotypeGVCFs has -Xmx8g).
On gatk 4.0.4.0 I see peak memory usage of 15.7G, while with gatk 4.0.6.0 I get:

```
...
19:06:23.757 INFO  GenotypeGVCFs - Initializing engine
19:06:24.785 INFO  FeatureManager - Using codec VCFCodec to read file file:///share/ScratchGeneral/evaben/cromwell/cromwell-executions/JointGenotyping/e9bf8c5e-3e70-476a-99a2-833f9d38cb2f/call-GenotypeGVCFs/shard-0/inputs/1017648146/Homo_sapiens_assembly38.dbsnp138.vcf
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
```

It seems unlikely to be just a performance regression, maybe something is wrong with my commandline/inputs that only the new version is revealing. This may be in the genomicsdb part of the codebase, as that is the input file I am reading. 

[stderr of failure (4.0.6.0) ](https://github.com/broadinstitute/gatk/files/2204252/gengvcferr.txt)
[stderr of success (4.0.4.0) ](https://github.com/broadinstitute/gatk/files/2204253/gengvcfgood.txt)
[script of failure](https://github.com/broadinstitute/gatk/files/2204254/gengvcfscript.txt)

**Comment by EvanTheB** [comment]
@cmnbroad apologies, I intended to upload the log from the same shard, the stderr is re-uploaded here. All shards of 4.0.6.0 failed, while all shards of 4.0.4.0 succeeded. 

[gengvcferr.txt](https://github.com/broadinstitute/gatk/files/2207790/gengvcferr.txt)

**Comment by cmnbroad** [comment]
Thanks @EvanTheB. @kgururaj can you take a look at once ? thx.

**Comment by kgururaj** [comment]
To be honest, I don't have a clear idea of why this is happening. I tried running a query with 1000 samples using the same GenomicsDB jar that GATK uses and the memory consumption stayed below 1 GB.

Some suggestions/questions:
* If you were importing/querying multiple intervals at once, I would expect #4994 to be relevant. But your script shows a single interval being imported/queried.
* Would it be possible to run the SelectVariants tool using the GenomicsDB workspace as input and see how much memory is being consumed? The Select tool simply extracts the data from GenomicsDB and prints out a VCF.

**Comment by EvanTheB** [comment]
From the stack trace I had assumed the error was likely related to loading the dbsnp vcf. From: gs://broad-references/hg38/v0/

I have attached a 1Mbase subset of my gvcf and a script that reliably reproduces the error for me.

[script.txt](https://github.com/broadinstitute/gatk/files/2217511/script.txt)
[NA12878.hg38.g.vcf.gz](https://github.com/broadinstitute/gatk/files/2217512/NA12878.hg38.g.vcf.gz)

**Comment by kgururaj** [comment]
Assuming the single VCF attached is being imported.

Memory consumed by:
* GenomicsDBImport: 1.2 GB
* SelectVariants: 1.4 GB
* GenotypeGVCFs: 2 GB

**Comment by EvanTheB** [comment]
@kgururaj are you using the script I provided? Otherwise it must be something site specific here.

**Comment by kgururaj** [comment]
Yes, using the same script

**Comment by EvanTheB** [comment]
I tried running gatk version 4.0.7.0 with the environment variable: 'TILEDB_DISABLE_FILE_LOCKING=YES' to see if that would fix the issue, but I still get the same error. I am not sure that the patch that enable that was actually in the 4.0.7.0 release.

**Comment by ldgauthier** [comment]
This issue has gone stale.  @EvanTheB you can reopen if this is still a problem.
