### ISSUE TITLE
Equivalent to SampleUtils.getSamplesFromCommandLineInput()

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#5039]
I'm working to migrate GATK3's VariantEval to GATK4.  This includes this code ~line 319:

        // Load the sample list, using an intermediate tree set to sort the samples
        final Set<String> allSampleNames = SampleUtils.getSamplesFromCommandLineInput(vcfSamples);
        sampleNamesForEvaluation.addAll(new TreeSet<String>(SampleUtils.getSamplesFromCommandLineInput(vcfSamples, SAMPLE_EXPRESSIONS)));
        isSubsettingSamples = ! sampleNamesForEvaluation.containsAll(allSampleNames);

Is there a GATK4 equivalent to SampleUtils.getSamplesFromCommandLineInput()?  The basic features this has are: 1) Given a list of string or filepaths, it parses everything into a set, 2) Filters the list based on SAMPLE_EXPRESSIONS (which is less hard to do).  Thanks.

**Comment by cmnbroad** [comment]
@bbimber The GATK4 command line parser will [automatically](https://github.com/broadinstitute/barclay/blob/94172297c32447a0f2bf5c057fa7b70177144228/src/main/java/org/broadinstitute/barclay/argparser/CommandLineArgumentParser.java#L725) do the file expansion part of this for any argument with any value that ends in ".list" or ".args". So by the time the tool sees the values, they will already have been expanded in place. Then you can post-process as as required. See SelectVariants in GATK4, which I think does something similar. I'll close this ticket, feel free to reopen if I'm misunderstanding.
