### ISSUE TITLE
Add improvements to gCNV WDL, including scattering case samples in chunks.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#5054]
@asmirnov239 and @mwalker174 should include any other useful additions they've made to their versions of the WDL.

**Comment by mwalker174** [comment]
I think we should do this in 2 PRs. First @asmirnov239 can first add his modification to run multiple samples in case mode. I can do a subsequent PR for "double-chunking" intervals to avoid PAPI/quota errors for high-resolution WGS.

**Comment by asmirnov239** [comment]
Yes I agree, I will also work on  #4397 in the same PR

**Comment by samuelklee** [comment]
Sorry, guess this was a dupe of #4397.
