### ISSUE TITLE
LeftAlignIndels example is invalid

### ISSUE THREAD

**Issue by anowlcalledjosh** [broadinstitute/gatk#5072]
### Tool(s) or class(es) involved

LeftAlignIndels

### Description 

The example for LeftAlignIndels uses a parameter `-O` which doesn't exist for the tool - the parameter listed in the documentation is `--OUTPUT`. Either the example should be updated to use `--OUTPUT`, or the tool should be changed to accept `-O`.

**Comment by cmnbroad** [comment]
Yes, for consistency the `@Argument` annotation for OUTPUT should probably use the standard fullName and shortName constants (StandardArgumentDefinitions.OUTPUT_LONG_NAME) used by the other tools (though it will break compatibility).
