### ISSUE TITLE
Improve handling of clipped read "stubs" in HC

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#5079]
Effectively implement #5057 for HaplotypeCaller.  Shortie reads with few bases inside the active region can have very biased likelihoods as David explains in #5060

This is probably less significant in HC for diploids than in M2 for somatic or MT.

**Comment by davidbenjamin** [comment]
I can do this but first, since it seems like a nice way to learn about the GATK engine, I'll open it up to @TedBrookings @MartonKN @takutosato @meganshand @sjfleming @madduran @dalessioluca.

**Comment by MartonKN** [comment]
Addressed in issue #5471

**Comment by davidbenjamin** [comment]
> Addressed in issue #5471

@MartonKN Note that if you write `closes #5079` in the PR you don't need to state that here because github automatically generates the cross-reference, as it did above for my comment.

**Comment by MartonKN** [comment]
Ok, thank you, David.
