### ISSUE TITLE
Known sites optimization on Spark

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#5103]
Loading the known sites file (e.g. dbsnp_138.hg18.vcf) takes around 6 minutes in the Spark pipeline using `KnownSitesCache`. This ticket is to see if we can improve this.

**Comment by tomwhite** [comment]
`KnownSitesCache` loads a VCF file and turns it into an in-memory `IntervalsSkipList`, which is shared by all tasks in the same VM. The Spark job stage that uses `KnownSitesCache` in BQSR takes 6 minutes to load the file into memory, but then the stage takes another 4 minutes to complete (total 10 minutes, stage name `treeAggregate at BaseRecalibratorSparkFn.java:39`).

Another approach is to uses Spark's `--files` option to share the VCF file with all executors, then use the file as a `FeatureDataSource` directly. I did this using a `.vcf.gz` file and the accompanying `.vcf.gz.tbi`. See the code in this branch: https://github.com/broadinstitute/gatk/tree/tw_known_sites_perf_files

This however was slower, the same stage took 39 minutes to complete, compared to 10. This is probably because reading from a file is much slower than using an in-memory lookup to find variants overlapping each read.

**Comment by tomwhite** [comment]
I wondered how much of the time was due to parsing the VCF file. To test this, I used Kryo to serialize the `IntervalsSkipList` to a binary blob, then tried loading the binary blob directly. This reduced the load time from around 6 minutes to 4.7 minutes - so some speed improvement, but not a lot. See https://github.com/broadinstitute/gatk/tree/tw_known_sites_perf_kryo

**Comment by tomwhite** [comment]
cc @lbergelson @droazen

**Comment by cmnbroad** [comment]
@tomwhite In your `--files` branch, you might try enabling feature caching on the `FeatureDataSource` (assuming your sequential queries are forward-only, increasing). Without that it will execute a separate index query for each `query(interval)` to find the overlaps. If you pass a non-zero `queryLookaheadBases` value to the FeatureDataSource constructor, it will use lookahead and the feature cache to satisfy queries - I would expect it to speed it up a lot.

**Comment by tomwhite** [comment]
@cmnbroad good idea! Reads going into BQSR are not coordinate-sorted since MarkDuplicates sorts by queryname, so it wouldn't improve anything as things stand (and would probably make things worse). However, HaplotypeCallerSpark sorts reads by coordinate - so we could move that sort to be before BQSR to benefit from the caching you suggested.

**Comment by tomwhite** [comment]
I can report that this worked well - the BQSR stage came down in time from 10 min to 4.7 min - a very significant improvement. I'm going to look at doing something similar with the reference.

**Comment by droazen** [comment]
@tomwhite Did https://github.com/broadinstitute/gatk/pull/5127 satisfy this ticket, or is there more to do?

**Comment by tomwhite** [comment]
Fixed in #5127
