### ISSUE TITLE
Investigate why some files have incorrect counts in CountReadsSpark

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#5133]
In doing MarkDuplicatesTesting I have encountered a number of large files output by MarkDuplicatesSpark that appear to have gained reads (890615361 total -> 890615487 total) when counting the reads using CountReadsSpark. Unfortunately it appears that CountReadsSpark is miscounting the reads in these files as its count disagrees with both the tool itself and normal CountReads. This doesn't apparently happen for all files, only some. Perhaps this can be isolated to a specific version of Hadoop-BAM?

**Comment by jamesemery** [comment]
To clarify, it fails not just for CountReadsSpark, for other GATKSparkTools that call `readsRDD.count()` also seem to have this problem.

**Comment by droazen** [comment]
@tomwhite We'd like your help in determining whether this is a problem in Hadoop-BAM (and if so, whether it's fixed in Disq).

**Comment by jamesemery** [comment]
Update: I have looked as far back as gatk4.0 and found the same issue, so it likely isn't a recent Hadoop-BAM issue (like the new split guessing).

**Comment by tomwhite** [comment]
@jamesemery can you share a file that you're seeing the issue with please?

**Comment by jamesemery** [comment]
Based on testing performed on google cloud, this problem seems to have resolved itself after we updated to the newest googleCloudJava package in this #5135. Something fixed by switching off of our ancient fork must have been responsible for the file being misread by spark. I suggest we close this issue as it appears to be resolved unless @droazen you want to do a post-mortem to figure out what the relevant change must have been?

**Comment by lbergelson** [comment]
I really want to know what caused this... it seems super dangerous to me.

**Comment by droazen** [comment]
Agreed -- let's do a bit more digging before closing this. If we don't understand the underlying cause, we'll be in constant danger of re-introducing this bug. At the very least, I'd like @tomwhite to be able to reproduce this and have a look.

**Comment by jamesemery** [comment]
@tomwhite has discovered the source of this bug and opened a PR in disq: https://github.com/disq-bio/disq/pull/34. It looks like it was related to gvcf block boundaries being multiples of the split guessing default.
