### ISSUE TITLE
Change "##Mutect Version=x.y" to "##MutectVersion=x.y"

### ISSUE THREAD

**Issue by rasmushenningsson** [broadinstitute/gatk#5183]
### Affected tool(s) or class(es)
Mutect2

### Affected version(s)
- [x] Latest public release version [2.1]
- [x] Latest master branch as of [2018-09-13]

### Description 
The VCF header line
"##Mutect Version=x.y"
causes problems for some VCF readers. Each header line is required to be a key-value pair and a space character is not expected in the key. (The VCF specification is not clear on this matter, but I've never encountered a space character in a VCF header key before.)
Making VCF files that are easily readable by downstream tools should be in the interest of Mutect2.

#### Steps to reproduce
Create a VCF file using Mutect2 and look at the header.

#### Expected behavior
output
"##MutectVersion=2.1"

#### Actual behavior
output
"##Mutect Version=2.1"

**Comment by davidbenjamin** [comment]
Thanks for spotting this, @rasmushenningsson!
