### ISSUE TITLE
Funcotator should create a cDNA annotation for Intronic Splice Sites

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#5187]
### Tool(s) or class(es) involved
_Funcotator,GencodeFuncotationFactory_

### Description
When annotating a variant and the `VariantClassification` is `SPLICE_SITE, INTRON`, Funcotator should include a non-empty `cDNA` annotation.

This `cDNA` annotation should include the number of bases that the start of the variant is away from the exon, as well as the reference and alternate alleles of the variant in question.

Concretely:
    `c.e[EXON NUMBER][+|-][BASES FROM EXON][REF ALLELE]>[ALT ALLELE]`

For example:
    c.e2-1A>G
    Where:
        2 = the number of the closest exon (1-based)
        -1 = number of bases away from the exon (1 before)
        A = Reference allele
        G = Alternate allele

This feature is requested for the clinical pipeline.

**Comment by jonn-smith** [comment]
In `GencodeFuncotationFactory::createIntronFuncotation`:

1) Get closest Exon
2) calculate offset to exon start (`exonOffset = closestExon.getStart() - variant.getStart()`)
3) Create cDNA string (`final String cDnaString = "c." + exonOffset + strandCorrectedRefAllele + ">" + strandCorrectedAltAllele`)

**Comment by jonn-smith** [comment]
@LeeTL1220 what should we do in the case that a variant occurs in a transcript that has no exons?

**Comment by LeeTL1220** [comment]
@jonn-smith Does that happen in reality?  That sounds like it would be a bug in the transcript data.  If you detect that the transcript has no exons "NA"?

**Comment by jonn-smith** [comment]
@LeeTL1220 I don't think it should ever happen, but I want to be prepared.  The code has a path for that case so I want to make sure it's accounted for.

`"NA"` is fine.
