### ISSUE TITLE
Picard tools run through GATK interpret ":" character as a tag delimiter

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#5189]
```
Using GATK 4.0.2.1

gatk FastqToSam --FASTQ=test_R1.fq --FASTQ2=test_R2.fq --RUN_DATE=2011-04-30T01:00:00+0100 --OUTPUT=test.bam --SM=test
Gives the error No value found for tagged argument: RUN_DATE=2011-04-30T01:00:00+0100

Using Picard 2.18.1-SNAPSHOT

java -jar XXXX/build/libs/picard.jar FastqToSam FASTQ=test_R1.fq FASTQ2=test_R2.fq RUN_DATE=2011-04-30T01:00:00+0100 OUTPUT=test.bam SM=test
Works without issues
```

See https://gatkforums.broadinstitute.org/gatk/discussion/comment/51988#Comment_51988

**Comment by droazen** [comment]
@cmnbroad Can you think of an easy fix for this?

**Comment by chandrans** [comment]
Thanks David and Chris.

**Comment by cmnbroad** [comment]
It looks like they're using a strange hybrid of Picard and Barclay syntax. If they just use pure Barclay syntax  with no "=" (`--RUN_DATE 2011-04-30T01:00:00+0100`) when running the Picard tool from gatk, the error message should go away.

The only part I don't understand is that they say the hybrid syntax works if they leave out `RUN_DATE`. I wouldn't expect that - I'll have to look into it.

**Comment by cmnbroad** [comment]
Closing this since it works using the correct syntax. Feel free to reopen if I'm missing something.
