### ISSUE TITLE
Straightforward port of VariantRecalibrator

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#52]

**Comment by akiezun** [comment]
as per an in-person disucssion, the integration tests will for now only work at the Broad system. Once we move to https://help.github.com/articles/versioning-large-files/ (or similar) these will be enabled again

**Comment by akiezun** [comment]
not going to happen in this iteration. depends on https://github.com/broadinstitute/hellbender/pull/345 and  https://github.com/broadinstitute/hellbender/pull/387

**Comment by akiezun** [comment]
and depends on https://github.com/broadinstitute/hellbender/issues/388

**Comment by droazen** [comment]
alpha-2

**Comment by droazen** [comment]
We should do the most straightforward port possible, since this tool will likely be eventually replaced.

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/2094.
