### ISSUE TITLE
gCNV WGS cohort germline WDL run outputs vcf files with names that do not correspond to the actual sample inside the file.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#5217]
I used the very last version of the WDL using the last master commit for the docker and the name of the output files seem to be a random permutation of the actual sample names. The name inside the file (i.e. the one listed in the #CHROM line) seems to be correct.

A previous run using a earlier version of the WDL (probably the one just before the last update) and the latest official gatk docker didn't have this issue.
.

**Comment by samuelklee** [comment]
Thanks for catching this, @vruano.  @asmirnov239 and I will take a look.

**Comment by samuelklee** [comment]
@vruano could you point us to the run results, either here or on Slack?

**Comment by samuelklee** [comment]
@asmirnov239 I just noticed you changed the call output in the GermlineCNVCaller tasks from a single tar containing all samples to an array of tars (one for each sample): `Array[File] gcnv_call_tars = glob("*-gcnv-calls.tar.gz")`.  Could this be the cause?  Also, wouldn't this be an issue in case mode, as well?

**Comment by vruano** [comment]
The FireCloud Job is here https://portal.firecloud.org/#workspaces/broad-firecloud-dsde/dsde-methods-sv-dev/monitor/ecdb3b72-7b4b-4612-9c87-1c0124f62708

**Comment by vruano** [comment]
The folder containing all the outputs (scripts and staged inputs) in the cloud is in https://console.cloud.google.com/storage/browser/fc-6da0ee01-0ec0-4606-b918-216fe3f7f098/ecdb3b72-7b4b-4612-9c87-1c0124f62708?pli=1

You should be able to browse down to each tasks sub-folder.

**Comment by samuelklee** [comment]
Thanks, @vruano, but I think you'll have to give me access to the FC workspace and bucket.

I've opened a branch sl_revert_glob that I think will fix the issue.  I'll test it out on FC and let you know how it goes.

**Comment by vruano** [comment]
I see what I can do about the perm issue, but is probably not up to me.

**Comment by vruano** [comment]
@cwhelan could you give andrei and sam access to the FC dsde-methods-sv-dev workspace  can investigate the bug. I and Steve had tried without success.

**Comment by samuelklee** [comment]
Thanks, we have access now.  I'm pretty sure that sl_revert_glob will fix the error.  I've rebased my dev branch sl_filter (which includes the filtering steps Jack mentioned in the BSV meeting today) onto sl_revert and am testing cohort mode on FC now.  I'll try to test scattered-case mode as well later today if that succeeds.

As @asmirnov239 points out, this revert leaves #4397 unresolved, so we should go back and clean up at some point.  However, our priority now is to get a stable v1 of the SFARI evaluation on FC.
