### ISSUE TITLE
Disable WellformedReadFilter in CNV WDLs.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#5233]
Profiling using JBuilder remotely on gsa5 (with a large load from other programs) seem to show that close to or over 50% of the CPU effort is dedicated to filter "bad" reads.

<img width="1006" alt="screen shot 2018-09-27 at 2 37 59 pm" src="https://user-images.githubusercontent.com/791104/46167159-09fe1f00-c263-11e8-8ea0-02621146659b.png">

To reproduce you may run (or better make your copy and run on a different profiling port and folder):
```
cd /dsde/working/valentin/crc-profiling
sh run.sh
```
```
#run.sh contents:
java  -agentpath:./bin/linux-x64/libjprofilerti.so=port=5006,nowait  -jar ./gatk-local.jar \ 
    CollectReadCounts \ 
            -I /dsde/working/CHM/33remap/msb2.m38.bam \
            -R /seq/references/Homo_sapiens_assembly38/v0/Homo_sapiens_assembly38.fasta \
            -O /tmp/test.tsv -L hg38.interval_list -imr OVERLAPPING_ONLY
```

The sample was chosen kinda at random , is a CHM pseudo diploid sample but you could use an alternative. Please change profiling port and output file.

On the profiling machine (presumably your laptop or desktop) you need to install JProfiler (Broad owns a license for that).

**Comment by vruano** [comment]
The problem seems to be that some of the "deep" filters inherited from ReadWalker require to look into the read-base/qualities (just to compare their lenghts) which seems to be quite costly to decode and some of the read-attributes when this particular tool does not need to look into those fields.  

It seems to me that we could override these check with a more lightweight alternative. 

<img width="1009" alt="screen shot 2018-09-27 at 3 03 36 pm" src="https://user-images.githubusercontent.com/791104/46168553-d32a0800-c266-11e8-96fd-d60d7c0380d5.png">

**Comment by samuelklee** [comment]
Thanks for looking into this, @vruano.  We've not optimized CollectReadCounts for runtime or experimented with how the filters might affect performance (the latter would be easier with the FC-based evaluation in place).  Can you first try to use `disable-read-filter` on the offending filters to see if that affects runtime or the resulting counts?

**Comment by vruano** [comment]
From the output:

```
16:34:01.251 INFO  CollectReadCounts - 50188374 read(s) filtered by: ((((WellformedReadFilter AND MappedReadFilter) AND NonZeroReferenceLengthAlignmentReadFilter) AND NotDuplicateReadFilter) AND MappingQualityReadFilter)
  6207655 read(s) filtered by: (((WellformedReadFilter AND MappedReadFilter) AND NonZeroReferenceLengthAlignmentReadFilter) AND NotDuplicateReadFilter)
      6207655 read(s) filtered by: ((WellformedReadFilter AND MappedReadFilter) AND NonZeroReferenceLengthAlignmentReadFilter)
          6207655 read(s) filtered by: (WellformedReadFilter AND MappedReadFilter)
              6207655 read(s) filtered by: MappedReadFilter
  43980719 read(s) filtered by: MappingQualityReadFilter
```

From this it seems that ```WellformedReadFilter``` never filters a read by itself and that is the one that eventually results in the sequence decoding.

**Comment by vruano** [comment]
A single sample run was 32 vs 52 minutes without and with the WellformedReadFilter.  About the output, I made the mistake of generating hdf5 and they are not easy to compare. but at least they have the same size and the number of filtered reads is the same so there is nothing to make me think that these should be any difference.

**Comment by samuelklee** [comment]
@vruano will you issue a PR disabling this filter in the tool or the WDL?  Probably the former is fine.

**Comment by samuelklee** [comment]
We decided in #5715 to disable this at the WDL level.

**Comment by vruano** [comment]
A solution was merged
