### ISSUE TITLE
Fix cancer_gene_census test data source in the funcotator test datasources in large

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#5243]
### Affected tool(s) or class(es)
_Funcotator_

### Affected version(s)
- [X] Latest master branch as of [20181001]

### Description 
There appears to be an extra folder in the funcotator test datasources in `large`:

`large/funcotator/funcotator_dataSources/cancer_gene_census/hg19/hg38`
`large/funcotator/funcotator_dataSources/cancer_gene_census/hg38/hg38`

This should be removed.

**Comment by lbergelson** [comment]
This was my fault, sorry about that.

**Comment by jonn-smith** [comment]
No worries.
