### ISSUE TITLE
Hellbender should export unit/integration testing utils as a maven artifact. 

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#525]
So that Hellbender-protected does not need to re-implemented BaseTest and other similar components.

**Comment by lbergelson** [comment]
We can do this buy moving code from test to src.  @vruano Any specific classes we need?  Looks like `BaseTest` and `CommandLineProgramTest`  Anything else?

**Comment by vruano** [comment]
Even if trivial that would be a contaminant for the production jar, I think is should be separated as a matter of principle, but won't oppose if others think that that is the way to go on pragmatical grounds.

**Comment by lbergelson** [comment]
I think it's reasonable to include necessary tests classes, it's intended that people can use hellbender as a base for writing additional tools, so we should provide whatever is necessary to test those tools.  

If it was a very large set of classes it might be worth putting them in a separate artifact, but I think that for the few classes we have it's fine to put them in the standard jar.

**Comment by droazen** [comment]
Agree with Louis -- test infrastructure can go in the standard jar, as long as tests themselves remain separate.

**Comment by lbergelson** [comment]
@vruano Should `ExomeToolsTestUtils` be exposed?  What about `ReadClipperTestUtils`?

**Comment by vruano** [comment]
Don't know about the second. I think that we may want to move Exome* stuff to hellbender protected if it is not to late as the reason of its existence is initially ReCapSeg reimplementation; but no one told me back then.

**Comment by vruano** [comment]
back to ```ReadClipperTestUtils``` I think any utility for testing should be in.

**Comment by vruano** [comment]
Non java test resources are not included in the package:

E.g. src/test/resources/hg19mini.fasta.fai.

**Comment by lbergelson** [comment]
What files do you want included @vruano?  Anything mentioned in basetest makes sense to me.  Are there other generic test resources that are needed?

**Comment by vruano** [comment]
ExomeToolsTestUtils depends on src/test/resources/org/broad.../exome/test_reference.fasta for it workings...

Yet as is mention in another issue, will move ExomeReadCounts and other stuff to protected so I think is fine to disregard this one.

**Comment by vruano** [comment]
As discussed on Hipchat, ExomeReadCounts resources need to be included too.

**Comment by akiezun** [comment]
@lbergelson are you helping here? I think it should be assigned to you no?

**Comment by lbergelson** [comment]
Yes, that should be mine.  Not sure why it's on david.

**Comment by droazen** [comment]
@lbergelson This one is done, isn't it?

**Comment by lbergelson** [comment]
We never baked the test files into the jar, but it doesn't seem very important or necessarily a good idea.  I'd call it closed.

**Comment by droazen** [comment]
Closing!
