### ISSUE TITLE
Add ability to specify AS-annotation combine operations

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#5250]
This should be possible in the FeatureDataSource using code similar to https://github.com/Intel-HLS/GenomicsDB/blob/master/src/main/java/com/intel/genomicsdb/importer/extensions/VidMapExtensions.java#L69

We don't have a use case for this right now, so I'm calling it low priority.  I started a draft at ldg_addAScombineOp but it needs tests.

**Comment by droazen** [comment]
@ldgauthier Is this one done?

**Comment by ldgauthier** [comment]
No, but it's not something I need.

**Comment by ldgauthier** [comment]
Closed via #4947
