### ISSUE TITLE
Make HaplotypeCallerSpark output match HaplotypeCaller output as closely as possible

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#5265]

**Comment by SaintBacchus** [comment]
@droazen is there any plan to do this work?

**Comment by droazen** [comment]
@SaintBacchus Yes, this work is in progress. The first step was to add a "strict" mode to `HaplotypeCallerSpark` that causes it to match the output of the regular `HaplotypeCaller` very closely (this was done in https://github.com/broadinstitute/gatk/pull/5416). The next step will be to improve the performance of the Spark version.

**Comment by droazen** [comment]
Closing -- we now have a `--strict` mode that matches the regular `HaplotypeCaller` at the expense of speed. Next step is to work on performance (https://github.com/broadinstitute/gatk/issues/5263)
