### ISSUE TITLE
Migrate to genomicsdb.org fork of GenomicsDB

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#5277]

**Comment by nalinigans** [comment]
Have started testing snapshot releases from genomicsdb.org in nalini_new_genomicsdb_jar branch. Will wait for @kgururaj to finish his work and release a final jar from com.intel before finally moving gatk to the new fork.

**Comment by nalinigans** [comment]
Waiting on https://github.com/broadinstitute/gatk/pull/5397 to be merged in.

**Comment by droazen** [comment]
Done in https://github.com/broadinstitute/gatk/pull/5587
