### ISSUE TITLE
Exception in onShutdown mask the actual cause of problems in onStartup.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#528]
The current runTool method implementation masks exception occurring in either onStartup or doWork if there is a exception in onShutdown.

It is more important to report the exception in onStartup or doWork that any occurring in onShutdown. 

Apart from this, developers are supposed to make onShutdown robust to failure in onStartup?

**Comment by lbergelson** [comment]
Where is this happening?  `onShutdown` and `onStartup` should only be implemented by someone writing a new traversal type.  `onShutdown` should be robust to failures earlier.

**Comment by vruano** [comment]
I'm working on a non-traversal tool.

**Comment by vruano** [comment]
IMO even with the best of intentions onShutdown could still fail and the runTool should be able to handle that.

**Comment by lbergelson** [comment]
>I'm working on a non-traversal tool.

What's the failure though, we should fix that.  

What result do you want if there's an exception in doWork and then a separate one in onShutdown?  You want to see a stacktrace from both?

**Comment by vruano** [comment]
In this particular case the failure is that I did not made onShutdown robust to failure in onStartup, once I corrected one I could see what the problem was. 

In general though, if there is an exception in onStartup/doWork and another in onShutdown I would rather see the once in onStartup/doWork if it has to be only one. That would be an improvement with respect to what happens now. 

That is good enough for me, but I guess I still have a non-cloud mentality here. Perhaps you see as equally important to report problems onShutdown that came after a onStartup/doWork in a cloud context (those without a previous error are still reported anyway).

**Comment by akiezun** [comment]
note to implementer: look into using `Throwable.getSuppressed()`

```
    /**
     * Returns an array containing all of the exceptions that were
     * suppressed, typically by the {@code try}-with-resources
     * statement, in order to deliver this exception.
     *
     * If no exceptions were suppressed or {@linkplain
     * #Throwable(String, Throwable, boolean, boolean) suppression is
     * disabled}, an empty array is returned.  This method is
     * thread-safe.  Writes to the returned array do not affect future
     * calls to this method.
    */
```

**Comment by akiezun** [comment]
i think @lbergelson is on it

**Comment by lbergelson** [comment]
I'm on it, just haven't gotten to it yet.
