### ISSUE TITLE
Support SAM v1.6 in GATK

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#5282]
Requires https://github.com/samtools/htsjdk/issues/1186

**Comment by lbergelson** [comment]
Support for 0 length arrays in sam: https://github.com/samtools/htsjdk/pull/1194

**Comment by droazen** [comment]
@lbergelson Is this one done?

**Comment by droazen** [comment]
@lbergelson informs me that we do read/write SAM 1.6, but that there are a few known issues that still need to be resolved (eg., with non-ascii characters).

**Comment by droazen** [comment]
Closing, as GATK does now read/write SAM 1.6.
