### ISSUE TITLE
Get gCNV in case mode to run under 30 cents per sample in the dsde-sv-pipe benchmark.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#5288]
The title says it.

We already found out that collect-read-counts can be twice as fast if we dissable the wellformed-read filter. #5233.

In addition each GermlineCNVCaller shard extracts from each case sample the relevant intervals probably without using an index becoming a rather slow operation. On top of that the python script takes .tsv files in so.. it seems to me that we would better served using .tsv from the start (dropping .hdf5 for that role) and perhaps indexing them with tabix? 

It seem that we may be loosing some cents in all the file localization that takes place between collect-read-counts and the germline-cnv-caller tools (which are basically transposing a big matrix thru files). Perhaps it would make more sense to use some kind a (Non-SQL) DB for the task.

**Comment by vruano** [comment]
Also looking into the python log output perhaps the minimum of 10 epochs for training is too hi as the numbers that are spit out seem to indicated that things are quite settle just a bunch of iteration (~4-5 or so).

**Comment by samuelklee** [comment]
@vruano BTW, are you using NIO for coverage collection?  See https://github.com/broadinstitute/gatk/issues/4806 and https://github.com/broadinstitute/gatk/pull/5015.

**Comment by samuelklee** [comment]
@vruano @mwalker174 can this be closed?

**Comment by mwalker174** [comment]
@samuelklee I think we can close this because we hit our target. Let's reassess where we are cost-wise after adding read count streaming. Our next goal will likely be wgs at ~100bp resolution.
