### ISSUE TITLE
Funcotator needs test coverage for "all transcripts" mode

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#5295]
There's currently no test coverage for "all transcripts" mode in Funcotator, as far as I can discover, and the GTF files used for MUC16/PIK3CA tests don't even have multiple transcripts.

**Comment by jonn-smith** [comment]
The regression tests added as part of #4344 fulfill this requirement.

However, they need to be refactored to take advantage of the newly-included full `hg19` and `hg38` reference sequences.
