### ISSUE TITLE
Mitochondria Pipeline Tools

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/gatk#5310]
## Feature request

The mitochondria pipeline should have new annotations and filters in Mutect2 and FilterMutectCalls. This is being addressed in #5193. An accompanying best practices WDL should also be developed and eventually be available in Firecloud.

I'll update here once the PR is merged and has been released.

**Comment by meganshand** [comment]
@SusieX I'll comment here with updates.

**Comment by jullee** [comment]
I'm excited to see the best practices WDL...is there a rough draft?

**Comment by meganshand** [comment]
@jullee I should have a rough draft by next week. I'll provide a link here when I have it working. Thanks for your interest!

**Comment by meganshand** [comment]
The changes to Mutect are included in the 4.0.11.0 release.  A rough draft of the WDL is here: https://portal.firecloud.org/#methods/mt/MitochondrialCalling/8

When this is a complete pipeline (beyond the draft stage) there will be more information on the GATK forum.
