### ISSUE TITLE
Set the PS for phased variants.

### ISSUE THREAD

**Issue by nh13** [broadinstitute/gatk#5314]
@lbergelson @droazen I would grateful if GATK4 could output the standard `PS` tag for phased variants.  GATK4 currently outputs the non-standard `PID` and `PGT` tags.  Tools like `rtg-tools` leverage the `PS` tag, especially for complex, linked variants.  For example a SNP+DEL on one haplotype, where the DEL spans a SNP on the other.  It could be as easy as finding all the places where `HAPLOTYPE_CALLER_PHASING_ID_KEY` and setting the `PS` tag (the value is the position of the variant earliest in the genome)

**Comment by droazen** [comment]
@ldgauthier Your thoughts on this request?

**Comment by ldgauthier** [comment]
This isn't high priority for us right now, but I would be happy to review a PR if you wanted to take a stab at a solution @nh13 .  None of our formal pipelines use the PID or PGT tags (unless Funcotator does something @jonn-smith ?) so a switch to PS wouldn't be a breaking change for us.

**Comment by nh13** [comment]
@ldgauthier thank-you, I'll see how difficult it is.

**Comment by jonn-smith** [comment]
Those tags should be transparent to Funcotator.

**Comment by tfenne** [comment]
Just FYI to @ldgauthier that I think this issue can be closed now that #5318 is merged and released.

**Comment by ldgauthier** [comment]
Closed by #5318
