### ISSUE TITLE
Haplotype Caller Spark and non Spark

### ISSUE THREAD

**Issue by Atahualkpa** [broadinstitute/gatk#5323]
Hi,
in the last months for my Master thesis project I've studied your tool, with this pipeline:

![ngs_pipeline_gatk](https://user-images.githubusercontent.com/10074137/47147968-ae5a0b00-d2cf-11e8-9fd6-15cd23fbcdcf.png)
in spark version, yes, I know is still in beta but I’ve found these problems when I compared the outputs from Haplotypecaller in spark and in not Spark versions. For comparing these results I've used this tool [https://drive.google.com/file/d/1r2WHyiz5WqOIyY_EZ1VZt92wGlL19SE4/view?usp=sharing](url) and I've obtained these plots for sensitivity and specificity( The sensitivity is defined as the number of sites inwhich both sequencing and microarrays detected a deviation from the reference sequencedivided by the number of sites where a variant was detected by using the microarrays)

**Spark**
Sensitivity
![spark_sensitivity_hg19](https://user-images.githubusercontent.com/10074137/47148261-86b77280-d2d0-11e8-8b5a-9ecfef16d889.png)
Specificity
![sparkspecificityhg19](https://user-images.githubusercontent.com/10074137/47148277-933bcb00-d2d0-11e8-97eb-1adceb4e5ee2.png)

**Local non Spark tool with GATK 2.7**
![hg19local](https://user-images.githubusercontent.com/10074137/47148427-fcbbd980-d2d0-11e8-87d8-04ec20c1005d.png)
furthermore I've executed the pipeline until BQSR in Spark version and after, I am focused just on Haplotypecaller because I've used this "backwards" approach and I've discovered that the pipeline is deterministic from the phase Variant Discovery, but don't in the phase of Preprocessing because when I've executed this phase more times, I've obtained results completely, this is the test with one single sample:
![comparisons_pfc32](https://user-images.githubusercontent.com/10074137/47148552-49071980-d2d1-11e8-8b1c-aec468285699.png)
furthermore when I've used the output from BQSR (executed in Spark) for execute of Haplotypecaller in local(not in Spark) and adapting this output for Haplotypecaller, I had to use the tool Samtools for sort the outputs and after this step the outputs are passed from average of 19 gigabytes to 13 gigabytes average for the all samples

I've opened this Issue because I would to help you with my experiments to improvement your tool.
thanks.

**Comment by SaintBacchus** [comment]
Hi, I also meet this issue. 

The  Specificity in `HaplotypeCallerSpark` was a bitter less than local mode in my test.

Do you known which configuration can improve the Specificity in `HaplotypeCallerSpark` ? @Atahualkpa

**Comment by droazen** [comment]
@Atahualkpa Thanks for taking the time to share your results with us! We are indeed aware that `HaplotypeCallerSpark` produces output that is less sensitive and accurate than the output of the regular `HaplotypeCaller` -- this is why we've kept it marked as beta. We plan to work on `HaplotypeCallerSpark` soon to make it match the regular `HaplotypeCaller` more closely. You can track this effort here: https://github.com/broadinstitute/gatk/issues/5265

**Comment by ldgauthier** [comment]
This was effectively done in #5416
