### ISSUE TITLE
GATK v4.0.8.1 GenomicsDBImport Error (VariantStorageManagerException exception); File syncing error

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#5342]
Command:
`java -Djava.io.tmpdir=/work/TMP \   
-Xmx40g -jar ~/bin/gatk-4.0.8.1/gatk-package-4.0.8.1-local.jar \    
GenomicsDBImport \     
-V /work/Analysis/III_3P_RG_DupMark.raw.snps.indels.g.vcf \    
-V /work/Analysis/IV_11N_RG_DupMark.raw.snps.indels.g.vcf \
-V /work/Analysis/IV_8N_RG_DupMark.raw.snps.indels.g.vcf \
-V /work/Analysis/IV_10P_RG_DupMark.raw.snps.indels.g.vcf \
-V /work/Analysis/IV_20P_RG_DupMark.raw.snps.indels.g.vcf \
--genomicsdb-workspace-path /work/Analysis/wang_chr19_re \
--intervals chr19`

**Error Log**

15:00:35.770 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/wang/bin/gatk-4.0.8.1/gatk-package-4.0.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
15:00:35.944 INFO  GenomicsDBImport - ------------------------------------------------------------
15:00:35.944 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.0.8.1
15:00:35.945 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
15:00:35.945 INFO  GenomicsDBImport - Executing as wang@Ubuntu1604 on Linux v3.16.0-43-generic amd64
15:00:35.945 INFO  GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_171-8u171-b11-2~14.04-b11
15:00:35.945 INFO  GenomicsDBImport - Start Date/Time: October 2, 2018 3:00:35 PM JST
15:00:35.945 INFO  GenomicsDBImport - ------------------------------------------------------------
15:00:35.945 INFO  GenomicsDBImport - ------------------------------------------------------------
15:00:35.946 INFO  GenomicsDBImport - HTSJDK Version: 2.16.0
15:00:35.946 INFO  GenomicsDBImport - Picard Version: 2.18.7
15:00:35.946 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2
15:00:35.946 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
15:00:35.946 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
15:00:35.946 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
15:00:35.946 INFO  GenomicsDBImport - Deflater: IntelDeflater
15:00:35.946 INFO  GenomicsDBImport - Inflater: IntelInflater
15:00:35.946 INFO  GenomicsDBImport - GCS max retries/reopens: 20
15:00:35.946 INFO  GenomicsDBImport - Using google-cloud-java fork https://github.com/broadinstitute/google-cloud-java/releases/tag/0.20.5-alpha-GCS-RETRY-FIX
15:00:35.946 INFO  GenomicsDBImport - Initializing engine
15:00:38.360 INFO  IntervalArgumentCollection - Processing 58617616 bp from intervals
15:00:38.366 INFO  GenomicsDBImport - Done initializing engine
Created workspace /work/Analysis/wgs_chr19
15:00:38.849 INFO  GenomicsDBImport - Vid Map JSON file will be written to /work/Analysis/wgs_chr19/vidmap.json
15:00:38.849 INFO  GenomicsDBImport - Callset Map JSON file will be written to /work/Analysis/wgs_chr19/callset.json
15:00:38.849 INFO  GenomicsDBImport - Complete VCF Header will be written to /work/Analysis/wgs_chr19/vcfheader.vcf
15:00:38.850 INFO  GenomicsDBImport - Importing to array - /work/Analysis/wgs_chr19/genomicsdb_array
15:00:38.850 INFO  ProgressMeter - Starting traversal
15:00:38.850 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Batches Processed   Batches/Minute
15:00:39.771 INFO  GenomicsDBImport - Importing batch 1 with 5 samples
Buffer resized from 28469bytes to 32688
Buffer resized from 28473bytes to 32630
Buffer resized from 28469bytes to 32745
Buffer resized from 28469bytes to 32717
Buffer resized from 28466bytes to 32648
Buffer resized from 32688bytes to 32758
Buffer resized from 32630bytes to 32726
Buffer resized from 32648bytes to 32703
Buffer resized from 32717bytes to 32751
Buffer resized from 32703bytes to 32765
Buffer resized from 32745bytes to 32768
Buffer resized from 32726bytes to 32763
Buffer resized from 32765bytes to 32767
Buffer resized from 32758bytes to 32765
Buffer resized from 32751bytes to 32762
Buffer resized from 32767bytes to 32769
Buffer resized from 32763bytes to 32768
Buffer resized from 32762bytes to 32768
Buffer resized from 32765bytes to 32767
Buffer resized from 32767bytes to 32769
Buffer resized from 32768bytes to 32769
Buffer resized from 32768bytes to 32769
Buffer resized from 32768bytes to 32769
terminate called after throwing an instance of 'VariantStorageManagerException'
  what():  VariantStorageManagerException exception : Error while syncing array chr19$1$58617616 to disk
TileDB error message : [TileDB::utils] Error: Cannot sync file '/work/Analysis/wgs_chr19/chr19$1$58617616/.__a89fdd44-1241-43ba-9072-6fcf116fbc1d139627949156096_1538460040234'; File syncing error

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/13135/gatk-v4-0-8-1-genomicsdbimport-error-variantstoragemanagerexception-exception/p1

**Comment by bhanugandham** [comment]
The user was running GenomicsDBImport on **NFS** when he encountered this issue.

**Comment by nalinigans** [comment]
I have added extra checking and some debug code in the branch nalini_issue_5342 -https://github.com/broadinstitute/gatk/tree/nalini_issue_5342. @bhanugandham, would it be possible to run gatk from this branch to get more information?

Also, would it be possible to get information on what mount and other nfs options were used while mounting the drive?

If we are not able to pinpoint the issue, we can introduce an option to treat NFS like HDFS/GCS, that is think about NFS eventually getting consistent and react accordingly. But, I would like to test this branch out first to get more information.

**Comment by bhanugandham** [comment]
@nalinigans 

I have asked the user for more info on the mount and nfs options. I will update this ticket when the user gets back to me.

Also would you like me to just run gatk from this branch on my system locally or do I need a special setup for this?

**Comment by nalinigans** [comment]
@bhanugandham, just running the gatk from this branch should be sufficient, no special setup needed.
Any info from the user?

**Comment by bhanugandham** [comment]
@nalinigans 

I have not heard from the user yet. I have pinged the user again to send us their nfs info and I will keep you posted. I will have the results from testing the gatk branch you sent to me by the end of the day.

**Comment by quantumdot** [comment]
Also seem to be experiencing this issue:

```
Using GATK jar /home/user/gatk-4.0.12.0/gatk-package-4.0.12.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx4g -Xms4g -jar /home/user/gatk-4.0.12.0/gatk-package-4.0.12.0-local.jar GenomicsDBImport -V /mnt/isilon/experiment/18075-01/aligned/variant_calling/18175D-01-03_S44_L006.filt.srt.nodup.recal.bam.g.vcf.gz -V /mnt/isilon/experiment/18075-01/aligned/variant_calling/18175D-01-04_S45_L006.filt.srt.nodup.recal.bam.g.vcf.gz -V /mnt/isilon/experiment/18075-01/aligned/variant_calling/18175D-01-01_S42_L006.filt.srt.nodup.recal.bam.g.vcf.gz -V /mnt/isilon/experiment/18075-01/aligned/variant_calling/18175D-01-02_S43_L006.filt.srt.nodup.recal.bam.g.vcf.gz --genomicsdb-workspace-path /mnt/isilon/experiment/18075-01/aligned/variant_calling/genomics_db -L /mnt/isilon/experiment/resources/final_mm10_exon.bed --interval-padding 500 --reader-threads 5
11:57:49.202 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/user/gatk-4.0.12.0/gatk-package-4.0.12.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
11:57:50.896 INFO  GenomicsDBImport - ------------------------------------------------------------
11:57:50.896 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.0.12.0
11:57:50.896 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
11:57:50.896 INFO  GenomicsDBImport - Executing as user@user-machine on Linux v3.13.0-119-generic amd64
11:57:50.896 INFO  GenomicsDBImport - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_191-b12
11:57:50.896 INFO  GenomicsDBImport - Start Date/Time: January 11, 2019 11:57:49 AM EST
11:57:50.897 INFO  GenomicsDBImport - ------------------------------------------------------------
11:57:50.897 INFO  GenomicsDBImport - ------------------------------------------------------------
11:57:50.897 INFO  GenomicsDBImport - HTSJDK Version: 2.18.1
11:57:50.897 INFO  GenomicsDBImport - Picard Version: 2.18.16
11:57:50.897 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2
11:57:50.897 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
11:57:50.897 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
11:57:50.897 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
11:57:50.897 INFO  GenomicsDBImport - Deflater: IntelDeflater
11:57:50.897 INFO  GenomicsDBImport - Inflater: IntelInflater
11:57:50.897 INFO  GenomicsDBImport - GCS max retries/reopens: 20
11:57:50.898 INFO  GenomicsDBImport - Requester pays: disabled
11:57:50.898 INFO  GenomicsDBImport - Initializing engine
11:57:52.588 INFO  FeatureManager - Using codec BEDCodec to read file file:///mnt/isilon/experiment/resources/final_mm10_exon.bed
11:57:53.791 INFO  IntervalArgumentCollection - Processing 199895151 bp from intervals
11:57:53.825 WARN  GenomicsDBImport - A large number of intervals were specified. Using more than 100 intervals in a single import is not recommended and can cause performance to suffer. It is recommended that intervals be aggregated together.
11:57:53.837 INFO  GenomicsDBImport - Done initializing engine
11:57:54.037 INFO  GenomicsDBImport - Vid Map JSON file will be written to /mnt/isilon/experiment/18075-01/aligned/variant_calling/genomics_db/vidmap.json
11:57:54.037 INFO  GenomicsDBImport - Callset Map JSON file will be written to /mnt/isilon/experiment/18075-01/aligned/variant_calling/genomics_db/callset.json
11:57:54.037 INFO  GenomicsDBImport - Complete VCF Header will be written to /mnt/isilon/experiment/18075-01/aligned/variant_calling/genomics_db/vcfheader.vcf
11:57:54.037 INFO  GenomicsDBImport - Importing to array - /mnt/isilon/experiment/18075-01/aligned/variant_calling/genomics_db/genomicsdb_array
11:57:54.038 INFO  ProgressMeter - Starting traversal
11:57:54.038 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Batches Processed   Batches/Minute
12:05:27.926 INFO  GenomicsDBImport - Starting batch input file preload
12:05:29.246 INFO  GenomicsDBImport - Finished batch preload
12:05:29.246 INFO  GenomicsDBImport - Importing batch 1 with 4 samples
terminate called after throwing an instance of 'VariantStorageManagerException'
  what():  VariantStorageManagerException exception : Error while syncing array chr10$3119692$3120841 to disk
TileDB error message :
```

The filesystem is being mounted at boot time in /etc/fstab as follows:
```
//server/share       /mnt/isilon     cifs    uid=user,credentials=/home/user/.smbcredentials,domain=THE_DOMAIN,iocharset=utf8,sec=ntlm,vers=3.0   0       0
```

**Comment by ldgauthier** [comment]
Karthik had suggested setting the environment variable TILEDB_DISABLE_FILE_LOCKING=1 for NFS (see https://github.com/broadinstitute/gatk/issues/4753) -- maybe give that a shot?

**Comment by quantumdot** [comment]
I tried setting that environment variable, but it did not resolve the issue. Please note that I have this filesystem mounted as `CIFS` not `NFS`.

**Comment by nalinigans** [comment]
Sync uses the system call fsync() to synchronize contents and not sure how CIFS is erroring out.

Please see my [previous comment](https://github.com/broadinstitute/gatk/issues/5342#issuecomment-433760934). Would it be possible to gather some more information using the gatk from [branch nalini_issue_5342](https://github.com/broadinstitute/gatk/tree/nalini_issue_5342)? This branch puts out additional information with errno, etc.

**Comment by nalinigans** [comment]
@olavurmortensen, no  #5587 does not solve this issue. Currently, working on a release of GenomicsDB to help with this.

**Comment by olavurmortensen** [comment]
@nalinigans Sounds good. Any time frame on that release?

**Comment by ldgauthier** [comment]
This has been done (see above.)
