### ISSUE TITLE
Need a tool to compare references

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#5345]
### Tool(s) or class(es) involved
_ReferenceComparer_

### Description
We need a tool that will, given two reference sequences and dictionaries, create a comparison table between them.  

A shell script already exists that does this (`compareTwoReferenceDictionaries.sh`), but it could be more complete.

Specifically, in addition to doing the comparison of the dictionaries, when small differences are found, the sequences should be investigated and the differences in the sequences themselves should be displayed for the user.

**Comment by ldgauthier** [comment]
I only know of one time we needed this since this issue was opened and the shell script was just fine.  For posterity, the script is at scripts/funcotator/testing/compareTwoReferenceDictionaries.sh
