### ISSUE TITLE
implement NVAR, or Number of genotyped VARiants

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#536]
NVAR, or Number of genotyped VARiants

Description:

[minor/major allele] A minor (respectively major) allele is an allele present in less than (respectively, in at least) half the alleles from all the genotyped samples.

Description:

[NMIN] NMIN is the number of variants of the given sample with a genotype that is not major/major.

Influenced by:

Ethnicity (the distribution of NMIN is usually bimodal with Africans in one mode in the higher values).

Remark:

Since this metric focuses of minor alleles, the proportion of rare variants considered (where more errors are expected) is higher. This makes NMIN more sensitive to errors than NALT, which is a desirable feature.

Calculated by:

pseq i-stats (NMIN)

**Comment by jbloom22** [comment]
@akiezun The description above seems to be a mix of NVAR and NMIN...  can you clarify?
