### ISSUE TITLE
combine_tracks WDL python loading column as float64 when expecting string

### ISSUE THREAD

**Issue by fpbarthel** [broadinstitute/gatk#5360]
I'm getting a type error here because L278 expects a string for `POSSIBLE_GERMLINE` but `pandas.read_csv` returns a `float64` for this column.
https://github.com/broadinstitute/gatk/blob/d4db277dfa1a9c13188644fd28616249061f8704/scripts/unsupported/combine_tracks_postprocessing_cnv/combine_tracks.wdl#L277-L278

**Comment by samuelklee** [comment]
@fpbarthel I would guess that using the appropriate Docker image would resolve this.  @LeeTL1220 any comment?

**Comment by LeeTL1220** [comment]
@fpbarthel This is an issue I have corrected in a branch but I have not merged the change yet.  If you can alter the WDL, for now, the below code snippet will fix this issue:  
```tumor_tagged_df = pandas.read_csv(tumor_tagged, delimiter='\t', comment="@")
tumor_tagged_df["POSSIBLE_GERMLINE"] = tumor_tagged_df["POSSIBLE_GERMLINE"].astype('str')
tumor_tagged_pruned_df = tumor_tagged_df[((tumor_tagged_df["POSSIBLE_GERMLINE"] == "0.0") | (tumor_tagged_df["POSSIBLE_GERMLINE"] == "0") ) & (tumor_tagged_df["type"] != "centromere") & (tumor_tagged_df["ID"].isna())]
```

**Comment by fpbarthel** [comment]
Thanks @LeeTL1220 !
