### ISSUE TITLE
build_docker.sh fails due to folders that have not been cleared up

### ISSUE THREAD

**Issue by MartonKN** [broadinstitute/gatk#5369]
build_docker.sh creates unzippedJar and testsJar, but it does not remove them and it fails as a result in subsequent runs. 

I ran ./build_socker.sh -e <GIT LOG HASH> and I got the error message 
mv: rename ./build/bundle-files-collected to ./unzippedJar/bundle-files-collected: Directory not empty

Only after removing unzippedJar and testJar could I build the image again successfully.

**Comment by ldgauthier** [comment]
Does it work if you supply a staging directory as described in the readme: https://github.com/broadinstitute/gatk/blob/master/scripts/docker/README.md
`sudo bash build_docker.sh -e ${GITHUB_TAG} -d ${STAGING_DIR}`

**Comment by droazen** [comment]
@MartonKN What Laura said -- you should always be running this script with a clean staging directory.

**Comment by lucidtronix** [comment]
That is good to know! Closing this because it was my bad instructions that led to the issue.
