### ISSUE TITLE
How to combine gCNV result?

### ISSUE THREAD

**Issue by shengqh** [broadinstitute/gatk#5373]
## Feature request

I used gatk4 docker file to perform the germline CNV cohort analysis. I got the individual vcf file for each sample. But I cannot find the tool to combine the CNV, just like combining gvcf in SNV analysis. Is there any such tool that I missed? And, is there any visualization scripts I can use? Thank you so much.

**Comment by samuelklee** [comment]
Hi @shengqh, tools such as you describe are still under development.  We are also still working to tune hyperparameters in the main gCNV pipeline, so thanks for trying it out!  Please let us know if you encounter any issues.

**Comment by samuelklee** [comment]
@shengqh As usual, the GT field refers to the ALT alleles, which are always <DEL>,<DUP>.  So 1=<DEL> and 2=<DUP>.  CN gives the copy-number call; the maximum called copy number can be set as a tool parameter.
