### ISSUE TITLE
Document existence of mixed-ploidy and non-diploid support in GenomicsDB

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#5383]
From a researcher in the field. Their data processing would be much simpler if GenomicsDB accepted non-diploid and mixed-ploidy cases. Currently, researcher is encountering challenges to a workaround that uses CombineGVCFs (a GATK3 tool).

---

As an update, looks like `GenomicsDBImport` only supports diploid data, so we cannot use it. Would really appreciate your help on this.

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/53201#Comment_53201

**Comment by sooheelee** [comment]
@droazen what do we do with such requests?

**Comment by droazen** [comment]
@sooheelee Bring it up at office hours, and if it's important we can consider it for inclusion in the goals for a future quarter.

**Comment by sooheelee** [comment]
Will do.

**Comment by droazen** [comment]
@sooheelee As discussed in person, `GenomicsDBImport` does support non-diploid data. Can you ask the user to try it?

**Comment by sooheelee** [comment]
For @vdauwera and @bhanugandham, our documentation is out of date.

**Comment by sooheelee** [comment]
Hey @bhanugandham @rcmajovski, what is the status of this documentation update? It would be great to be able to point users to this.

**Comment by droazen** [comment]
@sooheelee @bhanugandham Perhaps this ticket ought to live in the comms team issue tracker rather than here?

**Comment by sooheelee** [comment]
I've opened a Monday.com pulse for @rcmajovski and so will close this in the meantime.
