### ISSUE TITLE
GermlineCNVCaller `-XL` gives error "Intervals for read-count file do not contain all specified intervals"

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#5388]
### Affected tool(s) or class(es)
GermlineCNVCaller 

### Affected version(s)
v4.0.4.0 and v4.0.11.0 tested with same result

### Description 
![screenshot 2018-11-02 14 50 17](https://user-images.githubusercontent.com/11543866/47934764-a8a71c80-deae-11e8-9f8f-c8a8b563d77a.png)

```
java.lang.IllegalArgumentException: Intervals for read-count file /home/shlee/gcnv/cvg/HG00096_chr20XY.hdf5 do not contain all specified intervals.
        at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:724)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.writeIntervalSubsetReadCountFiles(GermlineCNVCaller.java:390)
        at org.broadinstitute.hellbender.tools.copynumber.GermlineCNVCaller.doWork(GermlineCNVCaller.java:285)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

Command runs fine sans `-XL` parameter. The contents of `-XL` are simply:

![screenshot 2018-11-02 14 51 58](https://user-images.githubusercontent.com/11543866/47934827-e0ae5f80-deae-11e8-891e-473ec8420433.png)

#### Expected behavior
It would be great to be able to iterate GermlineCNVCaller on coverage data while excluding various regions, e.g. centromeric regions, to test the impact of such regions on the denoising. Currently, the hypothetical workaround would be to collect coverage while excluding regions or to manually remove such intervals from the coverage data. Having to collect coverage once over all of the data is preferable to collecting coverage again and again over slightly variable regions.

**Comment by sooheelee** [comment]
@samuelklee, I tested using v4.0.11.0 and see the same error with `-XL` so here is the bug report as promised.

**Comment by samuelklee** [comment]
Can you describe the inputs you are passing to `-L` and -XL`?  (I'm guessing the latter is just a BED file of centromeric regions, but how about the former?)

Is there any issue when you use `FilterIntervals` as is done in the WDL (i.e., running `FilterIntervals` with `-L` = the output of `PreprocessIntervals` and `-XL` = your blacklist, and then passing the corresponding interval list to the `-L` argument of `GermlineCNVCaller`?  This allows one to mask intervals at the modeling steps without recollecting coverage as you describe.

**Comment by sooheelee** [comment]
Yes, I see the same error when using FilterIntervals in the context of the WDL when supplying the BED file with the `-XL` param.

**Comment by sooheelee** [comment]
Thanks for clarifying the `-XL` intervals should match the bins! This is the problem as the BED file presents centromeric regions. I will think of a way to solve this for the tutorial.

**Comment by samuelklee** [comment]
Hmm, actually, I think there might be more to it.  The current FilterIntervals code also assumes that the annotated bins match the bins resolved from -L/-XL.  So if you pass -L/-XL to AnnotateIntervals, then you should be OK.  However, you might still get into trouble if your coverage bins don't match exactly (which might happen if -XL splits some bins).

Let me try and clean some of this up in a future PR.  (I think the issue is that we are trying to leverage some of the -L/-XL machinery provided by the engine, which should hopefully be familiar to users, but some of the assumptions the engine makes aren't really in line with what we need for CNV.)  I think for the tutorial you can just go ahead and blacklist at the coverage collection step.
