### ISSUE TITLE
implement PMISS, percent missing

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#539]
Description:

The proportion of samples that have missing data (and hence no genotype) for a given site.

Influenced by:

Common structural variation, repetitive region, extreme GC content (hard to sequence), capture bias or general sample preparation failures.

Remark:

This QC highlights issues with the region if many samples have missing data there. It is important to flag these sites. The GVCFs contain this information in the genotype fields. A sample with a no call (./.) or a sample with very low GQ is a sample whose data is missing. All other samples will have a genotype.

Alternatively we could use a per-site PGEN metric defined as ( 1 - PMISS )

Typical threshold: The site is filtered out if PMISS is higher than (50\%).

**Comment by jbloom22** [comment]
@akiezun you say a sample with a no call (./.) or a sample with very low GQ is a sample whose data is missing, but did not define the threshold for the latter.  Am I to assume that "missing data" equivalent to one of NO_CALL, UNAVAILABLE, or MIXED below?

    /** The sample is no-called (all alleles are NO_CALL */
    NO_CALL,
    /** There is no allele data availble for this sample (alleles.isEmpty) */
    UNAVAILABLE,
    /** Some chromosomes are NO_CALL and others are called */
    MIXED  // no-call and call in the same genotype

**Comment by akiezun** [comment]
provide an option `minGQ`: everything with GQ below that (and everything `./.`) is "missing"
