### ISSUE TITLE
Change to INFO: "WARN IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM."

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#5393]
Researchers are unnecessarily alarmed by this notification and this should an INFO not WARN. Putting in this request based on @droazen's request.

Stem from [this](https://gatkforums.broadinstitute.org/gatk/discussion/comment/53339#Comment_53339) and other researchers on the forum over time.

**Comment by lbergelson** [comment]
@droazen These types of UI issues always bug me.  I opened a pr here: https://github.com/Intel-HLS/GKL/pulls.  Do we have any idea who is responsible for that repo now?

**Comment by droazen** [comment]
Thanks @lbergelson. Looks like the repo hasn't been updated since March. Recommend pinging Paolo from Intel and asking who the current maintainer is.
