### ISSUE TITLE
Allow MarkDuplicatesSpark to take in multiple inputs

### ISSUE THREAD

**Issue by jsotobroad** [broadinstitute/gatk#5398]
I tried running MarkDuplicatesSpark with multiple inputs like it is run in production and got this user error

```
A USER ERROR has occurred: Sorry, we only support a single reads input for spark tools for now.
```

For this to go into production it would need to have the ability to take in multiple inputs (I'm currently trying to make a "fast" version of the production germline pipeline and it would be great to have this tool included in that pipeline).

@jamesemery

**Comment by lbergelson** [comment]
@jsotobroad I'm curious why this is necessary, aren't the bams aggregated with MergeBamAlignments before it gets to MarkDuplicates?

**Comment by droazen** [comment]
@jsotobroad Ok, we can add this feature fairly easily to `MarkDuplicatesSpark` -- @jamesemery is working on it now.
