### ISSUE TITLE
is anyone to give a clear description about CollectAllelicCounts, is this need if not doing paired?

### ISSUE THREAD

**Issue by 2236529177** [broadinstitute/gatk#5404]
Dear author,
Thanks for your great kindness for writing such a wonderful tool for CNV.
but I think the tutorial is a little not easy understand, you write two parts, one for Pon, one for modersegments, but if I want to use PON to analyse the CNV, the tutorial is bitty and often feel puzzled, which is a must step.

I have some concrete questions for help. I hope u can hele me if you are not that busy.
Q1: you compared pon and paired in https://gatkforums.broadinstitute.org/dsde/discussion/11682#4， 
so are you implying we should just use PON, anothing you also gived a question "Should we include our particular tumor’s matched normal in the PoN", is there a definite answer?
![image](https://user-images.githubusercontent.com/25199946/48310203-6031e200-e5c5-11e8-9eb1-1fb8a5ca13bf.png)

Q2:  I am really puzzled about the function CollectAllelicCounts, we have  CollectReadCounts， why need  CollectAllelicCounts,  both of them need bam, what is the relationship between PON and paired , my innner heart is Paralytic. 
![image](https://user-images.githubusercontent.com/25199946/48310253-e4389980-e5c6-11e8-8798-92ca11941b12.png)

**Comment by 2236529177** [comment]
how can we understand this, though I know this fucntion has many possiboe inputs. 
but some has only normal inputs, how is related to tunor? thanks a lot.
![image](https://user-images.githubusercontent.com/25199946/48310320-7d1be480-e5c8-11e8-9dde-4ed9ca45f804.png)

**Comment by 2236529177** [comment]
I do not know where is the multimode. you said "However, in more typical cases, using the allele counts in tumor-only mode can work well. " do u mean by we should drop CollectReadCounts, and pON can use the result of CollectAllelicCounts, is that right?  waiting in urgent help ,thanks a lot.
![image](https://user-images.githubusercontent.com/25199946/48310385-5e6a1d80-e5c9-11e8-880d-97a04e2485a6.png)

**Comment by 2236529177** [comment]
one said this , another said that, really confused
![image](https://user-images.githubusercontent.com/25199946/48310557-f832ca00-e5cb-11e8-9c8d-38f19b12d014.png)
![image](https://user-images.githubusercontent.com/25199946/48310564-0b459a00-e5cc-11e8-9536-71a02f9be54d.png)

**Comment by droazen** [comment]
@samuelklee or @LeeTL1220, perhaps one of you could answer this?

**Comment by samuelklee** [comment]
Hi @2236529177,

The GATK forum might be a better place for these types of questions, but I'll try to answer a few of them here:

> Q1: you compared pon and paired in https://gatkforums.broadinstitute.org/dsde/discussion/11682#4，
> so are you implying we should just use PON, anothing you also gived a question "Should we include our particular tumor’s matched normal in the PoN", is there a definite answer?

Section 4.2 of the tutorial compares 1) denoising using a PoN containing multiple normal samples, and 2) denoising using a PoN containing only the matched normal.  Assuming that the samples contained in the panel of normals are representative of the systematic biases present in the case samples (i.e., all samples were sequenced similarly), then option 1 will almost certainly yield better results.

You can include the matched normals of tumor case samples in the PoN if you are really pressed for normal samples.  However, you should be aware of the implications this might have for denoising those normals as cases; that is, you should be sure to select an appropriate number of eigensamples to use for denoising---if you use all available eigensamples, you will end up denoising away the copy-ratio signal of those samples entirely.

> Q2: I am really puzzled about the function CollectAllelicCounts, we have CollectReadCounts， why need CollectAllelicCounts, both of them need bam, what is the relationship between PON and paired , my innner heart is Paralytic.

CollectReadCounts counts the number of reads that overlap genomic bins (the size of which you can select, typically ~100bp-1kb); these counts are used to estimate copy ratio.  In contrast, CollectAllelicCounts counts the number of alt and ref bases in the pileup at genomic sites; these allelic counts are used to estimate minor-allele fraction.

> how can we understand this, though I know this fucntion has many possiboe inputs.
> but some has only normal inputs, how is related to tunor? thanks a lot.

The possible inputs to ModelSegments are `denoised-copy-ratios`, `allelic-counts`, and `normal-allelic-counts`.  As alluded to above, you can run either tumor or normal samples as cases.  In both scenarios, you would provide denoised copy ratios (generated by running the output of CollectReadCounts through DenoiseReadCounts, using a PoN to denoise if available) to `denoised-copy-ratios` and/or allelic counts (output by CollectAllelicCounts) to `allelic-counts`.  Furthermore, when running a tumor case sample, you may additionally provide the allelic counts from a matched normal to `normal-allelic-counts`.  Note that the PoN is only used to denoise copy ratios, not allelic counts.

So the first example you showed is for running a normal case sample using only denoised copy ratios from the normal:
```gatk ModelSegments \
          --denoised-copy-ratios normal.denoisedCR.tsv \
          --output-prefix normal \
          -O output_dir```

The second example is for running a tumor case sample using only allelic counts from the tumor:
```gatk ModelSegments \
          --allelic-counts tumor.allelicCounts.tsv \
          --output-prefix tumor \
          -O output_dir```

Hope this helps.  If you have additional questions, please feel free to post on the forum!
