### ISSUE TITLE
Data Sources are bad right now.

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#5419]
FIX IT.

**Comment by lbergelson** [comment]
![image](https://user-images.githubusercontent.com/4700332/48581572-368ff800-e8f0-11e8-91bc-9063e11ce497.png)

**Comment by jonn-smith** [comment]
![image](https://user-images.githubusercontent.com/11667487/48581611-4c9db880-e8f0-11e8-8cf4-48ae7adb4ad3.png)
