### ISSUE TITLE
Emit vcf of all assembled variants

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#5426]
Many times the question comes up of whether variants are lost in HaplotypeCaller and Mutect2 because they are not assembled.  It seems like an easy and scalable way to answer this would be to emit an optional sites-only vcf of all variants in the `EventMap` before genotyping.  That way we could do internal validations about assembly much faster than currently. and user questions in this vein would not require the IDE or looking at bamouts in IGV.

I envision something like this:
```
gatk Mutect2 -I tumor.bam -O out.vcf --assembled-variants assembled.vcf
gatk SelectVariants truth.vcf --discordance assembled.vcf -O assembly-false-negatives.vcf
```

@ldgauthier @yfarjoun what do you think about this?

**Comment by ldgauthier** [comment]
My first step is usually to run HC with the debug output on, which enumerate the EventMap, so this is a much more concise and readable alternative.

IIRC, the EventMap is post-pruning, right?  So this would be events that are assembled and survive pruning, but then don't have enough alt read evidence to get genotyped as variants?

**Comment by davidbenjamin** [comment]
> IIRC, the EventMap is post-pruning, right?

That's right.
