### ISSUE TITLE
Funcotator data sources are swapped

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#5428]
The somatic are labeled as germline and visa-versa.

The files themselves must be changed, as well as the data source downloader (to point to the new paths).

**Comment by jonn-smith** [comment]
Should fix this at the same time as #5259 and #5429.

**Comment by droazen** [comment]
@jonn-smith Is this one fixed yet?

**Comment by jonn-smith** [comment]
@droazen No.  It won't be fixed until the sources are released again, which is backed up by a couple of other things.
