### ISSUE TITLE
Funcotator - Add ensembl data source support

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#5453]
Currently Funcotator only supports `Gencode` for transcript annotations.  We should expand this to support `Ensembl` as well.

This will involve making a parent class for both Gencode and Ensembl (`TranscriptDataSource`) and possibly a new tribble codec.  This will enable support for any Ensembl organism, such as _canis familiaris_.

Funcotator should then be changed to require a `TranscriptDataSource` rather than a `Gencode` data source.

**Comment by droazen** [comment]
Done!

**Comment by droazen** [comment]
(Closed by #6477)
