### ISSUE TITLE
Optimize CigarUtils.calculateCigar

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#5459]
In `CigarUtils.calculateCigar(final byte[] refSeq, final byte[] altSeq)` we have the following optimization to check for exact equality in order to avoid expensive Smith-Waterman alignment:

```
if (Arrays.equals(refSeq, altSeq)){
            return eg 101M
}
```

We could similarly optimize a broader class of alt haplotypes by ruling out indels and returning M-only Cigars.  To do this, line up the two sequences and see if there are a small number of non-contiguous mismatches.  If so, each mismatch is a substitution.

This optimization would shave about 5% off the runtime of both Mutect2 and HaplotypeCaller.

**Comment by lbergelson** [comment]
@davidbenjamin Have you tried enabling hardware smith-waterman acceleration?  In my experience it took the time that smith waterman takes in haplotype caller from ~10% -> ~0%.

**Comment by davidbenjamin** [comment]
@lbergelson I haven't, but if this comes out to ~5 lines of code, would you object?

**Comment by lbergelson** [comment]
If it's in a critical haplotype caller hotspot you might want to actually write a for loop instead of the stream.  They're faster.

**Comment by davidbenjamin** [comment]
> If it's in a critical haplotype caller hotspot you might want to actually write a for loop instead of the stream. They're faster.

I know, having learned that lesson several times.  Given that this is O(# of haplotypes) [each haplotype vs ref] and not O(# of haplotypes^2) [i.e. every haplotype vs every haplotype] or O(# of reads) I'm not expecting it to matter, but I will definitely profile.
