### ISSUE TITLE
BwaSpark and ReadsPipelineSpark with spark master 

### ISSUE THREAD

**Issue by qinqian** [broadinstitute/gatk#5481]
### Goal
Our team try to explore the usage of GATK Spark tool for our internal WES and WGS data.

### Affected tool(s) or class(es)
BwaSpark and ReadsPipelineSpark

### Affected version(s)
- [ X ] Latest public release version [gatk 4.0.11.0]

### Description 
For both tools, we encountered an issue when the driver shutdown the command as the screenshot. However, for the bwaspark, the alignment ratio seems to be unaffected by the error, but the lines number of the VCF file from ReadsPipelineSpark varies randomly, and quite different from the non-spark version of GATK 4.0.5.2.

#### Steps to reproduce
Before running the tool, we generated the image index for whole genome by using the fasta file from GATK official ftp site, and uploaded the reference file to Hadoop HDFS.

``` bash
gatk-4.0.11.0/gatk BwaMemIndexImageCreator -I Homo_sapiens_assembly38.fasta -O Homo_sapiens_assembly38.fasta.img
```

and then, we preprocess our pair end fastq files into unaligned ubam file as, 
``` bash
     java -jar picard.jar FastqToSam \
             F1=R1.fastq.gz
             F2=R2.fastq.gz
             O=unaligned_reads.bam \
             SM=sample001 \
             PL=illumina \
             RG=rg001
```

For BwaSpark, we used,
``` {bash}
   ../gatk-4.0.11.0/gatk --java-options "-Dgatk.spark.debug=true -XX:+PrintGCDetails" BwaSpark -I hdfs://ns/user/root/test/unaligned_reads.bam -O hdfs://ns/user/root/test/test3.bam -R hdfs://ns/user/root/Homo_sapiens_assembly38.fasta  --spark-runner SPARK --spark-master spark://master:7077 -- --num-executors 4 --driver-memory 4g --executor-cores 10 --executor-memory 20g
```

For ReadsPipelineSpark, we used, 
``` {bash}
 time_gatk "ReadsPipelineSpark --tmp-dir /tmp --align true -I hdfs://ns/user/root/test/unaligned_reads.bam -O hdfs://ns/user/root/test/test10.vcf -R hdfs://ns/user/root/Homo_sapiens_assembly38.fasta --known-sites hdfs://ns/user/root/Homo_sapiens_assembly38.dbsnp138.vcf -pairHMM AVX_LOGLESS_CACHING --max-reads-per-alignment-start 50" 4 44 88g 12g
```

#### Expected behavior
Both tool should end successfully without the specified error, and generated consistent result.

#### Actual behavior
Both tool ends throwing out the same error, but the alignment ratio of the bam file from bwaspark is the same as the original bwa, and seems to be ok. The vcf variant number changes between each runs, and different from the result of stable non-spark official GATK 4 version.

``` bash
2018-12-03 13:19:45 ERROR CoarseGrainedExecutorBackend:43 - RECEIVED SIGNAL TERM
```

The vcf line number for several runs of the ReadsPipelineSpark,
``` bash
94488 test2.vcf.gz
97426 test3.vcf.gz
82279 test4.hg19.vcf.gz
99403 test4.vcf.gz
86384 test7_hg19.vcf.gz
104854 test7.vcf.gz
68824 test9.vcf.gz
97810 test.vcf.gz
```

----

**Comment by ldgauthier** [comment]
@droazen are we supporting these Beta Spark tools?

**Comment by droazen** [comment]
@ldgauthier They are use-at-your-own-risk, though in general we try to help users with problems. However, in this case the report is so old, and `ReadsPipelineSpark` has changed so much since then, that it's unclear whether this is still an issue with the current version.

**Comment by ldgauthier** [comment]
Okay, I'm going to close and you can reopen if it's an issue in the latest version @qinqian
