### ISSUE TITLE
Fails to build with gradle-5

### ISSUE THREAD

**Issue by yurivict** [broadinstitute/gatk#5483]
See comments here: https://github.com/gradle/gradle/issues/7914#issuecomment-444189149

**Comment by lbergelson** [comment]
Hi @yurivict, gatk requires gradle 3.1.  We include the wrapper script so you can always just run `./gradlew` instead of using the system gradle and it will automatically resolve the correct version.

**Comment by yurivict** [comment]
It does build with ```gradle-4.6``` though.

**Comment by lbergelson** [comment]
We would be happy to accept a patch to move to a new version of gradle.   (We've wanted to do so for a long time but haven't gotten around to it... https://github.com/broadinstitute/gatk/issues/4659)

There's a partial upgraded version [here](https://github.com/broadinstitute/gatk/tree/lb_update_to_gradle_4.8) but it had some problem and I never got around to finishing it.

**Comment by lbergelson** [comment]
Our gradle script does a bunch of testing and packaging, so while build might work I think we had problems with getting all of tests to run correctly and the javadoc built right or something like that...  We definitely recommend you use the wrapper.  Is there a reason that the wrapper won't work for you?

**Comment by yurivict** [comment]
I'm a FreeBSD port maintainer, and only have resources to report problems, not to fix them.

**Comment by lbergelson** [comment]
Ah.  I see.  It's not clear to me what that problem is though.  You can have many version of gradle coexisting.  Gatk doesn't have to build with system gradle because it comes with the `./gradlew` wrapper which chooses the correct version to build it with.

**Comment by lbergelson** [comment]
I agree that it is a good security measure to use fixed signed dependencies for repeatable builds.

GATK depends on gradle 3.1. 
download [here](https://services.gradle.org/distributions/gradle-3.1-bin.zip) [shaw256](https://services.gradle.org/distributions/gradle-3.1-bin.zip.sha256)

**Comment by yurivict** [comment]
> GATK depends on gradle 3.1.: download shaw256

It currently works with gradle-4.6, no need to go back to 3.1.

**Comment by lbergelson** [comment]
Sure, if it builds correctly, but it's not supported.
