### ISSUE TITLE
Unable to disable command line in VCF header in FilterByOrientationBias

### ISSUE THREAD

**Issue by ycl6** [broadinstitute/gatk#5493]
### Affected tool(s) or class(es)
FilterByOrientationBias

### Affected version(s)
gatk-4.0.11.0

### Description 
Using `--add-output-vcf-command-line false` in `FilterByOrientationBias` didn't hide command line in the resulting VCF header

**Comment by cmnbroad** [comment]
Yeah, I think this is one of a number of tools that don't use `getDefaultToolVCFHeaderLines` to get the standard header lines, which honors this setting.

**Comment by davidbenjamin** [comment]
Orientation bias filtering is now done within FilterMutectCalls.
