### ISSUE TITLE
port NA12878DBWalker and the knowledge database (in hellbender-private)

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#55]
entered here but the code will be in hellbender-private

**Comment by akiezun** [comment]
@ldgauthier can you list here all subclasses of `NA12878DBWalker` that need to be ported?

**Comment by ldgauthier** [comment]
The code is hard to read and I don't know how to get that info from IntelliJ, but I think we need all of the subclasses in walkers/na12878kb/ including all in assess/ and probably most in core/:

gsa-unstable/private/gatk-tools-private/src/main/java/org/broadinstitute/gatk/tools/walkers/na12878kb/:
ExportReviews.java
ExtractConsensusSites.java
ImportCallset.java
ImportReviews.java
NA12878DBWalker.java
NA12878KnowledgeBaseServer.java
SummarizeConsensus.java
UpdateConsensus.java

gsa-unstable/private/gatk-tools-private/src/main/java/org/broadinstitute/gatk/tools/walkers/na12878kb/assess:
AllSitesWriter.java
AssessNA12878.java
Assessment.java
AssessmentType.java
Assessor.java
BadSitesWriter.java
ROCCurveNA12878.java (a different walker, but something else we use often)
SitesWriter.java

gsa-unstable/private/gatk-tools-private/src/main/java/org/broadinstitute/gatk/tools/walkers/na12878kb/core:
CallSet.java
ConsensusMaker.java
ConsensusSummarizer.java
MongoDBManager.java
MongoGenotype.java
MongoVariantContext.java
NA12878DBArgumentCollection.java
NA12878KBMain.java
NA12878KnowledgeBase.java
*NewlyAddedSites.java
*OneChunkIterator.java
PolymorphicStatus.java
*RawSiteIterator.java
SiteIterator.java
SiteManager.java
SiteSelector.java
TruthStatus.java
* I haven't come across these classes before, so I'm not sure if they're essential

(I haven't explored this code, but it's probably necessary)
gsa-unstable/private/gatk-tools-private/src/main/java/org/broadinstitute/gatk/tools/walkers/na12878kb/core/errors:
InvalidRecordHandler.java
InvalidRecordsLogError.java
InvalidRecordsRemove.java
InvalidRecordsThrowError.java
MongoVariantContextException.java

**Comment by eitanbanks** [comment]
The starred classes are critical.  I wrote them so can help describe functionality.

**Comment by akiezun** [comment]
@ldgauthier  to see the type hierarchy in intellij, press Ctrl+h

**Comment by droazen** [comment]
Are we actually going to create a `hellbender-private`? (please say no....) What is the future of this ticket?

**Comment by lbergelson** [comment]
Is there any reason these couldn't be generalized so they aren't hardcoded with our server address or whatever it is that keeps them private?  I don't see why we couldn't put them in public.

**Comment by ldgauthier** [comment]
@yfarjoun How do you feel about giving up on the NA12878 suite of tools in favor of the more general truth assessment walker we've talked about in the past?

**Comment by fleharty** [comment]
I would vote that we transition to a more general truth assessment walker.

Mark

**Comment by yfarjoun** [comment]
:+1:

**Comment by ldgauthier** [comment]
Closing this in favor of https://github.com/broadinstitute/gatk/issues/2267
