### ISSUE TITLE
Update JEXL recommendations in public documentation 

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#5509]
We should update any public docs that contain recommendations on how to write JEXL expressions to reflect the align with the doc changes made in https://github.com/broadinstitute/gatk/pull/5422. Specifically, we should recommend that multiple simple expressions be used in place of a single compound expression. Here are @sooheelee 's notes on what docs need to change:

Here are the documents we should also update to reflect these updates:

https://gatkforums.broadinstitute.org/gatk/discussion/1255/using-jexl-to-apply-hard-filters-or-select-variants-based-on-annotation-values
https://software.broadinstitute.org/gatk/documentation/article?id=11080
Also, here is a list of documents with the jexl tag:
https://gatkforums.broadinstitute.org/gatk/discussions/tagged/jexl

I have put in a word of caution in https://gatkforums.broadinstitute.org/gatk/discussion/12350/how-to-filter-on-genotype-using-variantfiltration/p1?new=1.

**Comment by bhanugandham** [comment]
Assigning this to @rcmajovski

**Comment by cmnbroad** [comment]
I believe this has been done now (https://dsp-comms.monday.com/boards/145112271/pulses/154019058), so I'm restoring the  link in the gakt docs for VariantFiltration.

**Comment by sooheelee** [comment]
This is done so I will close the ticket.
