### ISSUE TITLE
Must account for BGI sequence platform (and possibly others)

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#5517]
Currently `ValidateSamFile` has a limited list of platforms which does not include `BGI`.

We should add `BGI` to the list of valid platforms, and we should review our list of supported platforms to make sure there are no others we are missing.

**Comment by lbergelson** [comment]
@yfarjoun Do you know if BGI's sequencing is compatible with our tools without any special treatment?

**Comment by yfarjoun** [comment]
According to this paper https://www.nature.com/articles/s41467-018-03590-5

it is: "Each resulting qualified captured library with the SureSelect Human
All Exon kit (Aglient) was then loaded on *BGISEQ-5000 *sequencing
platforms, and we performed high-throughput sequencing for each captured
library. High-quality reads were aligned to the human reference genome
(GRCh37) using the Burrows-Wheeler Aligner (BWA v0.7.15) software. All
genomic variations, including single-nucleotide polymorphisms and InDels
were detected by *HaplotypeCaller of GATK *(v3.0.0).
"

**Comment by ldgauthier** [comment]
We can reopen this if we hear from any users running on BGI data.

**Comment by ldgauthier** [comment]
Actually it looks like Yossi has a PR for this: https://github.com/samtools/htsjdk/pull/1427
