### ISSUE TITLE
Scatter all bam walkers in M2 WDL

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#5534]
Currently we scatter `Mutect2` itself but not `CalculateContamination` and `CollectF1R2Counts`.  These take a few hours and it would be nice for development to be able to lower wall clock time.

I propose running `CollectF1R2Counts` and `GetPileupSummaries` within the scattered `M2` task and then combining the scattered output tables.  This seems cleaner than having multiple independent scatters.

@takutosato what do you think?

**Comment by takutosato** [comment]
Sounds good! I can work on it - should be a straightforward exercise in IO to concatenate the scattered output files (and sorting for `GetPileupSummaries`, I think)

**Comment by davidbenjamin** [comment]
@takutosato Alright, it's yours.  By the way, even though some or all of this could be done in bash, I think we should make proper GATK tools for merging.

**Comment by takutosato** [comment]
Addressed by #5599
