### ISSUE TITLE
implement an efficient overlaps function for collections of Locatable

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#559]
We should probably adapt the IntervalTree from htsjdk to work for us.  We've run into a number of cases where this is needed, in Valentine's exome code and in Tom's hadoop reader.  We could use both

```boolean overlaps(Locatable locatable, IntervalTree<Locatable> locatables)```

 and 

```Set<Locatable> getOverlapping(Locatable locatable, IntervalTree<Locatable> locatables)```

**Comment by akiezun** [comment]
assigning to me but @cmnbroad will work on it

**Comment by droazen** [comment]
Reassigning to @edwardkw

**Comment by jean-philippe-martin** [comment]
I got one. Microbenchmark shows it's 70x faster than a linear search.

**Comment by cmnbroad** [comment]
For the record, I only needed the IntervalVariantFilterin #792 because of a bug in VariantWalker, which I've now fixed so its no longer a use-case for this.

**Comment by lbergelson** [comment]
@jean-philippe-martin Want to add your solution to SimpleInterval or IntervalUtils?  This need shows up pretty often.

**Comment by jean-philippe-martin** [comment]
@lbergelson sure, I can split it off and make a separate pull request. Remind me in a bit if you don't see it in your inbox.

**Comment by jean-philippe-martin** [comment]
There you go, it's PR #892.

**Comment by droazen** [comment]
This is done -- `IntervalsSkipList` satisfies this ticket. Closing
