### ISSUE TITLE
copy read tensor model

### ISSUE THREAD

**Issue by xiaozhangzaq** [broadinstitute/gatk#5590]
i copy the user trained cnn vqsr model(gatk4 cnn) (from other machine to this machine), can i directly use the model to score vcf

**Comment by xiaozhangzaq** [comment]
Yes,if i want to use the model I trained on another machine, i should  train it again?
I have another question, i benchmark hg002 vcfs using default model and model I trained(use hg002 truth vcf and bed[HG002_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-22_v.3.3.2_highconf_triophased.vcf.gz]), but default model get better recall and precision. I want to know the default model  is trainning from what? can I use this model to vqsr  all vcf files?

**Comment by xiaozhangzaq** [comment]
Yes,So  if I want to use the model I trained on another machine, should  I train it again?
I have one more  question, I benchmark hg002 vcf using default model and model I trained(use hg002 truth vcf and bed[HG002_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-22_v.3.3.2_highconf_triophased.vcf.gz]), but default model gets better recall and precision. I want to know what the default model  is trainning from. Can I use this model to vqsr  all vcf files?

**Comment by lucidtronix** [comment]
Hi @xiaozhangzaq , Yes you can use the default model to vqsr all single sample VCF files.  The default model was trained on a very large aggregation of data with truth resources from Genomes in a Bottle, SynDip, and Platinum Genomes.  We trained on the NA12878, NA24149, and NA24143 samples from Genomes in a Bottle.  You do not have to train the model again to use it on another machine.

**Comment by xiaozhangzaq** [comment]
![chr1_error](https://user-images.githubusercontent.com/19809536/51717986-07c79800-207e-11e9-8cf7-197e4f91bb6c.png)
when i run CNNScoreVariants step, chr1 failed, but chr2-22 could run successfully( I use -L to run in parallel by chromosome). How much resources and time does this step(chr1) need?

**Comment by ldgauthier** [comment]
In production we can run a whole single-sample genome in 10GB of Java memory (-Xmx10g).  I wouldn't expect chr1 to take too much longer than chr2.
