### ISSUE TITLE
Provide an option for ReadsSource to load unmapped reads.

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#560]
ReadsSource currently cannot read unmapped read due to a limitation in the gcloud bam reader.  

Relates to #166 and #286

**Comment by akiezun** [comment]
@lbergelson do you have a ticket number for the gcloud bam reader? if yes, what is it? If not, how can we let google know about this?

**Comment by lbergelson** [comment]
I discovered that it actually is possible to load unmapped reads with the existing google code code.  I had thought it didn't include the ability to do so, but after further digging, there's a way to do it that we just haven't exposed.

**Comment by lbergelson** [comment]
The unmapped read issue is complicated though, we've discovered that the htsjdk getUnmapped functions don't return all unmapped reads, because mated unmapped reads are often aligned to the positions of their mate.  So these get picked up when reading in intervals, but they don't get picked up when calling getUnmapped.

**Comment by droazen** [comment]
This ticket is unblocked by the work done in https://github.com/googlegenomics/dataflow-java/pull/107

**Comment by droazen** [comment]
This is a dataflow ticket -- closing.
