### ISSUE TITLE
Rename default true boolean arguments in GATKTool and GATKSparkTool

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#5600]
Currently there are number of boolean arguments in GATKTool that are set by default to `true`. Unfortunately, the current syntax for changing that value on the command line is to write "--argument-name false" (eg. `--create-output-bam-index false`) which is confusing an counterintuitive. This format made more sense for arguments when the syntax in picard/gatk3 used to be "ARGUMENT=FALSE". I propose that these arguments have their statements inverted wherever possible so that the user should always be negating some option that was perviously true (eg. `--disable-output-bam-index-creation` or some other alternative). Given the new argument input format this makes more intuitive sense and helps differentiate between toggle arguments and arguments with inputs on the command line without having to remember what the default value is. 

A change like this would affect a number of old/bedrock arguments in the engine like, `--create-output-variant-index`, `--add-output-sam-program-record`, and `--add-output-vcf-command-line` to name a few. Since there are many arguments following this pattern perhaps the overhead from making a change like this isn't worth it. 

(Also applies to changes in GATKSparkTool #5574)

**Comment by lbergelson** [comment]
Now is a good time to make a breaking change like that.  @droazen Your comments?

**Comment by lbergelson** [comment]
I think that's a good idea if it's a permanent change.
