### ISSUE TITLE
CreateSomaticPanelOfNormals - Improve header content

### ISSUE THREAD

**Issue by af8** [broadinstitute/gatk#5609]
Hi,

`CreateSomaticPanelOfNormals` results in a VCF file whose header contains information only for one of all the samples used to create it.

* ##tumor_sample="..."
* ##GATKCommandLine="..."
* Possibly other commands like ##bcftools_concatCommand="..."

----
### Tool(s) or class(es) involved
_CreateSomaticPanelOfNormals_

### Description
Would it be possible to store in **##tumor_sample=** the list of all sample IDs used to create the PON ? The principal aim is to have a better traceability of the whole process in the final VCF header. Also, one will be able to compute the number of normals used, if useful.
----

Best,
Anthony

**Comment by davidbenjamin** [comment]
@af8 That seems reasonable.  I will add it to our to-do list.
