### ISSUE TITLE
Documentation request: Add MLEAC and MLEAF to Barclay as they do not show up in tool documentation

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#5624]
## Documentation request

Add MLEAC and MLEAF to Barclay as they do not show up in tool documentation. Current GATK version is 4.1.0.0.

`MLEAC` and `MLEAF` annotations do not show up in [GATK forum tool documentation](https://software.broadinstitute.org/gatk/documentation/tooldocs/4.1.0.0/) under _Variant Annotations_. They are encoded by `MLE_ALLELE_COUNT_KEY` and `MLE_ALLELE_FREQUENCY_KEY` in the codebase [here](https://github.com/broadinstitute/gatk/blob/4.1.0.0/src/main/java/org/broadinstitute/hellbender/utils/variant/GATKVCFConstants.java).

In case their current Javadoc explanations are wanting, here are some resources to reference.
- https://gatkforums.broadinstitute.org/gatk/discussion/1283/mleaf-and-mleac
- https://gatkforums.broadinstitute.org/gatk/discussion/3740/mleac-and-mleaf-after-subsetting-with-selectvariants
- https://gatkforums.broadinstitute.org/gatk/discussion/5544/ac-versus-mleac

**Comment by cmnbroad** [comment]
These appear to not be implemented as part of the Annotation framework (they're not `Annotation`-derived classes), so they can't just be tagged for doc. @ldgauthier do you know if that intentional or historical ?

**Comment by ldgauthier** [comment]
They get added as part of "genotyping" by the AFCalculator.  It happens during the QUAL calculation (which technically isn't an annotation), so it gets annotated during that calculation.  It may also need data we can't pass into the annotations as the InfoFieldAnnotation class is currently implemented, but I'm not 100% sure about that.

Also word on the street is that no one at the Broad uses these.  They were super useful for the low coverage 1000G data, but for modern higher coverage sequencing they're pretty much always the same as AC and AF.

**Comment by sooheelee** [comment]
Would you say they are taking up unnecessary real estate? Would they be better off not being emitted by default? 

From a documentation standpoint, our tools emit them so we should describe them in the docs somewhere as we do the other annotations. The docs describe a few other annotations that I have not ever even seen emitted.
