### ISSUE TITLE
Add --version 

### ISSUE THREAD

**Issue by marchoeppner** [broadinstitute/gatk#5627]
GATK currently has no way of reporting its version - so adding a "-v" or "--version" would be welcome.

**Comment by cmnbroad** [comment]
@marchoeppner `gatk --version` should do it. Does that not work for you ?

**Comment by marchoeppner** [comment]
Right, seems to be a recent update, Using the very latest release works. Thanks.

**Comment by lbergelson** [comment]
Yes, this was a long standing issue, you previously had to run a `gatk PrintReads --version`.  It was fixed by https://github.com/broadinstitute/gatk/pull/5537.
