### ISSUE TITLE
Add progress meter to CreateSomaticPanelOfNormals

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#5629]
### Tool(s) or class(es) involved
M2 PoN Creation

### Description
There is no progress meter when running `CreateSomaticPanelOfNormals`.  This makes debugging harder and the tool could be accidentally identified as frozen.

### Proposed solution
`final Consumer<Locatable> progressUpdater,` as a parameter to the backend class.
The CLI ( `CreateSomaticPanelOfNormals`) can just pass in `l -> progressMeter.update(l)` as long as the CLI extends GATKTool.
When you want to disable the progress meter, you can simply pass in: `l -> {}`

**Comment by davidbenjamin** [comment]
Closed by #5675, which made the tool a `VariantWalker`.
