### ISSUE TITLE
Variants with spanning deletions lack phase set information

### ISSUE THREAD

**Issue by tfenne** [broadinstitute/gatk#5651]
### Affected tool(s) or class(es)
HaplotypeCaller 4.1 with -ERC GVCF

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
It would appear that variants covered by a spanning deletion are not output with phasing information even when surrounded by phased variants on either side.  Since one of the alleles is covered by an upstream deletion phase is known, but the genotype itself is not phased and no phase set is attached.  The following is a cut-down example from a gVCF:

```
chr6  51618169  .  GT  G,<NON_REF>    948.60   .  DP=94         GT:AD:DP:F1R2:F2R1:GQ:PGT:PID:PL:PS:SB  0|1:32,39,0:71:3,4,0:29,35,0:99:0|1:51618169_GT_G:956,0,808,1054,926,1980:51618169:3,29,4,35
chr6  51618170  .  T   *,G,<NON_REF>  776.01   .  DP=92         GT:AD:DP:F1R2:F2R1:GQ:PL:SB             1/2:2,39,30,0:71:1,4,2,0:1,35,28,0:99:3533,786,723,1141,0,956,2837,916,1206,2757:1,1,6,63
chr6  51618171  .  G   <NON_REF>      .        .  END=51618173  GT:DP:GQ:MIN_DP:PL                      0/0:90:99:90:0,120,1800
chr6  51618174  .  A   G,<NON_REF>    1001.60  .  DP=89         GT:AD:DP:F1R2:F2R1:GQ:PGT:PID:PL:PS:SB  0|1:33,41,0:74:3,4,0:30,37,0:99:0|1:51618169_GT_G:1009,0,803,1108,926,2034:51618169:3,30,4,37
```

You can see that the SNP at 51618170 is flanked by phased variants at 51618169 and 51618174, but is output with unphased genotype and no `PS` (or `PID/PGT`).

I'm not entirely sure if this is on purpose for some reason I don't understand, or simply an edge case in the phasing code that's handled incorrectly.

#### Steps to reproduce
Run HC on reads with three variants, starting with a deletion, a variant spanned by the deletion and a variant just beyond the deletion.  FWIW I've requested permission to share an example case from real data and am awaiting an answer.

#### Expected behavior
I think the spanned variant should be output with phasing information, e.g. in the above case I would expect (abbreviated):

```
chr6  51618169  .  GT  G,<NON_REF>    ...  GT:DP:PS  0|1:71:51618169
chr6  51618170  .  T   *,G,<NON_REF>  ...  GT:DP:PS  2|1:71:51618169
chr6  51618171  .  G   <NON_REF>      ...  GT:DP     0/0:90
chr6  51618174  .  A   G,<NON_REF>    ...  GT:DP:PS  0|1:74:51618169
```

#### Actual behavior
The actual output (abbreviated):

```
chr6  51618169  .  GT  G,<NON_REF>    ...  GT:DP:PS  0|1:71:51618169
chr6  51618170  .  T   *,G,<NON_REF>  ...  GT:DP     1/2:71:51618169
chr6  51618171  .  G   <NON_REF>      ...  GT:DP     0/0:90
chr6  51618174  .  A   G,<NON_REF>    ...  GT:DP:PS  0|1:74:51618169
```

**Comment by droazen** [comment]
@cwhelan @ldgauthier Care to comment on this one?

**Comment by nh13** [comment]
@cwhelan @ldgauthier @droazen any thoughts on this one?

**Comment by cwhelan** [comment]
After some preliminary poking around, I think these sites are not being phased because the phasing code strictly limits itself to biallelic sites (see `AssemblyBasedCallerUtils.constructHaplotypeMapping()`), and at the example site here considers there to be three possible alleles: `T`, `G`, and `*`. I'm not sure how much work it would be to special-case an exception through the phasing code for the spanning deletion allele yet.

**Comment by ldgauthier** [comment]
I don't want to make any changes to phasing until the new assembly modifications are done, because I expect that will clear up a lot of lost sensitivity.

**Comment by ldgauthier** [comment]
See #5828 for more details about the above "new assembly modifications"

**Comment by nh13** [comment]
@ldgauthier is this fixed with `--linked-de-bruijn-graph`?

**Comment by fleharty** [comment]
@nh13 @ldgauthier @davidbenjamin Yes, the new assembly modifications have been made.

**Comment by cwhelan** [comment]
I'll take a look at this after my current spanning deletion work is done, then, or if possible I'll look into incorporating it into that.

**Comment by cwhelan** [comment]
I have a version of this working in the branch `cw_phase_star_allele`, but am holding off on making a PR until https://github.com/broadinstitute/gatk/pull/6859 can be merged to avoid conflicting changes to integration test files.

**Comment by cwhelan** [comment]
Fixed via https://github.com/broadinstitute/gatk/pull/6937
