### ISSUE TITLE
MarkDuplicateSpark is slower than normal MarkDuplicates

### ISSUE THREAD

**Issue by sooheelee** [broadinstitute/gatk#5670]
For @jamesemery, per their request, the researcher has submitted test data that I will slack you the location of. They have also provided additional information that will interest you in the forum thread that is not represented below.

---
@shlee 
I uploaded the file to a fileshare folder of the University Mainz and send you a PM with the link and login data. 
One other small thing I found out is, that MDSpark does not take comma in filenames although I quoted the filepath. Is there any way to allow comma in filepath or do I have to avoid using them?

@mack812 
I tested MDSpark with an unsorted SAM file as input and you are right, it works and the output is a sorted BAM file. So I can skip the SortSam tool wich will save me about 15-20 min in processing time. So MDSpark in total is faster than SortSam+MD +Indexing. 
Thanks for that hint!

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/56337#Comment_56337

**Comment by droazen** [comment]
It seems like the problem was that the researcher was starting with a coordinate-sorted bam, whereas `MarkDuplicatesSpark` requires a name-sorted bam for good performance.

@jamesemery feel free to close once you're satisfied that this is resolved, and once we've made whatever additional documentation clarifications are warranted.

**Comment by sooheelee** [comment]
We are in the process of updating tool documentation at https://github.com/broadinstitute/gatk/pull/5672 to clarify this issue. Researchers in forum thread appear satisfied, so I will close this.
