### ISSUE TITLE
VariantEval Error if output file does not pre-exist

### ISSUE THREAD

**Issue by kloot** [broadinstitute/gatk#5674]
### Affected tool(s) or class(es)
_VariantEval, -O, --output_

### Affected version(s)
- [X] Latest public release version [4.1.0.0]
- [ ] Latest master branch as of [date of test?]

### Description 
Program starts then terminates with error:
`***********************************************************************`
`A USER ERROR has occurred: Couldn't read file file:///[.....]/X034.eval.grp. Error was: It doesn't exist.`
`***********************************************************************`

Note: The error is not thrown, and VariantEval completes successfully, if a zero-byte file with the name passed with the `-o` or `--output` arguments is created before executing VariantEval
For this example: `touch X034.eval.grp`

#### Steps to reproduce
Command line:
`gatk VariantEval -R $ref -L autosomes.list --eval W034.raw.annotated.vcf.gz --dbsnp dbsnp.vcf.gz -O X034.eval.grp`

#### Expected behavior
Expect the program to create its own output file (as other GATK tools do)

#### Actual behavior
Terminates with error (above)

----

**Comment by cmnbroad** [comment]
Yup, unfortunately out test framework always creates an output file first, so it dosn't catch this. Easy fix.
