### ISSUE TITLE
Remove historic HC difference between VCF and GVCF mode

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#5676]
The HaplotypeCaller has slightly different behavior between VCF and GVCF output in some cases, which means that the variants at the edges of the active region may not be called in both.  This is due to the following line:
https://github.com/broadinstitute/gatk/blob/89ea9e01225db5c9bbe262c888a0abb74509f94c/src/main/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyRegionTrimmer.java#L318

The behavior for VCF mode should be made to conform to GVCF mode by defining `callableRegion = originalRegion.trim(callableSpan, extendedSpan);`

Super easy fix, but will break a bunch of tests.

**Comment by ldgauthier** [comment]
It might be prudent to hold off on this until after #5532 so the test update is less painful.

**Comment by davidbenjamin** [comment]
Closed by #6358.
