### ISSUE TITLE
Is the Downsampled annotation still a real thing?

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#5678]
This `DS` annotation has been kicking around in the header for a long time, but I've never seen it in the wild.  It doesn't show up in any of our integration tests.  We only have the ability to add this annotation if the GenotypingEngine gets a non-null `Map<String, AlignmentContext> stratifiedContexts`, but that doesn't seem to be the case in *_any_* of our tests.  Maybe it's a holdover from UnifiedGenotyper?

@davidbenjamin have you seen cases where we `calculateGenotypes` with stratifiedContexts (or refContext or rawContext or likelihoods)?  Given that there's zero test coverage, how would you feel about ripping it out and seeing if anyone complains?

**Comment by davidbenjamin** [comment]
@ldgauthier I wasn't aware of the `DS` annotation.  `stratifiedContexts` is almost certainly a holdover from UG, but before you delete too much let's run it by @LeeTL1220.  I have a feeling that his `AnnotatePairOrientation` tool might do UG-style annotation.

**Comment by ldgauthier** [comment]
It's specifically annotation that's happening inside the GenotypingEngine (not the AnnotationEngine), so it's unlikely, but worth getting another +1 for deleting code.

**Comment by davidbenjamin** [comment]
Probably safe then.
