### ISSUE TITLE
Funcotator should error and stop when annotating a VCF that already contains funcotations.

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#5679]
Funcotator should not allow an already-funcotated file to be funcotated again.  This check should at least be made on the `VCFHeader`.

For extra thoroughness we should consider checking the `INFO` field of some `VariantContext` objects (the first 10?) to ensure there is no `FUNCOTATION` section.

**Comment by FrankFeng** [comment]
Is it possible to add an option, which can force to re-annotate or overwrite previous annotations? Sometimes we need to re-annotate a VCF with a newer version of Funcotator. Thanks!
