### ISSUE TITLE
Logger always issues warning

### ISSUE THREAD

**Issue by timmykuo** [broadinstitute/gatk#5692]
### Affected tool(s) or class(es)
SAMSequenceDictionary function in IndexUtils.java: https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/utils/IndexUtils.java

### Affected version(s)
- [x] Latest public release version [version?]
- [x] Latest master branch as of [date of test?]

### Description 
The SAMSequenceDictionary function always logs a warning when a file is passed in. Needs an if statement that validates whether or not the file is actually a sequence dictionary before logging the warning

#### Steps to reproduce
Run GATK's HaplotypeCaller with a --dbsnp option set, or just pass a sequence dictionary into the SAMSequenceDictionary function directly

#### Expected behavior
Should use the --dbsnp file that I pass in if valid, rather than log a warning and creating a separate sequence dictionary

#### Actual behavior
Logs a warning and instead tries to create a new sequence dictionary based on the index file it finds

**Comment by cmnbroad** [comment]
@timmykuo I assume you're referring to the `createSequenceDictionaryFromFeatureIndex` function, which only gets called when a feature file that contains no embedded sequence dictionary is used. It unconditionally issues a warning indicating that the dictionary is missing, and that the code will try to fall back and extract one from the file's associated index. So it looks correct to me.

If I've misinterpreted the ticket, please include the actual command that you used, along with the actual warning that is logged.
