### ISSUE TITLE
Understanding the implementation of the StrandOddsRatio

### ISSUE THREAD

**Issue by nh13** [broadinstitute/gatk#5700]
I am trying to understand the calculation of the [`StrandOddsRatio`](https://software.broadinstitute.org/gatk/documentation/tooldocs/4.1.0.0/org_broadinstitute_hellbender_tools_walkers_annotator_StrandOddsRatio.php).  The online documentation and javadoc for the [`StrandOddsRatio` class](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandOddsRatio.java#L40) shows it as:
```latex
$$ refRatio = \frac{max(X[0][0], X[0][1])}{min(X[0][0], X[0][1} $$
```

Nonetheless, my reading of [the code](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/StrandOddsRatio.java#L102) shows it as
```latex
$$ refRatio = \frac{min(X[0][0], X[0][1])}{max(X[0][0], X[0][1} $$
```
The code is:
```java
final double refRatio = min(t00, t01)/ max(t00, t01);
```

The docs say its max/min while the code does min/max.  The same is true for the docs and implementation of `altRatio`.  It looks like either a bug, or the docs need to be updated.

**Comment by nh13** [comment]
Related to https://github.com/broadinstitute/gatk/issues/5698

**Comment by ldgauthier** [comment]
That might have been me.  I'm a little dyslexic.

**Comment by nh13** [comment]
No worries.

**Comment by sooheelee** [comment]
@nh13, the next release should reflect SOR documentation updates from #5703.
