### ISSUE TITLE
InbreedingCoeff javadoc claims value is "phred-scaled p-value" but actual value is neither phred-scaled nor a p-value

### ISSUE THREAD

**Issue by tfenne** [broadinstitute/gatk#5712]
### Tool(s) or class(es) involved
`InbreedingCoeff` variant annotation

### Description 
The javadoc, and from there the generated website documentation, describes the value as being a phred-scaled p-value.  However, looking at the values produced and also the code it would appear to be the non-transformed value `1 - observed_hets / expected_hets`.

----

**Comment by davidbenjamin** [comment]
@tfenne You're quite right.
