### ISSUE TITLE
GATKHelpDoclet-based Doc Generation and Embedded Images?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#5713]
Hello - I have a separate project that uses GATK4, and recently implemented something based on GATKHelpDoclet to auto-generate HTML docs from our walkers.  As you probably know, in addition to annotated arguments, the comment block at the top of the walker is incorporated into the final HTML.  Does this code have any ability to embed images into the final HTML, and if so do you have an example being used anywhere in GATK?  I thought at one point I saw this capability, but I'm not seeing this in the docs or code.  For example, perhaps there is some substitution supported, like {img:foo.png}?  Thanks for any help.

**Comment by cmnbroad** [comment]
@bbimber There isn't anything built in specifically for images, but ultimately the process is built on top of javadoc, and there are various stackoverflow threads on how to embed html image tags in javadoc.

**Comment by bbimber** [comment]
OK, thanks.  Given my build step already copies stylesheet.css into the output directory (analogous to what GATK does), it seems like it would be easy enough to have other resources copied too, and linking to them should be pretty easy.
