### ISSUE TITLE
HaplotypeCallerSpark crashes:8 parallel GATk jobs (8 samples) using 5 Spark cpus on each in a node with 40 cpus

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#5717]
User Question: I'm trying to speed up the process of calling variants using SPARK. I have access to a slurm HPC cluster, so I guess it's not that straightforward to run GATK in a proper distributed master-slave architecture (if there is any tutorial on how to setup slurm jobs to use GATK Spark tools on multiple nodes I would appreciate it a lot). 
Therefore, I run GATK in local mode with some SPARK threads, eventually speeding up the process by parallelising the number of samples processed simultaneously with GNU parallel. But then, I'm having troubles because some samples crash due to SPARK errors. Perhaps you could send my logs to the developers ? I'm trying to run 8 parallel GATk jobs (8 samples) using 5 Spark cpus on each in a node with 40 cpus. 

Best,
Pedro

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/comment/56193#Comment_56193

**Comment by bhanugandham** [comment]
[gatk4_errorLines.log](https://github.com/broadinstitute/gatk/files/2901904/gatk4_errorLines.log)
[parallel.log](https://github.com/broadinstitute/gatk/files/2901906/parallel.log)
[hs_err_pid82632.log](https://github.com/broadinstitute/gatk/files/2901907/hs_err_pid82632.log)

Please find attached error logs presented by the user.

**Comment by bhanugandham** [comment]
@jamesemery @tomwhite @cmnbroad 
Based on our conversation during GATK4 office hrs looping you all in in this issue.

**Comment by droazen** [comment]
@tomwhite Can you please have a look?

**Comment by tomwhite** [comment]
A few comments:
* Spark job failures are usually memory related. What was the command run in this case?
* Running HaplotypeCallerSpark is memory and compute intensive and should really be done on a cluster such as a Google Cloud Dataproc cluster. There are some scripts to help with this process here: https://github.com/broadinstitute/gatk/tree/master/scripts/spark_eval. Even if you don't use the scripts, they have settings for tuning memory, workers etc, that might be helpful.
* MarkDuplicatesSpark can be run effectively on a single multi-core machine, so might be a good one to start with to get into Spark.
* Spark manages parallelism, so GNU parallel is not needed (and doesn't really work well with Spark).
