### ISSUE TITLE
DetermineGermlineContigPloidy --contig-ploidy-priors: HOW DO YOU GENERATE THE PRIOR PROBABILITIES?

### ISSUE THREAD

**Issue by dislek** [broadinstitute/gatk#5719]
### Instructions

The github issue tracker is for bug reports, feature requests, and API documentation requests. General questions about how to use the GATK, how to interpret the output, etc. should be asked on the [official support forum](http://gatkforums.broadinstitute.org/gatk).
- Search the existing github issues to see if your issue (or something similar) has already been reported.  If the issue already exists, you may comment there to inquire about the progress.
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request** (for tool/class javadoc only -- for forum docs please post there)
- Consider if your "issue" is better addressed on the GATK forum: http://gatkforums.broadinstitute.org/gatk  Post there if you have questions about expected tool behavior, output format, unexpected results, or generally any question that does not fit into the categories above
- Use a **concise** yet **descriptive** title
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate
- Delete the other template blocks and this header.

----

### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) or class(es) involved
_Tool/class name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) or class(es) involved
_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by dislek** [comment]
Hello, I am trying to use the DetermineGermlineContigPloidy function in the GATK/4.1.0.0 and am running into some issues. I am having trouble figuring out how to generate the file for the --contig-ploidy-priors parameter. There seems to be absolutely no documentation regarding this issue. Am i missing something?

**Comment by samuelklee** [comment]
Hi @dislek, this type of question might be more appropriate for the GATK forum (and has actually been previously asked there, see https://gatkforums.broadinstitute.org/gatk/discussion/12543/determinegermlinecontigploidy and the thread linked in the answer).

The priors file is a TSV that is described in the tool documentation for DetermineGermlineContigPloidy.  You should manually construct this TSV, with contig names appropriate to the reference being used and prior probabilities appropriate for the quality of your data set---probably the suggestions in the example in the tool documentation are a reasonable place to start.  However, you may want to validate the ploidy calls output by DetermineGermlineContigPloidy using samples where the truth is known to ensure that the model is trained correctly using your choice of priors and other model parameters.
