### ISSUE TITLE
Handle unmarked duplicates where mates have MQ = 0

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#5720]
PCR duplicates may not be marked if their mates all have mapping quality zero and are assigned to different places.  This causes false positives in Mutect2.

**Comment by jamesemery** [comment]
@davidbenjamin If you aren't aware there is a proposal to handle this case better in MarkDuplicates floating around in Picard. If you haven't already expressed your opinions it may be worth leaving a comment on the discussion https://github.com/broadinstitute/picard/issues/1285#issuecomment-466123736.

**Comment by davidbenjamin** [comment]
Thanks @jamesemery!

**Comment by davidbenjamin** [comment]
Closed by #5734.
