### ISSUE TITLE
DetermineContigPloidy BETA AssertionError CNV WDL 

### ISSUE THREAD

**Issue by lesleygray** [broadinstitute/gatk#5738]
### Affected tool(s) or class(es)
org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy 

### Affected version(s)
gatk-4.0.12.0

### Description 
Bug in DetermineGermlineContigPloidy

`org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException:
python exited with 1
Command Line: python /tmp/cohort_determine_ploidy_and_depth.8087328354193956874.py --sample_coverage_metadata=/tmp/samples-by-coverage-per-contig8923805021585472070.tsv --output_calls_path=cohort_output/normal_cohort-calls --mapping_error_rate=1.000000e-02 --psi_s_scale=1.000000e-04 --mean_bias_sd=1.000000e-02 --psi_j_scale=1.000000e-03 --learning_rate=5.000000e-02 --adamax_beta1=9.000000e-01 --adamax_beta2=9.990000e-01 --log_emission_samples_per_round=2000 --log_emission_sampling_rounds=100 --log_emission_sampling_median_rel_error=5.000000e-04 --max_advi_iter_first_epoch=1000 --max_advi_iter_subsequent_epochs=1000 --min_training_epochs=20 --max_training_epochs=100 --initial_temperature=2.000000e+00 --num_thermal_advi_iters=5000 --convergence_snr_averaging_window=5000 --convergence_snr_trigger_threshold=1.000000e-01 --convergence_snr_countdown_window=10 --max_calling_iters=1 --caller_update_convergence_threshold=1.000000e-03 --caller_internal_admixing_rate=7.500000e-01 --caller_external_admixing_rate=7.500000e-01 --disable_caller=false --disable_sampler=false --disable_annealing=false --interval_list=/tmp/intervals6028309209465756355.tsv --contig_ploidy_prior_table=contig_ploidy_priort_hg38.tsv `--output_model_path=cohort_output/normal_cohort-model`

`Stdout:`
`Stderr: Traceback (most recent call last):
  File "/tmp/cohort_determine_ploidy_and_depth.8087328354193956874.py", line 67, in <module>
    "--caller_update_convergence_threshold": 1e-3
  File "/home/grayl/.local/lib/python3.6/site-packages/gcnvkernel/tasks/inference_task_base.py", line 638, in expose_args  "arguments; possible choices are: {1}".format(override_default_arg, valid_args)
AssertionError: Initializer argument of which the default is to be overridden --num_thermal_advi_iters is not a valid initializer arguments; possible choices are: {'--track_model_params_every', '--learning_rate', '--disable_annealing', '--random_seed', '--adamax_beta2', '--convergence_snr_trigger_threshold', '--track_model_params', '--sampler_smoothing_window', '--param_tracker_config', '--caller_update_convergence_threshold', '--caller_summary_statistics_reducer', '--caller_admixing_rate', '--initial_temperature', '--self', '--convergence_snr_averaging_window', '--max_advi_iter_first_epoch', '--num_thermal_epochs', '--disable_sampler', '--min_training_epochs', '--max_calling_iters', '--max_advi_iter_subsequent_epochs', '--adamax_beta1', '--log_emission_sampling_median_rel_error', '--total_grad_norm_constraint', '--convergence_snr_countdown_window', '--log_emission_samples_per_round', '--max_training_epochs', '--log_emission_sampling_rounds', '--disable_caller', '--obj_n_mc'} at org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75) at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126) at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170) at org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:151)`

#### Steps to reproduce
`gatk DetermineGermlineContigPloidy --input 1_AH285.counts.hdf5 --input 2_AH287.counts.hdf5 --input 3_AH288.counts.hdf5 --input 4_AH290.counts.hdf5 --input 5_AH291.counts.hdf5 --input 6_AH292.counts.hdf5 --input 7_AH295.counts.hdf5 --input 8_AH296.counts.hdf5 --contig-ploidy-priors contig_ploidy_priort_hg38.tsv --output cohort_output --output-prefix normal_cohort`

#### Expected behavior
Should identify key for caller_update_convergence_threshold

#### Actual behavior
Script terminates with AssertionError

**Comment by samuelklee** [comment]
@lesleygray Perhaps I'm not understanding the issue---from the title, it sounds like you are trying to use the BETA version of the GATK jar/Docker with the 4.0.12.0 germline CNV WDL?  The jar/Docker and WDLs all need to be from the same version of GATK, as these are updated in lockstep.

It looks like the name of the argument that the warning is complaining about (`num_thermal_advi_iters`) was introduced in #4720 (and replaced `num_thermal_epochs`, which is present in your python invocation), so I'm guessing you might be using a version of the jar/Docker that is older than that?

If this is not the case, could you explain why you expected that `caller_update_convergence_threshold` be identified as the incorrect argument instead?

**Comment by samuelklee** [comment]
Going to go ahead and close this.  @lesleygray feel free to reopen if I did not accurately diagnose the issue above.
