### ISSUE TITLE
GenomicsDBImport error (VariantStorageManagerException exception : Error while syncing array to disk)

### ISSUE THREAD

**Issue by olavurmortensen** [broadinstitute/gatk#5740]
As discussed in #5608 with @nalinigans. 

## Software version

GATK v4.1.0.0-32-g213f99c-SNAPSHOT

## OS/Platform

```
$ uname -a
Linux hnpv-fargenCompute01 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

## Command 

```
TILEDB_DISABLE_FILE_LOCKING=1

gatk --java-options "-Xmx4g -Xms4g" GenomicsDBImport \
    -V [GVCF file] \
    -V [GVCF file]  \
    --genomicsdb-workspace-path data/genomicsdb/run1 \
    --tmp-dir=tmp \
    -L [target BED file]
```

## CIFS configuration

/etc/fstab:
```
/[servername]/[mountame] /mnt/[mountname] cifs credentials=/root/.smbcredentials,iocharset=utf8,uid=1004,gid=1005,file_mode=0770,dir_mode=0770,noperm,mfsymlinks 0 0
```

## Log

Using GATK wrapper script /mnt/fargen/experiments/joint_call/gatk_27-02-2019_213f99c/gatk/build/install/gatk/bin/gatk
Running:
    /mnt/fargen/experiments/joint_call/gatk_27-02-2019_213f99c/gatk/build/install/gatk/bin/gatk GenomicsDBImport -V data/gvcf/FN000009.g.vcf.gz -V old_data/FN000010.g.vcf.gz --genomicsdb-workspace-path data/genomicsdb/run1 --tmp-dir=tmp -L /mnt/fargen/resources/sureselect_human_all_exon_v6_utr_grch38/S07604624_Padded.bed
12:52:35.654 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/fargen/experiments/joint_call/gatk_27-02-2019_213f99c/gatk/build/install/gatk/lib/gkl-0.8.6.jar!/com/intel/gkl/native/libgkl_compression.so
12:52:37.520 INFO  GenomicsDBImport - ------------------------------------------------------------
12:52:37.521 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.1.0.0-32-g213f99c-SNAPSHOT
12:52:37.521 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
12:52:37.521 INFO  GenomicsDBImport - Executing as olavur@hnpv-fargenCompute01.heilsunet.fo on Linux v4.4.0-101-generic amd64
12:52:37.521 INFO  GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_191-8u191-b12-2ubuntu0.16.04.1-b12
12:52:37.522 INFO  GenomicsDBImport - Start Date/Time: 28 February 2019 12:52:35 WET
12:52:37.522 INFO  GenomicsDBImport - ------------------------------------------------------------
12:52:37.522 INFO  GenomicsDBImport - ------------------------------------------------------------
12:52:37.523 INFO  GenomicsDBImport - HTSJDK Version: 2.18.2
12:52:37.523 INFO  GenomicsDBImport - Picard Version: 2.18.25
12:52:37.523 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2
12:52:37.524 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
12:52:37.524 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
12:52:37.524 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
12:52:37.524 INFO  GenomicsDBImport - Deflater: IntelDeflater
12:52:37.524 INFO  GenomicsDBImport - Inflater: IntelInflater
12:52:37.524 INFO  GenomicsDBImport - GCS max retries/reopens: 20
12:52:37.524 INFO  GenomicsDBImport - Requester pays: disabled
12:52:37.524 INFO  GenomicsDBImport - Initializing engine
12:52:38.096 INFO  FeatureManager - Using codec BEDCodec to read file file:///mnt/fargen/resources/sureselect_human_all_exon_v6_utr_grch38/S07604624_Padded.bed
12:52:43.641 INFO  IntervalArgumentCollection - Processing 134492644 bp from intervals
12:52:43.720 WARN  GenomicsDBImport - A large number of intervals were specified. Using more than 100 intervals in a single import is not recommended and can cause performance to suffer. If GVCF data only exists within those intervals, performance can be improved by aggregating intervals with the merge-input-intervals argument.
12:52:43.722 INFO  GenomicsDBImport - Done initializing engine
12:52:44.113 INFO  GenomicsDBImport - Vid Map JSON file will be written to /mnt/fargen/experiments/joint_call/data/genomicsdb/run1/vidmap.json
12:52:44.113 INFO  GenomicsDBImport - Callset Map JSON file will be written to /mnt/fargen/experiments/joint_call/data/genomicsdb/run1/callset.json
12:52:44.114 INFO  GenomicsDBImport - Complete VCF Header will be written to /mnt/fargen/experiments/joint_call/data/genomicsdb/run1/vcfheader.vcf
12:52:44.114 INFO  GenomicsDBImport - Importing to array - /mnt/fargen/experiments/joint_call/data/genomicsdb/run1/genomicsdb_array
12:52:44.114 INFO  ProgressMeter - Starting traversal
12:52:44.115 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Batches Processed   Batches/Minute
13:03:44.100 INFO  GenomicsDBImport - Importing batch 1 with 2 samples
[TileDB::FileSystem] Error: (sync_path) Cannot sync file; File syncing error; path=/mnt/fargen/experiments/joint_call/data/genomicsdb/run1/chr1$11981$12351/.__cd28ac27-6a06-422f-a674-2acfbdb072d1140406632785664_1551359040166; errno=22(Invalid argument)
terminate called after throwing an instance of 'VariantStorageManagerException'
  what():  VariantStorageManagerException exception : Error while syncing array chr1$11981$12351 to disk
TileDB error message :

**Comment by cmnbroad** [comment]
This looks the same as https://github.com/broadinstitute/gatk/issues/5342.

**Comment by nalinigans** [comment]
Did you `export TILEDB_DISABLE_FILE_LOCKING=1` before invoking ./gatk? 

```
~/gatk: export TILEDB_DISABLE_FILE_LOCKING=1
~/gatk: echo $TILEDB_DISABLE_FILE_LOCKING
1
~/gatk: ./gatk GenomicsDBImport -V ~/vcfs/ALL.all_fixed.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.NA21144.vcf.gz --genomicsdb-workspace-path ws111 -L 1
```

**Comment by nalinigans** [comment]
@olavurmortensen, looks like TILEDB_DISABLE_FILE_LOCKING=1  did not get passed to the program. Did you use `export TILEDB_DISABLE_FILE_LOCKING=1` as the command to set the environment variable?
If yes, then please use the attached zip that contains a shared library with some tracing messages. 
[libgenomicsdb.zip](https://github.com/broadinstitute/gatk/files/2922767/libgenomicsdb.zip)
To use the zip, from a bash shell:

```
%: tar zxf libgenomicsdb.zip
%: export LD_LIBRARY_PATH=`pwd`:$LD_LIBRARYPATH
%: export TILEDB_DISABLE_FILE_LOCKING=1
%: gatk --java-options "-Xmx4g -Xms4g" GenomicsDBImport ...
```
Please attach the log if you still see the issue.

**Comment by olavurmortensen** [comment]
@nalinigans Yeah, I forgot "export". It works now, you can close the issue. Thank you.

**Comment by nalinigans** [comment]
Not an issue.
