### ISSUE TITLE
Handle spark exception wrapping

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#575]
Dataflow and spark both wrap thrown exceptions in their own exceptions before transmitting them back to the client.  Spark doesn't maintain the cause field for the new exception, which makes it difficult to unwrap and retrieve the original exception type.  

The ability to do this is important because we want to present error's differently to the user depending on if they have a known `UserException` or some other type of exception.  It also makes our testing much more robust if we can test for specific failure conditions rather than the error prone `RuntimeException`

**Comment by lbergelson** [comment]
#574 is a workaround for this issue for some tests, but should be properly fixed at some point.

**Comment by tomwhite** [comment]
From Spark 1.5.0 (which has not yet been released), it will be possible to retrieve the user exception (see  [SPARK-8625](https://issues.apache.org/jira/browse/SPARK-8625)), so we'll be able to fix this. The change needed is in `DataflowCommandLineProgramUnitTest`.

Note that we'll need to upgrade Spark Dataflow too, to include https://github.com/cloudera/spark-dataflow/issues/69.

**Comment by droazen** [comment]
This is important -- nothing is more infuriating than generic/cryptic error messages. Let's do it for alpha-1.

**Comment by droazen** [comment]
Depends on https://github.com/broadinstitute/gatk/issues/1406
