### ISSUE TITLE
Transition from pymc3/theano to new ML framework.

### ISSUE THREAD

**Issue by clsgithubusr** [broadinstitute/gatk#5766]
----

### Affected tool(s) or class(es)
- GATK
- gcnvkernel 
- theano

### Affected version(s)
- GATK 4.1.0.0
- gcnvkernel 0.0.7
- theano 0.9.0
- GCC 7.3.0

### Description 
I have installed the python package theano(which is a requirement of gcnvkernel)  with python 3.6.6 which is compiled with gcc 7.3.0. I am not using the conda environment to install these packages.
Then i tried to run theano-nose, but is giving me the following error:

```sh

$ theano-nose
--
 
You can find the C code in this temporary file: /tmp/theano_compilation_error_gp0ar1kx
library inux-gnu/7.3.0/crtbeginS.o: is not found.
library inux-gnu/7.3.0/crtbeginS.o: is not found.
library inux-gnu/7.3.0/crtbeginS.o(.text+0x1a): is not found.
library inux-gnu/7.3.0/crtbeginS.o(.text+0x6b): is not found.
Traceback (most recent call last):
File "${INSTALLDIRGATK}/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 81, in <module>
actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "${INSTALLDIRGATK}/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 105, in <module>
actual_version, force_compile, _need_reload))
ImportError: Version check of the existing lazylinker compiled file. Looking for version 0.211, but found None. Extra debug information: force_compile=False, _need_reload=True
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
File "${INSTALLDIRGATK}/bin/theano-nose", line 11, in <module>
load_entry_point('Theano==1.0.4', 'console_scripts', 'theano-nose')()
File "${INSTALLDIRGATK}/lib/python3.6/site-packages/bin/theano_nose.py", line 207, in main
result = main_function()
File "${INSTALLDIRGATK}/lib/python3.6/site-packages/bin/theano_nose.py", line 45, in main_function
from theano import config
File "${INSTALLDIRGATK}/lib/python3.6/site-packages/theano/__init__.py", line 110, in <module>
from theano.compile import (
File "${INSTALLDIRGATK}/lib/python3.6/site-packages/theano/compile/__init__.py", line 12, in <module>
from theano.compile.mode import *
File "${INSTALLDIRGATK}/lib/python3.6/site-packages/theano/compile/mode.py", line 11, in <module>
import theano.gof.vm
File "${INSTALLDIRGATK}/lib/python3.6/site-packages/theano/gof/vm.py", line 674, in <module>
from . import lazylinker_c
File "${INSTALLDIRGATK}/lib/python3.6/site-packages/theano/gof/lazylinker_c.py", line 140, in <module>
preargs=args)
File ${INSTALLDIRGATK}/lib/python3.6/site-packages/theano/gof/cmodule.py", line 2396, in compile_str
(status, compile_stderr.replace('\n', '. ')))
Exception: Compilation failed (return status=1): /usr/bin/ld.gold: error: ${INSTALLDIRGCC}/bin/../lib/gcc/x86_64-pc-linux-gnu/7.3.0/crtbeginS.o: unsupported reloc 42 against global symbol _ITM_deregisterTMCloneTable. /usr/bin/ld.gold: error: ${INSTALLDIRGCC}/bin/../lib/gcc/x86_64-pc-linux-gnu/7.3.0/crtbeginS.o: unsupported reloc 42 against global symbol _ITM_registerTMCloneTable. ${INSTALLDIRGCC}/bin/../lib/gcc/x86_64-pc-linux-gnu/7.3.0/crtbeginS.o(.text+0x1a): error: unsupported reloc 42. ${INSTALLDIRGCC}/bin/../lib/gcc/x86_64-pc-linux-gnu/7.3.0/crtbeginS.o(.text+0x6b): error: unsupported reloc 42. collect2: error: ld returned 1 exit status.


```

Then I have installed theano with python 3.6.6 which is compiled with gcc 5.4.0, and it was giving me no errors

```sh

$ theano-nose 

----------------------------------------------------------------------
Ran 0 tests in 0.012s

OK
```

The Theano toolchain issue might be caused by theano not being actively developed anymore. Probably they never tested it with newer toolchains.
See this message that is also on the Theano github page.
https://groups.google.com/d/msg/theano-users/7Poq8BZutbY/rNCIfvAEAwAJ

#### Steps to reproduce
see description

#### Expected behavior
see description

#### Actual behavior
see description

----

## Feature request
- Switch from pymc3/Theano to another framework that offers the same functionality
- Modify the depedencies of gcnvkernel

----

**Comment by samuelklee** [comment]
Thanks @clsgithubusr, we are well aware that Theano is no longer in development.  There are plans to move future model implementations to pyro (https://github.com/pyro-ppl/pyro) and some prototype models have already been developed in that framework.  As is stated in the post you linked, things move relatively quickly in the ML world!

Fortunately, Theano is a relatively mature and stable framework.  If you use the GATK conda environment you shouldn’t have any issues.  If not, I don’t think we can make any guarantees.

It was a major decision for us to introduce python ML frameworks into our codebase, but it was necessary to enable methods that can take advantage of all of the developments happening in the field of ML.  We understand that deployment may be more difficult as a result, but using conda and Docker should hopefully ease the burden significantly.

**Comment by samuelklee** [comment]
See also: https://medium.com/@pymc_devs/theano-tensorflow-and-the-future-of-pymc-6c9987bb19d5

**Comment by mwalker174** [comment]
Closing as a part of my issue clearing rampage, but let it be known Pyro is on the roadmap for future CNV models, and we are currently looking into updating PyMC3 to resolve some dependency issues with gCNV.
