### ISSUE TITLE
Use conda env create --force rather than conda env update in localDevCondaEnv task.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#5776]
@cmnbroad correct me if I'm wrong, but we currently just update the conda env if it is already present.  This will add new packages that were added to the yml but will not remove old packages that were removed from the yml.

Note that the update --prune option seems like it should take care of this, but see https://github.com/conda/conda/issues/7279.

**Comment by cmnbroad** [comment]
Yeah, `--force` is the right thing to do, and I added it to build.gradle a few months ago as part of https://github.com/broadinstitute/gatk/pull/5081, but that PR has languished because my original package validation was lame, and I never went back and resolved it.

**Comment by samuelklee** [comment]
OK, great that you already were aware of it!  We can probably resolve it during the upcoming round of python dependency updates.
