### ISSUE TITLE
Upgrade to Spark 2.4

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#5782]

**Comment by tomwhite** [comment]
We'll need to test on a cluster as a part of this work.

One benefit will be that Spark 2.4.1 will allow us to run tests using Java 11. See https://github.com/disq-bio/disq/pull/88. (Even though it looks like Spark won't support Java 11 until Spark 3, according to https://issues.apache.org/jira/browse/SPARK-24417, Spark 2.4.1 will allow us to at least run tests using Java 11.)

There are also fixes for #1524 and #3840.
