### ISSUE TITLE
Genomics DB Import From CSV

### ISSUE THREAD

**Issue by mfawzysami** [broadinstitute/gatk#5830]
I have a CSV file that i have formulated myself as CSV file containing the following columns per line 

1,10583,10583,0|0,0|0,,
2,10611,10611,0|0,0|0,,
3,13302,13302,0|0,0|0,,
4,13327,13327,0|0,0|0,,
5,13957,13957,0|0,0|0,,
6,13980,13980,0|0,0|0,,
7,30923,30923,0|0,0|0,,
8,46402,46402,0|0,0|0,,
9,47190,47190,0|0,0|0,,
10,51476,51476,0|1,0|1,,

What could be the possible callsets and vid_mapping file to successfully run vcf2tiledb to successfully import it into genomicsdb

**Comment by ldgauthier** [comment]
Github issues are for bugs, feature requests, and documentation requests.  For tool support please see https://gatkforums.broadinstitute.org/gatk/
