### ISSUE TITLE
Do we need to implement baseRecalibration before creating Panel of Normal?

### ISSUE THREAD

**Issue by sjin09** [broadinstitute/gatk#5836]
Dear @sooheelee 

I am wondering if I need to perform base recalibration on the normal bam files before I proceed with creating the panel of normals, which will then be used for somatic mutation calling with MuTect2. 

The tutorial (https://software.broadinstitute.org/gatk/documentation/article?id=11136) and the documentation (https://software.broadinstitute.org/gatk/documentation/article?id=11127) suggest to me that baseRecalibration is not required, but I wanted to confirm before proceeding with the pipeline.

Regards,
Sangjin Lee

**Comment by ldgauthier** [comment]
Github issues are for bug reports, feature requests, and documentation requests.  For tool support please use the GATK forum: https://gatkforums.broadinstitute.org/gatk/
