### ISSUE TITLE
ValidateVariants silently does no validation in use common cases

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#5862]
There are several cases where ValidateVariants does no actual validation, and issues no warning message. This includes the default case, where the minimal set of required args is provided (these are examples from the doc, which should be updated when this is fixed): 

`gatk ValidateVariants -V some.vcf`
`gatk ValidateVariants -V some.vcf -R some.fasta`

Either of these silently results in no validation and no warning message, despite the entire VCF being decoded and traversed, because the default validation type is "ALL", which includes validation type "IDS". But IDS requires a dbsnp arg, and none was provided, so the code short-circuits out. The default case should probably do whatever validation it can, but at a minimum a warning should be logged. Ironically, if you provide an exclusion on the command line via `--validation-type-to-exclude IDS`, then validation is done.

Another no-op case is `--validation-type-to-exclude ALL` (also recommended in the doc), which also should probably be rejected, or at least logged, since it silently does no validation and reports no errors. This tripped up [this user](https://github.com/samtools/htsjdk/issues/1117), and resulted in a downstream BCF issue.

**Comment by jonn-smith** [comment]
When we test this, we should make sure it flags `AD` when there is only 1 field in there.

**Comment by samuelklee** [comment]
Not sure if this is related to https://github.com/broadinstitute/gatk/issues/4642, but might be good to look into that as well!

**Comment by jonn-smith** [comment]
I'm guessing that they are related (given the description @cmnbroad gave of #4642)

**Comment by cmnbroad** [comment]
Yup, its another variation of the same issue.

**Comment by jonn-smith** [comment]
I recommend we error out when provided with `--validation-type-to-exclude ALL`.  It doesn't make sense - why call the validator if you're not going to validate?

**Comment by cmnbroad** [comment]
I didn't realize before that there is no "include" (opt-in) validation type arg, only "exclude". So I'm not sure what the purpose of having "ALL" is in the first place, if the only thing you can usefully do with it is exclude it.

I think the best longer term fix would be to add an "--validation-type-to-include" arg, and have it default to the everything except for IDs, and then construct the actual types based on merging include/exclude args. But thats a bigger change then just fixing the current (silent do-nothing) default behavior, and requires more error checking for conflicting args.

Lets start with changing it so that when `--validation-type-to-exclude ALL` is provided, we log a warning message saying that IDs will be left out since no IDS were provided, and proceed with the remaining validations. Then if we want to get more ambitious we can talk about making the bigger change.

Also, as part of the initial fix, it might be a good idea to change `calculateValidationTypesToApply` so that it doesn't modify the `excludeTypes` list directly, since this is the list provided by the user, and instead uses it's own temporary list.

**Comment by cmnbroad** [comment]
And [one more instance](https://gatkforums.broadinstitute.org/gatk/discussion/24085/selectvariants-java-lang-illegalstateexception-allele-in-genotype-not-in-the-variant-context) of a user hitting this.

**Comment by jamesemery** [comment]
Closed Via #5984
