### ISSUE TITLE
Rename ValidateBasicSomaticShortMutations to something more in-line with MutationValidator

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#5871]
### Tool(s) or class(es) involved
ValidateBasicSomaticShortMutations 

### Description
It turns out that this tool is doing a subset of the CGA tool, MutationValidator.  Originally, the understanding (by both DSP and CGA) was the the GATK tool was doing a different algorithm, but this turned out to be incorrect.  We should rename the GATK tool perhaps to SomaticShortMutationValidator and cite MutationValidator.

Any relevant WDL should be updated to prevent unnecessary workflow failures.

@davidbenjamin 

(citation does not exist as per last offline meeting with CGA)

**Comment by davidbenjamin** [comment]
This is not necessary.
