### ISSUE TITLE
Get example code for using the built-in prefetching in the google-cloud-nio library

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#5882]
GATK still uses its own prefetching code for NIO, but the `google-cloud-nio` library now has this capability built in. @jean-philippe-martin could you please provide us with some example code of how one can turn on the built-in prefetcher? This is requested by @yfarjoun for Picard, but will also be helpful for GATK when we migrate to the built-in prefetcher.

**Comment by jean-philippe-martin** [comment]
Old code:
```Java
import org.broadinstitute.hellbender.utils.nio.SeekableByteChannelPrefetcher;
// ...
SeekableByteChannel input = ...
if (enablePrefetcher) {
  input = SeekableByteChannelPrefetcher.addPrefetcher(cloudPrefetchBuffer, input)
}
```

New code:
```Java
import com.google.cloud.storage.contrib.nio.SeekableByteChannelPrefetcher;
// ...
SeekableByteChannel input = ...
if (enablePrefetcher) {
  input = SeekableByteChannelPrefetcher.addPrefetcher(cloudPrefetchBuffer, input)
}
```

Also, the new one throws `IOException` whereas the GATK one throws `GATKException`. Other than that, they should be the same and you just need to change the import line.

**Comment by droazen** [comment]
@jean-philippe-martin Thanks -- is there some way to enable prefetching globally, so that it doesn't have to be manually added to each channel by client code?

**Comment by jean-philippe-martin** [comment]
Not in general, because prefetching isn't always desirable. By its nature it's designed for long sequential reads rather than random accesses.

In GATK though there is prefetcher code in a FeatureDataSource constructor, so anyone who uses that one will get the prefetching.

**Comment by droazen** [comment]
@yfarjoun We should sit down at some point to discuss the best way to activate the prefetching in Picard. It may be a little less trivial than I had thought based on the above, but should still be fairly simple.

**Comment by yfarjoun** [comment]
but for fingerprinting it seems that since it is effectively random-access,
perhaps prefetching will not be worth it?

**Comment by droazen** [comment]
@yfarjoun Well, as I said in person I believe that there are benefits to running with asynchronous prefetching turned on even in the random-access case. @jean-philippe-martin can confirm.

**Comment by jean-philippe-martin** [comment]
It's true that our measurements have shown some improvement even in a random access case. Surely we should be able to fabricate a more extreme case where prefetching doesn't help, so it still makes sense to offer a choice.

**Comment by jean-philippe-martin** [comment]
Example has been provided, closing this issue.
