### ISSUE TITLE
Option to restrict fragment length for calling CNVs

### ISSUE THREAD

**Issue by jnktsj** [broadinstitute/gatk#5884]
Hi GATK team!
I would like a minimum fragment length filter during calling CNVs (the CountReads step) if possible.  @LeeTL1220 helped me to find an option to set a maximum fragment length with `--read_filter  FragmentLength --maxFragmentLength <value>` ([link to the GATK forum page](https://gatkforums.broadinstitute.org/gatk/discussion/2338/how-can-i-invoke-read-filters-and-their-arguments)). However, it appears there is no minimum fragment length filter implemented.  Would it be possible to include the min fragment filter option in the future release or as a pre-release version?

The reason of asking this filter is:

there are shorter fragments in a FFPE tumor PCR-free WGS (top) compared to the PCR-plus WGS (bottom) from the same individual:
![image](https://user-images.githubusercontent.com/5141643/56065278-611c9a80-5d42-11e9-8b60-b82ea1d69e87.png)
and I observed higher MAD values in the PCR-free samples.  I would like to see whether the results improve after discarding the shorter fragments in the FFPE PCR-free WGS.
![image](https://user-images.githubusercontent.com/5141643/56065600-50b8ef80-5d43-11e9-9160-fb0beb5c11de.png)

**Comment by samuelklee** [comment]
@jnktsj can you let us know what you find?  Also, just checking---are you using separate PoNs for the PCR-Free and PCR-Plus samples?  And are both samples FFPE, or just the tumor?

**Comment by jnktsj** [comment]
@samuelklee We used the same PoN composed of 15 PCR-free normals (30x).  The tumor-normal pairs analyzed for the CNVs are FFPE tumors and blood normals.

I am still investing what is causing the larger noise in PCR-free CNV calls, but I suspect it might be due to the shorter fragments in the PCR-free tumor samples.  I will let you know the details after checking the genomic bins that have higher noise.
