### ISSUE TITLE
Update the M2 WDL readme with Funcotator instead of Oncotator

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#5889]
### Tool(s) or class(es) involved
Readme for M2 in https://github.com/broadinstitute/gatk/tree/master/scripts/mutect2_wdl

### Description 
This is the text currently in the readme, it needs to be updated to feature Funcotator instead of Oncotator:

> Functional annotation (Oncotator)
> 
> The M2 WDL can optionally run oncotator for functional annotation and produce a TCGA MAF from the M2 VCF. Oncotator is not a GATK4 tool and is provided in the M2 WDL as a convenience. There are several notes and caveats
> 
> Several parameters should be passed in to populate the TCGA MAF metadata fields. Default values are provided, though we recommend that you specify the values. These parameters are ignored if you do not run oncotator.
> 
> Several fields in a TCGA MAF cannot be generated by M2 and oncotator, such as all fields relating to validation alleles. These will need to be populated by a downstream process created by the user.
> 
> Oncotator does not enforce the TCGA MAF controlled vocabulary, since it is often too restrictive for general use. This is up to the user to specify correctly. Therefore, we cannot guarantee that a TCGA MAF generated here will pass the TCGA Validator. If you are unsure about the ramifications of this statement, then it probably does not concern you.
> 
> More information about Oncotator can be found at: http://archive.broadinstitute.org/cancer/cga/oncotator

**Comment by vdauwera** [comment]
Or maybe I'm confused and the user can get either/or, based on the wdl? It wasn't very clear either way.

**Comment by davidbenjamin** [comment]
@vdauwera I didn't even know that README existed.  It's horribly out of date in a lot of ways.  @LeeTL1220 Before I spend time fixing it, is there any way I could drastically shrink this file, like to 3 lines or so, or delete it entirely?  I mean, most of it is redundant if you just read the WDL, and I really don't want to add maintenance of this README on top of Terra and the two official M2 wdls we still have to drag around.

**Comment by vdauwera** [comment]
I agree a lot of the detailed content is redundant and not worth maintaining in separate places. Reducing to 2 or 3 lines seems a bit too drastic though -- I would love to see something like a half-page high-level overview to serve as cliff notes for the WDL.

**Comment by jonn-smith** [comment]
I have a blurb I can add that should be mostly sufficient.
