### ISSUE TITLE
test Hellbender on CRAM

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#590]
GATK4 needs to work on cram files. We need to add tests to check that we can process CRAM files and get results equivalent to BAM

At the minimum, this needs to cover adding tests for:
- [x] MarkDuplicates
- [x] BQSR
- [x] PrintReads
- [x] CountReads 
- [x] CountBases
- [x] MeanQualityByCycle
- [x] QualityScoreDistribution
- [ ] CalculateHsMetrics
- [ ] CollectGCBiasMetrics
- [x] CollectBaseDistributionByCycle
- [x] CollectQualityYieldMetrics
- [x] CollectInsertSizeMetrics
- [x] CollectAlignmentSummaryMetrics
- [ ] all picard tools in the sam package

Ideally also unit/integration tests for :
- [ ] HaplotypeCaller
- [ ] CNV coverage collection

(Make sure to use non-lossy settings when converting our BAMs to CRAM)

**Comment by droazen** [comment]
These can be exact copies of existing tests, but with CRAM instead of BAM

**Comment by droazen** [comment]
Will need to figure out how to convert BAM -> CRAM in order to do this.

**Comment by akiezun** [comment]
maybe use https://github.com/enasequence/cramtools/tree/cram3

**Comment by droazen** [comment]
For information on when CRAM is lossless vs. lossy, see http://samtools.github.io/hts-specs/CRAMv3.pdf

**Comment by droazen** [comment]
Probably best to wait until .crai support trickles in to hellbender during the next rev of htsjdk.

**Comment by akiezun** [comment]
@droazen is crai support in htsjdk yet? If yes, let's revup and keep moving on this

**Comment by cmnbroad** [comment]
The PR with the fixes we need for .crai indexes to work was just merged in to htsjdk yesterday.

**Comment by droazen** [comment]
We need to either wait for the next htsjdk release or switch to a SNAPSHOT version of htsjdk temporarily to get the fixes.

**Comment by akiezun** [comment]
its ok to wait. can we nudge the release a bit?

**Comment by droazen** [comment]
@cmnbroad Can this be closed as resolved? Are all the remaining issues with CRAM tests (like disabled tests) captured in separate tickets?

**Comment by cmnbroad** [comment]
Yes, closing via #1084
