### ISSUE TITLE
value of  USE_CACHED_READ_INDEL_INFORMATIVENESS_VALUES changes the result

### ISSUE THREAD

**Issue by mehrzads** [broadinstitute/gatk#5908]
### Affected tool(s) or class(es)
Haplotypecaller

### Affected version(s)
4.1.1 or later

### Description 
if you look at haplotypecaller.java::callRegion(), you will see these lines:
```
if (trimmingResult.hasLeftFlankingRegion()) {
                    result.addAll(referenceModelForNoVariation(trimmingResult.nonVariantLeftFlankRegion(), false, VCpriors));
                }
                // output variant containing region.
                result.addAll(referenceConfidenceModel.calculateRefConfidence(assemblyResult.getReferenceHaplotype(),
                        calledHaplotypes.getCalledHaplotypes(), assemblyResult.getPaddedReferenceLoc(), regionForGenotyping,
                        readLikelihoods, genotypingEngine.getPloidyModel(), calledHaplotypes.getCalls(), hcArgs.standardArgs.genotypeArgs.supportVariants != null,
                        VCpriors));
                // output right-flanking non-variant section:
                if (trimmingResult.hasRightFlankingRegion()) {
                    result.addAll(referenceModelForNoVariation(trimmingResult.nonVariantRightFlankRegion(), false, VCpriors));
                }

```
We trim the region left and right and calculate the Reference confidence. The problem is when we call calculateRefConfidence , we might trim reads for the left region and calculate TransientAttributes and put them in the cache. Next time, when we call  calculateRefConfidence, we trim the reads for the right region but we still look at the cache which is prepopulated with data for the left region and we use the same data which might result in the wrong output. 

if you turn USE_CACHED_READ_INDEL_INFORMATIVENESS_VALUES off, you might get different results which I do not think is the expected outcome.

Let me know if you want more information. Thank you.

**Comment by jamesemery** [comment]
@mehrzads Thank you for posting about this issue. Have you been able to demonstrate different ref-confidence calls in active regions as a result of changing USE_CACHED_READ_INDEL_INFORMATIVENESS_VALUES? It would be simple enough to add a defensive check to ensure the reads have their transient fields purged between calls to the ReferenceConfidenceModel to be absolutely sure there is no issue.

**Comment by jamesemery** [comment]
I just ran a preliminary test and it appears that the transient attribute field is getting purged between `if (trimmingResult.hasLeftFlankingRegion())` and `if (trimmingResult.hasRightFlankingRegion())` `ReferenceConfidenceModel` calls. That means this should be a safe operation but would rather be sure and necessarily clean the attribute fields for an added layer of protection.

**Comment by mehrzads** [comment]
Thank you James for your great work. Yes I have a sample that it seems to generate different results based on USE_CACHED_READ_INDEL_INFORMATIVENESS_VALUES. I think explicitly cleaning it will definitely solve the problem.
