### ISSUE TITLE
add unit tests for MarkDuplicatesSpark

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#591]
we need tests like those in `AbstractMarkDuplicatesCommandLineProgramTest` to run on Spark (this is required because the duplicate-detection logic is reimplemented on Spark and based on uniqueness of generated keys).

Also `MarkDuplicatesTest` and probably `OpticalDuplicateFinderTest`

**Comment by droazen** [comment]
Since @davidadamsphd has his hands full with getting the end-to-end large-scale validation tests for spark tools into a runnable state, I'm re-assigning this to @akiezun. @akiezun feel free to move this to beta if you don't think it's necessary for alpha -- if you have time, though, and run out of tickets, it might be a good use of time.

**Comment by davidadamsphd** [comment]
If @akiezun is going to pick this up, he should start from where I left off. If it gets bumped to Beta, I'd be happy to keep it in my queue.

**Comment by droazen** [comment]
Sounds good -- @akiezun if you run out of other tickets and decide to do this one for alpha, make sure to sync with @davidadamsphd on what has already been done here. If you decide to bump this one to beta instead, assign it back to @davidadamsphd

**Comment by akiezun** [comment]
@davidadamsphd what remains to be done here? I have fixes for all three cases in https://github.com/broadinstitute/gatk/issues/1042 (see issues referred from there). Assigning to @davidadamsphd for clarification

**Comment by akiezun** [comment]
@davidadamsphd ping

**Comment by droazen** [comment]
@akiezun Can you assess whether we have enough unit tests for MarkDuplicatesSpark at this point?

**Comment by akiezun** [comment]
yes, i think we do. All tests from MarkDuplicates are now run on spark (once https://github.com/broadinstitute/gatk/issues/1042 is fixed)
