### ISSUE TITLE
Extract GenotypeGVCFs engine into publicly accessible class/function

### ISSUE THREAD

**Issue by wrighth-omics** [broadinstitute/gatk#5910]
## Feature request

Make joint genotyping functionality available as a publicly accessible function to another class/program without passing through the GATK command line interface

### Tool(s) or class(es) involved
VariantContext
GenotypeGVCFs
Underlying engine classes

### Description
For various use cases where our pipelines produce in-memory VariantContext objects it would be faster and easier to pass these directly to a joint genotyping function and extract the results back into memory rather than writing to VCF, running the GenotypeGVCFs pipeline via the command line interface and then re-ingesting the resultant VCFs. From discussions during the GATK Working Group meetings it appears this request is similar in principle to existing functionality for the HaplotypeCaller that was implemented by "extracting the engine" from the HaplotypeCaller walkers so that it can be instantiated outside the command line utility.

Ideally, this implementation should make it possible to instantiate any necessary engine classes pass VariantContext objects directly to the GenotypeGVCFs.apply or GenotypeGVCFs.regenotypeVC and receive the re-genotyped VariantContext objects back for further processing from Java code.  

----

**Comment by jamesemery** [comment]
As an addendum to this task, we would also want to improve the test coverage to the underlying methods by hitting the newly exposed API.

**Comment by jamesemery** [comment]
This has been resolved via #6004
