### ISSUE TITLE
Annotation warnings should include info about their source

### ISSUE THREAD

**Issue by aushev** [broadinstitute/gatk#5912]
### HaplotypeCaller
When running HaplotypeCaller, I get tens of thousands of lines like the following:
```
13:02:04.113 WARN  DepthPerSampleHC - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
13:02:04.113 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
13:02:04.113 WARN  DepthPerSampleHC - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
13:02:04.113 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
```
The problem is they are not informative: you can't tell what position/region caused them. Resulting repetitive messages are redundant.

**Comment by lbergelson** [comment]
Hmn, those messages are supposed to only be produced once... something is wrong there.  It's not a super high priority but we'll try to look into it.

**Comment by gubrins** [comment]
Heys, I would like to know what happened with this, because I get the same problem.

**Comment by tfenne** [comment]
I would also really appreciate it if these log messages contained the locus/position that generated the warning.

**Comment by droazen** [comment]
@tfenne @gubrins @pkaleta @aushev I've opened a PR to improve these log messages here: https://github.com/broadinstitute/gatk/pull/6892

**Comment by tfenne** [comment]
Thanks @droazen & @ldgauthier !

**Comment by cheche0717** [comment]
hello , I met the same problem! I am a fresh . So I don't understand what above metioned .  I would like to know what happened with this . Looking forward everybody's reply ! Thanks very much!!!

Here is my command 

`gatk HaplotypeCaller -R /home/variation/202011/input/NCTC11134/fasta/N.far_NCTC11134.fa  --emit-ref-confidence GVCF -I CD142.sorted.markdup.bam -O CD142.g.vcf`

here is reported error : 
`16:06:46.622 WARN  DepthPerSampleHC - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null


16:06:46.623 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null

16:06:46.623 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null

16:06:46.623 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null

16:06:46.624 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null

16:06:46.624 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null

16:06:46.624 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null


16:06:50.918 INFO  ProgressMeter - NZ_LN868938.1:634261              3.5                  4090           1182.7

16:07:01.275 INFO  ProgressMeter - NZ_LN868938.1:659185              3.6                  4290           1181.6`

Could you help me ! I really need your help ! And I appreciate it specially!

**Comment by cheche0717** [comment]
> Thanks @droazen & @ldgauthier !

Could you help me with the same problem ? Thank you very much ! I would like to know what happened with this and how i do next step . i am a fresh .

**Comment by ldgauthier** [comment]
@cheche0717 there hasn't been a release since the warnings were updated, but you can build a new jar yourself off of the master branch in the github repository or use the nightly Docker: https://hub.docker.com/r/broadinstitute/gatk-nightly

**Comment by droazen** [comment]
Reopening since https://github.com/broadinstitute/gatk/pull/6891 is not yet merged
