### ISSUE TITLE
Fix SamFileValidator so that it doesn't incorrectly flag valid reads 

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#592]
`SamFileValidator`'s `isValid()` flags certain reads as being errors when they should not be.  This happens when a read that has flag 0x1 ( read has a mate) set to false has flags 0x2, 0x8, 0x20, 0x40 or 0x80 set to true.  

According to sam spec, if flag 0x1 is unset than those fields are uninterpretable and should be ignored.

This was identified in #569

**Comment by nenewell** [comment]
I will do this.

**Comment by nenewell** [comment]
To do this, I need to modify SamRecord.IsValid() in htsjdk.samtools. Should I submit this issue to htsjdk? Thank you.

**Comment by lbergelson** [comment]
Ah, sorry, I didn't look into where the actual code came from.  If it needs to be updated in htsjdk then it should be updated there.

**Comment by akiezun** [comment]
@lbergelson can you open a ticket in htsjdk (in addition or as a replacement of ) this one?

**Comment by droazen** [comment]
Closing
