### ISSUE TITLE
Missing allele-specific annotation data should be represented with "." instead of "nul"

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#5940]
For allele-specific ranksums, an allele may not have a rank sum value if it didn't have any hets.  Right now this is output as "nul", but should use the VCF . for missing. 

This will a pretty noticeable change with respect to older versions, though we never condone using different versions together in the same pipeline.

**Comment by droazen** [comment]
@ldgauthier I think you did this one, right? Can it be closed?

**Comment by ldgauthier** [comment]
Yes!  Closed via #6079
