### ISSUE TITLE
INFO  CombineGVCFs - Shutting down engine

### ISSUE THREAD

**Issue by jingydz** [broadinstitute/gatk#5947]
Hi,
This is a part of my script and I get the mistakes after I run it:
for sample in $samples ; do 
    sample_gvcfs=${sample_gvcfs}" --variant /data/users/zhanglei/species/Medicago/result/${sample}.HC.g.vcf.gz "
done
time gatk CombineGVCFs \
     -R /data/users/zhanglei/species/Medicago/Medicago.fa \
     ${sample_gvcfs} \
     -O $outdir/population/${outname}.HC.g.vcf.gz && echo "** ${outname}.HC.g.vcf.gz done **" &&

18:08:13.704 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/software/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
18:08:13.872 INFO  CombineGVCFs - ------------------------------------------------------------
18:08:13.873 INFO  CombineGVCFs - The Genome Analysis Toolkit (GATK) v4.0.3.0
18:08:13.873 INFO  CombineGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
18:08:13.873 INFO  CombineGVCFs - Executing as zhanglei@GenEngine on Linux v3.10.0-327.el7.x86_64 amd64
18:08:13.873 INFO  CombineGVCFs - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_201-b09
18:08:13.874 INFO  CombineGVCFs - Start Date/Time: May 18, 2019 6:08:13 PM CST
18:08:13.874 INFO  CombineGVCFs - ------------------------------------------------------------
18:08:13.874 INFO  CombineGVCFs - ------------------------------------------------------------
18:08:13.874 INFO  CombineGVCFs - HTSJDK Version: 2.14.3
18:08:13.874 INFO  CombineGVCFs - Picard Version: 2.17.2
18:08:13.874 INFO  CombineGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
18:08:13.875 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
18:08:13.875 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
18:08:13.875 INFO  CombineGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
18:08:13.875 INFO  CombineGVCFs - Deflater: IntelDeflater
18:08:13.875 INFO  CombineGVCFs - Inflater: IntelInflater
18:08:13.875 INFO  CombineGVCFs - GCS max retries/reopens: 20
18:08:13.875 INFO  CombineGVCFs - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
18:08:13.875 INFO  CombineGVCFs - Initializing engine
18:08:14.718 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340092.HC.g.vcf.gz
18:08:14.807 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340093.HC.g.vcf.gz
18:08:14.852 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340094.HC.g.vcf.gz
18:08:14.897 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340095.HC.g.vcf.gz
18:08:14.958 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340096.HC.g.vcf.gz
18:08:15.003 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340097.HC.g.vcf.gz
18:08:15.044 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340098.HC.g.vcf.gz
18:08:15.098 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340099.HC.g.vcf.gz
18:08:15.142 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340100.HC.g.vcf.gz
18:08:15.183 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340101.HC.g.vcf.gz
18:08:15.217 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340102.HC.g.vcf.gz
18:08:15.250 INFO  FeatureManager - Using codec VCFCodec to read file file:///data/users/zhanglei/species/Medicago/result/SRR340103.HC.g.vcf.gz
18:08:15.277 INFO  CombineGVCFs - Shutting down engine
[May 18, 2019 6:08:15 PM CST] org.broadinstitute.hellbender.tools.walkers.CombineGVCFs done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=2372403200
java.lang.IllegalArgumentException: Feature inputs must be unique: /data/users/zhanglei/species/Medicago/result/SRR340103.HC.g.vcf.gz
	at org.broadinstitute.hellbender.engine.MultiVariantWalker.lambda$initializeDrivingVariants$0(MultiVariantWalker.java:60)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.broadinstitute.hellbender.engine.MultiVariantWalker.initializeDrivingVariants(MultiVariantWalker.java:56)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.initializeFeatures(VariantWalkerBase.java:47)
	at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:558)
	at org.broadinstitute.hellbender.engine.MultiVariantWalker.onStartup(MultiVariantWalker.java:48)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:132)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /home/software/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/software/gatk-4.0.3.0/gatk-package-4.0.3.0-local.jar CombineGVCFs -R /data/users/zhanglei/species/Medicago/Medicago.fa --variant /data/users/zhanglei/species/Medicago/result/SRR340092.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340093.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340094.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340095.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340096.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340097.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340098.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340099.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340100.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340101.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340102.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340103.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340103.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340104.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340105.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340106.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340107.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340108.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340109.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340110.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/SRR340111.HC.g.vcf.gz -O /data/users/zhanglei/species/Medicago/result/population/result.HC.g.vcf.gz

**Comment by cmnbroad** [comment]
@jingydz The error message
`Feature inputs must be unique: /data/users/zhanglei/species/Medicago/result/SRR340103.HC.g.vcf.gz`  says exactly what the problem is, which is that you have a duplicate input:

/data/users/zhanglei/species/Medicago/result/SRR340102.HC.g.vcf.gz --variant /data/users/zhanglei/species/Medicago/result/**SRR340103.HC.g.vcf.gz** --variant /data/users/zhanglei/species/Medicago/result/**SRR340103.HC.g.vcf.gz** --variant /data/users/zhanglei/species/Medicago/result/SRR340104.HC.g.vcf.gz --variant

**Comment by lbergelson** [comment]
That seems like it should be a UserException instead of IllegalArgument?

**Comment by jingydz** [comment]
😂😂😂In fact, it is true that I wrote SRR340103 twice, which is wrong.

**Comment by cmnbroad** [comment]
Yeah, good point.

**Comment by shashank-bgp** [comment]
Hi,
I am trying to generate vcf using GATK pipeline from bam file, but everytime, I am getting the following exception:
01:13:15.801 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/data1/ngs/programs/gatk-4.0.0.0/gatk-package-4.0.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
01:13:16.075 INFO  HaplotypeCaller - ------------------------------------------------------------
01:13:16.075 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.0.0.0
01:13:16.075 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
01:13:16.076 INFO  HaplotypeCaller - Executing as shashank@grande on Linux v3.13.0-79-generic amd64
01:13:16.076 INFO  HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_72-internal-b15
01:13:16.076 INFO  HaplotypeCaller - Start Date/Time: January 18, 2020 1:13:15 AM IST
01:13:16.076 INFO  HaplotypeCaller - ------------------------------------------------------------
01:13:16.076 INFO  HaplotypeCaller - ------------------------------------------------------------
01:13:16.077 INFO  HaplotypeCaller - HTSJDK Version: 2.13.2
01:13:16.077 INFO  HaplotypeCaller - Picard Version: 2.17.2
01:13:16.077 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 1
01:13:16.078 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
01:13:16.078 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
01:13:16.078 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
01:13:16.078 INFO  HaplotypeCaller - Deflater: IntelDeflater
01:13:16.078 INFO  HaplotypeCaller - Inflater: IntelInflater
01:13:16.078 INFO  HaplotypeCaller - GCS max retries/reopens: 20
01:13:16.078 INFO  HaplotypeCaller - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes
01:13:16.078 INFO  HaplotypeCaller - Initializing engine
01:13:17.087 INFO  HaplotypeCaller - Shutting down engine
[January 18, 2020 1:13:17 AM IST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=2216689664
java.lang.NullPointerException
	at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.getContigNames(SequenceDictionaryUtils.java:463)
	at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.getCommonContigsByName(SequenceDictionaryUtils.java:457)
	at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.compareDictionaries(SequenceDictionaryUtils.java:234)
	at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.validateDictionaries(SequenceDictionaryUtils.java:150)
	at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.validateDictionaries(SequenceDictionaryUtils.java:98)
	at org.broadinstitute.hellbender.engine.GATKTool.validateSequenceDictionaries(GATKTool.java:621)
	at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:563)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:160)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195)
	at org.broadinstitute.hellbender.Main.main(Main.java:275)

Please suggest any solution.
Thank you.

**Comment by lbergelson** [comment]
@shashank-bgp Please open a new issue instead of asking questions in an unrelated one.  It looks like you're using an old version, I would try again with the newest release and see if the problem is fixed.  If not, open a new issue.

**Comment by xue-222** [comment]
> Hi, I am trying to generate vcf using GATK pipeline from bam file, but everytime, I am getting the following exception: 01:13:15.801 INFO NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/data1/ngs/programs/gatk-4.0.0.0/gatk-package-4.0.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so 01:13:16.075 INFO HaplotypeCaller - ------------------------------------------------------------ 01:13:16.075 INFO HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.0.0.0 01:13:16.075 INFO HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/ 01:13:16.076 INFO HaplotypeCaller - Executing as shashank@grande on Linux v3.13.0-79-generic amd64 01:13:16.076 INFO HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_72-internal-b15 01:13:16.076 INFO HaplotypeCaller - Start Date/Time: January 18, 2020 1:13:15 AM IST 01:13:16.076 INFO HaplotypeCaller - ------------------------------------------------------------ 01:13:16.076 INFO HaplotypeCaller - ------------------------------------------------------------ 01:13:16.077 INFO HaplotypeCaller - HTSJDK Version: 2.13.2 01:13:16.077 INFO HaplotypeCaller - Picard Version: 2.17.2 01:13:16.077 INFO HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 1 01:13:16.078 INFO HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false 01:13:16.078 INFO HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true 01:13:16.078 INFO HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false 01:13:16.078 INFO HaplotypeCaller - Deflater: IntelDeflater 01:13:16.078 INFO HaplotypeCaller - Inflater: IntelInflater 01:13:16.078 INFO HaplotypeCaller - GCS max retries/reopens: 20 01:13:16.078 INFO HaplotypeCaller - Using google-cloud-java patch 6d11bef1c81f885c26b2b56c8616b7a705171e4f from https://github.com/droazen/google-cloud-java/tree/dr_all_nio_fixes 01:13:16.078 INFO HaplotypeCaller - Initializing engine 01:13:17.087 INFO HaplotypeCaller - Shutting down engine [January 18, 2020 1:13:17 AM IST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.02 minutes. Runtime.totalMemory()=2216689664 java.lang.NullPointerException at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.getContigNames(SequenceDictionaryUtils.java:463) at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.getCommonContigsByName(SequenceDictionaryUtils.java:457) at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.compareDictionaries(SequenceDictionaryUtils.java:234) at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.validateDictionaries(SequenceDictionaryUtils.java:150) at org.broadinstitute.hellbender.utils.SequenceDictionaryUtils.validateDictionaries(SequenceDictionaryUtils.java:98) at org.broadinstitute.hellbender.engine.GATKTool.validateSequenceDictionaries(GATKTool.java:621) at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:563) at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:160) at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:134) at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:179) at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:198) at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:152) at org.broadinstitute.hellbender.Main.mainEntry(Main.java:195) at org.broadinstitute.hellbender.Main.main(Main.java:275)
> 
> Please suggest any solution. Thank you.

hello，have you solved this problem？
