### ISSUE TITLE
ModelSegments command memory error

### ISSUE THREAD

**Issue by MatthewP-Newbee** [broadinstitute/gatk#5948]
Hello, I use gatk-4.1.1.0. The `ModelSegments` command always throw `OutOfMemoryError`. Error message is long, I paste a few line of it.
```bash
[May 20, 2019 4:43:37 AM CST] org.broadinstitute.hellbender.tools.copynumber.ModelSegments done. Elapsed time: 357.17 minutes.
Runtime.totalMemory()=28631367680
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
        at java.lang.StringBuilder.<init>(StringBuilder.java:101)
```
I don't think this is caused by memory size. I set max memory to 500G, my `denoised_copy_ratios` input file size is `5.7M` and `AllelicCounts` inpute file size is `3.2G`.  
After some search, [this website](https://www.oracle.com/technetwork/java/javase/gc-tuning-6-140523.html#par_gc.oom) gives an explanation.  
> The parallel collector will throw an OutOfMemoryError if too much time is being spent in garbage collection: if more than 98% of the total time is spent in garbage collection and less than 2% of the heap is recovered, an OutOfMemoryError will be thrown. This feature is designed to prevent applications from running for an extended period of time while making little or no progress because the heap is too small. If necessary, this feature can be disabled by adding the option -XX:-UseGCOverheadLimit to the command line.
>   
This means some code bug?

**Comment by samuelklee** [comment]
Thanks for your question, @MatthewP-Newbee.  I suspect that you may not be using a suitable list of common SNP sites when running `CollectAllelicCounts`---`3.2G` seems quite large for an allelic-counts file.  Can you confirm whether or not this is the case?

The GATK forums might be more helpful for answering this type of question; e.g., see my previous responses to a similar post at https://gatkforums.broadinstitute.org/gatk/discussion/11915/error-with-gatk-modelsegments

**Comment by samuelklee** [comment]
User moved discussion to forum.
