### ISSUE TITLE
 Mutect2 method updated versions should be reserved

### ISSUE THREAD

**Issue by xiucz** [broadinstitute/gatk#6001]
Hi, 
I have a suggestion that the updated verisons  of  Mutect2 method [pdfs](https://github.com/broadinstitute/gatk/blob/master/docs/mutect/mutect.pdf) should be kept. 
Of course we can look up from the git history log for what have changed in each edition, but it will be much more straightforward to obtain information from pdf file.

Such as, [this picture](https://us.v-cdn.net/5019796/uploads/editor/8d/1rt7qtu6ohp2.png) 
in (this post)[https://gatkforums.broadinstitute.org/gatk/discussion/comment/56644#Comment_56644].
I know it comes from the  Mutect2 method old version, but it was no longer here.

Xiucz.

**Comment by davidbenjamin** [comment]
Since M2 only has one full-time developer, I think the history of mutect2 pdfs on github and the GATK release notes will have to suffice.
