### ISSUE TITLE
Nondeterministic behaviour in graph processing

### ISSUE THREAD

**Issue by mehrzads** [broadinstitute/gatk#6003]
----

### Affected tool(s) or class(es)
Mutect2, Haplotypecaller

### Affected version(s)
4.1.0

### Description 
It is not an actual accuracy bug but I wanted to share it with you in case you are not aware of it. If you look at BaseGraph.java. There are 4 places that you use "Collectors.toSet()". This converts a stream to an unordered set. The final order is dependant on the memory address that each element occupies so the order of result unordered set is not deterministic and can differ from run to run. 

This behavior is not problematic as long as we do not traverse the set in order. But let's look at MergeDiamonds.java as an example
`        final Set<SeqVertex> middles = getGraph().outgoingVerticesOf(top);
`
`        for ( final SeqVertex mi : middles ) {
`
First, we make unordered set "middles" and then traverse it. Merging diamonds is actually really sensitive which diamond you merge first and can result in different graphs if you change the order. This was not that important before but it seems that with the new chain pruning functionality that you put in mutect2. Sensitivity went up. and now we can actually see different results every time we run the mutect2.

I was wondering if it makes sense to change this? The way that we fixed it for ourselves was to change it to linkedHashSet to preserve the order.

_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by lbergelson** [comment]
@mehrzads Thanks for submitting this.  Iterating unordered sets is a constant cause of weird hard to pin down bugs.  We should fix this.

**Comment by droazen** [comment]
Tagging @jamesemery and @davidbenjamin

**Comment by davidbenjamin** [comment]
Let's re-visit this after a couple months of linked de Bruijn graph changes.  We tentatively plan to eliminate the `SeqGraph` entirely and work directly with the raw de Bruijn graph.
