### ISSUE TITLE
All ReadFilters should have a flag to invert their tests

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#6005]
All `ReadFilter`s should be able to be inverted by the user when specifying them on the command-line.

Currently the only filter that has this feature is the new `SoftClippedReadFilter`, which has a flag specific to itself.

The primary difficulty in implementing this feature is that Barclay may not parse the arguments correctly - it seems to only allow one argument of the same name on the command-line.  This is an issue because if using `PrintReads` and specifying multiple `ReadFilter`s you would only be able to invert one of them even if the argument was specified multiple times.

**Comment by lbergelson** [comment]
Namespaced arguments in barclay are something we've talked about before that could help with this.  So multiple argument collections / plugins objects could declare the same argument and it would be de-ambiguated by the full name of the plugin/collection.  Something like `--ReadNameFilter.invert --MappingQualityFilter.invert`

**Comment by lbergelson** [comment]
@cmnbroad

**Comment by cmnbroad** [comment]
Yeah, it would be useful (see https://github.com/broadinstitute/gatk/issues/2582). Not sure if/when we'll ever get around to the Barclay changes though.

Another simple option that wouldn't require Barclay changes would be to implement it as just another (plugin descriptor) command line argument that could be sued alongside `--read-filter`'. So if you wanted a `ReadNameFilter` and an inverted `ReadLengthFilter`, the syntax would be:

`--read-filter ReadNameFilter --invert-read-filter ReadLengthReadFilter`

**Comment by ConorMesser** [comment]
Is there any progress on this? Inverting the filters would be very helpful as currently, I am unable to filter the correct read set (especially compared to the specificity of samtools view).

**Comment by droazen** [comment]
@ConorMesser This was added in GATK 4.6 (https://github.com/broadinstitute/gatk/releases/tag/4.6.0.0):

* Added an --inverted-read-filter argument to allow for selecting reads that fail read filters from the command line easily (https://github.com/broadinstitute/gatk/pull/8724)

**Comment by droazen** [comment]
Closing -- this feature was added in GATK 4.6
