### ISSUE TITLE
PCA Inconsistencies: Projection Calculation

### ISSUE THREAD

**Issue by amritasridhar** [broadinstitute/gatk#6006]
https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/copynumber/denoising/SVDDenoisingUtils.java

If W is your matrix with with eigennumber eigensample vectors (ranked from highest to lowest eigenvalue). To finish PCA we multiply W_transpose*standardizedreadcount_transpose

In 445, 446, 449 Your result is standardizedreadcount - standardizedreadcount*W*W_transpose.

Where did you get this formula???? I cannot find it in literature.

**Comment by samuelklee** [comment]
Note that we subtract out the *projection* of the standardized read counts onto the eigenspace given by W (the assumption being that this subspace represents systematic noise).  This projection lives in the original data space (and not in the lower dimensional space, which contains the representation given by your expression) and is given by the projection matrix WW^T.
