### ISSUE TITLE
Need an ability to incorporate the outputs of cromwell runs into our WDL testing

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#6013]
### Tool(s) or class(es) involved
All WDL testing

### Description
Currently, our WDL tests are not instrumented to look inside the outputs of a cromwell run.  This stifles some WDL testing of differing parameters, since (for example) we cannot easily see if a file was created, such as a bamout.

**Comment by ldgauthier** [comment]
This should be doable, if not in the integration test framework, then in the new testing framework @KevinCLydon is working on.
