### ISSUE TITLE
Different result when changing the known indels vcf files order in RealignerTargetCreator from GATK3.4

### ISSUE THREAD

**Issue by xllbit** [broadinstitute/gatk#6016]
I checked the input known indel vcf files, when the two files include the sam indel region like the following, it may get the different results:
`file1.vcf
1       790799  .       CAG     C       950.51  PASS
file2.vcf
1       790800  .       AGT     A       1091    PASS 
`
I checked the code for this different and I thought the calculation of 'furthestStopPos' should be changed to `furthestStopPos = Math.max(furthestStopPos, vc.getEnd();` in RealignerTargetCreator.java line 221. 
Am I right or there are other reason that the 'furthestStopPos' should be 'furthestStopPos = vc.getEnd();'?

**Comment by ldgauthier** [comment]
@xllbit GATK 3 is no longer supported
