### ISSUE TITLE
Build failed with exception line 105

### ISSUE THREAD

**Issue by Firedrops** [broadinstitute/gatk#6019]
Following the instructions to build from the main readme, `./gradlew bundle` and `./gradlew clean` ends with these error messages:
```
...
Download https://repo1.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
Executing: git lfs pull --include src/main/resources/large

FAILURE: Build failed with an exception.

* Where:
Build file '/gatk/build.gradle' line: 105

* What went wrong:
A problem occurred evaluating root project 'gatk'.
> Execution of "git lfs pull --include src/main/resources/large" failed with exit code: 1.  git-lfs is required to build GATK but may not be installed. See https://github.com/broadinstitute/gatk#building for information on how to build GATK.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

The build is being attempted in a docker container in a 64-bit ubuntu VM on a Win10 host. What am I doing wrong?

**Comment by cmnbroad** [comment]
@Firedrops It looks like you don't have `git-lfs` installed. See https://github.com/broadinstitute/gatk#requirements (look for "To build GATK") for more details.

**Comment by cmnbroad** [comment]
Closing (@Firedrops feel free to reopen if this doesn't resolve the issue).

**Comment by Firedrops** [comment]
Thank you! That was indeed the issue. Hunting down the exact way to install lfs from the command line took a little time, so I'll add the steps here in case, feel free to add them to your readme.
`sudo` was cut out since the docker I'm using doesn't like it and says it's not a valid command (based on debian 9).
```
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
apt install -y git-lfs
```
