### ISSUE TITLE
Advise users how to get java 8

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#6024]
Java 8 is now old enough that it's not the default on new machines, (java 12 seems to be what comes on a new macbook.)  Installing java 8 has become more of a hassle because oracle now requires you to login in order to get it.

We should update the readme with information about how to get java 8, probably pointing people to https://adoptopenjdk.net/.  I think comms probably needs to update/add some documentation about this as well because it's definitely a friction point.

We might also want to advise using jenv for people with multiple java installations to manage them.

**Comment by lbergelson** [comment]
@bhanugandham Have people been having trouble installing java 8 recently?  I just found out that you now need to log into an oracle account to download it which is gross and off putting.

**Comment by bhanugandham** [comment]
@lbergelson people have not posted about this on the forum yet but thank you for letting me know I will keep an eye out for it.

**Comment by droazen** [comment]
This was done -- closing.
