### ISSUE TITLE
"Duplicating" a ticket on Disq (about PrintReadsSpark)

### ISSUE THREAD

**Issue by SHuang-Broad** [broadinstitute/gatk#6027]
See [here](https://github.com/disq-bio/disq/issues/110) in the Disq repo for full bug report and discussions.

**Comment by SHuang-Broad** [comment]
Update: 

The issue may have been fixed in Disq via [this](https://github.com/disq-bio/disq/pull/111).

@lbergelson can you teach me how to test this?
The PR didn't lead to a release (yet) so I don't know how to appropriately change `build.gradle` to test.

**Comment by lbergelson** [comment]
@SHuang-Broad You can install a version locally with `mvn install` and then build a GATK with that snapshot.
