### ISSUE TITLE
MultiVariantWalkerGroupedOnStart doesn't handle reads correctly

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#6030]
When `MultiVariantWalkerGroupedOnStart` finds a variant that does not share a start with the `currentVariants`, it processes that group of variants.  However, it does so using the `readsContext` of the *found* variant with a different start and not that of the group of processed variants.  Furthermore, in `afterTraverse` it processes any remaining variants with an empty `ReadsContext`, which is just wrong.

This has not been caught before because no existing implementations use reads.

**Comment by davidbenjamin** [comment]
@lbergelson This is for the new realignment filter with reassembly.  I'm using `MultiVariantWalkerGroupedOnStart` as you suggested, and I will fix this bug in the PR for the new tool.

**Comment by lbergelson** [comment]
That's a pretty nasty bug.  Good find.
