### ISSUE TITLE
GC Bias Correction

### ISSUE THREAD

**Issue by amritasridhar** [broadinstitute/gatk#6038]
When both panel of normals and sample are GC bias corrected, does that undo all the work you do for GC bias? As in if you apply the kernel to both normals and sample and then divide the sample by the normals, that should also divide out the kernel? It's hard to tell from going through the code.

**Comment by samuelklee** [comment]
Note that the GC-bias correction applied is specific to each sample, as opposed to a universal correction that is applied in the same way to all samples.  Samples which have relatively flat GC-bias curves will undergo less correction.  These sample-specific corrections thus do not drop out across the panel when bin-specific corrections are later applied.

By the way, the GATK Forum might be a better place for this type of question---other users might be able to provide answers or benefit from seeing the discussion.  GitHub issues are better suited for tracking bugs or feature requests.
