### ISSUE TITLE
Tool returned non-zero value 

### ISSUE THREAD

**Issue by lidd77** [broadinstitute/gatk#6056]
HI, 
the following commands were included at my bash script .
after I ran them,  I got a log file with "Tool returned:
6785087",  I am not sure why  the return code is 6785087 , not 0 ???

Anything wrong with my commands ?
Thanks ! 

gatk-4.1.2.0/gatk  BaseRecalibrator -R $fasta  -I $tumor_bam --known-sites a.vcf --known-sites b.vcf 
--intervals t.bed --interval-padding 50 --read-validation-stringency SILENT  -O recal_data.table 

gatk-4.1.2.0/gatk   ApplyBQSR -R $fasta -I $tumor_bam --bqsr-recal-file  recal_data.table 
 --intervals  t.bed --interval-padding 50 --read-validation-stringency SILENT -O  recal_data.bam

**Comment by cmnbroad** [comment]
@lidd77 If the return code is the value from BaseRecalibrator, then its the number of reads processed by the tool.

**Comment by lidd77** [comment]
> @lidd77 If the return code is the value from BaseRecalibrator, then its the number of reads processed by the tool.
@cmnbroad  
Thanks ! 
Are there some detailed introduction , like documents, about 'Tool returned value  ' ?
I don't know why this  BaseRecalibrator tool need to  return the number of reads processed , more explaination is welcome .

**Comment by lbergelson** [comment]
@cmnbroad I think we should change this behavior and return codes should only be error conditions.

**Comment by lbergelson** [comment]
Oh, I'm confused aren't I, this is just the standard out, not the actual return code.  Never mind... Maybe we should clarify the output message though so people aren't confused.

**Comment by lidd77** [comment]
@lbergelson  
perphaps it will not be led to be confused if  to add some verbose information about this standard output , like  "6785087 reads processed  " , not just number...
