### ISSUE TITLE
F1R2 F2R1 SB MB

### ISSUE THREAD

**Issue by vaishmanobala** [broadinstitute/gatk#6057]
What are the potential information we get from F1R2, F2R1, SB & MB fields? How are they calculated? Where are they used? Are these fields interconnected? What are the threshold of these fields to filter out only true positive variants? Please clarify. TIA

**Comment by lbergelson** [comment]
@takutosato Is there documentation explaining these fields?  I'm not even sure what MB is and can't figure out what generates it.

@vaishmanobala This type of question it probably better to ask on the [support forum](https://gatkforums.broadinstitute.org/gatk/categories/gatk-support-forum).  That said, I did a quick forum search and didn't find much information already there.

**Comment by davidbenjamin** [comment]
@vaishmanobala annotations are described in the header of Mutect2's output VCF.

Mutect2 for the most part uses probabilistic models to filter, not hard thresholds.  Please see our documentation: https://github.com/broadinstitute/gatk/blob/master/docs/mutect/mutect.pdf for details.
