### ISSUE TITLE
HaplotypeCaller --output-mode EMIT_ALL_SITES does not emit all sites

### ISSUE THREAD

**Issue by tfenne** [broadinstitute/gatk#6059]
### Affected tool(s) or class(es)
HaplotypeCaller --output-mode EMIT_ALL_SITES

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
I'm trying to generate a VCF (not a gVCF) that contains calls spanning all the sites in my regions.  Each region is small, and is more or less equivalent to a single variant.  Ideally I'd use `GENOTYPE_GIVEN_ALLELES`, but I don't know the alleles, and in some cases the variant location is approximate (e.g. somewhere in _this_ 10bp window).

I've been trying to use HaplotypeCaller to produce a VCF that contains calls covering my entire set of regions, but nothing seems to work.  I started with just `--output-mode` and eventually ended up with:

```
gatk HaplotypeCaller \
  -R ref.fasta \
  -L regions.interval_list \
  --disable-optimizations \
  --force-active \
  --output-mode EMIT_ALL_SITES \
  -I my.bam \
  -O my.vcf.gz
```

This does output considerably more records, including a lot of hom-ref records, but still nowhere near to the full set of bases within my regions.  E.g. in one test this emits variants spanning 3,468bp which is way better than the ~120bp I get without those options, but nowhere near the 293,570bp with the regions I'm supplying.

It would be great if `--output-mode EMIT_ALL_SITES` did as the documentation described, but if that's not possible, then perhaps that mode should simply be removed?

#### Steps to reproduce
Try calling a BAM file with HaplotypeCaller with a 100-1000bp region with `--output-mode EMIT_ALL_SITES`.

#### Expected behavior
VCF should contain records spanning the entire input region.

#### Actual behavior
VCF contains a minority of sites from the region.

**Comment by droazen** [comment]
@jamesemery This seems related to the forum issue we were discussing earlier today -- would you mind looking into it when you get a chance?

**Comment by jamesemery** [comment]
@tfenne I'm not sure we quite expect every site in the provided intervals to be covered by a variant or homeVar call. If the HaplotypeCaller deems a site to be active then it is assembled and genotyped, the emit all sites switch is applied to the genotyper and prevents the genotyper from returning a null variant context at sites that are clearly not real variants. That does not however mean that sites that never make it to the genotyper will get returned. That means activityRegions that are not considered sufficiently active to be assembled will still not be covered in the output. If you want an estimate of the reference confidence for non-variant sites perhaps you should use a GVCF instead?

**Comment by tfenne** [comment]
@jamesemery What I'm actually trying to do is essentially `GENOTYPE_GIVEN_ALLELES` except that I don't know the ALTs.  I realize that may sound silly.  What I've ended up doing for now is generate a gVCF, genotype it, and then write a custom tool that consumes VCF and gVCF and inserts hom-ref genotypes based on a) where there is no call in the VCF and b) there is confidence in the hom-ref genotype in the gVCF.

My point in logging this issue is mostly that `EMIT_ALL_SITES` is pretty misleading as it stands.  I think it would be good, at a minimum, to update the documentation for that option to make it very clear that it does not in fact "emit all sites" but instead "emits more sites, but still a subset of all sites in the region being called".

**Comment by ccartermices** [comment]
I want to know the format of the file regions.interval_list. Can you tell me please?

**Comment by michaelgatzen** [comment]
> I want to know the format of the file regions.interval_list. Can you tell me please?

@ccartermices There is a description about this file format in the documentation:
https://software.broadinstitute.org/gatk/documentation/article?id=11009

**Comment by michaelgatzen** [comment]
The argument has been renamed and the documentation improved in order to clarify the purpose of this mode.
