### ISSUE TITLE
Why Mutect2 always gives strange DP, AD, and AF information?

### ISSUE THREAD

**Issue by Chitanda-Satou** [broadinstitute/gatk#6067]
Dear all, 
May I ask about the DP, AD, and AF information of Mutect2?

If we perform somatic mutation calling with the same pair of tumor samples,  we can see that:
>chr2    227915762       .       T       C       240     PASS   
>STATUS=StrongSomatic;SAMPLE=yjhzy_T1;TYPE=SNV;DP=155;VD=69;AF=0.4452;SHIFT3=0;MSI=2.000;MSILEN=1;SSF=0;SOR=Inf;LSEQ=GAGCCTGGAGGGCCTGGGGG;RSEQ=CCAGGAGGCCCTGGCTGACC 
>GT:DP:VD:ALD:RD:AD:AF:BIAS:PMEAN:PSTD:QUAL:QSTD:SBF:ODDRATIO:MQ:SN:HIAF:ADJAF:NM
>0/1:155:69:34,35:45,41:86,69:0.4452:2,2:31.6:1:39.3:1:0.74799:1.12895:60:68:0.4416:0:1.4
>0/0:106:0:0,0:59,47:106,0:0:2,0:35.6:1:35.1:1:1:0:60:105:1:0:0.4

VarDict said the DP, AD, AF were 155, 69, and 0.4452. The control DP and AD were 106, 0, 0.

>chr2    227915762       .       T       C       .       PASS    
>DP=262;MQ=60.00;MQ0=0;NT=ref;QSS=242;QSS_NT=3070;ReadPosRankSum=1.63;SGT=TT->CT;SNVSB=0.00;SOMATIC;SomaticEVS=19.98;TQSS=1;TQSS_NT=1    
>DP:FDP:SDP:SUBDP:AU:CU:GU:TU
>106:0:0:0:0,0:0,0:0,0:106,106
>156:0:0:0:0,0:69,69:0,0:87,87

Strelka2 said the DP of tumor was 156. The control DP was 106, (The sequence was opposite with VarDict).

However, Mutect2 said that
>chr2    227915762       .       T       C       .       PASS   
>CONTQ=93;DP=88;ECNT=1;GERMQ=118;MBQ=35,40;MFRL=205,190;MMQ=60,60;MPOS=38;NALOD=1.70;NLOD=14.70;POPAF=3.00;SAAF=0.364,0.333,0.378;SAPP=0.014,0.036,0.950;TLOD=50.64       
>GT:AD:AF:DP:F1R2:F2R1   
>0/1:23,14:0.385:37:11,7:12,7    
>0/0:49,0:0.019:49:25,0:24,0
The DP, AD, AF were 37, 14, and 0.385. The control DP, AD and AF were 49, 0, 0.019.

There are serveral things which are confusing:

1.  Why the DP reported in Mutect2 results are different in ##INFO and ##FORMAT fields? We can see: CONTQ=93;**DP=88**, vs. **DP=37**.
2. Why the AF of Mutect2 is strange? **14 / ( 23 + 14) = 0.378 != 0.385**.
3. Why in the control sample, we got AF = 0.019, but **0 / (0 + 49) = 0**?
4. Why all the sites in the VCFs showed as above?

Any reply will be appreciated.

Best regards!

**Comment by davidbenjamin** [comment]
1.  INFO fields are for the variant as a whole (over all samples), FORMAT fields are for individual samples.
2. Mutect2 emits a probabilistic estimate of AF that accounts for, among other things, the uncertainty of reads.
3.  Same as 2.  Also, the Mutect2 AF should be thought of as the answer to "At what allele fraction is the allele present in this sample *if it exists in the sample*?"
4. I'm not sure what you mean.

**Comment by Chitanda-Satou** [comment]
Thank you @davidbenjamin !

One more question, could you please tell me why Mutect2 reports **smaller DP** than Strelka2 and VarDict? I guess it may be due to base quality filtering...

Best regards!

**Comment by davidbenjamin** [comment]
@Chitanda-Satou differences in mapping quality filtering are always possible.  There's also the fact that Mutect2 treats read *pairs*, as opposed to reads, as the fundamental unit of evidence.

**Comment by Chitanda-Satou** [comment]
@davidbenjamin Thanks a lot!

My questions have been solved.
