### ISSUE TITLE
Builds failing due to R dependency issues 

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#6072]
It looks like all of our builds are failing since we cleared the cache because of R dependency issues.

```
...

Setting up r-base-core (3.1.3-1trusty) ...
Installing new version of config file /etc/bash_completion.d/R ...
Installing new version of config file /etc/R/Renviron.site ...
Installing new version of config file /etc/R/Makeconf ...
Installing new version of config file /etc/R/repositories ...
Installing new version of config file /etc/R/Rprofile.site ...
Installing new version of config file /etc/R/ldpaths ...
Replacing config file /etc/R/Renviron with new version
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Installing packages into ‘/home/travis/site-library’
(as ‘lib’ is unspecified)
Error: (converted from warning) dependencies ‘rlang’, ‘vctrs’ are not available
Execution halted
```

Both libraries now require R >= 3.2.
We could either try again to nail down the R versions exactly, which is almost certainly possible but not something we've ever figured out a good way to do, or we could just upgrade R and hope for the best, kicking the can down the road again.

**Comment by droazen** [comment]
@lbergelson Recommend that we take the quickest path to getting tests passing again, as several people are waiting to merge their PRs in time for the next release.
