### ISSUE TITLE
one-space indentation at the end of mutect2.WDL file causes the task to be unrecognized

### ISSUE THREAD

**Issue by sclan** [broadinstitute/gatk#6078]
The closing bracket for task Funcotate in mutect2.wdl (the last line of the file) had a one-space indentation which invalidates the task section.

I'd appreciate if someone could review and approve the following PR.
https://github.com/broadinstitute/gatk/pull/6077

**Comment by lbergelson** [comment]
@sclan Forgot to close this when #6077 was merged.  Let me know if you still have issues.
