### ISSUE TITLE
Which regions to use for exome calling_interval_list

### ISSUE THREAD

**Issue by gevro** [broadinstitute/gatk#6080]
Agilent and other exome capture kits generally provide two types of region files: Target (regions that were originally specified for the design) and Probes (what the final design actually included).
==> Which is the correct one to use for the calling_interval_list?

One could make arguments either way for Targets as opposed to Probes.

**Comment by ldgauthier** [comment]
Calling intervals should be based on targets.  The targets are the goal and the probes are the implementation.   Depending on the bait design and the size of the exons, there can be regions of the targets that are not covered by baits, but still have coverage and still should be called.

**Comment by gevro** [comment]
Thanks. That’s what I thought too. But interestingly, looks like some of Agilent’s old BED files do not have such target BED files. Even though they are labeled as such, the boundaries of regions look only like probes. Specifically for the Sureselect clinical research exome and the Human all Exon v4 kits.
