### ISSUE TITLE
Stop Cloudera cookie rejected notifications from appearing on gradle build

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#610]
Something about the cloudera artifactory server is causing our gradle build to print out "cookie rejected" notifications when it checks it for dependencies.

```
:compileJava
Cookie rejected: "[version: 0][name: JSESSIONID][value: 4A10F85C449AC245A7195508DC597006][domain: repository.cloudera.com][path: /cloudera/][expiry: null]". Illegal path attribute "/cloudera/". Path of origin: "/artifactory/cloudera-repos/com/google/appengine/appengine-api-1.0-sdk/"
Cookie rejected: "[version: 0][name: JSESSIONID][value: 75ED0380B9A0ED0358C2B9666BED71A3][domain: repository.cloudera.com][path: /cloudera/][expiry: null]". Illegal path attribute "/cloudera/". Path of origin: "/artifactory/cloudera-repos/com/google/guava/guava/"
Cookie rejected: "[version: 0][name: JSESSIONID][value: 7693D886ED54601AF3EB1333359425D9][domain: repository.cloudera.com][path: /cloudera/][expiry: null]". Illegal path attribute "/cloudera/". Path of origin: "/artifactory/cloudera-repos/com/google/api-client/google-api-client-appengine/"
Cookie rejected: "[version: 0][name: JSESSIONID][value: 86B716FE5E36C74ABF85424380AEFC03][domain: repository.cloudera.com][path: /cloudera/][expiry: null]". Illegal path attribute "/cloudera/". Path of origin: "/artifactory/cloudera-repos/com/google/http-client/google-http-client-jackson2/"
```

We should figure out if this is a meaningful warning at all, and how to prevent it from happening.

@tomwhite Any idea what's causing these messages?  Not a high priority but they're mildly annoying.

**Comment by tomwhite** [comment]
Thanks for reporting this @lbergelson. I've raised it internally at Cloudera, so we'll see if it can be fixed.

I also had a hunt around to see if it would be possible to suppress this on the Gradle side, but I couldn't see anything. It's possible for Maven, but I don't think this applies to Gradle:

http://maven.apache.org/guides/mini/guide-http-settings.html#Ignoring_Cookies

**Comment by akiezun** [comment]
it's yours @tomwhite
