### ISSUE TITLE
Evaluate use of Spark Datasets for MarkDuplicatesSpark

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#6103]
Investigate if using Spark Datasets (and Spark SQL) in MarkDuplicatesSpark improves performance and/or simplifies the code.

**Comment by tomwhite** [comment]
I tried rewriting the core part of MarkDuplicatesSpark to use Spark Datasets rather than the current RDD implementation: see https://github.com/broadinstitute/gatk/compare/tw_md_spark_sql. The classes in `org.broadinstitute.hellbender.utils.read.markduplicates.sparkrecords` are replaced with a single "union" type `MarkDuplicatesSparkSqlRecord`, that can represent all of them (it uses a `type` field to indicate which is stored).

To test, I ran `MarkDuplicatesSpark` before and after the change on a cluster on exome-sized data. 

Before: 7.32 minutes
After: 7.43 minutes

So there was no significant difference in runtime with this change. This is probably because the part of `MarkDuplicatesSpark` that was changed is the `group by` on fragment/pair key, which actually is a fairly small part of the total runtime of MD; the rest is a shuffle to ensure the input data is queryname sorted. (Previous experiments have shown that using Spark SQL is no faster than using Spark RDDs for sorting reads.)

/cc @jamesemery @droazen

**Comment by jamesemery** [comment]
Thats disappointing. I suppose an answer would be to see if there is a significant difference over larger datasets/if there is any difference in used memory. between the two. You can actually see from the SparkUI how long the tool spends in each individual stage, perhaps we can get a breakdown of what spark thinks its doing and where the runtime has gone.

**Comment by tomwhite** [comment]
In previous benchmarking I've always seen an effect at the exome scale, so trying with a larger dataset is unlikely to reveal any significant difference.

Here is the stage breakdown.

Spark stages (master):

![MarkDuplicatesSparkMaster](https://user-images.githubusercontent.com/85085/63683680-e8027900-c7f2-11e9-9a88-5682c91c161a.png)

Spark stages (this branch):

![MarkDuplicatesSparkSql](https://user-images.githubusercontent.com/85085/63683694-f2247780-c7f2-11e9-963e-f28dd7114ee2.png)

The timings are essentially the same. The dataset code is run in stage 7, which only takes 11-12 seconds in either case - a small part of the overall runtime of Mark Duplicates Spark (>7 minutes). The runtime is dominated by sorting which I haven't managed to do any faster with Spark SQL.
