### ISSUE TITLE
using multithreads

### ISSUE THREAD

**Issue by shigej38** [broadinstitute/gatk#6117]
Hello Why doesn't gatk use all threads of the system at the same time? Does editing a given command correct this situation?
my used command is:
`$DIR/gatk/gatk --java-options "-Xmx7G -XX:ParallelGCThreads=4" HaplotypeCaller -R $GENOME -I $PLAYGROUND/$LBAM -O $PLAYGROUND/$BASE.vcf`

**Comment by lbergelson** [comment]
In gatk3 we had mechanism for multithreading in gatk, but they made the tools very complicated and didn't provide enough speed up to be worthwhile in most cases.  In gatk 4 we made the decision to write the tools as single threaded.  We have a separate implementation of some tools using spark which is a parallelization library.  

 If you want to parallelize the HaplotypeCaller you can shard the input and run multiple copies of the tool on different input shards.  That's how we do it in production.

Alternatively you can try out the beta tool HaplotypeCallerSpark which is natively parallel but is still being developed.  It hasn't been validated and may not produce results that are as accurate as the regular HaplotypeCaller.
