### ISSUE TITLE
gatk doesn't support aarch64, is there a plan to support?

### ISSUE THREAD

**Issue by Nymeriawolf** [broadinstitute/gatk#6118]
the most issue , gatk doesn't support aarch64, is there a plan to support?
and another issue, "The gatk environment, requires hardware with AVX support for tools that depend on TensorFlow (e.g. CNNScoreVariant). ", the word means gatk requires AVX ?or TensorFlow depend AVX? I confused.

**Comment by droazen** [comment]
Closing this one as answered
