### ISSUE TITLE
Change PostprocessGermlineCNVCalls to use output prefixes.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#6128]
With the addition of denoised-copy-ratio output in #5823, there are probably enough outputs to warrant this.  Might also check other CNV tools (I've personally been thinking we should do this in DenoiseReadCounts as well).  Should highlight in release notes.

**Comment by mwalker174** [comment]
Not a necessary change, though probably would have been preferred in hindsight.
