### ISSUE TITLE
Latest docker image points to v4.1.2.0 rather than v4.1.3.0

### ISSUE THREAD

**Issue by fleharty** [broadinstitute/gatk#6132]
### Description 

When using the "latest" tag on the docker, it points to 4.1.2.0 which is an earlier version.

wm462-624:resources fleharty$ docker run -it broadinstitute/gatk:latest
(gatk) root@3b6ada003edd:/gatk# java -jar gatk.jar -version
The Genome Analysis Toolkit (GATK) v4.1.2.0
HTSJDK Version: 2.19.0
Picard Version: 2.19.0
(gatk) root@3b6ada003edd:/gatk# 

A docker with version 4.1.3.0 exists when the tag is specified directly.
wm462-624:resources fleharty$ docker run -it broadinstitute/gatk:4.1.3.0
Unable to find image 'broadinstitute/gatk:4.1.3.0' locally
4.1.3.0: Pulling from broadinstitute/gatk
Digest: sha256:e37193b61536cf21a2e1bcbdb71eac3d50dcb4917f4d7362b09f8d07e7c2ae50
Status: Downloaded newer image for broadinstitute/gatk:4.1.3.0
(gatk) root@efd300ea536a:/gatk# java -jar gatk.jar -version
The Genome Analysis Toolkit (GATK) v4.1.3.0
HTSJDK Version: 2.20.1
Picard Version: 2.20.5

**Comment by droazen** [comment]
@fleharty I checked, but it looks like the `latest` tag on dockerhub points to the 4.1.3.0 image:

```
$ docker images broadinstitute/gatk
REPOSITORY            TAG                                        IMAGE ID            CREATED             SIZE
broadinstitute/gatk   4.1.3.0                                    0ef3d00baa09        3 weeks ago         3.72GB
broadinstitute/gatk   latest                                     0ef3d00baa09        3 weeks ago         3.72GB

$ docker run -it broadinstitute/gatk:latest
(gatk) root@c8bcdf54805c:/gatk# ./gatk --version
Using GATK jar /gatk/gatk-package-4.1.3.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gatk/gatk-package-4.1.3.0-local.jar --version
The Genome Analysis Toolkit (GATK) v4.1.3.0
HTSJDK Version: 2.20.1
Picard Version: 2.20.5
```

Could you try re-pulling the broadinstitute/gatk:latest image and check again?

**Comment by fleharty** [comment]
@droazen 
Turns out I used the latest at an earlier time, and this resulted in some confusion on my part.

Everything is good, I'm closing this ticket.  Sorry about the confusion.
