### ISSUE TITLE
GenomicsDBImport error: File2TileDBBinaryException

### ISSUE THREAD

**Issue by bhanugandham** [broadinstitute/gatk#6150]
Based on GATK office hrs discussion, this issue requires adjusting the buffer size, but that option is not available in GATK.

Please find below the user error report:

Hello, I've been trying to get the HaplotypeCaller-in-gVCF-mode to work for a combination of exome samples, some of which are diploid individuals, and others of which are bulks with ploidies ~20. For about 20% of my chromosomes, The GenomicsDBImport step fails, with the following error message:

```
09:58:45.656 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Batches Processed   Batches/Minute
09:58:46.530 INFO  GenomicsDBImport - Importing batch 1 with 6 samples
terminate called after throwing an instance of 'File2TileDBBinaryException'
what():  File2TileDBBinaryException : read_one_line_fully && "Buffer did not have space to hold a line fully - increase buffer size"
```

I'm not sure what this means, and a google search brings up next to nothing. 

I am working with mosquito exome data, 150bp PE illumina reads, GATK 4.1.3.0, java 1.8.0_181. I've been following the Broad best practices pretty closely, although I haven't managed to figure out how to bootstrap base recalibration yet.

Example GenomicsDBImport command:
```
gatk --java-options '-Xmx5G' GenomicsDBImport \
        --genomicsdb-workspace-path ../vcfs/combined_gvcfs/NW_021837046.1 \
        --intervals NW_021837046.1 \
        -V ../vcfs/gvcfs/BH2.gvcf \
        -V ../vcfs/gvcfs/BH3.gvcf \
        -V ../vcfs/gvcfs/K01.gvcf \
        -V ../vcfs/gvcfs/K02.gvcf \
        -V ../vcfs/gvcfs/M01.gvcf \
        -V ../vcfs/gvcfs/M02.gvcf 
``` 

I played around with increasing "--genomicsdb-segment-size" and "--genomicsdb-vcf-buffer-size", as well as the amount of memory available to java. Increasing any or all of them by a factor of about 10 had no effect, always producing the same error.

This Issue was generated from your [forums] 
[forums]: https://gatkforums.broadinstitute.org/gatk/discussion/24420/genomicsdbimport-error-file2tiledbbinaryexception/p1

**Comment by bhanugandham** [comment]
@mlathara @nalinigans Please let me know if you have any questions.

**Comment by mlathara** [comment]
It turns out we were wrong and there was already a knob exposed for this. I gave the user some directions on increasing the correct buffer size, and they have accepted that answer. 

We can probably go ahead and close this issue.

**Comment by bhanugandham** [comment]
Sounds good, thank you Melvin!
