### ISSUE TITLE
IndexFeatureFile should support GCS inputs/outputs

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#6161]

**Comment by droazen** [comment]
Requested by @yfarjoun

**Comment by cmnbroad** [comment]
While we're at it, we're going to change the name of the input argument from `-F` to `-I`.

**Comment by ldgauthier** [comment]
I've had to index VCFs in the cloud and it made me sad, but part of what made me sad was that I didn't have write permissions to save my index.  Any chance of indexing on the fly in those cases?
