### ISSUE TITLE
--model a_valid_ploidy_model_dir for CASE mode | DetermineGermlineContigPloidy

### ISSUE THREAD

**Issue by SaraAlthubaiti** [broadinstitute/gatk#6162]
Hi team,

I'm trying to run `DetermineGermlineContigPloidy` on one sample that I have, but in `CASE` mode it requires `--model a_valid_ploidy_model_dir` in which here (https://gatkforums.broadinstitute.org/gatk/discussion/23471/the-parameter-model-of-determinegermlinecontigploidy-when-use-case-mode#latest)

They said that it came from running `COHORT` mode first to have it, but in my case; I want to run `CASE` mode because I only have one sample, so to get --model from `COHORT` mode; I will not be able to have it since it couldn't run on one sample

`A USER ERROR has occurred: Bad input: Invalid combination of inputs: Running in cohort mode, but only a single sample was provided.`

So, how I could produce `-- model` for `CASE` mode to be used for one sample?

**Comment by samuelklee** [comment]
@SaraAlthubaiti It's unlikely that you would get reasonable results with DetermineGermlineContigPloidy with a single sample, so we explicitly disallow it.  This is because we typically require multiple samples to learn a model for per-contig biases.

**Comment by MerlinAC** [comment]
@SaraAlthubaiti 
Hi, I encountered the similar question as you posted. Have you solved it? And what kind of the file provided in the a_valid_ploidy_model_dir?
