### ISSUE TITLE
CNNFilterVariants should label good variants with PASS

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#6164]
Right now the CNNFilterVariants tool is applying filters to filter out variants by labeling with `SNP_Tranche_98_to_99` or similar, but good variants that pass filters still have `.` in the FILTER field.  The VCF spec says " filter status: PASS if this position has passed all filters, i.e., a call is made at this position ... If filters have not been applied,
then this field should be set to the missing value", i.e. `.` Calls may not be treated correctly in other GATK tools.

This issue is evidenced in the Terra workspace https://app.terra.bio/#workspaces/help-gatk/cnn-variant-filter/data in the filtered vcf output

**Comment by cmnbroad** [comment]
I think this was fixed in 4.13 https://github.com/broadinstitute/gatk/pull/5837.

**Comment by ldgauthier** [comment]
This did seem vaguely familiar.  The Terra version is stale.

**Comment by ldgauthier** [comment]
@lucidtronix can you modify the workspace or do we need to jump through some hoops with Beri?
