### ISSUE TITLE
port DepthOfCoverage (WGS coverage)

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#617]
the requirement is to port DepthOfCoverage or write a new tool that collects coverage information per base (primarily for WGS) and stats as DoC does. Integration tests also need to be ported or created. Current test data is broad-internal but we should move to using public data.

**Comment by droazen** [comment]
@vdauwera has requested that this be re-prioritized in the medium-term future.

**Comment by droazen** [comment]
Closing in favor of https://github.com/broadinstitute/gatk/issues/19
