### ISSUE TITLE
Mutect2: stats file not being generated when no mutation is called

### ISSUE THREAD

**Issue by hurrialice** [broadinstitute/gatk#6170]
Hi gatk team,

I just run a cfDNA sample and there is no variant being called, thus there is no ".stats" file being generated so that when it comes to `filterMutectCalls`, it gives error.

I wonder if it is wiser that we output an empty stats file, e.g.
```
statistic	value
callable	0
```

or simply reports 

```
ERROR: No callable variants detected!
```

instead of reporting missing stats file? This would be more informative.

Thanks!!

**Comment by davidbenjamin** [comment]
@hurrialice I'm having trouble reproducing this error.  What commands are you using for `Mutect2` and `FilterMutectCalls`?

**Comment by davidbenjamin** [comment]
Closing due to lack of response and unsuccessful attempts to reproduce the issue.  I have run test cases with no variants output that still produce a stats file.  We can re-open this if someone produces an example with the issue.

**Comment by Akazhiel** [comment]
Hi!

I've stumbled upon the same error, on running Mutect2, the `.stats` is not generated and sometimes `FilterMutectCalls` will complain the file is missing and sometimes not. I find this quite a weird behaviour.

The commands I use to run Mutect2 and FilterMutectCalls are the following:

```
gatk Mutect2 --reference GRCh38.fa --input sample1_final.bam --input sample2_final.bam --normal-sample SAMPLE_NORMAL --output Mutect_unfiltered.vcf --germline-resource af-only-gnomad.hg38.vcf.gz --dont-use-soft-clipped-bases --panel-of-normals 1000g_pon.hg38.vcf.gz
``` 

```
gatk FilterMutectCalls --variant Mutect_unfiltered.vcf --output Mutect.vcf --reference GRCh38.fa
```

Best regards!
