### ISSUE TITLE
Funcotator outputs fields in wrong order in some cases when writing vcf

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#6173]
There's an issue in `VcfFuncotationFactory.createFuncotationsOnVariant` where certain cites that need multiple functotations merged produce incorrect output.  The cause is an accidental conversion of LinkedHashMap -> HashMap which scrambles the iteration order of the map.  The order is used when writing the fields so the names of the fields end up on different values.

**Comment by lbergelson** [comment]
The issue seems to happen when you have multiple records in the datasource which exactly match the position and alleles of a record in the file being annotated.  The output fields for that datasource will be scrambled at those sites.  This affects both vcf and maf output.
