### ISSUE TITLE
GATK seems to read from requester pays buckets even when --gcs-project-for-requester-pays isn't specified

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#6176]
I set up a test requester pays bucket in GCS: `gs://droazen-requester-pays/` with a test file `gs://droazen-requester-pays/reads_data_source_test1.bam`. 

GATK `CountReads` happily reads from this file even when I don't specify the `--gcs-project-for-requester-pays` argument. The expected behavior is that it will refuse to proceed unless that argument is specified.

Command to replicate:

```
./gatk CountReads -I gs://droazen-requester-pays/reads_data_source_test1.bam
```

**Comment by droazen** [comment]
@jean-philippe-martin Any thoughts on what could be causing this?

**Comment by jean-philippe-martin** [comment]
The [rules for requester pays](https://cloud.google.com/storage/docs/requester-pays#requirements) now specify two conditions under which the bucket may be accessed:

1. userProject is specified (this is what `--gcs-project-for-requester-pays` does), or

2. The requester has `resourcemanager.projects.createBillingAssignment` permission for the project that contains the bucket. 

I suspect condition (2) is true here, so the access is granted. Note that if I remember correctly, condition (2) didn't exist when requester-pays was initially introduced.

**Comment by droazen** [comment]
Aha, that makes sense! Thanks for the information JP!
