### ISSUE TITLE
Write a utility method to convert a GATKRead to a well-formed SAM string

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#618]
Currently we convert from `GATKRead` to `SAMRecord` whenever we want to write out a SAM/BAM file (see, eg., `PrintReadsDataflowTransform` and `SAMFileGATKReadWriter`). This is wasteful and lossy. Let's write a utility method `toSAMString() `(or add a new `GATKRead` interface method) that can produce a well-formed SAM string from a `GATKRead`

Note that such a method already exists for raw `SAMRecord`s (`getSAMString()`)

**Comment by droazen** [comment]
Can use `SAMTextWriter.writeAlignment()` as starting point. 

There's already a method to create the SAM flags for a GATKRead (`ReadUtils.getSAMFlagsForRead()`).

Only non-trivial part is creating SAM representations of each attribute. Need to convert to TAG:TYPE:VALUE format. Probably need a table based on the standard attributes in the SAM spec -- there's already an implementation of this in `GenomicsConverter`. For NON-standard attributes, can use type "Z" (string).

**Comment by lbergelson** [comment]
We should also find any custom sam tags we're using and add them to the table.

**Comment by droazen** [comment]
Almost done in https://github.com/broadinstitute/hellbender/pull/871

**Comment by lbergelson** [comment]
closed by #871
