### ISSUE TITLE
GermlineCNVCaller Error with Python Exit code 137, Failing at Denoising model (warm-up)

### ISSUE THREAD

**Issue by arunbodd** [broadinstitute/gatk#6183]
[germlinecnv200samples_withinterval.txt](https://github.com/broadinstitute/gatk/files/3653052/germlinecnv200samples_withinterval.txt)

Hi,

I am running gatkv4.1.3.0 germlinecnvcaller on 200 PON samples in Cohort mode with exome interval lists and GC intervals lists. I am running this on a PBS system with 60G and 4 threads equalling 240G max memory for the entire job. I have tried few different ways of specifying memory options and threads and even mentioning memory using --java-options. 

Tried with mem=60G, threads=4, --java-options=240g
tried with mem=240, threads=1, --java-options=240g
tried with mem=715G, threads=1. --java-options=650g (this might be wrong)

for all the above scenarios, the program seems to run the first epoch (5000Iterations) with mem=60G, threads=4, but failing to run epoch2(200iterations or denoising(main))

But, for 50 samples, with mem=60G, threads=4 but not specifying anything on java-options, its running beyond epoch 2 or denoising(main) and running while i am writing this post.

But, my ultimate goal is to run ~300 PON samples and i am unable to get it run beyond denoising(warm-up), i am not sure if the way i am setting up the jobs are insufficient or its a totally different problem

Please help.

Thank you.

**Comment by mwalker174** [comment]
Hi @arunbodd, thanks for your question.

First, are you sure you have 240GB memory? Usually threads refers to the number of CPU cores, which is independent of memory size. If you in fact do have 240GB, you should set the java memory  somewhat lower (~220GB) so ensure you have enough leftover for the OS.

In general, the memory requirements will scale linearly with the number of samples and number of intervals. We recommend running gCNV with ~5,000-10,000 intervals. If you have more, you should shard your interval list. You may find the WDL helpful if you haven't looked at it already: https://github.com/broadinstitute/gatk/tree/master/scripts/cnv_wdl/germline

**Comment by samuelklee** [comment]
Closing, as this does not involve a bug fix or a feature request.  @arunbodd if you need additional help determining requirements or running the tool, you might want to post on the forums at https://gatkforums.broadinstitute.org/gatk.
