### ISSUE TITLE
How to call SNPs in GATK with multithreads in GATK?

### ISSUE THREAD

**Issue by ccartermices** [broadinstitute/gatk#6192]
I know that we can use HaplotypeCaller to call snps but i don't how to call SNPs in GATK with multithread in GATK4. Who can help me please?

**Comment by davidbenjamin** [comment]
@ccartermices GATK 4 implements multithreading via Spark (see the discussion in #2345).  Thus `HaplotypeCallerSpark` may be the tool you want.
