### ISSUE TITLE
Running the spark jar without the wrapper script

### ISSUE THREAD

**Issue by jamesthegiantpeach** [broadinstitute/gatk#6198]
Greetings,

I would like to be able to run spark reads pipeline from the jar file without the gatk wrapper script. My reason for this is that I already have existing infra for spark jobs that I would like to use. Specifically, I would like to be able to run gatk jobs with the kubernetes [spark operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator). This requires being able to give the SparkApplication CRD a main class location and a jar file. Is this feasible with gatk?

**Comment by lbergelson** [comment]
While we normally don't recommend ignoring that wrapper, this seems like a good reason to do so.  

The wrapper is pretty simple, most of what it's doing is some munging of the input to allow it to be more standardized in several different gatk use cases.  The only thing I can think of that you would want to be sure to copy is that it sets a number of properties. 

We set these spark `--conf` properties with the wrapper.  I don't actually know how important some of them are anymore.  If it works without them then you're probably good.
```
    "spark.kryoserializer.buffer.max" : "512m",
    "spark.driver.maxResultSize" : "0",
    "spark.driver.userClassPathFirst" : "false",
    "spark.io.compression.codec" : "lzf",
    "spark.executor.memoryOverhead" : "600",
    "spark.driver.extraJavaOptions" : EXTRA_JAVA_OPTIONS_SPARK,
    "spark.executor.extraJavaOptions" : EXTRA_JAVA_OPTIONS_SPARK
```

These are htsjdk properties we want to set for spark.  
```
EXTRA_JAVA_OPTIONS_SPARK= "-DGATK_STACKTRACE_ON_USER_EXCEPTION=true " \
                   "-Dsamjdk.use_async_io_read_samtools=false " \
                   "-Dsamjdk.use_async_io_write_samtools=false " \
                   "-Dsamjdk.use_async_io_write_tribble=false " \
                   "-Dsamjdk.compression_level=2 "
```

If you can get this value into your spark environment variables it prevents and anying warning output.  `SUPPRESS_GCLOUD_CREDS_WARNING=true`

Let us know how it works for you.

**Comment by lbergelson** [comment]
That sounds like a good thing to consider.  It's not something we have any experience with, so it might be hard for us to maintain, but if you or other community members are willing to put the effort in I think we would be happy to have that in our repo.

**Comment by jamesthegiantpeach** [comment]
I’m just now getting around to trying this. 

I packed the gatk spark jar into the spark-operator’s spark docker container. Now I’m just wondering if it’s possible to stream the genomes from S3 to the executors? I’m trying to avoid any HDFS usage.

**Comment by jamesthegiantpeach** [comment]
This ended up being trivial btw. I'll clean up an example and post/merge instructions somewhere.
