### ISSUE TITLE
PlotModeledSegments crashes with latest version of R package optparse

### ISSUE THREAD

**Issue by cboursnell** [broadinstitute/gatk#6207]
### Affected tool(s) or class(es)
PlotModeledSegments

### Affected version(s)
Confirmed with 4.1.3, but also any version before this that uses optparse

### Description 
The R package `optparse` is used in the R script `PlotModeledSegments.R` for plotting. The latest version of `optparse` (1.6.4) has been updated to include a check that the short-name of an option is only 1 character. 
See here: https://github.com/trevorld/r-optparse/commit/66acec58645f7401fc365bb769a72751671c2114
The `PlotModeledSegments.R` script in gatk has this line:
```make_option(c("--sample_name", "-sample_name"), dest="sample_name", action="store"),```
which will now make `optparse` throw an error

#### Steps to reproduce
Install `optparse 1.6.4` and run `gatk PlotModeledSegments`

#### Expected behavior
The Rscript should parse the inputs and run

#### Actual behavior
PlotModeledSegments.R gives an error

**Comment by samuelklee** [comment]
Closed by #6197.
