### ISSUE TITLE
Samples order of vcf files by Mutect2

### ISSUE THREAD

**Issue by wangshun1121** [broadinstitute/gatk#6214]
I used `Sample1` as `Normal`, and `Sample2` as `Tumor`, and sample order in Mutect2's output would be `Sample1 Sample2`.

I used to treat the first Sample in vcf file as Normal, and Second Sample as Tumor. When I made  `Sample1` as `Tumor`, and `Sample2` as `Normal`, then tumor sample would be first! This made trouble for following mutations filter process!

I wonder if there's any parameters in Mutect2 to appoint the order of samples in output?

**Comment by davidbenjamin** [comment]
@wangshun1121 The GATK, like much other software, orders samples alphabetically.  This is not a problem for FilterMutectCalls, the recommended tool for filtering the output of Mutect2.
