### ISSUE TITLE
Reg error in DetermineGermlineContigPloidy

### ISSUE THREAD

**Issue by ssri28** [broadinstitute/gatk#6217]
hi team ,
i am facing issue in running DetermineGermlineContigPloidy

my cmd :  /home/ec2-user/data/gatk_cnv/gatk-4.1.4.0/gatk --java-options "-Xmx8G" DetermineGermlineContigPloidy  --contig-ploidy-priors ploidy_model/interval_list.tsv  -L preprocessed_intervals.interval_list --input sample.counts_ESI_17.hdf5  --input sample.counts_ESI_17.hdf5  --output esi_ploidy --output-prefix esi_cnvploidy --verbosity DEBUG

ERROR: 
Using GATK jar /home/ec2-user/data/gatk_cnv/gatk-4.1.4.0/gatk-package-4.1.4.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx8G -jar /home/ec2-user/data/gatk_cnv/gatk-4.1.4.0/gatk-package-4.1.4.0-local.jar DetermineGermlineContigPloidy --contig-ploidy-priors ploidy_model/interval_list.tsv -L preprocessed_intervals.interval_list --input sample.counts_ESI_17.hdf5 --input sample.counts_ESI_17.hdf5 --output esi_ploidy --output-prefix esi_cnvploidy --verbosity DEBUG
08:48:45.706 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/ec2-user/data/gatk_cnv/gatk-4.1.4.0/gatk-package-4.1.4.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
08:48:45.729 DEBUG NativeLibraryLoader - Extracting libgkl_compression.so to /tmp/libgkl_compression2796572893882405738.so
Oct 17, 2019 8:48:45 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
08:48:45.917 INFO  DetermineGermlineContigPloidy - ------------------------------------------------------------
08:48:45.918 INFO  DetermineGermlineContigPloidy - The Genome Analysis Toolkit (GATK) v4.1.4.0
08:48:45.918 INFO  DetermineGermlineContigPloidy - For support and documentation go to https://software.broadinstitute.org/gatk/
08:48:45.918 INFO  DetermineGermlineContigPloidy - Executing as ec2-user@ip-172-31-4-142.us-east-2.compute.internal on Linux v4.14.133-113.105.amzn2.x86_64 amd64
08:48:45.918 INFO  DetermineGermlineContigPloidy - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_222-b10
08:48:45.919 INFO  DetermineGermlineContigPloidy - Start Date/Time: October 17, 2019 8:48:45 AM UTC
08:48:45.919 INFO  DetermineGermlineContigPloidy - ------------------------------------------------------------
08:48:45.919 INFO  DetermineGermlineContigPloidy - ------------------------------------------------------------
08:48:45.919 INFO  DetermineGermlineContigPloidy - HTSJDK Version: 2.20.3
08:48:45.919 INFO  DetermineGermlineContigPloidy - Picard Version: 2.21.1
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.BUFFER_SIZE : 131072
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.COMPRESSION_LEVEL : 2
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.CREATE_INDEX : false
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.CREATE_MD5 : false
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.CUSTOM_READER_FACTORY :
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.DISABLE_SNAPPY_COMPRESSOR : false
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.EBI_REFERENCE_SERVICE_URL_MASK : https://www.ebi.ac.uk/ena/cram/md5/%s
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.NON_ZERO_BUFFER_SIZE : 131072
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.REFERENCE_FASTA : null
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.SAM_FLAG_FIELD_FORMAT : DECIMAL
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
08:48:45.921 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
08:48:45.922 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
08:48:45.922 INFO  DetermineGermlineContigPloidy - HTSJDK Defaults.USE_CRAM_REF_DOWNLOAD : false
08:48:45.922 DEBUG ConfigFactory - Configuration file values:
08:48:45.927 DEBUG ConfigFactory -      gcsMaxRetries = 20
08:48:45.927 DEBUG ConfigFactory -      gcsProjectForRequesterPays =
08:48:45.927 DEBUG ConfigFactory -      codec_packages = [htsjdk.variant, htsjdk.tribble, org.broadinstitute.hellbender.utils.codecs]
08:48:45.927 DEBUG ConfigFactory -      gatk_stacktrace_on_user_exception = false
08:48:45.927 DEBUG ConfigFactory -      samjdk.use_async_io_read_samtools = false
08:48:45.927 DEBUG ConfigFactory -      samjdk.use_async_io_write_samtools = true
08:48:45.927 DEBUG ConfigFactory -      samjdk.use_async_io_write_tribble = false
08:48:45.927 DEBUG ConfigFactory -      samjdk.compression_level = 2
08:48:45.927 DEBUG ConfigFactory -      spark.kryoserializer.buffer.max = 512m
08:48:45.927 DEBUG ConfigFactory -      spark.driver.maxResultSize = 0
08:48:45.927 DEBUG ConfigFactory -      spark.driver.userClassPathFirst = true
08:48:45.927 DEBUG ConfigFactory -      spark.io.compression.codec = lzf
08:48:45.927 DEBUG ConfigFactory -      spark.executor.memoryOverhead = 600
08:48:45.927 DEBUG ConfigFactory -      spark.driver.extraJavaOptions =
08:48:45.928 DEBUG ConfigFactory -      spark.executor.extraJavaOptions =
08:48:45.928 DEBUG ConfigFactory -      read_filter_packages = [org.broadinstitute.hellbender.engine.filters]
08:48:45.928 DEBUG ConfigFactory -      annotation_packages = [org.broadinstitute.hellbender.tools.walkers.annotator]
08:48:45.928 DEBUG ConfigFactory -      cloudPrefetchBuffer = 40
08:48:45.928 DEBUG ConfigFactory -      cloudIndexPrefetchBuffer = -1
08:48:45.928 DEBUG ConfigFactory -      createOutputBamIndex = true
08:48:45.928 INFO  DetermineGermlineContigPloidy - Deflater: IntelDeflater
08:48:45.928 INFO  DetermineGermlineContigPloidy - Inflater: IntelInflater
08:48:45.928 INFO  DetermineGermlineContigPloidy - GCS max retries/reopens: 20
08:48:45.928 INFO  DetermineGermlineContigPloidy - Requester pays: disabled
08:48:45.928 INFO  DetermineGermlineContigPloidy - Initializing engine
08:48:45.931 DEBUG ScriptExecutor - Executing:
08:48:45.931 DEBUG ScriptExecutor -   python
08:48:45.932 DEBUG ScriptExecutor -   -c
08:48:45.932 DEBUG ScriptExecutor -   import gcnvkernel

WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
/home/ec2-user/miniconda3/envs/gatk/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
08:48:50.351 DEBUG ScriptExecutor - Result: 0
08:48:50.351 INFO  DetermineGermlineContigPloidy - Done initializing engine
08:48:50.352 INFO  DetermineGermlineContigPloidy - Shutting down engine
[October 17, 2019 8:48:50 AM UTC] org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=597164032
java.lang.IllegalArgumentException: List of input read-count files cannot contain duplicates.
        at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:725)
        at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.validateArguments(DetermineGermlineContigPloidy.java:304)
        at org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.doWork(DetermineGermlineContigPloidy.java:277)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)

Kindly help me in fixing the issue

**Comment by samuelklee** [comment]
Thanks for trying out the tool, @ssri28.  The exception message states that “List of input read-count files cannot contain duplicates,” so that would be the first thing to check.  Since we are either building a model or calling ploidy from the count files, it doesn’t make sense to allow duplicates.

The support forums at https://gatkforums.broadinstitute.org/ are a better place for getting help with running the tools and diagnosing exceptions.  GitHub issues should be reserved for bug reports and feature requests.

**Comment by ssri28** [comment]
Hi Samuel,

Thanks for the reply.

I have fixed that issue.
i am getting new issue while running "DetermineGermlineContigPloidy"

Commandline: /home/ec2-user/data/gatk_cnv/gatk-4.1.4.0/gatk
 DetermineGermlineContigPloidy  --contig-ploidy-priors
ploidy_model/interval_list.tsv --interval-merging-rule OVERLAPPING_ONLY  -L
preprocessed_intervals.interval_list --input sample.counts_ESI_17.tsv
 --input sample.counts_ES_msc.tsv  --output esi_ploidy --output-prefix
esi_cnvploidy --verbosity DEBUG

Error:
/home/ec2-user/miniconda3/envs/gatk/lib/python3.6/site-packages/h5py/__init__.py:36:
FutureWarning: Conversion of the second argument of issubdtype from `float`
to `np.floating` is deprecated. In future, it will be treated as
`np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/tmp/cohort_determine_ploidy_and_depth.4606632406719651975.py",
line 87, in <module>
    sample_metadata_collection, args.sample_coverage_metadata)
  File
"/home/ec2-user/miniconda3/envs/gatk/lib/python3.6/site-packages/gcnvkernel/io/io_metadata.py",
line 78, in read_sample_coverage_metadata
    sample_name, n_j, contig_list))
  File
"/home/ec2-user/miniconda3/envs/gatk/lib/python3.6/site-packages/gcnvkernel/structs/metadata.py",
line 227, in add_sample_coverage_metadata
    'Sample "{0}" already has coverage metadata
annotations'.format(sample_name))
gcnvkernel.structs.metadata.SampleAlreadyInCollectionException: Sample "$1"
already has coverage metadata annotations
10:40:30.979 DEBUG ScriptExecutor - Result: 1
10:40:30.980 INFO  DetermineGermlineContigPloidy - Shutting down engine
[October 17, 2019 10:40:30 AM UTC]
org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy
done. Elapsed time: 0.93 minutes.
Runtime.totalMemory()=3354918912
org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException:
python exited with 1
Command Line: python /tmp/
cohort_determine_ploidy_and_depth.4606632406719651975.py
--sample_coverage_metadata=/tmp/samples-by-coverage-per-contig5098057453977783950.tsv
--output_calls_path=/home/ec2-user/data/human_exome/esi_ploidy/esi_cnvploidy-calls
--mapping_error_rate=1.000000e-02 --psi_s_scale=1.000000e-04
--mean_bias_sd=1.000000e-02 --psi_j_scale=1.000000e-03
--learning_rate=5.000000e-02 --adamax_beta1=9.000000e-01
--adamax_beta2=9.990000e-01 --log_emission_samples_per_round=2000
--log_emission_sampling_rounds=100
--log_emission_sampling_median_rel_error=5.000000e-04
--max_advi_iter_first_epoch=1000 --max_advi_iter_subsequent_epochs=1000
--min_training_epochs=20 --max_training_epochs=100
--initial_temperature=2.000000e+00 --num_thermal_advi_iters=5000
--convergence_snr_averaging_window=5000
--convergence_snr_trigger_threshold=1.000000e-01
--convergence_snr_countdown_window=10 --max_calling_iters=1
--caller_update_convergence_threshold=1.000000e-03
--caller_internal_admixing_rate=7.500000e-01
--caller_external_admixing_rate=7.500000e-01 --disable_caller=false
--disable_sampler=false --disable_annealing=false
--interval_list=/tmp/intervals1150776469766824519.tsv
--contig_ploidy_prior_table=/home/ec2-user/data/human_exome/ploidy_model/interval_list.tsv
--output_model_path=/home/ec2-user/data/human_exome/esi_ploidy/esi_cnvploidy-model
        at
org.broadinstitute.hellbender.utils.python.PythonExecutorBase.getScriptException(PythonExecutorBase.java:75)
        at
org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:126)
        at
org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeArgs(PythonScriptExecutor.java:170)
        at
org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:151)
        at
org.broadinstitute.hellbender.utils.python.PythonScriptExecutor.executeScript(PythonScriptExecutor.java:121)
        at
org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.executeDeterminePloidyAndDepthPythonScript(DetermineGermlineContigPloidy.java:411)
        at
org.broadinstitute.hellbender.tools.copynumber.DetermineGermlineContigPloidy.doWork(DetermineGermlineContigPloidy.java:288)
        at
org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)
        at
org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
        at
org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
        at
org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
        at org.broadinstitute.hellbender.Main.main(Main.java:292)

Kindly give your inputs..

Thanks
Sridhar

**Comment by samuelklee** [comment]
From the new message you are getting (Sample "$1" already has coverage metadata annotations), I’m guessing that both of your samples have the same name (“$1”).  I would fix this upstream in the BAM.

Again, the forum is a better place for this kind of discussion, as other users can benefit from seeing discussion as well as previous posts—GitHub issues lose a lot of visibility once they are closed.

**Comment by ssri28** [comment]
Hi Sam,
Thanks for reply..
could you help me in creating apost in GATK forum..

I am searching it, couldnt find the link to post the  issues.

**Comment by samuelklee** [comment]
@ssri28 you should be able to find that information on the GATK forum website once you register.  I'm afraid I can't help you further here on GitHub.
