### ISSUE TITLE
GATK somatic CNV caller generates unexpected plot of denoisedCR

### ISSUE THREAD

**Issue by jaybee84** [broadinstitute/gatk#6225]
### Affected tool(s) or class(es)
_Somatic CNV caller_

### Affected version(s)
- [ ] https://hub.docker.com/r/broadinstitute/gatk/

### Description 
_I am following the steps outlined here: https://gatkforums.broadinstitute.org/gatk/discussion/11682 to generate copy number variation plots. When I execute the steps using the example data I am able to generate plots similar to example plots noted on the page. But the plots I generate using my own datafiles do not look as expected. 

Main differences between example data and experimental data processing : 
1. Reference genome : GRCh37 (instead of GRCh38 in example)_

#### Steps to reproduce
_1. Reference genome : GRCh37 (instead of GRCh38 in example)
2. WES sample_

#### Expected behavior
_Expected plot :
![test denoisedLimit4](https://user-images.githubusercontent.com/17917521/67444546-66df1c80-f5be-11e9-8887-26f7b07717b8.png)
_

#### Actual behavior
_
![experimental_datafile_plot denoisedLimit4](https://user-images.githubusercontent.com/17917521/67444584-9726bb00-f5be-11e9-9a0f-4a68717a0fd5.png)
_

----

**Comment by ldgauthier** [comment]
Given that this is not a bug, this question is more appropriate for the GATK forum (http://gatkforums.broadinstitute.org/gatk), where all users can benefit from the discussion.
