### ISSUE TITLE
GATKRead.copy() should guarantee a deep copy

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#623]
Currently `GATKRead.copy()` is unable to guarantee a deep copy, since we only have a deep copy method for Google `Read`s (`GenericData.clone()`, which it inherits), not `SAMRecord`s. We should write a deep copy method for `SAMRecord`, hook it up to the `GATKRead.copy()` implementation in `SAMRecordToGATKReadAdapter`, and change the method contract to guarantee that a deep copy will be performed.

This is not a huge priority, since `GATKRead` already guarantees that defensive copies will be made of all mutable reference types returned from accessor methods (which means that shallow copies should be safe to use freely), but would be nice for consistency and peace of mind.

**Comment by cmnbroad** [comment]
PR for the first part (underlying SAMRecord) change is submitted. When that is approved I'll update the Hellbender code.

**Comment by akiezun** [comment]
@cmnbroad can you include the pr number here?

**Comment by cmnbroad** [comment]
The htsjdk PR is [#317](https://github.com/samtools/htsjdk/pull/317). We'll also need a small change in gatk once we have the new htsjdk version.

**Comment by droazen** [comment]
@cmnbroad This one is unblocked now, and should be a very quick change. Since changing `copy()` into a deep copy method might hurt the performance of things like the read clipper, recommend adding a separate method `deepCopy()` to `GATKRead`.

**Comment by cmnbroad** [comment]
PR is https://github.com/broadinstitute/gatk/pull/1194

**Comment by cmnbroad** [comment]
Closed via #1194.
