### ISSUE TITLE
GATKRead implementations should have consistent toString() output

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#624]
All implementations of `GATKRead` should ideally agree on String representation -- the adapter classes should all implement `toString()`, and do so consistently.

**Comment by lbergelson** [comment]
I assume this can't be implemented by the interface itself because of the default methods are always overridden issue?

**Comment by droazen** [comment]
Re-assigning to @akiezun -- could you make `toString()` consistent between `SAMRecordToGATKReadAdapter` and `GoogleGenomicsToGATKReadAdapter`? For display purposes only -- something like "read_name contig:start-end" would be fine.
