### ISSUE TITLE
GATK 3.7 DepthOfCoverage

### ISSUE THREAD

**Issue by fanyucai1** [broadinstitute/gatk#6259]
hi doctor:

I run the command as follows:
java -Xmx40g -jar /software/gatk/3.7/GenomeAnalysisTK.jar -T DepthOfCoverage -allowPotentiallyMisencodedQuals --minBaseQuality 20 --minMappingQuality 20 -R /data/Database/hg19/ucsc.hg19.fasta -I 27_NC_T.sort.rmdup.recal.bam -o test -ct 150 -ct 200 -ct 250 -ct 500 -ct 1000 -ct 10000 -ct 50000 -L target.interval_list

The output as follows:
sample_id	total	mean	granular_third_quartile	granular_median	granular_first_quartile	%_bases_above_150	%_bases_above_200	%_bases_above_250	%_bases_above_500	%_bases_above_1000	%_bases_above_10000	%_bases_above_50000
27_NC_T	208310963	1425.11	500	500	500	86.2	84.5	83.1	78.2	78.2	78.2	78.2
Total	208310963	1425.11	N/A	N/A	N/A
##############
my question is :the result "%_bases_above_10000" and "%_bases_above_50000" are the same.
in fact, my data not sequencing 10000? why?

could you help me?

Thanks!

**Comment by lbergelson** [comment]
@fanyucai1 This question should go to the [GATK forums](https://gatkforums.broadinstitute.org/gatk/categories/gatk-support-forum)
