### ISSUE TITLE
GATKstr: output GT based on posteriors rather than likelihoods.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#6269]
It he more correct thing to do (as supposed what we do know based on likelihoods alone) and DRAGstr depends on this feature. 

Currently we choose  the alleles in the GT by taken the genotype that have the largest likelihood ignoring priors on genotypes (or allele frequencies) and the fact that unphase GT means that the het likelihood it supposed to be doubled (as part of the posterior calculation). For that reason is possible that we currently have some small bias against hets although is is only with low depth alignments.

**Comment by ldgauthier** [comment]
If Dragen is single-sample then does it take a population allele frequency resource to calculate priors?

**Comment by vruano** [comment]
They have a single sample formula based on ther STR score recalibration which generates a table for GOP/GCP for the pairHMM and another for the prior of the indel het at STR all based on period and number of repeats.

**Comment by vruano** [comment]
Their argument is that a fix prior across all sites in not accurate enough and they figure out that one can use the charactersitcis of the STR to determined a more adecuate one... ... obviously a population based prior may be more accurate... that is fair point to make and perhaps should be added to the evaluation. 
However I'm under the impression that DRAGEN's focus is on single sample self-contained analysis.

**Comment by vruano** [comment]
It seems that this issues is again relevant considering recent discussion including @eitanbanks and @jamesemery.

Now in DRAGEN mode we use posteriors to determine QUAL and  GT as does DRAGEN. However this is not so by default, and can be activated independently using the argument  ```--use-posteriors-to-calculate-qual``` and ```--genotype-assignment-method  USE_POSTERIOR_PROBABILITIES``` respectively.

**Comment by eitanbanks** [comment]
Oh, wait.  So the default is NOT to assign the GT based on the posteriors but rather based on the likelihoods?  Ok, then I'm happy with that!

I would like to request a few changes to the fields we emit now for variant positions:

1. we have a way to turn off the emission of the GP and PG tags and just have the PLs.  Or maybe the default should be that we don't emit them and there's a flag used to include them?
2. We use the PP (phred-scaled posterior) instead of GP.  GPs are floats and I'd rather have ints.
3. I don't think we need the GP (priors) and also the PL and PP, since the priors could be derived from the other two.

@ldgauthier WDYT here?

**Comment by vruano** [comment]
PL based genotyping is the  default for "vanilla" GATK, but the default for DRAGEN-GATK (with --dragen-mode on) is to use the posteriors.

**Comment by eitanbanks** [comment]
I see.  Is there **anything** population-based in the priors used by the dragen mode?  I'm thinking that if there isn't then we should consider them to be likelihoods still and not posteriors.

**Comment by jamesemery** [comment]
It is the default if you invoke the "--dragen-mode" argument which sets it. It could be uncoupled however. 

To add a few questions to your comments @eitanbanks and @ldgauthier: 
1. If we are excluding the GP and PG tags and only emitting the GLs should in that case we select the genotype based on the posteriors (it also computes the QUAL score for the variant based on the posteriors) should we not use the those for your use case? This would be different from what DRAGEN does if we are shooting for concordance. Empirically using newQUAL for qual calcuations in tandem with dragen produced worse results than just relying on DRAGNE for single sample but we could still use the same principle for quals. Alternatively we could just scrub those fields from the genotype annotation but still use them for genotype selection and QUAL calculations. 
3. It seems perfectly reasonable to include only two outputs would it be more concise to include the PL and the priors that were applied?

**Comment by vruano** [comment]
Their SNP priors are based on a point estimate of 1/1000 of being variant 0/1 or 1/1 and the 10^-3 is split between 0/1 1/1 with a 2:1 ratio. This is perhaps based on an empirical observation that the "average" human variant sites have a 2:1 het to hom-var ratio or simply to implement a flat prior between these two genotypes as there are two way to be a het and only one to be a hom-var. This is in high contrast with our vanilla priors which are based a AF prior and HardyWeinberg  so HET would be roughtly 1/1000 and hom-var 1/1000000 !!! if the ratio of het to hom-var in the "average" human is close to 2:1 rather than 1000:1 then they are more right that we are. 

The indel priors are based on their per-sample recalibration. 

Priors are priors however simplistic or synthetic they are. And the posteriors are posterior the same. But yes, a more informative and correct prior should yield better posteriors.

Answering to @ldgauthier old question (that I didn't really answer back then :P), I'm not aware if there is the possibility of provide a pop prior in DRAGEN, but is possible and a reasonable request.

Now, the DRAGEN priors can be reconstructed from the reference sequence at the site, a couple of single value arguments and  the DRAGstr model parameters that seats in a separate file (perhaps could be enclosed in the VCF header to make the vcf selfcontained). 

The GP or (PP) is derived from PL and those priors so you don't really need those in the output.

Another matter is the value that we use for the QUAL and the GT calls. Something that we have been doing wrong in vanilla GATK is to use the PL to fill GT (and perhaps GQ but I think that the VCF spec may be asking to do it that way not sure). Because it makes more (and perhaps only) sense to use posterior genotype probs to do so. By using the max PL we effectively setting a highly unrealistic flat uniform prior across genotypes. This only has a GT-noticeable effect on low coverage data though.

For QUAL, vanilla GATK does also uses posteriors, but basedvon alt. AF posteroprs rather than DRAGEN genotype posteriors approach. Both are reasonable ways to calculate QUAL and under some conditions they would converge to the same value but they are not equivalent in general.

I think that @eitanbanks points 1. 2. are reasonable request at least as option for the vanilla GATK but for DRAGEN-GATK I guess it should be approved by Illumina. Point 3. I think there might be a few typos.

**Comment by ldgauthier** [comment]
ReblockGVCF (which we run in production) will revert to PLs, so this behavior is irrelevant in the warp pipelines
