### ISSUE TITLE
if FASTEST_AVAILABLE is the recommended choise for --smith-watername, why isn't it the default?

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/gatk#6281]
from `org.broadinstitute.barclay.argparser.Argument`:
```java
    @Argument(fullName = SMITH_WATERMAN_LONG_NAME, doc = "Which Smith-Waterman implementation to use, generally FASTEST_AVAILABLE is the right choice", optional = true)
    public SmithWatermanAligner.Implementation smithWatermanImplementation = SmithWatermanAligner.Implementation.JAVA;
```

**Comment by droazen** [comment]
@yfarjoun We don't have continuous tests for the native SmithWaterman (since we don't have the ability to request the necessary hardware in travis), and so we didn't feel comfortable making it the default for that reason.

**Comment by yfarjoun** [comment]
is that the same for the pairHMM?

**Comment by droazen** [comment]
@yfarjoun The native PairHMM requires only AVX1, which is on pretty much all cloud CPUs at this point, so it can be (and is) tested in Travis. The native SmithWaterman requires AVX2, which is only on Skylake or newer CPUs -- and travis does not provide a way to request the required architectures, unfortunately.

**Comment by droazen** [comment]
Closing as answered
