### ISSUE TITLE
Mitochondria WDL still has genotyping-mode argument that no longer exists

### ISSUE THREAD

**Issue by meganshand** [broadinstitute/gatk#6286]
### Affected tool(s) or class(es)
Mitochondria WDL

### Affected version(s)
- [x] Latest public release version [version?]
- [x] Latest master branch as of [date of test?]

### Description 
Mitochondria WDL still has `--genotyping-mode` argument: https://github.com/broadinstitute/gatk/blob/master/scripts/mitochondria_m2_wdl/AlignAndCall.wdl#L420

This argument doesn't exist in GATK version 4.1.1.0 (which is the one that is currently being used in the mitochondria WDL), so this argument should be changed to the new force-call argument which was added in #6090

**Comment by ldgauthier** [comment]
Does that mean we're missing variants?  Or is no one actually running this exact WDL version?

**Comment by meganshand** [comment]
No one is using the GGA argument as far as I know.
