### ISSUE TITLE
SelectVariants hangs while selecting INDEL type

### ISSUE THREAD

**Issue by xiucz** [broadinstitute/gatk#6291]
I think it is a BUG, so I report it here.

I am dealing with a vcf of 748k to seprate INDEL type. But it is hanging for two days... 

```
~/gatktools/gatk-4.1.3.0/gatk SelectVariants \
-R ~/hg19/gatk_bundle/ucsc.hg19.fasta \
-select-type INDEL --variant CS19005_mutect2_filter.vcf.txt \
-O MCS19005_indel.vcf --tmp-dir tmp3
```

[CS19005_mutect2.filtered.vcf.txt](https://github.com/broadinstitute/gatk/files/3899649/CS19005_mutect2.filtered.vcf.txt)
 
Xiucz

**Comment by xiucz** [comment]
I try gatk3.7, it works:
```
java -jar  ~/software/gatktools/GenomeAnalysisTK.jar \
-T SelectVariants  -R ~/gatk_bundle/ucsc.hg19.fasta \
-V CS19005_mutect2_filter.vcf.txt  -selectType INDEL \
-o ttt.vcf
```

**Comment by cmnbroad** [comment]
Looks like the input file is a tumor sample with a handful of sites that have lots of alternate alleles (12-16). This in turn causes `GenotypeLikelihoods.calculatePLIndexToAlleleIndices` (which was added  to SV in GATK3 so it would handle non-diploid) to create millions and millions of PL index lists. Interestingly, this code is also in GATK 3, and I get the same results (hanging for a long time) with 3.8.1.

**Comment by davidbenjamin** [comment]
@lbergelson This is failing on an M2 input.  I can fix this.
