### ISSUE TITLE
ReadPosRankSumTest with leading insertions

### ISSUE THREAD

**Issue by kachulis** [broadinstitute/gatk#6294]
For an insertion variant, if a read provides evidence for the variant through a leading insertion, the ReadPosRankSumTest will ignore that read in the calculation of the annotation.  This is because `ReadUtils.getReadCoordinateForReferenceCoordinate` will return `ReadUtils.CLIPPING_GOAL_NOT_REACHED` in this case, which will cause the read to be skipped for the purposes of the annotation.  As a result, a variant where all the evidence is from leading insertions will have no ReadPosRankSum annotation calculated, even though this annotation should in that case provide strong evidence of an artifact.

**Comment by davidbenjamin** [comment]
@kachulis i'm working on a related bug.  It makes sense to bring this into that effort.
