### ISSUE TITLE
Why only java 8?

### ISSUE THREAD

**Issue by lucaspompeun** [broadinstitute/gatk#6298]
Why the software only works on java8 and not in java11?
I don't know the explanation, but seems to be an interesting thing to know.
Thanks

**Comment by lbergelson** [comment]
There are pretty significant incompatibilities between java 8 and 11 that make it hard to run the same code on both.  It affects a number of our dependencies which use features which were removed/altered from java 8 -> 11.  Unfortunately despite there being significant pain in switching to 11 there aren't particularly compelling new features after 8 so there isn't much incentive for developers to move forward.

That said, you CAN now run gatk on java 11 if you build it using java 11, the jars built on 8 are incompatible with 11 and vice a versa.  We consider running on 11 to be a beta feature and would love to hear feedback about either success or failure.
