### ISSUE TITLE
Documentation about mutect2 flags

### ISSUE THREAD

**Issue by HarshpreetChandok** [broadinstitute/gatk#6308]
Hello All,
Is there a detailed manual or documentation available explaining all the flags/filters applied by Mutect2?
For example: bad_haplotype, germline_risk, str_contraction, and many more.
It would be good to understand the principle or rationale behind assigning flags to variants which would help us eventually customize and filter the variants required as per the analysis.

**Comment by HarshpreetChandok** [comment]
Hello All,
Is there a detailed manual or documentation available explaining all the flags/filters applied by Mutect2?
For example: bad_haplotype, germline_risk, str_contraction, and many more.
It would be good to understand the principle or rationale behind assigning flags to variants which would help us eventually customize and filter the variants required as per the analysis.

**Comment by davidbenjamin** [comment]
@HarshpreetChandok 

Here's our documentation: https://github.com/broadinstitute/gatk/blob/master/docs/mutect/mutect.pdf

And here's our preprint: https://www.biorxiv.org/content/10.1101/861054v1
