### ISSUE TITLE
Mutect2 error when trying to create fragment with no read support

### ISSUE THREAD

**Issue by avalind** [broadinstitute/gatk#6310]
### Affected tool(s) or class(es)
_Mutect2_

### Affected version(s)
- GATK 4.1.4.1

### Description 
When running Mutect2 (from GATK v4.1.4.1) using the following command:

`gatk Mutect2 -R [path to grch37-1kg.fa] -I testcase.bam -O pon.vcf`

 to create a PoN on NovaSeq WGS-data processed through the best practice pipeline (with the BQSR-steps run through the Spark-enabled tools, and bwa mem with -Y flag) I get the following error in multiple regions:

[Stacktrace](https://www.dropbox.com/s/d2n5zflj9u11oj8/stacktrace.png?dl=0)

AFAIK this is related to the new code path introduced in #6240 and seem to be triggered when there are more than 2 reads supporting a fragment but all of them are either duplicate reads or supplemntary/secondary alignments.

Any input is greatly appreciated. I guess a temporary fix is to use the --independent-mates flag (although haven't tried it yet -- how much worse mutation calling performance do one incur when using that flag?)

#### Steps to reproduce
Use the following small test case .bam-file as input to the command specified above:

[Testcase](https://www.dropbox.com/s/hilcj3aj0jnjdmh/testcase.bam?dl=0)

#### Expected behavior
Completion of mutect2 without Exception

#### Actual behavior
Early termination of the mutect2 run due to raising an exception when trying to create a fragment with no read data to back it up.

----

**Comment by johnsCheng** [comment]
here i change the gatk-4.1.4.1 to gatk-4.1.2.0，then Mutect can work， 
I am not sure what the issue involved. But it keeps reporting the error 'need one or two reads to create fragment' before, however, what i input are totally paired reads after markduplication.

**Comment by droazen** [comment]
@davidbenjamin I've assigned this one to @KevinCLydon just so he can get some experience debugging GATK -- he may consult you at some point on recommended solutions.

**Comment by davidbenjamin** [comment]
Closed by #6327.
