### ISSUE TITLE
Germline CNV result visualization and further analysis.

### ISSUE THREAD

**Issue by xysj1989** [broadinstitute/gatk#6320]
Dear developer,

I have finished the pipeline of gCNV caller in GATK and get the VCF file for each samples. To make further analysis, are there any functions or codes from GATK which can:
(1) make segmentation and generate plots for results from  germline CNV caller, just like for somatic CNV caller? e.g.(https://software.broadinstitute.org/gatk/documentation/article?id=11682)?

(2) detect the LOH, estimate sample purity for germline CNV?

(3) give the exact breakpoints of a CNV result, not just a bin.

Best.

**Comment by ldgauthier** [comment]
The segments VCFs contain the event segmentation results for each sample.  Exact breakpoints are not given by this tool. Plots can be made using the denoised copy ratio TSV outputs.  Currently our germline workflow does not incorporate the B-allele frequency evidence required for LOH detection, although that's a future goal.
