### ISSUE TITLE
Intel-optimized tensorflow package specified in the conda env doesn't work on osx-64

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#6325]
The tensorflow package specified in gatkcondaenv.yml.template is linux-64 specific. The anaconda page lists a separate artifact for osx-64, which means we either need a platform-independent way to specify the intel-optimized package, or we need a separate conda env for osx.

**Comment by ldgauthier** [comment]
@bhanugandham I didn't see this in the conda setup article, but presumably it's a relatively common issue.

**Comment by bhanugandham** [comment]
good to know, thank you @ldgauthier

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/5026.
