### ISSUE TITLE
Mutect2 occasionally writes nonsense / invalid values for MPOS info tag

### ISSUE THREAD

**Issue by daviesrob** [broadinstitute/gatk#6342]
### Affected tool(s) or class(es)
Mutect2

### Affected version(s)
- [x] Latest public release version [4.1.4.1]
- [ ] Latest master branch as of [date of test?]

### Description 
Mutect2 occasionally writes lines including INFO tag `MPOS=-2147483648`.  This doesn't look sensible for "median distance from end of read", and the specific value is disallowed in [section 1.3 of the VCF specification](https://samtools.github.io/hts-specs/VCFv4.3.pdf).

I've had a quick look at the code, and think the dubious value may be generated in [ReadPosition::getValueForRead](https://github.com/broadinstitute/gatk/blob/946f39/src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosition.java#L57) when the result from [ReadPosRankSumTest.getReadPosition](https://github.com/broadinstitute/gatk/blob/946f39/src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosRankSumTest.java#L53) is cast to an `int`.  Looking at that function, it can [return `INVALID_ELEMENT_FROM_READ`](https://github.com/broadinstitute/gatk/blob/946f39/src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/ReadPosRankSumTest.java#L62) which is [defined as `Double.NEGATIVE_INFINITY`](https://github.com/broadinstitute/gatk/blob/946f39/src/main/java/org/broadinstitute/hellbender/tools/walkers/annotator/RankSumTest.java#L23).  According to the [java documentation](https://docs.oracle.com/javase/specs/jls/se7/html/jls-5.html#jls-5.1.3), casting NEGATIVE_INFINITY to int will result in a value of `INT_MIN`.  (Disclaimer: I haven't tested this, so it may be completely wrong...)

#### Steps to reproduce
See attached .zip file which includes a smallish bam file that shows the problem.  I ran mutect2 on it in the Docker container for the latest GATK release:
```sh
unzip mpos_issue.zip
cd mpos_issue
../gatk Mutect2 --input input/small.bam --reference input/small.fa --output small.vcf
grep MPOS=- small.vcf
```

#### Expected behavior
`MPOS` should have a sensible value.

#### Actual behavior
```
ref|NC_001224|	12835	.	A	AATAT	.	.	DP=2810;ECNT=5;MBQ=20,34;MFRL=185,202;MMQ=60,29;MPOS=-2147483648;POPAF=7.30;TLOD=3.04	GT:AD:AF:DP:F1R2:F2R1:PGT:PID:PS:SB	0|1:2804,3:1.431e-03:2807:1316,3:1412,0:0|1:12828_AATAC_A:12828:1200,1604,2,1
```

----

[mpos_issue.zip](https://github.com/broadinstitute/gatk/files/4014487/mpos_issue.zip)

**Comment by adrlar** [comment]
I am having an issue with the same bug, where these `MPOS=-2147483648` fields are causing an error in downstream analysis. If anyone has any update or a workaround I'd appreciate it.

**Comment by DrJCampbell** [comment]
I'm also having a problem with this bug breaking downstream analysis. Using bcftools to index the vcf containing `MPOS=-2147483648` converts it to `MPOS=.`.
