### ISSUE TITLE
Add engine level argument to selectively ignore soft-clipped bases due to adapter

### ISSUE THREAD

**Issue by fleharty** [broadinstitute/gatk#6346]
### Tool(s) or class(es) involved

Engine level argument

### Description

This is a new capability.  Presently tools like Mutect2 and HaplotypeCaller ignore
soft-clipping by default.  In some sequencing products that use long reads relative
to the insert size, the reads often contain some amount of adapter.  These reads
are typically soft-clipped by upstream tools like MergeBamAlignments.

The result is an increase in false positive rates in somatic samples that have long read lengths compared to insert size.  These false positives can be eliminated using the `-no-soft-clips` option, but this ignores all soft clips regardless of why the read was soft-clipped.

The proposal here is to add a new engine level argument that will allow GATK tools to ignore soft-clips that occur at the start position of the reads mate.  This will allow tools to utilize soft-clips that may contain evidence of indels without providing support for artifactual variants due to adapter sequence.

**Comment by droazen** [comment]
@fleharty Not sure this makes sense as a GATK-wide argument -- maybe an argument to the `StandardCallerArgumentCollection` (or similar) instead?

**Comment by fleharty** [comment]
@droazen I think it's fine to be an argument to `StandardCallerArgumentCollection` instead.  The purpose is to work with tools that ingest bam files and realign reads, so HC and M2 (are there more)?

**Comment by fleharty** [comment]
Once this option in implemented, it will be important to evaluate its impact on sensitivity and FPR in the Twist Somatic Exome.

**Comment by fleharty** [comment]
Some offline discussions have led us to the conclusion that this is best handled by tools upstream.  Adapters should not be simply soft-clipped, so it shouldn't be the responsibility of M2 or HC to include logic to remove adapters.
