### ISSUE TITLE
IndexFeatureFile fails with compressed vcf on GCS

### ISSUE THREAD

**Issue by kachulis** [broadinstitute/gatk#6348]
### Affected tool(s) or class(es)
IndexFeatureFile

### Affected version(s)
- [x] Latest master branch as of [1/6/2020]

### Description 
When running IndexFeatureFile on a compressed vcf stored on GCS, tool fails, error message:

```
  A USER ERROR has occurred: Error while trying to create index for dir/file.vcf.gz. Error was: 
  htsjdk.tribble.TribbleException.FeatureFileDoesntExist: Unable to open the input file, most 
  likely the file doesn't exist., for input source: /dir/file.vcf.gz
```
  When running on an uncompressed vcf on GCS, the tool succeeds.

I've traced the issue to `SeekableStreamFactory.getStreamFor` in htsjdk, which gets called from `IndexFactory.initIndexableBlockCompressedStream` (also in htsdjk), and doesn't appear to handle GCS paths correctly.

**Comment by cmnbroad** [comment]
Closed via https://github.com/broadinstitute/gatk/pull/6462 (actually via htsjdk https://github.com/broadinstitute/gatk/pull/6367) and https://github.com/broadinstitute/gatk/pull/6367.
