### ISSUE TITLE
MarkDuplicatesSpark crash 

### ISSUE THREAD

**Issue by Dagsbio** [broadinstitute/gatk#6350]
Hello, I am getting this error when running **gatk MarkDuplicatesSpark -I file.bam -O spark.bam** :

A USER ERROR has occurred: Failed to load reads from file.bam
 Caused by:Unsupported class file major version 55

Any solutions?

Thank you.

**Comment by jamesemery** [comment]
Hello @dagsbio and thank you for your question. It sounds like there was an issue with your bam file, possibly with the header version line.  We support up through bam v1.6. You can also try running ValidateSamFile on the bam. I would recommend however that you direct your questions/troubleshooting requests to the new gatk support forum here: https://gatk.broadinstitute.org/hc/en-us/community/topics

**Comment by Dagsbio** [comment]
Thank you, but I still got the error. Will post the full thing on that link you are sending though!
