### ISSUE TITLE
Output a more infromative out of memory error for GermlineCNVCaller

### ISSUE THREAD

**Issue by asmirnov239** [broadinstitute/gatk#6362]
Right now we get the following error message when we don't supply sufficient memory:

```
org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException: 
python exited with 137
```

Ideally we would report out of memory message explicitly. Perhaps we can just catch that exception and output message that this error is likely due to insufficient memory. @cmnbroad Do you have any thoughts on this?

**Comment by lbergelson** [comment]
That's not unique to out of memory errors, I think it's the result of the process being hit with a SIGKILL so there are other reasons it could happen.  A message that suggests that it might be a memory issue but doesn't hide the actual error would be helpful in pointing people in the right direction.

**Comment by asmirnov239** [comment]
@lbergelson Right, that what I was thinking. It's a very commonly occurring issue for gCNV, so it would be a very useful message for users.

**Comment by cmnbroad** [comment]
Yes, we can pretty easily detect this exit code and generate an error message suggesting it might be an OOM issue. I'll make a PR.

**Comment by asmirnov239** [comment]
@cmnbroad Thanks!
