### ISSUE TITLE
The ReadErrorCorrector doesn't actually correct any reads when its enabled in the HaplotypeCaller

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#6365]
In doing some trials with the ReadErrorCorrector I have noticed that it apparently seems to have no impact on my results. Upon closer inspection I have found the offending lines. In `ReadErrorCorrector.correctRead(final GATKRead inputRead)` we compute the `correctedQuals` and `correctedBases` arrays and then neglect to add them to the copied read later. This needs to be fixed. 
Other issues with the class:
- It apparently slows the HaplotypeCaller down 10x
- There is no tiebreaking for hamming distance comparisons
- ^those comparisons are done non-deterministically

**Comment by droazen** [comment]
This is fixed
