### ISSUE TITLE
Tensorflow dependency 

### ISSUE THREAD

**Issue by dror27** [broadinstitute/gatk#6369]
In scripts/gatkcondaenv.yml.template,  the following line produces an error upon the initial attempt to create the conda environment:

`anaconda::tensorflow=1.12.0=mkl_py36h69b6ba0_0`

It seems that the up to date dependency should be:

`anaconda::tensorflow=1.12.0=mkl_py36h2b2bbaf_0`

To replicate, perform a clean clone, with no conda environment created yet, and then:

`$ ./gradlew localDevCondaEnv`

This will fail with:

`ResolvePackageNotFound: - anaconda::tensorflow==1.12.0=mkl_py36h69b6ba0_0 `

**Comment by ldgauthier** [comment]
This is a known issue.  See #6325

**Comment by dror27** [comment]
Sorry. my bad. Looks like my search for this one did not find the existing issue. Thanx
