### ISSUE TITLE
deprecated useNewAFCalculator is not connected to anything...documentation should change

### ISSUE THREAD

**Issue by yfarjoun** [broadinstitute/gatk#6370]
During the deprecation of the useNewAFCalculator, the input argument was disconnected and AFAICT has no effect on the running of the code. The documentation of the argument should reflect this as it currently implies that setting it to false will use the old QUAL but it's not true.

    org/broadinstitute/hellbender/tools/walkers/genotyper/GenotypeCalculationArgumentCollection.java:55
```
@Argument(fullName = "use-new-qual-calculator", shortName = "new-qual", doc = "Use the new AF model instead of the so-called exact model", optional = true)
    public boolean useNewAFCalculator = true;
```

**Comment by yfarjoun** [comment]
possibly, this argument should be removed entirely.

**Comment by droazen** [comment]
@davidbenjamin  ^^

**Comment by davidbenjamin** [comment]
I'm in favor of removing it entirely.
