### ISSUE TITLE
where to download GATK3?

### ISSUE THREAD

**Issue by wuxiaopei0509** [broadinstitute/gatk#6373]
Hi,
Where Can I download the GATK3 ,I want to use Realigner and IndelRealigner tools in GATK.However the GATK4 is not available.
Anyone who can tell me where to download the GATK3 version?
--
Thank you!--

**Comment by cmnbroad** [comment]
@wuxiaopei0509 This repo is for bugs reports and feature requests. For general help, please use the GATK forum [here](https://gatk.broadinstitute.org/hc/en-us/community/topics). Thanks.
