### ISSUE TITLE
Nightly docker images have stopped publishing

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#6386]
It looks like the travis cron task that publishes the nightly docker images hasn't run in several months.

**Comment by lbergelson** [comment]
again? bleh

**Comment by jamesemery** [comment]
I checked, it looks like the cron job scheduling failed on the 2nd or 3rd of November last year. "Next job scheduled 3 months ago" being the message. I restarted the cron job and it is apparently working now. This is concerning since if this fails again we may not notice it for months again.

**Comment by droazen** [comment]
Fixed
