### ISSUE TITLE
Add denoised copy ratio ylim option to PlotModeledSegments

### ISSUE THREAD

**Issue by taytayp** [broadinstitute/gatk#6391]
### Tool(s) or class(es) involved
gatk 4.1.4.0, PlotModeledSegments

### Description
In exploring the CNV pipeline discussed [here](https://gatkforums.broadinstitute.org/gatk/discussion/11683), I ran into an issue where some of my CNVs that were at much higher copy ratios (upwards of 20/2) were not being plotted, since it appears the R script for part of this tool only limits to a maximum copy ratio of 4. 

I think the best case would be to add an additional flag to PlotModeledSegments where a user can specify the exact height they want their output graph to go to.

Alternatively, it might be useful to determine the highest copy ratio in the supplied `modelFinal.seg` file and pass that to `SetUpPlot()`. 

I ended up rewriting part of `WriteModeledSegmentsPlot()` to use this for my own project, and this reflects my second suggestion of determining the highest ratio and plotting using that. This might not be ideal for all users, since you'll lose detail in the lower copy ratios, but I hope this is a good start!  

---  
```
WriteModeledSegmentsPlot = function(sample_name, allelic_counts_file, 
                                    denoised_copy_ratios_file, modeled_segments_file, 
                                    contig_names, contig_lengths, output_dir, output_prefix) {
  modeled_segments_df = ReadTSV(modeled_segments_file)
  max_log2_ratio = max(modeled_segments_df$LOG2_COPY_RATIO_POSTERIOR_10, 
                       modeled_segments_df$LOG2_COPY_RATIO_POSTERIOR_50,
                       modeled_segments_df$LOG2_COPY_RATIO_POSTERIOR_90)
  max_copy_ratio = (2^max_log2_ratio) + 1
  
  num_plots = ifelse(all(file.exists(c(denoised_copy_ratios_file, allelic_counts_file))), 2, 1)
  png(output_file, 12, 3.5 * num_plots, units="in", type="cairo", res=300, bg="white")
  par(mfrow=c(num_plots, 1), cex=0.75, las=1)
  
  if (file.exists(denoised_copy_ratios_file) && denoised_copy_ratios_file != "null") {
    denoised_copy_ratios_df = ReadTSV(denoised_copy_ratios_file)
    
    #transform to linear copy ratio
    denoised_copy_ratios_df[["COPY_RATIO"]] = 2^denoised_copy_ratios_df[["LOG2_COPY_RATIO"]]
    
    #determine copy-ratio midpoints
    denoised_copy_ratios_df[["MIDDLE"]] = round((denoised_copy_ratios_df[["START"]] + denoised_copy_ratios_df[["END"]]) / 2)
    
    SetUpPlot(sample_name, "denoised copy ratio", 0, max_copy_ratio, "contig", contig_names, contig_starts, contig_ends, TRUE)
    PlotCopyRatiosWithModeledSegments(denoised_copy_ratios_df, modeled_segments_df, contig_names, contig_starts)
  }
  
  if (file.exists(allelic_counts_file) && allelic_counts_file != "null") {
    allelic_counts_df = ReadTSV(allelic_counts_file)
    
    SetUpPlot(sample_name, "alternate-allele fraction", 0, 1.0, "contig", contig_names, contig_starts, contig_ends, TRUE)
    PlotAlternateAlleleFractionsWithModeledSegments(allelic_counts_df, modeled_segments_df, contig_names, contig_starts)
  }
  
  dev.off()
  
  #check for created file and quit with error code if not found
  if (!file.exists(output_file)) {
    quit(save="no", status=1, runLast=FALSE)
  }
}```

**Comment by samuelklee** [comment]
Thanks for the suggestion @taytayp!  We could also just go ahead and expose this in PlotDenoisedCopyRatios as well and only output a single plot there.  I think it would be best to expose ylim parameters set to the current range by default (to preserve current behavior and so that comparison across samples remains easy), but perhaps we can consider a flag that plots the entire range.

Perhaps we can also address things like #5748 at the same time.
