### ISSUE TITLE
Worries about the results from GATK germline Copy Number Variation calling.

### ISSUE THREAD

**Issue by xysj1989** [broadinstitute/gatk#6407]
Dear developer,

We have finished the annotation of gCNV events identified by GATK Germline Copy Number Variation calling pipeline. And we got very exciting results to find several potential susceptibility genes with published literature evidence. But another cooperative team cannot find the same results or similar frequency from the same data, based on the combination algorithm of log R Ratio and B Allele Frequency.

It seems that the GATK germline CNV calling pipeline did not use log R Ratio or B Allele Frequency method from SNP data, right? We have discussions about this, and my collogues think that potential CNV events should be supported by the log R Ratio and B Allele Frequency evidence, even though they seem look good in IGV with BAM file. Or they may be not accepted by others.

What do you think about this? Dose GATK algorithm have some advantages to ignore LRR or BAF method. Do you have some method or explanation to solve my collogues’ concerning?

Best regards.

**Comment by droazen** [comment]
@mwalker174 @samuelklee  ^^^

**Comment by mwalker174** [comment]
Thanks for your question, @xysj1989. You are right that it can be advantageous to use SNP data for CNV calling. In my experience, however, it is not of high importance in practice. Indeed we do use BAF in our structural variation pipeline, but only for the purpose identifying high-quality calls. We typically find that BAF support tends to be weak/noisy for all but the largest CNVs, so requiring SNP evidence would greatly reduce sensitivity. @samuelklee can probably shed some more light on this.

**Comment by xysj1989** [comment]
Hello @mwalker174 , 

Thank you very much for your reply. We also find the same situation that smaller CNV size may not include enough SNP for BAF segmentation. It could be the reason that other SNP-based CNV callers show poorly sensitivity.

Now, we are going to use test GATK gCNV call in Whole Exon Sequencing data. We hope to get the same exciting results like whole genome sequencing.

Best regards.
