### ISSUE TITLE
Refactor ArtificialReadUtils to make it easier to select backing implementation (SAMRecord vs. Google Read)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#641]

**Comment by akiezun** [comment]
does need to be in alpha?

**Comment by droazen** [comment]
Yeah, refactoring this class is pretty essential to our ability to write good tests.

**Comment by davidbenjamin** [comment]
@droazen Close this in light of #4166?

**Comment by droazen** [comment]
@davidbenjamin Yes, this one can be closed
