### ISSUE TITLE
Request created from: Mutect2 - Need one or two reads to construct a fragment

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#6419]
This request was created from a contribution made by D B on January 17, 2020 14:43 UTC.

Link: https://gatk.broadinstitute.org/hc/en-us/community/posts/360056339072-Mutect2-Need-one-or-two-reads-to-construct-a-fragment

--

The command I used below is able to generate the .vcf output along with its index and stats file, but my snakemake run fails to complete due to exit status (3 instead of 0). I wonder if below error is caused by trying to split the runs by chromosome and setting improper interval padding.

Thank you for your time.

------------------------------------------------------------------------------------------------------------------------------------

a) GATK version used

_The Genome Analysis Toolkit (GATK) v4.1.4.1_

b) Exact GATK commands used

_/usr/bin/time -v gatk --java-options "-Xmx10G" Mutect2 -R ../reference/indices\_010920/GRCh38.d1.vd1.fa -L chr4.bed -I chr4.bam --max-mnp-distance 0 --interval-padding 100 -O chr4.vcf.gz_

c) The entire error log if applicable.

_java.lang.IllegalArgumentException: Need one or two reads to construct a fragment_  
_at org.broadinstitute.hellbender.utils.Utils.validateArg(Utils.java:725)_  
_at org.broadinstitute.hellbender.utils.read.Fragment.create(Fragment.java:43)_  
_at org.broadinstitute.hellbender.utils.read.Fragment.createAndAvoidFailure(Fragment.java:58)_  
_at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)_  
_at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)_  
_at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)_  
_at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)_  
_at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)_  
_at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)_  
_at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)_  
_at org.broadinstitute.hellbender.utils.genotyper.AlleleLikelihoods.groupEvidence(AlleleLikelihoods.java:589)_  
_at org.broadinstitute.hellbender.tools.walkers.mutect.SomaticGenotypingEngine.callMutations(SomaticGenotypingEngine.java:93)_  
_at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2Engine.callRegion(Mutect2Engine.java:251)_  
_at org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2.apply(Mutect2.java:320)_  
_at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.processReadShard(AssemblyRegionWalker.java:308)_  
_at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:281)_  
_at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1048)_  
_at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:139)_  
_at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)_  
_at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)_  
_at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)_  
_at org.broadinstitute.hellbender.Main.mainEntry(Main.java:206)_  
_at org.broadinstitute.hellbender.Main.main(Main.java:292)_<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/4421'>Zendesk ticket #4421</a>)<br>gz#4421</i>

**Comment by bshifaw** [comment]
Hi @davidbenjamin 

Mind having a look at this ticket, a user is receiving the error above and office hours mentioned this might be an issue on our end.

**Comment by davidbenjamin** [comment]
@bshifaw I believe we fixed this in master in this PR: #6327, but we haven't released since then.  I'll close this ticket based on that assumption, but please re-open if I'm wrong.
