### ISSUE TITLE
Trio calling with GATK, LowGQ

### ISSUE THREAD

**Issue by zvaksman** [broadinstitute/gatk#6424]
I have a question on why would a trio call is not considered De novo?

I visually inspected the variant (and other variants that follow the same pattern) and from the bam file the variants are well supported (see below the vcf output) with a good number of reads supporting each genotype. The vast majority of the reads were very high qual and high mapping scores (almost all near 60). 

Based on the vcf output the reason for failure is LowGQ, but how would this fail that parameter when so many passed with similar outcomes (bellow is another variant that was called de novo).

I found this issue in a large number of variants in our cohort (several thousands of variants some of which are variants of interest in our samples.) 

 

Outputs - LowGQ (failed to call De novo)

```
chrZ yy yy A G 532.25 PASS AC=1;AF=0.167;AN=6;BaseQRankSum=0.362;ClippingRankSum=-1.980e-01;DB;DP=101;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.167;MQ=59.54;MQRankSum=0.329;PG=0,0,0;QD=14.78;RAW_MQ=127600.00;ReadPosRankSum=-2.960e-01;SOR=0.542;VQSLOD=3.50 GT:AD:DP:FT:GQ:JL:JP:PL:PP 0/0:24,0:24:lowGQ:0:59:3:0,60,734:0,0,674 0/0:41,0:41:PASS:34:59:3:0,91,1289:0,34,1232 0/1:13,23:36:PASS:99:59:3:541,0,274:484,0,334

chrZ yy yy A G 342.25 PASS AC=1;AF=0.167;AN=6;BaseQRankSum=1.47;ClippingRankSum=0.825;DP=99;ExcessHet=3.0103;FS=5.073;MLEAC=1;MLEAF=0.167;MQ=60.00;MQRankSum=-8.590e-01;PG=0,0,0;QD=9.78;RAW_MQ=129600.00;ReadPosRankSum=1.26;SOR=1.623;VQSLOD=14.90;culprit=MQ .  GT:AD:DP:FT:GQ:JL:JP:PL:PP .  0/0:42,0:42:PASS:51:59:3:0,108,1620:0,51,1563 0/0:21,0:21:lowGQ:0:59:3:0,60,690:0,0,630 0/1:21,14:35:PASS:99:59:3:351,0,575:294,0,635

```

 

Output - call trio (passed to call De novo)

```
chrZ yy1 yy1 C CA 46.57 PASS 90.07 PASS C=1;AF=0.167;AN=6;BaseQRankSum=-6.930e-01;ClippingRankSum=-3.900e-01;DP=120;ExcessHet=3.0103;FS=0.000;MLEAC=1;MLEAF=0.167;MQ=60.00;MQRankSum=-8.800e-02;PG=0,0,0;QD=9.89;RAW_MQ=154800.00;ReadPosRankSum=-7.180e-01;SOR=0.709;VQSLOD=14.67;culprit=MQ;hiConfDeNovo=BS_RMKCB0F4   GT:AD:DP:GQ:JL:JP:PGT:PID:PL:PPGT:AD:DP:GQ:JL:JP:PL:PP 0/0:38,0:38:40:97:37:0,100,1120:0,40,1060 0/0:39,0:39:42:97:37:0,102,1165:0,42,1105 0/1:22,20:42:99:97:37:424,0,494:364,0,554 
```

**Comment by ldgauthier** [comment]
In the top examples, the posterior genotype probabilities for the second sample give it GQ0.  Presumably this is a parent and without a confident homRef call in the parent we don't call this variant de novo.  What is the CalculateGenotypePosteriors command you're using?

**Comment by zvaksman** [comment]
Thanks for the reply, the command we are using is listed below. Yes it was a parent that was called LowGQ however, why would that be so? I inspected the variants manually and did a pileup (the mapping quality was very good (mostly 60), base qualities scores were 30+ for most. There are sufficient reads supporting each genotype. What would be the reason? I looked through the manual and explanations and I cant come up with one. 

Also, the two variants are in two different individuals, in my study (with ~450 individuals I have 600,000 calls like these, all with 15+ depth in each of the parents and child. That is a lot of variants that have this status. I agree that some are problematic but that many?


``` /folder/gatk_4.0.5.2.jar (I renamed it for you to have the version) 
    --java-options "-Xms8000m
      CalculateGenotypePosteriors
      -R $(inputs.reference.path)
      -O $(inputs.output_basename).postCGP.vcf.gz
      -V $(inputs.vqsr_vcf.path)
      --supporting $(inputs.snp_sites.path)
      --pedigree $(inputs.ped.path)

**Comment by ldgauthier** [comment]
Depending on what the allele frequencies are in that supporting VCF, the prior on there being a variant could be very strong against homozygous reference calls.  We've found that the support resource doesn't have to be well population matched, but that was for overall accuracy.  There can be a small decrease in sensitivity.  Another option is to decrease the de novo mutation prior with `--de-novo-prior` to increase sensitivity as seen in slide 15 from the GATK workshop presentation here: https://drive.google.com/drive/u/0/folders/1FzkoFoIVI41JBp_E8S6WfwhJH7xt8T2Y  The default is 1e-6, which is not in agreement with the literature, but provided good results in our evaluations.

**Comment by ldgauthier** [comment]
I'm going to close this, but feel free to reopen if you're still having issues @zvaksman

**Comment by zvaksman** [comment]
Thanks
