### ISSUE TITLE
Typos in Tool Index docs

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#6440]
Three very minor typos are present in these documents that break the code when copied-and-pasted as they are.

-----

Link: https://gatk.broadinstitute.org/hc/en-us/community/posts/360056484652-Typos-in-docs

--

1.  [https://gatk.broadinstitute.org/hc/en-us/articles/360036726571-LeftAlignAndTrimVariants](/hc/en-us/articles/360036726571-LeftAlignAndTrimVariants)

the fifth code block on this page needs a '\\' at the end of the next to last line: 

--dont-trim-alleles \

2. [https://gatk.broadinstitute.org/hc/en-us/articles/360036712151-HaplotypeCaller](/hc/en-us/articles/360036712151-HaplotypeCaller)

the second code block on this page has incorrect -G flags. they should be:

-G StandardAnnotation \
 -G AS\_StandardAnnotation

3. [https://gatk.broadinstitute.org/hc/en-us/articles/360036730411-Mutect2](/hc/en-us/articles/360036730411-Mutect2)

the fifth code block on this page has incorrect flag for mitochondria. it should be:

--mitochondria-mode \

 

 <br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/4521'>Zendesk ticket #4521</a>)<br>gz#4521</i>

**Comment by lbergelson** [comment]
@GATKSupportTeam Would someone on the support team like to file a PR to resolve this?  It seems like a good intro PR for new members who haven't ever made one before.

**Comment by bhanugandham** [comment]
@derekca Would you wanna take this one?

**Comment by droazen** [comment]
Note that the tool doc links in this ticket are out-of-date. The current tool docs can be found at: 

https://gatk.broadinstitute.org/hc/en-us/sections/360012354372-4-2-0-0-Current
