### ISSUE TITLE
Indel Realignment and Alignment Metadata

### ISSUE THREAD

**Issue by DarioS** [broadinstitute/gatk#6459]
In the news file of a structural variant software I use, I read

>Added FIX_SA and FIX_MISSING_HARD_CLIP
>FIX_SA: rewrites split read SA tags
>corrects GATK indel realignment SA tag data inconsistency
>FIX_MISSING_HARD_CLIP: infers missing hard clipping if split read records have different lengths
>corrects for GATK indel realignment stripping hard clipping when realigning

Could such issues perhaps be resolved in an update to GATK?

**Comment by ldgauthier** [comment]
Those sound like issues with the IndelRealigner tool from GATK3, which is
not part of our pipeline anymore. Is this still a problem with 4.1.4.1?

**Comment by DarioS** [comment]
Indeed, this is no longer a problem with GATK4.
