### ISSUE TITLE
Create mapping from Human readable names to Ids for Google Genomics Reference API

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#646]
Right now, the "names" in the table mapping (in RefAPISource) are things like EOSt9JOVhp3jkwE. What we want is "GRCh37".

**Comment by akiezun** [comment]
does this affect spark?

**Comment by davidadamsphd** [comment]
Yes.

**Comment by droazen** [comment]
Ideally via a query, otherwise via a hardwired list of references.

**Comment by droazen** [comment]
Re-assigning to @akiezun, since he's out of work
