### ISSUE TITLE
Outdated gatkforums links

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#6505]
At least one place in the repo still references the old forum links: scripts/cnv_wdl/germline/cnv_germline_cohort_workflow.wdl

An IntelliJ "Find in Path" should work well.

**Comment by lbergelson** [comment]
We have another related ticket as well #6382

**Comment by ldgauthier** [comment]
I think it's fair to call this a dupe then.  I'll move my notes to the older issue.
