### ISSUE TITLE
Introduce proper argument for TILEDB_DISABLE_FILE_LOCKING in GenomicsDBImport

### ISSUE THREAD

**Issue by tmm211** [broadinstitute/gatk#6519]
### Tool(s) or class(es) involved
GenomicsDBImport

### Description
Users get confused by this error message: `A USER ERROR has occurred: Couldn't create GenomicsDBFeatureReader`
`Caused by: java.io.IOException: GenomicsDB JNI Error: VariantQueryProcessorException : Could not open array 1$1$249250621 at workspace: ...
TileDB error message : [TileDB::BookKeeping] Error: Cannot load book-keeping; Reading tile offsets failed`

In one of our [docs](https://gatk.broadinstitute.org/hc/en-us/articles/360035889971--How-to-Consolidate-GVCFs-for-joint-calling-with-GenotypeGVCFs), we offer this advice, but this is not a proper argument in the GATK tool docs yet:
_If you’re working on a POSIX filesystem (e.g. Lustre, NFS, xfs, ext4 etc), you must set the environment variable TILEDB_DISABLE_FILE_LOCKING=1 before running any GenomicsDB tool. If you don’t, you will likely see an error like Could not open array genomicsdb_array at workspace:[...]_

**This request is to add a proper argument to deal with this scenario in GenomicsDBImport and to document it in the tool docs.**

**Comment by GATKSupportTeam** [comment]
<i>(related to <a href='https://broadinstitute.zendesk.com/agent/tickets/4782'>Zendesk ticket #4782</a>)</i>

**Comment by zhpn1024** [comment]
I also encounter this error when most samples have been imported. I ran importing in batches '--batch-size 50 --consolidate '. The error occured at the last batch. Can I reuse some of the imported data files or have to rerun the whole importing again?

**Comment by zhpn1024** [comment]
> I also encounter this error when most samples have been imported. I ran importing in batches '--batch-size 50 --consolidate '. The error occured at the last batch. Can I reuse some of the imported data files or have to rerun the whole importing again?

...
13:13:26.069 INFO  GenomicsDBImport - Done importing batch 21/22
13:13:26.069 INFO  GenomicsDBImport - Starting batch input file preload
13:13:27.440 INFO  GenomicsDBImport - Finished batch preload
13:13:27.440 INFO  GenomicsDBImport - Importing batch 22 with 22 samples
[TileDB::Buffer] Error: Cannot read from buffer; End of buffer reached.
[TileDB::BookKeeping] Error: Cannot load book-keeping; Reading tile offsets failed.
terminate called after throwing an instance of 'VariantStorageManagerException'
  what():  VariantStorageManagerException exception : Error while consolidating TileDB array chrY$1$57227415
TileDB error message : [TileDB::BookKeeping] Error: Cannot load book-keeping; Reading tile offsets failed

**Comment by droazen** [comment]
Such an argument was added in https://github.com/broadinstitute/gatk/pull/6654 -- closing.
