### ISSUE TITLE
Remove guards that require a reference from CRAM code paths

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#6541]
There are a number of GATK code paths that check to ensure that a reference is provided whenever a CRAM input is provided. Since htsjdk now accepts both embedded reference and reference-less (no reference compression) CRAMs, these checks  should be removed once we update htsjdk. The CRAM code will defer accessing the reference until one is actually required, and will fail gracefully in the case where it is not provided.

**Comment by cmnbroad** [comment]
Duplicate of https://github.com/broadinstitute/gatk/issues/6665.

**Comment by lbergelson** [comment]
Woops, sorry!
