### ISSUE TITLE
GenotypeGVCFs GATK v4.1.6.0 refuses '--use-new-qual-calculator true'

### ISSUE THREAD

**Issue by splaisan** [broadinstitute/gatk#6547]
When set, the # argument leads to a message saying it is not recognized (idem with shorter notation -new-qual).

* is this parameter obsolete with this version of GATK4 (4.1.6.0) and should it be removed from best practice?
* is it the current default behaviour and is not needed anymore?
* did I do something wrong?

many questions ! sorry :-)

```
java ${javaopts} -jar $GATK/gatk.jar \
	GenotypeGVCFs \
	--reference ${reference_fa} \
	--variant gendb://${outfolder}/merged_gvcf.db \
	--annotation-group StandardAnnotation \
#	--use-new-qual-calculator true \
	--output ${outfolder}/gatk_variants.vcf.gz \
	--tmp-dir ${basedir}/tmpfiles/
```

**Comment by splaisan** [comment]
is this the answer? https://github.com/broadinstitute/gatk/issues/6370
the doc should then state it to avoid confusion.

**Comment by lbergelson** [comment]
@splaisan I believe that argument was removed and the documentation should have been updated.  Can you link to where you're seeing it recommended?

**Comment by lbergelson** [comment]
The old qual calculator has been completely removed so there's no need to specifically request the new one now.

**Comment by splaisan** [comment]
I was reading an old version of the tool page, a more recent one  (https://gatk.broadinstitute.org/hc/en-us/articles/360037594731-GenotypeGVCFs) gives it as deprecated but is not the page I found by searching google.

Thanks for confirming that it is obsolete

**Comment by lbergelson** [comment]
The most recent is actually this one: [4.1.6.0](https://gatk.broadinstitute.org/hc/en-us/sections/360008481611-4-1-6-0). There's some problems with how the website displays the versions at the moment so it's hard to find.

**Comment by splaisan** [comment]
> The most recent is actually this one: [4.1.6.0](https://gatk.broadinstitute.org/hc/en-us/sections/360008481611-4-1-6-0). There's some problems with how the website displays the versions at the moment so it's hard to find.

Apparently when an argument has been depreciated, it is not mentionned in later versions anymore as seen from https://gatk.broadinstitute.org/hc/en-us/articles/360041417092-GenotypeGVCFs
So people who do not read the version page where it is announced will never know it (unless I missed it in my reading)
Sooooo many versions out there and indeed v4.1.6.0 not found by searching GenotypeGVCFs but only by parsing until page 6.
Thanks for your help

**Comment by lbergelson** [comment]
I reached out to our comms team and they fixed the ordering bug in the list of versions so 4.1.6.0 should at least be the first one on the page now.  They are aware that there are some issues with the doc being hard to find/search but there's limited developer resources to make changes to the website right now.  We're doing what we can to improve things!

So I think arguments that marked as *Deprecated* are listed in the doc, but if an argument is actually *removed* then it's no longer mentioned anywhere.  We try to deprecate arguments for a period of time before removing them to give people warning that things might go away, but we don't have a set policy on how long/how many versions.  In general we try not to remove stuff very often to avoid this kind of issue, but sometimes people do get caught by it.
