### ISSUE TITLE
Best Practice GenomicsDB workspace(s) with intervals/scatter-gather?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6557]
Hello,

We're looking to switch our large-scale WGS/variant calling project to use GenomicsDB instead of CombineGVCFs to stage data prior to GenotypeGVCFs, primarily b/c it allows incremental addition of samples.  I'm wondering if you'd be willing to comment on this from the perspective of scatter/gather.  We process most GATK jobs using scatter/gather across a cluster by providing each job with a list of intervals.

While GenomicsDB workspaces appear to currently support multiple intervals, I am thinking that it actually makes more sense to simply maintain our data as a folder of workspaces, where each has a defined interval set.  The reasoning is that there seems to be no reason to maintain it as one large whole-genome workspace.  So far as I can tell, if I maintain this as a whole-genome workspace, I cannot easily scatter/gather the jobs to add new batches of samples?  in contrast, if maintained as a folder of workspaces, I could execute the merge job as one job per workspace/interval-set.  This obligates us to always execute GenotypeGVCFs as scatter/gather on those specific intervals; however, that doesnt seem like that big a limitation. 

If doing this, I'm considering maintaining a Multi-interval GenomicsDB 'file format', which would basically be a JSON or simple text file that maps Interval->Workspace, allowing code to figure out which workspace to select as input based on the intervals provided.

Does this seem sane?  Am I missing features in GenomicsDB that would argue toward maintaining a large gVCF dataset as a single workspace rather than many?

Thanks,
Ben

**Comment by ldgauthier** [comment]
We keep our shards as tarred genomicsDB workspaces.  Cromwell helps manage all the references, though.  You can see our exome workflow here: https://github.com/gatk-workflows/gatk4-germline-snps-indels/blob/master/JointGenotyping.wdl. We don't have a pipeline with incremental addition of samples, so we don't have a ready made solution there.  Subjectively the json idea sounds pretty good, although just keeping a list of paths would also work since you expect the same number of scatters, provided they're sorted, which isn't too hard.

**Comment by bbimber** [comment]
@ldgauthier in our case we're not necessarily doing one job/contig.  primary chromosomes are 1:1; however, we batch the unplaced contigs into sets of jobs to reduce the total job count.  therefore a slightly more formal scheme to map interval(s) -> workspace would make sense in our case.

**Comment by bbimber** [comment]
Hello,

We've been looking further at GenomicsDB workspaces.  Again, we're planning to create them scattered, with one job per interval.  Our workspaces would be somewhat long-lived.  So far as I can tell, the guts of a GenomicsDB workspace has one folder per contig anyway.  Is there a reasonable way to merge multiple workspaces together?  When working with Combined gVCFs files this merge operation was quite inefficient since you concatted/bgzipped big files, but it seems this could possibly be easier for multiple genomics DB workspaces, provided they had non-overlapping contigs.  Are there ways to do this?

**Comment by ldgauthier** [comment]
Hopefully @nalinigans or Melvin can answer this.  It may be the case that it's possible, but unsupported.

**Comment by mlathara** [comment]
Hi @bbimber 

So regarding this first question:
> the guts of a GenomicsDB workspace has one folder per contig anyway. Is there a reasonable way to merge multiple workspaces together?
You can try to pull together each of the contig folders under a single workspace. You just need a single copy of the callset.json, vidmap.json, vcfheader.vcf, and __tiledb_workspace.tdb in the merged workspace. As @ldgauthier suggests, it falls under the "probably works but unsupported umbrella".

I can't quite be sure, but the last part of your comment/question might be asking if some tool or option supports reading/merging from multiple genomicsdb workspaces. No such tool currently exists.

**Comment by bbimber** [comment]
@mlathara Thanks for the reply.  The reason I'm very interested in this is scatter/gather, so in our use-case, the inputs would be identical.  Like you say, this would essentially be X jobs initiated with the same command, just different intervals. Merging all the resulting per-contig workspaces back into one workspace has a lot of logistical appeal, and the resulting folder would still be a valid GenomicsDB workspace.  The alternate idea we had been considering was to maintain these as a folder of per-workspaces. That might work, but has the downside of not being a 'real' file format.  Any future operations would need to be interval-aware, which could be a problem.
