### ISSUE TITLE
GenomicsDB, update-workspace and the backup recommendation?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6558]
Hello,

To our thinking, one of the compelling reasons to use GenomicsDB over Combined gVCFs is that ability to incrementally append samples, and this is supported through --genomicsdb-update-workspace-path.  However, you docs state: "It is recommended that users backup existing genomicsdb workspaces before adding new samples using --genomicsdb-update-workspace-path. If the tool fails during incremental import for any reason, the workspace may be in an inconsistent/corrupted state".  These files are not small.  Given that recommendation, wouldnt it make just as much sense to let the user specify the workspace-to-update, the input gVCFs, and specify an alternate output path where the merged data is written?  To us, the key feature is incremental sample append, not update-in-place.  Is the user wanted to update the original copy, after successful completion of GenomicsDB they could certainly delete the original and move the new copy into that location?  Not to mention, in theory one could have some job trying to read the original workspace, which might get hosed if some other job is trying to edit that workspace in place.

Thanks for any thoughts or comments.

-Ben

**Comment by droazen** [comment]
@nalinigans @mlathara Your thoughts on this?

**Comment by mlathara** [comment]
GenomicsDB workspaces can be moved freely - i.e., there is nothing about the workspace name or path that cannot be changed after initial creation. This wasn't true in the past (way way back in the past) but is certainly true now. Just want to clarify that in case that wasn't clear.

I guess I see this as six of one, half a dozen of the other. Currently, the user can copy the initial workspace to a new location and incrementally import samples to the new location.  The option proposed by @bbimber (specify existing workspace, new gVCFs and new output location) would  require the tool to copy the existing workspace to the new location and then import new samples to it. Only real difference is who is doing the copying.

**Comment by nalinigans** [comment]
>Not to mention, in theory one could have some job trying to read the original workspace, which might get hosed if some other job is trying to edit that workspace in place.

This is not possible as new GenomicsDB workspace fragments are created for the incremental updates. During the actual finalization of the fragments, the array in the workspace is locked using Posix file locks for concurrency.

**Comment by mlathara** [comment]
> > Not to mention, in theory one could have some job trying to read the original workspace, which might get hosed if some other job is trying to edit that workspace in place.
> 
> This is not possible as new GenomicsDB workspace fragments are created for the incremental updates. During the actual finalization of the fragments, the array in the workspace is locked using Posix file locks for concurrency.

As @nalinigans says, individual arrays/intervals in a GenomicsDB workspace will be consistent during incremental import. One caveat though, since each array is independently updated, different arrays/intervals will finish adding samples at different times while incremental import is in progress. So, querying a workspace that is being incrementally imported into isn't recommended.

**Comment by bbimber** [comment]
@mlathara Your last sentence about querying during incremental update is my point.  It seems like it might be nice if GenomicsDB at least did something to indicate an update was happening (maybe write a lock file in the workspace?).  If there was a standard pattern, other tools could at least be aware of this and deal with it appropriately.  at minimum a reader could log a warning or something.

If there is no I/O difference between the user copying a workspace and updating vs. GenomicsDB reading the input workspace and writing the output to a new location, then I guess I agree that one can make an argument that it's not critical for GenomicsDBImport to execute that copy itself.  I dont understand the read/write pattern of these enough to answer that, but your replies above suggest no.

**Comment by mlathara** [comment]
@bbimber File locking doesn't work on all the filesystems GenomicsDB supports (hdfs/cloud, for instance) and is a pain on others (NFS, for instance -- painful enough that we've sometimes had to recommend users disable the existing file locking). For that reason, I wouldn't want users to depend on file locking for correctness.

Unfortunately, I think the cleanest approach is for the user to ensure correctness by avoiding the read/write conflicts themselves.
