### ISSUE TITLE
Why do we have force-call-filtered-alleles AND --alleles?

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#6572]
It seems like the argument `--force-call-filtered-alleles` is redundant with `--alleles`.   Unless I misunderstand it, it looks like force-call-filtered-alleles is just used to decide if we should look at the `--alleles` argument or not, which is only used in conjunction with force calling.  It seems redundant.  Couldn't we merge them into a single argument that takes an allele list?

**Comment by davidbenjamin** [comment]
@lbergelson `-alleles` specifies a VCF for force calling.  By default we don't force call filtered alleles from this VCF. `-force-call-filtered-alleles` says to force call every allele from that VCF.  You could merge the arguments by putting it on the user to manipulate the force-calling VCF, but I don't like the idea of extra files.

**Comment by lbergelson** [comment]
Aaah, I see.  That makes sense.  I misread.  Thank you.
