### ISSUE TITLE
Funcotator Speed Regression

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#6574]
When originally released, Funcotator had blistering speed.  In the latest tests, this speed has dropped off to be a very small fraction of that original data processing rate.

We need to profile Funcotator to determine the source of the slowdown, and then we must remedy it.

In particular the hg38 acceptance testing dataset (`hg38_trio.vcf`) has slowed significantly.

**Comment by jonn-smith** [comment]
Possibly related to #5143

**Comment by droazen** [comment]
Re-assigning to @haileypfox
