### ISSUE TITLE
FilterMutectCalls seems to generate duplicate strand bias filters in the output vcf files

### ISSUE THREAD

**Issue by hsiaoyi0504** [broadinstitute/gatk#6580]
### Affected tool(s) or class(es)
FilterMutect Calls

### Affected version(s)
4.1.6.0

### Description 
Originally post it in the [forum](https://gatk.broadinstitute.org/hc/en-us/community/posts/360061656311-Difference-between-and-strict-strand-strand-bias-in-vcf-files-generated-by-FilterMutectCalls). Now I suspect it's a bug in the output vcf files of the FilterMutectCalls.

#### Steps to reproduce
Just run `FilterMutectCalls`

#### Expected behavior
Only one filter for strand bias presented in the output vcf files. Alternatively, if they represent different origins of strand bias, they should clarify where the strand bias comes from.

#### Actual behavior
In the output vcf files, it contains two pretty similar or same filters.
```
##FILTER=<ID=strand_bias,Description="Evidence for alt allele comes from one read direction only">
##FILTER=<ID=strict_strand,Description="Evidence for alt allele is not represented in both directions">
```

### Tool(s) or class(es) involved
FilterMutectCalls

### Description
There should have a detailed description of the filters presented in the output vcf files

**Comment by fleharty** [comment]
@hsiaoyi0504 These are actually two separate, but very similar filters.  I agree that the descriptions are identical but their behavior is not.

The strict_strand filter is intended to be used on duplex sequencing.

@davidbenjamin Would you have a moment to chat about the best way to deal with these?

**Comment by davidbenjamin** [comment]
@fleharty Addressed on the forum.  The filter was and is still turned off by default.  It shows up in the VCF header even when turned off, like other M2 filters.
