### ISSUE TITLE
VQSR plot legend is masking part of the histogram

### ISSUE THREAD

**Issue by splaisan** [broadinstitute/gatk#6585]
Is there a script that can be tuned to stop putting the legend of VQSR plots on top of the plot?
It is masking important information as shown below.
When this is using ggplot2, the legend could be captured and plotted as a separate grid object next to the plot (for instance).

![example](https://i.imgur.com/53rbF0c.png)

**Comment by ldgauthier** [comment]
HI @splaisan ,

That's a known issue, but we never had a great solution before.  Your suggestion makes sense.  Would you care to open a PR to make the change: https://github.com/broadinstitute/gatk/blob/master/src/main/resources/org/broadinstitute/hellbender/tools/walkers/vqsr/plot_Tranches.R

**Comment by splaisan** [comment]
willing to give it a try but I need minimal info to do so

* can I add `library("ggplot2")` to the code or will this new library not be supported by the package?

* what value (are these defaults?) do

```
targetTITV = as.numeric(args[2])
targetSensitivity = as.numeric(args[3]) 
```

take for a command like this

> cmd="java ${javaopts} -jar $GATK/gatk.jar \
> 	VariantRecalibrator \
> 	-R ${reference_fa} \
> 	-V ${outfolder}/gatk_variants_excesshet_sitesonly.vcf.gz \
> 	-O ${outfolder}/gatk_variants_recalibrate_SNP.recal.vcf.gz \
> 	${intervals} \
> 	--resource:1001Gsnp,known=true,training=true,truth=true,prior=12.0 ${knownsnps} \
> 	--trust-all-polymorphic \
> 	--use-annotation DP \
> 	--use-annotation QD \
> 	--use-annotation FS \
> 	--use-annotation SOR \
> 	--use-annotation MQ \
> 	--use-annotation MQRankSum \
> 	--use-annotation ReadPosRankSum \
> 	--mode SNP \
> 	--max-gaussians ${maxSNPgaussians} \
> 	--tranches-file ${outfolder}/gatk_variants_recalibrate_snp.tranches \
> 	--tranche 100.0 \
> 	--tranche 99.95 \
> 	--tranche 99.9 \
> 	--tranche 99.8 \
> 	--tranche 99.6 \
> 	--tranche 99.5 \
> 	--tranche 99.4 \
> 	--tranche 99.3 \
> 	--tranche 99.0 \
> 	--tranche 98.0 \
> 	--tranche 97.0 \
> 	--tranche 90.0 \
> 	--rscript-file ${outfolder}/gatk_variantsgatk_variants_recalibrate_snp_plots.R \
> 	--tmp-dir ${basedir}/tmpfiles/"

Sorry but I do not know where to look in the java code for this

Thanks in advance

**Comment by splaisan** [comment]
alternatively, can we set `suppressLegend = ! is.na(args[4])` from the java command to get rid of the legend during ploting?

**Comment by splaisan** [comment]
this seems to work for me
* edited the par() on top
* edited the legend line
* added 0.05 to the column titles to not overlap

[-] and [+] below to spot the edits (the other commented lines where there already)

sorry but I am not familiar with PR, can you handle that for me please.

```
[-] par(mar = c(5, 5, 4, 2) + 0.1)
[+] par(mar=c(5.1, 4.1, 4.1, 8.1), xpd=TRUE)
novelTiTv = c(data2$novelTITV,data2$novelTiTv)
alpha = 1 - titvFPEstV(targetTITV, novelTiTv)
#print(alpha)

numGood = round(alpha * data2$numNovel);

#numGood = round(data2$numNovel * (1-data2$targetTruthSensitivity/100))
numBad = data2$numNovel - numGood;

numPrevGood = leftShift(numGood, 0)
numNewGood = numGood - numPrevGood
numPrevBad = leftShift(numBad, 0)
numNewBad = numBad - numPrevBad

d=matrix(c(numPrevGood, numNewGood, numNewBad, numPrevBad), 4, byrow=TRUE)
#print(d)

barplot(d/1000, horiz=TRUE, col=cols, space=0.2, xlab="Number of Novel Variants (1000s)", density=density, cex.axis=1.25, cex.lab=1.25) # , xlim=c(250000,350000))
#abline(v= d[2,dim(d)[2]], lty=2)
#abline(v= d[1,3], lty=2)
if ( ! suppressLegend )
[+]  legend("topright", inset=c(-0.5,0.1), c('Cumulative TPs','Tranch-specific TPs', 'Tranch-specific FPs', 'Cumulative FPs' ), fill=cols, density=density, bg='white', cex=1.25)
[-] legend(3, length(data2$targetTruthSensitivity)/3 +1, c('Cumulative TPs','Tranch-specific TPs', 'Tranch-specific FPs', 'Cumulative FPs' ), fill=cols, density=density, bg='white', cex=1.25)

[-] mtext("Ti/Tv", 2, line=2.25, at=length(data2$targetTruthSensitivity)*1.2, las=1, cex=1)
[-] mtext("truth", 2, line=0, at=length(data2$targetTruthSensitivity)*1.2, las=1, cex=1)

[+] mtext("Ti/Tv", 2, line=2.25, at=length(data2$targetTruthSensitivity)*1.25, las=1, cex=1)
[+] mtext("truth", 2, line=0, at=length(data2$targetTruthSensitivity)*1.25, las=1, cex=1)

axis(2, line=-1, at=0.7+(0:(length(data2$targetTruthSensitivity)-1))*1.2,tick=FALSE, labels=data2$targetTruthSensitivity, las=1, cex.axis=1.0)
axis(2, line=1, at=0.7+(0:(length(data2$targetTruthSensitivity)-1))*1.2,tick=FALSE, labels=round(novelTiTv,3), las=1, cex.axis=1.0)
```
