### ISSUE TITLE
MultiVariantWalker sequence dictionary cross-validation is miserable

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/gatk#6589]
By default MultiVariantWalker checks all contigs for all VariantDataSources for compatibility with the reference.  On hg38 this is a not insignificant time for three samples, but for 200 samples it's excruciating.  I hooked up the SequenceDictionaryValidationArgumentCollection in a branch for development purposes, but I wouldn't want to do that in production.  How can we improve this?  Certainly we only make calls over a very small subset of contigs -- can we restrict the VCF sequence dictionary to just called contigs?

**Comment by droazen** [comment]
@ldgauthier This is why the `--disable-sequence-dictionary-validation` argument exists in `GATKTool`. If you're confident in the compatibility of your inputs, and the checks are too expensive, you can run with that option and (optionally) perform some less strict validation of your own in your `onTraversalStart()` method.

**Comment by droazen** [comment]
(You can also permanently turn the validation off for your tool by overriding the `getSequenceDictionaryValidationArgumentCollection()` method)

**Comment by ldgauthier** [comment]
We used to call this `--unsafe`, but I feel like you've just put lipstick on the pig.

Usually you're more conservative than I am, so if you're okay with this then so am I.

**Comment by droazen** [comment]
@ldgauthier If you feel that you need some validation, but less strict/expensive than the default, then I'd suggest turning off the default validation, writing your own scaled-down dictionary validation routine, and calling it from `onTraversalStart()` in your tool. Then if it seems like the scaled-down validation might be generally useful, we could hook it up to the `SequenceDictionaryValidationArgumentCollection` as a third engine-level option.
