### ISSUE TITLE
How to use pipeline to call SNP and INDEL

### ISSUE THREAD

**Issue by sekhwal** [broadinstitute/gatk#6592]
I am looking to call single nucleotide polymorphism (SNP) and INDEL from my genome mapping results generated from HISAT pipeline. Please suggest process and command for that.

**Comment by lbergelson** [comment]
A lot of tutorials and information are available on our support [website](https://gatk.broadinstitute.org/hc/en-us). It includes best practice guides and a forum to ask questions.
