### ISSUE TITLE
please provide singularity recipe 

### ISSUE THREAD

**Issue by EricDeveaud** [broadinstitute/gatk#6601]
Hello, 

would it be possible to provide a singularity recipe 

regards

Eric

**Comment by ldgauthier** [comment]
Hi Eric,

The only parallelism implementations we support are local Spark and Google Cloud.  Our group has no experience with Singularity.  You may have some luck asking other users on the forum: https://gatk.broadinstitute.org/hc/en-us/community/topics

**Comment by lbergelson** [comment]
@EricDeveaud  A singularity recipe would be great but we don't have anyone here with expertise to do it.  We're open to taking a pull request!
