### ISSUE TITLE
GATK error 

### ISSUE THREAD

**Issue by javad30** [broadinstitute/gatk#6604]
I am trying to do SNPs call using GATK but I am getting below error. Any idea how can I solve this error? 

(base) glier_ubuntu@glierubuntu-Precision-7920-Tower:/media/glier_ubuntu/4TB/Javad_Final/7gatk/ScriptforSNP$ call_snps_gatk_firstpass.sh 6 '/media/glier_ubuntu/4TB/Javad_Final/5-trinity/Fastajavad_Trinity/Trinity.fasta' '/media/glier_ubuntu/4TB/Javad_Final/6bwa/2/filtered_merged.bam' 
Using GATK jar /home/glier_ubuntu/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx8G -jar /home/glier_ubuntu/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar CreateSequenceDictionary -R /media/glier_ubuntu/4TB/Javad_Final/5-trinity/Fastajavad_Trinity/Trinity.fasta -O /media/glier_ubuntu/4TB/Javad_Final/5-trinity/Fastajavad_Trinity/Trinity.dict
15:46:56.167 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/glier_ubuntu/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed May 13 15:46:56 EDT 2020] CreateSequenceDictionary  --OUTPUT /media/glier_ubuntu/4TB/Javad_Final/5-trinity/Fastajavad_Trinity/Trinity.dict --REFERENCE /media/glier_ubuntu/4TB/Javad_Final/5-trinity/Fastajavad_Trinity/Trinity.fasta  --TRUNCATE_NAMES_AT_WHITESPACE true --NUM_SEQUENCES 2147483647 --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
May 13, 2020 3:46:57 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
[Wed May 13 15:46:57 EDT 2020] Executing as glier_ubuntu@glierubuntu-Precision-7920-Tower on Linux 4.15.0-99-generic amd64; OpenJDK 64-Bit Server VM 11.0.7+10-post-Ubuntu-2ubuntu218.04; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:4.1.1.0
[Wed May 13 15:46:57 EDT 2020] picard.sam.CreateSequenceDictionary done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=2107637760
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
picard.PicardException: /media/glier_ubuntu/4TB/Javad_Final/5-trinity/Fastajavad_Trinity/Trinity.dict already exists.  Delete this file and try again, or specify a different output file.
	at picard.sam.CreateSequenceDictionary.doWork(CreateSequenceDictionary.java:209)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
Using GATK jar /home/glier_ubuntu/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx8G -jar /home/glier_ubuntu/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar HaplotypeCaller -R /media/glier_ubuntu/4TB/Javad_Final/5-trinity/Fastajavad_Trinity/Trinity.fasta -I /media/glier_ubuntu/4TB/Javad_Final/6bwa/2/filtered_merged.bam -O /media/glier_ubuntu/4TB/Javad_Final/6bwa/2/filtered_merged_firstpass.vcf.gz -stand-call-conf 30.0 --dont-use-soft-clipped-bases -jdk-inflater -jdk-deflater
May 13, 2020 3:47:00 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
15:47:00.973 INFO  HaplotypeCaller - ------------------------------------------------------------
15:47:00.974 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.1.1.0
15:47:00.974 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
15:47:00.974 INFO  HaplotypeCaller - Executing as glier_ubuntu@glierubuntu-Precision-7920-Tower on Linux v4.15.0-99-generic amd64
15:47:00.974 INFO  HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v11.0.7+10-post-Ubuntu-2ubuntu218.04
15:47:00.975 INFO  HaplotypeCaller - Start Date/Time: May 13, 2020 at 3:46:59 p.m. EDT
15:47:00.975 INFO  HaplotypeCaller - ------------------------------------------------------------
15:47:00.975 INFO  HaplotypeCaller - ------------------------------------------------------------
15:47:00.976 INFO  HaplotypeCaller - HTSJDK Version: 2.19.0
15:47:00.976 INFO  HaplotypeCaller - Picard Version: 2.19.0
15:47:00.979 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
15:47:00.979 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
15:47:00.979 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
15:47:00.979 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
15:47:00.980 INFO  HaplotypeCaller - Deflater: JdkDeflater
15:47:00.981 INFO  HaplotypeCaller - Inflater: JdkInflater
15:47:00.981 INFO  HaplotypeCaller - GCS max retries/reopens: 20
15:47:00.981 INFO  HaplotypeCaller - Requester pays: disabled
15:47:00.981 INFO  HaplotypeCaller - Initializing engine
15:47:15.632 INFO  HaplotypeCaller - Done initializing engine
15:47:20.372 INFO  HaplotypeCallerEngine - Disabling physical phasing, which is supported only for reference-model confidence output
15:47:20.380 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/home/glier_ubuntu/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar!/com/intel/gkl/native/libgkl_utils.so
15:47:20.391 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/home/glier_ubuntu/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
15:47:20.423 INFO  IntelPairHmm - Using CPU-supported AVX-512 instructions
15:47:20.423 INFO  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
15:47:20.423 INFO  IntelPairHmm - Available threads: 40
15:47:20.423 INFO  IntelPairHmm - Requested threads: 4
15:47:20.423 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
15:47:22.213 INFO  ProgressMeter - Starting traversal
15:47:22.213 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
15:47:22.231 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 0.0
15:47:22.231 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 0.0
15:47:22.239 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 0.00 sec
15:47:22.240 INFO  HaplotypeCaller - Shutting down engine
[May 13, 2020 at 3:47:22 p.m. EDT] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.38 minutes.
Runtime.totalMemory()=3212836864
Exception in thread "main" java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/broadinstitute/hellbender/transformers/ReadTransformer. Method 'org.broadinstitute.hellbender.utils.read.GATKRead lambda$identity$d67512bf$1(org.broadinstitute.hellbender.utils.read.GATKRead)' at index 65 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at org.broadinstitute.hellbender.transformers.ReadTransformer.identity(ReadTransformer.java:30)
	at org.broadinstitute.hellbender.engine.GATKTool.makePreReadFilterTransformer(GATKTool.java:290)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.traverse(AssemblyRegionWalker.java:267)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:984)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
Using GATK jar /home/glier_ubuntu/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx8G -jar /home/glier_ubuntu/gatk-4.1.1.0/gatk-package-4.1.1.0-local.jar VariantsToTable -V /media/glier_ubuntu/4TB/Javad_Final/6bwa/2/filtered_merged_firstpass.vcf.gz -O /media/glier_ubuntu/4TB/Javad_Final/6bwa/2/filtered_merged_firstpass_table.txt -F CHROM -F POS -F QD -F MQ -F FS -F SOR -F MQRankSum -F ReadPosRankSum -jdk-inflater -jdk-deflater
May 13, 2020 3:47:25 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
15:47:25.643 INFO  VariantsToTable - ------------------------------------------------------------
15:47:25.644 INFO  VariantsToTable - The Genome Analysis Toolkit (GATK) v4.1.1.0
15:47:25.644 INFO  VariantsToTable - For support and documentation go to https://software.broadinstitute.org/gatk/
15:47:25.644 INFO  VariantsToTable - Executing as glier_ubuntu@glierubuntu-Precision-7920-Tower on Linux v4.15.0-99-generic amd64
15:47:25.644 INFO  VariantsToTable - Java runtime: OpenJDK 64-Bit Server VM v11.0.7+10-post-Ubuntu-2ubuntu218.04
15:47:25.644 INFO  VariantsToTable - Start Date/Time: May 13, 2020 at 3:47:24 p.m. EDT
15:47:25.644 INFO  VariantsToTable - ------------------------------------------------------------
15:47:25.644 INFO  VariantsToTable - ------------------------------------------------------------
15:47:25.645 INFO  VariantsToTable - HTSJDK Version: 2.19.0
15:47:25.646 INFO  VariantsToTable - Picard Version: 2.19.0
15:47:25.649 INFO  VariantsToTable - HTSJDK Defaults.COMPRESSION_LEVEL : 2
15:47:25.649 INFO  VariantsToTable - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
15:47:25.649 INFO  VariantsToTable - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
15:47:25.649 INFO  VariantsToTable - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
15:47:25.650 INFO  VariantsToTable - Deflater: JdkDeflater
15:47:25.651 INFO  VariantsToTable - Inflater: JdkInflater
15:47:25.651 INFO  VariantsToTable - GCS max retries/reopens: 20
15:47:25.651 INFO  VariantsToTable - Requester pays: disabled
15:47:25.651 INFO  VariantsToTable - Initializing engine
15:47:25.751 INFO  FeatureManager - Using codec VCFCodec to read file file:///media/glier_ubuntu/4TB/Javad_Final/6bwa/2/filtered_merged_firstpass.vcf.gz
15:47:31.284 INFO  VariantsToTable - Done initializing engine
15:47:31.293 WARN  VariantsToTable - Allele-specific fields will only be split if splitting multi-allelic variants is specified (`--split-multi-allelic` or `-SMA`
15:47:31.294 INFO  ProgressMeter - Starting traversal
15:47:31.294 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
15:47:31.296 INFO  VariantsToTable - Shutting down engine
[May 13, 2020 at 3:47:31 p.m. EDT] org.broadinstitute.hellbender.tools.walkers.variantutils.VariantsToTable done. Elapsed time: 0.12 minutes.
Runtime.totalMemory()=3286237184
Exception in thread "main" java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class org/broadinstitute/hellbender/transformers/VariantTransformer. Method 'htsjdk.variant.variantcontext.VariantContext lambda$identity$76d6cab0$1(htsjdk.variant.variantcontext.VariantContext)' at index 65 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
	at org.broadinstitute.hellbender.transformers.VariantTransformer.identity(VariantTransformer.java:32)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.makePreVariantFilterTransformer(VariantWalkerBase.java:131)
	at org.broadinstitute.hellbender.engine.VariantWalkerBase.getTransformedVariantStream(VariantWalkerBase.java:155)
	at org.broadinstitute.hellbender.engine.VariantWalker.traverse(VariantWalker.java:98)
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:984)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:191)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
(base) glier_ubuntu@glierubuntu-Precision-7920-Tower:/media/glier_ubuntu/4TB/Javad_Final/7gatk/ScriptforSNP$

**Comment by lbergelson** [comment]
@javad30 Hi, it looks like you're running a gatk built for java 8 with java 11.  Pre-built gatk jars only support java 8.  Could you install openjdk 8 and try again?

**Comment by javad30** [comment]
> @javad30 Hi, it looks like you're running a gatk built for java 8 with java 11. Pre-built gatk jars only support java 8. Could you install openjdk 8 and try again?

It did work. Thank you so much for your help.

**Comment by lbergelson** [comment]
Yay!
