### ISSUE TITLE
Tools shown with tab-complete but do not exist/are unavailable

### ISSUE THREAD

**Issue by Neato-Nick** [broadinstitute/gatk#6615]
### Instructions

The github issue tracker is for bug reports, feature requests, and API documentation requests. General questions about how to use the GATK, how to interpret the output, etc. should be asked on the [official support forum](http://gatkforums.broadinstitute.org/gatk).
- Search the existing github issues to see if your issue (or something similar) has already been reported.  If the issue already exists, you may comment there to inquire about the progress.
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request** (for tool/class javadoc only -- for forum docs please post there)
- Consider if your "issue" is better addressed on the GATK forum: http://gatkforums.broadinstitute.org/gatk  Post there if you have questions about expected tool behavior, output format, unexpected results, or generally any question that does not fit into the categories above
- Use a **concise** yet **descriptive** title
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate
- Delete the other template blocks and this header.

----

### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

After sourcing the tab-completion script, some tools shown cannot be run. Maybe they exist somewhere in an experimental dev version but are not bundled for public release?

### Affected version(s)
- [x ] Latest public release version [4.1.7.0]
- [ ] Latest master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

After trying to tab complete the DepthOfCoverage, I saw a few tools not listed in the documentation. I tried running them and sure enough, there were errors:

`A USER ERROR has occurred: '*' is not a valid command.`
(* is one of the tools listed below)

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

```
cd gatk-4.1.7.0
source gatk-completion.sh
./gatk Depth<tab>
#>DepthOfCoverage         DepthPerAlleleBySample  DepthPerSampleHC
./gatk DepthPerSampleHC -h
...
***********************************************************************
A USER ERROR has occurred: 'DepthPerSampleHC' is not a valid command.
***********************************************************************
./gatk DepthPerAlleleBySample -h
...
***********************************************************************
A USER ERROR has occurred: 'DepthPerAlleleBySample' is not a valid command.
***********************************************************************
./gatk DepthOfCoverage -h
**BETA FEATURE - WORK IN PROGRESS**
USAGE: DepthOfCoverage [arguments]
Generate coverage summary information for reads data
Version:4.1.7.0
....
```

#### Expected behavior
_Tell us what should happen_

Only valid tools should be available for tab completion

**Comment by lbergelson** [comment]
Cool, someone is actually using the tab complete!  @Neato-Nick Thanks for reporting this.  It looks like it's picking up names of GenotypeAnnotations as program names for some reason... 
@jonn-smith This looks like a you question...

**Comment by cmnbroad** [comment]
It looks like it picks up everything that is tagged for doc. The tab completion doclet just needs to filter based on the presence of the `CommandLineProgramProperties` annotation.

**Comment by cmnbroad** [comment]
Ah, I just tried to fix this, and although the change itself is easy (in Barclay), it has an unfortunate side effect on the tab completion tests. The Barclay test class/argument container has an "extradocs" companion reference that is not a CLP. This change now filters that companion out when running the tab completion doclet. But that triggers a guard in docgen that throws if a class that is targeted for output references an extradocs class that is *not* selected for output, whcih is useful for docgen, but not tab completion or wdl gen. Also we need better separation and granularity for the Barclay tests in general, especially with the addition of wdlgen. @jonn-smith I'll take this one unless you object...

**Comment by jonn-smith** [comment]
@cmnbroad That works for me.  Looks like you have already tracked down the source.

**Comment by Neato-Nick** [comment]
> Cool, someone is actually using the tab complete! 

Yeah, it's really handy for when I can almost remember what a tool's name is but can't quite get there. It asks for more patience than what I'm used to w/tab-completes (takes 5-10 secs instead of instant return), but still much faster than `gatk -list` and digging for the right one

**Comment by cmnbroad** [comment]
I noticed that there is actually an old Barclay ticket for this issue, which we noticed...a while back. https://github.com/broadinstitute/barclay/issues/109.

**Comment by cmnbroad** [comment]
Closing via broadinstitute/barclay#164 and https://github.com/broadinstitute/gatk/pull/4523.
