### ISSUE TITLE
ERROR: Couldn't create GenomicsDBFeatureReader

### ISSUE THREAD

**Issue by wdermauw** [broadinstitute/gatk#6616]
Hi

After creating a GenomicsDB with 36 gvcf withGenomicsDBimport, I used GEnotypeGVCF on the GenomicsDB folder but get the following error: "ERROR: Couldn't create GenomicsDBFeatureReader". See below for the complete output.

FYI, I don't get this error when importing only six samples in GenomicsDB and then running GenotypeGVCF. 

FYI, also added "TILEDB_DISABLE_FILE_LOCKING=1" to environment (export TILEDB_DISABLE_FILE_LOCKING=1) before executing GenomicsDBimport command but that dit not help either.

Any suggestion would be highly appreciated.

##GenotypeVCF not working on 36 samples
(base) xxxxxx@galaxy:~$ gatk --java-options "-Xmx30g" GenomicsDBImport \
> -V output/B7_2.g.vcf.gz \
> -V output/B7_6.g.vcf.gz \
> -V output/B8_7.g.vcf.gz \
> -V output/B8_5.g.vcf.gz \
> -V output/B8_17.g.vcf.gz \
> -V output/B8_9.g.vcf.gz \
> -V output/B7_9.g.vcf.gz \
> -V output/B7_10.g.vcf.gz \
> -V output/B8_13.g.vcf.gz \
> -V output/B7_15.g.vcf.gz \
> -V output/B8_8.g.vcf.gz \
> -V output/B8_10.g.vcf.gz \
> -V output/B8_11.g.vcf.gz \
> -V output/F_A.g.vcf.gz \
> -V output/B7_3.g.vcf.gz \
> -V output/B8_19.g.vcf.gz \
> -V output/A8.g.vcf.gz \
> -V output/B7_4.g.vcf.gz \
> -V output/B8_4.g.vcf.gz \
> -V output/B8_4g.g.vcf.gz \
> -V output/B8_16.g.vcf.gz \
> -V output/A9_1.g.vcf.gz \
> -V output/X2.g.vcf.gz \
> -V output/X1.g.vcf.gz \
> -V output/7_5_2.g.vcf.gz \
> -V output/C3.g.vcf.gz \
> -V output/C1.g.vcf.gz \
> -V output/C2.g.vcf.gz \
> -V output/C3.g.vcf.gz \
> -V output/A9-10.g.vcf.gz \
> -V output/P3.g.vcf.gz \
> -V output/P4.g.vcf.gz \
> -V output/X4.g.vcf.gz \
> -V output/X5.g.vcf.gz \
> -V output/X6.g.vcf.gz \
> -V output/X7.g.vcf.gz \
> --genomicsdb-workspace-path ABchroneALL \
> --intervals pseudochromosome_1 \
> --intervals pseudochromosome_2 \
> --intervals pseudochromosome_3 \
> --batch-size 6
Using GATK jar /data/xxxxxx/miniconda3/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx30g -jar /data/xxxxxx/miniconda3/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar GenomicsDBImport -V output/B7_2.g.vcf.gz -V output/B7_6.g.vcf.gz -V output/B8_7.g.vcf.gz -V output/B8_5.g.vcf.gz -V output/B8_17.g.vcf.gz -V output/B8_9.g.vcf.gz -V output/B7_9.g.vcf.gz -V output/B7_10.g.vcf.gz -V output/B8_13.g.vcf.gz -V output/B7_15.g.vcf.gz -V output/B8_8.g.vcf.gz -V output/B8_10.g.vcf.gz -V output/B8_11.g.vcf.gz -V output/F_A.g.vcf.gz -V output/B7_3.g.vcf.gz -V output/B8_19.g.vcf.gz -V output/A8.g.vcf.gz -V output/B7_4.g.vcf.gz -V output/B8_4.g.vcf.gz -V output/B8_4g.g.vcf.gz -V output/B8_16.g.vcf.gz -V output/A9_1.g.vcf.gz -V output/TRZ.g.vcf.gz -V output/RAINBOW.g.vcf.gz -V output/7_5_2.g.vcf.gz -V output/Athens.g.vcf.gz -V output/C1.g.vcf.gz -V output/C2.g.vcf.gz -V output/C3.g.vcf.gz -V output/A9-10.g.vcf.gz -V output/P3.g.vcf.gz -V output/P4.g.vcf.gz -V output/Spg.g.vcf.gz -V output/EtAB.g.vcf.gz -V output/TuR.g.vcf.gz -V output/TuG.g.vcf.gz --genomicsdb-workspace-path ABchroneALL --intervals pseudochromosome_1 --batch-size 6
07:56:24.538 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/data/xxxxxx/miniconda3/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
May 27, 2020 7:56:24 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
07:56:24.849 INFO  GenomicsDBImport - ------------------------------------------------------------
07:56:24.850 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.1.6.0
07:56:24.850 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.oAB/gatk/
07:56:24.850 INFO  GenomicsDBImport - Executing as xxxxxx@galaxy on Linux v4.4.0-133-generic amd64
07:56:24.850 INFO  GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_192-b01
07:56:24.850 INFO  GenomicsDBImport - Start Date/Time: 27 May 2020 07:56:24 CEST
07:56:24.850 INFO  GenomicsDBImport - ------------------------------------------------------------
07:56:24.850 INFO  GenomicsDBImport - ------------------------------------------------------------
07:56:24.851 INFO  GenomicsDBImport - HTSJDK Version: 2.21.2
07:56:24.851 INFO  GenomicsDBImport - Picard Version: 2.21.9
07:56:24.851 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2
07:56:24.851 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
07:56:24.851 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
07:56:24.851 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
07:56:24.851 INFO  GenomicsDBImport - Deflater: IntelDeflater
07:56:24.851 INFO  GenomicsDBImport - Inflater: IntelInflater
07:56:24.851 INFO  GenomicsDBImport - GCS max retries/reopens: 20
07:56:24.851 INFO  GenomicsDBImport - Requester pays: disabled
07:56:24.852 INFO  GenomicsDBImport - Initializing engine
07:56:25.955 INFO  IntervalAABumentCollection - Processing 32654540 bp from intervals
07:56:25.957 INFO  GenomicsDBImport - Done initializing engine
07:56:26.238 INFO  GenomicsDBImport - Vid Map JSON file will be written to /data/xxxxxx/ABchroneALL/vidmap.json
07:56:26.238 INFO  GenomicsDBImport - Callset Map JSON file will be written to /data/xxxxxx/ABchroneALL/callset.json
07:56:26.238 INFO  GenomicsDBImport - Complete VCF Header will be written to /data/xxxxxx/ABchroneALL/vcfheader.vcf
07:56:26.238 INFO  GenomicsDBImport - Importing to array - /data/xxxxxx/ABchroneALL/genomicsdb_array
07:56:26.238 INFO  ProgressMeter - Starting traversal
07:56:26.238 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Batches Processed   Batches/Minute
07:56:26.670 INFO  GenomicsDBImport - Importing batch 1 with 6 samples
08:04:53.380 INFO  ProgressMeter - pseudochromosome_1:1              8.5                     1              0.1
08:04:53.380 INFO  GenomicsDBImport - Done importing batch 1/6
08:04:53.426 INFO  GenomicsDBImport - Importing batch 2 with 6 samples
08:10:51.448 INFO  ProgressMeter - pseudochromosome_1:1             14.4                     2              0.1
08:10:51.448 INFO  GenomicsDBImport - Done importing batch 2/6
08:10:51.492 INFO  GenomicsDBImport - Importing batch 3 with 6 samples
08:17:48.471 INFO  ProgressMeter - pseudochromosome_1:1             21.4                     3              0.1
08:17:48.471 INFO  GenomicsDBImport - Done importing batch 3/6
08:17:48.510 INFO  GenomicsDBImport - Importing batch 4 with 6 samples
08:23:17.675 INFO  ProgressMeter - pseudochromosome_1:1             26.9                     4              0.1
08:23:17.675 INFO  GenomicsDBImport - Done importing batch 4/6
08:23:17.709 INFO  GenomicsDBImport - Importing batch 5 with 6 samples
08:31:44.254 INFO  ProgressMeter - pseudochromosome_1:1             35.3                     5              0.1
08:31:44.255 INFO  GenomicsDBImport - Done importing batch 5/6
08:31:44.286 INFO  GenomicsDBImport - Importing batch 6 with 6 samples
08:38:39.554 INFO  ProgressMeter - pseudochromosome_1:1             42.2                     6              0.1
08:38:39.554 INFO  GenomicsDBImport - Done importing batch 6/6
08:38:39.556 INFO  ProgressMeter - pseudochromosome_1:1             42.2                     6              0.1
08:38:39.556 INFO  ProgressMeter - Traversal complete. Processed 6 total batches in 42.2 minutes.
08:38:39.556 INFO  GenomicsDBImport - Import of all batches to GenomicsDB completed!
08:38:39.556 INFO  GenomicsDBImport - Shutting down engine
[27 May 2020 08:38:39 CEST] oAB.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 42.25 minutes.
Runtime.totalMemory()=2545942528
Tool returned:
true

(base) xxxxxx@galaxy:~$ gatk --java-options "-Xmx30g -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" GenotypeGVCFs -R Reference/File_S16_uT_3_Pseudochromosomes.fasta -V gendb://ABchroneALL -O ABchroneALL.vcf.gz
Using GATK jar /data/xxxxxx/miniconda3/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx30g -DGATK_STACKTRACE_ON_USER_EXCEPTION=true -jar /data/xxxxxx/miniconda3/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar GenotypeGVCFs -R Reference/File_S16_uT_3_Pseudochromosomes.fasta -V gendb://ABchroneALL -O ABchroneALL.vcf.gz
09:48:14.426 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/data/xxxxxx/miniconda3/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
May 27, 2020 9:48:14 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
09:48:14.871 INFO  GenotypeGVCFs - ------------------------------------------------------------
09:48:14.871 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.1.6.0
09:48:14.872 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.oAB/gatk/
09:48:14.872 INFO  GenotypeGVCFs - Executing as xxxxxx@galaxy on Linux v4.4.0-133-generic amd64
09:48:14.872 INFO  GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_192-b01
09:48:14.872 INFO  GenotypeGVCFs - Start Date/Time: 27 May 2020 09:48:14 CEST
09:48:14.872 INFO  GenotypeGVCFs - ------------------------------------------------------------
09:48:14.872 INFO  GenotypeGVCFs - ------------------------------------------------------------
09:48:14.873 INFO  GenotypeGVCFs - HTSJDK Version: 2.21.2
09:48:14.873 INFO  GenotypeGVCFs - Picard Version: 2.21.9
09:48:14.873 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
09:48:14.874 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
09:48:14.874 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
09:48:14.874 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
09:48:14.874 INFO  GenotypeGVCFs - Deflater: IntelDeflater
09:48:14.874 INFO  GenotypeGVCFs - Inflater: IntelInflater
09:48:14.874 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
09:48:14.874 INFO  GenotypeGVCFs - Requester pays: disabled
09:48:14.874 INFO  GenotypeGVCFs - Initializing engine
09:48:16.015 INFO  GenotypeGVCFs - Shutting down engine
[27 May 2020 09:48:16 CEST] oAB.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=2301100032
***********************************************************************

A USER ERROR has occurred: Couldn't create GenomicsDBFeatureReader

***********************************************************************
oAB.broadinstitute.hellbender.exceptions.UserException: Couldn't create GenomicsDBFeatureReader
	at oAB.broadinstitute.hellbender.engine.FeatureDataSource.getGenomicsDBFeatureReader(FeatureDataSource.java:410)
	at oAB.broadinstitute.hellbender.engine.FeatureDataSource.getFeatureReader(FeatureDataSource.java:326)
	at oAB.broadinstitute.hellbender.engine.FeatureDataSource.<init>(FeatureDataSource.java:282)
	at oAB.broadinstitute.hellbender.engine.VariantLocusWalker.initializeDrivingVariants(VariantLocusWalker.java:76)
	at oAB.broadinstitute.hellbender.engine.VariantWalkerBase.initializeFeatures(VariantWalkerBase.java:67)
	at oAB.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:706)
	at oAB.broadinstitute.hellbender.engine.VariantLocusWalker.onStartup(VariantLocusWalker.java:63)
	at oAB.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:137)
	at oAB.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseAABs(CommandLineProgram.java:191)
	at oAB.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:210)
	at oAB.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:163)
	at oAB.broadinstitute.hellbender.Main.mainEntry(Main.java:206)
	at oAB.broadinstitute.hellbender.Main.main(Main.java:292)
Caused by: java.io.IOException: GenomicsDB JNI Error: GenomicsDBConfigException : Syntax error in JSON file /data/xxxxxx/ABchroneALL/callset.json
	at oAB.genomicsdb.reader.GenomicsDBQueryStream.jniGenomicsDBInit(Native Method)
	at oAB.genomicsdb.reader.GenomicsDBQueryStream.<init>(GenomicsDBQueryStream.java:209)
	at oAB.genomicsdb.reader.GenomicsDBQueryStream.<init>(GenomicsDBQueryStream.java:182)
	at oAB.genomicsdb.reader.GenomicsDBQueryStream.<init>(GenomicsDBQueryStream.java:91)
	at oAB.genomicsdb.reader.GenomicsDBFeatureReader.generateHeadersForQuery(GenomicsDBFeatureReader.java:176)
	at oAB.genomicsdb.reader.GenomicsDBFeatureReader.<init>(GenomicsDBFeatureReader.java:80)
	at oAB.broadinstitute.hellbender.engine.FeatureDataSource.getGenomicsDBFeatureReader(FeatureDataSource.java:407)
	... 12 more

#GenotypeGVCF working when only six samples are imported in GenomicsDB
gatk GenotypeGVCFs -R Reference/File_S16_uT_chromosomes.fasta -V gendb://GenomicsDB_wd -O test_chromosome_1_6_samples.vcf
Using GATK jar /data/xxxxx/miniconda3/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /data/xxxxx/miniconda3/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar GenotypeGVCFs -R Reference/File_S16_Tetranychus_urticae_3_chromosomes.fasta -V gendb://GenomicsDB_wd -O test_chromosome_1_6_samples.vcf
21:14:37.817 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/data/xxxxx/miniconda3/share/gatk4-4.1.6.0-0/gatk-package-4.1.6.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
May 26, 2020 9:14:38 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
21:14:38.245 INFO  GenotypeGVCFs - ------------------------------------------------------------
21:14:38.246 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.1.6.0
21:14:38.246 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
21:14:38.246 INFO  GenotypeGVCFs - Executing as xxxxx@galaxy on Linux v4.4.0-133-generic amd64
21:14:38.246 INFO  GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_192-b01
21:14:38.246 INFO  GenotypeGVCFs - Start Date/Time: 26 May 2020 21:14:37 CEST
21:14:38.246 INFO  GenotypeGVCFs - ------------------------------------------------------------
21:14:38.246 INFO  GenotypeGVCFs - ------------------------------------------------------------
21:14:38.247 INFO  GenotypeGVCFs - HTSJDK Version: 2.21.2
21:14:38.247 INFO  GenotypeGVCFs - Picard Version: 2.21.9
21:14:38.247 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
21:14:38.247 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
21:14:38.247 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
21:14:38.247 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
21:14:38.247 INFO  GenotypeGVCFs - Deflater: IntelDeflater
21:14:38.248 INFO  GenotypeGVCFs - Inflater: IntelInflater
21:14:38.248 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
21:14:38.248 INFO  GenotypeGVCFs - Requester pays: disabled
21:14:38.248 INFO  GenotypeGVCFs - Initializing engine
WARNING: No valid combination operation found for INFO field AC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AN - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field FS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field QD - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field SOR - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AN - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field FS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field QD - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field SOR - the field will NOT be part of INFO fields in the generated VCF records
21:14:39.358 INFO  GenotypeGVCFs - Done initializing engine
21:14:39.430 INFO  ProgressMeter - Starting traversal
21:14:39.431 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
WARNING: No valid combination operation found for INFO field AC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field AN - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field FS - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field QD - the field will NOT be part of INFO fields in the generated VCF records
WARNING: No valid combination operation found for INFO field SOR - the field will NOT be part of INFO fields in the generated VCF records
21:14:44.408 WARN  InbreedingCoeff - InbreedingCoeff will not be calculated; at least 10 samples must have called genotypes
21:14:49.472 INFO  ProgressMeter - chromosome_1:220314              0.2                 39000         233044.5
21:14:59.558 INFO  ProgressMeter - chromosome_1:712661              0.3                174000         518732.0
21:15:09.572 INFO  ProgressMeter - chromosome_1:1268793              0.5                295000         587240.0
21:15:19.634 INFO  ProgressMeter - chromosome_1:1772603              0.7                406000         605924.9
21:15:29.676 INFO  ProgressMeter - chromosome_1:2224562              0.8                491000         586327.0
21:15:39.688 INFO  ProgressMeter - chromosome_1:2797827              1.0                590000         587483.6
21:15:49.732 INFO  ProgressMeter - chromosome_1:3283434              1.2                692000         590611.7
21:15:59.769 INFO  ProgressMeter - chromosome_1:3697367              1.3                786000         587027.1
21:16:09.811 INFO  ProgressMeter - chromosome_1:4258637              1.5                905000         600796.6
21:16:19.812 INFO  ProgressMeter - chromosome_1:4679796              1.7                997000         595929.5
21:16:29.892 INFO  ProgressMeter - chromosome_1:5272909              1.8               1123000         609989.0
21:16:39.897 INFO  ProgressMeter - chromosome_1:5829289              2.0               1231000         613119.1
21:16:49.935 INFO  ProgressMeter - chromosome_1:6383684              2.2               1334000         613314.5
21:16:59.961 INFO  ProgressMeter - chromosome_1:6997412              2.3               1435000         612680.6
21:17:11.048 INFO  ProgressMeter - chromosome_1:7697582              2.5               1544000         611013.3
21:17:21.141 INFO  ProgressMeter - chromosome_1:8295832              2.7               1641000         608867.7
21:17:31.202 INFO  ProgressMeter - chromosome_1:9129097              2.9               1754000         612676.2
21:17:41.235 INFO  ProgressMeter - chromosome_1:10085011              3.0               1874000         618468.2
21:17:51.251 INFO  ProgressMeter - chromosome_1:10960634              3.2               1987000         621520.2

**Comment by droazen** [comment]
@nalinigans @mlathara your thoughts on this issue?

@wdermauw Did you confirm prior to the failed `GenotypeGVCFs` run that the `ABchroneALL` directory existed in the working directory, was readable, non-empty, etc.? The error you are getting is a very generic I/O error, so it's difficult to diagnose the problem without a bit more information.

**Comment by mlathara** [comment]
@wdermauw Can you paste the contents of `/data/xxxxxx/ABchroneALL/callset.json`. This error seems to suggest something is amiss with that...maybe one of the sample names was somehow mangled...

```
Caused by: java.io.IOException: GenomicsDB JNI Error: GenomicsDBConfigException : Syntax error in JSON file /data/xxxxxx/ABchroneALL/callset.json
```

**Comment by wdermauw** [comment]
@mlathara @droazen 
thank you for the quick reply...

i checked the callset.json and you are correct, sample names were somehow mingled...my sincere apologies

after the mapping/variant calling (using a pipeline), I noticed that two g.vcf.gz files had a space in their filename. I removed the space in the file name (X g.vcf.gz->X.g.vcf.gz) and continued with GenomicsDB, but apparently, GenomicsDb extracts the sample name not from the file name but from somewhere else (as in the callset.json file I found that the file mentioned above was called as X� and X�_stream, while this was not the case for all other files)

not using the vcf.gz files having a � symbol in callset.json solved the problem (GenotypeGVCF not throwing an error). 

thank you for helping out again, my apologies for the inconvenience caused

**Comment by droazen** [comment]
Closing as resolved

**Comment by zhangxiaojian-zxj** [comment]
i have meet the same question .  l want to know how to cue this question ? my sincere apologies

**Comment by zhangxiaojian-zxj** [comment]
> Closing as resolved

i have meet the same question . l want to know how to cue this question ? my sincere apologies
