### ISSUE TITLE
DepthOfCoverage docs?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6617]
It's great to see DepthOfCoverge ported to GATK4, but I noticed this line in the tool's doc: "Additionally, reads and bases can be filtered by mapping or base quality score."  I see that you can filter on base quality, but not mapping.  In GATK3, there was a -mmq argument, which doesnt seem to be in GATK4. Is there a different way to accomplish filtering on mapping quality (something with read filters perhaps), that I'm not seeing?  Was there a specific reason -mmq was dropped in GATK4?  Thanks.

**Comment by jamesemery** [comment]
Hello @bbimber thank you for the response. I would recommend using the read filters (in your case `-rf MappingQualityReadFilter --minimum-mapping-quality ##` to achieve the same functionality as the `-mmq` argument from GATK3. When porting over the tool we tried to push as much functionality into from obscure arguments into the existing filtering framework as possible and `-mmq` was one of the ones that was redundant as it was a simple filter placed on the reads before counting them. I will add some lines to the documentation clarifying this for users in the future.

**Comment by bbimber** [comment]
OK.  Another thing: since in GATK4 it inherits from LocusWalkerByInterval, -L is now required.  the usage examples still say -L is optional.  

Tangentially is there a shortcut way to say pass "all intervals in the genome" to GATK?  Can one pass the genome's DICT file or something like this?  Certainly it's not that hard to convert a .dict file to an interval list, but not automatic.

**Comment by jamesemery** [comment]
@bbimber can you open another ticket for your comment about -L? That is a reasonable complaint about the tool usability that would be worth addressing and we should make another issue to track this.
