### ISSUE TITLE
DepthOfCoverage logger

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6621]
Hello,

We've been using GATK4 DepthOfCoverage.  I noticed this:

log4j:WARN No appenders could be found for logger (org.broadinstitute.hellbender.tools.walkers.coverage.DepthOfCoverage).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

I noticed that DepthOfCoverage defines its own logger on line 84:

private final static Logger logger = Logger.getLogger(DepthOfCoverage.class);

Should it?

**Comment by samuelklee** [comment]
Thanks for catching this, @bbimber! I've opened a PR to address it.
