### ISSUE TITLE
Another DepthOfCoverage Comment

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6623]
One more DepthOfCoverage observation.  The GATK4 version let's one control the delimiter in the output, which seems like a useful idea.  However:

1) this isnt that big a deal, but why change the GATK3 default of tab to comma in GATK4?

2) The enum is named CSV and TABLE.  Why not rename 'TABLE' to 'TSV' to make it more clear? A comma-delimited table is still a table.  This is a beta tool now, and I assume with the next release changing an argument becomes harder.

**Comment by jamesemery** [comment]
@bbimber Thank you for your comment. In response to 1 this is a minor oversight, you are welcome to submit a PR to change that default back if you think it is important.
As for 2, that was GATK3 logic (which I think was intending to reflect Rtable file formatting) to keep the names as they are. You are welcome to submit a PR changing that argument though there is reason to preserve continuity with GATK tool that users are used to if they are doing specific things with the DepthOfCoverage.

**Comment by bbimber** [comment]
Thanks - neither of these are really that big a problem
