### ISSUE TITLE
variants processed metric not initialized properly

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#6631]
This request was created from a contribution made by danilovkiri on May 07, 2020 15:54 UTC.

Link: https://gatk.broadinstitute.org/hc/en-us/community/posts/360062628652-GATK-4-1-7-0-VariantAnnotator-Processing-Speed-Drop

--

GATK 4.1.7.0 VariantAnnotator processing speed rapidly decreases over time. Running with single-sample VCF file obtained from GenotypeGVCFs. No other tools were executed during the VariantAnnotator running. No RAM or SSD space overuse was found.

The INFO log is shown below. The exact command is at the top section of the log.

 

Using GATK jar /home/wgs/Tools/gatk-4.1.7.0/gatk-package-4.1.7.0-local.jar  
Running:  
java -Dsamjdk.use\_async\_io\_read\_samtools=false -Dsamjdk.use\_async\_io\_write\_samtools=true -Dsamjdk.use\_async\_io\_write\_tribble=false -Dsamjdk.compression\_level=2 -Xmx30G -Xms1G -jar /home/wgs/Tools/gatk-4.1.7.0/gatk-package-4.1.7.0-local.jar VariantAnnotator --reference /home/wgs/Genomes/hg38/bwa/hg38.fa --dbsnp /home/wgs/Tools/Supplementary/dbsnp-153-hgvs.sorted.hg38.vcf.gz --variant ./barcode.raw21-22.vcf.gz --output ../annotated\_output/barcode.gatk\_annotated21-22.vcf.gz -L chr21 -L chr22  
18:34:24.702 INFO NativeLibraryLoader - Loading libgkl\_compression.so from jar:file:/home/wgs/Tools/gatk-4.1.7.0/gatk-package-4.1.7.0-local.jar!/com/intel/gkl/native/libgkl\_compression.so  
May 07, 2020 6:34:24 PM shaded.cloud\_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine  
INFO: Failed to detect whether we are running on Google Compute Engine.  
18:34:24.814 INFO VariantAnnotator - ------------------------------------------------------------  
18:34:24.815 INFO VariantAnnotator - The Genome Analysis Toolkit (GATK) v4.1.7.0  
18:34:24.815 INFO VariantAnnotator - For support and documentation go to [https://software.broadinstitute.org/gatk/](https://software.broadinstitute.org/gatk/)  
18:34:24.815 INFO VariantAnnotator - Executing as wgs@wgs on Linux v4.15.0-99-generic amd64  
18:34:24.815 INFO VariantAnnotator - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0\_201-b09  
18:34:24.815 INFO VariantAnnotator - Start Date/Time: May 7, 2020 6:34:24 PM MSK  
18:34:24.815 INFO VariantAnnotator - ------------------------------------------------------------  
18:34:24.815 INFO VariantAnnotator - ------------------------------------------------------------  
18:34:24.815 INFO VariantAnnotator - HTSJDK Version: 2.21.2  
18:34:24.815 INFO VariantAnnotator - Picard Version: 2.21.9  
18:34:24.815 INFO VariantAnnotator - HTSJDK Defaults.COMPRESSION\_LEVEL : 2  
18:34:24.815 INFO VariantAnnotator - HTSJDK Defaults.USE\_ASYNC\_IO\_READ\_FOR\_SAMTOOLS : false  
18:34:24.815 INFO VariantAnnotator - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_SAMTOOLS : true  
18:34:24.816 INFO VariantAnnotator - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_TRIBBLE : false  
18:34:24.816 INFO VariantAnnotator - Deflater: IntelDeflater  
18:34:24.816 INFO VariantAnnotator - Inflater: IntelInflater  
18:34:24.816 INFO VariantAnnotator - GCS max retries/reopens: 20  
18:34:24.816 INFO VariantAnnotator - Requester pays: disabled  
18:34:24.816 INFO VariantAnnotator - Initializing engine  
18:34:25.065 INFO FeatureManager - Using codec VCFCodec to read file file:///home/wgs/Tools/Supplementary/dbsnp-153-hgvs.sorted.hg38.vcf.gz  
18:34:25.135 INFO FeatureManager - Using codec VCFCodec to read file file:///home/wgs/Analysis/barcode/gatk\_gvcf\_output/./barcode.raw21-22.vcf.gz  
18:34:25.197 INFO IntervalArgumentCollection - Processing 97528451 bp from intervals  
18:34:25.214 INFO VariantAnnotator - Done initializing engine  
18:34:25.265 INFO ProgressMeter - Starting traversal  
18:34:25.266 INFO ProgressMeter - Current Locus Elapsed Minutes Variants Processed Variants/Minute  
18:34:42.165 INFO ProgressMeter - chr21:5011000 0.3 5011000 17792638.2  
18:34:57.943 INFO ProgressMeter - chr21:5013000 0.5 5013000 9204639.3  
18:35:13.744 INFO ProgressMeter - chr21:5015000 0.8 5015000 6206939.2  
18:35:28.855 INFO ProgressMeter - chr21:5017000 1.1 5017000 4733837.6  
18:35:43.825 INFO ProgressMeter - chr21:5019000 1.3 5019000 3833297.3  
18:35:58.909 INFO ProgressMeter - chr21:5021000 1.6 5021000 3217111.8  
18:36:13.945 INFO ProgressMeter - chr21:5023000 1.8 5023000 2773120.8  
18:36:28.938 INFO ProgressMeter - chr21:5025000 2.1 5025000 2437900.3  
18:36:43.900 INFO ProgressMeter - chr21:5027000 2.3 5027000 2175656.8  
18:36:58.880 INFO ProgressMeter - chr21:5029000 2.6 5029000 1964274.1  
18:37:14.093 INFO ProgressMeter - chr21:5031000 2.8 5031000 1787994.7  
18:37:29.178 INFO ProgressMeter - chr21:5033000 3.1 5033000 1641980.9  
18:37:44.417 INFO ProgressMeter - chr21:5035000 3.3 5035000 1516939.4  
18:37:59.497 INFO ProgressMeter - chr21:5037000 3.6 5037000 1410720.2  
18:38:14.458 INFO ProgressMeter - chr21:5039000 3.8 5039000 1319156.0  
18:38:29.564 INFO ProgressMeter - chr21:5041000 4.1 5041000 1238078.1  
18:38:44.564 INFO ProgressMeter - chr21:5043000 4.3 5043000 1166919.9  
18:38:59.513 INFO ProgressMeter - chr21:5045000 4.6 5045000 1103749.5  
18:39:14.502 INFO ProgressMeter - chr21:5047000 4.8 5047000 1046965.1  
18:39:29.596 INFO ProgressMeter - chr21:5049000 5.1 5049000 995432.6  
18:39:44.628 INFO ProgressMeter - chr21:5051000 5.3 5051000 948954.5  
18:39:59.768 INFO ProgressMeter - chr21:5053000 5.6 5053000 906362.3  
18:40:14.735 INFO ProgressMeter - chr21:5055000 5.8 5055000 867888.1  
18:40:29.638 INFO ProgressMeter - chr21:5057000 6.1 5057000 832720.4  
18:40:44.659 INFO ProgressMeter - chr21:5059000 6.3 5059000 800069.6  
18:40:59.657 INFO ProgressMeter - chr21:5061000 6.6 5061000 769946.6  
18:41:14.687 INFO ProgressMeter - chr21:5063000 6.8 5063000 741974.6  
18:41:29.771 INFO ProgressMeter - chr21:5065000 7.1 5065000 715892.6  
18:41:44.840 INFO ProgressMeter - chr21:5067000 7.3 5067000 691624.2  
18:41:59.881 INFO ProgressMeter - chr21:5069000 7.6 5069000 669005.6  
18:42:14.970 INFO ProgressMeter - chr21:5071001 7.8 5071000 647769.7  
18:42:30.070 INFO ProgressMeter - chr21:5073001 8.1 5073000 627841.4  
18:42:45.137 INFO ProgressMeter - chr21:5075001 8.3 5075000 609157.2  
18:43:00.141 INFO ProgressMeter - chr21:5077001 8.6 5077000 591638.7  
18:43:15.170 INFO ProgressMeter - chr21:5079001 8.8 5079000 575085.3  
18:43:30.158 INFO ProgressMeter - chr21:5081001 9.1 5081000 559487.0  
18:43:45.170 INFO ProgressMeter - chr21:5083001 9.3 5083000 544700.5  
18:44:00.166 INFO ProgressMeter - chr21:5085001 9.6 5085000 530701.0  
18:44:15.249 INFO ProgressMeter - chr21:5087001 9.8 5087000 517336.9  
18:44:30.146 INFO ProgressMeter - chr21:5089001 10.1 5089000 504795.2  
18:44:45.136 INFO ProgressMeter - chr21:5091001 10.3 5091000 492780.7  
18:45:00.171 INFO ProgressMeter - chr21:5093001 10.6 5093000 481300.4  
18:45:15.178 INFO ProgressMeter - chr21:5095001 10.8 5095000 470371.4  
18:45:30.141 INFO ProgressMeter - chr21:5097001 11.1 5097000 459966.2  
18:45:45.097 INFO ProgressMeter - chr21:5099001 11.3 5099000 450023.6  
18:46:00.037 INFO ProgressMeter - chr21:5101001 11.6 5101000 440519.3  
18:46:14.991 INFO ProgressMeter - chr21:5103001 11.8 5103000 431406.5  
18:46:29.942 INFO ProgressMeter - chr21:5105002 12.1 5105000 422671.6  
18:46:44.855 INFO ProgressMeter - chr21:5107002 12.3 5107000 414311.2  
18:46:59.795 INFO ProgressMeter - chr21:5109002 12.6 5109000 406266.7  
18:47:14.769 INFO ProgressMeter - chr21:5111002 12.8 5111000 398517.0  
18:47:29.707 INFO ProgressMeter - chr21:5113002 13.1 5113000 391081.0<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/5566'>Zendesk ticket #5566</a>)<br>gz#5566</i>

**Comment by droazen** [comment]
@bhanugandham Based on our understanding of the code, we could not get the progress meter output we see here without there being actual variant records in the first 5 million bases of chr21. To debug this further, we'd need to inspect the user's actual `--variant` input (`barcode.raw21-22.vcf.gz`)

**Comment by lbergelson** [comment]
The progress meter is correct.  There just happened to be 5 million empty no calls at the start of the file which processed very fast.
