### ISSUE TITLE
AnalyzeCovariates Rscript error

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#6650]
This request was created from a contribution made by Lucas Kopecky Bobadilla on June 05, 2020 15:53 UTC.

Link: https://gatk.broadinstitute.org/hc/en-us/community/posts/360067974992-AnalyzeCovariates

--

 

Hello I am using the current 4.17 GATK version and I am trying to run AnalyzeCovariates. I ran the baserecalibrator to get the table file to run AnalyzeCovariates but I am getting this following error in the R command:

[June 5, 2020 10:45:08 AM CDT] org.broadinstitute.hellbender.tools.walkers.bqsr.AnalyzeCovariates done. Elapsed time: 0.02 minutes.

Runtime.totalMemory()=1233649664

org.broadinstitute.hellbender.utils.R.RScriptExecutorException: 

Rscript exited with 1

Command Line: Rscript -e tempLibDir = '/tmp/Rlib.323393943272793217';source('/tmp/BQSR.1306882797239975225.R'); /tmp/AnalyzeCovariates5750988274473323663.csv /media/brent/lucas\_SSD/dicamba\_rnaseq/GATK/qlty\_recalibration/trim\_DIC\_CHR\_F2\_R\_104\_1.table /media/brent/lucas\_SSD/dicamba\_rnaseq/GATK/qlty\_recalibration/AnalyzeCovariates.pdf

Stdout: 

Stderr: 

Attaching package: ‘gplots’

 

The following object is masked from ‘package:stats’:

 

    lowess

 

Error in distributeGraphRows(list(a, b, c), c(1, 1, 1)) : 

  object 'a' not found

Calls: source -> withVisible -> eval -> eval -> distributeGraphRows

Execution halted

 

Any idea what is going on?

 

Thanks!<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/5868'>Zendesk ticket #5868</a>)<br>gz#5868</i>

**Comment by bhanugandham** [comment]
User solved this issue by changing the line 16 in the Rscript from:

data <- read.csv(args[1])
to
data <- read.csv(args[1], stringsAsFactors = TRUE)

Can we make this change in our code?

**Comment by AleksandarBeatovic** [comment]
> User solved this issue by changing the line 16 in the Rscript from:
> 
> data <- read.csv(args[1])
> to
> data <- read.csv(args[1], stringsAsFactors = TRUE)
> 
> Can we make this change in our code?
Hello, could you please tell me where this R script is located? Thank you in advance!
