### ISSUE TITLE
GnarlyGenotyperIntegrationTest.testUsingGenomicsDB skipped on Travis.

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#6657]
Not sure if intermittent:
`Gradle suite > Gradle test > org.broadinstitute.hellbender.tools.walkers.GnarlyGenotyperIntegrationTest > testUsingGenomicsDB[4]([Ljava.io.File;@4f23de76, src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/twoSampleAS.vcf, src/test/resources/org/broadinstitute/hellbender/tools/walkers/GnarlyGenotyper/twoSampleASDB.vcf, [20:1-2147483647], [], /home/travis/build/broadinstitute/gatk/src/test/resources/large/human_g1k_v37.20.21.fasta) SKIPPED`

**Comment by droazen** [comment]
@samuelklee Did you find that this was repeatable?

**Comment by samuelklee** [comment]
Haven’t seen it since.

**Comment by droazen** [comment]
Closing for now -- @samuelklee feel free to reopen if you see this again.
