### ISSUE TITLE
GenomicsDB does not recognize certain features in GVCF files. 

### ISSUE THREAD

**Issue by zhen-fu** [broadinstitute/gatk#6670]
I used HaplotypeCaller (-ERC GVCF) to generate a few hundred GVCF files (see a section below, Fig. 1
![Fig1](https://user-images.githubusercontent.com/15146751/85318178-27d2d500-b485-11ea-8efb-a92bdad2cc1d.png)
). Then I was trying to use GenomicsDBImport to generate the datastore to be further processed by GenotypeGVCFs:
`gatk --java-options "-Xmx10g -Xms10g" GenomicsDBImport \
       --genomicsdb-workspace-path /home/zhen.fu/fu_scratch/Helico/genotye/chr1 \
      --batch-size 30 \
       -L HaChr01 \
       --sample-name-map sample_map_file \
       --tmp-dir=/home/zhen.fu/fu_scratch/Helico/genotye/tmp \
       --reader-threads 2
`

However, I realized that GenomicsDBImport seemed to only recognize "GT:DP:GQ:MIN_DP:PL", where ALT field is <NON_REF> for these sites. Conversely, GenomicsDBImport did not recognize the features in the true variant sites, where a true variant and <NON_REF> coexist, such as "GT:AD:DP:GQ:PL:SB". As GVCF records all sites, including the variant and non-variant sites. 

 The error I got was:
![Fig2](https://user-images.githubusercontent.com/15146751/85318248-3f11c280-b485-11ea-9c5e-71f01b8db1d9.png)

The GenomicsDBImport would only process the first batch (30 samples) and not going further. 
The version I am using is GATK 4.15

**Comment by mlathara** [comment]
@zhen-fu Can you attach the full output of GenomicsDBImport (including the full stack trace for the error you see). Also, did you process/change these vcfs in anyway between generating them from HaplotypeCaller and trying to import into GenomicsDB?

**Comment by zhen-fu** [comment]
Hi there, sorry it was my mistake, there was one g.vcf file finished abnormally, that caused this error. After fixing this file, it is working gracefully. Thank you!

**Comment by lbergelson** [comment]
Thanks for following up!
