### ISSUE TITLE
-dont-use-soft-clipped-bases doesn't work

### ISSUE THREAD

**Issue by davidbenjamin** [broadinstitute/gatk#6686]
Prior to assembly (in `AssemblyBasedCallerUtils.assembleReads`, we transform reads in several ways that are meant to be permanent (that is, we want to use them in both assembly and genotyping) within `finalizeRegion`.  (Additionally, we error reads within `ReadThreadingAssembler.runLocalAssembly`, but this is done on temporary copies of reads that are used for kmers and discarded).  These transformations include hard clipping low-quality ends, adaptor sequences, and, optionally, soft-clipped bases, as well as correcting the base qualities of overlapping mates.

According to the git history, these transformations have been accidentally temporary for quite a while.  Let's look at the relevant code.  First, in `Mutect2Engine.callRegion` we have (comments added and code simplified for clarity)

```
final AssemblyRegion assemblyActiveRegion = AssemblyBasedCallerUtils.assemblyRegionWithWellMappedReads(originalAssemblyRegion . . .);

// assembleReads finalizes region, modifying reads as a side effect
final AssemblyResultSet untrimmedAssemblyResult = AssemblyBasedCallerUtils.assembleReads(assemblyActiveRegion. . .);

final SortedSet<VariantContext> allVariationEvents = untrimmedAssemblyResult.getVariationEvents(MTAC.maxMnpDistance);

// when we trim on the originalAssemblyRegion, the trimmingResult takes its un-modified reads!
 final AssemblyRegionTrimmer.Result trimmingResult = trimmer.trim(originalAssemblyRegion, allVariationEvents, referenceContext);

// now the assemblyResult gets the unmodified reads of the trimmingResult!
final AssemblyResultSet assemblyResult = untrimmedAssemblyResult.trimTo(trimmingResult.getVariantRegion());
```

If we want things like `-dont-use-soft-clipped-bases` to work, we should call `trimmer.trim` on `untrimmedAssemblyResult`.  I think that change alone may be all we need.

Let's look at the corresponding code in `HaplotypeCallerEngine`:

```
final AssemblyResultSet untrimmedAssemblyResult =  AssemblyBasedCallerUtils.assembleReads(region. . .);

final SortedSet<VariantContext> allVariationEvents = untrimmedAssemblyResult.getVariationEvents(hcArgs.maxMnpDistance);

// same things as Mutect2 — we trim on the unmodified region
final AssemblyRegionTrimmer.Result trimmingResult = trimmer.trim(region, allVariationEvents, referenceContext);

// same as Mutect2
final AssemblyResultSet assemblyResult = untrimmedAssemblyResult.trimTo(trimmingResult.getVariantRegion());
```

In addition to the proposed simple fix, this brings up a few code smells:

* One would expect assembly not to modify its input reads, but it does through the side effect of `finalizeRegion`.
* Assembly has both the permanent changes of finalize region and the temporary changes of read error correction.
* `AssemblyResultSet` stores the reads but so does `AssemblyRegion`.

Without doing any serious refactoring, perhaps `finalizeRegion` could at least be split off from assembly so that the latter does not stealthily modify reads.

**Comment by davidbenjamin** [comment]
@ldgauthier @vruano Could I get your opinion on whether the changes to reads made in `finalizeRegion` are intended for pair-HMM and genotyping and not just assembly?  They certainly are in Mutect2, but I'm not sure about HaplotypeCaller.

**Comment by droazen** [comment]
@davidbenjamin I believe that the `trim()` call in question has always been on the original region, going back to GATK 3.x. Here's the equivalent line from the GATK 3.x `HaplotypeCaller` (line 901 HaplotypeCaller.java):

```
        final ActiveRegionTrimmer.Result trimmingResult = trimmer.trim(originalActiveRegion,allVariationEvents);
```

And, as in GATK 4.x, the clipping code in GATK 3.x called `clone()` on each read prior to clipping. It's worth testing whether the equivalent argument in GATK 3.x (which was named `--dontUseSoftClippedBases`) worked at all.

**Comment by droazen** [comment]
@davidbenjamin Actually, digging a bit deeper into the code, doesn't `AssemblyBasedCallerUtils.finalizeRegion()` replace the reads in the original `AssemblyRegion` with the clipped reads when it calls:

```
        region.clearReads();
        region.addAll(readsToUse);
```

And therefore the later call to `trim()` on the original region is actually seeing the clipped reads after all?

Have you checked your original hypothesis in a debugger?

**Comment by jamesemery** [comment]
I have empirically observed that in haplotype caller making modifications to the reads in the assemblyRegion.finalize() call (like adding annotations) results do percolate out to the genotyper. This applies to HaplotypeCaller though M2 might be doing something different that I am unaware of. Have we checked that the bug-report applies for both HaplotypeCaller and M2?

**Comment by davidbenjamin** [comment]
I have debugged with M2 exhaustively and I am as positive as can be (which is not 100% given current amounts of sleep).  I have not checked HaplotypeCaller but I trust James' observations.  

Perhaps the difference comes from the extra layer of transformations in M2.  That is, we have in M2 `originalActiveRegion -> assemblyActiveRegion -> untrimmedAssemblyResult`, hence assembling the reads in `assemblyActiveRegion` do not modify those in `originalActiveRegion` as a side effect.  In HaplotypeCaller we just have `region -> untrimmedAssemblyResult`, so that the side effects are on the original `region`.

Therefore it appears this is just an M2 bug.

**Comment by droazen** [comment]
As part of our work on this ticket can we confirm our belief that it doesn't apply to `HaplotypeCaller`?
