### ISSUE TITLE
Debugging Suggestions on GenomicsDB Run?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6688]
We are running GenomicsDBImport on a single chromosome with about 96 WGS gVCF samples as input.  It's being run on a slurm cluster, lustre filesystem.  Most of the scatter jobs finished, but the 4 largest have been sitting for nearly 5 days, and it's not clear whether they're doing anything, or what the problem is.  Can you suggest any debugging steps to try to troubleshoot what's going on with the jobs?  The command is essentially this:

java -Djava.io.tmpdir=<a local SSD on the node> \
-Xmx128g -Xms128g -Xss2m \
-jar GenomeAnalysisTK4.jar \
GenomicsDBImport \
-V <repeated for 96 different gVCFs> \
-L intervals.list \
 --genomicsdb-workspace-path <a lustre directory>

Thanks for any debugging suggestions.

-Ben

**Comment by lbergelson** [comment]
@bbimber Can you describe the interval list for the ones that are failing? Is it a single chunk of chromosome or many small ones?

**Comment by bbimber** [comment]
They are all intact chromosomes. The ones still going are each one chromosome and happen to be the largest 4. Also, it isn't entirely clear if they are failing per se, just that they've been hanging for a week without anything obvious happening.

**Comment by mlathara** [comment]
@bbimber You probably won't want to restart at this point, but the latest release (https://github.com/broadinstitute/gatk/releases/tag/4.1.8.0) has some optimizations targeted towards shared posix filesystems -- a knob called `--genomicsdb-shared-posixfs-optimizations`. It also reduces the storage space requirements for the genomicsdb workspace substantially.

You could also try to check on the size of the workspace where that scatter job is writing. The import should be writing to an "invisible" file (i.e., one starting with a ".") so no file may be visible under the contig directory. But if the process is making progress, the size should increase over time.

**Comment by mlathara** [comment]
Another good point @nalinigans brought up when I chatted with her about this was the amount of memory you're allocating for Java here. Do you happen to know how much memory the nodes you're running these on have? The `-Xmx128g -Xms128g` parameters set memory for Java obviously, but we also need some memory for the native (C/C++) part of the code. If these nodes don't have much more than 128G, then that could be starving out the native layer and explain some of this slowness. You could also try lowering that a bit (96G maybe?) to see if that makes a difference.

**Comment by bbimber** [comment]
@mlathara The nodes have considerably more (256 or so).  is there any rule or thumb or guidance on expected memory needs based on number of gVCFs and/or type of input (WES vs WGS)?

I do think you might be onto something though.  Out default cluster submission code takes our slurm job memory request, subtracts only a few GB and passes the remainder to -Xmx/Xms.  I will update to leave more buffer as you suggest.

Our cluster happens to be undergoing maintenance this week, so this particular job was killed.  I'll update the GATK version, add --genomicsdb-shared-posixfs-optimizations, and adjust the memory.

One other thing: i noticed GenomicsDBImport is not nearly as verbose in logging as typical GATK tools.  Is that expected, or a symptom of whatever problem we're having?

**Comment by mlathara** [comment]
Offhand I don't have any rule of thumb for memory usage, unfortunately. One thing that can help to reduce memory pressure is to use the `--batch-size` parameter. Also, this doesn't help you now, but we're looking to enable a feature to reduce the memory usage by 5x or more. Works for local/posix files right now, but we need a little tinkering to make it work with Google cloud files.

Regarding logging for GenomicsDBImport - that is expected. A lot of the heavy lifting is done by the native layer, so we need to do a bit more work to push updates back to the progress meter. It's on our to-do list....

**Comment by bbimber** [comment]
OK.  Giving the job more memory isnt really a problem.  Batch size is one thing we're interested in, i.e. how many WGS gVCFs can we practically combine at once, as compared to doing an iterative approach where we initialize a workspace with X gVCFs, and then keep appending new batches to it.

**Comment by mlathara** [comment]
The two main resources limiting how many gVCFs you can import at once will be memory and file handles. 

I'm not sure if you mean incremental import or batch size when you mention the iterative approach. I assume the latter, but just want to clarify that there isn't any reason to break up the import using incremental import. The batch size parameter effectively does that, so you might as well import all gVCFs you have available (optionally using batch size if you're running out of memory).

I'll throw out batch sizes of 50 or 100 as being reasonable, but the size of the intervals being imported will make a difference. It would be best to try to monitor how much memory is being used with those settings. There won't be a huge difference in import performance depending on the number of batches (ignoring memory issues) but if you have more than a 100 or so batches and you don't enable the `--consolidate` option you may see some query performance degradation.

**Comment by bbimber** [comment]
OK, interesting.  This was not entirely clear from the docs.  Our cluster in theory is functioning again on monday and we will start these.

**Comment by nalinigans** [comment]
@bbimber, could you make any progress?

**Comment by bbimber** [comment]
We've now run into a secondary issue with GenomicsDB workspaces.  In the thread above we talked about problems with WGS import, and reducing batchSize seemed to help.  Separately, we created a GenomicsDB workspace with a few hundred exome samples - this import worked fine with default settings.

Next, we are using this workspace as input for GenotypeGVCFs.  However, the performance is much, much slower than we saw when using similar sized combined gVCFs as input.  Do you expect this?  Are there ways to improve this?  If one thinks about a genomicsDB workspace more like a database than single file, are there defrag/shrink-like tasks that need to be performed on the workspace for efficiency?

**Comment by lbergelson** [comment]
@bbimber There is a defrag operation that you can perform on the DB.  My understanding is that it's only necessary if you have >100ish input batches.    

When you say similar size combine gVcfs do you mean similar size of the input data, or similar size of the stored database compared to the merged gvcf?  If you mean the later then that's expected because a genomicsdb will have much more data than an equivalent gvcf.  I assume you mean the former though.  I believe it is also expected that running from a genomicsdb should be slower than from a combined gvcf (up to a certain size of gvcf)  because the combination operation is done at at read-time so it slows down the genotyping operation.  The thing to look at is the sum of GenomicsDBImport + GenotypeGvcfs vs CombineGVCFS + GenotypeGvcfs.

**Comment by nalinigans** [comment]
> If one thinks about a genomicsDB workspace more like a database than single file, are there defrag/shrink-like tasks that need to be performed on the workspace for efficiency?
Did  you use the `--consolidate` option with GenomicsDBImport? This option consolidates fragments to help with query performance later. Usually not needed for very small batch sizes.
Also, available from 4.1.7.0 is a `--genomicsdb-shared-posixfs-optimizations` option. Can you try GenotypeGVCFs with this knob turned on and let us know?

**Comment by bbimber** [comment]
@lbergelson yes, i meant the same number of WES samples as input (either merged into one gVCF or imported into one workspace), not size of data on the disk.

I did not use --consolidate because your docs seemed to recommend against it.  For WES, we performed the GenomicsDB import with default options, which I assume means no batching.  We are doing batching on our WGS data, but that is not complete yet and we havent yet tried this for GenotypeGVCFs.

I didnt realize --genomicsdb-shared-posixfs-optimizations was an option for GenotypeGVCFs, but will try this.

**Comment by bbimber** [comment]
One tangential question.  If we run GenotypeGVCFs with a GenomicsDB workspace as the input, can we scatter/gather across arbitrary intervals, or do we need to execute that with intact contigs?  I recall that operations like CombineGVCFs need to operate on intact contigs, since the gVCF blocks might span across a given interval otherwise.

**Comment by lbergelson** [comment]
You should be able to scatter on arbitrary intervals.  I thought you could do so with CombineGvcfs as well.  You need to specify the --only-output-calls-starting-in-intervals option though or you can get duplicate calls.

**Comment by droazen** [comment]
@bbimber Do you consider this issue resolved?

**Comment by bbimber** [comment]
@droazen yes, at least to a point we have this worked out.  we really needed something besides CombineGVCFs in order to scale, but GenomicsDB definitely is a new format and I hope the tool keeps getting fleshed out.

One final question: is there a way to check the integrity of a GenomicsDB instance?  With a VCF one could at least iterate it, or check that it's a valid (non-truncated) gzip file.  

Thanks for the help - we can close the issue as well.

**Comment by droazen** [comment]
@nalinigans @mlathara Is there an integrity checker tool for GenomicsDB (or a programmatic way to check the integrity of a GenomicsDB instance)?

**Comment by droazen** [comment]
@bbimber Can this one be closed?

**Comment by nalinigans** [comment]
Just to add - GenomicsDB relies on the filesystem for integrity checks just like any other file on the filesystem. We could add integrity checks at a micro chunk-level, but that would be at the expense of performance.

**Comment by bbimber** [comment]
ok, thanks
