### ISSUE TITLE
Funcotator appears to add extra tab at end of line

### ISSUE THREAD

**Issue by fleharty** [broadinstitute/gatk#6693]
### Affected tool(s) or class(es)
Funcotator

### Affected version(s)
- [x] Latest public release version [version?]
- [x] Latest master branch as of [date of test?]

### Description 
Funcotator appears to output an unnecessary extra tab at the end of each line.

The change appears to have happened between gatk 4.1.4.0 and 4.1.6.0.

#### Expected behavior
Output correct number of tabs corresponding to the number of column headers.

#### Actual behavior
Outputs an extra tab.

**Comment by fleharty** [comment]
@jonn-smith If you get a sec, could you take a look at this?

**Comment by jonn-smith** [comment]
I'm guessing this is the MAF output then?

**Comment by fleharty** [comment]
@jonn-smith Yes, in the MAF

**Comment by jonn-smith** [comment]
OK - I found where it was happening.

This will be fixed along with the Funcotator Data Sources update.

**Comment by fleharty** [comment]
@jonn-smith Great, thaks!
