### ISSUE TITLE
GatherVcfs has a weird description about `--CREATE-INDEX`  option.

### ISSUE THREAD

**Issue by hsiaoyi0504** [broadinstitute/gatk#6697]
### Tool(s) or class(es) involved
GatherVcfs 

### Description 
https://gatk.broadinstitute.org/hc/en-us/articles/360045252512-GatherVcfs-Picard-
GatherVcfs has a weird description about `--CREATE-INDEX`  option.
It seems to me that the input and output of this tool are vcf files, but what documentation refers to is about a bam file output.

**Comment by droazen** [comment]
@hsiaoyi0504 Since this is a Picard tool, would you mind filing this ticket in the Picard repo: 
https://github.com/broadinstitute/picard ?

**Comment by hsiaoyi0504** [comment]
Sorry, @droazen. I am confused. In Picard’s documentation, it doesn’t mention this part: https://broadinstitute.github.io/picard/command-line-overview.html#GatherVcfs. Therefore, I thought this issue belongs here. Would you mind explain a little bit more? Thank you.

**Comment by cmnbroad** [comment]
Hi @hsiaoyi0504 - it is a bit confusing, but the fix for this issue will require changes in the picard source, so the issue needs to live there. I'll transfer it over - thx for reporting it.
