### ISSUE TITLE
Make the caching in FeatureDataSource more "window friendly" 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#670]
Make the caching in FeatureDataSource more "window friendly" (ie., prefetch and cache around the current interval instead of just after it).

Came up in the review of https://github.com/broadinstitute/hellbender/pull/614

**Comment by akiezun** [comment]
does this need to be in alpha? seems to be an optimization that can be postponed?

**Comment by droazen** [comment]
We've recently seen what a huge different the `FeatureDataSource` caching makes in the walker version of BQSR -- it is literally the difference between being able to run the tool to completion on large inputs and not being able to do so. This change would allow us to expand the caching to non-ReadWalker tools, which should improve people's initial experience running the hellbender tools by quite a bit. I vote to keep this in for alpha.

**Comment by droazen** [comment]
It seems like the existing caching that only looks ahead is actually good enough for most `VariantWalkers` -- `VariantFiltration` is an unusual case.

**Comment by droazen** [comment]
Closing this in favor of https://github.com/broadinstitute/gatk/issues/1151, since that is the only case that actually needs this feature.
