### ISSUE TITLE
RealignerTargetCreateur

### ISSUE THREAD

**Issue by elbakrifz** [broadinstitute/gatk#6703]
I WAS running this commande : java -jar /Users/mac/Downloads/gatk-4.1.8.0/gatk-package-4.1.8.0-local.jar  RealignerTargetCreator \                                                                                                                                                                            -R /Users/mac/Desktop/LmjFwholegenome_20070731_V5.2.fasta                                                                                                          -I /Users/mac/Desktop/NGS/marked-duplicates42.bam                                                                                                                       -O SRR6369642_realtarget.list  
 I get : 
A USER ERROR has occurred: RealignerTargetCreator is no longer included in GATK as of version 4.0.0.0. Please use GATK3 to run this tool

***********************************************************************
Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.

**Comment by elbakrifz** [comment]
I got the gatk_3.8 without java file

**Comment by cmnbroad** [comment]
@elbakrifz RealignerTargetCreator is no longer included in GATK.

This repo is for tracking GATK bugs and feature requests. For questions and usage help, please see the forums at https://gatk.broadinstitute.org/hc.
