### ISSUE TITLE
Haplotypecaller multithreading core use 

### ISSUE THREAD

**Issue by madzayasodara** [broadinstitute/gatk#6704]
Hi I'm using Haplotypecaller with multithreads (-nct 4) and would like to know whether the threads run in one core or each thread should be given a core (so using SLURM -c 4). thank you

**Comment by lbergelson** [comment]
@madzayasodara This sort of question should be asked on the [GATK forums](https://gatk.broadinstitute.org/hc/en-us/community/topics).  This is for reporting bugs and documentation issues.   It also sounds like you're using gatk 3 which is no longer supported.  We recommend upgrading to gatk 4.1.8.0.
