### ISSUE TITLE
PathSeqScore fails with java.util.NoSuchElementException: next on empty iterator

### ISSUE THREAD

**Issue by spromanos** [broadinstitute/gatk#6709]
Hi GATK team,

I tried running your PathSeq pipeline (broadinstitute/gatk:4.1.8.0) on my cohort and almost half of the samples failed the scoring step with this error message:
`20/07/17 09:38:35 INFO NewHadoopRDD: Input split: file:/cromwell_root/fc-6e61d4b2-bdc8-4abd-bb94-18d8fa11d9b6/7c1b0faa-e956-4289-9e2d-4fb8b9eff6ff/PathSeqPipeline/0ca5578f-70d3-498e-b7cc-23590f0ab31f/call-PathSeqAlign/MMRF_2072_2_BM.microbe_aligned.paired.bam:33554432+33554432 20/07/17 09:38:46 ERROR Executor: Exception in task 0.0 in stage 2.0 (TID 5) java.util.NoSuchElementException: next on empty iterator at scala.collection.Iterator$$anon$2.next(Iterator.scala:39) at scala.collection.Iterator$$anon$2.next(Iterator.scala:37) at scala.collection.Iterator$$anon$13.next(Iterator.scala:469) at scala.collection.convert.Wrappers$IteratorWrapper.next(Wrappers.scala:31) at org.broadinstitute.hellbender.relocated.com.google.common.collect.Iterators$PeekingImpl.next(Iterators.java:1155) at org.broadinstitute.hellbender.utils.spark.SparkUtils.lambda$putReadsWithTheSameNameInTheSamePartition$7bd206b0$1(SparkUtils.java:190) at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153) at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$4$1.apply(JavaRDDLike.scala:153) at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:823) at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:823) at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52) at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346) at org.apache.spark.rdd.RDD.iterator(RDD.scala:310) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) at org.apache.spark.scheduler.Task.run(Task.scala:123) at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408) at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)
`

Looking at the aligned bams that go into the scoring task, they don't appear to be empty or different to the rest of the cohort. Any thoughts?

**Comment by droazen** [comment]
@mwalker174 Any insight into this one?

**Comment by lbergelson** [comment]
Odd, it seems like we're getting a partition with no elements in it somehow.  I didn't think that was possible.  We're calling "iter.next()" without a check because we made the assumption that a partition always had at least 1 read in it.  

@spromanos How are your bams sorted? By queryname?

**Comment by spromanos** [comment]
@lbergelson coordinate.

**Comment by mwalker174** [comment]
Another user has reported the same error running a PathSeq output BAM on `BwaSpark`.

**Comment by lbergelson** [comment]
This needs a fix in the spark loading code.  We need to explicitly account for empty shards when doing the shuffle of the first readname to the shard to the left it.

**Comment by tedsharpe** [comment]
I have a PR that fixes this.  It's on the branch tws_desparkify_svdiscovery, which is a big refactor on some SV code.  Someone could have a look and pull out just that bit of code to make a new, smaller PR.

**Comment by cwhelan** [comment]
I currently have it on my plate to review @tedsharpe 's PR -- I will try to prioritize that if it contains fixes that would be useful elsewhere.

**Comment by lbergelson** [comment]
I'm so happy to hear that someone else has already fixed this problem!

**Comment by droazen** [comment]
The proposed fix for this issue is under review in PR https://github.com/broadinstitute/gatk/pull/6652 -- should be part of the next GATK release.

**Comment by droazen** [comment]
Closing -- the fix for this issue was merged in https://github.com/broadinstitute/gatk/pull/6652
