### ISSUE TITLE
available resource bundle is lacking INFO fields for best practice VariantRecalibrator

### ISSUE THREAD

**Issue by MWendorff** [broadinstitute/gatk#6715]
### Affected tool(s) or class(es)
VariantRecalibrator
Resource Bundle

### Affected version(s)
Resource Bundle downloaded 21. July 2020 (ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/ OR https://console.cloud.google.com/storage/browser/genomics-public-data/resources/broad/hg38/v0;tab=objects?prefix=)

### Description 
The available dataset lack information for FS, SOR etc. but this parameter are necessary for the best practice workflow of the VariantRecalibrator and cannot be added with the VariantAnnotator as the individual information is not included.

#### Steps to reproduce
Run VariantRecalibrator with the publicly available reference files. And the recommended parameter settings.

gatk --java-options "-Xmx24g -Xms24g" VariantRecalibrator \
    -V ${inputfile} \
    --trust-all-polymorphic \
    -tranche 100.0 -tranche 99.95 -tranche 99.9 -tranche 99.5 -tranche 99.0 -tranche 97.0 -tranche 96.0 -tranche 95.0 -tranche 94.0 -tranche 93.5 -tranche 93.0 -tranche 92.0 -tranche 91.0 -tranche 90.0 \
    -an FS -an ReadPosRankSum -an MQRankSum -an QD -an SOR \
    -mode INDEL \
    --max-gaussians 4 \
    -resource:mills,known=false,training=true,truth=true,prior=12 ${gatk_ref}Mills_and_1000G_gold_standard.indels.hg38.vcf.gz \
    -resource:axiomPoly,known=false,training=true,truth=false,prior=10 ${gatk_ref}Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz \
    -resource:dbsnp,known=true,training=false,truth=false,prior=2 ${gatk_ref}/Homo_sapiens_assembly38.dbsnp138.vcf \
    -O ${fileprefix}_indels.recal \
    --tranches-file ${fileprefix}_indels.tranches

#### Expected behavior
Calculation of VQSLOD tranches

#### Actual behavior
A USER ERROR has occurred: Bad input: Values for FS annotation not detected for ANY training variant in the input callset. VariantAnnotator may be used to add these annotations.

**Comment by ldgauthier** [comment]
Note that the error message says "in the input callset", which refers to your -V ${inputfile}.  It means that for the sites in your callset that correspond with the sites in the training resources, your callset does not have any variants with FS.
