### ISSUE TITLE
4.1.8.1 gzip tar file is broken?

### ISSUE THREAD

**Issue by GuoYu-Peng** [broadinstitute/gatk#6719]
I download 4.1.8.1 release tar.gz file but can't unzip.
```
 63800K .......... .......... .......... .......... .......... 49.2K
 63850K                                                         533G=21m48s

2020-07-22 09:06:30 (48.8 KB/s) - ‘4.1.8.1.tar.gz’ saved [65382686]
```
Here is Error:
```
$tar -zxf 4.1.8.1.tar.gz 

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by droazen** [comment]
@GuoYu-Peng I am able to extract the `.tar.gz` (https://github.com/broadinstitute/gatk/archive/4.1.8.1.tar.gz) fine on my end. Make sure you got a complete download -- the file size should be 69,129,515 bytes.

Please note that the `.tar.gz` contains only the GATK source code. For a runnable GATK installation you should download the zip file instead (https://github.com/broadinstitute/gatk/releases/download/4.1.8.1/gatk-4.1.8.1.zip)

**Comment by GuoYu-Peng** [comment]
Ok, I was wrong download then.
