### ISSUE TITLE
Mutect2 missed mutation with AF of ~2.5% 

### ISSUE THREAD

**Issue by slw287r** [broadinstitute/gatk#6724]
# Bug Report

### Affected tool(s) or class(es)
_Mutect2_

### Affected version(s)
- [x] 4.1.5.0 ~ 4.1.8.1

### Description 
_Mutation with AF ~2.5% missed by Mutect2 paired-calling. It may be related to M2's active region selection module_

#### Steps to reproduce

* Default (both `--force_active` and `--alleles` are OFF) → **No call**
```
gatk Mutect2 -I cancer.bam -I normal.bam -R /opt/dat/hs37d5.fa -normal normal -O no_call.vcf.gz -L interval.bed --force-active false -verbosity ERROR
```

* With force_active ON → **Correct call**
```
gatk Mutect2 -I cancer.bam -I normal.bam -R /opt/dat/hs37d5.fa -normal normal -O force_active.vcf.gz -L interval.bed --force-active true -verbosity ERROR
```

* With `--alleles` ON (make use of the above force_active results) → **Correct call**
```
gatk Mutect2 -I cancer.bam -I normal.bam -R /opt/dat/hs37d5.fa -normal normal -O force_alleles.vcf.gz -L interval.bed --force-active false -verbosity ERROR --alleles force_active.vcf.gz
```

#### Expected behavior

```
bcftools query -s cancer -f '%CHROM\t%POS\t%REF\t%ALT\t[%AF{0}]\n' force_alleles.vcf.gz
12	25378562	C	T	0.024
12	25378660	A	G	0.014
```

#### Actual behavior
_Empty output_

#### Other information

<details><summary> IGV screen shot of the mutation <code>12:g.25378562C>T</code></summary>
<img width="1131" alt="igv" src="https://user-images.githubusercontent.com/4134899/88393449-3861cc80-cdf0-11ea-8e31-1a99b3b21ed9.png">
</details>

We used the 1000genomes Phase2 Reference Genome Sequence (hs37d5).
![ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz](ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz)

The cancer and matched normal bams (aligned to hs37d5) to reproduce the above behaviors ([data.zip](https://github.com/broadinstitute/gatk/files/4971930/data.zip)).

Thanks,
Richard

**Comment by fleharty** [comment]
@slw287r Thanks for the detailed description.  This does look like a problem we would like to resolve.

@davidbenjamin Can you take a look into this?

**Comment by davidbenjamin** [comment]
@slw287r I reproduced your issue and there is definitely something wrong with the active pileup likelihood calculation here.  I will fix it.

**Comment by slw287r** [comment]
> @slw287r I reproduced your issue and there is definitely something wrong with the active pileup likelihood calculation here. I will fix it.

Thanks a mil!

**Comment by davidbenjamin** [comment]
@slw287r I found the error and have fixed it in a branch.  I will test it on a few genomes and then submit a PR.

**Comment by slw287r** [comment]
> @slw287r I found the error and have fixed it in a branch. I will test it on a few genomes and then submit a PR.

That's cool! thanks
