### ISSUE TITLE
HaplotypeCallerSpark ReadThreadingAssembler error

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#6738]
As discussed in GATK office hours, this issue was reported by a user with HaplotypeCaller Spark. The entire stack trace is included below.

This request was created from a contribution made by stanedav on August 03, 2020 10:07 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/360072104512-HaplotypeCallerSpark-error](https://gatk.broadinstitute.org/hc/en-us/community/posts/360072104512-HaplotypeCallerSpark-error)

\--

Hello, I am testing HaplotypeCallerSpark algorithm on my local machine for speeding up the variant calling. I tried to apply algorithm on my BQSR bam but I am getting this error (full log below):

ERROR Executor: Exception in task 15.0 in stage 5.0 (TID 1324)  
  
java.util.ConcurrentModificationException ... (more in log)

Version of GATK: 4.1.7.0

Command I used:

$gatk --java-options "-Xmx48g -Xms32g" HaplotypeCallerSpark \\  
  
\-R hg19.fasta \\  
  
\-I remdup\_recal.bam \\  
  
\-O output.g.vcf \\  
  
\-L wes.bed \\  
  
\-ERC GVCF \\  
  
\--dont-use-soft-clipped-bases

Full log:

[https://www.dropbox.com/s/iez0zixclsh86zp/hc.log?dl=0](https://www.dropbox.com/s/iez0zixclsh86zp/hc.log?dl=0)<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/6546'>Zendesk ticket #6546</a>)<br>gz#6546</i>

**Comment by cmnbroad** [comment]
This looks like the same issue as https://github.com/broadinstitute/gatk/issues/6513.

**Comment by jamesemery** [comment]
@gbrandt6 I think we have a fix for the user that should hopefully go in with the next release.

**Comment by droazen** [comment]
Closing as resolved in https://github.com/broadinstitute/gatk/pull/6741
