### ISSUE TITLE
HaplotypeCaller results 

### ISSUE THREAD

**Issue by stellaoh** [broadinstitute/gatk#6752]
Hi, 

I executed HaplotypeCaller and GenomicDBimport (GATK version 4.1.4.1). 

 

First Question.

In my haplotypeCaller results (sample names = 2016000051), 

there is no variant on chr1:10363 as below.

However, when I merge all samples using GenomicDBImport & Genotyping, 

I had this result. 

How emit this result? 

 

Second question. 

In this vcf, what mean this star? 

 

Third question. 

I find the variant on chr1:10120 T>A as below. 

But, consolidate vcf dosn't have this variant. I can't understand. 

 

Fourth question. 

In my haplotype calls, they emit the genotype on chr1:10126 as below. 

But in my consolidate vcf, 

the genotype is "./.". 

And the DP (107) is also different with haplotype caller vcf (DP=122). 

 

Fifth Question, 

In my HaplotypeCaller gvcf, 

 

In my consolidate vcf, 

How can emit the genotype (2|2) on chr1:10177??

**Comment by droazen** [comment]
@stellaoh These questions are more appropriate for the GATK support forum (https://gatk.broadinstitute.org/hc/en-us/community/topics) than here. I suggest reposting these questions there. This github issue tracker is for bug reports.
