### ISSUE TITLE
OSX Catalina Software Signing Compatibility

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#6756]
Apple is going to turn on Software Signing with OSX Catalina very soon (sometime this fall or so).

While signing GATK will be fine, theoretically we have to sign all of the dynamic libraries that we leverage.

OpenJDK did a release a while ago with these security features on and it was a major fiasco.

We need to research what the signing requirements are and how they will affect the GATK release process.

**Comment by droazen** [comment]
@jonn-smith @lbergelson All of the articles I've read on this topic so far imply that it will still be possible to run completely unsigned software, that the additional requirements only apply to signed software, and that CLI tools are unaffected. Eg., 

https://eclecticlight.co/2020/02/03/hardening-and-notarization-finally-arrive-in-catalina/
https://appletoolbox.com/everything-you-need-to-know-about-app-notarization-in-macos-catalina/
