### ISSUE TITLE
 **bug report** No .vcf.stats generated using Mutect2 (GATK v4.1.8.1) 

### ISSUE THREAD

**Issue by audrysgp** [broadinstitute/gatk#6768]
### Affected tool(s) or class(es)
Mutect2

### Affected version(s)
- GATK v4.1.8.1

### Description 
Hi, 
I am new to GATK so I hope this is not something trivial I overlooked.

I called somatic variants using `Mutect2` (GATK v4.1.8.1) and wished to filter the results using `FilterMutectCalls`.  I am running GATK via a docker container as described here: https://gatk.broadinstitute.org/hc/en-us/articles/360035889991--How-to-Run-GATK-in-a-Docker-container

``` bash
./gatk Mutect2 -I:tumor 1st.chr1.bam -I:normal 2nd.chr1.bam -O variants.vcf.gz --min-pruning 8 -R reference.chr1.fa
```
I repeated this three times, the last time to make sure whether the .vcf.stats is being generated or not. This was a test run using the input filtered for chr1 using `samtools view -b`. I though this was the reason for getting the error message about Contig 2 not being present.

```bash
...
18:39:03.207 INFO  ProgressMeter -          1:282722440            448.7               1529870           3409.8
18:39:06.592 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 19.218222963000002
18:39:06.592 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 5376.604473962
18:39:06.593 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 12201.77 sec
18:39:06.594 INFO  Mutect2 - Shutting down engine
[August 25, 2020 6:39:06 PM GMT] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 448.75 minutes.
Runtime.totalMemory()=12349079552
***********************************************************************

A USER ERROR has occurred: Contig 2 not present in the sequence dictionary [1]


***********************************************************************
Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
```
Is there any way of getting around this and generating .vcf.stats without repeating a lengthy variant calling `Mutect2`? Is this a problem introduced by running the truncated input files?

Looking up online, it seems this seemed to be an issue in the previous versions of GATK:https://github.com/broadinstitute/gatk/issues/6102

Thanks!

#### Expected behavior
I would expect .vcf.stats to be automatically generated with the output

#### Actual behavior
 No .vcf.stats can be located

**Comment by droazen** [comment]
@fleharty @davidbenjamin

**Comment by davidbenjamin** [comment]
@audrysgp It looks like your `samtools view` command removes reads from chr2 but leaves the record for chr2 in the bam header.  Then, when you run using the chr1 reference fasta, the GATK sees the discrepancy in sequence dictionaries and errors.

There is no need to use `samtools view` before running GATK tools.  Just run on the original bams and use the `-L` argument to specify an interval, in this case `-L 1`.

Also, I notice that the Mutect2 command you're using is incorrect in several ways.  The tutorial on the GATK forum: https://gatk.broadinstitute.org/hc/en-us/articles/360047232772--Notebook-Intro-to-using-Mutect2-for-somatic-data shows how to run Mutect2 optimally.
