### ISSUE TITLE
Argument types should be more clearly separated from argument names in the help output

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#6775]
The way argument types are specified in the GATK help output is apparently causing confusion for some users. Currently the argument type is separated from the argument name by a colon:

```
--input:GATKPath
```

This is leading some users to think that they need to include a colon in their command line, or even the literal string "GATKPath". I suggest that we separate the type from the name using a space instead, which would better mirror what the user needs to actually type on the command line. Eg., something like:

```
--input <GATKPath>
```

Reported by @gbrandt6 and @vdauwera

**Comment by cmnbroad** [comment]
Barclay PR for the command line part is https://github.com/broadinstitute/barclay/pull/172. We still need to update the GATK html templates to change the generated doc.

**Comment by cmnbroad** [comment]
Edit: looks like the html doc doesn't use the colon.

**Comment by droazen** [comment]
A fix for this issue has been merged into Barclay, and should be part of the next GATK release.
