### ISSUE TITLE
Suppressed: java.io.IOException: No space left on device

### ISSUE THREAD

**Issue by caijingtao1993** [broadinstitute/gatk#6787]
Dear sir：
       I marked the instructions used in PCR repeat as follows:
gatk MarkDuplicates -I Sample_sorted.bam -O Sample_sorted_markdup.bam -M Sample_markdup_metrics.txt
It will show that the storage of the device is insufficient, as shown below:
![image](https://user-images.githubusercontent.com/67781404/91958406-e2127280-ed39-11ea-915d-a2eee5c51fd1.png)

What method needs to be taken to solve it, please ask. Many thanks

**Comment by jamesemery** [comment]
You can also manually set the TMP directory in MarkDuplicates with the argument `--TMP_DIR <Directory>` this will allow intermediate files that are produced by the tool to be redirected to somewhere that does have sufficient space.

**Comment by droazen** [comment]
Closing as resolved
