### ISSUE TITLE
Investigate groupbykey OOM.

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/gatk#679]
When running BQSR with incompatible references we get an "out of memory" error (see #668). This isn't what we were expecting so this issue is a reminder to investigate in case the underlying cause is a bug.

**Comment by jean-philippe-martin** [comment]
focusing on performance right now. If someone else wants to investigate they're welcome to.

**Comment by akiezun** [comment]
This issue was moved to broadinstitute/gatk-dataflow#37
