### ISSUE TITLE
AddOrReplaceReadGroups error

### ISSUE THREAD

**Issue by elbakrifz** [broadinstitute/gatk#6796]
I was running this cmd :  
I get : java -jar /Users/mac/Downloads/picard-2.jar AddOrReplaceReadGroups                                                                                   I=/Users/mac/Desktop/NGS-/SRR6369642-pe.bam                                     O=/Users/mac/Desktop/NGS-/SRR6369642-pe-RG.bam                                  RGID=C7BDWACXX.5                                                                RGLB=Lmj_A445_EP+3.2run1                                                        RGPL=Illumina                                                                   RGPU=C7BDWACXX.5                                                                RGSM=NO8162944

 record positions. Printing Read-names as well.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010d32bea7, pid=1681, tid=6403
#
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.65-b01 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libgkl_compression7875913179822684367.dylib+0x6ea7]  deflate_medium+0x867
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/mac/Desktop/NGS-/hs_err_pid1681.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6

how can I fix it

**Comment by droazen** [comment]
@elbakrifz This looks like https://github.com/Intel-HLS/GKL/issues/101, which is believed to be fixed in the upcoming release of the GKL. For now, you can tell Picard to use the Java deflater, rather than the Intel deflater, by specifying `USE_JDK_DEFLATER=true` and/or `USE_JDK_INFLATER=true`
