### ISSUE TITLE
AddOrReplaceReadGroups error

### ISSUE THREAD

**Issue by elbakrifz** [broadinstitute/gatk#6797]
I was running : java -jar /Users/mac/Downloads/picard-2.jar AddOrReplaceReadGroups                                                                            I=/Users/mac/Desktop/NGS-/SRR6369642-pe.bam                                     O=/Users/mac/Desktop/NGS-/SRR6369642-pe-RG.bam                                  RGID=C7BDWACXX.5                                                                RGLB=Lmj_A445_EP+3.2_run1                                                       RGPL=Illumina                                                                   RGPU=C7BDWACXX.5                                                                RGSM=NO8162944     

  I get :00:13:06.733 INFO  NativeLibraryLoader - Loading libgkl_compression.dylib from jar:file:/Users/mac/Downloads/picard-2.jar!/com/intel/gkl/native/libgkl_compression.dylib
[Tue Sep 08 00:13:07 WEST 2020] AddOrReplaceReadGroups INPUT=/Users/mac/Desktop/NGS-/SRR6369642-pe.bam OUTPUT=/Users/mac/Desktop/NGS-/SRR6369642-pe-RG.bam RGID=C7BDWACXX.5 RGLB=Lmj_A445_EP+3.2_run1 RGPL=Illumina RGPU=C7BDWACXX.5 RGSM=NO8162944    VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json USE_JDK_DEFLATER=false USE_JDK_INFLATER=false
[Tue Sep 08 00:13:07 WEST 2020] Executing as mac@MacBook-Air-de-mac.local on Mac OS X 10.15.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17; Deflater: Intel; Inflater: Intel; Provider GCS is not available; Picard version: 2.23.0
INFO	2020-09-08 00:13:08	AddOrReplaceReadGroups	Created read-group ID=C7BDWACXX.5 PL=Illumina LB=Lmj_A445_EP+3.2_run1 SM=NO8162944

INFO	2020-09-08 00:13:08	AddOrReplaceReadGroups	Seen many non-increasing record positions. Printing Read-names as well.
fatal error 

the first time is was sorting ana indexing when I do it again I get this error how should I fix it !!

**Comment by droazen** [comment]
You should ask about this in the Picard repository (https://github.com/broadinstitute/picard), as this is a Picard tool.
