### ISSUE TITLE
IndelRealignement error 

### ISSUE THREAD

**Issue by elbakrifz** [broadinstitute/gatk#6798]
I was running this command : java -Xmx4G -jar /Users/mac/Desktop/GenomeAnalysisTK-3.8-0-ge9d806836\ 4/GenomeAnalysisTK.jar \ -T IndelRealigner \ -R /Users/mac/Desktop/NGS-/TriTrypDB-47_LmajorLV39c5_Genome.fasta \ -I /Users/mac/Desktop/NGS-/marked_duplicates42-pe.bam \ -targetIntervals /Users/mac/Desktop/NGS-/42-pe-realigner.intervals \ -o /Users/mac/Desktop/NGS-/42-pe-idelsrealigner.bam

I get :INFO  10:47:54,213 HelpFormatter - ---------------------------------------------------------------------------------- 
INFO  10:47:54,223 HelpFormatter - The Genome Analysis Toolkit (GATK) v3.8-0-ge9d806836, Compiled 2017/07/28 21:26:50 
INFO  10:47:54,224 HelpFormatter - Copyright (c) 2010-2016 The Broad Institute 
INFO  10:47:54,224 HelpFormatter - For support and documentation go to https://software.broadinstitute.org/gatk 
INFO  10:47:54,225 HelpFormatter - [Tue Sep 08 10:47:54 WEST 2020] Executing on Mac OS X 10.15.6 x86_64 
INFO  10:47:54,225 HelpFormatter - Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17 
INFO  10:47:54,229 HelpFormatter - Program Args:  -T IndelRealigner  -R /Users/mac/Desktop/NGS-/TriTrypDB-47_LmajorLV39c5_Genome.fasta  -I /Users/mac/Desktop/NGS-/marked_duplicates42-pe.bam  -targetIntervals /Users/mac/Desktop/NGS-/42-pe-realigner.intervals  -o /Users/mac/Desktop/NGS-/42-pe-idelsrealigner.bam 
INFO  10:47:54,492 HelpFormatter - Executing as mac@MacBook-Air-de-mac.local on Mac OS X 10.15.6 x86_64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_65-b17. 
INFO  10:47:54,493 HelpFormatter - Date/Time: 2020/09/08 10:47:54 
INFO  10:47:54,494 HelpFormatter - ---------------------------------------------------------------------------------- 
INFO  10:47:54,494 HelpFormatter - ---------------------------------------------------------------------------------- 
ERROR StatusLogger Unable to create class org.apache.logging.log4j.core.impl.Log4jContextFactory specified in jar:file:/Users/mac/Desktop/GenomeAnalysisTK-3.8-0-ge9d806836%204/GenomeAnalysisTK.jar!/META-INF/log4j-provider.properties
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
INFO  10:47:55,875 GenomeAnalysisEngine - Deflater: IntelDeflater 
INFO  10:47:55,876 GenomeAnalysisEngine - Inflater: IntelInflater 
INFO  10:47:55,876 GenomeAnalysisEngine - Strictness is SILENT 
INFO  10:47:56,246 GenomeAnalysisEngine - Downsampling Settings: No downsampling 
INFO  10:47:56,255 SAMDataSource$SAMReaders - Initializing SAMRecords in serial 
INFO  10:47:56,333 SAMDataSource$SAMReaders - Done initializing BAM readers: total time 0.07 
##### ERROR ------------------------------------------------------------------------------------------
how should I fix it

**Comment by droazen** [comment]
@elbakrifz The error is telling you that the sequence dictionary for your bam file does not match the sequence dictionary for your reference -- are you using the right reference? 

Also, you are running GATK 3, which we no longer officially support. This repository is for GATK 4 issues only.
