### ISSUE TITLE
Improvements to walker engine should (ideally) auto-propagate to the Spark part of the code

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#680]
When we make enhancements to the walker engine (eg., modify the `GATKTool` base class to support CRAM, or to validate the sequence dictionaries of the inputs), it would be good if Spark tools could also reap the benefits of these changes automatically. We may need to unify (or better integrate) the `GATKTool` and `SparkCommandLineProgram` base classes somehow to make this possible, as well as classes like `ReadsDataSource` (for walkers) and `ReadsSparkSource` (for Spark tools).

**Comment by akiezun** [comment]
this applies to spark too.

**Comment by droazen** [comment]
This was a meta-ticket that has spawned other tickets such as https://github.com/broadinstitute/gatk/issues/959 representing the actual work of better unifying the walker and spark portions of the codebase -- it can now be closed in favor of those other tickets.
