### ISSUE TITLE
Typos in FragmentUtils.adjustQualsOfOverlappingPairedFragments

### ISSUE THREAD

**Issue by DonFreed** [broadinstitute/gatk#6801]
### Affected tool(s) or class(es)
org.broadinstitute.hellbender.utils.fragments.FragmentUtils

### Affected version(s)
- [x] Latest public release version 4.1.8.1
- [X] Latest master branch as of September 8th, 2020

### Description 
At, https://github.com/broadinstitute/gatk/blob/12511551a3e273a1ad767253ccba9918d6eb45b9/src/main/java/org/broadinstitute/hellbender/utils/fragments/FragmentUtils.java#L93-L96

Both insertions and deletions use `getBaseInsertionQualities`. Deletions should instead use `getBaseDeletionQualities`.

**Comment by droazen** [comment]
@davidbenjamin @fleharty This seems like a simple mistake in the code for `FragmentUtils` (we're using the insertion qualities where we should be using the deletion qualities) -- can you confirm and open a PR to fix this if you agree?

**Comment by davidbenjamin** [comment]
@droazen @DonFreed Confirmed that this is as much of a mistake as it appears.  I will open a PR.

**Comment by DonFreed** [comment]
Thanks for the quick fix!
