### ISSUE TITLE
Picard engine level arguments don't show up in the GATK help output

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#6811]
When accessing the help output for Picard tools (example MarkDuplicates) through the gatk launch script it seems that engine level Picard arguments are not showing up in the help output (example `--TMP_DIR`). The default behavior in picard itself is to hide those engine arguments from the help output behind a special help flag `--stdhelp` which adds all of those arguments back into the help output. We should reintroduce those arguments into the GATK help output for Picard tools.

**Comment by droazen** [comment]
It's also worth noting here that GATK has a `--tmp-dir` argument, while Picard has `--TMP_DIR`, and it's not clear how they interact when running Picard tools from within GATK.

**Comment by jamesemery** [comment]
@droazen As it turns out they interact poorly. If i try to run a picard tool with the argument `--tmp-dir` you get a failure for the argument being unrecognized where as if I run a GATK tool with `--TMP_DIR` it also fails.

**Comment by droazen** [comment]
This one was fixed
