### ISSUE TITLE
Deletion followed by insertion not called/geontyped correctly by HaplotypeCaller

### ISSUE THREAD

**Issue by tfenne** [broadinstitute/gatk#6817]
### Affected tool(s) or class(es)
HaplotypeCaller

### Affected version(s)
- [x] Latest public release version [4.1.8.1]
- [ ] Latest master branch as of [date of test?]

### Description 
I have a sample with a complex variant that could be modeled either as a 1bp deletion followed by a 2bp MNP, or more likely as a 3bp deletion followed by a 2bp insertion (or, if you will, the replacement of three reference bases with two other bases).

The changes are clearly visible in the following screenshot.  The top track is the aligned/deduped BAM, and the bottom track is the assembly BAM generated by HaplotypeCaller:

![missing-insertion igv-screenshot](https://user-images.githubusercontent.com/1609210/93133361-516e5780-f694-11ea-9b7d-7aa71f5623cc.png)

When I call this region to generate a gVCF I get some fairly strange output despite HC clearly reconstructing the haplotype correctly (some annotations removed for readability):

```
#CHROM  POS       ID  REF   ALT              QUAL     FILTER  INFO                                                          FORMAT              test-sample
chr13   32953865  .   T     <NON_REF>        .        .       END=32953884                                                  GT:DP:GQ:MIN_DP:PL  0/0:204:99:196:0,120,1800
chr13   32953885  .   AGTT  A,<NON_REF>      3110.60  .       DP=213;MLEAC=1,0;MLEAF=0.500,0.00                             GT:AD:DP:GQ:PL:SB   0/1:108,82,0:1
chr13   32953888  .   T     *,TAA,<NON_REF>  585.02   .       DP=205;MLEAC=0,0,2;MLEAF=NaN,NaN,1.00;RAW_MQandDP=738000,205  GT:GQ:PL            ./.:99:0,0,0,0,0,0,0,0,0,0
chr13   32953889  .   A     <NON_REF>        .        .       END=32953905                                                  GT:DP:GQ:MIN_DP:PL  0/0:211:99:205:0,120,1800
```

When this is genotyped by `GenotypeGVCFs` the only resulting variant is the 3bp deletion:

```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  test-sample
chr13   32953885        .       AGTT    A       3110.60 .       AC=1;AF=0.500;AN=2;BaseQRankSum=0.00;DP=213;ExcessHet=3.0103;FS=2.544;MLEAC=1;MLEAF=0.500;MQ=60.00;MQRankSum=0.00;QD=16.37;ReadPosRankSum=-4.360e-01;SOR=0.506  GT:AD:DP:GQ:PL  0/1:108,82:190:99:3118,0,4288
```

I've tried this with GATK 4.1.4.1, and also 4.1.7.0 and 4.1.8.1 and they all have the same issue (output above is from 4.1.8.1).  I've also tried both with and without the `--linked-de-bruijn-graph` which doesn't appear to have any effect on this issue.

#### Steps to reproduce
Run the following on the [attached BAM file](https://github.com/broadinstitute/gatk/files/5220715/missed-insertion-bam.zip) using your favorite HG19 reference:

```
gatk HaplotypeCaller \
  -I missed-insertion.bam \
  -O missed-insertion.g.vcf \
  -R hg19.fa \
  -ERC GVCF \
  -L chr13:32953865-32953905 \
  --bam-output missed-insertion.assembly.bam \
```

#### Expected behavior
I would actually have expected this to be output as a single variant in the gVCF something along the lines of:

```
chr13   32953885  .   AGTT  AAA,<NON_REF>      3110.60  .       DP=213;MLEAC=1,0;MLEAF=0.500,0.00                             GT:AD:DP:GQ:PL:SB   0/1:108,82,0:1
```

I.e. with the inserted `AA` incorporated in the first ALT allele.  Or perhaps without the leading anchor base as `GTT>AA` at position 32953886.  Given that the change is on the same haplotype I'm not sure there is a good way to represent it as two separate variants.  I suppose it could be:

```
chr13  32953885  .  AGTT  A,<NON_REF>    .  .  .  GT  0|1
chr13  32953885  .  A     AAA,<NON_REF>  .  .  .  GT  0|1
```

but that's a bit weird.

#### Actual behavior
Insertion of 2bp is missed as shown above.

**Comment by droazen** [comment]
@tfenne Can you try running with the latest master? I'm wondering if this is the same issue that was fixed recently in https://github.com/broadinstitute/gatk/pull/6696

**Comment by tfenne** [comment]
Thanks for the pointer @droazen - I missed that recent PR.  That does indeed seem to fix it.  With the latest from master I get (info removed for readability):

```
#CHROM  POS       ID  REF   ALT            QUAL     FILTER  INFO          FORMAT                        test-sample
chr13   32953865  .   T     <NON_REF>      .        .       END=32953884  GT:DP:GQ:MIN_DP:PL            0/0:204:99:196:0,120,1800
chr13   32953885  .   AGTT  A,<NON_REF>    3110.60  .       .             GT:AD:DP:GQ:PGT:PID:PL:PS:SB  0|1:108,82,0:190:99:0|1:32953885_AGTT_A:3118,0,4288,3443,4535,7978:32953885:
chr13   32953888  .   T     TAA,<NON_REF>  3110.60  .       .             GT:AD:DP:GQ:PGT:PID:PL:PS:SB  0|1:108,82,0:190:99:0|1:32953885_AGTT_A:3118,0,4288,3443,4535,7978:32953885:61,47,42,40
chr13   32953889  .   A     <NON_REF>      .        .       END=32953905  GT:DP:GQ:MIN_DP:PL            0/0:211:99:205:0,120,1800
```

It does seem a little odd that the insertion is emitted as T>TAA when the anchoring T is removed in the phased deletion, but it is being called and that's great.

**Comment by droazen** [comment]
The representation leaves something to be desired, for sure, but like you said at least it's called now. Thanks for the fix @takutosato !
