### ISSUE TITLE
Does the result of HaplotypeCaller can be affected by the the scaffold order and the lower or upper letters in the reference.fa file

### ISSUE THREAD

**Issue by woaishiye** [broadinstitute/gatk#6825]
I wanted to detect variants with HaplotypeCaller（GATK version 4.1.1.0）, i run the program twice with two reference.fa, and i got so different results. The content of this two reference.fa is same and they are in the same version of soybean (Gmax_275_v2.0.fa). The differences of this two reference.fa are as below:
1.This two reference.fa were downloaded from different databases;
2.the order of scaffold is different, one is in the number order (just like scaffold_1, scaffold_2, scaffold_ 3, scaffold_4...),and the other one is in the dictionary order(just like scaffold_1002, scaffold_1005, scaffold_101, scaffold_1010...);
3.the coding method is different, one was coded with upper and lower letters (like ATGGccatgataGGTCaatgca), and the other one was coded only with upper words (like ATGGCCATGATAGGTCAATGCA). 

I compared the coding bases of this two reference.fa, totally same, but when i run HaplotypeCaller with this two reference.fa, i got a very different result, so i am wondering, if results of HaplotypeCaller can be  affected by the the scaffold order and the lower or upper letters in the reference.fa file?

### Instructions

The github issue tracker is for bug reports, feature requests, and API documentation requests. General questions about how to use the GATK, how to interpret the output, etc. should be asked on the [official support forum](http://gatkforums.broadinstitute.org/gatk).
- Search the existing github issues to see if your issue (or something similar) has already been reported.  If the issue already exists, you may comment there to inquire about the progress.
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request** (for tool/class javadoc only -- for forum docs please post there)
- Consider if your "issue" is better addressed on the GATK forum: http://gatkforums.broadinstitute.org/gatk  Post there if you have questions about expected tool behavior, output format, unexpected results, or generally any question that does not fit into the categories above
- Use a **concise** yet **descriptive** title
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate
- Delete the other template blocks and this header.

----

### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) or class(es) involved
_Tool/class name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) or class(es) involved
_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by droazen** [comment]
@woaishiye Could you provide more detail on how the output VCFs differ when run with the two different references? Are the variant calls themselves different in some way, or are the records just in a different order?

**Comment by woaishiye** [comment]
Thank you for your reply!
I got 80681 variant sites with one reference file, and i got 80703 variant sites with another reference file, i wanted to upload the original gatk-HaplotyperCaller(4.1.1.0) generated .vcf.gz file, but failed，so, here i just attach some examples of the difference between this two vcf file.
In one vcf, i got 1189144 and 1189216 variant sites on scaffold_21, but no this two variant sites in another vcf file. Please check the pictures below.

 



Here i have another question with the results of HaplotypeCaller, why 

there are some small different informations between this two vcf files in column “Qual”， “Info” ，“FILTER”and “DB0222A” at the same variant sites，i am not whether it is a problem, please check the pictures below, and help me out with all this problems.(I delete the same part in the line. )




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "broadinstitute/gatk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 凌晨2:17
收件人:&nbsp;"broadinstitute/gatk"<gatk@noreply.github.com&gt;;
抄送:&nbsp;"过去吧"<1469902489@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [broadinstitute/gatk] Does the result of HaplotypeCaller can be affected by the the scaffold order and the lower or upper letters in the reference.fa file (#6825)





 
@woaishiye Could you provide more detail on how the output VCFs differ when run with the two different references? Are the variant calls themselves different in some way, or are the records just in a different order?

**Comment by woaishiye** [comment]
Thank you for your reply!
I got 80681 variant sites with one reference file, and i got 80703 variant sites with another reference file, i wanted to upload the original gatk-HaplotyperCaller(4.1.1.0) generated .vcf.gz file, but failed，so, here i just attach some examples of the difference between this two vcf file.
In one vcf, i got 1189144 and 1189216 variant sites on scaffold_21, but no this two variant sites in another vcf file. Please check the information below.



the first vcf variant sites:

scaffold_21&nbsp;&nbsp;&nbsp; 1189143&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; G&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp; 718.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; AC=1;AF=0.500;AN=2;BaseQRankSum=2.09;DP=83;ExcessHet=3.0103;FS=36.237;MLEAC=1;MLEAF=0.500;MQ=37.39;MQRankSum=-4.520e-01;QD=8.66;ReadPosRankSum=1.21;SOR=5.305&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PL&nbsp;&nbsp;&nbsp; 0/1:60,23:83:99:726,0,2186
scaffold_21&nbsp;&nbsp;&nbsp; 1189144&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp; A&nbsp;&nbsp;&nbsp; 191.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; AC=1;AF=0.500;AN=2;BaseQRankSum=-1.061e+00;DP=84;ExcessHet=3.0103;FS=12.278;MLEAC=1;MLEAF=0.500;MQ=37.44;MQRankSum=0.824;QD=2.28;ReadPosRankSum=-3.850e-01;SOR=3.373&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PL&nbsp;&nbsp;&nbsp; 0/1:73,11:84:99:199,0,2951
scaffold_21&nbsp;&nbsp;&nbsp; 1189160&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp; 195.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; AC=1;AF=0.500;AN=2;BaseQRankSum=4.85;DP=76;ExcessHet=3.0103;FS=12.355;MLEAC=1;MLEAF=0.500;MQ=38.12;MQRankSum=-1.191e+00;QD=2.57;ReadPosRankSum=0.323;SOR=3.091&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PL&nbsp;&nbsp;&nbsp; 0/1:66,10:76:99:203,0,2589
scaffold_21&nbsp;&nbsp;&nbsp; 1189216&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp; 46.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; AC=1;AF=0.500;AN=2;BaseQRankSum=-3.025e+00;DP=48;ExcessHet=3.0103;FS=8.028;MLEAC=1;MLEAF=0.500;MQ=46.72;MQRankSum=-1.643e+00;QD=0.97;ReadPosRankSum=-3.135e+00;SOR=2.833&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PGT:PID:PL:PS&nbsp;&nbsp;&nbsp; 0|1:42,6:48:54:0|1:1189216_T_C:54,0,1696:1189216
scaffold_21&nbsp;&nbsp;&nbsp; 1189442&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp; 275.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; AC=1;AF=0.500;AN=2;BaseQRankSum=-2.866e+00;DP=41;ExcessHet=3.0103;FS=34.194;MLEAC=1;MLEAF=0.500;MQ=46.73;MQRankSum=-2.231e+00;QD=6.72;ReadPosRankSum=-2.022e+00;SOR=5.133&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PGT:PID:PL:PS&nbsp;&nbsp;&nbsp; 0|1:29,12:41:99:0|1:1189442_T_C:283,0,1124:1189442
scaffold_21&nbsp;&nbsp;&nbsp; 1189476&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; A&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp; 424.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; AC=1;AF=0.500;AN=2;BaseQRankSum=-2.268e+00;DP=44;ExcessHet=3.0103;FS=5.084;MLEAC=1;MLEAF=0.500;MQ=51.31;MQRankSum=-1.312e+00;QD=9.65;ReadPosRankSum=-7.250e-01;SOR=1.352&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PGT:PID:PL:PS&nbsp;&nbsp;&nbsp; 0|1:32,12:44:99:0|1:1189442_T_C:432,0,1305:1189442





the second vcf variant sites:
scaffold_21&nbsp;&nbsp;&nbsp; 1189143&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; G&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp; 303.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; AC=1;AF=0.500;AN=2;BaseQRankSum=1.48;DP=69;ExcessHet=3.0103;FS=18.532;MLEAC=1;MLEAF=0.500;MQ=37.56;MQRankSum=-8.190e-01;QD=4.40;ReadPosRankSum=1.65;SOR=4.161&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PGT:PID:PL:PS&nbsp;&nbsp;&nbsp; 0|1:56,13:69:99:0|1:1189143_G_C:311,0,2150:1189143
scaffold_21&nbsp;&nbsp;&nbsp; 1189160&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp; 248.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; AC=1;AF=0.500;AN=2;BaseQRankSum=4.83;DP=66;ExcessHet=3.0103;FS=12.860;MLEAC=1;MLEAF=0.500;MQ=37.83;MQRankSum=-9.900e-01;QD=3.77;ReadPosRankSum=0.635;SOR=3.541&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PGT:PID:PL:PS&nbsp;&nbsp;&nbsp; 0|1:56,10:66:99:0|1:1189143_G_C:256,0,2136:1189143
scaffold_21&nbsp;&nbsp;&nbsp; 1189442&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp; 275.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; AC=1;AF=0.500;AN=2;BaseQRankSum=-2.866e+00;DP=41;ExcessHet=3.0103;FS=34.194;MLEAC=1;MLEAF=0.500;MQ=46.73;MQRankSum=-2.231e+00;QD=6.72;ReadPosRankSum=-2.022e+00;SOR=5.133&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PGT:PID:PL:PS&nbsp;&nbsp;&nbsp; 0|1:29,12:41:99:0|1:1189442_T_C:283,0,1124:1189442
scaffold_21&nbsp;&nbsp;&nbsp; 1189476&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; A&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp; 424.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; AC=1;AF=0.500;AN=2;BaseQRankSum=-2.268e+00;DP=44;ExcessHet=3.0103;FS=5.084;MLEAC=1;MLEAF=0.500;MQ=51.31;MQRankSum=-1.312e+00;QD=9.65;ReadPosRankSum=-7.250e-01;SOR=1.352&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PGT:PID:PL:PS&nbsp;&nbsp;&nbsp; 0|1:32,12:44:99:0|1:1189442_T_C:432,0,1305:1189442




Here i have another question with the results of HaplotypeCaller, why 

there are some small different informations between this two vcf files in column “Qual”， “Info” ，“FILTER”and “DB0222A” at the same variant sites，i am not whether it is a problem, please check the information below, and help me out with all this problems.(I delete the same part in the line.please,check QUAL and QD )
#CHROM&nbsp;&nbsp;&nbsp; POS&nbsp;&nbsp;&nbsp; ID&nbsp;&nbsp;&nbsp; REF&nbsp;&nbsp;&nbsp; ALT&nbsp;&nbsp;&nbsp; QUAL&nbsp;&nbsp;&nbsp; FILTER&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; FORMAT&nbsp;&nbsp;&nbsp; DB0222A
scaffold_21&nbsp;&nbsp;&nbsp; 614445&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; G&nbsp;&nbsp;&nbsp; A&nbsp;&nbsp;&nbsp; 654.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; QD=15.22;ReadPosRankSum=0.747;SOR=0.885&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PL&nbsp;&nbsp;&nbsp; 0/1:19,24:43:99:662,0,403

#CHROM&nbsp;&nbsp;&nbsp; POS&nbsp;&nbsp;&nbsp; ID&nbsp;&nbsp;&nbsp; REF&nbsp;&nbsp;&nbsp; ALT&nbsp;&nbsp;&nbsp; QUAL&nbsp;&nbsp;&nbsp; FILTER&nbsp;&nbsp;&nbsp; INFO&nbsp;&nbsp;&nbsp; FORMAT&nbsp;&nbsp;&nbsp; DB0222A
scaffold_21&nbsp;&nbsp;&nbsp; 614445&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; G&nbsp;&nbsp;&nbsp; A&nbsp;&nbsp;&nbsp; 655.60&nbsp;&nbsp;&nbsp; .&nbsp;&nbsp;&nbsp; QD=15.25;ReadPosRankSum=0.747;SOR=0.885&nbsp;&nbsp;&nbsp; GT:AD:DP:GQ:PL&nbsp;&nbsp;&nbsp; 0/1:19,24:43:99:663,0,403





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "broadinstitute/gatk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 凌晨2:17
收件人:&nbsp;"broadinstitute/gatk"<gatk@noreply.github.com&gt;;
抄送:&nbsp;"过去吧"<1469902489@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [broadinstitute/gatk] Does the result of HaplotypeCaller can be affected by the the scaffold order and the lower or upper letters in the reference.fa file (#6825)





 
@woaishiye Could you provide more detail on how the output VCFs differ when run with the two different references? Are the variant calls themselves different in some way, or are the records just in a different order?

**Comment by woaishiye** [comment]
Thank you for your reply!
I got 80681 variant sites with one reference file, and i got 80703 variant sites with another reference file, i wanted to upload the original gatk-HaplotyperCaller(4.1.1.0) generated .vcf.gz file, but failed，so, here i just attach some examples of the difference between this two vcf file.
In one vcf, i got 1189144 and 1189216 variant sites on scaffold_21, but no this two variant sites in another vcf file. Please check the information below.



the first vcf variant sites:

 
scaffold_21&nbsp;&nbsp;&nbsp;&nbsp; 1189143&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; G&nbsp;&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp;&nbsp; 718.60
 
scaffold_21&nbsp;&nbsp;&nbsp;&nbsp; 1189144&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp;&nbsp; A&nbsp;&nbsp;&nbsp;&nbsp; 191.60
 
scaffold_21&nbsp;&nbsp;&nbsp;&nbsp; 1189160&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp;&nbsp; 195.60
 
scaffold_21&nbsp;&nbsp;&nbsp;&nbsp; 1189216&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp;&nbsp; 46.60
 
scaffold_21&nbsp;&nbsp;&nbsp;&nbsp; 1189442&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp;&nbsp; 275.60
 
scaffold_21&nbsp;&nbsp;&nbsp;&nbsp; 1189476&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A&nbsp;&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp;&nbsp; 424.60
 

the second vcf variant sites:
 
scaffold_21&nbsp;&nbsp;&nbsp;&nbsp; 1189143&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; G&nbsp;&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp;&nbsp; 303.60
 
scaffold_21&nbsp;&nbsp;&nbsp;&nbsp; 1189160&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp;&nbsp; 248.60
 
scaffold_21&nbsp;&nbsp;&nbsp;&nbsp; 1189442&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; T&nbsp;&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp;&nbsp; 275.60
 
scaffold_21&nbsp;&nbsp;&nbsp;&nbsp; 1189476&nbsp; .&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; A&nbsp;&nbsp;&nbsp;&nbsp; C&nbsp;&nbsp;&nbsp;&nbsp; 424.60
 

Here i have another question with the results of HaplotypeCaller, why 

there are some small different informations between this two vcf files in column “Qual”， “Info” ，“FILTER”and “DB0222A” at the same variant sites，i am not whether it is a problem, please check the information below, and help me out with all this problems.(I delete the same part in the line.please,check QUAL and QD )

scaffold_21&nbsp; &nbsp; 614445&nbsp; &nbsp; .&nbsp; &nbsp; G&nbsp; &nbsp; A&nbsp; &nbsp; QUAL:654.60&nbsp; &nbsp; .&nbsp; &nbsp; QD=15.22

 scaffold_21&nbsp; &nbsp; 614445&nbsp; &nbsp; .&nbsp; &nbsp; G&nbsp; &nbsp; A&nbsp; &nbsp; QUAL:655.60&nbsp; &nbsp; .&nbsp; &nbsp; QD=15.25
 



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "broadinstitute/gatk"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月22日(星期二) 凌晨2:17
收件人:&nbsp;"broadinstitute/gatk"<gatk@noreply.github.com&gt;;
抄送:&nbsp;"过去吧"<1469902489@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [broadinstitute/gatk] Does the result of HaplotypeCaller can be affected by the the scaffold order and the lower or upper letters in the reference.fa file (#6825)



 
@woaishiye Could you provide more detail on how the output VCFs differ when run with the two different references? Are the variant calls themselves different in some way, or are the records just in a different order?

**Comment by ldgauthier** [comment]
I have two questions for you @woaishiye:

1) Can you use the .dict file that goes with your references to verify that the MD5s for your contigs are the same between the two references?  (If you don't have a .dict file for some reason, you can use CreateSequenceDictionary in Picard/GATK)

2) Which reference was used to align the reads?  Is this the same input bam in the two cases?

**Comment by woaishiye** [comment]
@ldgauthier  below are the answers for your questions:
1.yes, the MD5 values in the .dict files for every contig are the same
2.I run the alignment process twice with the same clean data set. First, i mapped the reads onto the first reference, and then, i mapped the clean reads onto the second reference, so in total, i got two bam files as the input for gatk. But the content of these two reference files are the same. the only difference between these two reference file is that reference file 1 is the soft-mask version and reference file 2 is the unmask version（as we all konw, some databases release reference files of a organism in different version, for example, soft-mask version, hard-mask version, unmask version）.

**Comment by ldgauthier** [comment]
There are still too many variables here.  Do you know that the input bams are the same?  Are you using BWA-MEM?  My theory is that it's choosing different secondary alignments in MQ0 cases, preferring bases that are capital.  If you can show that the same reads going in produce different variants with your two different references then this will be a lot easier to debug.

**Comment by ldgauthier** [comment]
@woaishiye are you able to provide the information above?

**Comment by woaishiye** [comment]
@ldgauthier  I can not make sure that the input bam files are the same, because they are too big (42.33Gb for one bam), and i can not think of good method to make a complete comparison between the two bams.   
yes, i used the BWA-MEM to map my clean reads onto the reference.

Because the differences mainly shows up in the scaffold results, which have no impact on my study, i just need the chromosome variant information. so i ignored the difference and going on my research.

Thank you very much!!!
