### ISSUE TITLE
GATK3.8  GenotypeGVCFs  MQ abnormal

### ISSUE THREAD

**Issue by Rebbeca1985** [broadinstitute/gatk#6826]
Hi
We use GATK3.8 GenotypeGVCFs to get 3k population vcf. 
we checked the frequency of MQ and found that some sites with MQ higher than 60. Is it abnormal? The MQ peak from older version 3.3 was perfectly near 60 and few were higher than 60.
[GATK3.8.Total.MQ.pdf](https://github.com/broadinstitute/gatk/files/5230820/Total.MQ.pdf)
this file shows the MQ frequency resulted from GATK3.8

[GATA3.3.MQ.pdf](https://github.com/broadinstitute/gatk/files/5230848/MQ.pdf)
this is the MQ resulte from GATK3.3.

**Comment by droazen** [comment]
@Rebbeca1985 This github repository is for issues and bug reports related to GATK 4. GATK 3.x is no longer supported, though you can try asking about this on our support forum: https://gatk.broadinstitute.org/hc/en-us/community/topics
