### ISSUE TITLE
Mitochondria WDL Requester Pays

### ISSUE THREAD

**Issue by bshifaw** [broadinstitute/gatk#6828]
## Feature request

Mitochondria Pipeline

### Description
Many of the users on Terra that work with the GATK workflows get stuck working with requester-pays data. (e.g. [forum post](https://gatk.broadinstitute.org/hc/en-us/community/posts/360067820111/comments/360011055131)). This request asks that the workflow include the requester pays option like the [pathseq](https://github.com/broadinstitute/gatk/blob/5e5747b76fa98a3b6731dbc328e292fa941f269b/scripts/pathseq/wdl/pathseq_pipeline.wdl#L83) workflow.

**Comment by meganshand** [comment]
I believe this is already implemented [here](https://github.com/broadinstitute/gatk/blob/master/scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl#L56). @bshifaw Is this argument not showing up in Terra?

**Comment by bshifaw** [comment]
Oops, your right. Ticket closed.
