### ISSUE TITLE
Mutect WDL Requester Pays

### ISSUE THREAD

**Issue by bshifaw** [broadinstitute/gatk#6830]
## Feature request

Mutect WDL Requester Pays

### Description
Many of the users on Terra that work with the GATK workflows get stuck working with requester-pays data. (e.g. [forum post](https://gatk.broadinstitute.org/hc/en-us/community/posts/360067820111/comments/360011055131)). This request asks that the workflow include the requester pays option like the [pathseq](https://github.com/broadinstitute/gatk/blob/5e5747b76fa98a3b6731dbc328e292fa941f269b/scripts/pathseq/wdl/pathseq_pipeline.wdl#L83) workflow.

**Comment by droazen** [comment]
@fleharty / @davidbenjamin  ^^^

**Comment by droazen** [comment]
Related to https://github.com/broadinstitute/gatk/issues/6831 as pointed out by @jonn-smith

**Comment by davidbenjamin** [comment]
Closed by #6879.

**Comment by jkobject** [comment]
Hi, 

It seems this was removed in a new version of the workflow.

**Comment by jkobject** [comment]
It is on Master it seems but not in a tagged commit, so hard to use reproducibly.

**Comment by droazen** [comment]
@jkobject The requester pays option appears to be present in the most recent `4.2.5.0` release of the `Mutect2` workflow:

```
https://github.com/broadinstitute/gatk/blob/4.2.5.0/scripts/mutect2_wdl/mutect2.wdl
```

**Comment by jkobject** [comment]
Oh thanks! 
I am sorry it wasn't on dockstore, I should have checked here.
Best,
