### ISSUE TITLE
Funcotator WDL Requester Pays

### ISSUE THREAD

**Issue by bshifaw** [broadinstitute/gatk#6831]
### Tool Workflow
Funcotator WDL

### Description
Many of the users on Terra that work with the GATK workflows get stuck working with requester-pays data. (e.g. [forum post](https://gatk.broadinstitute.org/hc/en-us/community/posts/360067820111/comments/360011055131)). This request asks that the workflow include the requester pays option like the [pathseq](https://github.com/broadinstitute/gatk/blob/5e5747b76fa98a3b6731dbc328e292fa941f269b/scripts/pathseq/wdl/pathseq_pipeline.wdl#L83) workflow.

**Comment by droazen** [comment]
@jonn-smith ^^^

**Comment by jonn-smith** [comment]
Interesting.  I'll check it out.

**Comment by cmnbroad** [comment]
Sounds like we should probably add a param for this to the GATK generated WDLs too (@bshifaw ?). I can do that separately.
