### ISSUE TITLE
docker pull problem: manifest unknown

### ISSUE THREAD

**Issue by TatyanaLev** [broadinstitute/gatk#6836]
I'm trying to get the container/image from spacecade7/tutorial_11682_11683/ to use the copy number alteration tutorial.
The following error comes up on both my macbook, and on a linux system.   

$ docker pull spacecade7/tutorial_11682_11683
Using default tag: latest
Error response from daemon: manifest for spacecade7/tutorial_11682_11683:latest not found: manifest unknown: manifest unknown

**Comment by droazen** [comment]
@bhanugandham @gbrandt6 Do either of you recognize the docker image referenced above? Is it referenced in one of our official tutorials?

@TatyanaLev You might try using the official GATK docker images here instead: `broadinstitute/gatk:4.1.8.1`

**Comment by gbrandt6** [comment]
It looks like we recommend this docker image in one of our tutorials [(How to part I) Sensitively detect copy ratio alterations and allelic segments](https://gatk.broadinstitute.org/hc/en-us/articles/360035531092--How-to-part-I-Sensitively-detect-copy-ratio-alterations-and-allelic-segments) but I do not recognize the user that created it.

**Comment by droazen** [comment]
@gbggrant The tutorial might need to be updated to point to a different image, then, as this image may be gone.

Closing this issue so that the discussion can move to the forum.
