### ISSUE TITLE
How is QUAL calculated?

### ISSUE THREAD

**Issue by QuanLG** [broadinstitute/gatk#6846]
hello
         I can find "Difference between QUAL and GQ annotations in germline variant calling" on GATK web,but can't find how to calculate it. 
        And I can find on **https://www.biostars.org/p/174075/**  QUAL **is related to** the amount of data available (=depth of coverage at the site) (because we are more confident when we have more observations to rely on), the quality of the mapping of the reads and alignment of the bases (because if we are not sure the bases observed really belong there, they do not contribute much to our confidence), and the quality of the base calls (because if they look like machine errors, they also do not contribute much to our confidence),so the answer is right?

**Comment by davidbenjamin** [comment]
@QuanLG Here is our documentation: https://github.com/broadinstitute/gatk/blob/master/docs/gatk_qual.pdf

**Comment by QuanLG** [comment]
Thanks

**Comment by heixiong1990** [comment]
> @QuanLG Here is our documentation: https://github.com/broadinstitute/gatk/blob/master/docs/gatk_qual.pdf

I read the "gatk_qual.pdf" file and there is a question. Does the QUAL only relate to allele depth? I didn't see any formula that takes into account MQ and BQ. Does this hide in P(reads | g) or not.

**Comment by davidbenjamin** [comment]
That's right.  QUAL is an algorithm for going from P(reads | genotype) to
P(variant allele exists | all reads in all samples).  The genotype
likelihoods, which account for BQ and to a lesser extent MQ, are computed
inside HaplotypeCaller.
