### ISSUE TITLE
VariantEval with dbSNP to work with full dbSNP

### ISSUE THREAD

**Issue by uros-sipetic** [broadinstitute/gatk#6855]
### Tool(s) or class(es) involved
_GATK VariantEval_

### Description
Currently, if I provide a VCF to VariantEval together with a dbSNP file, but the input VCF does not variants on all chromosomes or contigs from the dbSNP, the tool will fail. 
The current solution is to always check the input VCF for all chromosomes/contigs where mutations exist, and then filter the dbSNP file to keep only the entries with those some chromosomes. 
Would it be possible to allow for the use of a full dbSNP file with GATK VariantEval, regardless of whether the input VCF has variants on all chromosomes that exist in the dbSNP or not?

More info on a forum post as well: 
https://gatk.broadinstitute.org/hc/en-us/community/posts/360072397571-VariatEval-ERROR-

**Comment by uros-sb** [comment]
Also, it seems that if the input VCF and the dbSNP are not sorted in the same way, for example:
Input VCF
>chr22
>chrX
>chrY
>chrM

dbSNP
>chr22
>chrM
>chrX
>chrY

again, the comparison analysis will fail with the error
> java.lang.IllegalStateException: The elements of the input Iterators are not sorted according to the comparator htsjdk.variant.variantcontext.VariantContextComparator

where the workaround is again to sort both the Input VCF and the dbSNP according to a specific dict, in order to make sure they are matching (if, for example, you don't how the input VCF and dbSNP were handled upstream), thus leading to always have to perform sorting before VariantEval, which can be 'expensive' if using the recent dbSNP databses (which are around 80GB)

**Comment by uros-sipetic** [comment]
Also, it seems that if the input VCF and the dbSNP are not sorted in the same way, for example:
Input VCF
>chr22
>chrX
>chrY
>chrM

dbSNP
>chr22
>chrM
>chrX
>chrY

again, the comparison analysis will fail with the error
> java.lang.IllegalStateException: The elements of the input Iterators are not sorted according to the comparator htsjdk.variant.variantcontext.VariantContextComparator

where the workaround is again to sort both the Input VCF and the dbSNP according to a specific dict, in order to make sure they are matching (if, for example, you don't how the input VCF and dbSNP were handled upstream), thus leading to always have to perform sorting before VariantEval, which can be 'expensive' if using the recent dbSNP databses (which are around 80GB)

(Reposting this, originally posted from a wrong account)

**Comment by uros-sipetic** [comment]
OK I did some more testing, turns out I was wrong (the forum post was also misleading). 
The problems in the comparison here are not between the Input VCF and the dbSNP, but between the dbSNP and the Reference FASTA file. 

I.e. I was using the dbSNP file where the order of chromosomes was like this
`1,2,3...` (downloaded from BROAD)
But the Reference FASTA had the order of chromosomes like this
`1,10,11...` (downloaded from ENSEMBL)

So yeah... if there's an option for the comparator not to look at the order of chromosomes, cool, and if not, then sorting the dbSNP according to the Reference FASTA is the way to go

**Comment by droazen** [comment]
@uros-sipetic The comparator depends on the ordering of the chromosomes imposed by the sequence dictionary in the header, so unfortunately this is not a check that can be relaxed.
