### ISSUE TITLE
INFO: Failed to detect whether we are running on Google Compute Engine: gatk4 4.1.8.1

### ISSUE THREAD

**Issue by Siadjeu** [broadinstitute/gatk#6875]
I am trying to run  gatk4 4.1.8.1 and I went through this problem:

Oct 08, 2020 6:35:26 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
18:35:26.515 INFO  MarkDuplicatesSpark - ------------------------------------------------------------
18:35:26.515 INFO  MarkDuplicatesSpark - The Genome Analysis Toolkit (GATK) v4.1.8.1
18:35:26.515 INFO  MarkDuplicatesSpark - For support and documentation go to https://software.broadinstitute.org/gatk/
18:35:26.515 INFO  MarkDuplicatesSpark - Executing as wup@mpcb006 on Linux v3.10.0-514.el7.x86_64 amd64
18:35:26.515 INFO  MarkDuplicatesSpark - Java runtime: OpenJDK 64-Bit Server VM v11.0.2+9
18:35:26.516 INFO  MarkDuplicatesSpark - Start Date/Time: October 8, 2020 at 6:35:26 PM CEST
18:35:26.516 INFO  MarkDuplicatesSpark - ------------------------------------------------------------
18:35:26.516 INFO  MarkDuplicatesSpark - ------------------------------------------------------------
18:35:26.516 INFO  MarkDuplicatesSpark - HTSJDK Version: 2.23.0
18:35:26.516 INFO  MarkDuplicatesSpark - Picard Version: 2.22.8
18:35:26.516 INFO  MarkDuplicatesSpark - HTSJDK Defaults.COMPRESSION_LEVEL : 2
18:35:26.517 INFO  MarkDuplicatesSpark - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
18:35:26.517 INFO  MarkDuplicatesSpark - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
18:35:26.517 INFO  MarkDuplicatesSpark - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
18:35:26.517 INFO  MarkDuplicatesSpark - Deflater: IntelDeflater
18:35:26.517 INFO  MarkDuplicatesSpark - Inflater: IntelInflater
18:35:26.517 INFO  MarkDuplicatesSpark - GCS max retries/reopens: 20
18:35:26.517 INFO  MarkDuplicatesSpark - Requester pays: disabled
18:35:26.517 INFO  MarkDuplicatesSpark - Initializing engine
18:35:26.517 INFO  MarkDuplicatesSpark - Done initializing engine
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/user/wup/miniconda3/envs/gatk/share/gatk4-4.1.8.1-0/gatk-package-4.1.8.1-local.jar) to method java.nio.Bits.unaligned()
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/10/08 18:35:27 INFO SparkContext: Running Spark version 2.4.5
18:35:27.640 WARN  NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
20/10/08 18:35:27 INFO SparkContext: Submitted application: MarkDuplicatesSpark
20/10/08 18:35:27 INFO SecurityManager: Changing view acls to: wup
20/10/08 18:35:27 INFO SecurityManager: Changing modify acls to: wup
20/10/08 18:35:27 INFO SecurityManager: Changing view acls groups to: 
20/10/08 18:35:27 INFO SecurityManager: Changing modify acls groups to: 
20/10/08 18:35:27 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(wup); groups with view permissions: Set(); users  with modify permissions: Set(wup); groups with modify permissions: Set()
20/10/08 18:35:28 INFO Utils: Successfully started service 'sparkDriver' on port 44712.
20/10/08 18:35:28 INFO SparkEnv: Registering MapOutputTracker
20/10/08 18:35:28 INFO SparkEnv: Registering BlockManagerMaster
20/10/08 18:35:28 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/10/08 18:35:28 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/10/08 18:35:28 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-50a111b1-9241-4bc8-b711-cdb6d7054e70
20/10/08 18:35:28 INFO MemoryStore: MemoryStore started with capacity 17.8 GB
20/10/08 18:35:28 INFO SparkEnv: Registering OutputCommitCoordinator
20/10/08 18:35:28 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/10/08 18:35:28 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://mpcb006.cm.cluster:4040
20/10/08 18:35:29 INFO Executor: Starting executor ID driver on host localhost
20/10/08 18:35:29 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46741.
20/10/08 18:35:29 INFO NettyBlockTransferService: Server created on mpcb006.cm.cluster:46741
20/10/08 18:35:29 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/10/08 18:35:29 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, mpcb006.cm.cluster, 46741, None)
20/10/08 18:35:29 INFO BlockManagerMasterEndpoint: Registering block manager mpcb006.cm.cluster:46741 with 17.8 GB RAM, BlockManagerId(driver, mpcb006.cm.cluster, 46741, None)
20/10/08 18:35:29 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, mpcb006.cm.cluster, 46741, None)
20/10/08 18:35:29 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, mpcb006.cm.cluster, 46741, None)
18:35:29.255 INFO  MarkDuplicatesSpark - Spark verbosity set to INFO (see --spark-verbosity argument)
20/10/08 18:35:29 INFO GoogleHadoopFileSystemBase: GHFS version: 1.6.3-hadoop2
WARNING	2020-10-08 18:35:29	SamReaderFactory	Unable to detect file format from input URL or stream, assuming SAM format.
WARNING	2020-10-08 18:35:29	SamReaderFactory	Unable to detect file format from input URL or stream, assuming SAM format.
20/10/08 18:35:29 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 231.0 KB, free 17.8 GB)
20/10/08 18:35:30 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 15.5 KB, free 17.8 GB)
20/10/08 18:35:30 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on mpcb006.cm.cluster:46741 (size: 15.5 KB, free: 17.8 GB)
20/10/08 18:35:30 INFO SparkContext: Created broadcast 0 from broadcast at SamSource.java:78
20/10/08 18:35:30 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 148.8 KB, free 17.8 GB)
20/10/08 18:35:30 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 25.4 KB, free 17.8 GB)
20/10/08 18:35:30 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on mpcb006.cm.cluster:46741 (size: 25.4 KB, free: 17.8 GB)
20/10/08 18:35:30 INFO SparkContext: Created broadcast 1 from newAPIHadoopFile at SamSource.java:108
20/10/08 18:35:30 INFO BlockManagerInfo: Removed broadcast_1_piece0 on mpcb006.cm.cluster:46741 in memory (size: 25.4 KB, free: 17.8 GB)
20/10/08 18:35:30 INFO BlockManagerInfo: Removed broadcast_0_piece0 on mpcb006.cm.cluster:46741 in memory (size: 15.5 KB, free: 17.8 GB)
WARNING	2020-10-08 18:35:30	SamReaderFactory	Unable to detect file format from input URL or stream, assuming SAM format.
WARNING	2020-10-08 18:35:30	SamReaderFactory	Unable to detect file format from input URL or stream, assuming SAM format.
20/10/08 18:35:30 INFO MemoryStore: Block broadcast_2 stored as values in memory (estimated size 231.0 KB, free 17.8 GB)
20/10/08 18:35:30 INFO MemoryStore: Block broadcast_2_piece0 stored as bytes in memory (estimated size 15.5 KB, free 17.8 GB)
20/10/08 18:35:30 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory on mpcb006.cm.cluster:46741 (size: 15.5 KB, free: 17.8 GB)
20/10/08 18:35:30 INFO SparkContext: Created broadcast 2 from broadcast at SamSource.java:78
20/10/08 18:35:30 INFO MemoryStore: Block broadcast_3 stored as values in memory (estimated size 148.8 KB, free 17.8 GB)
20/10/08 18:35:30 INFO MemoryStore: Block broadcast_3_piece0 stored as bytes in memory (estimated size 25.4 KB, free 17.8 GB)
20/10/08 18:35:30 INFO BlockManagerInfo: Added broadcast_3_piece0 in memory on mpcb006.cm.cluster:46741 (size: 25.4 KB, free: 17.8 GB)
20/10/08 18:35:30 INFO SparkContext: Created broadcast 3 from newAPIHadoopFile at SamSource.java:108
18:35:30.930 INFO  FileInputFormat - Total input files to process : 1
20/10/08 18:35:30 INFO SparkUI: Stopped Spark web UI at http://mpcb006.cm.cluster:4040
20/10/08 18:35:30 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/10/08 18:35:30 INFO MemoryStore: MemoryStore cleared
20/10/08 18:35:30 INFO BlockManager: BlockManager stopped
20/10/08 18:35:30 INFO BlockManagerMaster: BlockManagerMaster stopped
20/10/08 18:35:30 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/10/08 18:35:30 INFO SparkContext: Successfully stopped SparkContext
18:35:30.994 INFO  MarkDuplicatesSpark - Shutting down engine
[October 8, 2020 at 6:35:30 PM CEST] org.broadinstitute.hellbender.tools.spark.transforms.markduplicates.MarkDuplicatesSpark done. Elapsed time: 0.08 minutes.
Runtime.totalMemory()=2579496960

### Instructions

The github issue tracker is for bug reports, feature requests, and API documentation requests. General questions about how to use the GATK, how to interpret the output, etc. should be asked on the [official support forum](http://gatkforums.broadinstitute.org/gatk).
- Search the existing github issues to see if your issue (or something similar) has already been reported.  If the issue already exists, you may comment there to inquire about the progress.
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request** (for tool/class javadoc only -- for forum docs please post there)
- Consider if your "issue" is better addressed on the GATK forum: http://gatkforums.broadinstitute.org/gatk  Post there if you have questions about expected tool behavior, output format, unexpected results, or generally any question that does not fit into the categories above
- Use a **concise** yet **descriptive** title
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate
- Delete the other template blocks and this header.

----
Thanks in advance!
### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) or class(es) involved
_Tool/class name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) or class(es) involved
_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by droazen** [comment]
@Siadjeu It looks like you're running with Java 11, which is unsupported. Please try re-running with Java 8.

**Comment by Siadjeu** [comment]
@droazen ok thanks I will try to run it with java 8.

**Comment by Siadjeu** [comment]
@droazen I ran gatk4 with Java 8 and I am still encounter the same issue!

**Comment by Siadjeu** [comment]
@droazen here are the error messages with gatk4.1.8.1 and gatk4.1.4.1:

15:01:44.424 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/cm/shared/unil/software/8.3/GATK/4.1.4.1-GCCcore-8.3.0-Java-8/gatk-package-4.1.4.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Oct 09, 2020 3:01:45 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.


14:28:22.786 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/cm/shared/unil/software/8.3/GATK/4.1.8.1-GCCcore-8.3.0-Java-8/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Oct 09, 2020 2:28:23 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.

**Comment by droazen** [comment]
@Siadjeu Could you try running the latest 4.1.9.0 release and reporting whether you get the same error? We updated a number of our dependencies for that release, including the Google cloud NIO library that the error is coming from.

**Comment by droazen** [comment]
Also, can you tell us whether the tool runs to completion and produces an output file, despite the message about Google Compute Engine?

**Comment by Siadjeu** [comment]
@droazen, yes despite the message about Google gatk4 runs well and I got an output file. Thanks for your support!

**Comment by Siadjeu** [comment]
@droazen I ran the latest version but the message about google is still there!

14:08:05.607 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/cm/shared/unil/software/8.3/GATK/4.1
.9.0-GCCcore-8.3.0-Java-8/gatk-package-4.1.9.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Oct 14, 2020 2:08:06 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.

**Comment by lbergelson** [comment]
@Siadjeu Don't worry about the "Failed to detect" message.  It indicates some internal state in one of the google libraries but not an error we need to worry about.  Generally you shouldn't worry about INFO messages if everything else is going fine and they don't say something particular about what you're doing.  A WARNING or ERROR message would indicate a problem.  This should maybe be downgraded to be a DEBUG level message or something but it's in a third library and convincing them to change it might be a hassle.

**Comment by Siadjeu** [comment]
@lbergelson thanks for your comment and that is what I thought!

**Comment by 2624178329** [comment]
I meet a same error, but the result is still exist.

**Comment by xue-222** [comment]
> @Siadjeu Don't worry about the "Failed to detect" message. It indicates some internal state in one of the google libraries but not an error we need to worry about. Generally you shouldn't worry about INFO messages if everything else is going fine and they don't say something particular about what you're doing. A WARNING or ERROR message would indicate a problem. This should maybe be downgraded to be a DEBUG level message or something but it's in a third library and convincing them to change it might be a hassle.

Although there are results, but the size of the results is wrong, the results are too small.
