### ISSUE TITLE
Transform java-stream parallelism into spark parallelism after PR #6634 has been merged

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#6876]
### Affected tool(s) or class(es)
_EstimateDragstrParameters_

### Affected version(s)
- [ ] Latest public release version [version?]
- [X] Latest master branch as of [after PR 6634 has been merged in]

### Description 

Look for usages of ```Utils.runInParallel```. Change those to use Spark instead.

There is a possibility of removing multi-threading all together if we change the way we decimate and filter sites.

**Comment by ldgauthier** [comment]
Parallelism is ultra-low priority
