### ISSUE TITLE
Extract feature and feature codec from DragstrLocus and DragstrLocusUtils classes after #6634 PR has been merged.

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#6877]
### Tool(s) or class(es) involved
_ComposeSTRTableFile_, _EstimateDragstrLocus_

### Description
Seems that we should be able to do this and so reuse the same FeatureCodec framework for this kind of feature.:

**Comment by ldgauthier** [comment]
Refactoring won't happen
