### ISSUE TITLE
finalizeRegion modifies read base qualities in place

### ISSUE THREAD

**Issue by DonFreed** [broadinstitute/gatk#6882]
### Affected class
AssemblyBasedCallerUtils

### Affected version(s)
- [x] Latest public release version 4.1.9.0
- [x] Latest master branch as of 10/10/2020

### Description 
When adjusting the base quality of overlapping read pairs, the modifications are made in place. If the modified reads are later used in another active region, the results from the later active region will be changed by the earlier modification.

We had previously fixed this issue in #4926. But it looks like the refactoring in https://github.com/broadinstitute/gatk/commit/1353e3201bb11e29039efd89359b0a4cfc11e5c0 reverted to the earlier behavior.

`AssemblyBasedCallerUtilsUnitTest.testfinalizeRegion()` will fail due to this behavior if [line 67](https://github.com/broadinstitute/gatk/blob/master/src/test/java/org/broadinstitute/hellbender/tools/walkers/haplotypecaller/AssemblyBasedCallerUtilsUnitTest.java#L67) is changed from:
```
        AssemblyBasedCallerUtils.finalizeRegion(activeRegion, false, false, minbq, header, sampleList, false);
```
to:
```
        AssemblyBasedCallerUtils.finalizeRegion(activeRegion, false, false, minbq, header, sampleList, true);
```

**Comment by droazen** [comment]
@davidbenjamin It seems like your PR https://github.com/broadinstitute/gatk/pull/6358 may have had the side effect of reverting the fix in https://github.com/broadinstitute/gatk/pull/4926 -- mind having a look when you get a chance?
