### ISSUE TITLE
GenomicsDB: workspace with 1117 WGS samples = ~5m files?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6895]
We created a GenomicsDB workspace with 1117 WGS datasets. It was creating with batchSize=50, and created using 3 iterations of GenomicsDBImport (i.e. created it with some samples, and then did two rounds of appending samples to it).  There are 2473 contigs, since we are using the macaque MMul10 genome with unplaced contigs. It has 4,825,622 files and is ~7.4TB. I dont normally pay attention to file #; however, this because relevant since we ran into our lustre user limits. Is this within the range you expect?

**Comment by nalinigans** [comment]
@bbimber, just a back of envelope calculation for the number of files in a GenomicsDB workspace would be
`(num_samples/batch_size)*(num_genomic_fields*2)*num_contigs*num_iterations` for the number of files you end up with.  For your case, assuming 20 genomic info fields, it would approximately be `(1117/50)*(20*2)*2473*3=6.5M` files which seems to be in the ballpark of what you are seeing.

If you invoke GenomicsDBImport with the `consolidate` option, that would bring down the number of files by a factor of `(num_samples/batch_size)*num_iterations`, which in you case will be `(1117/50)*3=66`.

@droazen, GenomicsDB does have C/C++ based tools that do only consolidation, maybe we should offer a `gatk GenomicsDBImport --consolidate-only ...` option for existing workspaces. @mlathara, any other suggestions?

**Comment by bbimber** [comment]
Thanks for the replies. Are these C/C++ tools something one could run today on a genomics db workspace, even if there isnt a formal java wrapper?

**Comment by droazen** [comment]
@nalinigans I do think a `--consolidate-only` option for `GenomicsDBImport` would be valuable!

**Comment by bbimber** [comment]
Thanks for all your help here.
