### ISSUE TITLE
GenotypeGVCFs stuck with high CPU usage

### ISSUE THREAD

**Issue by OgnjenMilicevic** [broadinstitute/gatk#6896]
I am using a parallelized version of GenomicDBImport + GenotypeGVCFs per chormosome on 110 g.vcf samples. Most executions passed without a problem with a low CPU usage an varying time (as expected), but I just noticed that chr20 GenotypeGVCFs execution is not writing anything to stderr for 24hours+, and CPU rate is 70+ cores with only 5-6GB RAM usage.

I am using cromwell to run it, and all the other scatter branches went seamlessly. There is nothing of note in this particular stderr output, all the branches just warn occasionally that they need 10 samples for inbreeding coeficient.

Any recommendations on debugging it or fixing it?

**Comment by OgnjenMilicevic** [comment]
Last few entries:
17:59:25.486 WARN  InbreedingCoeff - Annotation will not be calculated, must provide at least 10 samples
17:59:25.486 WARN  InbreedingCoeff - Annotation will not be calculated, must provide at least 10 samples
17:59:25.489 WARN  InbreedingCoeff - Annotation will not be calculated, must provide at least 10 samples
Chromosome chr20 position 31052261 (TileDB column 2744081164) has too many alleles in the combined VCF record : 68 : current limit : 50. Fields, such as  PL, with length equal to the number of genotypes will NOT be added for this location.
17:59:26.568 WARN  MinimalGenotypingEngine - Attempting to genotype more than 50 alleles. Site will be skipped at location chr20:31052261
17:59:29.626 INFO  ProgressMeter -       chr20:31054467            129.8              28293000         217891.4
17:59:39.747 INFO  ProgressMeter -       chr20:31060641            130.0              28299000         217654.9

**Comment by ldgauthier** [comment]
Hi @OgnjenMilicevic ,

Is this the latest GATK version?  Highly multi-allelic sites are known to cause a slowdown in GenotypeGVCFs, but this was dramatically improved with the `-newQual` option, made default in 4.1.5.0.  110 whole genomes should be manageable, but excluding the low complexity regions could avoid some of the highly multi-allelic variants.

**Comment by OgnjenMilicevic** [comment]
I forked GATK pipelines, and they use docker GATK 4.0.10.1.

I will try adding newqual and report, but I assume it will fix it :)

**Comment by OgnjenMilicevic** [comment]
Am I doing something wrong?
I am trying:
java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx5g -jar /gatk/gatk-package-4.0.10.1-local.jar GenotypeGVCFs -R /cromwell-executions/WV1/0996bf87-1056-4bbc-b440-f7be97075b54/call-G1/shard-19/inputs/-701641790/Homo_sapiens_assembly38.fasta -V gendb:///cromwell-executions/WV1/0996bf87-1056-4bbc-b440-f7be97075b54/call-G1/shard-19/inputs/-700162289/db_chr20 -newQual -O gvcf_list.txt.chr20.vcf.gz

It says that -n option is not available. If I try double dash, it says: A USER ERROR has occurred: newQual is not a recognized option.

**Comment by ldgauthier** [comment]
Sorry about that.  The arg is either `-new-qual` or `--use-new-qual-calculator`

**Comment by OgnjenMilicevic** [comment]
Thanks, it truly solved it :)

Cheers!
