### ISSUE TITLE
How can we avoid lying about contig lengths when dealing with an artificially short reference?

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#690]
came up in review of #614. 
Because of sequence dict validation we needed to hardwire bogus contig lengths in the tests. This issue is about how to resolve this - keep validation and not having to lie about the lengths (and ideally not having to commit the whole reference into the repository).

**Comment by droazen** [comment]
This is solved, since we now have the ability to disable sequence dictionary validation at the engine level!
