### ISSUE TITLE
Debug GenomicsDB / GenotypeGVCFs crash?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6910]
Hello,

I am running GenotypeGVCFs using a GenomicsDB workspace with ~1200 WGS samples as input. We're running these jobs scattered on a slurm/lustre cluster, with each job given intervals. ~197/200 jobs finished, but several gave an odd error. I'm probably not giving you enough information to debug, but maybe this is enough to ask questions. the command is below:

```

java8 -Xmx48g -Xms48g -Xss2m \
-jar GenomeAnalysisTK4.jar GenotypeGVCFs \
-R REF.fasta \
--variant gendb://<genomicsdb_path> \
-O OUTPUT.vcf.gz \
--annotate-with-num-discovered-alleles \
-stand-call-conf 30 --max-alternate-alleles 12 \
-L <Repeated ~40 times for small contigs>

```
 
The error is the following:

```

21:58:51.873   WARN  MinimalGenotypingEngine -   Attempting to genotype more than 50 alleles. Site will be skipped at location   QNVO02001146.1:1343
--
21:59:01.308 INFO  ProgressMeter -  QNVO02001146.1:1679            425.0               1264000           2974.3
GENOMICSDB_TIMER,GenomicsDB iterator   next() timer,Wall-clock time(s),6.825391631999999,Cpu   time(s),6.825079531999995
#
# A fatal error has been detected by the   Java Runtime Environment:
#
#    SIGSEGV (0xb) at pc=0x00007fcca9a2ea19, pid=36873, tid=140574431450880
#
# JRE version: Java(TM) SE Runtime   Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server   VM (25.60-b23 mixed mode linux-amd64 )
# Problematic frame:
# C    [libtiledbgenomicsdb3086049122144672414.so+0x3e3a19]  ArraySchema::tile_num(void const*)   const+0x79
#
# Core dump written. Default location:   /home/groups/MgapGenomicsDb/@files/sequenceOutputPipeline/SequenceOutput_2020-10-06_16-46-33/Job734/core   or core.36873
#
# An error report file with more   information is saved as:
#   /home/groups/MgapGenomicsDb/@files/sequenceOutputPipeline/SequenceOutput_2020-10-06_16-46-33/Job734/hs_err_pid36873.log
#
# If you would like to submit a bug   report, please visit:
#     http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java   Virtual Machine in native code.
# See problematic frame for where to   report the bug.
#

```

Do you have an debugging suggestions based on this?  Thanks in advance.

**Comment by droazen** [comment]
@nalinigans Mind having a look at this one when you get a chance? Looks like a segfault in GenomicsDB?

**Comment by nalinigans** [comment]
This was a defect in one of the dependencies fixed in the later versions of GenomicsDB. Let me publish a jar with the new version and issue a PR. Thanks @bbimber.

**Comment by nalinigans** [comment]
@bbimber, can you please attach the core dump file if possible? Thanks.

**Comment by droazen** [comment]
Also, could you please post the version of GATK you're running @bbimber ?

**Comment by bbimber** [comment]
v4.1.8.0

**Comment by nalinigans** [comment]
One thing, v4.1.8.0 is backward compatible with all the workspaces generated by versions <4.1.8.0, not the other way around. For example, v4.1.7.0 cannot read a GenomicsDB workspace created by v4.1.8.0, but 4.1.8.0 can read a 4.1.7.0 workspace. So some questions -
1. Are the failures in the same set of nodes?
2.  Have all the "nodes" in the cluster been updated to running gatk v4.1.8.0.
3. Is it possible to attach a file named `__array_schema.tdb` from one of the arrays causing the segfault?

**Comment by bbimber** [comment]
See below:

1) Are the failures in the same set of nodes?

This job was split into 200 intervals and would have run across a lot of different nodes. One specific interval set is causing issues. That interval/job has failed 3 times, on different nodes with a similar error.

2) Have all the "nodes" in the cluster been updated to running gatk v4.1.8.0.

they all use the exact same JAR when they execute, which is 4.1.8.0. 

3) Is it possible to attach a file named __array_schema.tdb from one of the arrays causing the segfault?

I renamed it '.txt' to keep github happen, but here is that file.
[__array_schema.tdb.txt](https://github.com/broadinstitute/gatk/files/5441668/__array_schema.tdb.txt)

**Comment by nalinigans** [comment]
The array schema is fine. What is puzzling is this line `# Problematic frame:
# C    [libtiledbgenomicsdb3086049122144672414.so+0x3e3a19]  ArraySchema::tile_num(void const*)   const+0x79
` in the error. This particular function is not invoked for sparse arrays and the array schema has this array correctly marked sparse. Would it be possible to include the full core dump, for instance /home/groups/MgapGenomicsDb/@files/sequenceOutputPipeline/SequenceOutput_2020-10-06_16-46-33/Job734/hs_err_pid36873.log? 

Can you also try invoking GenomicsDBImport just for this problematic interval in a separate workspace and run SelectVariants/GenotypeGVFs to verify that the error produces?

**Comment by bbimber** [comment]
@nalinigans good ideas - we'll try those. core dumps from the last several failures are attached.
[errors.zip](https://github.com/broadinstitute/gatk/files/5446127/errors.zip)

**Comment by bbimber** [comment]
@nalinigans we were able to narrow this down to one contig, and it repros using SelectVariants on the workspace. do you want us to send that workspace to you?

**Comment by bbimber** [comment]
In the interest of time, here's a link to download a TAR.  it's 101GB, containing the single-contig workspace, two core dumps, and a sample command. 

https://prime-seq.ohsu.edu/_webdav/Labs/Bimber/Collaborations/Public/%40files/genomicsDB.tar.gz

Please let me know when/if you get this so I can remove it.

**Comment by nalinigans** [comment]
Thanks @bbimber, I have the file downloaded, please go ahead and remove it.

I have reproduced the seg fault - it is because of one faulty fragment - WGS_Sept_1117.gdb/QNVO02001147.1$1$28016/__58eb4600-9c95-425e-a585-4bb23b486577140340709598976_1596797671601. Not sure why, but it seems to be missing a number of files(e.g. `__coords.tdb`)  causing the fault. Things work fine if you move the fragment out of the array. 

For what its worth, all the samples from the callset.json seem to be represented in the rest of the fragments. So you might be fine with downstream processing with `__58eb4600-9c95-425e-a585-4bb23b486577140340709598976_1596797671601` removed for now. 

For our debugging, 

1. Was the GenomicsDBImport run in an update mode at all after an initial import?
2. Do you have any logs from `gatk GenomicsDBImport` for the `QNVO02001147.1$1$28016` array? 
3. Was anything reported in the Lustre logs?
4. I have attached the samples found in the callset.json for the `QNVO02001147.1$1$28016` array, can you confirm these were the expected samples? Are there any missing?

**Comment by bbimber** [comment]
Thanks. To those questions:

1) Yes, we updated after import. FWIW, when we do this, we always copy the original workspace to a working location and execute the update on this copy.

2) I'm sure we would. Is there something specific we should look for?

3) We dont generally have this level of detail on it would be pretty difficult to get that unless I'm asking for something fairly specific from the cluster admins.

4) regarding your samples.txt file: this appears to be the number 0-1116?  We do expect 1117 total samples. I'm not sure if you were expecting this to have the proper samples names, but the total count is what I expect.

**Comment by nalinigans** [comment]
Ah sorry, I just gave you the row_idx that the samples mapped to from the callset.json. Here is the sample_names file - 
[sample_map.txt](https://github.com/broadinstitute/gatk/files/5461169/sample_map.txt)

For (2), I would grep for any `WARN` from GenomicsDBImport.

**Comment by mlathara** [comment]
@bbimber for each import, do you remember how many samples were used and what the batch size was?

**Comment by bbimber** [comment]
@kray02 can you comment on the batchSize and number of iterations

@mlathara In general, if an append job fails, our code deletes the working copy of the workspace, re-copies the original and starts over. 

@nalinigans I will look for WARN. all the other intervals finished with GenotypeGVCFs, so this appears to be the only bad one.

**Comment by kray02** [comment]
@mlathara  I don't have the exact logs for earlier imports, approximately:

first import was 100 samples, unknown batch size
+ 250 samples, batch size 50
+ 200 samples, batch size 50
+ 461 samples, batch size 30
+ 101 samples, batch size 21

**Comment by mlathara** [comment]
So - the reason I asked for batch size and number of samples was to figure out the number of "fragments" within the contig folder (each fragment is associated with a folder starting with "__" and then a long uuid type string). Each batch is associated with a fragment, so number of fragments should be:

unknown + 250/50 + 200/50 + ceiling(461/30) + ceiling(101/21) = unknown + 30

Where unknown is the number of fragments for the first import. The total number of fragments in the contig folder was 49. So unless the batch size for the first import was 6, there would seem to be a few extraneous fragments in the contig folder. All of which leads me to wonder if there is some corner case being missed by the code that deals with append job failures. That could be one reason why the number of fragments is higher than expected (and some fragments are incomplete). 

One last thing that might help a bit is if you could share the timestamps for the folders immediately under the contig folder. Tarballs don't preserve those timestamps, but looking at those timestamps could help us figure out which fragments belong to which batches.

**Comment by mlathara** [comment]
The following list of fragments seem to be duplicated - i.e., for the two fragments listed on the same line, all the files from one fragment had the same md5sum as the corresponding file in the other fragment.

```
__d4333dff-c717-4484-9219-65a4896445c3140227366921984_1597305400099 __f609cfcb-7dcd-4a50-ac57-0408f6cc0953140340709598976_1596781578784
__5159f19c-84d7-49e7-9f32-aabeb983a853140340709598976_1596887157996 __8304a91e-7af1-415e-abc2-9e4f50138720140227366921984_1597387595945
__530ab92b-7071-41d8-9017-f1342a830676140112226502400_1600532201900 __a86cdfc9-ebf2-47f9-8b30-a72ed8117184139824271243008_1601649706007
__35856b6e-d6e4-4be7-a6b0-e3d632b016e4140112226502400_1600546863634 __8c21844e-9874-4864-9807-33950d4cd42f139824271243008_1601661032409
__21e2a898-af54-4eeb-938b-4218ba436303140112226502400_1600540722920 __ce278263-43e2-44ec-9afb-ed0721a0f4c0139824271243008_1601654896204
__16e19e07-c43e-4971-86ca-42f8e4ae6b5d140340709598976_1596876404605 __a4ef83ba-16ea-45d1-9850-f8e3e9c8f990140227366921984_1597379274446
__7a5f558d-4b8c-4c7d-8e37-34e5e5a259e5139824271243008_1601644574383 __94d49aac-cc7a-420a-b020-7a583a289a46140112226502400_1600525963840
__424ad700-1bc5-469c-bc7d-3d751bd83465140112226502400_1600553537405 __80eadc2f-0b61-4838-a552-efadf8b7298a139824271243008_1601669505776
```
This is  in addition to the `__58eb4600-9c95-425e-a585-4bb23b486577140340709598976_1596797671601` fragment @nalinigans identified earlier. Seems to hint at some sort of append job cleanup issue.

**Comment by bbimber** [comment]
@nalinigans we might be having a similar issue on this workspace, this time using that workspace for a GenomicsDbImport/append job, using --consolidate. 

Can you let us know how you determined which fragments are expected to exist? We believe this is related to QNVO02002898.1$1$11848, since it always fails in the same place: batch 3 of 4 for this contig.

**Comment by nalinigans** [comment]
At the least, all the array fragments should have the file `__coords.tdb` in them. Also, @mlathara [did find duplicate fragments with the workspace](https://github.com/broadinstitute/gatk/issues/6910#issuecomment-719655291) you shared with us before. Can you do that check too?

Did your script have to cleanup/restart GenomicsDBImport at any point?

**Comment by mlathara** [comment]
Can you give a bit more information here? If I'm understanding correctly, it's not clear that the same issue is at play here. The original issue was that duplicate/incomplete fragments were causing queries to the workspace to fail. 

In this latest instance, it seems you are appending additional samples to the existing workspace. Is that right? If so,
- are you seeing the same/similar error? That is, it's a core dump? Can you share the error messages, any logs, core dump files etc?
- did you clean up the workspace before importing? That is, remove the incomplete fragment @nalinigans identified and the duplicated ones?

My first instinct is that even if the incomplete/duplicated fragments weren't cleaned up, the incremental import shouldn't have an issue -- at least not till it gets to the consolidate phase, which only happens after all batches are imported. Sounds like you were seeing an issue at batch 3 of 4, so might have something to do with the samples in that batch...or some other import issue. You mentioned that previous imports to this particular contig failed -- were those just transient failures that worked when rerun, or was there some configuration that you changed to get that to work?

For completeness, the way I identified duplicate fragments was to do an md5sum check on some of the internal files. If any pair of fragments have the same md5sum they are likely duplicates. So, from the workspace directory, something like:

```
find . -name "ALT.tdb" -exec md5sum {} \;|sort
```
That will highlight the fragments that are potentially duplicate. To confirm that the fragments are indeed duplicates, you'll then want to take that list of potentially duplicate fragments and check that all corresponding files within each pair of potentially duplicate fragments actually have the same md5sum. I have a crude bash script that I can share if you want.

**Comment by bbimber** [comment]
The script copies the source workspace to a new location and executes the append/consolidate there. It did fail, but after failure it deletes the working copy and re-copies the original to that location. It's failed in the same contig/batch multiple times. Given this workspace has gone through multiple rounds of append and we did have errors during its creation, there is the possibility of an incomplete cleanup. Based on what @mlathara writes, it seems like it is possible for an error in the past to get carried forward, perhaps without causing new errors until --consolidate is used?

I do see some evidence of duplication, so I'm going to run a more thorough md5 check across all the contig folders.  I also see subdirs with widely different modified dates; however, I suppose this could be the result of incremental import.

This particular set of jobs is running GenomicsDbImport on the workspace, scattered as 48 jobs. About half the jobs have finished without errors. 

I'll post the results of the workspace-wide check for duplicated fragments.

**Comment by bbimber** [comment]
@mlathara also, to verify a question from earlier: is there anything within the workspace that lists what folders are expected to exist within each contig folder? there must be some kind of sample->fragment mapping being recorded somewhere?

**Comment by mlathara** [comment]
@bbimber mostly true and I don't want to discourage you cleaning up incomplete/duplicate fragments. But I don't think that is the root cause of your import failure. Duplicate/incomplete fragments should not cause errors during import (or at least, not till the consolidation phase after all the batches have been imported). 

When you do an import (incremental or otherwise) and specify `--consolidate`, all of the batches get must get imported and only then does consolidation happen. Since you said this failure happens during batch 3 of 4 of the import, this means consolidation hasn't started yet.

Regarding list of folders within each contig folder -- no there is no sample to fragment mapping. Theoretically, a sample can exist in multiple fragments (though this is not possible here, due to the way GenomicsDB is used within GATK). The __coords.tdb files have some low level information that helps map between samples and fragments, but these are all in binary formats and are not human readable.

**Comment by bbimber** [comment]
Two more things:

1) attached is the error log. There error is:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb23d5aba19, pid=147396, tid=140403504084736
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode linux-amd64 )
# Problematic frame:
# C  [libtiledbgenomicsdb6950059158101672698.so+0x3e3a19]  ArraySchema::tile_num(void const*) const+0x79
#
# Core dump written. Default location: /home/groups/MgapGenomicsDb/@files/sequenceOutputPipeline/SequenceOutput_2020-11-04_09-17-57/Job44/core or core.147396
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

[hs_err_pid147396.log.txt](https://github.com/broadinstitute/gatk/files/5496539/hs_err_pid147396.log.txt)


2) I was mistaken on when the error happens. The last line logged by GenomicsDBImport is "GenomicsDBImport - Importing batch 4 with 33 samples". There are 4 total batches, with a batchSize of 50. I dont know whether batch 4 finished or if this error is mid-batch import.

**Comment by nalinigans** [comment]
This seg fault looks like the fragment is missing the `__coords.tdb` file again. Can you do a `cd <array_name>; find . -type d '!' -exec test -e "{}/__coords.tdb" ";" -print | grep "__"`? This should list the fragments that do not have the `__coords.tdb` file at least.

**Comment by bbimber** [comment]
@nalinigans I'm looking into this. This will fall out form the workspace-wide md5 comparison that's running.

One additional observation/question: on my source workspace, most contig folders have 38 items: 36 fragments and two additional files. Some of them have many more fragments, particularly in a subset of the unplaced contigs. Should every contig folder have an equal number of fragments in it?

**Comment by mlathara** [comment]
Yes, all folders should have the same number of fragments unless different batch size parameters were used with different contig folders/workspaces. I talked a bit about expected number of fragments here: https://github.com/broadinstitute/gatk/issues/6910#issuecomment-719623951

**Comment by bbimber** [comment]
@mlathara The MD5 checking is going, but two conclusions:  

1) there are three array folders lacking a __coords.tdb file.

2) I counted the total fragment folders per contig, and many contig folders have a widely different number of fragments. I think the expected/correct number is 36, or at least the primary contigs seem to have this. Is there any way to figure out what is supposed to exist, and prune the problem folders?

I have a suspicion on where the duplicates could come from. Our jobs copy the source from non-lustre to the cluster, execute GenomicsDbImport/append, and copy the appended workspace to a new location. As we were getting this going, there were various job failures on the cluster. Some of these failures happened during that copy-back, resulting in a partially copied contig folder on the non-lustre disks. When the job restarted, it would destroy/recreate the copy on lustre, but I think it would be possible for this to not properly destroy that version that was partially copied off lustre. When the job finished again, it would rsync the new lustre version over that partial workspace. I dont know if fragment names are deterministic or not, but if they are not deterministic for a given job, then it might have been possible accumulate fragments there. I dont know if this happened, but it's the only place i can see where our code might have have been thoroughly cleaning up after itself and/or dealing with job failure. 

As I said above, I'm collecting MD5sums for all the files in the workspace. This could find duplicates, but I'm not sure whether it tells me which one should be removed.

[improperArrayNum.txt](https://github.com/broadinstitute/gatk/files/5497344/improperArrayNum.txt)

**Comment by bbimber** [comment]
regarding inspecting these arrays, would one of the TileDB bindings, like R (https://docs.tiledb.com/main/solutions/tiledb-embedded/api-usage/array-metadata), be a way to extract information about what fragments should exist?

**Comment by nalinigans** [comment]
No, that won't work as that is something else altogether. We do have some experimental GenomicsDB-R bindings, but nothing that would output the array metadata. I can conjure up a tool to do that for you, what flavor of OS are you running on?

**Comment by bbimber** [comment]
our cluster is centos7, but i could work with whatever you're able to most efficiently create. we really appreciate the help here.

**Comment by nalinigans** [comment]
Please find the print_array_schema executable [here](https://github.com/GenomicsDB/GenomicsDB/releases/download/v1.3.1/print_array_schema). You may have to do a `chmod +x print_array_schema` after downloading.
```
Usage: print_array_schema <genomicsdb-workspace-path>/genomicsdb_array
```
This will print out all the information for the array, it does not know anything about the fragments. Look at the `Types` printed out by the tool. Each fragment should have `__book_keeping.tdb.gz` and `__tiledb_fragment.tdb`. In addition, for each fragment, there should be one file for each type plus another file if it is a var type.

**Comment by nalinigans** [comment]
> I dont know if fragment names are deterministic or not, but if they are not deterministic for a given job, then it might have been possible accumulate fragments there.
Fragment names are uniquely created everytime.

**Comment by bbimber** [comment]
@nalinigans Thanks - i have run the tool but I'm not entirely certain where I should focus. I understand what it's saying about the expected files within each fragment directory. So I could (and in the process of) counting the set of files per fragment. For our workspace, we expect 39 files/fragment. Checking the presence of those files is in the same lines as testing if  __coords.tdb exists.

The current state of this workspace seems to be that some contigs have more fragment folders than expected. at least some of these fragment folders have the expected number of files. is there nothing in the workspace that reports what fragments should exist? 

Looking at this another way: can I run a SelectVariants on this workspace, requesting every sample that should exist? Can this write out GenomicsDB to a new workspace?

**Comment by mlathara** [comment]
So here's what you should do to clean up your workspace:
- first, delete any fragment that doesn't have the full complement of 39 files that it is supposed to have
- next, if there are any duplicate fragments delete all but one. it doesn't matter which one you delete, the fragments have identical data (make sure this is the case by checking md5sums for ALL files in the duplicate fragments). As an aside, this step is optional. That is to say, your workspace is still legal if you leave the duplicate fragments, but you MUST remove the incomplete ones. Not removing them will just take up extra space. And it'll make the last verification/sanity check a little trickier
- If you've deleted duplicate and incomplete fragments, you should now have the same number of fragments in all your contig folders. If you have fewer fragments in a contig folder, then it is likely that some import process may have failed midway. If you have too many fragments...some other weird corruption may have happened which may be hindering the redundancy check.

**Comment by bbimber** [comment]
@mlathara thanks, but one additional question. what occurs is --consolidate runs on a folder that contained additional, redundant/identical arrays? I ask b/c some of our jobs finished already on folders that I am fairly certain contained redundant arrays, but they completed w/o error.

**Comment by mlathara** [comment]
If consolidate ran without issues, that array/contig folder didn't have any fragments that were incomplete. And yes, the duplicates were consolidated down so everything should be fine. 

I should add, my last bullet about sanity checks regarding number of fragments does not apply to consolidated arrays. Those will, of course, only have a single fragment.

**Comment by bbimber** [comment]
Based on the thread above, we identified and removed any fragments (there were 3 total) that lacked all the expected files. The primary chromosome jobs had been running fine, but most are eventually hitting this 'bad_alloc' error. Does this suggest a memory issue?  There is not much else information printed. One example log is below. Note: these jobs are run on a slurm cluster with the following java options: -Xmx104g -Xms104g -Xss2m. The job requests 128gb RAM total, leaving 24 as a buffer for the c++ layer. 

05 Nov 2020 09:10:06,291 DEBUG:     09:10:06.291 INFO  GenomicsDBImport - Importing batch 2 with 50 samples
05 Nov 2020 20:39:53,314 DEBUG:     20:39:53.313 INFO  ProgressMeter -                  1:1           1695.3                     2              0.0
05 Nov 2020 20:39:53,454 DEBUG:     20:39:53.314 INFO  GenomicsDBImport - Done importing batch 2/4
05 Nov 2020 20:40:00,591 DEBUG:     20:40:00.589 INFO  GenomicsDBImport - Importing batch 3 with 50 samples
06 Nov 2020 11:08:48,202 DEBUG:     11:08:48.197 INFO  ProgressMeter -                  1:1           2564.2                     3              0.0
06 Nov 2020 11:08:48,358 DEBUG:     11:08:48.201 INFO  GenomicsDBImport - Done importing batch 3/4
06 Nov 2020 11:08:55,067 DEBUG:     11:08:55.067 INFO  GenomicsDBImport - Importing batch 4 with 33 samples
07 Nov 2020 15:40:57,625 DEBUG:     terminate called after throwing an instance of 'std::bad_alloc'
07 Nov 2020 15:40:57,908 DEBUG:       what():  std::bad_alloc

**Comment by bbimber** [comment]
While most jobs have been failing with an error like the above, chr8 gave the following. Does this also suggest a memory  issue, based on Z_MEM_ERROR: https://zlib.net/manual.html?

07 Nov 2020 08:34:25,100 DEBUG:     08:34:24.941 INFO  GenomicsDBImport - Done importing batch 3/4
07 Nov 2020 08:34:29,847 DEBUG:     08:34:29.847 INFO  GenomicsDBImport - Importing batch 4 with 33 samples
08 Nov 2020 10:46:27,095 DEBUG:     [TileDB::utils] Error: (gzip_handle_error) Cannot decompress with GZIP: inflateInit error: Z_MEM_ERROR
08 Nov 2020 10:46:27,280 DEBUG:     [TileDB::Codec] Error: Could not compress with .
08 Nov 2020 10:46:27,285 DEBUG:     [TileDB::ReadState] Error: Cannot decompress tile.
08 Nov 2020 10:47:00,459 DEBUG:     10:47:00.458 erro  NativeGenomicsDB - pid=16931 tid=17036 VariantStorageManagerException exception : Error while consolidating TileDB array 8$1$145679320
08 Nov 2020 10:47:00,473 DEBUG:     TileDB error message : 
08 Nov 2020 10:47:00,487 DEBUG:     terminate called after throwing an instance of 'std::exception'
08 Nov 2020 10:47:00,492 DEBUG:       what():  std::exception
08 Nov 2020 10:47:37,511 WARN :     process exited with non-zero value: 134

**Comment by nalinigans** [comment]
@bbimber, yes they are both memory issues - the GenomicsDBImport native layer is getting memory starved! You mention `-Xmx104g -Xms104g -Xss2m` with `24` left for the native layer. Is it possible to allocate more memory to the native layer by reducing -Xmx -Xms options? Also, what is the exact gatk command? Are you also doing a consolidate as part of this command?

**Comment by bbimber** [comment]
Yes, that is easy to do. The guidance on how much memory to leave wasnt clear on the docs. Is there a rule of thumb on how much we should leave? We can do whatever makes sense.

the command is something like:

```

 /home/exacloud/gscratch/prime-seq/java/java8/bin/java \
-Djava.io.tmpdir=/mnt/scratch/prime-seq/tmp.5E76utMagnGenomicsDB_Append_Merge_2020-11-04_09-17-56-Job1 \
-Xmx104g \
-Xms104g \
-Xss2m \
-jar /home/exacloud/gscratch/prime-seq/bin/GenomeAnalysisTK4.jar GenomicsDBImport \
-V <Repeated 183 times for gVCFs> \ 
--genomicsdb-update-workspace-path /home/exacloud/gscratch/prime-seq/workDir/9a2611e8-0112-1039-8c80-f8f3fc869aa5/Job1.work/WGS_Nov_1300.gdb \
--batch-size 50 \
--consolidate \
--genomicsdb-shared-posixfs-optimizations


```

**Comment by nalinigans** [comment]
Thanks @bbimber. Can you run the command without the `--consolidate` option? We will be working on a `--consolidate-only` option for `gatk GenomicsDBImport` soon, but can provide you a standalone tool to perform only the consolidation later today. Is that OK?

**Comment by nalinigans** [comment]
Please find the standalone consolidation tool [here](https://github.com/GenomicsDB/GenomicsDB/releases/download/v1.3.1/consolidate_genomicsdb_array). The usage is `consolidate_genomicsdb_array <genomicsdb_workspace_path> <array_name>`, for example `./consolidate_genomicsdb_array ~/my_ws/ "20\$1\$63025520"`

**Comment by bbimber** [comment]
@nalinigans the set of jobs was ultimately able to work. While our issues with duplication and bad fragments are most likely our fault, any future improvements to GenomicsDbImport to detect and/or fix these would be useful. Thanks for all your help on this front.
