### ISSUE TITLE
FindMendelianViolations default XPAR co-ordinates for b37 incorrect

### ISSUE THREAD

**Issue by dmarkie** [broadinstitute/gatk#6919]
### Affected tool(s) or class(es)
FindMendelianViolations

### Affected version(s)
Version:4.1.8.1 and several earlier versions

### Description 
Using the gatk FindMendelianViolations --help command to obtain information about this tool produces the following for the default XPAR regions:
--PSEUDO_AUTOSOMAL_REGIONS:String
List of chr:start-end for pseudo-autosomal regions on the female sex chromosome. Defaults
to HG19/b37 & HG38 coordinates.  This argument may be specified 0 or more times. Default
value: [chrX:10000-2781479, X:10001-2649520, chrX:155701382-156030895,
X:59034050-59373566]. 

These co-ordinates are also replicated in the output file. From the GRC site the co-ordinates for the b37 regions should be X:600001-2699520 and X:154931044-155260560 whereas those used by default seem to correspond to the Y chromosome values for b37.
When trying to correct this issue by using the --PSEUDO_AUTOSOMAL_REGIONS option it simply adds the newly defined regions to the command rather than replacing the defaults.

**Comment by droazen** [comment]
@dmarkie Thanks for the bug report! Since the code for this tool actually lives in the Picard repository (https://github.com/broadinstitute/picard), would you mind filing this ticket there?
