### ISSUE TITLE
create a multi-variant walker 

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#692]
The requirement here is to write a new type of walker that takes multiple (FeatureInputs) as the driving data type. The engine will then traverse all those at the same time (using a priority queue, @droazen) and present variants to the tool (all variants starting at the given position).

The is a prerequisite for GenotypeGVCFs.

**Comment by droazen** [comment]
alpha-2

**Comment by cmnbroad** [comment]
Unclear to me if this is a dup of https://github.com/broadinstitute/gatk/issues/2114 or not (2114 presents one variant at a time, as opposed to all variants that start at the same position).

**Comment by droazen** [comment]
This is done, thanks to @cmnbroad . We've decided not to implement a separate traversal for `GenotypeGVCFs` for now, as we've gotten it working with the standard GATK4 variant traversal.
