### ISSUE TITLE
Implementing Custom VariantAnnotation classes in GATK4?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#6929]
Hello - in GATK3 we wrote a variety of custom VariantAnnotation classes, and created a GATK3 fork / custom JAR with those classes. We run VariantAnnotator using that. I am hoping you might comment on whether this plan seems reasonable:

I am going to try to implement this in our DISCVRseq package, which is a standalone package that depends on GATK4. I am currently expecting that I would need to be a separate tool, like "VariantAnnotationExtended" in our code. My tool can make an instance of VariantAnnotatorEngine, passing whatever annotationList I see fit. It seems like I will either be able to use GATKTool.makeVariantAnnotations() as-is, or override it to search custom classpaths (not currently clear if that's needed). In the end, my new tool should be able to function like core GATK4 VariantAnnotator, picking up your core annotations and whatever new ones I make. The latter is useful so I dont need to execute two annotation commands if I want to use a combination of annotations. 

Is there a better way to implement custom VariantAnnotations in GATK4?

**Comment by cmnbroad** [comment]
@bbimber The `GATKAnnotationPluginDescriptor` uses the GATK config file to find packages that contain annotation classes, and will automatically discover annotation classes that are in packages listed there (see [this](https://github.com/broadinstitute/gatk/blob/f4996564f0abe02b6a202eaff402c2f3fa044633/src/main/java/org/broadinstitute/hellbender/cmdline/GATKPlugin/GATKAnnotationPluginDescriptor.java#L46) and [this](https://github.com/broadinstitute/gatk/blob/master/src/main/resources/org/broadinstitute/hellbender/utils/config/GATKConfig.properties#L77)).

**Comment by bbimber** [comment]
@cmnbroad OK, so I see that I can supply a custom --gatk-config file on the command line, and I suppose I would also provide my other JAR on the classpath with my additional VariantAnnotation classes?  That is useful, but also a little unclean given I am already building our DISCVRseq JAR, which includes the GATK4 dependency. I'm still inclined to make our tool that extends GATK's VariantAnnotation, and override makeVariantAnnotations(). I could either manipulate GATKAnnotationPluginDescriptor, or make my own to scan the expected package(s). It seems pretty surgical and less would be required of the user to run it.

**Comment by droazen** [comment]
@bbimber You also have the option of bundling your custom config file inside your DISCVRseq  jar -- that way you don't need to supply it on the command line

**Comment by bbimber** [comment]
@droazen I've finally been able to move ahead on this and have a question on what to expect for plugins that define arguments. I have two plugins that each share an argument. I created an ArgumentCollection class to define that argument, and then added this @ArgumentCollection to each plugin. Something like:

```

public class GenotypeConcordanceBySite extends PedigreeAnnotation implements InfoFieldAnnotation {    ​
   ​@ArgumentCollection
   ​public GenotypeConcordanceArgumentCollection args = new GenotypeConcordanceArgumentCollection();

​.   .etc......
}

Gpublic class GenotypeConcordance extends PedigreeAnnotation implements InfoFieldAnnotation {
   ​@ArgumentCollection
   ​public GenotypeConcordanceArgumentCollection args = new GenotypeConcordanceArgumentCollection();

.     etc......
}


public class GenotypeConcordanceArgumentCollection {
   ​@Argument(doc="Reference genotypes VCF", fullName = "reference-genotypes-vcf", shortName = "rg", optional = true)
   ​public FeatureInput<VariantContext> referenceVcf = null;
}

```

When I run VariantAnnotator with both plugins, I get an error from within Barclay about arguments with duplicate names. 

Ideally these plugins would not be aware of each other (since they can be used independently). Is there a way to define arguments that might be declared in different plugins, but are somehow resolved as identical and therefore allowed?
