### ISSUE TITLE
How to use all core on GATK tools?

### ISSUE THREAD

**Issue by ertanyilmaz38** [broadinstitute/gatk#6941]
Hello, I use GATK tools quite often in my daily work life. I use quite a lot of sample data every time I use it. The fact that GATK tools use a single core causes analysis processes to take quite a long time. Although I command --java-options "-Xmx32G -XX:ParallelGCThreads=8" to GATK tools, GATK tools slow down the process by using only one thread instead of using 8 threads. How can I get GATK tools to use 8 threads? Thank you.

**Comment by fleharty** [comment]
The option  -XX:ParallelGCThreads=8 will not increase the number of threads GATK uses.  That increases the number of threads available to the JVM garbage collector, and this will not speed up your jobs.

I suggest taking a look at the GATK forums, the following two articles are good starting points for running your jobs in parallel.

Pipelining GATK with WDL and Cromwell
https://gatk.broadinstitute.org/hc/en-us/articles/360035889771

Parallelism - Multithreading - Scatter
https://gatk.broadinstitute.org/hc/en-us/articles/360035532012-Parallelism-Multithreading-Scatter-Gather
