### ISSUE TITLE
Add a RefAPISource test for a query on an interval that starts on the contig and runs off of it

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#698]

**Comment by akiezun** [comment]
is spark affected?

**Comment by davidadamsphd** [comment]
Yes.

**Comment by akiezun** [comment]
what should the result be? blow up or truncated answer?

**Comment by akiezun** [comment]
IndexedFastaSequenceFile will blow up with SAMException.
CachingIndexedFastaSequenceFile will also blow up the same way
HadoopReferenceSequenceFileFactory : same

InMemoryReferenceSequenceFile will blow up with ArrayIndexOutOfBoundsException

so i guess the answer it: it should blow up (but the exception is somewhat arbitrary)
