### ISSUE TITLE
cannot view the vcf files of the official website

### ISSUE THREAD

**Issue by chaoyanggu** [broadinstitute/gatk#6988]
hi, I downloaded the hg38 database from the following URL two months ago, which contains some known sites of vcf files such as snp and indel;
https://gatk.broadinstitute.org/hc/en-us/articles/360035890811；GATK resource bundle
 But now I found that the contents of these vcf files cannot be viewed. I think the vcf files should  be viewed under normal circumstances; now I want to restart download the data; but the official website was updated two days ago, can you give me a website to download the data?
thanks

the error for view is:
1000G_phase1.snps.high_confidence.hg38.vcf  may be a binary file;

**Comment by ldgauthier** [comment]
The github issue tracker is for bug reports, feature requests, and API documentation requests. General questions about how to use the GATK, how to interpret the output, etc. should be asked on the [official support forum](http://gatkforums.broadinstitute.org/gatk).
