### ISSUE TITLE
Ambiguous REF reported when using GenotypeGVCFs/--force-output with GenomicsDB as input, but not a gVCF

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#7005]
Hello,

We are using GenotypeGVCFs (GATK version v4.1.8.0) to genotype either WGS or WXS data that have been stored in a GenomicDB workspace. We also use the --force-output argument to force GATK to output genotypes from a whitelist of sites. We ran into a problem where GenotypeGVCFs + --force-output + GenomicDB reports 'N' as the reference genotype for any site not present in the source workspace. In contrast, if you run a similar command with GenotypeGVCFs + --force-output + gVCF, the resulting VCF reports the correct reference base. In both cases we are passing the FASTA as -R to the tool.

Here are two example outputs:

This is from GenotypeGVCFs with a GenomicsDB workspace as input. Note: 1565827 and 1565828 are wild-type in all samples, but are included b/c of --force-output. It reports N as REF:
#CHROM	POS	ID	REF	ALT
1	1565827	.	N	.
1	1565828	.	N	.
1	1565829	.	T	TGATGGTGGC

This is from a similar command with a gVCF as input. The REF base is correct. Note, the ALT is different b/c of different samples in the inputs:
#CHROM	POS	ID	REF	ALT
1	1565827	.	G	.
1	1565828	.	A	.
1	1565829	.	T	.

But the key behavior difference is that if this is a site that would only get output b/c of --force-output, then when a gVCF is the source it gets the REF right, and when GenomicsDB is the source it reports N.

I am happy to do some legwork digging into the code and proposing a fix, but it would be helpful to know if there's a known issue around this, and/or get any pointers into where in the GATK/HTSJDK layer I might start looking.

An example command is something like:

```
java8 -jar <JAR> GenotypeGVCFs \
	-R $REF \
	-O $OUTPUT \
	--variant $GENOMICS_DB_WORKSPACE \
	-L 1:1565827-1565829 \
	-L 1:1699262-1699298 \
	-L 6:14972856-14972872 \
	-L X:135349386-135349395 \
	-L Y:3491100-3491102 \
	--only-output-calls-starting-in-intervals \
	--genomicsdb-shared-posixfs-optimizations \
	--force-output-intervals <BED_FILE>

```

In this example, those -L positions were selected b/c they elicit the behavior. Those sites are present in the BED file used for --force-output-intervals. At least in our hands, the combination of calling from a GenomicsDB workspace and using --force-output-intervals to output some site that would not normally get output will result in the 'N' REFs.
Thanks,
Ben

**Comment by bbimber** [comment]
A few other observatons/comments:

- There is a second issue: QUAL is 'inf' on those sites where it reports N as the REF.

- When comparing the situation where the input is GenomicsDB vs. a combined gVCF, I think I was told GenomicsDB does some of the aggregation of the fly (in contrast to a combined gVCF, where this aggregation was done by CombineGVCFs ahead of time)? Could that codepath be the problem here?

- It's worth noting that when one supplies --force-output-intervals (or includeNonVariants), then GenotypeGVCFs changes the mode in VariantLocusWalker to traverseByVariant. Point being it switches to a very different iteration pattern.

**Comment by bbimber** [comment]
Also, FeatureDataSource.getGenomicsDBFeatureReader requires the reference, but it's never used, apparently:

https://github.com/broadinstitute/gatk/blob/bc0994c180312cdca7afbe45b410b2c6fc312043/src/main/java/org/broadinstitute/hellbender/engine/FeatureDataSource.java#L387

Should something related to GenomicsDBFeatureReader be getting the reference? FeatureData source has an error if it's not provided: "You must provide a reference if you want to load from GenomicsDB".

**Comment by bbimber** [comment]
One final thing: i'm happy to try to debug this, and was going to write a test case based on the existing GenomicsDB integration tests. However, when I try to run any integration test involving genomicsdb, I get an exception like the following. I am on windows, so perhaps this is the issue?

09:03:37.460 FATAL GenomicsDBLibLoader - 
java.io.FileNotFoundException: File /tiledbgenomicsdb.dll was not found inside JAR.
	at org.genomicsdb.GenomicsDBLibLoader.loadLibraryFromJar(GenomicsDBLibLoader.java:118) ~[genomicsdb-1.3.2.jar:?]
	at org.genomicsdb.GenomicsDBLibLoader.loadLibrary(GenomicsDBLibLoader.java:55) [genomicsdb-1.3.2.jar:?]
	at org.genomicsdb.GenomicsDBUtilsJni.<clinit>(GenomicsDBUtilsJni.java:30) [genomicsdb-1.3.2.jar:?]
	at org.genomicsdb.GenomicsDBUtils.createTileDBWorkspace(GenomicsDBUtils.java:46) [genomicsdb-1.3.2.jar:?]
	at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.overwriteCreateOrCheckWorkspace(GenomicsDBImport.java:1005) [classes/:?]
	at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.onTraversalStart(GenomicsDBImport.java:661) [classes/:?]
	at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1056) [classes/:?]

**Comment by bbimber** [comment]
Hello - I realize people are probably out for stretches over christmas/new years, but we'd really like to try to dig into this issue. Does anyone have comments at least on the GenomicsDBLibLoader errors?

**Comment by bbimber** [comment]
Hello - I thought I'd write again to see if by chance anyone was back from the holidays. Again, I'm happy to do more legwork on our side, but would appreciate if anyone had thoughts on the GenomicsDBLibLoader error posted above.  Thanks.

**Comment by nalinigans** [comment]
> One final thing: i'm happy to try to debug this, and was going to write a test case based on the existing GenomicsDB integration tests. However, when I try to run any integration test involving genomicsdb, I get an exception like the following. I am on windows, so perhaps this is the issue?
> 
> 09:03:37.460 FATAL GenomicsDBLibLoader -
> java.io.FileNotFoundException: File /tiledbgenomicsdb.dll was not found inside JAR.
> at org.genomicsdb.GenomicsDBLibLoader.loadLibraryFromJar(GenomicsDBLibLoader.java:118) ~[genomicsdb-1.3.2.jar:?]
> at org.genomicsdb.GenomicsDBLibLoader.loadLibrary(GenomicsDBLibLoader.java:55) [genomicsdb-1.3.2.jar:?]
> at org.genomicsdb.GenomicsDBUtilsJni.(GenomicsDBUtilsJni.java:30) [genomicsdb-1.3.2.jar:?]
> at org.genomicsdb.GenomicsDBUtils.createTileDBWorkspace(GenomicsDBUtils.java:46) [genomicsdb-1.3.2.jar:?]
> at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.overwriteCreateOrCheckWorkspace(GenomicsDBImport.java:1005) [classes/:?]
> at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.onTraversalStart(GenomicsDBImport.java:661) [classes/:?]
> at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1056) [classes/:?]

Yes, Windows is not supported by GenomicsDB. This is mentioned obliquely in the requirements for gatk too -
```
Operating system

The GATK runs natively on most if not all flavors of UNIX, which includes MacOSX, Linux and BSD. It is possible to get it running on some recent versions of Windows, but we don't provide any support nor instructions for that. If you need to run on a Windows machine, consider using Docker.
```

**Comment by bbimber** [comment]
@nalinigans OK, thanks. I'll try to get docker going w/ intellij.

to the original question/bug: is there anything inherent about GenotypeGVCFs with GenomicsDB as the source vs. a gVCF as the source that one would expect to change how GATK determines the reference allele? I have not actually run this yet, but if I'm correct on the problem this probably should repo it (an addition to GenotypeGVCFsIntegrationTest):

```

    @Test(timeOut = 1000000)
    public void testGenotypeGVCFsWithGenomicsDbAndForceOutput() throws IOException {
        final File input = CEUTRIO_20_21_GATK3_4_G_VCF;
        SimpleInterval interval = new SimpleInterval("20", 1, 11_000_000);
        final File tempGenomicsDB = GenomicsDBTestUtils.createTempGenomicsDB(input, interval);
        final String genomicsDBUri = GenomicsDBTestUtils.makeGenomicsDBUri(tempGenomicsDB);

        File expected = getTestFile("CEUTrio.20.gatk3.7_30_ga4f720357.expected.vcf");
        String reference = b37_reference_20_21;

        runGenotypeGVCFSAndAssertSomething(genomicsDBUri, expected, Arrays.asList("--" + GenotypeGVCFs.FORCE_OUTPUT_INTERVALS_NAME, "20:10-20"), GenotypeGVCFsIntegrationTest::assertVariantsContextsHaveNonAmgibuousRefs, reference);
    }

```

**Comment by bbimber** [comment]
@nalinigans OK, I have been able to repro this using GATK's existing test data. It's not quite what I originally thought, but I created a test to illustrate it. It might be easier to show on this PR: #7018
