### ISSUE TITLE
AnalyzeCovariates Error "gplots"  

### ISSUE THREAD

**Issue by ertanyilmaz38** [broadinstitute/gatk#7006]
/home/detagen/Desktop/programlar/gatk-4.1.8.1/gatk AnalyzeCovariates --before-report-file /home/detagen/Desktop/pipeline/playground//BACKUP/FMF-248_Backup/before.recal.FMF-248.table --after-report-file /home/detagen/Desktop/pipeline/playground//BACKUP/FMF-248_Backup/after.recal.FMF-248.table --plots-report-file /home/detagen/Desktop/pipeline/playground//NECESSARY/FMF-248/AnalyzeCovariates.FMF-248.pdf
Using GATK jar /home/detagen/Desktop/programlar/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/detagen/Desktop/programlar/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar AnalyzeCovariates --before-report-file /home/detagen/Desktop/pipeline/playground//BACKUP/FMF-248_Backup/before.recal.FMF-248.table --after-report-file /home/detagen/Desktop/pipeline/playground//BACKUP/FMF-248_Backup/after.recal.FMF-248.table --plots-report-file /home/detagen/Desktop/pipeline/playground//NECESSARY/FMF-248/AnalyzeCovariates.FMF-248.pdf
12:57:16.643 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/detagen/Desktop/programlar/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Dec 17, 2020 12:57:16 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
12:57:16.774 INFO  AnalyzeCovariates - ------------------------------------------------------------
12:57:16.775 INFO  AnalyzeCovariates - The Genome Analysis Toolkit (GATK) v4.1.8.1
12:57:16.775 INFO  AnalyzeCovariates - For support and documentation go to https://software.broadinstitute.org/gatk/
12:57:16.775 INFO  AnalyzeCovariates - Executing as detagen@detagen on Linux v5.4.0-58-generic amd64
12:57:16.775 INFO  AnalyzeCovariates - Java runtime: OpenJDK 64-Bit Server VM v11.0.9.1+1-Ubuntu-0ubuntu1.18.04
12:57:16.775 INFO  AnalyzeCovariates - Start Date/Time: December 17, 2020 at 12:57:16 PM TRT
12:57:16.775 INFO  AnalyzeCovariates - ------------------------------------------------------------
12:57:16.775 INFO  AnalyzeCovariates - ------------------------------------------------------------
12:57:16.776 INFO  AnalyzeCovariates - HTSJDK Version: 2.23.0
12:57:16.776 INFO  AnalyzeCovariates - Picard Version: 2.22.8
12:57:16.776 INFO  AnalyzeCovariates - HTSJDK Defaults.COMPRESSION_LEVEL : 2
12:57:16.776 INFO  AnalyzeCovariates - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
12:57:16.776 INFO  AnalyzeCovariates - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
12:57:16.776 INFO  AnalyzeCovariates - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
12:57:16.776 INFO  AnalyzeCovariates - Deflater: IntelDeflater
12:57:16.776 INFO  AnalyzeCovariates - Inflater: IntelInflater
12:57:16.776 INFO  AnalyzeCovariates - GCS max retries/reopens: 20
12:57:16.776 INFO  AnalyzeCovariates - Requester pays: disabled
12:57:16.776 INFO  AnalyzeCovariates - Initializing engine
12:57:16.776 INFO  AnalyzeCovariates - Done initializing engine
12:57:17.333 INFO  AnalyzeCovariates - Generating csv file '/tmp/AnalyzeCovariates17353441228865531235.csv'
12:57:17.414 INFO  AnalyzeCovariates - Generating plots file '/home/detagen/Desktop/pipeline/playground/NECESSARY/FMF-248/AnalyzeCovariates.FMF-248.pdf'
12:57:17.829 INFO  AnalyzeCovariates - Shutting down engine
[December 17, 2020 at 12:57:17 PM TRT] org.broadinstitute.hellbender.tools.walkers.bqsr.AnalyzeCovariates done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=633339904
org.broadinstitute.hellbender.utils.R.RScriptExecutorException: 
Rscript exited with 1
Command Line: Rscript -e tempLibDir = '/tmp/Rlib.10272183847736955081';source('/tmp/BQSR.16251220439562120273.R'); /tmp/AnalyzeCovariates17353441228865531235.csv /home/detagen/Desktop/pipeline/playground/BACKUP/FMF-248_Backup/before.recal.FMF-248.table /home/detagen/Desktop/pipeline/playground/NECESSARY/FMF-248/AnalyzeCovariates.FMF-248.pdf
Stdout: 
Stderr: Error in library(gplots) : there is no package called ‘gplots’
Calls: source -> withVisible -> eval -> eval -> library
Execution halted

	at org.broadinstitute.hellbender.utils.R.RScriptExecutor.getScriptException(RScriptExecutor.java:80)
	at org.broadinstitute.hellbender.utils.R.RScriptExecutor.getScriptException(RScriptExecutor.java:19)
	at org.broadinstitute.hellbender.utils.runtime.ScriptExecutor.executeCuratedArgs(ScriptExecutor.java:130)
	at org.broadinstitute.hellbender.utils.R.RScriptExecutor.exec(RScriptExecutor.java:126)
	at org.broadinstitute.hellbender.utils.recalibration.RecalUtils.generatePlots(RecalUtils.java:360)
	at org.broadinstitute.hellbender.tools.walkers.bqsr.AnalyzeCovariates.generatePlots(AnalyzeCovariates.java:329)
	at org.broadinstitute.hellbender.tools.walkers.bqsr.AnalyzeCovariates.doWork(AnalyzeCovariates.java:341)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by AlijahArcher** [comment]
This is a problem with your `R` environment -- you need to install the `gplots` package (amongst a few others, if you don't already have them)

From  https://gatk.broadinstitute.org/hc/en-us/articles/360035889531-What-are-the-requirements-for-running-GATK-
```
R dependencies
Some of the GATK tools produce plots using R, so if you want to get the plots you'll need to have R and Rscript installed, as well as these R libraries: gsalib, ggplot2, reshape, gplots,
```

Here's a quick article on installing packages in R if you're unfamiliar (https://www.r-bloggers.com/2010/11/installing-r-packages/).  Note, you'll need a version of R that is compatible with these packages

**Comment by fanjieqi** [comment]
Run R in your console to enter the R console:
```Shell
R
```
Then, install packages and quit:
```R
install.packages("gsalib")
install.packages("reshape")
install.packages("gplots")
quit()
```
Finally, execute the command **gatk AnalyzeCovariates** once again.
