### ISSUE TITLE
Spark VariantWalkers?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#7013]
Hello - 

We have a tool build over VariantEval (https://bimberlab.github.io/DISCVRSeq/toolDoc/com_github_discvrseq_walkers_variantqc_VariantQC.html), which is not fast to run. It should be parallelizable, and I am assuming that making a spark version is the way one is supposed to do this. I see VariantWalkerSpark in your github and two example subclasses, but I dont see any real VariantWalkers using spark. Are there other spark variant walkers I'm not seeing? 

Thanks

**Comment by lbergelson** [comment]
@bbimber No, we don't currently have any real examples of spark VariantWalkers unfortunately.  I actually think you're the first person to be interested in one.  All of our expensive variant operations (particularly GenomicsDBImport and GenotypeGvcfs) are parallelized by splitting the input file into ranges and processing those independently right now.

**Comment by bbimber** [comment]
OK. Our pipelines currently all use gatk like you say. Our upstream code splits an operation (set of processing steps) into intervals and scatter/gathers across our slurm cluster. Other code then merges the output, which is usually a vcf.

VariantQC (which is basically a fancy variant eval), cannot currently be split so easily, since it aggregates data across the genome. Another option I've toyed with is making a mode in which one could execute it over a set of intervals, and have each job write some intermediate output with the pre-aggregated data. I would make another step that aggregates these outputs. If there are any facilities that exist in gatk to support this type of scenario I'd appreciate pointers. 

I was considering spark in this instance with the idea that it would be local parallelization, not a true spark cluster.

**Comment by bbimber** [comment]
If it helps, this is a dummy walker that illustrates the kind of parallelization I'm exploring whether I can implement. The main sticking point I think exists relates to different threads interacting with FeatureManager and the feature reading code:

I would appreciate any thoughts on how to approach this in GATK.

```

/**
 * This is a contrived example. It is designed to explore multithreading
 */
public class DemoMultiVariantEval extends MultiVariantWalkerGroupedOnStart {
    protected List<VariantEvalEngine> engines = new ArrayList<>();

    @ArgumentCollection
    protected VariantEvalArgumentCollection variantEvalArgs = new VariantEvalArgumentCollection();

    @Override
    protected void initializeDrivingVariants() {
        getDrivingVariantsFeatureInputs().addAll(VariantEvalEngine.getFeatureInputsForDrivingVariants(variantEvalArgs));

        super.initializeDrivingVariants();
    }

    private ExecutorService pool = null;
    private final int threads = 2;

    @Override
    public void onTraversalStart() {
        //Again, contrived. The real case would set up multiple engines with different parameters:
        engines.add(new VariantEvalEngine(variantEvalArgs, this, getSequenceDictionaryForDrivingVariants(), getSamplesForVariants(), logger));
        engines.add(new VariantEvalEngine(variantEvalArgs, this, getSequenceDictionaryForDrivingVariants(), getSamplesForVariants(), logger));

        final ThreadFactory threadFactory = new ThreadFactoryBuilder()
                .setNameFormat("dummywalker-thread-%d")
                .setDaemon(true)
                .build();

        pool = Executors.newFixedThreadPool(threads, threadFactory);
    }

    @Override
    public void apply(final List<VariantContext> variantContexts, final ReferenceContext referenceContext, final List<ReadsContext> readsContexts) {
        // Parallelization should help; however, these steps interact with FeatureManager and the FeatureInputs.
        // Is there an appropriate way to approach this?
        Utils.runInParallel(threads, () -> {
            this.engines.parallelStream().forEach(engine -> {
                engine.apply(variantContexts, referenceContext);
            });

            return null;
        });
    }

    @Override
    public void closeTool() {
        super.closeTool();

        if (pool != null) {
            pool.shutdownNow();
        }
    }
}


```
