### ISSUE TITLE
[Mutect2] the Alter Frequency[AF] is bigger than expected

### ISSUE THREAD

**Issue by jingchen-0927** [broadinstitute/gatk#7016]
## Bug Report
Hello,  I have a question about Mutect2 in GATK4(version 4.1.9.0). I wonder that the AF result is not exact.

### Affected version(s)
GATK4 version 4.1.9.0

### Description 
I got the result for the below site:
chr17   41244376        .       T       C       .       .       AS_SB_TABLE=575,531|23,21;DP=1192;ECNT=1;MBQ=30,30;MFRL=242,275;MMQ=60,60;MPOS=37;POPAF=7.30;TLOD=69.90      GT:AD:AF:DP:F1R2:F2R1:SB        0/1:1106,44:0.044:1150:531,27:571,17:575,531,23,21

I wander that the AF is higher then expected. Because the AF <= 0.038(44/1150). Could you tell me what's wrong with it? Or the  tenominator is lower than 1150? 

#### Steps to reproduce
My command lines is describled as below:
/software/GATK4/gatk-4.1.9.0/gatk --java-options "-XX:ParallelGCThreads=4 -Xmx20G -Djava.io.tmpdir=./tmp" Mutect2 -L chr17.bed --pcr-indel-model CONSERVATIVE -I samples-FFPE.recal.bam -tumor samples-FFPE -R ucsc.hg19.fasta --native-pair-hmm-threads 4 --min-base-quality-score 15 -germline-resource /Gatk_bundles/af-only-gnomad.raw.sites.hg19.vcf.gz --panel-of-normals  PoN.vcf.gz --f1r2-tar-gz chr17.f1r2.tar.gz -O samples-FFPE.chr17.raw.vcf

#### Expected behavior
So I used the gatk-4.1.3.0 for analysis the same date with the same input . In the INFO , we can find than all result is consistent except AF(0.038).
chr17   41244376        .       T       C       .       .       DP=1192;ECNT=1;MBQ=30,30;MFRL=242,275;MMQ=60,60;MPOS=37;POPAF=7.30;TLOD=59.10        GT:AD:AF:DP:F1R2:F2R1:SB        0/1:1106,44:0.038:1150:531,27:571,17:575,531,23,21

My command lines is describled as below:
/software/gatk/gatk-4.1.3.0/gatk --java-options "-XX:ParallelGCThreads=4 -Xmx20G -Djava.io.tmpdir=./tmp" Mutect2 -L chr17.bed --pcr-indel-model CONSERVATIVE -I samples-FFPE.recal.bam -tumor samples-FFPE -R ucsc.hg19.fasta --native-pair-hmm-threads 4 --min-base-quality-score 15 -germline-resource  af-only-gnomad.raw.sites.hg19.vcf.gz --panel-of-normals PoN.vcf.gz -O samples-FFPE.chr17.raw.vcf

### Description 
Hope for feedbacking me the reason causing the difference.
Thanks so much!!

----

**Comment by davidbenjamin** [comment]
AF is not calculated as AD/DP.  Rather, it is the mean posterior cell fraction conditioned on the variant existing.  The true AF is always unknown — the stochastic estimate AD/DP is merely the read fraction.

**Comment by jingchen-0927** [comment]
Dear David, thanks for your reply.
I could not get the idea of  "it is the mean posterior cell fraction conditioned on the variant existing" . Could you describe it in more detail ? Or could you offer me the explaination by web or document?  My email is jingchen_r@163.com. Thanks again.
