### ISSUE TITLE
Scatter/gather VariantEval (tool that doesnt create VCFs)?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#7030]
As I've posted in other issues, my makes a tool called VariantQC, which internally uses VariantEval to create various QC data about VCFs, and then turns that into an HTML report. Our data is becoming too large to practically process using VariantQC/VariantEval. We run most GATK tools scatter/gather on our cluster, with each tool executing over defined intervals. We have a final job that merges the resulting VCFs into one end file. That's great for VCF-creating tools, but does not work for VariantEval, since a) it aggregates data across the genome and therefore summaries per interval dont make sense, and b) it does produce an easily aggregatable product.

In #6973 I authored some changes to VariantEval, which include switching it to use MultiVariantWalkerGroupedOnStart, and also creating a separate VariantEvalEngine, which contains the guts of VariantEval.

I would like to do one more change, but @cmnbroad  suggested I run this proposal by others here first. The core idea is to make it possible to run VariantEval over a defined set of interval(s), and then make it save that state to disk. A separate step would read those files, combine, and then do the actual aggregation step. My use case is to enable this in VariantEvalEngine and then use that capability in our non-GATK VariantQC tool. I'd be happy to enable that in the VariantEval walker or not, depending on your thoughts.

Here is what happens now: VariantEval/VariantEvalEngine iterates the input VCF(s) and tracks values in StratificationManager. Once traversal is complete, onTraveralSuccess() will call finalizeReport(), which essentially takes the pre-aggregated information from StratificationManager and finalizes to make the output. Therefore if one could scatter jobs per interval, store the data from StratificationManager, and then restore/aggregate it, we could execute VariantEval/VariantQC scatter/gathered.

Here is the proposal:
 
- This assumes my PR to separate VariantEvalEngine has been merged.
- In StratificationManager, create a SerializedStratificationState class. This class is responsible for gathering the relevant state of StratificationManager and would get serialized to disk using Jackson.
- StratificationManager would have a saveToDisk(), and a new constructor that accepts the Path to a serialized SerializedStratificationState object. The implementation of saving/restoring would basically be private to StratificationManager.
- In VariantEvalEngine, make a public method for saveToDisk(), which saves StratificationManager and any potential other needed information to disk, serializing with Jackson.
- StratificationManager already has a concept of combineStrats() and Combiner. This needs to be fully implemented across the VariantEval classes; however, I propose to build off this to allow VariantEvaluators and VariantStratifiers to be combined. 
- If the above works, then it is possible to take N serialized SerializedStratificationState objects, restore and combine to create one StratificationManager that represents the data from across the genome.
- With the above steps, the core capabilities I need should be present. As far as how that's exposed in existing GATK tools, I dont have strong opinions. If you want this exposed in VariantEval, I'm happy to make an new argument for --save-state-to-disk-only, which would save the result of VariantEval's interation to a serialized file and skip the reports. To be useful, we need a companion walker to "MergeVariantEvals", which takes N serialized files, loads/aggregates and makes the actual report.

Does anyone have thoughts or concerns on this proposal? Is this something you think you'd accept as a PR to GATK/VariantEvalEngine/StratificationManager? Thanks in advance.

**Comment by cmnbroad** [comment]
We discussed this a bit today. I think we'd be open to taking these changes, including a standalone merge tool, assuming it can be done cleanly and with good test coverage for the new code. The existing implementation of `StratificationManager`, which is pretty much old school GATK3 code, relies heavily `Object` and type casts, etc.; I'd certainly encourage you to consider addressing the issues in https://github.com/broadinstitute/gatk/issues/5440 separately first.

**Comment by bbimber** [comment]
OK, once the VariantEvalEngine PR is wrapped up I will tackle this.
