### ISSUE TITLE
GenomicsDBImport java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7037]
### Version Information
GenomicsDBImport 4.1.9.0

### Summary
A user posted on the forum with an error from GenomicsDBImport. @nalinigans @mlathara Can you determine what is causing this java.lang.IndexOutOfBoundsException?

This request was created from a contribution made by vivekruhela on January 12, 2021 19:16 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/360076396392-No-Output-from-GenomicsDBImport](https://gatk.broadinstitute.org/hc/en-us/community/posts/360076396392-No-Output-from-GenomicsDBImport)

\--

Dear GATK Team,

I am using GATK version 4.1.9.0 for my WES data pipeline. In order to get accurate somatic call, I am trying to generate the Panel of Normal (PON) using GenomicsDBImport module of GATK. While using GenomicsDBImport for PON generation, I am not getting any output from my command. Here is the command I used to print the stack trace:

```
gatk GenomicsDBImport \\  
  
\-R /gatk\_bundle/hg19\_v0\_Homo\_sapiens\_assembly19.fasta \\  
  
\--variant normal1.vcf \\  
  
\--variant normal2.vcf \\  
  
\--variant normal3.vcf \\  
  
\--variant normal4.vcf \\  
  
\--variant normal5.vcf \\  
  
\--variant normal6.vcf \\  
  
\--variant normal7.vcf \\  
  
\--variant normal8.vcf \\  
  
\--variant normal9.vcf \\  
  
\--variant normal10.vcf \\  
  
\--variant normal11.vcf \\  
  
\--variant normal12.vcf \\  
  
\--variant normal13.vcf \\  
  
\--variant normal14.vcf \\  
  
\--variant normal15.vcf \\  
  
\--variant normal16.vcf \\  
  
\--variant normal17.vcf \\  
  
....  
  
\--variant normal80.vcf \\  
  
\--genomicsdb-workspace-path pon\_db \\  
  
\--tmp-dir /tmp1 \\  
  
\-L /gatk\_bundle/hglft\_genome\_3bc14\_d6f440.bed \\  
  
\--sequence-dictionary /gatk\_bundle/hg19\_v0\_Homo\_sapiens\_assembly19.dict \\  
  
\--reader-threads 15 \\  
  
\--java-options '-DGATK\_STACKTRACE\_ON\_USER\_EXCEPTION=true'
```

Here For interval list, I have downloaded the hg38 target interval from GATK resource bundle and converted into hg19 format using UCSC liftover utility. GenomicsDBImport is not reporting any error related to command but also not reporting any results. Here are the details from GenomicsDBImport log file:

```
17:16:16.069 INFO NativeLibraryLoader - Loading libgkl\_compression.so from jar:file:/home/akansha/vivekruhela/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar!/com/intel/gkl/native/libgkl\_compression.so  
  
Jan 12, 2021 5:16:16 PM shaded.cloud\_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine  
  
INFO: Failed to detect whether we are running on Google Compute Engine.  
  
17:16:16.329 INFO GenomicsDBImport - ------------------------------------------------------------  
  
17:16:16.329 INFO GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.1.9.0  
  
17:16:16.329 INFO GenomicsDBImport - For support and documentation go to [https://software.broadinstitute.org/gatk/](https://software.broadinstitute.org/gatk/)  
  
17:16:16.330 INFO GenomicsDBImport - Executing as akansha@sbilab on Linux v4.4.0-169-generic amd64  
  
17:16:16.330 INFO GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v1.8.0\_265-8u265-b01-0ubuntu2~16.04-b01  
  
17:16:16.330 INFO GenomicsDBImport - Start Date/Time: January 12, 2021 5:16:16 PM IST  
  
17:16:16.330 INFO GenomicsDBImport - ------------------------------------------------------------  
  
17:16:16.330 INFO GenomicsDBImport - ------------------------------------------------------------  
  
17:16:16.331 INFO GenomicsDBImport - HTSJDK Version: 2.23.0  
  
17:16:16.331 INFO GenomicsDBImport - Picard Version: 2.23.3  
  
17:16:16.331 INFO GenomicsDBImport - HTSJDK Defaults.COMPRESSION\_LEVEL : 2  
  
17:16:16.331 INFO GenomicsDBImport - HTSJDK Defaults.USE\_ASYNC\_IO\_READ\_FOR\_SAMTOOLS : false  
  
17:16:16.331 INFO GenomicsDBImport - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_SAMTOOLS : true  
  
17:16:16.331 INFO GenomicsDBImport - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_TRIBBLE : false  
  
17:16:16.331 INFO GenomicsDBImport - Deflater: IntelDeflater  
  
17:16:16.331 INFO GenomicsDBImport - Inflater: IntelInflater  
  
17:16:16.331 INFO GenomicsDBImport - GCS max retries/reopens: 20  
  
17:16:16.331 INFO GenomicsDBImport - Requester pays: disabled  
  
17:16:16.331 INFO GenomicsDBImport - Initializing engine  
  
17:16:20.910 INFO FeatureManager - Using codec BEDCodec to read file file:///home/akansha/vivekruhela/gatk\_bundle/hglft\_genome\_3bc14\_d6f440.bed  
  
17:16:20.921 INFO IntervalArgumentCollection - Processing 0 bp from intervals  
  
17:16:20.980 INFO GenomicsDBImport - Done initializing engine  
  
17:16:21.553 INFO GenomicsDBLibLoader - GenomicsDB native library version : 1.3.2-e18fa63  
  
17:16:21.554 INFO GenomicsDBImport - Vid Map JSON file will be written to /home/akansha/vivekruhela/pon\_db/vidmap.json  
  
17:16:21.554 INFO GenomicsDBImport - Callset Map JSON file will be written to /home/akansha/vivekruhela/pon\_db/callset.json  
  
17:16:21.554 INFO GenomicsDBImport - Complete VCF Header will be written to /home/akansha/vivekruhela/pon\_db/vcfheader.vcf  
  
17:16:21.554 INFO GenomicsDBImport - Importing to workspace - /home/akansha/vivekruhela/pon\_db  
  
17:16:21.554 WARN GenomicsDBImport - GenomicsDBImport cannot use multiple VCF reader threads for initialization when the number of intervals is greater than 1. Falling back to serial VCF reader initialization.  
  
17:16:21.554 INFO ProgressMeter - Starting traversal  
  
17:16:21.554 INFO ProgressMeter - Current Locus Elapsed Minutes Batches Processed Batches/Minute  
  
17:16:21.590 INFO GenomicsDBImport - Shutting down engine  
  
\[January 12, 2021 5:16:21 PM IST\] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 0.09 minutes.  
  
Runtime.totalMemory()=2761949184  
  
java.lang.IndexOutOfBoundsException: Index: 0  
  
at java.util.Collections$EmptyList.get(Collections.java:4456)  
  
at org.genomicsdb.model.GenomicsDBImportConfiguration$ImportConfiguration.getColumnPartitions(GenomicsDBImportConfiguration.java:2083)  
  
at org.genomicsdb.importer.GenomicsDBImporter.<init>(GenomicsDBImporter.java:203)  
  
at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.traverse(GenomicsDBImport.java:745)  
  
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)  
  
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)  
  
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)  
  
at org.broadinstitute.hellbender.Main.main(Main.java:289)
```
<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/92283'>Zendesk ticket #92283</a>)<br>gz#92283</i>

**Comment by mlathara** [comment]
Not completely sure, but this part of the log
```
17:16:20.921 INFO  IntervalArgumentCollection - Processing 0 bp from intervals
```
suggests that something is wrong with the bed file they are using (is it empty?) or perhaps the sequence dictionary. Looks like the tool thinks there are no intervals being imported (total size of intervals imported is 0)

**Comment by vivekruhela** [comment]
@mlathara : The bed file is not empty. Here is the screenshot of bed file:


![Screenshot_2021-01-14_18-15-35](https://user-images.githubusercontent.com/13174913/104592638-85827500-5694-11eb-955e-de6813bacec8.png)

The sequence dictionary is also not empty. Here is the screenshot of `.dict` file.

![Screenshot_2021-01-14_18-17-12](https://user-images.githubusercontent.com/13174913/104592784-bcf12180-5694-11eb-87f8-f92c8c09e863.png)

**Comment by droazen** [comment]
@vivekruhela The contig names in the sequence dictionary and in the bed file are not compatible. The bed file is using the chr1, chr2, etc. naming scheme, while the sequence dictionary uses 1, 2, etc. They appear to be from different references.

**Comment by vivekruhela** [comment]
As I have mentioned in the question itself, I downloaded the hg38 target intervals from gatk resources and then used UCSC liftover utility to convert it into hg19 based coordinates. Similarly, I have downloaded the hg19 fasta file and dict from the same gatk resources. So if I remove `chr` from chromosome name in the bed file, hopefully, that should work. (If you have any better ideas, please let me know.)

**Comment by vivekruhela** [comment]
I tried removing `chr` in the bed file, and I am getting the same error.

**Comment by mlathara** [comment]
Not sure this will work, but you could also try omitting the `--sequence-dictionary` argument and letting the tool construct one from the vcf headers. Also, when you removed the `chr` from the bed file does the tool output still indicate 0 bp from the intervals? Something like:

```
17:16:20.921 INFO  IntervalArgumentCollection - Processing 0 bp from intervals
```

**Comment by vivekruhela** [comment]
1. After removing `chr` the tool output still indicates 0 bp from the interval.
2. I tried omitting the `--sequence-dictionary` argument but the tool output still indicates 0 bp from the interval.
3. If I check my command by which I generated the vcf files. I used the following mutext2 (in tumor only mode) command for normal samples:
` $gatk Mutect2 --native-pair-hmm-threads 8 -R /refs/ucsc.hg19.fasta -I normal1.bam -tumor normal1 --disable-read-filter MateOnSameContigOrNoMappedMateReadFilter -O nornam1.vcf.gz`
The above command worked well for all 80 normals. Pleast let me know if I missed anything here to make vcf files compatible for GenomicDB module.

**Comment by mlathara** [comment]
Can you confirm that the contigs in the vcf headers have the same chromosome notation as your bed file? That is, they have the 'chr' prefix assuming you have the same prefix in your bed (or don't have the prefix if you're using the bed file without the prefix)

**Comment by vivekruhela** [comment]
The contigs in the vcf headers also contain `chr` and have same notwation as your bed file. Here is the screenshot of the vcf file. 
![Screenshot_2021-01-15_12-14-31](https://user-images.githubusercontent.com/13174913/104690967-65ea5b80-572b-11eb-81ab-92cc46535496.png)

**Comment by mlathara** [comment]
Just as a test, what happens if you replace the bed file with an actual interval? For instance, `-L chr1`

**Comment by vivekruhela** [comment]
As you suggested, I replace bed file with `-L chr1` and I am getting an error message shown below:

`A USER ERROR has occurred: Bad input: GenomicsDBImport does not support GVCFs with MNPs. MNP found at chr1:818499 in VCF /home/akansha/vivekruhela/PON/SRR1566827.vcf.gz`

Here is the screenshot:

![Screenshot_2021-01-15_12-52-59](https://user-images.githubusercontent.com/13174913/104694058-a1d3ef80-5730-11eb-8e04-0842e92a9e6e.png)

**Comment by mlathara** [comment]
@vivekruhela as the error there suggests, MNPs aren't completely supported. If you want to filter them out, you could try using something like `SelectVariants` with `--select-type-to-exclude` ([link ](https://gatk.broadinstitute.org/hc/en-us/articles/360051305531-SelectVariants#--select-type-to-exclude)) before ingesting using `GenomicsDBImport`.

As for your interval issue, it may helpful to refer to [this](https://gatk.broadinstitute.org/hc/en-us/articles/360035531852-Intervals-and-interval-lists). Your bed file should be formatted to have tab as a separator.

**Comment by vivekruhela** [comment]
@mlathara As suggested, I removed all MNPs from normal vcf files and changed the bed file formated and it worked. But it is not going beyond chromosome 1. Here are the stack trace:


    15:44:02.495 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/akansha/vivekruhela/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
    Jan 16, 2021 3:44:02 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
    INFO: Failed to detect whether we are running on Google Compute Engine.
    15:44:02.750 INFO  GenomicsDBImport - ------------------------------------------------------------
    15:44:02.750 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.1.9.0
    15:44:02.750 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
    15:44:02.750 INFO  GenomicsDBImport - Executing as akansha@sbilab on Linux v4.4.0-169-generic amd64
    15:44:02.751 INFO  GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_265-8u265-b01-0ubuntu2~16.04-b01
    15:44:02.751 INFO  GenomicsDBImport - Start Date/Time: January 16, 2021 3:44:02 PM IST
    15:44:02.751 INFO  GenomicsDBImport - ------------------------------------------------------------
    15:44:02.751 INFO  GenomicsDBImport - ------------------------------------------------------------
    15:44:02.751 INFO  GenomicsDBImport - HTSJDK Version: 2.23.0
    15:44:02.751 INFO  GenomicsDBImport - Picard Version: 2.23.3
    15:44:02.752 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2 
    15:44:02.752 INFO  GenomicsDBImport - HTSJDK     Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
    15:44:02.752 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
    15:44:02.752 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
    15:44:02.752 INFO  GenomicsDBImport - Deflater: IntelDeflater
    15:44:02.752 INFO  GenomicsDBImport - Inflater: IntelInflater
    15:44:02.752 INFO  GenomicsDBImport - GCS max retries/reopens: 20
    15:44:02.752 INFO  GenomicsDBImport - Requester pays: disabled
    15:44:02.752 INFO  GenomicsDBImport - Initializing engine
    15:44:07.262 INFO  FeatureManager - Using codec BEDCodec to read file file:///home/akansha/vivekruhela/gatk_bundle/hglift_genome1.bed
    15:44:07.274 INFO  IntervalArgumentCollection - Processing 2759468497 bp from intervals
    15:44:07.276 WARN  GenomicsDBImport - A large number of intervals were specified. Using more than 100 intervals in a single import is not recommended and can cause performance to suffer. If GVCF data only exists within those intervals, performance can be improved by aggregating intervals with the merge-input-intervals argument.
    15:44:07.307 INFO  GenomicsDBImport - Done initializing engine
    15:44:07.591 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.3.2-e18fa63
    15:44:07.592 INFO  GenomicsDBImport - Vid Map JSON file will be written to /home/akansha/vivekruhela/pon_db/vidmap.json
    15:44:07.592 INFO  GenomicsDBImport - Callset Map JSON file will be written to /home/akansha/vivekruhela/pon_db/callset.json
    15:44:07.592 INFO  GenomicsDBImport - Complete VCF Header will be written to /home/akansha/vivekruhela/pon_db/vcfheader.vcf
    15:44:07.592 INFO  GenomicsDBImport - Importing to workspace - /home/akansha/vivekruhela/pon_db
    15:44:07.592 WARN  GenomicsDBImport - GenomicsDBImport cannot use multiple VCF reader threads for initialization when the number of intervals is greater than 1. Falling back to serial VCF reader initialization.
    15:44:07.592 INFO  ProgressMeter - Starting traversal
    15:44:07.593 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Batches Processed   Batches/Minute
     15:44:14.158 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:44:23.557 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:44:36.913 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:45:08.280 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:45:28.258 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:46:06.473 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:48:43.534 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:49:00.423 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:49:49.381 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:50:27.647 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:51:04.867 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:51:12.352 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:52:51.733 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:56:45.519 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:56:59.794 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     15:59:40.804 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:02:37.245 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:02:46.778 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:03:16.229 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:03:22.458 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:04:03.836 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:04:10.565 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:04:46.237 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:04:53.564 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:05:11.645 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:08:46.742 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:09:31.595 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:10:23.393 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:12:33.856 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:13:07.008 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:13:59.401 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:15:59.411 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:16:52.551 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:18:50.226 INFO  GenomicsDBImport - Importing batch 1 with 80 samples 
     16:19:02.794 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:19:08.951 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:21:09.323 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:23:33.414 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:24:14.987 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:24:44.138 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:25:01.158 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:26:10.262 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:27:11.426 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:28:58.040 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:30:18.506 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:30:24.097 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:30:31.272 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:30:37.133 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:30:48.004 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:30:55.112 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:33:00.883 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:33:18.160 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:34:49.110 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:37:13.506 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:37:44.104 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:39:38.921 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:40:19.237 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:40:53.920 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:42:27.346 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:42:50.462 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:43:55.748 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:46:48.312 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:46:56.292 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:48:54.207 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:49:44.922 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:49:55.565 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:50:01.716 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:52:50.478 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:52:59.918 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:53:05.457 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:55:07.027 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:55:48.407 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:56:44.054 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:57:18.407 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:57:23.092 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     16:59:05.994 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
      17:00:15.068 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:02:16.125 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:02:27.021 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:03:08.466 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:03:51.314 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:04:11.652 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:05:06.334 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:06:27.887 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:08:00.480 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:09:02.408 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:09:18.392 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:10:24.819 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:10:30.493 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:10:36.487 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:10:44.518 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:10:50.014 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:11:05.544 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:12:11.749 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:12:27.018 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:12:37.849 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:14:05.487 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:14:13.264 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:14:17.666 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:14:22.417 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:14:58.524 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:15:15.527 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:15:21.443 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:15:34.087 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:16:17.453 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:16:24.495 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:16:31.053 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:16:42.692 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:17:07.867 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:17:23.997 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:17:29.915 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:17:35.266 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:17:44.299 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:17:49.894 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:17:58.917 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:18:05.526 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:18:10.954 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:18:17.177 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:18:22.600 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:18:30.825 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:18:36.178 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:18:41.657 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:18:48.155 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
      17:18:54.358 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:19:01.067 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
      17:19:08.337 INFO  GenomicsDBImport - Importing batch 1 with 80 samples
     17:19:09.814 INFO  ProgressMeter -          chr1:227419             95.0                     1              0.0
    17:19:09.814 INFO  GenomicsDBImport - Done importing batch 1/1
    17:19:09.815 INFO  ProgressMeter -          chr1:227419             95.0                     1              0.0
    17:19:09.815 INFO  ProgressMeter - Traversal complete. Processed 1 total batches in 95.0 minutes.
    17:19:09.815 INFO  GenomicsDBImport - Import completed!
    17:19:09.816 INFO  GenomicsDBImport - Shutting down engine
    [January 16, 2021 5:19:09 PM IST]     org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 95.12 minutes.
    Runtime.totalMemory()=13188464640

 And when I tried to create panel of normal using `CreateSomaticPanelOfNormals` and I am getting an error that `It isn't a regular file`: Here is the stack trace:

    17:19:12.932 INFO  CreateSomaticPanelOfNormals -     ------------------------------------------------------------
    17:19:12.933 INFO  CreateSomaticPanelOfNormals - The Genome Analysis Toolkit (GATK) v4.1.9.0
    17:19:12.933 INFO  CreateSomaticPanelOfNormals - For support and documentation go to https://software.broadinstitute.org/gatk/
    17:19:12.933 INFO  CreateSomaticPanelOfNormals - Executing as akansha@sbilab on Linux v4.4.0-169-generic amd64
    17:19:12.933 INFO  CreateSomaticPanelOfNormals - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_265-8u265-b01-0ubuntu2~16.04-b01
    17:19:12.933 INFO  CreateSomaticPanelOfNormals - Start Date/Time: January 16, 2021 5:19:12 PM IST
    17:19:12.934 INFO  CreateSomaticPanelOfNormals -  ------------------------------------------------------------
    17:19:12.934 INFO  CreateSomaticPanelOfNormals - ------------------------------------------------------------
    17:19:12.934 INFO  CreateSomaticPanelOfNormals - HTSJDK Version: 2.23.0
    17:19:12.934 INFO  CreateSomaticPanelOfNormals - Picard Version: 2.23.3
    17:19:12.934 INFO  CreateSomaticPanelOfNormals - HTSJDK Defaults.COMPRESSION_LEVEL : 2
    17:19:12.935 INFO  CreateSomaticPanelOfNormals - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
    17:19:12.935 INFO  CreateSomaticPanelOfNormals - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
    17:19:12.935 INFO  CreateSomaticPanelOfNormals - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
    17:19:12.935 INFO  CreateSomaticPanelOfNormals - Deflater: IntelDeflater
    17:19:12.935 INFO  CreateSomaticPanelOfNormals - Inflater: IntelInflater
    17:19:12.935 INFO  CreateSomaticPanelOfNormals - GCS max retries/reopens: 20
    17:19:12.935 INFO  CreateSomaticPanelOfNormals - Requester pays: disabled
    17:19:12.935 WARN  CreateSomaticPanelOfNormals - 

     [1m[31m   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

       Warning: CreateSomaticPanelOfNormals is a BETA tool and is not yet ready for use in production

       !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!![0m


    17:19:12.935 INFO  CreateSomaticPanelOfNormals - Initializing engine
    17:19:13.291 INFO  CreateSomaticPanelOfNormals - Shutting down engine
    [January 16, 2021 5:19:13 PM IST]     org.broadinstitute.hellbender.tools.walkers.mutect.CreateSomaticPanelOfNormals done.     Elapsed time: 0.01 minutes.
    Runtime.totalMemory()=2132803584
    ***********************************************************************

    A USER ERROR has occurred: Couldn't read file file:///home/akansha/vivekruhela/pon_db/.     Error was: It isn't a regular file

    ***********************************************************************
    Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
    Using GATK jar /home/akansha/vivekruhela/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar
    Running:
        java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/akansha/vivekruhela/gatk-4.1.9.0/gatk-package-4.1.9.0-local.jar CreateSomaticPanelOfNormals -R /home/akansha/vivekruhela/hg19/ucsc.hg19.fasta -V pon_db -O /home/akansha/vivekruhela/pon1.vcf.gz

**Comment by mlathara** [comment]
@vivekruhela The `GenomicsDBImport` tool doesn't accurately report back progress, so the fact that progress meter only refers to chr1 doesn't necessarily mean it only imported that. You should be able to check by listing the folders under the workspace directory and perhaps checking their sizes (something like `du -sh *` from the workspace folder may work).

As for `CreateSomaticPanelOfNormals` you need to add the `gendb://` schema to the genomicsdb workspace. In your case, something like:

```
gatk CreateSomaticPanelOfNormals -R /home/akansha/vivekruhela/hg19/ucsc.hg19.fasta -V gendb://pon_db -O /home/akansha/vivekruhela/pon1.vcf.gz
```
The example on the tool page shows this - look at step 3 [here](https://gatk.broadinstitute.org/hc/en-us/articles/360050816312-CreateSomaticPanelOfNormals-BETA-)

**Comment by vivekruhela** [comment]
@mlathara Thanks a lot for making my day. Although I already checked all the directories in the `pon_db` directory, it contained a directory for all chromosomes. Still, I was not sure whether it processed all chromosomes properly or not. That's why I ask. Thanks for the clarification that `genomeDBImport` does not accurately report back progress.

By adding `gendb://` in `CreateSometicPanelOfNormal`, it is working. Thanks for all your support. Now my all problem solved.

**Comment by droazen** [comment]
Closing as resolved
