### ISSUE TITLE
Picard MergeVcfs isnt the same as GATK3 CombineVariants

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#7038]
Hello,

There was at least one prior conversation about migrating or not migrating GATK3 CombineVariants to GATK4. My understanding is that there was a decision in GATK not to migrate CombineVariants, and instead push people to use Picard MergeVcfs. As you know, Picard MergeVcfs is somewhat similar; however, it doesnt merge genotypes. That is a pretty big difference in function. 

CombineVariants is one of the few GATK3 tools my lab is still using. I'd like to move us off GATK3 in the coming months. Given GATK has already decided not to migrate it, I would first like to propose that we could port and take it over in my lab's DISCVRseq project (https://github.com/bimberlab/discvrseq). I'm happy to give attribution to GATK, etc. I would likely rename it MergeVcfsAndGenotypes (this is more intuitive to me), but I would otherwise not change functionality much. I'd prefer to do this instead of porting to GATK4 because porting to GATK is going to throw up a lot more obstacles and probably require that I modernize/update a good amount of that tool's code. I appreciate why this is required, but it takes a lot more work from us.

If you did not like this, I'm open to considering porting to GATK4. In my initial review, it looked like CombineVariants was fairly self-contained and that most of the accessory code (merging genotypes is the most complex thing) was already migrated to GATK4. Some of you may have already done a more thorough review of it. 

What do you think?

**Comment by cmnbroad** [comment]
@droazen Thoughts on this ?

**Comment by cmnbroad** [comment]
@bbimber We discussed this internally today. The concerns about porting this tool go back pretty far in the GATK4 timeline (see https://github.com/broadinstitute/gatk/issues/17). AFAIK there isn't reason you can't port it and use it in your own toolset though.

**Comment by bbimber** [comment]
@cmnbroad OK, thanks for the reply. I will plan to port to DISCVRseq, making some minor changes but leaving a lot as-is. I'll rename it MergeVcfsAndGenotypes but include mention of GATK3 and CombineVariants in my description of it.

**Comment by bbimber** [comment]
In case anyone comes across this issue, we ported GATK3 CombineVariants under the name MergeVariantsAndGenotypes (it's basically the same tool), here:

https://bimberlab.github.io/DISCVRSeq/toolDoc/com_github_discvrseq_walkers_MergeVcfsAndGenotypes.html

**Comment by xiucz** [comment]
It is really a great job!   THANK YOU @bbimber . I have been waiting for the porting for many years! 😭

**Comment by bbimber** [comment]
Glad it's useful.

**Comment by skchronicles** [comment]
@bbimber I just stumbled across this issue, and I have a quick question. How does this differ from GATK3 CombineVariants? Is it the same thing functionally? Does it produce the exact same output?

Thank you for the clarification,
@skchronicles

**Comment by bbimber** [comment]
@skchronicles, I have not exhaustively tested every possible scenario and fringe case, but in theory it should be effectively the same as GATK3 combine variants. Happy to answer any questions if you hit issues.
