### ISSUE TITLE
an error of filtered SNP

### ISSUE THREAD

**Issue by K-zhangfengwei** [broadinstitute/gatk#7042]
I want to filter SNP, but encountered this error. Can anyone help me resolve this error.

thanks .
zhang.

`##### ERROR ------------------------------------------------------------------------------------------
##### ERROR ------------------------------------------------------------------------------------------
`

**Comment by droazen** [comment]
@K-zhangfengwei It looks like you're running GATK 3.x. This repository is for GATK 4.x and above -- can you try re-running with the latest release?
