### ISSUE TITLE
sync picard before alpha

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#705]
all picard tools should be synched before we go to alpha release. We are now at some version and need to sync to the latest available by the alpha release.

**Comment by droazen** [comment]
We should do this ONCE and never again (when the final switchover to the hellbender implementations happens), rather than doing this for alpha.

**Comment by akiezun** [comment]
agreed. it'll be a version after htsjdk moves over to java8.

**Comment by akiezun** [comment]
closing this in favor of #1210
