### ISSUE TITLE
Latest Funcotator DataSources Gencode hg19 has unexpected order for transcript segments

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#7051]
The 1.7 release of the data sources has a lifted over hg19 version of Gencode.

In this version contrary to other releases, the individual elements of each transcript seem to be represented in numerical order, rather than the order in which they appear in the transcript at transcription time.  For `+` strand transcripts, this doesn't matter, but for `-` strand transcripts, the ordering of the exons/CDS regions in the gencode gtf file is reversed to what is expected.  The result is that the coding sequence, protein prediction, and other annotations are incorrect.

One user has already run into this issue: https://gatk.broadinstitute.org/hc/en-us/community/posts/360076207992--Repost-Wrong-annotation-with-Funcotator-1-7

One of two fixes is required:

1. Update the code to always sort the transcript elements by how they appear in the transcribed sequence
2. When generating the Gencode data, always sort the transcript elements by their transcribed order.

We should do both and later roll back the sorting to optimize for speed.

**Comment by GATKSupportTeam** [comment]
<i>(related to <a href='https://broadinstitute.zendesk.com/agent/tickets/87559'>Zendesk ticket #87559</a>)</i>
