### ISSUE TITLE
How to improve the running speed of GATK4? How to set the number of threads for BaseRecalibrator, ApplyBQSR and Mutect2?

### ISSUE THREAD

**Issue by Ning-310** [broadinstitute/gatk#7052]
How to improve the running speed of GATK4? How to set the number of threads for BaseRecalibrator, ApplyBQSR and Mutect2?

**Comment by AlijahArcher** [comment]
Have you read through official docs on the GATK website?  https://gatk.broadinstitute.org/hc/en-us/articles/360035889611-How-can-I-make-GATK-tools-run-faster-

My team has had great success with the scatter-gather parallelism approach (https://gatk.broadinstitute.org/hc/en-us/articles/360035532012)

**Comment by fleharty** [comment]
@Ning-310 
The vast majority of our tools are single threaded since GATK 4, and we instead use a scatter-gather framework for parallelism.

@AlijahArcher thank you for pointing out the resources above.
