### ISSUE TITLE
Investigate errors seen in the DRAGEN-GATK GVCF outputs

### ISSUE THREAD

**Issue by jamesemery** [broadinstitute/gatk#7108]
There are reports that the GT fields in the DRAGEN-GATK gvcf mode outputs have some issues that are causing problems for some projects looking to use those outputs. Evidently among them are reports that some sites are reporting negative GQ fields for some variants and there are also reports the the PL arrays might not always be getting reported for every variant at some sites. We should look into this behavior and get a sense as to why this might be happening and fix these bugs.

**Comment by vruano** [comment]
Need a dataset to reproduce the issue and fix it.

**Comment by ldgauthier** [comment]
Addressed by #7120 and #7148
