### ISSUE TITLE
IlluminaBasecallsToFastq. Documentation request

### ISSUE THREAD

**Issue by genomika-2020** [broadinstitute/gatk#7110]
## Documentation request
   

### Tool 
IlluminaBasecallsToFastq  

### gatk version
 4.1.9.0  

### Description
 Hi,
The IlluminaBasecallsToFastq tool is great, but its documentation is quite misleading. In my opinion the following things should be clarified:

1.  It would be nice to know just from the beginning that the ` ExtractIlluminaBarcodes` tool must be used to prepare  `_barcode.txt` files (if these files are not present in the BaseCalls directory and, at least in my case, these files were not present after the Illumina run)  
2.   That the BaseCall directory must be inside the Illumina output directory - as some other files, from outside this folder are used by the tool  
3.   This description is not true:

   ```
   MULTIPLEX_PARAMS file contains the list of sample barcodes used to sort template, barcode, and index reads.
  It is essentially the same as the BARCODE_FILE used in the ExtractIlluminaBarcodes tool.
   ```
  because these tools require different columns, and column names. The same file cannot be used.
    ExtractIlluminaBarcodes:
    ```
   The BARCODE_FILE contains multiple fields including
 'barcode_sequence' (or 'barcode_sequence_1'), 'barcode_sequence_2' (optional), 'barcode_name', and 'library_name'.
    ```

IlluminaBasecallsToFastq:  File with the following header line worked in my case:
  `OUTPUT_PREFIX   BARCODE_1   BARCODE_2`   

Best,
Kasia

**Comment by droazen** [comment]
@genomika-2020 Could you please re-file this request in the Picard repo: https://github.com/broadinstitute/picard ? `IlluminaBasecallsToFastq` is a Picard tool. Thanks!
