### ISSUE TITLE
SelectVariants cannot filter variant types for GVCFs (VariantTypesVariantFilter)

### ISSUE THREAD

**Issue by michaelgatzen** [broadinstitute/gatk#7111]
When running `gatk SelectVariants -V ... --select-type SNP -O ...` on GVCFs the output is empty, since every GVCF VariantContext is assigned the type `MIXED` in HTSJDK, due to its symbolic alternate allele (e.g. `<NON_REF>,A`).

**Comment by michaelgatzen** [comment]
Is this expected? If not, how should we address that? I could think of copying the type determination code from HTSJDK into VariantTypesVariantFilter and accounting for this case, which would fix the problem for this filter. However I could also imagine that always assigning MIXED to every GVCF variant isn't very helpful in other situations, but making a change in HTSJDK's VariantContext would probably have massive downstream effects.

Also referenced here: https://gatk.broadinstitute.org/hc/en-us/community/posts/360071943332-SelectVariants-error

**Comment by droazen** [comment]
I agree that this behavior seems non-helpful -- perhaps `SelectVariants` needs a special GVCF-aware mode. I'd consult with @ldgauthier to see what she thinks would be best here.

**Comment by kachulis** [comment]
I think something somewhat similar is happening in #7100, related to the treatment of spanning deletions in htsjdk (discussed a few year ago here: samtools/htsjdk#806).  So if there is interest is improving some of the variant typing in htsjdk might be useful to try to resurrect that conversation.

**Comment by droazen** [comment]
@ldgauthier Would you mind weighing in here on what you think the `SelectVariants` behavior with GVCFs should be? Should we add in a special mode that is aware of the NON_REF allele?

**Comment by droazen** [comment]
Another likely related ticket: https://github.com/broadinstitute/gatk/issues/7111

**Comment by kachulis** [comment]
Fixed by #7193

**Comment by kachulis** [comment]
apparently #7193 hasn't been merged yet...
