### ISSUE TITLE
gCNV cohort model for WGS

### ISSUE THREAD

**Issue by PedroRaposo** [broadinstitute/gatk#7116]
Hello,

I was wondering if there is a generic WGS cohort model to be used for the gCNV detection already built.
This is because I do not have a cohort myself, only my WGS case samples.

I believe the data from the [tutorial](https://gatk.broadinstitute.org/hc/en-us/articles/360035531152) provided was based of the 1000 Genome Project [files](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/phase3/integrated_sv_map) but I am not aware of the existence of the files to be used directly in DetermineGermlineContigPloidy and GermlineCNVCaller as model.

Thank you

**Comment by mwalker174** [comment]
There is one available as a part of GATK-SV. These built using high-coverage 1000GP samples recently generated at NYGC. You can find the contig ploidy model and gcnv model here:

https://github.com/broadinstitute/gatk-sv/blob/master/input_values/ref_panel_1kg_v2.json

and preprocessed intervals file here:

https://github.com/broadinstitute/gatk-sv/blob/master/input_values/resources_hg38.json#L39
