### ISSUE TITLE
VariantFiltration BCF input and output

### ISSUE THREAD

**Issue by fgvieira** [broadinstitute/gatk#7132]
### Tool(s) or class(es) involved
`GATK VariantFiltration`

### Description
As of GATK v4.2.0.0, `VariantFiltration` only accepts `.vcf` or `.vcf.gz` files as input or output. Would it be possible to also support `.bcf` files?

Thanks,

**Comment by lbergelson** [comment]
H @fgvieira there are some problems with our implementation of bcf that make it inadvisable to use it right now in GATK.  We would like to fix it, and there has been substantial recent interest in using bcf, but we don't have a timeline fo when it will be available right now.

**Comment by lbergelson** [comment]
@fgvieira We actually now have someone working on bcf2 support in htsjdk, so hopefully this will be possible in the not too distant future.

**Comment by fgvieira** [comment]
That'd be great!
thanks,
