### ISSUE TITLE
ApplyBQSRSpark. java.io.IOException: Bad file descriptor

### ISSUE THREAD

**Issue by nickhir** [broadinstitute/gatk#7139]
### Affected tool(s) or class(es)
ApplyBQSRSpark

### Affected version(s)
gatk-4.1.9.0

### Description 
After roughly 1h of running ApplyBQSRSpark on my WGS BAM, it throws the error `java.io.IOException: Bad file descriptor`.
I then used `samtools quickcheck` to validate the integrity of my BAM file and everything seems fine. The BAM file is coordinate sorted and the duplicates are marked. The size of the BAM file is 142GB

#### Steps to reproduce
This is the command I used:

```bash
 java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar gatk-package-4.1.9.0-local.jar ApplyBQSRSpark -R ref-genome.fa -I buffy_coat.sorted.markdup.bam --spark-master local[45] --tmp-dirtmp --bqsr-recal-file buffy_coat_recal_bqsr.table -O buffy_coat.recal.bam
```

Any help is much appreciated!

Cheers

**Comment by nickhir** [comment]
*Update*
I restarted the process and now everything works as intended. I have no Idea what went wrong.

**Comment by lbergelson** [comment]
@nickhir Sounds like some temporary filesystem glitch.  Glad it's working now.
