### ISSUE TITLE
Investigate out of memory error in CalibrateDragstrModel

### ISSUE THREAD

**Issue by vruano** [broadinstitute/gatk#7189]
## Bug Report

Originally reported by @ldgauthier via slack.

### Affected tool(s) or class(es)
CalibrateDragstrModel

### Affected version(s)
- [X ] Latest public release version [4.2.0.0]

### Description 
An out-of-memory exception when running the aforementioned tool in at least one of many samples. Location where the error occur does not seem to be always the same but it was fixable by increasing memory over 15Gb.

#### Steps to reproduce

Since I'm not sure the data is public I won't disclose its location nor ID in this issue. Let's call it the "SAMPLE" in "SAMPLE.cram":

```
gatk --java-options "-Dsamjdk.reference_fasta=Homo_sapiens_assembly38.fasta -Xmx2g -DGATK_STACKTRACE_ON_USER_EXCEPTION=true" \
  CalibrateDragstrModel \
    -R Homo_sapiens_assembly38.fasta \
    -I SAMPLE.cram \
    -str Homo_sapiens_assembly38.str \
    -O SAMPLE.final.cram.dragstr \
    --parallel \
    --verbosity DEBUG
```

```Homo_sapiens_assembly38.str``` depends only on the reference and ca be composed using this:

```
gatk ComposeSTRFile -R Homo_sapiens_assembly38.fasta -O Homo_sapiens_assembly38.str
```

#### Expected behavior
Completes without issues.

#### Actual behavior
a Java Out-of-Memory error is throw and the execution finished without results.

**Comment by cmnbroad** [comment]
@vruano @ldgauthier Running this tool in parallel on a CRAM will consume large amounts of memory, since the code necessarily uses a separate reader per thread (see comments [here](https://github.com/broadinstitute/gatk/pull/7063#discussion_r568162015) in the PR where CRAM was enabled). If you want to run in parallel, I'd try reducing the number of threads in the thread pool.

**Comment by vruano** [comment]
@cmnbroad is correct, reducing parallelism from cram in a test run from 8 to 4 threads allowed the run to progress normally. 
Since there is a task to remove this adhoc parallelism for a spark alternative I guess that is the way to go from this point on. #6876

However that actually would not solve the mem consumption issues as spark to work effectively would require several java-vm one per thread and so the memory would need to be scaled up if you really want to run in parallel, is that right?

**Comment by vruano** [comment]
Also ironically this tool does not need to look into the read sequences nor the reference, only the mapping information matters so is a bit frustrating that you paid the price of the whole sandwich when you only want the slice of salami.

**Comment by vruano** [comment]
A fix for this issue has already been merged.
