### ISSUE TITLE
unparsable vcf record with allele +

### ISSUE THREAD

**Issue by kuangtianhui** [broadinstitute/gatk#7214]
The Genome Analysis Toolkit (GATK) v4.2.0.0

When I run gatk IndexFeatureFile --input ./merged_flt_c1.imputed.vcf, I got an error as below:

A USER ERROR has occurred: Error while trying to create index for ./merged_flt_c1.imputed.vcf. Error was: htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 343338: unparsable vcf record with allele - 

I run this "gatk IndexFeatureFile" with different vcf fies, it return different error such as,
A USER ERROR has occurred: Error while trying to create index for ./merged_flt_c3.imputed.vcf. Error was: htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 2124615: unparsable vcf record with allele +
 
So, How could I solve it?
thank y
![1618915844](https://user-images.githubusercontent.com/67847482/115384785-027c3800-a20a-11eb-93d2-05431fe258b5.png)

**Comment by ldgauthier** [comment]
This is a user error, not a GATK bug. For questions about tool usage, please use the GATK forum: https://gatk.broadinstitute.org/hc/en-us/community/topics
