### ISSUE TITLE
contig-ploidy priors

### ISSUE THREAD

**Issue by kghimire09** [broadinstitute/gatk#7216]
Hello, 
I am using DetermineGermlineContigPloidy to call copy number variants. I have a cohort of samples that I am using to generate a model. For the cohort more -contig-ploidy-priors is required argument. How do I generate this file for my data?
Any suggestions?

**Comment by ldgauthier** [comment]
Github is for error reports.  For questions about tool usage, please use the GATK forum: https://gatk.broadinstitute.org/hc/en-us/community/topics
