### ISSUE TITLE
GenomicsDBImport crash without error reported in log file

### ISSUE THREAD

**Issue by Han-Cao** [broadinstitute/gatk#7218]
GenomicsDBImport
Latest public release version [4.2.0.0]

I am running  GenomicsDBImport on 5X WGS of ~1000 human samples, which is parallelized for each chromosome with batch size = 400. The code I use is as following:

<pre>gatk --java-options "-Xmx80G -Xms80G" GenomicsDBImport \
--genomicsdb-workspace-path "${outpath}/chr${region}" \
-L $region \
--sample-name-map $sample_map \
-R /scratch/PI/boip/Reference/Human_genome/GRCh37/hs37d5.fa \
--batch-size 400 \
--reader-threads 5
</pre>

It seems that GenomicsDBImport crash after finishing 1 batch for large chromosomes. For example, here I simultaneously run for chr1-12 (not finished yet). For chr5-12, file size of 1 batch is less than 40GB and they successfully finished import batch 1 and running for batch 2 or 3. Thus, the file size for chr5-12 are 59GB now. However, for chr1-4, they just crash in batch 1 for very long time without any error. I have check the memory usage and there is still >35GB free memory for the compute node of each chromosome. Please see the followings for detail:

File size for all chromosomes, the GenomicsDB for chr1-4 is smaller:
<pre>[hcaoad@login-0 GenomicsDB]> du -h --max-depth=1
59G     ./chr10
59G     ./chr6
50G     ./chr2
59G     ./chr12
59G     ./chr9
59G     ./chr5
59G     ./chr7
48G     ./chr1
59G     ./chr11
59G     ./chr8
40G     ./chr4
41G     ./chr3
647G    .
</pre>

Files in GenomicsDB of chr1 batch 1. As you can see, no update for the database since Apr 20 13:34, while current time is Apr 21.
<pre>[hcaoad@login-0 .__6f46d0f3-86b3-4e38-92be-9a912291df0c139544093255424_1618555702611]> pwd
/home/hcaoad/scratch/Han/WGS/HK_WGS_5X/GenomicsDB/chr1/1$1$249250621/.__6f46d0f3-86b3-4e38-92be-9a912291df0c139544093255424_1618555702611
[hcaoad@login-0 .__6f46d0f3-86b3-4e38-92be-9a912291df0c139544093255424_1618555702611]> date
Wed Apr 21 11:09:46 HKT 2021
[hcaoad@login-0 .__6f46d0f3-86b3-4e38-92be-9a912291df0c139544093255424_1618555702611]> ll -h
total 48G
-rwx------ 1 hcaoad boip 260M Apr 20 13:34 AD.tdb
-rwx------ 1 hcaoad boip 203M Apr 20 13:34 AD_var.tdb
-rwx------ 1 hcaoad boip 304M Apr 20 13:34 ALT.tdb
-rwx------ 1 hcaoad boip 146M Apr 20 13:34 ALT_var.tdb
-rwx------ 1 hcaoad boip 353M Apr 20 13:34 BaseQRankSum.tdb
-rwx------ 1 hcaoad boip 7.3G Apr 20 13:34 __coords.tdb
-rwx------ 1 hcaoad boip 132M Apr 20 13:34 DB.tdb
-rwx------ 1 hcaoad boip 3.4G Apr 20 13:34 DP_FORMAT.tdb
-rwx------ 1 hcaoad boip 295M Apr 20 13:34 DP.tdb
-rwx------ 1 hcaoad boip 8.1G Apr 20 13:34 END.tdb
-rwx------ 1 hcaoad boip 223M Apr 20 13:34 ExcessHet.tdb
-rwx------ 1 hcaoad boip 158M Apr 20 13:34 FILTER.tdb
-rwx------ 1 hcaoad boip    0 Apr 20 13:34 FILTER_var.tdb
-rwx------ 1 hcaoad boip 3.7G Apr 20 13:34 GQ.tdb
-rwx------ 1 hcaoad boip 253M Apr 20 13:34 GT.tdb
-rwx------ 1 hcaoad boip 277M Apr 20 13:34 GT_var.tdb
-rwx------ 1 hcaoad boip 250M Apr 20 13:34 ID.tdb
-rwx------ 1 hcaoad boip  47M Apr 20 13:34 ID_var.tdb
-rwx------ 1 hcaoad boip 158M Apr 20 13:34 InbreedingCoeff.tdb
-rwx------ 1 hcaoad boip 3.3G Apr 20 13:34 MIN_DP.tdb
-rwx------ 1 hcaoad boip 260M Apr 20 13:34 MLEAC.tdb
-rwx------ 1 hcaoad boip  76M Apr 20 13:34 MLEAC_var.tdb
-rwx------ 1 hcaoad boip 260M Apr 20 13:34 MLEAF.tdb
-rwx------ 1 hcaoad boip  80M Apr 20 13:34 MLEAF_var.tdb
-rwx------ 1 hcaoad boip 236M Apr 20 13:34 MQRankSum.tdb
-rwx------ 1 hcaoad boip 204M Apr 20 13:34 PGT.tdb
-rwx------ 1 hcaoad boip 6.8M Apr 20 13:34 PGT_var.tdb
-rwx------ 1 hcaoad boip 208M Apr 20 13:34 PID.tdb
-rwx------ 1 hcaoad boip  15M Apr 20 13:34 PID_var.tdb
-rwx------ 1 hcaoad boip 315M Apr 20 13:34 PL.tdb
-rwx------ 1 hcaoad boip  14G Apr 20 13:34 PL_var.tdb
-rwx------ 1 hcaoad boip 173M Apr 20 13:34 PS.tdb
-rwx------ 1 hcaoad boip 496M Apr 20 13:34 QUAL.tdb
-rwx------ 1 hcaoad boip 412M Apr 20 13:34 RAW_MQandDP.tdb
-rwx------ 1 hcaoad boip 358M Apr 20 13:34 ReadPosRankSum.tdb
-rwx------ 1 hcaoad boip 254M Apr 20 13:34 REF.tdb
-rwx------ 1 hcaoad boip 1.5G Apr 20 13:34 REF_var.tdb
-rwx------ 1 hcaoad boip 278M Apr 20 13:34 Samples.tdb
-rwx------ 1 hcaoad boip 256M Apr 20 13:34 Samples_var.tdb
-rwx------ 1 hcaoad boip 510M Apr 20 13:34 SB.tdb
</pre>
Log file for chr1, no error reported:
<pre>Using GATK jar /home/hcaoad/miniconda2/share/gatk4-4.2.0.0-0/gatk-package-4.2.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx80G -Xms80G -jar /home/hcaoad/miniconda2/share/gatk4-4.2.0.0-0/gatk-package-4.2.0.0-local.jar GenomicsDBImport --genomicsdb-workspace-path /scratch/PI/boip/Han/WGS/HK_WGS_5X/GenomicsDB//chr1 -L 1 --sample-name-map input/sample.map -R /scratch/PI/boip/Reference/Human_genome/GRCh37/hs37d5.fa --batch-size 400 --reader-threads 5
14:48:08.923 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/home/hcaoad/miniconda2/share/gatk4-4.2.0.0-0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Apr 16, 2021 2:48:09 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
14:48:09.080 INFO  GenomicsDBImport - ------------------------------------------------------------
14:48:09.081 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.2.0.0
14:48:09.081 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
14:48:09.081 INFO  GenomicsDBImport - Executing as hcaoad@hhnode-ib-46 on Linux v3.10.0-1062.el7.x86_64 amd64
14:48:09.081 INFO  GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_152-release-1056-b12
14:48:09.081 INFO  GenomicsDBImport - Start Date/Time: April 16, 2021 2:48:08 PM HKT
14:48:09.081 INFO  GenomicsDBImport - ------------------------------------------------------------
14:48:09.081 INFO  GenomicsDBImport - ------------------------------------------------------------
14:48:09.081 INFO  GenomicsDBImport - HTSJDK Version: 2.24.0
14:48:09.081 INFO  GenomicsDBImport - Picard Version: 2.25.0
14:48:09.081 INFO  GenomicsDBImport - Built for Spark Version: 2.4.5
14:48:09.081 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2
14:48:09.081 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
14:48:09.081 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
14:48:09.082 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
14:48:09.082 INFO  GenomicsDBImport - Deflater: IntelDeflater
14:48:09.082 INFO  GenomicsDBImport - Inflater: IntelInflater
14:48:09.082 INFO  GenomicsDBImport - GCS max retries/reopens: 20
14:48:09.082 INFO  GenomicsDBImport - Requester pays: disabled
14:48:09.082 INFO  GenomicsDBImport - Initializing engine
14:48:09.524 INFO  IntervalArgumentCollection - Processing 249250621 bp from intervals
14:48:09.551 INFO  GenomicsDBImport - Done initializing engine
14:48:09.781 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.3.2-e18fa63
14:48:09.782 INFO  GenomicsDBImport - Vid Map JSON file will be written to /scratch/PI/boip/Han/WGS/HK_WGS_5X/GenomicsDB/chr1/vidmap.json
14:48:09.782 INFO  GenomicsDBImport - Callset Map JSON file will be written to /scratch/PI/boip/Han/WGS/HK_WGS_5X/GenomicsDB/chr1/callset.json
14:48:09.782 INFO  GenomicsDBImport - Complete VCF Header will be written to /scratch/PI/boip/Han/WGS/HK_WGS_5X/GenomicsDB/chr1/vcfheader.vcf
14:48:09.782 INFO  GenomicsDBImport - Importing to workspace - /scratch/PI/boip/Han/WGS/HK_WGS_5X/GenomicsDB/chr1
14:48:09.783 INFO  ProgressMeter - Starting traversal
14:48:09.783 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Batches Processed   Batches/Minute
14:48:09.935 INFO  GenomicsDBImport - Starting batch input file preload
14:48:21.686 INFO  GenomicsDBImport - Finished batch preload
14:48:21.686 INFO  GenomicsDBImport - Importing batch 1 with 400 samples
</pre>

I am now trying to solve this by reducing batch size, will update once it finished for batch1.

**Comment by gbrandt6** [comment]
@Han-Cao, are you the same user who posted on the GATK Forum as well? https://gatk.broadinstitute.org/hc/en-us/community/posts/360077628671-GenomicsDBImport-output-unmapped-in-ProgressMeter-and-running-very-slow-with-WGS-data-of-large-sample-size
If so, has this issue then been resolved?

**Comment by Han-Cao** [comment]
@gbrandt6 Yes, I am the same user. I have reduced the batch size and it can correctly run. But it runs slower compared to larger batch size.

**Comment by droazen** [comment]
Closing as resolved
