### ISSUE TITLE
Regression in GenomicsDBImport  progressMeter

### ISSUE THREAD

**Issue by TedBrookings** [broadinstitute/gatk#7222]
### Affected tool(s) or class(es)
_GenomicsDBImport_

### Affected version(s)
- 4.2.0.0
- after git revision 2b949f0dda49f495ce8fc7e3b8528cbc534e4819

### Description 
_Progress meter does not accurately describe genomic locus being processed._

#### Steps to reproduce
_Run GenomicsDBImport (e.g. using -L to subset to a specific genomic locus)_

#### Expected behavior
_Progress meter should display the locus that is currently being processed during the import_

#### Actual behavior
_Progress meter displays unmaped locus. See [this forum post](https://gatk.broadinstitute.org/hc/en-us/community/posts/360077628671-GenomicsDBImport-output-unmapped-in-ProgressMeter-and-running-very-slow-with-WGS-data-of-large-sample-size) for an example_

**Comment by TedBrookings** [comment]
@mlathara If you could take a look at this, it would be helpful. It looks like you changed
`progressMeter.update(intervals.get(0))` in logMessageOnBatchCompletion()  to `progressMeter.update(null)`
Presumably there was a problem with intervals being empty?

**Comment by mlathara** [comment]
Hi,

So, the progressMeter for GenomicsDBImport never accurately showed the locus being processed. Previously, the progressMeter would just always show the first interval being imported. As you imply, I changed to null to support some workflows where intervals may be empty.

All of which to say, this isn't a regression but a known issue. The bulk of the lifting by the import tool is done in native code so bubbling that up isn't straight forward.

**Comment by TedBrookings** [comment]
@droazen I think this is out of my depth now. From my perspective the user's issue is addressed (there isn't a bug in processing).

**Comment by droazen** [comment]
@mlathara I think we should either:

- Keep track of the "furthest" locus processed so far across all threads, and output that in progress meter

- Or, if that's too difficult, it's probably best to suppress the progress meter output completely, and just output the current batch numbers

**Comment by mlathara** [comment]
@droazen I think suppressing progress meter is the way to go. It won't be particularly easy to surface the locus information, and I also think that would be misleading. 

For instance, say a user is importing 3 intervals (for simplicity, chr 1, 2 and 3) in parallel. The progress meter will immediately start showing that the import process is at chr3 suggesting that it is roughly 2/3 of the way through. And of course it'll seem to be going a lot slower after that point. Could also get weird (and this is likely) if the furthest interval completes before the others.

**Comment by droazen** [comment]
@mlathara You've convinced me -- let's just get rid of the progress meter output then :) But as a compromise, when we print the current batch number, we should ideally give a bit more information, such as the sample names in the current batch. Since this is only printed once per batch, it shouldn't be too spammy.
