### ISSUE TITLE
WARNING: BAM index and WARN  IndexUtils - Feature file

### ISSUE THREAD

**Issue by kuangtianhui** [broadinstitute/gatk#7228]
When I run gatk BaseRecalibrator, I got two WARNING. The detail was shown as below. I want to know what causes this situation and how to solve this warning? Thank you very much!
WARNING 1:
WARNING: BAM index file /home/kth/Mydata/Bam/7-99.sorted.markdup.bai is older than BAM /home/wangh/kth/Mydata/NAM/NAM_7/Bam/7-99.sorted.markdup.bam
03:30:10.633 INFO  FeatureManager - Using codec VCFCodec to read file file:///home/wangh/kth/Mydata/NAM/ref_geno/hmp321_282_agpv4/hmp321_agpv4_chr1.vcf.gz
03:30:10.683 INFO  FeatureManager - Using codec VCFCodec to read file file:///home/wangh/kth/Mydata/ref_geno/hmp321_282_agpv4/hmp321_agpv4_chr2.vcf.gz
03:30:10.702 INFO  FeatureManager - Using codec VCFCodec to read file file:///home/wangh/kth/Mydata/ref_geno/hmp321_282_agpv4/hmp321_agpv4_chr3.vcf.gz
...
FeatureManager - Using codec VCFCodec to read file file:///home/kth/Mydata/ref_geno/hmp321_282_agpv4/hmp321_agpv4_chr10.vcf.gz
WARNING 2:
WARN  IndexUtils - Feature file "file:///home/kth/Mydata/ref_geno/hmp321_282_agpv4/hmp321_agpv4_chr1.vcf.gz" appears to contain no sequence dictionary. Attempting to retrieve a sequence dictionary from the associated index file
03:30:10.877 WARN  IndexUtils - Feature file "file:///home/kth/Mydata/ref_geno/hmp321_282_agpv4/hmp321_agpv4_chr2.vcf.gz" appears to contain no sequence dictionary. Attempting to retrieve a sequence dictionary from the associated index file
03:30:10.891 WARN  IndexUtils - Feature file "file:///home/kth/Mydata/ref_geno/hmp321_282_agpv4/hmp321_agpv4_chr3.vcf.gz" appears to contain no sequence dictionary. Attempting to retrieve a sequence dictionary from the associated index file
...
WARN  IndexUtils - Feature file "file:///home/kth/Mydata/ref_geno/hmp321_282_agpv4/hmp321_agpv4_chr10.vcf.gz" appears to contain no sequence dictionary. Attempting to retrieve a sequence dictionary from the associated index file
03:30:10.983 INFO  BaseRecalibrator - Done initializing engine
03:30:10.990 INFO  BaseRecalibrationEngine - The covariates being used here:
03:30:10.990 INFO  BaseRecalibrationEngine - 	ReadGroupCovariate
03:30:10.990 INFO  BaseRecalibrationEngine - 	QualityScoreCovariate
03:30:10.990 INFO  BaseRecalibrationEngine - 	ContextCovariate
03:30:10.990 INFO  BaseRecalibrationEngine - 	CycleCovariate
03:30:11.011 INFO  ProgressMeter - Starting traversal
03:30:11.013 INFO  ProgressMeter -        Current Locus  Elapsed Minutes       Reads Processed     Reads/Minute
03:30:24.519 INFO  ProgressMeter -            1:3107536              0.2                  2000           8885.6
03:30:34.696 INFO  ProgressMeter -            1:5338575              0.4                  3000           7600.4
03:30:46.210 INFO  ProgressMeter - ...

**Comment by kuangtianhui** [comment]
By the way The Genome Analysis Toolkit (GATK) v4.2.0.0

**Comment by droazen** [comment]
@kuangtianhui It looks like the bam index on `/home/wangh/kth/Mydata/NAM/NAM_7/Bam/7-99.sorted.markdup.bam` is older than the bam itself. This may indicate that the index is out-of-date with respect to the bam. I recommend that you reindex the bam using `samtools index`

The warning about the missing sequence dictionary is not a big deal, and you can safely process the VCF without a sequence dictionary in the header, provided you've manually confirmed that the VCF uses the same reference as your BAMs.
