### ISSUE TITLE
Failed to detect whether we are running on Google Compute Engine: gatk4 4.2.0.0

### ISSUE THREAD

**Issue by pd410668** [broadinstitute/gatk#7229]
When I am trying to run gatk HallotypeCaller I got error below. Can someone give me some advices?

INFO: Failed to detect whether we are running on Google Compute Engine.
12:55:36.413 INFO  HaplotypeCaller - ------------------------------------------------------------
12:55:36.413 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.2.0.0
12:55:36.414 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
12:55:36.414 INFO  HaplotypeCaller - Executing as linux@Paulina on Linux v5.4.0-67-generic amd64
12:55:36.414 INFO  HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v11.0.10+9-Ubuntu-0ubuntu1.18.04
12:55:36.414 INFO  HaplotypeCaller - Start Date/Time: 24 April 2021 at 12:55:36 CEST
12:55:36.414 INFO  HaplotypeCaller - ------------------------------------------------------------
12:55:36.414 INFO  HaplotypeCaller - ------------------------------------------------------------
12:55:36.414 INFO  HaplotypeCaller - HTSJDK Version: 2.24.0
12:55:36.414 INFO  HaplotypeCaller - Picard Version: 2.25.0
12:55:36.414 INFO  HaplotypeCaller - Built for Spark Version: 2.4.5
12:55:36.414 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
12:55:36.414 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
12:55:36.414 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
12:55:36.414 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
12:55:36.415 INFO  HaplotypeCaller - Deflater: IntelDeflater
12:55:36.415 INFO  HaplotypeCaller - Inflater: IntelInflater
12:55:36.415 INFO  HaplotypeCaller - GCS max retries/reopens: 20
12:55:36.415 INFO  HaplotypeCaller - Requester pays: disabled
12:55:36.415 INFO  HaplotypeCaller - Initializing engine
12:55:36.508 INFO  IntervalArgumentCollection - Processing 1 bp from intervals
12:55:36.511 INFO  HaplotypeCaller - Done initializing engine
12:55:36.515 INFO  HaplotypeCallerEngine - Disabling physical phasing, which is supported only for reference-model confidence output
12:55:36.523 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/home/linux/Downloads/SNP/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_utils.so
12:55:36.524 INFO  NativeLibraryLoader - Loading libgkl_pairhmm_omp.so from jar:file:/home/linux/Downloads/SNP/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_pairhmm_omp.so
12:55:36.552 INFO  IntelPairHmm - Flush-to-zero (FTZ) is enabled when running PairHMM
12:55:36.553 INFO  IntelPairHmm - Available threads: 12
12:55:36.553 INFO  IntelPairHmm - Requested threads: 4
12:55:36.553 INFO  PairHMM - Using the OpenMP multi-threaded AVX-accelerated native PairHMM implementation
12:55:36.569 INFO  ProgressMeter - Starting traversal
12:55:36.569 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
12:55:36.587 INFO  HaplotypeCaller - 0 read(s) filtered by: MappingQualityReadFilter 
0 read(s) filtered by: MappingQualityAvailableReadFilter 
0 read(s) filtered by: MappedReadFilter 
0 read(s) filtered by: NotSecondaryAlignmentReadFilter 
0 read(s) filtered by: NotDuplicateReadFilter 
0 read(s) filtered by: PassesVendorQualityCheckReadFilter 
0 read(s) filtered by: NonZeroReferenceLengthAlignmentReadFilter 
0 read(s) filtered by: GoodCigarReadFilter 
0 read(s) filtered by: WellformedReadFilter 
0 total reads filtered
12:55:36.588 INFO  ProgressMeter -             unmapped              0.0                     1           3333.3
12:55:36.588 INFO  ProgressMeter - Traversal complete. Processed 1 total regions in 0.0 minutes.
12:55:36.588 INFO  VectorLoglessPairHMM - Time spent in setup for JNI call : 0.0
12:55:36.589 INFO  PairHMM - Total compute time in PairHMM computeLogLikelihoods() : 0.0
12:55:36.589 INFO  SmithWatermanAligner - Total compute time in java Smith-Waterman : 0.00 sec
12:55:36.589 INFO  HaplotypeCaller - Shutting down engine
[24 April 2021 at 12:55:36 CEST] org.broadinstitute.hellbender.tools.walkers.haplotypecaller.HaplotypeCaller done. Elapsed time: 0.00 minutes.
Runtime.totalMemory()=528482304

**Comment by droazen** [comment]
@pd410668 This is just an informational message, and nothing to worry about. It's not an error. It looks like the `HaplotypeCaller` otherwise completed normally.
