### ISSUE TITLE
Picard 2.25.0 bug causes IlluminaBasecallsToSam to fail demultiplexing barcoded reads

### ISSUE THREAD

**Issue by myourshaw** [broadinstitute/gatk#7254]
### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_
Picard IlluminaBasecallsToSam and IlluminaBasecallsToFastq

### Affected version(s)
- [X] Latest public release version [4.2.0.0]
- [ ] Latest master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._
"This bug has been fixed in Picard release https://github.com/broadinstitute/picard/releases/tag/2.25.4 - The version of gatk that you are using (4.2.0.0) was packaged with Picard https://github.com/broadinstitute/picard/releases/tag/2.25.0 in it (which has the bug)." See [IlluminaBasecallsToSam and IlluminaBasecallsToFastq do not demultiplex NovaSeq barcoded reads](https://github.com/broadinstitute/picard/issues/1679) for details.

The GATK release needs to be updated to contain Picard 2.25.4 or better.

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_
Run tools with NovaSeq run directory as input and many dual index barcodes.

#### Expected behavior
_Tell us what should happen_
Reads having each of the dual index barcodes should be demultiplexed to separate files.

#### Actual behavior
_Tell us what happens instead_
Reads having each of the dual index barcodes are all in the UNKNOWN files.

----

**Comment by jamesemery** [comment]
This should be fixed in the next release as we are now on Picard 2.25.4 in master via #7255
