### ISSUE TITLE
ApplyVQSR Variant not filtered although all AS_FilterStatus failed.

### ISSUE THREAD

**Issue by nickhir** [broadinstitute/gatk#7259]
Hello,

I am using ApplyVQSR (GATK 4.2.0.0) and I noticed that some of my variants still have `PASS` in their FILTER field, although all AS_FilterStatus in the INFO field say they did not pass the filtering.

Here are some variant sites, so you know what I mean:

```bash
1       121009  .       C       T       274.04  PASS    AC=2;AF=1.00;AN=2;AS_BaseQRankSum=.;AS_FS=0.000;AS_FilterStatus=VQSRTrancheSNP97.00to98.00;AS_MQ=60.00;AS_MQRankSum=.;AS_QD=34.25;AS_ReadPosRankSum=.;AS_SOR=1.179;AS_VQSLOD=11.9465;AS_culprit=DP;DP=8;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=60.00;QD=34.25;SOR=1.179     GT:AD:DP:GQ:PL  1/1:0,8:8:24:288,24,0
1       723891  .       G       C       2109.06 PASS    AC=2;AF=1.00;AN=2;AS_BaseQRankSum=.;AS_FS=0.000;AS_FilterStatus=VQSRTrancheSNP97.00to98.00;AS_MQ=54.83;AS_MQRankSum=.;AS_QD=32.45;AS_ReadPosRankSum=.;AS_SOR=1.078;AS_VQSLOD=5.4769;AS_culprit=MQ;DP=69;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=55.14;POSITIVE_TRAIN_SITE;QD=32.45;SOR=1.078 GT:AD:DP:GQ:PL
1       754182  .       A       G       2229.06 PASS    AC=2;AF=1.00;AN=2;AS_BaseQRankSum=.;AS_FS=0.000;AS_FilterStatus=VQSRTrancheSNP97.00to98.00;AS_MQ=58.05;AS_MQRankSum=.;AS_QD=29.05;AS_ReadPosRankSum=.;AS_SOR=1.136;AS_VQSLOD=6.0153;AS_culprit=DP;DP=52;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=58.05;POSITIVE_TRAIN_SITE;QD=31.88;SOR=1.136 GT:AD:DP:GQ:PGT:PID:PL:PS                                                                                                   1|1:0,52:52:99:1|1:754182_A_G:2243,157,0:754182
1       760912  .       C       T       2851.06 PASS    AC=2;AF=1.00;AN=2;AS_BaseQRankSum=.;AS_FS=0.000;AS_FilterStatus=VQSRTrancheSNP97.00to98.00;AS_MQ=59.02;AS_MQRankSum=.;AS_QD=30.05;AS_ReadPosRankSum=.;AS_SOR=0.743;AS_VQSLOD=5.6443;AS_culprit=MQ;DP=82;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=58.91;POSITIVE_TRAIN_SITE;QD=33.30;SOR=0.743 GT:AD:DP:GQ:PL                                                                                                              1/1:0,80:80:99:2865,240,0
1       772755  .       A       C       2802.06 PASS    AC=2;AF=1.00;AN=2;AS_BaseQRankSum=.;AS_FS=0.000;AS_FilterStatus=VQSRTrancheSNP97.00to98.00;AS_MQ=58.30;AS_MQRankSum=.;AS_QD=31.13;AS_ReadPosRankSum=.;AS_SOR=1.166;AS_VQSLOD=5.1557;AS_culprit=MQ;DP=93;ExcessHet=3.0103;FS=0.000;MLEAC=2;MLEAF=1.00;MQ=58.35;POSITIVE_TRAIN_SITE;QD=31.13;SOR=1.191 GT:AD:DP:GQ:PL                                                                                                              1/1:0,90:91:99:2816,270,0
```

As you see, I am using allele-specific annotations for filtering. I read in the documentations, that if one allele passes, the whole site passes, but as you can see with my examples, there is only one allele which did not pass and yet the FILTER field says PASS.
The GATK documentation also says, that the allele-specific tools is still a beta, so I think that this might be a bug.

Here is the command that I used to generate the recalibrated vcf file:
```bash
gatk ApplyVQSR -V cohort.indel.recalibrated.vcf.gz --recal-file cohort_snp.recal --tranches-file cohort_snp.tranches --truth-sensitivity-filter-level 97 -mode SNP -AS -O cohort.recalibrated.vcf.gz
```

Cheers!

**Comment by droazen** [comment]
@nickhir I notice that your `--truth-sensitivity-filter-level` is 97, and the `AS_FilterStatus` at these sites assigns the alleles to the `VQSRTrancheSNP97.00to98.00` tranche. What happens if you run with a `--truth-sensitivity-filter-level` of 99 instead?

**Comment by nickhir** [comment]
Hello, 
I forgot to report back here. I figured out what my problem was:
I ran ApplyVQSR twice on my dataset. The first time with a sensitivity threshold of 99% and the second time with 97% (on the data which resulted from the 99% threshold run). When I use 97% right away everything worked. 

However, I am still a little confused, why "updating" the sensitivity threshold results in my observed output, where these sites PASS the filtering and if I use 97% right away they do not pass.

However, the "fix" (i.e. using the intended filtering threshold on the original data) is very simple and doesn't take long, so I will close this issue. Feel free to reopen if you need any more information. 
Thank you!
