### ISSUE TITLE
Can A Walker Subclass Hide an Inherited Argument or Give It A Default?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#7287]
My lab has a variety of custom walkers. Many subclass MultiVariantWalkerGroupedOnStart, which is a useful iteration pattern. We tend to scatter/gather on our cluster, where each job is given an interval set. When doing this, handling variant spanning those borders is critical. We just had an issue around this, which stems from MultiVariantWalkerGroupedOnStart and the fact that ignoreIntervalsOutsideStart defaults to false. For our usage, we almost never want this to be true, and it's a really subtle problem if the user doesnt remember to set this.

So my question is: is there a best-practice way for subclasses to override / remove or set default on inherited arguments? Granted, individual walkers could simply change the value of ignoreIntervalsOutsideStart during the init phase, but I dont like that solution since it basically leaves an useless/ignored argument. 

thanks in advance for any ideas.

**Comment by cmnbroad** [comment]
There is a pattern for abstracting these out, and even hiding them, but its intrusive and probably way overkill for this (see for example how `getSequenceDictionaryValidationArgumentCollection` is used). Also see `customCommandLineValidation` which can similarly be used for command line arg validation. Another option is to use a subclass constructor that resets the defaults, and logs a warning if you clobber a user value.  The worst way is to do what AlleleFrequencyQC does in onTraversalStart, which just silently clobbers...

**Comment by bbimber** [comment]
Yeah, I thought about just stomping over it and adding a warning. I'll look into these options.
