### ISSUE TITLE
genotype is ./. but with many high quality reads

### ISSUE THREAD

**Issue by biozzq** [broadinstitute/gatk#7291]
Dear all,

According to the best practice of SNP calling (gvcf->combine gvcf->genotype), I found that the genotype is ./. but with the supporting of many high quality reads. In my mind, the genotype of these sites should be 0/0. The version I used is 4.2.0.
![image](https://user-images.githubusercontent.com/15704257/120892516-4fdd2900-c641-11eb-8d59-deb72c6dbcfc.png)

sincerely,
Zheng zhuqing

**Comment by vruano** [comment]
The GT field is decided based on the content on PL not AD. PL=0,0,0 so there is no confidence on any GT vs the others.

PL=0,0,0 probrably is cause by a hom-ref site in that sample at that site with ALT list ```<NON-REF>``` that nontheless  had many pileup reads that did not support the reference (e.g. contained apparent SNP or softclips right before or after or a deletion/insertion at that point). 

If for whatever reason, the local assembly  didn't come out with a concrete alternative allele the PL are set to 0,0,0 (perhaps 0,0,X) to indicate the lack of confidence in a hom-ref call. 

The non-zero AD[ref] tracks the number of reads that support the reference but it does not tell you how many didn't.

**Comment by vruano** [comment]
Btw please post these tech questions in the [GATK community forum](https://gatk.broadinstitute.org/hc/en-us/community/topics) .... my understanding is that github issues are not the place to ask how to use the tools or interpret result but it is rather for development purposes.

Let me know here when you do and I will repost my reply there. Thanks.

**Comment by droazen** [comment]
Closing as resolved
