### ISSUE TITLE
How to add new sample to the existing VCF files?

### ISSUE THREAD

**Issue by jun3234** [broadinstitute/gatk#7292]
Hi, GATK contributors

Thank you for the great software!

I had looked  for the answer several days. 

Question:
Several samples are new sequenced and `g.vcf` was called using `GATK` with `-ERC GVCF` models.
I want to add this new sample variants into the existing VCF file (no g.vcf avaliable) that downloaded from other researchers.
I have tested some commands like `CombineGVCFs`, `MergeVcfs` but all failed.
Could you give some advices?
Any respone would be helpful.

Thanks ~

**Comment by vruano** [comment]
Can you gain access to the original gvcfs for those samples? if not I don't think there is a standard way to do such a thing in GATK following best practices. Perhaps there is some  general VCF merging tool that would do the trick sort-of but it won't be the same as if you had run that sample with the rest thru the single sample + joint-genotyping pipeline.

**Comment by vruano** [comment]
Btw please post these tech questions in the [GATK community forum](http://gatk.broadinstitute.org/hc/en-us/community) .... my understanding is that github issues are not the place to ask how to use the tools or interpret result but it is rather for development purposes.

Let me know here when you do and I will repost my reply there. Thanks.

**Comment by jun3234** [comment]
OK, I bookmark this website.
Thank you again.
