### ISSUE TITLE
Mutect2 --genotype-germline-sites remove experimental label

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7318]
As discussed at the GATK Office Hours meeting, the --genotype-germline-sites should no longer be labeled as experimental.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/360077847071-Mutect-genotype-germline-sites-status](https://gatk.broadinstitute.org/hc/en-us/community/posts/360077847071-Mutect-genotype-germline-sites-status)

\--

If not an error, choose a category for your question(REQUIRED):  
  
e) Will Mutect2's \[--genotype-germline-sites\](/hc/en-us/articles/360037593851-Mutect2#--genotype-germline-sites) be in future releases?

I notice that this flag is still set to `EXPERIMENTAL` in the Mutect2 docs.  Is there a way I can track the status of this feature?  It is important for the functionality of the pipeline I have built (i.e. we want to be able to see all of the germline variants that Mutect wants to call -- doesn't have to perfect per sé, but those calls are important), so we want to ensure it stays in the picture because it seems to be working for our needs (even after a lot of pressure testing).<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/149087'>Zendesk ticket #149087</a>)<br>gz#149087</i>

**Comment by fleharty** [comment]
@GATKSupportTeam There is no plan to remove this argument, and yes we should change this from being experimental.

**Comment by fleharty** [comment]
@davidbenjamin When you get back can you take a look at removing the experimental flag from the M2 docs?
