### ISSUE TITLE
Next minor GATK release?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#7322]
Hello,

Do you have an estimate on when you might be releasing the next minor GATK release? I'm hoping to pick up the GenomicsDB update (https://github.com/broadinstitute/gatk/commit/8796404cab594b716d43755f61fd405c92208141). I realize we could build our own, but for one of our projects we release a public dataset with documentation on the tools, and it's nicer to use official releases. Thanks.

**Comment by droazen** [comment]
Hi @bbimber, our next release is imminent -- we're just waiting on 1-2 final PRs to be merged. I can safely say it will go out this week.
