### ISSUE TITLE
In case of shut down while updating gvcf file to GenomicDB

### ISSUE THREAD

**Issue by chochangwoo1023** [broadinstitute/gatk#7324]
### Tool(s) or class(es) involved
GenomicsDBImport(v4.1.8.1)

### Description
Hello, I was construct to genomicdb using GenomicDBImport and import gvcf file for update genomicdb(Command).

 but since my server was shut down, during GenomicDBImport process, process is broke down. After I tried to GenomicDBImport same command for overwrite genomicdb and encounter to error message(error message).
 
In this case, should genomicdb be recreated from scratch? How to update the gvcf file I want to update? what should I do?

### Command

java -jar $GATK GenomicsDBImport \
-L chr${1} \
-V $File_PATH/4762/bwa-gatk4/VARIANT/ForEachChr/chr22.g.vcf \
-V $File_PATH/4763/bwa-gatk4/VARIANT/ForEachChr/chr22.g.vcf \
-V $File_PATH/4764/bwa-gatk4/VARIANT/ForEachChr/chr22.g.vcf \
-V $File_PATH/4765/bwa-gatk4/VARIANT/ForEachChr/chr22.g.vcf \
-V $File_PATH/4767/bwa-gatk4/VARIANT/ForEachChr/chr22.g.vcf \
--genomicsdb-update-workspace-path $DB_PATH/test_database \
--genomicsdb-shared-posixfs-optimizations true \
--max-num-intervals-to-import-in-parallel 5 \
--reader-threads 10 \
--tmp-dir $Script_PATH/tmp

### Error message

10:49:12.018 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/mnt/mone/OMICS/Tools/Programs/gatk/gatk-4.1.8.1/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jun 18, 2021 10:49:12 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
10:49:12.231 INFO  GenomicsDBImport - ------------------------------------------------------------
10:49:12.232 INFO  GenomicsDBImport - The Genome Analysis Toolkit (GATK) v4.1.8.1
10:49:12.232 INFO  GenomicsDBImport - For support and documentation go to https://software.broadinstitute.org/gatk/
10:49:12.232 INFO  GenomicsDBImport - Executing as chowoo1023@bdcm04 on Linux v3.10.0-514.2.2.el7.x86_64 amd64
10:49:12.232 INFO  GenomicsDBImport - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_191-b12
10:49:12.232 INFO  GenomicsDBImport - Start Date/Time: June 18, 2021 10:49:11 AM KST
10:49:12.233 INFO  GenomicsDBImport - ------------------------------------------------------------
10:49:12.233 INFO  GenomicsDBImport - ------------------------------------------------------------
10:49:12.233 INFO  GenomicsDBImport - HTSJDK Version: 2.23.0
10:49:12.233 INFO  GenomicsDBImport - Picard Version: 2.22.8
10:49:12.234 INFO  GenomicsDBImport - HTSJDK Defaults.COMPRESSION_LEVEL : 2
10:49:12.234 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
10:49:12.234 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
10:49:12.234 INFO  GenomicsDBImport - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
10:49:12.234 INFO  GenomicsDBImport - Deflater: IntelDeflater
10:49:12.234 INFO  GenomicsDBImport - Inflater: IntelInflater
10:49:12.234 INFO  GenomicsDBImport - GCS max retries/reopens: 20
10:49:12.234 INFO  GenomicsDBImport - Requester pays: disabled
10:49:12.235 INFO  GenomicsDBImport - Initializing engine
10:49:12.577 WARN  GenomicsDBImport - genomicsdb-update-workspace-path was set, so ignoring specified intervals.The tool will use the intervals specified by the initial import
10:49:12.938 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.3.0-e701905
10:49:13.163 INFO  IntervalArgumentCollection - Processing 51304566 bp from intervals
10:49:13.163 INFO  GenomicsDBImport - Done initializing engine
10:49:13.164 INFO  GenomicsDBImport - Callset Map JSON file will be re-written to /mnt/mone/OMICS/Project/Joint_call/GATK_GenomicDB/test_database/test_overwrite_1/callset.json
10:49:13.164 INFO  GenomicsDBImport - Incrementally importing to workspace - /mnt/mone/OMICS/Project/Joint_call/GATK_GenomicDB/test_database/test_overwrite_1
10:49:13.164 INFO  ProgressMeter - Starting traversal
10:49:13.164 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Batches Processed   Batches/Minute
10:49:13.231 INFO  GenomicsDBImport - Shutting down engine
[June 18, 2021 10:49:13 AM KST] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=2194669568
org.genomicsdb.exception.GenomicsDBException: Duplicate sample name found: 4762. Sample was originally in /mnt/mone/OMICS/Project/Asian_Genome/Korea/4762/bwa-gatk4/VARIANT/ForEachChr/chr22.g.vcf
        at org.genomicsdb.importer.extensions.CallSetMapExtensions.checkDuplicateCallsetsForIncrementalImport(CallSetMapExtensions.java:270)
        at org.genomicsdb.importer.extensions.CallSetMapExtensions.mergeCallsetsForIncrementalImport(CallSetMapExtensions.java:241)
        at org.genomicsdb.importer.GenomicsDBImporter.<init>(GenomicsDBImporter.java:252)
        at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport.traverse(GenomicsDBImport.java:745)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1049)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by droazen** [comment]
@chochangwoo1023 We recommend recreating the GenomicsDB from scratch in this case, since it may have been corrupted when your server shut down.
