### ISSUE TITLE
ASEReadCounter check for no genotype info

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7327]
We have determined that a sites-only VCF causes ASEReadCounter to only output a header. There are warnings in the stack trace but it is not clear that the tool found no genotypes in the file. We can look into adding a check in ASEReadCounter to exit out if the VCF has no genotype fields. The documentation for this tool should also be more specific.

This request was created from a contribution made by Chunyang Bao on June 14, 2021 23:15 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/1260803844270-ASEReadCounter-ouputs-only-header-](https://gatk.broadinstitute.org/hc/en-us/community/posts/1260803844270-ASEReadCounter-ouputs-only-header-)

\--

I am using ASEReadCounter to call allelic read counts on 1000 genome reference. But, I found ASEReadCounter generatd only header in output file. Here I enclosed my command and stderr log. Please help me to check it. Thank you!

If you are seeing an error, please provide(REQUIRED) :  
  
a) GATK version used: 4.1.8.1  
  
b) Exact command used:

java -Xmx8000m -Djava.io.tmpdir=/broad/hptmp/cbao \\  
  
\-jar ${path2gatk}/gatk-package-4.1.8.1-local.jar \\  
  
ASEReadCounter \\  
  
\-L scattered.interval\_list \\  
  
\-R Homo\_sapiens\_assembly19.fasta \\  
  
\-V 1000G\_phase1.snps.high\_confidence.b37.vcf.gz \\  
  
\-I downsample\_10k.bam \\  
  
\-O output.txt --verbosity INFO

c) Entire error log:

19:13:25.991 INFO NativeLibraryLoader - Loading libgkl\_compression.so from jar:file:/broad/software/free/Linux/redhat\_7\_x86\_64/pkgs/gatk\_4.1.8.1/gatk-package-4.1.8.1-local.jar!/com/intel/gkl/native/libgkl\_compression.so

Jun 14, 2021 7:13:26 PM shaded.cloud\_nio.com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials

WARNING: Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see [https://cloud.google.com/docs/authentication/](https://cloud.google.com/docs/authentication/).

19:13:26.217 INFO ASEReadCounter - ------------------------------------------------------------

19:13:26.218 INFO ASEReadCounter - The Genome Analysis Toolkit (GATK) v4.1.8.1

19:13:26.218 INFO ASEReadCounter - For support and documentation go to [https://software.broadinstitute.org/gatk/](https://software.broadinstitute.org/gatk/)

19:13:26.219 INFO ASEReadCounter - Executing as [cbao@uger-c009.broadinstitute.org](mailto:cbao@uger-c009.broadinstitute.org) on Linux v3.10.0-1160.15.2.el7.x86\_64 amd64

19:13:26.219 INFO ASEReadCounter - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0\_181-b13

19:13:26.219 INFO ASEReadCounter - Start Date/Time: June 14, 2021 7:13:25 PM UTC

19:13:26.219 INFO ASEReadCounter - ------------------------------------------------------------

19:13:26.219 INFO ASEReadCounter - ------------------------------------------------------------

19:13:26.220 INFO ASEReadCounter - HTSJDK Version: 2.23.0

19:13:26.220 INFO ASEReadCounter - Picard Version: 2.22.8

19:13:26.220 INFO ASEReadCounter - HTSJDK Defaults.COMPRESSION\_LEVEL : 2

19:13:26.220 INFO ASEReadCounter - HTSJDK Defaults.USE\_ASYNC\_IO\_READ\_FOR\_SAMTOOLS : false

19:13:26.220 INFO ASEReadCounter - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_SAMTOOLS : true

19:13:26.220 INFO ASEReadCounter - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_TRIBBLE : false

19:13:26.220 INFO ASEReadCounter - Deflater: IntelDeflater

19:13:26.220 INFO ASEReadCounter - Inflater: IntelInflater

19:13:26.220 INFO ASEReadCounter - GCS max retries/reopens: 20

19:13:26.221 INFO ASEReadCounter - Requester pays: disabled

19:13:26.221 INFO ASEReadCounter - Initializing engine

19:13:26.663 INFO FeatureManager - Using codec VCFCodec to read file file:///cga/bass/Chunyang/ref/hg19/1000G\_phase1.snps.high\_confidence.b37.vcf.gz

19:13:26.818 INFO FeatureManager - Using codec IntervalListCodec to read file file:///cga/bass/Chunyang/ref/hg19/gatk\_b37.scattered\_wgs\_intervals/scatter-50/temp\_0001\_of\_50/scattered.interval\_list

19:13:26.831 INFO IntervalArgumentCollection - Processing 29268134 bp from intervals

19:13:26.834 WARN IndexUtils - Feature file "/cga/bass/Chunyang/ref/hg19/1000G\_phase1.snps.high\_confidence.b37.vcf.gz" appears to contain no sequence dictionary. Attempting to retrieve a sequence dictionary from the associated index file

19:13:26.973 INFO ASEReadCounter - Done initializing engine

19:13:26.977 INFO ProgressMeter - Starting traversal

19:13:26.977 INFO ProgressMeter - Current Locus Elapsed Minutes Loci Processed Loci/Minute

19:13:27.118 WARN ASEReadCounter - Ignoring site: variant is not het at postion: 1:835092

19:13:27.118 WARN ASEReadCounter - Ignoring site: variant is not het at postion: 1:835132

19:13:27.118 WARN ASEReadCounter - Ignoring site: variant is not het at postion: 1:835133

... 

...

...

19:13:28.229 WARN ASEReadCounter - Ignoring site: variant is not het at postion: 1:29617944

19:13:28.230 WARN ASEReadCounter - Ignoring site: variant is not het at postion: 1:29618025

19:13:28.231 INFO ASEReadCounter - 0 read(s) filtered by: ValidAlignmentStartReadFilter

0 read(s) filtered by: ValidAlignmentEndReadFilter

0 read(s) filtered by: HasReadGroupReadFilter

0 read(s) filtered by: MatchingBasesAndQualsReadFilter

0 read(s) filtered by: SeqIsStoredReadFilter

51 read(s) filtered by: NotDuplicateReadFilter

63 read(s) filtered by: NotSecondaryAlignmentReadFilter

3 read(s) filtered by: MappedReadFilter

117 total reads filtered

19:13:28.231 INFO ProgressMeter - 1:29618022 0.0 110019 5264067.0

19:13:28.231 INFO ProgressMeter - Traversal complete. Processed 110019 total loci in 0.0 minutes.

19:13:28.233 INFO ASEReadCounter - Shutting down engine

\[June 14, 2021 7:13:28 PM UTC\] org.broadinstitute.hellbender.tools.walkers.rnaseq.ASEReadCounter done. Elapsed time: 0.04 minutes.

Runtime.totalMemory()=2303197184

output.txt:

contig position variantID refAllele altAllele refCount altCount totalCount lowMAPQDepth lowBaseQDepth rawDepth otherBases improperPairs

Thanks for your help!

Chunyang<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/165377'>Zendesk ticket #165377</a>)<br>gz#165377</i>

**Comment by jamesemery** [comment]
The issue was that the user supplied a sites-only vcf. AESReadCounter only evaluates results at het sites which don't exist in sites-only outputs. Fixed by #7326

**Comment by gbrandt6** [comment]
Thank you @jamesemery, looks good!
