### ISSUE TITLE
Mutect2 Mitochondria Mode clarifications regarding heteroplasmy

### ISSUE THREAD

**Issue by VGDEC** [broadinstitute/gatk#7350]
### Affected tool(s) or class(es)
Mutect2 mitochondria mode

### Affected version(s)
- Gatk 4.2.0.0

### Description 
1) I wanted to clarify that does the AF parameter under the FORMAT column in output vcf after running the mutect2 with mitochondria mode can be considered as representation of heteroplasmy levels?
2) If point 1. is true, then question is that does it provide the genotypes on the basis of the level of heteroplasmy?  e.g. does it show variants with heteroplasmy levels 0-95% as 0/1 and with heteroplasmy 95-100 as 1/1? In the vcf I obtained as output, it is showing only 0/1 for all the levels of heteroplasmy (0-95% and 95-100%)
3) Does the mitochondria mode applies the rule of alignment of mtDNA to the 8000 shifted bases and then realignment. Or do we have to manually apply it (as described in the blog https://gnomad.broadinstitute.org/news/2020-11-gnomad-v3-1-mitochondrial-dna-variants/)

**Comment by meganshand** [comment]
1. AF in the FORMAT column can be used to represent heteroplasmy levels. 
2. Currently the genotype is always reported as het (0/1). There is a request to change this but it hasn't been implemented yet: https://github.com/broadinstitute/gatk/issues/6257 If you'd like to fix this feel free to make a PR and I'd be happy to review it.
3. Mitochondria mode in Mutect alone does not automatically shift the reference. However, you can use the full pipeline which does the shift automatically. You can find the WDL here: https://github.com/broadinstitute/gatk/blob/master/scripts/mitochondria_m2_wdl/MitochondriaPipeline.wdl or the Terra workspace here: https://app.terra.bio/#workspaces/help-gatk/Mitochondria-SNPs-Indels-hg38 Depending on the coverage of your data, if you don't need high sensitivity over the region with the breakpoint it also might not be worth doing the full realignment. You'll still be able to make calls on the edges of the linearized reference, you just might not have the full sensitivity you would if you realigned. I hope that helps!

**Comment by droazen** [comment]
@meganshand Can this one be closed as answered?
