### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [broadinstitute/gatk#7377]
https://github.com/broadinstitute/gatk/blob/b4cba377e0aff179dbff615783506913e7fe3aa4/src/main/java/org/broadinstitute/hellbender/tools/LocalAssembler.java#L1272

The program can potentially fail to release a system resource.

**Comment by droazen** [comment]
Reviewed this and confirmed it's not an issue -- closing.
