### ISSUE TITLE
Make RECAL_TABLE_FILE optional in BQSR dataflow

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/gatk#738]
If we may be running the BaseRecalibrator phase immediately followed by the ApplyBQSR phase then we may choose not to save the recalibration tables report to a file (and instead just use it directly). 

This note is a reminder to make the corresponding RECAL_TABLE_FILE optional: not setting it would be a way to indicate we don't want the textual report.

**Comment by akiezun** [comment]
this applies to spark too right?

**Comment by akiezun** [comment]
maybe this still should be alpha, wdyt?

**Comment by jean-philippe-martin** [comment]
The arguments reshuflfling may have solved this already. Will have to check post-merge.

**Comment by jean-philippe-martin** [comment]
The idea behind removing RECAL_TABLE_FILE (now just called -O) was that we may want to call multiple tools from the command line, and have the right thing happen.

The current design, instead, is that we can either call the tools one at a time via the command line, or call the special pipeline command that'll run a curated set of tools together. Because of the way the code's now organized, this special pipeline command doesn't require RECAL_TABLE_FILE.

So I'd say that this issue is closed. Later we can go back and implement a "give multiple tools on the command line" feature - but I would expect that to be after the alpha release.
