### ISSUE TITLE
intermittent ArrayIndexOutOfBoundsException in CalibrateDragstrModelIntegrationTest.testDragstrModelInferenceFailingOverToDefaults?

### ISSUE THREAD

**Issue by samuelklee** [broadinstitute/gatk#7403]
Not sure what's going on here, but thought I'd document. See https://storage.googleapis.com/hellbender-test-logs/build_reports/master_35408.2/tests/test/classes/org.broadinstitute.hellbender.tools.dragstr.CalibrateDragstrModelIntegrationTest.html#testDragstrModelInferenceFailingOverToDefaults[0](1,%20false)

**Comment by jamesemery** [comment]
Oh boy this smacks of being a race condition. More interesting is the fact that its failing specifically when threads = 1 and cram is off? I'm not sure if its also failing elsewhere on other runs though. It looks like its failing when it tries to add a new                     `final ReadsPathDataSource result = new ReadsPathDataSource(readArguments.getReadPaths(), factory);` to the datasource pool which sounds like a horrible race condition of some kind. 

@vruano

**Comment by jamesemery** [comment]
To add some commentary to why this is happening: It looks like multiple threads are hitting this line simultaneously and based on the overload of `ArrayList.add()` this error could be triggered by multiple calls to `ensureCapacityInternal()` inside the add method:
```
        final List<ReadsPathDataSource> readSources = new ArrayList<>(threads);
        final ThreadLocal<ReadsPathDataSource> threadReadSource = ThreadLocal.withInitial(
                () -> {
                    final ReadsPathDataSource result = new ReadsPathDataSource(readArguments.getReadPaths(), factory);
                    readSources.add(result);
                    return result;
                });
```
The fix should be simple you just have to make sure ti synchronize the initialization or swap out the readSources object to one that is itself thread safe.

@vruano

**Comment by vruano** [comment]
Chaning the holding collection to a Vector which is synchronized. There is no performance impact as this add and single collection iteractiion should happen just a finite number of times.

**Comment by vruano** [comment]
PR with the fix is in place.
