### ISSUE TITLE
Funcotator not populating Match_Norm_Seq_Allele1 and Match_Norm_Seq_Allele2 when generating MAF

### ISSUE THREAD

**Issue by dheiman** [broadinstitute/gatk#7408]
### Affected tool(s) or class(es)
Funcotator

### Affected version(s)
- [x] Latest public release version [4.2.1.0]
- [ ] Latest master branch as of [date of test?]

### Description 
When processing a VCF with tumor and matched normal into a MAF, the `Match_Norm_Seq_Allele1` and `Match_Norm_Seq_Allele2` fields are not populated.

#### Steps to reproduce

`gatk --java-options -Xmx2048m Funcotator --data-sources-path /cromwell_root/datasources_dir --ref-version hg38 --output-file-format MAF -R /cromwell_root/getzlab-workflows-reference_files-oa/hg38/gdc/GRCh38.d1.vd1.fa -V` [`C3N-02729.vcf.gz`](https://github.com/broadinstitute/gatk/files/6977700/C3N-02729.vcf.gz) `-O C3N-02729.maf --annotation-default normal_barcode:C3N-02729_N --annotation-default tumor_barcode:C3N-02729_T --annotation-default Center:broadinstitute.org --annotation-default source:Unknown --transcript-selection-mode BEST_EFFECT`

(NOTE: reference files available at `gs://getzlab-workflows-reference_files-oa/hg38/gdc`)

#### Expected behavior
`Match_Norm_Seq_Allele1` and `Match_Norm_Seq_Allele2` fields should be populated as appropriate based on the `GT` field for the matched normal in the VCF

#### Actual behavior
`Match_Norm_Seq_Allele1` and `Match_Norm_Seq_Allele2` are populated with `__UNKNOWN__`

**Comment by jonn-smith** [comment]
@dheiman Good catch.  It is indeed not being populated.  The fix is pretty quick - I've implemented it already, I just need to add in some test cases.

**Comment by jonn-smith** [comment]
@dheiman I've implemented a fix in PR #7422, but I wanted to check to see if you're aware that TCGA MAF spec v2.4.1 has an _**interesting**_  definition of these fields in the case of insertions:

![image](https://user-images.githubusercontent.com/11667487/129929526-4a9bd6a2-5985-4317-9d74-80e939cc038b.png)

So these fields will actually contain alt/tumor bases in the case of an insertion.
