### ISSUE TITLE
Can't run apt-get inside docker image

### ISSUE THREAD

**Issue by fleharty** [broadinstitute/gatk#7447]
### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

### Affected version(s)
- [x] Latest public release version 4.2.2.0

### Description 

Running apt-get inside docker image fails.

#### Steps to reproduce

(base) fleharty@wm3b9-dfa docker % docker run -it broadinstitute/gatk:4.2.2.0
Unable to find image 'broadinstitute/gatk:4.2.2.0' locally
4.2.2.0: Pulling from broadinstitute/gatk
a7fe112a8303: Already exists 
Digest: sha256:32175c3c7c1fb9f5bd6650183c9c5cf26fb822dddb0cad0123d48c33124b6065
Status: Downloaded newer image for broadinstitute/gatk:4.2.2.0
(gatk) root@bc90fdaf700c:/gatk# 
(gatk) root@bc90fdaf700c:/gatk# 
(gatk) root@bc90fdaf700c:/gatk# apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]                                        
Get:3 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [26.7 kB]           
Get:4 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [543 kB]           
Get:5 http://packages.cloud.google.com/apt cloud-sdk-bionic InRelease [6786 B]        
Get:6 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1426 kB]         
Err:5 http://packages.cloud.google.com/apt cloud-sdk-bionic InRelease                                           
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FEEA9169307EA071 NO_PUBKEY 8B57C5C2836F4BEB
Get:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2295 kB]        
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]             
Get:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                 
Get:10 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB] 
Get:11 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]    
Get:13 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]          
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2200 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [34.4 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [575 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [2731 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [11.4 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [11.3 kB]
Reading package lists... Done                                 
W: GPG error: http://packages.cloud.google.com/apt cloud-sdk-bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FEEA9169307EA071 NO_PUBKEY 8B57C5C2836F4BEB
E: The repository 'http://packages.cloud.google.com/apt cloud-sdk-bionic InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by fleharty** [comment]
@droazen @lbergelson 
I spoke with @jamesemery about this, and he suggested I make a ticket and ping you two.

I'm trying to use the GATK docker as a starting point, but I run into this problem with GPG signatures.

W: GPG error: http://packages.cloud.google.com/apt cloud-sdk-bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY FEEA9169307EA071 NO_PUBKEY 8B57C5C2836F4BEB

**Comment by fleharty** [comment]
This problem also exists for the base image,
broadinstitute/gatk:gatkbase-2.3.0

**Comment by droazen** [comment]
@fleharty This was believed to be fixed in https://github.com/broadinstitute/gatk/pull/7180

What happens if you manually run `curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -`, and then run the `apt-get` command ?

**Comment by fleharty** [comment]
@droazen 
Your suggestion works, thanks!

Should we close the ticket?

**Comment by droazen** [comment]
@fleharty Not yet -- I need to figure out why this happened again. I'm guessing that Google invalidated their package signing key after our most recent release. We may need to run that command every time the docker image is run, rather than just at build time. Or at least we should document the workaround somewhere in our README.

**Comment by droazen** [comment]
Closing as resolved
