### ISSUE TITLE
GATK_DepthOfCoverage

### ISSUE THREAD

**Issue by AlirezaTafazzoli** [broadinstitute/gatk#7453]
I am using GATK DepthOfCoverage tool for some of my samples.
I need to use genome reference GRCh37.
Everything is working fine but an error will occur whenever I run it (attached photos).
I have used all different type of references, including Ensembl, UCSC, NCBI, and GATK source itself but the same error is still there.
Also I know that I need to use a unique database and use that to create all fai, dict, bed file so that for sure the namings are the same in my all types of files. But I don't know how to create .bed file out of a reference genome (i.e. Homo_sapiens.GRCh37.dna.primary_assembly.fa)
Would you please guide me what can I do about that?

.

![Screenshot from 2021-09-02 00-11-51](https://user-images.githubusercontent.com/87016284/131868327-660a9a9c-cc93-4c6e-a08c-0a67eddf2f47.png)
![Screenshot from 2021-09-02 00-12-00](https://user-images.githubusercontent.com/87016284/131868369-0a80d306-8a05-4a87-a566-02c3713561c4.png)

**Comment by droazen** [comment]
@jamesemery Could you look at this one when you get a chance?

**Comment by jamesemery** [comment]
Hello @AlirezaTafazzoli looking at your error and the the stderr output it looks like what happened is that the bed file you used of your genes was generated on a different reference. If you have a standard GRC37 reference the chr1 name should be valid. Could you check the .ditct files for the reference you have to make sure the names align with the ones in the genes.bed file you are using? I would also check to be 100% sure that your bam file also has the same contigs in its sequence dictionary. Furthermore it would be helpful to diagnose this issue if you could rerun with a stacktrace on "GATK_STACKTRACE_ON_USR_EXCEPTION" in the java options in the output you posted. I would also recommend using samtools to regenerate the .dict files for your reference and trying again if you are sure the genes.bed file is matched correctly. 

As a minor sidenote, if you want per-gene coverage information out of DepthOfCoverage i would recommend checking out hte --gene-list argument and files. Those will allow you to get coverage across different transcripts and including the ability to distinguish between intros and exons in coverage calculation.

**Comment by AlirezaTafazzoli** [comment]
Hi @jamesemery Thanks for your email.
Actually, I was successful with calculation of "DepthOfCoverage" with following procedure:
1. I found the exact reference fasta file which is used for mapping procedures in my pipeline + .dict and .fa.fai
2. I made a bed file out of the reference fasta file, using the following command:
    faidx -i bed genome.fa > out.bed
3. Finally I did this for performing the "DepthOfCoverage" tool:
    gatk DepthOfCoverage -R reference.fa -O result -I s269825.haplotagged.bam -L out.bed

So everything works fine but there is another problem: the size of output file is very huge (GBs)! Should it be like that?

**Comment by jamesemery** [comment]
Hi @AlirezaTafazzoli. I'm glad you were able to fix your problem and I'm sorry the size was unworkable. I might consider adding the command `--omit-depth-output-at-each-base` which will remove from the output the file (which is probably the largest output file) that details the per-base, per-nucleotide summaries of the depth across the intervals. That will make the size more manageable.
