### ISSUE TITLE
Two times HaplotypeCaller give different results

### ISSUE THREAD

**Issue by Chenwei-cri** [broadinstitute/gatk#7454]
I run HaplotypeCaller twice , the former one was stopped because of  unexpected power outages. I check the LOG and found the chromosome where HaplotypeCaller  stopped. So i star another HaplotypeCaller(later one) with the "-L  *.intervals", it begin from  the chromosome where former HaplotypeCaller  stopped.The ref genome and the parameters were all the same. However,  HaplotypeCaller give different results.

Note: the ref genome has 26 chromosomes :A01-A13;D01-D13

**_The former LOG:_**

nohup: ignoring input and appending output to ‘nohup.out’
09:04:49.857 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/home/chenwei/biosoft/gatk-4.0.10.1/gatk-package-4.0.10.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
09:05:02.971 INFO  HaplotypeCaller - ------------------------------------------------------------
09:05:02.971 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.0.10.1
09:05:02.971 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
09:05:02.972 INFO  HaplotypeCaller - Executing as chenwei@localhost.localdomain on Linux v3.10.0-1160.31.1.el7.x86_64 amd64
09:05:02.972 INFO  HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_292-b10
09:05:02.973 INFO  HaplotypeCaller - Start Date/Time: August 22, 2021 9:04:49 AM CST
09:05:02.973 INFO  HaplotypeCaller - ------------------------------------------------------------
09:05:02.973 INFO  HaplotypeCaller - ------------------------------------------------------------
09:05:02.974 INFO  HaplotypeCaller - HTSJDK Version: 2.16.1
09:05:02.974 INFO  HaplotypeCaller - Picard Version: 2.18.13
09:05:02.975 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
09:05:02.975 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
09:05:02.975 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
09:05:02.975 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
09:05:02.975 INFO  HaplotypeCaller - Deflater: IntelDeflater
09:05:02.975 INFO  HaplotypeCaller - Inflater: IntelInflater
09:05:02.975 INFO  HaplotypeCaller - GCS max retries/reopens: 20
09:05:02.975 INFO  HaplotypeCaller - Requester pays: disabled
09:05:02.976 INFO  HaplotypeCaller - Initializing engine
09:05:05.609 INFO  HaplotypeCaller - Done initializing engine
09:05:05.616 INFO  HaplotypeCallerEngine - Tool is in reference confidence mode and the annotation, the following changes will be made to any specified annotations: 'StrandBiasBySample' will be enabled. 'ChromosomeCounts', 'FisherStrand', 'StrandOddsRatio' and 'QualByDepth' annotations have been disabled
09:05:06.026 INFO  HaplotypeCallerEngine - Standard Emitting and Calling confidence set to 0.0 for reference-model confidence output
09:05:06.026 INFO  HaplotypeCallerEngine - All sites annotated with PLs forced to true for reference-model confidence output
09:05:06.055 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/share/home/chenwei/biosoft/gatk-4.0.10.1/gatk-package-4.0.10.1-local.jar!/com/intel/gkl/native/libgkl_utils.so
09:05:06.083 INFO  PairHMM - OpenMP multi-threaded AVX-accelerated native PairHMM implementation is not supported
09:05:06.083 WARN  PairHMM - ***WARNING: Machine does not have the AVX instruction set support needed for the accelerated AVX PairHmm. Falling back to the MUCH slower LOGLESS_CACHING implementation!
09:05:06.411 INFO  ProgressMeter - Starting traversal
09:05:06.412 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
09:05:16.445 INFO  ProgressMeter -            A01:27883              0.2                   110            657.9
09:05:27.780 INFO  ProgressMeter -            A01:45980              0.4                   240            673.9
09:05:38.219 INFO  ProgressMeter -            A01:64498              0.5                   360            679.1
.......
11:56:31.165 INFO  ProgressMeter -        A13:109860605          16011.4               6803200            424.9
11:56:41.437 INFO  ProgressMeter -        A13:109878042          16011.6               6803330            424.9
11:56:51.882 INFO  ProgressMeter -        A13:109913861          16011.8               6803540            424.9
11:57:02.097 INFO  ProgressMeter -        A13:109924924          16011.9               6803620            424.9
11:57:14.212 INFO  ProgressMeter -        A13:109930687          16012.1               6803650            424.9
11:57:26.561 INFO  ProgressMeter -        A13:109956963          16012.3               6803750            424.9
11:57:36.911 INFO  ProgressMeter -        A13:109987769          16012.5               6803890            424.9
11:57:46.970 INFO  ProgressMeter -        A13:110044797          16012.7               6804130            424.9
11:59:08.401 INFO  ProgressMeter -        A13:110053612          16014.0               6804190            424.9
11:59:19.031 INFO  ProgressMeter -        A13:110075986          16014.2               6804320            424.9
11:59:39.855 INFO  ProgressMeter -        A13:110084620          16014.6               6804360            424.9
11:59:50.062 INFO  ProgressMeter -        A13:110124793          16014.7               6804520            424.9
12:00:00.449 INFO  ProgressMeter -        A13:110174275          16014.9               6804730            424.9
12:00:10.826 INFO  ProgressMeter -        A13:110235342          16015.1               6804970            424.9
12:00:21.070 INFO  ProgressMeter -        A13:110259350          16015.2               6805060            424.9
12:00:31.315 INFO  ProgressMeter -        A13:110314490          16015.4               6805270            424.9
12:00:47.727 INFO  ProgressMeter -        A13:110336003          16015.7               6805350            424.9
12:01:14.585 INFO  ProgressMeter -        A13:110337464          16016.1               6805360            424.9
12:01:37.243 INFO  ProgressMeter -             D01:4554          16016.5               6805510            424.9
12:01:41.697 WARN  DepthPerSampleHC - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
12:01:41.697 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
12:01:47.448 INFO  ProgressMeter -            D01:17964          16016.7               6805600            424.9
12:02:09.831 INFO  ProgressMeter -            D01:20727          16017.1               6805620            424.9
12:02:20.114 INFO  ProgressMeter -            D01:26228          16017.2               6805660            424.9
12:02:30.262 INFO  ProgressMeter -            D01:52324          16017.4               6805810            424.9
12:02:42.612 INFO  ProgressMeter -            D01:61819          16017.6               6805880            424.9
12:03:15.275 INFO  ProgressMeter -            D01:67055          16018.1               6805910            424.9
12:03:26.973 INFO  ProgressMeter -            D01:75559          16018.3               6805980            424.9
12:03:37.256 INFO  ProgressMeter -           D01:101543          16018.5               6806140            424.9
12:03:49.911 INFO  ProgressMeter -           D01:106344          16018.7               6806170            424.9
12:04:23.685 INFO  ProgressMeter -           D01:108187          16019.3               6806180            424.9
12:04:33.872 INFO  ProgressMeter -           D01:131768          16019.5               6806320            424.9
12:04:44.080 INFO  ProgressMeter -           D01:142033          16019.6               6806390            424.9
12:05:30.576 INFO  ProgressMeter -           D01:151103          16020.4               6806460            424.9
12:05:40.721 INFO  ProgressMeter -           D01:171985          16020.6               6806600            424.9
12:05:52.649 INFO  ProgressMeter -           D01:179627          16020.8               6806650            424.9
12:06:05.001 INFO  ProgressMeter -           D01:191227          16021.0               6806730            424.9
12:06:32.206 INFO  ProgressMeter -           D01:211153          16021.4               6806880            424.9
12:06:46.312 INFO  ProgressMeter -           D01:220323          16021.7               6806940            424.9
12:06:56.646 INFO  ProgressMeter -           D01:232399          16021.8               6807020            424.9
12:07:10.267 INFO  ProgressMeter -           D01:235919          16022.1               6807050            424.9
12:07:22.064 INFO  ProgressMeter -           D01:256207          16022.3               6807200            424.9

**_The later LOG_**

nohup: ignoring input and appending output to ‘nohup.out’
09:13:38.398 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/share/home/chenwei/biosoft/gatk-4.0.10.1/gatk-package-4.0.10.1-local.jar!/com/intel/gkl/native/libgkl_compression.so
09:13:57.227 INFO  HaplotypeCaller - ------------------------------------------------------------
09:13:57.228 INFO  HaplotypeCaller - The Genome Analysis Toolkit (GATK) v4.0.10.1
09:13:57.228 INFO  HaplotypeCaller - For support and documentation go to https://software.broadinstitute.org/gatk/
09:13:57.229 INFO  HaplotypeCaller - Executing as chenwei@localhost.localdomain on Linux v3.10.0-1160.31.1.el7.x86_64 amd64
09:13:57.229 INFO  HaplotypeCaller - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_292-b10
09:13:57.230 INFO  HaplotypeCaller - Start Date/Time: September 3, 2021 9:13:38 AM CST
09:13:57.230 INFO  HaplotypeCaller - ------------------------------------------------------------
09:13:57.230 INFO  HaplotypeCaller - ------------------------------------------------------------
09:13:57.232 INFO  HaplotypeCaller - HTSJDK Version: 2.16.1
09:13:57.232 INFO  HaplotypeCaller - Picard Version: 2.18.13
09:13:57.232 INFO  HaplotypeCaller - HTSJDK Defaults.COMPRESSION_LEVEL : 2
09:13:57.232 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
09:13:57.232 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
09:13:57.232 INFO  HaplotypeCaller - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
09:13:57.233 INFO  HaplotypeCaller - Deflater: IntelDeflater
09:13:57.233 INFO  HaplotypeCaller - Inflater: IntelInflater
09:13:57.233 INFO  HaplotypeCaller - GCS max retries/reopens: 20
09:13:57.233 INFO  HaplotypeCaller - Requester pays: disabled
09:13:57.233 INFO  HaplotypeCaller - Initializing engine
09:13:59.096 INFO  IntervalArgumentCollection - Processing 818575866 bp from intervals
09:13:59.161 INFO  HaplotypeCaller - Done initializing engine
09:13:59.164 INFO  HaplotypeCallerEngine - Tool is in reference confidence mode and the annotation, the following changes will be made to any specified annotations: 'StrandBiasBySample' will be enabled. 'ChromosomeCounts', 'FisherStrand', 'StrandOddsRatio' and 'QualByDepth' annotations have been disabled
09:13:59.598 INFO  HaplotypeCallerEngine - Standard Emitting and Calling confidence set to 0.0 for reference-model confidence output
09:14:00.256 INFO  HaplotypeCallerEngine - All sites annotated with PLs forced to true for reference-model confidence output
09:14:00.284 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/share/home/chenwei/biosoft/gatk-4.0.10.1/gatk-package-4.0.10.1-local.jar!/com/intel/gkl/native/libgkl_utils.so
09:14:00.312 INFO  PairHMM - OpenMP multi-threaded AVX-accelerated native PairHMM implementation is not supported
09:14:00.312 WARN  PairHMM - ***WARNING: Machine does not have the AVX instruction set support needed for the accelerated AVX PairHmm. Falling back to the MUCH slower LOGLESS_CACHING implementation!
09:14:00.595 INFO  ProgressMeter - Starting traversal
09:14:00.596 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Regions Processed   Regions/Minute
09:14:12.096 INFO  ProgressMeter -             D01:2563              0.2                    20            104.3
09:14:24.689 WARN  DepthPerSampleHC - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
09:14:24.690 WARN  StrandBiasBySample - Annotation will not be calculated, genotype is not called or alleleLikelihoodMap is null
09:14:24.884 INFO  ProgressMeter -            D01:10031              0.4                    60            148.2
09:14:36.441 INFO  ProgressMeter -            D01:19554              0.6                   130            217.6
09:14:51.359 INFO  ProgressMeter -            D01:21053              0.8                   140            165.5
09:15:02.193 INFO  ProgressMeter -            D01:34263              1.0                   220            214.3
09:15:13.398 INFO  ProgressMeter -            D01:56554              1.2                   360            296.7
09:15:30.110 INFO  ProgressMeter -            D01:64506              1.5                   410            274.8
09:15:52.270 INFO  ProgressMeter -            D01:67714              1.9                   430            231.0
09:16:02.342 INFO  ProgressMeter -            D01:78287              2.0                   520            256.3
09:16:52.817 INFO  ProgressMeter -           D01:106965              2.9                   690            240.4
09:17:09.091 INFO  ProgressMeter -           D01:135175              3.1                   860            273.7
09:17:32.003 INFO  ProgressMeter -           D01:149928              3.5                   970            275.3
09:17:55.133 INFO  ProgressMeter -           D01:151229              3.9                   980            250.7
09:18:06.184 INFO  ProgressMeter -           D01:177386              4.1                  1150            281.0
09:18:16.290 INFO  ProgressMeter -           D01:186634              4.3                  1210            283.9
09:18:26.473 INFO  ProgressMeter -           D01:200966              4.4                  1310            295.6
09:18:46.719 INFO  ProgressMeter -           D01:211678              4.8                  1400            293.6
09:19:00.194 INFO  ProgressMeter -           D01:220982              5.0                  1460            292.4
09:19:12.550 INFO  ProgressMeter -           D01:234061              5.2                  1550            298.1
09:19:22.847 INFO  ProgressMeter -           D01:245468              5.4                  1640            305.4
09:19:41.055 INFO  ProgressMeter -           D01:256802              5.7                  1720            303.1
09:19:53.832 INFO  ProgressMeter -           D01:264839              5.9                  1770            300.6
09:20:06.250 INFO  ProgressMeter -           D01:267762              6.1                  1790            293.7
09:20:22.129 INFO  ProgressMeter -           D01:274217              6.4                  1840            289.4
09:20:40.521 INFO  ProgressMeter -           D01:290971              6.7                  1950            292.6
09:20:55.248 INFO  ProgressMeter -           D01:298320              6.9                  2010            290.8

### Instructions

The github issue tracker is for bug reports, feature requests, and API documentation requests. General questions about how to use the GATK, how to interpret the output, etc. should be asked on the [official support forum](http://gatkforums.broadinstitute.org/gatk).
- Search the existing github issues to see if your issue (or something similar) has already been reported.  If the issue already exists, you may comment there to inquire about the progress.
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request** (for tool/class javadoc only -- for forum docs please post there)
- Consider if your "issue" is better addressed on the GATK forum: http://gatkforums.broadinstitute.org/gatk  Post there if you have questions about expected tool behavior, output format, unexpected results, or generally any question that does not fit into the categories above
- Use a **concise** yet **descriptive** title
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate
- Delete the other template blocks and this header.

----

### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

### Affected version(s)
- [ ] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

#### Expected behavior
_Tell us what should happen_

#### Actual behavior
_Tell us what happens instead_

----

### Tool(s) or class(es) involved
_Tool/class name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) or class(es) involved
_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by Chenwei-cri** [comment]
For chromosome D01 , Current Locus was different between two runs,is it normal condition?

**Comment by gokalpcelik** [comment]
HaplotypeCaller does not resume from where it stopped. If you need to perform the same task again restart the whole task using the very same commandline.

**Comment by Chenwei-cri** [comment]
Now I see. Thanks!
