### ISSUE TITLE
HaplotypeCaller step interruption

### ISSUE THREAD

**Issue by kuangtianhui** [broadinstitute/gatk#7461]
Dear Author，

My gatk is gatk4-4.2.1.0-0. When my scripts run at HaplotypeCaller step, the process was interrupt for ram  dificient. If I run HaplotypeCaller only,  whether the gvcf file product last run will be overwritten? Or I should delete the last gvcf file, than starting HaplotypeCaller step again?
 
Best wishes,
Tian-hui Kuang

**Comment by jamesemery** [comment]
Hello @kuangtianhui. Sorry to hear that you had a failure. Generally you should not have to worry, if you rerun the same inputs with more RAM available GATK should happily overwrite the incomplete output files leftover from the last run. It doesn't hurt to delete them yourself to be sure. For future reference if you have questions of this nature that aren't related to bugs or feature requests you should direct them to our user forums where we have moderators and other users that will be able to answer your questions about how to run our tools correctly: https://gatk.broadinstitute.org/hc/en-us/community/topics.
