### ISSUE TITLE
GATK 4.2.2.0 bug GenotypeGVCFs error IndexOutOfBoundsException

### ISSUE THREAD

**Issue by GATKSupportTeam** [broadinstitute/gatk#7465]
This issue came up on the forum and Ted Brookings took a look at the stack trace to verify that it is most likely not an issue with the input data. The user also specified that they did not get this issue with GATK 4.2.0.0.

This request was created from a contribution made by Quentin Chartreux on September 10, 2021 12:27 UTC.

Link: [https://gatk.broadinstitute.org/hc/en-us/community/posts/4406578679195-GenotypeGVCFs-error-IndexOutOfBoundsException](https://gatk.broadinstitute.org/hc/en-us/community/posts/4406578679195-GenotypeGVCFs-error-IndexOutOfBoundsException)

\--

I try to perform joint genotyping with genotypeGVCF. 

Before i run haplotypecaller then Genomicsdbiimport and now genotypesGVCF. 

I used gatk 4.2.2.0. 

I run Genomicsdbiimport by interval so i would like to perform genotypesGVCF by interval. 

the command use for genotypesgvcf is : 

gatk \\  
  
\--java-options "-Xmx${memory\_java}M -Xms${memory\_java}M -XX:ParallelGCThreads=${SLURM\_CPUS\_PER\_TASK}" \\  
  
GenotypeGVCFs \\  
  
\-R ${REF\_Genome} \\  
  
\-V gendb://${vcf\_database\_tmp} \\  
  
\-O ${TMP\_DIR}/gentaumix\_interval\_${SLURM\_ARRAY\_TASK\_ID}\_raw.vcf.gz \\  
  
\-D ${DBSNP} \\  
  
\--sequence-dictionary ${Dict} \\  
  
\-L ${Interval} \\  
  
\-G StandardAnnotation -G AS\_StandardAnnotation \\  
  
\--only-output-calls-starting-in-intervals \\  
  
\--merge-input-intervals \\  
  
2> ${log\_DIR}/Interval\_${SLURM\_ARRAY\_TASK\_ID}

And the log (for one interval but it's the same for all): 

Using GATK jar /shared/ifbstor1/projects/gentaumix/conda/envs/gatk\_4.2.2.0/share/gatk4-4.2.2.0-0/gatk-package-4.2.2.0-local.jar  
  
Running:  
  
java -Dsamjdk.use\_async\_io\_read\_samtools=false -Dsamjdk.use\_async\_io\_write\_samtools=true -Dsamjdk.use\_async\_io\_write\_tribble=false -Dsamjdk.compression\_level=2 -Xmx7000M -Xms7000M -XX:ParallelGCThreads=2 -jar /shared/ifbstor1/projects/gentaumix/conda/envs/gatk\_4.2.2.0/share/gatk4-4.2.2.0-0/gatk-package-4.2.2.0-local.jar GenotypeGVCFs -R /shared/projects/gentaumix/Ressources/grch38\_BWA\_2/GCA\_000001405.15\_GRCh38\_no\_alt\_plus\_hs38d1\_analysis\_set.fa -V gendb:///tmp/tmp.6QEyWPGpWs/vcf\_database/Interval\_6 -O /tmp/tmp.6QEyWPGpWs/gentaumix\_interval\_6\_raw.vcf.gz -D /shared/projects/gentaumix/Ressources/known\_sites/Homo\_sapiens\_assembly38.dbsnp138.vcf --sequence-dictionary /shared/projects/gentaumix/Ressources/known\_sites/Homo\_sapiens\_assembly38.dict -L /shared/projects/gentaumix/Ressources/interval\_genomicsdbi/temp\_6/interval.interval\_list -G StandardAnnotation -G AS\_StandardAnnotation --merge-input-intervals  
  
14:17:35.171 WARN GATKAnnotationPluginDescriptor - Redundant enabled annotation group (StandardAnnotation) is enabled for this tool by default  
  
14:17:35.232 INFO NativeLibraryLoader - Loading libgkl\_compression.so from jar:file:/shared/ifbstor1/projects/gentaumix/conda/envs/gatk\_4.2.2.0/share/gatk4-4.2.2.0-0/gatk-package-4.2.2.0-local.jar!/com/intel/gkl/native/libgkl\_compression.so  
  
Sep 10, 2021 2:17:35 PM shaded.cloud\_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine  
  
INFO: Failed to detect whether we are running on Google Compute Engine.  
  
14:17:35.492 INFO GenotypeGVCFs - ------------------------------------------------------------  
  
14:17:35.492 INFO GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.2.2.0  
  
14:17:35.492 INFO GenotypeGVCFs - For support and documentation go to [https://software.broadinstitute.org/gatk/](https://software.broadinstitute.org/gatk/)  
  
14:17:35.493 INFO GenotypeGVCFs - Executing as quentin67100@cpu-node-9 on Linux v3.10.0-1160.6.1.el7.x86\_64 amd64  
  
14:17:35.493 INFO GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v1.8.0\_282-b08  
  
14:17:35.493 INFO GenotypeGVCFs - Start Date/Time: 10 septembre 2021 14:17:35 CEST  
  
14:17:35.493 INFO GenotypeGVCFs - ------------------------------------------------------------  
  
14:17:35.494 INFO GenotypeGVCFs - ------------------------------------------------------------  
  
14:17:35.495 INFO GenotypeGVCFs - HTSJDK Version: 2.24.1  
  
14:17:35.495 INFO GenotypeGVCFs - Picard Version: 2.25.4  
  
14:17:35.495 INFO GenotypeGVCFs - Built for Spark Version: 2.4.5  
  
14:17:35.495 INFO GenotypeGVCFs - HTSJDK Defaults.COMPRESSION\_LEVEL : 2  
  
14:17:35.495 INFO GenotypeGVCFs - HTSJDK Defaults.USE\_ASYNC\_IO\_READ\_FOR\_SAMTOOLS : false  
  
14:17:35.495 INFO GenotypeGVCFs - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_SAMTOOLS : true  
  
14:17:35.495 INFO GenotypeGVCFs - HTSJDK Defaults.USE\_ASYNC\_IO\_WRITE\_FOR\_TRIBBLE : false  
  
14:17:35.495 INFO GenotypeGVCFs - Deflater: IntelDeflater  
  
14:17:35.496 INFO GenotypeGVCFs - Inflater: IntelInflater  
  
14:17:35.496 INFO GenotypeGVCFs - GCS max retries/reopens: 20  
  
14:17:35.496 INFO GenotypeGVCFs - Requester pays: disabled  
  
14:17:35.496 INFO GenotypeGVCFs - Initializing engine  
  
14:17:36.493 INFO FeatureManager - Using codec VCFCodec to read file file:///shared/projects/gentaumix/Ressources/known\_sites/Homo\_sapiens\_assembly38.dbsnp138.vcf  
  
14:17:38.548 INFO GenomicsDBLibLoader - GenomicsDB native library version : 1.4.1-d59e886  
  
14:17:39.941 info NativeGenomicsDB - pid=12231 tid=12232 No valid combination operation found for INFO field AS\_InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records  
  
14:17:39.941 info NativeGenomicsDB - pid=12231 tid=12232 No valid combination operation found for INFO field AS\_QD - the field will NOT be part of INFO fields in the generated VCF records  
  
14:17:39.941 info NativeGenomicsDB - pid=12231 tid=12232 No valid combination operation found for INFO field InbreedingCoeff - the field will NOT be part of INFO fields in the generated VCF records  
  
14:17:39.941 info NativeGenomicsDB - pid=12231 tid=12232 No valid combination operation found for INFO field MLEAC - the field will NOT be part of INFO fields in the generated VCF records  
  
14:17:39.941 info NativeGenomicsDB - pid=12231 tid=12232 No valid combination operation found for INFO field MLEAF - the field will NOT be part of INFO fields in the generated VCF records  
  
14:17:41.513 INFO FeatureManager - Using codec IntervalListCodec to read file file:///shared/projects/gentaumix/Ressources/interval\_genomicsdbi/temp\_6/interval.interval\_list  
  
14:17:41.628 INFO IntervalArgumentCollection - Processing 62000000 bp from intervals  
  
14:17:41.743 INFO GenotypeGVCFs - Done initializing engine  
  
14:17:41.897 INFO ProgressMeter - Starting traversal  
  
14:17:41.898 INFO ProgressMeter - Current Locus Elapsed Minutes Variants Processed Variants/Minute  
  
14:17:52.020 INFO ProgressMeter - chr2:60009645 0.2 9000 53349.1  
  
14:18:02.071 INFO ProgressMeter - chr2:60039632 0.3 37000 110048.1  
  
14:18:02.683 INFO GenotypeGVCFs - Shutting down engine  
  
GENOMICSDB\_TIMER,GenomicsDB iterator next() timer,Wall-clock time(s),5.257768857000008,Cpu time(s),5.221303873999989  
  
\[10 septembre 2021 14:18:02 CEST\] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 0.46 minutes.  
  
Runtime.totalMemory()=7034372096  
  
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0  
  
at java.util.ArrayList.rangeCheck(ArrayList.java:659)  
  
at java.util.ArrayList.get(ArrayList.java:435)  
  
at org.broadinstitute.hellbender.tools.walkers.annotator.allelespecific.StrandBiasUtils.combineAttributeMap(StrandBiasUtils.java:120)  
  
at org.broadinstitute.hellbender.tools.walkers.annotator.allelespecific.AS\_StrandBiasTest.combineRawData(AS\_StrandBiasTest.java:118)  
  
at org.broadinstitute.hellbender.tools.walkers.annotator.VariantAnnotatorEngine.combineAnnotations(VariantAnnotatorEngine.java:234)  
  
at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.mergeAttributes(ReferenceConfidenceVariantContextMerger.java:318)  
  
at org.broadinstitute.hellbender.tools.walkers.ReferenceConfidenceVariantContextMerger.merge(ReferenceConfidenceVariantContextMerger.java:142)  
  
at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFsEngine.callRegion(GenotypeGVCFsEngine.java:130)  
  
at org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs.apply(GenotypeGVCFs.java:281)  
  
at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$0(VariantLocusWalker.java:135)  
  
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)  
  
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)  
  
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)  
  
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)  
  
at java.util.Iterator.forEachRemaining(Iterator.java:116)  
  
at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)  
  
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)  
  
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)  
  
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)  
  
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)  
  
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)  
  
at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:490)  
  
at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:132)  
  
at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1085)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)  
  
at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)  
  
at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)  
  
at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)  
  
at org.broadinstitute.hellbender.Main.main(Main.java:289)

For information the command used for haplotype caller and genomicsdbiimport are : 

srun --ntasks=1 gatk --java-options "-Xmx${SLURM\_MEM\_PER\_CPU}M" HaplotypeCaller \\  
  
\-R ${REF\_Genome} \\  
  
\-L ${Scattered\_DIR}/temp\_${i}\_of\_${SCATTER\_COUNT}/scattered.interval\_list \\  
  
\-I ${BAM\_INPUT\_DIR}/${BAM\_INPUT} \\  
  
\-O ${temp\_gVCF\_OUTPUT\_DIR}/${i}.${GVCF\_OUTPUT} \\  
  
\-G StandardAnnotation -G AS\_StandardAnnotation -G StandardHCAnnotation \\  
  
\-GQB 10 -GQB 20 -GQB 30 -GQB 40 -GQB 50 -GQB 60 -GQB 70 -GQB 80 -GQB 90 \\  
  
\-ERC GVCF \\  
  
\--pcr-indel-model NONE \\  
  
2> ${logs\_HC}/${i}.${GVCF\_OUTPUT}.log &

and 

gatk --java-options "-Xmx${memory\_java}M -Xms${memory\_java}M -XX:ParallelGCThreads=${SLURM\_CPUS\_PER\_TASK}" GenomicsDBImport \\  
  
\--sample-name-map ${cohort\_map} \\  
  
\--genomicsdb-workspace-path ${VCF\_database\_DIR\_tmp}/Interval\_${SLURM\_ARRAY\_TASK\_ID} \\  
  
\--batch-size 74 \\  
  
\--reader-threads ${SLURM\_CPUS\_PER\_TASK} \\  
  
\-L ${Interval} \\  
  
\--tmp-dir ${TMP\_DIR} \\  
  
\--genomicsdb-shared-posixfs-optimizations \\  
  
2> ${logs\_DIR}/Interval\_${SLURM\_ARRAY\_TASK\_ID}.log<br><br><i>(created from <a href='https://broadinstitute.zendesk.com/agent/tickets/186539'>Zendesk ticket #186539</a>)<br>gz#186539</i>

**Comment by gbrandt6** [comment]
User reported the issue has been solved.
