### ISSUE TITLE
GATK Funcotator [SQLITE_IOERR_LOCK]  I/O error in the advisory file locking logic (disk I/O error)

### ISSUE THREAD

**Issue by CromitDolores0808** [broadinstitute/gatk#7474]
## Bug Report
18:47:11.757 INFO  Funcotator - Shutting down engine
[September 19, 2021 6:47:11 PM CST] org.broadinstitute.hellbender.tools
.funcotator.Funcotator done. Elapsed time: 0.13 minutes.
Runtime.totalMemory()=1885339648
**org.broadinstitute.hellbender.exceptions.GATKException: Unable to query
 the database for geneName: WASH7P**
      ....
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.ins
tanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.ins
tanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Mai
n.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
**Caused by: org.sqlite.SQLiteException: [SQLITE_IOERR_LOCK]  I/O error i
n the advisory file locking logic (disk I/O error)**
        at org.sqlite.core.DB.newSQLException(DB.java:909)
### Affected version(s)
GATK 4.1.9.0

### Description 
GATK Funcotator [SQLITE_IOERR_LOCK]  I/O error in the advisory file locking logic (disk I/O error)

I downloaded the  data-sources by "gsutil cp gs://broad-public-datasets/funcotator/funcotator_dataSources.v1.7.20200521s.tar.gz .".  I can't find useful information for this error. Thank you.

#### Steps to reproduce
Using GATK jar /lustre1/ruibinxi_pkuhpc/ljx/software/gatk-4.1.9.0/gatk-
package-4.1.9.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_i
o_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjd
k.compression_level=2 -jar /lustre1/ruibinxi_pkuhpc/ljx/software/gatk-4
.1.9.0/gatk-package-4.1.9.0-local.jar Funcotator -R /home/ruibinxi_pkuh
pc/lustre1/ljx/reference_genomes/hg38_bwa/hg38.fa -V /home/ruibinxi_pku
hpc/lustre1/ljx/data/raodn/WES/GATK/P14P_filtered.vcf.gz -O /home/ruibi
nxi_pkuhpc/lustre1/ljx/data/raodn/WES/GATK/P14P_filtered_funcotator.maf
 --output-file-format MAF --data-sources-path /home/ruibinxi_pkuhpc/lus
tre1/ljx/reference_genomes/funcotator_dataSources.v1.7.20200521s/ --ref
-version hg38

**Comment by jonn-smith** [comment]
I believe this is an issue with the `lustre` filesystem (it doesn't seem to support locking).  Others have reported this kind of issue with sqlite as well (https://github.com/CGATOxford/CGATPipelines/issues/39).

Unfortunately, I'm not aware of any way to fix the issue itself while using `lustre`.

However, you can move the funcotator data sources to a local disk and it should work fine.
