### ISSUE TITLE
CombineGVCFS

### ISSUE THREAD

**Issue by Dream-sugar** [broadinstitute/gatk#7482]
Teacher, may I ask you a question? Hello, I have a lot of samples. When merging multiple gvcf into one file, there is not enough memory. Can I merge them into several VCFS first, and then merge these VCF files?

**Comment by droazen** [comment]
@Dream-sugar That approach should work, yes -- you should post this on our user forum (https://gatk.broadinstitute.org/hc/en-us/community/topics) for further assistance in setting up such a pipeline.
