### ISSUE TITLE
GATK error ：OSError: [Errno 8] Exec format error: 'java'

### ISSUE THREAD

**Issue by xhxlilium** [broadinstitute/gatk#7484]
I have run :
gatk  MarkDuplicates -MAX_FILE_HANDLES 1000 -I ERR036185_sort.bam -O ERR036185_mark.bam -M ERR036185_mark_metrics.txt

but raise an error:OSError: [Errno 8] Exec format error: 'java'
i don‘t know why this error raise, as I can successfully run the command "gatk" without error,but if "gatk  MarkDuplicates", the error raised again

**Comment by droazen** [comment]
@xhxlilium This error indicates that the version of Java you've installed on your system does not match the CPU architecture -- for example, the Intel version of the JDK on an ARM system. Can you confirm that you've installed the correct JDK for your system?
