### ISSUE TITLE
Branch builds are no longer getting skipped in travis

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#7536]
It appears that both the "branch" and "PR" builds are always running the complete test suite in travis. We had added a check in previously to skip the "branch" builds to save on costs.

Here's an example:
https://github.com/broadinstitute/gatk/pull/7533

**Comment by droazen** [comment]
@lbergelson ^^

**Comment by lbergelson** [comment]
I suspect this instance is cause by the branch being pushed and then a pr being created after a small delay.  It gives the travis vms enough time to start and pass the check for "no pr exists".  Then the PR is created and it starts a pr build while the original branch build is still runnning.  I suspect a second push on this branch won't run the branch build again.  

There's a small window of time between pushing the commit and making the pr where the branch build will be skipped entirely, but it's reasonable to get 1 branch build when you push a new branch. 

It's also possible that I mangled the github key and the tests are always failing now.

**Comment by droazen** [comment]
@lbergelson Here's another example of a PR that's been up a while and been through several rounds of review, and yet in the latest travis builds the branch builds are still not getting skipped:

https://github.com/broadinstitute/gatk/pull/7511

**Comment by lbergelson** [comment]
Yeah, that one is suspicious...

**Comment by lbergelson** [comment]
Hmn.  I'm not sure what's going on.  The script seems to work locally.  I've reset the api token to a new one, maybe it was messed up?

**Comment by lbergelson** [comment]
@droazen I put a new github api token in and tested it here https://github.com/broadinstitute/gatk/pull/7537.  It successfully skipped.  I'm not sure what went wrong but I must have messed up the token when I rotated keys.  

Going to close this.  Reopen if you see this again going forward.  The token is set directly in travis so it propagates without a rebase.
