### ISSUE TITLE
Script for chromosome Y features

### ISSUE THREAD

**Issue by AlirezaTafazzoli** [broadinstitute/gatk#7547]
Hi, 
I'm looking for any shell script which may provide the Y chromosome structure information, gene names, number of repeated/duplicated genes, STRs list, etc. via Terminal.
Can anybody help me with that?

**Comment by droazen** [comment]
@AlirezaTafazzoli Sorry, this issue tracker is for GATK bug reports. You might try posting on a genomics forum.
