### ISSUE TITLE
Could not find biz.k11i:xgboost-predictor:0.3.0 **bug report**

### ISSUE THREAD

**Issue by mpage21** [broadinstitute/gatk#7636]
### Affected version(s)
- Latest master branch as of 1/12/2022

### Description 
When I tried to build from the github repo, I received the following error:

FAILURE: Build failed with an exception.

* Where:
Build file '/gatk/build.gradle' line: 688

* What went wrong:
A problem occurred evaluating root project 'gatk'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find biz.k11i:xgboost-predictor:0.3.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/biz/k11i/xgboost-predictor/0.3.0/xgboost-predictor-0.3.0.pom
       - https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot/biz/k11i/xgboost-predictor/0.3.0/xgboost-predictor-0.3.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/biz/k11i/xgboost-predictor/0.3.0/xgboost-predictor-0.3.0.pom
       - file:/root/.m2/repository/biz/k11i/xgboost-predictor/0.3.0/xgboost-predictor-0.3.0.pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

#### Steps to reproduce
`git clone https://github.com/broadinstitute/gatk.git`
`cd gatk/`
`./gradlew bundle`

**Comment by lbergelson** [comment]
Huh... That's not good.  I wonder if it's because we removed the jcenter repository resolver from the build.  Maybe local caches are hiding the problem for us.  

Could you try checkout out the branch `lb_add_back_jcenter` and seeing if that fixes the problem?

**Comment by mpage21** [comment]
Yup! I'll try that right now

**Comment by mpage21** [comment]
I was able to build it this time. Thank you!
