### ISSUE TITLE
Possible speed up when using SelectVariants?

### ISSUE THREAD

**Issue by kvn95ss** [broadinstitute/gatk#7671]
Hello,

We are working with ~1700 exome samples. The vcf file generated after joint genotyping is around 80 GB (uncompressed). When we are extracting samples from this master file, each extraction (regardless of singleton or trio exome) takes around 40-60 minutes. 

We are using gatk 4.1.8.0 for production, and we tried the latest gatk (4.2.5.0) but we saw roughly 10 min decrease in extraction time. We gzipped/indexed our vcf, we still see similar performance.

The variants / minute speed is ~50k. Any idea if our extraction rates are slow, or are we performing as expected?

For what its worth, our data is stored on a HDDs in RAID 5.

**Comment by droazen** [comment]
@kvn95ss Can you clarify whether the performance was **faster** in the newer version (4.2.5) compared to the older version? We did do some performance work in `SelectVariants` between 4.1.8 and 4.2.5.

Also, there are reports that `SelectVariants` is **much** slower if the sample names in the header are not sorted, because the tool has to reorder the genotypes on output if they're not sorted. Can you check whether your sample names are sorted?

**Comment by kvn95ss** [comment]
Thank you for writing back! To answer your questions - 
1. We did not see any noticable difference in extraction time (takes ~50 minutes per vcf)
2. The sample names in the header are sorted

I raised this issue on GATK forum as well - https://gatk.broadinstitute.org/hc/en-us/community/posts/4430247943451-Is-it-possible-to-speed-up-SelectVariants- and as mentioned in the thread, we have currently resorted to ```bcftools``` for extraction.

**Comment by cmnbroad** [comment]
@kvn95ss It looks like you're using `--exclude-non-variants` with SelectVariants, which can negatively impact performance. It would be interesting to know how much leaving that out changes things ,if thats an option for you.

**Comment by kvn95ss** [comment]
```--exclude-non-variants``` is actually important for us, so we hadn't considered turning it off.

**Comment by kvn95ss** [comment]
Hello, as indicated in our [community post over at GATK forum](https://gatk.broadinstitute.org/hc/en-us/community/posts/4430247943451-Is-it-possible-to-speed-up-SelectVariants-), we have moved over to ```bcftools``` for extracting samples. 

The only quirk we have noticed is the incorrect INFO/DP values, where select variants would encode values on per-sample basis while bcftools would copy over the INFO/DP from the bigger vcf file. That being said, the FORMAT/DP is encoded with the correct per-sample value, so it doesn't affect our downstream analysis. 

To further speed up the extraction, we have used bcf file format instead of vcf. With uncompressed bcf, the 80 GB vcf file goes down to ~9 GB. Here's how much we have sped up extraction times - 

1. ```SelectVariants``` from GATK on vcf file of 100 GB - ~50 minutes
2. ```bcftools``` on vcf file of 100 GB - ~15 minutes
3. ```bcftools``` on ```bcf``` file of 10 GB - ~5 minutes

So in the end, we dropped extraction times from ~50 minutes to ~5 minutes.

**Comment by lbergelson** [comment]
Wow... we should fix that.

**Comment by lbergelson** [comment]
I suspect in our case we're doing additional work fixing up annotations after subsetting which it sounds like bcftools just ignores.  If bcftools is essentially just cutting by column ten it's going to be hard to catch them.  There is probably a lot we can do to get much closer though.

**Comment by kvn95ss** [comment]
FYI, and this is mentioned in later comment on my linked GATK forum post as well, the only difference we could find was the discrepancy between INFO/DP and FORMAT/DP, rest of the values are identical.
