### ISSUE TITLE
Simple way to have VariantsToTable output all fields. Just want the entire VCF as a table.

### ISSUE THREAD

**Issue by abalter** [broadinstitute/gatk#7677]
I'm trying, for example,

`gatk VariantsToTable -V clinvar.vcf -O clinvar.tsv`

It goes through the motions and displays progress. The output file is created, and it has the right number of lines. But the lines are all empty!

Maybe add a default value to the `-F` switch?

**Comment by abalter** [comment]
@droazen -- is there a way to simply list all the possible fields in the header? Then I could use that list to create an input for the `-F` flag.

**Comment by droazen** [comment]
@abalter The complete list of fields should be present in the VCF header, but unfortunately I don't know of a convenient way to extract them apart from the manual method. It would be pretty simple to write a script or GATK tool to parse the VCF header and list all the fields, but the best solution would be to patch the `VariantToTable` to default `-F` to all the fields, as discussed above.

**Comment by slagelwa** [comment]
> @abalter The complete list of fields should be present in the VCF header

Key word here is "should be", which isn't always the case.
