### ISSUE TITLE
CombineGVCFs auto-generated workflow is missing vcf indices as inputs

### ISSUE THREAD

**Issue by rickymagner** [broadinstitute/gatk#7681]
### Affected tool(s) or class(es)
CombineGVCFs

### Affected version(s)
- [X] Latest public release version [4.2.5.0]
- [ ] Latest master branch as of [date of test?]

### Description 
The auto-generated wdl for CombineGVCFs on dockstore won't work because it doesn't have any inputs for the indices of the input vcfs. This means GATK cannot access the vcf indices because they never get localized, so the workflow fails. 

#### Steps to reproduce
Take any vcfs and run them through the workflow to get an error about missing indices. 

#### Expected behavior
Including the indices in the task inputs will allow them to get localized along with the vcfs so GATK can operate normally. 

#### Actual behavior
You get an error saying it requires index files to proceed.

**Comment by cmnbroad** [comment]
For variant inputs, there is no actual arg corresponding to the index inputs (like there is for read inputs), so for variants the index needs to be added to the input annotation as a companion file.
