### ISSUE TITLE
how to multithread mutect2 process ?

### ISSUE THREAD

**Issue by mtariqsajid** [broadinstitute/gatk#7688]
can any one please help me how to speedup mutect2 
I have 40 core processor and 96gb ram

but mutect2 use 4 threads only and around 1gb ram
`./gatk Mutect2 -R cs_ref.fa -I cs_cr_mapped_AORRG_sorted_dedup.bam -O cs_cr_mapped_AORRG_sorted_dedup2.vcf`

**Comment by DarioS** [comment]
It is not designed to enable you to do that. It uses a scatter-gather approach for parallelism. You'll want to submit multiple tasks that each process a disjoint interval of the genome. Personally, I have wondered how Mutect2 performs for variants at the borders of interval boundaries.

**Comment by your-highness** [comment]
On scatter-gather see here: https://gatk.broadinstitute.org/hc/en-us/articles/360035532012-Parallelism-Multithreading-Scatter-Gather

Best to scatter by chromosome - so no interval boundaries per definition exist.

**Comment by droazen** [comment]
Closing as answered
