### ISSUE TITLE
Block compressed gVCF file is rejected by GenomicsDBImport --bypass-feature-reader due to non-standard file extension

### ISSUE THREAD

**Issue by lessdata** [broadinstitute/gatk#7691]
### Affected tool(s) or class(es)
GenomicsDBImport

### Affected version(s)
- [ ] Latest public release version [4.2.5.0]

### Description 
My gVCF files are block compressed and indexed, but the files have the file extension ".gvcf.gz" rather than ".vcf.gz". When I run `GenomicsDBImport` with `--bypass-feature-reader`, the ".gvcf.gz" file cannot be recognized as a block compressed vcf file. The code of `GenomicsDBImport` validates if input is block compressed by checking if the file extension is ".vcf.gz".

```
    private static void assertVariantFileIsCompressedAndIndexed(final Path path) {
        if (!path.toString().toLowerCase().endsWith(FileExtensions.COMPRESSED_VCF)) {
            throw new UserException("Input variant files must be block compressed vcfs when using " +
                BYPASS_FEATURE_READER + ", but " + path.toString() + " does not appear to be");
        }
        Path indexPath = path.resolveSibling(path.getFileName() + FileExtensions.COMPRESSED_VCF_INDEX);
        IOUtils.assertFileIsReadable(indexPath);
    }
```

I understand that this is an issue on my side because I did not name my gVCF files with the standard extension ".vcf.gz". Is it possible to make this check less stringent in a future release? Maybe make any ".gz"/".bgz" file acceptable, or check the ".tbi" index file to identify block compression (existing index typically means the file is block compressed and indexed). 

Thank you. 

----

**Comment by droazen** [comment]
@lessdata In many cases we need to rely on the file extensions to check the file format, because actually opening the files and reading the first few bytes to determine the format gets expensive when the files are hosted in the cloud and there are many VCFs. I do agree that this error message could be improved, however -- it should mention the file extensions that are allowed.
