### ISSUE TITLE
Option to not run VariantRecalibrator's Rscript

### ISSUE THREAD

**Issue by ning-y** [broadinstitute/gatk#7697]
### Instructions

The github issue tracker is for bug reports, feature requests, and API documentation requests. General questions about how to use the GATK, how to interpret the output, etc. should be asked on the [official support forum](http://gatkforums.broadinstitute.org/gatk).
- Search the existing github issues to see if your issue (or something similar) has already been reported.  If the issue already exists, you may comment there to inquire about the progress.
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request** (for tool/class javadoc only -- for forum docs please post there)
- Consider if your "issue" is better addressed on the GATK forum: http://gatkforums.broadinstitute.org/gatk  Post there if you have questions about expected tool behavior, output format, unexpected results, or generally any question that does not fit into the categories above
- Use a **concise** yet **descriptive** title
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate
- Delete the other template blocks and this header.

----

### Tool(s) or class(es) involved

VariantRecalibrator

### Description

VariantRecalibrator automatically runs the generated Rscript to produce recalibration plots.

This is usually good and convenient, but it requires that all *R* dependencies must be installed in the same environment in the current running GATK environment. This is not necessarily the case for sandbox-based package managers e.g. docker or conda.

A viable fix on the user's side is to include R dependencies with GATK in e.g. docker or conda. But I think I would prefer if my packages were as independent of each other as possible. It would be great if **VariantRecalibrator had an option to write but not run the Rscript for recalibration plots.** Then, the user can call the Rscript in an appropriate e.g. R conda environment or docker image.

**Comment by droazen** [comment]
@ning-y This is a very reasonable suggestion -- but are you not able to run the official GATK docker image or conda environment when running this tool?

**Comment by ning-y** [comment]
I use the conda package [bioconda/gatk4 (version 4.2.5.0)](https://bioconda.github.io/recipes/gatk4/README.html), but from memory that conda package does not include the necessary R dependencies --- I could be wrong, though!
