### ISSUE TITLE
CombineGVCFs: KEY END found in VariantContext field INFO but this key isn't defined in the VCFHeader.

### ISSUE THREAD

**Issue by sunjh22** [broadinstitute/gatk#7728]
----

### Affected tool(s) or class(es)
gatk CombineGVCFs

### Affected version(s)
- [v4.1.8.1]

### Description 
When I am using CombineGVCFs to join the two raw_variants.vcf files derived from HaplotypeCaller, it throws an error: KEY END found in VariantContext field INFO at chr1:20094 but this key isn't defined in the VCFHeader. However, when I checked original files, there is no KEY END in INFO.

#### Steps to reproduce
The command line I used is:
`~/biosoft/gatk-4.1.8.1/gatk --jave-options "-Xmx30G" CombineGVCFs -R ${REF} -V first_raw_variants.vcf -V second_variants.vcf -O cohort.g.vcf.gz`
In which, ${REF} refers to the human reference file.

#### Expected behavior
It should return a combined gvcf file

#### Actual behavior
An error happened, as described in above.

----

**Comment by droazen** [comment]
@sunjh22 Are your input VCFs GVCFs (which do have an END attribute), or normal VCFs (which don't have the END attribute)? If they are normal VCFs, you can't use `CombineGVCFs` to combine them, as that tool only takes GVCFs as input.

**Comment by sunjh22** [comment]
@droazen Thank you so much for the reminder! I forgot to add the `-ERC GVCF` (GVCF mode) in `HaplotypeCaller`. I tried again and it worked well this time! Thanks again. I will close this session now.
