### ISSUE TITLE
An argument of GetPileupSummaries maybe redundant in Mutect2.wdl ?

### ISSUE THREAD

**Issue by gudeqing** [broadinstitute/gatk#7731]
Hi, 

 In the Mutect2.wdl file,  the section of task definition for M2, I found the following argument maybe redundant, but I am not quite sure.

 -L ~{variants_for_contamination} 

Best regards!

**Comment by droazen** [comment]
@davidbenjamin Can you comment on this? Is this argument actually redundant?

**Comment by davidbenjamin** [comment]
@gudeqing I think you are referrring to the calls to `GetPileupSummaries`, where we have both `-L` and `-V` arguments with the same variable.  This is actually not redundant, though I admit it is clumsy.  This is a consequence of `GetPileupSummaries` being written as a GATK `LocusWalker`, which is necessary for optimal performance.
