### ISSUE TITLE
Mutect2: Attempt to create a bai entry for an unmapped slice with unexpected alignment start (0) or span (-2147483647) values

### ISSUE THREAD

**Issue by carbocation** [broadinstitute/gatk#7755]
### Affected tool(s) or class(es)
Mutect2

### Affected version(s)
GATK version 4.2.5.0, run from the `us.gcr.io/broad-gatk/gatk:4.2.5.0` docker image.

### Description 
Rarely (~0.1%) within exomes that were sequenced at Broad (by GP), we encounter the error message whose stack trace is shown below. This occurs during batch processing, but it is specific to the .CRAM files: running Mutect2 on the same file produces the same error, and running Mutect2 on other files with the same arguments works fine. The files that trigger this error have contents that match the Broad GP-produced .md5 checksum, and they also pass `samtools quickcheck`.

#### Steps to reproduce
(The variables are filled in as one might reasonably expect.)
```sh
/gatk/gatk --java-options "-Xmx${RAM}G" \
    Mutect2 \
    --input ${cram} \
    --reference ${REFERENCE_FASTA} \
    --panel-of-normals ${PON} \
    --germline-resource ${GNOMAD} \
    --intervals ${INTERVALS} \
    --output ${unfiltered}
```

#### Expected behavior
In all other cases, somatic variant calling proceeds successfully.

#### Actual behavior
```
00:17:31.944 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.2.5.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
00:17:32.225 INFO  Mutect2 - ------------------------------------------------------------
00:17:32.226 INFO  Mutect2 - The Genome Analysis Toolkit (GATK) v4.2.5.0
00:17:32.226 INFO  Mutect2 - For support and documentation go to https://software.broadinstitute.org/gatk/
00:17:32.227 INFO  Mutect2 - Executing as root@8d398eecd56e on Linux v5.10.90+ amd64
00:17:32.227 INFO  Mutect2 - Java runtime: OpenJDK 64-Bit Server VM v1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
00:17:32.228 INFO  Mutect2 - Start Date/Time: April 5, 2022 12:17:31 AM GMT
00:17:32.228 INFO  Mutect2 - ------------------------------------------------------------
00:17:32.228 INFO  Mutect2 - ------------------------------------------------------------
00:17:32.229 INFO  Mutect2 - HTSJDK Version: 2.24.1
00:17:32.230 INFO  Mutect2 - Picard Version: 2.25.4
00:17:32.230 INFO  Mutect2 - Built for Spark Version: 2.4.5
00:17:32.231 INFO  Mutect2 - HTSJDK Defaults.COMPRESSION_LEVEL : 2
00:17:32.231 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
00:17:32.231 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
00:17:32.232 INFO  Mutect2 - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
00:17:32.232 INFO  Mutect2 - Deflater: IntelDeflater
00:17:32.232 INFO  Mutect2 - Inflater: IntelInflater
00:17:32.233 INFO  Mutect2 - GCS max retries/reopens: 20
00:17:32.233 INFO  Mutect2 - Requester pays: disabled
00:17:32.233 INFO  Mutect2 - Initializing engine
00:17:33.373 INFO  Mutect2 - Shutting down engine
[April 5, 2022 12:17:33 AM GMT] org.broadinstitute.hellbender.tools.walkers.mutect.Mutect2 done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=361234432
htsjdk.samtools.cram.CRAMException: Attempt to create a bai entry for an unmapped slice with unexpected alignment start (0) or span (-2147483647) values
	at htsjdk.samtools.cram.BAIEntry.<init>(BAIEntry.java:60)
	at htsjdk.samtools.cram.BAIEntry.<init>(BAIEntry.java:83)
	at htsjdk.samtools.cram.CRAIIndex.openCraiFileAsBaiStream(CRAIIndex.java:89)
	at htsjdk.samtools.SamIndexes.asBaiSeekableStreamOrNull(SamIndexes.java:91)
	at htsjdk.samtools.CRAMFileReader.initWithStreams(CRAMFileReader.java:203)
	at htsjdk.samtools.CRAMFileReader.<init>(CRAMFileReader.java:194)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:432)
	at htsjdk.samtools.SamReaderFactory.open(SamReaderFactory.java:106)
	at org.broadinstitute.hellbender.engine.ReadsPathDataSource.<init>(ReadsPathDataSource.java:245)
	at org.broadinstitute.hellbender.engine.ReadsPathDataSource.<init>(ReadsPathDataSource.java:181)
	at org.broadinstitute.hellbender.engine.GATKTool.initializeReads(GATKTool.java:452)
	at org.broadinstitute.hellbender.engine.GATKTool.onStartup(GATKTool.java:724)
	at org.broadinstitute.hellbender.engine.AssemblyRegionWalker.onStartup(AssemblyRegionWalker.java:79)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:138)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
	at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
	at org.broadinstitute.hellbender.Main.main(Main.java:289)
```

**Comment by carbocation** [comment]
Interesting. The CRAI file itself (when you gunzip it) appears normal although I don't have an md5 from GP for the CRAI (just for the CRAM). I suppose I can't rule out a bitflip somewhere. I don't know which software GP uses to produce CRAI files and since they lack a header, I'm not sure I'll be able to find out.

Having reindexed it with `samtools index` (v1.7, htslib 1.7-2), and then diffing my gunzipped crai vs the original crai, I think I see the offending line:

```
# Original .crai:
-1	0	-2147483647	710543306	480	278484

# samtools-1.7 .crai:
-1	0	1	710543306	480	278484
```

I'll ping our Broad GP contact to see if they can identify an issue in their pipeline.

**Comment by cmnbroad** [comment]
Yes, thats almost certainly created by an older CRAM implementation (possibly htsjdk/gatk/picard) rather than a random bitflip.

**Comment by carbocation** [comment]
I'm going to close this since it's not a GATK issue. Thanks for the tips.

**Comment by kachulis** [comment]
@cmnbroad for the sake of my own edification, is there a reason that for unmapped slices the htsjdk cram implementation allows alignment span values of 0 or 1, but no other values (and similarly alignment starts of only 0 or -1)?  Based on a cursory reading of the spec, it seems like these values are ignored for unmapped slices, and could in theory be set to anything while still being technically on-spec?

**Comment by cmnbroad** [comment]
@kachulis In the past, htsjdk had bugs that resulted in bad index files. Those checks are an attempt to try to detect and reject such files, since they can result in subtle downstream problems. The 1 and -1 allowances are a compromise for common cases that are out-of-spec, but legitimate. So it's a compromise between being too defensive and too aggressive. A value like -2147483647 winds up getting rejected.

**Comment by kachulis** [comment]
got it, thanks!

**Comment by carbocation** [comment]
Just got an update by email from the GP team indicating that their perspective is that these are valid index files. It seems that this issue lives in a liminal space where Mutect2 is crashing due to reasons that are not a GATK bug, but also not due to any formal problem in the GP pipeline either. Still, I'm running Broad-built software on recently sequenced Broad-provided genetic data, so it seems a little odd that these aren't playing well together.

Trying to think of a solution so that other people in this situation aren't left confused by the error message, is this error specific enough that an additional statement could be added to the error message, e.g., "This error may be triggered by CRAM indexes produced by older implementations of `htsjdk`, in which case reindexing with an updated `htsjdk` may resolve this problem."? Or is this error more general, making such a suggestion inappropriate?

**Comment by droazen** [comment]
@carbocation Could you clarify which version of which specific tool produced the index files that are triggering the error? Thanks!

**Comment by carbocation** [comment]
@droazen I have forward that question to GP and will get back to you once I get their answer. (At least, to my knowledge, I can't determine this without their help since I only have access to the output but not the pipeline.)

**Comment by kachulis** [comment]
@carbocation @droazen just to speed along the question and answer process, the index files that triggered this error were produced using samtools v1.3.1, and was run back in 2019.  So the issue here is with compatibility between the current htsjdk cram implementation and older versions of htslib.  The current GP pipeline uses a much newer version of samtools, which appears to be more compatible with htsjdk, and so shouldn't produce data that runs into this issue (@cmnbroad's explanation of the different allowances htsjdk makes is relevant here).

Personally, I think the spec is (probably intentionally) quite lenient about this behavior, even more than htsjdk.  The relevant line is, I believe, "Slices containing solely unmapped unplaced data (reference ID -1) still require values for all columns, although the alignment start and span will be ignored. It is recommended that they are both set to zero." towards the bottom of page 22 in https://samtools.github.io/hts-specs/CRAMv3.pdf.  It's always a fun time when a spec uses the word "recommended" :)

  I'd guess this is a situation where earlier specs were too vague, and so too many different behaviors appeared in the wild, and now the spec can't be solidified without pushing a bunch of tools suddenly off-spec.  Though a cram expert could probably give more detail on exactly the thinking around that wording.
