### ISSUE TITLE
Explain when there will be more than two reads with the same name in MarkDuplicates

### ISSUE THREAD

**Issue by tovanadler** [broadinstitute/gatk#776]
MarkDuplicatesDataflow has a function called labelPairedEndsWithAlignmentInfo that sorts the reads and then pairs them up. I am not sure why there would ever be more than two here, so if someone could add an explanation, that would be great.

**Comment by lbergelson** [comment]
@akiezun I think you wrote this initially?

**Comment by jean-philippe-martin** [comment]
I don't know the answer, but in the interest of moving forward, the function you mean is now called
[keyPairedEndsWithAlignmentInfo](https://github.com/broadinstitute/hellbender/blob/master/src/main/java/org/broadinstitute/hellbender/tools/dataflow/transforms/markduplicates/MarkDuplicatesUtils.java#L110).

**Comment by akiezun** [comment]
sorry, i missed it. will look tomorrow

**Comment by droazen** [comment]
A question for beta

**Comment by akiezun** [comment]
closing this. i have not seen more than 2. please reopen if you have an example
