### ISSUE TITLE
Mutect2 (GATK 4.2.6.1) emitting MNPs despite max-mnp-distance 0

### ISSUE THREAD

**Issue by valleema** [broadinstitute/gatk#7782]
### Affected tool(s) or class(es)
Mutect2 `--max-mnp-distance 0`

### Affected version(s)
- [X] Latest public release version [4.2.6.1]

### Description
Same issue than described here: https://github.com/broadinstitute/gatk/issues/6473
```
singularity exec docker://broadinstitute/gatk:4.2.6.1 gatk Mutect2 \
    -R NC_000962.3.fa \
    -I input.bam \
    -O output.vcf \
    --annotation StrandBiasBySample \
    --num-matching-bases-in-dangling-end-to-recover 1 \
    --max-reads-per-alignment-start 75 \
    --max-mnp-distance 0
```

And a MNP remains:
```
grep -P "NC_000962.3\t761155" output.vcf
NC_000962.3  761155  .       C       T,G     .       .       AS_SB_TABLE=0,0|9,9|0,2;DP=20;ECNT=1;MBQ=0,17,23;MFRL=0,311,334;MMQ=60,60,60;MPOS=31,40;POPAF=7.30,7.30;TLOD=44.10,3.01GT:AD:AF:DP:F1R2:F2R1:FAD:SB     0/1/2:0,18,2:0.807,0.143:20:0,5,0:0,4,1:0,15,2:0,0,9,11
```

#### Expected behavior
```
grep -P "NC_000962.3\t761155" output.vcf
NC_000962.3        761155  .       C       T     [...]
NC_000962.3        761155  .       C       G     [...]
```

BAM, BAI, and VCF here: [files.zip](https://github.com/broadinstitute/gatk/files/8488204/files.zip)

Cheers!

**Comment by jamesemery** [comment]
Hey @valleema. We don't think this is a bug given that the argument `--max-mnp-distance` is intended to remove Multi-Nucliotide polymorphism which generally are adjacent SNPs(i.e. sites with the pattern ref: AA alt: GT for example). Your example site here doesn't have an MNP but rather is a multi-allelic site. Consequently the flag `--max-mnp-distance` is not doing anything wrong in this case. I would direct future questions about your use case (namely how to un-collapse multi-allelic sites) to our forums: https://gatk.broadinstitute.org/hc/en-us/community/topics. Thank you;
