### ISSUE TITLE
CI failures because of conda environment problems

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#7800]
Both Travis and Github actions are failing all of the conda tests at the moment.

[Example Log](https://api.travis-ci.com/v3/job/567253185/log.txt) 

There seems to be a problem with the conda environment.
```
java.lang.RuntimeException: A required Python package ("gcnvkernel") could not be imported into the Python environment. This tool requires that the GATK Python environment is properly established and activated. Please refer to GATK README.md file for instructions on setting up the GATK Python environment.
```
```
 java.lang.AssertionError: The installed version of sklearn does not match the 0.23.1 version that was requested. Check the build log to see the actual version that was resolved by conda.
```

**Comment by lbergelson** [comment]
This seems to be caused by an incompatible minor update of a transitive dependency called typing_extensions that is installed as part of pymc3.  

The maintainers say that their release shouldn't be picked up by package managers because it contains an instruction to only be used in 3.7+.  Our version of conda is picking it up anyway though and apparently doesn't understand their package files. 

It's possible upgrading the conda version in the base docker will fix this problem, but as far as I can tell we're using the most recent release of miniconda that supports python 3.6.  

Ideally we can peg the version of typing_extensions to 4.1.1 somehow.

**Comment by samuelklee** [comment]
BTW thanks @lbergelson for the diagnosis above! Not sure of the best way to prevent this sort of thing in the future without making the environment overly restrictive (this is not really my area of expertise), but perhaps a more thorough pinning of dependencies is worthwhile.

**Comment by YingChen-bio** [comment]
Thanks @lbergelson for the solution above. I just went into this conda env problem when trying to use CNNScoreVariants. By downgrading typing_extensions to 4.1.1, it works fine now.

**Comment by lbergelson** [comment]
A bit of further information.  The conda forge maintainers actually noticed that this was problematic and pushed a patched version of the recipe with corrected version bounds.  I'm not sure why we're still resolving the old incorrect version.  

I'm in favor of pinning the exact dependencies to prevent this problem.  We can always unpin and test periodically.
