### ISSUE TITLE
Ability to follow symlinks to bam files AND find the corresponding index files

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/gatk#781]
User writes: 

> It's great that the GATK walkers can follow symlinks to bam files. But I've never understood, why GATK UG and HC can't look for the index file in the same location as the bam. Instead one has to also create symlinks to the index files in the same location as the symlinks to the bam files. This prevents one from using as input a file with bam symlinks. There are several ways to work around this, but it's just such an annoying obstacle, which I run into every 3 or 6 months, because I forget about this behaviour. Please please fix and you can come and raid my mini fridge at work full of chocolate (currently also holds LEGO). If you choose to ignore this enhancement request, then GATK is still a pretty good tool :)

Sounds legit to me. Not something I think is worth spending time on in GATK3, but sounds like a reasonable feature request for 4.

This Issue was generated from your [forums] 
[forums]: http://gatkforums.broadinstitute.org/discussion/5944/symlinks-to-bam-files/p1

**Comment by lbergelson** [comment]
This sounds like something that should be done at the htsjdk level I think.

**Comment by lbergelson** [comment]
This is done in htsjdk and will function in hellbender for walkers once we update to a new htsjdk release.

**Comment by droazen** [comment]
Closing, since this was addressed at the htsjdk level.
