### ISSUE TITLE
allele frequency to define a heterozygous SNP by HaplotypeCaller 

### ISSUE THREAD

**Issue by charliechen912ilovbash** [broadinstitute/gatk#7875]
Hi,
As title, by default, what is the threshold of allele frequency to define a heterozygous SNP by HaplotypeCaller in human genome?
Like 40%~60% ?
and what is the threshold of allele frequency to define a homozygous SNP
Like >80%?

Thanks

**Comment by jamesemery** [comment]
Hi @charliechen912ilovbash. The HaplotypeCaller has no baked in hard-cuttoff for allele frequency. We genotype the SNPs according to all three possible models and select the best option based on the likelihoods and any priors. DRAGEN-GATK introduces FRD which behaves differently and computes another model that partially takes into account the divergence from neat diploid percentages (but it doesn't do anything in non-diploid samples). I would direct informational questions like this to our forums [here](https://gatk.broadinstitute.org/hc/en-us/community/topics) as there are resources there on our tools and this tracker is intended for feature requests.
