### ISSUE TITLE
Fails with Gradle-7.5.1

### ISSUE THREAD

**Issue by yurivict** [broadinstitute/gatk#7984]
### Affected tool(s) or class(es)
Build

### Affected version(s)
- [X] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
```
=======================<phase: build          >============================
===>  Building for gatk-4.2.6.1_1

Welcome to Gradle 7.5.1!

Here are the highlights of this release:
 - Support for Java 18
 - Support for building with Groovy 4
 - Much more responsive continuous builds
 - Improved diagnostics for dependency resolution

For more details see https://docs.gradle.org/7.5.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/wrkdirs/usr/ports/biology/gatk/work/gatk-4.2.6.1/build.gradle' line: 15

* What went wrong:
Plugin [id: 'de.undercouch.download', version: '4.1.2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'de.undercouch.download:de.undercouch.download.gradle.plugin:4.1.2')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

#### Steps to reproduce
regular build

Version: 4.2.6.1
Java-17
FreeBSD 13.1

**Comment by droazen** [comment]
@yurivict Unfortunately we only support the version of gradle bundled with the GATK repo, which is currently version `7.3.2`. We're happy to consider a PR to update us to a newer gradle, however (just need to modify the version in `gradle-wrapper.properties`)

We also don't currently support Java 17, though we have an open work-in-progress PR to update us to it, which we expect to get merged within the next month or so:  https://github.com/broadinstitute/gatk/pull/8013

**Comment by cmnbroad** [comment]
The Java 17 branch includes an upgrade to gradle 7.5.1.
