### ISSUE TITLE
Remove save&reload requirement for BQSR

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/gatk#799]
This was mentioned already as a comment in #562 but it should be an issue instead.

BQSR on Dataflow can *theoretically* avoid the step of saving the textual report, instead piping the recalibration analysis results directly to the ApplyBQSR phase. In practice it cannot, because it turns out that **saving a report and immediately loading it back is not a no-op**. it actually changes in some necessary way.

It would be great if someone familiar with that part of the code could help factor the mutation apart from the saving/loading, so I could just call that in the pipeline. This would speed things up a bit and the code would be that much cleaner.

**Comment by droazen** [comment]
This applies to the new spark implementation as well.

**Comment by akiezun** [comment]
@jean-philippe-martin can you provide me with an example input that reproduces the problem? I tried it on a small bam file and it was fine.

**Comment by jean-philippe-martin** [comment]
@akiezun I think I saw it with the ch20.1m-2m input. I have never tried the Spark path, though, and the Dataflow one is now gone.

In order to reproduce this problem you have to use BaseRecal and ApplyBQSR together without intermediate files, as the ReadsPreprocessingPipeline did with Dataflow (well, did until we figured it didn't work). The equivalent in Spark is called ReadsPipelineSpark, and the offending code is [right there](https://github.com/broadinstitute/gatk/blob/master/src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java#L61). So to reproduce the problem, first make sure to remove the disk round-trip there. Then I expect the ch20.1m-2m input will do the trick, though I haven't tried it with the Spark code.

**Comment by akiezun** [comment]
did you see the same problem on non-dataflow, non-spark BQSR?

**Comment by jean-philippe-martin** [comment]
As far as I know all the non-Dataflow non-Spark code communicates via files so yes, it has the problem that it is slower than it would be if we removed the file round-trip.

**Comment by akiezun** [comment]
i was not able to reproduce on stand-alone BQSR. I wonder if it's caused by the combine. What input can I use to reproduce the problem?

**Comment by jean-philippe-martin** [comment]
(answered via chat; please ping me again if still unclear)

**Comment by akiezun** [comment]
Commandline that JP uses:  
```
gcloud beta dataproc jobs submit spark --cluster hellbender-16x1 --jar build/libs/*-all-*jar BaseRecalibratorSparkOptimized --input gs://jpmartin/hellbender-test-inputs/CEUTrio.HiSeq.WGS.b37.ch1.1m-65m.NA12878.bam -L 1:5000-65005000 -R gg://reference/EOSsjdnTicvzwAE --knownSites gs://hellbender/test/resources/large/dbsnp_138.b37.20.21.vcf --apiKey $GOOGLE_API_KEY --sparkMaster yarn-client --output gs://jpmartin/test-output/br2.64m.hb-16x1.recal.txt
```

**Comment by akiezun** [comment]
@droazen is it the case that `ReadsPipelineSpark` has this issue? It does not save the report before applying it.

**Comment by jean-philippe-martin** [comment]
For reference, here is how I reproduced the bug with the Dataflow version.

Add the following lines in BaseRecalibratorOptimizedTransform.addQuantizationInfo (just above the comment linking to this issue):
```java
  BaseRecalibrationEngine recalibrationEngine = new BaseRecalibrationEngine(recalArgs, header);
  QuantizationInfo qi = new QuantizationInfo(rt, recalArgs.QUANTIZING_LEVELS);
  BaseRecalOutput ret = new BaseRecalOutput(rt, qi, recalibrationEngine.getCovariates());
```
Then run it like this (you may have to provide your own paths):
````
./hb BaseRecalibrator -R ../../sample-data/GRCh37.ch20.fixup.fa -I ../../sample-data/CEUTrio.HiSeq.WGS.b37.ch20.4m-6m.NA12878.bam --knownSites tstBQSR/dbsnp_132.b37.excluding_sites_after_129.chr17_69k_70k.vcf -O recaltable_4m-6m_br

./hb BaseRecalibratorDataflowOptimized --runner=BLOCKING -R gg://reference/EOSsjdnTicvzwAE -I gs://.../hellbender-test-inputs/CEUTrio.HiSeq.WGS.b37.ch20.4m-6m.NA12878.bam --knownSites tstBQSR/dbsnp_132.b37.excluding_sites_after_129.chr17_69k_70k.vcf --O recaltable_4m-6m_DF2 --apiKey=$GOOGLE_API_KEY --project=genomics-pipelines --staging=gs://.../staging-jpmartin

$ diff -qs recaltable_4m-6m_DF2 recaltable_4m-6m_br
Files recaltable_4m-6m_DF2 and recaltable_4m-6m_br differ
````

I could get it to trigger with the 2Mbp input, but not with the 1Mbp.

**Comment by jean-philippe-martin** [comment]
OK, here is how to see the problem. BaseRecalibratorSpark has the workaround in place (write report, read it back in). I changed it to print the difference between the original RecalibrationTable and the post-workaround RecalibrationTable in the report.

The results for the 1m-1m1k input show (edited to fit):
```
Matching: 37625/38386 (98.018%). Errors: 761 Big errors (>1.0%): 600
```

This means that about 2% of the entries in RecalibrationTables had the wrong value for numMismatches. Further, 600 of those had an error of more than one percent.

The command line I used is this:
```
spark-submit --master local[2] build/libs/*-all-*jar BaseRecalibratorSpark --input ../../sample-data/CEUTrio.HiSeq.WGS.b37.ch20.1m-1m1k.NA12878.bam --output table_tmp.txt -R gg://reference/EOSsjdnTicvzwAE --knownSites src/test/resources/large/dbsnp_138.b37.20.21.vcf --apiKey $GOOGLE_API_KEY
```

I pushed the repro code to jp_spark_repro, the key line is [BaseRecalibratorSparkFn:100](https://github.com/broadinstitute/gatk/blob/jp_spark_repro/src/main/java/org/broadinstitute/hellbender/tools/spark/transforms/BaseRecalibratorSparkFn.java#L100) where I compare the before and after tables.

**Comment by jean-philippe-martin** [comment]
Just for fun I tried rounding the number, but that didn't seem to have any impact.

**Comment by akiezun** [comment]
reproduced. 
Summary of big diffs I get (count expectedVal actualVal) 
```
 302 0.14285714285714285 0.14
 130 0.125 0.13
 114 0.3333333333333333 0.33
  42 0.16666666666666666 0.17
  37 0.2857142857142857 0.29
  21 0.09090909090909091 0.09
  10 0.1111111111111111 0.11
   7 0.375 0.38
   2 0.43452380952380953 0.43
   2 0.325 0.33
   2 0.18181818181818182 0.18
```

Top 10 of all diffs (count expectedVal actualVal):
```
 302 0.14285714285714285 0.14
 130 0.125 0.13
 114 0.3333333333333333 0.33
  42 0.16666666666666666 0.17
  37 0.2857142857142857 0.29
  21 0.09090909090909091 0.09
  20 0.42857142857142855 0.43
  16 1.3333333333333333 1.33
  10 0.1111111111111111 0.11
   9 0.4107142857142857 0.41
```

So it seems to be a rounding issue when rounding to 2 decimal places I think.

**Comment by akiezun** [comment]
confirmed that this is the rounding to 2 decimal places issue. All numbers are exactly the same after rounding to 2 decimal places. Adding the following code to `BaseRecalibratorSparkFn`:

```
roundToTwoDecimalPlaces(combinedTables);
checkForRoundtripDifference(combinedTables, ret.getRecalibrationTables(), "(after rounding) ");
```

gives:
```
NumMismatches: Matching: 48528/49402 (98.23084085664549%). Errors: 874 Big errors (>1.0%): 669
NumObservations: Matching: 49402/49402 (100.0%). Errors: 0 Big errors (>1.0%): 0
Empirical quality: Matching: 49402/49402 (100.0%). Errors: 0 Big errors (>1.0%): 0
(after rounding) NumMismatches: Matching: 49402/49402 (100.0%). Errors: 0 Big errors (>1.0%): 0
(after rounding) NumObservations: Matching: 49402/49402 (100.0%). Errors: 0 Big errors (>1.0%): 0
(after rounding) Empirical quality: Matching: 49402/49402 (100.0%). Errors: 0 Big errors (>1.0%): 0
```

**Comment by akiezun** [comment]
the approach we're taking will be to implement in-memory rounding
