### ISSUE TITLE
Add support for tagged arguments to argument parsing system

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#80]
These are arguments of the form: -V:tag filename

Needed for assigning logical names to sources of Sam/variant/etc. records (eg., "tumor" and "normal").

**Comment by fleharty** [comment]
@droazen My understanding is that tagged inputs were removed from GATK4, is there a plan to reintroduce them?

**Comment by cmnbroad** [comment]
@fleharty There is a plan to reintroduce them - see #2473.
