### ISSUE TITLE
GermlineCNVCaller error when testing for nf-core modules

### ISSUE THREAD

**Issue by ryanjameskennedy** [broadinstitute/gatk#8097]
### Affected tool(s) or class(es)
[gcnvkernel metadata.py SampleReadDepthMetadata class](https://github.com/broadinstitute/gatk/blob/4e1741896bcd04d70493f94b082dd0d27023f14c/src/main/python/org/broadinstitute/hellbender/gcnvkernel/structs/metadata.py#L177)
[gcnvkernel metadata.py SampleMetadataCollection class](https://github.com/broadinstitute/gatk/blob/4e1741896bcd04d70493f94b082dd0d27023f14c/src/main/python/org/broadinstitute/hellbender/gcnvkernel/structs/metadata.py#L215)
[gcnvkernel model_denoising_calling.py](https://github.com/broadinstitute/gatk/blob/4e1741896bcd04d70493f94b082dd0d27023f14c/src/main/python/org/broadinstitute/hellbender/gcnvkernel/models/model_denoising_calling.py)
[gcnvkernel io_metadata.py write_sample_coverage_metadata function](https://github.com/broadinstitute/gatk/blob/4e1741896bcd04d70493f94b082dd0d27023f14c/src/main/python/org/broadinstitute/hellbender/gcnvkernel/io/io_metadata.py#L16)
[theano scan_op.py](https://github.com/Theano/Theano/blob/master/theano/scan_module/scan_op.py)

### Affected version(s)
- [x] Latest public release version [version?]
- [ ] Latest master branch as of [date of test?]

### Description 
I'm getting a strange error (see below) when running a nf-core module test. I am using test files, which are obviously smaller as for short testing times i.e. the provided bam file only provides mapped reads for a small section of the genome.

#### Steps to reproduce
Run the following to create and interactive container and mount the required zip folder ([gatk_test.tar.gz](https://github.com/broadinstitute/gatk/files/10022295/gatk_test.tar.gz)):
```docker run -it -v /path/to/gatk_test_dir:/mnt/gatk_test broadinstitute/gatk bash```
If you bash the `gatk_germlinecnvcaller.sh` within the provided zip folder in a gatk4 Docker container.

#### Expected behavior
gatk GermlineCNVCaller should run as expected.

#### Actual behavior
```TypeError: ('The following error happened while compiling the node', forall_inplace,cpu,scan_fn}(Elemwise{Maximum}[(0, 0)].0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, Elemwise{mul,no_inplace}.0, Subtensor{int64::}.0, Elemwise{sub,no_inplace}.0), '\n', "Inconsistency in the inner graph of scan 'scan_fn' : an input and an output are associated with the same recurrent state and should have the same type but have type 'TensorType(float64, row)' and 'TensorType(float64, matrix)' respectively.")```

----

**Comment by NstVasileva** [comment]
I had the same error on my files. I ran CollectReadCounts (without errors and next DetermineGermlineContigPloidy also without errors) for chr1 and chr6. I'm interested only in chr6, but GATKCNVCaller need 2 intervals at least and I haven't some target regions just whole chromosome 6. And when I run GATKCNVCaller in cohort mode it gave me this error.

**Comment by ryanjameskennedy** [comment]
@NstVasileva Have you managed to solve it yet?

**Comment by NstVasileva** [comment]
@ryanjameskennedy no)

**Comment by ryanjameskennedy** [comment]
Sorry to be a pain but is there any update on this?

**Comment by asmirnov239** [comment]
Thank you for bringing this to our attention! 
This is closed by #8180, which fixes the edge case where the number of intervals in the analyzed contig is equal to two. 
Note that GermlineCNVCaller as well as any downstream tools do not support having only a single interval on any provided contig.

**Comment by ryanjameskennedy** [comment]
That's great! Thank you so much. Do you know when the next release will be released?

**Comment by asmirnov239** [comment]
@droazen Do you know when it will be?

**Comment by ryanjameskennedy** [comment]
Again, I'm sorry for being a pain, but the nf-core/raredisease release depends on these changes in which I'm responsible for adding gatk4 cnvcaller modules. Without this fix in a singularity container or conda-recipe, I cannot fully add it, and we cannot release our first pipeline collection:( Thus, @droazen, do you have an update on the release date?

**Comment by mwalker174** [comment]
@ryanjameskennedy Can you use a nightly build? https://hub.docker.com/r/broadinstitute/gatk-nightly
