### ISSUE TITLE
HaplotypeCaller fails "read must be flow based: 180652-BC94-0022826568 chr1:14585-14703" on Ultima provided samples

### ISSUE THREAD

**Issue by ScienceConnor** [broadinstitute/gatk#8112]
### Affected tool(s) or class(es)
HaplotypeCaller

### Affected version(s)
- [4.3.0.0 ] Latest public release version 

### Description 
I'm attempting to run HaplotypeCaller on Ultima flow based bams with the "--flow-mode STANDARD" and "--likelihood-calculation-engine FlowBasedHMM" arguments. However, I'm getting the following error "java.lang.IllegalArgumentException: read must be flow based: 180652-BC94-0022826568 chr1:14585-14703". The bams were created from fastqs provided directly from Ultima, so they are definitely flow-based. One question I have: how does HaplotypeCaller determine if a read is flow-based or not? Is this specified in the Read Groups?

#### Steps to reproduce
gatk --java-options "-Xmx4g" HaplotypeCaller -R hg38.fa --flow-mode STANDARD --likelihood-calculation-engine FlowBasedHMM -I [bam] -O [bam%.BQSRapplied.bam].GATK.vcf.gz

#### Expected behavior
HaplotypeCaller should complete successfully

#### Actual behavior
HaplotypeCaller fails, expecting flow-based reads

**Comment by meganshand** [comment]
@ScienceConnor Can you provide an example read? Does it have a flow matrix tag, for example `tp`? I believe this is what HaplotypeCaller is checking for.

**Comment by droazen** [comment]
The `HaplotypeCaller` logic for determining whether a read is flow-based is as follows:

```
    public static boolean isFlow(final GATKRead rec) {
        return rec.hasAttribute(FlowBasedRead.FLOW_MATRIX_TAG_NAME)
                || rec.hasAttribute(FlowBasedRead.FLOW_MATRiX_OLD_TAG_KR)
                || rec.hasAttribute(FlowBasedRead.FLOW_MATRiX_OLD_TAG_TI);
    }
```

So the reads need to have either a "tp" (FLOW_MATRIX_TAG_NAME), "kr" (FLOW_MATRiX_OLD_TAG_KR), or "ti" (FLOW_MATRiX_OLD_TAG_TI) attribute in order to be considered flow-based.

**Comment by ScienceConnor** [comment]
Here is the first full read from a sample:
140797-BC90-0012194902  272     chr1    10534   0       3S86M   *       0       0       CGCAGTACCACCGAAATCTGTGCAGAGGAGAACGCAGCTCCGCCCTCGCGGTGCTCTCCGGGTCTGTGCTGAGGAGAACGCAACTCCGC    /98;9:99<9619==7;9;9;9;;9;6665=909;;99;719694709099;59;9;90999;9;9;99;9;99;9=909;<8786,9B       RG:Z:140797-BC90.bc8ea210-7829-498d-9c68-285d6ca99837.50m

Can the flow matrix tag be added using AddOrReplaceReadGroups?

**Comment by meganshand** [comment]
`AddOrReplaceReadGroups` won't be able to add that tag since it's data on flow quality that should be reported by the sequencer. I've asked someone from Ultima to take a look and they will get back to you shortly.

**Comment by ilyasoifer** [comment]
Hi @ScienceConnor - thanks for the feedback, this is Ilya from Ultima Genomics. 
From what I see, this seems to me to be more of the output format issue rather than the issue with HaplotypeCaller per se.
Would you mind pinging me over ilya dot soifer at ultimagen dot com and I am happy to help you out.
