### ISSUE TITLE
Website color scheme

### ISSUE THREAD

**Issue by maxim-h** [broadinstitute/gatk#8115]
### Tool(s) or class(es) involved
_online documentation_

### Description 
_First of all, thank you for a great tool with amazing documentation. The issue that I noticed recently is that all that great documentation on the website became almost impossible to read. The text is light grey on white and parameters are shown in pale blue on white. Surely I cannot be the only one who gets a headache after looking at it for 5 minutes._
![image](https://user-images.githubusercontent.com/22867431/204846210-c6d03c9c-f91b-4b3f-88b3-6927768b4946.png)

Ideally a dark theme would be amazing, but anything with a little more contrast would be a big help.

----

P.S.: Before you say so, I did try to make a post about this on the forum. Any sign in request bounces back to the main page without doing anything.
P.P.S: I do think that the issue here is appropriate considering the fact that the influx of new issues might reduce significantly if people can actually read the documentation.

**Comment by droazen** [comment]
@maxim-h Thanks for reporting this issue! When I visit the latest docs for that tool (`LiftoverVcf`), which are at https://gatk.broadinstitute.org/hc/en-us/articles/9570440033179-LiftoverVcf-Picard-, I don't see any light grey text. The text shows up as black on a white background:

<img width="862" alt="liftovervcf_docs" src="https://user-images.githubusercontent.com/798637/204858080-a851e3e8-70a8-4583-9cdb-f89258a78471.png">

Is this possibly an issue with the web browser you're using? Can you try with a different browser / device and see if the issue persists for you?

**Comment by AJDCiarla** [comment]
@maxim-h Thank you again for bringing these issues to our attention! 

I am on the GATK Team and oversee the GATK forum; I'm concerned about your troubles with signing into your account to create a new forum post. If you could answer some of the following questions, I hope to be able to help identify the origin of the issue.

When did you start having trouble signing into your GATK account? 
What is the username/email address associated with your GATK Forum account? 
Could you please walk me through more of what you are seeing/doing when trying to log into your existing GATK account?

Sign In Screen:  <img width="707" alt="Screen Shot 2022-11-30 at 12 40 52 PM" src="https://user-images.githubusercontent.com/108379952/204869379-633a776f-45ba-4666-9935-e8ce563b6ef3.png">

Thank you again, and I look forward to hearing back from you!

Anthony

**Comment by maxim-h** [comment]
@droazen thank you for a quick reply. 
You were right. I am using Mozilla Firefox 107.0.1 (64-bit). When I open the page in Chromium it shows properly contrasted text.

But looking even further into the issue I realized that I can fix the problem in Firefox by going to Settings > General > Fonts > Advanced and then **UN**checking the option "Allow pages to choose their own fonts, instead of your selections above". 

![image](https://user-images.githubusercontent.com/22867431/204879119-14608610-6c34-4c3b-be55-1ec9f297ab2b.png)

After that the page is rendered properly in Firefox as well. So I'm assuming Chromium also doesn't allow pages to choose their own font.

![image](https://user-images.githubusercontent.com/22867431/204879897-3cd99232-7976-4db4-b2b9-592de1325c1d.png)

There is still a question as to why GATK website chooses such an ineligible font when given an opportunity to do so by the browser, but at least disabling this ability fixes things. This is the only webpage where I encountered that issue and it may be nice to keep the option enabled in case some other websites rely on it.

But from my side you can close the issue since there is a workaround. Unless you still want to investigate it further.

**Comment by maxim-h** [comment]
@AJDCiarla 

Hello. So, to preface my answers it's also important to note that I am having these issues on Firefox. Now that I tried it in Chromium the Sign in link works.

`When did you start having trouble signing into your GATK account?`
The issue is actually not with my account. I cannot even get to the Sign-in screen that you show.
`What is the username/email address associated with your GATK Forum account?`
As I mentioned before, the issue is not account specific. In fact I don't really remember if I still have one. My plan was to try my email and if it was already in the system to recover it.
`Could you please walk me through more of what you are seeing/doing when trying to log into your existing GATK account?`
When I open the [forum page](https://gatk.broadinstitute.org/hc/en-us/community/topics) and click New Post button or if I just click the "Sign in" button in the top panel

![image](https://user-images.githubusercontent.com/22867431/204882347-257314af-1421-4e74-87e2-dffe760480d1.png)

 I don't get redirected to the Sign in page, but to the main page of GATK
 
![image](https://user-images.githubusercontent.com/22867431/204882697-43bd0d15-0dd8-479b-af69-78951bb7d56c.png)

The URL that I see in the browser does have some extra info:

https://gatk.broadinstitute.org/hc/en-us/signin?return_to=https%3A%2F%2Fgatk.broadinstitute.org%2Fhc%2Fen-us%2Fcommunity%2Fposts%2Fnew 

But it still doesn't change where I end up.
The same is happening eevn if I run Firefox with `--safe-mode` to see if it's due to any of my extensions.

**Comment by AJDCiarla** [comment]
@maxim-h Thank you for this follow-up information. Please note that if you have any pop-up blockers enabled or are browsing in "incognito" or "safe mode," you may encounter these problems. Please ensure you have disabled any blockers and are trying to sign in through a regular browser. 

I hope this helps! Please let me know if this leads you to success.

Anthony

**Comment by maxim-h** [comment]
@AJDCiarla 

Ah, I see. Ok, so the reason was the following: I didn't use any 3rd party blockers or add-ons, but the Firefox has built-in "enhanced tracking protection" which I had to disable for it to work. I guess it's because of cross-site tracking required for this zendesk provider. 
Sorry, this was the first time it actually broke a website in 1-2 years of usage, so I didn't expect to be a culprit.
