### ISSUE TITLE
Maven repo for nightly builds?

### ISSUE THREAD

**Issue by bbimber** [broadinstitute/gatk#8138]
Hello,

In the past there was a Maven repo where nightly builds were published. Does this exist anyone? I am pretty sure i used this in the past, but I cant find it today. I am specifically interested in a GATK build with this commit: https://github.com/broadinstitute/gatk/commit/564be5465bdd39c649b62fc0091ee80e72323ae7. 

Thanks in advance.

**Comment by lbergelson** [comment]
@bbimber I think the automated publishing of maven snapshots broke when we transistioned to github actions and you're the first person to ask about it.

We'll try to get it fixed when we can, but until then I've published this for you: `4.3.0.0-15-g564be54-SNAPSHOT`

Add:  
```
    maven {
        url "https://broadinstitute.jfrog.io/broadinstitute/libs-snapshot/" //for htsjdk snapshots
    }
```
 to your build.gradles `repositories {}` block and then you should be able to resolve that version in your build.  I think those builds expire every 3 months or something so let me know if you have problems and I can re-up it.

**Comment by bbimber** [comment]
Thanks @lbergelson. I try to not depend on this, but when we're developing tools that rely on a GATK feature not yet in a release (like i'm trying to do here), it's quite useful to have those snapshots.

**Comment by lbergelson** [comment]
@bbimber No problem.   We fully intended to have snapshot builds available.  It's a bug/oversight that they're not.

**Comment by bbimber** [comment]
@lbergelson: I thought I had this worked out, but I dont seem to be able to find the latest artifacts. I'm specifically trying to find an artifact with this commit from July: https://github.com/broadinstitute/gatk/commit/810326c4ec4ff4e17b3c6fedd0b08eba98ecbefa

When I look here:

https://broadinstitute.jfrog.io/ui/native/libs-snapshot/org/broadinstitute/gatk/

I dont see much with a modified date beyond May. Should I be looking somewhere else?
