### ISSUE TITLE
Implement parameter groups for CommandLinePrograms

### ISSUE THREAD

**Issue by LeeTL1220** [broadinstitute/gatk#817]
I would like a mechanism to group our `@Argument` in our `CommandLinePrograms`.  These should be arbitrary group names set by the developer.

Python has a pretty good model, which can be used for reference.

https://docs.python.org/3/library/argparse.html#argument-groups

**Comment by droazen** [comment]
We can already do this using `@ArgumentCollection` -- closing.

**Comment by magicDGS** [comment]
I would also like to have this, but adding the doc from the collection... I think that anyway there's a discussion about it in https://github.com/broadinstitute/barclay/issues/7
