### ISSUE TITLE
PreprocessIntervals don't convert intervals with chr22, chr21

### ISSUE THREAD

**Issue by NstVasileva** [broadinstitute/gatk#8177]
`gatk PreprocessIntervals -R GRCh38.fa --padding 0 -L chr22:25000-35000 -L chr22:50000-60000 -imr OVERLAPPING_ONLY -O gatk_intervals.interval_list`

results no intervals in output .interval_list file, but everything is OK for chr1, chr6, chrX, for example. For 'chr22' alone it works.

**Comment by samuelklee** [comment]
Note from the tool documentation: `Finally, bins that contain only Ns are filtered out.` These regions in chr22 contain only Ns, so this result is expected.
