### ISSUE TITLE
Periodicity in GQ frequency distribution

### ISSUE THREAD

**Issue by RWilton** [broadinstitute/gatk#8179]
## Bug Report
HaplotypeCaller

### Affected version(s)
4.3.0

### Description 
A plot of the frequency distribution of GQ values associated with variants reported by HaplotypeCaller demonstrates "periodicity".

The following counts GQ values for TP variant calls (data from HG002, aligned to GRCh38 with three different read aligners, chr14 only):

![GQdist HC](https://user-images.githubusercontent.com/8249753/215591505-06b76118-cdbf-4b04-ae70-55acaaf8fce9.png)

Most of the distribution is periodic on GQ values that are even multiples of 3.  This is seen in the data for this plot: [GCdist.xlsx](https://github.com/broadinstitute/gatk/files/10540627/GCdist.xlsx)

In addition, about 80% of the reported variants were associated with GQ=99 (not plotted here).

This kind of thing might be an artifact of the algorithm used to compute GQ.  For example, underlying data such as MAPQ might be manifesting the same periodicity, which is then "passed through" to GQ.

It might also be an implementation error.  For example, premature rounding or the use of an integer variable instead of a floating point variable might lead to inadvertent quantization of a result.

But this is just speculation, given only that the distribution would be expected to be smooth, not periodic.

#### Steps to reproduce
A little bit of awk should suffice to pull GQ values from a plain-text VCF file.

#### Expected behavior
No periodicity in the frequency distribution of GQ values.  For example, here is the distribution of GQ values for the same three sets of read mappings but with variants called with DeepVariant:

![GQdist DV](https://user-images.githubusercontent.com/8249753/215611788-9372cec8-7841-4d90-b137-b3f950902fba.png)

In addition, about 15% of the reported variants were associated with GQ=99 (not plotted here).

#### Actual behavior
(As above.)

Thanks for any insight you can provide on this!

**Comment by jamesemery** [comment]
Hello @RWilton. We have observed this behavior in the GQ in the past and we attribute it to some rounding to integers that happens internal to the genotyping array when we convert to PL before computing the GQ which results in quantized GQ scores in practice as you have observed. Generally fine differences in calculated GQ below its current resolution in the output for HaplotypeCaller are not expected to make very much of a difference especially if we are re-computing the genotypes in using VQSR anyway, so it has not been a priority for us to un-quantize the results.

**Comment by RWilton** [comment]
That explains why the frequency distribution of GQ is not smooth.

For what it's worth, HaplotypeCaller is not alone in this. Here's the same phenomenon with the same data using FreeBayes (with the dots connected on one of the data series to make the periodicity more obvious):

![GQ FB](https://user-images.githubusercontent.com/8249753/217343870-ab62f2e6-e4e7-49fe-b8d8-587250894955.png)

I have nothing else to add at this point, so please feel free to close this issue.

Thanks again!
