### ISSUE TITLE
Change ReadGroups name on gvcf or vcf files?

### ISSUE THREAD

**Issue by cjchen5** [broadinstitute/gatk#8245]
### Tool(s) or class(es) involved
gatk AddOrReplaceReadGroups

### Description
Hi,
I'd like to change the ReadGroups name on .gvcf or .vcf files. However, AddOrReplaceReadGroups seems only works on bam file. 
Is there any way to change the ReadGroups name on .gvcf or .vcf files? 

Thanks!

**Comment by droazen** [comment]
Hi @cjchen5, VCFs don't have read groups, only BAM/CRAM/SAM files do. Do you mean that you want to change the sample names in the VCF? You can do this by updating the sample names in the VCF header -- they are typically in the final line of the header before the VCF records start. There are a couple of tools that can assist with this sort of task, such as `FixVcfHeader` in GATK/Picard.

**Comment by droazen** [comment]
Closing as answered
