### ISSUE TITLE
Haplotype calls deletion followed by insertion instead of indel

### ISSUE THREAD

**Issue by rollf** [broadinstitute/gatk#8253]
### Affected tool(s) or class(es)

HaplotypeCaller

### Affected version(s)
- [x] Latest public release version (4.4.0.0, also 4.1.4.1)
- [ ] Latest master branch as of [date of test?]

### Description 

I am using the HaplotypeCaller (GATK 4.4.0.0). When I look at the input BAM file in IGV, I expect the variant `NC_000015.9:g.48760182_48760185delinsGGGT`. However, HaplotypeCaller reports `NC_000015.9:g.48760182_48760185del` as well as an insertion `NC_000015.9:g.48760184_48760185insGGGT` (i.e. two distinct variants instead of a single indel). In the `bamout`, one can clearly see that the local realignment suggests the deletion + insertion and not the indel.

![image](https://user-images.githubusercontent.com/58295931/226553360-bff887ea-3823-44b7-bddb-46f70705c0b3.png)

I understand that the local realignment is expected to improve variant calling and that his approach is battle-tested. I am thus not convinced this is a bug. However, the realignment/variant call is not obvious to the human eye - one would expect the indel instead. The variant seems like a clear heterozygous indel. I checked this [blog post](https://gatk.broadinstitute.org/hc/en-us/articles/360035891111-Expected-variant-at-a-specific-site-was-not-called): The bamout is as outlined above, the mapping + base quality seems fine (judging by IGV) and `--max-alternate-alleles` doesn't seem useful here (and indeed doesn't do anything to the result). I didn't got into kmer fiddling as suggested by the blog post. This is not a homopoly region.

I also tested with 4.1.4.1 which only reports the deletion. The screenshot from above is from the 4.4.0.0 invocation. Here is the same situation for 4.1.4.1 (realignment is similar, `out.vcf` does not contain the insertion):

![image](https://user-images.githubusercontent.com/58295931/226554045-0d9dd7e3-65ec-40ce-a6bd-74d73d4a2507.png)

FYI, the variant lies on FBN1 / NM_000138.5 (rev strand). cDNA notation would be `NM_000138.5:c.4698_4701del` or `NM_000138.5:c.4698_4701delinsACCC`.
(Actually, assuming delins is correct, this could rather be `NC_000015.9:g.48760182_48760185inv` / `NM_000138.5:c.4698_4701inv`)

#### Steps to reproduce

Please find [attached](https://github.com/broadinstitute/gatk/files/11026375/hc-del-and-ins-vs-indel.zip) the necessary data to reproduce the scenario.

#### Expected behavior

The indel variant `NC_000015.9:g.48760182_48760185delinsGGGT` gets called.

#### Actual behavior

Two distinct variants `NC_000015.9:g.48760182_48760185del` as well as a  `NC_000015.9:g.48760184_48760185insGGGT` get called.

Again, I'm not sure this is a bug. I'm sorry if this isn't any. In this case, it would be nice to understand the reasoning behind the calls here.

**Comment by jamesemery** [comment]
This looks like a representation issue that is a result of the SmithWaterman parameters we use for variant calling where the cost for an insertion + deletion is likely to cost less than 4 adjacent SNPs. Fortunately most variant evaluation scripts re-align the haplotypes locally which should exclude this from counting against the tool in most cases. If you have any specific issues to report related to this I would recommend going through our forums.

**Comment by rollf** [comment]
There are further comments at https://gatk.broadinstitute.org/hc/en-us/community/posts/14436692351259-Haplotype-calls-deletion-followed-by-insertion-instead-of-indel
