### ISSUE TITLE
Funcotator - Cannot set splice site window size from CLI

### ISSUE THREAD

**Issue by jonn-smith** [broadinstitute/gatk#8276]
The splice site window size (in bases) was never hooked into the CLI.  This should be added as a CLI option.

**Comment by zhanyinx** [comment]
Hi there,

is there any update on this?
Thanks

Best
Zhan

**Comment by jonn-smith** [comment]
@zhanyinx I just put in a fix for it - #8463

When it gets merged it will be in the nightly builds.

**Comment by zhanyinx** [comment]
@jonn-smith thanks a lot

**Comment by jonn-smith** [comment]
@zhanyinx Just merged a fix to this, which exposes a new CLI parameter.  Tonight's nightly build will have the new option for you to try.
