### ISSUE TITLE
gatk --help works gatk --list or --java-options doesn't 

### ISSUE THREAD

**Issue by SallemiAmeni** [broadinstitute/gatk#8280]
Hi, 
This is what i got when i run the command gatk --help 
(base) ameni@ameni-Aspire-A315-55G:~/Documents/pharmacogenomics$ gatk --help

 Usage template for all tools (uses --spark-runner LOCAL when used with a Spark tool)
    gatk AnyTool toolArgs

 Usage template for Spark tools (will NOT work on non-Spark tools)
    gatk SparkTool toolArgs  [ -- --spark-runner <LOCAL | SPARK | GCS> sparkArgs ]

 Getting help
    gatk --list       Print the list of available tools

    gatk Tool --help  Print help on a particular tool

 Configuration File Specification
     --gatk-config-file                PATH/TO/GATK/PROPERTIES/FILE

 gatk forwards commands to GATK and adds some sugar for submitting spark jobs

   --spark-runner <target>    controls how spark tools are run
     valid targets are:
     LOCAL:      run using the in-memory spark runner
     SPARK:      run using spark-submit on an existing cluster 
                 --spark-master must be specified
                 --spark-submit-command may be specified to control the Spark submit command
                 arguments to spark-submit may optionally be specified after -- 
     GCS:        run using Google cloud dataproc
                 commands after the -- will be passed to dataproc
                 --cluster <your-cluster> must be specified after the --
                 spark properties and some common spark-submit parameters will be translated 
                 to dataproc equivalents

   --dry-run      may be specified to output the generated command line without running it
   --java-options 'OPTION1[ OPTION2=Y ... ]'   optional - pass the given string of options to the 
                 java JVM at runtime.  
                 Java options MUST be passed inside a single string with space-separated values.

   --debug-port <number> sets up a Java VM debug agent to listen to debugger connections on a
                         particular port number. This in turn will add the necessary java VM arguments
                         so that you don't need to explicitly indicate these using --java-options.
   --debug-suspend       sets the Java VM debug agent up so that the run get immediatelly suspended
                         waiting for a debugger to connect. By default the port number is 5005 but
                         can be customized using --debug-port

But when i run other commands with gatk like gatk --list, i got this error :
gatk --list
Using GATK jar /home/ameni/Documents/pharmacogenomics/gatk-4.4.0.0/gatk-package-4.4.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /home/ameni/Documents/pharmacogenomics/gatk-4.4.0.0/gatk-package-4.4.0.0-local.jar --help
Error: LinkageError occurred while loading main class org.broadinstitute.hellbender.Main
	java.lang.UnsupportedClassVersionError: org/broadinstitute/hellbender/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by wangwenzheng-agis** [comment]
Hi,i have the same problem, have you solve it ?

**Comment by SallemiAmeni** [comment]
Hello,
yes simply because i was working under the base environment of conda, so
conda deactivate command solved the problem

Le dim. 9 avr. 2023 à 15:09, wangwenzheng-agis ***@***.***> a
écrit :

**Comment by cmnbroad** [comment]
@wangwenzheng-agis @SallemiAmeni This error occurs when the Java version you're using is out of date. Starting with [version 4.4.0](https://github.com/broadinstitute/gatk/releases/tag/4.4.0.0), GATK requires Java 17.

**Comment by droazen** [comment]
Closing as answered

**Comment by jonasjonker** [comment]
The getting started article on [gatk.broadinstitute.org](https://gatk.broadinstitute.org/hc/en-us/articles/360036194592-Getting-started-with-GATK4) says you need a "Unix-style OS and Java 1.8". Maybe that article can be updated?
