### ISSUE TITLE
Fix ReadsPreprocessingPipelineIntegrationTest

### ISSUE THREAD

**Issue by jean-philippe-martin** [broadinstitute/gatk#829]
See pull #812 

> Apply the actual BaseRecalibratorTransform here, and delete the stub. If the 
> ReadsPreprocessingPipelineIntegrationTest fails as a result, temporarily disable the test, 
> create a ticket to fix it, and assign it to me.

@droazen

**Comment by droazen** [comment]
Ticket is no longer valid, since `ReadsPreprocessingPipelineIntegrationTest` no longer exists.
