### ISSUE TITLE
Update funcotator bundled data sources

### ISSUE THREAD

**Issue by robby81** [broadinstitute/gatk#8296]
The latest version of the funcotator data sources dates to mid-2020. This is almost three years now without any update of the following sources:
*gencode (v34, now 43)
*dbsnp
*COSMIC
*clinvar

Therefore, a new bundle should be provided to stay up-to-date again.

**Comment by droazen** [comment]
@robby81 Some changes need to be made to the tool to support the newer releases of Gencode. We're planning on addressing that this quarter, after which we'll do a new data source release.

**Comment by robby81** [comment]
@droazen is there a new release available?

**Comment by zhanyinx** [comment]
I am looking forward to the new datasource release. Meanwhile, if anyone wants to get newer version of some databases, I have created a repo which updates some of them. Checkout [here](https://github.com/zhanyinx/variantalker/tree/main/update_db)
