### ISSUE TITLE
The haplotypecaller results were inconsistent with what was observed by IGV

### ISSUE THREAD

**Issue by xiechangxiao** [broadinstitute/gatk#8356]
Hello,
There's a question about haplotypecaller that's been bothering me for a long time.
GT is 0/1 in haplotypecaller's out vcf, but 1/1 in IGV. Can you help me explain?
This is cmd:
`gatk-4.2.6.1/gatk HaplotypeCaller -R hg19.fasta -I bam  -A QualByDepth -A FisherStrand -A ReadPosRankSumTest  -A StrandOddsRatio -A MappingQualityRankSumTest -A RMSMappingQuality  --max-reads-per-alignment-start 0  --linked-de-bruijn-graph --recover-all-dangling-branches --max-mnp-distance 2 -O vcf`
IGV picture as below:
![image](https://github.com/broadinstitute/gatk/assets/35715828/de85a9ed-6d80-43fb-9ce6-a6fec79fca67)

**Comment by jamesemery** [comment]
Hello @xiechangxiao. For future reference we would ask you to direct these sorts of questions at our [forums](https://gatk.broadinstitute.org/hc/en-us/community/topics). It wold be helpful to see a few things for this site to help understand what is happening. If you could report the actual VCF line corresponding to the mis-genotyped call (which should report how the call was made) that would help diagnose what was happening. Furthermore I would recommend you rerun haplotypecaller with the `--bamout` argument so you can see what haplotypes were generated and how they were realigned.

**Comment by droazen** [comment]
Hi @xiechangxiao, could you please repost this on our forums, as @jamesemery suggested above (https://gatk.broadinstitute.org/hc/en-us/community/topics)? We'd be happy to help you there. This issue tracker is for bug reports.
