### ISSUE TITLE
Make Hadoop a 'provided' dependency

### ISSUE THREAD

**Issue by tomwhite** [broadinstitute/gatk#836]
It's common for Hadoop JARs to be provided at runtime (e.g. when running the `hadoop` or `spark-submit` commands). This is because the client-server RPC is fragile, so it's important to use the same version of each.

To solve this we should make the Hadoop JARs a ['provided' dependency](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html) (in the Maven sense). Gradle doesn't support 'provided' out of the box, so a workaround may be needed.

**Comment by droazen** [comment]
This was resolved in a different way in https://github.com/broadinstitute/gatk/pull/882. Closing!
