### ISSUE TITLE
How to apply the BQSR in population-based snp-calling for samples with low sequence depth. Urgently.

### ISSUE THREAD

**Issue by Mirror1211** [broadinstitute/gatk#8414]
Hi everyone,

I am going to use GATK4 to carry out population-based snp-calling for around 500 samples with the ploidy level from 2 to 6.
The sequence depth varied from 2x to 80x.

Since there are many samples with low sequence depth (<5x), I was advised to use the population-based snp-calling pipeline. 
Recently, I met some problems in the flowchart of this analysis.

Firstly, I found the pipelines that detailedly explained the flowchart of BQSR and variant calling for single-sample snp-calling. But I have no idea about the pipeline of the BQSR in population-based snp-calling.  Should I apply the BQSR sample by sample following the flowchart menthioned above (the command line below), and then used these corrected bam files to identify the variants based on population-based method? Or there is another correct pipeline for this analysis.

**Command lines:**

```
for i in sample1.bam sample2.bam sample3.bam
do
      java -jar picard.jar MarkDuplicates I=$i O=$i_bam CREATE_INDEX=true M=$i_metrics
      gatk HaplotypeCaller -R $reference -I $i.sorted.dedup.bam -O "$i".g.vcf.gz --tmp-dir ./tmp -ERC GVCF
      #SNP
      gatk GenotypeGVCFs -R $reference -V "$i".g.vcf.gz -O "$i".vcf.gz
      gatk SelectVariants -R $reference -V "$i".vcf.gz -select-type SNP -O "$i".snp.vcf.gz
      gatk VariantFiltration -R $reference -V $path_BQSR/bqsr1.snp.vcf.gz -filter "QD < 2.0" --filter-name "QD2" -filter "FS > 60.0" --filter-name "FS60" -filter "MQ < 40.0" --filter-name "MQ40" -filter "MQRankSum < -12.5" --filter-name "MQRankSum-12.5" -filter "ReadPosRankSum < -8.0" --filter-name "ReadPosRankSum-8.0" -O $"i".filtered.snp.vcf.gz
      gatk SelectVariants -R $reference -V $"i".filtered.snp.vcf.gz --exclude-filtered -O "$i".select.filtered.snp.vcf.gz
      #INDEL
      gatk SelectVariants -R $reference -V "$i".vcf.gz -select-type INDEL -O "$i".indel.vcf.gz
      gatk VariantFiltration -R $reference -V "$i".indel.vcf.gz -filter "QD < 2.0" --filter-name "QD2" -filter "FS > 200.0" --filter-name "FS200" -filter "ReadPosRankSum < -20.0" --filter-name "ReadPosRankSum-20" -O "$i".filtered.indel.vcf.gz
      gatk SelectVariants -R $reference -V "$i".filtered.indel.vcf.gz --exclude-filtered -O "$i".selected.filtered.indel.vcf.gz

      gatk BaseRecalibrator -R $reference -I $i_bam -O grp1 --use-original-qualities --known-sites "$i".select.filtered.snp.vcf.gz --known-sites "$i".selected.filtered.indel.vcf.gz
      gatk ApplyBQSR -R $reference -I $i_bam -O "$i".sorted.dedup.BQSR1.bam -bqsr grp1 --static-quantized-quals 10 --static-quantized-quals 20 --static-quantized-quals 30 --add-output-sam-program-record --create-output-bam-md5 --use-original-qualities
      gatk ValidateSamFile -I "$i".sorted.dedup.BQSR.bam -O  "$i"_validateSamFile_of_bqsr_bam_file.out
      samtools index "$i".sorted.dedup.BQSR.bam
done
      gatk --java-options "-Xmx30G" HaplotypeCaller -R $reference -I  sample1.sorted.dedup.BQSR.bam sample2.sorted.dedup.BQSR.bam sample3.sorted.dedup.BQSR.bam -O sample1_sample2_sample4.g.vcf.gz --tmp-dir tmp -ERC GVCF
```

Secondly, how do I set the ploidy parameter for different samples in the population-based snp-calling?
Finally, for each taxa, there are some samples with relatively high sequence depth (> 10x). Is there any better choices for the snp-calling pipeline ??

Sincerely.
Jing

**Comment by droazen** [comment]
Hi [Mirror1211](https://github.com/Mirror1211),

This github issue tracker is for bug reports -- could you please repost this question on our support forum (https://gatk.broadinstitute.org/hc/en-us/community/topics)?
