### ISSUE TITLE
java.lang.IllegalStateException: There are no sources based on those query parameters

### ISSUE THREAD

**Issue by ShirelyI** [broadinstitute/gatk#8415]
### Instructions

The github issue tracker is for bug reports, feature requests, and API documentation requests. General questions about how to use the GATK, how to interpret the output, etc. should be asked on the [official support forum](http://gatkforums.broadinstitute.org/gatk).
- Search the existing github issues to see if your issue (or something similar) has already been reported.  If the issue already exists, you may comment there to inquire about the progress.
- Determine whether your issue is a **bug report**, a **feature request**, or a **documentation request** (for tool/class javadoc only -- for forum docs please post there)
- Consider if your "issue" is better addressed on the GATK forum: http://gatkforums.broadinstitute.org/gatk  Post there if you have questions about expected tool behavior, output format, unexpected results, or generally any question that does not fit into the categories above
- Use a **concise** yet **descriptive** title
- Choose the corresponding template block below and fill it in, replacing or deleting text in italics (surrounded by `_`) as appropriate
- Delete the other template blocks and this header.

----

## Bug Report

03:51:59.035 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/opt/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
Jul 13, 2023 3:51:59 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
INFO: Failed to detect whether we are running on Google Compute Engine.
03:51:59.220 INFO  GenotypeGVCFs - ------------------------------------------------------------
03:51:59.220 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.2.0.0
03:51:59.220 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
03:51:59.220 INFO  GenotypeGVCFs - Executing as dingrj@localhost.localdomain on Linux v4.18.0-348.7.1.el8_5.x86_64 amd64
03:51:59.220 INFO  GenotypeGVCFs - Java runtime: OpenJDK 64-Bit Server VM v11.0.11+9-Ubuntu-0ubuntu2.18.04
03:51:59.220 INFO  GenotypeGVCFs - Start Date/Time: July 13, 2023 at 3:51:58 AM UTC
03:51:59.221 INFO  GenotypeGVCFs - ------------------------------------------------------------
03:51:59.221 INFO  GenotypeGVCFs - ------------------------------------------------------------
03:51:59.221 INFO  GenotypeGVCFs - HTSJDK Version: 2.24.0
03:51:59.221 INFO  GenotypeGVCFs - Picard Version: 2.25.0
03:51:59.221 INFO  GenotypeGVCFs - Built for Spark Version: 2.4.5
03:51:59.221 INFO  GenotypeGVCFs - HTSJDK Defaults.COMPRESSION_LEVEL : 2
03:51:59.221 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
03:51:59.221 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
03:51:59.221 INFO  GenotypeGVCFs - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
03:51:59.221 INFO  GenotypeGVCFs - Deflater: IntelDeflater
03:51:59.221 INFO  GenotypeGVCFs - Inflater: IntelInflater
03:51:59.221 INFO  GenotypeGVCFs - GCS max retries/reopens: 20
03:51:59.222 INFO  GenotypeGVCFs - Requester pays: disabled
03:51:59.222 INFO  GenotypeGVCFs - Initializing engine
03:51:59.571 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.3.2-e18fa63
11:51:59.957 info  NativeGenomicsDB - pid=1480681 tid=1480682 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
11:51:59.957 info  NativeGenomicsDB - pid=1480681 tid=1480682 No valid combination operation found for INFO field MLEAC  - the field will NOT be part of INFO fields in the generated VCF records
11:51:59.957 info  NativeGenomicsDB - pid=1480681 tid=1480682 No valid combination operation found for INFO field MLEAF  - the field will NOT be part of INFO fields in the generated VCF records
03:52:00.341 INFO  GenotypeGVCFs - Done initializing engine
03:52:00.369 INFO  ProgressMeter - Starting traversal
03:52:00.369 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
03:52:00.377 INFO  GenotypeGVCFs - Shutting down engine
[July 13, 2023 at 3:52:00 AM UTC] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 0.02 minutes.
Runtime.totalMemory()=2583691264
java.lang.IllegalStateException: There are no sources based on those query parameters
        at org.genomicsdb.reader.GenomicsDBFeatureIterator.<init>(GenomicsDBFeatureIterator.java:167)
        at org.genomicsdb.reader.GenomicsDBFeatureReader.query(GenomicsDBFeatureReader.java:152)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.refillQueryCache(FeatureDataSource.java:569)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.queryAndPrefetch(FeatureDataSource.java:538)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.query(FeatureDataSource.java:504)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$2(VariantLocusWalker.java:149)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:668)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:148)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1058)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)
Using GATK jar /opt/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx56g -Djava.io.tmpdir=./tmp -jar /opt/gatk-4.2.0.0/gatk-package-4.2.0.0-local.jar GenotypeGVCFs -R ../../01.ref/MS/genome.fasta -V gendb://genomeDB.Chr23 -all-sites -O Chr23.raw.vcf.gz

### Affected tool(s) or class(es)
_Tool/class name(s), special parameters?_

### Affected version(s)
- [ ] Latest public release version [version?]   V4.2.0.0
- [ ] Latest master branch as of [date of test?]

### Description 
_Describe the problem below. Provide **screenshots** , **stacktrace** , **logs** where appropriate._
There are no results generated.
![image](https://github.com/broadinstitute/gatk/assets/103233242/2c505328-c0a0-473a-bd64-63b2137e0f06)

#### Steps to reproduce
_Tell us how to reproduce this issue. If possible, include command lines that reproduce the problem. (The support team may follow up to ask you to upload data to reproduce the issue.)_

1:singularity exec ~/biosoft/resequence/Reseq_genek.sif gatk --java-options "-Xmx48g -Djava.io.tmpdir=./tmp" HaplotypeCaller -R ../../01.ref/MS/genome.fasta  -I ../../02.mapping/MS/F10.sort.markdup.bam -L Chr01  -ERC GVCF -O F10/F10.Chr01.g.vcf.gz 
2:singularity exec ~/biosoft/resequence/Reseq_genek.sif gatk  --java-options "-Xmx56g -Djava.io.tmpdir=./tmp -DGATK_STACKTRACE_ON_USER_EXCEPTION=true"  GenomicsDBImport  --sample-name-map  gvcf.Chr01.map  --genomicsdb-workspace-path  genomeDB.Chr01  -L Chr01  --reader-threads 56  --batch-size 50  --tmp-dir ./tmp  
3：singularity exec ~/biosoft/resequence/Reseq_genek.sif gatk  --java-options "-Xmx56g -Djava.io.tmpdir=./tmp" GenotypeGVCFs -R ../../01.ref/MS/genome.fasta  -V gendb://genomeDB.Chr01 -all-sites -O Chr01.raw.vcf.gz 

#### Expected behavior
_Tell us what should happen_
![image](https://github.com/broadinstitute/gatk/assets/103233242/d7bf204e-483b-4586-96cb-db3d504ae360)

#### Actual behavior
_Tell us what happens instead_

----
![image](https://github.com/broadinstitute/gatk/assets/103233242/44b7620e-c7bc-412f-9d2a-0c0370d4d935)

### Tool(s) or class(es) involved
_Tool/class name(s), special parameters?_

### Description
_Specify whether you want a modification of an existing behavior or addition of a new capability._
_Provide **examples**, **screenshots**, where appropriate._

----

### Tool(s) or class(es) involved
_Tool/class name(s), parameters?_

### Description 
_Describe what needs to be added or modified._

----

**Comment by droazen** [comment]
Hi [ShirelyI](https://github.com/ShirelyI),

Could you try running with the latest GATK release (4.4), and see if the issue persists? There have been a lot of fixes to GenomicsDB (which is where the error is coming from) between 4.2 and 4.4.

@nalinigans / @mlathara, have either of you seen this error before when reading from GenomicsDB? What does it indicate?

**Comment by mlathara** [comment]
@ShirelyI can you elaborate a bit on the exact issue here? You're trying to run GenotypeGVCFs on some input genomicsdb workspace, and it doesn't work at all with the above error? Or does the error only happen with certain workspaces (chr23)? Can you also list the files/folders in (one of) the workspaces that doesn't work?

Can you also share the contig description from the fasta, maybe by grepping something like
```
grep "^>" genome.fasta
```

**Comment by ShirelyI** [comment]
Hi mlathara,
it doesn't work at all chromosomes  but chr01,
the contig description from the fasta is as follows and I only analyse the Chr***
![image](https://github.com/broadinstitute/gatk/assets/103233242/838657ef-5f16-4c47-af85-ee89aeef3ffb)

**Comment by mlathara** [comment]
To confirm, it works on Chr01 but nothing else? And can you list the
files/folders in the Chr01 genomicsdb versus say Chr02?

**Comment by tzaquin** [comment]
I'm experiencing the same issue. using gatk 4.4

**Comment by hde08** [comment]
Hi, 

I am experiencing exactly the same issue. I also run gatk on a cluster using singularity. When using --include-non-variant-sites the same error message is reported for all but the first chromosome. When exluding non variant sites it works fine. 

```
05:04:16.405 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/gatk/gatk-package-4.5.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
05:04:16.556 INFO  GenotypeGVCFs - ------------------------------------------------------------
05:04:16.559 INFO  GenotypeGVCFs - The Genome Analysis Toolkit (GATK) v4.5.0.0
05:04:16.559 INFO  GenotypeGVCFs - For support and documentation go to https://software.broadinstitute.org/gatk/
05:04:16.563 INFO  GenotypeGVCFs - Initializing engine
05:04:16.929 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.5.1-84e800e
16:04:16.979 INFO  NativeGenomicsDB - pid=680685 tid=680686 No valid combination operation found for INFO field InbreedingCoeff  - the field will NOT be part of INFO fields in the generated VCF records
16:04:16.979 INFO  NativeGenomicsDB - pid=680685 tid=680686 No valid combination operation found for INFO field MLEAC  - the field will NOT be part of INFO fields in the generated VCF records
16:04:16.979 INFO  NativeGenomicsDB - pid=680685 tid=680686 No valid combination operation found for INFO field MLEAF  - the field will NOT be part of INFO fields in the generated VCF records
05:04:17.059 INFO  GenotypeGVCFs - Done initializing engine
05:04:17.104 INFO  ProgressMeter - Starting traversal
05:04:17.105 INFO  ProgressMeter -        Current Locus  Elapsed Minutes    Variants Processed  Variants/Minute
05:04:17.124 INFO  GenotypeGVCFs - Shutting down engine
[June 26, 2024 at 5:04:17 AM GMT] org.broadinstitute.hellbender.tools.walkers.GenotypeGVCFs done. Elapsed time: 0.01 minutes.
Runtime.totalMemory()=1126170624
java.lang.IllegalStateException: There are no sources based on those query parameters
        at org.genomicsdb.reader.GenomicsDBFeatureIterator.<init>(GenomicsDBFeatureIterator.java:167)
        at org.genomicsdb.reader.GenomicsDBFeatureReader.query(GenomicsDBFeatureReader.java:149)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.refillQueryCache(FeatureDataSource.java:622)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.queryAndPrefetch(FeatureDataSource.java:591)
        at org.broadinstitute.hellbender.engine.FeatureDataSource.query(FeatureDataSource.java:557)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.lambda$traverse$2(VariantLocusWalker.java:149)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
        at org.broadinstitute.hellbender.engine.VariantLocusWalker.traverse(VariantLocusWalker.java:148)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1098)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:149)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:198)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:217)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:166)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:209)
        at org.broadinstitute.hellbender.Main.main(Main.java:306)
Using GATK jar /gatk/gatk-package-4.5.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xmx4g -jar /gatk/gatk-package-4.5.0.0-local.jar GenotypeGVCFs -R /nvme/disk0/lecellier_data/WGS_GBR_data/Ref_genomes/Amil_scaffolds_final_v3.fa -V gendb://scaffold_2 -O /nvme/disk0/lecellier_data/WGS_GBR_data/GATK_files/Vcf_files/aspat_clean_scaffold_2.vcf.gz --include-non-variant-sites --tmp-dir /nvme/disk0/lecellier_data/WGS_GBR_data/tmp
```

**Comment by r-poloni** [comment]
Hi, I am experiencing the same issue with gatk_4.5:
java.lang.IllegalStateException: There are no sources based on those query parameters 
when setting -L HiC_scaffold_7 both directly in the options and in a file with contig name. If I run genome-wide there are no problems.

**Comment by hde08** [comment]
Is your GenomicDB named as your contig ? If so it may produce an error if your working directory is in the Genomic DB, see my comment here : 

https://gatk.broadinstitute.org/hc/en-us/community/posts/26901826831899-GenotypeGVCFs-issue-when-using-include-non-variant-sites-parameter

In addition the option -L needs to be set in in both the GenomicDBimport step and the GenotypeGVCFs step, see below : 

`singularity exec --bind /nvme/disk0/lecellier_data:/nvme/disk0/lecellier_data /home/hdenis/gatk_latest.sif gatk --java-options "-Xmx15g -Xms4g" GenomicsDBImport --genomicsdb-workspace-path "${INDIR}GenomicDB/${CONTIG_NAME}" --batch-size 50 -L $CONTIG --sample-name-map "${INDIR}aspat_gvcf_clean.sample_map" --tmp-dir /nvme/disk0/lecellier_data/WGS_GBR_data/tmp --reader-threads 7 --genomicsdb-shared-posixfs-optimizations true --bypass-feature-reader true `

`singularity exec --bind /nvme/disk0/lecellier_data:/nvme/disk0/lecellier_data /home/hdenis/gatk_latest.sif gatk --java-options "-Xmx58g" GenotypeGVCFs -R $REF_3 -V "gendb://${INDIR}GenomicDB/${CONTIG_NAME}" -O "${OUTDIR}aspat_clean_${CONTIG_NAME}.vcf.gz" --tmp-dir /nvme/disk0/lecellier_data/WGS_GBR_data/tmp --include-non-variant-sites true -L $CONTIG --only-output-calls-starting-in-intervals true`

**Comment by r-poloni** [comment]
Hi hde08! Thanks for the answer. That is a bit weird indeed. When I use GenotypeGVCF -V gendb://07_genomicdb without setting -L option and I have a genomicDB with entire genome or with more scaffolds it works, but with only one scaffold it does not, and throws the error. In general, I don't understand what is the point of using GenomicDBimport if you have to recall again the intervals in GenotypeGVCF.
The DB is not named as the contig.
