### ISSUE TITLE
Looking into broadcasting reference to all workers for native Spark Reads pipeline

### ISSUE THREAD

**Issue by davidadamsphd** [broadinstitute/gatk#855]
Look into broadcasting the reference to all of the workers. This would make AddContextDataToReadSpark and the BQSR code simpler and may have better performance than our current code.

**Comment by laserson** [comment]
I'm gonna start with supporting .2bit files, since we're gonna be broadcasting full references.

**Comment by akiezun** [comment]
is this done?

**Comment by laserson** [comment]
.2bit broadcast should be working at least in BQSR.  I'm not sure the intended scope of this issue.  Looks like fasta broadcasting was also implemented.

**Comment by davidadamsphd** [comment]
I think we also want to have broadcast working for fasta files (not sure if it works).

**Comment by droazen** [comment]
This is done! Closing.
