### ISSUE TITLE
UpdateVCFSequenceDictionary replaces "##FORMAT=<ID=GQ" with stock text

### ISSUE THREAD

**Issue by MikeWLloyd** [broadinstitute/gatk#8629]
I am using GATK 4.4.0.0 via the official docker release to reheader output from SVABA with an appropriate sequence dictionary. I am using `UpdateVCFSequenceDictionary` for this purpose with the following command: 

```
singularity exec -B "$PWD" broadinstitute-gatk-4.4.0.0.img gatk UpdateVCFSequenceDictionary --source-dictionary Mus_musculus.GRCm39.dna.primary_assembly.dict -V svaba.somatic.indel.vcf --replace true -O svaba.somatic.indel.vcf.reheaded.vcf
```

I have encountered a curious behavior, where by the tool is not simply adjusting the sequence dictionary, but is also modifying a FORMAT field. 

Original VCF header: 

```
##FORMAT=<ID=GQ,Number=1,Type=String,Description="Genotype quality (currently not supported. Always 0)">
```

Updated VCF header: 

```
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
```

From what I can see, the updated text is used frequently in your GATK VCF files, but I can't dig out the specific code where it is being set via `UpdateVCFSequenceDictionary`. I am wondering if there is a collision where `UpdateVCFSequenceDictionary` detects GQ and prints a stock header field to match expectation, rather than leaving it alone. I would expect the tool to simply replace the dictionary portion of the VCF without modifying the FORMAT/INFO fields. This is causing issues with downstream analysis because SVABA QC values are float/string not integer.

**Comment by cmnbroad** [comment]
@MikeWLloyd GATK uses code in htsjdk that, for better or worse, attempts to "repair" bad headers when it sees them, and I suspect thats what is happening here. I'm not sure what version the old and new headers are in your case, but it looks to me like the VCF spec going back to at least v4.1 does explicitly state that GQ is integer.

**Comment by MikeWLloyd** [comment]
@cmnbroad Thanks for the reply. I will look through that code to see if I turn up where this is happening. Is there a way to override/skip this repair? I understand as the header is coming from SVABA the VCF header is out of spec for GATK. It is one of the reasons I am using the tool to fix the dictionary of the VCF. It would be helpful to avoid the repair of other header fields in such cases. In the meantime, I will add a step to re-repair that particular header line so that downstream python scripts don't throw errors for the type mismatch. If there is no current way to avoid the header repair, and because it is a spec issue within GATK, I will close the issue.

**Comment by cmnbroad** [comment]
@MikeWLloyd No need to look - I know exactly where and why its happening. Unfortunately, I don't know of any way to stop it  short of implementing a more principled header versioning (which we've done, but it's not merged yet). And honestly, although I understand it causes you downstream issues, in this case, I think the repair is doing the right thing anyway, since its making the header spec-compliant where it previously wasn't.

**Comment by MikeWLloyd** [comment]
Thanks again @cmnbroad, and I totally understand. I did go into this expecting just such an answer, but it never hurts to ask, and I also wanted to make this issue to leave a record for any future folks who might run into the same header issues. 

Related to that, is there any chance of including in the tool docs that additional header correction/modification is occuring? It took me awhile to trace what was happening because it does not state in the tool doc that beyond the dictionary replacement additional header manipulations happen. 

Either way, thanks again for your time, and I will implement my work around.

**Comment by cmnbroad** [comment]
@MikeWLloyd Sorry you had to track that down. Although I sympathize, I doubt we would undertake to update the documentation for that, since its complicated to explain (there are other ramifications since many types of lines can be repaired), and I would guess that it affects about 50 GATK tools. We do have a plan and implementation for a better versioning strategy for VCFv4.3+.
