### ISSUE TITLE
Prevent users enabling annotations with mismatching data type (flow etc)

### ISSUE THREAD

**Issue by gokalpcelik** [broadinstitute/gatk#8788]
Here is an user trying to enable flow based annotations for non-flow data. 

https://gatk.broadinstitute.org/hc/en-us/community/posts/24596063911963-Error-while-running-Mutect2-java-lang-IllegalArgumentException-the-index-points-past-the-last-element-of-the-collection-or-array-334-333

What could be done to prevent this? 
Possible ideas
- Check data and disable nonmatching annotations with a warning in the log
- Prevent running the command at all with error messages in the log
- Change the way annotations are named such as FB_myannotation...

**Comment by jamesemery** [comment]
@ilyasoifer Looks like this user got tricked by some of the flow based annotations that don't work on their data. I would like to cut down on the risk that this happens for users. If we had more foresight I would advocate renaming all of the flow specific annotations to something like "flowbased_#####". How destructive would this be for your pipelines? 

We have some appropriate checks in GATK for the flow-ness of the bam that give warnings more broadly about flow-based mode but we don't currently have any safeguards in the annotations. Thoughts?

**Comment by ilyasoifer** [comment]
@jamesemery, @gokalpcelik  - this looks like a bug actually, this annotation should work on any data IMO. Would it be possible to get data to reproduce this crash? We should fix this quickly.

**Comment by ilyasoifer** [comment]
@gokalpcelik I see that the bug exists in the updated code too. We can fix it, but would be good to have some dataset that can be used to validate. Any chance to ask the user to generate a small example?

**Comment by ilyasoifer** [comment]
I think even more important is that they share the reference genome that they are using.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ilyasoifer** [comment]
@gokalpcelik, @jamesemery  - I submitted a PR (#8810) that should be fixing this issue. Could you please take a look? 
Thanks!
