### ISSUE TITLE
CombineGVCFs meet error

### ISSUE THREAD

**Issue by yanwuanxin** [broadinstitute/gatk#8869]
`
gatk --java-options '-Xmx4g -Djava.io.tmpdir=./tmp' CombineGVCFs -R ../genome.fasta --variant ./s1_blood.g.vcf --variant ./s1.g.vcf -O ./test.merge.g.vcf
`
running the above code will encounter an error:
![image](https://github.com/broadinstitute/gatk/assets/61311726/e2c2ac75-e9ad-440d-86cc-823d40ea7f03)

**Comment by yanwuanxin** [comment]
reinstalling gatk has solved the problem

**Comment by droazen** [comment]
Glad to hear this was resolved!
