### ISSUE TITLE
Troubleshooting VCF Output Truncation Issue during GATK CombineGVCFs Process

### ISSUE THREAD

**Issue by Ben-Akande** [broadinstitute/gatk#8882]
I'm running gatk-4.1.2.0 where I combine the VCF outputs for my six samples for proceeding steps such as Cigar split, base recalibration, sample naming, etc to generate my genotype VCF outputs. Unfortunately, combining the vcf output truncates chromosomal reads from 25 to 12. Interestingly, all six samples have 25 chromosomal read data in them. 

`gatk CombineGVCFs -R /home/akandeba/Desktop/Zebrafish_reference/GCF_000002035.6_GRCz11_genomic.fna --variant *_sampnamed.g.vcf.g.gz -O Pen_wsamps.g.vcf.gz
`

A look into the output is shown below:
` zgrep -v "^#" Pen_wsamps.g.vcf.gz | cut -f 1 | sort | uniq -c`

> gzip: Pen_wsamps.g.vcf.gz: invalid compressed data--format violated
> 3180475 NC_007112.7
> 4073215 NC_007113.7
> 3812157 NC_007114.7
> 3619687 NC_007115.7
> 4122713 NC_007116.7
> 3324278 NC_007117.7
> 3953942 NC_007118.7
> 3483638 NC_007119.7
> 3122617 NC_007120.7
> 2771400 NC_007121.7
> 2731475 NC_007122.7
> 2732872 NC_007123.7
> 3064453 NC_007124.7
> 2476811 NC_007125.7
> 2820480 NC_007126.7

The NC_ are ReqSeq ID for the respective chromosomes. I am interested in data on chromosome 19 which is most likely committed by this approach. I would greatly appreciate any help to resolve this issue.

**Comment by droazen** [comment]
Hi @Ben-Akande , could you please post this question on the GATK forum (https://gatk.broadinstitute.org/hc/en-us/community/topics)?  We'll help you troubleshoot it there.
