### ISSUE TITLE
SAM flags difference between Google-backed and SAMRecord-backed GATK reads

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#891]
The GenomicsConverter makeSAMRecord method (converts a GoogleRead to a SAM Record) sets the first-of-pair and second-of-pair-flags in the SAM record based only on the presence and value of the readNumber field:

```
flags += (read.getReadNumber() != null && 
    read.getReadNumber() == 0) ? 64 : 0; // first_in_pair
flags += (read.getReadNumber() != null && 
    read.getReadNumber() == 1) ? 128 : 0;  // second_in_pair
```

The flag value is determined independent of the value of the numberOfReads field, which conflicts with how the GATK ReadUtils class responds to flag state queries on Google read-backed GATK reads. That code requires both isPaired()==true, which in turn requires numberOfReads==2, as well as readNumber==0 in order to set the firstOfPair flag.

We need to change one or the other if we want to have consistent SAMString rendering and conversions between the two underlying models.

Per my conversation with droazen, we need to determine if we want to make a change in GenomicsConverter class to be more selective in how it sets the flag.

**Comment by lbergelson** [comment]
Closing since google reads are no longer a thing.
