### ISSUE TITLE
Check in an ADAM Parquet file for testing purposes

### ISSUE THREAD

**Issue by laserson** [broadinstitute/gatk#896]
cf. comment in #888

**Comment by akiezun** [comment]
I;d like this for alpha

**Comment by laserson** [comment]
@akiezun How big a file are we talking about?  (i.e., which of the current testing files should I convert to ADAM/Parquet?)

**Comment by akiezun** [comment]
how about this one 
src/test/resources/org/broadinstitute/hellbender/tools/picard/analysis/MeanQualityByCycle/first5000a.bam

and try it with MeanQualityByCycleSpark
