### ISSUE TITLE
Add explicit support for headerless SAMRecords to htsjdk

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#903]
The SAMRecord class currently allows the header to be set to null (either at construction time or via `setHeader()`), but may blow up or allow itself to enter an inconsistent state when it lacks a header (eg., the reference name and reference index can get out of sync).

We should patch this class (and subclasses such as `BAMRecord`) in https://github.com/samtools/htsjdk/ to behave sensibly in all cases when a header is not present (eg., use a special missing value for reference index when the reference index cannot be looked up), and add unit tests to prove that headerless `SAMRecords` function correctly.

This is important for dataflow and spark, where we want to serialize `SAMRecords` without paying the cost of serializing a header for each record.

**Comment by droazen** [comment]
This one is for @cmnbroad

**Comment by cmnbroad** [comment]
The changes in htsjdk are in [PR 327](https://github.com/samtools/htsjdk/pull/327). We'll most likely need some changes in gatk as well depending on the resolution to #900.

**Comment by cmnbroad** [comment]
Closing via https://github.com/samtools/htsjdk/pull/327.
