### ISSUE TITLE
Test crams that have a .crai index (as opposed to a .bai index)

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#921]
Now that .crai is supported in htsjdk

**Comment by droazen** [comment]
Should probably go in `CRAMSupportIntegrationTest`

**Comment by cmnbroad** [comment]
This needs the fixes in https://github.com/samtools/htsjdk/pull/343.

**Comment by akiezun** [comment]
involves revup of htsjdk

**Comment by cmnbroad** [comment]
Closed via #988.
