### ISSUE TITLE
Simplify HaplotypeBAMWriter code.

### ISSUE THREAD

**Issue by cmnbroad** [broadinstitute/gatk#944]
The HaplotypeBAMWriter implementation as ported from GATK is currently spread out over 5 classes, with a base class and two subclasses for the writers and a base class and one subclass to represent the writer destination. All of the functionality can be reduced to one simple HaplotypeBAMWriter class (or possibly two if we want to keep the destination separate).

**Comment by kvinter1** [comment]
See pull request: https://github.com/broadinstitute/gatk/pull/5122
