### ISSUE TITLE
rename respository to gatk

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#945]
we need to rename to gatk. Hellebender will remain the codename and the mascot.
(at a later point, we'll rename packages too but that's more work. This ticket is only about the repo).

**Comment by lbergelson** [comment]
so sad

**Comment by akiezun** [comment]
sad but necessary
@vdauwera will buy us a plush hellbender

BTW, @vdauwera will people be confused when they find the broadinstitute/gatk repository and think this is the 3.x branch that they can use for production? I bet they will - what should we do about this then?

**Comment by vdauwera** [comment]
For the most part I expect people use the precompiled jar for production
work, so I'm not too worried about that. Just make sure to have a TL;DR
line at the top of the readme that makes it clear what this is.

On Mon, Oct 5, 2015 at 1:16 PM, Adam Kiezun <notifications@github.com>
wrote:

> sad but necessary
> @vdauwera <https://github.com/vdauwera> will buy us a plush hellbender
>
> BTW, @vdauwera <https://github.com/vdauwera> will people be confused when
> they find the broadinstitute/gatk repository and think this is the 3.x
> branch that they can use for production? I bet they will - what should we
> do about this then?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/broadinstitute/hellbender/issues/945#issuecomment-145602883>
> .
>



-- 
Geraldine A. Van der Auwera, Ph.D.
Group leader, Comms & Support
Data Science & Data Engineering
Broad Institute

**Comment by akiezun** [comment]
adding issue comment to test hipchat integration after rename
