### ISSUE TITLE
remove Dataflow dependency

### ISSUE THREAD

**Issue by akiezun** [broadinstitute/gatk#954]
This entails moving all dataflow code to hellbender-dataflow and mininimizing other dependencies. Ideally, up to the point of dropping from the buildscript.

**Comment by akiezun** [comment]
what do do about things like `SparkCommandLineProgram` that has a dependency on `com.google.cloud.dataflow.sdk.options.PipelineOptionsFactory`?

Or `ReadFilter` that implements `SerializableFunction` from `com.google.cloud.dataflow.sdk.transforms.SerializableFunction`

**Comment by akiezun** [comment]
This involved disentangling Spark code from Dataflow code

**Comment by droazen** [comment]
I have done the disentangling work in https://github.com/broadinstitute/gatk/pull/982

**Comment by droazen** [comment]
The remaining part of this ticket is for beta.
