### ISSUE TITLE
Make it easier to run spark tools

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#961]
Spark tools should be just as easy to run as walkers. Users shouldn't have to write a shell script to invoke spark-submit or gcloud, build a special jar and upload it somewhere, log in to a particular machine, etc. Ideally we want something as simple as: `./hellbender ToolName [toolOptions] [sparkOptions]`, and the engine should figure out whether to invoke spark-submit or gcloud and invoke it on the user's behalf.

Options include:
-Invoke spark-submit/gcloud programmatically within hellbender (possibly using a simple `Runtime.getRuntime().exec()` approach).

-Write a shell script that can run any hellbender command and auto-delegate to spark-submit / gcloud as necessary.

**Comment by droazen** [comment]
Also need to think about an eventual binary distribution

**Comment by tomwhite** [comment]
Spark has a relatively new helper class for programmatic launching that may be handy here: https://spark.apache.org/docs/1.5.0/api/java/org/apache/spark/launcher/package-summary.html

**Comment by davidadamsphd** [comment]
I've got a demo working with that I'll hand over to Louis today. I was focused on dev work without needing to call `gradle sparkJar`, but it should be easy to modify it to submit the spark jar to somewhere else.

**Comment by droazen** [comment]
Out of all the remaining alpha tickets this one might be the most important for making a good first impression on people -- hope we can get something working in time! :)

**Comment by akiezun** [comment]
done by https://github.com/broadinstitute/gatk/pull/1211
