### ISSUE TITLE
Make GCS authentication work without using dataflow options classes

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#963]

**Comment by droazen** [comment]
If possible! This would potentially allow us to remove the entire `com.google.cloud.genomics.dataflow` dependency.

**Comment by droazen** [comment]
Affects https://github.com/broadinstitute/hellbender/issues/954

**Comment by davidadamsphd** [comment]
This has partially been handled by JP already :) with his `AuthHolder` class. The only missing piece is removing our dependance on `GCSOptions.Methods.createGCSAuth(options)` by instead calling the create auth stuff directly.

**Comment by droazen** [comment]
This one is definitely for beta

**Comment by droazen** [comment]
This one is almost done -- assigning to @jean-philippe-martin to do the last remaining piece.

**Comment by droazen** [comment]
@jean-philippe-martin Can we close this one?

**Comment by jean-philippe-martin** [comment]
I think the question is about `com.google.cloud.dataflow.sdk.options.PipelineOptions`. In that case we're not done, there is still some of that about.

**Comment by jean-philippe-martin** [comment]
I've removed some in #2786. The rest are all related to the `ReferenceAPISource`.
