### ISSUE TITLE
Write a wiki / tutorial documenting how to run hellbender on spark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#964]
Using dataproc clusters on GCE, the Broad cluster, local clusters, etc.

**Comment by droazen** [comment]
Depends on https://github.com/broadinstitute/hellbender/issues/961

**Comment by vdauwera** [comment]
One of you guys is going to have to write a first draft of this. It can be a bullet point list of commands to run or things to check. Then we can massage it into a user-facing doc. But we have to have something to start from.

**Comment by droazen** [comment]
Since this depends on https://github.com/broadinstitute/gatk/issues/961, reassigning to @lbergelson

**Comment by droazen** [comment]
I think we've satisfied this one for alpha purposes with our recent README changes. We can write a more in-depth guide for beta.

**Comment by droazen** [comment]
Re-opening -- this was closed by accident.

**Comment by droazen** [comment]
From @sooheelee:

```
We have two tutorials on Dataproc Spark. None on other types of Spark setups.

https://software.broadinstitute.org/gatk/documentation/article?id=11093
software.broadinstitute.org
GATK | Doc #11093 | (How to) Create a Spark cluster on Google Dataproc
The website of the Genome Analysis Toolkit

https://software.broadinstitute.org/gatk/documentation/article?id=10060
software.broadinstitute.org
GATK | Doc #10060 | (How to) Run FlagStatSpark on a cloud Spark cluster
The website of the Genome Analysis Toolkit
```

**Comment by droazen** [comment]
Closing as done

**Comment by sooheelee** [comment]
Adding myself as a contributer, given I developed and wrote #11060, and #11093 is derivative of the former.
