### ISSUE TITLE
Test spark tools with cram

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#966]
Determine whether spark tools currently work with cram (locally or hdfs).

**Comment by tomwhite** [comment]
[Hadoop-BAM](https://github.com/HadoopGenomics/Hadoop-BAM) doesn't support CRAM, so reading CRAM files from HDFS won't work.

**Comment by droazen** [comment]
@tomwhite Doesn't Hadoop-BAM rely on htsjdk internally? If so, it should be possible to patch it to work with cram, as htsjdk now has transparent support for cram via the SAMReader interface. But perhaps I am naive...would you be able to look into this?

**Comment by lbergelson** [comment]
Hadoop-bam is running a very old htsjdk, that doesn't support cram.  There's an old open pull request there htsjdk 1.133, but maybe we could open a 1.40 request.

**Comment by droazen** [comment]
Yes, let's do that (if it's easy)

**Comment by lbergelson** [comment]
We should make some contact with the people who run it.  If we're going to rely on their code we need to have some relationship with them.

**Comment by cmnbroad** [comment]
I don't think just upgrading htsjdk will be enough - cram files don't work with Hellbender spark tools, even with Hadoop-BAM using the current htsjdk. It looks like there is at least some code in Hadoop-BAM that explicitly recognizes SAM/BAM (like [this](https://github.com/cmnbroad/Hadoop-BAM/blob/master/src/main/java/org/seqdoop/hadoop_bam/AnySAMInputFormat.java#L184) for one example).

**Comment by droazen** [comment]
@tomwhite just added support. We should try `SortBamSpark` on a large CRAM file to see if we have any reading or writing problem, and add cram tests for other spark tools if it looks good.

**Comment by cmnbroad** [comment]
@tomwhite would know better than I, but AFAICT the current work addresses the CRAM reading side, but not writing. I think we'd need additional changes to support writing CRAM, both in Hadoop-BAM and ReadSparkSink.

**Comment by droazen** [comment]
From @tomwhite :+1:

**Comment by droazen** [comment]
Also, Hadoop-BAM version 7.3.0 is required

**Comment by akiezun** [comment]
blocked by htsjdk bug https://github.com/samtools/htsjdk/issues/394

**Comment by akiezun** [comment]
fixed by #1268
