### ISSUE TITLE
Check hellbender tool listing / usage page for accuracy

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#967]

**Comment by akiezun** [comment]
depends on  #418 (the review should be of all arguments printed by the tool, not just the tool's description)

**Comment by droazen** [comment]
@vdauwera is too busy to get to this before alpha -- reassigning to @akiezun

**Comment by akiezun** [comment]
still blocked by #418

**Comment by akiezun** [comment]
done https://github.com/broadinstitute/gatk/issues/1150
lot's of little badness
