### ISSUE TITLE
Actually run all hellbender tools to make sure none are ridiculously slow or broken

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#968]

**Comment by droazen** [comment]
@vdauwera to delegate to somebody

**Comment by vdauwera** [comment]
I think there's been a misunderstanding: my team is responsible for Q&As, not QA...

(snark aside, it's fine, we'll do it)

**Comment by droazen** [comment]
This isn't really QA in the rigorous sense -- it's more "make sure nothing is egregiously busted so that we don't embarrass ourselves in alpha"

**Comment by droazen** [comment]
Also, this should ideally be done after https://github.com/broadinstitute/hellbender/issues/961, https://github.com/broadinstitute/hellbender/issues/959, and https://github.com/broadinstitute/hellbender/issues/958 as a final pre-alpha sanity check, as those tickets (and others) will have a huge effect on consistency across tools.

**Comment by akiezun** [comment]
we've run all the relevant tools recently. What else is needed here? Can we close this? If not, please make an explicit list of things to check (tools, configuration, etc).

**Comment by droazen** [comment]
Closing -- the remaining pieces of this have individual tickets
