### ISSUE TITLE
Port dataflow optimizations to spark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#970]

**Comment by jean-philippe-martin** [comment]
PR #987 is part of this.

**Comment by akiezun** [comment]
is there more to do here or is this ok to close?

**Comment by jean-philippe-martin** [comment]
ApplyBQSR's next, and then we can close.

**Comment by droazen** [comment]
There is more to do here, actually -- but I've spun it out into a separate ticket (https://github.com/broadinstitute/gatk/issues/1006).

**Comment by droazen** [comment]
@jean-philippe-martin I think we should do the comparison in https://github.com/broadinstitute/gatk/issues/995 before porting the ApplyBQSR optimizations, actually. If it turns out that we decide to go with the simpler broadcast approach we'd then need to figure out how the dataflow ApplyBQSR changes fit in. So it probably makes sense to spin out a separate ticket for the ApplyBQSR changes and close this one.

**Comment by jean-philippe-martin** [comment]
OK, sure, I can wait.

**Comment by droazen** [comment]
Ok, all remaining pieces of this ticket have been spun out into sub-tickets. Closing!
