### ISSUE TITLE
add a progress bar for local walkers

### ISSUE THREAD

**Issue by lbergelson** [broadinstitute/gatk#974]
We should have a progress bar for local walkers.  This can be based on GATK's progress bar

**Comment by droazen** [comment]
Stretch goal for alpha :)

**Comment by akiezun** [comment]
AFAIK the GATK3 one used multithreading etc. Can we do a simple one just for readwalkers that does not use multithreading?

**Comment by droazen** [comment]
I think we could -- printing the number of records processed would be trivial.

**Comment by akiezun** [comment]
yup, number of records plus position of the last read. Just print every 10000th read or something.

So the same for variant walker, and interval walker and we're good.
