### ISSUE TITLE
Profile/optimize spark tools

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#986]
@jean-philippe-martin will be porting his dataflow optimizations to spark as part of https://github.com/broadinstitute/gatk/issues/970, and then going on leave for several weeks. It would be good if @tomwhite and @laserson could advise him over the next week or so as he does this, and then take over the process of optimization after he leaves.

I've created this ticket as a place for @jean-philippe-martin, @tomwhite, and @laserson to sync up and spawn additional tickets as necessary.

**Comment by droazen** [comment]
Assigned to @tomwhite and @laserson (github will only let me put one assignee in, unfortunately).

**Comment by tomwhite** [comment]
Sure, happy to help with this.

**Comment by jean-philippe-martin** [comment]
OK, I pushed my code to #987. It's not merged yet (and it'll have to be to pass all tests), but the BaseRecal tests pass. You can have a look and we can talk about merging (it doesn't have to be via github messages, though. We can meet, or email?)

**Comment by droazen** [comment]
This ticket is just a meta-ticket that was used to spawn additional performance-related tickets for spark -- closing.
