### ISSUE TITLE
how to use GATK to call Somatic Indels 

### ISSUE THREAD

**Issue by WinterLi1993** [broadinstitute/gatk#993]
Dear Teacher,
        I saw some website said we can use "IndelsGenotyperV2" to call Somtic Indels ,but I have not find any information about this tool on GATK office site. It has been cancled ??
        I wanna find a better tool to call somatic Indels  to do some cancer research,Expecting your answer !   

Java -jar GenomeAnalysisTK.jar -T IndelsGenotyperV2 -l INFO -R hg18.fasta -I:normal Normal.cleaned.bam -I:tumor 
Tumor.cleaned.bam -bed Sample.brief.indels -o Sample.detailed.indels -D snp132.txt --somatic --minCoverage 8 
--minNormalCoverage 6 --minFraction 0.1 --minConsensusFraction 0.5 --window_size 360 --minIndelsCount 3

**Comment by WinterLi1993** [comment]
@tomwhite

**Comment by vdauwera** [comment]
Hi @WinterLi1993 

The tool you refer to has indeed been canceled. A new tool is being developed; it is called MuTect 2 and will be released soon as part of the next version of GATK. When it is ready, there will be an announcement here: http://gatkforums.broadinstitute.org/

That is also a good place to ask any questions about how to use the tools. This place here is only for questions about the software code of the tools.

**Comment by WinterLi1993** [comment]
OK，thank you !
