### ISSUE TITLE
Allow variants to be broadcast in AddContextDataToReadSpark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#994]
We currently have support for broadcasting the reference in `AddContextDataToReadSpark` -- the `joinStrategy` parameter controls whether we use `ShuffleJoinReadsWithRefBases` or `BroadcastJoinReadsWithRefBases`. We need the same thing for variants so that we can profile a "broadcast everything except the reads approach" against the manual sharding approach taken in https://github.com/broadinstitute/gatk/pull/987. We should use the existing `joinStrategy` argument to select between a `ShuffleJoinReadsWithVariants` and a `BroadcastJoinReadsWithVariants`.

**Comment by droazen** [comment]
@tomwhite or @laserson, would one of you be able to take this?

**Comment by tomwhite** [comment]
I've opened PR #1004 for this. Would you like to take a look @droazen? I haven't tried this on a cluster, but I guess you can run it side-by-side with JP's optimization.

**Comment by droazen** [comment]
Thanks, that was fast! I'll have a look at the PR in a bit.
