### ISSUE TITLE
Profile the sharded BQSR against the broadcast BQSR on spark

### ISSUE THREAD

**Issue by droazen** [broadinstitute/gatk#995]
As mentioned in the discussion for https://github.com/broadinstitute/gatk/pull/987, we want to compare the manual sharding approach taken to optimizing BQSR in that branch against an alternative approach of broadcasting the reference and variants. The latter approach would be simpler and more flexible/idiomatic (allow spark to handle sharding and data localization rather than doing it manually), but might be slower. Let's find out what the performance is like for both approaches before making a decision.

**Comment by droazen** [comment]
Depends on both https://github.com/broadinstitute/gatk/issues/994 and the merge of https://github.com/broadinstitute/gatk/pull/987

**Comment by droazen** [comment]
Assigning to @akiezun as discussed in person

**Comment by akiezun** [comment]
I think @droazen is doing this already.

**Comment by laserson** [comment]
Also note #1007.

**Comment by droazen** [comment]
![bqsr_spark](https://cloud.githubusercontent.com/assets/798637/10831310/43e41214-7e5b-11e5-9591-fe3b7d0b3ba6.png)

**Comment by droazen** [comment]
The plot above shows the results of running our four implementations of BQSR (the walker version, the shuffle version, the broadcast version, and the "manual sharding" version) on a ~7 GB bam with ~250 MB vcf and full size (~3 GB) reference (though I used the compressed `.2bit` version of the reference for the broadcast tests, which came in at ~750 MB).

-The single-threaded walker version running on a Broad server with inputs over NFS took ~45 minutes to process the file (this is the hard-to-see point in the upper left of the plot).

-The shuffle version on 96 cores (3 executors with 32 cores each) took ~38 minutes (this is the hard-to-see point towards the upper right of the plot)

-The broadcast version with 4 cores per executor (the BROADCAST_4 line) scaled reasonably well up to 32 total cores, then got slower after that. I tried increasing the number of cores per executor to 16 and 32 (these are the BROADCAST_16 and BROADCAST_32 lines respectively), but this didn't help. I suspect that the broadcast approach comes with a fixed amount of overhead that dominates the runtime on a small input, and by increasing the size of the bam input we may see it scale past 32 cores.

-The "manual sharding" version (aka "BaseRecalibratorSparkOptimized") performed the best, despite having to read the bam from a GCS bucket rather than from the local HDFS like the other implementations, but also didn't scale past 32 cores. Tried increasing the number of cores per executor here as well from 4 to 32 (the SHARDING_4 and SHARDING_32 lines), but it made no significant difference.

**Comment by droazen** [comment]
Based on these results, I think we want to try out the broadcast version on larger inputs and see if it scales as well as or better than the "manual sharding" implementation in `BaseRecalibratorSparkOptimized` (on the assumption that the cost of the broadcast will dominate on small bam inputs but stay roughly the same as we increase the bam size but keep the reference/variants the same).

**Comment by droazen** [comment]
Re-assigning to @jean-philippe-martin -- remaining task is to run both the `BROADCAST` and `BaseRecalibratorSparkOptimized` implementations at larger scale than the 7 GB inputs used to produce the plots above, and then make a decision about whether `BROADCAST` is viable, or we should devote time into improving `BaseRecalibratorSparkOptimized`

**Comment by jean-philippe-martin** [comment]
![throughput vs core count](https://cloud.githubusercontent.com/assets/10458949/11080726/940ccfd2-87cb-11e5-99b8-a1ebc4bb6949.png)

Thanks to @droazen for doing those measurements. I've taken the input and plotted the per-core throughput numbers above. What we expect to see is a drop after the non-distributed version, and then a steady decline as we add cores. This matches what we're seeing here: the walker throughput is 145 MB/min/core, and then we quickly drop to 50, 32, then finally 15 MB/min/core. This matches well with my earlier informal measurement on the cloud where I saw 15 MB/min/core on 128 cores. It looks like there is room for improvement.

**Comment by droazen** [comment]
I did some additional runs on the Broad cluster on a 14 GB bam, twice as large as the bam used in the plot above. This was with 60 cores, 4 cores per executor, and 16 GB of memory per executor. Results:

Broadcast (3 runs): 10m52.020s, 11m46.975s, 10m17.274s
Sharded (3 runs): 19m33.310s, 13m36.466s, (died from out-of-memory error)

Not sure what's going on here, but something about this configuration is favorable to Broadcast and unfavorable to Sharded. We should try to understand what and why.

Below are the commands I used to run each implementation on dataflow01, for reference:

    spark-submit \
      --master yarn-client \
      --driver-memory 8G \
      --num-executors 16 \
      --executor-cores 4 \
      --executor-memory 16G \
      --conf spark.driver.maxResultSize=0 \
      --conf spark.driver.userClassPathFirst=true \
      --conf spark.executor.userClassPathFirst=true \
      --conf spark.io.compression.codec=lzf \
      --conf spark.yarn.executor.memoryOverhead=600 \
          $JAR BaseRecalibratorSpark \
            --input hdfs:///user/droazen/bqsr/CEUTrio.HiSeq.WGS.b37.NA12878.1m-130m.bam \
            --output bqsr_out_${1}.bam \
            -R hdfs:///user/droazen/bqsr/human_g1k_v37.2bit \
            --knownSites hdfs:///user/droazen/bqsr/dbsnp_138.b37.1m-130m.vcf \
            --joinStrategy BROADCAST \
            --apiKey $API_KEY \
            --sparkMaster yarn-client


    spark-submit \
      --master yarn-client \
      --driver-memory 8G \
      --num-executors 16 \
      --executor-cores 4 \
      --executor-memory 16G \
      --conf spark.driver.maxResultSize=0 \
      --conf spark.driver.userClassPathFirst=true \
      --conf spark.executor.userClassPathFirst=true \
      --conf spark.io.compression.codec=lzf \
      --conf spark.yarn.executor.memoryOverhead=600 \
      --conf spark.akka.frameSize=1024 \
          $JAR BaseRecalibratorSparkOptimized \
            --input gs://droazen-testing/spark/CEUTrio.HiSeq.WGS.b37.NA12878.1m-130m.bam \
            --output bqsr_out_${1}.bam \
            -R hdfs:///user/droazen/bqsr/human_g1k_v37.fasta \
            --knownSites /local/dev/droazen/new_test/dbsnp_138.b37.1m-130m.vcf \
            -L 1:1-130000000 \
            --apiKey $API_KEY \
            --sparkMaster yarn-client

**Comment by jean-philippe-martin** [comment]
Thanks. This shows that bcast can go faster when given more RAM: going from
the earlier experimental envelope of 192GB of RAM to 256GB instead, the
bcast version can go from 19 min to 10min (sharded takes 7min with the
small amount of memory). This is consistent with my earlier experiments
that also showed that increasing the RAM-per-core sped up the bcast
computation.

I wouldn't worry about having found a configuration where sharded performs
poorly. My experiments so far have shown that there are lots of
configuration points where one or the other performs poorly; the onus is on
finding the good configuration values that result in better performance, or
identifying which algorithms may be performant for a larger range of
parameter choices.

To maximize understanding I would suggest that we not change too many
parameters at a time. For example it seems unnecessary to have multiple
variants of the 128Mbp input.

I found there can be significant (>50%) variation between identical runs.
One way to reduce this is to set spark.task.maxFailures=1 which I strongly
recommend for all experiments going forward.

One concern I have is that our cluster memory is already far larger than
the input size. In fact here each machine can fit the whole input
comfortably in RAM. This is not going to be the case for the full input.
Since it would take too long to iterate using the full input, it seems wise
instead to reduce both the input size and to keep a close eye on the amount
of memory we're using to make sure we're not going down a path that would
not be able to cope with the full input.

**Comment by droazen** [comment]
What remains to be done for this ticket are tests on both the broadcast and sharded implementations at the ~100GB scale -- once these are done, we can call this ticket done for alpha.

@jean-philippe-martin These tests should be sure to use a current version of master, so that they can take advantage of the speedup provided by the new `SAMRecord` Kryo serializer merged in https://github.com/broadinstitute/gatk/pull/1127. This should benefit both implementations. Also note that `BaseRecalibratorOptimized` has been renamed to `BaseRecalibratorSharded` in master.

**Comment by droazen** [comment]
JP was able to complete additional benchmarking with 14 GB and 28 GB bam inputs before going back on leave, and he has shared these results with us. We still need to test at the 100 GB scale, so I'm re-assigning to @akiezun to complete that remaining task.

**Comment by droazen** [comment]
@akiezun Description of the steps to be performed:

1. Create a ~100 GB slice of `/humgen/gsa-hpprojects/GATK/bundle/current/b37/CEUTrio.HiSeq.WGS.b37.NA12878.bam` using `PrintReads` (will need to experiment with intervals a bit to get the right size -- for reference, the first 130 megabases of chromosome 1 produces a ~14 GB bam).

2. Create an index on the bam slice above using `samtools index`

3. Create a slice of `/humgen/gsa-hpprojects/GATK/bundle/current/b37/dbsnp_138.b37.vcf` using `SelectVariants` and the same interval used to create the bam above.

4. Create an index on the vcf slice above using `IndexFeatureFile`

5. For the reference, use the existing complete `.2bit` reference `/local/dev/droazen/spark_inputs/human_g1k_v37.2bit` on `dataflow01`

6. Put all inputs into both hdfs (for the BROADCAST implementation) and a GCS bucket (for the SHARDED implementation).

7. Create an up-to-date hellbender spark jar from the latest master.

8. Run the BROADCAST implementation on `dataflow01` using the unix `time` command and a script like the one below:

    spark-submit \
      --master yarn-client \
      --driver-memory 8G \
      --num-executors 16 \
      --executor-cores 4 \
      --executor-memory 10G \
      --conf spark.driver.maxResultSize=0 \
      --conf spark.driver.userClassPathFirst=true \
      --conf spark.executor.userClassPathFirst=true \
      --conf spark.io.compression.codec=lzf \
      --conf spark.yarn.executor.memoryOverhead=600 \
      $JAR BaseRecalibratorSpark \
        --input hdfs:///path/to/your.bam \
        --output bqsr_out_broadcast.bam \
        -R hdfs:///user/droazen/bqsr/human_g1k_v37.2bit \
        --knownSites hdfs:///path/to/your.vcf \
        --joinStrategy BROADCAST \
        --apiKey $API_KEY \
        --sparkMaster yarn-client

I recommend running BROADCAST with 4 cores per executor and 10 GB/memory per executor (though this may need to be increased if you see any swapping). 16 executors (ie., 64 cores total) seems like a good size for our cluster as it would allow you to increase memory per core if necessary. All inputs should be in hdfs, as in the example script above.

9. Run the SHARDED implementation on `dataflow01` using the unix `time` command and a script like the one below:

    spark-submit \
      --master yarn-client \
      --driver-memory 8G \
      --num-executors 16 \
      --executor-cores 4 \
      --executor-memory 10G \
      --conf spark.driver.maxResultSize=0 \
      --conf spark.driver.userClassPathFirst=true \
      --conf spark.executor.userClassPathFirst=true \
      --conf spark.io.compression.codec=lzf \
      --conf spark.yarn.executor.memoryOverhead=600 \
      --conf spark.akka.frameSize=1024 \
      $JAR BaseRecalibratorSparkSharded \
        --input gs://your.bam \
        --output bqsr_out_sharded.bam \
        -R hdfs:///user/droazen/bqsr/human_g1k_v37.fasta \
        --knownSites /path/to/your.vcf \
        -L EXACT_INTERVALS_FOR_YOUR_BAM \
        --apiKey $API_KEY \
        --sparkMaster yarn-client

Notes on running the SHARDED implementation:
    -The bam must be in a GCS bucket
    -The vcf must be in a local file (not hdfs!)
    -The reference should be either an indexed fasta (not `.2bit`, ) in hdfs, or you can use the Google API for the reference (eg., `-R gg://reference/EOSsjdnTicvzwAE` for b37) -- not sure which option is better for this implementation, may want to test both
    -You MUST specify the exact intervals spanning the reads in the bam using `-L`, otherwise you will get very poor performance.
    -You MUST specify `--conf spark.akka.frameSize=1024` otherwise you will get a crash.
    -It's unclear what the ideal executor size for this implementation is, but there is some evidence that it does slightly better with more cores per executor (compared to BROADCAST), so you may want to try that.

**Comment by droazen** [comment]
These profiling tickets do not absolutely need to be in for alpha -- moving to beta.

**Comment by droazen** [comment]
@akiezun Could you do the 100GB-scale test described above before the holiday break (or delegate to someone else if you don't have time)?

**Comment by akiezun** [comment]
I've done 1-7 of this ticket (ie make resources, run cluster version). I have copied the data to GSC too but not run the google version yet. Here's what I run 

```

bam="hdfs:///user/akiezun/data/CEUTrio.HiSeq.WGS.b37.NA12878.chr1_4.bam" 

ref="hdfs:///user/droazen/bqsr/human_g1k_v37.2bit"
dbsnp="hdfs:///user/akiezun/data/dbsnp_138.b37.excluding_sites_after_129.chr1_4.vcf"
bamout=${bam}.md.bqsr

name=BaseRecalibratorSpark_hdfs_100Gb_exec${execs}_cores${cores}_execMem${execMem}_partition${partition}
echo $name

./bin/gatk/gatk-launch \
BaseRecalibratorSpark \
-I $bam \
-R $ref \
--programName ${name} \
-O $bamout \
--joinStrategy BROADCAST \
--knownSites $dbsnp \
--sparkMaster yarn-client \
-- \
--sparkRunner SPARK \
--deploy-mode client \
--master yarn-client \
--driver-memory 8G \
--conf spark.driver.maxResultSize=0 \
--conf spark.driver.userClassPathFirst=true \
--conf spark.executor.userClassPathFirst=true \
--conf spark.io.compression.codec=lzf \
--conf spark.yarn.executor.memoryOverhead=600 \
--executor-memory ${execMem}g \
--num-executors $execs \
--executor-cores $cores
```

on 50 executors, 4 cores each, 10GB per executor - it took 23min:41seconds

**Comment by akiezun** [comment]
@droazen can you run it on GSC or maybe ask @jean-philippe-martin ? I put the bam file in the hellbender-validation/test-input/NA12878 bucket

**Comment by droazen** [comment]
Alright, I'll take this one.

**Comment by droazen** [comment]
Reassigning to @jamesemery

**Comment by droazen** [comment]
Relates to https://github.com/broadinstitute/gatk/issues/1675 and https://github.com/broadinstitute/gatk/issues/1689

**Comment by droazen** [comment]
This was done
